### ISSUE TITLE
Speech to text is slow with bytes received from Microsoft.Skype.Bots.Media.UnmixedAudioBuffer Source

### ISSUE THREAD

**Issue by danacoldeainfiniswiss** [Azure-Samples/cognitive-services-speech-sdk#1005]
HI, I am using the Speech to Text service with push audio stream. The source are the bytes received from the UnmixedAudioBuffer from Microsoft.Skype.Bots.Media sdk. I am using the sample app
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/src/RecordingBot.Services/Media/SerializableAudioMediaBuffer.cs

I write these bytes to the stream I create with AudioInputStream.CreatePushStream(). While the participants in the meeting speak, the recognizing events come in fast enough, but after they finish a sentence it takes a long time before the last recognizing + recognized event of the sentence are received. The delay is even bigger when the speakers use the browser version of the Teams app.

I tried setting the SpeechServiceConnection_EndSilenceTimeoutMs property, but this had no effect on the delay of the recognized event. 

Is there any other approach I could take to improve this?

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
