### ISSUE TITLE
Unable to find documentation of TTS voice configuration for iOS and Android

### ISSUE THREAD

**Issue by namrathanithya** [Azure-Samples/cognitive-services-speech-sdk#1006]
We have a requirement of specific voice configuration (pitch, speed and language) for TTS. I am able to find the documentation for javascript and looking for some documentation for android and iOS. For javascript, I have followed the documentation which I mentioned below. Could you help me with similar documentation for android and iOS?

JS link: [https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-text-to-speech?tabs=script%2Cwindowsinstall&pivots=programming-language-javascript](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-text-to-speech?tabs=script%2Cwindowsinstall&pivots=programming-language-javascript)

**Comment by trrwilson** [comment]
Thanks for contacting us!

Are you looking for documentation on environment setup for these environments and deployment to Android/iOS devices? If so, you can find the preliminaries here:
- [Get the Speech SDK - iOS](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk?tabs=ios%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio#get-the-speech-sdk)
- [Get the Speech SDK - Android](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk?tabs=android%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio#get-the-speech-sdk)

Please let us know if these don't have what you're looking for and we'll get back with further details.

**Comment by namrathanithya** [comment]
Hi, We are developing a mobile application in which the requirement is to configure the text to speech audio options like pitch, speed and language. I've found the code for web app and looking for similar code for Android and iOS.

I've followed the "Use SSML to customize speech characteristics" section in below link to configure speech. Looking for similar documentation for android and iOS.

Web app- [(https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-text-to-speech?tabs=script%2Cwindowsinstall&pivots=programming-language-javascript)]

**Comment by glecaros** [comment]
Hi @namrathanithya,

In that same page there is a [Java](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-text-to-speech?tabs=script%2Cwindowsinstall&pivots=programming-language-java#use-ssml-to-customize-speech-characteristics) that demonstrates how to do it in android. The code required for objective-C/swift should be similar (use the speakSsml API passing the xml as a string)

I'll also bring up to the team that we have that gap in the objc docs.

Please let me know if that helps.

**Comment by pankopon** [comment]
Closed since answered, please open a new issue if more support is needed.
