### ISSUE TITLE
Custom command with a language other than English

### ISSUE THREAD

**Issue by Cris21395** [Azure-Samples/cognitive-services-speech-sdk#1008]
I am trying to create a custom command application selecting Spanish language. I add some commands and use the keyword recognition to improve accuracy. Everything seems to work fine from the portal, since I use the test option and I am capable of interacting with the custom command app. Also, the app is deployed correctly. However, when I say the keyword from my app to start listening voice commands, an error is thrown: "The server returned status code '404' when status code '101' was expected".

I have another custom command application with English language, and it works perfectly fine. Is there any issue using another language rather than English?

Thanks in advance.

**Expected behavior**
A custom command application running correctly using a language other than English.

**Version of the Cognitive Services Speech SDK**
1.14.0

**Platform, Operating System, and Programming Language**
 - OS: Windows
 - Hardware - x64
 - Programming language: C#

**Comment by trrwilson** [comment]
Thanks for contacting us!

How are you configuring the language to Spanish in the C# application? If you could share the code snippet of how you're connecting, that'd be a huge help in diagnosing further -- as would a client log collected per these instructions: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

**Comment by Cris21395** [comment]
Hi @trrwilson,

Thank you for your prompt reply.

As you pointed out, I used logging to know what was going on. The problem was I didn't set the [Language](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.dialog.dialogserviceconfig.language?view=azure-dotnet#Microsoft_CognitiveServices_Speech_Dialog_DialogServiceConfig_Language) in the configuration. I thought that the speech sdk implicitly knew that passing the key of the suscription and the id of the application.

The service works so well. Congrats for the job well done.

Cheers, - Cristian.
