### ISSUE TITLE
Language Identification Quality Threshold exposed?

### ISSUE THREAD

**Issue by aargreen** [Azure-Samples/cognitive-services-speech-sdk#1011]
**Is your feature request related to a problem? Please describe.**
When testing Language Identification in the java SDK, we seem to get a reasonable number of "no match results"

**Describe the solution you'd like**
Is there a quality threshold that determines the difference between perhaps a low confidence language result and a noMatch language result?
Is this threshold exposed in any way for the customer to set, perhaps through the setServiceProperty in SpeechConfig?

Related: Is there a list of all the properties which can be set with Speechconfig.setServiceProperty?

**Comment by dargilco** [comment]
Hi @aargreen , thank you for posting these questions.

If you can share an example of an audio file for which you are getting NoMatch, but expect a valid Language ID result, we can run it on our side and have a look. It does take a few seconds of speech to get reliable Language identification.

Speech SDK does not expose a "quality threshold" now, but we are working at the moment on updating the Language ID feature to allow more choices by the developer. This will probably address your request.  

Regarding SpeechConfig.setServcieProprty, those properties are mostly meant for internal usage and a few configuration options of new service features in public preview. When relevant, they will be shown in sample code in this repo of on docs.microsoft.

Darren

**Comment by aargreen** [comment]
Thanks @dargilco for the responses.  I think will hold off on providing examples for now, but may look into it in the future.  Ok to close the ticket from my end.
