### ISSUE TITLE
I found bug in speaker-recognition/verification/dependent-verification.html

### ISSUE THREAD

**Issue by githat** [Azure-Samples/cognitive-services-speech-sdk#1012]
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/javascript/browser/speaker-recognition/verification/dependent-verification.html

I displayed this sample HTML in a browser and entered the required parameters to create the profile.
Then when I specify Test Identification File and click verifySpeakerButton, I get a javascript error.
Because speechConfig has changed to undefined.
When I removed the "var" on line 106, the error disappeared.
Isn't this obviously a bug?

**Comment by trrwilson** [comment]
Thanks for contacting us with this. I see the same issue -- I'll follow up with the team to get this looked into ASAP.
