### ISSUE TITLE
Large delay before and after <audio> tag in SSML

### ISSUE THREAD

**Issue by alaa-eddine** [Azure-Samples/cognitive-services-speech-sdk#1013]
**Describe the bug**
When using <audio> tag within SSML, there is a large delay (about 1s) before and after the audio file.

**To Reproduce**
just use the following SSML to produce a speech
```
<speak version="1.0" xmlns="https://www.w3.org/2001/10/synthesis" xml:lang="en-US"><voice name="en-US-AriaNeural">Hello<audio src="https://germiz.com/world.wav" />, how are you?</voice></speak>
```

**Expected behavior**
I'm attaching an audio file generated by a competitor speech synthesizer using the same SSML, you can notice the different in delay between "Hello" and "World" compared to MS Azure TTS

[hello_world.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6211780/hello_world.zip)

**Comment by yulin-li** [comment]
@alaa-eddine , thx for reaching out. I forward your issue to service team and will get back to you when I get anything.

**Comment by yulin-li** [comment]
I got an answer from service team. You can using the following SSML to set the tailing silence of `Hello` to reduce the silence.

```xml
<speak version="1.0" xmlns="https://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xml:lang="en-US">
<voice name="en-US-AriaNeural">
<mstts:silence type="tailing" value="100ms"/>Hello<audio src="https://germiz.com/world.wav" />, how are you?
</voice></speak>
```

**Comment by alaa-eddine** [comment]
Awesome !
I was not aware that we can use mstts:silence this way .
This fixes my issue, thank you very much!

**Comment by yulin-li** [comment]
That it great!
