### ISSUE TITLE
Connection Failure HoloLens 2

### ISSUE THREAD

**Issue by MrFabouMR** [Azure-Samples/cognitive-services-speech-sdk#1014]
**Describe the bug**
I get TTS running on Unity, but if I build it into the HoloLens 2 it says "Connection Failure" and Ill get no Audio from TTS
When I'm deleting the if result.Reason == ResultReason.SynthesizingAudioCompleted I'll get an error that says that the samplecount is 0.

**To Reproduce**
1. Clone https://github.com/ActiveNick/HoloBot Sample which use parts of this sample here
2. Import it into Unity 2019.4.15f and change to IL2CPP
3. Capabilities: InternetClient, InternetClientServer, PrivateNetworkClientserver, Microphone

**Expected behavior**
TTS with Audio in HL2

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 - OS: HL2
 - Hardware - ARM64
 - Programming language: C#

**Comment by jhakulin** [comment]
@MrFabouMR Thanks for the report, we will investigate.

**Comment by jhakulin** [comment]
@MrFabouMR I could not reproduce the problem with HL2, some more questions. 
Can you reproduce the problem in UWP x64 environment if you deploy the same app there ?
What is the SW version you have in HL2 ?
You have double checked that InternetClient, InternetClientServer capabilities are added ?
Could you try to get Speech SDK logs from Application.persistentDataPath by doing the following?
        string logFile = Application.persistentDataPath + "/LogFile.txt";
        speechConfig.SetProperty(PropertyId.Speech_LogFilename, logFile);

**Comment by MrFabouMR** [comment]
@jhakulin I can't try it with x64 cause HL2 supports only ARM64. My emulator can't recognize the mic.
My Software Version is 10.0.19041.1131
I checked all capabilities
persistentDataPath tries to safe the logfile into the hololens, I can't reach them there.

**Comment by jhakulin** [comment]
@MrFabouMR You can reach to persistentDataPath using Windows Device Portal
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/using-the-windows-device-portal persistenDataPath is written to %userprofile%\AppData\Local\Packages\<productname>\LocalState.
There is some setup to do, but in order to process your request better, we would need to see the log.

**Comment by MrFabouMR** [comment]
@jhakulin  I understand, I hope we can fix it soon. 
When I'm pressing on the LocalState nothing happens, after 5min it says "failed to get files for package"

**Comment by jhakulin** [comment]
@MrFabouMR Could you please report back can you reproduce the problem with the official speech synthesis sample for Unity ? https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/unity/text-to-speech

**Comment by jhakulin** [comment]
@MrFabouMR Also please let us know which version of Speech SDK you are using ?

**Comment by MrFabouMR** [comment]
@jhakulin  Okay, I got it! 
Thank you very much. My version was 1.6.0 and I updated it to 1.16. It works now :-)
/close
