### ISSUE TITLE
Combining multiple utterances from continuousSpeech with white space

### ISSUE THREAD

**Issue by aargreen** [Azure-Samples/cognitive-services-speech-sdk#1018]
**Is your feature request related to a problem? Please describe.**
I would like to combine the multiple RecognitionResults from a continuous speech recognition into a single transcription with language correct whitespace.

**Describe the solution you'd like**
I would like to combine RecognitionResult texts together into a single transcription with correct white space.
1) Right now I am adding a single white space character between utterance texts in my own code.
2) I'm concerned that that might not always be appropriate to do, like for Japanese, where there is less use of white space.

Questions: 
1) Is there any utils available for combining multiple utterances with correct white space?
2) Is an utterance always guaranteed to end with some punctuation, after which a white space is appropriate in all languages?

**Comment by rhurey** [comment]
Thanks for the question. I'm checking with our team that owns punctuation and will get back once I have a definitive answer.

**Comment by aargreen** [comment]
Thx for checking into it @rhurey

**Comment by rhurey** [comment]
Sorry this took a while to get an answer back.

We don't have a utility to combined multiple phrases, and each phrase, while likely, isn't guaranteed to end in punctuation.

We've had a thought of exposing another method on the API surface to get the entire recognition in one call, but haven't had the right opportunity to take it further.

**Comment by aargreen** [comment]
Thanks @rhurey.  For my current use case getting the entire recognition would be great (assuming its still low latency).

**Comment by pankopon** [comment]
Closing this issue as we have an internal work item about the API (but no ETA). Implementation is not likely to happen soon, but we'll try to provide information about the release schedule here when better known.
