### ISSUE TITLE
Can You give a iOS sample how to use SPXPushAudioInputStream with AudioUnit?

### ISSUE THREAD

**Issue by hold-my-hand** [Azure-Samples/cognitive-services-speech-sdk#102]
`  NSError *error;
    AVAudioSession *audioSession = [AVAudioSession sharedInstance];
    
    [audioSession setCategory:AVAudioSessionCategoryPlayAndRecord withOptions:AVAudioSessionCategoryOptionAllowBluetooth error:&error];
    [audioSession setPreferredSampleRate:DEF_mSampleRate error:&error];
    [audioSession setPreferredInputNumberOfChannels:DEF_numberOfChannels error:&error];
    [audioSession setPreferredIOBufferDuration:3 error:&error];
    

 AudioStreamBasicDescription audioFormat;
    audioFormat.mSampleRate = DEF_mSampleRate;
    audioFormat.mFormatID = kAudioFormatLinearPCM;
    audioFormat.mFormatFlags = kAudioFormatFlagIsSignedInteger | kAudioFormatFlagIsPacked;
    audioFormat.mFramesPerPacket = 1;
    audioFormat.mChannelsPerFrame = 1;
    audioFormat.mBitsPerChannel = 16;
    audioFormat.mBytesPerPacket = 2;
    audioFormat.mBytesPerFrame = 2;
    
    AudioUnitSetProperty(audioUnit,
                         kAudioUnitProperty_StreamFormat,
                         kAudioUnitScope_Output,
                         OUTPUT_BUS,
                         &audioFormat,
                         sizeof(audioFormat));
    AudioUnitSetProperty(audioUnit,
                         kAudioUnitProperty_StreamFormat,
                         kAudioUnitScope_Input,
                         INPUT_BUS,
                         &audioFormat,
                         sizeof(audioFormat));
static OSStatus RecordCallback(void *inRefCon,
                               AudioUnitRenderActionFlags *ioActionFlags,
                               const AudioTimeStamp *inTimeStamp,
                               UInt32 inBusNumber,
                               UInt32 inNumberFrames,
                               AudioBufferList *ioData)
{
    OMRecordManager *record = (__bridge OMRecordManager *)inRefCon;
    @autoreleasepool {
        OSStatus err = noErr;
        err =   AudioUnitRender(audioUnit, ioActionFlags, inTimeStamp, inBusNumber, inNumberFrames, buffList);

        NSMutableData *pcmData = [[NSMutableData alloc] init];
        for (int i=0; i<buffList->mNumberBuffers; i++) {
            [pcmData appendBytes:buffList->mBuffers[i].mData length:buffList->mBuffers[i].mDataByteSize];
        }
        [record didRecordData:pcmData];
}

-(SPXPushAudioInputStream *)inputStream{
    if (!_inputStream) {
        SPXAudioStreamFormat *format  =[[SPXAudioStreamFormat alloc] initUsingPCMWithSampleRate:16000 bitsPerSample:16 channels:1];
        
        _inputStream = [[SPXPushAudioInputStream alloc] initWithAudioFormat:format];
    }
    return _inputStream;

}

-(void)startRecognizer{
  NSString *speechKey = @"xxxx";
    NSString *serviceRegion = @"westus";
    self.recognizerID =  [NSString stringWithFormat:@"%@",@([NSDate timeIntervalSinceReferenceDate])];
    SPXSpeechTranslationConfiguration *speechConfig = [[SPXSpeechTranslationConfiguration alloc] initWithSubscription:speechKey region:serviceRegion];
    [speechConfig setSpeechRecognitionLanguage:self.sourceLanguageId];
    [speechConfig addTargetLanguage:self.destinationLanguageId];
    if (!speechConfig) {
        NSLog(@"Could not load speech config");
        //        [self updateRecognitionErrorText:(@"Speech Config Error")];
        return;
    }
    SPXAudioConfiguration *audioConfiguration = [[SPXAudioConfiguration alloc] initWithStreamInput:self.inputStream];
  
     _speechRecognizer = [[SPXTranslationRecognizer alloc] initWithSpeechTranslationConfiguration:speechConfig audioConfiguration:audioConfiguration];
    __weak typeof(self) weakMS = self;
    [_speechRecognizer  addRecognizedEventHandler:^(SPXTranslationRecognizer * recognizer, SPXTranslationRecognitionEventArgs * eventArgs) {
        NSLog(@"reason:%@",@(eventArgs.result.reason));
        [weakMS.results addObject:eventArgs.result];
        [weakMS updateRecognitionResult];
    }];
    [_speechRecognizer addRecognizingEventHandler:^(SPXTranslationRecognizer * recognizer, SPXTranslationRecognitionEventArgs * eventArgs) {
        [weakMS.results addObject:eventArgs.result];
        [weakMS updateRecognitionResult];
        [weakMS.results removeLastObject];
    
    }];
  [_speechRecognizer addCanceledEventHandler:^(SPXTranslationRecognizer * recognizer, SPXTranslationRecognitionCanceledEventArgs * eventArgs) {
        [weakMS updateRecognitionResult];
        NSLog(@"cancel recognizer:%@",eventArgs.errorDetails);
    }];
    [_speechRecognizer addSessionStartedEventHandler:^(SPXRecognizer * recognizer, SPXSessionEventArgs * eventArgs) {
        NSLog(@"addSessionStartedEventHandler");
    }];
    
    [_speechRecognizer addSessionStoppedEventHandler:^(SPXRecognizer * recognizer, SPXSessionEventArgs * eventArgs) {
        NSLog(@"addSessionStoppedEventHandler");
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1.1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            [weakMS teardown];
        });
    }];
    [_speechRecognizer startContinuousRecognition];

}
-(void)didRecordData:(NSData *)pcmData{
    [_inputStream write:pcmData];
}

`

this is main code

**Comment by ariefshah** [comment]
Did you got this working? @hold-my-hand

**Comment by hold-my-hand** [comment]
> Did you got this working? @hold-my-hand

Yes,when I change the write param of recordFile

-(AudioStreamBasicDescription)audioStreamBasicDescription{
    AudioStreamBasicDescription asbd;
    memset(&asbd, 0, sizeof(asbd));
    asbd.mSampleRate = 16000;            //采样率
    asbd.mFormatID = kAudioFormatLinearPCM;
    asbd.mFormatFlags = kLinearPCMFormatFlagIsSignedInteger | kAudioFormatFlagIsPacked;
    asbd.mChannelsPerFrame = 1;         //单声道
    asbd.mFramesPerPacket = 1;          //每一个packet一侦数据
    asbd.mBitsPerChannel = 16;          //每个采样点16bit量化
    asbd.mBytesPerFrame = (asbd.mBitsPerChannel / 8) * asbd.mChannelsPerFrame;
    asbd.mBytesPerPacket = asbd.mBytesPerFrame ;
    return asbd;
}

**Comment by wolfma61** [comment]
not sure what this means - assuming the best ....
