### ISSUE TITLE
display string validation bug due to line breaking in batched transcription results

### ISSUE THREAD

**Issue by jhwang7628** [Azure-Samples/cognitive-services-speech-sdk#1020]
**Describe the bug**
We have experienced a schema validation error due to Azure batch transcription returning strings that are formatted like this under `data/combinedRecognizedPhrases/0/display`
```
{
  ...
  "display": "long foo... \n" + "long bar... \n" + "long foobar..."
}
``` 
However, due to the schema pattern matching ([link](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/transcriptionresult_v3.schema.json#L129)), the validator will choke as line break character cannot be matched.

**To Reproduce**
This behavior is observed in many of our ingested transcriptions. However, I cannot post these data due to privacy concerns. I assume long transcript can cause this fairly frequently.

**Expected behavior**
Schema pattern be allowing line breaking if Azure-S2T returns it.

**Version of the Cognitive Services Speech SDK**
I am using Azure S2T V3.

**Platform, Operating System, and Programming Language**
 - OS: macOS 10.15.7
 - Programming language: JavaScript

**Comment by chlandsi** [comment]
Hi @jhwang7628 , could you post a transcription id of one of the affected transcriptions, the approximate time (day) of the transcription and the region, so we can check against the service logs? Thank you!

**Comment by jhwang7628** [comment]
Hi,

Not sure if this is the ID you are looking for. But this is the last part of the endpoint URL we used to GET the result: `0c74c6f4-4718-4302-a98c-aae3e99ba016`
The timestamp of the run is `timestamp: '2021-03-30T01:58:58Z'`
The region is `westus`.

Let me know if those information is enough.

**Comment by jhwang7628** [comment]
@chlandsi , we've found similar problems with the `recognizedPhrases`. We are removing all RE matching in our schema as a temporary solution.

**Comment by chlandsi** [comment]
Hi @jhwang7628, this happens with the default punctuation mode when the transcribed text contains the words "new line", which is then interpreted as a punctuation instruction and replaced with a newline. You can work around this by setting the `PunctuationMode` to `Automatic` or `None` in the properties of the transcription.

**Comment by jhwang7628** [comment]
Just to be clear, are you saying everytime "new line" appears in the transcribed text (in Lexical? Display?), it would be interpreted as a punctuation instruction and replaced with "\n"?

**Comment by chlandsi** [comment]
Yes, with the default punctuation mode setting (`DictatedAndAutomatic`) the words "new line" (also "period", "comma" etc.) can be, depending on the context, interpreted as dictated punctuation and the corresponding symbols are inserted into the display form instead of the words. The lexical form is not affected by this.

**Comment by jhwang7628** [comment]
I see. This is good to know! I guess in any case, it could be good to modify the RE to include line break in case users are using the punctuation mode?

**Comment by chlandsi** [comment]
We have adapted the schema in #1033. Thank you for raising the issue!
