### ISSUE TITLE
Python Batch Transcription Status continuously "Running"

### ISSUE THREAD

**Issue by jeffkayne** [Azure-Samples/cognitive-services-speech-sdk#1021]
**Describe the bug**
Hi, I am not getting a "Completed" response from a python batch transcription job for 2 audio files around 3 minutes in length. The model is a custom speech trained STT model.

Transcription ID: "598105ec-b1a5-4507-8408-0fe3d78c1c0e"
SERVICE_REGION: francecentral

**Platform, Operating System, and Programming Language**
 - iOS
 - Programming language: Python

**Comment by chlandsi** [comment]
Hi @jeffkayne, there is an issue that is slowing sown transcriptions in France Central. Could you drop me a mail at <my alias> at microsoft.com?

**Comment by glecaros** [comment]
Closing this issue as there hasn't been any movement in some time. Feel free to reopen if needed.
