### ISSUE TITLE
Unable to successfully use mstts:backgroundaudio

### ISSUE THREAD

**Issue by ccoreilly** [Azure-Samples/cognitive-services-speech-sdk#1022]
Whenever I use the `mstts:backgroundaudio` tag, an Internal Server Error is raised by the SpeechSynthesizer.

I am using the following SSML:

```
<speak version="1.0" xml:lang="en-US" xmlns:mstts="http://www.w3.org/2001/mstts">
  <mstts:backgroundaudio src="https://www2.cs.uic.edu/~i101/SoundFiles/StarWars3.wav" />
  <voice name="en-US-GuyNeural">
    The text provided in this document will be spoken over the background audio.
  </voice>
</speak>
```

The file is a reachable 1 channel pcm_s16le 22050Hz audio. But the speechSynthesis throws the following CancellationResults:

```
{
  "privResult": {
    "privResultId": "8C65755E71AD44C6BA49381DBD938FCF",
    "privReason": 1,
    "privErrorDetails": "Internal server error. websocket error code: 1011",
    "privProperties": {
      "privKeys": [
        "CancellationErrorCode"
      ],
      "privValues": [
        "ConnectionFailure"
      ]
    }
  }
}
```

Other mstts tags like `mstts:express-as` work as intended.

Tested on Node with `microsoft-cognitiveservices-speech-sdk` version `1.16.0` in the following regions:
- eastus
- westeurope

**Comment by ccoreilly** [comment]
Using the Java library (version 1.16.0) the result is successful but `getAudioData().length` is 0 bytes.

**Comment by ccoreilly** [comment]
I managed to get it to work on Node. I was using the [sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/node/synthesis.js) from the repository and had to comment out the `wordBoundary` event listener for it to work.

It would be nice if the CancellationReason of the synthesizer would contain such information. When using the `audio` tag with wordBoundary the following error is shown:

```
{
  "privResult": {
    "privResultId": "D94942955541470EB617303755F41C41",
    "privReason": 1,
    "privErrorDetails": "Cannot send word boundary events if audio source is present in ssml websocket error code: 1007",
    "privProperties": {
      "privKeys": [
        "CancellationErrorCode"
      ],
      "privValues": [
        "BadRequestParameters"
      ]
    }
  }
}
```

This is not the case when using the `mstts:backgroundaudio` tag (see error above).

Moreover, I am not managing to get it to work with Java. I tried setting the following property to no avail:

`speechConfig.setProperty("SpeechServiceResponse_Synthesis_WordBoundaryEnabled", "false");`

**Comment by yulin-li** [comment]
Hi @ccoreilly, thanks for reaching out. Seems this is a service issue instead of SDK. Adding @Yueying-Liu for checking

**Comment by Yueying-Liu** [comment]
@Dapeng ***@***.***> Will you be the owner to debug the background audio tag?
view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure-Samples%2Fcognitive-services-speech-sdk%2Fissues%2F1022%23issuecomment-839322992&data=04%7C01%7Cyueyingl%40microsoft.com%7C64b9970454e54a8fcf4c08d914dc1bb2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637563757881943446%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CwZ7b3oqUM8VqomxPWYX2Wwxjery6NILeP2ZcpkRDqM%3D&reserved=0>

Yueying

**Comment by yulin-li** [comment]
assigned to @Yueying-Liu to follow up

**Comment by yulin-li** [comment]
@ccoreilly For now, the background audio and word boundary could not work together. The SDK returns error with details except for the browser SDK. This is due to the limitation of w3c websocket interface. 

The service team is working on fixing the issue that background audio and word boundary could not work together. But as this is not a blocker to your work. We will close this issue and keep tracking internally.

**Comment by ccoreilly** [comment]
@yulin-li can you tell me how to disable to word boundary in the Java SDK? I only managed to do it in the JavaScript SDK but not Java and it is thus blocking my usage of the tag.

**Comment by yulin-li** [comment]
@ccoreilly The word boundary feature is disabled by default. Make sure the `WordBoundary` event is not subscribed is enough.
