### ISSUE TITLE
Trouble finding JavaScript speech-sdk bundle min .js

### ISSUE THREAD

**Issue by inglesuniversal** [Azure-Samples/cognitive-services-speech-sdk#1023]
Hi,

Every time you guys update the JS bundle . min . js (Speech SDK for JavaScript (Browser, I have such a hard time finding it.

Can you kindly provide me with a fixed URL or GitHub URL were I can always download the latest version.

Thanks

**Comment by rhurey** [comment]
Thanks. I put an item in our backlog to have a "Latest"  folder we can update each release.

We should be able to start that with the next release.

**Comment by BrianMouncer** [comment]
@inglesuniversal 

I picked up this work item from our backlog.
Can you please confirm if these are what you need to find the latest release each milestone?

The link will alway point to the latest java script package, 

https://aka.ms/csspeech/jsbrowserpackage

These two links will always point to the uncompressed RAW SDK package.

https://aka.ms/csspeech/jsbrowserpackageraw
https://aka.ms/csspeech/microsoft.cognitiveservices.speech.sdk.bundle.js.map

**Comment by inglesuniversal** [comment]
That's simply AWESOME... I was looking for that for quite a while!!!

Thanks so much for your continued support.

#STAYSAFE
