### ISSUE TITLE
Add speaker identification and verification for Python SDK

### ISSUE THREAD

**Issue by pymia** [Azure-Samples/cognitive-services-speech-sdk#1031]
**Is your feature request related to a problem? Please describe.**
At the moment I can only see C# and C++ support for speaker identification and verification in the quickstart folder.
It will benefit for the Python community to have this support. 

**Describe the solution you'd like**
Able to register the speaker profile and verify them with the speech API.
Able to register the speaker profile and identify them with the speech API.

**Describe alternatives you've considered**
NA.

**Additional context**
NA.

**Comment by ralph-msft** [comment]
Thanks for this feature request.

We have filed this internally as feature request for triage. At this time we don't have any updates if and/or when this would be available.
