### ISSUE TITLE
MetaData Capture during translation

### ISSUE THREAD

**Issue by maheshcheetirala** [Azure-Samples/cognitive-services-speech-sdk#1032]
Hello Team ,
We are trying to build this solution to a customer on their call center.  one challenge we observed is metadata is missing and we are getting all files as same date after transcribing by running this solution. Just wanted your help and tips on how we can hold metadata and get that metadata in SQL tables so we can build dash boards based on dates or weeks to understand the sentiment analysis. Please let us know if there is a way we can achieve this.

Thanks
Mahesh

**Comment by ralph-msft** [comment]
Unfortunately you have not provided enough information for us to be able help you.

- What Cognitive Speech services are you using?
- What metadata are you looking for?
- What is the minimum code that reproduces the issue you are seeing?

**Comment by maheshcheetirala** [comment]
Hello Team,
I am using the batch ingestion client ARM template given in the repository.
After getting the results in SQL database I don't see any column called
date or last modified date for the files. It's generating hash Id which
becomes difficult in building a dashboard based on daily call data or
weekly data to analyse sentiment.
Please let me know what to do.

Thanks
Mahesh

**Comment by zhouwangzw** [comment]
@HenryvanderVegte Could you please help Mahesh?

**Comment by HenryvanderVegte** [comment]
Hi Mahesh,

in the Table called "Transcriptions" you will find the info you are looking for. It contains Name (which is the name of the audio file on storage) as well as SourceUri and Timestamp. I think the timestamp is what you are looking for.

Regarding the metadata: Our solution only works with the audio file, so we don't process custom metadata at all. If you'd like to ingest metadata into the database, you'd need to change the database schema. You could do the mapping between metadata and the audio file based on the Name in the Transcriptions table.

I hope this answers your question.

Thanks!
Henry

**Comment by maheshcheetirala** [comment]
Hello Henry,
Thank you for the information. In the transcription table time stamp is the
time at which the transcription occurred. Even we have 30 files all files
are getting same time stamp.
I was looking for a solution that can capture metadata from azure blob and
preserve it in SQL database, please let me know what code changes do I
need to make.

Thanks
Mahesh

**Comment by HenryvanderVegte** [comment]
Hi Mahesh,

yes, that is the timestamp when the ingestion client is submitting the job - and this is happening every 2 minutes. So if you're uploading files over weeks you can create your sentiment dashboard with a granularity of 2 mins.

Capturing metadata from blob is definitely possible, but requires a bit of work. In theory, you could use an Azure Function to how we process audio data.
I'd have a look at the following guides to process blob events (or service bus messages):
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=csharp
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=csharp


If you'd like to have a look at how we process the events in the solution, I'd advise you to start here:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/batch-ingestion-client/StartTranscriptionByTimer/StartTranscriptionByTimer.cs

and this is where we write transcription results to the database:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/batch-ingestion-client/Connector/DatabaseConnector.cs


Thanks!
Henry

**Comment by maheshcheetirala** [comment]
Thanks, I'll check it out.
