### ISSUE TITLE
Europe Api service down/slow

### ISSUE THREAD

**Issue by SOliasS** [Azure-Samples/cognitive-services-speech-sdk#1036]
The Api in Europe seems to be struggling at the moment.
I ether have to wait 10 seconds for an response or i get an cancel event with:

Microsoft.CognitiveServices.Speech.CancellationErrorCode.ServiceTimeout
 or
Microsoft.CognitiveServices.Speech.CancellationErrorCode.ServiceUnavailable
with the following example error
Timeout: no recognition result received SessionId: 4f39613743a785149cef3e531e45d2d4

**Comment by AdamGustavsson** [comment]
I'm also experiencing issues. I use Text-to-speech in the westeurope region

**Comment by backnext321** [comment]
same problem here: westeurope microsoft.cognitiveservices.speech.sdk.... Waiting seconds for speech and hiccups. Sometimes no problem and then again...

**Comment by ralph-msft** [comment]
Thanks for reporting these issues. These should all be mitigated as of 2021-04-08 at 13:15 UTC.
