### ISSUE TITLE
DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by backnext321** [Azure-Samples/cognitive-services-speech-sdk#1037]
cognitive-services-speech-sdk for Javascript Browser: TTS
As I use the new way to reach the microsoft.cognitiveservices.speech.sdk.bundle.js (example version 1.16.0) https://aka.ms/csspeech/jsbrowserpackageraw
I get this warning:
DevTools failed to load SourceMap: Could not parse content for https://aka.ms/csspeech/microsoft.cognitiveservices.speech.sdk.bundle.js.map: Unexpected token < in JSON at position 6
Do I still have to provide the sdk.bundle.js.map file somewhere?

**Version of the Cognitive Services Speech SDK 1.16.0**

 - OS: Windows 10
 - Programming language: JavaScript
 - Browser Chrome

**Comment by ralph-msft** [comment]
Thanks for reporting this issue. This is now resolved.

If you continue to have issues, please re-open this issue as needed.
