### ISSUE TITLE
Handling Session Started Errors

### ISSUE THREAD

**Issue by vivianliu0** [Azure-Samples/cognitive-services-speech-sdk#1038]
Hi! I'm currently using the Java Speech SDK (Version 1.16.0) in my project, where we are using SpeechRecognizers that are being subscribed to sessionStarted, sessionStopped, recognized, and canceled events. Currently, we are invoking startContinuousRecognitionAsync() and waiting for the sessionStarted callback before sending audio to our pushStream. On a success the sessionStarted callback is invoked, but what is expected to happen in a failure case? I see that the canceled callback is invoked only when a recognition event is unsuccessful (e.g. after receiving the sessionStarted callback), what happens if there is a failure starting the session?

**Comment by ralph-msft** [comment]
The canceled event is also raised if the SDK cannot connect to the speech service. For example if you use the ```SpeechConfig.fromEndpoint("wss://not.a.valid.endpoint.goes:1234/here", "subscriptionKey");```, the canceled event will be raised with the error details.

**Comment by vivianliu0** [comment]
Thanks for clarifying! I see now that if the SDK cannot connect to the speech service, the sessionStarted event is raised as well as the canceled event. Is it possible for the sessionStarted event to not be raised when startContinuousRecognitionAsync() is invoked?

**Comment by glecaros** [comment]
Hi @vivianliu0,
Unfortunately changing that behavior would be considered a breaking change. I'll bring this up to the team so it can be considered for when we have our next major version and also to see if we can have more detailed documentation about these events.

I'll close this issue, please feel free to reopen if you need further help.
