### ISSUE TITLE
SPXSpeechSynthesizer - iOS - play audio

### ISSUE THREAD

**Issue by tomasgreen** [Azure-Samples/cognitive-services-speech-sdk#1039]
Hi!

I've been trying to take control of playing the audio coming from the SPXSpeechSynthesizer but it seems as if the system doesn't recognise the format (tried playing the files on my Mac as well, same result).

It doesn't seem to matter if I store the file using SPXAudioConfiguration(wavFileOutput:) or the resulting audioData property.
I also tried to write the data buffer directly to a AVAudioPCMBuffer but all I got was "static".

**Format**: SPXSpeechSynthesisOutputFormat.raw24Khz16BitMonoPcm
**NSOSStatusErrorDomain Code**: 1954115647
**Framework**: 1.16.0
**Devices**: tested on iOS 14.x (simulator and device)

**Comment by glharper** [comment]
@tomasgreen Raw PCM formats don't seem to be supported for playback on any platform. Are you experiencing the same issue with RIFF PCM output?

**Comment by tomasgreen** [comment]
@glharper Yeah, that did it! I assumed that the raw format would be the most reliable but I should have tried using another format before reaching out... that's what I get for posting an issue on a Friday afternoon 😉

Thanks!
