### ISSUE TITLE
Confidence scores for Translation requests

### ISSUE THREAD

**Issue by spines** [Azure-Samples/cognitive-services-speech-sdk#104]
**Is your feature request related to a problem? Please describe.**

When we're running translation requests via the C++ Speech SDK, confidence scores are not included in the detailed output. 

Example code (C++)

```
auto config = SpeechTranslationConfig::FromSubscription(api_key, region);
config->SetSpeechRecognitionLanguage(fromLanguage);
config->SetOutputFormat(OutputFormat::Detailed);

for (int i=0; i<targetLanguages.size(); i++)
    config->AddTargetLanguage(targetLanguages[i]);

auto audioInput = AudioConfig::FromWavFileInput(file_path);
auto recognizer = TranslationRecognizer::FromConfig(config, audioInput);
auto result = recognizer->RecognizeOnceAsync().get();

cout << result->Properties.GetProperty(PropertyId::SpeechServiceResponse_JsonResult);

```

Output (modified text): {"Duration":200000000,"Offset":400000,"RecognitionStatus":"Success","Text”:”Testing one two three.“,”Translation":{"TranslationStatus":"Success","Translations":[{"Language":"en","Text":"Testing one two three.”}]}}

In practice, we're using this API because we're starting with arbitrary input audio and we want to display back translations in both Spanish and English. Confidence scores would be very useful to us since we don't have a way to automatically detect the input audio language. Currently, we'd run both "input=spanish" and "input=english" and drop the output with lower confidence. 

**Describe the solution you'd like**

For both the recognition and each of the translations, provide a confidence score (0-100). 

**Describe alternatives you've considered**

None of the other API endpoints we've seen concisely do transcription and translation.

An alternative that would help us out is for the translation endpoint to take a best guess what language it's in (e.g. config->SetSpeechRecognitionLanguage("unk")) 

**Additional context**

I'm assuming these endpoints are relatively new, but if I'm missing something obvious (admittedly I'm relatively new to C++) please let me know and close this ticket.

Thank you!

**Comment by wolfma61** [comment]
thank you, this has been added to the internal feature request list.

there is discussion/thinking about 'language identification', but this hasn't made it into an stand-alone service or into the translation service (seems to be not a trivial issue to have this information 'with confidence' ;))
once available, we will make it available from the sdk, but no ETA available,
