### ISSUE TITLE
Default output device is not updated at runtime if device changes

### ISSUE THREAD

**Issue by StevenJDH** [Azure-Samples/cognitive-services-speech-sdk#1040]
**Describe the bug**
When using  the default output device for audio output, if you change the device because let's say you were using your PC speakers and then changed to headphones, the audio will still continue to use your PC speakers. Likewise, if you started with headphones and then unplugged them, you won't hear anything because it's still trying to use the headphones as opposed to PC speakers. This is also the same with Bluetooth speakers.

**To Reproduce**
1. Start application using  cognitive services speech library with default output device. Make sure that the `SpeechSynthesizer` object is set as an instance variable not a local variable for this test.
2. Trigger a TTS message to hear it.
3. Now plug in your headphones, or click the windows volume controls, and above the volume level, select a new output device.
4. Trigger another TTS message and observe how it still targets the original output device.
5. Now restart the application and trigger another message and observe how now it targets your current output device, your headphones.

**Expected behavior**
Audio output should always target whatever the current default output device is. This is the exact same behavior we can see in the `System.Speech` library for local TTS.

**Version of the Cognitive Services Speech SDK**
1.16.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - x64
 - Programming language: C#

**Additional context**
 - No error messages.
 - Current workaround is to instantiate a new `SpeechSynthesizer` object each time TTS is needed to ensure it is using the current default output device.

**Comment by glharper** [comment]
@StevenJDH Thanks for letting us know about this issue. I've added a item on our team's backlog to track work against this.
