### ISSUE TITLE
Speech-To-Text :: Continuous :: Python SDK :: silence

### ISSUE THREAD

**Issue by madkote** [Azure-Samples/cognitive-services-speech-sdk#1043]
Hi all,

I am using Python SDK for continuous speech recognition from an audio stream.
Sometimes audio has long silence and I would like to handle it.
is it possible?

**Comment by glharper** [comment]
@madkote Thanks for using Speech SDK. I believe the property SpeechServiceConnection_EndSilenceTimeoutMs, which can be set on a SpeechConfig object, is what you're looking for.

**Comment by madkote** [comment]
@glharper I will verify and let you know.

**Comment by madkote** [comment]
@glharper it helped. thx.
