### ISSUE TITLE
System.DllNotFoundException: libMicrosoft.CognitiveServices.Speech.core.so in XF (Android)

### ISSUE THREAD

**Issue by IlGalvo** [Azure-Samples/cognitive-services-speech-sdk#1044]
**Problem Description**
When clicking on the button to start mic recognition, this exception is thrown:

> System.DllNotFoundException: libMicrosoft.CognitiveServices.Speech.core.so assembly:<unknown assembly> type:<unknown type> member:(null)
>   at (wrapper managed-to-native) Microsoft.CognitiveServices.Speech.Internal.SpeechConfig.speech_config_from_subscription(intptr&,string,string)
>   at Microsoft.CognitiveServices.Speech.SpeechConfig.FromSubscription (System.String subscriptionKey, System.String region) [0x00007] in <f7a54065b3b540c8b26d9a68c1528ef2>:0

**To Reproduce**
1. Download the attached example.
2. Insert key and region
3. Select Android as destination
4. Run and click on the button to start the mic.

**Expected behavior**
It starts to listen from mic and then return a result.

**Version of the Cognitive Services Speech SDK**
https://www.nuget.org/packages/Microsoft.CognitiveServices.Speech/1.16.0

**Platform, Operating System, and Programming Language**
 - OS: Windows
 - Hardware - x64
 - Programming language: C# (Xamarin Forms - Android)

**Additional context**
To setup the project I followed:

> https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/setup-platform?tabs=xaml%2Cwindows%2Cjre%2Cbrowser&pivots=programming-language-csharp

So both x86 and x64 versions of Microsoft Visual C++ Redistributable per Visual Studio 2019 are installed.

In addition, I inspected the .apk and the libraries exist.

[Test.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6318772/Test.zip)

**Comment by glharper** [comment]
@IlGalvo Thank you for the detailed writeup, and including your test solution! Running the test solution on an Android Emulator (Pixel 2 Pie 9.0) does not produce the exception you describe. From the debug output, I see:[Mono] DllImport attempting to load: 'libMicrosoft.CognitiveServices.Speech.core.so'.
[Mono] DllImport error loading library '/data/data/com.companyname.test/files/.__override__/libMicrosoft.CognitiveServices.Speech.core.so': '(null)'.
[chatty] uid=10086(com.companyname.test) identical 1 line
[Mono] DllImport error loading library '/data/data/com.companyname.test/files/.__override__/libMicrosoft.CognitiveServices.Speech.core.so': '(null)'.
[Mono] DllImport error loading library '/system/lib/libMicrosoft.CognitiveServices.Speech.core.so': '(null)'.
[chatty] uid=10086(com.companyname.test) identical 1 line
[Mono] DllImport error loading library '/system/lib/libMicrosoft.CognitiveServices.Speech.core.so': '(null)'.
[Mono] DllImport loaded library 'libMicrosoft.CognitiveServices.Speech.core.so'.
[Mono] DllImport searching in: 'libMicrosoft.CognitiveServices.Speech.core.so' ('libMicrosoft.CognitiveServices.Speech.core.so').
[Mono] Searching for 'speech_config_from_subscription'.
[Mono] Probing 'speech_config_from_subscription'.
[Mono] Found as 'speech_config_from_subscription'.

And I can see that Test\Test.Android\obj\Debug\110\android\assets contains Microsoft.CognitiveServices.Speech.csharp.dll
When you write "the libraries exists," do you mean this dll exists in that location?

**Comment by IlGalvo** [comment]
If it can help, here they are my VS spec:
[VS Spec.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6327222/VS.Spec.txt)

As you can see in the picture below, I tried to deploy bot debug and release in these devices:
![Img1](https://user-images.githubusercontent.com/17992288/115068134-27af3480-9ef2-11eb-9001-2a8a14a01d01.jpg)

Lastly, the libraries I was talking about, are thoose located in `lib` in the apk.
I attach one of them below, but they're all the same practically.
[com.companyname.test-Signed.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6327237/com.companyname.test-Signed.zip)

If you need further information, please tell me.
Thanks in advance.

**Comment by glharper** [comment]
Try switching the Processor for your emulators to x86 (instead of x86_64). I'm noticing the .zip you provided doesn't have our .so files in the x86_64 folder for some reason.

**Comment by glharper** [comment]
I have reproduced this when I switched to a x64 emulator

**Comment by IlGalvo** [comment]
Ok, confirmed: on x86 emulator and my actual ARM device, everything works great!

So the problem lies only in the x86 android devices.
