### ISSUE TITLE
custom wake word model in JS

### ISSUE THREAD

**Issue by accateo** [Azure-Samples/cognitive-services-speech-sdk#1048]
Hi,
will cognitive service speech SDK (Node or JavaScript) support custom wake word model in future?

Thanks

**Comment by chschrae** [comment]
Hi there,

Thanks for reaching out.

Currently there are no plans to add this. Could you tell us more about the scenario you are working on? Perhaps there is another way to achieve your goals.

**Comment by chschrae** [comment]
After further investigation, it turns out there ARE plans! However no release has the work item attached to it yet so I do not know when it would be available.

**Comment by accateo** [comment]
@chschrae I would activate the registration only when a specific keyword is "heard"
