### ISSUE TITLE
Getting Error 964 while setting proxy details in cognitive speech services

### ISSUE THREAD

**Issue by Thenmozhi16** [Azure-Samples/cognitive-services-speech-sdk#105]
In Cognitive speech services earlier version, I have connection issue(no connection to the remote host) in proxy network. In version 1.1.0, I have provided the proxy information using SetProxy(). But still I'm getting error in proxy network.

Error details: 694. Please check network connection, firewall setting, and the region name used to create speech factory.

**Comment by zhouwangzw** [comment]
Can you see connection and traffic to the proxy server? Currently SDK supports http proxy. Does your proxy server support to tunnel traffic via port 443?

**Comment by Thenmozhi16** [comment]
Yes,proxy server supports traffic via port 443.

We suspect the following could be the issue:
While setting proxy settings in Microsoft API, SetProxy() method accepts  Proxy server name, port, username, password. But our environment is single sign on environment. We dont have separate credentials for Proxy server.

**Comment by wolfma61** [comment]
We also fixed an issue with empty proxy username and passwords.
You might want to retest with the latest release 1.3.1
