### ISSUE TITLE
nodejs - Transcription status "NotStarted", no transcription id

### ISSUE THREAD

**Issue by junaidahmed361** [Azure-Samples/cognitive-services-speech-sdk#1050]
When I submit my transcription job from nodejs, I am faced with a couple of issues. First, the api's createTranscription method returns nothing when doing an asynchronous call. Since this isn't working, and since it is a REST api, I tried sending a request from Postman with the appropriate body and headers to the Create Transcription endpoint. My file is in a Azure blob container. I am returned a 201 response where the job was created, however there is no transcription job id and the status reads "NotStarted" each time I submit.

Here is the returned body:
```
{
    "self": "https://westus2.api.cognitive.microsoft.com/speechtotext/v3.0/transcriptions/22014645-b005-4acb-9aaf-93e9960f2d38",
    "model": {
        "self": "https://westus2.api.cognitive.microsoft.com/speechtotext/v3.0/models/1cfa5e5e-6203-4c9f-b9b3-30142e84fac5"
    },
    "links": {
        "files": "https://westus2.api.cognitive.microsoft.com/speechtotext/v3.0/transcriptions/22014645-b005-4acb-9aaf-93e9960f2d38/files"
    },
    "properties": {
        "diarizationEnabled": false,
        "wordLevelTimestampsEnabled": false,
        "channels": [
            0,
            1
        ],
        "punctuationMode": "DictatedAndAutomatic",
        "profanityFilterMode": "Masked"
    },
    "lastActionDateTime": "2021-04-21T16:22:05Z",
    **"status": "NotStarted",**
    "createdDateTime": "2021-04-21T16:22:05Z",
    "locale": "en-US",
    "displayName": "Transcription using default model for en-US"
}
```

**Comment by chlandsi** [comment]
The transcription id is the id at the end of the `self` field in the response: "self": "https://westus2.api.cognitive.microsoft.com/speechtotext/v3.0/transcriptions/**22014645-b005-4acb-9aaf-93e9960f2d38**". To see the current status of your transcription, do a GET request on that route. Please also refer to these [docs](https://docs.microsoft.com/en-gb/azure/cognitive-services/speech-service/batch-transcription).

**Comment by junaidahmed361** [comment]
Thanks
