### ISSUE TITLE
Pronunciation Accessment- word level detail

### ISSUE THREAD

**Issue by anushaa01** [Azure-Samples/cognitive-services-speech-sdk#1052]
I am facing issue with the word level result. As per the docs,  in error type, we should get any one of the 3 parameters that is: omitted, inserted and missed spelled. But We are only getting if the word is misspelled.

**Comment by chschrae** [comment]
Hi there!

Thank you for your issue.

Can you provide any more details about your use or the SDK?

Do you have a particular code snippet that shows the area you are getting the unexpected value?

**Comment by pankopon** [comment]
Closed since no update, please open a new issue if support is still needed.
