### ISSUE TITLE
Streaming is not supported for speech-to-text on Android

### ISSUE THREAD

**Issue by cl-6666** [Azure-Samples/cognitive-services-speech-sdk#1057]
The voice-to-text does not support Android streaming, which is not found in your official documents. We are using our own directional microphone. We want to identify it on your platform in real time based on the audio stream we recorded. I asked your customer service to say no before Support, because our current approach is to synthesize our own audio stream into wav and then go to your platform for recognition. The recognition speed is a bit slow in about 3 seconds, so I want to try streaming recognition

**Comment by glecaros** [comment]
hi @cl-6666, maybe you can try using something like [this example](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/android/sdkdemo/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/sdkdemo/MicrophoneStream.java) to populate it with your stream.

Please let me know if that works.

**Comment by cl-6666** [comment]
我试过了，这种方法不行，我们麦克风现在返回的是byte[] data，不知道您那边是否可以提供一个类似这样的api 
   ，mRecognizer.writeAudio(data, 0, data.length);   实时的传输给你们流    然后识别结果回调给我们

**Comment by cl-6666** [comment]
I tried it, but this method doesn’t work. Our microphone now returns byte[] data. I don’t know if you can provide an api like this
，MRecognizer.writeAudio(data, 0, data.length); transmit it to you in real time, and then call back the recognition result to us

**Comment by cl-6666** [comment]
> 嗨@ cl-6666，也许您可​​以尝试使用类似[此示例的内容](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/android/sdkdemo/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/sdkdemo/MicrophoneStream.java)来填充您的流。
> 
> 请让我知道是否可行。

I tried it, but this method doesn’t work. Our microphone now returns byte[] data. I don’t know if you can provide an api like this
，MRecognizer.writeAudio(data, 0, data.length); transmit it to you in real time, and then call back the recognition result to us

**Comment by glecaros** [comment]
[This example](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/java/android/keyword-recognizer-stream/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/quickstart/MainActivity.java) uses a push audio input stream. Let me know if that is what you need.

**Comment by cl-6666** [comment]
> [本示例](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/java/android/keyword-recognizer-stream/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/quickstart/MainActivity.java)使用推送音频输入流。让我知道这是否是您所需要的。

Hello, I saw this case. This is to identify local files. I think I may not express it clearly. The effect we want is like this. Directly take the real-time audio stream returned by our own microphone and give it to you for real-time recognition. , I saw that other platforms do this and I posted the code.

 if (isLast) {
            if (mRecognizer != null) {
                mRecognizer.stopListening();
            }
        } else {
            mRecognizer.writeAudio(data, 0, data.length);
        }

 /**
     * 听写监听器。
     */
    private RecognizerListener mRecognizerListener = new RecognizerListener() {

        @Override
        public void onBeginOfSpeech() {
            // 此回调表示：sdk内部录音机已经准备好了，用户可以开始语音输入5e9d71b3
            if (mListener != null) {
                mListener.onRecognizerPrepared();
            }
        }

        @Override
        public void onError(SpeechError error) {
            // 错误码：10118(您没有说话)，可能是录音机权限被禁，需要提示用户打开应用的录音权限。
            // 如果使用本地功能（语记）需要提示用户开启语记的录音权限。
            if (mListener != null) {
                mListener.onRecognizerError(error.getPlainDescription(true));
            }
        }

        @Override
        public void onEndOfSpeech() {
            // 此回调表示：检测到了语音的尾端点，已经进入识别过程，不再接受语音输入
            if (mListener != null) {
                mListener.onSpeechFinished();
            }
        }

        @Override
        public void onResult(RecognizerResult results, boolean isLast) {
            Log.d(TAG, results.getResultString());
            String printResult = printResult(results);

            if (isLast) {
                if (mListener != null) {
                    mListener.onGetRecognizerResult(printResult);
                }
//                FileSDCardUtil.saveFileToExternalFileDir(mContext, FileSDCardUtil.loadDataFromSDCard("/storage/emulated/0/msc/iat.wav"), "ali" + System.currentTimeMillis()+".wav");
            }

            if (isLast) {
                if (mListener != null) {
                    mListener.onGetRecognizerResultEnd();
                }
            }
        }

        @Override
        public void onVolumeChanged(int volume, byte[] data) {
            Log.d(TAG, "返回音频数据：" + data.length);
            if (mListener != null) {
                mListener.onVolumeChanged(volume);
            }
        }

        @Override
        public void onEvent(int eventType, int arg1, int arg2, Bundle obj) {

        }
    };

Where isLast is whether the speech is finished

**Comment by cl-6666** [comment]
> [本示例](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/java/android/keyword-recognizer-stream/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/quickstart/MainActivity.java)使用推送音频输入流。让我知道这是否是您所需要的。

Hello, I saw this case. This is to identify local files. I think I may not express it clearly. The effect we want is like this. Directly take the real-time audio stream returned by our own microphone and give it to you for real-time recognition. , I saw that other platforms do this and I posted the code.

if (isLast) {
if (mRecognizer != null) {
mRecognizer.stopListening();
}
} else {
mRecognizer.writeAudio(data, 0, data.length);
}

Where isLast is whether the speech is finished

**Comment by cl-6666** [comment]
> [This example](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/java/android/keyword-recognizer-stream/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/quickstart/MainActivity.java) uses a push audio input stream. Let me know if that is what you need.

Hello, I saw this case. This is to identify local files. I think I may not express it clearly. The effect we want is like this. Directly take the real-time audio stream returned by our own microphone and give it to you for real-time recognition. , I saw that other platforms do this and I posted the code.

if (isLast) {
if (mRecognizer != null) {
mRecognizer.stopListening();
}
} else {
mRecognizer.writeAudio(data, 0, data.length);
}

Whether isLast has finished speaking, the last is to return the result in the result listener

**Comment by glecaros** [comment]
What I believe you need to do is to use that same mechanism that sample uses; so you would create your recognizer using a PushAudioInputStream and do something like:

```java
audioRecorder.startRecording();

byte[] buffer = new byte[audioRecorderBufferSize];

while (audioRecorder.getRecordingState() == AudioRecord.RECORDSTATE_RECORDING) {
    int bytesRead = audioRecorder.read(buffer, 0, buffer.length);
    if (bytesRead != buffer.length) {
        throw new RuntimeException();
    }
    stream.write(buffer);
}
stream.close();
```

**Comment by cl-6666** [comment]
> 我相信您需要做的是使用样本使用的相同机制。因此您可以使用PushAudioInputStream创建识别器，然后执行以下操作：
> 
> ```java
> audioRecorder 。startRecording（）;
> 
> 字节[]缓冲区= 新 字节[audioRecorderBufferSize]；
> 
> 而（audioRecorder 。 getRecordingState（）==  AudioRecord 。 RECORDSTATE_RECORDING）{
>      INT bytesRead = audioRecorder 。读（缓冲，0，缓冲器。长度）;
>     如果（bytesRead ！=缓冲区。长度）{
>         抛出 新 的RuntimeException（）;
>     }
>     流。写（缓冲区）;
> }
> 流。关闭（）;
> ```

Hello, now I have a problem. The reco.recognized.addEventListener method is sometimes executed, sometimes not. I don’t know what caused it. The reco.recognizing.addEventListener method is executed every time, but there is no punctuation in the result. Now The realization is a single recognition, I also posted the code


`  public void streamingRecognition(String language) {
        content.clear();
        speechConfig.setSpeechRecognitionLanguage("zh-CN");
        audioInputStream = PushAudioInputStream.create();
        audioInput = AudioConfig.fromStreamInput(audioInputStream);
        reco = new SpeechRecognizer(speechConfig, audioInput);
        reco.recognizing.addEventListener((o, speechRecognitionResultEventArgs) -> {
            final String s = speechRecognitionResultEventArgs.getResult().getText();
            Log.i("TAG", "Intermediate result received: " + s);
            content.add(s);
            content.remove(content.size() - 1);
        });

        reco.recognized.addEventListener((o, speechRecognitionResultEventArgs) -> {
            Log.i("TAG", "recognized: " + speechRecognitionResultEventArgs.getResult().getText());
        });

        reco.canceled.addEventListener((s, e) -> {
            System.out.println("CANCELED: Reason=" + e.getReason());
            if (e.getReason() == CancellationReason.Error) {
                Log.e("TAG", "CANCELED: ErrorCode=" + e.getErrorCode());
                Log.e("TAG", "CANCELED: ErrorDetails=" + e.getErrorDetails());
                Log.e("TAG", "CANCELED: Did you update the subscription info?");
            }

        });

        reco.startContinuousRecognitionAsync();
//        final Future<Void> task = reco.startContinuousRecognitionAsync();
//        setOnTaskCompletedListener(task, result -> {
//
//        });
    }

    public void streamingResults(byte[] bytes, boolean isLast, boolean frontPoint) {
        if (frontPoint) {
            if (identifyCallback != null) {
                identifyCallback.onNext(InternalConfig.VOICE_CODE);
            }
            return;
        }
        audioInputStream.write(bytes);

        if (isLast) {
            if (identifyCallback != null) {
                identifyCallback.onNext(content.toString());
            }
        }
    }`

**Comment by cl-6666** [comment]
> What I believe you need to do is to use that same mechanism that sample uses; so you would create your recognizer using a PushAudioInputStream and do something like:
> 
> ```java
> audioRecorder.startRecording();
> 
> byte[] buffer = new byte[audioRecorderBufferSize];
> 
> while (audioRecorder.getRecordingState() == AudioRecord.RECORDSTATE_RECORDING) {
>     int bytesRead = audioRecorder.read(buffer, 0, buffer.length);
>     if (bytesRead != buffer.length) {
>         throw new RuntimeException();
>     }
>     stream.write(buffer);
> }
> stream.close();
> ```

Hello, now I have a problem. The reco.recognized.addEventListener method is sometimes executed, sometimes not. At this time, my microphone has ended, and there is no print result in the log. I don’t know what caused it, reco.recognizing. The addEventListener method is executed every time, but there is no punctuation in the result. Now it is a single recognition. I also posted the code.


```
   public void streamingRecognition(String language) {
        content.clear();
        speechConfig.setSpeechRecognitionLanguage("zh-CN");
        audioInputStream = PushAudioInputStream.create();
        audioInput = AudioConfig.fromStreamInput(audioInputStream);
        reco = new SpeechRecognizer(speechConfig, audioInput);
        reco.recognizing.addEventListener((o, speechRecognitionResultEventArgs) -> {
            final String s = speechRecognitionResultEventArgs.getResult().getText();
            Log.i("TAG", "Intermediate result received: " + s);
            content.add(s);
            content.remove(content.size() - 1);
        });

        reco.recognized.addEventListener((o, speechRecognitionResultEventArgs) -> {
            Log.i("TAG", "recognized: " + speechRecognitionResultEventArgs.getResult().getText());
        });

        reco.canceled.addEventListener((s, e) -> {
            System.out.println("CANCELED: Reason=" + e.getReason());
            if (e.getReason() == CancellationReason.Error) {
                Log.e("TAG", "CANCELED: ErrorCode=" + e.getErrorCode());
                Log.e("TAG", "CANCELED: ErrorDetails=" + e.getErrorDetails());
                Log.e("TAG", "CANCELED: Did you update the subscription info?");
            }

        });

        reco.startContinuousRecognitionAsync();
//        final Future<Void> task = reco.startContinuousRecognitionAsync();
//        setOnTaskCompletedListener(task, result -> {
//
//        });
    }

    public void streamingResults(byte[] bytes, boolean isLast, boolean frontPoint) {
        if (frontPoint) {
            if (identifyCallback != null) {
                identifyCallback.onNext(InternalConfig.VOICE_CODE);
            }
            return;
        }
        audioInputStream.write(bytes);

        if (isLast) {
            if (identifyCallback != null) {
                identifyCallback.onNext(content.toString());
            }
        }
    }
```

**Comment by yulin-li** [comment]
Hi @cl-6666 I translated the issue title to English to make it more convenient, fell free to update it.

**Comment by glecaros** [comment]
Hi @cl-6666. from the behavior you are describing I wonder if you are sending enough audio for the service to detect the end of speech. Maybe you can keep your microphone open a bit longer (or try sending a few frames filled with 0's so they are identified as silence)
