### ISSUE TITLE
The method recognize_once_async of the intent_recognizer is blocking the thread

### ISSUE THREAD

**Issue by LukasEdl** [Azure-Samples/cognitive-services-speech-sdk#1058]
**Describe the bug**
When i try to run method `recognize_once_async` of the IntentRecognizer-classthe the code after that is blocked until the intent is recognized or the recognition is canceled. However, it should not block the thread and run the code afterwards.

**To Reproduce**
Here is code to reproduce the error. I am using Pyhton 3.6 64-Bit and version 1.16.0 of azure-cognitiveservices-speech.

```
import azure.cognitiveservices.speech as speechsdk
class Luis():

    intent_recognizer = None
    done = False
    def recognized_cb(self, evt):
        result = evt.result
        print(result.reason)
        print(result.text)

        self.done = True
        if result.reason == speechsdk.ResultReason.RecognizedKeyword:
            print("RECOGNIZED KEYWORD: {}".format(result.text))
    def canceled_cb(self, evt):
        print('cancel')
        result = evt.result
        print(result.reason)

        self.done = True
        if result.reason == speechsdk.ResultReason.Canceled:
            print("CANCELED: {}".format(result.cancellation_details.reason))

    def run(self):
        print('Start setting up luis intent recognition')
        app_id = 'app_id'
        model = speechsdk.intent.LanguageUnderstandingModel(app_id=app_id)
        speech_key, service_region = "speech_key", "westeurope"
        intent_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region,
                                               speech_recognition_language='de-DE')

        self.intent_recognizer = speechsdk.intent.IntentRecognizer(speech_config=intent_config)
        self.intent_recognizer.add_all_intents(model)
        self.intent_recognizer.recognized.connect(self.recognized_cb)
        self.intent_recognizer.canceled.connect(self.canceled_cb)
        print('Luis intent recognition successful initialized')
        print('Waiting for hot word detection')
        print('start recording')
        self.intent_recognizer.recognize_once_async()
        i = 0
        while not self.done:
            i = i + 1
            print(f'concurrent {i}')

Luis().run()
```

**Expected behavior**
After the call `self.intent_recognizer.recognize_once_async()`, the code should run into the while loop and execute it until an intent is recognized or the recognition is canceled.

**Version of the Cognitive Services Speech SDK**
1.16.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 64-Bit
 - Hardware - x64
 - Programming language: Python 3.6 64-Bit

**Additional context**
 - No error message is shown

**Comment by glecaros** [comment]
Hi @LukasEdl, can you try storing the future returned by the async method?
```python
future = self.intent_recognizer.recognize_once_async()
...
future.get()
```

**Comment by LukasEdl** [comment]
Hi @glecaros storing it was the solution. As long as the return value is kept in the current method it works, however if i put it in a variable and the return the function without returnging the variable it starts blocking the thread again.

**Comment by glecaros** [comment]
Hi @LukasEdl,

What happens is that when that future goes out of scope (no references are kept) the destructor gets called and that implicitly gets the future.

I'll close the issue, feel free to reopen if you need further help.

**Comment by LukasEdl** [comment]
Hi @glecaros,
thank you for the information. Maybe this information could be added to the documentation. Im sure that would be helpful for others as well.

**Comment by glecaros** [comment]
I'll bring it up to the team.
