### ISSUE TITLE
Python Speech SDK support for ARM64

### ISSUE THREAD

**Issue by isthistechsupport** [Azure-Samples/cognitive-services-speech-sdk#1060]
The Speech SDK on ARM64 has gradually added support for more and more languages. Is Python on the roadmap as well? Given how Python is a huge part of programming on a Raspberry Pi, it's inconvenient that we can't use it for Speech on Pi development, and it'd make a great addition

**Comment by glecaros** [comment]
Hi @isthistechsupport,
Thank you for reaching out! We do have a backlog item that covers this. I'll add your request to it as a data point so the team has more information when scheduling it.

**Comment by amitkumarshukla** [comment]
@isthistechsupport We are closing the request at this point of time. Please look at the https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/releasenotes for the latest release notes. Thanks a lot

**Comment by oscholz** [comment]
reopening it and marking it as accepted so that @isthistechsupport will get notified when we address this.

**Comment by pankopon** [comment]
Closing this item because it is a feature request for which we have no ETA at the moment, therefore it doesn't seem reasonable to keep the issue open indefinitely. Please keep an eye on Speech SDK release notes for updates on this topic.
