### ISSUE TITLE
Segmentation fault if "SPEECH-StopRecognitionTimeoutInSeconds" is set to zero (0)

### ISSUE THREAD

**Issue by santoojoshi** [Azure-Samples/cognitive-services-speech-sdk#1061]
Describe the bug
Segmentation fault if SPEECH-StopRecognitionTimeoutInSeconds is set to 0. If set to 1 sec, it works fine.

To Reproduce

Run a Speech To Text continuous recognition

Expected behavior
StopContinuousRecognitionAsync() should stop recognition immediately.

Version of the Cognitive Services Speech SDK
1.16.0

Platform, Operating System, and Programming Language

OS: CentOS Linux release 7.7.1908
Hardware - x64, x86, ARM, ...
Programming language: C++
Additional context

We are experiencing segmentation fault in load runs of continuous speech recognition in SpeechSDK.  Load is of 200 concurrent continuous speech recognition. Load is run on a k8s environment with multiple pods having 4core CPU and  3GB memory each.
 
Each successful recognition is for 25 sec and for few recognitions are stopped  at 15th seconds using following methods:

Following Configurations are used
recog_channel->azureASRChannelConfig.azureASRSpeechConfig->SetProperty("SPEECH-USPPollingInterval", "300");
recog_channel->azureASRChannelConfig.azureASRSpeechConfig->SetProperty("SPEECH-BytesPerFrame", "4800");
recog_channel->azureASRChannelConfig.azureASRSpeechConfig->SetProperty("BufferDataSizeInBytes", "32000");
**recog_channel->azureASRChannelConfig.azureASRSpeechConfig->SetProperty("SPEECH-StopRecognitionTimeoutInSeconds", "0");**

recog_channel->azureASRChannelConfig.azureSpeechRecognizer->StartContinuousRecognitionAsync().wait();
 
   recog_channel->azureASRChannelConfig.azureSpeechRecognizer->StopContinuousRecognitionAsync();
 
   recog_channel->azureASRChannelConfig.azureSpeechRecognizer.reset();
   recog_channel->azureASRChannelConfig.azureAudioConfig.reset();
   recog_channel->azureASRChannelConfig.azurePushAudioInputStream.reset();
   recog_channel->azureASRChannelConfig.azureASRSpeechConfig.reset();
 

Please find attached core dump
[segfault.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6404320/segfault.txt)

**Comment by santoojoshi** [comment]
> Hi @santoojoshi,
> 
> Thanks for contacting us! That parameters is not intended to be changed and is set to a value that matches when (P99) an actual service timeout happened. What are you trying to accomplish by changing the timeout value?

Hi @glecaros 
This is a server implementation where we support many calls at the same time with 300 concurrent callers or more. 
We are running a multi threaded architecture where in each thread service a caller. After Speech end detected, StopContinuousRecognitionAsync() takes long time for completion. We are suggested from azure team to use SPEECH-StopRecognitionTimeoutInSeconds, which is available from release 1.14.   So we are using this variable to finish the call immediately and release the thread. 
But with value of 0, we are facing crashes. But with value of 1 its fine.

**Comment by amitkumarshukla** [comment]
@santoojoshi We recommend not using 0 as value for "SPEECH-StopRecognitionTimeoutInSeconds". Please use 1 as value and as you have already confirmed that there is no segmentation fault. Also let us know the source from where you have received the recommendation about using the 0 value. We would like to correct that.

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
