### ISSUE TITLE
Unity CloudBuild Build fails if using multiple platforms. 

### ISSUE THREAD

**Issue by Tiger-Cross** [Azure-Samples/cognitive-services-speech-sdk#1062]
**Describe the bug**
When creating a Unity CloudBuild target for a project that uses this SDK, the build fails and produces the message `error CS0234: The type or namespace name 'CognitiveServices' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)`

This is because the `Microsoft.CognitiveServices.Speech.csharp.dll` file for each platform conflicts.  As a quick workaround folders must be deleted for other build platforms. I.e. if you are building for android, you must delete the IOS and WSP folders otherwise the build will error. This does not fix the bug permanently however. For that, the .dll's should be re-named, e.g. with _android, _ios and _wsp.

**To Reproduce**
1. Create a new Unity project and an associated Git repository. 
2. Import the Azure Speech SDK for Unity and commit to the git repo (may need to use Git-lfs for large files)
3. Set up CloudBuild for the selected project either in the Unity Editor or on the Dashboard.
4. Trigger a build to run.

**Expected behavior**
The build will run for some time and then fail with the previously mentioned error message.

**Version of the Cognitive Services Speech SDK**

1.16.0 as linked in the README [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/unity/from-microphone).

**Platform, Operating System, and Programming Language**
 - Unity CloudBuild

**Additional context**
 - N/A

**Comment by jhakulin** [comment]
@Tiger-Cross Thanks for the report and sorry for the problem with Unity Cloud build. I will create workitem to fix this, I believe the issue is with the library metafiles. Could you comment if it helps if you copy Microsoft.CognitiveServices.Speech.csharp.dll under each platform (Android, iOS, WSA, x86, x86_64) and tag the each copy to target the specific platform only?

**Comment by Tiger-Cross** [comment]
that's OK! the issue isn't blocking me right now (since I used the workaround suggested) I just wanted to help it get resolved for others. When trying to add tags for a DLL it's not the same process as for a prefab or GameObject in the hierarchy. Do you mean I need to select the icon in the bottom right corner of the screenshot below?

![image](https://user-images.githubusercontent.com/33670466/116737218-dd957b00-a9e8-11eb-9b8e-d83e11ea57dc.png)

**Comment by jhakulin** [comment]
@Tiger-Cross Yes, I did some modifications to meta files. Could you please try with the meta files attached here ?
[Plugins.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6408219/Plugins.zip)

**Comment by Tiger-Cross** [comment]
@jhakulin I'm sorry but I tried doing both of the actions you suggested: 1. Adding tags to the assets, and 2. Using the linked plugin folder with updated meta files (copying the x86_64 dll to the WSA folder).  

1. The CloudBuild still resulted in the same error as logged in the initial issue comment.
2. Caused the following error in the editor: 
`PrecompiledAssemblyException: Multiple precompiled assemblies with the same name Microsoft.CognitiveServices.Speech.csharp.dll included or the current platform. Only one assembly with the same name is allowed per platform. Assembly paths: 
Assets/SpeechSDK/Plugins/x86_64/Microsoft.CognitiveServices.Speech.csharp.dll
Assets/SpeechSDK/Plugins/WSA/Microsoft.CognitiveServices.Speech.csharp.dll`
Which I assume is because you asked me to copy the dll across? Did you mean I should just move it instead?

**Comment by jhakulin** [comment]
@Tiger-Cross Meta files should prevent collision between WSA and x86_64, did you do following ?

1. Copy Microsoft.CognitiveServices.Speech.csharp.dll from \Plugins\x86_64 folder to \Plugins\WSA folder
2. Replace all meta files under /Plugins from Plugins.zip
3. Make a build again

**Comment by Tiger-Cross** [comment]
@jhakulin I can confirm those are the steps that I took. Although I did 1. and 2. the opposite way around to what you suggested because otherwise the copying would have been overwritten.

**Comment by jhakulin** [comment]
@Tiger-Cross Could you please send a picture of Unity inspector for both /x86_64/Microsoft.CognitiveServices.Speech.csharp.dll and WSA/Microsoft.CognitiveServices.Speech.csharp.dll ?

**Comment by Tiger-Cross** [comment]
@jhakulin of course. Also to make this absolutely clear, I'm not seeing this error on a local unity build. Only when a commit gets pushed to the master branch of my project and a CloudBuild is triggered.

Here's the screenshot for the x86_64 dll:

![image](https://user-images.githubusercontent.com/33670466/116811326-a2a65b00-ab40-11eb-9331-2679afa9776a.png)

And here's the one from the WSA dll:

![image](https://user-images.githubusercontent.com/33670466/116811336-b487fe00-ab40-11eb-824b-3ef3dffc2d74.png)

**Comment by Tiger-Cross** [comment]
I've also just noticed that when using the META files from the plugins folder you zipped and sent earlier I see this error in the Unity Editor:
`Unable to open Assets/SpeechSDK/Plugins/x86_64/Microsoft.CognitiveServices.Speech.csharp.dll: Check external application preferences.`

**Comment by jhakulin** [comment]
@Tiger-Cross What is the Unity version you have ? Have you installed iOS and/or UWP support ? 
The settings are not correct. What you should have for example for x86_64 is following
![image](https://user-images.githubusercontent.com/16473503/116897699-6cbdb100-abea-11eb-8e73-e1f50c462130.png)

And for WSA (when using the meta files I sent as zip attachment)
![image](https://user-images.githubusercontent.com/16473503/116897997-bad2b480-abea-11eb-9c5b-a0182c4d3152.png)

**Comment by Tiger-Cross** [comment]
@jhakulin I am using Unity 2019.4.19 and on my CloudBuild whatever the lastest 2019.4 subversion is. I should add that my build target is for android so I do not need IOS or UWP support in this case.

**Comment by jhakulin** [comment]
@Tiger-Cross Could be that because you have not installed iOS and UWP support, Unity do not know how to map the libraries for iOS and Windows from Speech SDK unity package and thus you need to either remove or rename the libraries. I'll check if there is something we can do to make it easier.

**Comment by Tiger-Cross** [comment]
@jhakulin that would be really helpful thanks! It's not possible (to the best of my knowledge) to install those configurations while specifying a different build target. For now I'll continue to use the temporary solution I mentioned which was the deletion of the IOS and UWP libraries.

**Comment by Tiger-Cross** [comment]
@jhakulin I should also add that I am not the only one experiencing this issue. I voiced this issue on a slack group with many Unity developers and I heard from others that have also run into it. This is how I heard of the initial workaround.

**Comment by jhakulin** [comment]
@Tiger-Cross Since Speech SDK Unity plugin contains libraries for Windows/iOS/Android platforms (and in next release also for Mac) and meta files are used to target the libraries to specific platforms/architectures, if Unity installation does not include the all platforms, meta files do not provide the purpose. We can add note in our documentation for Unity CloudBuild in the coming release.

**Comment by Tiger-Cross** [comment]
That's great thanks a lot!
