### ISSUE TITLE
Android build size increased three times.

### ISSUE THREAD

**Issue by ranjanraviraj** [Azure-Samples/cognitive-services-speech-sdk#1063]
**Describe the bug**
Before integrating speech service my APK build size was around 24 MB in release mode. I have used these properties in release mode.

**release {
    debuggable = false
    minifyEnabled true
    shrinkResources true
    proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }**

But after integrating Speech service version **com.microsoft.cognitiveservices.speech:client-sdk:1.16.0** APK build size drastically increased to 80 MB. 

Is there any way to reduce the size?

**Expected behavior**
APK size shouldn't increase to more than three times. 

**Version of the Cognitive Services Speech SDK**
com.microsoft.cognitiveservices.speech:client-sdk:1.16.0

**Platform, Operating System, and Programming Language**
 - OS: Android
 - Programming language: Kotlin

**Comment by amitkumarshukla** [comment]
@ranjanraviraj Please let me know if your scenario is a compressed audio scenario ? Did you build libgstreamer_android.so also and put it with the app ?

**Comment by ranjanraviraj** [comment]
> @ranjanraviraj Please let me know if your scenario is a compressed audio scenario ? Did you build libgstreamer_android.so also and put it with the app ?

The answer is no. We are not using any compressed audio or libstreamer. If you are asking this capability is there in SDK that I need to turn off then I am not aware of how to do that.

**Comment by amitkumarshukla** [comment]
@ranjanraviraj I tried all your settings and for me the size do not get increased much. Could you please unzip the apk and send me the content and size of lib\* folders 
for example for me for arm64-v8a I have the following 
![image](https://user-images.githubusercontent.com/36176886/117049694-58041a80-acc9-11eb-88d5-abb7cc4bbc54.png)

**Comment by amitkumarshukla** [comment]
@ranjanraviraj have you figured out the size issue after unzipping the apk ?

**Comment by ranjanraviraj** [comment]
> @ranjanraviraj have you figured out the size issue after unzipping the apk ?

These libraries inside the lib folder that you mentioned. 

![image](https://user-images.githubusercontent.com/55788218/117325404-50519b00-aeae-11eb-9474-1040bd02a400.png)

Hope this is helpful.

**Comment by amitkumarshukla** [comment]
@ranjanraviraj the first 3 files in your list is it added by you ?

**Comment by ranjanraviraj** [comment]
> @ranjanraviraj the first 3 files in your list is it added by you ?

Yes. It was added long back. That time apk size was around 24 MB. But after adding speech sdk size went till 79 MB. I tried to remove unused resources but it was of no much use.

**Comment by amitkumarshukla** [comment]
@ranjanraviraj Could you please check the APK size with different version of speech sdk and let me know your observation. Because my assumption is there is no way the size will be so big. If you add SpeechSDK to any project the max increase in the apk size should be approx 15mb.

**Comment by ranjanraviraj** [comment]
> @ranjanraviraj Could you please check the APK size with different version of speech sdk and let me know your observation. Because my assumption is there is no way the size will be so big. If you add SpeechSDK to any project the max increase in the apk size should be approx 15mb.

Started with version 1.14.0 then 1.15.0 and last 1.16.0. All versions have same results. I will try once more and share results again.

**Comment by amitkumarshukla** [comment]
@ranjanraviraj I will suggest, please disable speech functionality and comment the code related to that and check the APK size to see how much is the base size of your APK.

**Comment by ranjanraviraj** [comment]
> @ranjanraviraj I will suggest, please disable speech functionality and comment the code related to that and check the APK size to see how much is the base size of your APK.

As suggested I disable functionality related to Speech Service and the size reduced to 36 MB. 

![image](https://user-images.githubusercontent.com/55788218/117415327-d06f1380-af35-11eb-88c4-1b45c1337ed7.png)
And library information 

![image](https://user-images.githubusercontent.com/55788218/117415595-1cba5380-af36-11eb-85c3-f660d993e154.png)

**Comment by amitkumarshukla** [comment]
@ranjanraviraj I can see the size reduction without speech sdk is 44mb. Could it be possible for you to send us an android studio project with some sample code where I can try to see the issue myself locally. When switching on and off speech SDK does this behavior. Because in my sample app I can see the difference of only 15mb.

**Comment by amitkumarshukla** [comment]
@ranjanraviraj Please share a sample project which can show us the same issue you are facing.

**Comment by jhakulin** [comment]
@ranjanraviraj When you unzip and look into your .apk file, which architectures you see there under lib directory ?

If you want that your apk contains only e.g. arm64-v8a architecture, please specify that in your app/build.gradle file, 
see example below

```
    flavorDimensions 'cpuArch'
    productFlavors {
        arm8 {
            dimension 'cpuArch'
            ndk {
                abiFilters 'arm64-v8a'
            }
        }
    }
```

Otherwise, without specifying the above, the .apk file contains all flavors "arm64-v8a", "armeabi-v7a", "x86" and "x86_64" and that increases your .apk size.

**Comment by ranjanraviraj** [comment]
> @ranjanraviraj When you unzip and look into your .apk file, which architectures you see there under lib directory ?
> 
> If you want that your apk contains only e.g. arm64-v8a architecture, please specify that in your app/build.gradle file,
> see example below
> 
> ```
>     flavorDimensions 'cpuArch'
>     productFlavors {
>         arm8 {
>             dimension 'cpuArch'
>             ndk {
>                 abiFilters 'arm64-v8a'
>             }
>         }
>     }
> ```
> 
> Otherwise, without specifying the above, the .apk file contains all flavors "arm64-v8a", "armeabi-v7a", "x86" and "x86_64" and that increases your .apk size.

Thanks for the update. Please find all folder details in unzip folder of APK. According to your solution, I can avoid other folders being part of the build?

See current folder structure. 
![image](https://user-images.githubusercontent.com/55788218/118682685-4caf0400-b81e-11eb-960a-2d72894d083d.png)

**Comment by jhakulin** [comment]
@ranjanraviraj Yes, you can target the apk for the architectures which are needed by your customers only.

**Comment by jhakulin** [comment]
Closing the issue as answered, let us know if there is more information needed.

**Comment by hiddow** [comment]
APK size increase about 8MB @jhakulin  ，any idea to reduse the SDK size?
