### ISSUE TITLE
Foreign Voicename's Throw Errors in Unity

### ISSUE THREAD

**Issue by Wholebitmedia** [Azure-Samples/cognitive-services-speech-sdk#1064]
**Describe the bug**

I am using the documentation found on this page:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support

...To substitute the default "enUSJessaRUS" speech synethesis into one of the foreign "Standard Voices"(specifically "ja-JP-Ayumi") in the "Voicename voicename" variable field in the "Speech Recognition" 3 language translation scene inside the Unity C# "Speech Recognition" script.

**To Reproduce**

1. Load the  Speech Recognition scene into Unity and enter the Azure cognitive service credentials.
2. Voicename should be assigned in the Start() section.  
 voiceName = VoiceName.enUSJessaRUS;
to
 voiceName = VoiceName.VoiceName.ja-JP-Ayumi;
3. Throws error for change of voice in the compiler.  Eliminating hyphens does not fix this.

**Expected behavior**-3 errors in console...

--Assets\Cogntive Services\speech\SpeechSDKSample\Scripts\SpeechRecognition.cs(132,34): error CS0103: The name 'JP' does not exist in the current context

--Assets\Cogntive Services\speech\SpeechSDKSample\Scripts\SpeechRecognition.cs(132,34): error CS0103: The name 'jp' does not exist in the current context

--Assets\Cogntive Services\speech\SpeechSDKSample\Scripts\SpeechRecognition.cs(132,34): error CS0103: The name 'Ayumi' does not exist in the current context

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

All latest versions of cogservices and this project

Windows 10u x64 C# Unity 2020.3.4f

**Comment by amitkumarshukla** [comment]
@yulin-li Could you please look at this.

**Comment by yulin-li** [comment]
@Wholebitmedia , thanks for reaching out. Could you point me the sample codes you are using? I didn't find any our codes containing `voiceName = VoiceName.enUSJessaRUS`

**Comment by yulin-li** [comment]
@Wholebitmedia , as said [here](https://github.com/Azure-Samples/Cognitive-Speech-TTS/tree/master/Samples-Http), the samples in `Cognitive-Speech-TTS` is not supported. Could you try to use the Unity sample in this repo?

**Comment by Wholebitmedia** [comment]
Both LUIS and REST have been depreciated and there are no updated implementation examples for C# or Unity beyond the link I posted.  The Speech SDK documentation does not specify any updated C# code examples for the voicename field.

**Comment by yulin-li** [comment]
voice name is actually a string, you can find all voices [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/unity).
And, you can refer to the unity sample codes https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/unity

**Comment by Wholebitmedia** [comment]
Entering in the foreign text gives this error in the console.  There is only one voice in this system.

ArgumentException: Length of created clip must be larger than 0
UnityEngine.AudioClip.Create (System.String name, System.Int32 lengthSamples, System.Int32 channels, System.Int32 frequency, System.Boolean stream, UnityEngine.AudioClip+PCMReaderCallback

**Comment by pankopon** [comment]
If still needed or helpful (.NET Core C# samples):
- Synthesis with a specific voice
  https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_synthesis_samples.cs#L110
- Get a list of available voices
  https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_synthesis_samples.cs#L820
- Both can be tried out with a sample console app
  https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/csharp/dotnetcore/console

**Comment by jhakulin** [comment]
@Wholebitmedia Please use ja-JP-Ayumi voice name as follows:

1. Use the Unity sample below
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/unity/text-to-speech

2. Add following modification just after speechConfig has been created from subscription
```csharp
            var voice = "Microsoft Server Speech Text to Speech Voice (ja-JP, Ayumi)";
            speechConfig.SpeechSynthesisVoiceName = voice;
```
I verified that works ok. Closing the issue, let us know if there is more problems.

**Comment by Wholebitmedia** [comment]
OK this works, thank you for your help!  :)
