### ISSUE TITLE
Conversation Transcription/Speaker Identification in Python

### ISSUE THREAD

**Issue by soranaka** [Azure-Samples/cognitive-services-speech-sdk#1068]
The documentation here: https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.speech_py_impl.conversation?view=azure-python#create-conversation-async ,
Does not list enough information for me to understand how to go about creating a Conversation object. By following the general structure found here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-conversation-transcription?pivots=programming-language-csharp , I wrote 
`conversation = Conversation.create_conversation_async(speech_config,'id').get()`

Which logs `in method 'Conversation_create_conversation_async', argument 1 of type 'SpeechConfigPtr' `

Does anyone know or have advice on what I should be doing to get conversation transcription working in Python?

**Comment by amitkumarshukla** [comment]
@soranaka Thanks a lot for reporting this issue. Right now conversation transcription is not supported in python language. We support it in C++, C#, Java and Objective C. If you have a choice for using any of the supported language please use that. We will go and remove the documentation for conversation transcription from the official docs. We will re-introduce those documentation once we support conversation transcription in python. Please check the release notes https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/releasenotes for future releases.

Thanks
