### ISSUE TITLE
RuntimeError: Exception with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED) [CALL STACK BEGIN]

### ISSUE THREAD

**Issue by geniusrasaq** [Azure-Samples/cognitive-services-speech-sdk#1069]
Hello Everyone,

I have been trying to transcribe an audio file from speech to text for a while using cognitive speech sdk but I am getting the error listed below:

RuntimeError: Exception with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED)
[CALL STACK BEGIN]

    > user_get_id

    - user_get_id

    - user_get_id

    - user_get_id

    - user_get_id

    - user_get_id

    - user_get_id

    - user_get_id

    - user_get_id

    - user_get_id

    - user_get_id

    - user_get_id

    - user_get_id

    - user_get_id

    - recognizer_create_speech_recognizer_from_config

    - recognizer_create_speech_recognizer_from_source_lang_config

[CALL STACK END]

I want to transcribe 10,000 large audio files. However, I have been trying to transcribe one audio file with this source code: https://github.com/Azure-Samples/cognitive-services-speech-sdk just to see out it works before passing the 10,000 audio files into the speech API  but it is not working. Kindly help me out regarding this.

Here is the source code: 

def speech_recognize_once_from_file():
    """performs one-shot speech recognition with input from an audio file"""
    # <SpeechRecognitionWithFile>
    speech_config = speechsdk.SpeechConfig(subscription="", region="")
    audio_config = speechsdk.audio.AudioConfig(filename="data/gen.wav")
    # Creates a speech recognizer using a file as audio input, also specify the speech language
    speech_recognizer = speechsdk.SpeechRecognizer(
        speech_config=speech_config, language="en-US", audio_config=audio_config)

    # Starts speech recognition, and returns after a single utterance is recognized. The end of a
    # single utterance is determined by listening for silence at the end or until a maximum of 15
    # seconds of audio is processed. It returns the recognition text as result.
    # Note: Since recognize_once() returns only a single utterance, it is suitable only for single
    # shot recognition like command or query.
    # For long-running multi-utterance recognition, use start_continuous_recognition() instead.
    result = speech_recognizer.recognize_once()

    # Check the result
    if result.reason == speechsdk.ResultReason.RecognizedSpeech:
        print("Recognized: {}".format(result.text))
    elif result.reason == speechsdk.ResultReason.NoMatch:
        print("No speech could be recognized: {}".format(result.no_match_details))
    elif result.reason == speechsdk.ResultReason.Canceled:
        cancellation_details = result.cancellation_details
        print("Speech Recognition canceled: {}".format(cancellation_details.reason))
        if cancellation_details.reason == speechsdk.CancellationReason.Error:
            print("Error details: {}".format(cancellation_details.error_details))
speech_recognize_once_from_file()

**Comment by amitkumarshukla** [comment]
@geniusrasaq The problem you described can only happen when the file is not present in your data folder. Please check if all your paths are correct. The path to the file should be relative to the path where you are running your script.

**Comment by geniusrasaq** [comment]
@amitkumarshukla , thank you so much for your reply. Actually, the audio file "gen" is inside the folder data.

**Comment by amitkumarshukla** [comment]
Could you send me the zip of your folder with everything inside. I will try to check this at my end.

**Comment by amitkumarshukla** [comment]
@geniusrasaq Could you send me the .py code rather than .ipynb

**Comment by geniusrasaq** [comment]
@amitkumarshukla , here is the updated folder with .py file.
[microsoft_speech_to_text_plus .py file.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6444479/microsoft_speech_to_text_plus.py.file.zip)

thank you

**Comment by geniusrasaq** [comment]
@amitkumarshukla , I am still having the same error.

**Comment by amitkumarshukla** [comment]
@geniusrasaq I just modified your sample a bit and to me it works absolutely fine. You need to install python wheel for speech sdk on your system. 

```py
#!/usr/bin/env python
# coding: utf-8

import time
import wave
import string
import base64
import pyaudio


# In[ ]:


# get_ipython().system('pip install requests')
# get_ipython().system('pip install azure-cognitiveservices-speech')
try:
    import azure.cognitiveservices.speech as speechsdk
except ImportError:
    print("""
    Importing the Speech SDK for Python failed.
    Refer to
    https://docs.microsoft.com/azure/cognitive-services/speech-service/quickstart-python for
    installation instructions.
    """)
    import sys
    sys.exit(1)


def speech_recognize_continuous_from_file():
    """performs continuous speech recognition with input from an audio file"""
    # <SpeechContinuousRecognitionWithFile>
    speech_config = speechsdk.SpeechConfig(subscription="....", region="....")
    audio_config = speechsdk.audio.AudioConfig(filename="data/gen.wav")

    print('reco : ')
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)

    done = False

    def stop_cb(evt):
        """callback that signals to stop continuous recognition upon receiving an event `evt`"""
        print('CLOSING on {}'.format(evt))
        nonlocal done
        done = True

    # Connect callbacks to the events fired by the speech recognizer
    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
    speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))
    # stop continuous recognition on either session stopped or canceled events
    speech_recognizer.session_stopped.connect(stop_cb)
    speech_recognizer.canceled.connect(stop_cb)
    
    # Start continuous speech recognition
    speech_recognizer.start_continuous_recognition()
    while not done:
        time.sleep(.5)

    speech_recognizer.stop_continuous_recognition()

speech_recognize_continuous_from_file()

```

Another question what is the python version and platform are you using ?

**Comment by geniusrasaq** [comment]
@amitkumarshukla , thank you so much for your prompt response.
The python version on my system is python 3.8.3 and I am also using windows 8 OS. 
I am running my code on jupyter notebook

**Comment by amitkumarshukla** [comment]
@geniusrasaq Oh. Actually we do not support Speech SDK on windows 8. Please upgrade it to windows 10. Your problem will be solved.

**Comment by geniusrasaq** [comment]
@amitkumarshukla , oh my bad. I'm actually using windows 10

**Comment by amitkumarshukla** [comment]
@geniusrasaq Did you try the sample which I provided you ?

**Comment by amitkumarshukla** [comment]
@geniusrasaq Could you also send me the screen shot of the command prompt where you have the code and where you are running the code.

**Comment by jhakulin** [comment]
@geniusrasaq I tested the sample @amitkumarshukla provided works well in Windows with the standard python shell or under Jupyter Notebook terminal. With Jupyter Notebook, please make sure your data/gen.wav file is included in the project. This should be done automatically when you run "jupyter notebook" command on the command prompt (Windows) in the root directory which contains the python script and gen directory with audio samples. Closing the issue as answered, let us know if you have any other issues.

**Comment by geniusrasaq** [comment]
@amitkumarshukla ,The code is working now. Thanks.
