### ISSUE TITLE
TypeInitializationException in aspnet core and docker

### ISSUE THREAD

**Issue by vermegi** [Azure-Samples/cognitive-services-speech-sdk#107]
**Describe the bug**
I have a working example using the C# Speech SDK in a .Net Core Console app. 

However if I dockerize this application and then run it inside the container I get a TypeInitializationException on Microsoft.CognitiveServices.Speech.csharp.bindings.dll. 

If I create the same application as a aspnet core app, I also get the same exception. 

I already installed the C++ redistributable package and changed the target platform from Any CPU. 

I also tried adding ksuser.dll, mf.dll, mfcore.dll, mfplat.dll, mfreadwrite.dll to my output directory, this didn't help either. 

**To Reproduce (.Net Core + docker)**
1. Create a new .Net Core console app
2. Add latest Speech SDK nuget package
3. Add line for speech config setup (basic speech SDK sample)
4. Run the code --> all works fine
5. add docker support 
6. Run same sample from docker container --> throws exception

**To Reproduce (aspnet core)**
1. Create a new aspnet core app
2. Add latest Speech SDK nuget package
3. Add api controller and get/post method in which you config the speech SDK
4. Run the code and call your api endpoint through postman --> throws exception

**Expected behavior**
find the missing DLL's 

**Version of the Cognitive Services Speech SDK**
1.1.0

**Platform, Operationg System, and Programming Language**
 - OS: Windows Server 2016 Datacenter
 - Hardware - x64 

**Additional context**
 - Error messages: 

DllNotFoundException: Unable to load DLL &#x27;Microsoft.CognitiveServices.Speech.csharp.bindings.dll&#x27; or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE&#x2B;SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_carbon_csharp(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)

**Comment by mahilleb-msft** [comment]
Hi @vermegi,

  maybe first thing to check is that you're not trying to use the microphone, because this will not work from inside the container.

  Recognition from other sources (here: file), I've just successfully tried based on our `samples/csharp/dotnetcore/console` sample:

1. Configure subscription key / region according to the sample README and build the solution in Visual Studio.
2. Right-click on the **samples** project, select **Publish...** and publish the app to a folder.
3. For me, the publish folder was `samples/bin/Debug/netcoreapp2.0/publish`, relative to the samples root directory.
4. Add a Dockerfile into the `samples/csharp/dotnetcore/console` folder with the content shown below.
5. Put the VC runtime DLLs into a folder called `vcruntimedlls`.
6. Run `docker build -t dotnettestcore .`
7. Run `docker run --rm -ti dotnettestcore`
8. Within the Docker run: `dotnet samples.dll`
9. Pick option 3 to do continuous recognition from file.

Hope this helps,

Mark

_Dockerfile content_
```
FROM microsoft/dotnet:2.0-runtime
COPY samples/bin/Debug/netcoreapp2.0/publish /app
COPY vcruntimedlls /app
WORKDIR /app
```

**Comment by mahilleb-msft** [comment]
@vermegi - please let us know if this resolves your issue.

**Comment by mahilleb-msft** [comment]
I'm closing this for now, hoping things work for you now. Please feel to re-open if problem persists!

Thanks, Mark

**Comment by vermegi** [comment]
Hi Mahileb,
Sorry for getting back on this so late, but I encountered 2 problems when trying out your sample:

1. the copy for the vcruntimedlls gives an error when building the container. (it is not able to find the file)
2. if I leave out the line for the copy of the vcruntimedlls, then when running dotnet samples.dll with sample 3, it gives the same exception:

Unhandled Exception: System.AggregateException: One or more errors occurred. (The type initializer for 'Microsoft.Cognit
iveServices.Speech.Internal.carbon_csharpPINVOKE' threw an exception.) ---> System.TypeInitializationException: The type
 initializer for 'Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE' threw an exception. ---> System.Type
InitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundExcep
tion: Unable to load DLL 'Microsoft.CognitiveServices.Speech.csharp.bindings.dll': The specified module could not be fou
nd. (Exception from HRESULT: 0x8007007E)
   at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallback
s_carbon_csharp(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZ
eroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalid
OperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryD
elegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE.SWIGExceptionHelper..ctor()
   at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE.SpeechConfig_FromSubscription(String jarg1, Strin
g jarg2)
   at Microsoft.CognitiveServices.Speech.Internal.SpeechConfig.FromSubscription(String subscription, String region)
   at MicrosoftSpeechSDKSamples.SpeechRecognitionSamples.<ContinuousRecognitionWithFileAsync>d__3.MoveNext() in F:\dev\g
ithub\cognitive-services-speech-sdk\samples\csharp\sharedcontent\console\speech_recognition_samples.cs:line 168
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MicrosoftSpeechSDKSamples.Program.Main(String[] args) in F:\dev\github\cognitive-services-speech-sdk\samples\cshar
p\sharedcontent\console\Program.cs:line 38

**Comment by vermegi** [comment]
Yes, excellent, that fixes it! Super thx!

**Comment by anjsha** [comment]
@mahilleb-msft 
**Thanks a ton!** I faced similar issue while running dot net core sample app on docker.
_Microsoft Cognitive Speech SDK version 1.11.0_
