### ISSUE TITLE
Silence between keyword recognition and PhraseListGrammar sentence

### ISSUE THREAD

**Issue by crazyracer98** [Azure-Samples/cognitive-services-speech-sdk#1070]
**Describe the bug**
The silence time between keyword recognition and sentences from PhraseListGrammar with SpeechRecognizer.startKeywordRecognitionAsync() is too short. (Android, Java)
If the user says the keyword, then waits for showUiAppIsListening() (look code below) and then tries to say the rest of the sentence, the recognition is only active for under one second and no speech gets recognized.
Previous issue was #950.

**To Reproduce**
```java
SpeechConfig speechConfig = SpeechConfig.fromSubscription(azure_subscription_key, azure_subscription_region);
AudioConfig audioConfig = AudioConfig.fromDefaultMicrophoneInput();
SpeechRecognizer speechRecognizer = new SpeechRecognizer(speechConfig, audioConfig);
PhraseListGrammar phraseListGrammar = PhraseListGrammar.fromRecognizer(speechRecognizer);
InputStream inputStream = activity.getAssets().open(getKeywordFile());
KeywordRecognitionModel keywordRecognitionModel = KeywordRecognitionModel.fromStream(inputStream, "hey computer", false);
inputStream.close();

speechRecognizer.recognizing.addEventListener((o, speechRecognitionEventArgs) -> {
    showUiAppIsListening(true);
}
speechRecognizer.recognized.addEventListener((o, speechRecognitionEventArgs) -> {
    parsePhrase(speechRecognitionEventArgs.getResult().getText());
    showUiAppIsListening(false);
}
phraseListGrammar.addPhrase("hey computer send message to peter");
phraseListGrammar.addPhrase("hey computer recover state of instrument");
// ...many other phrases
speechRecognizer.startKeywordRecognitionAsync(keywordRecognitionModel);
```
1. Say keyword ("hey computer")
2. Wait for UI change from showUiAppIsListening(boolean)
3. Say sentence ("send message to peter")

**Expected behavior**
Someone (a user) not familiar with the recognition expects the app to behave like Alexa, Hey Google, or Siri and waits for the keyword to be recognized by the app, then proceeds to say the full sentence.
Also, in a noisy environment the keyword only gets recognized 75% of the time which why this is important.

**Version of the Cognitive Services Speech SDK**
1.16.0

**Platform, Operating System, and Programming Language**
 - OS: Android 6.0.1
 - Hardware - ARM
 - Programming language: Java

**Additional context**
Logs in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/950#issuecomment-784965678.

**Comment by pankopon** [comment]
Hi, unfortunately the silence timeout between keyword and speech recognition remains not adjustable. I've created an internal feature work item about this and it will be considered for future releases. Closing the issue, we'll update this when the release schedule is known.

**Comment by tripfish** [comment]
Is there any news?

**Comment by pankopon** [comment]
Unfortunately no news, sorry. It is actually possible to control the timeout with [Embedded Speech](https://aka.ms/embedded-speech) but not when using cloud speech services as here.

**Comment by pankopon** [comment]
Internal work item ref. 3521402.
