### ISSUE TITLE
Speaker Diarization Support in Speech SDK

### ISSUE THREAD

**Issue by josephsctan** [Azure-Samples/cognitive-services-speech-sdk#1073]
**Is your feature request related to a problem? Please describe.**
I'm using [Microsoft.CognitiveServices.SpeechRecognizer](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechrecognizer?view=azure-dotnet) which supports Phrase lists ([PhraseListGrammar](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.phraselistgrammar?view=azure-dotnet)) but 
but it does not support  speaker diarization which is only available in the V3 REST API.

The [Create Transcript API](https://centralus.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/operations/CreateTranscription) supports diarization but not Phrase Lists!

I need both.

**Describe the solution you'd like**
Enable Microsoft.CognitiveServices.Speech.SpeechRecognizer to do diarization (multi-speaker please)

**Describe alternatives you've considered**
Merge the output from the Speech SDK and the Speech API ? Yuck.

**Additional context**
Or, enable the Speech API V3 to support Phrase Lists (but prefer to use the SDK!)

**Comment by josephsctan** [comment]
Conversation Transcription requires multi channel audio and a specialized mic setup - it is quite unsuitable  for transcribing mono channel audio that we can get from the browser  
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-devices-sdk-microphone

**Comment by jhakulin** [comment]
@josephsctan Speaker diarization feature is in the Speech SDK plans for future releases during this year.
