### ISSUE TITLE
High variance in latency in speech to text with recognize_once mode 

### ISSUE THREAD

**Issue by gopik** [Azure-Samples/cognitive-services-speech-sdk#1074]
**Describe the bug**
We use ms speech services sdk (nodejs) to do streaming speech to text in recognize_once mode. For some recordings, we experience a huge latency (multiples of seconds even after the entire audio has been pushed). This is a concern since the audio is being pushed at real time rate, so 10seconds worth of audio is pushed in 10 seconds, and the delay is after the entire audio has been pushed.

**To Reproduce**
The attached audio file when transcribed using sdk, takes up to 8 sec after the last chunk is pushed to push stream.
Interestingly this latency is highly variable ranging from 2s to 8s.

**Expected behavior**
Latency after the entire data push should be small and ideally shouldn't be variable. If it's variable due to env (network/cpu etc), we would like to understand and fix.

**Version of the Cognitive Services Speech SDK**
    "microsoft-cognitiveservices-speech-sdk": "^1.13.1"

**Platform, Operating System, and Programming Language**
 - CentOS Linux 8 (Core)
 - x64
 - JavaScript
 - Browser - NA

**Additional context**
SessionId: 41f1324c01a748d5a191da91f82f750c
Recognition mode: RECOGNIZE_ONCE

[otp10sec.wav.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6456460/otp10sec.wav.zip)

**Comment by pankopon** [comment]
@glharper Can you please comment, is this kind of variance expected with nodejs?

**Comment by glharper** [comment]
@gopik What recognizer settings are you using? I'm getting a silence timeout for that file, which starts with 6 seconds of silence. Also, could you upgrade to version 1.16 and try again?

**Comment by gopik** [comment]
We used 72s initial silence timeout for this recording (which looks incorrect and we'll fix this). This was to avoid too many initial silence timeouts occurring in production. The timeout error was inconsistent with the actual silence, say the recording has speech starting from 4th sec and IST was set to 6s, it would still timeout.

We used a phrase_list for this containing following terms - ["completed", "next step", "hello", "nominee", "done", "repeat"]



What's the right way to tune initial silence timeout value? In our scenario, the speech can be at the tail end of the recording. We do have a fixed size of recording duration. Does it make sense to set it as the recording duration it self?

**Comment by gopik** [comment]
[speechatbeginning.wav.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6465920/speechatbeginning.wav.zip)

I've added another instance where speech is at the beginning (first 3 second of a 10 second audio). This was not transcribed until 10 seconds into the audio in our production. But when we try with a test client later, it is transcribed within 3-4 sec from the beginning. We need help debugging the root cause of such issues. Any additional tracing/logging would help resolve this?

**Comment by glharper** [comment]
@gopik I've just tested with the latest version, and am seeing recognizing and recognized callbacks almost immediately without a phraselist. With a phraselist, however, results come much slower. I also tested with the C# version of Speech SDK, and adding a phraselist has the same effect, results arrive about 5x slower. This appears to be a service issue with phraselists.

**Comment by gopik** [comment]
Thanks @glharper. This sounds great, we'll validate this and update.

**Comment by gopik** [comment]
This did improve latency in majority of cases (with less accuracy due to missing phrase_list). But there are still instances which take very long time. I'm adding a sample here. 

We are using base model with no phrase list and initial silence timeout of 72 sec. It takes 4-7 seconds after the eof for recognize event. In this case, the speech is at the end.

[speechatend.wav.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6470599/speechatend.wav.zip)

**Comment by glharper** [comment]
@gopik I'm not seeing the latency you describe with an initial silence timeout of 72 seconds. The recognize result is returning within a couple of seconds for me. Here is the code I'm using:
```
  var sdk = require("microsoft-cognitiveservices-speech-sdk");
  var fs = require("fs");
  
  var filename = "speechatend.wav";
  // replace with your own subscription key,
  // service region (e.g., "westus"), and
  // the name of the file you want to run
  // through the speech recognizer.
  var subscriptionKey = "KEY";
  var serviceRegion = "REGION"; // e.g., "westus"
 
  // now create the audio-config pointing to our stream and
  // the speech config specifying the language.
  var speechConfig = sdk.SpeechConfig.fromSubscription(subscriptionKey, serviceRegion);
  
  // setting the recognition language to English.
  speechConfig.speechRecognitionLanguage = "en-US";
  speechConfig.setProperty(sdk.PropertyId[sdk.PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs], "72000");
  
  //var audioConfig = sdk.AudioConfig.fromStreamInput(pushStream);
  var audioConfig = sdk.AudioConfig.fromWavFileInput(fs.readFileSync(filename), filename);
  
  // create the speech recognizer.
  var recognizer = new sdk.SpeechRecognizer(speechConfig, audioConfig);
  
  recognizer.recognized = (reco, e) => {
    try {
        var res = e.result;
        console.log(`recognized: ${res.text}, json ${res.properties.getProperty(sdk.PropertyId.SpeechServiceResponse_JsonResult)}`);
    } catch (error) {
        console.log(error);
    }
  };
  recognizer.recognizing = (reco, e) => {
    try {
        var res = e.result;
        console.log(`recognizing: ${res.text}, json ${res.properties.getProperty(sdk.PropertyId.SpeechServiceResponse_JsonResult)}`);
    } catch (error) {
        console.log(error);
    }
  };

  console.log("Now recognizing from: " + filename);

  
  // start the recognizer and wait for a result.
  try {
    recognizer.recognizeOnceAsync(
      function (result) {
        console.log(`recognitionResult: ${result}`);
      },
      function (err) {
        console.trace("err - " + err);
      });
    } catch (error) {
        console.log(error);
    }
```

**Comment by gopik** [comment]
Thanks @glharper. Is there additional instrumentation which could be enabled to collect data about this issue (server side or client side)? Given the default concurrency limit is 100, we believe this is not the issue.

**Comment by glharper** [comment]
@gopik The JS SDK does not have a property to get a client-side latency measurement, but the C# SDK does, SpeechServiceResponse_RecognitionLatencyMs. If you are able to reproduce the latency using the [C# from file sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/dotnet/from-file), you can add 
```
       recognizer.Recognized += (s, e) =>
       {
           var resultLatency = e.Result.Properties.GetProperty(PropertyId.SpeechServiceResponse_RecognitionLatencyMs);
            Console.WriteLine($"({Util.GetCurrentTime()}) Intermediate result (latencyMs={resultLatency}): {e.ToString()}, Offset: {e.Result.OffsetInTicks}, Duration: {e.Result.Duration}.");
       };
```
to that quickstart code to see the latency.

Server-side, if you can pass on a sessionId for a SR session where you've experienced latency, I can try to find some latency numbers and pass them on to the backend team to ask for an explanation.

**Comment by ccoreilly** [comment]
@glharper I can confirm we are also experiencing increased latency in continuous recognition with the latest Java Client SDK 1.17.0 when using the PhraseListGrammar (the same issue happened with version 1.16.0).

Here are my findings in a test setup (tested on both versions 1.16.0 and 1.17.0):
Using SttLanguage `de-DE`:
- Using no PhraseListGrammar resulted in an average latency of 1 second
- Creating a PhraseListGrammar but not adding any phrases did not increase the average latency
- Adding phrases to the PhraseListGrammar and then clearing them did not increase the average latency
- Using a PhraseListGrammar with a list of phrases increased latency to ~5 seconds (5x increase)

Using SttLanguage `es-US` the same behaviour is observed (~1s latency without or with an empty PhraseListGrammar) but **the latency increases up to 13 seconds** (13x increase!) when using a PhraseListGrammar with a list of phrases.

Here is the session Id and two latency log outputs by the client:

```
SPX_TRACE_INFO:  uspimpl.cpp:642 connectionUrl=wss://westeurope.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?endSilenceTimeoutMs=1000&initialSilenceTimeoutMs=5000&language=en-US&profanity=raw&punctuation=none
SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1226 [0x7f144414b1c0]CSpxAudioStreamSession::FireSessionStartedEvent: Firing SessionStarted event: SessionId: 12284ab5bc914d1399fdec097a192c60
SPX_TRACE_INFO:  usp_metrics.cpp:424 SendSerializedTelemetry: Send telemetry (requestId:2a920d3eeda349128a31517167d98d27): {""Metrics"":[{""PhraseLatencyMs"":[1598]}],""ReceivedMessages"":[{""turn.start"":[""2021-05-19T14:06:25.372Z""]},{""turn.end"":[""2021-05-19T14:06:32.356Z""]},{""speech.endDetected"":[""2021-05-19T14:06:32.356Z""]},{""speech.phrase"":[""2021-05-19T14:06:32.356Z""]}]}
SPX_TRACE_INFO:  usp_metrics.cpp:424 SendSerializedTelemetry: Send telemetry (requestId:629b5db7235a48f0a66d828c940d2aa0): {""Metrics"":[{""PhraseLatencyMs"":[13146]},{""FirstHypothesisLatencyMs"":[5317]}],""ReceivedMessages"":[{""turn.start"":[""2021-05-19T14:06:32.385Z""]},{""turn.end"":[""2021-05-19T14:06:45.105Z""]},{""speech.startDetected"":[""2021-05-19T14:06:36.166Z""]},{""speech.endDetected"":[""2021-05-19T14:06:45.105Z""]},{""speech.hypothesis"":[""2021-05-19T14:06:36.276Z"",""2021-05-19T14:06:37.875Z"",""2021-05-19T14:06:38.571Z"",""2021-05-19T14:06:39.166Z"",""2021-05-19T14:06:39.779Z"",""2021-05-19T14:06:42.081Z"",""2021-05-19T14:06:42.482Z"",""2021-05-19T14:06:43.077Z"",""2021-05-19T14:06:44.876Z""]},{""speech.phrase"":[""2021-05-19T14:06:45.105Z"",""2021-05-19T14:06:45.105Z""]}]}
```

I hope this input helps speed up the deployment of a fix as we are heavily relying on the PhraseListGrammar using both languages in production. In the meantime, if there is any workaround we can use please let me know.

**Comment by jhakulin** [comment]
@ccoreilly Thanks for the information. We are currently investigating the issue and will keep you updated.

**Comment by pankopon** [comment]
Closing this as it seems the remaining main topic is about PhraseList latency that's been specifically reported and followed up in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1124. If there are other issues still, please create a new item either here or https://github.com/microsoft/cognitive-services-speech-sdk-js/issues (if JS specific).
