### ISSUE TITLE
pronunciationAssessFromMicrophone is time too long 

### ISSUE THREAD

**Issue by aerokwok** [Azure-Samples/cognitive-services-speech-sdk#1076]
**Describe the bug**

**To Reproduce**
1. ...
2. ...

**Expected behavior**

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - please be specific
 - Hardware - x64, x86, ARM, ...
 - Programming language: C#, C++, Java, JavaScript, Objective-C, Python
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific

**Additional context**
 - Error messages, log information, stack trace, ...
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by pankopon** [comment]
Closed since no details available. Please open a new issue with more info if support is still needed.
