### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by davecatt** [Azure-Samples/cognitive-services-speech-sdk#1077]
Link in the description "See the accompanying article on the SDK documentation page which describes how to build this sample from scratch in Visual Studio 2017." results in a 404.

**Comment by pankopon** [comment]
After searching it looks like at least the following have broken links:
- https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/cpp/windows/translate-speech-to-text
- https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/dotnet/translate-speech-to-text
- https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/dotnetcore/translate-speech-to-text
- https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/uwp/translate-speech-to-text
- https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/java/jre/translate-speech-to-text

We will fix this for the 1.17.0 or 1.18.0 release at the latest.
