### ISSUE TITLE
ErrorDetails=Websocket message size cannot exceed 65536 bytes websocket error code: 1007

### ISSUE THREAD

**Issue by marcoferri72** [Azure-Samples/cognitive-services-speech-sdk#1079]
Hello,
I wanted to ask for help on this error that I receive from the service when I submit an audio file lasting about an hour. The error is generated after about 20/30 minutes of processing the material sent. I use a nodejs batch and I tried, as documented examples on the sdk site, to send both the file and the stream without success.
Here is a copy of the code for the two cases:

const fs = require('fs');
const sdk = require("microsoft-cognitiveservices-speech-sdk");
const filePath=" my file .wav";

#####################
FILE
######################
let audioConfig = sdk.AudioConfig.fromWavFileInput (fs.readFileSync (filePath))
######################

######################
STREAM
######################
let pushStream = sdk.AudioInputStream.createPushStream ();
let audio = fs.createReadStream (filePath);
audio.on ('data', function (arrayBuffer) {
     pushStream.write (arrayBuffer.slice ());
}). on ('end', function () {
     pushStream.close ();
});
let audioConfig = sdk.AudioConfig.fromStreamInput (pushStream);
#######################

const speechConfig = sdk.SpeechConfig.fromSubscription("my key", "my region");
speechConfig.speechRecognitionLanguage = "it-IT";

let recognizer = new sdk.SpeechRecognizer(speechConfig, audioConfig);

    recognizer.recognizing = (s, e) => {
        //console.log(`RECOGNIZING: Text=${e.result.text}`);
    };
    
    recognizer.recognized = (s, e) => {
        console.log('RECOGNIZED:  reason: ',e.result.reason);
        if (e.result.reason == sdk.ResultReason.RecognizedSpeech) {
            //console.log(`RECOGNIZED: Text=${e.result.text}`);
            console.log('RECOGNIZED: ',e.result.json);
        }
        else if (e.result.reason == sdk.ResultReason.NoMatch) {
            console.log("NOMATCH: Speech could not be recognized.");
        }
    };
    
    recognizer.canceled = (s, e) => {
        console.log(`CANCELED: Reason=${e.reason}`);
    
        if (e.reason == sdk.CancellationReason.Error) {
            console.log(`"CANCELED: ErrorCode=${e.errorCode}`);
            console.log(`"CANCELED: ErrorDetails=${e.errorDetails}`);
            console.log("CANCELED: Did you update the subscription info?");
        }
    
        recognizer.stopContinuousRecognitionAsync();
    };
    
    recognizer.sessionStopped = (s, e) => {
        console.log("\n    Session stopped event.");
        recognizer.stopContinuousRecognitionAsync();
    };

    recognizer.startContinuousRecognitionAsync();

thanks for the help.

node version v15.14.0
microsoft-cognitiveservices-speech-sdk 1.16.0

Operating System Ubuntu 18.04.5 LTS

**Comment by pankopon** [comment]
@glharper Can you please check, is there anything nodejs specific to consider?

**Comment by glharper** [comment]
@marcoferri72 Thanks for using Speech SDK, and writing this issue up. Could you attach the hour-long audio file you used to reproduce this?

**Comment by marcoferri72** [comment]
hi @glharper, this is the audio file, thanks. 


[GoldenClip_20200714_1143_1595427221.16.part01.rar.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6470823/GoldenClip_20200714_1143_1595427221.16.part01.rar.zip)
[GoldenClip_20200714_1143_1595427221.16.part02.rar.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6470842/GoldenClip_20200714_1143_1595427221.16.part02.rar.zip)
[GoldenClip_20200714_1143_1595427221.16.part03.rar.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6470852/GoldenClip_20200714_1143_1595427221.16.part03.rar.zip)
[GoldenClip_20200714_1143_1595427221.16.part04.rar.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6470859/GoldenClip_20200714_1143_1595427221.16.part04.rar.zip)
[GoldenClip_20200714_1143_1595427221.16.part05.rar.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6470872/GoldenClip_20200714_1143_1595427221.16.part05.rar.zip)
[GoldenClip_20200714_1143_1595427221.16.part06.rar.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6470899/GoldenClip_20200714_1143_1595427221.16.part06.rar.zip)
[GoldenClip_20200714_1143_1595427221.16.part07.rar.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6470908/GoldenClip_20200714_1143_1595427221.16.part07.rar.zip)
[GoldenClip_20200714_1143_1595427221.16.part08.rar.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6470914/GoldenClip_20200714_1143_1595427221.16.part08.rar.zip)
[GoldenClip_20200714_1143_1595427221.16.part09.rar.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6470921/GoldenClip_20200714_1143_1595427221.16.part09.rar.zip)

**Comment by glharper** [comment]
@marcoferri72 I've reproduced this and opened a bug against this issue. I'll check back in when the fix is checked in and released. Thanks for using Speech SDK and letting us know about this!
