### ISSUE TITLE
Get verbose intent JSON result

### ISSUE THREAD

**Issue by hramoser** [Azure-Samples/cognitive-services-speech-sdk#108]
**Is your feature request related to a problem? Please describe.**
The Speech SDK provides luis.ai JSON output via
`GetProperty(PropertyId::LanguageUnderstandingServiceResponse_JsonResult)`
We are not able to get the extended result similar to the output REST API with "verbose=true".
Setting `config->SetOutputFormat(mcs::OutputFormat::Detailed)` does not help.

**Describe the solution you'd like**
Setting `config->SetOutputFormat(mcs::OutputFormat::Detailed);` should provide the detailed luis JSON result.

**Describe alternatives you've considered**
-

**Additional context**
Tested with Speech SDK 1.1.0, Ubuntu 16.04, 64 bit.

**Comment by zhouwangzw** [comment]
Thank you for reporting this. The detailed output format only applies for speech recognition. Currently there is no way to get verbos result for LUIS response. We will add this as a feature request, but we do not know when it will be available.
Sorry for inconvenience.

**Comment by zhouwangzw** [comment]
I am closing the issue. If you have new questions, please open a new one. 

Thanks,
