### ISSUE TITLE
How to disable / enable use of "profanity" on the speech SDK for javascript web?

### ISSUE THREAD

**Issue by inglesuniversal** [Azure-Samples/cognitive-services-speech-sdk#1093]
It is discussed in your website but not clearly stated how to use it.

Thanks.

**Comment by jhakulin** [comment]
@inglesuniversal Thanks for question, you can use this method to enable/disable profanity using setProfanity method on SpeechConfig object. 
https://docs.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/speechconfig?view=azure-node-latest#setProfanity_ProfanityOption_

**Comment by inglesuniversal** [comment]
Thanks for the info... As a matter of fact, I've seen those notes before... but trying to set it up to RAW before the recognition engine starts has been a little difficult to figure it out...

        speechConfig.speechRecognitionLanguage = langID;

        var profanityConfig = profanityOption('profanity', 2); // 2 = Raw

        var audioConfig  = SpeechSDK.AudioConfig.fromDefaultMicrophoneInput();

        recognizer = new SpeechSDK.SpeechRecognizer(speechConfig, audioConfig, profanityConfig);

The code above gives me this error:  profanityOption is not a function

Can you tell me what is the correct way of setting it up?  It would be greatly appreciated.

**Comment by jhakulin** [comment]
@inglesuniversal 

You need to do something like below:

```
  speechConfig.speechRecognitionLanguage = langID;
  // set profanity
  speechConfig.setProfanity(SpeechSDK.ProfanityOption.Raw);
  var recognizer = new SpeechSDK.SpeechRecognizer(speechConfig, audioConfig);
```

**Comment by inglesuniversal** [comment]
It magically worked!!! 

Thanks...
