### ISSUE TITLE
RuntimeError: Exception with an error code: 0x9 (SPXERR_UNEXPECTED_EOF) [CALL STACK BEGIN]

### ISSUE THREAD

**Issue by geniusrasaq** [Azure-Samples/cognitive-services-speech-sdk#1097]
Hello Everyone,

I have been trying to transcribe 6000 audio files for a while using Microsoft cognitive speech sdk but I am getting the error listed below.

Note: I passed one audio file into the code and it worked. However, when I passed in the 6000 audio files into the code, it throws the error listed below:

RuntimeError: Exception with an error code: 0x9 (SPXERR_UNEXPECTED_EOF)
[CALL STACK BEGIN]

/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x16892d) [0x7fa843e6f92d]
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x179ffc) [0x7fa843e80ffc]
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0xef26c) [0x7fa843df626c]
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x15c23f) [0x7fa843e6323f]
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x11694b) [0x7fa843e1d94b]
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1df622) [0x7fa843ee6622]
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1c2879) [0x7fa843ec9879]
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1d6ffa) [0x7fa843eddffa]
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1c87e2) [0x7fa843ecf7e2]
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1e13f0) [0x7fa843ee83f0]
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1e1759) [0x7fa843ee8759]
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x21071f) [0x7fa843f1771f]
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(recognizer_create_speech_recognizer_from_config+0x109) [0x7fa843f1910b]
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/_speech_py_impl.so(+0x1086e0) [0x7fa8447c06e0]
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/_speech_py_impl.so(+0x92c69) [0x7fa84474ac69]
/usr/bin/python3(_PyMethodDef_RawFastCallKeywords+0x1d7) [0x5580e885ec47]
/usr/bin/python3(_PyCFunction_FastCallKeywords+0x20) [0x5580e885ea50]
[CALL STACK END]

Kindly, help me to fix this.

Here is the source code:

import time
import wave
import string
def speech_recognize_continuous_from_file():
    """performs continuous speech recognition with input from an audio file"""
    # <SpeechContinuousRecognitionWithFile>
    speech_config = speechsdk.SpeechConfig(subscription='.............', region='.......')
    audio_config = speechsdk.audio.AudioConfig(filename='/content/gdrive/MyDrive/Colab Notebooks/Google_STT_Notebook/tem/tbd_convert/recordings/')
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)

    done = False

    def stop_cb(evt):
        """callback that signals to stop continuous recognition upon receiving an event `evt`"""
        print('CLOSING on {}'.format(evt))
        nonlocal done
        done = True

    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
    speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))
    # stop continuous recognition on either session stopped or canceled events
    speech_recognizer.session_stopped.connect(stop_cb)
    speech_recognizer.canceled.connect(stop_cb)

    # Start continuous speech recognition
    speech_recognizer.start_continuous_recognition()
    while not done:
        time.sleep(.5)

**Comment by jhakulin** [comment]
@geniusrasaq Thanks for the report, could you please provide Speech SDK traces as instructed here?
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

Also looking at your source code, for AudioConfig construction you need to provide filename, not the directory path.
Something like below:
```
speech_config = speechsdk.SpeechConfig(subscription='****', region='****')

entries = os.listdir('files/')
for audiofilename in entries:
    audio_config = speechsdk.audio.AudioConfig(filename='files/'+audiofilename)
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)

    done = False

    def stop_cb(evt):
        print('CLOSING on {}'.format(evt))
        global done
        done = True

    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
    speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))
    # stop continuous recognition on either session stopped or canceled events
    speech_recognizer.session_stopped.connect(stop_cb)
    speech_recognizer.canceled.connect(stop_cb)

    # Start continuous speech recognition
    speech_recognizer.start_continuous_recognition()
    while not done:
        time.sleep(.5)
```

**Comment by geniusrasaq** [comment]
@jhakulin, thank you for your reply. I tried the code you provided above and it worked. However, the code is splitting each audio files in the directory into subsections. I increased the sleeping time to higher number but it still did not work.

**Comment by geniusrasaq** [comment]
@jhakulin , what can I do to make the code finished transcribing each audio files before moving to the next one.

**Comment by jhakulin** [comment]
@geniusrasaq The script I provided earlier will transcribe each audio file at the time, so that first file is transcribed before starting the second one and so on. Could you please provide more information what do you mean by "code is splitting each audio files in the directory into subsections" ? Also could you attach your audio files to this case so that I could reproduce the possible issue you are seeing?

**Comment by geniusrasaq** [comment]
@jhakulin, thank you for your prompt response. Attached is the copy of some of the audios that I am transcribing and the output that I got from Microsoft speech sdk and how I want to be. [](url)
[Sample_record (3).zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6529285/Sample_record.3.zip)

**Comment by dargilco** [comment]
@geniusrasaq If you need to transcribe a large set of WAV files, we recommend using [batch transcription](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription). You can find Python sample code [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python). Speech SDK is best for streaming live audio to the cloud or for processing a small number of short WAV files.

Regarding your attachment Sample_record (3).zip. Recognition results will always be given one "sentence" at a time. There is no way to configure the Speech Service to produce one recognition result for the whole file using Speech SDK. It's up to you (the app developer) to concatenate the recognition results into one string if that is what you need. 

If you need help with batch transcription, please don't hesitate to open a new GitHub issue here. 

Thanks,

Darren
