### ISSUE TITLE
Java -  source attachment

### ISSUE THREAD

**Issue by comoroberto** [Azure-Samples/cognitive-services-speech-sdk#1099]
Hi.

I'm trying out the Java code sample of speech recognition. The jar included in pom through https://csspeechstorage.blob.core.windows.net/maven/ seems doesn't have any source attachment and it is not possibile to inspect the classes.

Is there any way to add them ?

Thanks

**Comment by dargilco** [comment]
Hi @comoroberto, this is Darren from the Speech SDK team. We do not release Speech SDK source code for Java or any of the other programming languages. Is there a particular issue with Speech SDK that we can help you with? If so, feel free to open a new GitHub issue here. Thanks!
