### ISSUE TITLE
Got any plans to provide library for ARM?

### ISSUE THREAD

**Issue by boldragon** [Azure-Samples/cognitive-services-speech-sdk#11]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [v] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>
Do you have any plans to release ARM(32/64) library, cf. Raspberry?
If you have, When would it be released? ;)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). Other.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wolfma61** [comment]
Definitely in the list...
I assume you are thinking about Linux?

Wolfgang

**Comment by boldragon** [comment]
Yes. Thank you for your comment. will wait for that. ;)

**Comment by onurtirpan** [comment]
Any plan for ARM support? Asking for Win 10 IoT = Raspberry PI.
