### ISSUE TITLE
Can I get the record file?

### ISSUE THREAD

**Issue by hold-my-hand** [Azure-Samples/cognitive-services-speech-sdk#110]
when  finish recognizer or translationRecognizer ，I want save the audio data in a record file,how to do it in iOS?

**Comment by zhouwangzw** [comment]
If you want to save audio data in a file, you can capture the audio before sending to SDK. For example, your application reads data from microphone, writes the data to file, and at the same time, write the same data to SDK via SPXPushAudioInputStream for recognition/translation. The SDK itself does not have the functionality to save audio data in a file.

**Comment by hold-my-hand** [comment]
OK,I do it ,and that is ok
