### ISSUE TITLE
Speech translation from BLOB

### ISSUE THREAD

**Issue by elibenis** [Azure-Samples/cognitive-services-speech-sdk#1101]
I am following the tutorial "How to use the Speech Services Batch Transcription API from Python" (see: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python).

When I run the code, a dialog box appears reading, 'How do you want to open this file' I chose Windows Media Player but it throws an error when selected...'Windows Media Player cannot play the file. The Player might not support the file type or a required codec might not be installed on your computer.'

Any clues for resolution?

**Comment by zhouwangzw** [comment]
Which file did the dialog box ask you to open? The sample itself does not pop up any dialog box, so it must be something wrong with settings or configuration. Could you please check whether you have Python 3.7 installed and other settings?

**Comment by pankopon** [comment]
Closed as there has been no further information since May. Please open a new issue if you need more support.
