### ISSUE TITLE
https://speech.microsoft.com/portal stuck on loading

### ISSUE THREAD

**Issue by webian** [Azure-Samples/cognitive-services-speech-sdk#1102]
Hello,
I tried different browser and 2 different Microsoft account but the https://speech.microsoft.com/portal is stuck and won't finish loading (spinner in loop).

**Comment by dargilco** [comment]
Hi @webian, I'm Darren from the Speech Services team. Roughly where are you located in the world? Which browser are you using? I have not heard of any outage in MS Account or the speech portal, and it works for me now from west coast USA. Have you tried clearing your browser cash (deleting all data and cookies)?

**Comment by webian** [comment]
Hi @dargilco,
I'm in Italy near Venice.
I tried to clear browser cache and also with a Chrome (v 90.0.4430.212) guest account so clean and no extension.

In the console see these errors: so I generated [this log](https://pastebin.com/bRpwAzza).

OS: Windows 10 Enterprise 20H2 19042.985

**Comment by dargilco** [comment]
Thanks for the quick reply! I contacted the speech portal team and will follow up here when I have more information.

**Comment by dargilco** [comment]
@webian I talk to Richard from the speech portal team and he said that unfortunately there is not enough details in the log you provided. He asked that you follow the instructions in [the attached PDF](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6557378/troubleshooting-speech-portal.pdf) and let us know the result. Thanks! Darren

**Comment by webian** [comment]
@dargilco the root cause was that I was missing an Azure subscription even if I could login in Azure.
I then close this and thank you for your help!

**Comment by dargilco** [comment]
@webian Glad to hear your issue was resolved. Good luck with your project!
Darren
