### ISSUE TITLE
Not able to connect to Speech using VNET and custom subdomain from Python API

### ISSUE THREAD

**Issue by dsuarez993** [Azure-Samples/cognitive-services-speech-sdk#1103]
Hi, 

Begging for some help around here.

I've been trying for the whole day to use the Speech to Text feature of Cognitive Services with VNET integration using Python API, and no success.

If I use it without VNET and using Region and Token, it works perfectly fine, but once I set the VNET...

In Azure the Network Setup is as follows, allowing traffic from our public organization IP:
![image](https://user-images.githubusercontent.com/31488342/119670626-55649300-be39-11eb-8849-4409f0963efb.png)

Then the Endpoint:
![image](https://user-images.githubusercontent.com/31488342/119670954-a1173c80-be39-11eb-93ad-34f34671e6ab.png)

Funny thing, with Postman I can issue requests using the **REST API** with endpoints like `https://<resource>.cognitiveservices.azure.com/speechtotext/v3.0/transcriptions` and I get responses back, so the service is reachable from my machine...

But no way to make it work using **Python**. Here a snippet with the code I'm using:
```
speech_config = speechsdk.SpeechConfig(endpoint=endpoint, subscription=subscription_key)
speech_config.set_property(speechsdk.PropertyId.Speech_LogFilename, "./speech-log.txt")
audio_input = speechsdk.AudioConfig(filename=file)
speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_input)
result = speech_recognizer.recognize_once()
print(result.text)
# Checks result.
if result.reason == speechsdk.ResultReason.RecognizedSpeech:
    print("Recognized: {}".format(result.text))
elif result.reason == speechsdk.ResultReason.NoMatch:
    print("No speech could be recognized: {}".format(result.no_match_details))
elif result.reason == speechsdk.ResultReason.Canceled:
    cancellation_details = result.cancellation_details
    print("Speech Recognition canceled: {}".format(cancellation_details.reason))
    if cancellation_details.reason == speechsdk.CancellationReason.Error:
        print("Error details: {}".format(cancellation_details.error_details))
```

When I use the endpoint suggested by Azure: `https://<resource>.cognitiveservices.azure.com/sts/v1.0/issuetoken` I get the following error:
```
Speech Recognition canceled: CancellationReason.Error
Error details: Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 11001. SessionId: <session-id>
```
This endpoint seems to be only to issue a token, as I can validate by issuing same request with Postman, so I tried with `https://<resource>.cognitiveservices.azure.com`, resulting on the error:
```
Speech Recognition canceled: CancellationReason.Error
Error details: Invalid argument exception: You must specify a WS or WSS scheme for the endpoint SessionId: <session-id>
```
So I tried with the WSS and WS protocol instead of HTTPS, in other words `wss://<resource>.cognitiveservices.azure.com` , which after a few seconds returns the following error (same with ws://):
```
Speech Recognition canceled: CancellationReason.Error
Error details: WebSocket upgrade failed: Internal service error (404). Please check request details. SessionId: <session-id>
```
I've been trying very different combinations of possible endpoints and API versions, search in the documentation, all around internet but nothing. 

Can anyone guide me through this? Am I using the right endpoint? Am I missing something?

Thanks!

**Comment by dargilco** [comment]
@dsuarez993 Are the instructions here not helpful? https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-service-vnet-service-endpoint

**Comment by pmooij** [comment]
thanks for getting into this @dargilco as I'm facing the same problem.

specifically this section https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-services-private-link?tabs=portal#speech-to-text-rest-api-v30 addresses this properly for the REST API, specifically v3.
so through the REST API the firewall and the service work as expected.

However, for the SpeechSDK I can't find a way to put the appropriate location / url into the function.
furthermore when scrolling down to this section https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-services-private-link?tabs=portal#construct-endpoint-url the examples seem to use the v1 syntax

when I tried tailoring `wss://my-private-link-speech.cognitiveservices.azure.com/stt/speech/recognition/conversation/cognitiveservices/v1?language=en-US` to my cognitive service that did not work either.

which API version(s) are being used by the SpeechSDK and how could I infuse the custom domain into that?

Thanks!

**Comment by pmooij** [comment]
mea culpa @dargilco, missed a service endpoint on the particualar databricks subnet we're originating from

herewith I confirm that the following does work as expected, using a firewall restricted cognitive service

```python
transscript_endpoint = f"wss://{custom_domain}.cognitiveservices.azure.com/stt/speech/recognition/conversation/cognitiveservices/v1?language=en-US"
speech_config = speechsdk.SpeechConfig(subscription=subscription_key, endpoint=transscript_endpoint)
```

**Comment by dargilco** [comment]
Thank you for the update, and good luck with your project! Don't hesitate to open an issue here if you run into other problems. 
Darren
