### ISSUE TITLE
How to use WordBoundary with stream or audio file output

### ISSUE THREAD

**Issue by MikeMnD** [Azure-Samples/cognitive-services-speech-sdk#1104]
I'm using the microsoft-cognitiveservices-speech-sdk on Node.js

The only example i found is a JS browser based and I want to make the request, save the file and save the word timing info in complimentary file.
At the moment saving to file works as expected but no callbacks are called.
This is the code I'm using: 

`synthesizeSpeechToStream(subscriptionKey: string, serviceRegion: string) {
    const speechConfig = sdk.SpeechConfig.fromSubscription(subscriptionKey, serviceRegion);
    const pathToFile = `output/stream-from-file-${Date.now()}.wav`;
    const audioConfig = sdk.AudioConfig.fromAudioFileOutput(pathToFile);
    const phrase = 'Saving to file and getting word timing data.';
    const synthesizer = new sdk.SpeechSynthesizer(speechConfig, audioConfig);

    const wordBoundaryList = [];
    // Before beginning speech synthesis, setup the callbacks to be invoked when an event occurs.

    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });

    // The event synthesizing signals that a synthesized audio chunk is received.
    // You will receive one or more synthesizing events as a speech phrase is synthesized.
    // You can use this callback to streaming receive the synthesized audio.
    synthesizer.synthesizing = function (s, e) {
      const str = `(synthesizing) Reason: ${sdk.ResultReason[e.result.reason]} Audio chunk length: ${e.result.audioData.byteLength}`;
      console.log(str);
    };

    // The event synthesis completed signals that the synthesis is completed.
    synthesizer.synthesisCompleted = function (s, e) {
      console.log(`(synthesized)  Reason: ${sdk.ResultReason[e.result.reason]} Audio length: ${e.result.audioData.byteLength}`);
    };

    // The synthesis started event signals that the synthesis is started.
    synthesizer.synthesisStarted = function (s, e) {
      console.log(`(synthesis started)${s}`);
    };

    // This event signals that word boundary is received. This indicates the audio boundary of each word.
    // The unit of e.audioOffset is tick (1 tick = 100 nanoseconds), divide by 10,000 to convert to milliseconds.
    synthesizer.wordBoundary = function (s, e) {
      console.log(`(WordBoundary), Text: ${e.text}, Audio offset: ${e.audioOffset / 10000}ms.`);
      wordBoundaryList.push(e);
    };

    rl.question(phrase, (text: string) => {
      rl.close();
      // start the synthesizer and wait for a result.
      synthesizer.speakTextAsync(text,
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        (result) => {
          synthesizer.close();
          if (result) {
            // return result as stream
            return fs.createReadStream(pathToFile);
          }
        },
        (err) => {
          console.trace(`err - ${err}`);
          synthesizer.close();
        });
    });
  }`

Any manual, guide or tips and tricks beside diving into the source code of the SDK will be appreciated.
I'm using payed account with Pay-As-You-Go don't know if I should contact the support for such an issue?

**Comment by dargilco** [comment]
Hi @MikeMnD, I'm Darren from the Speech Services team. Do you mind posting your question on the Speech SDK JS site, so other JS developers can benefit from our reply? Over here: https://github.com/microsoft/cognitive-services-speech-sdk-js/issues
Thanks,
Darren

**Comment by MikeMnD** [comment]
Hi, @dargilco I've done it. https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/377
