### ISSUE TITLE
We need to add ip to the whitelist

### ISSUE THREAD

**Issue by cl-6666** [Azure-Samples/cognitive-services-speech-sdk#1105]
Hello, we have a demand here. Our Internet has access requirements, and IP must be restricted. We are now using your Android speech recognition, synthesis, and translation services. Now we want to configure the IP or domain name to be accessed on our side. , I don’t know if it is convenient for you to provide it?

**Comment by dargilco** [comment]
You can configure your service to allow access to the IP addressed covered by the Azure Service Tag "CognitiveServicesManagement". See link here: https://docs.microsoft.com/en-us/azure/virtual-network/service-tags-overview

Please follow these steps to add the IP Address ranges to an allow list:
* Download IP Ranges for all service tags: https://www.microsoft.com/download/details.aspx?id=56519
* Select the IPs of "CognitiveServicesManagement".
* If you are using Azure: Navigate to the networking section of your App Service resource, and click on "Configure Access Restriction" option to add the IPs to an allow list.

The above can also be done by writing a script that will get the updated IP Addresses and apply them to your App Service resource. The QnA Make team has an example generic PowerShell Script: https://github.com/pchoudhari/QnAMakerBackupRestore/blob/master/AddRestrictedIPAzureAppService.ps1

I hope the above helps. I am closing this issue. If this did not answer your needs, please reactivate. 

Thanks,

Darren

**Comment by cl-6666** [comment]
Hello, we tried according to the format you posted, and found that the number of IPs to be configured is too much. Is there a domain name format? In this case, we don't need to configure so many IPs.

**Comment by dargilco** [comment]
Hi @cl-6666 yes, I see there are now 778 IP addresses listed under the CognitiveServicesManagement service tag. These are all the Microsoft AI services. Are you looking for only speech IP addresses and/or host names? I've contacted the Speech Service folks to get some guidance around this and will reply when I have more info.

**Comment by dargilco** [comment]
@cl-6666 Sorry for the late reply. Unfortunately CognitiveServicesManagement service tag is all we have now for you to use. We do not yet have a service tag specific to Speech Services (or Speech Services per Azure Region).  I believe what you can do to narrow the list is download the IP addresses in the CognitiveServicesManagement service tag, and then trim it down based on the Azure regions you will be using (see [mapping between country & Azure region name here](https://azure.microsoft.com/en-us/global-infrastructure/geographies/)). Assignment of IP address ranges per county is public information, so you can use that. This is probably not the answer you expected, but I thought I would mention it anyway.
Thanks,
Darren
