### ISSUE TITLE
SPXERR_CHANGE_CONNECTION_STATUS_NOT_ALLOWED

### ISSUE THREAD

**Issue by amitguptampct12** [Azure-Samples/cognitive-services-speech-sdk#1108]
How to handle this kind of exception.

libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Exception with an error code: 0x1f (SPXERR_CHANGE_CONNECTION_STATUS_NOT_ALLOWED)
[CALL STACK BEGIN]

3   MicrosoftCognitiveServicesSpeech    0x000000010b3ea795 user_get_id + 153621
4   MicrosoftCognitiveServicesSpeech    0x000000010b4ea066 user_get_id + 1200358
5   MicrosoftCognitiveServicesSpeech    0x000000010b4e9ff9 user_get_id + 1200249
6   MicrosoftCognitiveServicesSpeech    0x000000010b4ebfdb user_get_id + 1208411
7   MicrosoftCognitiveServicesSpeech    0x000000010b4ea196 user_get_id + 1200662
8   MicrosoftCognitiveServicesSpeech    0x000000010b4ed5c8 user_get_id + 1214024
9   libsystem_pthread.dylib             0x00007fff61167109 _pthread_start + 148
10  libsystem_pthread.dylib             0x00007fff61162b8b thread_start + 15
[CALL STACK END]

**Comment by dargilco** [comment]
@amitguptampct12 What is the scenario you are running? what Speech SDK APIs are you using? give us some more info on your usage case. Also please [provide Speech SDK logs](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging). Reply here and drag the Speech SDK log file into your reply box to attach the log. 
Thanks,
Darren

**Comment by glecaros** [comment]
Closing this issue as it hasn't seen movement in quite some time. @amitguptampct12, please feel free to reopen if you need further help.
