### ISSUE TITLE
About SPXTranslationRecognitionResult

### ISSUE THREAD

**Issue by hold-my-hand** [Azure-Samples/cognitive-services-speech-sdk#111]
A SPXTranslationRecognitionResult with reason value  SPXResultReason_TranslatingSpeech, other SPXTranslationRecognitionResult   with reason value SPXResultReason_TranslatedSpeech, I see they have different resultId, but I want put all result in a array。When receive SPXResultReason_TranslatedSpeech result ,I want replace the SPXResultReason_TranslatingSpeech with the SPXResultReason_TranslatedSpeech,How to do?

**Comment by zhouwangzw** [comment]
Results with SPXResultReason_TranslatingSpeech are intermediate results, which are hypotheses about the words recognized by the service. The intermediate results is mainly used to enhance the user speech experience (e.g. as feedback of the in-progress recognition to what is being spoken), but their content can be changed until the final results are received. Results with SPXResultReason_TranslatedSpeech are final results. When you receive the final result, you can discard all intermediate results you received before. In the event with SPXResultReason_TranslatedSpeech, you can also find offset and duration, which indicates the audio segment corresponding to the recognized text. 

Thanks,
Zhou

**Comment by zhouwangzw** [comment]
I am closing the issue. Please open a new issue if you have any questions.
