### ISSUE TITLE
InvalidPayload when posting MP3 for transcription

### ISSUE THREAD

**Issue by OD1995** [Azure-Samples/cognitive-services-speech-sdk#1111]
**Describe the bug**
Got an unexpected response of:
```
Transfer-Encoding: chunked
api-supported-versions: 2.0,3.0
api-deprecated-versions: 2.0
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
apim-request-id: 961dac3d-0ded-4954-b355-029a2f997c13
x-content-type-options: nosniff
Cache-Control: no-store
Date: Fri, 28 May 2021 14:56:58 GMT
Content-Type: application/json; charset=utf-8

{
  "code": "InvalidRequest",
  "message": "A valid value is required for transcription.dataset. OR The value of transcription.Locale is a custom culture identifier. Custom cultures are not supported. OR Only absolute URIs containing a valid scheme, authority and path are allowed for transcription.contentContainerUrl.",
  "innerError": {
    "code": "InvalidPayload",
    "message": "A valid value is required for transcription.dataset. OR The value of transcription.Locale is a custom culture identifier. Custom cultures are not supported. OR Only absolute URIs containing a valid scheme, authority and path are allowed for transcription.contentContainerUrl."
  }
}
```

**To Reproduce**
Using https://uksouth.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/operations/CreateTranscription/console, I posted this:
```
{
  "contentUrls": [
    "https://fsevideos.blob.core.windows.net/video-from-stream/Emails-From-Abroad-Min1.mp3?sv=2020-04-08&st=2021-05-28T11%3A40%3A20Z&se=2021-05-29T11%3A40%3A20Z&sr=b&sp=r&sig=EC7SJ7n3HsvHzqXd7BeiAlxC660WuhievIo0kWTy08E%3D"
  ],
  "locale": "en-UK",
  "displayName": "Test1"
}
```

**Comment by dargilco** [comment]
Hi @OD1995, thank you for posting this question. It seems to be about [Batch Transcription](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription). The issues we track in this GitHub repo are about Speech SDK. I will contact the appropriate team to try to get someone to answer your question here, but I will go ahead and close the issue. A better way to get help with Batch Transcription is to post a [StackOverflow question tagged with azure-speech](https://stackoverflow.com/questions/tagged/azure-speech). We regularly monitor those questions.
Darren

**Comment by OD1995** [comment]
Appreciate the fast response @dargilco and apologies for posting in the wrong place. I have now posted my question [here](https://stackoverflow.com/questions/67741659/invalidpayload-when-posting-mp3-for-transcription-when-using-azure-speech-to-tex)
