### ISSUE TITLE
SPXERR_START_RECOGNIZING_INVALID_STATE_TRANSITION

### ISSUE THREAD

**Issue by incomingflyingbrick** [Azure-Samples/cognitive-services-speech-sdk#1112]
Hi , i am using android sdk to do speech to text.
There is bug like when using speech recogniztion.
I can't reproduce this, but I have the following error message/

SDK version is **Java,  1.16.0**

Canceled Event was called

RuntimeError
0x13 (SPXERR_START_RECOGNIZING_INVALID_STATE_TRANSITION) 
[CALL STACK BEGIN]

  #0: 0x7a98d30b50  ???
  #1: 0x7a98d30434  ???
  #2: 0x7a98d3c20c  ???
  #3: 0x7a98d3a214  ???
  #4: 0x7a98dcfa7c  ???
  #5: 0x7a98dcf068  ???
  #6: 0x7a98dd081c  ???
  #7: 0x7a98dcf118  ???
  #8: 0x7a98dd1b88  ???
  #9: 0x7accbe574c  ???
  #10: 0x7accb9aa80  ???

[CALL STACK END]

 SessionId: c7205119c1854df4946bd70fc2bed707

**Comment by jhakulin** [comment]
@incomingflyingbrick 1.17.0 Speech SDK release contains fixes which impacts to this, could you please take that into use and let us know if you have any issues?

**Comment by incomingflyingbrick** [comment]
> @incomingflyingbrick 1.17.0 Speech SDK release contains fixes which impacts to this, could you please take that into use and let us know if you have any issues?

I see, I upgraded to 1.17.0 the issure is gone now
