### ISSUE TITLE
Why it take so long between SESSION STARTED e SPEECH DETECTED events

### ISSUE THREAD

**Issue by antonioalveslopes** [Azure-Samples/cognitive-services-speech-sdk#1114]
**Describe the bug**
I'm using the Java SDK for speech recognition, I noticed that when I send a audio stream, the session started events comes very fast, but the speech detected event delays almost 5s to start, even if my streaming has a recognizable voice. In the log it could verify that the first audio chunk is send at 2021-06-01T22:53:49.1855151Z, but the speech detected event only comes at 2021-06-01T22:53:53.2778653Z. 4s later.

**To Reproduce**
1. Use IntentRecognition::startContinuousRecognitionAsync
2.  AudioInputStream.createPullStream(callback, AudioStreamFormat.getCompressedFormat(AudioStreamContainerFormat.ALAW));

**Expected behavior**
It would be satisfatory if the event speech detected could be delivered just after the firsts chunks of audio.

**Version of the Cognitive Services Speech SDK**
SDK: 1.17.0

**Platform, Operating System, and Programming Language**
 - OS: Ubuntu 20.04
 - Hardware - x64
 - Programming language: Java

**Additional context**
 - Log is attached
[azure.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6581008/azure.log)

**Comment by BrianMouncer** [comment]
Good after noon and thank you for reaching out to us,

Can you give me a little more detail about what you are seeing.
A code sample would be great, but if not what I an interested in is which event are you listening to that is taking this long.

e.g. if you are listening to ResultReason.RecognizedSpeech then that would sound about right, as this even will not fire until you stop speaking or the service sees enough silence to endpoint and generate a final result.

but if you are listening to the ResultReason.RecognizingSpeech event, that should fire as soon as we process enough audio to recognize the first word.  This is an intermediate result, and the final "RecognizedSpeech" result may start with something completely different as we get enough audio to make a better interpretation of what was said, but it should arrive relatively fast. 

If you haven't seen samples already, this might help experiment and see the different timing and word accuracy of the two event types.

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java

```
            // Subscribes to events.
            recognizer.recognizing.addEventListener((s, e) -> {
                if (e.getResult().getReason() == ResultReason.RecognizingKeyword) {
                    System.out.println("RECOGNIZING KEYWORD: Text=" + e.getResult().getText());
                }
                else if (e.getResult().getReason() == ResultReason.RecognizingSpeech) {
                    System.out.println("RECOGNIZING: Text=" + e.getResult().getText());
                }
            });

            recognizer.recognized.addEventListener((s, e) -> {
                if (e.getResult().getReason() == ResultReason.RecognizedSpeech) {
                    System.out.println("RECOGNIZED: Text=" + e.getResult().getText());
                }
                else if (e.getResult().getReason() == ResultReason.NoMatch) {
                    System.out.println("NOMATCH: Speech could not be recognized.");
                }
            });
```

**Comment by antonioalveslopes** [comment]
> Good after noon and thank you for reaching out to us,
> 
> Can you give me a little more detail about what you are seeing.
> A code sample would be great, but if not what I an interested in is which event are you listening to that is taking this long.
> 
> e.g. if you are listening to ResultReason.RecognizedSpeech then that would sound about right, as this even will not fire until you stop speaking or the service sees enough silence to endpoint and generate a final result.
> 
> but if you are listening to the ResultReason.RecognizingSpeech event, that should fire as soon as we process enough audio to recognize the first word. This is an intermediate result, and the final "RecognizedSpeech" result may start with something completely different as we get enough audio to make a better interpretation of what was said, but it should arrive relatively fast.
> 
> If you haven't seen samples already, this might help experiment and see the different timing and word accuracy of the two event types.
> 
> https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java
> 
> ```
>             // Subscribes to events.
>             recognizer.recognizing.addEventListener((s, e) -> {
>                 if (e.getResult().getReason() == ResultReason.RecognizingKeyword) {
>                     System.out.println("RECOGNIZING KEYWORD: Text=" + e.getResult().getText());
>                 }
>                 else if (e.getResult().getReason() == ResultReason.RecognizingSpeech) {
>                     System.out.println("RECOGNIZING: Text=" + e.getResult().getText());
>                 }
>             });
> 
>             recognizer.recognized.addEventListener((s, e) -> {
>                 if (e.getResult().getReason() == ResultReason.RecognizedSpeech) {
>                     System.out.println("RECOGNIZED: Text=" + e.getResult().getText());
>                 }
>                 else if (e.getResult().getReason() == ResultReason.NoMatch) {
>                     System.out.println("NOMATCH: Speech could not be recognized.");
>                 }
>             });
> ```

Hi, I'm using that code bellow. The event that take too long to start is `speechStartDetected`. The event `sessionStarted` comes fast, but even with an audio with enough voice, the  `speechStartDetected` takes too long to start.

```PullAudioInputStreamCallback callback = new WavStream(new FileInputStream(path));
		AudioInputStream inStream = AudioInputStream.createPullStream(callback,
				AudioStreamFormat.getCompressedFormat(AudioStreamContainerFormat.ALAW));

		AudioConfig audioInput = AudioConfig.fromStreamInput(inStream);
		IntentRecognizer recognizer = new IntentRecognizer(config, audioInput);

		LanguageUnderstandingModel model = LanguageUnderstandingModel.fromAppId(agentId);
		recognizer.addAllIntents(model);

		// recognizer.addIntent(model, "Utilities.Reject");
		var begin = System.currentTimeMillis();

		recognizer.recognized.addEventListener((s, e) -> {
			if (e.getResult().getReason() == ResultReason.RecognizedIntent) {
				logger.info("RECOGNIZED: Text=" + e.getResult().getText());
				recognizingText = e.getResult().getText();
				logger.info("    Intent Id: " + e.getResult().getIntentId());
				logger.info("    Intent Service JSON: " + e.getResult().getProperties()
						.getProperty(PropertyId.LanguageUnderstandingServiceResponse_JsonResult));
				String propertyJson = e.getResult().getProperties()
						.getProperty(PropertyId.LanguageUnderstandingServiceResponse_JsonResult);
				JsonObject json = JsonParser.parse(propertyJson);

				stopRecognitionSemaphore.release();
			} else if (e.getResult().getReason() == ResultReason.RecognizedSpeech) {
				logger.info("RECOGNIZED: Text=" + e.getResult().getText());
				recognizingText = e.getResult().getText();
				logger.info("    Intent not recognized.");
				resultIntent.addProperty("text", e.getResult().getText());
				resultIntent.addProperty("intent", "no-match");
				stopRecognitionSemaphore.release();
			}

			else if (e.getResult().getReason() == ResultReason.NoMatch) {
				logger.info("NOMATCH: Speech could not be recognized.");
				recognizingText = ".";
				resultIntent.addProperty("intent", "no-match");
				stopRecognitionSemaphore.release();
			}
		});

		recognizer.sessionStarted.addEventListener((s, e) -> {
			logger.info("SESSION STARTED: ");
		});

		recognizer.sessionStopped.addEventListener((s, e) -> {
			logger.info("SESSION STOPPED");
		});

		recognizer.speechStartDetected.addEventListener((s, e) -> {
			var end = System.currentTimeMillis();
			System.out.println("STARTING SPEECH DETECTED: " + (end - begin));
			logger.info("STARTING SPEECH DETECTED: " + (end - begin));
		});

		recognizer.speechEndDetected.addEventListener((s, e) -> {
			logger.info("STOPPING SPEECH DETECTED");
		});

		recognizer.canceled.addEventListener((s, e) -> {
			logger.info("CANCELED DETECTED");
		});
		recognizer.recognizing.addEventListener((s, e) -> {
			logger.info("RECOGNIZING: " + e.getResult().getText());
			recognizingText += e.getResult().getText();
			stopRecognitionSemaphoreSilence.release();
		});

		recognizer.canceled.addEventListener((s, e) -> {
			CancellationDetails cancellation = CancellationDetails.fromResult(e.getResult());
			logger.warn("CANCELED: Reason=" + cancellation.getReason());
			resultIntent.addProperty("intent", "failed");
			if (cancellation.getReason() == CancellationReason.Error) {
				resultIntent.addProperty("error_details", cancellation.getErrorDetails());
				resultIntent.addProperty("error", cancellation.getErrorCode().toString());
				logger.warn("CANCELED: ErrorCode=" + cancellation.getErrorCode());
				logger.warn("CANCELED: ErrorDetails=" + cancellation.getErrorDetails());
				stopRecognitionSemaphore.release();
				stopRecognitionSemaphoreSilence.release();
			}
		});

		logger.info("STARTING RECOG ASYNC...");
		IntentRecognitionResult intentRecognitionResult = recognizer.recognizeOnceAsync().get();```

**Comment by pankopon** [comment]
Based on the log, connection to the service is not confirmed before 4427ms. The service indicates the start of processing (turn.start) shortly after. From that point onwards the time of received events w.r.t. offset and duration of speech (e.g. "6500000 (100ns)" = 650ms) seems normal. So the perceived delay before the first speech event is due to the time taken to establish an actual connection to the remote service. The 'session started' event is generated locally, therefore it can appear quickly (you will get the event even if connection fails).
```
$ egrep "ConnectionMessageReceived|Response: Speech|connection" azure.log
[618482]: 1063ms SPX_TRACE_INFO:  uspimpl.cpp:664 connectionUrl=wss://brazilsouth.sr.speech.microsoft.com/speech/recognition/interactive/cognitiveservices/v1?format=detailed&language=pt-br
[618482]: 4427ms SPX_TRACE_INFO:  uspimpl.cpp:1005 TS:3365, OnConnected: connection:0x7c01bc70
[618482]: 4612ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1323 [0x7f9168056e30]CSpxAudioStreamSession::FireConnectionMessageReceived; path=turn.start
[618482]: 5378ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1323 [0x7f9168056e30]CSpxAudioStreamSession::FireConnectionMessageReceived; path=speech.startDetected
[618482]: 5378ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:1284 Response: Speech.StartDetected message. Speech starts at offset 6500000 (100ns).
[618482]: 5551ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1323 [0x7f9168056e30]CSpxAudioStreamSession::FireConnectionMessageReceived; path=speech.hypothesis
[618482]: 5551ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:1336 Response: Speech.Hypothesis message. Starts at offset 6500000, with duration 3400000 (100ns). Text: pode
[618482]: 5688ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1323 [0x7f9168056e30]CSpxAudioStreamSession::FireConnectionMessageReceived; path=speech.hypothesis
[618482]: 5688ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:1336 Response: Speech.Hypothesis message. Starts at offset 6500000, with duration 9100000 (100ns). Text: pode agendar
[618482]: 5789ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1323 [0x7f9168056e30]CSpxAudioStreamSession::FireConnectionMessageReceived; path=speech.hypothesis
[618482]: 5789ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:1336 Response: Speech.Hypothesis message. Starts at offset 6500000, with duration 10500000 (100ns). Text: pode agendar para
[618482]: 5890ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1323 [0x7f9168056e30]CSpxAudioStreamSession::FireConnectionMessageReceived; path=speech.hypothesis
[618482]: 5890ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:1336 Response: Speech.Hypothesis message. Starts at offset 6500000, with duration 12700000 (100ns). Text: pode agendar para amanhã
[618482]: 5954ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1323 [0x7f9168056e30]CSpxAudioStreamSession::FireConnectionMessageReceived; path=speech.endDetected
[618482]: 5954ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:1303 Response: Speech.EndDetected message. Speech ends at offset 30300000 (100ns)
[618482]: 5964ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1323 [0x7f9168056e30]CSpxAudioStreamSession::FireConnectionMessageReceived; path=speech.phrase
[618482]: 5964ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:1585 Response: Speech.Phrase message. Status: 0, Text: Pode agendar para amanhã., starts at 6500000, with duration 16200000 (100ns).
[618482]: 5964ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1323 [0x7f9168056e30]CSpxAudioStreamSession::FireConnectionMessageReceived; path=turn.end
```
