### ISSUE TITLE
Custom Speech Endpoint for JS

### ISSUE THREAD

**Issue by Ananya-96** [Azure-Samples/cognitive-services-speech-sdk#1116]
**Describe the bug**
Passing the endpointId, WebSocket connection to STT fails. If endpointId is not passed, the SDK works fine.

**To Reproduce**

	async sttFromMic() {
		  const tokenObj = await this.getTokenOrRefresh();
		  const speechConfig: SpeechConfig =
			speechsdk.SpeechConfig.fromAuthorizationToken(
			  tokenObj.authToken,
			  tokenObj.region
			);
		  speechConfig.endpointId = 'my custom speech endpoint id';
		  speechConfig.speechRecognitionLanguage = 'en-US';
		  speechConfig.speechSynthesisLanguage = 'en-US';
		  const audioConfig: AudioConfig =
			speechsdk.AudioConfig.fromDefaultMicrophoneInput();
		  const recognizer: SpeechRecognizer = new speechsdk.SpeechRecognizer(
			speechConfig,
			audioConfig
		  );
		  recognizer.startContinuousRecognitionAsync();
		  //  The event recognizing signals that an intermediate recognition result is received.
		  recognizer.recognizing = function (s, e) {
			console.log(recognizer.speechRecognitionLanguage);
			console.log('recognizing text', e.result.text);
		  };
		  //  The event recognized signals that a final recognition result is received.
		  recognizer.recognized = function (s, e) {
			console.log('recognized text', e.result.text);
		  };
		}
  
    async getTokenOrRefresh() {
      const cookie = new Cookie();
      const speechToken = cookie.get('speech-token');
  
      if (speechToken === undefined) {
        const speechKey = 'my key';
        const speechRegion = 'westus';
  
        const headers = {
          headers: {
            'Ocp-Apim-Subscription-Key': speechKey,
            'Content-Type': 'application/x-www-form-urlencoded',
          },
        };
  
        try {
          const tokenResponse = await axios.post(
            'https://${speechRegion}.api.cognitive.microsoft.com/sts/v1.0/issueToken',
            null,
            headers
          );
          cookie.set('speech-token', speechRegion + ':' + tokenResponse.data, {
            maxAge: 540,
            path: '/',
          });
          return {
            authToken: tokenResponse.data,
            region: speechRegion,
          };
        } catch (err) {
          console.log(err);
        }
      } else {
        console.log('Token fetched from cookie: ' + speechToken);
        const idx = speechToken.indexOf(':');
        return {
          authToken: speechToken.slice(idx + 1),
          region: speechToken.slice(0, idx),
        };
      }
    }

**Version of the Cognitive Services Speech SDK**
Javascript SDK version - 1.17.0

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - Windows
 - Hardware - x64
 - Programming language: JavaScript
 - Browser - Chrome

**Additional context**
 WebsocketMessageAdapter.js:33 WebSocket connection to 'wss://westus.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?cid={my-connection-id}&format=simple&Authorization={auth-token}&X-ConnectionId=0B997FA7267D4F819F24ABF9EAA7F75A' failed: 
WebsocketMessageAdapter.open @ WebsocketMessageAdapter.js:33
WebsocketConnection.open @ WebsocketConnection.js:24
(anonymous) @ ServiceRecognizerBase.js:541
fulfilled @ ServiceRecognizerBase.js:6
invoke @ zone-evergreen.js:364
onInvoke @ core.js:41708
invoke @ zone-evergreen.js:363
run @ zone-evergreen.js:123
(anonymous) @ zone-evergreen.js:857
invokeTask @ zone-evergreen.js:399
onInvokeTask @ core.js:41686
invokeTask @ zone-evergreen.js:398
runTask @ zone-evergreen.js:167
drainMicroTaskQueue @ zone-evergreen.js:569
invokeTask @ zone-evergreen.js:484
invokeTask @ zone-evergreen.js:1621
globalZoneAwareCallback @ zone-evergreen.js:1647

**Comment by Ananya-96** [comment]
@BrianMouncer  Is there any update on this issue?

**Comment by adriensas** [comment]
I have the exact same issue,
I'm almost certain it is a bug as I've used the same functions in python and got the expected result : 
https://github.com/Azure-Samples/AzureSpeechReactSample/issues/2 (Sorry I've missplaced the issue).

**Comment by glharper** [comment]
@Ananya-96 @adriensas Deployment IDs are tied to a specific key and region pair. Using the latest JS SDK version, I received the same "connection failed" (with a 404) error when using a valid deployment ID not paired to an otherwise valid key. 

When retesting with a valid deployment ID and the key to which that ID is paired, however, there was no connection error, so I'm wondering if that's the issue you are seeing.

@adriensas, You mentioned that your endpoint ID worked in python, correct? If your endpoint ID and key still works in python, but not JS, could you followup with me at <my_github_username>(at)microsoft(dot)com?

Thanks again for using Speech SDK!

**Comment by pankopon** [comment]
@Ananya-96 @adriensas Please confirm if the information provided in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1116#issuecomment-883592428 does help in your case or if you need more support.

**Comment by pankopon** [comment]
Closing the item since no further updates received & issues presumed resolved based on https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1116#issuecomment-883592428. Please open a new issue if more support is needed.

**Comment by adriensas** [comment]
@pankopon I'm very sorry for the late reply I didn't have the time to come back to that matter before.
If tried many things meanwhile.
It seems that the custom endpoint works in JS when using a predefined language but when I use the `AutoDetectSourceLanguageConfig` and I instantiate the recognizer with `sdk.SpeechRecognizer.FromConfig(speechConfig, autoDetectConfig, audioConfig)`, it cease working even though it detects the correct language to which I've associated the custom endpoint id.
Thank you in advance for your help.
