### ISSUE TITLE
InitialSilenceTimeoutMs ignored with DialogServiceConnector

### ISSUE THREAD

**Issue by aalonso-solusoft** [Azure-Samples/cognitive-services-speech-sdk#1117]
**Describe the bug**
InitialSilenceTimeoutMs is ignored when I use DialogServiceConnector. I always have a timeout of 5 seconds before the Speech Service stops recognizing speech even if I try to change this timeout using the setProperty method.

**To Reproduce**

```java
DialogServiceConfig dialogServiceConfig = BotFrameworkConfig.fromSubscription(configuration.speechSubscriptionKey, configuration.speechRegion);
dialogServiceConfig.setProperty(PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs, "15000");
DialogServiceConnector botConnector = new DialogServiceConnector(dialogServiceConfig, AudioConfig.fromDefaultMicrophoneInput());
botConnector.listenOnceAsync();
```

**Version of the Cognitive Services Speech SDK**
Java SDK version - 1.17.0

**Platform, Operating System, and Programming Language**

- OS: [e.g. Windows, Linux, Android, iOS, ...] - Android
- Programming language: Java

**Comment by BrianMouncer** [comment]
What specifically are you trying to change?
We have several silence timeouts, and I want to make sure you are using the correct one.

e.g we also have end silence timeouts and the Conversation_Initial_Silence_Timeout and SpeechServiceConnection_EndSilenceTimeoutMs.

Thanks.

**Comment by aalonso-solusoft** [comment]
I want to edit two timeouts. First, I want to give my user more than 5 seconds to say something before the bot assumes that it was an empty speech. I also want to give my users the oportunity to pause one or two seconds in the middle of a speech. For example "I have 5 liters of gasoil type a (pause of one or two seconds) and 10 liters of gasoil type b".

Quoting rhurey from issue #502:

"Initial Silence Timeout: The amount of silence at the beginning of a recognition before the Speech Service stops recognizing speech.
End Silence Timeout: The amount of silence after speech before the Speech Service stops recognizing speech."

I think that I need to edit those values.

Thank you for your answer.

**Comment by glecaros** [comment]
Hi @aalonso-solusoft, were you able to make your scenario work using those two timeouts? Please let us know if you need any further assistance

**Comment by aalonso-solusoft** [comment]
Hi @glecaros . No, I only have timeouts of 5 seconds, even if I configure the "PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs" with bigger times.

**Comment by BlackstarprojectFX** [comment]
Reducing the volume level on the mic between 20-30, will greatly reduce background interference. Most people have theirs set between 70-100, which (as you can guess) can cause a lot of unwanted performance with speech recognition.

**Comment by glecaros** [comment]
Hi @aalonso-solusoft, I talked with the service team and there seems to be an issue on how the property is being populated by the SDK (we opened a bug internally to fix this) In the meantime, you can try the following workaround:

```java
this.dialogServiceConfig.SetServiceProperty("initialSilenceTimeoutMs", "10000", ServicePropertyChannel.UriQueryParameter);
this.dialogServiceConfig.SetServiceProperty("endSilenceTimeoutMs", "15000", ServicePropertyChannel.UriQueryParameter);
```

Please let me know if that helps.

**Comment by aalonso-solusoft** [comment]
Thanks @glecaros, it works perfectly. I close the issue.
