### ISSUE TITLE
The online service failed to process the emoji expression

### ISSUE THREAD

**Issue by ghpfxf** [Azure-Samples/cognitive-services-speech-sdk#1118]
**Additional context**
 ssml data

<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis"
       xmlns:mstts="https://www.w3.org/2001/mstts" xml:lang="zh-CN">
    <voice name="zh-CN-XiaoxiaoNeural">
        <mstts:express-as style="assistant" styledegree="2">
            🤪🤩🤩你来电话了，要接听还是拒绝？
        </mstts:express-as>
    </voice>
</speak>

**Comment by BrianMouncer** [comment]
@ghpfxf 

Thank you for reporting this.  I've asked on of our TTS team members to look into this.
reviewing the documentation of the express-as SSML extention, I see that the "assistant" speaking style is only supported with specific neural voices.

Can you provide some more information about what voice you are trying to speak this SSML with, and if you are speaking an entire SSML document, or just the fragment that you included above? and do you see any difference if you speak the ascii format rather that the unicode emoji?  :-) versus 🤪?

Thanks,

Brian.

does this also not work for you?

<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis"
       xmlns:mstts="https://www.w3.org/2001/mstts" xml:lang="zh-CN">
    <voice name="zh-CN-XiaoxiaoNeural">
        <mstts:express-as style="assistant" styledegree="2">
            🤪🤩🤩你来电话了，要接听还是拒绝？
        </mstts:express-as>
    </voice>
</speak>

**Comment by yulin-li** [comment]
Hi @ghpfxf , I checked the SSML with emoji and this issue only reproes on Java SDK.

We will fix this issue in next SDK update 1.18.

As a workaround before next release, you can filter out all surrogate characters (most of them are un-readable) 

Refer this https://stackoverflow.com/questions/12867000/how-to-remove-surrogate-characters-in-java

**Comment by yulin-li** [comment]
Update: this error is fixed in 1.18, and released.
