### ISSUE TITLE
Word Granularity doesn't take effect in PronunciationAssessmentResult when using Java SDK and IOS SDK

### ISSUE THREAD

**Issue by huijuanl** [Azure-Samples/cognitive-services-speech-sdk#1121]
**Describe the bug**
Word Granularity doesn't take effect in PronunciationAssessmentResult when using Java SDK and IOS SDK

**To Reproduce**
1.Java SDK
We have no ios environment but reproduce the issue using java sdk.  We checked com.microsoft.cognitiveservices.speech.PronunciationAssessmentResult and find it has no propertiy related to "word":

Code to reproduce the issue:
```
public static void main(String[] args) throws InterruptedException, ExecutionException {
    SpeechConfig speechConfig = SpeechConfig.fromSubscription("xxxxxxxxxxx", "chinaeast2");
    fromFile(speechConfig);
}
public static void fromFile(SpeechConfig speechConfig) throws InterruptedException, ExecutionException {
    com.microsoft.cognitiveservices.speech.audio.AudioConfig audioConfig = com.microsoft.cognitiveservices.speech.audio.AudioConfig.fromWavFileInput("C:\\Users\\huijuanli\\source\\repos\\cognitive-services-speech-sdk\\quickstart\\python\\translator\\goodmorning.wav");
    SpeechRecognizer recognizer = new SpeechRecognizer(speechConfig, audioConfig);
    String referenceText = "Good Morning";    PronunciationAssessmentConfig pronumciationassessmentconfig = new PronunciationAssessmentConfig(referenceText,PronunciationAssessmentGradingSystem.HundredMark,PronunciationAssessmentGranularity.Word,true);
    pronumciationassessmentconfig.setReferenceText(referenceText);
    pronumciationassessmentconfig.applyTo(recognizer);
    Future<SpeechRecognitionResult> task = recognizer.recognizeOnceAsync();
    SpeechRecognitionResult result =  task.get();
    PronunciationAssessmentResult pronunciationResult = PronunciationAssessmentResult.fromResult(result);
    System.out.println(pronunciationResult.getFluencyScore());
}
```
Output:

![image](https://user-images.githubusercontent.com/30285223/121318374-c6c63a80-c93d-11eb-8ac2-395c24c937fc.png)
![image](https://user-images.githubusercontent.com/30285223/121318463-db0a3780-c93d-11eb-8926-0bc6cfcdbc40.png)

**Expected behavior**
Customer wants to use word property in Java SDK and IOS SDK.  Could you support them?

we use the python sdk and found the result was different from the java sdk. In the python SDK, Word Granularity takes effect.
In python sdk, azure.cognitiveservices.speech.speech.PronunciationAssessmentPhonemeResult involve the word property.

**Platform, Operating System, and Programming Language**
 - Programming language: , Java, , Objective-C

**Comment by yulin-li** [comment]
For Java and Objc, we do not parse the word level pronunciation result. You can get them from the json in recognition result.

e.g.
```java
result.getProperties().getProperty(PropertyId.SpeechServiceResponse_JsonResult);
```
