### ISSUE TITLE
Speech recognition continues despite of music at the beginning

### ISSUE THREAD

**Issue by markok20** [Azure-Samples/cognitive-services-speech-sdk#1122]
Hi

I have a jupyter notebook code ready to convert audio to text and I have tried it and it works fine with wav-files in English and Finnish.

But when I have audio files with waiting music at the beginning for about 3-4 seconds, it gives me this:
No speech could be recognized: NoMatchDetails(reason=NoMatchReason.InitialSilenceTimeout)

So I think the reason why the code does not work is the music at the beginning, how can I work with this so that it continues to recognize speech despite of the fact that there is waiting music for about 3-4 seconds at the beginning?

Part of my code is below:
------------------
audio_file_path = Path("audiofile").resolve()

speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)
audio_input = speechsdk.AudioConfig(filename=str(audio_file_path))
speech_recognizer = speechsdk.SpeechRecognizer(
        speech_config=speech_config, language="fi-FI", audio_config=audio_input)

def recognize_audio_file():
    print('Recognizing first result...')

    result = speech_recognizer.recognize_once()
    if result.reason == speechsdk.ResultReason.RecognizedSpeech:
        print('Recognized: {}'.format(result.text))
    elif result.reason == speechsdk.ResultReason.NoMatch:
        print('No speech could be recognized: {}'.format(result.no_match_details))
    elif result.reason == speechsdk.ResultReason.Canceled:
        cancellation_details = result.cancellation_details
        print('Speech Recognition canceled: {}'.format(cancellation_details.reason))
        if cancellation_details.reason == speechsdk.CancellationReason.Error:
            print('Error details: {}'.format(cancellation_details.error_details))

if __name__ == '__main__':
    recognize_audio_file()

-----------------

Many thanks for your advice beforehand.

Marko

**Comment by markok20** [comment]
Many thanks!

**Comment by jhakulin** [comment]
Closing the issue, let us know if there is any other issues.
