### ISSUE TITLE
Unity editor gets frozen after calling the speech service and relaunching it.

### ISSUE THREAD

**Issue by lingllting** [Azure-Samples/cognitive-services-speech-sdk#1123]
**Describe the bug**
I updated the latest unity plugin and found the unity editor got frozen quite often. After investigation, I found unity got frozen when calling the speech SDK for the first time and relaunching the editor, it could be 100% reproduced on Windows. 
For macOS, I also encountered this issue, but it did also happen during the compile process when I change some code and unity starts to compile.

**To Reproduce**
1. Run unity and call the Speech-to-text APIs.
2. Stop unity and run it again.

**Expected behavior**
The unity should be running as normal when restarting it.

**Version of the Cognitive Services Speech SDK**
Speech SDK 1.17.0
Unity version: 2019.4.6f1

**Platform, Operating System, and Programming Language**
- macOS
- Windows

**Comment by alondorn** [comment]
Hi, 
I'm experiencing the same issue. 
I found out that if I'm saving the scene\project, quitting Unity, and running the project again, it doesn't happen again for this project.

**Comment by lingllting** [comment]
> Hi,
> I'm experiencing the same issue.
> I found out that if I'm saving the scene\project, quitting Unity, and running the project again, it doesn't happen again for this project.

It's happening everytime to me, I ended up force quitting the unity editor often.

**Comment by jhakulin** [comment]
@lingllting Was this with Unity Editor? The problem could happen if all Speech SDK objects are not disposed when you stop the Editor. Do you see the problem if you use some of our Unity samples? For example: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/unity/from-microphone

**Comment by lingllting** [comment]
> @lingllting Was this with Unity Editor? The problem could happen if all Speech SDK objects are not disposed when you stop the Editor. Do you see the problem if you use some of our Unity samples? For example: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/unity/from-microphone

Thanks for the great information! I found I didn't dispose the speech recognize the same as what it is done in the example. After I dispose the recognize manually, the problem doesn't seem to occur again.

**Comment by jhakulin** [comment]
Thanks for letting us know, closing the case.
