### ISSUE TITLE
Long response time when using Speech To Text with Phrase List Grammar in Unity.

### ISSUE THREAD

**Issue by alondorn** [Azure-Samples/cognitive-services-speech-sdk#1124]
**Describe the bug:**
We're using the Speech SDK for Unity for Speech-To-Text purposes.
As we need to recognize custom phrases, we're using the PhraseListGrammar feature but we're experiencing a much longer response time when using the Phrase List feature than without it.
Without PhraseList, the recognition time is about 2 seconds while with PhraseList, it's about 4.5 seconds.
We tried both the RecognizeOnceAsync method and the StartContinuousRecognitionAsync method and with both of them, we're having the same results, although, with Continuous Recognition, the response time getting better as long as we're keeping the recognizer working for a long time, but after stopping it and starting it again, the response time is long again.

**To Reproduce:**
 void Start()
    {
           config = SpeechConfig.FromSubscription(subscriptionkey, "westeurope");
           pushStream = AudioInputStream.CreatePushStream();
           audioInput = AudioConfig.FromStreamInput(pushStream);
           recognizer = new SpeechRecognizer(config, audioInput);
           recognizer.Recognizing += RecognizingHandler;
           recognizer.Recognized += RecognizedHandler;
           recognizer.Canceled += CanceledHandler;
          if (keywords.Length > 0)
                {
                    phraseList = PhraseListGrammar.FromRecognizer(recognizer);
                    for (int i = 0; i < keywords.Length; i++) //Tested with arrays of up to five words.
                    {
                        phraseList.AddPhrase(keywords[i]);
                    }
                }
    }

public async void StartRecording()
    {
           if (!Microphone.IsRecording(Microphone.devices[0]))
            {
                audioSource.clip = Microphone.Start(Microphone.devices[0], true, 200, 16000);
            }
            await recognizer.StartContinuousRecognitionAsync().ConfigureAwait(false);
            lock (threadLocker)
            {
                recognitionStarted = true;
                Debug.Log("RecognitionStarted: " + recognitionStarted.ToString());
            }
    }

**Expected behavior:**
Same short recognition time as if not using Phrase List.

**Version of the Cognitive Services Speech SDK:**
Microsoft.CognitiveServices.Speech.1.17.0 (Unity package)

**Platform, Operating System, and Programming Language:**
Unity 2019.3.15f1,   Windows 10,	x64,	C#

**Comment by brandom-msft** [comment]
Hi @alondorn, thanks for your inquiry. Your suspicions are correct in that this increase in latency is not expected - what you're seeing is a known issue and is in active investigation by the service team. We'll look to provide updates as they become available.

**Comment by chschrae** [comment]
@brandom-msft  If there is an internal work item for this can you make sure this issue is linked there and close this issue. We can update the issue when the bug is resolved.

**Comment by jhakulin** [comment]
@alondorn There has been done improvements/fixes in the service side, could you please comment if you still see the problem?

**Comment by jhakulin** [comment]
Closing the issue, let us know if you see problems still.

**Comment by alondorn** [comment]
@jhakulin 
As I understand from the QA team, the problem seems to be solved now.
Thank you.

**Comment by hiddow** [comment]
@jhakulin Hi，The problem seems to have reappeared again!

**Comment by LenujiS** [comment]
I'm experiencing the same behavior with Microsoft Cognitive Services Speech SDK version 1.38.0.
