### ISSUE TITLE
Voice is not Recognized on medium or lower frequency. 

### ISSUE THREAD

**Issue by manju605** [Azure-Samples/cognitive-services-speech-sdk#1125]
**I have implemented Speaker Independent-Identification but every 10/6 times only voice is recognized.**

I have recorded speech in WAV format & Enrolled a user, & Identification audio i am getting from URL & converting to Buffer & enrolling for identification, this works but if audio volume is bit low(moderate) or low, its not identifying the voice. 

this happens both in profile enrolment audio(user recorded) &  as well  as audio used for Identification.

And my implementation is NodeJs

**Comment by glharper** [comment]
@manju605 Could you upload an example of a WAV that works, and one that doesn't? This may be a service issue.

**Comment by manju605** [comment]
> @manju605 Could you upload an example of a WAV that works, and one that doesn't? This may be a service issue.


https://drive.google.com/file/d/12Wpy3fU6HWmtK_jFYatSDNajOovYfOsD/view?usp=sharing
https://drive.google.com/file/d/1IE58rUTaW7S2OzM0RPjBFHxeHhuue3Wj/view?usp=sharing

These are two recording which failed.

**Comment by glharper** [comment]
@manju605 Thank you for the wav files. I actually don't know why they wouldn't be identified...I'm consistently getting a positive identification with a score of 0.74 using the attached code. Could you try this code on your side and let me know if you still get inconsistent results?

[independent-identification.js.1125.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6640301/independent-identification.js.1125.txt)
