### ISSUE TITLE
JavaScript sample passes string array to AddPhrase when SDK doc says it only takes string

### ISSUE THREAD

**Issue by noahsw** [Azure-Samples/cognitive-services-speech-sdk#1130]
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/c09ba521937e4dcc042a181d6595e39dd458753e/samples/js/browser/index.html#L744

According to https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.phraselistgrammar.addphrase?view=azure-dotnet, `addPhrase` only accepts a string. Therefore, shouldn't the sample script call `addPhrase` for each array element in `.split(";")` ?

**Comment by glharper** [comment]
@noahsw That link is to the C# documentation. The JS documentation can be found [here](https://docs.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/phraselistgrammar?view=azure-node-latest).

Thanks for using Speech SDK!
