### ISSUE TITLE
Error on deploying to AppService

### ISSUE THREAD

**Issue by manju605** [Azure-Samples/cognitive-services-speech-sdk#1131]
**I Have implemented Azure Speaker Recognition which works in local but gives error on deploying to azure**

I get below error when i deploy to my app service & it work fine in my local PC &  when i uninstall this package  'microsoft-cognitiveservices-speech-sdk', 

![image](https://user-images.githubusercontent.com/60870713/121886859-99113500-cd33-11eb-91ce-a69c6ed8262c.png)

**Comment by trrwilson** [comment]
Hello!

The JS Speech SDK takes a dependency on `username-sync` but does not invoke this call stack directly. From a quick search, it appears this is typically related to an expected system path (such as `/etc/passwd`) not being accessible and is often resolved by fixing a file permissions issue or ensuring a location is appropriately mounted (if an image is involved). One of the responses here (note/warning: external link) suggests that turning on verbose logging via `npm_config_loglevel=verbose` may help track down the particular reference that isn't accessible : https://stackoverflow.com/questions/61961485/a-system-error-occurred-uv-os-get-passwd-returned-enoent-no-such-file-or-direc

Could you please give that a shot and investigate along those lines? Given this is a relationship between an NPM dependency and the specific environment that's in use, the Speech SDK team won't have a lot of specific information we can recommend--this is happening outside of the project code.

**Comment by manju605** [comment]
Hi,

on turning on npm_config_loglevel=verbose its not showing any further details still same.

![image](https://user-images.githubusercontent.com/60870713/122073935-6f7d0a00-ce16-11eb-84e7-de774d20eb28.png)

**Comment by glecaros** [comment]
Hi @manju605, were you able to resolve this issue by adding the volume mapping that @trrwilson suggested? (from a quick read this does seem related to `/etc/passwd` not being accessible from the image so `-v /etc/passwd:/etc/passwd` could help fix this)

**Comment by pankopon** [comment]
Closed since no further update in two weeks. It would seem the described file access is not supported in a sandbox on Azure.
