### ISSUE TITLE
Some Digits were not recognized by a speech recognizer 

### ISSUE THREAD

**Issue by yveskaufmann** [Azure-Samples/cognitive-services-speech-sdk#1132]
**Describe the bug**

Our use case is that we want to enable our users to tell us there identification number,
which is numeric with a specific length.  We are concatenating successful speech recognition 
results until we have collected enough digits, so that they match the required digit count of our ids. 
Note that we are using the recognizer in a phone-bot, but for sack of simplictily we are ignoring this for now. 

 
The issue which we are facing is that, depending on the speaker or speaking speed that some digits
aren't recognized by the recognizer. 

## Problem 

Let's imagine a user wants to tell the id __0987656__, 
some users make small pauses every two digits, which we will display here 
in the example with a underscore e.g:  __"09_87_65_4"__.

In the log output below you can see that the 7 was not recognized by recognizer.

```java
Started the SpeechRecognitionSession 45fd4a833b6146d5ac6329e696290adb
StartOfSpeechDetected for session 45fd4a833b6146d5ac6329e696290adb
Recognizing "text"=0 ResultId:b26ab8a9436a4b8ab3147a1f62ab340c Status:RecognizingSpeech Recognized text:<0>.
Recognizing "text"=09 ResultId:2435b6e3bf1e49ea9f824296d9adadb1 Status:RecognizingSpeech Recognized text:<09>.
Recognizing "text"=098 ResultId:18908db21194406e82ed254aed495708 Status:RecognizingSpeech Recognized text:<098>.
** Intermediate Recognized text="" ResultId:aa8c3612b12140fea972ddfb334120cc Status:NoMatch Recognized text:<>.
EndOfSpeechDetected for session 45fd4a833b6146d5ac6329e696290adb
StartOfSpeechDetected for session 45fd4a833b6146d5ac6329e696290adb
Recognizing "text"=6 ResultId:9fda802ac20b48e0a831b008c8c00158 Status:RecognizingSpeech Recognized text:<6>.
Recognizing "text"=65 ResultId:131eb45983f0475db4dd03b07c7fa845 Status:RecognizingSpeech Recognized text:<65>.
** Intermediate Recognized text="65" ResultId:69e6d4e2506c4d36bfde3370e97170d9 Status:RecognizedSpeech Recognized text:<65>.
EndOfSpeechDetected for session 45fd4a833b6146d5ac6329e696290adb
StartOfSpeechDetected for session 45fd4a833b6146d5ac6329e696290adb
Recognizing "text"=4 ResultId:2c879fd6e9c84e158bdec1f35b7e637e Status:RecognizingSpeech Recognized text:<4>.
** Intermediate Recognized text="4" ResultId:e443b9379eb54e93b957ec329c657554 Status:RecognizedSpeech Recognized text:<4>.
```

We would expect that the digit 7 is recognized as well.

### Demo Code 

This snippet below demonstrates how we used the speech recognizer in the example above, in which we passed in a pre-recorded 
speech from a user. In the pre-corded audio_09_87_65_4.wav, a speaker enumerates the digits  __"09_87_65_4"__ by 
keeping longer pauses inbetween the groups.

NOTE: In our concrete application we are using PushAudioInputStream.

```java
package com.parloa.phonegateway;

import com.google.common.io.ByteStreams;
import com.microsoft.cognitiveservices.speech.PropertyId;
import com.microsoft.cognitiveservices.speech.ServicePropertyChannel;
import com.microsoft.cognitiveservices.speech.SpeechConfig;
import com.microsoft.cognitiveservices.speech.SpeechRecognizer;
import com.microsoft.cognitiveservices.speech.audio.AudioConfig;
import lombok.Data;
import lombok.extern.slf4j.Slf4j;

import java.io.*;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.atomic.AtomicBoolean;

@Slf4j
public class DemoApplication {

	public static void main(String[] args) throws ExecutionException, InterruptedException {

		Options options = parseArguments(args);

		AtomicBoolean continueToListen = new AtomicBoolean(false);
		StringBuffer buffer = new StringBuffer();

		SpeechConfig speechConfig = SpeechConfig.fromSubscription(
			"*******", "westeurope"
		);

		speechConfig.setSpeechRecognitionLanguage("de-DE");
		speechConfig.setProperty(PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs, options.getInitialSilenceTimeoutMs());
		speechConfig.setProperty(PropertyId.SpeechServiceConnection_EndSilenceTimeoutMs, options.getEndSilenceTimeoutMs());
		speechConfig.setServiceProperty("punctuation", "none", ServicePropertyChannel.UriQueryParameter);
		speechConfig.setProperty(PropertyId.Speech_LogFilename, "speechLog.txt");

		AudioConfig audioConfig;

        // We listen either from the local microphone or we pass a precorded wavefile.
		if (options.useDemoFile) {
			File audioFile = getDemoAudioFile();
			audioConfig = AudioConfig.fromWavFileInput(audioFile.getPath());
		} else {
			audioConfig = AudioConfig.fromDefaultMicrophoneInput();
		}

		SpeechRecognizer speechRecognizer = new SpeechRecognizer(speechConfig, audioConfig);

		speechRecognizer.recognized.addEventListener((s, e) -> {

			String text = e.getResult().getText();
			buffer.append(text);
			log.info("** Intermediate Recognized text=\"{}\" {}", text, e.getResult());
            
            // We wait until we have recognized enough digits.
			if (buffer.length() < 7) {
				continueToListen.set(true);
			} else {
				log.info("Joinded Recognized text=\"{}\" {}", buffer.toString(), e.getResult());
				continueToListen.set(true);
				buffer.delete(0, buffer.length());
			}

			e.getResult().close();
		});

		speechRecognizer.recognizing.addEventListener((s, e) -> {
			log.info("Recognizing \"text\"={} {}", e.getResult().getText(), e.getResult());
			e.getResult().close();
		});

		speechRecognizer.speechStartDetected.addEventListener((s, e) -> {
			log.info("StartOfSpeechDetected for session {}",
				e.getSessionId()
			);
		});

		speechRecognizer.speechEndDetected.addEventListener((s, e) -> {
			log.info("EndOfSpeechDetected for session {}",
				e.getSessionId()
			);
		});

		speechRecognizer.sessionStarted.addEventListener((s, e) -> {
			log.info("Started the SpeechRecognitionSession {}",
				e.getSessionId()
			);
		});

		speechRecognizer.sessionStopped.addEventListener((s, e) -> {
			log.info("Stopped the SpeechRecognitionSession {}",
				e.getSessionId()
			);
		});
		;

		speechRecognizer.canceled.addEventListener((s, e) -> {
			log.error("SpeechRecognizer canceled. Result {}", e.getResult());
			log.error("SpeechRecognizer canceled. Error Code {}",  e.getErrorCode());
			log.error("SpeechRecognizer canceled. Error Details {}", e.getErrorDetails());
			log.error("SpeechRecognizer canceled. {}", e);
		});

		speechRecognizer.startContinuousRecognitionAsync().get();
	}

	@Data
	public static class Options {
		boolean useDemoFile = false;
		String initialSilenceTimeoutMs = "5000";
		String endSilenceTimeoutMs = "1000";
	}

	static Options parseArguments(String[] args) {
		Options op = new Options();
		for (int i = 0; i < args.length; i++) {
			String arg = args[i];
			switch (arg) {
				case "--help":
				case "-h":
					System.out.println("STT Demo");
					System.out.println("");
					System.out.println("Options:");
					System.out.println("  -h, --help Display this help message");
					System.out.println("  -i, --initialSilence [ms] The initial timeout in ms default is 5000");
					System.out.println("  -e, --endSilence [ms] The end timeout in ms default is 1000");
					System.out.println(" --demo Stream the sample demo file to azure");

					System.exit(0);
					break;

				case "--demo":
					op.setUseDemoFile(true);
					break;

				case "--initialSilence":
				case "-i":
					if (i+1 < args.length) {
						op.setInitialSilenceTimeoutMs(args[i+1]);
					}
					break;

				case "--endSilence":
				case "-e":
					if (i+1 < args.length) {
						op.setEndSilenceTimeoutMs(args[i+1]);
					}
					break;

			}
		}

		return op;
	}

	private static File getDemoAudioFile() {
		File audioFile = new File("audio_09_87_65_4.wav");
		if (!audioFile.exists()) {
			ClassLoader cl = DemoApplication.class.getClassLoader();

			try (FileOutputStream fs = new FileOutputStream(audioFile.getName())) {
				try (InputStream in = cl.getResourceAsStream(audioFile.getName())) {
					ByteStreams.copy(in, fs);
				}
				;
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
		return audioFile;
	}
}
```

**To Reproduce**
1. Build a jar from the code above and run it 
2. Run java -jar demo.jar 
3. Slowly speak into you local microphone the digits _09_87_65_4_.

**Expected behavior**
We would expect in this particular case the the digit 7 will be recognized.

**Version of the Cognitive Services Speech SDK**
1.17.0

**Platform, Operating System, and Programming Language**
 - OS: Linux
 - Hardware - x64.
 - Programming language: Java

**Additional context**
- [speechLog.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6649646/speechLog.txt)

Thank you in advance 

Yves

**Comment by trrwilson** [comment]
Thank you for reporting this issue! Your code looks very reasonable. From the behavior you're seeing with the digit missing, it seems like the end silence timeout is segmenting the digit sections with timing that degrades accuracy (e.g. *immediately* before the new section) -- that, or some of the audio is being dropped on a subsequent recognition.

A couple of followup questions:

- Does this reproduce across different silence timeout configurations? Additionally, do you observe those configurations taking the expected effect when you apply them?
- Would it be possible to share the repro .wav file for us to analyze? I'm not able to readily reproduce with my microphone just now; that isn't necessarily surprising given how timing-sensitive this likely is.

Thanks!

**Comment by yveskaufmann** [comment]
Thank you for responding so fast! 

> Does this reproduce across different silence timeout configurations? Additionally, do you observe those configurations taking the expected effect when you apply them?

I have experimented a bit with  _SpeechServiceConnection_EndSilenceTimeoutMs_ when set to ~0-5 the issue isn't anymore reproducible with our pre-recorded wave file, but not sure yet if this would fix the issue for other cases as well. 

I experiment also with _SpeechServiceConnection_InitialSilenceTimeoutMs_ and notice no impacts on the digit recognition 
It behaved liked described in the documentation that the ASR wait the specified time, if it received only silence input, until it responded back to us.

> Would it be possible to share the repro .wav file for us to analyze? I'm not able to readily reproduce with my microphone just now; that isn't necessarily surprising given how timing-sensitive this likely 

My colleague kindly gave us permission to share the audio file with you.

[audio_09_87_65_4.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6655414/audio_09_87_65_4.zip)

Thank You!

**Comment by pankopon** [comment]
@yveskaufmann Sorry for the long delay in response. EndSilenceTimeout, in this context, modifies the processing of individual utterances/phrases within a long-running session, and in your case this appears to cause problems with some short utterances. I reproduced the original issue using your audio file, but after disabling EndSilenceTimeout by setting the value to 0, all the digits are recognized correctly. Can you please confirm if this solution works for you?
