### ISSUE TITLE
SR and TTS connection bug

### ISSUE THREAD

**Issue by incomingflyingbrick** [Azure-Samples/cognitive-services-speech-sdk#1134]
platform android
java sdk versin 1.1.7
during 8 hours of none stop SR and TTS test
I found there is a high chance of getting connection error, like can't connect to server.

for TTS the error msg is like this:
**Error:Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 7. USP state: 2. Received audio size: 0 bytes. ErrorCode:ConnectionFailure**

for SR the error msg is like this:
**Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 7. SessionId: 4f4c2054a40f4f1b849e95790361ad85**

**Comment by chschrae** [comment]
Thanks for reaching out. I know the service team is constantly working on making sure their "up" time is as high as possible. Do you have any other information on this? Does it happen every time or just some times? Does it always occur at the same period of time? 

Without more concrete information this doesn't really sound like something that the SDK team can help with. It may be the service or related to the specific environment. If we don't have enough to go on or find out there isn't anything we can do, we will close this issue.

**Comment by incomingflyingbrick** [comment]
Hi, this problem occurs randomly.
Is there a limit on how many socket connections we can have with one
subscription key?
If there is a limit , what should I do to make every user can connect to
server when needed.

**Comment by chschrae** [comment]
Hi @incomingflyingbrick there is no limit.

One thing might be to check that all the recognizer objects are closed and properly cleaned up.

Otherwise without more information it would be hard to look into.
You could set the log file property and generate some logs, though with your large testing it may get too large.
speechConfig.setProperty(PropertyId.Speech_LogFilename, "./sdk.log");
Are you able to show your code?

**Comment by pankopon** [comment]
@incomingflyingbrick Can you please provide more information as requested? Also be sure to update your SDK to the latest 1.18.0 release, just in case.

**Comment by pankopon** [comment]
Closing the item since no further updates received, please open a new issue if more support is needed.
