### ISSUE TITLE
Quickstart js speaker-recognition Unexpected token R in JSON at position 0

### ISSUE THREAD

**Issue by yanhuibin315** [Azure-Samples/cognitive-services-speech-sdk#1136]
**Describe the bug**
When I run ```node dependent-verification.js```, I got this ERROR: SyntaxError: Unexpected token R in JSON at position 0.

**To Reproduce**
1. clone the main code
2. cd quickstart/javascript/node/speaker-recognition/verification/
3. npm install
4. node dependent-verification.js

**Expected behavior**
Maybe I expected it will verification wav file or output something like cosole.log.

**Version of the Cognitive Services Speech SDK**
I use main branch and I guess maybe it's 1.6 version.

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - x64
 - Programming language: JavaScript

**Additional context**
 - Error Message:
```
> node .\dependent-verification.js
Create Profile ERROR: SyntaxError: Unexpected token R in JSON at position 0
```
- Verify subkey and endpoint: I use them in postman and I get the right response. So I gusses my subkey and region is TRUE.

**Comment by glharper** [comment]
@yanhuibin315 Thanks for using Speech SDK. Did you remember to add a subscription key and region to dependent-verification.js?

**Comment by yanhuibin315** [comment]
> @yanhuibin315 Thanks for using Speech SDK. Did you remember to add a subscription key and region to dependent-verification.js? (Note that speaker verification is currently available only in the westus region.)

yeah~ And I got speechConfig Succeed. I guess it's wrong when I use 
```
...
client.createProfileAsync(
    sdk.VoiceProfileType.TextIndependentIdentification,
    locale,
    function (result) {
      console.log("I got result.")
      var profile = result;
      ...
```
And "I got result" not output on powershell.

**Comment by glharper** [comment]
@yanhuibin315 That first parameter should be sdk.VoiceProfileType.TextDependentVerification in dependent-verification.js. Using a VoiceProfileType.TextIndependentIdentification voice profile in verification scenarios will not work. Are there modifications you made to dependent-verification.js, besides adding the subscription key and region? [This line](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/2d35d4cf839867e7d76d6b2738843cdc1ad72979/quickstart/javascript/node/speaker-recognition/verification/dependent-verification.js#L26) from the quickstart uses the correct profile type...

**Comment by yanhuibin315** [comment]
Thanks for your reply @glharper . And I got my fault!! I use the wrong region. ```westuse``` is OK, but I used ```https://westus.api.cognitive.microsoft.com```. 🙏.
