### ISSUE TITLE
AudioConfig.FromMicrophoneInput on Unity Android cannot use Bluetooth Microphone

### ISSUE THREAD

**Issue by huy-ffd** [Azure-Samples/cognitive-services-speech-sdk#1137]
### **Describe the bug**
I want to use the **from-microphone** example with a **Bluetooth microphone** for Unity Android ARM64, and I do not want to use the _Built-in Microphone_.

**To Reproduce**
I tried using a **custom AudioConfig** in order to use my **Bluetooth Microphone**.

**HelloWorld.cs** from the **from-microphone** example was the script that I tried to add to. Speech To Text. Unity.
- https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/csharp/unity/from-microphone/Assets/Scripts/HelloWorld.cs

At the following section, I made a simple addition.
```
// Creates an instance of a speech config with specified subscription key and service region.
// Replace with your own subscription key and service region (e.g., "westus").
var config = SpeechConfig.FromSubscription("YourSubscriptionKey", "YourServiceRegion");

// Make sure to dispose the recognizer after use!
using (var recognizer = new SpeechRecognizer(config))
```

SpeechRecognizer can take a custom AudioConfig, so I wanted to use:

```
AudioConfig.FromMicrophoneInput("");
```

FromMicrophoneInput takes the **deviceName** as a string.

1. I tried Android side, accessing MicrophoneInfo **getAddress**
2. I tried Android side, accessing MicrophoneInfo **getId**
3. I tried Android side, accessing MicrophoneInfo **getDescription**
4. I tried the Unity microphone names gotten through **Microphone.devices**

I supplied the **AudioConfig** to the SpeechConfig, but recognition would not work in each case.

**Expected behavior**

I expected to use `Audioconfig.FromMicrophoneInput` with a Device Name to supply the speech recognizer with my Bluetooth Microphone.

But I believe that I am not using the correct Device Name for the Unity Android configuration, but the following documentation does not talk about Unity Android Selecting a Device:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-select-audio-input-devices

Regardless of the device name that I have tried, I will get a Canceled error on the Unity app and the speech recognition will not succeed: `ResultReason.Canceled`

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using?
Microsoft.CognitiveServices.Speech.1.17.0.unitypackage

**Platform, Operating System, and Programming Language**
 - OS: Android
 - Hardware - ARM64
 - Programming language: C#

**Comment by jhakulin** [comment]
@huy-ffd Thanks for the report. Currently Speech SDK audio device selection using microphone device name is not supported for Bluetooth mics on Android. Does Unity Microphone provide the access to Bluetooth mic devices on Android (https://docs.unity3d.com/ScriptReference/Microphone-devices.html) ? If yes, then you can use following sample 
to stream audio to Speech SDK from Unity microphone.
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/unity/from-unitymicrophone

**Comment by huy-ffd** [comment]
Thank you @jhakulin! It was delightful to see your helpful answer earlier in the morning for me.

Unity Microphone does allow access to Bluetooth Microphone (name and device) on Android, but for my current Android board, and experimenting with the Unity Microphone alone, my board does not place nicely with Unity Microphone in recording tests, and in the example above.

I'll try with my Samsung S21 and see if the example works for Bluetooth or not and write a follow-up comment.

**Comment by huy-ffd** [comment]
I have tested a Samsung S21 with the https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/unity/from-unitymicrophone

And a Bluetooth Microphone. When explicitly selecting the Bluetooth Microphone, I can confirm that this does work on the Samsung S21 with the above example.

My custom Android board does not work with the Unity Microphone recording, but that's my problem, so I'll close this issue.

Thanks! jhakulin!
