### ISSUE TITLE
SPXERR_GSTREAMER_NOT_FOUND_ERROR, Python under Windows 10

### ISSUE THREAD

**Issue by MBelkhechine** [Azure-Samples/cognitive-services-speech-sdk#1138]
**Describe the bug**
Hi, 

I am unable to use codec compressed audio input with Python. I followed the instructions described under [this documentation](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams?tabs=debian&pivots=programming-language-python) to configure GStreamer 1.18.3. I have verified the installation by running the command  gst-inspect-1.0.exe --version  and I got the following output: 

gst-inspect-1.0 version 1.18.3
GStreamer 1.18.3
Unknown package origin

 [The provided python sample code](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams?tabs=debian&pivots=programming-language-python) works fine under Ubuntu 18.04 and I was able to pass compressed audio input and get the recognized text but under Windows, I get the following error: 

line 883, in _get_impl
    return reco_type._from_config(speech_config._impl, auto_detect_source_language_config._impl, audio_config._impl)
RuntimeError: Exception with an error code: 0x29 (SPXERR_GSTREAMER_NOT_FOUND_ERROR)
[CALL STACK BEGIN]

    > property_bag_copy

    - property_bag_copy

    - property_bag_copy

    - property_bag_copy

    - property_bag_copy

    - recognizer_create_speech_recognizer_from_config

    - recognizer_create_speech_recognizer_from_auto_detect_source_lang_config

    - 00007FF978F4A206 (SymFromAddr() error: Attempt to access invalid address.)

    - 00007FF978F87A77 (SymFromAddr() error: Attempt to access invalid address.)

    - 00007FF978F88A7D (SymFromAddr() error: Attempt to access invalid address.)

    - PyArg_ParseTuple_SizeT

    - PyEval_EvalFrameDefault

    - PyFunction_Vectorcall

    - PyEval_EvalFrameDefault

    - PyObject_GC_Del

    - PyFunction_Vectorcall

[CALL STACK END]

**Version of the Cognitive Services Speech SDK**
1.17.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - i5-8365U
 - Programming language: Python version 3.9.5

**Comment by ralph-msft** [comment]
Thanks for trying the Cognitive Services Speech SDK, and sorry to see that you are running into issues.

For Windows 10 using version 1.17 of the SDK, you'll need to follow these steps:
1. Download and install version the version 1.19.1 MSVC x86_x64  of the GStreamer DLLs. You can find the download links [here](https://gstreamer.freedesktop.org/documentation/installing/on-windows.html?gi-language=c)
    * If you have any previous versions of GStreamer installed, please uninstall those first 
2. Set ```GSTREAMER_ROOT_X86_64``` user environment variable to ```C:\gstreamer\1.0\msvc_x86_64```
3. Append the following to your ```PATH``` user environment variable: ```C:\gstreamer\1.0\msvc_x86_64\bin```
4. Reboot your machine to make sure that all running programs get the updated environment variables

**Comment by MBelkhechine** [comment]
Hi Ralph,

thank you. It worked :)
