### ISSUE TITLE
Do we have container image for Speaker Recognition Service

### ISSUE THREAD

**Issue by manju605** [Azure-Samples/cognitive-services-speech-sdk#1139]
I have developed Speaker Recognition service in my node application, now i need to deploy that to AzureApp Service, 
but due to this issue [uv_os_getpassword](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1131), i am unable to the direct deployment to AppService, so for Containerising I dont see any Image mentioned in docs [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-container-howto?tabs=stt%2Ccsharp%2Csimple-format), do we have a image for that?

**Comment by chschrae** [comment]
Hi @manju605,

I'm sorry to say, currently there is no container image for the Speaker Recognition Service.

Thank you for your question and for reaching out. I have made your request known to the Speaker Recognition team and they have the task on their backlog.
