### ISSUE TITLE
Connection failed (no connection to the remote host). Internal error: 1 - from Azure Function

### ISSUE THREAD

**Issue by crgarcia12** [Azure-Samples/cognitive-services-speech-sdk#114]
**Describe the bug**

I'm following this guide:
https://github.com/Microsoft/vscode-iot-workbench/blob/master/docs/iot-devkit/devkit-translator.md

The azure function code:
            var speechTranslation = new SpeechTranslation(speechSubscriptionKey, speechServiceRegion, log);
            string result = await speechTranslation.TranslationWithAudioStreamAsync(req.Body, fromLanguage);
            log.LogInformation("Translation result: " + result);

The printed logs:

Session started event.	
2018-12-05T16:01:05.333	CANCELED: Reason=Error	
2018-12-05T16:01:05.333	CANCELED: ErrorCode=ConnectionFailure	
2018-12-05T16:01:05.333	CANCELED: ErrorDetails=Connection failed (no connection to the remote host). Internal error: 
2018-12-05T16:01:05.333	CANCELED: Did you update the subscription info?

**To Reproduce**
Follow this guide, and create the azure function that communicate with speach recognition
https://github.com/Microsoft/vscode-iot-workbench/blob/master/docs/iot-devkit/devkit-translator.md

**Version of the Cognitive Services Speech SDK**
    <PackageReference Include="Microsoft.Azure.Devices" Version="1.17.1" />
    <PackageReference Include="Microsoft.CognitiveServices.Speech" Version="1.1.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.*" />

**Platform, Operationg System, and Programming Language**
 - OS: Windows azure function

**Comment by crgarcia12** [comment]
Seems the Azure function staying in North Europe cannot talk to Cognitive services in westeurope. I created another CogServices in North Europe and it worked

**Comment by wolfma61** [comment]
closng this ....
