### ISSUE TITLE
Got the errror when build on AppStore 

### ISSUE THREAD

**Issue by duydtdev** [Azure-Samples/cognitive-services-speech-sdk#1141]
I got the below errors. I'm using version 1.17.0.

Dear Developer,

We identified one or more issues with a recent delivery for your app.  Please correct the following issues, then upload again.

ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.

ITMS-90562: Invalid Bundle - There's an issue with the app's bitcode compilation. Rebuild the app using the current public (GM) version of Xcode and upload it again.

ITMS-90562: Invalid Bundle - The app submission can not be successfully recompiled from bitcode due to missing symbols during linking. You can try to reproduce and diagnose such issues locally by following the instructions from: https://developer.apple.com/library/archive/technotes/tn2432/_index.html

I also found out the same issue here (https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/702)
But could you help tell me that did you fixed this issue? And how can I deploy my application to AppStore?

**Comment by jhakulin** [comment]
@duydtdev Thanks for the report. Which architectures you are targeting in your app ? Speech SDK supports arm64, so in case you have armv7 in the list of supported architectures, please remove it.

**Comment by duydtdev** [comment]
@jhakulin Thanks for your reply. I turn off Bitcode when deploy, then it works fine. I will try your way once. Thank you
