### ISSUE TITLE
Getting "Undefined" text when Using the Azurer Cognitive Speech to Text Service

### ISSUE THREAD

**Issue by vinay047** [Azure-Samples/cognitive-services-speech-sdk#1143]
Hi All,

I am trying the integrate the Speech to Text azure service in my node js code. While testing I am getting the following error,

**RECOGNIZED: Text=undefined**

please find below the code snippet, which will give you clear idea on how we are using the azure speech to text service. Search couple of blogs but couldn't able to find out the solution. if you guys point out in the right direction that will really  helpful.

Could able to find out the reason behind this. 

      const fs = require('fs');
      const sdk = require("microsoft-cognitiveservices-speech-sdk");
      const speechConfig = sdk.SpeechConfig.fromSubscription("<paste-your-subscription-key>", "<paste-your-region>");

let pushStream = sdk.AudioInputStream.createPushStream();
#### Convert audio chunk into Raw buffer######

    const muLawDecoder = (muLawByte) => {
        muLawByte = ~muLawByte;
        const sign = muLawByte & 0x80;
        const exponent = (muLawByte & 0x70) >> 4;
       let data = muLawByte & 0x0f;
         data |= 0x10;
         data = data << 1;
         data = data + 1;
         data = data << (exponent + 2);
         data = data - 0x84;
         const r = sign === 0 ? data : data * -1;
        return r;
    };

      function mulawToPcm(muLawBuffer) {
        const outBuffer = Buffer.alloc(muLawBuffer.length * 2);

         let i = 0;
        for (const b of muLawBuffer) {
        outBuffer.writeInt16LE(muLawDecoder(b), i);
         i = i + 2;
      }
         return outBuffer;
     }

        #########

       //Using websokeck to get the Live Text in UI 

        wss.on("connection", function connection(ws, req) {
         
        // On incoming message to websocket, in this case it's assuming Twilio
          ws.on("message", function incoming(message) {
          const msg = JSON.parse(message);
      
        switch (msg.event) {
          case "connected":
             console.log(`A new call has connected.`);
            //End
              break;
         case "start":
           ################################# Azure Speech to text Code #################
         let audioConfig = sdk.AudioConfig.fromStreamInput(pushStream);
        let recognizer = new sdk.SpeechRecognizer(speechConfig, audioConfig);
        recognizer.recognizeOnceAsync(result => {
        console.log(`RECOGNIZED:AZURE  Text=${result.text}`);
        const text = result.text
        wss.clients.forEach((client) => {
           if (client.readyState === WebSocket.OPEN) {
            if (prefix === "recognized") {
            client.send(
              JSON.stringify({
                event: "interim-transcription",
                text,
              })
            );
          }
        }
       });
    
    });  

          break;
        case "media":
      
          if (msg.media.track == "outbound") {
			  // msg.media.payload will be base 64 endcode and this function "mulawToPcm"
			  //will convert base64 into raw buffer and this raw buffer we are passing to the audio //Config
            const raw = Buffer.from(msg.media.payload, "base64");
            pushStream.write(mulawToPcm(raw), null, () => {});
          } 
          
          break;
        case "stop":        
		   pushStream.close();         
          break;
        }
      });
         ws.on("close", function close(event) {
         wsMap.set(ws.worker, null);
      });

Note : - I am Using Twilio service to get the Outbound Call in my application. 
Angular 9 : Frontend .
Nodejs : Backend.

Like using as reference for this code -
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-speech-to-text?tabs=windowsinstall&pivots=programming-language-nodejs#recognize-from-in-memory-stream

And Following this Topic :--  Recognize from in-memory stream

Thanks in advance!

**Comment by rhurey** [comment]
Something (unknown) is likely going wrong with the recognizeOnceAsync() call if you're getting an empty text back.

To check, the result object returned from recognizeOnceAsync will have a reason field and possibly an errorDetails populated.
`
console.log(`RECOGNIZED:AZURE  Reason=${sdk.ResultReason[result.reason]}`);
console.log(`RECOGNIZED:AZURE  ErrorDetails=${result.errorDetails}`);
`

**Comment by vinay047** [comment]
Thanks for your response  @rhurey, 

I will try to populate the error details by using your suggestion and will notify you on this.

**Comment by vinay047** [comment]
Hey @rhurey ,

I tried your suggestion and I am getting the following error :-

**RECOGNIZED:AZURE Reason=Canceled
RECOGNIZED:AZURE ErrorDetails=Unable to contact server. StatusCode: 500, undefined Reason: TypeError [ERR_INVALID_URL]: Invalid URL: wss://EastUS.stt.speech.microsoft.com/speech/recognition/interactive/cognitiveservices/v1?language=en-US&format=simple&Ocp-Apim-Subscription-Key=XXXXXXXXXXXXX-ConnectionId=53XXXXXXX2CB
RECOGNIZED:AZURE Text=undefined**

Kindly request you to provide some thoughts on this.

Thanks.

**Comment by glharper** [comment]
@vinay047 Are you still able to reproduce this with version 1.19? Does this happen with a different key/region?

**Comment by pankopon** [comment]
Closed as no customer update, please open a new issue if more support is needed.
