### ISSUE TITLE
Batch:  Punctuation - Automatic and Dictated vs Dictated Only - capitalization still applied?

### ISSUE THREAD

**Issue by kleindev** [Azure-Samples/cognitive-services-speech-sdk#1146]
We've been trying to track down what appears to be random capitalization - but I think we've narrowed it down to punctuation modes.  If we do Dicated only it appears to leave capitalization where Automatic and Dictated would insert a period

Is it possible to control capitalization when _not_ using Automatic punctuation ? 

I have yet to try no punctuation - I still want the benefit of transcribing dictated punctuation, but we don't want the capitalization of inferred / automatic punctuation

**Comment by zhouwangzw** [comment]
If I understand correctly, you are using batch transcription, right? In batch transcription, the punctuationMode property is used to configure different punctuation options, and you can find different forms of recognized phrases in the result file, like Display, Lexical, ITN, masked ITN, and etc. Please find [the link](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription#configuration-properties)  for details. However, currently, it is not supported to use punctuation but without capitalization. If you do not want capitalization at all, would it be possible that you convert all texts into lower case after receiving the transcription result? 

Thanks.

**Comment by kleindev** [comment]
We are using the Display format.  The feedback we are getting from the editors is that basic words appear to be capitalized mid-sentence.  It is not apparent on why the word was capitalized - perhaps there was a pause in the audio or something random?  It would be nice to have an option to transcribe Dictated punctuation and reduce what looks to be over eager capitalization. 

We may look into making everything lowercase and then only capitalizing around dictated periods ourselves - just wanted to check if there was any options to control modes/methods batch uses to capitalize words

**Comment by zhouwangzw** [comment]
Would it be possible to share the transcription results, probably also the expected ones, so that we can ask the science team to look into that? You can create a Azure support ticket if you want to send the data privately to us. 

Thanks!

**Comment by pankopon** [comment]
Closed as there has been no further update since June. Please open a new issue if more support is needed.
