### ISSUE TITLE
Speaker separation not work in Batch Transcription API

### ISSUE THREAD

**Issue by yanhuibin315** [Azure-Samples/cognitive-services-speech-sdk#1150]
**Describe the bug**
I want to use speaker separation in batch transcription api. But it maybe not work. I use "katiesteve.wav" to speech-to-text and set diarizationEnabled to TRUE. But I just get speaker 1 in the result.json. Can anyone tell me why not speaker 2? 

**To Reproduce**
1. clone the ```cognitive-services-speech-sdk``` code and I found a wav file named "katiesteve.wav".
2. change wav ac and bytes by ffmpeg
``` ffmpeg -i <input_file.wav> -ac 1 -b 256000 -y <output_file.wav> ```
3. send a request to "/speechtotext/v3.0/transcriptions" and this my body
```json
{
  "contentUrls": [
    "*******************"
  ],
  "properties": {
    "diarizationEnabled": true,
    "wordLevelTimestampsEnabled": true,
    "punctuationMode": "DictatedAndAutomatic",
    "profanityFilterMode": "Masked"
  },
  "locale": "en-US",
  "displayName": "katiesteve by diarization"
}
```
4. when it shows sccueed. I got the [report.json](https://drive.google.com/file/d/1w_eP1OP2kiq0jXc5Ete7-bt4IBpQ-BiQ/view?usp=sharing)
5. Actrually it should talk by two persons, but the result.json just show speaker 1.

**Expected behavior**
It should show two speaker in conversation but one.

**Platform, Operating System, and Programming Language**
 - Windows
 - Postman

**Additional context**
 - Wav file: https://drive.google.com/file/d/1OzU0K79RjKCaoYhpxvF45jH5vppVhSS4/view?usp=sharing
 - report.json: https://drive.google.com/file/d/1w_eP1OP2kiq0jXc5Ete7-bt4IBpQ-BiQ/view?usp=sharing

**Comment by zhouwangzw** [comment]
Thanks for reporting. We are checking.

**Comment by zhouwangzw** [comment]
@yanhuibin315 Thanks for reporting issue. Our scientist team is looking into it and trying to improve diarization model to reduce error rate. However, this might take some time until the new model is published, and at this moment we do not have ETA for that yet. Sorry for the inconvience!
