### ISSUE TITLE
chinaeast2 server for Android LUIS SDK fails because of malformed URL connection

### ISSUE THREAD

**Issue by huy-ffd** [Azure-Samples/cognitive-services-speech-sdk#1152]
**Describe the bug**

- **chinaeast2** server supports LUIS Azure intent recognition and operates on a separate portal than the Western Azure.
- When using the chinaeast2 _LanguageUnderstandingSubscriptionKey_, _LanguageUnderstandingServiceRegion_, and _LanguageUnderstandingAppId_, the Intent Recognition fails with a **Canceled error** because the URL in the Java Android SDK is incorrect when trying to access the LUIS server.

Using a packet sniffer on the Android Device,
![image](https://user-images.githubusercontent.com/50151722/123208778-8655d900-d474-11eb-870d-10d2dcb99b98.png)

The Android cognitive-services-speech-sdk for LUIS specifically tries to access

- **chinaeast2.sr.speech.microsoft.com.mshome.net**

And it fails repeatedly because that URL does not exist.

While trying the **chinaeast2 servers for Speech-To-Text**, it works,

![image](https://user-images.githubusercontent.com/50151722/123211138-e1d59600-d477-11eb-98d3-746d0e6dbc42.png)

We can see that the format of the Speech-To-Text Java SDK URL is:

- **chinaeast2.stt.speech.azure.cn**

That Speech-To-Text URL above is valid.

So I think that the **internal URL** that the Java Android cognitive-services-speech-sdk is accessing for **chinaeast2 LUIS** is invalid.

**To Reproduce**
1. I used both https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/java/android/intent-recognition and https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/java/android/sdkdemo
2. I changed _LanguageUnderstandingSubscriptionKey_, _LanguageUnderstandingServiceRegion_, and _LanguageUnderstandingAppId_ to use the **chinaeast2** key, appID, and region.
3. **LUIS for chinaeast2** can be found at: https://luis.azure.cn
4. You can create a LUIS app just like on the Western servers. The chinaeast2 servers are also using a valid up-to-date 3.0 API that be validated through POSTMAN or testing any POST request.
5. I built the Android APKs and deployed them to my phone. Testing the chinaeast2 servers for **Speech-To-Text** and other cognitive servers worked, but **LUIS would fail** with: **ErrorCode = ConnectionFailure. ErrorDetails=Connection failed (no connection to the remote host).**

![image](https://user-images.githubusercontent.com/50151722/123209631-c2d60480-d475-11eb-8239-f379b32b6d4b.png)

Using a packet sniffer, you can see that

"chinaeast2.sr.speech.microsoft.com.mshome.net" is probably a malformed URL.
And
it's probably supposed to end with **azure.cn** instead of **microsoft.com.mshome.net**

![image](https://user-images.githubusercontent.com/50151722/123209850-0e88ae00-d476-11eb-8113-eacec089660e.png)

**Expected behavior**

When the Java SDK is working for the western servers, after pressing **Recognize Intent**, I can say a few words and get an Intent response back:

![GetImage](https://user-images.githubusercontent.com/50151722/123210370-bdc58500-d476-11eb-8a10-f3e813166c97.jpeg)

**Version of the Cognitive Services Speech SDK**

I have tried both 1.14.0 and 1.15.0 and 1.17.0
- com.microsoft.cognitiveservices.speech:client-sdk:1.14.0
- com.microsoft.cognitiveservices.speech:client-sdk:1.15.0
- com.microsoft.cognitiveservices.speech:client-sdk:1.17.0

**Platform, Operating System, and Programming Language**
 - OS: Android
 - Hardware - ARM64
 - Programming language: Java

**Comment by rhurey** [comment]
Thanks for pointing this out. There's a couple of different problems.

First, the SDK is incorrectly building the URL's for the IntentRecognizer for China* regions. I've got a bug tracking this in our internal database.

Second, even if the URL was built correctly, not all the components for the Speech->LUIS integration are deployed in China East2. So you'd get back recognized speech, but not recognized intents.

**Comment by huy-ffd** [comment]
Thanks Ryan! 

I could be talking about something completely different for the 2nd thing you mentioned, but for the Speech->LUIS Integration Intent Recognition,

the China East 2 REST API seems to recognize speech and intents like for example:

Saying Open Main Menu returns a few predicted intents:

![image](https://user-images.githubusercontent.com/50151722/123861148-ae619400-d8db-11eb-8b64-8ea366e951cc.png)

**Comment by rhurey** [comment]
The Speech SDK doesn't use the REST API, but talks to a different stream based endpoint. 

That stream based endpoint doesn't have the LUIS integration deployed.

You can try overriding the SDK's host generation by using code like:
```
var host = "wss://chinaeast2.sr.speech.azure.cn";
var speechConfig = SpeechConfig.FromHost(new Uri(host), "key"); // ChinaEast2 LUIS Key
```
(My test app is in C#, not Java...)

(Or I mis-configured my LUIS test app in azure.cn)

**Comment by huy-ffd** [comment]
I see what you mean, Ryan. I have tried your suggestion in Java, and the WebSocket failed with the following:

```
06-29 21:22:10.811 15100 15202 D CANCELED: Reason=Error 
06-29 21:22:10.811 15100 15202 D CANCELED: ErrorCode=Authenticati 
onFailure 
06-29 21:22:10.811 15100 15202 D CANCELED: ErrorDetails=WebSocket 
upgrade failed: Authentication error (401). Please check subscription informati 
on and region name. 
06-29 21:22:10.811 15100 15202 D CANCELED: Did you update the sub 
scription info? 
```

**Comment by rhurey** [comment]
That error means you have the wrong key.  

I'd have expected RecognizedSpeech for the reason instead of RecognizedIntent. Make sure to use the prediction resource's endpoint key and not the LUIS app's authoring key.

**Comment by huy-ffd** [comment]
You are right. ResultReason was `ResultReason.RecognizedSpeech` and not `ResultReason.RecongizedIntent`. I was using a US LUIS Prediction Key instead of the China East 2.

**Comment by glecaros** [comment]
Hi @huy-ffd, I understand from the thread that you were able to solve your issue. Will close this item but please feel free to create a new one if you need further assistance.

**Comment by huy-ffd** [comment]
I did not solve the issue, @glecaros 

1. The Cognitive Services SDK is still incorrectly building its URL for the IntentRecognizer for China* regions.
2.  Speech->LUIS integration are deployed in China East2 does not have all the components like a websocket on the Cognitive Services End.

Ryan was just showing me how he knew that all the components on the Cognitive Service was not setup on the China East2, and I was following his method of testing the China East 2 LUIS Intent Recognizer.

So the issue that China East2 LUIS server fails because of malformed URL connection still exists.

**Comment by glecaros** [comment]
Got it, reopened the issue. Sorry for the confusion.

**Comment by pankopon** [comment]
Internal work item ref. 3622485.

**Comment by dargilco** [comment]
There are no plans to support LUIS based IntentRecognzier in China regions. There is a way to make IntentRecognizer with [simple pattern matching](https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-use-simple-language-pattern-matching?tabs=jre%2Cwindows%2Cubuntu%2Cmaven&pivots=programming-language-csharp) work in China regions. Please open a new issue if you would like to use simple pattern machine in China region and we can assist you with that. Closing this issue.
