### ISSUE TITLE
Dynamically change InitialSilenceTimeoutMs of a started SpeechRecognizer

### ISSUE THREAD

**Issue by yveskaufmann** [Azure-Samples/cognitive-services-speech-sdk#1154]
Hi everyone,

I have the requirement, to change dynamically the _InitialSilenceTimeoutMs_ of a SpeechRecognizer which
was started via _startContinuousRecognitionAsync_.  

```java
SpeechConfig speechConfig = SpeechConfig.fromSubscription(...);
speechConfig.setProperty(PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs, 6000);
speechConfig.setProperty(PropertyId.SpeechServiceConnection_EndSilenceTimeoutMs, 0);
SpeechRecognizer speechRecognizer = new SpeechRecognizer(speechConfig, ...);
speechRecognizer.startContinuousRecognitionAsync().get();

// In some situation we need a shorter timeout 
speechConfig.setProperty(PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs, 2000);
```

I have the impression that, the change of the SpeechConfig will only be effective after creating a new SpeechRecognizer from the changed speechConfig.

Is there a way to achieve this, without creating a new SpeechRecognizer instance?   

Thanks 
Yves

**Comment by rhurey** [comment]
Yes, you're correct in that the SpeechConfig's settings are copied into the recognizer object on create. For properties that are updatable on a created recognizer, the recognizer has its own properties collection that can be used.

In this case, the simplest way to change the initial silence setting is likely to create a new instance of the SpeechRecognizer.

As an implementation detail (subject to change) the timeout is specified to the Speech Service on connection, so you'd need to:

- stop recognition
-  update the property on the recognizer directly
- acquire the connection object
- close the connection
- then re-start recognition.

**Comment by yveskaufmann** [comment]
Thank you,

for this information.
