### ISSUE TITLE
How to adjust the speed and volume of the sound?

### ISSUE THREAD

**Issue by ouweiya** [Azure-Samples/cognitive-services-speech-sdk#1155]
How to adjust the speed and volume of the sound?

I know it can be done through SSML, but I prefer to do it through configuration? I checked the documentation but didn't find what I needed.

**Comment by rhurey** [comment]
I believe that SSML is the only way to adjust those properties.

@yinhew?

**Comment by yinhew** [comment]
We currently only support rate(speech)/volume control through SSML.
@ouweiya what's the pain to use SSML?
