### ISSUE TITLE
Pronunciation assessment - word level result

### ISSUE THREAD

**Issue by anushaa01** [Azure-Samples/cognitive-services-speech-sdk#1157]
I am facing issue with word level result, as per the docs in error type we should get the parameters as inserted, ommited, missspelled. but we are only getting missspelled if the word is missspelled.

**Comment by yinhew** [comment]
@anushaa01 inserted, ommit can only show up when miscue is enabled, did you enable miscue?

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-pronunciation-assessment?pivots=programming-language-python#pronunciation-assessment-configuration-parameters

**Comment by anushaa01** [comment]
Hi Yunhew,

Let me check and get back to you.

Thanks,
Anusha Agarwal

**Comment by glecaros** [comment]
Hi @anushaa01 ,

Were you able to try what @yinhew suggested?

**Comment by pankopon** [comment]
Closed since no further comments from the customer in 27 days. Please open a new issue if more support is needed.
