### ISSUE TITLE
32bit / armv7 for iOS platforms

### ISSUE THREAD

**Issue by cchitsiang** [Azure-Samples/cognitive-services-speech-sdk#116]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Currently the Speech SDK only supports 64bit iOS platforms. Any plan to support 32bit iOS platforms?

**Describe alternatives you've considered**

**Additional context**

**Comment by zhouwangzw** [comment]
Currently the SDK does not support 32bit iOS platform. There is no short-term plan to support it. Sorry for inconvenience.

**Comment by cchitsiang** [comment]
Too bad :(
