### ISSUE TITLE
Support for PHP in the new SDK

### ISSUE THREAD

**Issue by shoutbomb** [Azure-Samples/cognitive-services-speech-sdk#1161]
**Is your feature request related to a problem? Please describe.**
My rest based integration using PHP is no longer supported.

**Describe the solution you'd like**
Can you provide an SDK supporting PHP, since there was support for PHP in the REST version.

**Describe alternatives you've considered**
Rewriting my programs in Python, but this is an expense I am not ready for.

**Additional context**

**Comment by glharper** [comment]
@shoutbomb Thanks for using Speech SDK, and for writing this up. We prioritize enhancement requets like this one according to community input/feedback, and will do so accordingly here. Thanks again.
