### ISSUE TITLE
JavaScript SDK does not work: The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead.

### ISSUE THREAD

**Issue by YounKimAtAri** [Azure-Samples/cognitive-services-speech-sdk#1164]
The JS SDK does not work as the ScriptProcessorNode is deprecated on the `[https://aka.ms/csspeech/jsbrowserpackageraw](https://aka.ms/csspeech/jsbrowserpackageraw)` when it calls **_return context.createScriptProcessor(bufferSize, 1, 1);_**

**Comment by glharper** [comment]
@YounKimAtAri What code are you using to produce this issue? Could you describe "does not work" in more detail? Are you not receiving results when called JS SDK APIs?

**Comment by YounKimAtAri** [comment]
@glharper 

I found out why it happened. There is a still JS error message, but not it's working. 

Thank you.
