### ISSUE TITLE
app crash at library loading phase

### ISSUE THREAD

**Issue by huiweyl** [Azure-Samples/cognitive-services-speech-sdk#1168]
**Describe the bug**
on iOS 13.1, app will crash when launch.

**To Reproduce**
1. on an iOS 13.1 device, install the app with SDK integrated (the app should be exported using adhoc or archive method)
2. launch the app, it crashes

in console, we can see following log:
**********
Error loading /var/containers/Bundle/Application/6A54D177-A088-4680-A59F-4397210DBE4E/hf.app/Frameworks/UnityFramework.framework/UnityFramework:  dlopen(/var/containers/Bundle/Application/6A54D177-A088-4680-A59F-4397210DBE4E/hf.app/Frameworks/UnityFramework.framework/UnityFramework, 0x0109): relative file paths not allowed '@rpath/GStreamerWrapper.framework/GStreamerWrapper'
**********

**Expected behavior**
app should launch correctly

**Version of the Cognitive Services Speech SDK**
1.16.0 

**Platform, Operating System, and Programming Language**
 - OS: iOS
 - Hardware - arm64
 - Programming language: Objective-C

**Additional context**
1. on iOS 13.5 / 14, this issue does NOT repro
2. if the binary is exported using development method (or run it directly with xcode), this issue does NOT repro

**Comment by glharper** [comment]
@huiweyl Thanks for using Speech SDK, and including log info with this issue. Are you able to reproduce this using version 1.17.0 of Speech SDK?

**Comment by huiweyl** [comment]
there's not a 1.17.0 version on Pod:

[!] CocoaPods could not find compatible versions for pod "MicrosoftCognitiveServicesSpeech-iOS":
  In snapshot (Podfile.lock):
    MicrosoftCognitiveServicesSpeech-iOS (= 1.16.0, ~> 1.9)

  In Podfile:
    ******************, which depends on
      MicrosoftCognitiveServicesSpeech-iOS (= 1.17.0)

**Comment by huiweyl** [comment]
1.17.0 sdk still repros this issue

**Comment by calbertts** [comment]
I'm having the same issue.
I have a durable function app and one of the activity just requires the library:

```
const sdk = require('microsoft-cognitiveservices-speech-sdk');
```

And it crashes even if the function doesn't do anything, once I remove the `require` statement, it works.

This started on Wednesday, these are my 7 days logs:
![image](https://user-images.githubusercontent.com/1326651/125976576-9850566d-b950-44a6-a9e2-35781b2b4532.png)

And it hasn't worked ever again since then.

**Comment by jhakulin** [comment]
@huiweyl Based on your report, the problem occurs only with iOS 13.1 version, is that right?

**Comment by huiweyl** [comment]
We ONLY tested SDK on 13.1  / 13.5 / 14.1 
I'm not sure if this will happen on other iOS version.

**Comment by jhakulin** [comment]
@huiweyl Speech SDK 1.19.0 has been released which contains a fix, let us know if there are any problems.
