### ISSUE TITLE
Log Timings for Connections to the speech service

### ISSUE THREAD

**Issue by dkmbw** [Azure-Samples/cognitive-services-speech-sdk#117]
**Is your feature request related to a problem? Please describe.**
We want to measure how long network connections take and their latencies, so we can see how much time we have to wait, so we can perhaps change to other services, when the load is to high

**Describe the solution you'd like**
Logging to stdout when a network connection starts and ends

**Describe alternatives you've considered**
i have no idea as long as the source is closed how to do this.

**Comment by zhouwangzw** [comment]
The release 1.2.0 adds a Connection object, which allows you to subscribe to Connected and Disconnected events.
