### ISSUE TITLE
Keyword Recognition - Silence duration after keyword detection

### ISSUE THREAD

**Issue by lrodorigo** [Azure-Samples/cognitive-services-speech-sdk#1170]
**Describe the bug**
After the keyword is detected, the user has no time to give commands. In detail the speech to text operation is terminated in a very short time after the keyword detection. Is there a way to set the duration of the silence between the keyword and the following commands?
The current maximum delay is really short and is difficult fot the user to understand a "keyword spotted feedback" (e.g. a led whitch turns on) and then continue speaking without hitting the silence threshold timeout between the keyword and the following commands.

I tried the solutions reported in the following posts, with no success:
Azure-Samples/cognitive-services-speech-sdk#131 (comment)
and
```
auto config = SpeechConfig::FromSubscription("<<KEY>>", "eastus");
config->SetProperty(PropertyId::SpeechServiceConnection_EndSilenceTimeoutMs, "10000");
```
Expected behavior
We expect that setting the SpeechServiceConnection_EndSilenceTimeoutMs property also affects the delay between the keyword and the successive utterances (or we expect an alternative way to configure this delay).

**Setup (please complete the following information):**

OS: Ubuntu 20.04
Azure CPP SDK v 1.17.0

**Comment by chschrae** [comment]
Hi,

Thanks for reaching out to us. There are currently two workarounds depending on your needs and the scenario.

You can use a separate KeywordRecognizer object that will only be used for keyword recognition. When the keyword is recognized, you then call your SpeechRecognizer to RecognizeOnce. This should give you the functionality you want.

If you have a dialog bot or a custom commands scenario, you can use the DialogServiceConnector object which utilizes a service called Keyword Verification and that will solve this issue.

Please let us know if this solves your issue or if there is some reason it doesn't work for you.

**Comment by lrodorigo** [comment]
It is really a pity that a so simple parameter is not exposed directly in the `SpeechRecognizer->recognizeWithKeyword`, it would perform really better in many use cases. I will try using the KeywordRecognizer+SpeechRecognizer approach.

**Comment by chschrae** [comment]
I agree and we are working on an easier solution that works within the speech recognizer. Thanks again for your input!

**Comment by vkjambit** [comment]
hi, are there any news on this topic? 
i used the keywordrecognizer and started a recognizeonce after that - the keyword works perfectly but the speechrecognizer after that works really bad and i don't know why (i'm using it on an android device)
