### ISSUE TITLE
Catalyst support

### ISSUE THREAD

**Issue by hsncr** [Azure-Samples/cognitive-services-speech-sdk#1171]
Hi everyone,

My problem is that I can't use the framework in my framework that has catalyst support. 

My questions are;

1. What are the reasons that make you disable catalyst support?
2. If it is not related with core functionality, Do you plan to add support for mac catalyst in the near future?
3. Most importantly; Is there a solution to workaround this issue?

Thanks in advance.

**Comment by glharper** [comment]
@hsncr Thanks for using Speech SDK, and writing this issue up. I was unaware Speech SDK explicitly supported catalyst. Was there a previous SDK version where catalyst was supported?

Which errors are you seeing, that you can't use Speech SDK with catalyst?

**Comment by hsncr** [comment]
@glharper If I choose mac as a target device, I get following error on catalyst supported app;

Building for Mac Catalyst, but linking in dylib built for iOS, file '{POD_NAME}/Example/Pods/MicrosoftCognitiveServicesSpeech-iOS/MicrosoftCognitiveServicesSpeech.framework/MicrosoftCognitiveServicesSpeech' for architecture arm64

**Comment by jhakulin** [comment]
@hsncr Speech SDK 1.19.0 has been released which includes support for Mac Catalyst, let us know if there are any problems.
