### ISSUE TITLE
sdk内部报错引起服务异常重启

### ISSUE THREAD

**Issue by ghpfxf** [Azure-Samples/cognitive-services-speech-sdk#1173]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff50b218d11, pid=1, tid=0x00007ff4d7c87700
#
# JRE version: OpenJDK Runtime Environment (8.0_292-b10) (build 1.8.0_292-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.292-b10 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x21d11]  abort+0x203
#
# Core dump written. Default location: /home/xpmotors/local/core or core.1
#
# An error report file with more information is saved as:
# /home/xpmotors/local/hs_err_pid1.log
terminate called after throwing an instance of 'Microsoft::CognitiveServices::Speech::Impl::ExceptionWithCallStack'
  what():  Exception with an error code: 0x2 (SPXERR_ALREADY_INITIALIZED)
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%208&component=java-1.8.0-openjdk
#

**Comment by chschrae** [comment]
Hi there,

Thanks for reaching out. Can you give me some more detail on what your code looks like that causes this error? Is there a particular scenario that causes it or is it every time? What OS and architecture are you running?

**Comment by pankopon** [comment]
Closed since no update received in 3 weeks. Please open a new issue if more support is needed.
