### ISSUE TITLE
Deployment issues No matching distribution found for swagger_client . Please help. Runs locally fine on laptop. 

### ISSUE THREAD

**Issue by novosartovt** [Azure-Samples/cognitive-services-speech-sdk#1175]
When deploy app to azure functions it failes to locate swagger_client. If i do PIP list i do see the package there. 

**To Reproduce**
1. Import swagger based on steps provided
2. Deploy function from VS Code to Azure function it failes 
3. Added import to requirements.txt 

**Expected behavior**
It should deploy

**Version of the Cognitive Services Speech SDK**
azure-cognitiveservices-speech==1.17.0

**Platform, Operating System, and Programming Language**
 - OS:  Windows,
 - Programming language:  Python

**Additional context**
 - Error messages,
 -10:16:45 AM alcatel-voc: ERROR: Could not find a version that satisfies the requirement swagger_client==1.0.0 (from -r requirements.txt (line 12)) (from versions: none)
10:16:45 AM alcatel-voc: ERROR: No matching distribution found for swagger_client==1.0.0 (from -r requirements.txt (line 12))
10:16:45 AM alcatel-voc: WARNING: You are using pip version 20.2.3; however, version 21.1.3 is available.
10:16:45 AM alcatel-voc: You should consider upgrading via the '/tmp/oryx/platforms/python/3.9.0/bin/python3.9 -m pip install --upgrade pip' command.
10:16:45 AM alcatel-voc: Done in 1 sec(s).
10:16:46 AM alcatel-voc: /opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9 -p packagedir=.python_packages/lib/site-packages
10:16:51 AM alcatel-voc: Deployment failed.

**Comment by novosartovt** [comment]
Also, i tried to do pip install -r requirements.txt     and seems fine saying its already installed on my local .
Requirement already satisfied: swagger-client in c:\users\t6175122\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from -r requirements.txt (line 12)) (1.0.0)

**Comment by chlandsi** [comment]
Hi @novosartovt , can you post the exact contents of your requirements.txt file? You would have to make sure that the package you downloaded from the swagger autogeneration is packaged and uploaded with your Azure function, and then put the path to that location into your requirements.txt file, since pip needs to install the package from that local file, rather than from a published package in the package index.

**Comment by novosartovt** [comment]
> Hi @novosartovt , can you post the exact contents of your requirements.txt file? You would have to make sure that the package you downloaded from the swagger autogeneration is packaged and uploaded with your Azure function, and then put the path to that location into your requirements.txt file, since pip needs to install the package from that local file, rather than from a published package in the package index.

Thank you for reply . I'm very new to this any help would greatly assist me. Here is what inside the req file . Please let me know if anything else  i need to add. How do i specify local path in requirement doc? 
# DO NOT include azure-functions-worker in this file
# The Python Worker is managed by Azure Functions platform
# Manually managing azure-functions-worker may cause unexpected issues

azure-functions==1.7.2
azure-cognitiveservices-speech==1.17.0
#logging
#sys
requests==2.25.1
#json,os,time
swagger-ui-py==0.3.0
swagger-client
#grpcio==1.33.1
#grpcio-tools==1.33.1

protobuf==3.17.3
#python-dateutil==2.8.1
six==1.16.0
certifi==2017.4.17
python_dateutil==2.1
#setuptools == 21.0.0
urllib3==1.26

**Comment by novosartovt** [comment]
I was able to deploy .Thank you i put "./python-client" in requirments.txt

**Comment by chlandsi** [comment]
Great to hear that!

**Comment by novosartovt** [comment]
> Great to hear that!

Thanks again !
