### ISSUE TITLE
Decreased speech recognition accuracy with the de-DE model: Fä- words

### ISSUE THREAD

**Issue by ccoreilly** [Azure-Samples/cognitive-services-speech-sdk#1176]
**Describe the bug**
Using the latest de-DE speech recognition model currently we are experiencing more and more false positives. Words that begin with Fä- are recognized instead of what is being said.
Unfortunately this is hard to reproduce but looking at our logs this phenomena started appearing about 2,5 weeks ago and more and more utterances are being recognized falsely since then. For example:

Instead of "Nein, danke", the speech recognizer returns "Fählein danke".
Instead of "Einmal", the speech recognizer returns "Fähren mal".

**To Reproduce**
The issue is really hard to reproduce consistently but wanted to share just in case other users of the de-DE model are experiencing this issue.
We have however deployed an older baseline (20200619) and the issue is gone. We did not have this issue before and are using the generic model since January.

**Expected behavior**
The speech recognizer should not favour words starting with the phonemes of Fä.

**Version of the Cognitive Services Speech SDK**
1.17

**Platform, Operating System, and Programming Language**
We are using the Java Speech SDK v1.17 in a Docker image based on openjdk:11-jdk-slim

**Additional context**
As I wrote above, the issue does not appear with the baseline model 20200619 (which is an acceptable workaround for now). We have not tested the latest baseline 20201127 because we assume this is the same model as when you don't set an endpointId. We thus have the following questions:
- Is the generic model the same as the latest baseline or is it "newer".
- If the model is the same, which means it has not changed since Nov. 2020 and we didn't have this issue until 2,5 weeks ago: what has changed internally that can produce such a behaviour?

The audio we are sending to the speech recognizer is linear PCM 8kHz 16-bit coming from the phone.

**Comment by chschrae** [comment]
@ccoreilly Hi there,

Thanks for reaching out and pointing out this issue. I've contacted the Speech Recognition team and they are looking into it. I will let you know when I have more information.

**Comment by oskoller** [comment]
To Answer the questions:

- yes, the generic baseline model is currently the same as 20201127, this has not changed recently
- So far I am not aware of any changes in the past 2.5 weeks that could have caused this issue. To further investigate I would need a way to reproduce the issue.
