### ISSUE TITLE
Connection error on SpeechSDKDemo java from AWS EC2

### ISSUE THREAD

**Issue by xavcastle** [Azure-Samples/cognitive-services-speech-sdk#1177]
Hi all,

I am developing a Java application that uses speech SDK. 

We use the SpeechSDKDemo (client-sdk 1.17.0) code for testing the basic configuration. Azure Speech api is configured in: northeurope region.

- SpeechSDKDemo runs correct on Azure VM (northeurope region) running with Linux (ubuntu 20.04) + openjdk version "11.0.11" 64 Bit
- SpeechSDKDemo fails on AWS EC2 (eu-west-1a region) running with Amazon Linux 2 (RHEL 7)  + openjdk version "11.0.11" 64 Bit

Error displayed in EC2:
CANCELED: ErrorDetails=Error in sending a http request.0
CANCELED: ErrorDetails=Canceled

We use the same jar and libs for both enviroments. Outbound rules in EC2 allow all ports. 

We need to connect the EC2 to the Azure api as we have to deal with other infraestructure in AWS.

Does anybody experienced same issue? Does anybody have an idea how to solve it?

Thank you!

**Comment by chschrae** [comment]
Hi there,

Thanks for reaching out. Based on the error message, my first question would be "does the EC2 instance have connectivity to other things?" 

Assuming the connection isn't the problem, I would try reaching other regional endpoints for the Azure cognitive services subscription key.

I will attempt to set up a similar test myself as well.

**Comment by chschrae** [comment]
@xavcastle Have you run the instructions on this page to setup your RHEL environment? https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7

**Comment by xavcastle** [comment]
Hi @chschrae, thank you for your quick help!

- EC2 instance has connectivity to other things? -> **YES, it has conectivity!**

I launched two new blank EC2 instances to avoid conflicts with previously installed software.
- First EC2 with ubuntu 20.04
- Second EC2 with AWS Linux2.

On the ubuntu instance after installing openjdk version "11.0.11", SpeechSDKDemo **worked correctly** without any problem, so it seems that the problem has not relation with regional endpoints

On the AWS Linux2, I followed the steps as written in https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7:

1. sudo yum update **OK**
2. amazon-linux-extras **OK**
3. sudo amazon-linux-extras install java-openjdk11 **OK**
4. java -version 
   **openjdk version "11.0.11" 2021-04-20 LTS**
5. openssl version -d
   **OPENSSLDIR: "/etc/pki/tls"**
6. sudo yum groupinstall 'Development Tools' **OK**
7.  g++ --version
   **g++ (GCC) 7.3.1 20180712 (Red Hat 7.3.1-13)**
8.  ldconfig -p | grep libstdc++
   **libstdc++.so.6 (libc6,x86-64) => /lib64/libstdc++.so.6**
9.  strings /lib64/libstdc++.so.6 | egrep "GLIBCXX_|CXXABI_"
   **found both GLIBCXX_3.4.19 and CXXABI_1.3.7**
10.  sudo rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm **OK**
11. sudo yum install -y alsa-lib dotnet-sdk-2.1 java-1.8.0-openjdk-devel openssl python3 **OK**
12. sudo yum install -y gstreamer1 gstreamer1-plugins-base gstreamer1-plugins-good gstreamer1-plugins-bad-free gstreamer1-plugins-ugly-free **OK**
13. sudo yum install -y gmp-devel mpfr-devel libmpc-devel **OK**
14. curl https://ftp.gnu.org/gnu/gcc/gcc-5.4.0/gcc-5.4.0.tar.bz2 -O **OK**
15. tar jxf gcc-5.4.0.tar.bz2 **OK**
16. mkdir gcc-5.4.0-build && cd gcc-5.4.0-build **OK**
17. ../gcc-5.4.0/configure --enable-languages=c,c++ --disable-bootstrap --disable-multilib --prefix=/usr/local
18. make -j$(nproc) **ERROR**
19. sudo make install-strip 
     **ERROR
     /bin/sh: line 3: cd: x86_64-unknown-linux-gnu/libstdc++-v3: No such file or directory
     make[1]: *** [install-strip-target-libstdc++-v3] Error 1
     make[1]: Leaving directory `/home/ec2-user/gcc-5.4.0-build' 
     make: *** [install-strip] Error 2**
21. export SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt **OK**
22. export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH **OK**
23. Attempting to run SpeechSDKDemo  failed again with the error;
     CANCELED: ErrorDetails=Error in sending a http request.0
     CANCELED: ErrorDetails=Canceled

As AWS linux2 AMI distro is widely used by EC2 users, it would be great to have a solution to allow EC2 instances to use Azure Cognitive Services.

Thank you!
@xavcastle

**Comment by chschrae** [comment]
@xavcastle 
Wow nice work in digging into the details.

I know for now the AWS linux2 is not officially supported. I agree it would be a good thing to support in the future, but I can't promise anything around that.

For RHEL it is indeed supported and should work. Were you able to get that to work with the instructions?

**Comment by xavcastle** [comment]
@chschrae
We can't wait until then. 
We will have to think what to do. Maybe migrating the Linux2 to a new Ubuntu instance (more work before summer hollidays!). 
Thank you for your help!

**Comment by chschrae** [comment]
@xavcastle So I finally got my RHEL instance set up and I was getting a connection refused error until I followed the line to export the certificate environment variable
export SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt

Maybe this is the same issue you were having. Hope this helps.

**Comment by xavcastle** [comment]
@chschrae 
I did it also in AWS Linux2, but keeps getting a connection error.
I'll change to ubuntu distro.
Best!
