### ISSUE TITLE
Some numbers are not converted to digits when spoken in colloquial german

### ISSUE THREAD

**Issue by StefanOstwald** [Azure-Samples/cognitive-services-speech-sdk#1182]
**Describe the bug**
This bugs refers to German (Germany).

When a number is expressed in colloquial German, the STT transcribes the input only to words and does not convert it to digits.

**Issue "40"**
The "g" at the end of the word can be pronounced soft and sound like a "ch"
Colloquial STT Transcript: "Vierzi**ch**", which is not converted to "40"
Proper spelling: "Vierzi**g**", which is correctly converted to "40"
Expected behavior: The transcript contains only the digit 40.

**Issue ... und dreißig**
The "d" at the end of the word and the beginning of the next word can be pronounced like one "d".
Colloquial STT Transcript: "Sechsun**d**reißig", which is not converted to "36"
Proper spelling: "Sechsunddreißig", which is correctly converted to "36"
Expected behavior: The transcript contains only the digit 36.

**Platform, Operating System, and Programming Language**
We are using the Java Speech SDK v1.17 in a Docker image based on openjdk:11-jdk-slim

**Additional context**
The audio we are sending to the speech recognizer is linear PCM 8kHz 16-bit coming from the phone.

**Comment by oskoller** [comment]
Thanks for reaching out and reporting the bug. 

I tried speaking numbers 'colloquially' against the current default de-de base model, but I could not reproduce the transcription into the lexical form of 'vierzich' or 'sechsundreißig'. 

Could you share audio files reproducing this behavior and specify against which endpoint / model you are experiencing the issue?

**Comment by StefanOstwald** [comment]
Hi Oscar,
sorry, I don't have audio recordings. I have only seen it in the logs.
We use the default de-de model as SAAS in West Europe.

**Comment by oskoller** [comment]
Hi Stefan, I understand. In that case, we will just incorporate changes into the model to make such recognitions less likely. 
Thanks for your help!
