### ISSUE TITLE
Sample for async conversation transcription without voice samples

### ISSUE THREAD

**Issue by matej-svejda** [Azure-Samples/cognitive-services-speech-sdk#1183]
Hi,

I'm trying to use Azure Speech to transcribe conversations (in my case it's mostly recorded interviews) that have:

* Multiple participants (anywhere between 1 and 10)
* No voice samples of the participants

I implemented the first prototype using the batch transcription REST API 3.0, but there only two speakers are support.
My second approach was to use async conversation transcription, since in the documentation it says that you don't need samples of the speakers to get diarization (the second *Note* box here https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/conversation-transcription clearly says "User voice samples are optional. Without this input, the transcription will show different speakers, but shown as "Speaker1", "Speaker2", etc. instead of recognizing as pre-enrolled specific speaker names."). However, I'm at a loss as to how to get it to work. I tried simply removing the "addParticipantAsync" from the samples, but that just produces empty output.

So my question/feature request: is there an example that shows how to do async conversation transcription with speaker diarization without speaker samples? And if there isn't, it would be great to have one (any language, though I personally would prefer JS).

Thanks :)

**Comment by glharper** [comment]
@matej-svejda Are your recorded interviews in 8-channel audio? If so, could you share one so that I can see what happening and give a code sample that works for me?

**Comment by matej-svejda** [comment]
@glharper Ah, so you having an 8-channel audio is hard requirement for using the conversation transcription service? What I need transcriptions for are mostly recordings of online meetings (Zoom, Teams etc.). So if the conversation transcription service isn't the way to go, is there any other way to transcribe those with speaker diarisation? It would really help a lot, because accuracy wise your transcription service beats the other ones by a lot :)

**Comment by HeidiHanZhang** [comment]
@matej-svejda could you send this question to CTSFeatureCrew@microsoft.com that I will be happy to facilitate you further.

**Comment by pankopon** [comment]
Closed as further support is handled by CTSFeatureCrew.
