### ISSUE TITLE
Question: startContinuousRecognitionAsync (and stop) Future thread cleanup in java?

### ISSUE THREAD

**Issue by aargreen** [Azure-Samples/cognitive-services-speech-sdk#1184]
We are noticing a build-up of CPU and memory over time when using the MS Speech SDK in java.   The issue might be unrelated to the Speech SDK itself, but in wrapper code around it and we are still debugging, however I was wondering if it was also possible that we were not cleaning up some of the speech threads properly.

we call startContinuousRecognitionAsync.get() right now WITH NO Timeout parameter.
and we call stopContinuousRecognitionAsync.get() WITH a timeout parameter.

Was wondering if it was considered best practice to call both of these with a timeout parameter?
Also is it possible/recommended to check that the futures launched by these calls are finished and if not cancel them?

Other semi-related question: Is it ok to close a release a PushAudioInputStream input stream multiple times?  Currently I have code which closes it once directly after streaming audio to it, but was wondering if it would be ok to close it again in a "finally block" to ensure it closed in a case of exception between creating th4e object and the start of streaming data to the object.

**Comment by amitkumarshukla** [comment]
@aargreen Could you please send your sample so that we can look at it and give you the right solution.

**Comment by aargreen** [comment]
@amitkumarshukla 
Pseudocode below. In general want to make sure I am cleaning up everything properly including resources and anything related to threads.

//Declare 5 resources
SpeechConfig speechConfig = null;
AutoDetectSourceLanguageConfig autoDetectSourceLanguageConfig = null;
AudioConfig audioConfig = null;
SpeechRecognizer recognizer = null;
PushAudioInputStream pushStream = null;

try {
      // Create the 5 resources. 
      pushStream = AudioInputStream.createPushStream();
      audioConfig= AudioConfig.fromStreamInput(pushStream);
      speechConfig = SpeechConfig.fromSubscription(.....)
      autoDetectSourceLanguageConfig = AutoDetectSourceLanguageConfig.fromLanguages(....);
      recognizer = new SpeechRecognizer(speechConfig, autoDetectSourceLanguageConfig, audioConfig);

      //Set up recognizer callback functions
      .....

      //Launch actual recognition and stream data
      recognizer.startContinuousRecognitionAsync().get();
      writeInputStreamToPushStream();  //Our own function copy from input stream into push stream
      pushStream.close();
     
      // Stop recognition with a time limit on blocking
     // QUESTION: SHOULD I DO ANYTHING DIFFERENT WITH THESE FUTURES (START/STOP) TO ENSURE CLEANUP?
      Future<Void> recogizerFuture = recognizer.stopContinuousRecognitionAsync();
      recogizerFuture.get(MSFT_LID_FUTURE_RETURN_TIMEOUT_MS, TimeUnit.MILLISECONDS);
} finally {
   // Close all resources except pushStream which should be already closed.
   // QUESTION: IS IT OK TO CLOSE PUSHSTREAM HERE AS WELL JUST TO BE SURE?
   //NOTE: Not shown below, but closing code also catches exceptions and proceeds to attempt to close other resources. 
   speechConfig.close(); 
   autoDetectSourceLanguageConfig.close();
   audioConfig.close()
   recognizer.close()
  
}

**Comment by aargreen** [comment]
One follow-up question based on some heap dumps I am doing.  Can SpeechRecognizer.close() fail or throw any exceptions?

**Comment by jhakulin** [comment]
@aargreen Some comments here. SpeechRecognizer.close() can throw IllegalStateException if you try to dispose a recognizer while async recognition is running. From 1.18.0 and onwards for closeable objects, you can use try-with-resources pattern like in quickstart sample here: https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/java/jre/from-microphone/src/speechsdk/quickstart/Main.java, and then your app does not call explicitly close. Calling close for pushstream several times should not cause bad side effects. Let us know if these will help.

**Comment by aargreen** [comment]
Thanks @jhakulin.  I seem to be making a little progress diagnosing the issue, but still running testing.

Two follow up questions on SpeechRecognizer.close() exceptions. 
1) Would the try-with-resources pattern still throw an exception (and fail to cleanup) if async recognition is running?  
2) Is it acceptable to call cancel on any async futures that may be running to try to prevent closure exceptions?

For example I have a timer on this future:
Future<Void> recogizerFuture = recognizer.stopContinuousRecognitionAsync();
recogizerFuture.get(MSFT_LID_FUTURE_RETURN_TIMEOUT_MS, TimeUnit.MILLISECONDS);

Can I change this too:
Future<Void> recogizerFuture = recognizer.stopContinuousRecognitionAsync();
recogizerFuture.get(MSFT_LID_FUTURE_RETURN_TIMEOUT_MS, TimeUnit.MILLISECONDS);
recogizerFuture.cancel(). // ADDED

**Comment by pankopon** [comment]
@jhakulin Please check and update status if still valid.

**Comment by pankopon** [comment]
Closed since no update in a year and no further comments from the customer. Please open a new issue with latest information if support is still needed.
