### ISSUE TITLE
Include devcontainer configuration in repo to simply use in codespaces 

### ISSUE THREAD

**Issue by mikekistler** [Azure-Samples/cognitive-services-speech-sdk#1185]
**Is your feature request related to a problem? Please describe.**

I would like to use this repo in a GitHub Codespace -- specifically to run the Jupyter notebook samples.  But because there is no devcontainer configuration in the repo, GitHub uses a generic container that is missing many of the elements that are needed to run the notebook.  After the notebook starts, I am prompted to:
1. Install the VSCode Jupyter notebook extension
2. Install the VSCode Python extension
3. Select the version of Python to use
4. Install the ipykernel for Jupyter.

I also have to pip install the SDK package, azure-cognitiveservices-speech, via the terminal, for the notebook to work successfully.

I believe most if not all these steps could be automatically performed as part of the container initialization if the proper container configuration file was included in the repo.

**Describe the solution you'd like**

I would like to be able to launch the repo in a Codespace, open the notebook file, and simply start running cells without having to install or configure anything.

**Describe alternatives you've considered**

Create my own repo -- but please don't make me do that

**Additional context**

devdivcodingdays

**Comment by amitkumarshukla** [comment]
Thanks a lot for your feedback. We will keep this as feature request. We will prioritize it based and work on it. Please look at the future releases. I am closing this issue for the time being. Thanks a lot.
