### ISSUE TITLE
Timeout behaves differently for different streams

### ISSUE THREAD

**Issue by has-n** [Azure-Samples/cognitive-services-speech-sdk#1189]
**Describe the bug**
I'm capturing mic data (using fromDefaultMicrophone and from createPushStream). I set the `SpeechServiceConnection_EndSilenceTimeoutMs` value for both streams but they behave differently. The fromDefaultMicrophone stream does not honor it but createPushStream does. 

**To Reproduce**
1. create two streams using fromDefaultMicrophone and createPushStream
2. set SpeechServiceConnection_EndSilenceTimeoutMs to a number 
3. let the timeout lapse and try to capture data in the streams 
4. createPushStream will not work after the timeout but fromDefaultMicrophone will 

**Expected behavior**
Both streams honor the timeout value. 

**Version of the Cognitive Services Speech SDK**
JS 1.18.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - x64
 - Programming language: JavaScript
 - Browser : Chromium wrapped in Electron

**Comment by glharper** [comment]
@has-n Thanks for using Speech SDK, and writing this issue up. In my testing on Edge with 1.18, I'm seeing the timeout being honored when set to 1000ms, using SpeechRecognizer.startContinuousRecognitionAsync(). The speech service sends EndOfDictation, and the SDK stops listening to the microphone.

In 1.17, in the same scenario (1s end timeout), the recognizer keeps recognizing after the 1s timeout using the default microphone.

Would you mind sharing the code you're using to reproduce this?

**Comment by has-n** [comment]
I'm unable to repro this. Might have been an issue with my code. Closing for now. Thanks for the help anyways @glharper!
