### ISSUE TITLE
Does it have volume change parameter in the speech recognizer in the android SDK?

### ISSUE THREAD

**Issue by mingxin-yang** [Azure-Samples/cognitive-services-speech-sdk#119]

**Comment by mingxin-yang** [comment]
I want to make an animation based on the volume, how to do?

**Comment by zhouwangzw** [comment]
The SDK does not expose API to control microphone. If you want to control mic, you can open the mic by yourself, and feed audio data to SDK via AudioInputStream. In this way, you have full control on mic. 

Thanks,

**Comment by zhouwangzw** [comment]
I am closing the issue. If you have new questions, please feel free to open a new issue.
