### ISSUE TITLE
stopContinuousRecognitionAsync callback does not fire when OutputFormat.Detailed is set

### ISSUE THREAD

**Issue by has-n** [Azure-Samples/cognitive-services-speech-sdk#1190]
**Describe the bug**
If a callback is passed to stopContinuousRecognitionAsync, it does not fire if output format is set to detailed

**To Reproduce**
1. in the browser sample, set the Result Format to Detailed
2. add a callback to the stopContinuousRecognitionAsync function
3. START continuous recognition then click the STOP button

**Expected behavior**
When Result Format is set to Simple, the callback and sessionStopped event are fired. When Result Format is set to Detailed, neither the callback nor sessionStopped are called. 

Result Format set to Simple:
```
(sessionStarted) SessionId: A0196D424C7A4023A51F1964F42AA15D
(recognizing) Reason: RecognizingSpeech Text: test
(recognized)  Reason: RecognizedSpeech
(recognized)  Reason: NoMatch NoMatchReason: NotRecognized
(sessionStopped) SessionId: A0196D424C7A4023A51F1964F42AA15D
```

Result Format set to Detailed:
```
(sessionStarted) SessionId: 283FFF244D29490CABECD82D8A937887
(recognizing) Reason: RecognizingSpeech Text: test
(recognized)  Reason: RecognizedSpeech
(recognized)  Reason: RecognizedSpeech
```

**Version of the Cognitive Services Speech SDK**
Javascript 1.18.0

**Platform, Operating System, and Programming Language**
 - OS: Windows
 - Hardware - x64
 - Programming language:  JavaScript
 - Browser [e.g. Chrome, Safari] Chrome

**Comment by has-n** [comment]
@glharper , if it helps, I am not able to replicate this with 1.17.

**Comment by glharper** [comment]
@has-n Thank you for finding this and writing it up, this is indeed a regression from 1.17. Expect a 1.18.1 release for JS Speech SDK within the next couple of weeks with this fix included. Thanks again!

**Comment by glharper** [comment]
@has-n [Version 1.18.1](https://github.com/microsoft/cognitive-services-speech-sdk-js/releases/tag/v1.18.1) of the JS Speech SDK has been released with a fix for this issue. Thanks again for reporting it, and using Speech SDK.
