### ISSUE TITLE
Long response time when using Speech To Text with PhraseListGrammar in Java

### ISSUE THREAD

**Issue by hiddow** [Azure-Samples/cognitive-services-speech-sdk#1192]
**Describe the bug**
We use com.microsoft.cognitiveservices.speech:client-sdk:1.18.0 in our project for test now, when we add PhraseListGrammar to Improve recognition accuracy , the response become longer > 7s; if we remove PhraseListGrammar the response become normal about 3s.

**To Reproduce**
1. Recognize from file
2. add PhraseListGrammar to Improve recognition accuracy 

**Expected behavior**
the response time should be normal when add PhraseListGrammar to Improve recognition accuracy

**Version of the Cognitive Services Speech SDK**
com.microsoft.cognitiveservices.speech:client-sdk:1.18.0

**Platform, Operating System, and Programming Language**
 - Android

**Additional context**

Here is my code:

```kotlin
        val config = SpeechConfig.fromSubscription(
            speechSubscriptionKey,
            serviceRegion
        )
        config.speechRecognitionLanguage = keyLan

        val audioFormat = AudioStreamFormat.getWaveFormatPCM(
            16000.toLong(),
            16.toShort(), 1.toShort()
        )

        val pullAudio = AudioInputStream.createPullStream(
            PcmFileAudioInputStream(mAudioPath),
            audioFormat
        )
        val audioConfig = AudioConfig.fromStreamInput(pullAudio)

        val recognizer = SpeechRecognizer(config, audioConfig)

        //Add this the response become longer > 7s
        val phraseList = PhraseListGrammar.fromRecognizer(recognizer)
        phraseList.addPhrase(curSentence?.sentence)

        val task: Future<SpeechRecognitionResult> =
            recognizer.recognizeOnceAsync()
```

**Comment by pankopon** [comment]
Hi, this is a known issue https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1124 and should have improved by now but apparently it's still observed, we'll check with the service team.
