### ISSUE TITLE
How to use start_continuous_recognition_async() function

### ISSUE THREAD

**Issue by abhishekk673** [Azure-Samples/cognitive-services-speech-sdk#1194]
I'm trying to build streamlit webapp in python for Speech To Text.In the demo there are two buttons start button for start recognizing and stop button for stopping the recognizing.But i'm trying to work on recognising the speech for more than 15 seconds so i opted for start_continuous_recognition_async() instead of recognize_once_async().But the code given in https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_sample.py#L576
is not working.

I ran this code.
def mic11():
  speech_config = speechsdk.SpeechConfig(subscription="", region="")
  speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config)
  speech_recognizer.start_continuous_recognition_async()

    done = False

    def stop_cb(evt):
        print('CLOSING on {}'.format(evt))
        speech_recognizer.stop_continuous_recognition_async()
        nonlocal done
        done = True

    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
    speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))

    speech_recognizer.session_stopped.connect(stop_cb)
    speech_recognizer.canceled.connect(stop_cb)

    speech_recognizer.start_continuous_recognition_async()
    while not done:
        time.sleep(.5)

from_mic11()

How to start and stop recognizing.
<img width="929" alt="Speech-to-text" src="https://user-images.githubusercontent.com/84219490/127821885-e65e7a01-3c74-402a-a8c4-25cb6d75716b.PNG">

**Comment by abhishekk673** [comment]
@joshholmes @paulbatum @Porges @berberich @dargilco

**Comment by glharper** [comment]
@abhishekk673 Thanks for using Speech SDK, and writing this issue up. In the code above:
- Where are you setting up the AudioConfig? 
- Why are you calling start_continuous_recognition_async() twice? I'm not seeing that in the sample.
- The stop_continuous_recognition_async() call needs to be the last line of from_mic11, not in the stop_cb()

Hopefully fixing those items will get you started.

**Comment by abhishekk673** [comment]
import azure.cognitiveservices.speech as speechsdk

def mic11():
    speech_config = speechsdk.SpeechConfig(subscription="", region="")
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config)
    speech_recognizer.start_continuous_recognition_async()

    done = False

    def stop_cb(evt):
        print('CLOSING on {}'.format(evt))
        nonlocal done
        done = True

        speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
        speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
        speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
        speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
        speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))

        speech_recognizer.session_stopped.connect(stop_cb)
        speech_recognizer.canceled.connect(stop_cb)

        while not done:
            time.sleep(.5)

    speech_recognizer.stop_continuous_recognition_async()




The Issue Remains the same.I'm trying to develop button for starting the conversation and stop the conversation after speaking.How to do that?

**Comment by abhishekk673** [comment]
@glharper @dargilco @oskoller

**Comment by glharper** [comment]
@abhishekk673 It appears your event connection code (including and after speech_recognizer.recognizing.connect) is now part of the stop_cb() method because of the indentation. Please don't indent the event connection code. Try something like:
```
def mic11():
    speech_config = speechsdk.SpeechConfig(subscription="", region="")
    audio_config = speechsdk.audio.AudioConfig(filename=YOUR_FILENAME_HERE)
    language = 'en-US'
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, language=language, audio_config=audio_config)

    done = False

    def stop_cb(evt):
        print('CLOSING on {}'.format(evt))
        nonlocal done
        done = True

    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
    speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))

    speech_recognizer.session_stopped.connect(stop_cb)
    speech_recognizer.canceled.connect(stop_cb)

    speech_recognizer.start_continuous_recognition_async()
    while not done:
        time.sleep(.5)

    speech_recognizer.stop_continuous_recognition_async()
```

**Comment by abhishekk673** [comment]
Thanks @glharper Its working now.I'm trying to add a start and stop button to this.How to split them into start and stop functions and how to stop this functionality.

**Comment by abhishekk673** [comment]
@glharper I'm trying to build like this one.In order to start the conversation hit the start button.To stop the coversation hit stop.
<img width="880" alt="start-recognising" src="https://user-images.githubusercontent.com/84219490/128044223-8a1ac9af-50cd-4e82-a52e-7c842d7dc8bc.PNG">
<img width="835" alt="stop-recognising" src="https://user-images.githubusercontent.com/84219490/128044233-006210db-f783-482c-bc60-74a73abd2cc6.PNG">

**Comment by pankopon** [comment]
I believe the code I posted in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1195 can be used as a working example of separating start/stop controls from the recognition thread. In your code where the Start (Speak) button press is handled, call `start_recognition.set()`, and in the handler of Stop button, call `stop_recognition.set()`. Hope this helps, please create a new issue in case more support is needed.
