### ISSUE TITLE
How to stop_continuous_recognition_async()

### ISSUE THREAD

**Issue by abhishekk673** [Azure-Samples/cognitive-services-speech-sdk#1195]
def speech_recognize_continuous_from_microphone():
    """performs continuous speech recognition with input from an audio file"""
    # <SpeechContinuousRecognitionWithFile>
    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)

    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config)

    done = False

    def stop_cb(evt):
        """callback that signals to stop continuous recognition upon receiving an event `evt`"""
        print('CLOSING on {}'.format(evt))
        nonlocal done
        done = True

    # Connect callbacks to the events fired by the speech recognizer
    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
    speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))
    # stop continuous recognition on either session stopped or canceled events
    speech_recognizer.session_stopped.connect(stop_cb)
    speech_recognizer.canceled.connect(stop_cb)

    # Start continuous speech recognition
    speech_recognizer.start_continuous_recognition_async()
    while not done:
        time.sleep(.5)

    speech_recognizer.stop_continuous_recognition_async()
    
Ran this code.But it runs indefinetely without stopping.How to stop it and how to create seperate functions for start and stop?
<img width="556" alt="Start-Continuous-Recognition" src="https://user-images.githubusercontent.com/84219490/127966307-fb4d3b13-5529-430f-8b2e-27ef53e6fec5.PNG">

**Comment by abhishekk673** [comment]
@glharper

**Comment by pankopon** [comment]
This is apparently modified from speech_recognize_continuous_from_file(). In the original it would stop based on the session_stopped event which would always follow the canceled event which would automatically occur when the file ends. Because now the input is microphone, there is no end of stream and `done` is never set True. You need a separate input event like a key press to stop it.

The simplest change is to replace
```
while not done:
    time.sleep(.5)
```
with e.g.
```
input("Press a key to stop...\n")
```
so that recognition stops when you press a key. (Depending on the exact moment this occurs, it may take a few seconds for recognition to ramp down the service connection and finish.)

**Comment by abhishekk673** [comment]
@pankopon where to add this Input("press a key to stop ..\n")?Is there any way to separate both these functionalities and call them separately?

import azure.cognitiveservices.speech as speechsdk
import time
def from_mic11():
    speech_config = speechsdk.SpeechConfig(subscription="628b2561066c49b5a91eaf369c8a81de", region="eastus")
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config)
    speech_recognizer.start_continuous_recognition_async()

    done = False

    def stop_cb(evt):
        print('CLOSING on {}'.format(evt))
        
        nonlocal done
        done = True

    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
    speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))

    speech_recognizer.session_stopped.connect(stop_cb)
    speech_recognizer.canceled.connect(stop_cb)
    
    while not done:
        time.sleep(.5)
    
    input("Press a key to stop...\n")
    
    speech_recognizer.stop_continuous_recognition_async()
from_mic11()

**Comment by pankopon** [comment]
Like said, replace
```
while not done:
    time.sleep(.5)
```
in code with
```
input("Press a key to stop...\n")
```

For separate start/stop functions/control, try something like below: create a new thread for recognition, then use Python threading events to notify the recognition thread when to start/stop. In this case, start and stop are triggered by a key press in the main thread.

```
import threading

try:
    import azure.cognitiveservices.speech as speechsdk
except ImportError:
    print("""
    Importing the Speech SDK for Python failed.
    Refer to
    https://docs.microsoft.com/azure/cognitive-services/speech-service/quickstart-python for
    installation instructions.
    """)
    import sys
    sys.exit(1)

# Replace with your own subscription key and service region (e.g., "westus").
speech_key, service_region = "YourSubscriptionKey", "YourServiceRegion"

# Events to control recognition start/stop in a separate thread
start_recognition = threading.Event()
stop_recognition = threading.Event()


def recognize_speech():
    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)

    # create a speech recognizer instance
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config)

    def canceled_cb(evt):
        try:
            result = evt.result
            if result.reason == speechsdk.ResultReason.Canceled:
                cancellation_details = result.cancellation_details
                print('CANCELED: {}'.format(cancellation_details.reason))
                if cancellation_details.reason == speechsdk.CancellationReason.Error:
                    print('Error details: {}'.format(cancellation_details.error_details))
        except Exception as e:
            print(e)

    # connect callbacks to events fired by the speech recognizer
    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED: {}'.format(evt)))
    speech_recognizer.canceled.connect(canceled_cb)

    # wait for a notification to start recognition
    start_recognition.wait()

    # start continuous speech recognition
    speech_recognizer.start_continuous_recognition()

    # wait for a notification to stop recognition
    stop_recognition.wait()

    # stop continuous speech recognition
    speech_recognizer.stop_continuous_recognition()


if __name__ == '__main__':
    thread1 = threading.Thread(target=recognize_speech)
    thread1.start()
    input("Press a key to start recognition...\n")
    start_recognition.set()
    input("Press a key to stop recognition...\n")
    stop_recognition.set()
    thread1.join()
```

Alternatively you could call `start_recognition.set()` and `stop_recognition.set()` from inside functions, possibly in different threads, and instead of user input they could be triggered by some other logic in your app.
