### ISSUE TITLE
Stop_pronunciation_assesment and how to display what is spoken by user?

### ISSUE THREAD

**Issue by abhishekk673** [Azure-Samples/cognitive-services-speech-sdk#1196]
def pronunciation_assessment_from_microphone():
    """"performs one-shot pronunciation assessment asynchronously with input from microphone."""

    # Creates an instance of a speech config with specified subscription key and service region.
    # Replace with your own subscription key and service region (e.g., "westus").
    # Note: The pronunciation assessment feature is currently only available on en-US language.
    config = speechsdk.SpeechConfig(subscription="", region="")

    # The pronunciation assessment service has a longer default end silence timeout (5 seconds) than normal STT
    # as the pronunciation assessment is widely used in education scenario where kids have longer break in reading.
    # You can adjust the end silence timeout based on your real scenario.
    config.set_property(speechsdk.PropertyId.SpeechServiceConnection_EndSilenceTimeoutMs, "3000")

    reference_text = ""
    # create pronunciation assessment config, set grading system, granularity and if enable miscue based on your requirement.
    pronunciation_config = speechsdk.PronunciationAssessmentConfig(reference_text=reference_text,
                                                                   grading_system=speechsdk.PronunciationAssessmentGradingSystem.HundredMark,
                                                                   granularity=speechsdk.PronunciationAssessmentGranularity.Phoneme,
                                                                   enable_miscue=True)

    recognizer = speechsdk.SpeechRecognizer(speech_config=config)
    while True:
        # Receives reference text from console input.
        print('Enter reference text you want to assess, or enter empty text to exit.')
        print('> ')

        try:
            reference_text = input()
        except EOFError:
            break

        pronunciation_config.reference_text = reference_text
        pronunciation_config.apply_to(recognizer)

        # Starts recognizing.
        print('Read out "{}" for pronunciation assessment ...'.format(reference_text))

        # Note: Since recognize_once() returns only a single utterance, it is suitable only for single
        # shot evaluation.
        # For long-running multi-utterance pronunciation evaluation, use start_continuous_recognition() instead.
        result = recognizer.recognize_once_async().get()

        # Check the result
        if result.reason == speechsdk.ResultReason.RecognizedSpeech:
            print('Recognized: {}'.format(result.text))
            print('  Pronunciation Assessment Result:')

            pronunciation_result = speechsdk.PronunciationAssessmentResult(result)
            print('    Accuracy score: {}, Pronunciation score: {}, Completeness score : {}, FluencyScore: {}'.format(
                pronunciation_result.accuracy_score, pronunciation_result.pronunciation_score,
                pronunciation_result.completeness_score, pronunciation_result.fluency_score
            ))
            print('  Word-level details:')
            for idx, word in enumerate(pronunciation_result.words):
                print('    {}: word: {}, accuracy score: {}, error type: {};'.format(
                    idx + 1, word.word, word.accuracy_score, word.error_type
                ))
        elif result.reason == speechsdk.ResultReason.NoMatch:
            print("No speech could be recognized")
        elif result.reason == speechsdk.ResultReason.Canceled:
            cancellation_details = result.cancellation_details
            print("Speech Recognition canceled: {}".format(cancellation_details.reason))
            if cancellation_details.reason == speechsdk.CancellationReason.Error:
                print("Error details: {}".format(cancellation_details.error_details))
                
                
pronunciation_assessment_from_microphone()

After Running this code.How to stop the pronunication assesment.It keeps on asking the next question.It is also not displaying what is pronounced.
<img width="671" alt="pronunciation-assesment" src="https://user-images.githubusercontent.com/84219490/127966782-acd8e153-dbc0-41bc-b914-5a83a7a09f02.PNG">

**Comment by pankopon** [comment]
Hi, the code has a loop
```
while True:
    ...
    try:
        reference_text = input()
    except EOFError:
        break
```
so if you don't want the assessment to repeat, either enter an empty line when asked for reference text, or remove the loop in code. Please see pronunciation_assessment_continuous_from_file() for comparison and spend some time familiarizing yourself with the code and syntax.

The sample does display what is spoken - in your example, apparently "Hi." (display format with capitalization and punctuation) which is read from `result.text` and "hi" (lexical form) from `word.word`. (If you meant displaying phonetic notation like in the International Phonetic Alphabet, it is not supported.) But you might want to try it with a longer sentence for more proper results, for example:

```
Enter reference text you want to assess, or enter empty text to exit.
>what's the weather like
Read out "what's the weather like" for pronunciation assessment ...
Recognized: What's the weather like?
  Pronunciation Assessment Result:
    Accuracy score: 100.0, Pronunciation score: 100.0, Completeness score : 100.0, FluencyScore: 100.0
  Word-level details:
    1: word: what's, accuracy score: 100.0, error type: None;
    2: word: the, accuracy score: 100.0, error type: None;
    3: word: weather, accuracy score: 100.0, error type: None;
    4: word: like, accuracy score: 98.0, error type: None;
```

**Comment by abhishekk673** [comment]
@pankopon thanks issue resolved
