### ISSUE TITLE
[Keyword Recognition] Support to the Italian language

### ISSUE THREAD

**Issue by lrodorigo** [Azure-Samples/cognitive-services-speech-sdk#1197]
Hi, I would to know if there is any plan to release the Keyword recognition service for the italian language.

**Comment by pankopon** [comment]
Hi, thank you for the query. The latest status is:

- At the moment there is no concrete date for official it-IT support.
- However, it is worth trying to leverage the en-US on-device model from Custom Keyword for the Italian keyword, if the keyword pronunciations map relatively well to the English language. The keyword verification model in the service is en-*, so it will likely perform well if the pronunciations map well.

**Comment by pankopon** [comment]
Closed as answered, please open a new issue of more support is needed.
