### ISSUE TITLE
How can I get the confidence score from the speech result?

### ISSUE THREAD

**Issue by boldragon** [Azure-Samples/cognitive-services-speech-sdk#12]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [V] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). Other.

### Versions
>

### Mention any other details that might be useful
during this Speech SDK porting, I couldn't find any confidence score which I would be able to utilize the value to retry the ASR. 
on the result class, I've only found ; ErrorDetails, Properties, Reason, ResultId, Text.

Is there any way to get its confidence score, or get the result as NBest list?
(I used to have confidence score former bing asr api.)

Please let me know if you have answers or plans. 
Thank you in advance, Good day! ;)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by zhouwangzw** [comment]
The SDK 0.4.0 can give you confidence value if the output format is specified as detailed, e.g. 
[public Microsoft.CognitiveServices.Speech.SpeechRecognizer CreateSpeechRecognizer (string language, Microsoft.CognitiveServices.Speech.SpeechOutputFormat format);
](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechfactory.createspeechrecognizer?view=azure-dotnet#Microsoft_CognitiveServices_Speech_SpeechFactory_CreateSpeechRecognizer_System_String_Microsoft_CognitiveServices_Speech_SpeechOutputFormat_), then the [SpeechRecognitionResult.Best()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechrecognitionresultextensions?view=azure-dotnet) will give you the detailed output including confidence score.

Thanks

**Comment by zhouwangzw** [comment]
The confidence value is also available in C++, but not via Best(). The detailed output in Json format is stored in SpeechRecognitionResult.Properties[ResultProperty::Json].

**Comment by boldragon** [comment]
Checked. Thank you for your great support! =)

**Comment by vkim** [comment]
In Java I got it like this:
`PropertyCollection properties = e.getResult().getProperties();
String property = properties.getProperty(PropertyId.SpeechServiceResponse_JsonResult);`

**Comment by KrishnaChaitanyaL** [comment]
> The confidence value is also available in C++, but not via Best(). The detailed output in Json format is stored in SpeechRecognitionResult.Properties[ResultProperty::Json].

Since the Best() method returns the IEnumerable<DetailedSpeechRecognitionResult>, can we just go with the one with highest Confidence value or take the average?

**Comment by soumyadipchatterjee** [comment]
I am not getting the confidence score. How can I get that?

document.addEventListener("DOMContentLoaded", function () {
    startRecognizeOnceAsyncButton = document.getElementById("startRecognizeOnceAsyncButton");
    subscriptionKey = document.getElementById("subscriptionKey");
    serviceRegion = document.getElementById("serviceRegion");
    phraseDiv = document.getElementById("phraseDiv");

    startRecognizeOnceAsyncButton.addEventListener("click", function () {
      startRecognizeOnceAsyncButton.disabled = true;
      phraseDiv.innerHTML = "";

      // if we got an authorization token, use the token. Otherwise use the provided subscription key
      var speechConfig;
      if (authorizationToken) {
        speechConfig = SpeechSDK.SpeechConfig.fromAuthorizationToken(authorizationToken, serviceRegion.value);
      } else {
        if (subscriptionKey.value === "" || subscriptionKey.value === "subscription") {
          alert("Please enter your Microsoft Cognitive Services Speech subscription key!");
          return;
        }
        speechConfig = SpeechSDK.SpeechConfig.fromSubscription(subscriptionKey.value, serviceRegion.value);
       

      }
      speechConfig.OutputFormat = 1;
      speechConfig.speechRecognitionLanguage = "en-US";
      var audioConfig  = SpeechSDK.AudioConfig.fromDefaultMicrophoneInput();
      recognizer = new SpeechSDK.SpeechRecognizer(speechConfig, audioConfig);

      recognizer.recognizeOnceAsync(
        function (result) {
          console.log(result)
          // if (result.Reason == ResultReason.RecognizedSpeech){
            // var detailedResults = result.Best();
          // }

          console.log(result.getJson());
          startRecognizeOnceAsyncButton.disabled = false;
          phraseDiv.innerHTML += result.text;
          // window.console.log(result);

          recognizer.close();
          recognizer = undefined;
        },
        function (err) {
          startRecognizeOnceAsyncButton.disabled = false;
          phraseDiv.innerHTML += err;
          window.console.log(err);

          recognizer.close();
          recognizer = undefined;
        });
    });
Is there anything that I am missing?

**Comment by chlandsi** [comment]
@soumyadipchatterjee The javascript bindings don't expose the detailed results as the `.Best()` property on the SpeechRecognitionResult. You can, however, get the json representation of the detailed result, which is accessible on the [SpeechRecognitionResult](https://docs.microsoft.com/javascript/api/microsoft-cognitiveservices-speech-sdk/speechrecognitionresult?view=azure-node-latest) as `.json`.

**Comment by soumyadipchatterjee** [comment]
Sorry, my mistake. I have to use speechConfig.outputFormat = 1 not speechConfig.OutputFormat = 1;.
Now I can get the detailed output. 
Anyway thank you :)

**Comment by manojmsrit** [comment]
How can I enable "Word level confidence" for MS Azure service using Python language. What configuration needs to be modified ? Please suggest me regarding this. Thank you in advance.

**Comment by amitkumarshukla** [comment]
Please follow this 
https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.speechconfig?view=azure-python#set-service-property-name--str--value--str--channel--azure-cognitiveservices-speech-servicepropertychannel-

You need to use the following property in your speech config
set_service_property(name: str, value: str, channel: azure.cognitiveservices.speech.ServicePropertyChannel) 

Like this
import azure.cognitiveservices.speech as msspeech

config.set_service_property(name='wordLevelConfidence', value='true', channel=msspeech.ServicePropertyChannel.UriQueryParameter)
config.set_service_property(name='format', value='detailed', channel=msspeech.ServicePropertyChannel.UriQueryParameter)

That will help you get the detailed result in the final json output like this 
{"Id":"12345767e9984244b4386631bd8a3b3d","RecognitionStatus":"Success","Offset":500000,"Duration":13200000,"DisplayText":"What's the weather like?","NBest":[{"Confidence":0.97701865,"Lexical":"what's the weather like","ITN":"what's the weather like","MaskedITN":"what's the weather like","Display":"What's the weather like?","Words":[{"Word":"what's","Confidence":0.9752328},{"Word":"the","Confidence":0.9912971},{"Word":"weather","Confidence":0.9947196},{"Word":"like","Confidence":0.9936005}]},{"Confidence":0.92623466,"Lexical":"what is the weather like","ITN":"what is the weather like","MaskedITN":"what is the weather like","Display":"What is the weather like?","Words":[{"Word":"what","Confidence":0.44181886},{"Word":"is","Confidence":0.020716537},{"Word":"the","Confidence":0.77797073},{"Word":"weather","Confidence":0.8319083},{"Word":"like","Confidence":0.8447693}]}]}

Do let us know if you need anything else.

**Comment by cembora** [comment]
How can I take word level confidence on java(Android)?. I can take detailed json result when I set speechConfig.outputFormat = OutputFormat.Detailed but this not gives me word level confidence. I tried to set   speechConfig.setProperty("wordLevelConfidence","true") but no luck.

**Comment by ziadhassan7** [comment]
**This worked for me**

```
SpeechConfig config = SpeechConfig.fromSubscription(speechSubscriptionKey, serviceRegion);

config.setServiceProperty("wordLevelConfidence","true", ServicePropertyChannel.UriQueryParameter);
config.setServiceProperty("format", "detailed", ServicePropertyChannel.UriQueryParameter);
```
