### ISSUE TITLE
Azure start_continuous_recognition

### ISSUE THREAD

**Issue by abhishekk673** [Azure-Samples/cognitive-services-speech-sdk#1200]
Hello @glharper,
While running this piece of code.

    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
    
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED: {}'.format(evt)))
    speech_recognizer.canceled.connect(canceled_cb)

I got output like this 
<img width="751" alt="Start-Continuous-Recognition-list" src="https://user-images.githubusercontent.com/84219490/128443387-56c828c3-a9ba-4b3d-b570-3532598f7148.PNG">

instead of this 

RECOGNIZING: SpeechRecognitionEventArgs(session_id=a9a54e348c6e4b4a9e614b2f51200476, result=SpeechRecognitionResult(result_id=0d0c91269fea4535ae3836a93f076190, text="hello can you start speaking", reason=ResultReason.RecognizingSpeech))
C

i just only require "hello can you start speaking".

The output is printing in terminal.How to publish the terminal output into streamlit webapp ?

start_recognition = threading.Event()
stop_recognition = threading.Event()

def recognize_speech():
    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)

    # create a speech recognizer instance
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config)
    speech_recognizer

    def canceled_cb(evt):
        try:
            result = evt.result
            if result.reason == speechsdk.ResultReason.Canceled:
                cancellation_details = result.cancellation_details
                print('CANCELED: {}'.format(cancellation_details.reason))
                if cancellation_details.reason == speechsdk.CancellationReason.Error:
                    print('Error details: {}'.format(cancellation_details.error_details))
        except Exception as e:
            print(e)

    # connect callbacks to events fired by the speech recognizer
    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)[2]))
    
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED: {}'.format(evt)))
    speech_recognizer.canceled.connect(canceled_cb)

    # wait for a notification to start recognition
    start_recognition.wait()

    # start continuous speech recognition
    speech_recognizer.start_continuous_recognition_async()

    # wait for a notification to stop recognition
    stop_recognition.wait()

    # stop continuous speech recognition
    speech_recognizer.stop_continuous_recognition_async()

if __name__ == '__main__':
    thread1 = threading.Thread(target=recognize_speech)
    thread1.start()
    input("Press a key to start recognition...\n")
    start_recognition.set()
    input("Press a key to stop recognition...\n")
    stop_recognition.set()
    thread1.join()

Can we write seperate functions to call start_recognition and stop_recognition?

**Comment by pankopon** [comment]
Please see below for some examples. `recognize_speech()` now writes into a queue and `consume_results()` reads from it, `result` contains the latest text (recognizing or recognized). Remove any prints you don't need. Call `start_recognition()` and `stop_recognition()` from where you want to start and stop. If only final recognized text is needed, remove or comment out `speech_recognizer.recognizing.connect(recognizing_cb)`. Note that some more error handling in case of cancellation due to an error would be probably very good to have. Add/modify threads, queues, globals as necessary.

```
import threading
import queue

try:
    import azure.cognitiveservices.speech as speechsdk
except ImportError:
    print("""
    Importing the Speech SDK for Python failed.
    Refer to
    https://docs.microsoft.com/azure/cognitive-services/speech-service/quickstart-python for
    installation instructions.
    """)
    import sys
    sys.exit(1)

# Replace with your own subscription key and service region (e.g., "westus").
speech_key, service_region = "YourSubscriptionKey", "YourServiceRegion"

# Global events to control recognition start/stop in a separate thread
event_start_recognition = threading.Event()
event_stop_recognition = threading.Event()
end_of_results = object()


def recognize_speech(out_q):
    print('ENTER recognize_speech')
    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)

    # create a speech recognizer instance
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config)

    def canceled_cb(evt):
        try:
            result = evt.result
            if result.reason == speechsdk.ResultReason.Canceled:
                cancellation_details = result.cancellation_details
                print('CANCELED: {}'.format(cancellation_details.reason))
                if cancellation_details.reason == speechsdk.CancellationReason.Error:
                    print('Error details: {}'.format(cancellation_details.error_details))
        except Exception as e:
            print(e)

    def recognizing_cb(evt):
        if "RecognizingSpeech" in str(evt.result.reason):
            out_q.put(evt.result.text)

    def recognized_cb(evt):
        if "RecognizedSpeech" in str(evt.result.reason):
            out_q.put(evt.result.text)

    # connect callbacks to events fired by the speech recognizer
    speech_recognizer.recognizing.connect(recognizing_cb)
    speech_recognizer.recognized.connect(recognized_cb)
    speech_recognizer.canceled.connect(canceled_cb)

    # wait for notification to start
    event_start_recognition.wait()

    # start continuous speech recognition
    speech_recognizer.start_continuous_recognition()

    # wait for notification to stop
    event_stop_recognition.wait()

    # stop continuous speech recognition
    speech_recognizer.stop_continuous_recognition()

    # indicate end of results
    out_q.put(end_of_results)
    print('EXIT recognize_speech')


def consume_results(in_q):
    print('ENTER consume_results')
    while True:
        result = in_q.get()
        if result is end_of_results:
            in_q.put(end_of_results)
            break
        else:
            print(result)
    print('EXIT consume_results')


def start_recognition():
    event_start_recognition.set()

def stop_recognition():
    event_stop_recognition.set()


if __name__ == '__main__':
    q = queue.Queue()
    thread1 = threading.Thread(target=consume_results, args=(q, ))
    thread1.start()
    thread2 = threading.Thread(target=recognize_speech, args=(q, ))
    thread2.start()
    
    input("Press a key to start recognition...\n")
    start_recognition()
    input("Press a key to stop recognition...\n")
    stop_recognition()

    thread2.join()
    thread1.join()
```

**Comment by abhishekk673** [comment]
Thanks @glharper Your code is working.I'm getting output like this.




<img width="847" alt="strat-stop-continuous" src="https://user-images.githubusercontent.com/84219490/128453400-85a8baa8-6cd8-4900-8a3e-5ab59c542696.PNG">

But I only require last  line as output.

Hello, can you start recognizing something?

**Comment by abhishekk673** [comment]
hello @pankopon @glharper 

while Calling  start_recognition() and stop_recognition()  to start and stop.Its not working in the code.Can you please check once

**Comment by Datakult0r** [comment]
@mlnewbie987 I would like to get in touch with you - we have a couple of agents identifying people that are interested in repurposing their skillset to genAI and that's what we do. your name popped up, if you want to reach me usually on discord (datakult2047) or LinkedIN (https://www.linkedin.com/in/philippe-k%C3%BCng-a315ba4b/)
