### ISSUE TITLE
Build your app in LUIS portal tutorial only returning RecognizedSpeech

### ISSUE THREAD

**Issue by Captain-Oppai** [Azure-Samples/cognitive-services-speech-sdk#1203]
**Describe the bug**
After finishing the tutorial [here](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-get-started-create-app), the finished project never returns anything other than "Intent not recognized" regardless of the intent I'm trying to test.

**To Reproduce**
1. Follow the tutorial from the link above
2. Fill in the subscription key, service region, and app ID
3. Attempt to test the project and say any phrase

**Expected behavior**
The program should return with intent based on the LUIS app I've made and any entities associated with the phrase and recognized by the model.

**Version of the Cognitive Services Speech SDK**
1.18.0

**Additional context**
[log.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6950201/log.txt)

I have attempted to use both 'AddAllIntents()' and 'AddIntent()' functions (as well in tandum) but in either case still fails to work.

**Comment by jhakulin** [comment]
@Captain-Oppai Thanks for the report. we will check.

**Comment by jhakulin** [comment]
@Captain-Oppai We have checked that in your session and seems that used key is not authorized to do the required intent operation.

Could you please get the prediction resource and use that key? See link below.
https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-how-to-azure-subscription?tabs=portal

In addition, we are making change to service to show an error in case of invalid key is being used.

**Comment by Captain-Oppai** [comment]
That was it, thanks! I think an error like that would really help (especially for people who are not well versed in using Azure).
