### ISSUE TITLE
Should KeywordRecognitionModel be singleton or transient

### ISSUE THREAD

**Issue by ShrivastavaAkash** [Azure-Samples/cognitive-services-speech-sdk#1205]
Hi,

I'm trying to run this SDK on a server app where different audio streaming sessions may have the `Keywords` that the app needs to recognize.

I have created a model for Keyword Recognition from speech studio and I'm seeing huge performance problems when I run close to ~10 concurrent sessions.

Right now I'm using the model as a singleton, so all sessions share the same model instance (which works fine for 2-5 sessions).

What is the best practice regarding this? should I create a new `KeywordRecognitionModel` instance for each session? 

A close approximation of the code looks like below:

```c#
// static/singleton model instance
static KeywordRecognitionModel model = KeywordRecognitionModel.FromFile($"{modelPath}");


// all below instances are 1 per session
var callback = new CustomPullStreamReaderCallback();
PullAudioInputStream pullStream = AudioInputStream.CreatePullStream(callback);
var audioConfig = AudioConfig.FromStreamInput(pullStream);
var kw = new KeywordRecognizer(audioConfig);

var result = await context.Recognizer.RecognizeOnceAsync(model);
```

Speech SDK version used: 1.16.0
Application Env: Linux container (azure AKS)
Technology: .Net 5 (C#)

**Comment by jhakulin** [comment]
@ShrivastavaAkash Thanks for the report. We are checking what is the main reason for the performance issue and let you know what could be best approach here. I believe it is just due to several instances of KeywordRecognizer running at the same time. I would believe also that using singleton model or several model (e.g. separate KWS model per instance) does not make a difference to performance.

**Comment by jhakulin** [comment]
After checking this, it is known that current KWS model is CPU expensive and that is the reason for the CPU load issue you have with several instances (over 5). We have work ongoing to improve the model in future to consume less CPU and memory. Closing the item.
