### ISSUE TITLE
[Speech Service SDK] JAVA API to set the Proxy

### ISSUE THREAD

**Issue by mirza-samsung** [Azure-Samples/cognitive-services-speech-sdk#121]
Hello,

  We are trying 'Java' Speech sample inside company network. And we are getting connectionError.
  
Error details :
Session started event.
CANCELED: Reason=Error
CANCELED: ErrorCode=ConnectionFailure
CANCELED: ErrorDetails=Connection failed (no connection to the remote host). Internal error: 8. Error details: 998. Please check network connection, firewall setting, and the region name used to create speech factory.
CANCELED: Did you update the subscription info?

C++ version works fine after overloaded 2 parameter SetProxy API

config->SetProxy(string proxyHostName, int proxyPort);

Same is not available in JAVA. We are getting compilation error.
config.setProxy(string proxyHostName, int proxyPort);

When we try to use below API by passing empty/NULL to 3rd & 4th parameter, it doesn't work even from C++ sample. We are getting same connection error.
public void SetProxy (string proxyHostName, int proxyPort, string proxyUserName, string proxyPassword);

So could you please let us know JAVA API to setProxy similar to C++ (2 parameter) or any other  API to set the Proxy ?

Thanks,

**Comment by zhouwangzw** [comment]
For Java API setProxy, you need to set both proxyUserName and proxyPassword to empty, if there is no username and password needed for the proxy, e.g
config.setProxy("somehost", "1234", "", "");

We will make it clearer in documentation. 

Thanks,

**Comment by mirza-samsung** [comment]
Thanks for your reply.
Actually we tried the same by passing empty string, but it doesn't work in both C++ & Java.

Java doesn't have 2 parameter overloaded functions, it has only 4 parameter setProxy function which doen't work
config.setProxy("somehost", "1234", "", "");

In C++, 2 parameter overloaded functions works fine.
config->SetProxy(proxyHostName, proxyPort); ==> Works fine in C++
config->SetProxy(proxyHostName, proxyPort,"",""); ===> Doesn't work, some error

**Comment by zhouwangzw** [comment]
Thanks for reporting. It seems that some proxy servers do not like empty string for user name and password. We will change not to send authorization headers if user name or password is empty. It will be available in the next release.

**Comment by wolfma61** [comment]
please retry with the latest version 1.3.1
we fixed proxy setting with empty usernames and passwords.
