### ISSUE TITLE
Exception with an error code: 0x38 (SPXERR_AUDIO_SYS_LIBRARY_NOT_FOUND) when using Heroku cloud

### ISSUE THREAD

**Issue by aditya17082010** [Azure-Samples/cognitive-services-speech-sdk#1215]
bk

**Comment by amitkumarshukla** [comment]
@bhargav27k Could you please provide the sample code and repro steps ? Please provide the platform info too.

**Comment by bhargav27k** [comment]
hello @amitkumarshukla @glharper @pankopon 

import azure.cognitiveservices.speech as speechsdk
import sys
import streamlit as st

st.set_page_config(page_title="Reading Fluency Web App",page_icon="",layout="centered",initial_sidebar_state="expanded",)
st.title('Reading Fluency Assesment')
st.sidebar.subheader("About App")

def asses_from_microphone():
    """"performs one-shot pronunciation assessment asynchronously with input from microphone."""
    
    # Creates an instance of a speech config with specified subscription key and service region.
    # Replace with your own subscription key and service region (e.g., "westus").
    # Note: The pronunciation assessment feature is currently only available on en-US language.
    config = speechsdk.SpeechConfig(subscription="", region="")

    # The pronunciation assessment service has a longer default end silence timeout (5 seconds) than normal STT
    # as the pronunciation assessment is widely used in education scenario where kids have longer break in reading.
    # You can adjust the end silence timeout based on your real scenario.
    config.set_property(speechsdk.PropertyId.SpeechServiceConnection_EndSilenceTimeoutMs, "3000")

    reference_text = ""
    # create pronunciation assessment config, set grading system, granularity and if enable miscue based on your requirement.
    pronunciation_config = speechsdk.PronunciationAssessmentConfig(reference_text=reference_text,
                                                                   grading_system=speechsdk.PronunciationAssessmentGradingSystem.HundredMark,
                                                                   granularity=speechsdk.PronunciationAssessmentGranularity.Phoneme,
                                                                   enable_miscue=True)

    recognizer = speechsdk.SpeechRecognizer(speech_config=config)
    while True:
        # Receives reference text from console input.
        st.success('Enter reference text you want to assess, or enter stop to exit.')

        try:
            reference_text = st.text_input("Enter your text","")
            if reference_text == "stop":
                st.success('Entered stop to exit')
                sys.exit(0)
        except EOFError:
            break

        pronunciation_config.reference_text = reference_text
        pronunciation_config.apply_to(recognizer)

        # Starts recognizing.
        st.success('\U0001f4E2 Read out "{}" for pronunciation assessment ...'.format(reference_text))
        

        # Note: Since recognize_once() returns only a single utterance, it is suitable only for single
        # shot evaluation.
        # For long-running multi-utterance pronunciation evaluation, use start_continuous_recognition() instead.
        result = recognizer.recognize_once_async().get()

        # Check the result
        if result.reason == speechsdk.ResultReason.RecognizedSpeech:
            st.success('Recognized: {}'.format(result.text))
            st.success('  Pronunciation Assessment Result:')

            pronunciation_result = speechsdk.PronunciationAssessmentResult(result)
            
            st.info(st.info('Accuracy score: {}'.format(pronunciation_result.accuracy_score)))
            st.info(st.info('Pronunciation score: {}'.format(pronunciation_result.pronunciation_score)))
            st.info(st.info('Completeness score: {}'.format(pronunciation_result.completeness_score)))
            st.info(st.info('FluencyScore: {}'.format(pronunciation_result.fluency_score)))
            
            st.success('  Word-level details:')
            for idx, word in enumerate(pronunciation_result.words):
                st.info('    {}: word: {}, accuracy score: {}, error type: {};'.format(
                    idx + 1, word.word, word.accuracy_score, word.error_type
                ))
        elif result.reason == speechsdk.ResultReason.NoMatch:
            #st.error("No speech could be recognized")
            pass
        elif result.reason == speechsdk.ResultReason.Canceled:
            cancellation_details = result.cancellation_details
            st.warning("Speech Recognition canceled: {}".format(cancellation_details.reason))
            if cancellation_details.reason == speechsdk.CancellationReason.Error:
                st.warning("Error details: {}".format(cancellation_details.error_details))
                
        break

 
st.sidebar.info("This web app is made to asses the reading fluency of the user")
st.sidebar.info("Click on start button for assesment")
 
start=st.sidebar.checkbox("Start")
if start:               
    asses_from_microphone()

st.sidebar.info("Type your text in the writing area for speech assesment")
st.sidebar.info("Don't forget to rate this app")

feedback = st.sidebar.slider('How much would you rate this app?',min_value=0,max_value=10,step=1)

if feedback:
  st.header("Thank you for rating the app!")
  st.balloons()

**Comment by bhargav27k** [comment]
hello @amitkumarshukla 

heroku requirements.

================================================================

streamlit==0.86.0
numpy==1.18.1
pandas==0.25.3
azure-cognitiveservices-speech==1.18.0

================================================================

mkdir -p ~/.streamlit/

echo "\
[server]\n\
port = $PORT\n\
enableCORS = false\n\
headless = true\n\
\n\
" > ~/.streamlit/config.toml

================================================================

python-3.7.11

================================================================

I've read about this issue in some comments section that


speech to text app works locally but not in the Heroku cloud. Why? This is because a streamlit/heroku app is hosted server side, therefore my Python code will try to listen to the server's microphone and will obviously result in an error. Solution? WOuld be to run the code client side, meaning Javascript.

How to include streamlit-webrtc code into my code to work on heroku platform ?

Can you please help me with code snippet that is either javascript code snippet or streamlit-webrtc code snippet that can make this work on heroku platform.

**Comment by amitkumarshukla** [comment]
@aditya17082010 Could you please explain your scenario ? From where the audio is coming ? Why do you need Microphone inside Cloud ? Could you read audio packet from network and use PullStream or PushStream to stream it to speech SDK ?

**Comment by aditya17082010** [comment]
Hello @amitkumarshukla 
I'm trying to build a speech recognition app where user can check their pronunciation assessment capabilities.so i'm using azure cognitive services and streamlit and publish as a webapp.But it working fine in local and unable to work while deployed on heroku cloud.So I require microphone in cloud to record audio from speaker and assess it.

Could you read audio packet from network and use PullStream or PushStream to stream it to speech SDK ?
I didn't check it can you please you let me where to add that in my code shared above..

**Comment by amitkumarshukla** [comment]
Pull Stream sample
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/fc581947e3d13cecabf6e365f6c441a690d36a25/samples/python/console/speech_sample.py#L346

Push Stream sample
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/fc581947e3d13cecabf6e365f6c441a690d36a25/samples/python/console/speech_sample.py#L417

Also if you are building webjob consider using Microsoft speech JavaScript SDK
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/browser

Do let me know if that helps

**Comment by samkuls** [comment]
Hi Amit, I have developed api in .net core and want to exposing to our organization . there are two apis. first one is working where i am uploading wave file and performing STT. second is not working when using microphone and deployed on Azure webapp. please let me know solution considering developed in c#

**Comment by samkuls** [comment]
@amitkumarms : please provide me any example of pullstream/pushstream in c#

**Comment by pankopon** [comment]
@samkuls See
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/cca81f48c54bccd5fb6d4e6227c2605edcd0b885/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L416
and
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/cca81f48c54bccd5fb6d4e6227c2605edcd0b885/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L488
for general examples. In the future please create new issues for questions on specific topics.

**Comment by cankatti** [comment]
[e]()
