### ISSUE TITLE
Async Conversation Transcription with RemoteConversationTranscriptionClient completes after first few seconds

### ISSUE THREAD

**Issue by madCodes** [Azure-Samples/cognitive-services-speech-sdk#1216]
I have around 10 min audio recoding of a conversation. I have followed the "RemoteConversationWithFileAsync" sample and I only get first few seconds of transcriptions ( 7 transcription results ) and RemoteConversationTranscriptionOperation is complete. Is some kind of quota kicking in here? I have Standard pricing Tier and I didn't come across any kind of limitation in the documentation.

**Comment by msjunzh** [comment]
@madCodes what's the format of the audio?

**Comment by madCodes** [comment]
I converted an mp3 file to .wav file using audacity and added 7 more silent channels to make it 8. So the final file is wav file with 16000Hz , 16 bit PCM  and 8 channels.

**Comment by msjunzh** [comment]
Thanks. The 8 channel input should be the DDK microphone array format.
In your case, need to the mp3 file to a 16KHZ mono audio and use the single channel.
And add those 2 lines to make it working.
var connection = Connection.FromRecognizer(conversationTranscriber);
connection.SetMessageProperty("speech.config", MicSpec", "\"1_0_0\"");

**Comment by madCodes** [comment]
@msjunzh I have exported the mp3 file to 16KHZ mono single channel and added the lines you suggested, but I see the following error.
": Exception with an error code: 0x14 (SPXERR_UNEXPECTED_CREATE_OBJECT_FAILURE)"

Btw  I'm using this sample code from [here ](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/31abbe1e4b6e3a0bc7d60a72fd3802cb928654dc/samples/csharp/sharedcontent/console/remote_conversation_samples.cs#L128)and I have edited the function "UploadAudioAndStartRemoteTranscription" to add the following lines before line no. 143

```
var connection = Connection.FromRecognizer(conversationTranscriber);
    connection.SetMessageProperty("speech.config", "MicSpec", "1_0_0");
```

**Comment by msjunzh** [comment]
I see, try to add those 2 lines after this?
                    await conversationTranscriber.JoinConversationAsync(conversation);

**Comment by madCodes** [comment]
@msjunzh  Thanks. After moving those 2 lines as suggested error seems to have gone. But it stills stops after 7 transcription results.
I have tried with different audios, all seem to stop after 7 transcription results.

**Comment by msjunzh** [comment]
@madCodes I see. should be some bug for there, I will take a look and update back here.

**Comment by msjunzh** [comment]
@madCodes Need to remove the timer in [L194](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/31abbe1e4b6e3a0bc7d60a72fd3802cb928654dc/samples/csharp/sharedcontent/console/remote_conversation_samples.cs#L194) for longer audio.
Change it to 
            await m_taskCompletionSource.Task;

**Comment by madCodes** [comment]
I missed spotting that line. Thanks, that is the culprit.

**Comment by jhakulin** [comment]
Closing the issue as looks like this has been answered
