### ISSUE TITLE
Cannot access speech recognition, translation, synthesis

### ISSUE THREAD

**Issue by cl-6666** [Azure-Samples/cognitive-services-speech-sdk#1219]
Hello, I have encountered a strange problem. To access your speech recognition, synthesis, and translation, you must change the device dns to access, otherwise an error will be reported，Synthetic error message CancellationReason:Error ErrorCode: RuntimeError ErrorDetails:USP error: timeout waiting for the first

**Comment by cl-6666** [comment]
The current test dns is changed to: 223.5.5.5 can be accessed normally, the tested dns is 114.114.114.114, or use the default dns of the device, the picture below can not be accessed normally
![image](https://user-images.githubusercontent.com/51937265/129820702-b6377614-22f3-4b8f-8d76-6e433e773c00.png)

**Comment by amitkumarshukla** [comment]
@cl-6666 Thanks a lot for your question. Could you please describe the scenario in details. Please provide the platform detail also.

**Comment by cl-6666** [comment]
Hello, I am directly calling this interface: https://api.translator.azure.cn/translate, the problem I described above will appear. Only by changing the dns can the translation be performed normally. The synthesis is directly used by the SDK. , We found this problem on an Android device

**Comment by pankopon** [comment]
@cl-6666 Apparently the domain name server in question cannot resolve the translator service address, main or related, or some connections are blocked. This would require analysis of the DNS server configuration. See https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1105 for how to get a list of all Microsoft service addresses that need to be allowed.
