### ISSUE TITLE
WebSocket connection error on JS - Speech SDK API Intent Recognition

### ISSUE THREAD

**Issue by karthikeyanmlp** [Azure-Samples/cognitive-services-speech-sdk#122]
**Describe the bug**

**Branch:** cognitive-services-speech-sdk/samples/js/browser/
**Error on:** Speech SDK API Intent Recognition
While using sdkIntentStartRecognizeOnceAsyncBtn WebSocket Error occurred.
**Error:**

> WebSocket connection to 'wss://speech.platform.bing.com/speech/uswest/recognition/interactive/cognitiveservices/v1?format=simple&language=en-US&Authorization=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1cm46bXMuY29nbml0aXZlc2VydmljZXMiLCJleHAiOiIxNTQ1MjEwMDMwIiwicmVnaW9uIjoid2VzdHVzIiwic3Vic2NyaXB0aW9uLWlkIjoiN2NkMWZlYWIyZThlNGFmNDg3ZjJiYmZjODEyMzFlNTMiLCJwcm9kdWN0LWlkIjoiU3BlZWNoU2VydmljZXMuRjAiLCJjb2duaXRpdmUtc2VydmljZXMtZW5kcG9pbnQiOiJodHRwczovL2FwaS5jb2duaXRpdmUubWljcm9zb2Z0LmNvbS9pbnRlcm5hbC92MS4wLyIsImF6dXJlLXJlc291cmNlLWlkIjoiL3N1YnNjcmlwdGlvbnMvNzQ2ZWVhMmMtNTNhNS00MDQ3LWJjNGItNTY1NTRiNTIwMDFkL3Jlc291cmNlR3JvdXBzL0VSUy1Cb3RUZXN0L3Byb3ZpZGVycy9NaWNyb3NvZnQuQ29nbml0aXZlU2VydmljZXMvYWNjb3VudHMvRVJTQUlCb3RUZXN0U3BlZWNoU2VydmljZTEiLCJzY29wZSI6InNwZWVjaHNlcnZpY2VzIiwiYXVkIjoidXJuOm1zLnNwZWVjaHNlcnZpY2VzLndlc3R1cyJ9.knmJBdagRT2C3C5FphNr9KtqBO8v46eKZvlpWKeZqnY&X-ConnectionId=61D4134207164BA6B4A69042278BF001' failed: HTTP Authentication failed; no valid credentials available

**To Reproduce**
1. Place LUIS App ID in Application ID
2. Click "recognizeOnceAsync()" button on "Speech SDK API Intent Recognition"

**Expected behavior**
Intent will not return, Web Socket error occurred in-between

**Version of the Cognitive Services Speech SDK**
_cognitive-services-speech-sdk/samples/js/browser/_

**Platform, Operationg System, and Programming Language**
 - OS: Windows
 - Hardware - x86
 - Browser  chrome

**Additional context**
 - Speech SDK API recognizeOnceAsync, Speech SDK API Continuous Speech Recognition are working file only problem on Speech SDK API Intent Recognition

**Comment by fmegen** [comment]
since you are using an authorization token, please make sure it is not expired.
currently, the speech sdk does not automatically retrieve or renew a token but instead relies on the client code to regulary update the token.

please retry using the subscription key and see if you still see the connection error.

**Comment by karthikeyanmlp** [comment]
> since you are using an authorization token, please make sure it is not expired (which usually happens only a few minutes after requesting the token).
> 
> currently, the speech sdk does not automatically retrieve or renew a token but instead relies on the client code to regulary update the token.
> 
> please retry using the subscription key and see if you still see the connection error.

Can you please describe where(on which file and where) the changes required?

**Comment by karthikeyanmlp** [comment]
> since you are using an authorization token, please make sure it is not expired (which usually happens only a few minutes after requesting the token).
> 
> currently, the speech sdk does not automatically retrieve or renew a token but instead relies on the client code to regulary update the token.
> 
> please retry using the subscription key and see if you still see the connection error.

**Comment by karthikeyanmlp** [comment]
> since you are using an authorization token, please make sure it is not expired (which usually happens only a few minutes after requesting the token).
> 
> currently, the speech sdk does not automatically retrieve or renew a token but instead relies on the client code to regulary update the token.
> 
> please retry using the subscription key and see if you still see the connection error.

Thanks for your response @fmegen 

I have checked. With the authorization token all other services are working fine.
**Speech SDK API Intent Recognition** only having problem with socket connection.

**Comment by fmegen** [comment]
You need to use the LanguageUnderstanding SubscriptionKey to retrieve the Access Token.
The speech subscription key cannot be used to access the Intent api.

But since you have an Language Understanding AppId, you should have the corresponding Subscription Key already. Please use this subscription when requesting the token.

kind regards,
 friedel

**Comment by karthikeyanmlp** [comment]
> You need to use the LanguageUnderstanding SubscriptionKey to retrieve the Access Token.
> The speech subscription key cannot be used to access the Intent api.
> 
> But since you have an Language Understanding AppId, you should have the corresponding Subscription Key already. Please use this subscription when requesting the token.
> 
> kind regards,
> friedel

Now its working fine for me 
Thanks @fmegen

**Comment by fmegen** [comment]
Thank you for your suggestions.
I created a pull request adding a Note to the SpeechConfig class.
https://github.com/Microsoft/cognitive-services-speech-sdk-js/pull/14

**Comment by i524304** [comment]
Hey @fmegen,

While using cognitive servcices speech options for web chat using this sample (https://github.com/microsoft/BotFramework-Samples/blob/master/docs-samples/web-chat-speech/index.html) i am getting this web sockect connection error 

Error : WebSocket connection to 'wss://speech.platform.bing.com/speech/recognition/interactive/cognitiveservices/v1?format=simple&language=en-US&Ocp-Apim-Subscription-Key=c21f56822fe046e8ac67d5b47dbb2b6e&X-ConnectionId=2607EB6D18B74798BD56FAA15AE367A0' failed: HTTP Authentication failed; no valid credentials available
Open @ WebsocketMessageAdapter.ts:81
Open @ WebsocketConnection.ts:97
(anonymous) @ Recognizer.ts:170
(anonymous) @ Promise.ts:234
ExecuteSuccessCallback @ Promise.ts:435
on @ Promise.ts:424
ContinueWithPromise @ Promise.ts:231
FetchConnection @ Recognizer.ts:159
(anonymous) @ Recognizer.ts:108
(anonymous) @ Promise.ts:234
ExecuteSuccessCallback @ Promise.ts:435
Resolve @ Promise.ts:390
Resolve @ Promise.ts:348
(anonymous) @ Promise.ts:209
ExecuteSuccessCallback @ Promise.ts:435
Resolve @ Promise.ts:390
Resolve @ Promise.ts:348
(anonymous) @ Promise.ts:209
ExecuteSuccessCallback @ Promise.ts:435
Resolve @ Promise.ts:390
Resolve @ Promise.ts:348
(anonymous) @ MicAudioSource.ts:94
ConsoleLoggingListener.ts:29 2020-08-10T13:55:11.599Z | ConnectionEstablishErrorEvent | metadata: {} | connectionId: 2607EB6D18B74798BD56FAA15AE367A0 | statusCode: 1006 | reason: 
OnEvent @ ConsoleLoggingListener.ts:29
OnEvent @ EventSource.ts:36
OnEvent @ WebsocketMessageAdapter.ts:246
o.connectionState.r.ConnectionState.Disconnected.o.connectionEstablishDeferral.o.websocketClient.onclose @ WebsocketMessageAdapter.ts:107
ConsoleLoggingListener.ts:29 2020-08-10T13:55:11.601Z | RecognitionEndedEvent | metadata: {} | requestId: B12CB181E44F41F7993F367E61E0D27B | audioSourceId: 224E12AD056C43689EE493D5BC5AC6CE | audioNodeId: 14A801E9EE724A4980CA894E0E6874CD | connectionId: 2607EB6D18B74798BD56FAA15AE367A0 | authFetchEventId: 5D761F6E47B04D0DB3CA468CFF2C74A3 | status: 7 | error:  | serviceTag: <NULL>
OnEvent @ ConsoleLoggingListener.ts:29
OnEvent @ EventSource.ts:36
OnEvent @ Recognizer.ts:485
OnComplete @ Recognizer.ts:470
OnConnectionEstablishCompleted @ Recognizer.ts:406
(anonymous) @ Recognizer.ts:177
(anonymous) @ Promise.ts:279
ExecuteSuccessCallback @ Promise.ts:435
Resolve @ Promise.ts:390
Resolve @ Promise.ts:348
o.connectionState.r.ConnectionState.Disconnected.o.connectionEstablishDeferral.o.websocketClient.onclose @ WebsocketMessageAdapter.ts:108


I have tried passing my speech API key and LUIS API key as well. Please try to look into this.
