### ISSUE TITLE
feature to set a custom HttpClient or HttpClientHandler

### ISSUE THREAD

**Issue by gsgou** [Azure-Samples/cognitive-services-speech-sdk#1220]
**Is your feature request related to a problem?
Intercepting the http traffic of mobile apps could reveal application secrets.
Additional security is possible with a custom HttpClient to ignore proxies for example.

**Describe the solution you'd like**
Set a custom default HttpClient or HttpClientHandler.

**Comment by amitkumarshukla** [comment]
@gsgou  Your feature request is not very clear to us. Could you please explain in detail what exactly you want to be added inside Microsoft Speech SDK.

**Comment by gsgou** [comment]
@amitkumarshukla In Microsoft.CognitiveServices.Speech and in Azure.AI.TextAnalytics packages i would like to use an overload of SpeechRecognizer and TextAnalyticsClient that takes as parameters an HttpClient or HttpClientHandler as well beside a key and url. Is this possible in a preview package or as feature request in the pipeline already?

**Comment by amitkumarshukla** [comment]
@gsgou Microsoft.CognitiveServices.Speech does not talk to the speech service using REST API. It uses websocket to stream audio to the service and get the transcription back to the client. 

What will be the purpose of providing HttpClient or HttpClientHandler as input to the SpeechRecognizer. We are still not clear. 

We do have proxysetup. Could that help ?

**Comment by gsgou** [comment]
@amitkumarshukla thank you for your Feedback. Thanks for the hint. A proxysetup would be indeed helpful to ensure that the client isn't respecting the mobile's proxy setting.

In case you can point me to the source of Microsoft.CognitiveServices.Speech and Azure.AI.TextAnalytics would be a time savor else i ll do the searching with the next opportunity. Thanks again for the quick reponse :)

**Comment by amitkumarshukla** [comment]
For Microsoft speech SDK please follow https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechconfig.setproxy?view=azure-dotnet

The same API is there for other languages also.

We do not own the TextAnalytics, but https://docs.microsoft.com/en-us/javascript/api/@azure/ai-text-analytics/textanalyticsclientoptions?view=azure-node-latest#proxyOptions might help you. 

Thanks

**Comment by amitkumarshukla** [comment]
I am closing this issue. Please feel free to open a new one if you need more anything else. Thank you
