### ISSUE TITLE
zh-Hans should be modified to zh-CN in quickstart javascript sample

### ISSUE THREAD

**Issue by windspeedjeep29** [Azure-Samples/cognitive-services-speech-sdk#1221]
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/javascript/browser/translate-speech-to-text-multiple-languages/index.html is using zh-Hans as Chinese-simplified, this will result in connection failure. The correct one is zh-CN.

**Comment by amitkumarshukla** [comment]
@glharper Could you please look at this sample.

**Comment by amitkumarshukla** [comment]
Thanks @windspeedjeep29 for notifying the issue. 

Thanks a lot @glharper for fixing the issue. I am closing this.
