### ISSUE TITLE
Speech SDK and Directline Speech with Bot Framework and Unity

### ISSUE THREAD

**Issue by davidjrh** [Azure-Samples/cognitive-services-speech-sdk#1224]
Hello folks, 

We’re trying to implement a virtual assistant using the Directline Speech channel, and we need to join different clients using the same conversation (currently using Unity clients). We’ve tried different approaches by setting the following properties with no success:
```
            dialogServiceConfig.SetProperty(PropertyId.Conversation_From_Id, "group1");
            dialogServiceConfig.SetProperty(PropertyId.Conversation_ParticipantId, "<Unique ID>");
            dialogServiceConfig.SetProperty(PropertyId.Conversation_Conversation_Id, "<A conversation ID>");
            dialogServiceConfig.SetProperty(PropertyId.Conversation_Connection_Id, "<Directline Bearer Token>"); // We don’t know the format of this property, is just passing a token?
```

On the properties documentation available at [PropertyId Enum (Microsoft.CognitiveServices.Speech) - Azure for .NET Developers | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.propertyid?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.CognitiveServices.Speech.PropertyId.Conversation_Conversation_Id);k(TargetFrameworkMoniker-.NETFramework,Version%253Dv4.7.1);k(DevLang-csharp)%26rd%3Dtrue&view=azure-dotnet), I can find the following, but I can’t find any sample or any other reference in the cloud. 

Conversation_Connection_Id	10009	Additional identifying information, such as a Direct Line token, used to authenticate with the backend service. Added in 1.16.0

Any of you has information on this?

**Comment by amitkumarshukla** [comment]
@davidjrh Thanks a lot for question. We will get back to you very soon.

**Comment by pankopon** [comment]
@trrwilson Please check or reassign.

**Comment by jhakulin** [comment]
@davidjrh Thanks for the report. I checked with the team and using the same conversation id between different clients should work and if that does not work for you we would like to get more traces of the failure. Related to PropertyId.Conversation_Connection_Id, you do not need to set that at all and will be deprecated in future.
 
Could you please provide a trace for unsuccessful operation as instructed here ?
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

**Comment by jhakulin** [comment]
@davidjrh We have not been able to reproduce this issue, thus closing the issue. In case you have more information on how to reproduce the issue and you have sample code to share, we can reopen this.
