### ISSUE TITLE
add retry for connection failures that will make speech applications more robust

### ISSUE THREAD

**Issue by gsgou** [Azure-Samples/cognitive-services-speech-sdk#1227]
**Is your feature request related to a problem? Please describe.**
Lately i am receiving from the SDK sporadically but more often following:
ErrorCode: ConnectionFailure
ErrorDetails: Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 101.

**Describe the solution you'd like**
I would like a retry policy from the SDK so i won't implement it on top.

**Comment by Abdull** [comment]
I have noticed this as well. I'd say it's great if the SDK would take care of these errors and abstract them away from us API users.

**Comment by rhurey** [comment]
Right now the cadence is every 2 months(ish) so the first half of October is the best resolution estimate I have.

**Comment by gsgou** [comment]
@rhurey  tks a lot for the estimation. Appreciate it!
Can some of the team have a look as well on this one?
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1232

**Comment by pankopon** [comment]
Internal work item ref. 3705147. This will be included in the Speech SDK 1.19.0 release which is expected by mid-November.

**Comment by gsgou** [comment]
Thanks for the update @pankopon, allows us prioritize features accordingly.

**Comment by gsgou** [comment]
@pankopon v1.19.0 is out with "Automatically reconnect when a connection attempt fails."
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/releasenotes#bug-fixes

Is there an API available like the number of retries etc.. or comes out of the box as implemented?

**Comment by jhakulin** [comment]
Closing as fix is included in the 1.19.0.

@gsgou We do not currently have public API for configuring the retry mechanism, we will consider adding one in the future. Let us know what kind of information you would like to see and if you get any problems with the latest release.
