### ISSUE TITLE
SpeechRecognizer raise memory leak

### ISSUE THREAD

**Issue by sehungen** [Azure-Samples/cognitive-services-speech-sdk#1228]
**Describe the bug**
Opened audio file is never released.

**To Reproduce**
1. Whenever I create instance of SpeechRecognizer, it opens audio file but never close.
``` speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_input) ```
2. More it is created, more memory is run out. 

**Expected behavior**
Add close method or close audio file when recognizer instance is closed.

**Version of the Cognitive Services Speech SDK**
azure-cognitiveservices-speech==1.17.0

**Platform, Operating System, and Programming Language**
 - OS: ubuntu 20.04
 - Hardware - x86
 - Programming language: Python

**Comment by BrianMouncer** [comment]
I should have kept this open, for tracking.
If you have more feedback, let us know.
If not, you can use this to track when we add Close() or __Exit__ in a future release.

Thanks again for reporting this issue.

**Comment by pankopon** [comment]
Internal work item ref. 3753799.

**Comment by kamrapooja** [comment]
i am not able to use close function in python code. could u please code snippet for the same?

**Comment by glecaros** [comment]
This has already been simplified internally, will keep this open until the next release makes it public.

**Comment by glecaros** [comment]
closing this as the update to the python bindings is live in the latest release
