### ISSUE TITLE
Not able to get the eastus region for python client from swagger v2

### ISSUE THREAD

**Issue by georgearun** [Azure-Samples/cognitive-services-speech-sdk#1233]
I am using Azure Batch transcription services for Speech to Text. Previously was using Rest API v2 for Batch transcription. Currently, they have migrated to v3.

I am using -> "https://editor.swagger.io/" to generate client from File -> import url -> "https://eastus.cris.ai/docs/v2.0/swagger" but not able to generate client client.

Has anyone worked on this or migrated their code to v3

**Comment by chlandsi** [comment]
Hi, the swagger definition for the v3 API is at https://eastus.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/export?DocumentFormat=Swagger&ApiName=Speech%20to%20Text%20API%20v3.0. A sample for how to get the Python client is [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python).

**Comment by georgearun** [comment]
> Hi, the swagger definition for the v3 API is at https://eastus.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/export?DocumentFormat=Swagger&ApiName=Speech%20to%20Text%20API%20v3.0. A sample for how to get the Python client is [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python).

Can you provide a link to the sample code with Python where they have used SAS URI.
Thanks

**Comment by chlandsi** [comment]
You can pass a SAS Uri in the sample [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/b251c80e3bed61b247519601a3db8cb147e97278/samples/batch/python/python-client/main.py#L155). If you are looking to generate a SAS Uri from Python, please refer to the [docs of the Azure Storage SDK](https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob?view=azure-python#generate-blob-sas-account-name--container-name--blob-name--snapshot-none--account-key-none--user-delegation-key-none--permission-none--expiry-none--start-none--policy-id-none--ip-none----kwargs-).
