### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'Microsoft.CognitiveServices.Speech.core.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)  

### ISSUE THREAD

**Issue by samkuls** [Azure-Samples/cognitive-services-speech-sdk#1234]
**Describe the bug**
System.DllNotFoundException: Unable to load DLL 'Microsoft.CognitiveServices.Speech.core.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
 

**To Reproduce**
1. Created STT from wave file 

**Expected behavior**
It should convert the uploaded wave file to text

**Version of the Cognitive Services Speech SDK**
Nuget package version: 1.18.0

**Platform, Operating System, and Programming Language**
Build on VS 2019 

**Additional context**
 The same is working when i am deploying dlls on my local IIS

**Comment by brandom-msft** [comment]
@samkuls 
The error you're getting indicates an issue resolving dependencies, can you share more about the project setup?

In the references list of your project, what is the status of the SDK? E.g. does it have a ⚠warning symbol on it? Does the path to the package location seem correct?

**Comment by jhakulin** [comment]
@samkuls Could you confirm you have installed Microsoft Visual C++ Redistributable for Visual Studio 2019 ?

See prerequisites here:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/setup-platform?tabs=dotnet%2Cwindows%2Cjre%2Cbrowser&pivots=programming-language-csharp

**Comment by samkuls** [comment]
@jhakulin Thank you
