### ISSUE TITLE
How to get session id for  synthesizer

### ISSUE THREAD

**Issue by gauravG2021** [Azure-Samples/cognitive-services-speech-sdk#1238]
Hi,
we can get sessiond for stt using below code

// register the callbacks
 recognizer->Recognizing.Connect([recog_channel](const SpeechRecognitionEventArgs& e) noexcept
                                {
                                });
resource->recognizer->SessionStarted.Connect([recog_channel](const SessionEventArgs& e) noexcept
                                {
                                cout << " session id is :: "<<e.SessionId;
                                });
 resource->recognizer->SpeechStartDetected.Connect( [recog_channel](const RecognitionEventArgs& e)
                                {
                                }
                                });
 recognizer->Canceled.Connect([recog_channel](const SpeechRecognitionCanceledEventArgs& e) 
{
}
recognizer->StartContinuousRecognitionAsync();

====================================================================================
Similarly for synthesizer
// register the callbacks
synthesizer->SynthesisStarted.Connect([&channel](const SpeechSynthesisEventArgs& e) noexcept {
                                        });
synthesizer->Synthesizing.Connect([](const SpeechSynthesisEventArgs& e) noexcept {
                                        });
synthesizer->SynthesisCanceled.Connect([&channel](const SpeechSynthesisEventArgs& e) {
}
synthesizer->StartSpeakingText("some text")

Here i am not able to find the session id for synthesizer session(similiarly to recognizer session)

### Why i need the session id?
My concern is i am using the sdk on a server with 50+ concurrent calls planning to take them to 200+, 
so i will  need an id to uniquley identify the recognizer/synthesizer with Microsoft, in case i need to raise  a ticket,(
if need help from MS to debug an  issue)

Thanks
gaurav

**Comment by yulin-li** [comment]
@gauravG2021, thx for reaching out. You can use [result id](https://docs.microsoft.com/en-us/cpp/cognitive-services/speech/speechsynthesisresult#resultid) of `SpeechSynthesisResult` for this purpose.
