### ISSUE TITLE
Pronunciation Assesment

### ISSUE THREAD

**Issue by deeplearning987** [Azure-Samples/cognitive-services-speech-sdk#1241]
Hello @glharper @amitkumarshukla 

**Describe the bug**

In Pronunciation Assessment. If any single letter or key word in the displayed  text that doesn't match with the spoken output then it is not displaying the result. 

**To Reproduce**
1. It should try to give word mismatch issue.

**Expected behavior**

**Version of the Cognitive Services Speech SDK**
1.18.0

**Platform, Operating System, and Programming Language**
 - OS: [Windows]
 - Hardware - x64, x86, ARM.
 - Programming language: Python
 -

*
![Screenshot (14)](https://user-images.githubusercontent.com/89828183/131888927-950742b6-4f4a-45b6-ab1b-ae6ebd6adad6.png)
I'm trying to build a webapp using Azure Speech SDK and Stream lit.
While displaying the assessment score like pronunciation score or completeness score.
I don't want to display Delta Generator but it is displayed by default how to remove it?

I'm using stream lit for frontend webapp.
st.info(st.info('Pronunciation score: {}'.format(pronunciation_result.pronunciation_score)))

**Comment by yulin-li** [comment]
Hi @deeplearning987 , thx for reaching out. Could you paste the repro codes and sample audio so we can investigate?

**Comment by pankopon** [comment]
Closed since no customer update in more than a month. Please open a new issue if support is still needed.
