### ISSUE TITLE
Deployment US GOV Virginia 

### ISSUE THREAD

**Issue by Eceder** [Azure-Samples/cognitive-services-speech-sdk#1242]
**Describe the bug**
Deployed solution following Getting started guide. Per the guide all of the pieces are there no errors during deployment.
Being deployed to USGOV Virginia 

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/ingestion/ingestion-client/Setup/guide.md

**To Reproduce**
Upload files to audio-input but don't get any results back. Files just stay in audio-input container 

Appinsight I am seeing the following exception. We deployed this in test subscription that wasnt in GOV space and everything worked as expected. Within USGOV Virginia cannot get it to run properly   

Event time | 9/1/2021, 8:24:10.640 PM (Local time) |  
-- | -- | --
Message | The listener for function 'StartTranscriptionByTimer' was unable to start. Retry failed after 6 tries. (No such host is known.) (No such host is known.) (No such host is known.) (No such host is known…[show more] |  
Exception type | System.Net.Sockets.SocketException |  
Failed method | Azure.Core.Pipeline.HttpClientTransport+<ProcessAsync>d__8.MoveNext |  
Problem Id | System.Net.Sockets.SocketException at Azure.Core.Pipeline.HttpClientTransport+<ProcessAsync>d__8.MoveNext |  
Assembly | Azure.Core, Version=1.9.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8 |  
Severity level | Error |  
Telemetry type | exception |  
Device type | PC |  
Client IP address | 0.0.0.0 |  
Role name | starttranscriptionfunction-20210831t193152z |  
Role instance | d0126224e64fa271e1cd08a43a27e488b4b1a0efa0476f4d823c3ba26c6cf6b8 |  
SDK version | azurefunctions: 3.1.3.0 |  
Sample rate | 1

**Comment by HenryvanderVegte** [comment]
Hi @Eceder,

deploying the Ingestion Client to Azure Gov should be possible, but is not supported by the ARM template right now.
There are 2 more things you need to do to make it work. You need to go to your StartTranscriptionFunction and change the following application settings (under Settings->Configuration->Application Settings):

1.) Change the variable "AzureSpeechServicesRegion" to "usgovvirginia"
2.) Add a new variable "IsAzureGovDeployment" and set the value to "true"

Please let me know if that worked for you.

Best,
Henry

**Comment by Eceder** [comment]
I made changes but still getting same failures 
Should I also be making these changes to the FetchTranscriptionFunction?

**Comment by HenryvanderVegte** [comment]
Hi,

the reason why you were seeing this issue was that the storage endpoint was formatted incorrectly for Azure Gov (core.windows.net vs. core.usgovcloudapi.net). 
I have updated the ARM template now to include Azure Gov regions (https://github.com/Azure-Samples/cognitive-services-speech-sdk/pull/1248) , please redeploy the Ingestion Client with the updated template and let me know if it worked!

Best,
Henry

**Comment by Eceder** [comment]
Redeployed and is working as expected. Thank you for your time and effort’s

**Comment by HenryvanderVegte** [comment]
Perfect, thanks!
