### ISSUE TITLE
Installing Python install azure-cognitiveservices-speech on macOS M1

### ISSUE THREAD

**Issue by fantinuoli** [Azure-Samples/cognitive-services-speech-sdk#1244]
**Describe the bug**
Impossible to install the python azure-cognitiveservices-speech on a macOS M1 machine

**To Reproduce**
pip install install azure-cognitiveservices-speech

**Expected behavior**
Module gets installed

**Version of the Cognitive Services Speech SDK**
1.18.0

**Platform, Operating System, and Programming Language**
 - OS: macOS Big Sur
 - Hardware ARM (M1)
 - Programming language:  Python

**Additional context**
@XYs-MacBook-Pro ~ % pip install install azure-cognitiveservices-speech
Collecting install
  Downloading install-1.3.4-py3-none-any.whl (3.1 kB)
ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech (from versions: none)
ERROR: No matching distribution found for azure-cognitiveservices-speech

OR

@XYs-MacBook-Pro backend % pipenv install azure-cognitiveservices-speech
Installing azure-cognitiveservices-speech...
Error:  An error occurred while installing azure-cognitiveservices-speech!
Error text: 
ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech (from versions: none)
ERROR: No matching distribution found for azure-cognitiveservices-speech

✘ Installation Failed

**Comment by jhakulin** [comment]
@fantinuoli Thanks for reporting the issue, we are working on Mac M1 support and targeting to release the support (including Python wheels) on 1.19.0 Speech SDK release.

**Comment by jhakulin** [comment]
Speech SDK 1.19.0 has been released with Mac M1 ARM based silicon support, let us know if there is any problems.

**Comment by samvanlier** [comment]
Hello,
I'm trying to install azure-cognitiveservices-speech in a ARM64 docker but the `pip install` is still not working.
[Pypi](https://pypi.org/project/azure-cognitiveservices-speech/) gives the right version according to the release notes.
But when running `pip install azure-cognitiveservices-speech==1.19.0` gives the same error as before
```
ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech==1.19.0 (from versions: none)
ERROR: No matching distribution found for azure-cognitiveservices-speech==1.19.0
```

**Comment by jhakulin** [comment]
@samvanlier Thanks for the report. I just checked the functionality on my M1 mac by using https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/python/from-microphone 
```
jarnohakulinen@Jarnos-MacBook-Pro from-microphone % python3 --version
Python 3.9.7

jarnohakulinen@Jarnos-MacBook-Pro from-microphone % python3 -m pip install --force-reinstall azure-cognitiveservices-speech
Collecting azure-cognitiveservices-speech
  Downloading azure_cognitiveservices_speech-1.19.0-cp39-cp39-macosx_11_0_arm64.whl (5.1 MB)
     |████████████████████████████████| 5.1 MB 731 kB/s
Installing collected packages: azure-cognitiveservices-speech
Successfully installed azure-cognitiveservices-speech-1.19.0

jarnohakulinen@Jarnos-MacBook-Pro from-microphone % python3 quickstart.py
Say something...
Recognized: What's the weather like?
```
Here pip install was able to find and install the package correctly on Mac M1 ARM64 device. 

No good ideas here, but I am wondering if `python3 -m pip install azure-cognitiveservices-speech` would make a difference on your environment ? 
What is the python3 version you are using ?
