### ISSUE TITLE
Add GovCloud regions to Sample SDK

### ISSUE THREAD

**Issue by noahsw** [Azure-Samples/cognitive-services-speech-sdk#1252]
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/e1ccf3156c94f0b1a668946fc7dd41a64af1230e/samples/js/browser/index.html#L30

Thanks!

**Comment by glharper** [comment]
@noahsw Please see the linked JS PR. Adding those regions to the sample won't, by itself, enable access via JS SDK. The linked PR, which should be in version 1.19 (due by mid-October), will help. I will add these regions to the sample to coincide with the 1.19 release.

**Comment by glharper** [comment]
@noahsw [JS Speech SDK version 1.19.0](https://github.com/microsoft/cognitive-services-speech-sdk-js/releases/tag/v1.19.0) has been released, with support for usgov regions. Thanks again for writing this issue up!

**Comment by noahsw** [comment]
Thx @glharper but I'm not seeing any changes to https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/e1ccf3156c94f0b1a668946fc7dd41a64af1230e/samples/js/browser/index.html#L30. I was hoping to see the GovCloud regions in the dropdown.

**Comment by glharper** [comment]
@noahsw I have a [PR](https://github.com/Azure-Samples/cognitive-services-speech-sdk/pull/1297) now for [this file](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/public/index.html). The structure of the sample has changed, so the file path you linked to will be deleted at some point.
