### ISSUE TITLE
The Confidence field is missing in WordLevelTimingResult class.

### ISSUE THREAD

**Issue by FrogView** [Azure-Samples/cognitive-services-speech-sdk#1253]
![image](https://user-images.githubusercontent.com/23505231/132830967-f1da740f-8edc-4cb9-8652-7e24f23ccf96.png)

I want to get the results of word level. When I call the C# SDK API directly, **the returned word results does not contains the Confidence field**.
![image](https://user-images.githubusercontent.com/23505231/132831480-f2146bb6-0c44-4a21-b3f0-09217fed28ba.png)

**But the JSON results from the SpeechServiceResponse_JsonResult property contains the Confidence field.** 

var jsonResult = e.Result.Properties.GetProperty(PropertyId.SpeechServiceResponse_JsonResult);
![image](https://user-images.githubusercontent.com/23505231/132832015-73de9aaf-83c6-4158-af50-8f9e20030588.png)

So why is the Confidence field missing from the WordLevelTimingResult class? Can you help to add this field?

**Comment by dargilco** [comment]
Closing since there is no reply.
