### ISSUE TITLE
failed to connect host

### ISSUE THREAD

**Issue by sosilent** [Azure-Samples/cognitive-services-speech-sdk#1254]
**Describe the bug**
cognitive-services-speech-sdk/samples jdk demo failed to create tts mp3 file.

**To Reproduce**
1. clone cognitive-services-speech-sdk
2. .mvn package
3. run
4. input some words, and the output is:

Enter some text that you want to synthesize, or enter empty text to exit.
> i want the red apple.
CANCELED: Reason=Error
CANCELED: ErrorCode=ConnectionFailure
CANCELED: ErrorDetails=Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 2543. USP state: 2. Received audio size: 0 bytes.
CANCELED: Did you update the subscription info?
Enter some text that you want to synthesize, or enter empty text to exit.

**Version of the Cognitive Services Speech SDK**
1.18.0

**Platform, Operating System, and Programming Language**
 - OS: Linux
 - Hardware - x64
 - Programming language: Java

**Comment by glharper** [comment]
@sosilent Thanks for using SpeechSDK, and writing this issue up. Please make sure your certificates are correctly configured by working through [this guide.](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-openssl-linux?pivots=programming-language-java)

Let us know if you have issues after doing that.

**Comment by pankopon** [comment]
Closed since no customer update in a month. Please open a new issue if support is still needed.
