### ISSUE TITLE
Usage of DisconnectAll()

### ISSUE THREAD

**Issue by gauravG2021** [Azure-Samples/cognitive-services-speech-sdk#1259]
Hi,
We call below apis to unregister the call backs
                     synthesizer->SynthesisStarted.DisconnectAll();
                     synthesizer->Synthesizing.DisconnectAll();
                      synthesizer->SynthesisCanceled.DisconnectAll();
                      synthesizer->SynthesisCompleted.DisconnectAll();

However we have found that some times the call backs of SynthesisStarted and SynthesisCanceled still gets called even after calling DisconnectAll().

we call hlpr_stop_synthesis() to stop the synthesis. 
So is there anything which can cause such behaviour.
Below  is the code:-

struct MyResource{

        std::shared_ptr<SpeechSynthesizer> synthesizer;
        std::shared_ptr<AudioDataStream> audio_stream;
        std::string result_id;

        MyResource(){
                cout<< "#### Creating new Resource ####");
                synthesizer=nullptr;
                audio_stream=nullptr;

                result_id="";

                static auto subscriptionKey ="key "

                static auto region = "region"

                auto speechConfig = SpeechConfig::FromSubscription(subscriptionKey, region); 

                speechConfig->SetSpeechSynthesisOutputFormat(SpeechSynthesisOutputFormat::Raw8Khz16BitMonoPcm);

                speechConfig->SetSpeechSynthesisVoiceName("Microsoft Server Speech Text to Speech Voice (en-US, JessaNeural)")
                synthesizer = SpeechSynthesizer::FromConfig(speechConfig, nullptr);

        }

        ~MyResource();
};

static bool hlpr_start_synthesis(my_channel_t* channel, const char* src_text){
    if(channel->resource!=nullptr){
        std::shared_ptr<SpeechSynthesisResult> result;
        time_t finish;
        time_t start;
        time(&start);
        result = channel->resource->synthesizer->StartSpeakingText(src_text);
        time(&finish);
        cout << "Time DIff : "<< difftime(finish, start));
        channel->resource->audio_stream = AudioDataStream::FromResult(result);
    }
    return TRUE;

}

 bool create_synthesizer(my_channel_t* channel){

        try{
                if(channel->resource == nullptr){
                        channel->resource = new MyResource();

                        auto resource=channel->resource;

                        if(channel->resource->synthesizer==nullptr){
                                return FALSE;
                        }
                        resource->synthesizer->SynthesisStarted.Connect([&channel](const SpeechSynthesisEventArgs& e) noexcept {
                                        cout << "Result_id" << e.Result->ResultId.c_str());
                                        if(channel->resource!=nullptr){
                                         channel->resource->result_id=e.Result->ResultId;
                                         }
                                        });
                        resource->synthesizer->Synthesizing.Connect([](const SpeechSynthesisEventArgs& e) noexcept {
                                        cout << "audio data being received";
                                        });
                        resource->synthesizer->SynthesisCanceled.Connect(
                                        [&channel](const SpeechSynthesisEventArgs& e) {

                                           cout << "synthesis canceled" << e.Result->ResultId.c_str() );
                                        if(channel->resource!=nullptr){

                                        const auto cancellation =
                                        SpeechSynthesisCancellationDetails::FromResult(e.Result);
                                        if(CancellationReason::Error == cancellation->Reason)
                                        {
                                        cout<<  "ErrorDetails:" << e.Result->ResultId.c_str() ;

                                        }
                                        else if (CancellationReason::CancelledByUser == cancellation->Reason) {
                                            cout<<  "CANCELED CancelledByUser :" << e.Result->ResultId.c_str() ;
                                        }
                                        else if (CancellationReason::EndOfStream == cancellation->Reason){
                                        cout<<  "CANCELED EndOfStream :" << e.Result->ResultId.c_str() ;

                                        }
                                        }
                                        });
                        resource->synthesizer->SynthesisCompleted.Connect([&channel](const SpeechSynthesisEventArgs& e) {
                                            cout<<  "SynthesisCompleted :" << e.Result->ResultId.c_str() ;
                                        });
                        return TRUE;
                }

        }
        catch(Exception &e) {
                cout << "Exception catch: "<<  e.what());
        }
        catch(...) {
                cout << "hlpr_create_synthesizer() ";
        }
        return FALSE;

}

 void hlpr_stop_synthesis(my_channel_t *synth_channel){
        time_t finish;
        time_t start;
        auto resource=synth_channel->resource;
        try
        {
                if( resource!=nullptr && resource->synthesizer!=nullptr){
                        shared_ptr<SpeechSynthesizer> synthesizer = resource->synthesizer;

                        hlpr_close_audio_stream(synth_channel,callerfn);
                        string result_id = synth_channel->resource->result_id;
                        delete(synth_channel->resource);
                        synth_channel->resource = nullptr;
                        time(&start);
                        hlpr_stop_synthesizer(ynthesizer,result_id);
                        time(&finish);

                }
                else
                        cout <<  "synthesizer/resource is NULL ";
        }
        catch(Exception &e) {
                cout << " catch Exception: " <<  e.what();

        }
        catch(...) {
                cout << " Generic Catch";
        }

}
bool hlpr_deregister_azure_callbacks(my_channel_t *synth_channel, string caller_fn_name)
{
        if (synth_channel !=nullptr && synth_channel->resource !=nullptr)
        {
                try{
                        auto synthesizer = synth_channel->resource->synthesizer;
                        synth_channel->resource->synthesizer->SynthesisStarted.DisconnectAll();
                        synth_channel->resource->synthesizer->Synthesizing.DisconnectAll();
                        synth_channel->resource->synthesizer->SynthesisCanceled.DisconnectAll();
                        synth_channel->resource->synthesizer->SynthesisCompleted.DisconnectAll();
                        cout << "hlpr_deregister_azure_callbacks() completed Sucessfully resut";
                }

                catch(Exception &e) {
                        cout << hlpr_deregister_azure_callbacks() into catch Exception: << e.what());
                }
                catch(...) {
                        cout << "hlpr_deregister_azure_callbacks() Generic Catch" ;

                }
                return TRUE;
        }
        return FALSE;
}
 void hlpr_close_audio_stream(my_channel_t *synth_channel){
        if( synth_channel->resource!=nullptr && synth_channel->resource->audio_stream!=nullptr){
                hlpr_deregister_azure_callbacks(synth_channel,caller_fn_name);
                synth_channel->resource->audio_stream.reset();
                synth_channel->resource->audio_stream=nullptr;
                cout << "audio_stream closed";
        }
}

 void hlpr_stop_synthesizer(shared_ptr<SpeechSynthesizer> synthesizer,string result_id){
    time_t finish;
    time_t start;
    time(&start);
    synthesizer->StopSpeakingAsync().wait();
    time(&finish);
    cout << "Time Difference for StopSpeakingAsync() in seconds := " << difftime(finish, start);

    synthesizer.reset();

}

**Comment by rhurey** [comment]
Thanks for getting in touch with us.

I took the code above and filled in a couple of blanks and ran it. I got back the results I expected, so wanted to check back on where I'd filled in blanks and see if I was on track to what you had.

Namely, I added main and it's contents, defined a small my_channel_t, and remove the lambda capture by reference in create_synthsizer

Here's what I have in all:
```
#include <iostream>
#include <speechapi_cxx.h>
#include <chrono>
#include <thread>

using namespace Microsoft::CognitiveServices::Speech;

using namespace std;

struct MyResource {

    std::shared_ptr<SpeechSynthesizer> synthesizer;
    std::shared_ptr<AudioDataStream> audio_stream;
    std::string result_id;

    MyResource() {
        cout << "#### Creating new Resource ####" << endl;
        synthesizer = NULL;
        audio_stream = nullptr;

        result_id = "";

        static auto subscriptionKey = KEY;

        static auto region = REGION;

        auto speechConfig = SpeechConfig::FromSubscription(subscriptionKey, region);


        speechConfig->SetSpeechSynthesisOutputFormat(SpeechSynthesisOutputFormat::Raw8Khz16BitMonoPcm);

        speechConfig->SetSpeechSynthesisVoiceName("Microsoft Server Speech Text to Speech Voice (en-US, JessaNeural)");
        synthesizer = SpeechSynthesizer::FromConfig(speechConfig, nullptr);

    }

    ~MyResource() 
    {
        cout << "Destroyed" << endl;
    }
};

struct my_channel_t
{
    MyResource* resource = nullptr;
};

static bool hlpr_start_synthesis(my_channel_t* channel, const char* src_text) {
    if (channel->resource != nullptr) {
        std::shared_ptr<SpeechSynthesisResult> result;
        time_t finish;
        time_t start;
        time(&start);
        result = channel->resource->synthesizer->StartSpeakingText(src_text);
        time(&finish);
        cout << "Time DIff : " << difftime(finish, start) << endl;
        channel->resource->audio_stream = AudioDataStream::FromResult(result);
    }
    return true;

}

bool create_synthesizer(my_channel_t* channel) {

    try {
        if (channel->resource == nullptr) {
            channel->resource = new MyResource();

            auto resource = channel->resource;

            if (channel->resource->synthesizer == nullptr) {
                return false;
            }
            resource->synthesizer->SynthesisStarted.Connect([channel](const SpeechSynthesisEventArgs& e) noexcept {
                cout << "Result_id" << e.Result->ResultId.c_str() << endl;
                if (channel->resource != nullptr) {
                    cout << "Enpty " << channel->resource->result_id.empty() << endl;
                    channel->resource->result_id = e.Result->ResultId;
                }
                });
            resource->synthesizer->Synthesizing.Connect([](const SpeechSynthesisEventArgs& e) noexcept {
                cout << "audio data being received" << endl;
                });
            resource->synthesizer->SynthesisCanceled.Connect(
                [channel](const SpeechSynthesisEventArgs& e) {

                    cout << "synthesis canceled" << e.Result->ResultId.c_str() << endl;
                    if (channel->resource != nullptr) {

                        const auto cancellation =
                            SpeechSynthesisCancellationDetails::FromResult(e.Result);
                        if (CancellationReason::Error == cancellation->Reason)
                        {
                            cout << "ErrorDetails:" << e.Result->ResultId.c_str() << endl;

                        }
                        else if (CancellationReason::CancelledByUser == cancellation->Reason) {
                            cout << "CANCELED CancelledByUser :" << e.Result->ResultId.c_str() << endl;
                        }
                        else if (CancellationReason::EndOfStream == cancellation->Reason) {
                            cout << "CANCELED EndOfStream :" << e.Result->ResultId.c_str() << endl;

                        }
                    }
                });
            resource->synthesizer->SynthesisCompleted.Connect([channel](const SpeechSynthesisEventArgs& e) {
                cout << "SynthesisCompleted :" << e.Result->ResultId.c_str() << endl;
                });
            return true;
        }


    }
    catch (exception& e) {
        cout << "Exception catch: " << e.what() << endl;
    }
    catch (...) {
        cout << "hlpr_create_synthesizer() " << endl;
    }
    return false;

}

void hlpr_close_audio_stream(my_channel_t* synth_channel);

void hlpr_stop_synthesizer(shared_ptr<SpeechSynthesizer> synthesizer, string result_id) {
    time_t finish;
    time_t start;
    time(&start);
    synthesizer->StopSpeakingAsync().wait();
    time(&finish);
    cout << "Time Difference for StopSpeakingAsync() in seconds := " << difftime(finish, start) << endl;

    synthesizer.reset();
}

void hlpr_stop_synthesis(my_channel_t* synth_channel) {
    time_t finish;
    time_t start;
    auto resource = synth_channel->resource;
    try
    {
        if (resource != nullptr && resource->synthesizer != nullptr) {
            shared_ptr<SpeechSynthesizer> synthesizer = resource->synthesizer;

            hlpr_close_audio_stream(synth_channel);
            string result_id = synth_channel->resource->result_id;
            delete(synth_channel->resource);
            synth_channel->resource = nullptr;
            time(&start);
            hlpr_stop_synthesizer(synthesizer, result_id);
            time(&finish);

        }
        else
            cout << "synthesizer/resource is NULL " << endl;
    }
    catch (exception& e) {
        cout << " catch Exception: " << e.what() << endl;

    }
    catch (...) {
        cout << " Generic Catch" << endl;
    }

}
bool hlpr_deregister_azure_callbacks(my_channel_t* synth_channel)
{
    if (synth_channel != nullptr && synth_channel->resource != nullptr)
    {
        try {
            auto synthesizer = synth_channel->resource->synthesizer;
            synth_channel->resource->synthesizer->SynthesisStarted.DisconnectAll();
            synth_channel->resource->synthesizer->Synthesizing.DisconnectAll();
            synth_channel->resource->synthesizer->SynthesisCanceled.DisconnectAll();
            synth_channel->resource->synthesizer->SynthesisCompleted.DisconnectAll();
            cout << "hlpr_deregister_azure_callbacks() completed Sucessfully resut" << endl;
        }

        catch (exception& e) {
            cout << e.what();
        }
        catch (...) {
            cout << "hlpr_deregister_azure_callbacks() Generic Catch" << endl;

        }
        return true;
    }
    return false;
}
void hlpr_close_audio_stream(my_channel_t* synth_channel) {
    if (synth_channel->resource != nullptr && synth_channel->resource->audio_stream != nullptr) {
        hlpr_deregister_azure_callbacks(synth_channel);
        synth_channel->resource->audio_stream.reset();
        synth_channel->resource->audio_stream = nullptr;
        cout << "audio_stream closed" << endl;
    }
}


int main()
{
    my_channel_t channel;

    create_synthesizer(&channel);
    hlpr_start_synthesis(&channel, "Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. Some text to speak. ");

    std::this_thread::sleep_for(std::chrono::milliseconds(1000));

    hlpr_stop_synthesis(&channel);
}
```

**Comment by pankopon** [comment]
Closed as answered.
