### ISSUE TITLE
API + Model release notes / change documentation

### ISSUE THREAD

**Issue by hemnaathR** [Azure-Samples/cognitive-services-speech-sdk#1262]
Hello,
Is there a place where the changes to the cognitive services api and new models are documented?

Our application broke recently because the POSTing of transcription using the batch client started failing with 

`BatchClient.FailedHttpClientRequestException: Given timeToLive value is too long.`

so then we had to go and update the timeToLive value.

Then we noticed that the transcription results started to contain a lot more recognized phrases. This im guessing is due to a model change in cognitive services?

Is there a place where the updates are documented? Would be nice to know what the changes are so we dont get any surprises in our own apps when using the cognitive services speech api.

Azure Speech service location: UK South

**Comment by zhouwangzw** [comment]
What do you mean by "a lot more recognized phrases"? Are you referring to the multiple NBest results for the same recognized phrase. Do you see any change in accuracy?

**Comment by hemnaathR** [comment]
no just a lot more "recognizedPhrases": [...] in the json result. For example, this used to be one recognizedPhrase: 

"I'm going to avoid diving straight into questions"

now its like 

"I'm." 
"Going to avoid diving." 
"Straight into questions."

we are using DictatedAndAutomatic punctuation mode.

**Comment by zhouwangzw** [comment]
Would it be possible to share the audio and the result you get?

**Comment by hemnaathR** [comment]
yeah ill try to get permission. is there a way i can send it to you directly and not attach it here?

**Comment by hemnaathR** [comment]
there are a few examples here regarding over segmentation of phrases

[sky_boris.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/7226175/sky_boris.zip)

Well.
Looking at what we can.
Do to sort that out.
...
A first of all, we've got the.
Fastest growing economy.
In the GC.
...
I think.
The.
British.

**Comment by hemnaathR** [comment]
bump

**Comment by pankopon** [comment]
@zhouwangzw Are there any open items remaining? Please update.

**Comment by zhouwangzw** [comment]
@pankopon I do not think there is open items for now. I am closing the issue. If you have new issues or questions, please re-open it or create a new one. Thanks!
