### ISSUE TITLE
Error in speech recognition verification in js on a web browser

### ISSUE THREAD

**Issue by ersaurabh101** [Azure-Samples/cognitive-services-speech-sdk#1264]
**Describe the bug**
I downloaded all the files and placed in xampp. I am able to run dependent-verification.html. I added 
>Subscription
>Region
>Selected the Enrollment File "myVoiceIsMyPassportVerifyMe01.wav" and clicked  **Create Voice Profile** button.

I got the message:
Profile created ProfileId: 6b76d604-9f85-4273-bf72-483546ef34ed
(Enrollment result) Reason: EnrollingVoiceProfile

But when I upload the same wav file on **Test Identification File** and press verify, I get this error
(Verification result) Reason: Canceled
(Verification canceled) Error Details: undefined
(Verification canceled) Error Code: undefined

Please guide what needs to be done to verify the profile.

**Comment by glharper** [comment]
@ersaurabh101 (I updated your comment to remove the image with credentials displayed). Just checked using the sample and the credentials, I was able to verify the file correctly (see image below). That 400 return means a bad request, and since the underlying operations are REST, if you could try again and show me the network inspector in Chrome for those 400 requests, that could help.

![2021_09_27](https://user-images.githubusercontent.com/64209257/134939879-770dc2b7-e005-4d4a-bfe7-25d2e5b1043b.png)

**Comment by ersaurabh101** [comment]
This is the network screenshot for you. I also have a question why verify button is disabled. I mean if I have created a profile, next time I only need to verify. Why everytime it asks to create and then verify. If you need anydesk of my system, you can get in touch at ersaurabh101@gmail.com

![image](https://user-images.githubusercontent.com/50316624/134943330-e2c638b5-6649-4c46-a6c1-2dc83863c54b.png)

**Comment by glharper** [comment]
@ersaurabh101 I see the issue. You received the result "Enrolli**ng** Voice Profile", and verification won't work until you receive a "Enroll**ed** Voice Profile" result. Try selecting all the "myVoiceIsMyPassport..." files for the enrollment files, then click "Create Voice Profile". The sample will submit each file for enrollment, and after the third or fourth enrollment, you should see "EnrolledVoiceProfile". After that, the Verify Speaker should work correctly.

**Comment by ersaurabh101** [comment]
Yes it worked as you guided, 
![image](https://user-images.githubusercontent.com/50316624/134948059-c306a85a-55d1-4c11-b9f6-b286bae9af82.png)

but now if i refresh the page and submit another audio to verify, why verify button is disabled ?
![image](https://user-images.githubusercontent.com/50316624/134948225-73190d97-e329-4e50-89a0-6317094de89a.png)

**Comment by glharper** [comment]
@ersaurabh101 If you refresh the page, everything in the page will be reset. The SDK cannot hold variable values between page refreshes. To verify another file, click "Choose File" for Test Identification File, select a different file, and click Verify Speaker, without refreshing the page.

**Comment by ersaurabh101** [comment]
Makes sense, 1 last thing. 
Image there is a audio button on this html page, user clicks it and speaks, then this audio directly goes to verification, how can this be achieved ? Audio button on html page is simple but how do we pass it for verification ? If you can help in someway, it will be a great headstart.

**Comment by glharper** [comment]
@ersaurabh101 Unfortunately, direct microphone input for speaker verification in JS is not supported at the moment.

**Comment by ersaurabh101** [comment]
Do i get this option in NodeJs ?

**Comment by glharper** [comment]
@ersaurabh101 Microphone access from Speech SDK in Node is not possible for any scenario, speaker verification included.
