### ISSUE TITLE
Error code: 1007. Error details: Starting September 1st, 2021 standard voices will no longer be supported for new users. Please use n USP state

### ISSUE THREAD

**Issue by david-95** [Azure-Samples/cognitive-services-speech-sdk#1268]
I use ssml to generate voice file, to change voice speed.  but I get below error.
I am using nerual voice : 
     lang="en-US",voice_name="en-US-AriaNeural"
what can I do if I want to use ssml to change voice speed ?

Speech synthesis canceled: CancellationReason.Error
Error details: Connection was closed by the remote host. Error code: 1007. Error details: Starting September 1st, 2021 standard voices will no longer be supported for new users. Please use n USP state: 3. Received audio size: 0 bytes.

**Comment by ralph-msft** [comment]
Thanks for trying the Cognitive Speech SDK!

Could you please include the SSML that you are running into issues with?

As a side note, please note that the voice name in the SSML will override the one you set on the SpeechConfig so please double check that you are using a supported voice:
https://docs.microsoft.com/azure/cognitive-services/speech-service/language-support#text-to-speech

**Comment by david-95** [comment]
Thanks for your response!
I really made a stupid thing, my ssml have an issue. I tried to replace lang with customized string, but the replacement didn't take effect, so the lang in ssml didn't have value. after I fixed it, the 1007 issue disappeared.
