### ISSUE TITLE
Batch ARM Template and Private Endpoints

### ISSUE THREAD

**Issue by adthorn** [Azure-Samples/cognitive-services-speech-sdk#1269]
We're having issues with Private Endpoints for the services. Is there a way to use a custom DNS with the speech service? We created everything with Private Endpoints and the Azure DNS is all correct.  It cannot connect to the speech service endpoint. I created a new public speech service , updated the key in the Key vault and then tried it again and no dice. It won't process the files with the standard SDK but I get no errors.

**Comment by ralph-msft** [comment]
Thanks for the trying the Microsoft Cognitive Services Speech SDK!

To better assist you:
- What version of the Microsoft Cognitive Services Speech SDK are you using?
- What environment are you using the SDK in?
  - Which operating system and version?
  - What programming language?
  - Are you using the SDK from a container?
- Which Cognitive Speech Service are you using? Speech to text, text to speech, etc…?
- Could you please enable the SDK logging and attach the logs to this issue? You can find instructions on how to do this here: https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging

On a side note, we do have some documentation about setting up private endpoints that may be helpful to you as well: https://docs.microsoft.com/azure/cognitive-services/speech-service/speech-services-private-link

**Comment by adthorn** [comment]
I'm currently using the ARM Template for the Batch Ingestion Client. The stock Ingestion Client Sample that's provided from Microsoft (https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/ingestion/ingestion-client)

**Comment by adthorn** [comment]
The current client doesn't support a private speech service (custom domain with private endpoint) that I can see. However even if I allow the Speech Service via the Storage Account, I get no where.

Basically, I'm doing vNET integration and private endpoints with the 2 function apps in the App Service. I'm doing private endpoints with the storage account (datalake gen2). I'm doing a private endpoint for the Service bus namespace too. I'm basically doing private endpoints everywhere that I can to secure this solution.

**Comment by adthorn** [comment]
If we had the ability to change the Speech Service Endpoint, that would **probably** resolve all these issues I'm having with Private Endpoints and the DNS.

**Comment by adthorn** [comment]
I am able to get a token if I remove the firewall off of the cognitive speech service.

**Comment by HenryvanderVegte** [comment]
Closing this as the issue was that a premium service bus with private endpoint was used, which resulted in EventGrid not being able to send service bus messages anymore.
