### ISSUE TITLE
Got "cancelled" when is trying to Identify speaker

### ISSUE THREAD

**Issue by DaddyWesker** [Azure-Samples/cognitive-services-speech-sdk#1271]
**Describe the bug**
Hello, i'm trying to test C++ speaker identify on my own data and i'm receiving sometimes following: The most similar voice profile is:  with similarity score: 0. When i'm trying to see into what is SpeakerRecognitionResult looks like i'm seeing 
ResultID "5033b74998db4184b4dd6918ab702790"
Reason "Canceled"
So, what it could be related to? I'm attaching header and source with wrapper i've wrote using your quickstart for speaker identify. And main.cpp. But i'll delete my subscription_key since, as i understand, it shouldn't be shown to anyone except me. It is located in the SpeakerRecognitionWrapper.cpp . Also, i've renamed all files with .txt ext since i wasn't been able to attach them as it is.

[SpeakerRecognitionWrapper.h.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/7275345/SpeakerRecognitionWrapper.h.txt)

[SpeakerRecognitionWrapper.cpp.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/7275346/SpeakerRecognitionWrapper.cpp.txt)

[main.cpp.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/7275348/main.cpp.txt)

If it is necessary, i can upload files which throws that problem.

**To Reproduce**
1. Create several profiles
2. Try to identify with a wav file

**Expected behavior**
SOme score (not zero) and speaker ID

**Version of the Cognitive Services Speech SDK**
1.18.0

**Platform, Operating System, and Programming Language**
 - OS: Linux MInt 20.1
 - Hardware - x64 Laptop with AMD Ryzen 5800h
 - Programming language: C++

Thanks in advance for any help

**Comment by DaddyWesker** [comment]
Also, i've noticed another strange result. Let's say, i've added two profiles (as in the code above) and i've got profile a762f465-8b6c-418d-a9de-7cf1e196c05f and profile f9bcb09f-1a2b-4d72-9dc1-81e22e0df428 nothing more. After invoking identify method i'm getting result with following ID - 00000000-0000-0000-0000-000000000000 and similarity score 0.379906. WHat it could be?

**Comment by glharper** [comment]
@DaddyWesker Thanks for not including your subscription key and for uploading your code. Could you add the wav files you're using as well?

@yshahin Who should we ping about ID: 00000000-0000-0000-0000-000000000000, score 0.379906 result?

**Comment by yshahin** [comment]
empty GUID is the same as nothing matched. The audio passed in did not match either profiles.
Matching happens with a confidence score and if that is low enough we return empty GUID as a match meaning there was none from the list provided matched the audio.

**Comment by DaddyWesker** [comment]
@glharper 
Here is the two train files
https://drive.google.com/file/d/10d7vD280ss_YzOYWtKHiuTs9aGIFePCu/view?usp=sharing
https://drive.google.com/file/d/16zti-7HsuUuTB9JvacGtNarSazcbEeOl/view?usp=sharing

And here is the test files i've got "canceled" with
https://drive.google.com/file/d/1WcXnX2xZMx1ielT5OPOJbnEkYTA6CQ4m/view?usp=sharing

@yshahin 
THanks for your explanation. I guess question with zeros instead of ID is closed, Only "canceled" problem remains.

**Comment by pankopon** [comment]
@glharper Can you please update, was the issue reproduced or solved?

**Comment by sparshsinha123** [comment]
@DaddyWesker When I added the following lines to your code above to see the error message while enrolling
```cpp
void SpeakerRecognitionWrapper::AddEnrollmentsToTextIndependentProfile(shared_ptr<VoiceProfile> profile, string path_to_train_file)
{
    auto audio_config_train = Audio::AudioConfig::FromWavFileInput(path_to_train_file);
    shared_ptr<VoiceProfileEnrollmentResult> enroll_result = nullptr;
    while (enroll_result == nullptr || enroll_result->GetEnrollmentInfo(EnrollmentInfoType::RemainingEnrollmentsSpeechLength) > 0)
        enroll_result = client->EnrollProfileAsync(profile, audio_config_train).get();
    std::shared_ptr< VoiceProfileEnrollmentCancellationDetails > details = VoiceProfileEnrollmentCancellationDetails::FromResult(enroll_result);
    
    std::cout << "error details " << details->ErrorDetails << std::endl;
    std::cout << "Enrollment completed.\n\n";
    
}
```
I get the following error
```bash
error details Bad request (400). Error details: Activation Phrase is not matched Please verify the provided subscription details and language information.
```

@glharper what is the activation phrase here?

**Comment by glharper** [comment]
@sparshsinha123 @DaddyWesker Currently for Independent scenarios, the activation phrase is "I'll talk for a few seconds so you can recognize my voice in the future."

There is a VoiceProfileClient::GetActivationPhrasesAsync(profileType, languageCode) API to retrieve the latest activation phrase, in the unlikely event the phrase changes in the future (more likely is that new phrases will be added someday).

**Comment by sparshsinha123** [comment]
Hey @glharper, thanks for pointing out. 
So is the activation phrase required every time we enrol a speaker?

**Comment by glharper** [comment]
@sparshsinha123 Yes, the activation phrase is required at the start of the audio, for every voice profile you would like to enroll. After the activation phrase, you can use different phrases for independent scenarios. But the activation phrase must come first.

**Comment by jhakulin** [comment]
Closing the issue as answered. Please let us know if there is more information needed for anything else.
