### ISSUE TITLE
How to "connect" API created models / dataset to Speech Studio UI?

### ISSUE THREAD

**Issue by kleindev** [Azure-Samples/cognitive-services-speech-sdk#1272]
Previously, after creating a speech model (or dataset) with the API, I could refresh the Speech Studio and get an option to connect it to the UI - thus being able to create tests, etc

What are the steps to create items in the API and have them visible in the Speech Studio portal?

**Comment by chschrae** [comment]
Hi @kleindev ,

Thanks for reaching out. Can you be a little more specific about what you are doing? Are you using the API from the SDK or a separate REST API? What language are you running from and when did this stop working as expected?

**Comment by kleindev** [comment]
@chschrae we are using this CLI -> https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/spx-basics?tabs=linuxinstall

./spx csr model create --name MODEL-$(Build.BuildNumber) --base "$(basemodel)" --datasets $datasets_string  --output url $HOME/build-speech-output/model-created.json --wait

We can't say when it exactly stopped working, but it last worked on 8/24/2021 (this is a manual step we do monthly - sometimes bi-weekly)

The model and datasets get created, but we no longer have the option to make them visible in the portal - which is needed to conduct some testing before adopting the new model

**Comment by chschrae** [comment]
@kleindev I have contacted the Speech portal team and will let you know when I receive more information.

**Comment by chschrae** [comment]
Hi @kleindev  are you able to specify the "project" via creating a project with "spx csr project create" and then passing that project when creating a model with the --project option?

We have had issues with other features not showing if there is no project assigned. There should be a warning in the portal when there are items without a project.

Let me know if that helps.

**Comment by kleindev** [comment]
@chschrae   So we need to create a new project each time?  

On this "There should be a warning in the portal when there are items without a project." - where is this location?  This sounds similar to the warning we use to get

**Comment by chschrae** [comment]
Hi @kleindev,

It turns out there is a bug in the portal and an update for this will be live in a week or two. Thanks for reporting it!
