### ISSUE TITLE
Java SDK - startContinuousRecognitionAsync never stops

### ISSUE THREAD

**Issue by Fosol** [Azure-Samples/cognitive-services-speech-sdk#1277]
I am using the Java SDK and have been attempting to find out why the `speechEndDetected` never occurs.  I've used an `PushAudioInputStream` to send a WAV file.  It transcribes the whole thing but never sends the stop event, which means I can't get the response back reliably.

If I don't wait for some kind of stop event, then it returns a partial result instead of the whole thing.

**To Reproduce**
1. Create Java Spring API
2. Create Controller endpoint

```java
@PostMapping(path = "/transcribe", consumes = { MediaType.MULTIPART_FORM_DATA_VALUE })
	public String uploadFile(@RequestPart(value = "file", required = true) MultipartFile files)
			throws InterruptedException, ExecutionException, IOException {

		AudioStreamFormat format = AudioStreamFormat.getWaveFormatPCM(40000L, (short) 16, (short) 2);
		PushAudioInputStream audioStream = AudioInputStream.createPushStream(format);
		InputStream fileStream = files.getInputStream();
		audioStream.write(files.getBytes());

		AudioConfig audioConfig = AudioConfig.fromStreamInput(audioStream);
		SpeechRecognizer recognizer = new SpeechRecognizer(speechConfig, audioConfig);

		try {
			Semaphore stop = new Semaphore(0);
			recognizer.startContinuousRecognitionAsync().get();

			StringBuilder text = new StringBuilder();

			recognizer.recognized.addEventListener((o, e) -> {
				if (e.getResult().getReason() == ResultReason.RecognizedSpeech) {
					System.out.println("RECOGNIZED: Text=" + e.getResult().getText());
					text.append(e.getResult().getText());
				} else if (e.getResult().getReason() == ResultReason.NoMatch) {
					System.out.println("RECOGNIZED: Text=" + e.getResult().getText());
					text.append("NoMatch");
				}
			});
			recognizer.recognizing.addEventListener((o, e) -> {
				System.out.println("RECOGNIZING: Text=" + e.getResult().getText());
			});
			recognizer.speechStartDetected.addEventListener((o, e) -> {
				System.out.println("SPEECH START DETECTED");
			});
			recognizer.speechEndDetected.addEventListener((o, e) -> {
				System.out.println("SPEECH END DETECTED");
				stop.release();
			});
			recognizer.canceled.addEventListener((o, e) -> {
				text.append("Failed:" + e.getReason() + " [" + e.getErrorCode() + "] - " + e.getErrorDetails());
				stop.release();
			});
			recognizer.sessionStarted.addEventListener((o, e) -> {
				System.out.println("SESSION STARTED");
			});
			recognizer.sessionStopped.addEventListener((o, e) -> {
				System.out.println("SESSION STOPPED");
				stop.release();
			});

			stop.acquire();
			recognizer.stopContinuousRecognitionAsync().get();

			audioStream.close();
			fileStream.close();

			return text.toString();
		} finally {
			audioConfig.close();
			recognizer.close();
		}
	}
```

**Expected behavior**
When the `SpeechRecognizer` no longer has anything more to transcribe it should send a stop event.

**Version of the Cognitive Services Speech SDK**
1.18.0

**Platform, Operating System, and Programming Language**
 - OS: Windows, within Docker container `mcr.microsoft.com/vscode/devcontainers/java`
 - Hardware - x64
 - Programming language: Java
 - Browser: Postman

There is no error message, it just never ends.

**Comment by mrscarvalho** [comment]
Is there some way to define the exact time ContinuousRecognition should stop, and make it IGNORE silences (like all the other SDKs)? We have to extract text from audio FILES that may have silences (or "non transcrible" music or background sounds) and should not stop on them regardless in the beginning, middle or end - it should go to the end of file, and process all the file. And using recognize_once the limit is too low (we have files between 30 seconds up to 3 minutes).
