### ISSUE TITLE
Recognition Canceled (no connection to remote host)

### ISSUE THREAD

**Issue by LAYLAYLAYLA** [Azure-Samples/cognitive-services-speech-sdk#1280]
Recognition canceled. Reason: Error; ErrorDetails: Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 11001. SessionId: 40f5ac188d6c4ca6b9f0e16820ad7d95

Session stopped event.

I keep getting this error in all of the sample can someone please inform me on what I can do to solve this issue

**Comment by pankopon** [comment]
Closed since no customer update in two weeks, please open a new issue if support is still needed.

**Comment by sandrohanea** [comment]
Hello @dargilco ,
We started to get the same error when a wrong subscription region is provided.
Previously it failed with an meaningful exception.
We're using 1.18.0.

Sample code (ignore invalid wave data as it doesn't matter in this scope):
```

// See wrong subscription region: "North Europe" instead of "northeurope"
var speechConfig = SpeechConfig.FromSubscription("test", "North Europe");

var pushAudioInputStream = new PushAudioInputStream(AudioStreamFormat.GetWaveFormatPCM(123, 8, 2));
var audioConfig = AudioConfig.FromStreamInput(pushAudioInputStream);
var recognizer = new SpeechRecognizer(speechConfig, audioConfig);


recognizer.Recognizing += (sender, eventArgs) =>
{
    Console.WriteLine(eventArgs.Result.Text);
};

recognizer.Canceled += (sender, eventArgs) =>
{
    Console.WriteLine(eventArgs.Result.Text);
};

recognizer.Recognized += (sender, eventArgs) =>
{
    Console.WriteLine(eventArgs.Result.Text);
};

pushAudioInputStream.Write(new byte[] { 22, 23, 12 });

while (true)
{
    var result = await recognizer.RecognizeOnceAsync();
    if (result.Reason == ResultReason.Canceled || result.Reason == ResultReason.NoMatch)
    {
        break;
    }
}
```
