### ISSUE TITLE
SynthesisCanceled Error

### ISSUE THREAD

**Issue by mromeolisten** [Azure-Samples/cognitive-services-speech-sdk#1281]
Hello, 
We're getting the error: 

```
SynthesisCanceled: (cancel) Reason: Error: Unsupported voice my_custom_voice_model. 
websocket error code: 1007
```
When attempting text-to-speech with our custom neural voice

We've verified we're hitting the correct **_Voice Model Name_** , **_Endpoint_** , as well as the region, which is supported _**https://eastus.voice.speech.microsoft.com/cognitiveservices/v1?
deploymentId**_

**Comment by yulin-li** [comment]
Thanks @mromeolisten, which SDK version are you using? Could you share the code snippet?

**Comment by yulin-li** [comment]
Synced with @mromeolisten via email. There was a typo in his codes. Closing this issue.
