### ISSUE TITLE
Segmentation fault when aborting ContinuousRecognitionAsync

### ISSUE THREAD

**Issue by hramoser** [Azure-Samples/cognitive-services-speech-sdk#1288]
**Describe the bug**
We have an application where async speech recognition must be aborted if there is no result within a given time-span. This application handles many parallel recognizers.
Occasionally the application crashes within libMicrosoft.CognitiveServices.Speech.core.so.

**To Reproduce**
See attached source code.

**Expected behavior**
It must be possible to stop the recognition without any problems or side-effects (StopContinuousRecognitionAsync).

**Version of the Cognitive Services Speech SDK**
1.18

**Platform, Operating System, and Programming Language**
 - OS: Ubuntu 18.04
 - Hardware - x64
 - Programming language: C++

**Additional context**
See attached sample code. Note: the issue only occurs occasionally!

[many_threads.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/7381119/many_threads.zip)
n

**Comment by hramoser** [comment]
Hi @Darren!

We still have this issue with v1.19. Sadly the call stack is not very helpful (to me). One explanation could be that data is sent when the underlying object has already been deleted.

libpthread.so.0!__libc_send(int fd, const void * buf, size_t len, int flags) (/build/glibc-S9d2JN/glibc-2.27/sysdeps/unix/sysv/linux/send.c:28)
libMicrosoft.CognitiveServices.Speech.core.so![Unknown/Just-In-Time compiled code] (Unknown Source:0)
std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>::operator()() const(const std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()> * const this) (/usr/include/c++/7/bits/std_function.h:706)
std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)(std::__future_base::_State_baseV2 * const this, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()> * __f, bool * __did_set) (/usr/include/c++/7/future:561)
std::__invoke_impl<void, void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::__invoke_memfun_deref, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&)() (/usr/include/c++/7/bits/invoke.h:73)
std::__invoke<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&)() (/usr/include/c++/7/bits/invoke.h:95)
std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&)::{lambda()#1}::operator()() const(const std::<lambda()> * const __closure) (/usr/include/c++/7/mutex:672)
std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&)::{lambda()#2}::operator()() const() (/usr/include/c++/7/mutex:677)
std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&)::{lambda()#2}::_FUN()() (/usr/include/c++/7/mutex:677)
libpthread.so.0!__pthread_once_slow(pthread_once_t * once_control, void (*)(void) init_routine) (/build/glibc-S9d2JN/glibc-2.27/nptl/pthread_once.c:116)
libMicrosoft.CognitiveServices.Speech.core.so![Unknown/Just-In-Time compiled code] (Unknown Source:0)
libpthread.so.0!start_thread(void * arg) (/build/glibc-S9d2JN/glibc-2.27/nptl/pthread_create.c:463)
libc.so.6!clone() (/build/glibc-S9d2JN/glibc-2.27/sysdeps/unix/sysv/linux/x86_64/clone.S:95)

Von: Darren ***@***.******@***.***>
Gesendet: Donnerstag, 28. Oktober 2021 18:06
An: Azure-Samples/cognitive-services-speech-sdk ***@***.******@***.***>
Cc: Ramoser Herbert ***@***.******@***.***>; Mention ***@***.******@***.***>
Betreff: [External] Re: [Azure-Samples/cognitive-services-speech-sdk] Segmentation fault when aborting ContinuousRecognitionAsync (Issue #1288)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Hi @jhoelzl<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjhoelzl&data=04%7C01%7Ch.ramoser%40commend.com%7Cc4bdef2ae0064b6c983608d99a2ccef6%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637710339511935389%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4Wsmy6QQSTyzpOIIQhlZgYcZNLxY0TDEacwFOWe77oA%3D&reserved=0> @hramoser<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhramoser&data=04%7C01%7Ch.ramoser%40commend.com%7Cc4bdef2ae0064b6c983608d99a2ccef6%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637710339511935389%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dvZVlkNt1CE1%2BISeuOIZbyYdLVmatZrhYGtilkfpnzY%3D&reserved=0> As of now I cannot get this to reproduce using preview version of Speech SDK 1.19. This may have been fixed as a result of other code changes and bug fixes in this release. Speech SDK 1.19 is due to be released sometime next week. Please update to 1.19 when it comes out and let me know if you still see this issue. I am not 100% confident that it was fixed in 1.19 since it's very hard for me to get this to happen. I only saw it once when running with 1.18, but I did not have the proper debug-instrumented binaries at the time so other than a call stack I could not make progress in understanding the issue. I'm hoping it was fixed in 1.19.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure-Samples%2Fcognitive-services-speech-sdk%2Fissues%2F1288%23issuecomment-953988932&data=04%7C01%7Ch.ramoser%40commend.com%7Cc4bdef2ae0064b6c983608d99a2ccef6%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637710339511945383%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8UJlncGw4XMFKELTkOtxbO1W6px%2BgmiOC43IHfzsyFs%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADSNMDUHLXTZPUAT6WK3RO3UJFYFXANCNFSM5GLQYQAA&data=04%7C01%7Ch.ramoser%40commend.com%7Cc4bdef2ae0064b6c983608d99a2ccef6%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637710339511955374%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xbubHyuh5grzxQrX7JJfcSiUg08Uux2%2Fy7WJVo4Lp3Y%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ch.ramoser%40commend.com%7Cc4bdef2ae0064b6c983608d99a2ccef6%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637710339511955374%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vFkdpL8QTyWbUDP737%2BukK5fEjf80vZOfwtKqJWo9IU%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ch.ramoser%40commend.com%7Cc4bdef2ae0064b6c983608d99a2ccef6%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637710339511965368%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ce6VJIcMmYDzraOQspp8Yb1ogGMiHxd8I8IvVrZ9KKA%3D&reserved=0>.


Von: Darren ***@***.***>
Gesendet: Donnerstag, 28. Oktober 2021 18:06
An: Azure-Samples/cognitive-services-speech-sdk ***@***.***>
Cc: Ramoser Herbert ***@***.***>; Mention ***@***.***>
Betreff: [External] Re: [Azure-Samples/cognitive-services-speech-sdk] Segmentation fault when aborting ContinuousRecognitionAsync (Issue #1288)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Hi @jhoelzl<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjhoelzl&data=04%7C01%7Ch.ramoser%40commend.com%7Cc4bdef2ae0064b6c983608d99a2ccef6%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637710339511935389%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4Wsmy6QQSTyzpOIIQhlZgYcZNLxY0TDEacwFOWe77oA%3D&reserved=0> @hramoser<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhramoser&data=04%7C01%7Ch.ramoser%40commend.com%7Cc4bdef2ae0064b6c983608d99a2ccef6%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637710339511935389%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dvZVlkNt1CE1%2BISeuOIZbyYdLVmatZrhYGtilkfpnzY%3D&reserved=0> As of now I cannot get this to reproduce using preview version of Speech SDK 1.19. This may have been fixed as a result of other code changes and bug fixes in this release. Speech SDK 1.19 is due to be released sometime next week. Please update to 1.19 when it comes out and let me know if you still see this issue. I am not 100% confident that it was fixed in 1.19 since it's very hard for me to get this to happen. I only saw it once when running with 1.18, but I did not have the proper debug-instrumented binaries at the time so other than a call stack I could not make progress in understanding the issue. I'm hoping it was fixed in 1.19.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure-Samples%2Fcognitive-services-speech-sdk%2Fissues%2F1288%23issuecomment-953988932&data=04%7C01%7Ch.ramoser%40commend.com%7Cc4bdef2ae0064b6c983608d99a2ccef6%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637710339511945383%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8UJlncGw4XMFKELTkOtxbO1W6px%2BgmiOC43IHfzsyFs%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADSNMDUHLXTZPUAT6WK3RO3UJFYFXANCNFSM5GLQYQAA&data=04%7C01%7Ch.ramoser%40commend.com%7Cc4bdef2ae0064b6c983608d99a2ccef6%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637710339511955374%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xbubHyuh5grzxQrX7JJfcSiUg08Uux2%2Fy7WJVo4Lp3Y%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ch.ramoser%40commend.com%7Cc4bdef2ae0064b6c983608d99a2ccef6%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637710339511955374%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vFkdpL8QTyWbUDP737%2BukK5fEjf80vZOfwtKqJWo9IU%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ch.ramoser%40commend.com%7Cc4bdef2ae0064b6c983608d99a2ccef6%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637710339511965368%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ce6VJIcMmYDzraOQspp8Yb1ogGMiHxd8I8IvVrZ9KKA%3D&reserved=0>.

**Comment by dargilco** [comment]
@hramoser  Thank you for checking, I will continue to investigate. Which Linux device are you using?
Darren

**Comment by dargilco** [comment]
@hramoser is this run on VMs? can you share the specification of the VM hardware you are running on (number of vCPUs, Memory, etc.). If run on Azure VM, can you point to the exact VM type (series) from https://docs.microsoft.com/en-us/azure/virtual-machines/sizes ?

**Comment by dargilco** [comment]
@hramoser also, What is your Speech key's Azure region? And what Azure region is the VM deployed to? Thanks!

**Comment by hramoser** [comment]
PC with Ubuntu 18.04 within VirtualBox (Host Windows 10).

-Herbert

Von: Darren ***@***.***>
Gesendet: Mittwoch, 3. November 2021 15:48
An: Azure-Samples/cognitive-services-speech-sdk ***@***.***>
Cc: Ramoser Herbert ***@***.***>; Mention ***@***.***>
Betreff: [External] Re: [Azure-Samples/cognitive-services-speech-sdk] Segmentation fault when aborting ContinuousRecognitionAsync (Issue #1288)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

@hramoser<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhramoser&data=04%7C01%7Ch.ramoser%40commend.com%7C7bce41bbdf81489223df08d99ed8eb2f%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637715476765235219%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aP5XW2GEIWFpyb%2FNrvANPMGY4%2BUhPBKjivUnSfh7UXY%3D&reserved=0> Thank you for checking, I will continue to investigate. Which Linux device are you using?
Darren

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure-Samples%2Fcognitive-services-speech-sdk%2Fissues%2F1288%23issuecomment-959307949&data=04%7C01%7Ch.ramoser%40commend.com%7C7bce41bbdf81489223df08d99ed8eb2f%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637715476765245213%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pA4Tba8AIND%2BLpIc0rCcGPbH0IdKBTIL6yQT1PN7KZY%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADSNMDRVJVBLBCRY2JFMAEDUKFKSRANCNFSM5GLQYQAA&data=04%7C01%7Ch.ramoser%40commend.com%7C7bce41bbdf81489223df08d99ed8eb2f%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637715476765245213%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=q%2Fh13YPGUeUeNnbvZ96AcZ15tFZVuSa%2FgTI9b1BZdDs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ch.ramoser%40commend.com%7C7bce41bbdf81489223df08d99ed8eb2f%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637715476765255209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rK%2BPfeQ4HdRBUJQVSozrJfkwdL4xJ2Xopy8afaogfOA%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ch.ramoser%40commend.com%7C7bce41bbdf81489223df08d99ed8eb2f%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637715476765255209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8xTl%2FTyvwu2BcvkvlNaeUs228yMEBnhYp5ONp%2FDWo1o%3D&reserved=0>.

**Comment by hramoser** [comment]
@Darren
We observed this problem at our Azure VM (the application is running in a Docker container):
Region VM: westeurope
VM size: Standard_B2ms
Region Speech key: westeurope

For convenience we reproduce and debug this on a development PC (Host Windows 10, Ubuntu 18.04 running in VirtualBox). The VM has 24 MB RAM and 4 CPUs. On the PC the application is running without Docker.

Von: Darren ***@***.***>
Gesendet: Donnerstag, 4. November 2021 00:01
An: Azure-Samples/cognitive-services-speech-sdk ***@***.***>
Cc: Ramoser Herbert ***@***.***>; Mention ***@***.***>
Betreff: [External] Re: [Azure-Samples/cognitive-services-speech-sdk] Segmentation fault when aborting ContinuousRecognitionAsync (Issue #1288)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

@hramoser<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhramoser&data=04%7C01%7Ch.ramoser%40commend.com%7C38c2876338ab406fe84208d99f1dc5b9%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637715772481284156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rMByQiIdlY%2FGgw3mlWhIHxgGGt5fZBEtNBv4WV5PqZs%3D&reserved=0> also, What is your Speech key's Azure region? And what Azure region is the VM deployed to? Thanks!

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure-Samples%2Fcognitive-services-speech-sdk%2Fissues%2F1288%23issuecomment-960266149&data=04%7C01%7Ch.ramoser%40commend.com%7C38c2876338ab406fe84208d99f1dc5b9%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637715772481284156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DEpnCDrnNSGCRxYfyvpjASk7EE0KDdoUpfYJsqoDIVY%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADSNMDUHABJHCF26RLNERVDUKHEK3ANCNFSM5GLQYQAA&data=04%7C01%7Ch.ramoser%40commend.com%7C38c2876338ab406fe84208d99f1dc5b9%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637715772481294148%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=02jwdOISTLZxyr%2BGGa%2B4m2FFqWmM2HZun0%2B6vmcapIw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ch.ramoser%40commend.com%7C38c2876338ab406fe84208d99f1dc5b9%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637715772481304142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qq0ug1RD53YJeY2fWm2iL5aRwLBeVfF5K2Q%2BNrP%2B%2B5c%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ch.ramoser%40commend.com%7C38c2876338ab406fe84208d99f1dc5b9%7C13b1ddb756454e7fbe663171548559da%7C0%7C0%7C637715772481304142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qCO96aNRdoKfhJgJ0NXvmw%2B6OIbqi%2Bi5PZq%2FdYpW7Ts%3D&reserved=0>.

**Comment by dargilco** [comment]
Thank you @hramoser this information helps.

**Comment by dargilco** [comment]
@hramoser for the last 3 days I've been running the sample you provided on Ubunty 18.04 x64 Azure VMs (size "Standard B2 ms). I'm running under gdb debugger. I'm not seeing a segmentation fault. Are you running under a debugger in order to get the calls stack when you hit segmentation fault? (i.e. "gdb ./sample.out" and then "run"). Or do you have a different way to get the crash call stack? 
I will be out of the office returning Nov. 22 and will continue to look at this when I get back. But at the moment I need to figure out the difference between how we run things.

**Comment by jhoelzl** [comment]
Hi @dargilco, any updates on this?

**Comment by dargilco** [comment]
@jhoelzl can you please e-mail me at dcohen@microsoft.com? Since I cannot get a local repo, I'd like to discuss sharing a private build of Speech SDK binaries with you, so you can give us a full call stack with variable values.  Thanks! Darren

**Comment by dargilco** [comment]
Taking this offline directly with @hramoser. Closing this issue, but will update if there are any findings or a fix associated with this issue.
