### ISSUE TITLE
Custom commands are never recognized

### ISSUE THREAD

**Issue by Cris21395** [Azure-Samples/cognitive-services-speech-sdk#1291]
Hello everyone,

I have developed an app for Unity that allows to use voice commands. The user can interact with the app using a keyword to recognize the speech and say a voice command to run an action. The keyword is perfectly recognized. However, once the voice command is said, a default response is sent, which is defined as a fallback when a voice command is not recognized.

The app does not throw any error and I have enabled the speech log feature but I do not find anything relevant to solve my issue.

I'm using the C# SDK Azure-CognitiveServices-Speech 1.18.0 version.

Thank you.

**Comment by pankopon** [comment]
Closed as resolved.
