### ISSUE TITLE
Random drops when using STT (JavaScript)

### ISSUE THREAD

**Issue by has-n** [Azure-Samples/cognitive-services-speech-sdk#1293]
**Describe the bug**
For my use case, I need to convert both sides of a video call to text. For the mic, I am using the SDK's mic recognition. For the speaker, I am using the MediaStream API. 

I use continuous async recognition on both sides. 

Completely randomly, I see drops in the STT (on both mic & speaker streams). The error message is

```
{
  privSessionId: 'F181283623C54E55AF77F6018A7D8FA7',
  privReason: 0,
  privErrorCode: 3
}
```
Please note that the error details field is undefined here. 

As per the [documentation](https://docs.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/cancellationerrorcode?view=azure-node-latest), this is due to too many requests. But we're on a paid tier and should not have this issue (I think). 

Separately, if I try to restart the recognition, I see the following error

```
{
    "privSessionId": "9AC4B13654CE431BA7C0EAF39209DBA0",
    "privReason": 0,
    "privErrorDetails": "Validation failed with status: TooManyRequests websocket error code: 1007",
    "privErrorCode": 2
}
```
Which should be for "BadRequestParameters" but the error details lists "TooManyRequests". 

I'm try to figure these questions out & would appreciate inputs:
1. why are these drops happening randomly?
2. why does there seem to be disparity in the error messages? 

**To Reproduce**
1. start mic recognition 
2. immediately start a new stream based recognition (capturing data from the speaker)

**Expected behavior**
Multiple streams return data without dropping.

**Version of the Cognitive Services Speech SDK**
1.17

**Platform, Operating System, and Programming Language**
 - OS: Windows & MacOS
 - Hardware: x64
 - Programming language: JavaScript
 - Browser [e.g. Chrome, Safari]: Chromium (Electron wrapper)

Editing to add a few more session IDs where this has happened:
'6AB0F788BF5748D4AEDA49C9BE4B2B55'
'FC0B3E74428F486A82A5F2FE185DE981'
'A28A98715DA34BA3A17697120A4B6C7E'
'18F23D3C0A854F12970E0707AAEFAA6C'
'3246FAFA4BB249E284E79338EC58215E'

**Comment by glharper** [comment]
@has-n To see how many connections are active, you can use the sessionStarted and sessionStopped callbacks on each recognizer to increment and decrement a connection counter:
```
let connectionCounter = 0;

reco1.sessionStarted = (s, e) => {
 connectionCounter += 1;
}
reco1.sessionStopped = (s, e) => {
 connectionCounter -= 1;
}
```
...and so on.

Also, [JS Speech SDK version 1.19.0](https://github.com/microsoft/cognitive-services-speech-sdk-js/releases/tag/v1.19.0) has been released, so the error surfacing should be a bit clearer if you upgrade.

**Comment by has-n** [comment]
Thanks @glharper . The app is deployed across many users so will have to centralize the counting. 

Will test with 1.19.0 and raise an issue if it comes up.

Closing the issue for now. Thanks for all the help!
