### ISSUE TITLE
CreateProfileAsync  Whether this parameter is supported  zh-CN

### ISSUE THREAD

**Issue by AlexRen01** [Azure-Samples/cognitive-services-speech-sdk#1294]
**Describe the bug**

I follow this quick start to register my voice and then check for errors in my voice in another audio stream: HTTPS://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-speaker - recognition? Tabs = script&pivots = programming language -- csharp.
but  CreateProfileAsync  like not supported  zh-CN

`using (var profile = await client.CreateProfileAsync(VoiceProfileType.TextDependentVerification, "zh-CN"))`

**To Reproduce**

**Version of the Cognitive Services Speech SDK**
Microsoft.CognitiveServices.Speech  1.18

**Platform, Operating System, and Programming Language**
Microsoft.CognitiveServices.Speech  1.18

**Additional context**
![image](https://user-images.githubusercontent.com/48472715/138995332-c22310f5-ed8d-408a-b2ee-3b1e2e9fc82a.png)

**Comment by glharper** [comment]
@AlexRen01 Thanks for using Speech SDK. There's a new release, 1.19, with updated support for voice profiles, could you check using that version? My tests using 1.19 and zh-CN created a new voice profile correctly.

**Comment by jhakulin** [comment]
Closing the issue as not repro with 1.19.0 version of SDK. Please let us know if there is more issues.
