### ISSUE TITLE
Microsoft bot framework support voice assistant in python language ? and can i use a library from python speech-to-text and text-to-speech ?

### ISSUE THREAD

**Issue by MohdAwamleh** [Azure-Samples/cognitive-services-speech-sdk#1295]
Microsoft bot framework support voice assistant in python language ? 
and can i use a library from python speech-to-text and text-to-speech without objection from azure?
and please i need an example if Microsoft support voice assistant

**Comment by amitkumarshukla** [comment]
@MohdAwamleh Could you please provide more details about what are you planning to do ?

**Comment by chschrae** [comment]
@MohdAwamleh  I can take a guess at what you are asking, but please let me know if this helps.

It sounds like you are saying you have your own preference of speech-to-text and text-to-speech that is NOT from Microsoft and you want to connect to your own bot-framework bot for the dialog portion.

Currently the Dialog Service Connector is not available in Python, but if you only need the bot-framework connection of it then you should be able to use the Bot-Framework-SDK to talk to your bot directly. Your speech-to-text and text-to-speech would be handled by the other libraries you mentioned.

Link to Bot-framework python SDK: https://github.com/Microsoft/botbuilder-python#:~:text=This%20repository%20contains%20code%20for%20the%20Python%20version,conversation%20and%20build%20sophisticated%20bot%20applications%20using%20Python.

**Comment by jhakulin** [comment]
@MohdAwamleh Support for Dialog Service Connector APIs for Python supporting BotFramework configuration will be released in the next 1.20.0 Speech SDK release (ETA beginning of Feb 2022).

**Comment by jhakulin** [comment]
Closing as support for this has been released in 1.20.0 Speech SDK release. Please let us know if there are any issues.
