### ISSUE TITLE
High CPU usage with compressed audio

### ISSUE THREAD

**Issue by trydis** [Azure-Samples/cognitive-services-speech-sdk#1298]
**Describe the bug**
High CPU usage when using compressed audio.

- Processing 1 stream resulted in ~60% CPU usage
- When the client was done sending the audio data it spiked to ~100%
- When the client disconnected it took around 10-15 seconds for it to settle down
- When repeating the same with uncompressed audio the CPU usage was insignificant, even when processing multiple audio streams
- Profiling the code didn't really uncover any bad actors
- Main suspect is that GStreamer is causing the high CPU usage

**To Reproduce**
1. Start continuous recognition
2. Send compressed audio, which in our case was MU-LAW (8000 hz/8 bps/mono)
3. Observe CPU usage

**Expected behavior**
Lower CPU usage

**Version of the Cognitive Services Speech SDK**
1.18.0

**Platform, Operating System, and Programming Language**
 - OS: Linux (Ubuntu VM on Parallels and when running in Kubernetes)
 - Hardware: x64
 - Programming language: C#
 - Browser: N/A

**Comment by amitkumarshukla** [comment]
@trydis Thanks a lot for reporting the issue. I am looking at this right now and will get back to you.

**Comment by jhakulin** [comment]
@trydis We have identified one possible reason for the CPU issue and working on improvement for the near future release.

**Comment by trydis** [comment]
@jhakulin Great, thanks for the update.

**Comment by robch** [comment]
@trydis: I've confirmed that our possible reason is likely the culprit. Under some circumstances, we had a thread that wasn't using appropriate synchronization mechanisms, and was effectively "spinning" while we were waiting for audio data to be decompressed via gstreamer. I verified that running 8 instances of mp3 decoding would peg my development machine to 100% CPU usage, whereas, after the fix, the same setup only resulted in 10% CPU usage. The fix should be in our next public release, 1.20.

**Comment by trydis** [comment]
Thanks @robch 👍

**Comment by pankopon** [comment]
Internal work item ref. 3914918.

**Comment by trydis** [comment]
@jhakulin: Sorry for not noticing this until now. I've switched jobs in the meantime, so not able to verify it currently. Hopefully i will be able to use it again 😀 Thanks for the fix!
