### ISSUE TITLE
reuse sdk.AudioInputStream.createPushStream() with same data gives another recognizer.recognizeOnceAsync result

### ISSUE THREAD

**Issue by koenti** [Azure-Samples/cognitive-services-speech-sdk#130]
I used the provided node.js sample to experiment.
When I want to reuse/loop my code, the recognize results are wrong.  The first loop the result is ok, but the next loops the results are all wrong.  I problem seems to be the way I reuse/rebuild pushStream variable.
I expect 5 times the same results, when I read 5 times the same WAV file and do 5 times the recognition.

`function loop() {
  // create the push stream we need for the speech sdk.
  var pushStream = undefined;
  pushStream = sdk.AudioInputStream.createPushStream();

  // open the file and push it to the push stream.
  fs.createReadStream(filename).on('data', function (arrayBuffer) {
    pushStream.write(arrayBuffer.buffer);
  }).on('end', function () {
    pushStream.close();
    analyse(pushStream);  // Rest of sample code where recognition is done.  When done, loop() is called again. 
});
}`

**Expected behavior**
I try to reset all variables, so I expect the recognition result is always the same.

**Version of the Cognitive Services Speech SDK**
1.2.0

**Platform, Operationg System, and Programming Language**
Node.js

**Comment by rhurey** [comment]
Your look code looks right.

Can you help me understand what other modifications to the sample you made?

I tried this and was was able to get 5 recognitions:

> "use strict";
> 
> // pull in the required packages.
> var sdk = require("microsoft-cognitiveservices-speech-sdk");
> var fs = require("fs");
> 
> // replace with your own subscription key,
> // service region (e.g., "westus"), and
> // the name of the file you want to run
> // through the speech recognizer.
> var subscriptionKey = <YOUR KEY HERE>;
> var serviceRegion = "westus"; // e.g., "westus"
> var filename = "whatstheweatherlike.wav"; // 16000 Hz, Mono
> 
> var count = 1;
> 
> function loop() {
>   // create the push stream we need for the speech sdk.
>   var pushStream = undefined;
>   pushStream = sdk.AudioInputStream.createPushStream();
> 
>   // open the file and push it to the push stream.
>   fs.createReadStream(filename).on('data', function (arrayBuffer) {
>     pushStream.write(arrayBuffer.buffer);
>   }).on('end', function () {
>     pushStream.close();
>     analyse(pushStream); // Rest of sample code where recognition is done. When done, loop() is called again.
>   });
> }
> 
> function analyse(pushStream) {
> 
> // we are done with the setup
> console.log("Now recognizing from: " + filename);
> 
> // now create the audio-config pointing to our stream and
> // the speech config specifying the language.
> var audioConfig = sdk.AudioConfig.fromStreamInput(pushStream);
> var speechConfig = sdk.SpeechConfig.fromSubscription(subscriptionKey, serviceRegion);
> 
> // setting the recognition language to English.
> speechConfig.speechRecognitionLanguage = "en-US";
> 
> // create the speech recognizer.
> var recognizer = new sdk.SpeechRecognizer(speechConfig, audioConfig);
> 
> // start the recognizer and wait for a result.
> recognizer.recognizeOnceAsync(
>   function (result) {
>     console.log(result);
> 
>     recognizer.close();
>     recognizer = undefined;
>     if(count++ < 5){
>        loop();
>     }
>   },
>   function (err) {
>     console.trace("err - " + err);
> 
>     recognizer.close();
>     recognizer = undefined;
>   });
> }
> 
> loop();

**Comment by rhurey** [comment]
It would also be helpful to know what results you are getting.

**Comment by fmegen** [comment]
What is happening in this function?

it might be the code re-uses the Recognizer (like, stores it as a global variable, etc)
analyse(pushStream); // Rest of sample code where recognition is done. When done, loop() is called again.

can you share more details about your setup?

**Comment by wolfma61** [comment]
closing

**Comment by julis903** [comment]
I have the same problem, I create a new recognizer and a new pushStream but I receive the text of the old call with the new text concatenated. I would like instead to receive two separate text.

**Comment by rhurey** [comment]
Can you make sure it's not the same issue as this: https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/73

The sample had a bug in it with how the buffer was being passed....

**Comment by julis903** [comment]
It is the same, thank you!
