### ISSUE TITLE
REST API for Language Identification and support for links to audio files

### ISSUE THREAD

**Issue by nosalan** [Azure-Samples/cognitive-services-speech-sdk#1304]
Is it possible to perform Language Identification without using SDK but directly through HTTP for batch mode and WS API for continuous mode? If yes a link to documentation or example is welcome.

My use case would that I hit HTTP Endpoint to which I send send link to the audio file and get detected languages in the response. STT service has such capability.

**Comment by jhakulin** [comment]
@nosalan Checked with the team and REST API for LID is not publicly available yet, however that will be released in the near future releases.
