### ISSUE TITLE
Speech To Text StartContinuousRecognition Realtime Performance

### ISSUE THREAD

**Issue by derevell** [Azure-Samples/cognitive-services-speech-sdk#1305]
We are using the basicRecognizer.StartContinuousRecognitionAsync() and a PushAudioInputStream to push an audio input stream from a mic and then output the results to a text editor. I am looking to see if there is a setting to break the results into 2-4 words chunks on the basicRecognizer.Recognized event vs the entire phrase (example 15 word sentence) to give a more real-time experience. to the end user seeing "real-time" recognition.

Expected Behavior:
As the user mic audio stream is uploaded the results are returned in smaller chunks.

**Comment by jhakulin** [comment]
@derevell Thanks for the report. By using Recognizing event, you will get the intermediate results almost in real-time. The Recognized event will provide you the final result of the last spoken phrase, that happens e,g, if you have a pause in the speech input during continuous recognition. You will see this well when you register to both Recognizing and Recognized events and display their output in your app. Let us know if using Recognizing event, will help you to get the results you need.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechrecognizer.recognizing?view=azure-dotnet

**Comment by jhakulin** [comment]
Closing, let us know if more information is needed.
