### ISSUE TITLE
Documentation of service properties

### ISSUE THREAD

**Issue by 4voiceAG** [Azure-Samples/cognitive-services-speech-sdk#1306]
```SpeechConfig``` contains 2 methods to control how exactly how you want STT to work: ```SetProperty()``` and ```SetServiceProperty()```.
While SetProperty accepts a PropertyId enum value which you can look up in the corresponding documentation (https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.propertyid?view=azure-dotnet), SetServiceProperty() only accepts string-valued property names and string-valued property values.

So far, I wasn't able to find an overview of the possible properties values and a description of the different parameter values.

IMO such an overview could be very helpful to find out if a given behavior is supported and how to activate it.

In the concrete case I was looking for a way to control auto punctuation for STT dictation and couldn't find anything appropriate in the Speech PropertyIds.
Thanks to @rhurey's reply to issue https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/667#issuecomment-690840772 I found the service property "punctuation" and value "explicit", but I'd wish for an easier accessable list.

**Comment by jhakulin** [comment]
@4voiceAG Thanks for the report. We have a workitem internally to make the documentation clearer on this area. Setting issue accepted.

**Comment by 4voiceAG** [comment]
Great, thanks!

**Comment by pankopon** [comment]
Internal work item ref. 2904427.

**Comment by dargilco** [comment]
We have an internal work item to document what properties are supported on each object. Therefore, I'm closing this issue.

**Comment by ygorlf** [comment]
@dargilco this page is already available? Still trying to figure out which options I can use to customize the punctuation property
