### ISSUE TITLE
swagger_client.rest.ApiException: (400)

### ISSUE THREAD

**Issue by georgearun** [Azure-Samples/cognitive-services-speech-sdk#1307]
I have downloaded python-client for 'eastus'  and installed successfully pip by following these steps - [https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python](url)

**While running the code for Batch transcription I'm getting the following error:**
"""
swagger_client.rest.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-store', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=utf-8', 'api-supported-versions': '2.0,3.0', 'api-deprecated-versions': '2.0', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'apim-request-id': 'f1c39f84-d268-41bb-a268-1c53f8c1aaab', 'x-content-type-options': 'nosniff', 'Date': 'Thu, 11 Nov 2021 10:02:52 GMT'})
HTTP response body: {
  "code": "InvalidRequest",
  "message": "Only \"Standard\" subscriptions for the region of the called service are valid.",
  "innerError": {
    "code": "InvalidSubscription",
    "message": "Only \"Standard\" subscriptions for the region of the called service are valid."
  }
}
"""

I am trying to get the transcript for audio that is 30+ mins long. Using SDK it's just giving partial output. What can be the possible solution for the above issue, have tried other local too.

**Comment by chlandsi** [comment]
It looks like you are using a free subscription. Batch transcription is only available with a standard (paid) subscription.
