### ISSUE TITLE
Can i set silence duration at end of speech ?

### ISSUE THREAD

**Issue by yeshunping** [Azure-Samples/cognitive-services-speech-sdk#131]
It seems that the default silence duration is 2s , it means that after 2 second silence, silence detected will be triggered. BUT on some cases, we need a shorter threshold for it, for example , 1s or 600ms for it.
I will C++ SDK ,but i failed to find a interface to set it. I only found that 
```
InitialSilenceTimeout = 2
```
for NoMatchCode

Is there such a interface ? or if this feature will be supported in the coming release ? or existed already in SDK of other languages ?

**Comment by yeshunping** [comment]
or is there some config for EndSilenceTimeout ?

**Comment by yeshunping** [comment]
ok ,I will try SpeechConfig. thanks very much.

**Comment by nansravn** [comment]
Any update regarding the silence timeout via SDK APIs? Is that already available?

**Comment by wolfma61** [comment]
There is a 'SetProperty' method on the config which was added to the SDK to allow you to set parameters to the request
(in C#: https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.propertycollection.setproperty?view=azure-dotnet)

This way you can set the EndSilenceTimeout (PropertyIDs in C#:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.propertyid?view=azure-dotnet

thx
Wolfgang
