### ISSUE TITLE
Python batch transcription quick start sample needs V3 upgrade

### ISSUE THREAD

**Issue by eric-urban** [Azure-Samples/cognitive-services-speech-sdk#1312]
The Python batch transcription [quickstart sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/python/from-blob) and it's README need to be updated for v3 as shown in [this PR](https://github.com/Azure-Samples/cognitive-services-speech-sdk/pull/736/files) for a similar sample.

**Comment by pankopon** [comment]
Closing this item since the referred sample has been removed as outdated.
