### ISSUE TITLE
Is it possible to get "libMicrosoft.CognitiveServices.Speech.core.so" file which supports platform that uses "softfp" as floating point ABI? 

### ISSUE THREAD

**Issue by hys618** [Azure-Samples/cognitive-services-speech-sdk#1314]
Hello, I'm trying to use speech SDK in my embedded linux environment. 
I've downloaded SDK file, followed the instructions in quickstart guide, and modified Makefile so that I can build the quickstart sample source in arm32 environment for my hardware device. 
I failed to build the sample source because my working environment only supports "softfp" as floating point ABI whereas the .so file("libMicrosoft.CognitiveServices.Speech.core.so") is compiled in an environment which uses VFP register arguments(floating point ABI == hard).

It's impossible for me to simply modify the toolchain that I use because of other dependencies.
I guess my suggestion may be somewhat unrealistic or strange, but is it possible to get another version of .so file which can be successfully built in my current platform, or do you have any plans to provide .so file which could be used in platforms that use "softfp" as floating point ABI?

**Comment by pankopon** [comment]
Hi, can you describe your environment in more detail? What is the device and OS (if details can be enclosed) and why is 'hard' not supported (as based on 'softfp' the device should still have FPU)? - This may be the first time anyone has asked for a different floating-point ABI to use, so currently there are no plans.

**Comment by pankopon** [comment]
Closed since no further details received, please open a new item if you need more support.
