### ISSUE TITLE
RaspberryPi SDK Translator

### ISSUE THREAD

**Issue by MooonSwitch** [Azure-Samples/cognitive-services-speech-sdk#1316]
My current project is to use the Azure azure-cognitiveservices-speech on a raspberry pi to translate a conversation between two people using bluetooth headphones. I'm not sure what to do anymore, as the Raspbian OS doesn't work with SDK, nor did it work when I downloaded windows onto my Raspberry Pi either. I've seen lots of mentions about Ubuntu being a solution, but I'm not sure which version to use (Desktop, Server, Core) or if that's even going to solve my solution. Any sort of guidance would be very much appreciated, as I'm at a loss at this point.

Thank you :)

**Comment by pankopon** [comment]
Hi, the officially supported Linux distributions are listed at https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk?tabs=linux%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio#get-the-speech-sdk and Ubuntu is among them. We test on RPi 4 using Ubuntu.

The following has been verified to work with RPi 4:
1. Install **Ubuntu Server 20.04.3 LTS** (64 or 32-bit), see instructions https://ubuntu.com/tutorials/how-to-install-ubuntu-on-your-raspberry-pi#1-overview
1. After base installation (no desktop required unless you wish to add it), do
    ```
   sudo apt update
   sudo apt upgrade
   sudo apt install alsa-utils pulseaudio pulseaudio-utils
    ```
   and reboot.
1. Verify that audio works in general recording and playback (e.g. with `arecord` and `aplay`). In case of missing (playback) audio, do additional configuration as described in https://forums.raspberrypi.com/viewtopic.php?t=289126.
1. Finally install Speech SDK specific dependencies as documented on the Speech SDK page linked above plus any quickstart/sample specific pages and readmes.

**Comment by MooonSwitch** [comment]
What if I wanted to take the pi outside of the range of my personal computer, would I still follow all these steps?

**Comment by pankopon** [comment]
@MooonSwitch Not sure what you mean - the setup needs to be done just once; install OS, configure, verify it works (incl. BT in your case). Compare it to setting up any portable device, like even a laptop, that you can then take with you and use anywhere.

**Comment by MooonSwitch** [comment]
Okay awesome, thank you! Next question, which is probably stated in the link you sent but I want to make sure, is this version of SDK on Ubuntu 20.04 only usable with C++, Java, and .NET Core? My original program was in Python so it would save some time if it's available in Python. I'm asking because I tried using "pip install azure-cognitiveservices-speech" and it didn't work immediately.

**Comment by pankopon** [comment]
Yes, as noted on https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk?tabs=linux%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio#get-the-speech-sdk Python is supported only on Linux x64 for now. There is a backlog item about ARM support but no ETA.

**Comment by MooonSwitch** [comment]
So I've followed your instructions, and my progress has come to another halt. While I've been using the Ubuntu 20.04 server, I am only able to download ARM versions of softwares. If there isn't ARM support yet, would using a different OS on my raspberry pi 4 help with this issue?

**Comment by pankopon** [comment]
@MooonSwitch ARM is supported with C++, Java and .NET Core. Or do you mean you can only use Python in development? Unfortunately the Speech SDK has Python ARM packages only for macOS at the moment.

**Comment by pankopon** [comment]
Closed as answered, please open a new item if you need more support.
