### ISSUE TITLE
No such module 'MicrosoftCognitiveServicesSpeech'

### ISSUE THREAD

**Issue by ykying** [Azure-Samples/cognitive-services-speech-sdk#1317]
**Describe the bug**
iOS -> Archive -> 1.19 version will show No such module 'MicrosoftCognitiveServicesSpeech'

After rollback to 1.18.0, everything is fine

**Comment by jhakulin** [comment]
@ykying Thanks for the report, we need more information in order to proceed. Could you please provide more information on what is the iOS-> Archive ? And how you reproduce this ?
iOS -> Archive -> 1.19 version will show No such module 'MicrosoftCognitiveServicesSpeech'

**Comment by jhakulin** [comment]
@ykying This is probably the same problem as reported here https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1320. We are making an update to pod file

**Comment by jhakulin** [comment]
closing this as duplicate as informed earlier, please let us know if there is problems
