### ISSUE TITLE
ModuleNotFoundError: No module named '_speech_py_impl' (again)

### ISSUE THREAD

**Issue by mrscarvalho** [Azure-Samples/cognitive-services-speech-sdk#1318]
Hi,

I'm testing Azure Cognitive Services Speech-to-text with Python following the "Get started" [HERE](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-speech-to-text?tabs=windowsinstall&pivots=programming-language-python).

The error happens at first line when trying to import the library: import azure.cognitiveservices.speech as speechsdk

I already installed the library with pip install azure-cognitiveservices-speech, it is listed among all other libraries, the file "speech_py_impl.py" is there at site-packages folder (I even tried to put this folder on system path - no change).

Also installed last version of Microsoft Visual C++ Redistributable ([here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)) as suggested on [THIS](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/792) similar issue. 

I'm using Python 3.7 x64 on Windows 7, and SDK version is: azure-cognitiveservices-speech==1.19.0

For development I'm just using Notepad++ and other simple text editors, where I can run many other Python apps (including other Cloud APIs I'm testing to choose one for production).

I already generated the key, but the error happens even before the authentication step.

Something I'm missing to setup the environment?

Thanks and regards.

_Full error message:_
```
Traceback (most recent call last):
  File "D:\Python\Anaconda3\lib\site-packages\azure\cognitiveservices\speech\speech_py_impl.py", line 27, in swig_import_helper
    return importlib.import_module(mname)
  File "D:\Python\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: Não foi possível encontrar o procedimento especificado.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Dropbox (AP)\DELPHI\Python\VoiceRecognition\MicrosoftAzure\AzureTeste1.py", line 3, in <module>
    import azure.cognitiveservices.speech as speechsdk
  File "D:\Python\Anaconda3\lib\site-packages\azure\cognitiveservices\speech\__init__.py", line 8, in <module>
    from .speech import *
  File "D:\Python\Anaconda3\lib\site-packages\azure\cognitiveservices\speech\speech.py", line 8, in <module>
    from . import speech_py_impl as impl
  File "D:\Python\Anaconda3\lib\site-packages\azure\cognitiveservices\speech\speech_py_impl.py", line 33, in <module>
    _speech_py_impl = swig_import_helper()
  File "D:\Python\Anaconda3\lib\site-packages\azure\cognitiveservices\speech\speech_py_impl.py", line 31, in swig_import_helper
    return importlib.import_module('_speech_py_impl')
  File "D:\Python\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_speech_py_impl'
```

**Comment by jhakulin** [comment]
@mrscarvalho Speech SDK supports Windows10 or later OS versions. The problem might be due to Windows 7 version you are using. Do you have possibility to upgrade the OS ?

**Comment by mrscarvalho** [comment]
Hi @jhakulin, thank you for the reply!

I just tested on Windows 10 and it worked (although a very different environment than my developing machine). :-)

But it limits a bit. Although officially ended support by Microsoft Win 7 is still used around, especially in companies that have a longer time life for software. I'm also testing the ComputerVision SDK and it works well on Win 7.

I also tested on **Windows Server 2016**, and I had the **same error**. It is annoying because I was planning to create a server application to process speech-to-text requests from our team preventing the need to install libraries for all users (all our servers have this OS). We have many Python apps running on them and never had compatibility issues (Python 3.7).

Anyway, I’ll keep exploring the SDK, that seems to be doing a good job (although our very difficult contents to convert because background music and fast paced speech). ;-)

**Comment by jhakulin** [comment]
@mrscarvalho On Windows Server 2016, have you also installed  Microsoft Visual C++ Redistributable package ? 
How about do you have several Python versions installed on the system ? Sometimes several Python versions have conflicted and caused failures like this. Please check the older closed items in this samples repo by searching closed items with ModuleNotFoundError, you will find issues like this: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/792

**Comment by mrscarvalho** [comment]
Hello @jhakulin, thank you for the reply!

After spending a couple of hours fighting with Azure Speech installation not working on a Win 10 computer and still having the “ModuleNotFoundError: No module named '_speech_py_impl'” error, I realized that the MS Visual C++ 2015-2022 Redistributable should match PYTHON’s bits, not Windows bits...

So, after installing the x86 version of the C++ redistributable it worked on that Win 10, and also in Windows Server 2016 with Python 3.7.2 (32 bits) we use.

Anyone having the same issue, check the Microsoft Visual C++ 2015-2022 Redistributable that matches to your PYTHON’s bits: 

https://aka.ms/vs/17/release/vc_redist.x64.exe -> for PYTHON 64 bits!

https://aka.ms/vs/17/release/vc_redist.x86.exe -> for PYTHON 32 bits!

PS: It didn’t work on Windows 7 anyway, even after the update. :-(

**Comment by jhakulin** [comment]
@mrscarvalho Thanks for this information, this is also something we want to update in our documentation to be more clear.
