### ISSUE TITLE
JAVA SDK 1.18/1.19 issue: stopContinuousRecognitionAsync().get() costs 10 seconds

### ISSUE THREAD

**Issue by Bob-Pengcheng** [Azure-Samples/cognitive-services-speech-sdk#1319]
Hello, we call "stopContinuousRecognitionAsync().get()" in session stopped listener.  

For sdk 1.16, it works fine. 

After we upgrade the sdk version to 1.19, "stopContinuousRecognitionAsync().get()"  always costs 10 seconds.

Now, we have to call "stopContinuousRecognitionAsync().get()" asynchronously to avoid the issue.

However, I still wonder what's the change in 1.19 causes this issue.

```
reco.sessionStopped.addEventListener((s, e) -> {
    System.out.println("Session stopped event.");
    // it works fine in 1.16, but always costs 10 seconds in 1.19,
    try {
        System.out.println("Begin Time is " + (new Date()).toString());
        reco.stopContinuousRecognitionAsync().get();
        System.out.println("End Time is " + (new Date()).toString());
    } catch (Exception ex) {
        ex.printStackTrace();
    }
});
```

**Comment by Bob-Pengcheng** [comment]
Add some black-box test.

In 1.19, It seems  stopContinuousRecognitionAsync().get() is waiting eventListener to be finished.
`Session stopped event in.
Begin Time is Fri Nov 19 17:03:13 CST 2021
Session stopped event out.
time cost= 9998
End Time is Fri Nov 19 17:03:23 CST 2021
`

In 1.16. stopContinuousRecognitionAsync().get() finishes without waiting.
`Session stopped event in.
Begin Time is Fri Nov 19 17:06:17 CST 2021
time cost= 191
End Time is Fri Nov 19 17:06:17 CST 2021
`

Test codes are listed below.  
`reco.sessionStopped.addEventListener((s, e) -> {
                System.out.println("Session stopped event in.");
                try {
                    stopTranslationWithFileSemaphore.release();
                    Thread.sleep(9999);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                System.out.println("Session stopped event out.");
            });

            System.out.println("Begin working...");
            reco.startContinuousRecognitionAsync().get();

            stopTranslationWithFileSemaphore.acquire();
            long startTime = System.currentTimeMillis();
            System.out.println("Begin Time is " + (new Date()).toString());
            reco.stopContinuousRecognitionAsync().get();
            System.out.println("time cost= " + (System.currentTimeMillis() - startTime));
            System.out.println("End Time is " + (new Date()).toString());`

**Comment by glharper** [comment]
@Bob-Pengcheng 
There's a known usability challenge with synchronizing these stopContinuousRecognitionAsync() calls with stopping audio flow. We plan to improve this in an upcoming release, but we can share some information about the behavior and workarounds:

The problem: internally, the SpeechRecognizer processes input audio in chunks of 100ms (3200B for default 16khz16bit mono PCM). When stopContinuousRecognitionAsync() is called, the recognizer patiently waits to fill the rest of its current chunk (up to another 100ms worth) before gracefully requesting a final result and stop. If audio input (e.g. via a PushAudioInputStream) is stopped before the stopContinuousRecognitionAsync() call is completed, the recognizer may wait up to 10s in case more audio arrives.

Workaround option 1: if the end of audio flow can be deferred until the final recognition or SessionStopped event arrives, that will fully prevent the recognizer from getting stuck waiting for 10s. The downside is that this may result in a small audio discontinuity--audio that was "in flight" while stopContinuousRecognitionAsync() is called will be sent but not used, and if the audio after the stop*() needed to be kept then this may be inappropriate.

Workaround option 2: to fully work around the problem and lose absolutely no audio at the end of a session, a bit of state management is needed:

Premise: don't directly call stopContinuousRecognitionAsync() (which could be thought of as "waitForTheLastAudioAndRequestALastRecognitionAsync()") but instead use an "end of stream" state to produce a more forceful (but still graceful) closure

When a stop is desired:
Stop servicing more data: don't write more to a PushAudioInputStream or don't return new real data out of a PullAudioInputStream; Instead, write a 0-length buffer (for push streams) or return a 0-length read (for pull streams)
Internally, the SDK marks the stream as "ended" when it processes this 0-byte element and will immediately begin stopping with no expectation of more audio

With the stream ended, the recognizer will quickly receive a final recognition result (if applicable) immediately followed by a Canceled event with a Reason of "EndOfStream." This isn't an error--rather it's the signal that the recognizer is now fully stopped and can be used again.

To restore the stream: at any point after the Canceled event arrives and before a new start*() call is made, ensure a non-zero-length data component is made available. This can mean ensuring the next "real" PushAudioInputStream::Write call is made before the recognizer is started or it can mean immediately pushing a very small amount (e.g. 32B) of artificial silence (0s) when Canceled with EndOfStream arrives -- either way, what's important is to clear that "end of stream" state before calling start*() again.

As long as the "ended" stream was restored first, a subsequent startContinuousRecognitionAsync() call will behave normally and allow recognition to continue.

That last one is certainly a headache and it's a priority to make this more elegant. If the slightly "lossy" first workaround is usable, it's much simpler.
