### ISSUE TITLE
Using Speech SDK in Azure Function raises error of missing "Microsoft.CognitiveServices.Speech.csharp.bindings.dll"

### ISSUE THREAD

**Issue by vansen** [Azure-Samples/cognitive-services-speech-sdk#132]
I am trying to use the speech SDK inside an Azure function. It picks up a wav file and sends it to Speech Recognition and I would like to have the transcribed text back. I am usin 64 Bit in VS 2017 and in the Function App. I deploy using VS and then run the Function inside the Azure Portal for testing purposes. 
I am using NuGet: Microsoft.CognitiveServices.Speech, v1.2.0

When it reaches the line:
var config = SpeechConfig.FromSubscription(sSubcriptionID, "westeurope");
it breaks with the following exception:

System.TypeInitializationException: The type initializer for 'Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'Microsoft.CognitiveServices.Speech.csharp.bindings.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_carbon_csharp(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate) at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE.SWIGExceptionHelper..cctor() --- End of inner exception stack trace --- at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE.SWIGExceptionHelper..ctor() at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE..cctor() --- End of inner exception stack trace --- at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE.SpeechConfig_FromSubscription(String jarg1, String jarg2) at Microsoft.CognitiveServices.Speech.Internal.SpeechConfig.FromSubscription(String subscription, String region) at Microsoft.CognitiveServices.Speech.SpeechConfig.FromSubscription(String subscriptionKey, String region) at HomeAutomation.SpeechToText.<Run>d__0.MoveNext() 

Any advice on what to do here?

Thanks

**Comment by wolfma61** [comment]
at the minimum you need these dlls deployed with your application Microsoft.CognitiveServices.Speech.core.dll, Microsoft.CognitiveServices.Speech.csharp.bindings.dll, Microsoft.CognitiveServices.Speech.csharp.dll. Also the redistributable for the runtime library for VS2017 needs to be deployed to the target environment.

if those are there, it should all run fine.

**Comment by vansen** [comment]
Thanks, I found the files in the subfolders but had to include them as files in the project and set the copy property to always. Then it worked. Aren't the dlls supposed to be published automatically to the function app when a publish is made with the NuGet package installed?

**Comment by wolfma61** [comment]
closing - if you still experience problems, please open a new issue

**Comment by Koustavmodak** [comment]
I'm getting the same error after installing the redistributable for vs2017 and the mentioned dlls are in the execution path. I'm using the sdk from webjobs in c#. I'm getting the error from fromsubscription() method.
