### ISSUE TITLE
C# - Dispose duration

### ISSUE THREAD

**Issue by trydis** [Azure-Samples/cognitive-services-speech-sdk#1321]
`StopContinuousRecognitionAsync` takes around 10 seconds to complete (timeout AFAIK).

Is it then the expected behavior that disposing the recognizer takes around 10 seconds as well?

This line:
`this.recoHandle?.Dispose()`

Version of the Cognitive Services Speech SDK
1.19.0

OS: macOS/Linux
Hardware: x64
Programming language: C#

**Comment by glharper** [comment]
@trydis Thanks for using Speech SDK, and writing this issue up. This may be related to #1319...could you share some sample code to reproduce this?

**Comment by trydis** [comment]
I'm working on something else this week, so i'll be unable to share something in the near future.

That being said, https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1319#issuecomment-974283960 makes a lot of sense. 

I'm seeing all combinations:
- Sometimes `StopContinuousRecognitionAsync` takes 10 seconds, something it's quick
- Sometimes `SpeechRecognizer.Dispose()` takes 10 seconds, something it's quick

So stopping & disposing takes between <1 sec -> ~20 seconds.

I guess it depends on what's mentioned in the comment, if there are chunks available or not after stopping the recognizer or not.

Should be able to look more into it next week.

**Comment by trydis** [comment]
Here's the output from a profiling session, with 50 instances of the `SpeechRecognizer`.

`StopContinuousRecognitionAsync` and `Dispose` taking ~10 seconds each.

<img width="699" alt="Skjermbilde 2021-12-09 kl  11 10 47" src="https://user-images.githubusercontent.com/446036/145376928-748e9f10-054a-46cb-a384-89a969674c01.png">

**Comment by trydis** [comment]
Option 2 from https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1319#issuecomment-974283960 works for stopping the recognizer, but disposing it still takes ~10 seconds. I guess having some sort of recognizer pool could circumvent the problem.

**Comment by trydis** [comment]
Just to follow up, the solution seemed to be calling `Close` on the `PushAudioInputStream`, before disposing things.

Didn't see it mentioned in the quickstart:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-speech-to-text?tabs=windowsinstall&pivots=programming-language-csharp

But discovered it in the samples.
