### ISSUE TITLE
High variance in latency in speech-to-text with recognizeOnceAsync + Pronunciation Assessment

### ISSUE THREAD

**Issue by owenchu** [Azure-Samples/cognitive-services-speech-sdk#1327]
**Describe the bug**
We use the speech sdk in the browser to transcribe user-generated audio against reference text using the Pronunciation Assessment feature. For ~95% of the time, we are able to get a response in ~2 seconds, which is great. But for ~5% of the time, response time can be as long as ~20 seconds.

Extremely high response time seems to go away when Pronunciation Assessment is disabled. 

I'm not sure if this issue is related to #1074 and #1124. Let me know if I can do anything else on my side to capture more debug information.

**To Reproduce**
```
const azureStt = require('microsoft-cognitiveservices-speech-sdk');
const speechConfig = azureStt.SpeechConfig.fromAuthorizationToken(...);
speechConfig.speechRecognitionLanguage = 'en-US';
speechConfig.requestWordLevelTimestamps();
speechConfig.outputFormat = azureStt.OutputFormat.Detailed;

const audioConfig = azureStt.AudioConfig.fromWavFileInput(wavFile);
let recognizer = new azureStt.SpeechRecognizer(speechConfig, audioConfig);

const pronunciationAssessmentConfig =
    new azureStt.PronunciationAssessmentConfig(
      referenceText,
      azureStt.PronunciationAssessmentGradingSystem.HundredMark,
      azureStt.PronunciationAssessmentGranularity.Phoneme,
      true /* EnableMiscue */,
);
pronunciationAssessmentConfig.applyTo(recognizer);

recognizer.recognizeOnceAsync(...);
```

**Expected behavior**
Consistent response time when using recognizeOnceAsync + Pronunciation Assessment

**Version of the Cognitive Services Speech SDK**
Tested with these SDK versions:
"microsoft-cognitiveservices-speech-sdk": "^1.18.0"
"microsoft-cognitiveservices-speech-sdk": "^1.19.0"

**Platform, Operating System, and Programming Language**
 - OS: macOS
 - Hardware: x64
 - Programming language: JavaScript
 - Browser: Chrome

**Additional context**
WebSocket messages from Chrome DevTools (note the "Time" field of the two highlighted messages): 
<img width="1257" alt="ws-messages" src="https://user-images.githubusercontent.com/1363403/142962321-489a3a60-1dd3-49e1-a1fc-617085e72025.png">

Here's some details for more interesting messages in the stream:

**[speech-config]** (upstream)
```
Path: speech.config
X-RequestId: 5DF51D09A4B44239B7B5B4919663FCB8
X-Timestamp: 2021-11-23T02:00:59.743Z
Content-Type: application/json

{"context":{"system":{"name":"SpeechSDK","version":"1.19.0","build":"JavaScript","lang":"JavaScript"},"os":{"platform":"Browser/MacIntel","name":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.20 Safari/537.36","version":"5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.20 Safari/537.36"},"audio":{"source":{"bitspersample":16,"channelcount":1,"connectivity":"Unknown","manufacturer":"Speech SDK","model":"File","samplerate":16000,"type":"File"}}},"recognition":"interactive"}
```

**[speech.context]** (upstream)
```
Path: speech.context
X-RequestId: 2C20CAE7DCD04F98A60C2A313139BE37
X-Timestamp: 2021-11-23T02:00:59.743Z
Content-Type: application/json

{"phraseDetection":{"enrichment":{"pronunciationAssessment":{"referenceText":"My third story is about death.","gradingSystem":"HundredMark","granularity":"Phoneme","dimension":"Comprehensive","enableMiscue":true}}},"phraseOutput":{"detailed":{"options":["PronunciationAssessment","WordTimings","SNR"]},"format":"Detailed"}}
```

**[turn.start]** (downstream)
```
X-RequestId:2C20CAE7DCD04F98A60C2A313139BE37
Path:turn.start
Content-Type:application/json; charset=utf-8

{
  "context": {
    "serviceTag": "a726a8ce39db461085edff14194e64e9"
  }
}
```

**[speech.startDetected]** (downstream)
```
X-RequestId:2C20CAE7DCD04F98A60C2A313139BE37
Path:speech.startDetected
Content-Type:application/json; charset=utf-8

{"Offset":900000}
```

**[telemetry]** (upstream)
```
Path: telemetry
X-RequestId: 2C20CAE7DCD04F98A60C2A313139BE37
X-Timestamp: 2021-11-23T02:01:22.567Z
Content-Type: application/json

{"Metrics":[{"End":"2021-11-23T02:00:59.496Z","Name":"ListeningTrigger","Start":"2021-11-23T02:00:59.496Z"},{"End":"2021-11-23T02:01:22.566Z","Name":"Microphone","Start":"2021-11-23T02:00:59.565Z"},{"End":"2021-11-23T02:00:59.742Z","Id":"795FC1A610254DDB8A58CFC2E362ECA0","Name":"Connection","Start":"2021-11-23T02:00:59.497Z"},{"PhraseLatencyMs":[22999]},{"FirstHypothesisLatencyMs":[22452]}],"ReceivedMessages":{"turn.start":["2021-11-23T02:00:59.813Z"],"speech.startDetected":["2021-11-23T02:01:21.909Z"],"speech.hypothesis":["2021-11-23T02:01:22.017Z","2021-11-23T02:01:22.421Z","2021-11-23T02:01:22.422Z"],"speech.endDetected":["2021-11-23T02:01:22.437Z"],"speech.phrase":["2021-11-23T02:01:22.564Z"],"turn.end":["2021-11-23T02:01:22.566Z"]}}
```

**Comment by yulin-li** [comment]
Thanks @owenchu for reporting this issue, @yinhew could you help to take a look?

**Comment by yinhew** [comment]
@owenchu Thanks for reporting this issue!
We've looked into this issue and partially understood the cause, but we still need more time to fully resolve it.
The issue only happened to Central US region per our investigation, you can switch to a different region like East US as a quick work around if it's doable for you.
We will update this thread if there is any progress.

**Comment by owenchu** [comment]
Thanks for the update!

I just switched to West US. I'll report back if it happens again.

**Comment by owenchu** [comment]
This issue seems to also happen in westus.

What are the fields in [SpeechRecognitionResult](https://docs.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/speechrecognitionresult?view=azure-node-latest) that I can log on my side to help you debug the issue?

**Comment by owenchu** [comment]
This somehow has worsened in our production environment. I've seen requests that took as long as 67 seconds.

**Comment by yinhew** [comment]
@owenchu this looks a different issue. How many times did you hit this for?
Can you follow below sample code to print the session id, which can help us debug?
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/index.html#L731

**Comment by owenchu** [comment]
Here's some session ID / latency pairs:

973EF2551CFA494F9B7D3B27C379BF4C / 11,986 ms
56D8E35FB53A4A99B49E46326BA9A776 / 10,999 ms
929B7E3A15124368A549AF8571E24289 / 10,579 ms

**Comment by yinhew** [comment]
Thanks for these session IDs! They helped a lot to my debugging.
Per debugging, the above cases were due to network transition issue, the audio chunks were uploaded using nearly 10 seconds.
So it was a different issue.
Where was the client invoking our speech service? Was it far from West US (California)?

Can you share me some cases with more significant latency when you hit?

**Comment by owenchu** [comment]
Thanks for getting back to me, @yinhew!

The audio chunks were indeed sent from countries quite far from California. My use case involves directly streaming audio from the user's browser from all over the world. Is there a reliable way on the client side to find out the best endpoint to send audio over?

**Comment by yinhew** [comment]
Here is our full region list:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/regions#speech-to-text-text-to-speech-and-translation

If you have CDN and distributed deployments of your website on different countries, you can point to different regions for different deployments.

If you don't have your backend server, you can try to roughly detect the user location by IP or language info in client code, and map to the nearest region in above list.

**Comment by owenchu** [comment]
Thanks for the info! I'll give it a try.

**Comment by glecaros** [comment]
Hi @owenchu, were you able to resolve your issue using @yinhew's suggestion?

**Comment by owenchu** [comment]
The issue has been largely resolved, although I still see latency spikes at times. I'm not sure if it's because of slow network connections or code start issues of the API instances. That said, feel free to close the issue for now. :-)

**Comment by glecaros** [comment]
Glad it was solved. Please open a new issue if you run into other problems. Thanks!
