### ISSUE TITLE
Confidence possible values 

### ISSUE THREAD

**Issue by nosalan** [Azure-Samples/cognitive-services-speech-sdk#1329]
I'm using .net core SDK for one shot language recognition from audio with `RecognizeOnceAsync` . After setting detailed output I see this:

```
{
  "Id": "SomeId",
  "RecognitionStatus": "Success",
  "Offset": 0,
  "Duration": 300800000,
  "PrimaryLanguage": {
    "Language": "en-us",
    "Confidence": "High"
  },
  "DisplayText": "",
  "NBest": [{
      "Confidence": 0.0,
      "Lexical": "",
      "ITN": "",
      "MaskedITN": "",
      "Display": ""
    }
  ]
}
```
The question is, what are the possible values of Confidence string? Can it be configured so that the confidence is a numerical value ranging from 0 to 1?

**Comment by dargilco** [comment]
Hi @nosalan, I reached out to the language ID service folks to answer your question. I or they will reply soon.

**Comment by shiwenmichael** [comment]
The confidence can be High or Low, and it is not configurable.

**Comment by nosalan** [comment]
Thanks.
