### ISSUE TITLE
Detecting multiple languages in one-shot mode

### ISSUE THREAD

**Issue by nosalan** [Azure-Samples/cognitive-services-speech-sdk#1330]
I'm using .net core SDK for one shot language recognition from audio with `RecognizeOnceAsync` . After setting detailed output I see this:

```
{
  "Id": "SomeId",
  "RecognitionStatus": "Success",
  "Offset": 0,
  "Duration": 300800000,
  "PrimaryLanguage": {
    "Language": "en-us",
    "Confidence": "High"
  },
  "DisplayText": "",
  "NBest": [{
      "Confidence": 0.0,
      "Lexical": "",
      "ITN": "",
      "MaskedITN": "",
      "Display": ""
    }
  ]
}
```
Is it possible to see a list of languages detected and not only primary language? The audio I sent was in fact english-chinese. 
Why is the DisplayText and NBest result returned? It always seems to be empty.

**Comment by dargilco** [comment]
Hi @nosalan, I'm not sure what you mean by "see a list of languages detected and not only primary language". Are you using the new SourceLanguageRecognizer object, as shown in this sample? https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/standalone_language_detection_samples.cs#L16 . It seems so based on your detailed recognition output. This will only give you the detected language, not the recognized text. If you want both language detection and recognition result, you need to use the SpeechRecognizer object, as shown in this sample: https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_recognition_with_language_id_samples.cs#L21. In both cases you must specify a set of languages when calling AutoDetectSourceLanguageConfig.FromLanguages.

**Comment by dargilco** [comment]
Also @nosalan, do you need to detect the language once at the start, or do you need to detect it periodically since the language may change from English to Chinse (and vice versa)? If the language may change, be sure to use continuous language ID as pers this sample: https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/standalone_language_detection_samples.cs#L132 .

**Comment by nosalan** [comment]
Hi @dargilco, I hoped for an array of languages returned that are present in the audio being submitted in one shot mode. It's nice that it is available in the continuous mode, however, this mode is slower even if I have the entire audio ready. I should choose something from those options, thanks.
