### ISSUE TITLE
Problems with Diarization - Rest API

### ISSUE THREAD

**Issue by murilomendes** [Azure-Samples/cognitive-services-speech-sdk#1331]
Hello Guys!

I'm implementing Speech-to-text in an app. But I'm facing some problems with some audio files. 

What I'm trying to do is create a transcription and get the Speech as Text, with the "speakers" differentiation.  But the response only appear "Speaker":  1. The audio file is a conversation between two people. Nothing extraordinary.

The file is: https://drive.google.com/file/d/15saVNxnlZ8chSs07ggkgKUptmgW6284m/view?usp=sharing

The request body is:
`{
  "contentUrls": [
    "****"
  ],
  "properties": {
    "diarizationEnabled": true,
    "wordLevelTimestampsEnabled": true,
    "punctuationMode": "Automatic",
    "profanityFilterMode": "masked"
  },
  "locale": "pt-BR",
  "displayName": "Esta é uma transcrição de teste"
}`

A good observation is: I've tried with another audio with < 30 seconds and get the same problem. 

Thank you!!

**Comment by eldakms** [comment]
@murilomendes , we have a new set of diarization models that should address this issue (will be in public preview some time by February). Currently they are in private preview only, you can ping me directly at eldak at microsoft.com if you want to have early access. Thanks!

**Comment by pankopon** [comment]
@murilomendes Did you try early access to new models and if yes, did they work better?
@eldakms Is the public preview of new models still due in Feb? Is there any work item or doc page that we could track for status?

**Comment by pankopon** [comment]
@eldakms Please update with status.

**Comment by pankopon** [comment]
Closing the item since no more updates from either side. Please open a new issue if more support is needed.
