### ISSUE TITLE
Add offset parameter to PushAudioInputStream.Write method

### ISSUE THREAD

**Issue by sandrohanea** [Azure-Samples/cognitive-services-speech-sdk#1333]
**Is your feature request related to a problem? Please describe.**
Currently, PushAudioInputStream.Write have 2 overloads: one with the buffer, and one with both the buffer and a count(size).
We receive this buffer from another source and possibly it also has an offset where the data starts but in order to pass that to the pushAudioInputStream we need to copy the entire buffer. Also, Span<byte> support could have fixed this problem but probably that is more complicated with the whole c++ interop.

**Describe the solution you'd like**
Enrich the SDK with a new overload for the `PushAudioInputStream.Write` method to also contain an offset, similar to Stream.Write(byte[] buffer, int offset, int count).
Maybe also rename the `size` parameter of the existing method with `count` (to have the same signature as Stream.Write).

**Describe alternatives you've considered**
Support for Span<byte> which can be created over the buffer without copying the data and allocating more memory or copying to buffer from the exact offset before passing it to PushAudioInputStream.Write method.

**Additional context**
![image](https://user-images.githubusercontent.com/40202887/143416453-8d118ace-76cb-4001-a14f-0e8c2bcc799f.png)

**Comment by dargilco** [comment]
Thank you for your good suggestion @sandrohanea! I've created a ticket in our internal work tracking system with all the details you provided. It will be reviewed in our next round of SDK release planning and prioritized with other feature requests. I will go ahead and close this issue as it will continue to be tracked internally. 
Darren
