### ISSUE TITLE
Pronunciation assessment results missing in Android build (C# Unity)

### ISSUE THREAD

**Issue by aidenkoh801** [Azure-Samples/cognitive-services-speech-sdk#1334]
Hi all!
I'm trying to implement pronunciation assessment in an Android Unity app, and have been unsuccessful in getting any pronunciation results from SpeechRecognitionEventArgs.

I was successful in getting pronunciation results when running on my Windows machine (within Unity Editor).

What could be causing this error?

Here is my RecognizedHandler code:

```c#
    private void RecognizedHandler(object sender, SpeechRecognitionEventArgs e)
    {
        
        if (e.Result.Reason == ResultReason.RecognizedSpeech)
        {

            pronunciationString = "";
            recognizedString = $"{e.Result.Text}";

            // Function is unable to progress from here on in Android build:
            var pronunciationResult = PronunciationAssessmentResult.FromResult(e.Result);
            
            pronunciationString += string.Format(
                "Accuracy score: {0}, Pronunciation score: {1}, Completeness score : {2}, FluencyScore: {3} \n",
                pronunciationResult.AccuracyScore, pronunciationResult.PronunciationScore,
                pronunciationResult.CompletenessScore, pronunciationResult.FluencyScore);
            pronunciationString += "\n Word level details \n";
            
            foreach (var word in pronunciationResult.Words)
            {
                pronunciationString += string.Format("Word: {0}, Accuracy score: {1}, Error type: {2}", word.Word,
                    word.AccuracyScore, word.ErrorType);
                
                foreach (var phoneme in word.Phonemes)
                {
                    pronunciationString += string.Format("Phoneme: {0}, Phoneme AccuracyScore: {1} \n",
                        phoneme.Phoneme, phoneme.AccuracyScore);
                }
            }
        }
        if (e.Result.Reason == ResultReason.NoMatch)
        {   
           Debug.Log($"NOMATCH: Speech could not be recognized.");
        }
    }
```

Any help will be much appreciated!

**Comment by yulin-li** [comment]
Hi @aidenkoh801 , thx for using Speech SDK and reporting this issue. Could you pls share the [SDK log](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging) so we can investigate quickly?

**Comment by aidenkoh801** [comment]
Hi @yulin-li, thanks for getting back, 
Here is the SDK log, it seems that the pronunciation results does return, from 9956ms onwards.
[logFile.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/7664992/logFile.txt)

Thank you!

**Comment by yulin-li** [comment]
Hi @aidenkoh801, sorry for the late reply. I am investigating the issue. Meanwhile, as a work around, you can parse the raw json string in your codes (using `result.Properties.GetProperty(PropertyId.SpeechServiceResponse_JsonResult);`)

**Comment by aidenkoh801** [comment]
Hi @yulin-li , thanks for replying :)
Yes, parsing the raw json string works well
Upon further testing, I believe in the Android build we cannot access PronunciationResults from PronunciationAssessmentResult.FromResult(e.Result) as they do not exist

**Comment by pankopon** [comment]
@yulin-li Please update with findings, has the issue been resolved?

**Comment by jliong-ch** [comment]
Hi, I am also trying to implement Pronunciation Assessment into my project.
It works fine on Windows but it gives serialization error when I build into Android APK and try to use it.

And like what was described it was from the line:
`PronunciationAssessmentResult.FromResult(e.Result)`
So the problem still exists on Android platform at least...

Is there any possible update or fix to it? Otherwise I'll just parse the json string on my own

**Comment by pankopon** [comment]
@yulin-li Any status update, or is the suggested workaround still the only way to go?

**Comment by monoganog** [comment]
Can confirm still having this issue on both Android and iOS devices, but not in the editor. Using unity version 2020.3 and Microsoft.CognitiveServices.Speech.1.21.0.unitypackage

The workaround mentioned by @yulin-li does allow access to the pronunciation results thankfully

**Comment by yulin-li** [comment]
@monoganog thanks for confirmation. @pankopon I don't think we can fix this issue could be fixed easily. So we can close this issue and put it into our internal backlog. Thanks.
