### ISSUE TITLE
"Bad Conversion" - DialogServiceConnector with CustomCommandsConfig & AudioConfig

### ISSUE THREAD

**Issue by CarteKiwi** [Azure-Samples/cognitive-services-speech-sdk#1337]
Hi,

"bad conversion" exception thrown when using AudioConfig.FromMicrophoneInput("my selected microphone").
(When instanciate DialogServiceConnector without the AudioConfig parameter, everything is working fine)

![Capture](https://user-images.githubusercontent.com/12309245/144026994-87401f2d-3cc3-4a6f-b630-79b05bd6a1b3.PNG)

**To reproduce:**
Instanciate DialogServiceConnector using AudioConfig.FromMicrophoneInput(...)

**Expected behavior**
I need to instanciate DialogServiceConnector using a specific microphone. 

**Version of the Cognitive Services Speech SDK**
Version 1.19.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - x64
 - Programming language: C#
 -  UWP app

**Comment by brandom-msft** [comment]
Hi @CarteKiwi -

How are you enumerating your devices? I'm wondering if this is an issue with the device.

Also, how is your `commandsConfig` object being set up?

**Comment by CarteKiwi** [comment]
Hi @brandom-msft,

Thanks you for your reply. Appreciate.

I finally gave up the idea to select the microphone. 
I'm using `var config = AudioConfig.FromDefaultMicrophoneInput();`
But it's not a solution. By the way, I think that it's linked to [my other problem HERE](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1338).

To answer your questions:
- Here is how I list devices:
```
            var devices = await DeviceInformation.FindAllAsync(DeviceClass.AudioCapture);

            foreach (var device in devices)
            {
                Debug.WriteLine($"AUDIO DEVICE : {device.Name}, {device.Id}");
            }
```
- commandsConfig is set up like that:
```
            var commandsConfig = CustomCommandsConfig.FromSubscription(applicationId, subscription, region);
            commandsConfig.SetProperty(PropertyId.SpeechServiceConnection_RecoLanguage, "fr-fr");
```

**Comment by brandom-msft** [comment]
Can you provide a log capturing this behavior? I see the log you posted on the other issue (thank you!) but this scenario is different and the exception provided doesn't give a lot of immediate clues. Thanks!

**Comment by CarteKiwi** [comment]
No log in the file. It's empty.

![image](https://user-images.githubusercontent.com/12309245/144572708-3730041f-4a93-48cd-98de-493662521d0c.png)

![image](https://user-images.githubusercontent.com/12309245/144571359-1cb1b622-8930-4d11-a3a7-e63605054bb9.png)

StackTrace:
  at Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail(IntPtr hr)

I also tried passing `AudioProcessingOptions.Create(AudioProcessingConstants.AUDIO_INPUT_PROCESSING_ENABLE_DEFAULT` in connector constructor.
Same result.

**Comment by CarteKiwi** [comment]
Just found something ! Don't use the Device NAME even if the variable name is called "deviceName" !!! **Use Device ID instead** ! :)
Everything is now working well. No need to use the devcon cmd.
Just have to specify the device ID in the AudioConfig method.
The Speech SDK should change the name of the variable to be more explicit :)
Thanks anyway, and great job for all the **Speech Studio** stuff, it's awesome :)
