### ISSUE TITLE
wrong error - batch transcription failed with The recordings URI contains invalid data.

### ISSUE THREAD

**Issue by vovanb** [Azure-Samples/cognitive-services-speech-sdk#1340]
**Describe the bug**
wrong error message - in case that original file is stereo and IsDiarizationEnabled = true batch transcription is failed with error
The recordings URI contains invalid data.

**To Reproduce**
1.using default example https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/31abbe1e4b6e3a0bc7d60a72fd3802cb928654dc/samples/batch/csharp example 
2.file https://batchrecordingstorage.file.core.windows.net/fileshare/rcd_2b6297790426000d_220c10de.tmp_stereo.wav?sp=rl&st=2021-12-05T17:00:12Z&se=2023-01-06T17:00:00Z&sv=2020-08-04&sig=zOFNnP1LZ9hyv2sx5Go6v8Lc3cnCoqimys6tM%2BWppho%3D&sr=f

**Expected behavior**
return actual error that file should be in mono format

**Version of the Cognitive Services Speech SDK**
v3

**Platform, Operating System, and Programming Language**
 - OS: Windows
 - Hardware - x64
 - Programming language: C#

**Additional context**
 The recordings URI contains invalid data.

**Comment by zhouwangzw** [comment]
Thanks for reporting the issue. We will investigate.

**Comment by zhouwangzw** [comment]
I looked into the issue. Yes, the error message "The recordings URI contains invalid data" that is returned in the GET transcription response is not very clear for your case. Currently, as workaround, you can check the report.json file for detailed error messages for each audio in your request. You can get the location of report.json file via GET transcription files (https://eastus2.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/operations/GetTranscriptionFiles). In the report.json, the status of each audio of your request as well possible error messages are listed. For example, you will get the following error messages for your sample audio:

{
  "successfulTranscriptionsCount": 0,
  "failedTranscriptionsCount": 1,
  "details": [
    {
      "source": "https://batchrecordingstorage.file.core.windows.net/fileshare/rcd_2b6297790426000d_220c10de.tmp_stereo.wav?sp=rl&st=2021-12-05T17:00:12Z&se=2023-01-06T17:00:00Z&sv=2020-08-04&sig=zOFNnP1LZ9hyv2sx5Go6v8Lc3cnCoqimys6tM%2BWppho%3D&sr=f",
      "status": "Failed",
      "errorMessage": "Reason BadChannelConfiguration, Details: Stereo audio is not supported when using diarization. (JobId 511bef28-38c3-4184-90ee-2d6924581da9).",
      "errorKind": "BadChannelConfiguration"
    }
  ]
}

I will forward your request for better error message to the team and we will provide a better error message in a future version.
Thanks,
Zhou

**Comment by zhouwangzw** [comment]
I am closing the issue. Please raise a new one if you have any questions.
