### ISSUE TITLE
"MicrosoftCognitiveServicesSpeech/SPXSpeechApi.h' file not found

### ISSUE THREAD

**Issue by zhao520wei** [Azure-Samples/cognitive-services-speech-sdk#1342]
your project not work   /Users/mac_bigsur/Desktop/Demo/cognitive-services-speech-sdk-master 2/samples/objective-c/ios /speech-samples
not work

last download form github

Xcode 13.1

my Pod
 pod 'MicrosoftCognitiveServicesSpeech-iOS', '1.17.0'

when I run the demo app 

dyld: Library not loaded: @rpath/MicrosoftCognitiveServicesSpeech.framework/MicrosoftCognitiveServicesSpeech
  Referenced from: /var/containers/Bundle/Application/150CD0F3-9AB1-4D40-8C40-E3235B306FC8/speech-samples.app/speech-samples
  Reason: image not found

**Comment by jhakulin** [comment]
@zhao520wei Thanks for the report, I believe this is known issue we are making update to Speech SDK pod. Please see workaround until we have new pod pushed to the Cocoapods repo.
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1320#issuecomment-988836381

**Comment by jhakulin** [comment]
There will be a fix for https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1320 in 1.21.0 Speech SDK release. Setting pending close.

**Comment by jhakulin** [comment]
Fix has been included in 1.21.0 Speech SDK for iOS, closing the item.
