### ISSUE TITLE
Invalid Bundle in TestFlight

### ISSUE THREAD

**Issue by CheShengSu** [Azure-Samples/cognitive-services-speech-sdk#1344]
**Describe the bug**
My App can run on simulator and My iPhone. 
But when upload the archive to App Store Connect, I got the error: "invalid binary file".

**To Reproduce**
1.  Add the line to Podfile 

``` 
platform :ios, '15.0'
target 'MyTarget' do
  use_frameworks!
  pod 'MicrosoftCognitiveServicesSpeech-iOS', '1.18.0'
end
 ```

2. Archive and upload to App Store Connect

**Expected behavior**
 upload to App Store Connect without error.

**Version of the Cognitive Services Speech SDK**
1.18.0

**Platform, Operating System, and Programming Language**
 - IDE: Xcode 13.1
 - Hardware - MacBook Pro (15-inch, 2018)
 - Programming language: Swift (SwiftUI)

**Additional context**
error message in my mail:
 ```
ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.
ITMS-90562: Invalid Bundle - There's an issue with the app's bitcode compilation. Rebuild the app using the current public (GM) version of Xcode and upload it again.
ITMS-90562: Invalid Bundle - The app submission can not be successfully recompiled from bitcode due to missing symbols during linking. You can try to reproduce and diagnose such issues locally by following the instructions from: https://developer.apple.com/library/archive/technotes/tn2432/_index.html
```

If I disable "Include bitcode for iOS content", the upload will be success without error. But this action will also disable dSYM files for debugging.

I also fine the same issue here:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1141

**Comment by jhakulin** [comment]
@CheShengSu Thanks for the report. We have fixed bitcode issue in 1.19.0 version of Speech SDK. Could you please upgrade to that ? NOTE: currently you need a workaround for 1.19.0 when building for generic iOS device, see this https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1320#issuecomment-988836381

**Comment by CheShengSu** [comment]
Thanks.  I have tried '1.19.0' before but got "module not found" error when archiving. I will report a new issue for '1.19.0'.

**Comment by CheShengSu** [comment]
In MicrosoftCognitiveServicesSpeech-iOS 1.19.0, this issue also exists!!

**Comment by jhakulin** [comment]
@tomasgreen In https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1209 you informed there was no bitcode issues anymore on 1.19.0, could you confirm this ? Any ideas what might be the reason here?

**Comment by tomasgreen** [comment]
> @tomasgreen Related to #1209 you informed in email there was no bitcode issues anymore on 1.19.0, could you confirm this ? Any ideas what might be the reason here ? Thanks for help!

Hi! No I haven't had any issues since the 1.19.0 release but then I'm using Swift Package Manager and not CocoaPods. 

@CheShengSu try dropping CocoaPods and use SPM instead. You do this by creating a local swift package with a binary target and include the framework in your project. I'm attaching some quick and dirty code that should do the trick!

Once you've included the framework you can simply use `SPMMicrosoftCognitiveServicesSpeech` as an import in your code.

Btw @jhakulin, where's Microsofts official spm package? 😉

```swift
// swift-tools-version:5.5
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "SPMMicrosoftCognitiveServicesSpeech",
    platforms: [.iOS(.v13)],
    products: [
        .library(
            name: "SPMMicrosoftCognitiveServicesSpeech",
            targets: ["SPMMicrosoftCognitiveServicesSpeech"]),
        .library(
            name: "MicrosoftCognitiveServicesSpeech",
            targets: ["MicrosoftCognitiveServicesSpeech"])
    ],
    targets: [
        .target(
            name: "SPMMicrosoftCognitiveServicesSpeech",
            dependencies: ["MicrosoftCognitiveServicesSpeech"]),
        .binaryTarget(
            name: "MicrosoftCognitiveServicesSpeech",
            url: "https://csspeechstorage.blob.core.windows.net/drop/1.19.0/MicrosoftCognitiveServicesSpeech-XCFramework-1.19.0.zip",
            checksum: "077cf2c2ff5d70c62d4ada90b80c0fc3b8bc59818b4eeaae5b1b28c48e4ddab4"
        )
    ]
)
```

**Comment by jhakulin** [comment]
@tomasgreen Thank you for the help! I have not yet exact plan to move to SPM, however that looks like a correct thing to do. Will let you know once we have more information. @CheShengSu Were you able to see the issue when using SPM as instructed above?

**Comment by CheShengSu** [comment]
@jhakulin and @tomasgreen , thank you a lot. But My Xcode seems to have bug that can't using SPM to add package. I will try the `SPMMicrosoftCognitiveServicesSpeech` method when I can use SPM.

**Comment by tomasgreen** [comment]
@jhakulin sound good, although there is no need to "move" to anything. You might already be familiar with this but you can support both SPM, CocoaPods etc at the same time. You can create a separate repo or just add a Package.swift file to this repo.

The above instructions works just fine but I was a bit preoccupied yesterday and there's an even simpler syntax:

```swift
// swift-tools-version:5.5
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "MicrosoftCognitiveServicesSpeech",
    platforms: [.iOS(.v13)],
    products: [
        .library(
            name: "MicrosoftCognitiveServicesSpeech",
            targets: ["MicrosoftCognitiveServicesSpeech"])
    ],
    targets: [
        .binaryTarget(
            name: "MicrosoftCognitiveServicesSpeech",
            url: "https://csspeechstorage.blob.core.windows.net/drop/1.19.0/MicrosoftCognitiveServicesSpeech-XCFramework-1.19.0.zip",
            checksum: "077cf2c2ff5d70c62d4ada90b80c0fc3b8bc59818b4eeaae5b1b28c48e4ddab4"
        )
    ]
)
```

For each new version of framework you need to change the url to the zip-file and change the checksum using `shasum -a 256 MicrosoftCognitiveServicesSpeech.xcframework.zip`. Lastly you might want to manage versions by tagging the repo, this is optional but preferred.

I might be kicking in open doors here and if so I apologise for the verbose answer 🙂

**Comment by tomasgreen** [comment]
@CheShengSu did you update to Xcode 13.2? If so you might want to follow this thread https://developer.apple.com/forums/thread/696504, there's a few (me including) outraged developers out there 🙂

I managed to get Xcode back on track this morning by downloading the app from the developer site, but as I understand it hans't worked for everyone. Downgrading to 13.1 is always an option.

**Comment by CheShengSu** [comment]
Yes, my Xcode version is 13.2, I will try downgrading to 13.1. Thank you!

**Comment by tomasgreen** [comment]
> Yes, my Xcode version is 13.2, I will try downgrading to 13.1. Thank you!

I hope it works out!

P.S It might be a good idea to look at the material in https://developer.apple.com/library/archive/technotes/tn2432/_index.html, it's actually quite helpful to rebuild the app from Bitcode locally (in case you haven't already tried it).

**Comment by CheShengSu** [comment]
I downgraded my Xcode to 13.1, after add local SPM "MicrosoftCognitiveServicesSpeech", Xcode can't compile at the import: 
`import MicrosoftCognitiveServicesSpeech`. The message is 
"No such module 'MicrosoftCognitiveServicesSpeech'".
I don't know why.

**Comment by tomasgreen** [comment]
> I downgraded my Xcode to 13.1, after add local SPM "MicrosoftCognitiveServicesSpeech", Xcode can't compile at the import:
> `import MicrosoftCognitiveServicesSpeech`. The message is
> "No such module 'MicrosoftCognitiveServicesSpeech'".
> I don't know why.

Did you add the framework to your targets "General"->"Frameworks, Libraries, and Embedded content"?

**Comment by CheShengSu** [comment]
I added from "project", "package Dependencies", "+", "Add Local...", the folder `MicrosoftCognitiveServicesSpeech` containing `Package.swift`.
In "targets", "General", "Frameworks, Libraries, and Embedded content", "+", I can't find `MicrosoftCognitiveServicesSpeech`.

**Comment by tomasgreen** [comment]
> I added from "project", "package Dependencies", "+", "Add Local...", the folder `MicrosoftCognitiveServicesSpeech` containing `Package.swift`.
> In "targets", "General", "Frameworks, Libraries, and Embedded content", "+", I can't find `MicrosoftCognitiveServicesSpeech`.

I actually haven't seen that button before, using it the way you described didn't work for me either for some reason. I guess it's another amazing Xcode bug 🙂

Instead of doing it that way just drag your local package folder over to the project root. Wait for it to resolve which might take some time and you might get failures in the meantime, but just hold on until it's completed, the errors will go away. 

Once it's resolved you should find a framework available to be added in "Frameworks, Libraries, and Embedded content".

**Comment by CheShengSu** [comment]
I still can't successfully add a local package to my project.
I got some other task to do that I prefer to wait for the pod version or official package of `MicrosoftCognitiveServicesSpeech`. 
Thanks for your kindly help very much!

**Comment by CheShengSu** [comment]
Finally I successfully uploaded my app to TestFlight!
I just add local package `MicrosoftCognitiveServicesSpeech` 1.19.0 , add this package to my target, and archive and upload to TestFlight.
Thanks for your help!

**Comment by jhakulin** [comment]
@CheShengSu Thanks for info. Did you use Swift package manager or Cocoapod? I am curious if there was some reason the upload did not work before ?

**Comment by CheShengSu** [comment]
I mainly use Cocopod in my App for other libraries, but for `MicrosoftCognitiveServicesSpeech` library, I manually add local package.
