### ISSUE TITLE
framework not found MicrosoftCognitiveServicesSpeech 1.19.0

### ISSUE THREAD

**Issue by CheShengSu** [Azure-Samples/cognitive-services-speech-sdk#1345]
**Describe the bug**
I can build App and run successfully. But when archiving, I get an error.

**To Reproduce**
1. set Podfile
```
platform :ios, '15.0'
target 'Test20211214' do
  use_frameworks!
  pod 'MicrosoftCognitiveServicesSpeech-iOS', '1.19.0'
end
```
2. Archive the project.

**Expected behavior**
Successfully archive.

**Version of the Cognitive Services Speech SDK**
MicrosoftCognitiveServicesSpeech-iOS, '1.19.0'

**Platform, Operating System, and Programming Language**
 - IDE: Xcode Version 13.1 (13A1030d)
 - Hardware: MacBook Pro (15-inch, 2018)
 - Programming language: Swift (SwiftUI)

**Additional context**

Showing Recent Messages
> Ld /Users/jasonsu/Library/Developer/Xcode/DerivedData/Test20211214-dvwjivtibflxniherebbravcmapl/Build/Intermediates.noindex/ArchiveIntermediates/Test20211214/InstallationBuildProductsLocation/Applications/Test20211214.app/Test20211214 normal (in target 'Test20211214' from project 'Test20211214')
>     cd /Users/jasonsu/Dropbox/myProgram/temp/Test20211214
>     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios15.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk -L/Users/jasonsu/Library/Developer/Xcode/DerivedData/Test20211214-dvwjivtibflxniherebbravcmapl/Build/Intermediates.noindex/ArchiveIntermediates/Test20211214/BuildProductsPath/Release-iphoneos -F/Users/jasonsu/Library/Developer/Xcode/DerivedData/Test20211214-dvwjivtibflxniherebbravcmapl/Build/Intermediates.noindex/ArchiveIntermediates/Test20211214/BuildProductsPath/Release-iphoneos -F/Users/jasonsu/Dropbox/myProgram/temp/Test20211214/Pods/MicrosoftCognitiveServicesSpeech-iOS -F/Users/jasonsu/Library/Developer/Xcode/DerivedData/Test20211214-dvwjivtibflxniherebbravcmapl/Build/Intermediates.noindex/ArchiveIntermediates/Test20211214/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/MicrosoftCognitiveServicesSpeech-iOS -filelist /Users/jasonsu/Library/Developer/Xcode/DerivedData/Test20211214-dvwjivtibflxniherebbravcmapl/Build/Intermediates.noindex/ArchiveIntermediates/Test20211214/IntermediateBuildFilesPath/Test20211214.build/Release-iphoneos/Test20211214.build/Objects-normal/arm64/Test20211214.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/jasonsu/Library/Developer/Xcode/DerivedData/Test20211214-dvwjivtibflxniherebbravcmapl/Build/Intermediates.noindex/ArchiveIntermediates/Test20211214/IntermediateBuildFilesPath/Test20211214.build/Release-iphoneos/Test20211214.build/Objects-normal/arm64/Test20211214_lto.o -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/jasonsu/Library/Developer/Xcode/DerivedData/Test20211214-dvwjivtibflxniherebbravcmapl/Build/Intermediates.noindex/ArchiveIntermediates/Test20211214/BuildProductsPath/Release-iphoneos -Xlinker -final_output -Xlinker /Applications/Test20211214.app/Test20211214 -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/jasonsu/Library/Developer/Xcode/DerivedData/Test20211214-dvwjivtibflxniherebbravcmapl/Build/Intermediates.noindex/ArchiveIntermediates/Test20211214/IntermediateBuildFilesPath/Test20211214.build/Release-iphoneos/Test20211214.build/Objects-normal/arm64/Test20211214.swiftmodule -framework MicrosoftCognitiveServicesSpeech -lsqlite3 -framework Pods_Test20211214 -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/jasonsu/Library/Developer/Xcode/DerivedData/Test20211214-dvwjivtibflxniherebbravcmapl/Build/Intermediates.noindex/ArchiveIntermediates/Test20211214/IntermediateBuildFilesPath/Test20211214.build/Release-iphoneos/Test20211214.build/Objects-normal/arm64/Test20211214_dependency_info.dat -o /Users/jasonsu/Library/Developer/Xcode/DerivedData/Test20211214-dvwjivtibflxniherebbravcmapl/Build/Intermediates.noindex/ArchiveIntermediates/Test20211214/InstallationBuildProductsLocation/Applications/Test20211214.app/Test20211214
> 
> ld: framework not found MicrosoftCognitiveServicesSpeech
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jhakulin** [comment]
@CheShengSu Did you apply the workaround for excluding armv7 architecture as described here: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1320#issuecomment-988836381 ?

**Comment by CheShengSu** [comment]
@jhakulin After I add 
`EXCLUDED_ARCHS[sdk=iphoneos*] = armv7`
to the file 
`MicrosoftCognitiveServicesSpeech-iOS.debug/release.xcconfig`, 
I can successfully archive. But when uploading to App Store Connect, I get the error same to 
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1344

**Comment by jhakulin** [comment]
closing this issue as based on my understanding we need to check only https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1344
