### ISSUE TITLE
Missing "Microsoft.CognitiveServices.Speech.core.dll" in Blazor WASM project (same as #930)

### ISSUE THREAD

**Issue by mkb13** [Azure-Samples/cognitive-services-speech-sdk#1349]
I am still experiencing issue #930 (reported in January 2021), with repro steps as outlined here: https://stackoverflow.com/questions/65761453/azure-speech-to-text-c-sdk-in-blazor-webasm-app-bug .

I am trying to use the Azure Cognitive Services - Text to Speech in a Blazor Webassembly app.  Here was the finding from trrwilson in response to #930:

"
Unfortunately, the core SDK (that .core.dll) is portable C++ code that doesn't yet target WASM. What you see is that blazor can resolve the pure .NET binding DLL (.csharp.dll) and make it work, but the magic that makes it possible for blazor to run .NET DLLs in WASM doesn't work for C++. When you copy the x86/x64 .core.dll, it still says "not found" because those are targeting the wrong architecture -- native code needs the explicit WASM target to work.

For this to happen, the SDK team needs to do work to add WASM as a compilation target for the core DLL. I'll ensure there's an item on our backlog to track it.
"

The recommended solution was to use the JavaScript version of the SDK.  I have spent many hours trying to get the JavaScript SDK working for my purpose and it is suboptimal -- it does not seem to have parity with the C# API in a couple of ways which I am about to file a separate issue about.

Has there been any update on this?  I would like to put in my vote for it to be revisited and wasn't sure how to do that other than filing the bug here again (I realize it's not technically a bug with the samples).

Thanks for your consideration.

**Comment by rhurey** [comment]
Thanks for checking in with us on this. I wish I had better news, but the end answer is still that we don't support it.

The more complete answer is also more nuanced. Over the last year we've been doing some work to separate out the non-portable pieces of the base C/C++ library, namely in the networking stack into something that could allow the emscripten websocket implementation to replace the existing non-portable networking code. But this hasn't been done with a concrete goal of "Have WASM working by..." leading me to not want to give false hope about imminency.

I'll look at the other issues and see if we can do some gap closing between C# and JS. That's usually something we can move quicker on.

**Comment by pankopon** [comment]
Closing the item as WASM is not a supported target and there is no plan to add support in the near future. Please raise new issues on JavaScript specific topics as appropriate.
