### ISSUE TITLE
TextToSpeech - JavaScript Samples - Include enumerating available languages/voices

### ISSUE THREAD

**Issue by mkb13** [Azure-Samples/cognitive-services-speech-sdk#1350]
**Is your feature request related to a problem? Please describe.**
I am not finding a way to enumerate available languages/voices for speech synthesis with the JavaScript SDK, and it doesn't appear to be covered in the sample.  In C#, it's on the SpeechSynthesizer class ("GetVoicesAsync" -- https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechsynthesizer?view=azure-dotnet) but I don't see an equivalent in JavaScript (https://docs.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/speechsynthesizer?view=azure-node-latest).  

**Describe the solution you'd like**
If there is a way to do this it would be great if you could add it to the sample.  If there is no way to do it my request is that this functionality be added to the JavaScript SDK for parity with the C# API (and also something I would expect for API completeness -- hopefully it's already there and I'm just missing it).

**Describe alternatives you've considered**
- One alternative is to hard-code the list from https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support which seems less than ideal.
- The other option is to use the C# API, but I am calling this from a Blazor Webassembly project and using the C# SDK in that scenario is currently broken (see #903).  I prefer this option but can't use it.

**Additional context**
I have also submitted a question on the forum (https://docs.microsoft.com/en-us/answers/questions/663637/how-to-enumerate-voices-in-azure-text-to-speech-in.html) but this approach was not fruitful the last time I asked a question about the JavaScript SDK.  They just pointed me to the sample here where my question was also not answered.

**Comment by rhurey** [comment]
GetVoicesAsync is a gap between the C# and JS implementations. @glharper and I discussed this today and this is going to go into his backlog of tasks.

In the meantime, there is a REST API that will return the supported language list. It's documented [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/rest-text-to-speech#get-a-list-of-voices).

**Comment by glecaros** [comment]
hi @mkb13 , were you able to use the workaround suggested by @rhurey?. We have internally a work item to add this feature to JS so you should be able to see it in a later version.

**Comment by mkb13** [comment]
> hi @mkb13 , were you able to use the workaround suggested by @rhurey?. We have internally a work item to add this feature to JS so you should be able to see it in a later version.

Thanks to both, yes, it worked.  Thanks for considering adding it to JS.

**Comment by pankopon** [comment]
Closing the issue since GetVoicesAsync API has been added.

**Comment by dargilco** [comment]
From the [1.20 release notes](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/releasenotes?tabs=speech-sdk):
JavaScript: Added getVoicesAsync() API to SpeechSynthesizer to retrieve the list of supported synthesis voices (GitHub issue 1350)
