### ISSUE TITLE
TextToSpeech - JavaScript - QuickStart "Get result as an in-memory stream" section appears to be wrong

### ISSUE THREAD

**Issue by mkb13** [Azure-Samples/cognitive-services-speech-sdk#1351]
**Describe the bug**
The JavaScript version of the QuickStart (https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-text-to-speech?tabs=script%2Cwindowsinstall&pivots=programming-language-browserjs) appears to be incomplete/wrong in the "Get result as an in-memory stream" section and this section is not covered in the sample.

**To Reproduce**

Call the following function from the sample, using a working key and location, similar to the browser sample here (cognitive-services-speech-sdk/quickstart/javascript/browser/):

```
function synthesizeSpeech() {
    const speechConfig = sdk.SpeechConfig.fromSubscription("<paste-your-speech-key-here>", "<paste-your-speech-location/region-here>");
    const synthesizer = new sdk.SpeechSynthesizer(speechConfig);

    synthesizer.speakTextAsync(
        "Getting the response as an in-memory stream.",
        result => {
            synthesizer.close();
            return result.audioData;
        },
        error => {
            console.log(error);
            synthesizer.close();
        });
}

```
**Expected behavior**

I expect "return result.audioData" to actually return something somewhere but it does not.  I don't even think this callback returns anything (if I am reading the docs correctly -- https://docs.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/speechsynthesizer?view=azure-node-latest#speakTextAsync_string___e__SpeechSynthesisResult_____void___e__string_____void__AudioOutputStream___PushAudioOutputStreamCallback___PathLike_ -- it returns void).  Since I'm trying to do JavaScript/C# interop -- calling this function from C# and needing to get the bytes back -- I had to do a convoluted callback method to get result.audioData out, and I'm not sure I did it the desired way.  

I also expect the audio NOT to play through the default speakers, but it does.  (To prevent this I had to pass null as the second parameter to the SpeechSynthesizer constructor.)

**Version of the Cognitive Services Speech SDK**
JavaScript, 1.19.0 -- I followed the instructions to download the SDK from https://aka.ms/csspeech/jsbrowserpackage and copied microsoft.cognitiveservices.speech.sdk.bundle.js to my project accessible from my HTML.  I also had to copy microsoft.cognitiveservices.speech.sdk.bundle.js.map to avoid errors.

**Platform, Operating System, and Programming Language**
I'm running Windows and am writing a Blazor Webassembly app.  Due to issue #903 I am not able to use the C# SDK (which I would prefer) so I am trying to use the workaround of JavaScript.  I'm using Microsoft Edge as my browser.

**Additional context**
I want to get the bytes out rather than play directly to the speaker because I want to be able to store them later for offline use, which is why I am using Blazor Webassembly.  My app uses the HTML5 <audio> element, setting the source to a URL beginning with "data:audio/mpeg;base64," followed by the base64-encoded string made from the result.audioData ArrayBuffer.  (I still want to save my data as a byte array though, and just base64-encode it right before playing it -- or even not do that if there's another way to play it.)  It would be great if the sample included this way of playing the audio -- first getting it as a stream/byte array and then playing it in the browser.

I already posted this in the "Q&A" forum (https://docs.microsoft.com/en-us/answers/questions/648016/trouble-with-javascript-sample-in-text-to-speech-q.html) but was directed to the sample, which doesn't currently help, hence my post here.

**Comment by rhurey** [comment]
First, thanks for contacting us about this.

Bluntly, that example isn't right, and the document text needs some updates also.

The function should look like:
```
function synthesizeSpeech() {
    const speechConfig = sdk.SpeechConfig.fromSubscription("<paste-your-speech-key-here>", "<paste-your-speech-location/region-here>");
    const synthesizer = new sdk.SpeechSynthesizer(speechConfig, null);

    synthesizer.speakTextAsync(
        "Getting the response as an in-memory stream.",
        result => {
            synthesizer.close();
            
            // At this point, result.audioData contains the full synthesis for the specified text.
        },
        error => {
            console.log(error);
            synthesizer.close();
        });
}
```
To have the synthesizer not speak, you can pass null for the 2nd parameter, as you found out. This will initialize it with no audio output source, and the result object given in the callback will have the synthized data in it.

But rather than use the callback to get at the data using one of the output streams may be more efficient. Are you looking to have the synthesizeSpeech method be blocking and return the byte array?

**Comment by mkb13** [comment]
Thanks very much for the answer.  I don't particularly want it to be blocking -- I'm calling it from C# and ideally would like to have a way to call some function (a wrapper on synthesizeSpeech?) asynchronously and get back the bytes.  (This is in the context of a Blazor Webassembly.  I would prefer to use the C# API, but it doesn't work because something hasn't been compiled for the necessary target per issue #930.)  I'm just not that familiar with JavaScript -- how do I get it from an output stream?  (Maybe that should be the example instead... doesn't seem that great to be like "here, in the middle of this function you can do all your work.")  

Unfortunately I also had to base64-encode the byte array as a string in order to get past the C#-JS interop, which is definitely not efficient, but that may be beyond the scope of this question.  (I see this: https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/6.0/byte-array-interop about .NET 6.0 but I don't have that yet.  I'm also not sure what the previous -- i.e. current -- behavior was supposed to be -- I'm converting to base64-encoding myself in my JavaScript function.)

I see "AudioOutputStream" and "PushAudioOutputStreamCallback" in the docs here https://docs.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/speechsynthesizer?view=azure-node-latest#speakTextAsync_string___e__SpeechSynthesisResult_____void___e__string_____void__AudioOutputStream___PushAudioOutputStreamCallback___PathLike_ but to be honest I didn't even try to figure out what that meant -- I guess I kind of assumed it didn't work since I would have expected it to be in the example for that exact use case if it did.  Also, since I'm doing C# interop I'm not sure if there's a way to pass that back.

Thanks for any suggestions!

**Comment by pankopon** [comment]
@mkb13 I found the following (test) examples on fromStreamOutput with push and pull streams:

synthesis to push audio output stream
https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/bab74ae636157ba28b622ea8aa27fb6852641f22/tests/SpeechSynthesisTests.ts#L670

synthesis to pull audio output stream
https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/bab74ae636157ba28b622ea8aa27fb6852641f22/tests/SpeechSynthesisTests.ts#L618

synthesis to pull audio output stream 2
https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/bab74ae636157ba28b622ea8aa27fb6852641f22/tests/SpeechSynthesisTests.ts#L645

@rhurey @glharper in case there are any other/better samples...

**Comment by pankopon** [comment]
Closed as examples were provided and no further comments received since January. Please open a new issue if more support is needed.
