### ISSUE TITLE
java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V

### ISSUE THREAD

**Issue by lst94** [Azure-Samples/cognitive-services-speech-sdk#1352]
**Describe the bug**
I'm using client-sdk-1.19.0.jar in my project,but it doesn't effect on Centos7.  I have set the environment variable according to this link "https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7". 
When I use TTS, it shows the following info: 
java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V
org.springframework.web.servlet.DispatcherServlet.triggerAfterCompletionWithError(DispatcherServlet.java:1302)

**Version of the Cognitive Services Speech SDK**
client-sdk-1.19.0.jar

**Platform, Operating System, and Programming Language**
 - OS: Linux Centos7
 - Hardware: x64
 - Programming language:  Java
 - Browser: Chrome

This can be programed normally on Windows10, but not Centos7. Is it a bug? Or Is there anything wrong with my setting on Centos7?

**Comment by lst94** [comment]
And another info shows:   java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V
	org.springframework.web.servlet.DispatcherServlet.triggerAfterCompletionWithError(DispatcherServlet.java:1302)

**Comment by jhakulin** [comment]
@lst94 Thanks for the report. We have changed the package configuration in 1.19.0 for CentOS7. Could you please let us know have you also done all the prerequisite steps like updated C/C++ compiler and runtime libraries as described in https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7 ?

**Comment by lst94** [comment]
@jhakulin Yes,I have done all steps before, but it still doesn't work.

>  gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-pc-linux-gnu/7.5.0/lto-wrapper
目标：x86_64-pc-linux-gnu
配置为：../gcc-7.5.0/configure --enable-languages=c,c++ --disable-bootstrap --disable-multilib --prefix=/usr/local
线程模型：posix
gcc 版本 7.5.0 (GCC)

**Comment by jhakulin** [comment]
@lst94 I checked the instructions using WSL version of CentOS7 and noticed there is an error in the `C/C++ compiler and runtime libraries` instructions download path, the correct one is:

`curl https://ftp.gnu.org/gnu/gcc/gcc-7.5.0/gcc-7.5.0.tar.gz -O`
`tar -xf gcc-7.5.0.tar.gz`

Did you notice the same and made the required changes? 

After that runtime libraries gets installed in `/usr/local/lib/lib64` directory and set the following environment variable needed for Java:
`export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH` 

After that I made basic testing using https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/java/jre/from-microphone quickstart and run it in shell under the src directory of that sample
`java -cp "../../client-sdk-1.19.0.jar:" speechsdk.quickstart.Main`. This worked without problems on CentOS7 WSL.

Are you seeing problems if you run that sample ?

What kind of application you are using ?

**Comment by lst94** [comment]
@I have noticed that error, so I change the link ".bz2" to ".gz". I have set the LD_LIBRARY_PATH. Here is my setting:
`echo $LD_LIBRARY_PATH`
`/usr/local/SpeechSDK-Linux-1.19.0/lib/x64:/usr/local/lib64:`
I haven't tried that sample,just test TTS in my project.

**Comment by jhakulin** [comment]
@lst94 For TTS, could you please run https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/java/jre/text-to-speech quickstart and let us know if you see the issue ?

Also could you please answer, what kind of application project you have ?

**Comment by lst94** [comment]
@jhakulin I'll test tomorrow. JAVA WEB (SSM)

**Comment by jhakulin** [comment]
@lst94 For Java development, you do not need to set /usr/local/SpeechSDK-Linux-1.19.0/lib/x64 in your LD_LIBRARY_PATH, not sure if that would cause any issue, but please also try removing it.

**Comment by lst94** [comment]
@jhakulin Still the same,I'll test that sample tomorrow.

**Comment by jhakulin** [comment]
@lst94 Sure, thanks for the help!

**Comment by lst94** [comment]
@jhakulin  It seems to be another question.
`Exception in thread "main" java.lang.NoClassDefFoundError: com/microsoft/cognitiveservices/speech/SpeechConfig
        at Main.main(Main.java:25)
Caused by: java.lang.ClassNotFoundException: com.microsoft.cognitiveservices.speech.SpeechConfig
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)`

**Comment by jhakulin** [comment]
@lst94 Please be a bit more specific on the steps you did ? Did you follow quickstart steps ?

**Comment by lst94** [comment]
@jhakulin I have done all steps except Eclipse. Java8 and gcc7.5.0 and library path are all ready.

**Comment by jhakulin** [comment]
@lst94 Unfortunately I do not know what are the steps you have done. Regarding your original problem if you want to run Speech SDK on browser/web environment, we recommend you to use Speech SDK for Javascript. There can be limitations with speech SDK for Java when working with web apps. Have you used Speech SDK for Java earlier or is this first time use with 1.19.0 ?

**Comment by lst94** [comment]
@jhakulin It's my first time to use the SDK 1.19.0, but it's successful on Windows 10.

**Comment by jhakulin** [comment]
@lst94 Running Speech SDK in browser/web app environment, I recommend you to take a look for Speech SDK for Javascript examples https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-text-to-speech?tabs=script%2Cwindowsinstall&pivots=programming-language-browserjs. Let us know if this would help you further.

**Comment by lst94** [comment]
@jhakulin  OK,I'll have a try.Thanks.

**Comment by lst94** [comment]
@jhakulin Speech SDK for Javascript is helpful on Centos7, thanks a lot!

**Comment by jhakulin** [comment]
Closing as answer/resolution provided
