### ISSUE TITLE
RuntimeError: Exception with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED)

### ISSUE THREAD

**Issue by SyedHamza0196** [Azure-Samples/cognitive-services-speech-sdk#1353]
**Describe the bug**
I am trying to deploy a streamlit app using free azure cognitive services speech

It crashes on line: speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)

File "/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/speech.py", line 806, in __init__
File "/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/speech.py", line 869, in _get_impl
RuntimeError: Exception with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED)

**Expected behavior**
By passing the uploaded_file.name in audio_config it should create the config but error occurs in SpeechRecognizer

**Version of the Cognitive Services Speech SDK**
azure-cognitiveservices-speech==1.19.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - x86
 - Programming language: Python
 - Browser [Chrome, Firefox, Opera, Edge]

**Additional context**
`RuntimeError: Exception with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED) 
[CALL STACK BEGIN] 
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x164418) [0x7f102f0da418]
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x166a99) [0x7f102f0dca99] /usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x163cdc) [0x7f102f0d9cdc] 
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x11fb96) [0x7f102f095b96] 
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x11fb96) [0x7f102f095b96] 
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x12ca59) [0x7f102f0a2a59] /usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x120a31) [0x7f102f096a31] 
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1b3a63) [0x7f102f129a63] 
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x11fa7b) [0x7f102f095a7b] 
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1b2f8b) [0x7f102f128f8b] 
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(recognizer_create_speech_recognizer_from_config+0xf2) [0x7f102f02cf12] 
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/_speech_py_impl.so(+0x123c69) [0x7f102f72dc69] 
/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/_speech_py_impl.so(+0x7f538) [0x7f102f689538] 
/usr/bin/python3(_PyMethodDef_RawFastCallKeywords+0x1d7) [0x559385713437] 
/usr/bin/python3(_PyCFunction_FastCallKeywords+0x20) [0x559385713240] 
/usr/bin/python3(_PyEval_EvalFrameDefault+0x4c13) [0x5593857870f3] 
/usr/bin/python3(_PyFunction_FastCallKeywords+0x10a) [0x559385714afa] 
[CALL STACK END]`

`Traceback:
File "/usr/local/lib/python3.7/dist-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
File "/content/speech_to_text_app.py", line 35, in <module>
    from_file(uploaded_file.name)
File "/content/speech_to_text_app.py", line 21, in from_file
    speech_config=speech_config, audio_config=audio_input)
File "/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/speech.py", line 806, in __init__
    self._impl = self._get_impl(impl.SpeechRecognizer, speech_config, audio_config, language, source_language_config, auto_detect_source_language_config)
File "/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/speech.py", line 869, in _get_impl
    return reco_type._from_config(speech_config._impl,  audio_config._impl)`

**Comment by rhurey** [comment]
A quick thought, where is the file?  Local to the script, on a remote machine?

The SDK would need the file to be local.

**Comment by glharper** [comment]
Pending close for inactivity
