### ISSUE TITLE
Speech Recognizer - Concurrent Request limit

### ISSUE THREAD

**Issue by trydis** [Azure-Samples/cognitive-services-speech-sdk#1354]
How is `Concurrent Request limit` counted in relation to continuous recognition?

- Is it incremented when calling `StartContinuousRecognitionAsync` and decrement by calling `StopContinuousRecognitionAsync`? 

- Or do we actually need to keep track of data written to the input stream and the `Recogniz*` events?

Ran a test with 300 concurrent sessions using 3 subscriptions and got some `Error code: TooManyRequests, Error details: The number of parallel requests exceeded the number of allowed concurrent transcriptions.` errors.

I guess it's because it's scaling up. I've assumed the counting was related to `StartContinuousRecognitionAsync/StopContinuousRecognitionAsync`, just want to make sure my assumption is correct (or not).

**Comment by rhurey** [comment]
The limits are evaluated at connection time when a recognition request begins. You don't need to keep track of the events returned or the amount of data sent.

https://docs.microsoft.com/azure/cognitive-services/speech-service/speech-services-quotas-and-limits#detailed-description-quota-adjustment-and-best-practices has some more information and best practices on ramping up test loads.

**Comment by trydis** [comment]
Thanks, that's the answer i hoped for (and expected) 👍

Yes, i've read that info, thanks for mentioning it. The wording is a bit confusing, since it's focusing more on request/response workloads as opposed to continuous data streams.
