### ISSUE TITLE
VerificationEnroll function does not return phrasesList in NET 6.0

### ISSUE THREAD

**Issue by djimmo** [Azure-Samples/cognitive-services-speech-sdk#1356]
**Describe the bug**
Hi,

I am enrolled in the Speaker Recognition capability and very eager to try out this functionality. However when I try to compile the example method VerificationEnroll I get the following error in Visual Studio for Mac 2022 Preview:

![Screenshot 2021-12-17 at 11 01 22](https://user-images.githubusercontent.com/5882470/146555971-c875a0d8-31e2-4ec9-95b2-45e282338111.png)

If I change phraseResult into a normal variable within the function scope, the code compiles but crashes on the "Speak the passphrase" console printout since phraseResult.Phrases does not exist.

I get these results for client, profile and phrasesResult

client -> {"Properties":{},"IsDisposed":false}
profile -> {"Id":"","Type":2,"IsDisposed":false}
phrasesResult -> {"ResultId":"DC8162328FA142ED85EFF0265A8D7672","Reason":1,"Phrases":null,"Properties":{}}

What am I doing wrong?

regards,
Djim

**To Reproduce**
1. Use the VerificationEnroll example from the Getting Started Documentation
2. Run the code

**Expected behavior**
I expect the phrasesList to return phrases so they can be used to start enrolling a speaker profile

**Version of the Cognitive Services Speech SDK**
Microsoft.CognitiveServices.Speech 1.19.0

**Platform, Operating System, and Programming Language**
 - OS: macOS Monterey 12.1
 - Hardware: x64
 - Programming language: C# .NET 6.0
 - IDE: Visual Studio for Mac 17.0 Preview

**Comment by rhurey** [comment]
Well, I'll have to apologize for the QuickStart doc being wrong. The VoiceProfilePhraseResult doesn't implement IDisposable and can't be in a using statement.

Past that, the retrieval request was canceled (Reason:1 where ResultReason.Canceled = 1)

You can get a more detailed reason for the cancelation with code like:
```
?VoiceProfilePhraseCancellationDetails.FromResult(phraseResult)
{Reason:Error ErrorDetails:<Authentication error (401). Please check subscription information and region name.>}
    ErrorCode: AuthenticationFailure
    ErrorDetails: "Authentication error (401). Please check subscription information and region name."
    Reason: Error
    voiceProfileEnrollmentResult: {ResultId:3aa7b736135b472691d6b5d16840c38a Reason:Canceled Recognized Json:{"error":{"code":"401","message": "The Pass Phrases Operation under Speaker Verification is not supported with the current subscription key and pricing tier CognitiveServices.S0."}}}
```
(From the VS immediate window)

Which leads to me a guess at why the request may have been canceled. Speaker Recognition is gated service that requires prior approval to use. The details for this can be found [here.](https://docs.microsoft.com/en-us/legal/cognitive-services/speech-service/speaker-recognition/limited-access-speaker-recognition)

**Comment by pankopon** [comment]
Closing the item since the QuickStart doc has been corrected and no further details received. Please open a new issue if more support is needed.
