### ISSUE TITLE
can not get VoiceSignature of ja-JP

### ISSUE THREAD

**Issue by jian-sun** [Azure-Samples/cognitive-services-speech-sdk#1357]
`async function createProfile(profile) {
    let form = new formData();
    form.append('file', fs.createReadStream(profile));
    let headers = form.getHeaders();
    headers['Ocp-Apim-Subscription-Key'] = subscriptionKey;
    headers['language'] = 'ja-jp';
 
    let url = "https://signature.eastasia.cts.speech.microsoft.com/api/v1/Signature/GenerateVoiceSignatureFromFormData?enableTranscription=true&language=ja-JP";

    try {
    let response = await axios.post(url, form, { headers: headers,timeout:300000});
    
    // get signature from response, serialize to json string
    return JSON.stringify(response.data.Signature);
    } catch(e) {
        console.log(e)
    }
}`

when I use language=ja-JP, 500(500 Internal Server Error) was returned from the result of restful api
when I use language=en-us, I can get the VoiceSignature of voice

Does the api not support jananese?

**Comment by glharper** [comment]
@jian-sun Thank you for reporting this issue. There is a fix on the way, but to unblock you, setting "enableTranscription=False" should create a Japanese voice signature correctly.

**Comment by glharper** [comment]
@jian-sun This API is now patched, and japanese signatures with enableTranscription=true should work. Thanks again, closing this issue.
