### ISSUE TITLE
Resource warning with python swagger client

### ISSUE THREAD

**Issue by Nolent** [Azure-Samples/cognitive-services-speech-sdk#1359]
I have a lot of ResourceWarning when i'm using th swagger client

```
Exception ignored in: <function _SelectorTransport.__del__ at 0x7f793bbaeaf0>
Traceback (most recent call last):
File "/usr/lib/python3.9/asyncio/selector_events.py", line 704, in __del__
     _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
ResourceWarning: unclosed transport <_SelectorSocketTransport fd=20>
Exception ignored in: <socket.socket fd=20, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('my_address'), raddr=('52.239.134.100', 443)>
```
Is there a way to close them properly ?

**Comment by chlandsi** [comment]
Hi, the autogenerated swagger client uses `urllib3` under the hood and we are not aware of any related issues. This client doesn't use asyncio, so the problem might be related to the calling code. Maybe also check the issues for the client generator https://github.com/swagger-api/swagger-codegen?

**Comment by Nolent** [comment]
These errors are coming from `azure-core` lib and not from here
