### ISSUE TITLE
Azure text-to-speech is not accessable in Windows 2012 r2 (again !!!)

### ISSUE THREAD

**Issue by sprgchma** [Azure-Samples/cognitive-services-speech-sdk#1362]
1. The full description of bug is in [issue #811](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/811)
2. It was reemerged after a year just before the holidays season
3. Also for other developers, just be prepared. If you choose Azure service - you will be that unlucky person who spend the Christmas implementing workaround for the bug from Microsoft.

**Comment by pestevao** [comment]
Same here!

**Comment by pankopon** [comment]
@yulin-li Are you aware of any service issues related to this?

**Comment by yulin-li** [comment]
Sorry for the inconvenience, this is a service regression introduced recently. Service team is working on fixing. We will update here when it finished.

**Comment by yulin-li** [comment]
related https://github.com/Azure-Samples/Cognitive-Speech-TTS/issues/221

**Comment by yulin-li** [comment]
This bug were fixed and deployed.
