### ISSUE TITLE
Speech Recognizer - File Recordings with pauses are truncated at the First Pause.

### ISSUE THREAD

**Issue by MikeHannegan** [Azure-Samples/cognitive-services-speech-sdk#1365]
**Describe the bug**
We have a voice processing platform and we want to be able to record responses in a .wav file and transcribe the response and store the text.  If there is silence of over 1 second in the .wav file, the recognizer stops the transcription.  I will attach 2 files - one that has long pauses and will not transcribe properly and a file with shorter pauses with the same verbiage that will transcribe properly.

**To Reproduce**
1. Use the code below to send the files into the recognizer
2. Review the results.
        /// <summary>
        /// Transcribes text from a PCM audio WAV file asynchronously.
        /// </summary>
        /// <param name="languageCode">Language used when recording,</param>
        /// <param name="waveFilePath">Fully qualified path and file name of the audio file.</param>
        /// <returns></returns>
        public async Task<string> TextFromPcmFileAsync(string languageCode, string waveFilePath)
        {
            SpeechConfig speechConfig = SpeechConfig.FromSubscription(_SubscriptionKey, _Location);

            var audioConfig = AudioConfig.FromWavFileInput(waveFilePath);
            var recognizer = new SpeechRecognizer(speechConfig, languageCode, audioConfig);

            var result = await recognizer.RecognizeOnceAsync();

            return result.Text;
        }

**Expected behavior**
The output of both file transcriptions should be "Thank you for calling the City of Portland Utility Billing Department to make a payment. Press 1 to hear your current account information. Press 2 to speak to a representative Press 0."

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using. NuGet Microsoft Cocnitive Services Speech Version 1.19.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 10, Windows Server 2019
 - Hardware - x64, 
 - Programming language: C# Visual Studio 2019

**Additional context**
 - Any other additional information
[MSCS-LongPausesWaveFile.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/7817180/MSCS-LongPausesWaveFile.log)
[MSCS-ShortPausesWaveFile.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/7817181/MSCS-ShortPausesWaveFile.log)
[SampleRecordingFiles.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/7817234/SampleRecordingFiles.zip)

**Comment by glecaros** [comment]
Hi @MikeHannegan ,

Thanks for reaching out! RecognizeOnce is meant to segment after a pause in the input speech (around 500ms), to transcribe multi utterance files I would recommend using StartContinuousRecognition, otherwise you would need to call RecognizeOnce multiple times (until you hit EOF)

Thanks

**Comment by pankopon** [comment]
To add, there's a Windows C# example of continuous speech recognition from a file:

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/02ecde7edddbd27514e8a8ef4d5c0dfdfbddd134/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L193

Closing the item as answered, please open a new issue if more support is needed.
