### ISSUE TITLE
Speaker capture exception

### ISSUE THREAD

**Issue by QLinkAll** [Azure-Samples/cognitive-services-speech-sdk#1369]
When I use speech translation, I set up to capture sound from the speaker. The sound device uses fromdefaultspeakeroutput(). But what was captured was the sound of the microphone.

**Comment by glharper** [comment]
@QLinkAll Thanks for using Speech SDK, and writing this issue up. Could you describe your scenario in more detail, and provide sample code?

**Comment by pankopon** [comment]
@QLinkAll AudioConfig methods `From*Output` are used with speech synthesis (text to speech) to specify the output for synthesized audio (see https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/583).
In your use case you would need to get a handle/copy of the audio stream playing to the speaker and copy audio from that to the SDK input by using e.g. a push stream and `FromStreamInput`. One push stream usage example (in C#, others are available as well): https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/02ecde7edddbd27514e8a8ef4d5c0dfdfbddd134/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L506).

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
