### ISSUE TITLE
Problem on Node sample

### ISSUE THREAD

**Issue by samuelcalegari** [Azure-Samples/cognitive-services-speech-sdk#137]
I have tested this example
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/node

the speech recognition works on of an "helloworld wav file" but not on another file (files are in zip bellow)

I have this error :

Reason: NoMatch NoMatchReason: InitialSilenceTimeout

on other file the recognition is partial (not all sentences are recognized)

[speech2.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/2759145/speech2.zip)

thanks !

**Comment by rhurey** [comment]
I could use some clarification on what results you're seeing from the result-16-mono2.wav file.

With recognizeOnceAsync I'd expect recognition to happen up to the first detected phrase which is detected by pausing in the speech being recognized.

I don't speak what I assume is French, so its difficult for me to tell how well that's happening in this sample.

What I'm getting for the first phrase is:
(recognized)  Reason: RecognizedSpeech Text: L'utilisation faite des ordinateurs il faut remonter en fait après-guerre un et de remonter sur travaux de Roberto USA dans les années 50 pour s' apercevoir que cette personne qui interroge beaucoup sur l'apport de du traitement de l'information que peuvent ?

To get the rest of the file, you can keep calling recognizeOnceAsync() or use continuous recognition with startContinuousRecognitionAsync.

When are you getting the initial silence timeout?

**Comment by wolfma61** [comment]
sounds like you used RecognizeOnce, which limits the length of the recognition to about 15 seconds - This might give you the silence timeout or similar results because there was no speech in these 15 seconds in your audio file.

ContinuousRecognition has not the length restriction. You might receive results like silence timeout during the recognition, but the service 'keeps listening', and as speech is recognized, you are receiving the recognition results

thx
Wolfgang

**Comment by hungltph03955** [comment]
@samuelcalegari 

I am having the same problem as you. I see you have solved them. However, when I tried your method, I still got an InitialSilenceTimeout error. Can you give me the details of your method ?
Thank you so much.

**Comment by samuelcalegari** [comment]
> @samuelcalegari
> 
> I am having the same problem as you. I see you have solved them. However, when I tried your method, I still got an InitialSilenceTimeout error. Can you give me the details of your method ?
> Thank you so much.

Do you use recognizer.startContinuousRecognitionAsync() function ?
