### ISSUE TITLE
files from local storage not pulled and not transcribed - error Timeout when downloading recordings URI.

### ISSUE THREAD

**Issue by vovanb** [Azure-Samples/cognitive-services-speech-sdk#1370]
**Describe the bug**
the local recording available to public internet using ngrok. Recently the files are not produced by Speech To Text API.
In ngrok we see subsequently HEAD queries:

```
HEAD /batchrecordings/rcd_2b6297790426000d_220c10de.tmp_stereo.wav HTTP/1.1
Host: localhost
X-Forwarded-For: 51.104.27.80
X-Forwarded-Proto: https
X-Original-Host: efcf-77-137-66-120.ngrok.io
```

 In API we see progress on recording , but after 20 min we receive  Timeout when downloading recordings URI.:

```
1/9/2022 3:38:45 PM Deleting all existing completed transcriptions.
1/9/2022 3:38:49 PM Created transcription https://uksouth.api.cognitive.microsoft.com/speechtotext/v3.0/transcriptions/bbb43625-5d9c-4a3f-965f-59c3c39f7e2b
1/9/2022 3:38:49 PM Checking status.
1/9/2022 3:38:49 PM Transcriptions status: 0 completed, 0 running, 1 not started yet
1/9/2022 3:39:49 PM Transcriptions status: 0 completed, 1 running, 0 not started yet
1/9/2022 3:40:49 PM Transcriptions status: 0 completed, 1 running, 0 not started yet
1/9/2022 3:41:49 PM Transcriptions status: 0 completed, 1 running, 0 not started yet
1/9/2022 3:42:50 PM Transcriptions status: 0 completed, 1 running, 0 not started yet
1/9/2022 3:43:50 PM Transcriptions status: 0 completed, 1 running, 0 not started yet
1/9/2022 3:44:50 PM Transcriptions status: 0 completed, 1 running, 0 not started yet
1/9/2022 3:45:50 PM Transcriptions status: 0 completed, 1 running, 0 not started yet
1/9/2022 3:46:50 PM Transcriptions status: 0 completed, 1 running, 0 not started yet
1/9/2022 3:47:50 PM Transcriptions status: 0 completed, 1 running, 0 not started yet
1/9/2022 3:48:50 PM Transcriptions status: 0 completed, 1 running, 0 not started yet
1/9/2022 3:49:50 PM Transcriptions status: 0 completed, 1 running, 0 not started yet
1/9/2022 3:50:50 PM Transcriptions status: 0 completed, 1 running, 0 not started yet
1/9/2022 3:51:50 PM Transcriptions status: 0 completed, 1 running, 0 not started yet
1/9/2022 3:52:51 PM Transcriptions status: 0 completed, 1 running, 0 not started yet
1/9/2022 3:53:51 PM Transcriptions status: 0 completed, 1 running, 0 not started yet
1/9/2022 3:54:51 PM Transcriptions status: 0 completed, 1 running, 0 not started yet
1/9/2022 3:58:00 PM Transcription failed. Status: Timeout when downloading recordings URI.
1/9/2022 3:58:00 PM Transcriptions status: 1 completed, 0 running, 0 not started yet
Press any key...

```

**To Reproduce**

1.using default example https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/31abbe1e4b6e3a0bc7d60a72fd3802cb928654dc/samples/batch/csharp and assign to use recording from local file system
 new Uri("https://efcf-77-137-66-120.ngrok.io/batchrecordings/rcd_2b6297790426000d_220c10de.tmp_stereo.wav")

2.put file https://batchrecordingstorage.file.core.windows.net/fileshare/rcd_2b6297790426000d_220c10de.tmp_stereo.wav?sv=2020-10-02&st=2022-01-09T09%3A46%3A45Z&se=2022-01-10T09%3A46%3A45Z&sr=f&sp=r&sig=C9qwxFouy7QfBbGTQ9GsazWcK%2BhUFLmjIMpeDyFEbu0%3D into local system . Create Virtual folder batchRecordings pointing to folder with file. Run Ngrok to local IIS ngrok http -host-header=rewrite localhost:80

**Expected behavior**
file fetched by speech API and return success transcription . Error is not clear, since response for HEAD query sent to Azure properly. What is 20 min timeout , where it configured?
```
HTTP/1.1 200 OK
Content-Length: 3872046
Content-Type: audio/wav
Last-Modified: Sun, 05 Dec 2021 15:16:42 GMT
Accept-Ranges: bytes
ETag: "53b4b21bebe9d71:0"
Server: Microsoft-IIS/10.0
X-Powered-By: ASP.NET
Date: Sun, 09 Jan 2022 12:43:49 GMT
```

**Version of the Cognitive Services Speech SDK**
3.0

**Platform, Operating System, and Programming Language**
 Windows, C#, X64

**Additional context**
manual fetch for transcription returns 404 Not Found  why?
GET https://uksouth.api.cognitive.microsoft.com/speechtotext/v3.0/transcriptions/8b685e03-651a-46dd-805e-b9f3381493f0/files HTTP/1.1
Host: uksouth.api.cognitive.microsoft.com
Ocp-Apim-Subscription-Key: •••••••••••••••••••••••••••• 
same file using SAS working fine.

**Comment by zhouwangzw** [comment]
@vovanb Our service logs shows that after the transcription service requested HTTP Headers successfully, it tried to use HTTP GET to download audio from the audio source URL, but got the timeout error (no audio has been downloaded before timeout).  Multiple retries indicated the same error. The request failed after exceeding retry limit. And it seems that you deleted the request afterwards. 

Have you tried to use a audio source which is located in Azure blob storage with SAS? Since we have not seen the same error for other customers around the same time, I suspect whether this error could be due to network or the audio server issue related to this audio source?

Thanks,

**Comment by vovanb** [comment]
@zhouwangzw thanks for prompt response. How I can access service logs? Note in our ngrok session there is no GET request at all and HEAD request we responded properly.
Yes using SAS sharing it is working fine. 
I did test with our DMZ server (without ngrok) and it is also has problem:
Below recording file is available from internet:
https://ccsp.ei.eilabonline.biz/scshare/rcd_2b6297790426000d_220c10de.tmp_stereo.wav
With test for this file, I did not get response status (client.GetTranscriptionsAsync ) for result at all:
```
1/10/2022 1:26:02 PM Deleting all existing completed transcriptions.
1/10/2022 1:26:15 PM Created transcription https://uksouth.api.cognitive.microsoft.com/speechtotext/v3.0/transcriptions/1251738d-48e0-4658-8eee-500c0a16215f
1/10/2022 1:26:15 PM Checking status.
1/10/2022 1:26:20 PM Transcriptions status: 0 completed, 1 running, 0 not started yet
1/10/2022 1:27:34 PM Transcriptions status: 0 completed, 0 running, 0 not started yet
1/10/2022 1:28:42 PM Transcriptions status: 0 completed, 0 running, 0 not started yet
```

**Comment by zhouwangzw** [comment]
For this request https://uksouth.api.cognitive.microsoft.com/speechtotext/v3.0/transcriptions/1251738d-48e0-4658-8eee-500c0a16215f, the transcription did succeeded at 2022-01-10T11:26:58.809Z UTC time, but our service received a delete request at 2022-01-10T11:27:19.972Z UTC, so that the request has been removed.

**Comment by vovanb** [comment]
the status is not returned neither for DMZ nor for SAS transcription. again I am using same tester API as before. If exist way to access transcription?

**Comment by zhouwangzw** [comment]
Did you make "DELETE" request to delete transcription request? We see the DELETE request in our logs, which then removes the complete transcription from our system, and you cannot access the transcription anymore. If the request has not been deleted, it should be always accessible.

**Comment by vovanb** [comment]
finally - we had two servers polling simultaneously. so now I got success for SAS and DMZ recording , only ngrok is failing.
Can you please provide details how access service logs? I think it will be useful for troubleshooting.

**Comment by zhouwangzw** [comment]
It is great that you found the issue. The service logs I mentioned are our internal logs for investigating issues of our service, so they are not accessible for customers. But for you case, our service is just calling HTTP GET to read audio stream, but got timeout without receiving any bytes, so there is not much we can provide. Have you ever tried to download the audio URL when ngrok is enabled, from any machine in Internet, e.g. via browser?

**Comment by vovanb** [comment]
it is still available for download 
https://efcf-77-137-66-120.ngrok.io/batchrecordings/rcd_2b6297790426000d_220c10de.tmp_stereo.wav
Using Browser it downloaded correct, but GET request is not coming, only HEAD :
`
HEAD /batchrecordings/rcd_2b6297790426000d_220c10de.tmp_stereo.wav 200 OK 
HEAD /batchrecordings/rcd_2b6297790426000d_220c10de.tmp_stereo.wav 200 OK
HEAD /batchrecordings/rcd_2b6297790426000d_220c10de.tmp_stereo.wav 200 OK    `

**Comment by zhouwangzw** [comment]
Would it be possible to keep this link alive for some time? It is still unclear why our service cannot reach this audio. We are investigating.

**Comment by vovanb** [comment]
np at all. Keep in mind that problem reproduceable with any ngrok: you can create virtual folder and point ngrok to local iis using below command
ngrok http -host-header=rewrite localhost:80

**Comment by zhouwangzw** [comment]
I cannot access the link anymore. Ngrok is essentially a tool that exposes your localhost at a certain port to the public network, it seems to me that something related to network configuration blocks the HTTP GET to return results. Is there anything that a  HTTP client need to be aware of when accessing a ngrok URL?

**Comment by vovanb** [comment]
Not that I am aware about something. Note that it reproducible with any ngrok  instance.
I created another session for you
https://e447-5-10-21-66.ngrok.io/scshare/rcd_2b6297790426000d_220c10de.tmp_stereo.wav

**Comment by zhouwangzw** [comment]
Thank for sharing the link! We are investigating.

**Comment by vovanb** [comment]
Thanks for investigating, I can take it with ngrok support maybe. Can you please share your curl.

**Comment by zhouwangzw** [comment]
Sorry, forgot to attach the screenshot. I added them to the previous message now.

**Comment by zhouwangzw** [comment]
I am closing the issue. If you still have problem, please reopen it or create a new one. Thanks!
