### ISSUE TITLE
Is there any chance that I can get "libMicrosoft.CognitiveServices.Speech.core.so" file which runs in softfp environment?

### ISSUE THREAD

**Issue by younsunhwang** [Azure-Samples/cognitive-services-speech-sdk#1373]
Hello. I've posted the request below about a month ago. 

https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1314

My team and I have tested several STT APIs from different companies, and still interested in applying Azure's STT APIs even though "libMicrosoft.CognitiveServices.Speech.core.so" file is not compatible with our legacy software system. The problem is, as I've described earlier in issue #1314, that this .so file that Azure is providing is using hardfp floating point ABI whereas our legacy software is based on softfp floating point ABI. The answerer from previous issue #1314 has mentioned that even systems which use softfp floating point ABI has FPU, and I know that our system is also equipped with FPU as well. 

Theoretically, it is possible to rebuild the whole project using hardfp if my system can use FPU. However, the software that my team is working on is basically a pack of many different software modules and libraries, and all of them are already developed and built using softfp. Therefore, it is practically impossible for my team to just shift from softfp to hardfp, considering the time and effort it takes to rearrange and rebuild every software modules and libraries to make them compatible with hardfp. 

I'd like to describe details about OS and device that my team is using for your reference. My team is developing software for webOS, and our software is running in display devices such as digital signages and televisions. 
Every device that we are working on is based on arm32 architecture. I suppose that this somewhat cumbersome and abrupt thing to ask for, but is there any chance that I can get "libMicrosoft.CognitiveServices.Speech.core.so" file which runs in softfp environment? It doesn't have to be an official version since my team needs the so file to test the performance after applying STT APIs just for now. My team would like to look over as many options as possible, and we regarded that Azure's STT APIs are worth trying since we've found out that Azure's STT functions shows nice performance in demo pages and samples programs that you provide.

**Comment by glharper** [comment]
@younsunhwang Could you send me an e-mail regarding this issue to <my_username>(at)microsoft(dot)com? Thanks.
