### ISSUE TITLE
Continuous Speech not inserting blanks after "period"  using sdk 1.19/1,9  C# VS 2019  

### ISSUE THREAD

**Issue by pryannow1** [Azure-Samples/cognitive-services-speech-sdk#1375]
I am experimenting with voice to text using the microphone, it works well, with one exception for some reason I cannot figure out how to set/configure the voice to text to have a space(s) using en-us after a "period" Can someone point me to the documentation to set this

This is the actual text output :

Ricardo presented to my office on January 21st, 2020 for evaluation and treatment of injuries sustained in an automobile accident on January 16th, 2020.He explained that he was the driver of an SUV V that was rented by a vehicle coming at a high speed. As a result of the accident record or experience neck pain.Mid back pain low back pain and left shoulder pain immediately after the accident he was able to drive to the hospital. However, Ricardo was not concerned about his own injuries while in the emergency room.His wife was involved in the accident and her injuries were addressed while he stayed with her at the ER.Nevertheless, his injuries were significant and continued to worsen during the first few days following the accident.

 am using VS 2019 (64 Bit) UWP C# with Microsoft.CognitiveServices.Speech 1.19 and 1.9 tested both with 1.19 and 1.9 same results

 AudioConfig audioConfig = AudioConfig.FromDefaultMicrophoneInput();
     SpeechConfig speechconfig;
        
     // SpeechRecognizer recognizer;
     readonly TaskCompletionSource<int> stopRecognition = new TaskCompletionSource<int>();
      
     public async Task SpeechContinuousMicAsync()
     {
         StaticVariables.VoiceText = " ";
         StaticVariables.ContinuousVoice = true;
         speechconfig = SpeechConfig.FromSubscription(Names.VoiceKey,  Names.VoiceRegion);
         speechconfig.EnableDictation();
            
         // Creates a speech recognizer from microphone.
         using (var recognizer = new SpeechRecognizer(speechconfig,audioConfig))
         {
             // Subscribes to events.
             recognizer.Recognizing += (s, e) => {
                // StaticVariables.VoiceText += e.Result.Text;
             };
             recognizer.Recognized += (s, e) => {
                 StaticVariables.VoiceText += e.Result.Text;
             };
             recognizer.Canceled += (s, e) => {
                 Console.WriteLine($"\n    Canceled. Reason: {e.Reason.ToString()}, CanceledReason: {e.Reason}");
             };
             recognizer.SessionStarted += (s, e) => {
                 Console.WriteLine("\n    Session started event.");
             };
             recognizer.SessionStopped += (s, e) => {
                    
                 Console.WriteLine("\n    Session stopped event.");
             };
             // Starts continuous recognition. 
             // Uses StopContinuousRecognitionAsync() to stop recognition.
             await recognizer.StartContinuousRecognitionAsync().ConfigureAwait(false);
             do
             {
             } while (StaticVariables.ContinuousVoice == true) ;
             // Stops recognition.
             await recognizer.StopContinuousRecognitionAsync().ConfigureAwait(false);
               
         }
     }

**Comment by glharper** [comment]
@pryannow1 Thanks for using Speech SDK, and writing this issue up. Would the following code change format your text correctly?
```
         recognizer.Recognized += (s, e) => {
             StaticVariables.VoiceText += $"{e.Result.Text} ";
         };
```

**Comment by pryannow1** [comment]
Thanks for the reply.  
I just tested using $"{e.Result.Text} "    worked 
Interesting, continuous speech will return a sentence at a time, I assumed it would just return a random length.  Are there docs that explain this, as I missed it 

Again thank you I really appreciate your reply  enjoy your day

**Comment by glharper** [comment]
@pryannow1 Glad that worked for you. Continuous speech can return a sentence or two at a time for the recognized event for your speech scenario. There are some two sentence results in your original text above (like "Mid back pain low back pain and left shoulder pain immediately after the accident he was able to drive to the hospital. However, Ricardo was not concerned about his own injuries while in the emergency room."), which had a space after the period. 

I wasn't able to find specific documentation about the text field of the SpeechRecognitionResult other than "Presents the recognized text in the result."([here]( https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechrecognitionresult?view=azure-dotnet)) It may be that a more detailed description may not apply to results in other languages, or even different speech scenarios.

**Comment by pryannow1** [comment]
Thank you

I will see how it works once I get the Dr. to use it


Paul

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________
