### ISSUE TITLE
Speech service return error 1006

### ISSUE THREAD

**Issue by XDavidT** [Azure-Samples/cognitive-services-speech-sdk#1376]
**Describe the bug**
Trying to use Speech for my first time, and no error print, but when debug the result I get:

> Unable to contact server. StatusCode: 1006, undefined Reason: getaddrinfo ENOTFOUND en-us.tts.speech.microsoft.com

wav file created but no sound

**To Reproduce**
Run this:
```
const sdk = require("microsoft-cognitiveservices-speech-sdk");
const fs = require("fs");

function synthesizeSpeech() {
    const speechConfig = sdk.SpeechConfig.fromSubscription("<removed-my-key>", "en-US");
    const audioConfig = sdk.AudioConfig.fromAudioFileOutput("./path-to-file.wav");

    const synthesizer = new sdk.SpeechSynthesizer(speechConfig, audioConfig);
    console.log("starting")
    synthesizer.speakTextAsync(
        "this is a test.",
        result => {
            console.log("Start synthesizer")
            synthesizer.close();
            if (result) {
                // return result as stream
                return fs.createReadStream("./path-to-file.wav");
            }
            console.log(result.resultId);
            console.log(result.errorDetails)
        },
        error => {
            console.log(error);
            console.log(error);
            synthesizer.close();
        });
}

synthesizeSpeech();

```

**Expected behavior**
No error :)

**Version of the Cognitive Services Speech SDK**
1.19.0

**Platform, Operating System, and Programming Language**
 - OS: macOs 12.1
 - Hardware - x64
 - Programming language: Nodejs

**Additional context**
video describe:
https://drive.google.com/file/d/16sFjbVXUTHjXBlJU6bG1WWAYXK0Mbygm/view?usp=sharing
result.id = "04E1967AD7174FB9AFF5E318964F8E54"

**Comment by ram-msft** [comment]
@XDavidT Thanks for the details. The format for the endpoint is {region}.tts.speech.microsoft.com. "en-us" is a locale, not a region. Please use the valid regions include westus, northeurope, etc.

**Comment by XDavidT** [comment]
> @XDavidT Thanks for the details. The format for the endpoint is {region}.tts.speech.microsoft.com. "en-us" is a locale, not a region. Please use the valid regions include westus, northeurope, etc.

Then I changed it to: 
`const speechConfig = sdk.SpeechConfig.fromSubscription("<my-key>", "en-US/westus");`
But it still provides the same result.
Is there any region list I can use?
Or you can share examples of your speechconfig so I can test and see if that is the issue?

**Comment by glharper** [comment]
@XDavidT Use
`
const speechConfig = sdk.SpeechConfig.fromSubscription("<my-key>", "westus");`

for a westus key.

**Comment by XDavidT** [comment]
> westus

Thx, but it's still not resolve me issue, it's just changed my error to this:
> Unable to contact server. StatusCode: 1006, undefined Reason:  Unexpected server response: 401

**Comment by glharper** [comment]
Which region is your key for? To get a free key, follow the steps here: What is the Speech service? - Azure Cognitive Services | Microsoft Docs<https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/overview#try-the-speech-service-for-free>
