### ISSUE TITLE
AttributeError: module 'swagger_client' has no attribute 'CustomSpeechTranscriptionsApi'

### ISSUE THREAD

**Issue by ablaziak** [Azure-Samples/cognitive-services-speech-sdk#1377]
I was trying to run speaker recognition from blob. When I tried to generate swagger_client package with URL provided in readme and "westeurope" region I got "No API definition provided." information on the page, and then when I downloaded and installed package (which was possible) I received error "AttributeError: module 'swagger_client' has no attribute 'CustomSpeechTranscriptionsApi'" while running the quickstart.py file. How can I fix this?

**Comment by ablaziak** [comment]
@chlandsi Unfortunately I got same error after installing package from this link "AttributeError: module 'swagger_client' has no attribute 'CustomSpeechTranscriptionsApi'". I was referring to this one https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/python/from-blob

**Comment by chlandsi** [comment]
@ablaziak Please follow the sample I mentioned. The one you are referring to is outdated, we'll update it ASAP. Sorry for the inconvenience.

**Comment by ablaziak** [comment]
It worked for the sample you mentioned, thank you for your help!

**Comment by kwongtn** [comment]
As of v3.1, afaik the following APIs are being replaced:
```py
transcription_api = cris_client.CustomSpeechTranscriptionsApi(
    api_client=client
)
webhook_api = cris_client.CustomSpeechWebHooksApi(api_client=client)
```

You'll need to replace with the following (yes these 2 unified into 1 endpoint)
```py
default_api = cris_client.DefaultApi(api_client=client)
```

I've submitted a PR to update docs here:
- https://github.com/Azure-Samples/cognitive-services-speech-sdk/pull/2012
