### ISSUE TITLE
Exception has occurred: AttributeError module 'swagger_client' has no attribute 'Transcription'

### ISSUE THREAD

**Issue by rsarosh** [Azure-Samples/cognitive-services-speech-sdk#1378]
**Describe the bug**
After installing swagger-client as described at  https://github.com/platformsh/platformsh-client-python

from admin console did the following:

 git clone https://github.com/platformsh/platformsh-client-python.git
 cd platformsh-client-python
 python setup.py install

added the references to the dir

sys.path.append ('platformsh-client-python/swagger-client')
import swagger_client as cris_client

Got the following error:
**Exception has occurred: AttributeError
module 'swagger_client' has no attribute 'Transcription'**

at the following lines

    transcription_definition = cris_client.Transcription(
        display_name=NAME,
        description=DESCRIPTION,
        locale=LOCALE,
        content_urls=[uri],
        properties=properties
    )

**To Reproduce**

run the code after installing swagger-client

**Expected behavior**
Code should have run

**Version of the Cognitive Services Speech SDK**
Latest version

**Platform, Operating System, and Programming Language**
 - OS: Windows 11 enterprise - 10.0.22000 Build 22000
 - Hardware - x64-based PC
 - Programming language:  Python
 - Browser Chrome

**Additional context**
 - Error messages, stack trace, sample code to reproduce the issue, ...
 - Please provide full Speech SDK Log, as per the instructions [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging)?
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by chlandsi** [comment]
Hi, please follow these [instructions](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python) to install the python client for batch transcription. Thanks!

**Comment by rsarosh** [comment]
@chlandsi  Thanks for the quick reply. Now I am getting 401 error. Access denied because of wrong API or invalid subscription key. I am certain my subscription is right, as it is a cut and paste. However, my API endpoint is as follows: 

https://eastus.api.cognitive.microsoft.com/speechtotext/v3.0 

My subscription is in "East US". Do you see any issue with the API endpoint?

I do have a cognitive service multi-service account under the same subscription. I can use the Speech Studio under the same subscription at https://speech.microsoft.com/portal/1309fbe8478c402985c52b9125926600/speechtotexttool 

Thanks for your help in Advance.

**Comment by chlandsi** [comment]
Hi @rsarosh, the endpoint looks correct (Note that you only have to enter the region, `eastus`, in the sample code). Please make sure you are using the subscription key for your Cognitive Services or Speech resource, and not the subscription id. You can get the key from the "Keys and Endpoint" tab on your resource in the Azure Portal.

**Comment by rsarosh** [comment]
Thanks @chlandsi. There are small mistakes done by noobs like me... Will create a PR for your readme ...these small things will save a lot of time and issues for you. Appreciate your help.
