### ISSUE TITLE
getting internal error: 8 and error detail: 998 with the latest sample of speech translation of Java version.

### ISSUE THREAD

**Issue by enelguo** [Azure-Samples/cognitive-services-speech-sdk#138]
**Describe the bug**
CANCELED: Reason=Error
CANCELED: ErrorCode=ConnectionFailure
CANCELED: ErrorDetails=Connection failed (no connection to the remote host). Internal error: 8. Error details: 998. Please check network connection, firewall setting, and the region name used to create speech factory.
CANCELED: Did you update the subscription info?

1. Checked the connection and it works fine. 
2. Checked my subscription with TTS service application and it works fine as well.
3. Check NetMonitor captured data, it shows that request is sent to destination "fe-prod-sea.cris.ai" and got some replies.
So I don't think it is a proxy issue as someone else has already posted.

**Version of the Cognitive Services Speech SDK**
1.2.0

**Platform, Operationg System, and Programming Language**
JDK 1.8
win7

**Comment by fmegen** [comment]
Hi @enelguo,

do you have more information about this isssue?
we would need to know:

- what api did you call (speech, intent, translation)
- what region did you pass in the speech-config?
- did you configure a proxy? do you need a proxy in your setup?

in case you saw already some response, do you have a sessionId of a session where the error occurred on?

kind regards,
 friedel

**Comment by enelguo** [comment]
Hi @fmegen ,

First of all, thank you for your quick reply!!
I'm trying to provide as much as I can.
1. I'm trying the speech translation sample with method "translationWithMicrophoneAsync()". Error occured when calling "recognizer.startContinuousRecognitionAsync().get();"
2. Region is "southeastasia". I think it is located in Singapore.
3. No, I'm not using proxy and I'm sure cloud service is working since my python TTS app works fine.

Regarding the session ID you've mentioned, I don't know where to get it. But I see that the request goese to a server of "fe-prod-sea.cris.ai" as you can see in screenshot.
Furthermore, server side does reply with some information, also you can find it in screenshot.

I suspect that request is not going to the right server at all.

![cs1](https://user-images.githubusercontent.com/3490186/51509245-4b7a9180-1e33-11e9-8029-9402c0ed22a3.png)

**Comment by zhouwangzw** [comment]
@enelguo Do you see the same problem when running your application on Windows 10, instead of Win7?  The Speech SDK is tested on Windows 10. Win7 is not tested nor supported.

**Comment by enelguo** [comment]
Hi zhou,

I will try as you suggested. 
JDK may not be working on win7 with same expectations on win10.
Thank you!

**Comment by wolfma61** [comment]
closing
