### ISSUE TITLE
SpeechToText - Objective-C - Can I get the Word level pronunciation assessment result

### ISSUE THREAD

**Issue by wing199901** [Azure-Samples/cognitive-services-speech-sdk#1380]
**Is your feature request related to a problem? Please describe.**
I am not finding a way to get word level pronunciation assessment result with the Objective-C SDK, and it doesn't appear to be covered in the sample.

**Comment by pankopon** [comment]
Hi, please take a look at the [how to use pronunciation assessment](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-pronunciation-assessment?pivots=programming-language-objectivec) page. Parameter `granularity:SPXPronunciationAssessmentGranularity_Phoneme` in the example should already produce scores on the word level, though you can also use `granularity:SPXPronunciationAssessmentGranularity_Word`. (See [configuration parameters](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-pronunciation-assessment?pivots=programming-language-objectivec#configuration-parameters) for details.)

**Comment by wing199901** [comment]
Thanks very much for the answer. I want to call the Word level pronunciation assessment result like this (https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.pronunciationassessment.pronunciationassessmentresult.words?view=azure-dotnet#microsoft-cognitiveservices-speech-pronunciationassessment-pronunciationassessmentresult-words). 
How can I do this in Objective-C?

**Comment by pankopon** [comment]
Right - based on https://docs.microsoft.com/objectivec/cognitive-services/speech/spxpronunciationassessmentresult SPXPronunciationAssessmentResult seems to lack a property for words, while it exists in C#. So there's just the JSON result with word level scores.
@yulin-li Can you please confirm the above & is there a plan to add the Words property to SPXPronunciationAssessmentResult in Obj-C?

**Comment by pankopon** [comment]
@wing199901 Meanwhile, you may read the JSON result string like
```
    [speechRecognizer addRecognizedEventHandler: ^ (SPXSpeechRecognizer *recognizer, SPXSpeechRecognitionEventArgs *eventArgs) {
        NSString *jsonResult = [eventArgs.result.properties getPropertyById:SPXSpeechServiceResponseJsonResult];
        NSLog(@"Received JSON: %@", jsonResult);
        // insert JSON parsing as appropriate...
    }];
```
The structure of the JSON result is as in the [sample response](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-pronunciation-assessment?pivots=programming-language-objectivec#sample-responses).

**Comment by yulin-li** [comment]
Hi @wing199901 thx for using Pronunciation Assessment and reaching out. Currently out objc SDK doesn't parse the json to object. I think you can parse it as @pankopon suggested.
We heard your requirement and added this work to backlog. I will let you know when it finished.

**Comment by yulin-li** [comment]
Hi @wing199901 We will implement this feature and release it with next version (1.21).

We tracked this internally (id 4094454), so I will close the issue here. Fell free to reopen it for any concerns

**Comment by dargilco** [comment]
Speech SDK 1.21 was release. See release notes: https://docs.microsoft.com/azure/cognitive-services/speech-service/releasenotes?tabs=speech-sdk#speech-sdk-1210-april-2022-release
