### ISSUE TITLE
Diarization doesn't work for more than 2 speakers

### ISSUE THREAD

**Issue by AnkurDahama** [Azure-Samples/cognitive-services-speech-sdk#1384]
Hi folks, 

I'm working on a project in which we're using Azure Speech-to-text to transcribe Swedish language meetings. (recorded from Zoom, Teams, Meets, etc. so they’re mono-channel).

The meetings have more than 2 speakers, but only 2 speakers are identified when we use REST API Batch transcription. 

I've read in the documentation that Rest Batch API only supports 2 speakers. Will this be updated to more than 2 speakers soon?

However, my second approach was to use async conversation transcription, since in the documentation it says that you don't need samples of the speakers to get diarization ("User voice samples are optional. Without this input, the transcription will show different speakers, but shown as "Speaker1", "Speaker2", etc. instead of recognizing as pre-enrolled specific speaker names.”). 

Could you help on how to get this to work?

**Comment by jhakulin** [comment]
@AnkurDahama Thanks for the question, with conversation transcription you can differentiate speakers by using DifferentiateGuestSpeakers property as documented here https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/conversation-transcription
```
config.SetProperty("DifferentiateGuestSpeakers", "true");
```

**Comment by zhouwangzw** [comment]
@AnkurDahama  Batch transcription will support diarization >2 speakers in the next version, which will be probably released as preview in the next months. Thanks!

**Comment by AnkurDahama** [comment]
thanks!

**Comment by kamrapooja** [comment]
Any timeline by when this feature [diarization >2]  will be added
