### ISSUE TITLE
How to log utterances on LUIS when using through custom commands.

### ISSUE THREAD

**Issue by J-Hardyy** [Azure-Samples/cognitive-services-speech-sdk#1390]
Hi,

How do I log utterances on LUIS when consuming the service via custom commands using DialogServiceConnector?

I see the DialogServiceConnector takes a CustomCommadsConifg parameter which has a set property method. 
What properties are able to be set via this method? Are they the same as the properties answered in Issue #1306 ?

Many thanks.

**Comment by dargilco** [comment]
Hi @J-Hardyy, this is Darren from the Speech SDK team. Thank you for your question. I am looking for the right person from CustomCommands to answer your first question.

Regarding your second question (about "what properties are able to be set"), is this directly related to your first question? if not, can you tell me what you are trying to do? what functionality is missing that you are looking for a property settings to solve.

Thanks,

Darren

**Comment by J-Hardyy** [comment]
Hi Darren,

Thank you for your response. It is directly linked to my first question. However, it would be good to know what other functionality is available via this set property method.

Thanks

**Comment by Emma-ms** [comment]
Hi @J-Hardyy, this is Emma from Custom Commands team. Thanks for reaching out. Could you help to clarify the expect result of "LUIS utterances", do you want the Speech recognized (SR) result or LUIS recognized result as well? 
For example, SR -"turn on the light"; then LUIS get -  intent "<command Name> such as ConrolDevice", entity "<parameter Names> such as light and of/off".

For the full result that includes both recognized sentence and intent/entity, I think from CC side, the best way is to add an activity in rules ->response for each command on speech portal. You can get even more than the LUIS result, such as the CC parameters after slot mapping and rule selection. Here are some examples
Save lastUtterance in parameters
![image](https://user-images.githubusercontent.com/58613011/151641784-8127b45a-679b-410f-ad85-53e92916c4ad.png)
Return recognized parameters in activities
![image](https://user-images.githubusercontent.com/58613011/151641647-baecb623-92e0-4f2b-81dc-3ee30f634ae5.png)
As users own their model, CC service will not log users' conversation in runtime for privacy. As a result, I'm afraid you cannot "enable" more log if it is not defined in response. 

If it is SR result only, it looks to be the same question as https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1306. We will leave the question to Darren.

Please let us know if it answers your question, or you have any other questions on Custom Commands.

Thanks,
Emma

**Comment by J-Hardyy** [comment]
Hi,

Thank you for your response. I wanted the LUIS result. If LUIS won't log the utterances made via Custom commands I'll probably go down the route of adding a response to each command as you have suggested in your examples.

Thank you.

**Comment by Emma-ms** [comment]
Cool. Please try that and let us know if you have any other questions.

**Comment by dargilco** [comment]
Closing the issue. @J-Hardyy please feel free to re-activate if you have more questions. Thanks!
