### ISSUE TITLE
Unity sample on iOS gives SPXERR_MIC_ERROR

### ISSUE THREAD

**Issue by brandom-msft** [Azure-Samples/cognitive-services-speech-sdk#1393]
Going through the [sample for interacting with a bot in C# Unity](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/csharp/unity/VirtualAssistantPreview), when I deploy to iPhone and try to run I get an immediate cancellation. 

(XCode first showed an error that I must use NSMicrophoneUsageDescription for microphone access. I added that entry to info.plist and when I ran, I got a prompt requesting microphone access, but I still got a cancellation) 

To get a log, I updated the script following the [steps for C#](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging#sample) and updated the info.plist in XCode to [enable file access ](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging#ios). 

From that log I see the error details:

[756173]: 4263ms SPX_DBG_TRACE_SCOPE_EXIT:  microphone_pump_base.cpp:179 MicrophonePumpBase::UpdateState ... Done!
[756173]: 4272ms SPX_TRACE_ERROR:  audio_sys.cpp:126 Error: AudioQueueStart failed (-50)
[756173]: 4272ms SPX_THROW_HR_IF:  microphone_pump_base.cpp:127 (0x015) = 0x15
[756173]: 4299ms SPX_TRACE_ERROR:  exception.cpp:119 About to throw Exception with an error code: 0x15 (SPXERR_MIC_ERROR)
[CALL STACK BEGIN]

**Comment by brandom-msft** [comment]
In order to access the microphone, you need to enable this setting in Unity

Unity -> Build Settings -> Player Settings -> Player -> Other Settings -> Prepare iOS for Recording

![MicrosoftTeams-image](https://user-images.githubusercontent.com/42854725/151466773-e5588dc4-047c-418a-a82f-dc16bee66d35.png)

Then I build the app in XCode and deploy and it works!

**Comment by taeyoungkimbgl** [comment]
@brandom-msft Thank you I solved my error!!!

**Comment by el-mimoso** [comment]
> In order to access the microphone, you need to enable this setting in Unity
> 
> Unity -> Build Settings -> Player Settings -> Player -> Other Settings -> Prepare iOS for Recording
> 
> ![MicrosoftTeams-image](https://user-images.githubusercontent.com/42854725/151466773-e5588dc4-047c-418a-a82f-dc16bee66d35.png)
> 
> Then I build the app in XCode and deploy and it works!

This should be in the getting started guide, thank you so much!!!
