### ISSUE TITLE
Trying to run speaker recognition in C#

### ISSUE THREAD

**Issue by Shubham7054** [Azure-Samples/cognitive-services-speech-sdk#1395]
Hi, I'm trying out [Speaker recognition](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/csharp/dotnet/speaker-recognition/helloworld/Program.cs), but it's throwing an error. With the help of debugger I realized there is some error on line 143 (using (var audioInput = AudioConfig.FromWavFileInput(trainingFile)))

Error thrown -> "AudioProcessingOptions = 'audioInput.AudioProcessingOptions' threw an exception of type 'System.ApplicationException'".

I'm following [these steps](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/dotnet/from-microphone#quickstart-recognize-speech-from-a-microphone-in-c-under-net-framework-for-windows) and the only change I made in the code above are subscription key and region. Thanks in advance for help

**Comment by dargilco** [comment]
Hi @Shubham7054, this is Darren from the Speech SDK team. Thank you for posting this question. Which operating system are you using? What version of Speech SDK are you using? If possible, please use latest version (1.19) and also provide as with SDK logs ([see here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging)).
Thanks, Darren

**Comment by eric-urban** [comment]
@Shubham7054 - If the WAV file is not present I can repro this issue. Please be sure to set paths to each audio file. You can use the WAV files in this directory of the samples repository: [sampledata/audiofiles](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/sampledata/audiofiles). I hope this helps!

**Comment by dargilco** [comment]
Thank you @eric-urban for checking. I will close this issue, but @Shubham7054 feel free comment here if Eric's suggestion did not solve your problem. If that's the case I will re-open the issue.
Darren

**Comment by Shubham7054** [comment]
Hi, thanks for replying. In [this code](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/csharp/dotnet/speaker-recognition/helloworld/Program.cs) the wav files listed are myVoiceIsMyPassportVerifyMe01.wav, myVoiceIsMyPassportVerifyMe02.wav, myVoiceIsMyPassportVerifyMe03.wav (line 134-136) and if we look closely, program.cs file and these wav files are in same [directory](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/dotnet/speaker-recognition/helloworld). I even tried to play these audio from program.cs using [this](https://stackoverflow.com/questions/3502311/how-to-play-a-sound-in-c-net) and it's playing, unable to fix this issue yet

**Comment by eric-urban** [comment]
@Shubham7054 - Double checking, were you also granted access to the speaker recognition preview? https://docs.microsoft.com/en-us/legal/cognitive-services/speech-service/speaker-recognition/limited-access-speaker-recognition

**Comment by Shubham7054** [comment]
@eric-urban I followed [these steps](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/overview#try-the-speech-service-for-free) to try the speech service and I didn't came across this documentation and the form in it. Am I supposed to fill this form as well? Was curious as I have subscription key and region and that's all required according to [this](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/dotnet/from-microphone#quickstart-recognize-speech-from-a-microphone-in-c-under-net-framework-for-windows)

**Comment by eric-urban** [comment]
@Shubham7054 - Yes applying for access is required currently, so we’ll need to update the sample instructions. Good catch! Thanks

**Comment by dargilco** [comment]
Closing this issue, as we have an internal work item for updating the sample code with the proper note as per the above. Thanks all!
