### ISSUE TITLE
 is there any to replace or boost a word in speech to text result

### ISSUE THREAD

**Issue by jian-sun** [Azure-Samples/cognitive-services-speech-sdk#1396]
I wanta  replace a word in one sentence from stt service
for example
stt result: XXXXXX too XXXXXXX
expected: XXXXXX two XXXXXX

is there any way to improve weight or priority of 【two】
like google
https://cloud.google.com/speech-to-text/docs/adaptation-model

**Comment by dargilco** [comment]
Hi @jian-sun , this is Darren from the Speech SDK team. Thank you for your question. It would help us if you could give us a few examples of full sentences, so we see the context of the too/two recognition. Also, in order for me to point you to sample code, what is your programming language and operating system?
We do have PhraseListGrammar which you can use. See the "Improve recognition accuracy" section for your particular programming language. [This link is for C#](https://docs.microsoft.com/azure/cognitive-services/speech-service/get-started-speech-to-text?tabs=windowsinstall&pivots=programming-language-csharp#improve-recognition-accuracy), but you can switch to another programming language at the top of the page. Also see the [ContinuousRecognitionWithFileAndPhraseListsAsync() sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/c93daf0ec99bd16220d0debc43d73da3f2a3d824/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L686).
For more advanced customization, we have [Custom Speech](https://docs.microsoft.com/azure/cognitive-services/speech-service/custom-speech-overview), but based on your short description PhraseListGrammar may help.
Darren
