### ISSUE TITLE
Avoiding sending empty recognition results to the API

### ISSUE THREAD

**Issue by aalonso-solusoft** [Azure-Samples/cognitive-services-speech-sdk#1398]
Hello, we are using the Cognitive Speech SDK for Android to develop a voice assistant. Are there any way to avoid sending empty strings to the API when the user does not speak anything?

**To Reproduce**

1. Configure the DialogServiceConnector and invoke the listenOnceAsync operation:
```java
DialogServiceConfig dialogServiceConfig = BotFrameworkConfig.fromSubscription(configuration.speechSubscriptionKey, configuration.speechRegion);
DialogServiceConnector botConnector = new DialogServiceConnector(dialogServiceConfig, AudioConfig.fromDefaultMicrophoneInput());
botConnector.listenOnceAsync();
```
2. User tells nothing.
3. DialogServiceConnector recognizes and sends "" to the API.

**Version of the Cognitive Services Speech SDK**
Java SDK version - 1.17.0

**Platform, Operating System, and Programming Language**

- OS: [e.g. Windows, Linux, Android, iOS, ...] - Android
- Programming language: Java

**Comment by dargilco** [comment]
Hi @aalonso-solusoft, this is Darren from the Speech SDK team. Thank you for posting this question.

Can you please describe in more details what you are seeing now and what are changes you want to see for the case that nothing is spoken? I don't understand what "sending empty strings to the API" means. Is this about the "Recognized" event? Is this about what your bot gets? both?

Also, please repeat the experiment while logging and share the log here:
https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging

Thanks,

Darren

**Comment by aalonso-solusoft** [comment]
Helo @dargilco , thanks for your answer.

Yes, it happens in both places really, in the client side we are getting the "" text in the recognized event and in the bot side we are getting an activity with null text and we are handling it as an unknown intent.

We only want to know if it is the default behaviour or if there is a property for maybe ignoring silences and not sending them to the bot 

Here is my log file:
[SpeechSdk.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/7984539/SpeechSdk.log)

Thanks for your answer.

**Comment by aalonso-solusoft** [comment]
Ok, I assumed this was necessary to deal with unanswered messages.

We, in our application have a buttom that when gets clicked opens a card and start listening to the user. In that card there is also a "quick actions menu" that, when you click one of them, send a message to the bot. So, in these situations there are two messages going to the bot, the first, the silence and the second the quick action. The bot responses to both and we are receiving the "sorry i didn't understand you" response and the quick action response.

But now this is not a bug for us because we implemented a conversation mechanism (using the conversationId field of the messages) and we are able to separate the two messages in two different conversations and discarding the response received due to the first silence and it works for us. We are only exploring the posibilities of the SDK.

**Comment by dargilco** [comment]
@aalonso-solusoft Glad to hear you have found solution. Just out of curiosity, is the case where users click to open the card, but do not speak afterward, a common case? or is this small number of cases? If the former, it seems like it's wasteful to send audio with no speech to the service, as you are still being charged for it. Is there a way to update the UI such that you are more confident that if a user clicks a button they will actually be speaking?

**Comment by aalonso-solusoft** [comment]
Now is not very common indeed. Thanks for your suggestion, you are right and we will speak with our design team.

Thank you very much.
