### ISSUE TITLE
.NET Standard Support

### ISSUE THREAD

**Issue by NathanNZ** [Azure-Samples/cognitive-services-speech-sdk#14]
### This issue is for a: (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ X ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

1. Start up a .NET Core 2 or above console application
2. Install the Microsoft.CognitiveServices.Speech nuget package
3. Package installs with no libraries referenced.

### Any log messages given by the failure
> None

### Expected/desired behavior
1. Start up a .NET Core 2 or above console application
2. Install the Microsoft.CognitiveServices.Speech nuget package
3. Package installs setting up the required references (bringing in the Windows Compatibility Pack if needbe)

### OS and Version?
> Windows 10

### Versions
> 0.4.0

### Mention any other details that might be useful
Would be great if we could get some .NET Standard support to work in .NET Core - even if it only works on Windows we can at least throw it in a Windows Server Docker container 👍

**Comment by zhouwangzw** [comment]
Thanks for your feedback. We are currently working on .NET Standard/.NET Core support and will make it available very soon. Please stay tuned!

**Comment by mahilleb-msft** [comment]
@NathanNZ - can you check out release 0.5.0 of the Speech SDK? It adds .NET Standard / Core support. This is for Windows only at this stage, other platforms will follow. Check out https://docs.microsoft.com/azure/cognitive-services/speech-service/quickstart-csharp-dotnetcore-windows for an intro.
