### ISSUE TITLE
Microsoft cognitive Services package Seems to cause UnityEditor to hang when switching between projects.

### ISSUE THREAD

**Issue by Matt-Finlay** [Azure-Samples/cognitive-services-speech-sdk#1401]
**Describe the bug**
When i include the Microsoft cognitive Services package in my Project, and change application focus between unity and visual studio, when returning to unity, unity will just hang with spinning wheel, until i quit/relaunch it. if i take out cognitive services asset package, the same project works fine.

**To Reproduce**
1. Use the a project with cog services bundle in it. 
2. ..

**Expected behavior**
Normal recompile behavior, when switching between VS/Unity.

**Version of the Cognitive Services Speech SDK**
1.20.0

**Platform, Operating System, and Programming Language**
 - Windows
 - Intel x64
 - Programming language: C#

**Additional context**
- The STT is working well aside from the above crash.
 - Any other additional information: I am developing for oculus quest 2
- if you want the specific script/project that i am using to eliminate that as the cause, please send me a PM.

**Comment by BrianMouncer** [comment]
@Matt-Finlay

I'll try to reproduce this with our public Unity samples.
What version of Unity are you using?
Also, is any use of our package, or is there a particular sample that you have seen this happen with?

Thanks,

**Comment by BrianMouncer** [comment]
@Matt-Finlay 

Thanks for telling us know you resolved the issue. What was the issue you fixed?
Was this related to disposing of objects correctly?
What could we document better, so you could have root caused this quicker?

Thanks,
