### ISSUE TITLE
NameError: name 'SpeechSynthesisOutputFormat' is not defined

### ISSUE THREAD

**Issue by Vaaai** [Azure-Samples/cognitive-services-speech-sdk#1402]
**Describe the bug**
When following the Python tutorial and using the same code snippet as described in the Microsoft docs ([Link](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-text-to-speech?tabs=script%2Cwindowsinstall&pivots=programming-language-python)) to utilise Azure's Text-to-Speech services I get the following error message:

`NameError: name 'SpeechSynthesisOutputFormat' is not defined`

**To Reproduce**
Use the code snippet below

`
speech_config.set_speech_synthesis_output_format(SpeechSynthesisOutputFormat["Audio48Khz192KBitRateMonoMp3"])
synthesizer = speechsdk.SpeechSynthesizer(speech_config=speech_config, audio_config=None)
result = synthesizer.speak_text_async("Customizing audio output format.").get()
stream = speechsdk.AudioDataStream(result)
stream.save_to_wav_file("Test/test.mp3")
`
**Expected behavior**

Getting a test.mp3 file with text-to-speech audio

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 - OS: Mac Big Sur (11.6)
 - Hardware: Apple Silicion
 - Programming language: Python

**Comment by BrianMouncer** [comment]
@Vaaai can you try this instead, this is what we use in our [public samples](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_synthesis_sample.py).

speech_config.set_speech_synthesis_output_format(speechsdk.SpeechSynthesisOutputFormat.Audio16Khz32KBitRateMonoMp3)

The above sample worked for me when I changed the format from 16khz to 48khz.

speechsdk.SpeechSynthesisOutputFormat.Audio48Khz192KBitRateMonoMp3

Can you please give that a try and let me know how it goes?

Thanks,

**Comment by yulin-li** [comment]
@Vaaai thx for reporting this. We believe it's a doc issue. Could you pls try our sample as Brian suggested?

**Comment by Vaaai** [comment]
Thank you @BrianMouncer and @yulin-li . Brian's code worked! Thank you also for the public samples' link.
