### ISSUE TITLE
What are the audio formats supported by Pronounciation Assessment?

### ISSUE THREAD

**Issue by indjec** [Azure-Samples/cognitive-services-speech-sdk#1407]
Can anyone list me the list of audio formats supported by Pronounciation Assessment Api? I have seen the support of .wav but could not find any documentation related to this.

**Comment by jhakulin** [comment]
@yulin-li @yinhew Could you please comment and link to documentation which audio formats supported by Pronounciation Assessment Api?

**Comment by jddt444** [comment]
The logging service needs to be up to date so when its logging pertains to a request context, it has get right of entry to to that information and that it successfully makes use of this records to log the request identifiers out to get on [riseaesthetics](https://riseaesthetics.co/).

**Comment by yinhew** [comment]
The audio formats being supported are the same for pronunciation assessment and STT. @indjec @jhakulin

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
