### ISSUE TITLE
Is there a Rest API example for getting TTS Word Boundary?

### ISSUE THREAD

**Issue by Jun711** [Azure-Samples/cognitive-services-speech-sdk#1409]
1) 
I am using Python requests to get audio through the cognitoService speech REST API. Is there an example somewhere that I refer to so that I can save time figuring it out? 

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-text-to-speech
```
requests.post("https://westus2.tts.speech.microsoft.com/cognitiveservices/v1", data=data ,headers=headers)
```

I don't need most of the functions from the sdk so I prefer not to install the sdk if possible to keep the cloud function light. 

2)
Does it cost more to get word boundary?

Thank you

**Comment by yulin-li** [comment]
@Jun711, thank for reaching out but unfortunately out REST api doesn't support word boundary, nor other events such as viseme or bookmark.

We recommend you to use our SDK to get them.

**Comment by Jun711** [comment]
@BrianMouncer @yulin-li Thank you. 

It seems that it is using websocket to get word boundary. From the [example](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_synthesis_sample.py#L432), it subscribes to `synthesis_word_boundary.connect` events to get word boundaries. 

I have some questions
1) Are they guaranteed to come in the correct sequence? 

2) It doesn't seem to have 'last word' event, does it? 

3) Are word boundary events always sent before audio data is sent?

**Comment by yulin-li** [comment]
> Are they guaranteed to come in the correct sequence?

yes

> It doesn't seem to have 'last word' event, does it?

We don't, but you can detect if it's the last word by `textOffset`

> Are word boundary events always sent before audio data is sent?

Word boundary events are always sent before the corresponding audio

> Should my server reset the websocket connection for every request? Does it to disconnect and reconnect the websocket connection every now and then?

You don't need to care about the websocket connection. You can just use `SpeechSynthesizer` and SDK will handle the connection.

**Comment by Jun711** [comment]
@yulin-li Thank you!

**Comment by Jun711** [comment]
@yulin-li How do I turn on error logging for this SDK? I notice that sometimes there is 502 error but there is no error logged.

**Comment by yulin-li** [comment]
see [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging)

**Comment by litao09h** [comment]
@yulin-li  Is there a websocket example for getting TTS ?

**Comment by yulin-li** [comment]
> @yulin-li Is there a websocket example for getting TTS ?

You can use SDK which uses websocket

**Comment by litao09h** [comment]
> > @yulin-li Is there a websocket example for getting TTS ?
> 
> You can use SDK which uses websocket

we used golang sdk,  and get cgo error. Speech SDK depends  on too many c/c++ packages,  install those packages in docker is a hard work and not graceful, and cgo error is  hard to debugging . so, we perform to  rest api or websocket api.

**Comment by litao09h** [comment]
> > @yulin-li Is there a websocket example for getting TTS ?
> 
> You can use SDK which uses websocket
thanks for replay!

we used golang sdk,  and get cgo error. Speech SDK depends  on too many c/c++ packages,  install those packages in docker is a hard work and not graceful, and cgo error is  hard to debugging . so, we refer to  rest api or websocket api.

**Comment by yulin-li** [comment]
Yes, I knew it's pain... But currently we don't have a public doc for the websocket protocol. Maybe you can try to follow the instruction to set up environment for go

**Comment by wodny** [comment]
@litao09h:
> we used golang sdk, and get cgo error. Speech SDK depends on too many c/c++ packages, install those packages in docker is a hard work and not graceful, and cgo error is hard to debugging . so, we refer to rest api or websocket api.

Take a look at https://learn.microsoft.com/en-us/answers/questions/776407/tts-rest-endpoint-for-ssml-bookmark-tag.html.
