### ISSUE TITLE
SetProxy() via Automatic Configuration Script

### ISSUE THREAD

**Issue by robintel** [Azure-Samples/cognitive-services-speech-sdk#141]
**Is your feature request related to a problem? Please describe.**
With SDK 1.1.0, a new option was introduced for the SpeechConfig methods.

public void SetProxy (string proxyHostName, int proxyPort, string proxyUserName, string proxyPassword);

This is nice,. But I don't have that. Instead, we use an automatic configuration script.

**Describe the solution you'd like**
I'd like a method like:

public void SetProxyFromScript (string location);

**Describe alternatives you've considered**
I am using the SDK for a console-based application, I don't see many options here.

**Additional context**
This Automation Configuration Script is set as:
![image](https://user-images.githubusercontent.com/3413911/51386032-51b1fa80-1b21-11e9-8850-2b2b329af1ab.png)

**Comment by wolfma61** [comment]
It is my understanding that proxy script are JavaScript files that expose a method which returns the proxy/port information.
We currently have no intention to host javascript in the SDK to retrieve this information

**Comment by wolfma61** [comment]
closing
