### ISSUE TITLE
Continuous speaker recognition

### ISSUE THREAD

**Issue by Shubham7054** [Azure-Samples/cognitive-services-speech-sdk#1412]
Hey, In the documentation there is [recognize once method](https://docs.microsoft.com/en-us/java/api/com.microsoft.cognitiveservices.speech.speechrecognizer.recognizeonceasync?view=azure-java-stable), but we need continuous recognition so that if there is a voice change it can detect. I was curious if it's possible or we have to call recognize once in an interval of 5-10 seconds. 
Also our input will be [audio stream](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-audio-input-streams)

**Comment by brandom-msft** [comment]
Hi @Shubham7054, we do support continuous recognition - you can find the [documentation here](https://docs.microsoft.com/java/api/com.microsoft.cognitiveservices.speech.speechrecognizer.startcontinuousrecognitionasync?view=azure-java-stable). If you haven't already, take a look at our [samples and quickstarts](https://docs.microsoft.com/azure/cognitive-services/speech-service/get-started-speech-to-text?tabs=windowsinstall&pivots=programming-language-java#use-continuous-recognition) for more info!
