### ISSUE TITLE
Need to understand Batch Transcription

### ISSUE THREAD

**Issue by kamrapooja** [Azure-Samples/cognitive-services-speech-sdk#1419]
I want to implement Speaker Diarization with speech to text functionality. But this functionality is only availalabe in Batch transcription API. I have gone through sample code as well that is available here:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python
In the sample swagger_client has been used. I am not able to understand why we are using swagger_client. Do we have direct api in azure cognitive service SDK python? Currently i am using azure.cognitiveservices.speech package for speech to text functionality.
Please help

**Comment by zhouwangzw** [comment]
The azure.cognitiveservices.speech package is for real-time transcription only. Batch transcription is a REST API, which is not included in that packages. The sample you referred is using swagger generated REST client to call batch service, but you can also write your own REST client to call batch transcription. This is the batch documentation: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription.
Thanks!

**Comment by kamrapooja** [comment]
Implemented. Thanks a lot. One question, is there any upper limitation on audio file size as well?

**Comment by kamrapooja** [comment]
I have implemented the azure Batch Transcription REST API. In the document it is written that we can get capitalized and punctuated text in "Display" key. But in "Dispaly" it is also converting numeric data to number. e.g. 63 miles instead of sixty three miles.
Can we get data in words only"
Lexical is only raw data without punctuation.
We want data with punctuation only.
Please suggest for the same.

**Comment by kamrapooja** [comment]
Please respond

**Comment by zhouwangzw** [comment]
@kamrapooja it is currently not supported to have punctuation only without other post processing features.

**Comment by kamrapooja** [comment]
@zhouwangzw thanks for the response

**Comment by kamrapooja** [comment]
Closed
