### ISSUE TITLE
Last word from last speech recognition is leading next recognition with phrases added and EndSilenceTimeoutMs at 0

### ISSUE THREAD

**Issue by brknbyt** [Azure-Samples/cognitive-services-speech-sdk#1421]
**Describe the bug**

When adding phrases with dashes("-") to the speech recognizer and saying first the added phrase then anything else, the last word of the phrase is added to as the first recognized word in the next recognition. This problem only appears when the EndSilenceTimoutMs is set between 0-9 or larger than 2000. It does not appear when the value is set between including 1000 and 2000. We are using the german ("de-DE") language model. We observed the problem first with the SDK version 1.17. Using the 1.20 version didn't solve it.

If we add f.e. the phrases "Ingrid-Hope" and "von Oldenburg" to the phrases and say "Ingrid-Hope von Oldenburg", it will correctly recognize \<Ingrid-Hope von Oldenburg\>. But when we then say something like "ja" after that, the recognizer returns \<Oldenburg ja\>. The problem appears always when the EndSilenceTimoutMs is set to 0, and inconsistently when larger 2000.

**To Reproduce**
1. Create a speech recognizer
2. Add phrases containing "-" into the PhraseListGrammar (e.g. "Richard-Wagner-Straße")
3. Start a continuous speech recognition session.
4. Say the phrases added to the PhraseListGrammar and have the recognizer recognize it.
5. Say something else like "ja".

**Expected behavior**
The recognition after the phrase should only contain the said words. (e.g. "ja")

**Version of the Cognitive Services Speech SDK**
1.20

**Platform, Operating System, and Programming Language**
 - OS: Linux
 - Hardware - x64
 - Programming language: Java

**Additional context**

Example code to reproduce, example audio, and log file below. Run it with the options _-e 0 --demo_ to reproduce.

```
package com.parloa.phonegateway;

import com.google.common.io.ByteStreams;
import com.microsoft.cognitiveservices.speech.PhraseListGrammar;
import com.microsoft.cognitiveservices.speech.PropertyId;
import com.microsoft.cognitiveservices.speech.ServicePropertyChannel;
import com.microsoft.cognitiveservices.speech.SpeechConfig;
import com.microsoft.cognitiveservices.speech.SpeechRecognizer;
import com.microsoft.cognitiveservices.speech.audio.AudioConfig;
import lombok.Data;
import lombok.extern.slf4j.Slf4j;

import java.io.*;
import java.util.concurrent.ExecutionException;

@Slf4j
public class DemoApplication {

  public static void main(String[] args) throws ExecutionException, InterruptedException {

    Options options = parseArguments(args);

    StringBuffer buffer = new StringBuffer();

    SpeechConfig speechConfig = SpeechConfig.fromSubscription(
        "**", "westeurope");

    speechConfig.setSpeechRecognitionLanguage("de-DE");
    speechConfig.setProperty(PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs,
        options.getInitialSilenceTimeoutMs());
    speechConfig.setProperty(PropertyId.SpeechServiceConnection_EndSilenceTimeoutMs, options.getEndSilenceTimeoutMs());
    speechConfig.setServiceProperty("punctuation", "none", ServicePropertyChannel.UriQueryParameter);
    speechConfig.setProperty(PropertyId.Speech_LogFilename, "speechLog.txt");

    AudioConfig audioConfig;

    // We listen either from the local microphone or we pass a precorded wavefile.
    if (options.useDemoFile) {
      File audioFile = getDemoAudioFile();
      audioConfig = AudioConfig.fromWavFileInput(audioFile.getPath());
    } else {
      audioConfig = AudioConfig.fromDefaultMicrophoneInput();
    }

    SpeechRecognizer speechRecognizer = new SpeechRecognizer(speechConfig, audioConfig);

    speechRecognizer.recognized.addEventListener((s, e) -> {
      String text = e.getResult().getText();
      buffer.append(text);
      log.info("** Intermediate Recognized text=\"{}\" {}", text, e.getResult());
      e.getResult().close();
    });

    speechRecognizer.recognizing.addEventListener((s, e) -> {
      log.info("Recognizing \"text\"={} {}", e.getResult().getText(), e.getResult());
      e.getResult().close();
    });

    speechRecognizer.speechStartDetected.addEventListener((s, e) -> {
      log.info("StartOfSpeechDetected for session {}",
          e.getSessionId());
    });

    speechRecognizer.speechEndDetected.addEventListener((s, e) -> {
      log.info("EndOfSpeechDetected for session {}",
          e.getSessionId());
    });

    speechRecognizer.sessionStarted.addEventListener((s, e) -> {
      log.info("Started the SpeechRecognitionSession {}",
          e.getSessionId());
    });

    speechRecognizer.sessionStopped.addEventListener((s, e) -> {
      log.info("Stopped the SpeechRecognitionSession {}",
          e.getSessionId());
    });
    ;

    speechRecognizer.canceled.addEventListener((s, e) -> {
      log.error("SpeechRecognizer canceled. Result {}", e.getResult());
      log.error("SpeechRecognizer canceled. Error Code {}", e.getErrorCode());
      log.error("SpeechRecognizer canceled. Error Details {}", e.getErrorDetails());
      log.error("SpeechRecognizer canceled. {}", e);
    });

    log.info("Adding STT hint phrases: ");
    PhraseListGrammar grammar = PhraseListGrammar.fromRecognizer(speechRecognizer);
    grammar.addPhrase("Ingrid-Hope");
    grammar.addPhrase("von Oldenburg");

    speechRecognizer.startContinuousRecognitionAsync().get();
  }

  @Data
  public static class Options {
    boolean useDemoFile = false;
    String initialSilenceTimeoutMs = "5000";
    String endSilenceTimeoutMs = "1000";
  }

  static Options parseArguments(String[] args) {
    Options op = new Options();
    for (int i = 0; i < args.length; i++) {
      String arg = args[i];
      switch (arg) {
        case "--help":
        case "-h":
          System.out.println("STT Demo");
          System.out.println("");
          System.out.println("Options:");
          System.out.println("  -h, --help Display this help message");
          System.out.println("  -i, --initialSilence [ms] The initial timeout in ms default is 5000");
          System.out.println("  -e, --endSilence [ms] The end timeout in ms default is 1000");
          System.out.println("  -p --phrases List of phrases for the recognizer ");
          System.out.println(" --demo Stream the sample demo file to azure");

          System.exit(0);
          break;

        case "--demo":
          op.setUseDemoFile(true);
          break;

        case "--initialSilence":
        case "-i":
          if (i + 1 < args.length) {
            op.setInitialSilenceTimeoutMs(args[i + 1]);
          }
          break;

        case "--endSilence":
        case "-e":
          if (i + 1 < args.length) {
            op.setEndSilenceTimeoutMs(args[i + 1]);
          }
          break;

      }
    }

    return op;
  }

  private static File getDemoAudioFile() {
    File audioFile = new File("100717_f0ee229e-94b8-42ec-bbec-cdbd2bf759b4.wav");
    if (!audioFile.exists()) {
      ClassLoader cl = DemoApplication.class.getClassLoader();

      try (FileOutputStream fs = new FileOutputStream(audioFile.getName())) {
        try (InputStream in = cl.getResourceAsStream(audioFile.getName())) {
          ByteStreams.copy(in, fs);
        }
        ;
      } catch (IOException e) {
        e.printStackTrace();
      }
    }
    return audioFile;
  }
}

```

[100717_f0ee229e-94b8-42ec-bbec-cdbd2bf759b4.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/8110241/100717_f0ee229e-94b8-42ec-bbec-cdbd2bf759b4.zip)
[speechLog.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/8110244/speechLog.txt)

**Comment by trrwilson** [comment]
Thank you for getting in touch, @brknbyt ! This is a *fantastic* level of detail for the issue report and I really appreciate the effort to get us all the information needed. It worked.

This appears to be an unintended interaction between setting "punctuation=none" and using dynamic grammar information (PhraseListGrammar) entries that contain punctuation. With your input file, I'm able to consistently hit the "Oldenburg ja" recognition when "punctuation=none" is set and never hit it when "punctuation=none" is not set.

I've raised this as a support incident with the team that manages post-processing of display text and hope we'll be able to update here with a resolution soon. In the interim, or if this ends up being more complicated, two potential workarounds:

- If you can omit the `setServiceProperty` call that disables punctuation and manually filter punctuation, instead, that does appear to completely sidestep the issue for me in the trials I've run with your input and data
- Alternatively, if you can use the *lexical* form of recognition results, then you can [request detailed output format](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/c93daf0ec99bd16220d0debc43d73da3f2a3d824/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java#L77) and use that unretouched form the result, which appears to not be impacted by this bug

**Comment by stefan-parloa** [comment]
> If you can omit the setServiceProperty call that disables punctuation and manually filter punctuation, instead, that does appear to completely sidestep the issue for me in the trials I've run with your input and data

When the punctuation like commas are filtered afterwards, it is not possible for the user to share numbers which include a comma. So this solution does not work for our use case.

> Alternatively, if you can use the lexical form of recognition results, then you can [request detailed output format](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/c93daf0ec99bd16220d0debc43d73da3f2a3d824/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java#L77) and use that unretouched form the result, which appears to not be impacted by this bug

The lexical form does not convert spoken numbers into digits, so the processing afterwards does not work in our use case.

This issue is posing more and more issues with our clients.

@trrwilson @pankopon Can you give an update if it is possible to resolve the issue in the upcoming weeks? This would be wonderful!

**Comment by pankopon** [comment]
Closing the item since the service team in question informed us that a fix has been finally deployed. Please open a new issue (or check with the support contact person you've been communicating with) if more help is needed.
