### ISSUE TITLE
Cannot read property 'options' of undefined within Pronunciation Assessment library.

### ISSUE THREAD

**Issue by samjonescode** [Azure-Samples/cognitive-services-speech-sdk#1422]
**Describe the bug**
Unable to use the Pronunciation Assessment JavaScript library. Encountering an error when using 'PronunciationAssessmentConfig.applyTo'. Source of the error is inside SpeechContext.js class, see screenshots at the bottom of the issue.  

**To Reproduce**
1. npm install the microsoft speech services dependency (into an **Angular 13** app).
2. Paste in the boilerplate code provided at the bottom of this issue (inside ngOnInit).
3. Replace the empty credentials with real credentials for an Azure speech services instance.
4. Run the application and open the browser console to see an error.

**Expected behavior**
Expected to connect to my remote CognitiveServicesSpeechServices instance.

**Version of the Cognitive Services Speech SDK**
^1.20.0

**Platform, Operating System, and Programming Language**
 - OS: Windows
 - Hardware - x86
 - Programming language: JavaScript,
 - Browser: Chrome
 - 
**Additional context**
Below is the boilerplate code to reproduce the issue. Note that I removed the subscriptionKey and endpointId from this sample intentionally.
 -  `  var pronunciationAssessmentConfig = new PronunciationAssessmentConfig(
      'reference text',
      PronunciationAssessmentGradingSystem.HundredMark,
      PronunciationAssessmentGranularity.Word
    );
     const subscriptionKey = '';
    const speechConfig = SpeechConfig.fromSubscription(subscriptionKey, 'eastus');
    speechConfig.speechRecognitionLanguage = 'en-US';
    speechConfig.endpointId ='''';

    const autoDetectSourceLanguageConfig: AutoDetectSourceLanguageConfig =
      AutoDetectSourceLanguageConfig.fromLanguages(['en-US']);
    const audioConfig: AudioConfig = AudioConfig.fromDefaultMicrophoneInput();

    const speechRecog = SpeechRecognizer.FromConfig(
      speechConfig,
      AutoDetectSourceLanguageConfig.fromLanguages(['en-US']),
      audioConfig
    );
  
    pronunciationAssessmentConfig.applyTo(speechRecog);
`
Inside SpeechContext setPronunciationAssessmentParams method, the property 'options' is undefined.
![image](https://user-images.githubusercontent.com/24918477/155045322-9f33f8bb-faa2-4244-8470-b427dbfee2bd.png)
![image](https://user-images.githubusercontent.com/24918477/155045522-da01f6a2-9d8b-4fac-8c52-de412e12b11b.png)

**Comment by yulin-li** [comment]
fixed with https://github.com/microsoft/cognitive-services-speech-sdk-js/pull/487. Thanks @samjonescode !
