### ISSUE TITLE
Please add Arm64 version for linux

### ISSUE THREAD

**Issue by ilanh** [Azure-Samples/cognitive-services-speech-sdk#1423]
If running python docker in an M1 machine getting:
ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech (from versions: none)
ERROR: No matching distribution found for azure-cognitiveservices-speech

steps to reproduce:
`docker run --rm python:3.9 pip install azure-cognitiveservices-speech`

verify arch:
`docker run --rm python:3.9 uname -a`
outputs
`Linux c3f07c62c195 5.10.76-linuxkit #1 SMP PREEMPT Mon Nov 8 11:22:26 UTC 2021 aarch64 GNU/Linux`

Similar post by @samvanlier in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1244#issuecomment-998814231_

**Comment by jhakulin** [comment]
@ilanh We do have Python wheels for 3.9 and arm64 for M1, see https://pypi.org/project/azure-cognitiveservices-speech/#files
and there azure_cognitiveservices_speech-1.20.0-cp39-cp39-macosx_11_0_arm64.whl 
However I am not sure how things should be configured on docker, wheel package we released has been verified on local machine using pip install. One option to try here is to download the wheel and install it by doing 
`python -m pip install azure_cognitiveservices_speech-1.20.0-cp39-cp39-macosx_11_0_arm64.whl`

**Comment by jhakulin** [comment]
@ilanh Are you running Docker on Linux or Mac ? I was maybe confused with M1 referring to Mac

**Comment by trrwilson** [comment]
@jhakulin got all the info but I'll just add the [documentation link](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk?tabs=linux%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio#tabpanel_1_linux) for reference.

Quoted from there:

>The Speech SDK only supports Ubuntu 18.04/20.04, Debian 9/10, Red Hat Enterprise Linux (RHEL) 7/8, and CentOS 7/8 on the following target architectures when used with Linux:
>- x86 (Debian/Ubuntu), x64, ARM32 (Debian/Ubuntu), and ARM64 (Debian/Ubuntu) for C++ development
>- x64, ARM32 (Debian/Ubuntu), and ARM64 (Debian/Ubuntu) for Java
>- x64, ARM32 (Debian/Ubuntu), and ARM64 (Debian/Ubuntu) for .NET Core
>- x64 for Python

**Comment by ilanh** [comment]
> @ilanh Are you running Docker on Linux or Mac ? I was maybe confused with M1 referring to Mac. For Linux, we currently do not have arm64 support unfortunately for Python

Got it, 
in that case, my request is that if it's possible,  add a wheel for ARM64 Debian/Ubuntu.

**Comment by dargilco** [comment]
I opened an internal work item for consideration to support Python on arm64. Closing this issue.

**Comment by lezkizofrenik** [comment]
Bringing this up again. Looking forward to ARM64 support. Any updates?

**Comment by pankopon** [comment]
The Speech SDK 1.24.0 release, which is expected before the end of this year, will add Python packages for Linux ARM64 (on [supported Linux distributions](https://learn.microsoft.com/azure/cognitive-services/speech-service/quickstarts/setup-platform?tabs=linux&pivots=programming-language-python)).

Internal work item ref. 2105397.
