### ISSUE TITLE
Input URL for Batch Transcription API 

### ISSUE THREAD

**Issue by kamrapooja** [Azure-Samples/cognitive-services-speech-sdk#1424]
As per Batch Transcription document, Content url can be either Blob or Blob Container.
Will it not work if i give audio url that is there on one of our servers. e.g. audio resides in jboss server locally

**Comment by trrwilson** [comment]
The swagger document might be a bit clearer on the inputs: https://westus.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/operations/CreateTranscription

`contentContainerUrl` will need to refer to an appropriate Azure item, but `contentUrls` can include any locations that are accessible for the request -- e.g. in the above the "contoso.com" URLs.

**Comment by kamrapooja** [comment]
Ok thanks, will check it and will revert in case any problem.

**Comment by kamrapooja** [comment]
Closed

**Comment by zhouwangzw** [comment]
@kamrapooja Is this ip and port public accessible? Could you please share the transcription id that failed, and we can check why it failed.

**Comment by kamrapooja** [comment]
Pleae help

**Comment by zhouwangzw** [comment]
The service log shows that the failure of the transcription with id "125598df-0963-4510-b819-0857cfa673fb" was due to using diarization with stereo audio. You can find error message in the report.json which is included when you GET transcription files. Currently, diarization only works with mono audio. 
Thanks!

**Comment by kamrapooja** [comment]
@zhouwangzw - Thanks a lot. Able to get data after converting audio to mono type.
