### ISSUE TITLE
error while loading shared libraries: libMicrosoft.CognitiveServices.Speech.core.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by leonardltk** [Azure-Samples/cognitive-services-speech-sdk#1428]
I am trying to run a tts like in https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/cpp/linux/text-to-speech 

What i have done is follows:
1. install the sdk
2. updated my machine via
```bash
apt-get update
apt-get -y install build-essential libssl1.0.0 libasound2 wget
```
4. Compiled it using `make`, and outputs are like:
```bash
g++ helloworld.cpp -o helloworld \
    --std=c++14 \
    -I~/speechsdk/include/cxx_api -I~/speechsdk/include/c_api \
    -L~/speechsdk/lib/x64 \
    -lMicrosoft.CognitiveServices.Speech.core -lpthread -l:libasound.so.2
```
6. Run it like:
```bash
./helloworld
```

However i got the following error message
```bash
./helloworld: error while loading shared libraries: libMicrosoft.CognitiveServices.Speech.core.so: cannot open shared object file: No such file or directory
```

**Version of the Cognitive Services Speech SDK**
How do i check this ?
I installed it like this
```bash
export SPEECHSDK_ROOT="~/speechsdk"
mkdir -pv "$SPEECHSDK_ROOT"
wget -O SpeechSDK-Linux.tar.gz https://aka.ms/csspeech/linuxbinary
tar --strip 1 -xzf SpeechSDK-Linux.tar.gz -C "$SPEECHSDK_ROOT"
```

**Platform, Operating System, and Programming Language**
 - OS: Linux
 - Hardware - 
1.  Architecture:        x86_64
2. CPU op-mode(s):      32-bit, 64-bit
 - Programming language: C++
 - Browser: Chrome

**Comment by rhurey** [comment]
Did you add the Speech SDK location to the library path?

https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/cpp/linux/text-to-speech#run-the-sample
