### ISSUE TITLE
TypeError when calling AudioConfig.fromWavFileInput in the JS SDK.

### ISSUE THREAD

**Issue by bisquad** [Azure-Samples/cognitive-services-speech-sdk#1429]
In my index.html I have the following scripts which are largely taken from the JS browser sample.

```
<!-- Speech SDK REFERENCE -->
<script src="https://aka.ms/csspeech/jsbrowserpackageraw"></script>

<!-- Speech SDK presence check -->
<script>
  // On document load resolve the Speech SDK dependency
  function Initialize(onComplete) {
      if (!!window.SpeechSDK) {
          onComplete(window.SpeechSDK);
      }
  }
</script>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    var SpeechSDK;

    Initialize(function (speechSdk) {
        SpeechSDK = speechSdk;
    });
  });  
</script>

<script>
  const speechTranslationConfig = SpeechSDK.SpeechTranslationConfig.fromSubscription("subscriptionkey", "region");
  const audioConfig = SpeechSDK.AudioConfig.fromWavFileInput("classroom-german.wav");
</script>
```

I get the following error.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'slice')
    at FileAudioSource.readHeader (jsbrowserpackageraw:29862:36)
    at new FileAudioSource (jsbrowserpackageraw:29775:44)
    at Function.AudioConfig.fromWavFileInput (jsbrowserpackageraw:4479:36)
    at index.html:52:49
```

The line throwing the error is line 202 from FileAudioSource.ts: `processHeader(h.buffer.slice(h.byteOffset, h.byteOffset + h.byteLength));`

My package.json is as follows.

```
{
  "name": "speech-web-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "microsoft-cognitiveservices-speech-sdk": "^1.20"
  }
}
```

**Comment by rhurey** [comment]
From a browser you'll need to pass a File object and not a file name. The SDK won't try to read arbitrary files, and the support for file names is for use from NodeJS.

There should be a better error message for that scenario, thought.

**Comment by bisquad** [comment]
> From a browser you'll need to pass a File object and not a file name. The SDK won't try to read arbitrary files, and the support for file names is for use from NodeJS.
> 
> There should be a better error message for that scenario, thought.

Thanks, that was the problem.
