### ISSUE TITLE
Pronunciation assessment - Extra words issue

### ISSUE THREAD

**Issue by Nyankoo** [Azure-Samples/cognitive-services-speech-sdk#1430]
**Describe the bug**
When using `PronunciationAssessmentConfig` with the `referenceText` "女は可愛いです" and then recoding "女**と男**は可愛いです" via microphone input, the recognized text in `e.Result.Text` is still "女は可愛いです", which makes it impossible to check if the recognized text matches the expected text.

**To Reproduce**
```
config = SpeechConfig.FromSubscription(getSubscriptionKey(), getSubscriptionRegion());
config.SetServiceProperty("punctuation", "explicit", ServicePropertyChannel.UriQueryParameter);
config.SpeechRecognitionLanguage = "ja-JP";
config.OutputFormat = OutputFormat.Detailed;
            
var configPronunciation = new PronunciationAssessmentConfig("女は可愛いです", GradingSystem.HundredMark, Granularity.Word, true);

stopRecognition = new TaskCompletionSource<int>();

using(var recognizer = new SpeechRecognizer(config, AudioConfig.FromDefaultMicrophoneInput()))
{
                configPronunciation.ApplyTo(recognizer);
                
                recognizer.Recognized += recognizedSentence;
                recognizer.Canceled += canceled;
                recognizer.SessionStopped += sessionStopped;

                await recognizer.StartContinuousRecognitionAsync().ConfigureAwait(false);
                Task.WaitAny(new[] { stopRecognition.Task });
                await recognizer.StopContinuousRecognitionAsync().ConfigureAwait(false);
}
```

**Expected behavior**
A way to identify that the recorded input doesn't match the expected text.

**Version of the Cognitive Services Speech SDK**
C# SDK 1.20.0

**Platform, Operating System, and Programming Language**
 - OS: Windows, Android
 - Hardware - x64, x86
 - Programming language: C#

**Comment by yinhew** [comment]
Hi, @Nyankoo 

Our API currently has constraint which can only recognize the words that appear in reference text.
e.g. referenceText "女は可愛いです", recording "女は可愛いです可愛", then the second "可愛" will be recognized.

Thanks,
Yinhe

**Comment by Nyankoo** [comment]
Hi @yinhew 
thank you for looking into this!

Is there any other way or a workaround to at least check if what the user recorded is different from what is expected?
Currently, a wrong but similar sentence like the example above will result in an ok-ish accuracy score, so it is hard to differentiate if the recording is simply pronounced wrong or actually something different.

**Comment by yinhew** [comment]
@Nyankoo to work around, you can set reference text to empty when sending the request, and then use the recognized text to compare to the reference text.

**Comment by Nyankoo** [comment]
@yinhew This doesn't seem to work, as `PronunciationAssessmentResult.FromResult(e.Result).Words` seems to only have the full sentence instead of each individual word.

I need the accuracy score of each individual work AND to be able to check if the recording of the user is correct.

**Comment by Nyankoo** [comment]
@yinhew Any update on this?

**Comment by yulin-li** [comment]
@Nyankoo looks I cannot repro your issue. I got 4 words in `PronunciationAssessmentResult.FromResult(e.Result).Words`

![image](https://user-images.githubusercontent.com/12013783/158325725-97c08525-22d1-4e2f-8416-1b9eb1b2c6d7.png)

**Comment by Nyankoo** [comment]
@yulin-li Yes, that isn't the issue. The issue is that when using PronunciationAssessmentConfig, I can say something similar or with additional words, and the SDK will not recognize that.

For example:

"女は可愛いです" results in what you have on your screenshot and equals what we wanted the user to say.
"女と男は可愛いです" will also result in what you have in your screenshot, but with less AccuracyScore. The AccuracyScore is not low enough to determine whenever the user has trouble pronouncing the sentence or if he said words that aren't in the sentence. An example for this would be when the user would need to translate from English to Japanese, were he then adds an extra word or uses a word that's wrong but similar.

So what I already said in a previous message: I need the accuracy score of each individual word AND to be able to check if the recording of the user is correct.

**Comment by yinhew** [comment]
@Nyankoo  can you share your audio file for "女と男は可愛いです" ?

**Comment by Nyankoo** [comment]
@yulin-li @yinhew There is no audio file, only microphone input.

**Comment by yulin-li** [comment]
Hi @Nyankoo as we are not Japanese speakers... would you like to share a audio that could repro this issue?

**Comment by Nyankoo** [comment]
@yulin-li We can't share an audio file right now, but this behavior should also be reproduceable with any other language, eg. English.

Simply test the following:
- `new PronunciationAssessmentConfig("The woman is beautiful", GradingSystem.HundredMark, Granularity.Word, true)`
- Audio input/recoding: "The woman and the man are beautiful".

This should result in a low Accuracy Score, but with no actual indication that the input/recoding is different from what is expected.

**Comment by yinhew** [comment]
> @Nyankoo to work around, you can set reference text to empty when sending the request, and then use the recognized text to compare to the reference text.

@Nyankoo looks you didn't follow my guidance above. The reference text need be set to empty.

**Comment by Nyankoo** [comment]
@yinhew maybe you didn't read my replies above, but setting the reference text to empty doesn't work. See the quote below.

> @yinhew This doesn't seem to work, as `PronunciationAssessmentResult.FromResult(e.Result).Words` seems to only have the full sentence instead of each individual word.
> 
> I need the accuracy score of each individual work AND to be able to check if the recording of the user is correct.

**Comment by yinhew** [comment]
@Nyankoo I tried below config and can see the accuracy score on individual word:

- new PronunciationAssessmentConfig("", GradingSystem.HundredMark, Granularity.Word, true)

- Audio input/recording: "good morning"

Output:

![image](https://user-images.githubusercontent.com/46698869/159611884-7391bfe6-bf32-410b-a4a8-d9458f29166a.png)

**Comment by Nyankoo** [comment]
@yinhew I tested a little bit more, and it seems the issue is caused by using a phrase list and the fact that Japanese doesn't have spaces between words.

When adding spaces in between words, we can reliably get each word's accuracy score. Without the spaces, the SDK recognizes everything as one word. Saying the sentence very slowly fixes this issue, but is not really a solution.

Thank you for assisting me with this. When you don't have any follow-up questions, you can close the issue.

**Comment by yinhew** [comment]
@Nyankoo I tried below config and can see the accuracy score on individual word:

new PronunciationAssessmentConfig("", GradingSystem.HundredMark, Granularity.Word, true)

Audio input/recording (synthesized by our TTS API): "女と男は可愛いです"

![image](https://user-images.githubusercontent.com/46698869/159847090-d77dbd77-01b0-4409-955e-0fa4d804c93e.png)

**Comment by Nyankoo** [comment]
@yinhew Did you also use a phrase list with "女と可愛いです"?

**Comment by yinhew** [comment]
@Nyankoo no, I didn't use any phrase list.

**Comment by Nyankoo** [comment]
@yinhew Like I mentioned in my previous message, to reproduce this issue, you need to use a phrase list.

**Comment by yinhew** [comment]
@Nyankoo why you need set phrase list?
Phrase list is not recommended for pronunciation assessment API

**Comment by Nyankoo** [comment]
@yinhew Because we expect specific sentences and without a phrase list, recognition is not accurate enough. This is mostly a problem with names, as the API recognizes other words that are similar instead of the name.

**Comment by pankopon** [comment]
@yinhew Are there still open pending items on this? Please update, othewise we'll close the issue.

**Comment by pankopon** [comment]
Closed since no further updates since March, please open a new issue if more support is needed.
