### ISSUE TITLE
Is it possible to return words in canonical (formatted) form?

### ISSUE THREAD

**Issue by alanj1998** [Azure-Samples/cognitive-services-speech-sdk#1431]
Hi,

I am working with the ContinuousRecognitionAsync functionality with configuration which enables RequestWordLevelTimestamps. 
When the word list is returned with the timestamps, the word property contains the detected word in its lexical form.
Is it possible to return these in their formatted structure? For example:

**Lexical text**: "hello my name is bob"
**Recognized text:** "Hello. My name is Bob."
**Recognized Words Array**:
```json
[
    {
        "word": "hello" 
        ...
    },
    {
        "word": "my" 
        ...
    },
    {
        "word": "name" 
        ...
    },
    {
        "word": "is" 
        ...
    },
    {
        "word": "bob" 
        ...
    }
]
```
**What I am looking for**:
```json
[
    {
        "word": "Hello." 
        ...
    },
    {
        "word": "My" 
        ...
    },
    {
        "word": "name" 
        ...
    },
    {
        "word": "is" 
        ...
    },
    {
        "word": "Bob." 
        ...
    },
]
```

Also, side note, is diarization enabled for StartContinuousRecognitionAsync?

**Comment by rhurey** [comment]
Today word level timing is only available with the lexical form.

Speaker diarization is available from the ConversationTranscriber object.
