### ISSUE TITLE
Bad email recognition in french

### ISSUE THREAD

**Issue by Nolent** [Azure-Samples/cognitive-services-speech-sdk#1436]
**Describe the bug**
Sorry if this bug should not be reported here, i just don't know where to post it
In french, when an email is recognized, some words of the sentence are squashed in it.
I don't know if this problem occur in other languages.
```json
{
    "DisplayText": "Okay super, le numéro de téléphone, c'est le bon parce que j'ai reussiavousjoindrelasuperladressemailcestbienexample.truc@gmail.com.",
    "Duration": 108000000,
    "Id": "3c7cb860b362419e9f06293b8f5bd7e4",
    "NBest": [
        {
            "Confidence": 0.8691261,
            "Display": "Okay super, le numéro de téléphone, c'est le bon parce que j'ai reussiavousjoindrelasuperladressemailcestbienexample.truc@gmail.com.",
            "ITN": "okay super le numéro de téléphone c'est le bon parce que j'ai reussiavousjoindrelasuperladressemailcestbienexample.truc@gmail.com",
            "Lexical": "okay super le numéro de téléphone c'est le bon parce que j'ai réussi à vous joindre la super l'adresse mail c'est bien example point truc arobase gmail point com",
            "MaskedITN": "okay super le numéro de téléphone c'est le bon parce que j'ai reussiavousjoindrelasuperladressemailcestbienexample.truc@gmail.com",
```

**To Reproduce**
1. Say a sentence containing a email address, in french
2. Launch recognition

**Expected behavior**
The recognized sentence should be
`Okay super, le numéro de téléphone, c'est le bon parce que j'ai reussi a vous joindre super l'adresse mail c'est bien example.truc@gmail.com ?`

**Version of the Cognitive Services Speech SDK**
azure-cognitiveservices-speech 1.16.0

**Platform, Operating System, and Programming Language**
 - OS: Debian Bullseye
 - Hardware - x64
 - Programming language: Python

**Comment by fezuo** [comment]
Thank you for reporting this issue, we will improve email address display format and fix this case.

**Comment by chschrae** [comment]
Closing the issue to keep the issues fresh.
