### ISSUE TITLE
Blazor Server Side Example

### ISSUE THREAD

**Issue by martingholmes** [Azure-Samples/cognitive-services-speech-sdk#1437]
Hi, I am new to web development and trying to get going with Blazor. Is there any one with an example Blazor Server Side example of speech to text using browsers microphone?

**Comment by chschrae** [comment]
Hi there! 

Thanks for reaching out. Although we don't have a Blazor sample, it would seem that Blazor is able to run .NET assemblies and so I would imagine the .NET code would be the sample to try and follow. Have you tried that?

If you are having trouble with some code, could you share some of your code and describe where it doesn't work as expected?

**Comment by martingholmes** [comment]
Hi, I have my code wortking in C# in both console and winforms. It's the bit around accessing microphone in Blazor and JSinterop im struggling with. Would like to use StartContinuousRecognitionAsync() so would need access to the buffer stream of the microphone

**Comment by chschrae** [comment]
Since I'm not that familiar with Blazor, I'm not 100% sure what you need. But if you need to work with a stream instead of a microphone there are pull and push stream samples that show how to do that. Have you tried those?
