### ISSUE TITLE
[Speech Service SDK] Using proxy with node.js SDK.

### ISSUE THREAD

**Issue by javiergrandeveloper** [Azure-Samples/cognitive-services-speech-sdk#144]
HI Team,  I'm trying to use the Node.js SDK Speech Service behind a proxy but I don't find any method to do it.  I know that on the Java and .NET SDK exists a method setProxy but this method doesn`t exist on the node.js SDK.

Thanks.

**Comment by fmegen** [comment]
Hi @javiergrandeveloper,
currently, the node.js does not support proxies for https and websocket connections that it initiates.
Let me check what we are supporting right now.

kind regards,
 friedel

**Comment by wolfma61** [comment]
closing, not resolved, but will be in an upcoming release
