### ISSUE TITLE
Language Identification Continuous Recognition Sythesizing

### ISSUE THREAD

**Issue by SGNjogu** [Azure-Samples/cognitive-services-speech-sdk#1441]
I have a scenario where I need audio returned after speech has been translated using continuous recognition. The rest of the events work just fine for me.

Are there plans to have this implemented, and if so is there an approximate ETA?

My current consideration is to use Recognized to return text, and then convert that text to speech, which isn't the most ideal scenario.

I could also be wrong and may have missed something. Kindly advise.

**Comment by dargilco** [comment]
What programming language are you using?

See an example of how to do this in C++:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/cpp/windows/console/samples/translation_samples.cpp#L82

From the TranslationSynthesisEventArgs you can get the TranslationSynthesisResult which includes an audio buffer of the synthesized audio in the target language:
https://docs.microsoft.com/dotnet/api/microsoft.cognitiveservices.speech.translation.translationsynthesisresult?view=azure-dotnet

The same is true for C#.  Not sure about the other programming langauges. 

Darren

**Comment by SGNjogu** [comment]
I'm using C#.

For the examples given, synthesizing works just fine.

My scenario needs continuous language identification, as in this example:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/a3f9e4a63394acd8adc11252c6bcf7f247155b22/samples/csharp/sharedcontent/console/translation_samples.cs#L587

The synthesizing event for this is not in the documentation, and doesn't fire, but is exactly what I need. I am using FromMicrophoneInput() for AudioConfig.

**Comment by dargilco** [comment]
TranslationRecognizer in C# has a Synthesizing event with the audio buffer (https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.translation.translationrecognizer.synthesizing?view=azure-dotnet). You can use the TranslationRecognizer with or without Language ID (continuous or at-start) and for both cases the Synthesizing event should fire. Are you saying that this event is not firing for you? Does if fire if you use TranslationRecognizer without language ID?

**Comment by SGNjogu** [comment]
Yes, the event is defined in the recognizer, but for the specific recognizer in the example above, the Synthesizing event doesn't fire. My scenario requires two target languages, but even with one TargetLanguage, it still doesn't fire. It identifies the language the user is speaking and translates correctly, but I need this event to fire to get the translated audio.

**Comment by SGNjogu** [comment]
I am implementing the method  [https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/a3f9e4a63394acd8adc11252c6bcf7f247155b22/samples/csharp/sharedcontent/console/translation_samples.cs#L587]  as is.

The only difference is that instead of using a pre-recorded file as in

>  `using (var audioInput = AudioConfig.FromWavFileInput(@"en-us_zh-cn.wav"))`

I am using input from a microphone as 

> `using (var audioInput = AudioConfig.FromMicrophoneInput(_inputDevice.DeviceId))`

I have tried using a pre-recorded file as well, but Synthesizing still did not fire.

My setup requires two target languages (two people having a conversation). I need to identify the language each user is using continuously, and translate it for the other user. The Recognizing and Recognized events fire as expected.

**Comment by dargilco** [comment]
Thank you for the additional information. Can you please try to do recognition with language id, and see if you get the synthesizing events? I know this is not your scenario, but I want to make sure you get those events in your code, when not using LID. This will tell me there is something about LID feature that causes events to to be fired.

Also, for the failing case, can you please provide Speech SDK logs while doing recognition with LID, and not getting synthesizing events? https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging .

**Comment by SGNjogu** [comment]
I have tried both with and without language id. The Synthesizing event still doesn't fire. I have had to go around and use SpeechSynthesizer to convert text from the Recognized event to speech.

These are the logs with the Synthesizing event subscribed. 

[AzureSpeechLogFile.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/8361235/AzureSpeechLogFile.txt)

**Comment by yulin-li** [comment]
Hi @SGNjogu , from your log file, I found that the target languages are `fr-FR` and `en-GB`, as the doc says, the synthesizing event is fired only when there is single target languages

**Comment by dargilco** [comment]
Adding link to doc: https://docs.microsoft.com/azure/cognitive-services/speech-service/get-started-speech-translation?tabs=script%2Cwindowsinstall&pivots=programming-language-csharp#synthesize-translations

**Comment by SGNjogu** [comment]
Thanks @yulin-li @dargilco. 

The event firing with only one language makes sense to me. Would be pretty nice as an added feature though, firing the event depending on the results from the recognized event. That way, you get translated text, the language ids, and the translated audio.
