### ISSUE TITLE
Crash reported on iOS

### ISSUE THREAD

**Issue by gyuri-fluttech** [Azure-Samples/cognitive-services-speech-sdk#1442]
**Describe the bug**
A crash was reported on iOS but cannot reproduce it. 

**To Reproduce**
Please check the attached crash log.

**Expected behavior**
The sdk works without unexpected crashes

**Version of the Cognitive Services Speech SDK**
1.19.0

**Platform, Operating System, and Programming Language**
 - OS: iOS 
 - Hardware -ARM-64
 - Programming language: Swift
 
[crashlog.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/8333654/crashlog.log)

**Comment by jhakulin** [comment]
@gyuri-fluttech Thanks for the report, from the crashlog it is hard to identify the crash reason. Do you happen to have managed repro this problem? Would it be possible to share the app code how Speech SDK APIs are used ? Thanks!

**Comment by jhakulin** [comment]
@gyuri-fluttech Unfortunately we cannot proceed the issue without local repro or more information. Set pending close.
