### ISSUE TITLE
The main.py code for transcription using the Python SDK does not work

### ISSUE THREAD

**Issue by Remmy27** [Azure-Samples/cognitive-services-speech-sdk#1445]
**Describe the bug**
I have followed the steps to run the main.py speech transcription here: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python 

I have generated the client library and have used pip to install it. I've then set my keys and regions and other variables in the code and when I have run it I get the following error.

'swagger_client' has no attribute 'DefaultApi'

when I print(dir(cris_client)) I get:
 ['ApiClient', 'Component', 'Configuration', 'CustomSpeechDatasetsForModelAdaptationApi', 'CustomSpeechEndpointsApi', 'CustomSpeechModelEvaluationsApi', 'CustomSpeechModelsApi', 'CustomSpeechProjectsApi', 'CustomSpeechTranscriptionsApi', 'CustomSpeechWebHooksApi', 'Dataset', 'DatasetLocales', 'DatasetProperties', 'DatasetUpdate', 'Endpoint', 'EndpointLinks', 'EndpointProperties', 'EndpointPropertiesUpdate', 'EndpointUpdate', 'EntityError', 'EntityReference', 'Error', 'Evaluation', 'EvaluationProperties', 'EvaluationUpdate', 'File', 'FileLinks', 'FileProperties', 'InnerError', 'Links', 'Model', 'ModelCopy', 'ModelDeprecationDates', 'ModelFile', 'ModelLinks', 'ModelManifest', 'ModelProperties', 'ModelUpdate', 'PaginatedDatasets', 'PaginatedEndpoints', 'PaginatedEvaluations', 'PaginatedFiles', 'PaginatedModels', 'PaginatedProjects', 'PaginatedTranscriptions', 'PaginatedWebHooks', 'Project', 'ProjectLinks', 'ProjectProperties', 'ProjectUpdate', 'ServiceHealth', 'ServiceHealthApi', 'Transcription', 'TranscriptionProperties', 'TranscriptionUpdate', 'WebHook', 'WebHookLinks', 'WebHookProperties', 'WebHookPropertiesUpdate', 'WebHookUpdate', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'api', 'api_client', 'configuration', 'models', 'rest']

It looks like generating the client hasn't generated DefaultAPI but I've done it multiple times now and it still doesnt work. 

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using. 
I'm using v3.0 

**Platform, Operating System, and Programming Language**
 - OS: Windows
 - Hardware - x64,
 - Programming language: Python
 - Browser Chrome

**Additional context**
 - Error messages, stack trace, sample code to reproduce the issue, ...
 - Please provide full Speech SDK Log, as per the instructions [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging)?
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by chlandsi** [comment]
Hi @Remmy27, please try this url for generating the swagger: https://westus.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/export?DocumentFormat=Swagger&ApiName=Speech%20to%20Text%20API%20v3.0 while we investigate. Thanks!

**Comment by chlandsi** [comment]
This will be fixed shortly with #1448.

**Comment by 6lv1-blr** [comment]
In French because it's link to a french setting : 
For others locales than west-us I suppose you have to use a similar swagger download modification

Bonjour, pour la france j'ai eu besoin d'utiliser le fichier json suivant au lieu du fichier du Readme.md de l'exemple dans swagger
sinon j'obtenais l'erreur 'swagger_client' has no attribute 'DefaultApi'

https://francecentral.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/export?DocumentFormat=Swagger&ApiName=Speech%20to%20Text%20API%20v3.0

**Comment by chlandsi** [comment]
The sample is fixed. Thanks for notifying us, and sorry for the inconvenience!
