### ISSUE TITLE
How to run speech to text on a folder in blob container

### ISSUE THREAD

**Issue by heeyounglee** [Azure-Samples/cognitive-services-speech-sdk#1446]
I'm using this sample: https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/python/python-client/main.py

If I use URIs for a single file (RECORDINGS_BLOB_URI) or a container (RECORDINGS_CONTAINER_URI), the script works.
But if I set the URI of a folder, I get this error:

`Transcription failed: The recordings URI is invalid.`

How can i run it on a folder?

**Comment by chlandsi** [comment]
Hi @heeyounglee, this is currently not supported. You would need to enumerate the blobs with the prefix you want on your client side and use the API for multiple urls to transcribe them (up to 1000 urls are supported per request).
