### ISSUE TITLE
android java sdk repeat problem. 

### ISSUE THREAD

**Issue by ScholesMoneybrain** [Azure-Samples/cognitive-services-speech-sdk#1447]
**Describe the bug**
The continuous recognize function only work first time. 

**To Reproduce**
Using sample app, 
1. Build and run the app.
2. On the main activity, click 'recognize continuously' and check it works. 
3. Finish the main activity, re-start the main activity and click 'recognize continuously'. See the STT not work. 

It doesn't work even in case of pressing the 'stop' button and finish the activity. 

**Expected behavior**
The STT recognize the speech after restart activity when 'recognize continuously' clicked or 
restart after 'stop' and 'recognize continuously' buttons clicked again. 

**Version of the Cognitive Services Speech SDK**
1.20.0

**Platform, Operating System, and Programming Language**
 - OS: android 9.0
 - Hardware -  ARM
 - Programming language: Java

**Additional context**

**Comment by dargilco** [comment]
@ScholesMoneybrain this is Darren from the Speech SDK team. Thank you for posting this. I will try later today to run this on my Android phone to confirm your observation. I'll post an update after I do that.

**Comment by ScholesMoneybrain** [comment]
@dargilco Thanks for the response. I found that "microphoneStream.close()" made it work again when I finish using it.

**Comment by dargilco** [comment]
@ScholesMoneybrain That's good news. If you have a fix for this sample, can you please create a pull request for this fix? I will test it and approve the fix.

**Comment by dargilco** [comment]
@ScholesMoneybrain I run the sample app as-is on my Samsung Galaxy S10 phone running Android version 12. I'm able to do repeated continuous recognition sessions, so it seems to be work on my phone: I press "Recognize continuously", say a few utterances, then press "Stop". Then press "Recognize continuously" again, say a few utterances, then press "Stop" (repeat that a few times). In all cases I get recognition results. Is that the scenario that was not working for you? I could not understand what you meant by "Finish the main activity, re-start the main activity". 
Perhaps something has changed in the Android audio APIs between version 9 and 12, as you say calling "microphoneStream.close()" fixed the problem for you, and this method only includes  Android AudioRecorder API calls:
    public void close() {
        this.recorder.release();
        this.recorder = null;
    }

Unfortunately I don't have a device with Android version 9 to test on.

**Comment by ScholesMoneybrain** [comment]
"Recognize continuously" again, say a few utterances, then press "Stop" => This scenario also works for me. 
"Close the app by pressing back button and restart app and try again" => didn't work for me. 
Maybe it is audio api issue. And I just have a device running android 9.

**Comment by dargilco** [comment]
Thanks for the clarification @ScholesMoneybrain . I start "Recognize continuously", it recognized my voice, then I press the Phone's back button, then I re-launch the app. I see that it continues to recognize my voice (I do not need to press anything). So it seems to be working for me. 
If you show me where you added the call to "microphoneStream.close()", or send a PR yourself, I will consider adding it to our code even though I can't get a repo of this issue myself. Otherwise I'll close this issue. Thanks!

**Comment by ScholesMoneybrain** [comment]
I called 'microphoneStream.close()' on 'onDestroy'. You can close this. Thanks!
