### ISSUE TITLE
ClickOnce deployment --> missing dlls

### ISSUE THREAD

**Issue by GRPDAN01** [Azure-Samples/cognitive-services-speech-sdk#1451]
**Describe the bug**
When deploying a C# application using the Microsoft.CognitiveServices.Speech NuGet, only the Microsoft.CognitiveServices.Speech.csharp.dll is sent to the output

**To Reproduce**
1. Create a new C# console (.NET Framework) project
2. Add Microsoft.CognitiveServices.Speech NuGet to the project
3. Build
4. Check the output directory --> All references are present
5. Publish
6. Check the publish directory --> Only the ***.Speech.csharp.dll is present

**Expected behavior**
This list of dlls should be present in the publish directory:
- Microsoft.CognitiveServices.Speech.core.dll
- Microsoft.CognitiveServices.Speech.csharp.dll
- Microsoft.CognitiveServices.Speech.extension.audio.sys.dll
- Microsoft.CognitiveServices.Speech.extension.codec.dll
- Microsoft.CognitiveServices.Speech.extension.kws.dll
- Microsoft.CognitiveServices.Speech.extension.lu.dll
- Microsoft.CognitiveServices.Speech.extension.mas.dll

**Version of the Cognitive Services Speech SDK**
1.20.0 (same issue ith 1.19.0)

**Platform, Operating System, and Programming Language**
 - OS: Windows 11 Pro
 - Programming language: C#, VS2022, .NET Framework 4.7.2

**Additional context**
 - When trying to use the cognitive services from a client using ClickOnce deployment and checking the output using the Remote Tools for VS, you can see that the application can't find the ***.Speech.core.dll and so you can't start a speech recognition

**Comment by ralph-msft** [comment]
Thanks for trying the Microsoft Cognitive Services Speech SDK. Including native dependencies from Nuget packages when using ClickOnce to publish an application seems to be a general pain point.

The workaround is to explicitly add the native dependencies to your project as "Content", at which point the publish step will pick up those file. Specifically, open up your project file (```.csrpoj```) in your text editor of choice and can add the following just before the closing ```</Project>``` at the end:
```XML
  <ItemGroup>
    <Content Visible="false" Include="$(SpeechNativeDllDir)\Microsoft.CognitiveServices.Speech.core.dll" />
    <Content Visible="false" Include="$(SpeechNativeDllDir)\Microsoft.CognitiveServices.Speech.extension.audio.sys.dll" />
    <Content Visible="false" Include="$(SpeechNativeDllDir)\Microsoft.CognitiveServices.Speech.extension.lu.dll" />
    <Content Visible="false" Include="$(SpeechNativeDllDir)\Microsoft.CognitiveServices.Speech.extension.kws.dll" />
    <Content Visible="false" Include="$(SpeechNativeDllDir)\Microsoft.CognitiveServices.Speech.extension.codec.dll" />
    <Content Visible="false" Include="$(SpeechNativeDllDir)\Microsoft.CognitiveServices.Speech.extension.mas.dll" />
  </ItemGroup>
```

After this, you the needed native DLLs will start showing up in the list of files to publish:
![image](https://user-images.githubusercontent.com/18542438/160928080-eac6ee15-7a35-4f4e-9403-15d42e248345.png)

**Comment by GRPDAN01** [comment]
Thanks a lot @ralph-msft . Your suggestion resolved this issue. 👍
