### ISSUE TITLE
Is there an API health check dashboard or notify developer tool?

### ISSUE THREAD

**Issue by Jun711** [Azure-Samples/cognitive-services-speech-sdk#1455]
`westus2 fr-CA-SylvieNeural` has been down for quite some time

**Comment by dargilco** [comment]
@yulin-li are you aware of any issues with the above region/voice-name?

**Comment by yulin-li** [comment]
@Jun711 , sorry for this. I believe it's a service issue. Could you use other regions first? I will check with service guys and let you know when it recovers.

**Comment by Jun711** [comment]
@yulin-li yea, I changed the region to `westus` for `fr-CA-SylvieNeural` and it was ok. btw, other voices that I use are working normally using `westus2` endpoint

**Comment by softrime** [comment]
@Jun711 the issue was fixed. fr-CA-SylvieNeural is back in westus2. Please have a check.
