### ISSUE TITLE
[express-as] element is not allowed.

### ISSUE THREAD

**Issue by ylz201** [Azure-Samples/cognitive-services-speech-sdk#1456]
**Describe the bug**

**To Reproduce**
1. client-sdk version 1.19.0  
2. 
3. invoke method: synthesizer.StartSpeakingSsml(text)

**Expected behavior**

**Version of the Cognitive Services Speech SDK**
1.19.0  

**Platform, Operating System, and Programming Language**
 - OS: Mac
 -JDK 1.8
 - Programming language: Java

**Additional context**
Respones messages:
 CANCELED: ErrorDetails=Connection was closed by the remote host. Error code: 1007. Error details: [express-as] element is not allowed. Currently only [speak], [voice] and [prosody] elements are allo USP state: 3. Received audio size: 0 bytes.

**Comment by yulin-li** [comment]
Hi @ylz201 could share the SSML you use?

**Comment by pankopon** [comment]
Closed since no response from the customer, please open a new issue if more support is needed.
