### ISSUE TITLE
Planned support for CentOs?

### ISSUE THREAD

**Issue by phxql** [Azure-Samples/cognitive-services-speech-sdk#146]
Hi,

currently we are unable to use the SDK as it only works with Ubuntu Linux. Our servers run on CentOS and we would like to use the SDK. Are there any plans to support CentOS?

Thanks!

**Comment by wolfma61** [comment]
yes, there are plans (<- not there is a real useful answer)

Unfortunately it won't be in the next update (later this month). 
Before promising something we can't live up to, I won't mention a date... sorry...
red-hat and centos are on the short list ... but really - no promises ...

thx
Wolfgang

**Comment by wolfma61** [comment]
sorry - didn't happen so far.
it is still on the wishlist, but no date available.
