### ISSUE TITLE
Wrong error message during the usage of Custom speech for Fr

### ISSUE THREAD

**Issue by Farhad-Heybati** [Azure-Samples/cognitive-services-speech-sdk#1460]
**Describe the bug**
I get an error:
Number of success: 0
Number of failure: 1
Error message: [
  {
    filename: audio.wav
    inputText: Cliquez sur le nom du test pour afficher la pag...
    message:  Error: normalized text is empty.
    status: Failed
  }
]
But the test file is not empty.
**To Reproduce**
1. Use the following for test: C:\Users\faheybat\OneDrive - Microsoft\1-RATP\speech-sdk-master\cognitive-services-speech-sdk-master\sampledata\customspeech\fr-FR\testing\test-audio-and-trans.zip
2. the trans document text is not empty  but the uploads end in error stating that the transcript file is empty

**Expected behavior**

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - please be specific
 - Hardware - x64, x86, ARM, ...
 - Programming language: C#, C++, Java, JavaScript, Objective-C, Python
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific

**Additional context**
 - Error messages, stack trace, sample code to reproduce the issue, ...
 - Please provide full Speech SDK Log, as per the instructions [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging)?
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by adbds** [comment]
When uploading a data set with transcription, the first step consists in normalizing the text. It seems in the present case that the single line couldn't be normalized. This could happen for multiple reasons. Could you please share the transcription?

**Comment by pankopon** [comment]
Closed since no response from the customer, please open a new issue if more support is needed.
