### ISSUE TITLE
I seem to be receiving spurious transcripts -- how best to debug this

### ISSUE THREAD

**Issue by davehorton** [Azure-Samples/cognitive-services-speech-sdk#1463]
**Describe the bug**
I am doing some testing where I mute my phone in order to send a silence stream to Azure, but I am finding that frequently after anywhere from 5 to 20 seconds it will send me back a transcript, usually a single word often "yes", or even a single letter "i".  I have made recordings of the audio streams that I am sending to verify they are nothing but silence packets.  

Here is an example such response when I was sending silence:

 {"Id":"aac5d52c662a44b38dde27f6de04aee9","RecognitionStatus":"Success","Offset":500000,"Duration":199600000,"DisplayText":"","NBest":[{"Confidence":0.0,"Lexical":"","ITN":"","MaskedITN":"","Display":""},{"Confidence":0.66225314,"Lexical":"yes","ITN":"yes","MaskedITN":"yes","Display":"yes"},{"Confidence":0.44512013,"Lexical":"yeah","ITN":"yeah","MaskedITN":"yeah","Display":"yeah"},{"Confidence":0.48643345,"Lexical":"yep","ITN":"yep","MaskedITN":"yep","Display":"yep"},{"Confidence":0.5523342,"Lexical":"no","ITN":"no","MaskedITN":"no","Display":"no"}]}.

I can provide the wave file corresponding to this call if helpful, I have examined it can find no audio artifacts that should have resulted in a transcript.

**To Reproduce**

I call into my system, mute my phone and wait several seconds while doing streaming recognition

**Expected behavior**

I expected to either receive no transcript or a no speech detected event.

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.
1.20

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - please be specific
 - Hardware - x64, x86, ARM, ...
 - Programming language: C#, C++, Java, JavaScript, Objective-C, Python
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific

Debian 10

**Comment by jhakulin** [comment]
@davehorton Thanks for creating the issue, we are investigating and let you know what might be causing this.

**Comment by hoskha** [comment]
@davehorton Thanks for reporting this issue. 
The speech recognition engine can occasionally produce random words due to silence or noise fed in for a long period of time. We do have a postprocessing step to catch such instances, and empty the result. In your case, you can see the top result was emptied as expected. We will work to empty the rest of the results as well in a future release. However, as always, it is recommended to ignore the non-top results, if the top result is empty, even if the microphone is capturing real speech.

**Comment by davehorton** [comment]
when you say "top result" do you mean the very first result in the NBest list?  I have been ordering them by confidence before processing, and then looking at the one with highest confidence.  Is there some meaning to the original NBest order?

**Comment by hoskha** [comment]
It is not recommended to sort based on confidence. The order you get originally is the best order based on recognition logic. However, we add some supplemental confidence score which you can use in the app to decide whether to caution the user or maybe ask for a retry. But should not be used for ordering.

**Comment by davehorton** [comment]
OK, thanks for the clarification on this.  I have modified my code to look at the "top" result to see if this is the case (emptied).  I will close the issue now, and re-open if I have any questions or issues, but this clarification has been helpful.
