### ISSUE TITLE
Not able to delete audio file in Speech service

### ISSUE THREAD

**Issue by kamrapooja** [Azure-Samples/cognitive-services-speech-sdk#1464]
**Describe the bug**
I am using speechSDK in python. Using FFMPEG i am getting audio from video that i have and then using that audio in speech sdk. And when speech to text is done,i am trying to delete this audio file in session_stopped event. But i am not able to delete it.

**To Reproduce**

1.  import azure.cognitiveservices.speech as speechsdk
2. speech_config = speechsdk.SpeechConfig(subscription=key, endpoint=endpoint)
3. speech_config.request_word_level_timestamps()
4. audio_config = speechsdk.audio.AudioConfig(filename=audio_file)   
5. speech_recognizer.session_stopped.connect(self.stop_cb)
6. def stop_cb(self, evt):
        self.speech_recognizer.stop_continuous_recognition()
        os.remove(audio_file)
but here os.remove(audio_file) is giving exception. //using by process

**Expected behavior**
When speech to text is completed i should be able to delete audio file

**Version of the Cognitive Services Speech SDK**
1.17.0

**Platform, Operating System, and Programming Language**
 - OS: Windows
 - Hardware - x64
 - Programming language: Python
 - Browser [e.g. Chrome, Safari] (if applicable) - NA

**Comment by jhakulin** [comment]
@kamrapooja Thanks for the report. We will investigate this.

If you try to remove the audio file in your program outside of the stop event handler and after the stop_continuous_recognition() has been executed, do you see any problems?

**Comment by pankopon** [comment]
@kamrapooja The input file remains open until the recognizer using it is closed. Currently this requires the recognizer goes out of scope, for example:
```
def recognize_speech():
    speech_config = speechsdk.SpeechConfig(subscription=key, endpoint=endpoint)
    audio_config = speechsdk.audio.AudioConfig(filename=audio_file)
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)
    ...

if __name__ == '__main__':
    recognize_speech()
    os.remove(audio_file)
```

We have a work item to add close/exit methods to SpeechRecognizer (among others) so that this can be controlled in more detail, ref. #1228.

**Comment by kamrapooja** [comment]
> @kamrapooja Thanks for the report. We will investigate this.
> 
> If you try to remove the audio file in your program outside of the stop event handler and after the stop_continuous_recognition() has been executed, do you see any problems?

I have tried this as well, but it is not working.

**Comment by kamrapooja** [comment]
> @kamrapooja The input file remains open until the recognizer using it is closed. Currently this requires the recognizer goes out of scope, for example:
> 
> ```
> def recognize_speech():
>     speech_config = speechsdk.SpeechConfig(subscription=key, endpoint=endpoint)
>     audio_config = speechsdk.audio.AudioConfig(filename=audio_file)
>     speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)
>     ...
> 
> if __name__ == '__main__':
>     recognize_speech()
>     os.remove(audio_file)
> ```
> 
> We have a work item to add close/exit methods to SpeechRecognizer (among others) so that this can be controlled in more detail, ref. #1228.

Is close method available for python?

**Comment by pankopon** [comment]
@kamrapooja There is no close method yet, it's on the backlog for some future release. So you should limit the scope of speech_recognizer as in the example; run recognition inside a function and remove the input file elsewhere (main level or another function) after the function to run recognition has ended.

**Comment by kamrapooja** [comment]
Ok.
