### ISSUE TITLE
Punctuation is lost when using ConversationTranscriber since 13th, April, by node.js, ja-JP, eastasia

### ISSUE THREAD

**Issue by songdai-xenera-jp** [Azure-Samples/cognitive-services-speech-sdk#1468]
**Describe the bug**
I recently found the punctuation in speech-to-text result was lost. I am using region: eastasia, language: ja-JP, ConversationTranscriber, 

Here is the sample:

            let pushStream = AudioInputStream.createPushStream(AudioStreamFormat.getWaveFormatPCM(sampleRate, 16, channels));
            let audioConfig = AudioConfig.fromStreamInput(pushStream);
            let speechConfig = SpeechTranslationConfig.fromSubscription();
            speechConfig.setProperty("ConversationTranscriptionInRoomAndOnline", "true");
            speechConfig.setProperty("DifferentiateGuestSpeakers", "true");
            speechConfig.requestWordLevelTimestamps();
            speechConfig.setServiceProperty("transcriptionMode", "RealTime", ServicePropertyChannel.UriQueryParameter);
            speechConfig.speechRecognitionLanguage = language

            let conversation = Conversation.createConversationAsync(speechConfig);
            let transcriber = new ConversationTranscriber(audioConfig);

            transcriber.joinConversationAsync(conversation, function () {
                    transcriber.transcribed = function (s, e) {
                        logger.info(`socket id=${socket.id} conversation-transcriber transcribed sessionid=${e.sessionId} speakerId=${e.result.speakerId} text=${e.result.text}`);
                    }
            }`

**To Reproduce**
 Run codes above you will find this issue, the punctuation was missing, this screenshot was token this morning.
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/84056479/163749705-d4b02799-b36f-4cab-8665-8d42a688693a.png">

**Expected behavior**
Could you add the punctuation back. Or could you please explain what had happened ? Our source codes had not been changed recently.

**Version of the Cognitive Services Speech SDK**
Our sdk version is `"microsoft-cognitiveservices-speech-sdk": "1.19.0",`

**Platform, Operating System, and Programming Language**
We are running in Azure cloud.

**Additional context**
 - Error messages, stack trace, sample code to reproduce the issue, ...
 - Please provide full Speech SDK Log, as per the instructions [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging)?
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by pankopon** [comment]
@msjunzh Can you please comment, is this a known issue?

**Comment by songdai-xenera-jp** [comment]
Hi, hi, can you confirm whether this is an inner issue at least? Our client is quite confused about this.

**Comment by pankopon** [comment]
@songdai-xenera-jp Hi, the latest status is that this seems to be a service issue indeed, investigation is ongoing and we'll update as soon as there is more info. (@msjunzh @BrianMouncer for follow-up.)

**Comment by songdai-xenera-jp** [comment]
@pankopon Hi, hi, thank you for your reply. May I know your release plan for this issue? Is there an exact release date for this one, we have to reply to our client before 1st, May, sorry but a precise date will be appreciated.

**Comment by songdai-xenera-jp** [comment]
@pankopon Thank you very much! We had tested and it worked as expected now. The punctuation is back, thank you!

**Comment by songdai-xenera-jp** [comment]
close this issue now
