### ISSUE TITLE
Speech Recognition would need some Enhancement

### ISSUE THREAD

**Issue by robintel** [Azure-Samples/cognitive-services-speech-sdk#147]
**Description**

I'm trying to get some speech recognition from fr-FR when the speech has some background music, and is acquired via a telephone call. For this reason, speech recognition seems to fail in its entirety.

SDK version is 1.1.0.

**Describe the solution you'd like**

I would have expected that at least some part of the speech would be recognized. 

**Describe alternatives you've considered**

I've managed to get this partially working, by trimming the first 3-5 seconds of audio.

**Additional context**
Attached, please find the audio files, one that worked (partial text only), and one that didn't (full text).

[Audio Samples.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/2812202/Audio.Samples.zip)

**Comment by zhouwangzw** [comment]
Could you please provide more details about "speech recognition seems to fail in its entirety."? I tried both audio files in the zip you provided, and I could get some results back, but I do not understand French so can not judge whether they are completed or how accurate they are. 
For example, for the long one: 
    SpeechStartDetected received: offset: 7400000.
RECOGNIZED (elapsedTicks=78017787): Text=Déjeuner chez BMW pour le premium FN aie le temps à votre service de 8 h 30 à 18 h du lundi au vendredi., Offset=7400000, Duration=00:00:14.1200000
RECOGNIZED (elapsedTicks=42606155): Text=Merci de bien vouloir renouveler votre rappel., Offset=148700000, Duration=00:00:08.1100000
SpeechEndDetected received: offset: 260000000.

Thanks,
Zhou
