### ISSUE TITLE
Cannot Recognize Speech Error: Error occurred while processing 'audio.wav'. Invalid WAV header in file, RIFF was not found

### ISSUE THREAD

**Issue by nileenas** [Azure-Samples/cognitive-services-speech-sdk#1476]
Hi,
I captured  one voice message from WhatsApp and it saved as wav file using node js. But I pass this wav file for speech translation using JavaScript sdk it not showing anything and also try this file into demo app also, in demo app I got error "Cannot Recognize Speech Error: Error occurred while processing 'audio.wav'. Invalid WAV header in file, RIFF was not found".

![WhatsApp Image 2022-04-27 at 2 27 04 PM](https://user-images.githubusercontent.com/99943566/165487408-b2daebe6-e86f-41df-b5a8-2dbf6b227677.jpeg)

This is my audio media information

**Comment by BrianMouncer** [comment]
@nileenas 

What platform are you trying this on, and do you have GStreamer installed?

To read Opus and other compressed formats, you need to decode the audio file. 
The SDK needs RAW PCM under the covers.  You can either convert the audio ahead of time, or on some system you can install GStreamer and the speech extension will decode the audio for you.

[General overview](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams?tabs=linux%2Cdebian%2Cjava-android%2Cterminal&pivots=programming-language-csharp)

[C# example]( https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/0b2d96951e5620c53d60dab6b53647d45d149bf8/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L266 ) 

[Linux example](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/cpp/linux/compressed-audio-input/README.md)

**Comment by nileenas** [comment]
I am captured one voice message from WhatsApp its voices format is ogg and it is encoded by base64 and written into wav extension file. I am using speech to text JavaScript sdk  with Bot framework sdk with node js.

**Comment by brandom-msft** [comment]
@nileenas The JavaScript SDK does not support compressed audio, you'll need to convert to WAV in the default format - some [details can be found here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams?tabs=windows%2Cdebian%2Cjava-android%2Cterminal&pivots=programming-language-javascript).

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
