### ISSUE TITLE
Getting the Voice Signatures of Guests in Conversation Transcription

### ISSUE THREAD

**Issue by danieljlevine** [Azure-Samples/cognitive-services-speech-sdk#1477]
Hi,

I know that I can enroll speakers a-priori to create signatures and then add them to conversations so they they can be identified by name using their speech signatures.  However, I would like to also be able to get guest signatures (Guest_0, Guest_1, etc.) either during the conversation or at the end).  My plan would be to upload these signatures with an identifier I provide to Azure so they could be used to identify previously encountered speakers by name in future conversations.

How can I get Guest_0 or Guest_1's voice signatures back so I can use them again in the future?

**Comment by BrianMouncer** [comment]
Conversational Transcription Service does not allow you to download the temporary voice profiles built to tag Guest_0 and Guest_1 users in a meeting, especially for identifying them by name in other recorded meetings.  This would go against the responsible use of ai polices of getting each users permission/consent to use the data to build a profile to identify them in meeting.  The user should also be informed they can remove their profile and delete their training data at any time.  It would be difficult to get consent and reliably inform the user of the profile and how to delete it, if the profile was created on their behalf using audio from the meeting they were in and about to leave.

I can see real value in using the meeting audio to save the user user time recording training data, but the user still needs to give consent before it is used. I think a good workflow would be for the user be guided to a profile creation page, to be able to listen to the training audio automatically selected from the meeting to make sure it is only of them and the content is something they are ok using for training, and have the user record one more audio of them reading the consent text to build a voice profile of them.

**Comment by danieljlevine** [comment]
Thanks, I understand the issue better now for why this is not a permitted capability. I will probably just generate the signatures the traditional way a-priori so that conversations are labeled by speaker from the start.
