### ISSUE TITLE
Python SDK Conversation transcription not showing the conversation

### ISSUE THREAD

**Issue by anastazijaverovic** [Azure-Samples/cognitive-services-speech-sdk#1478]
Hey,
Using your sample code, I'm trying to run conversation transcription with speaker differentiation in Python. I've replaced the placeholders with subscription code, region, and wav file location.
Once I run the function, the session starts, but there is no text and no user id:

SESSION STARTED: SessionEventArgs(session_id=0fd49b59cdff413b800d5248e06438fc)
CANCELED ConversationTranscriptionCanceledEventArgs(session_id=0fd49b59cdff413b800d5248e06438fc, result=ConversationTranscriptionResult(result_id=9115c190042248399c93123fa059b82b, **user_id=, utterance_id=, text=**, reason=ResultReason.Canceled))
CLOSING ConversationTranscriptionCanceledEventArgs(session_id=0fd49b59cdff413b800d5248e06438fc, result=ConversationTranscriptionResult(result_id=9115c190042248399c93123fa059b82b, user_id=, utterance_id=, text=, reason=ResultReason.Canceled))
SESSION STOPPED SessionEventArgs(session_id=0fd49b59cdff413b800d5248e06438fc)
CLOSING SessionEventArgs(session_id=0fd49b59cdff413b800d5248e06438fc)

Thanks!

**Comment by jhakulin** [comment]
@anastazijaverovic Thanks for the report. Currently CTS is only working with 8 channel wave recorded with the specific microphone array configuration as described here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk-microphone. I know that this requirement is not easy for the customers at all and thus we are working on to make the experience simpler by enabling single channel.

Could you please share the wave file you were using ?

**Comment by anastazijaverovic** [comment]
Hi, thanks for the info! Tried again with another wave file, and it worked.

**Comment by glecaros** [comment]
Closing as it seems the issue was resolved.
