### ISSUE TITLE
Unity / Mac OS not including libMicrosoft.CognitiveServices.Speech.core.dylib in builds

### ISSUE THREAD

**Issue by abethke** [Azure-Samples/cognitive-services-speech-sdk#1479]
Plugin works in Unity 2019.3.0f6 editor on Mac OS (Big Sur) but whenever I build it keeps complaining that..

```
System.DllNotFoundException: libMicrosoft.CognitiveServices.Speech.core.dylib
  at (wrapper managed-to-native) Microsoft.CognitiveServices.Speech.Internal.SpeechConfig.speech_config_from_subscription(intptr&,string,string)
  at Microsoft.CognitiveServices.Speech.SpeechConfig.FromSubscription (System.String subscriptionKey, System.String region) [0x00007] in <b8dd20b6ccf24a32b5099c49029fcb4b>:0 
  at SecondSoulVoice.Initialize () [0x0003e] in <4b66316e05d04f90a2d86cc777dc6101>:0 
  at Main+<Awake>d__74.MoveNext () [0x005aa] in <4b66316e05d04f90a2d86cc777dc6101>:0 
```

I've tested with the latest example project and Speech SDK as well as using this successfully in an iOS project.  The problem is only with the Mac OS build.

**Comment by BrianMouncer** [comment]
Did I read that correctly?  it works in the editor, but fails when run as a standalone application?
There are some steps in the readm.md file on setting up and running as a stand alone app, did those instructions help at all?

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/csharp/unity/from-microphone/README.md#build-and-run-the-sample-as-a-stand-alone-desktop-application

**Comment by abethke** [comment]
That is correct but I'm running Unity and the standalone app on a Mac. 
No, the additional instructions were not useful for resolving this issue. 
To the best of my knowledge despite setting up the assembly correctly to target a Mac it is still being stripped from the published app.

![image](https://user-images.githubusercontent.com/9933215/165936934-a21cab94-beaf-4071-929d-b116aea46e6e.png)

**Comment by jhakulin** [comment]
@abethke There is following additional information when running standalone app. Have you done that ?

Navigate to the HelloWorld_Data/Plugins folder in your build output folder. Copy the DLL Microsoft.CognitiveServices.Speech.core.dll into the HelloWorld_Data/Managed folder.

**Comment by jhakulin** [comment]
@abethke Verified that MacOS standalone app worked directly using Unity 2019.4.22f1, quickstart https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/unity/from-microphone and the latest Speech SDK from https://aka.ms/csspeech/unitypackage. 

Not clear why deployment does not work for you, you can try to update to latest Unity LTS version as your version seems old, see https://unity3d.com/unity/qa/lts-releases

**Comment by abethke** [comment]
Doing the manual copy of the dylib file to the Managed folder worked for me. 

Thanks so much for the help @jhakulin
