### ISSUE TITLE
Python :: recognize_once_async() example :: extended

### ISSUE THREAD

**Issue by roman-telepathy-ai** [Azure-Samples/cognitive-services-speech-sdk#148]
HI all,

first, thanks for providing these examples, which are very useful.

My question: could you please provide an example how to use `result_future = speech_recognizer.recognize_once_async()` with IOLoop (when one is available already before initiating the recognition.

THanks in advance

**Comment by chlandsi** [comment]
Hi,
the asynchronous methods in the Python package don't use the asyncio framework built into Python and are thus independent of any `IOLoop`. On the `ResultFuture`, you can call `.get()` to get the final result of asynchronous single shot recognition, which is a blocking call. However, subscribing to the various signals the different recognizers send gives you probably more flexibility and also more information than just the final result; have a look at the samples for continuous recognition on how they can be used.

**Comment by roman-telepathy-ai** [comment]
@chlandsi thx for reply. your answer gives me the direction.

Just curious to know, `.recognize_once_async()` runs in a thread? any details on implementation?

**Comment by chlandsi** [comment]
Yes, the recognition runs in a thread separate from Python. Only the callbacks are again executed by the Python interpreter, under the GIL, but not on the recognition thread.

**Comment by roman-telepathy-ai** [comment]
ok got it. Thanks a lot!

I need to threat it as *blocking code*. Thanks!

**Comment by chlandsi** [comment]
I'm not sure if I made myself clear, just to clarify:
`result = recognize_once_async()` is nonblocking. `result.get()` is blocking, but you don't need to call it if you can work with event callbacks instead.

**Comment by roman-telepathy-ai** [comment]
I understood it correctly - will try it. Probably the result or callback function should be returned as future.
thx

**Comment by roman-telepathy-ai** [comment]
@chlandsi wait... so it is possible to use callbacks with `recognize_once_async()` **AND** with `start_continuous_recognition()` (closing with `stop_continuous_recognition()` respectively)?

Whereby for `recognize_once_async()` I would need to define the callback for `speech_recognizer.recognized` only?

if so, then it might work.

**Comment by chlandsi** [comment]
Yes, you can use all the callbacks the recognizer offers both with recognize_once_async and with continuous recognition.
________________________________
