### ISSUE TITLE
Node support for STT using Mic

### ISSUE THREAD

**Issue by priyankark** [Azure-Samples/cognitive-services-speech-sdk#1480]
**Is your feature request related to a problem? Please describe.**
The docs mention that the SDK doesn't support STT using Mic for the Node version of the package. We were able to get this working using a combination of few external packages. 

I had raised a request if we could update the docs with the sample we have (https://github.com/MicrosoftDocs/azure-docs/issues/91950) so that users who want use the Node version of the SDK aren't blocked by the limitation and was asked to contribute here. I would be happy to raise a PR.

**Describe the solution you'd like**
SDK can support Mic based STT.

**Describe alternatives you've considered**
Used external packages to handle Mic streaming.

**Additional context**

**Comment by brandom-msft** [comment]
Thanks for opening the issue and your contributions, @priyankark. I've notified the team so they can find the best next step, please stay tuned.

**Comment by glharper** [comment]
@priyankark Thanks for opening this issue, a sample demonstrating STT in Node on windows using microphone input would be much appreciated. Please open a PR, and include a readme describing any out-of-band pre-requisites (like SOX) required, and installation steps for those pre-requisites.

**Comment by pankopon** [comment]
Closing the issue as the PR has been approved and merged.
