### ISSUE TITLE
How to store transcriptions in subdirectory of container

### ISSUE THREAD

**Issue by BernardWez** [Azure-Samples/cognitive-services-speech-sdk#1483]
I'm following this sample: https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/python/python-client/main.py.

I'm trying to store the transcriptions in a specific sub-directory of my storage container using the `destinationContainerUrl` parameter. (SAS url is generated for that directory). However, this leads to an InvalidRequest error with the following message:

`The property transcription.properties.DestinationContainerUrl is not a SAS URL for a container.`

Is there a way to store the transcriptions in a specific directory within a container or is this simply not supported?

**Comment by chlandsi** [comment]
This is not supported at the moment; the SAS Uri needs to be at the container level. There is no control over the location of the generated blobs with the current API.
