### ISSUE TITLE
getting status of transcription in Azure STT

### ISSUE THREAD

**Issue by haldernayan** [Azure-Samples/cognitive-services-speech-sdk#1484]
Hi,

We are using Azure Ingestion client to do transcription. Is there a way to programmatically check the status of transcription when it is complete within Azure Ingestion Client.

**Comment by HenryvanderVegte** [comment]
Hi @haldernayan, 

I'm not sure if I got your question correctly, but we already check the status of the transcription programmatically inside the FetchTranscriptionFunction here:

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/b2a2074734d920fb88f9cdc2a4cebcfe6883eafb/samples/ingestion/ingestion-client/FetchTranscription/TranscriptionProcessor.cs#L51

Another option would be to listen to blob created events as soon as the transcriptions are written to the blob storage:
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-event-overview

Hope this helps!

**Comment by HenryvanderVegte** [comment]
no further response, closing now.
