### ISSUE TITLE
What is the difference between PushStream and PullStream?

### ISSUE THREAD

**Issue by CodingOctocat** [Azure-Samples/cognitive-services-speech-sdk#1489]
The samples I've seen all use `PushStream`, so when do I use `PullStream`?

If you need to coding `SynthesizeAudioToStreamAsync()`, then you need to use `AudioOutputStream.CreatePushStream();` or `AudioOutputStream.CreatePullStream();`?

**Comment by coin8086** [comment]
The official document should really make it clear. I was rather confusing, too!
