### ISSUE TITLE
[Chrome extension] Refused to load the script

### ISSUE THREAD

**Issue by DelalSeletli** [Azure-Samples/cognitive-services-speech-sdk#1494]
Hi, 
I am trying to create an extension that can use Azure cognitive service sdk to make speech to text. Everything worked fine with the mv2 extension but since i have to migrate to mv3 i'm having some trouble. Step by step i'm trying to make it all works. Now i'm stuck with an error

> Refused to load the script 'blob:chrome-extension://extension_id/{...}' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback

I'm having this issue since i'm trying to implement the Azure sdk in my web accessible resources which is an iframe to make all the retranscription. 

Here is my code : 

**audiosources.html**

```
<!DOCTYPE html>
<html>
    <body>
        <script src="distrib/browser/microsoft.cognitiveservices.speech.sdk.bundle.js"></script>
        <script src="audiosources.js"></script>
    </body>
</html>
```

**audiosource.js**

```
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    switch(message.type) {
        case "startStreaming":
            startStreaming(message, sender, sendResponse);
            break;
        case "init":
            console.log("init");
            break;
    }
    sendResponse();
});

function startStreaming(message, sender, sendResponse) {
    for (const tabId in Live) {
        chrome.tabs.sendMessage(parseInt(tabId), {
            type: "removeTranscript",
        });
        stopStreaming(tabId);
    }
    captureUser(sender.tab.id);
}

function captureUser(tabId) { 
    audioConfigUser = SpeechSDK.AudioConfig.fromMicrophoneInput(microphoneId);
    recognizerUser = new SpeechSDK.SpeechRecognizer(
        speechConfig,
        audioConfigUser
    );
    console.log("recognizerUser : ", recognizerUser);
    recognizerUser.startContinuousRecognitionAsync();
    recognizerUser.recognized = (s, e) => {
        toContentUser(tabId, e.result.text);
    };
}
```

the error occurs when i'm using the function : 

> startContinuousRecognitionAsync()

**manifest.json**

```
{
    "manifest_version": 3,
    "version": "1",
    "name": "Extension stt Azure MV3",
    "minimum_chrome_version" : "93",
    "content_scripts": [
        {
            "matches": ["<all_urls>"],
            "js": ["content.js",
                    "public/js/jquery-3.6.0.min.js"],
            "css": ["public/css/index.css"]

        }
    ],
    "background": {
        "service_worker" : "background.js"
    },
    "web_accessible_resources": [
        {
            "resources":["audiosources.html", "public/icons/copy_icon_24dp.png", "public/css/index.css"],
            "matches":["<all_urls>"],
            "use_dynamic_url": true
        }
    ],
    "permissions":["tabCapture", "tabs"],
    "action":{
        "default_popup":"popup.html",
        "default_icon" : "./public/icons/logo.png"
    }
}
```

Thanks for your help !

**Comment by rhurey** [comment]
While I haven't written a Chrome extension, a quick look at the MV3 documentation makes me suspect you need to request cross origin permissions for the Speech SDK to be able to connect to the Azure Speech Service.

https://developer.chrome.com/docs/extensions/mv3/xhr/#requesting-permission

You could try adding permissions for *stt.speech.microsoft.com.

**Comment by DelalSeletli** [comment]
Not working, i think we just can't use dynamic script in new chrome extension manifest v3. However i am trying using sandbox pages for it since there is no CSP restriction. But i'm getting an error on the AudioContext() function 

`The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page `

I tried to initialize it before, resume it but not working.

**Comment by pankopon** [comment]
Closed since no further comments in 2 months. Please open a new issue if more support is needed.

**Comment by dinesh22TL5** [comment]
It solves the problem sometimes
https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/657
