### ISSUE TITLE
Maven Repo not working?

### ISSUE THREAD

**Issue by PieperCH** [Azure-Samples/cognitive-services-speech-sdk#150]
Hi there,

the maven repo at 
https://csspeechstorage.blob.core.windows.net/maven/

doesn't seem to work.  ("The specified resource does not exist.")
Could you please check what's wrong here?

Regards,
Christian

**Comment by wolfma61** [comment]
It is a URI, and as described in the documentation you enter this URI in Android Studio or Maven as the URI to pull the Maven package from.
You can't just use it as a direct link in the browser.

thx
Wolfgang
