### ISSUE TITLE
Getting phoneme or IPA

### ISSUE THREAD

**Issue by pikojek** [Azure-Samples/cognitive-services-speech-sdk#1500]
Is there any way to get the Phoneme or IPA from the text input instead of using audio/recording?

**Comment by trrwilson** [comment]
@yulin-li is there a supported way to retrieve pronunciation information directly from synthesis with or without producing synthesized audio?

@pikojek, you may have already stumbled across it given the qualification you gave of "instead of using audio," but this *is* at least crudely possible using temporary audio as an intermediary between synthesis and pronunciation assessment, as per something like:

```csharp
static async Task<string> GetIpaForTextAsync(string phrase)
{
    var tempAudioPath = Path.GetTempFileName();
    var synthesizer = new SpeechSynthesizer(
        SpeechConfig.FromSubscription(mySpeechKey, mySpeechRegion),
        AudioConfig.FromWavFileOutput(tempAudioPath));
    _ = await synthesizer.SpeakTextAsync(phrase);

    var recognizer = new SpeechRecognizer(
        SpeechConfig.FromSubscription(mySpeechKey, mySpeechRegion),
        AudioConfig.FromWavFileInput(tempAudioPath));
    var pronunciationConfig = new PronunciationAssessmentConfig(phrase)
    {
        PhonemeAlphabet = "IPA",
    };
    pronunciationConfig.ApplyTo(recognizer);
    var recoResult = await recognizer.RecognizeOnceAsync();
    var pronunciationResult = PronunciationAssessmentResult.FromResult(recoResult);

    var pronunciationBuilder = new StringBuilder();
    foreach (var pronouncedWord in pronunciationResult.Words)
    {
        foreach (var pronouncedPhoneme in pronouncedWord.Phonemes)
        {
            pronunciationBuilder.Append(pronouncedPhoneme.Phoneme);
        }
        pronunciationBuilder.Append(' ');
    }
    return pronunciationBuilder.ToString();
}
```

With calling code like:
```csharp
static async Task Main(string[] args)
{
    Console.OutputEncoding = Encoding.Unicode;
    var input = "hello world, this is a test";
    Console.WriteLine($"Getting pronunciation for input: {input}");
    var pronunciation = await GetIpaForTextAsync(input);
    Console.WriteLine(pronunciation);
}
```

That yields the expected output of:
```
Getting pronunciation for input: hello world, this is a test
hɛloʊ wɝrld ðɪs ɪz ə tɛst
```

That's a lot of extra work for just retrieving the pronunciation, but it's at least attainable -- given speech-to-text is all about getting recognitions (and metadata like pronunciation) from audio, this indirection may be the best current fit if pronunciation isn't baked into text-to-speech in a directly accessible way.

**Comment by yulin-li** [comment]
Hi @pikojek, unfortunately we don't have an API to get the phonemes of input text. As Travis said, you can try to synthesize a temp audio and use pronunciation assessment to get the phoneme.

**Comment by pikojek** [comment]
> Hi @pikojek, unfortunately we don't have an API to get the phonemes of input text. As Travis said, you can try to synthesize a temp audio and use pronunciation assessment to get the phoneme.

I see, that's why I cannot find it on the documentation. event using API, noted on this @yulin-li :bow:

**Comment by pikojek** [comment]
> @yulin-li is there a supported way to retrieve pronunciation information directly from synthesis with or without producing synthesized audio?
> 
> @pikojek, you may have already stumbled across it given the qualification you gave of "instead of using audio," but this _is_ at least crudely possible using temporary audio as an intermediary between synthesis and pronunciation assessment, as per something like:
> 
> ```cs
> static async Task<string> GetIpaForTextAsync(string phrase)
> {
>     var tempAudioPath = Path.GetTempFileName();
>     var synthesizer = new SpeechSynthesizer(
>         SpeechConfig.FromSubscription(mySpeechKey, mySpeechRegion),
>         AudioConfig.FromWavFileOutput(tempAudioPath));
>     _ = await synthesizer.SpeakTextAsync(phrase);
> 
>     var recognizer = new SpeechRecognizer(
>         SpeechConfig.FromSubscription(mySpeechKey, mySpeechRegion),
>         AudioConfig.FromWavFileInput(tempAudioPath));
>     var pronunciationConfig = new PronunciationAssessmentConfig(phrase)
>     {
>         PhonemeAlphabet = "IPA",
>     };
>     pronunciationConfig.ApplyTo(recognizer);
>     var recoResult = await recognizer.RecognizeOnceAsync();
>     var pronunciationResult = PronunciationAssessmentResult.FromResult(recoResult);
> 
>     var pronunciationBuilder = new StringBuilder();
>     foreach (var pronouncedWord in pronunciationResult.Words)
>     {
>         foreach (var pronouncedPhoneme in pronouncedWord.Phonemes)
>         {
>             pronunciationBuilder.Append(pronouncedPhoneme.Phoneme);
>         }
>         pronunciationBuilder.Append(' ');
>     }
>     return pronunciationBuilder.ToString();
> }
> ```
> 
> With calling code like:
> 
> ```cs
> static async Task Main(string[] args)
> {
>     Console.OutputEncoding = Encoding.Unicode;
>     var input = "hello world, this is a test";
>     Console.WriteLine($"Getting pronunciation for input: {input}");
>     var pronunciation = await GetIpaForTextAsync(input);
>     Console.WriteLine(pronunciation);
> }
> ```
> 
> That yields the expected output of:
> 
> ```
> Getting pronunciation for input: hello world, this is a test
> hɛloʊ wɝrld ðɪs ɪz ə tɛst
> ```
> 
> That's a lot of extra work for just retrieving the pronunciation, but it's at least attainable -- given speech-to-text is all about getting recognitions (and metadata like pronunciation) from audio, this indirection may be the best current fit if pronunciation isn't baked into text-to-speech in a directly accessible way.

I see, so basically we mimicking the speech recognizer audio from the synthesizer. ahh great, huge thanks @trrwilson for providing the example as well. I'm going to follow your example :heart:

**Comment by pikojek** [comment]
worked as expected :tada:. hopefully in the future the result from synthesizer also include the IPA text as swell.
thank you guys. I will close this issue
