### ISSUE TITLE
Batch Transcription in Python without swagger-client

### ISSUE THREAD

**Issue by kamrapooja** [Azure-Samples/cognitive-services-speech-sdk#1501]
I want to use Azure batch transcription rest api without swagger-client. But i did not find any sample code for the same.
Is it bossible to call azure batch transcription in python without swagger-client? If yes, please provide sample code.

**Comment by kamrapooja** [comment]
I have written the following code but giving error 400. 
        base_url = 'https://centralindia.api.cognitive.microsoft.com/speechtotext/v3.0/transcriptions'
        json_data1 = {
                'contentUrls': [
                    'blob storage audio url'
                ],
                'properties': {
                    'diarizationEnabled': False,
                    'wordLevelTimestampsEnabled': True
                },
                'locale': 'en-US',
                'displayName': 'Transcription using default model for en-US'
            }
        headers = {'accept':'application/json','Content-Type': 'application/json', 'Ocp-Apim-Subscription-Key': key}

        response = requests.post(base_url, data=json_data1, headers=headers)
        print(response)

It is giving error "b'{\r\n  "code": "InvalidPayload",\r\n  "message": "Unexpected character encountered while parsing value: c. Path \'\', line 0, position 0."\r\n}'

Please help to resolve it.

**Comment by zhouwangzw** [comment]
Hello, @kamrapooja,

have you tried with  "data=json.dump(json_data1)" when calling post?

Thanks,
Zhou

**Comment by kamrapooja** [comment]
working fine after changing code to data = json.dumps(json_data1).
Thanks a lot
