### ISSUE TITLE
huge SDK size for ios-arm64_armv7

### ISSUE THREAD

**Issue by marosoaie** [Azure-Samples/cognitive-services-speech-sdk#1508]
**Describe the bug**
There is a huge difference in size for the iOS MicrosoftCognitiveServicesSpech SDK between the different architectures. 

```
marosoaie@mac MicrosoftSpeechSDK % du -hs MicrosoftCognitiveServicesSpeech.xcframework/* 
4.0K	MicrosoftCognitiveServicesSpeech.xcframework/Info.plist
577M	MicrosoftCognitiveServicesSpeech.xcframework/ios-arm64_armv7
 12M	MicrosoftCognitiveServicesSpeech.xcframework/ios-arm64_x86_64-maccatalyst
 12M	MicrosoftCognitiveServicesSpeech.xcframework/ios-arm64_x86_64-simulator
 13M	MicrosoftCognitiveServicesSpeech.xcframework/macos-arm64_x86_64
```

What's the reason for this difference? The arm64_armv7 binary is 577 compare to 12 for the others.

**To Reproduce**
Download the latest Cognitive Services SDK from https://aka.ms/csspeech/macosbinary and check the file size for each architecture.

**Expected behavior**
I would expect the native SDK to have a reasonable size. Now it looks like the size of the arm64armv7 is 577M. After stripping the armv7 architecture from the binary there's still 288M left, which would have a large impact on the size of a mobile app.

**Version of the Cognitive Services Speech SDK**
MicrosoftCognitiveServicesSpeech-XCFramework-1.21.0

**Platform, Operating System, and Programming Language**
iOS

**Additional context**

**Comment by jhakulin** [comment]
@marosoaie ios-arm64_armv7 contains bitcode for both arm64 and armv7 architectures, see information about bitcode:
https://developer.apple.com/documentation/xcode/doing-basic-optimization-to-reduce-your-app-s-size
Bitcode is an Apple technology that enables you to recompile your app to reduce its size. The recompilation happens when you upload your app to App Store Connect or export it for Ad Hoc, Development, or Enterprise distribution.

Bitcode is not enabled for simulator bits or maccatalyst and thus the difference.

**Comment by marosoaie** [comment]
@jhakulin Which size can we expect the SDK to have in an AppStore release after recompilation? I haven't found a reliable way to test this.

**Comment by jhakulin** [comment]
@marosoaie In my understanding the bitcode is currently the default option, but optional when deploying iOS apps to Apple store. So you can decide also to deploy without bitcode (Xcode project setting to enable/disable bitcode) and then the deployed app should not contain the bitcode. For example, the size of the arm64 slice without bitcode is about 7MB which should be the size impact for the app deployed to arm64 based devices. You can test what is bitcode disabled size by stripping out the bitcode using Xcode tools.

Bitcode enables Apple to recompile the app for optimizations (e.g. some time in future without requiring for new app deployment from you). I have not seen clear promise/documentation for size reduction when bitcode is enabled, however I would assume the size is not bigger than if bitcode is not enabled. Unfortunately we do not have exact information about the size impact when Apple store does its magic compared to framework which has not enabled the bitcode. Would be needed to test this by creating a test app and deploy it to store and download it to the device and examine the impact in particular device and also follow its size over time.
