### ISSUE TITLE
Cannot install with pip when using PyPy venv

### ISSUE THREAD

**Issue by sveinbjornt** [Azure-Samples/cognitive-services-speech-sdk#1509]
**Describe the bug**
Does the cognitive services speech SDK not work under PyPy? I am unable to install the package in a PyPy virtual environment. According to [this page](https://docs.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-overview): "The libraries support Python 3.6 or later, and it is also tested with PyPy 5.4+"

**To Reproduce**
1. Set up Python PyPy virtual environment
2. Activate virtual environment
3. Run "pip install azure-cognitiveservices-speech"

**Expected behavior**
azure-cognitiveservices-speech is installed

**Version of the Cognitive Services Speech SDK**
1.21.0

**Platform, Operating System, and Programming Language**
 - OS: macOS
 - Hardware - x64
 - Programming language:  Python 3.7 (PyPy 7.3.9)

**Additional context**
pip says: "ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech (from versions: none)
ERROR: No matching distribution found for azure-cognitiveservices-speech"

**Comment by jhakulin** [comment]
@sveinbjornt Thanks for the report. There indeed seems some problem with the tag used in Speech SDK wheel name (check the list of Speech SDK whl packages https://pypi.org/project/azure-cognitiveservices-speech/#files here), which seems to prevent the installation on PyPy. Please see possible workaround steps below (tested on Ubuntu20.04 WSL)

jhakulin$ pypy3
Python 3.8.13 (7.3.9+dfsg-1~ppa1~ubuntu20.04, Apr 02 2022, 00:30:03)
[PyPy 7.3.9 with GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

jhakulin$ pypy3 -m pip install azure_cognitiveservices_speech-1.21.0-cp38-cp38-manylinux1_x86_64.whl
Defaulting to user installation because normal site-packages is not writeable
ERROR: azure_cognitiveservices_speech-1.21.0-cp38-cp38-manylinux1_x86_64.whl is not a supported wheel on this platform.

As PyPy version 7.3.9 is using Python3.8, rename the .whl package to use the pp38-pypy38_pp73 tag instead of cp38-cp38 in the .whl package name and try install again

jhakulin$ pypy3 -m pip install azure_cognitiveservices_speech-1.21.0-pp38-pypy38_pp73-manylinux1_x86_64.whl
Defaulting to user installation because normal site-packages is not writeable
Processing ./azure_cognitiveservices_speech-1.21.0-pp38-pypy38_pp73-manylinux1_x86_64.whl
Installing collected packages: azure-cognitiveservices-speech
Successfully installed azure-cognitiveservices-speech-1.21.0

**Comment by sveinbjornt** [comment]
This worked for installing the azure_cognitiveservices_speech package under PyPy, but when I run the following command in the REPL:

````
import azure.cognitiveservices.speech as speechsdk
````

I get the following:

````
Python 3.7.12 (44db26267d0a, Oct 24 2021, 14:21:50)
[PyPy 7.3.7 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import azure.cognitiveservices.speech as speechsdk
Traceback (most recent call last):
  File "/usr/share/nginx/greynir.is/p37/site-packages/azure/cognitiveservices/speech/speech_py_impl.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/share/nginx/greynir.is/p37/lib-python/3/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1015, in _gcd_import
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load
  File "<frozen importlib._bootstrap>", line 974, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.cognitiveservices.speech._speech_py_impl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/share/nginx/greynir.is/p37/site-packages/azure/cognitiveservices/speech/__init__.py", line 8, in <module>
    from .speech import *
  File "/usr/share/nginx/greynir.is/p37/site-packages/azure/cognitiveservices/speech/speech.py", line 8, in <module>
    from . import speech_py_impl as impl
  File "/usr/share/nginx/greynir.is/p37/site-packages/azure/cognitiveservices/speech/speech_py_impl.py", line 17, in <module>
    _speech_py_impl = swig_import_helper()
  File "/usr/share/nginx/greynir.is/p37/site-packages/azure/cognitiveservices/speech/speech_py_impl.py", line 16, in swig_import_helper
    return importlib.import_module('_speech_py_impl')
  File "/usr/share/nginx/greynir.is/p37/lib-python/3/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1015, in _gcd_import
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load
  File "<frozen importlib._bootstrap>", line 974, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_speech_py_impl'
````

**Comment by pankopon** [comment]
@sveinbjornt Are you using macOS (as in the original description) or RHEL/CentOS (based on `[PyPy 7.3.7 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux`)? If the latter, what is the exact OS version? (post the output of `cat /etc/redhat-release`)

**Comment by sveinbjornt** [comment]
This was an attempt to install in a PyPy 7.3.7 virtual environment on Debian 11.2.

**Comment by pankopon** [comment]
@sveinbjornt Looks like there's some incompatibility between PyPy and CPython (python.org), I got the same error with PyPy installed from Debian repositories. (Your "Red Hat" built PyPy seems odd on Debian.)
```
# cat /etc/debian_version
11.3

# pypy3 --version
Python 3.7.10 (7.3.5+dfsg-2+deb11u1, Feb 03 2022, 02:45:53)
[PyPy 7.3.5 with GCC 10.2.1 20210110]
```
But if Debian 11 is your actual OS environment, won't you be able to use the regular Python (3.9 from Debian repos) instead? With that there are no issues:
```
# python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import azure.cognitiveservices.speech as speechsdk
>>>
```
Please note that https://docs.microsoft.com/azure/developer/python/sdk/azure-sdk-overview does not apply to the Speech SDK as is, for example Python version 3.6 is not supported anymore and there is no testing with PyPy.
The Speech SDK system requirements are described in
https://docs.microsoft.com/azure/cognitive-services/speech-service/speech-sdk?tabs=linux%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio#get-the-speech-sdk.

**Comment by sveinbjornt** [comment]
I was hoping to use Azure Speech in a large NLP project which we run with PyPy because it delivers significantly better performance for our use case. But if the Azure Speech SDK won't run on PyPy I guess I'll just have to find some way around that.

**Comment by pankopon** [comment]
We have created a backlog item for PyPy support, to be considered for future releases of the Speech SDK. There is no ETA yet, we'll update this item when there is more information available.

**Comment by pankopon** [comment]
Internal work item ref. 4332431.
