### ISSUE TITLE
Cannot created a conversation with a conversation id

### ISSUE THREAD

**Issue by hunter001325** [Azure-Samples/cognitive-services-speech-sdk#1510]
**Describe the bug**
Our project need the HOST can enter the conversation again even if he changed to another devices.
but it failed when i created a conversation with a conversation id（such as "AIYKZ" or GUID) on the demo of multi-device-conversation．
how to fix it?

**To Reproduce**
1. open the c++ project "multi-device-conversation".
2. pass the conversionId to Conversation::CreateConversationAsync method.
    // Create the conversation object you'll need to manage the conversation
    auto conversationId = "AIYKZ";
    auto conversation = Conversation::CreateConversationAsync(speechConfig, conversationId).get();

**Expected behavior**
Conversation can be created.

**Version of the Cognitive Services Speech SDK**
1.21.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 11
 - Hardware - x64
 - Programming language:  C++

**Additional context**
Exception thrown at 0x00007FFF1D98F6DC in helloworld.exe: Microsoft C++ exception: Microsoft::CognitiveServices::Speech::Impl::HttpException at memory location 0x00000074D2EFF010.
Exception thrown at 0x00007FFF1D98F6DC in helloworld.exe: Microsoft C++ exception: Microsoft::CognitiveServices::Speech::Impl::HttpException at memory location 0x00000074D2BFD020.
The thread 0x142f0 has exited with code 0 (0x0).
The thread 0x1b6a0 has exited with code 0 (0x0).
Exception thrown at 0x00007FFF1D98F6DC in helloworld.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFF1D98F6DC in helloworld.exe: Microsoft C++ exception: Microsoft::CognitiveServices::Speech::Impl::HttpException at memory location 0x00000074D2BFD020.
The thread 0x2240c has exited with code 0 (0x0).
The thread 0x225fc has exited with code 0 (0x0).
Exception thrown at 0x00007FFF1D98F6DC in helloworld.exe: Microsoft C++ exception: std::runtime_error at memory location 0x00000074D2BFD4A8.
Exception thrown at 0x00007FFF1D98F6DC in helloworld.exe: Microsoft C++ exception: std::runtime_error at memory location 0x00000074D25EE090.
Unhandled exception at 0x00007FFF1D98F6DC in helloworld.exe: Microsoft C++ exception: std::runtime_error at memory location 0x00000074D25EE090.

**Comment by ralph-msft** [comment]
Thanks for trying the Cognitive Services Speech SDK.

Unfortunately, moving the host of the conversation from one device to another is not currently supported. Support for this may be added in a future release.

The Conversation::CreateConversationAsync overload with conversation ID as the second parameter is intended to be [used by the ConversationTranscriber](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-conversation-transcription).

**Comment by hunter001325** [comment]
Thank you for your reply.
practically, the host use PC created a meeting, he'd like to change to phone when he went out, our app support such a scenario.

**Comment by hunter001325** [comment]
We are planning to buy a EC2 of AWS instance and mock the host on it, in order to prevent the real host changed device, but it has no audio device. I tried to install a Virtual Audio driver, but it failed in the end. I want to know if Azure Cloud providing a Windows Server with audio device.

**Comment by ralph-msft** [comment]
You don't need have an audio device to use the ConversationTranslator scenario. You can simply not call ```conversationTranslator->StartTranscribingAsync()``` and ```conversationTranslator->StopTranscribingAsync()``` and you will be good to go.

In addition to the [supported speech recognition languages](https://docs.microsoft.com/azure/cognitive-services/speech-service/language-support?tabs=speechtotext#speech-to-text), the ConversationTranslator also supports all of these [text languages for translation](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support?tabs=speechtotext#text-languages). For example, we don't have any speech recognition models for Klingon, but you can still create a conversation as a host, or join a conversation as a participant with that language selected. In that case you wouldn't be able any speech recognition. However, you can send send text instant messages (```conversationTranslator->SendTextMessageAsync```), and all other recognitions and IMs from other participants will be received in Klingon for you.

On a separate note, if you want to stream audio from another device to the AWS instance, you can inject the audio into the ConversationTranslator using a ```PushAudioInputStream```. As an example you can refer to the following sample C++ code:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/cpp/windows/console/samples/speaker_recognition_samples.cpp
In particular, take a look at the ```VerifyVoiceProfileWithPushStream``` and ```PushData``` methods

**Comment by hunter001325** [comment]
Thanks for your reply, I follow your suggestion, but it failed again, I have tried in both demo of C++ and C# .

I comment C# as follow:
// Start sending audio
//await conversationTranslator.StartTranscribingAsync().ConfigureAwait(false);
// Stop audio capture
//await conversationTranslator.StopTranscribingAsync().ConfigureAwait(false);

It run Exception:
System.ApplicationException: Exception with an error code: 0xe (SPXERR_MIC_NOT_AVAILABLE)
   Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail(IntPtr hr)
   Microsoft.CognitiveServices.Speech.Transcription.ConversationTranslator.<>c__DisplayClass57_0.<RunAsync>b__0()
   System.Threading.Tasks.Task.Execute()
   
 I comment C+ as follow:
// Start sending audio
//conversationTranslator->StartTranscribingAsync().get();
// Leave the conversation. You will stop receiving events
//conversationTranslator->LeaveConversationAsync().get();

It run crash.

I think it will still pick up the microphone device and crash when it fails.

**Comment by ralph-msft** [comment]
I was able to reproduce the issue you are seeing and this appears to be a bug. If you don't specify an AudioConfig, by default it tries to use the default audio input device on the system. Unfortunately, this will fail when there are no audio capture devices, even if you don't try to capture audio.

The workaround is specify a different audio config to work around this:

### C++
```cpp
auto pushStream = AudioInputStream::CreatePushStream(AudioStreamFormat::GetWaveFormatPCM(16000, 16, 1));
auto audioConfig = AudioConfig::FromStreamInput(pushStream);

auto conversationTranslator = ConversationTranslator::FromConfig(audioConfig);
```

### C#
```C#
var pushStream = AudioInputStream.CreatePushStream(AudioStreamFormat.GetWaveFormatPCM(16000, 16, 1));
var audioConfig = AudioConfig.FromStreamInput(pushStream);

using (var convTrans = new ConversationTranslator(audioConfig))
{
    // ....
}
```

**Comment by hunter001325** [comment]
It works, that's very kind of you.
