### ISSUE TITLE
Pronunciation Assessment: ErrorType=None, even though a phoneme is missing from the pronunciation

### ISSUE THREAD

**Issue by fabswt** [Azure-Samples/cognitive-services-speech-sdk#1511]
**Describe the bug**

Pronunciation Assessment is returning `"ErrorType":"None"` even though a phoneme is missing from the pronunciation.

**To Reproduce**
1. Use the attached audio – `alan-bugs-without-the-s.wav`
2. Run a pronunciation assessment for it with a `reference_text` of `bugs` (mind the plural.)
3. Observe the results in the JSON. I get an `"ErrorType":"None"`.

**Expected behavior**
I'm expecting for the API to return an ErrorType of `Mispronunciation` for the word, because the S sound is actually missing at the end of it.

(In passing: ErrorType is for words... Is maybe a similar field planned for each phoneme as well? This would come in handy.)

**Version of the Cognitive Services Speech SDK**
azure-cognitiveservices-speech Python 1.21.0

**Platform, Operating System, and Programming Language**
- macOS
- ARM M1
- Python 3.9.12

**Additional context**

The WAV file and sample JSON results are here: https://www.dropbox.com/sh/3wjan0o6m93i0hy/AABi2eszykaWD1Sqc5LYno-ea?dl=0 

Tags: omissions.

**Comment by fabswt** [comment]
It's worth pointing that **intrusions** (insertions) suffer from the same issue. Try saying these words wrong: "psychology" with a P, or "colonel" as "co-lo-nel", and you'll get `ErrorType=None` – where I'd expect, instead, `ErrorType=Mispronunciation`.

**Comment by yulin-li** [comment]
Hi @fabswt , thank you for using the Pronunciation Assessment service and sorry for the late reply. Looks this is a model issue and our engineers are following up.

BTW, this is a little tricky as `bug` is read out with `s`, so the system usually gives a lower score but without error. `Mispronunciation` usually means the pronunciation is almost totally wrong.

cc @yinhew

**Comment by fabswt** [comment]
Hey,
Any news on the release of that model?
