### ISSUE TITLE
Add Custom Commands application as a skill in Bot framework composer application

### ISSUE THREAD

**Issue by ridasaleem0** [Azure-Samples/cognitive-services-speech-sdk#1514]
The documentation (https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-custom-commands-integrate-remote-skills) gives an idea about how to export the Custom Commands application as a skill, however, there is no skills tab available in the Speech studio under Custom commands settings.

Is there a way to export our commands app as a skill inside the bot framework application?

**Comment by ridasaleem0** [comment]
@sigmundm

**Comment by chschrae** [comment]
As we are tracking this issue here: https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/issues/581 I'm going to close this one to make sure the answer is consolidated.
