### ISSUE TITLE
Random android crash when garbage collector clean object that was still internally used

### ISSUE THREAD

**Issue by PeraDllGD** [Azure-Samples/cognitive-services-speech-sdk#1515]
**Describe the bug**

Backstory: we are using Unity (v2019.4.16f1) to develop Android VR app for Pico Neo3 devices.

We are using sample code from here as our starting point, we are really satisfied with recognition so far but app started randomly crashing in different intervals (really hard to reproduce, its totally random)

Error that we are getting in logcat is **Error AndroidRuntime signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x79bc9b56a0 (always different address)** (Unity console doesn't show any log on crashing, its totally disconnected by that point)

After a lot of researching, last try before giving up was trying to do test with disabled garbage collector and this was first time app didn't crash - worked as expected (besides memory filling but this is less important as culprit is found and this won't be used in final product).

Conclusion: Seems like gc is collecting object that is used internally by sdk which was still in use but flagged for cleaning (I read somewhere --- _The problem is due to the program holding on to the raw handle (example IntPtr) without keeping a reference to the managed object holding on to the resource. Without keeping that reference, the object becomes eligible for finalization/collection_), which also explain error above (fault addr).

Interestingly, in editor we never had any crash, but once app is built (using il2cpp), it does.
We are using latest version of sdk --- Microsoft.CognitiveServices.Speech.1.21.0.unitypackage

**Comment by jhakulin** [comment]
@PeraDllGD Thanks for the report, could you please provide information which sample you were using as base? Also are you able to see the problem with sample project? Any possibilities to share code which reproduces the issue?

**Comment by jhakulin** [comment]
@PeraDllGD Could you also provide Android Tombstone native crash file which we could analyze further by symbolicating it? You can for example use, https://github.com/hexhacking/xCrash to get the xcrash file.

**Comment by PeraDllGD** [comment]
After few more testings, I think its happening with longer sentences quite more often (example "hello, how are you today" and that calling gc.collect after its detected, has 20-30% chance to crash app)

**Comment by PeraDllGD** [comment]
Actually I did, I uploaded sample on google drive (and shared with you) - I didn't delete library folder, so you don't need to rebuilt it  Unity version 2019.4.16f1 (same as original project)

Tested on Huawei P20 Pro

3 modified things from sample (and from my testing)
- I removed api key and region (which for me is endpoint) before sending 
- changed **SpeechTranslationConfig.FromSubscription** to **SpeechTranslationConfig.FromEndpoint** for **CreateSpeechRecognizer** method
- when **StopRecognition** is called, I'm starting **coroutine** which will call **GC.Collect()** every frame (10 times)

To reproduce:
- Start recognition
- Say longer sentence, for example "hello, how are you today"
- Stop recogntion
- Start again
- Say again, for example "hello, how are you today" but stop it at random point (it doesn't need to be fully processed)
- Than start again
- Say again, for example "hello, how are you today" but stop after you get result
(it should fail at this point, as its random, you might need to try multiple times to get it, but you will get it eventually)

Also before I noticed another problem if you stop/start in same frame, it would throw exception "**ObjectDisposedException: Cannot access a disposed object.**" but I solve that in main project by adding queue of recognizer

**Comment by chschrae** [comment]
@PeraDllGD Can you share the main code file here so others can look at it?

**Comment by PeraDllGD** [comment]
(I had to convert it to .txt extension to be able to send it here - convert it back to .cs before use)
[SpeechRecognition.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/8821532/SpeechRecognition.txt)

So literally to create sample project, you will need to
- download sample for Unity
- change SpeechRecognition script with this one
- provide credentials inside inspector (SpeechServiceRegion, because of code change I mentioned above, is actually EndPoint, not region (I didn't change name) - thats how I have my credentials so had to make that change)

Thats it, now press Continuous/Stop recognition with aforementioned reproduction steps

**Comment by PeraDllGD** [comment]
Hi, is there any update on this issue?

**Comment by PeraDllGD** [comment]
I was about to write really big review about all testings I did (prepared screenshots, screen recording, etc..) but at the end, I think I found what was issue (hint: Unity, its always Unity 🤣 )

Briefly
I tested P20 Pro again, took recording, etc.. than tried on S10e, same crash (it crashed literally each time I tried it, totally random from 1 to 10 stop recognition)
I also updated to latest version (1.22) still was getting same problem
- Enable Translation was turned off

As for SpeechConfig -> SpeechTranslationConfig, yes, that was mistake on my part, as I initial changed it to wrong place, so I just copied it (but this is not problem)

Solution - I tried with updating Unity version to 2021.1.28f1, and I wasn't able to reproduce this issue anymore 🤦 I will need to test it bit more but so far so good

Then I went through all release notes starting from 2019.4.16f1 to 2021.1.28f1 (search for "garbage") (of course not all are important but still want to put this in here, maybe it will help somebody else - as far as I can tell, only 1 might be valid)

-----------------------------------------------------------------------
https://unity3d.com/unity/whats-new/2019.4.24
- Build Pipeline: Fixed excessive garbage collection occurring during the build process.

https://unity3d.com/unity/whats-new/2020.1.0
- Build Pipeline: Reduce amount of garbage collection performed inside the ContentBuildInterface.

https://unity3d.com/unity/whats-new/2020.1.14
- **Scripting: Fixed issue where thread statics that reused thread static slots would not adhere to type alignment. This would cause the garbage collector to incorrectly clean up thread static data because it would only scan pointer aligned memory for references. This would lead to memory becoming corrupted and inducing random crashes.** --- this might be fix, but its saying also https://issuetracker.unity3d.com/issues/crash-on-mono-class-fill-runtime-generic-context-when-entering-play-mode-repeatedly that its fixed for 2019.4.15f1 🤷 

https://unity3d.com/unity/whats-new/2020.2.0
- Scripting: Added a way to get the stack trace without garbage collection in the Editor.
- Scripting: Added: Added GarbageCollector.Mode.Manual, which disables automatic GC but still allows manual control by calling GC.Collect\(\) or GarbageCollector.CollectIncremen
- Asset Pipeline: Fixed an issue where Artifacts for deleted asset didn't get deleted in artifact garbage collection.
- Build Pipeline: Reduced amount of garbage collection performed inside the ContentBuildInterface.

https://unity3d.com/unity/whats-new/2020.2.2
- WebGL: Fixed a bug where calling unityInstance.Quit() from JavaScript would not let JS VM garbage collect away the Unity game instance.

https://unity3d.com/unity/whats-new/2020.3.6
- Build Pipeline: Fixed an excessive garbage collection issue that occurred during the build process.

https://unity3d.com/unity/whats-new/2020.3.9   
- Profiling: GarbageCollectAssets is triggered frequently when higher frame counts are set ---- up to v19 this msg is spammed
- WebGL: Fixed an issue where the Garbage Collector could corrupt memory on WebGL.

https://unity3d.com/unity/whats-new/2020.3.14
- 2D: Fixed SpriteResolver generates garbage every few frames when playing an animation 

https://unity3d.com/unity/whats-new/2020.3.28
- Particles: Added: Added a version of GetTrails that doesn't allocate any garbage.

https://unity3d.com/unity/whats-new/2020.3.31
- Graphics: Fixed Brief garbage frame after changing resolution on Metal by ensuring that the recreated surface on size change doesn't dispose of its previously rendered contents

https://unity3d.com/unity/whats-new/2021.1.0
- Package: Removed unnecessary allocations and garbage collections during runtime.

https://unity3d.com/unity/whats-new/2021.1.2
- Build Pipeline: Fixed excessive garbage collection occurring during the build process.

https://unity3d.com/unity/whats-new/2021.1.7
- Universal: Fixed an issue where ShadowCaster2D was generating garbage when running in the editor.

https://unity3d.com/unity/whats-new/2021.1.9
- Profiling: GarbageCollectAssets is triggered frequently when higher frame counts are set 

https://unity3d.com/unity/whats-new/2021.1.13
- Core: Fixed an issue that caused incremental garbage collection to sometimes fail to use all of the available spare time before vsync. 

https://unity3d.com/unity/whats-new/2021.1.14
- Profiler: Fixed and issue where the contribution to asset garbage collection frequency from Profiler in the Editor wasn't removed.

**Comment by jhakulin** [comment]
@PeraDllGD Thanks a lot for the extensive testing and analysis. Initial crash stack also originates from Unity side, which matches to your analysis. I will close the issue.
