### ISSUE TITLE
SpeechRecognizer.AuthorizationToken - How to check if it is valid?

### ISSUE THREAD

**Issue by adammpolak** [Azure-Samples/cognitive-services-speech-sdk#1516]
I want to implement something like "TryGetValidToken()" which will either grab my token if valid, or generate a new one if not.

How can I check if the AuthorizationToken is valid?

**Comment by chschrae** [comment]
Hi @adammpolak,

This is the page that talks about how to use authentication tokens: https://docs.microsoft.com/en-us/azure/cognitive-services/authentication?tabs=powershell#authenticate-with-an-authentication-token

I realize there is no instructions on how to check if the token is valid, but it does mention that each token is valid for 10 minutes so you could try keeping a timestamp of when you last got a token and then checking if 10 minutes have passed before retrieving another token. Maybe 9 minutes and 45 seconds to give yourself some wiggle room. Does that help?

**Comment by adammpolak** [comment]
@chschrae understood

That is what we are doing now but we were hoping that was something a bit more robust.

Appreciate the quick response!
