### ISSUE TITLE
Speech keyword recognizer takes more than 10 seconds to return result (iOS-swift)

### ISSUE THREAD

**Issue by asad-96** [Azure-Samples/cognitive-services-speech-sdk#1518]
**Describe the bug**
I have integrated Azure STT sdk for keyword recognition. It is working but takes more than 10 seconds to give results.

**To Reproduce**
        let audioConfig = SPXAudioConfiguration.init()
        
        let reco = try! SPXKeywordRecognizer(audioConfig)
        let keywordModelFile = Bundle.main.url(forResource: "morphood", withExtension: "table")

        if keywordModelFile == nil {
            print("Cannot find keyword model file!")
            return
        }

        var keywordRecognitionModel: SPXKeywordRecognitionModel?
        do {
            try keywordRecognitionModel = SPXKeywordRecognitionModel(fromFile: keywordModelFile!.path)
        } catch {
            print("Cannot find keyword model! \(error) happened")
                        return
        }
       try! reco.recognizeOnceAsync({ srresult in

                    if SPXResultReason.canceled == srresult.reason {
                        print("Keyword recognition was canceled")
                    } else if SPXResultReason.recognizedKeyword == srresult.reason {
                            print("recognition result: \(srresult.text ?? "(no result)")")
                    } else {
                        print("There was an error.")
                    }
            }, keywordModel: keywordRecognitionModel!)

**Expected behavior**
recoginzer should return the results in 2-sec max.

**Version of the Cognitive Services Speech SDK**
'MicrosoftCognitiveServicesSpeech-iOS', '~> 1.17'

**Platform, Operating System, and Programming Language**
 - OS: iOS
 - Hardware - x64, x86, ARM, ...
 - Programming language: Swift

**Additional context**
"Audio config object deallocated." I'm getting this in log

**Comment by glecaros** [comment]
Hi @asad-96, thank you for reaching out!

A couple of questions:
- What does your audio config look like? (i.e is it a stream input, microphone, etc)
- Have you tried upgrading to the latest sdk?

**Comment by pankopon** [comment]
Closed since no response from the customer, please open a new issue if further support is needed.

**Comment by bptstmlgt** [comment]
Just wanted to report that I am seeing the same issue on 1.32.1

Keyword gets detected -> the mic stops immediately after -> but the completion is called about 10 seconds later.

Furthermore, the `addRecognizedEventHandler` doesn't catch anything.

The model is configured within Azure Speech Studio, and it's a pretty simple keyword. I don't think it's model-related since the detection seems to be working fine and on time.
