### ISSUE TITLE
How to iterate over PropertyCollection? (TTS)

### ISSUE THREAD

**Issue by fabswt** [Azure-Samples/cognitive-services-speech-sdk#1523]
I have a TTS example like so, in Python:

```python
speech_synthesizer = speechsdk.SpeechSynthesizer(speech_config=speech_config, audio_config=None)
speech_synthesizer.synthesis_word_boundary.connect(wordbound)
result = speech_synthesizer.speak_text_async(reftext).get()
```
I'm trying to iterate over `PropertyCollection` to see which properties are available and what the result contains, but I'm stuck. **How can I iterate over `PropertyCollection`?**

<br>
Some related feedback on the Python documentation:

1. [PropertyCollection Class](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.propertycollection?view=azure-python) mentions `property_id` but without mentioning its type. Personally, took me a while to figure I had to call it like so `result.properties.get_property(speechsdk.PropertyId.SpeechServiceResponse_SynthesisFirstByteLatencyMs)`
2.  The [JavaScript version of PropertyCollection class](https://docs.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/propertycollection?view=azure-node-latest) comes with a `keys` property. Anything like it for the Python version?
3. [PropertyId Enum for .NET](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.propertyid?view=azure-dotnet) lists both property name and id, but the [Python version of the same page](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.propertyid?view=azure-python) is missing the ids.

**Comment by glecaros** [comment]
What in particular are you trying to query from the result?

**Comment by fabswt** [comment]
Thanks. Ended up with this:

```python
  # Explore which properties are available on the result
  # https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.propertyid?view=azure-python
  for i in speechsdk.PropertyId:
      if result.properties.get_property(i) != '':
          print("%s: %s" % (i, result.properties.get_property(i)))
```
