### ISSUE TITLE
Timing data for Azure Text to speech

### ISSUE THREAD

**Issue by fabswt** [Azure-Samples/cognitive-services-speech-sdk#1524]
**Is your feature request related to a problem? Please describe.**
I need to be able to synchronize the audio generated by the TTS with the original text that produced it.

As far as I can tell, there's no such thing in the API right now (did not see timing data in my API calls, nor in the content generated by Audio Content Creation.)

**Describe the solution you'd like**
I'd like to have metadata that describes the speech that was synthesized, such as where a sentence or word starts and ends in the audio stream. Something in the same format as what the speech recognition API provides wold work fine:

```json
[
    {
        "Duration": 2500000,
        "Offset": 5800000,
        "Phonemes": [
            {
                "Duration": 1300000,
                "Offset": 5800000,
                "Phoneme": "ɡ"
            },
            {
                "Duration": 500000,
                "Offset": 7200000,
                "Phoneme": "ʊ"
            },
            {
                "Duration": 500000,
                "Offset": 7800000,
                "Phoneme": "d"
            }
        ],
        "Syllables": [
            {
                "Duration": 2500000,
                "Offset": 5800000,
                "Syllable": "ɡʊd"
            }
        ],
        "Word": "good"
    },
    { … }
]
```

**Describe alternatives you've considered**
- Processing the synthesized audio back through a speech recognition API would be too slow and expensive.
- Amazon Polly does provide what I've described above (they call them speech marks.)
- [Existing support for visemes](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-speech-synthesis-viseme?pivots=programming-language-python) is not the same thing, seeing as a single viseme maps to multiple possible phonemes.

**Comment by glecaros** [comment]
@yulin-li can you please take a look?

**Comment by yulin-li** [comment]
Hi @fabswt, you can try to use the word boundary event to get the offset and duration of each word. Refer to this sample https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/96cb39806823a649942c8c0cb481254f78b0cefd/samples/csharp/sharedcontent/console/speech_synthesis_samples.cs#L671

**Comment by fabswt** [comment]
Sorry, I should have been more specific. This is really the phonemes I'm after.

**Comment by yulin-li** [comment]
`phonemes` is not available in TTS. If you need it for lipsync, we have viseme for it.

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/96cb39806823a649942c8c0cb481254f78b0cefd/samples/csharp/sharedcontent/console/speech_synthesis_samples.cs#L727-L780

**Comment by fabswt** [comment]
Could you add it to feature requests?
