### ISSUE TITLE
Question about top result

### ISSUE THREAD

**Issue by alanj1998** [Azure-Samples/cognitive-services-speech-sdk#1525]
Hi,

We are implementing the Speech Service in our product and are generally interested about the NBest results returned by the SDK. 

Our initial implementation (c#) looked at the .Best() result and sorted the results by confidence before returning the top result (first in the array) to the client.
For some reason, we are seeing that only the top result (before sorting in our app) returned from the .Best() method as an array is formatted with capitalization, commas, full stops etc while the other four are not formatted. So in some cases, the result with the highest confidence is not the one we can use since it's unformatted.

So my question is, how is the top result chosen by the SDK, and how come the result with the highest confidence is not the top result in some cases?

Thanks,
Alan

**Comment by pankopon** [comment]
Hi, the results are as sent by the speech service. The first result in the array is always considered the best one. Please see the [Speech-to-text FAQ](https://docs.microsoft.com/azure/cognitive-services/speech-service/faq-stt#i-get-several-results-for-each-phrase-with-the-detailed-output-format--which-one-should-i-use-) for more details.
