### ISSUE TITLE
Content Uris

### ISSUE THREAD

**Issue by newworld0** [Azure-Samples/cognitive-services-speech-sdk#1526]
Hi there, the API works nicely when using Container URI, the only issue I am having, which I am stuck at is getting to process files in only one subdir. The scenario here is , in the container there are 3 folders, Audio-Input , Processed, and Transcript-Out directories. even after I moved the files into the processed dire the API still process them, I tried to rename the extension like .old , also did not work, I tried to get the file list from the blob using segment sync, but that gives me only the file names and the API needs array of URI's. any suggestion or method you can provide to force the API to use a subdir and not the entire container or how to build Uri's for the list of files. thanks an advance!

**Comment by chlandsi** [comment]
There is no support for reading audio from a specific prefix of a blob container with the current API. Your best option is probably to use the API for lists of files, and generate SAS Uris for the files with the prefix you want with something like this:

```python
from azure.storage.blob import (BlobClient, BlobServiceClient, ContainerSasPermissions, generate_container_sas)
import datetime

connection_string = ...
some_prefix = ...
container_name = ...
account_name = ...

serviceclient = BlobServiceClient.from_connection_string(connection_string)
containerclient = serviceclient.get_container_client(container_name)
blobs = containerclient.list_blobs(name_starts_with=some_prefix)

start = datetime.datetime.utcnow()
end = datetime.datetime.utcnow() + datetime.timedelta(days=1)
containersastoken = generate_container_sas(account_name, container_name, serviceclient.credential.account_key, permission=ContainerSasPermissions(read=True, list=True), start=start, expiry=end)

urls = []
for blob in blobs:
    blbclient = serviceclient.get_blob_client(container_name, blob['name'])
    urls.append(f"{blbclient.url}?{containersastoken}")

```
(Keep in mind that there is limit of 1000 urls per request, you might have to split the input into multiple requests if there are more)

**Comment by newworld0** [comment]
Thanks for the information @chlandsi , I am not sure if the API language matter, I am working with C#. I will try to use the above logic and see the outcome. currently my workaround is to delete the blob when it is done transcribing. btw a 1000 limit is plenty :-)
