### ISSUE TITLE
unable to install sdk

### ISSUE THREAD

**Issue by NimaQu** [Azure-Samples/cognitive-services-speech-sdk#1527]
**Describe the bug**
unable to install SDK through pip

**To Reproduce**
1. use command `pip install azure-cognitiveservices-speech`

**Expected behavior**
successful installed

**Version of the Cognitive Services Speech SDK**
latest - 1.22.0

**Platform, Operating System, and Programming Language**
 - OS: Ubuntu 20.04.4 LTS
 - Hardware - ARM64
 - Programming language: Python 3.9

**Additional context**
```
(venv) root@arm:~/bot/yuyan# pip install azure-cognitiveservices-speech
ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech (from versions: none)
ERROR: No matching distribution found for azure-cognitiveservices-speech
(venv) root@arm:~/bot/yuyan# python --version
Python 3.9.5
(venv) root@arm:~/bot/yuyan# python -c "import struct; print(struct.calcsize('P') * 8)"
64
```

**Comment by pankopon** [comment]
Hi, the Speech SDK does not support Python on Linux ARM (32 or 64-bit). We have a backlog item about it but no ETA.

Please see https://docs.microsoft.com/azure/cognitive-services/speech-service/speech-sdk?tabs=linux%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio#get-the-speech-sdk for the list of supported target architectures.
