### ISSUE TITLE
Using C++ library to run android crashes

### ISSUE THREAD

**Issue by lichao252244354** [Azure-Samples/cognitive-services-speech-sdk#1531]
Hello，when I use libMicrosoft.CognitiveServices.Speech.core.so  libMicrosoft.CognitiveServices.Speech.extension.audio.sys.so libMicrosoft.CognitiveServices.Speech.extension.codec.so libMicrosoft.CognitiveServices.Speech.extension.kws.so in android studio,android app will appear  dlopen failed: library "libpthread.so.0"  the android environment is arm64 ,cloud you provide a version of the C++ library for the android platform to support the use of the android system, the Linux C++ library arm64 in android environment 
do not support，I found that Linux is the glibc library ,Android is bionic C ,thank you very much ,I want to  recognition in android environment by calling C++ library from android studio

**Comment by lichao252244354** [comment]
thank you very much ,My app based on C++ ，I want to  cross platform through C++ library ，in Android studio ,We can call C++ through JNI ，This way we can use the same code to run on windows, android, linux  IOS , So I hope android arm-v7a arm-v8a can be provided by C++ library ，Can be cross-compiled with NDK in Visual Studio 2019 , I tried cross-compiling, but I don't have the source code，Many libraries require GNU libc support

**Comment by lichao252244354** [comment]
If Microsoft.CognitiveServices.Speech/1.22.0 does not depend on GNU libraries ，I hope it can support android

**Comment by jhakulin** [comment]
@lichao252244354 Speech SDK Nuget includes C++ libraries for Android, please follow instructions here: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1531#issuecomment-1155210186

You cannot use Linux libraries on Android.

**Comment by lichao252244354** [comment]
OK ,thank you very much , I will try SDK Nuget in  tomorrow，and tell you the result

**Comment by lichao252244354** [comment]
I found packages\Microsoft.CognitiveServices.Speech.1.21.0\build\monoandroid\libs\armeabi-v7a is this library support Android C++ ,I will use in android studio for armeabi-v7a android phone ,thank you

**Comment by jhakulin** [comment]
Closing and completing the issue
