### ISSUE TITLE
Slowness in getting real time transcription from NAudio WasapiLoopbackCapture

### ISSUE THREAD

**Issue by domenicozurlo** [Azure-Samples/cognitive-services-speech-sdk#1532]
I am testing the solution (taken from github) that transcribes the audio stream that comes from NAudio WasapiLoopbackCapture and so from the output devices. I noticed that the transcription is slow and are needed 5-6 seconds at the beginning, in order to start the transcription. Do you have any idea to improve this situation? Furthermore do you have any suggestion regards the management of the buffer in a situation in which a server must manage more clients that ask for the transcription starting from an audio stream like the NAudio WasapiLoopbackCapture?
Thanks.

Below the code used:

    using (var pushStream = AudioInputStream.CreatePushStream(AudioStreamFormat.GetWaveFormatPCM(48000, 16, 2)))
            {
                using (var audioInput = AudioConfig.FromStreamInput(pushStream))
                {
                    // Creates a speech recognizer using audio stream input.
                    using (var recognizer = new SpeechRecognizer(config, language, audioInput))
                    {
                        // Subscribes to events.
                        recognizer.Recognizing += (s, e) =>
                        {
                            Console.WriteLine($"RECOGNIZING: Text={e.Result.Text}");
                        };

                        recognizer.Recognized += (s, e) =>
                        {
                            if (e.Result.Reason == ResultReason.RecognizedSpeech)
                            {
                                Console.WriteLine($"RECOGNIZED: Text={e.Result.Text}");
                            }
                            else if (e.Result.Reason == ResultReason.NoMatch)
                            {
                                Console.WriteLine($"NOMATCH: Speech could not be recognized.");
                            }
                        };

                        recognizer.Canceled += (s, e) =>
                        {
                            Console.WriteLine($"CANCELED: Reason={e.Reason}");

                            if (e.Reason == CancellationReason.Error)
                            {
                                Console.WriteLine($"CANCELED: ErrorCode={e.ErrorCode}");
                                Console.WriteLine($"CANCELED: ErrorDetails={e.ErrorDetails}");
                                Console.WriteLine($"CANCELED: Did you update the subscription info?");
                            }

                            stopRecognition.TrySetResult(0);
                        };

                        recognizer.SessionStarted += (s, e) =>
                        {
                            Console.WriteLine("\nSession started event.");
                        };

                        recognizer.SessionStopped += (s, e) =>
                        {
                            Console.WriteLine("\nSession stopped event.");
                            Console.WriteLine("\nStop recognition.");
                            stopRecognition.TrySetResult(0);
                        };

                        // Starts continuous recognition. Uses StopContinuousRecognitionAsync() to stop recognition.
                        await recognizer.StartContinuousRecognitionAsync().ConfigureAwait(false);

                        MMDevice currentDevice = null;
                        foreach (MMDevice d in new MMDeviceEnumerator().EnumerateAudioEndPoints(DataFlow.Render, DeviceState.Active))
                        {

                            Console.WriteLine(d.FriendlyName);
                            currentDevice = d;
                            if (d.FriendlyName == "Cuffie (Realtek(R) Audio)")
                            {
                                currentDevice = d;
                            }
                        }
                        var capture = new WasapiLoopbackCapture();
                        var writer = new WaveFileWriter("c:\\temp\\test.wav", capture.WaveFormat);

                        capture.DataAvailable += async (s, e) =>
                        {
                            if (writer != null)
                            {
                                if (e.BytesRecorded > 0)
                                {
                                    var floatArray = new float[e.BytesRecorded / 4];
                                    Buffer.BlockCopy(e.Buffer, 0, floatArray, 0, e.BytesRecorded);

                                    byte[] ba = ConvertFloatArrayToInt16ByteArray(floatArray);
  
                                }
                            }
                        };
                        capture.RecordingStopped += (s, e) =>
                        {
                            if (writer != null)
                            {
                                writer.Dispose();
                                writer = null;
                            }
                            capture.Dispose();
                        };
                        capture.StartRecording();
                        Console.WriteLine("Record Started, Press Any key to stop the record");
 
                        Console.ReadLine();
                        capture.StopRecording();
                        pushStream.Close();

                        // Waits for completion.
                        // Use Task.WaitAny to keep the task rooted.
                        Task.WaitAny(new[] { stopRecognition.Task });

                        // Stops recognition.
                        await recognizer.StopContinuousRecognitionAsync().ConfigureAwait(false);
                    }
                }
            }

**Comment by glharper** [comment]
@domenicozurlo Thank you for using Speech SDK, and for writing this issue up. @ralph-msft was able to get the following code working, please let us know if it works for you as well:
```
async Task RecognizeOnceFromLoopbackAsync(string language, string subsKey, string subsRegion)
{
    uint sampleRate = 48000;
    byte bitsPerSample = 16;
    byte channels = 2;
    var stopRecognition = new TaskCompletionSource<int>(TaskCreationOptions.RunContinuationsAsynchronously);
    var config = SpeechConfig.FromSubscription(subsKey, subsRegion);
    // To enable SDK logging, uncomment the following line
    //config.SetProperty(PropertyId.Speech_LogFilename, @"c:\temp\wasapi_loopback.log");
    // Specify the PCM format
    using (var audioFormat = AudioStreamFormat.GetWaveFormatPCM(sampleRate, bitsPerSample, channels))
    // Create a push input stream with the correct PCM format
    using (var pushStream = AudioInputStream.CreatePushStream(audioFormat))
    // Create an audio config that uses the push stream
    using (var audioConfig = AudioConfig.FromStreamInput(pushStream))
    // Creates a speech recognizer using audio stream input.
    using (var recognizer = new SpeechRecognizer(config, language, audioConfig))
    {
        // Subscribes to events.
        recognizer.Recognizing += (s, e) =>
        {
            Console.WriteLine($"RECOGNIZING: Text={e.Result.Text}");
        };
        recognizer.Recognized += (s, e) =>
        {
            if (e.Result.Reason == ResultReason.RecognizedSpeech)
            {
                Console.WriteLine($"RECOGNIZED: Text={e.Result.Text}");
            }
            else if (e.Result.Reason == ResultReason.NoMatch)
            {
                Console.WriteLine($"NOMATCH: Speech could not be recognized.");
            }
        };
        recognizer.Canceled += (s, e) =>
        {
            Console.WriteLine($"CANCELED: Reason={e.Reason}");
            if (e.Reason == CancellationReason.Error)
            {
                Console.WriteLine($"CANCELED: ErrorCode={e.ErrorCode}");
                Console.WriteLine($"CANCELED: ErrorDetails={e.ErrorDetails}");
                Console.WriteLine($"CANCELED: Did you update the subscription info?");
            }
            stopRecognition.TrySetResult(0);
        };
        recognizer.SessionStarted += (s, e) =>
        {
            Console.WriteLine("\nSession started event.");
        };
        recognizer.SessionStopped += (s, e) =>
        {
            Console.WriteLine("\nSession stopped event.");
            Console.WriteLine("\nStop recognition.");
            stopRecognition.TrySetResult(0);
        };
        var capture = new WasapiLoopbackCapture();
        // It is important that you set the wave format here to match what you set as the AudioStreamFormat earlier
        // This ensures things match, and avoids the need to conversion before writing
        capture.WaveFormat = new WaveFormat((int)sampleRate, bitsPerSample, channels);
        var writer = new WaveFileWriter("c:\\temp\\test.wav", capture.WaveFormat);
        capture.DataAvailable += (s, e) =>
        {
            if (e.BytesRecorded <= 0)
            {
                return;
            }
            pushStream.Write(e.Buffer, e.BytesRecorded);
            writer?.Write(e.Buffer, 0, e.BytesRecorded);
        };
        capture.RecordingStopped += (s, e) =>
        {
            if (e.Exception != null)
            {
                Console.WriteLine("Recording failed: " + e.Exception);
            }
            writer?.Dispose();
            writer = null;
            capture.Dispose();
        };
        // Starts continuous recognition. Uses StopContinuousRecognitionAsync() to stop recognition.
        await recognizer.StartContinuousRecognitionAsync()
            .ConfigureAwait(false);
        capture.StartRecording();
        Console.WriteLine("Record Started, Press Any key to stop the record");
        Console.ReadLine();
        capture.StopRecording();
        pushStream.Close();
        // Waits for completion.
        await stopRecognition.Task
            .ConfigureAwait(false);
        // Stops recognition.
        await recognizer.StopContinuousRecognitionAsync().ConfigureAwait(false);
    }
}
```

**Comment by domenicozurlo** [comment]
@glharper @ralph-msft Thanks for your feedback. I tried your solution but the transcription is still slow. Furthermore I tried to use the WasapiLoopbackCapture from the CSCore library and it is very faster and I think that this can be a solution.

Thanks,
Domenico.

**Comment by pankopon** [comment]
Closing the item as resolved since a better solution was found. Please open a new issue if more support is needed.
