### ISSUE TITLE
Cannot add multi target languages on JavaScript demo

### ISSUE THREAD

**Issue by hunter001325** [Azure-Samples/cognitive-services-speech-sdk#1534]
**Describe the bug**
We found that multi-device-conversation sdk can add multi target languages,  but it can't in JavaScript Demo（cognitive-services\quickstart\javascript\browser\multi-device-conversation\multi-device-conversation.html）.

**To Reproduce**
1. I tried to add multi target languages in multi-device-conversation.html，it doesn't work.
                var config = SpeechSDK.SpeechTranslationConfig.fromSubscription(subscriptionKey.value, serviceRegion.value);
                config.speechRecognitionLanguage = language;
		config.addTargetLanguage("en");
		config.addTargetLanguage("en-US");

2. I found that the online demo you provided works perfectly, I debug the js code and found it sent a command through websocket with useToLanguages method in chunk-common.js.
![image](https://user-images.githubusercontent.com/23079039/173986300-78cebb01-26c3-463a-85b1-2f085af0925d.png)

3. but multi-device-conversation.html has not import chunk-common.js file.

**Expected behavior**
We expect multi-device-conversation.html can add multi target languages.

**Version of the Cognitive Services Speech SDK**
1.21.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 11
 - Hardware: x64 AMD
 - Programming language: JavaScript
 - Browser: Chrome or Edge

**Comment by glharper** [comment]
@hunter001325 Thanks for using Speech SDK, and writing this issue up. Please review the above PR and let us know if the proposed API works for your use case.
