### ISSUE TITLE
How can I generate token like official website?

### ISSUE THREAD

**Issue by cc963020001** [Azure-Samples/cognitive-services-speech-sdk#1535]
How can I generate token like official website?
![20220616151439](https://user-images.githubusercontent.com/60285867/174014168-6f4cadd7-3550-4c5b-bd30-9b49b106dab7.png)

**Comment by glharper** [comment]
@cc963020001 Thank you for using Speech SDK, and writing this issue up. To clarify, you are asking to be able to generate authenticated credentials to use Azure Resources completely in your own code, correct?

**Comment by cc963020001** [comment]
> @cc963020001感谢您使用 Speech SDK 并撰写此问题。为了澄清，您要求能够生成经过身份验证的凭据以在您自己的代码中完全使用 Azure 资源，对吗？

I hope to generate this token like official website. My expression may not be clear. It is roughly to generate my own token value to realize the conversion of text to speech.

**Comment by cc963020001** [comment]
[click here](https://azure.microsoft.com/zh-cn/services/cognitive-services/text-to-speech/)

**Comment by glharper** [comment]
@cc963020001 Thank you for clarifying. To get an authorization token from Azure Cognitive Services, you have to send a POST request with your subscription key to the appropriate region-specific endpoint. For example:
```
            const headers = { 
                headers: {
                    'Ocp-Apim-Subscription-Key': speechKey,
                    'Content-Type': 'application/x-www-form-urlencoded'
                }
            };

            try {
                const tokenResponse = await axios.post(`https://${speechRegion}.api.cognitive.microsoft.com/sts/v1.0/issueToken`, null, headers);
                console.log(`token: ${tokenResponse.data}`);
            } catch (err) {
                console.log(`error received: ${err}`);
            }
```
(The above code is taken from [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/server/index.js).)

**Comment by cc963020001** [comment]
[语音转文本.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/8930880/default.zip)
Here is the source code. I wrote it according to the style of official website, that is, this token is dynamic. I don't know how it was generated. Please help me have a look. Thank you!

**Comment by glharper** [comment]
@cc963020001 I'm not seeing in your code where the localizedResources.token variable gets reset with a POST request to the https://${speechRegion}.api.cognitive.microsoft.com/sts/v1.0/issueToken endpoint. Could you show me where that's happening?

**Comment by cc963020001** [comment]
I know this token is temporary, but I just don't know how it was generated. Is there an instance or document?

**Comment by cc963020001** [comment]
I'm new to the web, and I can only be simple.

**Comment by glharper** [comment]
@cc963020001 There is a full code sample for running Speech Recognition using auth tokens [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/browser), with instructions on the specific command line steps to run the sample [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/browser#how-to-run-the-sample).
