### ISSUE TITLE
 Connection failed (no connection to the remote host)

### ISSUE THREAD

**Issue by lichao252244354** [Azure-Samples/cognitive-services-speech-sdk#1536]
Anddroid phone recognizer occured :Connection failed (no connection to the remote host). Internal error: 1. Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED [0x80000001 | -1],I checked the error code is 5 ，I check the CancellationErrorCode  error code 5 Indicates Indicates a connection error. the X-ConnectionId: 29018316918f43afb39784bfd94bbeb2 SessionId: 29018316918f43afb39784bfd94
![error](https://user-images.githubusercontent.com/27394097/174290359-e5cee2e9-f2e9-4a84-8bf8-f0602e5da3d7.PNG)
bbeb2 , cloud help me solve this problem

**Comment by jhakulin** [comment]
@lichao252244354 Could you please provide us SDK log by following Android specific instructions below?
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging#android

**Comment by pankopon** [comment]
@lichao252244354 Please run a basic Android speech recognition quickstart like https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/java/android/from-microphone on your phone. Does it not work?

**Comment by dargilco** [comment]
Closing since there is no response from the customer.
