### ISSUE TITLE
C++ PCM audio stream recognizer

### ISSUE THREAD

**Issue by lichao252244354** [Azure-Samples/cognitive-services-speech-sdk#1539]
I found C# have the  PCM audio streaming method ，Is there a similar method in C++? thank you very much 
![info](https://user-images.githubusercontent.com/27394097/174577418-7cac6c58-1f08-442a-8c43-e543503406b2.PNG)
!

**Comment by glharper** [comment]
@lichao252244354 Yes, the corresponding C++ method is documented [here](https://docs.microsoft.com/en-us/cpp/cognitive-services/speech/audio-audiostreamformat#getwaveformatpcm). Thank you for using Speech SDK, and writing this issue up.

**Comment by lichao252244354** [comment]
OK， thank you very much
