### ISSUE TITLE
Speech Recognition with Intents missing the query words after special character

### ISSUE THREAD

**Issue by karthikeyanmlp** [Azure-Samples/cognitive-services-speech-sdk#154]
**Speech Recognition with Intents missing query words on Intent Recognition**
In Javascript Speech SDK intent recognized with `LanguageUnderstandingServiceResponse_JsonResult`.
The recognized query words are missed after the special characters($, +, etc.,) occurrence.
Solution: Recognized query words from Speech SDK must parsing/encoded while process with LUIS.

**Steps to reproduce the behavior**
1. Speek with sentence with &
2. Check the `SpeechSDK.ResultReason.RecognizedSpeech` for exact text we speak
3. Check the `SpeechSDK.ResultReason.RecognizedIntent` there where the words after & is missed

**Expected behavior**
Recognized query words from Speech SDK must parsing/encoded while process with LUIS.

**Version of the Cognitive Services Speech SDK**
SpeechSDK-JavaScript-1.1.0
SpeechSDK-JavaScript-1.2.1

**Programming Language**
 - Programming language: JavaScript

**Issues with log information**
Sample item to reproduce the issue:
*Note: Problematic lines are highlighted below

(sessionStarted) SessionId: 712B58292F564C9C85B9E45CD6C14AA9
(speechStartDetected) SessionId: 712B58292F564C9C85B9E45CD6C14AA9
(recognizing) Reason: RecognizingIntent Text: he
(recognizing) Reason: RecognizingIntent Text: show
(recognizing) Reason: RecognizingIntent Text: show comp
(recognizing) Reason: RecognizingIntent Text: show company
(recognizing) Reason: RecognizingIntent Text: show company did
(recognizing) Reason: RecognizingIntent Text: show company detail
(recognizing) Reason: RecognizingIntent Text: show company details
(recognizing) Reason: RecognizingIntent Text: show company details for
(recognizing) Reason: RecognizingIntent Text: show company details for 80
(recognizing) Reason: RecognizingIntent Text: show company details for AT and
(recognizing) Reason: RecognizingIntent Text: show company details for AT&T
(recognizing) Reason: RecognizingIntent Text: show company details for AT&T lab
(recognizing) Reason: RecognizingIntent Text: show company details for AT&T laboratory
(recognizing) Reason: RecognizingIntent Text: show company details for AT&T laboratories
(speechEndDetected) SessionId: 712B58292F564C9C85B9E45CD6C14AA9
(recognized)  Reason: RecognizedIntent Text: _**Show company details for AT&T laboratories**_. IntentId: BusinessDetails Intent JSON: {
  "query": "_**show company details for AT**_",
  "topScoringIntent": {
    "intent": "BusinessDetails",
    "score": 0.835796535
  },
  "entities": []
}
(continuation) Reason: RecognizedIntent Text: _**Show company details for AT&T laboratories**_. IntentId: BusinessDetails Intent JSON: {
  "query": "_**show company details for AT**_",
  "topScoringIntent": {
    "intent": "BusinessDetails",
    "score": 0.835796535
  },
  "entities": []
}
(sessionStopped) SessionId: 712B58292F564C9C85B9E45CD6C14AA9

**Comment by fmegen** [comment]
thank you for reporting the issue, we will look into the root cause.

**Comment by fmegen** [comment]
we can reproduce the incorrect behavior and work on a fix for the issue

**Comment by yoursrv2008** [comment]
I am facing the same issue. Can we expect the fix shortly?

**Comment by fmegen** [comment]
this is a service side issue with no change required on the client side.

**Comment by mahilleb-msft** [comment]
Hey -- this is now fixed on the service side, can you try again?
Thanks for your patience.

**Comment by karthikeyanmlp** [comment]
Thank you @fmegen and @mahilleb-msft, Now it is working fine.
