### ISSUE TITLE
sample1.py speech recognition script crashes on Linux

### ISSUE THREAD

**Issue by Vasanvs** [Azure-Samples/cognitive-services-speech-sdk#155]
When we run the sample1.py speech recognition script in Linux command line, it is working fine.

But for our specific application, we require this sample1.py script to be called from a C program. When we call this program from the C interface, it gives the following error message without capturing and recognizing the speech.

Say something...
Speech Recognition canceled: CancellationReason.Error
Error details: Connection failed (no connection to the remote host). Internal error: 1. Error details: 2308. Please check network connection, firewall setting, and the region name used to create speech factory.

Is this a known issue or is there a workaround for this?

**Comment by Vasanvs** [comment]
I was running the Python script as a system call from C program. Interestingly, if I just do a simple ping of an internet site from inside the same python script, the ping command is successful. This means that there is no network connectivity issue from that server and also from inside the python script. However the error comes in as mentioned in the issue report above "Connection failed (no connection to the remote host). Internal error: 1. Error details: 2308. Please check network connection, firewall setting, and the region name used to create speech factory.". This possibly means that there is an issue in contacting the speech engine site alone in this manner.

If we download and try the SPeech SDK C API and run the same way from my existing C program interface, the same error results. However the same sample code of C API Speech recognition library when run from the command line, is fully successful.

**Comment by chlandsi** [comment]
Can you share the relevant portions of your code so we can try to replicate the issue?

**Comment by wolfma61** [comment]
no feedback - closing
