### ISSUE TITLE
How to Continuously listen for stream input（Not from the microphone）

### ISSUE THREAD

**Issue by cdd404467** [Azure-Samples/cognitive-services-speech-sdk#1552]
你好，我现在有个应用场景是：从语音通话中获取到音频数据，然后使用SPXPullAudioInputStream 去读取这个音频数据，现在的问题是，我持续获取到音频数据后如何去持续调用 SPXPullAudioInputStream 这个类，然后转化成SPXAudioConfiguration，再通过SPXSpeechRecognizer 监听audioConfig和speechConfig 来完成持续的语音转文字。我是要不断的去初始化SPXPullAudioInputStream 这个类吗，还是它有监听可以使用。（我想知道的是如何持续将音频数据转为SPXPullAudioInputStream，不是SPXSpeechRecognizer的持续监听回调）

**Comment by pankopon** [comment]
@cdd404467 Please write support questions in this forum in English.

We have an example of SPXPullAudioInputStream usage in
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/7a745ea846d05bed1eef2e1806e3679ef0bbcfd9/samples/objective-c/ios/speech-samples/speech-samples/ViewController.m#L442

(The data source is the example is a file, just use whatever the source in your case instead.)
