### ISSUE TITLE
Azure speech to text error in Azure ML studio 

### ISSUE THREAD

**Issue by haldernayan** [Azure-Samples/cognitive-services-speech-sdk#1553]
I have installed correctly swagger-client in Azure ML studio by following link 👍 

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/python/README.md

However I am getting the following error in Azure python speech to text in Azure ML studio.

AttributeError: module 'swagger_client' has no attribute 'DefaultApi'

I need help to resolve this.

**Comment by glecaros** [comment]
Hi @haldernayan, were you able to resolve your problem?

**Comment by pankopon** [comment]
Closed since no update from the customer since June, please create a new item if more support is needed.
