### ISSUE TITLE
EXC_BAD_ACCESS usp_reco_engine_adapter.cpp:2907

### ISSUE THREAD

**Issue by toddtian** [Azure-Samples/cognitive-services-speech-sdk#1555]
**Describe the bug**
I received 3 crash reports, the crash reason is:

EXC_BAD_ACCESS: Attempted to dereference null pointer.
I have posted details stack trace in Additional context.

**To Reproduce**
Unknown, because we are unable to reach the end-user to ask details, we also unable to reproduce it on our devices.

**Expected behavior**

**Version of the Cognitive Services Speech SDK**
  - MicrosoftCognitiveServicesSpeech-iOS (1.19.0)

**Platform, Operating System, and Programming Language**
 - iOS 15.3.1
 - iPhone 13 
 - Swift

**Additional context**

EXC_BAD_ACCESS: Attempted to dereference null pointer.

0  MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::Impl::CSpxUspRecoEngineAdapter::OnTurnEnd(Microsoft::CognitiveServices::Speech::USP::TurnEndMsg const&) (usp_reco_engine_adapter.cpp:2907:26)
1  MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::USP::CSpxUspCallbackWrapper::OnTurnEnd(Microsoft::CognitiveServices::Speech::USP::TurnEndMsg const&)::{lambda(std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::USP::ISpxUspCallbacks>)#1}::operator()(std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::USP::ISpxUspCallbacks>) const (usp.h:171:134)
2  MicrosoftCognitiveServicesSpeech _ZZN9Microsoft17CognitiveServices6Speech3USP10Connection4Impl15OnTransportDataEbRKNSt3__13mapINS5_12basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEESC_NS5_4lessISC_EENSA_INS5_4pairIKSC_SC_EEEEEEPKhmENK4$_12clINS5_10shared_ptrINS2_9CallbacksEEEEEDaT_ (uspimpl.cpp:1380:57)
3  MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::USP::Connection::Impl::Invoke(std::__1::function<void (std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::USP::Callbacks>)>) (functional:1873:16)
4  MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::USP::Connection::Impl::OnTransportData(bool, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, unsigned char const*, unsigned long) (uspimpl.cpp:1380:17)
5  MicrosoftCognitiveServicesSpeech unsigned long Microsoft::CognitiveServices::Speech::Impl::event<std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::add<Microsoft::CognitiveServices::Speech::USP::Connection::Impl>(std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::USP::Connection::Impl>, void (Microsoft::CognitiveServices::Speech::USP::Connection::Impl::*)(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&))::{lambda(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)#1}::operator()(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const (event.h:44:21)
6  MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::Impl::event<std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::raise(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) (functional:1873:16)
7  MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::USP::UspWebSocket::HandleTextData(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) (event.h:79:51)
8  MicrosoftCognitiveServicesSpeech unsigned long Microsoft::CognitiveServices::Speech::Impl::event<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::add<Microsoft::CognitiveServices::Speech::USP::UspWebSocket>(std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::USP::UspWebSocket>, void (Microsoft::CognitiveServices::Speech::USP::UspWebSocket::*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&))::{lambda(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)#1}::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const (event.h:44:21)
9  MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::Impl::event<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::raise(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) (functional:1873:16)
10 MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::Impl::CSpxWebSocket::OnWebSocketFrameReceived(unsigned char, unsigned char const*, unsigned long) (web_socket.cpp:937:17)
11 MicrosoftCognitiveServicesSpeech on_underlying_io_bytes_received (uws_client.c:1423:37)
12 MicrosoftCognitiveServicesSpeech dowork_read (tlsio_appleios.c:499:21)
13 MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::Impl::CSpxWebSocket::DoWork() (web_socket.cpp:748:9)
14 MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::Impl::CSpxWebSocket::WorkLoop(std::__1::weak_ptr<Microsoft::CognitiveServices::Speech::Impl::CSpxWebSocket>)::$_9::operator()() const (web_socket.cpp:709:26)
15 MicrosoftCognitiveServicesSpeech std::__1::packaged_task<void ()>::operator()() (future:1993:12)
16 MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::Impl::CSpxThreadService::Task::Run() (thread_service.cpp:156:9)
17 MicrosoftCognitiveServicesSpeech void Microsoft::CognitiveServices::Speech::Impl::CSpxThreadService::Thread::RunTask<std::__1::pair<std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::Impl::CSpxThreadService::Task>, std::__1::promise<bool> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::deque<std::__1::pair<std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::Impl::CSpxThreadService::Task>, std::__1::promise<bool> >, std::__1::allocator<std::__1::pair<std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::Impl::CSpxThreadService::Task>, std::__1::promise<bool> > > >&) (thread_service.h:215:23)
18 MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::Impl::CSpxThreadService::Thread::WorkerLoop(std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::Impl::CSpxThreadService::Thread>) (thread_service.cpp:325:27)
19 MicrosoftCognitiveServicesSpeech _ZNSt3__1L8__invokeIPFvNS_10shared_ptrIN9Microsoft17CognitiveServices6Speech4Impl17CSpxThreadService6ThreadEEEEJS8_EEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOSB_DpOSC_ (type_traits:3545:1)
20 libsystem_pthread.dylib          __pthread_start

**Comment by dargilco** [comment]
Thank you @toddtian for reporting this issue. I am following up with the SDK team on this. This carsh report is from a single user (single device)?

**Comment by toddtian** [comment]
No problem.
Yes, it's from a single user on single devices.

The api region is east-us.

**Comment by dargilco** [comment]
@toddtian Can you describe what your code does? Is it using SPXSpeechRecognizer? if so, how is audio fed into the recognizer? (input stream, WAV file or live microphone). Can you share snippets of your code?

**Comment by toddtian** [comment]
Yes, I can share the details of our code, it's using SPXSpeechRecognizer, and the audio is fed into SPXPushAudioInputStream from the microphone.

Can you leave your email for me? I can send snippets of the relative code.

**Comment by dargilco** [comment]
Please send to dcohen AT microsoft DOT com. Thanks!

**Comment by toddtian** [comment]
I have sent an email to you. Thanks.

**Comment by dargilco** [comment]
Thank you for your e-mail. Closing this issue as this is now tracked internaly ([Microsoft internal bug](https://msasg.visualstudio.com/DefaultCollection/Skyman/_workitems/edit/4344685))
