### ISSUE TITLE
SSML <bookmark> with sentence having  <phoneme> not working

### ISSUE THREAD

**Issue by pierat** [Azure-Samples/cognitive-services-speech-sdk#1557]
**Describe the bug**
Hi, bookmarks seems now to work for sentences containing text. As soon as I add phoneme, it is no more working and all bookmarks are no more reached.

**To Reproduce**
Use the following string
`<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="en-US"><voice name="en-US-AriaNeural"><phoneme alphabet="ipa" ph="ˈækˌsɛs riˈvjuz"/> We are selling <bookmark mark="flower_1"/>roses and <bookmark mark="flower_2"/>daisies.<bookmark mark="end"/></voice></speak>
`
With the standard Java sample that I previously use for 
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1245

**Expected behavior**
I expect 3 bookmarks reached, as it is when there is no phoneme element
Bookmark flower_1 reached. Audio offset: 491ms.
Bookmark flower_2 reached. Audio offset: 833ms.
Bookmark end reached. Audio offset: 1266ms.

In the reality, with phoneme element, only one is reached 
Bookmark flower_1 reached. Audio offset: 1466ms.

**Version of the Cognitive Services Speech SDK**
1.22.0

**Platform, Operating System, and Programming Language**
 - Windows 10 pro
 - Hardware - x64
 - Programming language: Java

**Additional context**
None

**Comment by yulin-li** [comment]
Hi, thanks for reporting this, we are reviewing this issue.

**Comment by Laxminarayen** [comment]
Hi, We have also been using the Azure Cognitive Services Speech SDK (using python API) for production applications and have also been facing the same issues. Is there a timeline for this to be fixed?

**Comment by yulin-li** [comment]
Hi, I will talk to our engineer for updates.

**Comment by yulin-li** [comment]
@newhillchan could take a look?

**Comment by pierat** [comment]
Hi, any ideas on the status of this issue ?

Thanks, Pierre

**Comment by laultman** [comment]
I appear to have the same issue. The **bookmark does not trigger the event** while synthesizing the SSML. I am using SSML and the SDK sample HelloWorld as my base project to test. I added an event and a method to process the event as follows:
```csharpe
            // Creates a speech synthesizer using the default speaker as audio output.
            using (var synthesizer = new SpeechSynthesizer(config))
            {
                string text = SourceTextSSML.TextInsertLavCrankBearingInBlock;

				synthesizer.BookmarkReached += new EventHandler<SpeechSynthesisBookmarkEventArgs>(synthesizer_BookmarkReached);


				using (var result = await synthesizer.SpeakSsmlAsync(text))
				{
					if (result.Reason == ResultReason.SynthesizingAudioCompleted)
                    {
                        //Console.WriteLine($"{voices[i]} said: [{text}]");
                    }
                    else if (result.Reason == ResultReason.Canceled)
                    {
                        var cancellation = SpeechSynthesisCancellationDetails.FromResult(result);
                        Console.WriteLine($"CANCELED: Reason={cancellation.Reason}");

                        if (cancellation.Reason == CancellationReason.Error)
                        {
                            Console.WriteLine($"CANCELED: ErrorCode={cancellation.ErrorCode}");
                            Console.WriteLine($"CANCELED: ErrorDetails=[{cancellation.ErrorDetails}]");
                            Console.WriteLine($"CANCELED: Did you update the subscription info?");
                        }
                    }
                }
            }
		}

		static void synthesizer_BookmarkReached(object sender, SpeechSynthesisBookmarkEventArgs e)
		{
			Console.WriteLine("Bookmark ({0}) reached at: {1} ", e.Text, e.AudioOffset);
		}

```
The SSML string is as follows:
```csharpe
            internal static string TextInsertLavCrankBearingInBlock =
			    "<speak version=\"1.0\" xmlns=\"http://www.w3.org/2001/10/synthesis\" xml:lang=\"en-US\">" +
					"<voice name = \"en-US-GuyNeural\">" +
				        "<prosody pitch = \"medium\">" +
				        "<p>Inserting crankshaft bearing into <say-as interpret-as = \"characters\">LAV</say-as> engine block at journal number 1." +
                        "</p>" +
						"<bookmark mark='BrFrame-0019.png'/>" +
				        "<p>" +
				        "<s>Ensure matching bearing numbers.</s>" + 
                        "<bookmark mark='Insert'/>" +
						"<s>Locate block position 1.</s>" +
				        "<s>Ensure your bearing lock tab is properly inserted. </s>" +
				        "<s>Press bearing into position, checking bearing is flush with block. </s>" +
				        "</p>" +
				        "<p><s>Press the Video menu button or press Play to hear this again.</s>" +
				        "<s>You may press Cancel button at any time.</s>" +
				        "</p>" +
				        "</prosody>" +
					"</voice>" +
				"</speak>";

```

**Comment by laultman** [comment]
UPDATE:
I added an event and event handler for the Synthesizer completed to test that events were working at all in the SDK.
```csharp
synthesizer.SynthesisCompleted += new EventHandler<SpeechSynthesisEventArgs>(synthesizer_Completed);
```
I next added a simple handler for it.
```csharp
		static void synthesizer_Completed(object sender, SpeechSynthesisEventArgs e)
		{
			Console.WriteLine("Completed: result ({0})", e.Result.Reason);
		}

The event for the completed synthesis performed as expected.
```

**Comment by laultman** [comment]
Additional Update: This same issue is found in the Windows version of System.Speech. The difference is Azure Cognitive services ignores the bookmark tags while the Windows System.Speech throws a hard error: Invalid format (XML).

I was able to get the Windows System.Speech to work by looking up the [W3C specification:](https://www.w3.org/TR/speech-synthesis/) in section 3.3.2 _**mark**_ Element. Using the statement found in the standard allowed the Windows System.Speech to fire the event as expected.
The format is: <mark name='text-value-here'/>
This statement is still ignored by Azure Cognitive services.

**Comment by pankopon** [comment]
@newhillchan @yulin-li Please update status.
