### ISSUE TITLE
Unable to recognize PCM data in player

### ISSUE THREAD

**Issue by Zhengyi66** [Azure-Samples/cognitive-services-speech-sdk#1558]
I want to use the speech-to-text function in the player, but SPEECH-SDK cannot recognize the sampled PCM data.

The following is the recognition result：
```
System.out: SpeechUtil startContinuousRecognitionAsync.
System.out:  SpeechUtil Session started event.
System.out: SpeechUtil NOMATCH: Speech could not be recognized.
SpeechUtil: code:SessionId:45da5eead3714f508c128e02dece913a ResultId:36fe080c02d84d05a0a894ab67cc1efe Reason:NoMatch Recognized text:<>.
System.out: SpeechUtil CANCELED: Reason=EndOfStream
System.out: SpeechUtil CANCELED: ErrorCode=NoError
System.out:  SpeechUtil Session stopped event.
```

Hello，I save the PCM data in the player to a file, then convert the pcm file to a WAV file, and use ffmprobe to view the format。

```
***deMini Downloads % ffprobe output.wav                                     
ffprobe version 5.0.1 Copyright (c) 2007-2022 the FFmpeg developers
  built with Apple clang version 13.0.0 (clang-1300.0.29.30)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.0.1_2 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, wav, from 'output.wav':
  Metadata:
    encoder         : Lavf59.16.100
  Duration: 00:00:23.22, bitrate: 256 kb/s
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, 1 channels, s16, 256 kb/s
```

Why can't it be recognized？

**Comment by dargilco** [comment]
@Zhengyi66 Thank you for using Speech SDK. I'm Darren from the SDK team. To help you I will need more information. But before that, please make sure you viewed all the relevant samples in this GitHub repository. First run the closest provided sample to your scenario, and make sure it works. 
If the sample(s) run fine on your platform, but your code still does not, please provide the following:
- What language is spoken? The default recognition language is American English (`en-us`). If you are trying to recognize any other language, you need to set the right language code (see [quickstart](https://docs.microsoft.com/azure/cognitive-services/speech-service/get-started-speech-to-text?tabs=terminal&pivots=programming-language-swift) documentations)
- Your Operating System and programming language
- Share you code (or parts of it) if possible
- In particular, how do you feed audio into the SDK? Are you providing WAV file name? Are you feeding audio buffers to the SDK via an input stream? if so, is it a push or pull input stream? (based on your short description above, sounds like you are using an input stream).
-  Provide a short WAV file representing the audio data you send into the SDK
- Turn on SDK logging while you do speech recognition and share the log file. See [instructions here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging). 
-  Make sure you use the latest SDK version (1.22).
16bit/sample (little endian), mono, 16khz sample rate is the default audio input stream format. I think that's what your tool shows, after dumping the audio to a WAV file. So perhaps there is some other issue.
Thanks, Darren.

**Comment by Zhengyi66** [comment]
Thank you for your help。I have found the problem according to your hint。

Have a nice weekend。
