### ISSUE TITLE
Node.JS sample push stream should be skipping header

### ISSUE THREAD

**Issue by mahilleb-msft** [Azure-Samples/cognitive-services-speech-sdk#1561]
**Describe the bug**

I believe samples/js/node should be skipping the WAV header in function openPushStream, like the samples for other languages using that pattern. Also, would be great if would validate the WAV header on the file input to set the right sample rate in the audio config (or error out for unsupported format).

Right now an extra WAV header is sent, which can lead to different recognition results.

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/node/index.js#L17

**To Reproduce**

Run the sample.

**Expected behavior**

**Version of the Cognitive Services Speech SDK**

microsoft-cognitiveservices-speech-sdk 1.22.0

**Platform, Operating System, and Programming Language**

 - Linux x64 Node.JS v14.17.2
 - JavaScript

**Comment by jhakulin** [comment]
Thanks @mahilleb-msft ! I created internal workitem for this, ref: 4353630

**Comment by chschrae** [comment]
Updated the sample
