### ISSUE TITLE
What is this error means 'Error code: 1012. Error details: Instance is shutting down'

### ISSUE THREAD

**Issue by toddtian** [Azure-Samples/cognitive-services-speech-sdk#1563]
SDK 1.22
Region: eastus

I got this error in SPXSpeechRecognizer canceled event handler, the error details:

error occured in recognizing, Optional(\"Connection was closed by the remote host. Error code: 1012. Error details: Instance is shutting down SessionId: 8b5c3308a2b34b56aaa02fda469818fd\")

We are unable to reproduce it, could you please give us some hints? What reasons may cause this error? 

Thanks.

**Comment by jhakulin** [comment]
@toddtian Thanks for the report and sharing the session id information. We will investigate and let you know if we need more information.

**Comment by pankopon** [comment]
@toddtian There has been no reproduction of this error during our investigations. If it starts occurring again, please try to collect [Speech SDK logs](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging) for more detail.
Closing this item, please create a new issue if more support is needed.
