### ISSUE TITLE
Multi Device conversation issue in java speech sdk 

### ISSUE THREAD

**Issue by jeason789** [Azure-Samples/cognitive-services-speech-sdk#1566]
**Describe the bug**
Conversation Host's transcribed/transcribing listeners not trigger when a java client participant join conversation with AudioConfig.fromDefaultMicrophoneInput(); But java client participant's transcribed/transcribing listeners work properly,transcribed/transcribing callback received correct result text from self speech

**To Reproduce**
1. create Conversation using java sdk
2. Join this conversation using java sdk with DefaultMicrophoneInput

**Expected behavior**
1. both two role in the conversation can receive participant's speech result callback from transcribing/transcribed listener

**Version of the Cognitive Services Speech SDK**
java sdk: 'com.microsoft.cognitiveservices.speech:client-sdk:1.22.0'

**Platform, Operating System, and Programming Language**
 - OS: Mac os
 - Hardware - ARM, ...
 - Programming language:  Java

**Additional context**
 - none

**Comment by jhakulin** [comment]
@jeason789  Thanks for the report, could you please provide a log based on the instructions here ? https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging. 
That would help us to understand better what happens.

**Comment by jeason789** [comment]
[2022.7.9.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/9075680/2022.7.9.log)
this is a java participant log, i create a conversation using "https://translator.microsoft.com/chatroom/" demo, and  join this conversation with java client, java client participant can receive speech translation text from remote client and self speech, but remote client (chatroom demo) can receive speech text from java client

**Comment by jeason789** [comment]
`private void joinConversation() throws ExecutionException, InterruptedException {
        // Replace these values with the details of your Cognitive Speech subscription
        String subscriptionKey = "my subscription key";

        // Replace below with your region identifier from here: https://aka.ms/speech/sdkregion
        String region = "japaneast";

        // Sets source and target languages.
        // Replace with the languages of your choice, from list found here: https://aka.ms/speech/sttt-languages
        String fromLanguage = "zh-CN";
        String toLanguage = "zh-CN";

        // Set this to the display name you want for the conversation host
        String displayName = "900187";

        // Create an instance of the speech translation config
        var config = SpeechTranslationConfig.fromSubscription(subscriptionKey, region);
        config.setProperty(PropertyId.Speech_LogFilename, "/Users/xinda/log/xx.log");
        config.setSpeechRecognitionLanguage(fromLanguage);
        config.addTargetLanguage(toLanguage);

        // Create the conversation
        var conversation = Conversation.createConversationAsync(config,"RPHKZ").get();
        // Start the conversation so the host user and others can join
        conversation.startConversationAsync();

        // Get the conversation ID. It will be up to your scenario to determine how this is shared with other participants.
        String conversationId = conversation.getConversationId();
        System.out.println("Created " + conversationId + " conversation");

        // At this point, you can use the conversation object to manage the conversation.
        // For example, to mute everyone else in the room you can call this method:
        conversation.muteAllParticipantsAsync();

        // Configure which audio source you want to use. If you are using a text only language, you
        // can use the other overload of the constructor that takes no arguments
        var audioConfig = AudioConfig.fromDefaultMicrophoneInput();
        var conversationTranslator = new ConversationTranslator(audioConfig);
        // You should connect all the event handlers you need at this point
        conversationTranslator.sessionStarted.addEventListener((s, e) ->
        {
            System.out.println("Session started: " + e.getSessionId());

        });
        conversationTranslator.canceled.addEventListener((s, e) ->
        {
            switch (e.getReason()) {
                case EndOfStream:
                    System.out.println("End of audio reached");
                    break;

                case Error:
                    System.out.println("\"Canceled due to error. {" + e.getErrorCode() + "}: {" + e.getErrorDetails() + "}");
                    break;
            }
        });
        conversationTranslator.conversationExpiration.addEventListener((s, e) ->
        {
            System.out.println("Conversation will expire in {" + e.getExpirationTime() + "} minutes");


        });

        conversationTranslator.participantsChanged.addEventListener((s, e) ->
        {
            System.out.println("The following participant(s) have");
            switch (e.getReason()) {
                case JoinedConversation:
                    System.out.println("joined");
                    break;

                case LeftConversation:
                    System.out.println("left");
                    break;

                case Updated:
                    System.out.println("been updated");
                    break;
            }
            System.out.println(":");


            for (Participant participant : e.getParticipants()) {
                System.out.println(participant.getDisplayName());

            }
        });
        conversationTranslator.textMessageReceived.addEventListener((s, e) ->
        {
            System.out.println("Received an instant message from " + e.getResult().getParticipantId() + ": '{e.Result.Text}'");
            for (Map.Entry<String, String> entry : e.getResult().getTranslations().entrySet()) {

                System.out.println("Received an instant message from " + entry.getKey() + ": " + entry.getValue() + "");

            }
        });
        conversationTranslator.transcribed.addEventListener((s, e) ->
        {
            System.out.println("Received a transcription from " + e.getResult().getParticipantId() + ": " + e.getResult().getText() + "");
            for (Map.Entry<String, String> entry : e.getResult().getTranslations().entrySet()) {

                System.out.println("Translated into " + entry.getKey() + ": " + entry.getValue() + "");

            }
        });
        conversationTranslator.transcribing.addEventListener((s, e) ->
        {
            System.out.println("Received a partial transcription from " + e.getResult().getParticipantId() + ": " + e.getResult().getText() + "");

            for (Map.Entry<String, String> entry : e.getResult().getTranslations().entrySet()) {
                System.out.println("Translated into " + entry.getKey() + ": " + entry.getValue() + "");
            }
        });
        // Enter the conversation to start receiving events
        conversationTranslator.joinConversationAsync(conversation, displayName).get();
        // You can now send an instant message to all other participants in the room
        conversationTranslator.sendTextMessageAsync("The instant message to send");

        // If specified a speech-to-text language, you can start capturing audio
        conversationTranslator.startTranscribingAsync();
        System.out.println("Started transcribing. Press Ctrl + c to stop");

    }`
this is my java code

**Comment by jeason789** [comment]
it happened since July 6，2022，it worked well before

**Comment by ralph-msft** [comment]
Thanks for reporting the issue. We were able to reproduce the issues you are seeing.

We are in the process of fixing these service issues but don't have an exact ETA at this time. We will post a follow-up message here once the issue is resolved.

In the meantime, you can use the following work around:
  * If you are creating a new conversation using the Java speech SDK, please add the following to your SpeechConfig:
        ```
        speechConfig.setServiceProperty("usePipelineVersion", "1", ServicePropertyChannel.UriQueryParameter);
        ```
  * If you are joining an existing conversation using the Java speech SDK, please add the following to your AudioConfig:
        ```
        audioConfig.SetProperty(PropertyId.SpeechServiceConnection_Endpoint, "wss://" + region + 
        .s2s.speech.microsoft.com/speech/translation/cognitiveservices/v1?usePipelineVersion=1");
        ```
        where ```region``` is the region of your Cognitive Speech subscription

**Comment by lenqing6** [comment]
[samTest.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/9088991/samTest.log)
Line 220 of the log is the conversation removeparticipantasync method, which was successfully executed but did not respond correctly.

Line 221 of the log is the conversation mutepartitionasync method, which was successfully executed and received the correct return.

Line 225 of the log is the conversation unmutepartitionasync method, which was successfully executed and received the correct return.

The problem is 220 lines.

**Comment by jeason789** [comment]
> Thanks for reporting the issue. We were able to reproduce the issues you are seeing.
> 
> We are in the process of fixing these service issues but don't have an exact ETA at this time. We will post a follow-up message here once the issue is resolved.
> 
> In the meantime, you can use the following work around:
> 
> * If you are creating a new conversation using the Java speech SDK, please add the following to your SpeechConfig:
>   `speechConfig.setServiceProperty("usePipelineVersion", "1", ServicePropertyChannel.UriQueryParameter);`
> * If you are joining an existing conversation using the Java speech SDK, please add the following to your AudioConfig:
>   `audioConfig.SetProperty(PropertyId.SpeechServiceConnection_Endpoint, "wss://" + region +  .s2s.speech.microsoft.com/speech/translation/cognitiveservices/v1?usePipelineVersion=1");`
>   where `region` is the region of your Cognitive Speech subscription

it works， thanks！

**Comment by juandausa** [comment]
> Thanks for reporting the issue. We were able to reproduce the issues you are seeing.
> 
> We are in the process of fixing these service issues but don't have an exact ETA at this time. We will post a follow-up message here once the issue is resolved.
> 
> In the meantime, you can use the following work around:
> 
> * If you are creating a new conversation using the Java speech SDK, please add the following to your SpeechConfig:
>   `speechConfig.setServiceProperty("usePipelineVersion", "1", ServicePropertyChannel.UriQueryParameter);`
> * If you are joining an existing conversation using the Java speech SDK, please add the following to your AudioConfig:
>   `audioConfig.SetProperty(PropertyId.SpeechServiceConnection_Endpoint, "wss://" + region +  .s2s.speech.microsoft.com/speech/translation/cognitiveservices/v1?usePipelineVersion=1");`
>   where `region` is the region of your Cognitive Speech subscription

Hi Ralph, thanks for your prompt response. Can I apply the same workaround to the iOS SDK?

**Comment by ralph-msft** [comment]
You can use the same workaround across all platforms and/or programming languages supported by the Cognitive Speech Services SDK. The documentation for the Objective C version of the APIs can be found [here](https://docs.microsoft.com/objectivec/cognitive-services/speech/).

For the audio issue your seeing, could you please share the [SDK client logs](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging)?

**Comment by juandausa** [comment]
Hi Ralph,
The canceled event is reporting the following error:

```
0x5 (SPXERR_INVALID_ARG) 
[CALL STACK BEGIN]

  # 0: 0x78bb31ef5431  ???
  # 1: 0x78bb31ef48ef  ???
  # 2: 0x78bb31ef3332  ???
  # 3: 0x78bb31ef2b1d  ???
  # 4: 0x78bb31ef2192  ???
  # 5: 0x78bb31ef1e6b  ???
  # 6: 0x78bb31f27ece  ???
  # 7: 0x78bb31f2946b  ???
  # 8: 0x78bb31f28cf8  ???
  # 9: 0x78bb31fa4c36  ???
  #10: 0x78bb31fa4362  ???
  #11: 0x78bb31fa58a0  ???
  #12: 0x78bb31fa43ec  ???
  #13: 0x78bb31fa693d  ???
  #14: 0x78be5957358b  ???
  #15: 0x78be5950bd88  ???

[CALL STACK END]
```
Here you will find the [speech.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/9101878/speech.log), and also here you have the URL we are using: `wss://centralus.s2s.speech.microsoft.com/speech/translation/cognitiveservices/v1?usePipelineVersion=1`.

**Comment by ralph-msft** [comment]
Looking through the logs, the SPXERR_INVALID_ARG is not related to the microphone not working for guests. Those errors are happening after Leave...() has been called.

The cause for the microphone issues was an authorization error:
```
[25520]: 10821ms SPX_TRACE_INFO:  usp_connection.cpp:908 TS:1016, TransportError: connection:0x6d8918f0, code=1, string=WebSocket upgrade failed: Authentication error (401). Please check subscription information and region name.
[25520]: 10822ms SPX_TRACE_ERROR:  usp_reco_engine_adapter.cpp:2134 Response: On Error: Code:1, Message: WebSocket upgrade failed: Authentication error (401). Please check subscription information and region name..
[25520]: 10822ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:2841 TryChangeState; audioState/uspState: 2/1000 => 2/-1 USP-ERRORERROR
```
Subscription keys are region specific so it is likely that the region that the conversation host is using doesn't match that used for the guest.

The simplest solution here: The service issues causing issues with the language codes is now resolved. This means you don't need to specify the endpoint anymore which should resolve your issue.

Alternatively, you need to specify an endpoint for some other reason, you can use a string with placeholders for the region to allow the SDK to automatically substitute the same region as the host is using:
```Java
audioConfig.setProperty(PropertyId.SpeechServiceConnection_Endpoint, "wss://{region}.s2s.speech.microsoft.com/speech/translation/cognitiveservices/v1?usePipelineVersion=1");
```
Other supports placeholders are:
```
{language}      The speech language you are using (e.g. en-US)
{meetingId}     The current conversation ID (e.g. ABCDE)
```

**Comment by juandausa** [comment]
Hi Ralph, thanks for the update.
Yesterday we tested our application and seems that the issue has been fixed.
