### ISSUE TITLE
Is there any way to get the timestamp based on phrase 

### ISSUE THREAD

**Issue by SAIVENKATARAJU** [Azure-Samples/cognitive-services-speech-sdk#1567]
Hi,
I understand Azure provides word level timestamp by giving offset and durations. but is there any way to get timestamp on phrase wise or like whenever speaker takes a pause?

**Comment by BrianMouncer** [comment]
What is the action you want to take for this "event", and are you using single shot recognition, or continuous recognition.?

Without knowing specifically what you are looking for, let me offer some possibilities for continuous recognitions.
This sample code would be a good place to start...

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/191c9492557422e6780ef0432f327326ba912e2b/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L206-L224

In the above sample, you will see there is both a "recognizing" and "recognized" event.
"Recognizing" will happen right away and continue to change as more audio becomes available and it becomes clear what the speaker is saying.

Whereas the "recognized" event will only happen after the service ends a recognition.  e.g. the user spoke for some time, and either came to the end of a sentence, or stopped speaking long enough for the recognizer to end even if it did not sound like the natural end of a sentence.

Both of these can have word level recognition timing events, which you can combine for the entire phrase/recognition.
The "final recognized" event will most likely to be when the user stopped speaking for several seconds.

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/191c9492557422e6780ef0432f327326ba912e2b/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L111-L123

**Comment by SAIVENKATARAJU** [comment]
Thanks for your reply. I will try and update you.

**Comment by glecaros** [comment]
Hi @SAIVENKATARAJU,
Were you able to resolve this?

**Comment by pankopon** [comment]
Closed since no update from the customer since July, please open a new item if more support is needed.
