### ISSUE TITLE
Updating Speech SDK from 1.17 to 1.22 Android

### ISSUE THREAD

**Issue by juandausa** [Azure-Samples/cognitive-services-speech-sdk#1568]
## Describe the question
Hi there, we have an app using the Speech SDK v1.17 and we are trying to include the latest version but, we are having issues with the method `startTranscribingAsync`. Although it can be executed, after a couple of seconds the client receives a canceled event indicating that 'Connection was closed by the remote host. Error code: 1008. Error details: Host Connection Not Found!'.

## To Reproduce

- Create a conversation from the [web](https://translator.microsoft.com).
- Join a conversation using Java SDK 1.17 with DefaultMicrophoneInput.
- Execute StartTranscribingAsync.
- After a couple of seconds a canceled event is received.

## Expected behavior
Be able to use the latest version without errors.

## Platform, Operating System, and Programming Language

OS: Android 12.0
Hardware: Emulated Device
Programming language: Java - Kotlin

## Additional context
Here you can find the [logs](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/9095611/android.log).
The following lines of code are used to join a conversation and start the transcribing process.

```
private fun getAudioConfig(): AudioConfig {
      var audioConfig = AudioConfig.fromDefaultMicrophoneInput()
      if (config.endpoint.isNotEmpty())
          audioConfig.setProperty(ENDPOINT_PROPERTY, config.endpoint)
      if (config.logFile.isNotEmpty())
          audioConfig.setProperty(LOG_FILE_PROPERTY, config.logFile)
      if (config.useMultiChannelAudio)
          audioConfig.setProperty(MULTI_CHANNEL_AUDIO_PROPERTY, "true")

      return audioConfig
}
    
fun startRecord() {
        try {
            conversationTranslator?.startTranscribingAsync()?.get()
        }
        ....
}
```

We appreciate any kind of feedback and suggestions.
Thanks,

**Comment by BrianMouncer** [comment]
How are you creating the conversation, and user profile when you join the conversation?
are they in the same application, or in two different apps?
Is the subscription key the same when creating the user profile and conversation, and later when you use the ConversationID to join a participant to the conversation later?

Was the profile created with the 1.17 SDK or with the 1.22 SDK?

Can you try to reproduce the problem with this public sample?

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/java/jre/conversation-transcription/src/speechsdk/quickstart/Main.java

**Comment by ralph-msft** [comment]
The error you are seeing ``` Error code: 1008. Error details: Host Connection Not Found! ``` is happening because you are setting the multi channel audio property on the AudioConfig.

You do *not* need to set this property at all. Please remove that for the conversation host, as well as all conversation guests.

**Comment by juandausa** [comment]
Hi Ralph, thanks for your prompt response. We could solve the issue by applying that change.
