### ISSUE TITLE
Can't install azure-cognitiveservices-speech package for python

### ISSUE THREAD

**Issue by Serenya** [Azure-Samples/cognitive-services-speech-sdk#157]
I can't install azure-cognitiveservices-speech described in speech service SDK for python https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-python

When I run:

`pip install azure-cognitiveservices-speech`

I get an error message:

 **Could not find a version that satisfies the requirement azure-cognitiveservices-speech (from versions: )
No matching distribution found for azure-cognitiveservices-speech**

I have following configuration:
 - OS: Windwos x64
 - Hardware - x64
 - Programming language: Python
 - Python version 3.6.8
 - pip version 19.0.2

**Comment by chlandsi** [comment]
Can you make sure that you have the 64-bit version of Python installed? Currently, 32-bit Python is not supported.

**Comment by Serenya** [comment]
@chlandsi, you made my day :) Thanks!

**Comment by wiazur** [comment]
I'm having the same issue. But I'm already using Python 3.8.0 64-bit. Windows 10. Any other suggestions? I have installed many other Cognitive Services and they all install OK.

**Comment by krishnappan** [comment]
I also had the same issue with Python 3.8.0 in Windows 10. Then i realized that azure-cognitiveservices-speech is only available for Python 3.5, 3.6 and 3.7 for MacOS, Linux and Windows. So i installed Python 3.6.7 and then installed azure-cognitiveservices-speech on top of Python 3.6.7 without any issues. Hope this clarify you doubt.

**Comment by AnonCoder786** [comment]
> I also had the same issue with Python 3.8.0 in Windows 10. Then i realized that azure-cognitiveservices-speech is only available for Python 3.5, 3.6 and 3.7 for MacOS, Linux and Windows. So i installed Python 3.6.7 and then installed azure-cognitiveservices-speech on top of Python 3.6.7 without any issues. Hope this clarify you doubt.

Thank you👌💓

**Comment by SaahiilM** [comment]
Try using 
`pip3 install azure-cognitiveservices-speech`

I used this to install the services on python 3.8.2 
also I have python 2.7.18 installed in my system.
So to install any packages for python2 I use `pip` and to install any packages in Python 3.7 and later I use `pip3`
