### ISSUE TITLE
speechconfig and audioconfig

### ISSUE THREAD

**Issue by wilsonchua20** [Azure-Samples/cognitive-services-speech-sdk#158]
how do i build speechconfig, audioconfig, IntentRecognizer classes? what do i put inside these classes?

**Comment by zhouwangzw** [comment]
If you are using C#, please refer to https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/intent_recognition_samples.cs to see how to use speechconfig, audioconfig, and IntentRecognizer.
You can also find samples in other languages in this repository too.

**Comment by zhouwangzw** [comment]
The general documentation about speech SDK and speech service is available here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/. You can find API reference docs here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk-reference.

Thanks.

**Comment by wilsonchua20** [comment]
ohh is this for speech SDK? is it different from the rest api? im using java btw.

thanks

**Comment by fmegen** [comment]
the speech sdk is a client side library available for many languages (including java) that provides an API to interact with the speech service. That way, you dont need to use the REST layer.

For an introduction please visit https://docs.microsoft.com/de-de/azure/cognitive-services/speech-service/

**Comment by wilsonchua20** [comment]
may i know what is/are the library i need to import in java for the speech sdk?

**Comment by fmegen** [comment]
please have a look at the quickstart for your platform (from the above link).

for example, java on windows description is here
https://docs.microsoft.com/de-de/azure/cognitive-services/speech-service/quickstart-java-jre

hope that helps
