### ISSUE TITLE
STT on a Python Web App tries to listen to microphone on the server side (SPXERR_MIC_NOT_AVAILABLE)

### ISSUE THREAD

**Issue by cihanunlu** [Azure-Samples/cognitive-services-speech-sdk#1582]
Hello there,   

I have an python web app, developed for research purposes, in which i used Microsoft Text to Speech API (single-shot speech translation). I used "pywebio" python framework and I used Azure speech recognition api.

 But my problem is related to an error i encountered when i want to run the api. The web app, runs perfectly on my own local host. However, when i deployed it on the web using cloud api (i used google cloud for deployment), i get the following error :

`RuntimeError: Exception with an error code:  0xe (SPXERR_MIC_NOT_AVAILABLE) [CALL STACK BEGIN] `

When you take a look at the url you can see the error as well. Here is the link: https://wide-empire-351421.ew.r.appspot.com// 

 I think it is because the api tries to listen to the microphone of the server but it needs to do it on client side. Whats ur take on it?

**Comment by brandom-msft** [comment]
@cihanunlu - you've got it right. Since the app is running on the server, that's where it is trying to source a microphone from and thus fails. If you want to run from the server you could supply audio from a file or stream.

**Comment by cihanunlu** [comment]
> @cihanunlu - you've got it right. Since the app is running on the server, that's where it is trying to source a microphone from and thus fails. If you want to run from the server you could supply audio from a file or stream.

Then how can i use the microphone as the main input through browser and transmit it to the server as a stream? I know that there are pull stream and push stream sample codes in GitHub speech SDK. However, I could not figure it out. Either way, what i wanted to do is to make the user use his/her mic. Do you have any idea @brandom-msft ?

**Comment by brandom-msft** [comment]
Is there a specific reason why you want to deploy to the web with a python webapp? If you are strongly wedded to a python middle-tier scenario, then you would need to write some companion app that will capture and transmit audio to your service.

Another option would be to use the JavaScript SDK. When users access your site, the JS implementation can leverage their browser's microphone access to capture/send audio. If you're not doing anything complex with the captured audio, this is probably your fastest/simplest, most direct path forward.

You can read more documentation to get started [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/quickstarts/setup-platform?pivots=programming-language-javascript&tabs=windows%2Cubuntu%2Cdotnet%2Cjre%2Cmaven%2Cbrowser%2Cmac%2Cpypi)

And [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/browser) are some JS browser samples

**Comment by cihanunlu** [comment]
> Is there a specific reason why you want to deploy to the web with a python webapp? If you are strongly wedded to a python middle-tier scenario, then you would need to write some companion app for users to run locally that will capture and transmit audio to your service.
> 
> Another option would be to use [the JavaScript SDK](https://docs.microsoft.com/azure/cognitive-services/speech-service/quickstarts/setup-platform?pivots=programming-language-javascript&tabs=windows%2Cubuntu%2Cdotnet%2Cjre%2Cmaven%2Cbrowser%2Cmac%2Cpypi). When users access your site, the JS implementation can leverage their browser's microphone access to capture/send audio. If you're not doing anything complex with the captured audio, I think this is probably your fastest/simplest, most direct path forward.
> 
> Additionally, [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/browser) are some JS browser samples

Well, the reason why i want to deploy the app on python is that I recently discovered Pywebio framework in which I am, without any difficulty, able to deploy it without using html or css. Could you provide some examples of these "companion apps".? Do you mean a third party app out of the main program?

JavaScript SDK seems great but it needs additional html coding and i do not have experience in JS. This was another thing why i used python.

**Comment by glecaros** [comment]
Hi @cihanunlu, I'm closing this issue as it has been clarified. Please open a new issue if you run into other problems. Thanks
