### ISSUE TITLE
SDK (spx) (on CMD) audio to text transcription error: 

### ISSUE THREAD

**Issue by asad1910** [Azure-Samples/cognitive-services-speech-sdk#1586]
**Describe the bug**
While the Spx is transcribing on CMD, at times (not all the time) it gives an error saying, please check your subscription.  
While my subscription is perfectly fine and all. Even the dues are all paid on time. 
I feel like maybe it loses connection? But says to check the subscription.

**To Reproduce**
Happens randomly

**Expected behavior**
the transcription stops in the middle and the error pops up. 

**Version of the Cognitive Services Speech SDK**
latest

**LOG FILE IS ATTACHED**
[log-133029040687365538.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/9167126/log-133029040687365538.log)

**Comment by brandom-msft** [comment]
Hi @asad1910 - thank you for providing a log. From there I can see it's not losing connection, but there does seem to be very high latency on the recognition from the service. I'm routing to the appropriate team for investigation, in the meantime can you share some more details? You mentioned, this happens randomly - at what frequency or how often would you estimate this is occuring?

**Comment by HenryvanderVegte** [comment]
Hi @asad1910 ,

could you provide the exact error message you are receiving, as well as a session id when the subscription error happens?
In the log file I can find the high decoder latency, but no indication of a subscription error.

Thanks!
Henry

**Comment by asad1910** [comment]
@brandom-msft It usually happens like once or twice a week. Completely random. I still feel like it's the internet issue.

**Comment by asad1910** [comment]
@HenryvanderVegte  Hi there
I will write it down if it ever happens again. 
Also what does high decoder latency means? Internet issue?

**Comment by HenryvanderVegte** [comment]
Hi @asad1910 ,

thanks! Please also provide a timestamp when it occurs!
Decoder latency means that it took us a bit longer than usual to transcribe your audio, might have been related to a higher load in our cluster. This is unrelated to the subscription error message you're seeing.

Thanks!
Henry

**Comment by glecaros** [comment]
hi @asad1910,
Did you continue to run into this issue?

**Comment by asad1910** [comment]
hi @glecaros 
Nope, so far so good. 
Feel free to close this post though.
