### ISSUE TITLE
Crash at EXC_BAD_ACCESS usp_reco_engine_adapter.cpp:2983

### ISSUE THREAD

**Issue by toddtian** [Azure-Samples/cognitive-services-speech-sdk#1589]
Describe the bug
I received a crash reports, the crash reason is:

EXC_BAD_ACCESS: Attempted to dereference null pointer at usp_reco_engine_adapter.cpp:2983

I have posted details stack trace in Additional context.

To Reproduce
Unknown, it crashed after the session starting about 1900 seconds.

Expected behavior

Version of the Cognitive Services Speech SDK

MicrosoftCognitiveServicesSpeech-iOS (1.22.0)
Platform, Operating System, and Programming Language

iOS 15.5
iPhone 6S
Swift

Additional context

Exception Type:     EXC_BAD_ACCESS 
Exception Subtype:  KERN_INVALID_ADDRESS

EXC_BAD_ACCESS: Attempted to dereference null pointer.

0  MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::Impl::CSpxUspRecoEngineAdapter::OnTurnEnd(Microsoft::CognitiveServices::Speech::USP::TurnEndMsg const&) (usp_reco_engine_adapter.cpp:2983:26)
1  MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::USP::CSpxUspCallbackWrapper::OnTurnEnd(Microsoft::CognitiveServices::Speech::USP::TurnEndMsg const&)::{lambda(std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::USP::ISpxUspCallbacks>)#1}::operator()(std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::USP::ISpxUspCallbacks>) const (usp_callbacks.h:158:134)
2  MicrosoftCognitiveServicesSpeech _ZZN9Microsoft17CognitiveServices6Speech3USP17CSpxUspConnection15OnTransportDataEbRKNSt3__13mapINS4_12basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEESB_NS4_4lessISB_EENS9_INS4_4pairIKSB_SB_EEEEEEPKhmENK4$_12clINS4_10shared_ptrINS2_9CallbacksEEEEEDaT_ (usp_connection.cpp:1086:57)
3  MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::USP::CSpxUspConnection::Invoke(std::__1::function<void (std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::USP::Callbacks>)>) (functional:1885:16)
4  MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::USP::CSpxUspConnection::OnTransportData(bool, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, unsigned char const*, unsigned long) (usp_connection.cpp:1086:17)
5  MicrosoftCognitiveServicesSpeech unsigned long Microsoft::CognitiveServices::Speech::Impl::event<std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::add<Microsoft::CognitiveServices::Speech::USP::CSpxUspConnection>(std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::USP::CSpxUspConnection>, void (Microsoft::CognitiveServices::Speech::USP::CSpxUspConnection::*)(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&))::{lambda(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)#1}::operator()(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const (event.h:44:21)
6  MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::Impl::event<std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::raise(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) (functional:1885:16)
7  MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::USP::UspWebSocket::HandleTextData(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) (event.h:79:51)
8  MicrosoftCognitiveServicesSpeech unsigned long Microsoft::CognitiveServices::Speech::Impl::event<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::add<Microsoft::CognitiveServices::Speech::USP::UspWebSocket>(std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::USP::UspWebSocket>, void (Microsoft::CognitiveServices::Speech::USP::UspWebSocket::*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&))::{lambda(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)#1}::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const (event.h:44:21)
9  MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::Impl::event<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::raise(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) (functional:1885:16)
10 MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::Impl::CSpxWebSocket::OnWebSocketFrameReceived(unsigned char, unsigned char const*, unsigned long) (web_socket.cpp:1004:17)
11 MicrosoftCognitiveServicesSpeech void Microsoft::CognitiveServices::Speech::Impl::CSpxWebSocket::cast_and_invoke<unsigned char, unsigned char const*, unsigned long>(void*, void (Microsoft::CognitiveServices::Speech::Impl::CSpxWebSocket::*)(unsigned char, unsigned char const*, unsigned long), unsigned char, unsigned char const*, unsigned long) (web_socket.h:129:25)
12 MicrosoftCognitiveServicesSpeech on_underlying_io_bytes_received (uws_client.c:1423:37)
13 MicrosoftCognitiveServicesSpeech dowork_read (tlsio_appleios.c:500:21)
14 MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::Impl::CSpxWebSocket::DoWork() (web_socket.cpp:809:22)
15 MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::Impl::CSpxWebSocket::WorkLoop(std::__1::weak_ptr<Microsoft::CognitiveServices::Speech::Impl::CSpxWebSocket>)::$_8::operator()() const (web_socket.cpp:769:26)
16 MicrosoftCognitiveServicesSpeech std::__1::packaged_task<void ()>::operator()() (future:1866:12)
17 MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::Impl::CSpxThreadService::Task::Run() (thread_service.cpp:159:9)
18 MicrosoftCognitiveServicesSpeech void Microsoft::CognitiveServices::Speech::Impl::CSpxThreadService::Thread::RunTask<std::__1::pair<std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::Impl::CSpxThreadService::Task>, std::__1::promise<bool> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::deque<std::__1::pair<std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::Impl::CSpxThreadService::Task>, std::__1::promise<bool> >, std::__1::allocator<std::__1::pair<std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::Impl::CSpxThreadService::Task>, std::__1::promise<bool> > > >&) (thread_service.h:215:23)
19 MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::Impl::CSpxThreadService::Thread::WorkerLoop(std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::Impl::CSpxThreadService::Thread>) (thread_service.cpp:328:27)
20 MicrosoftCognitiveServicesSpeech _ZNSt3__1L8__invokeIPFvNS_10shared_ptrIN9Microsoft17CognitiveServices6Speech4Impl17CSpxThreadService6ThreadEEEEJS8_EEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOSB_DpOSC_ (type_traits:3694:1)
21 libsystem_pthread.dylib          __pthread_start

**Comment by dargilco** [comment]
This is likely the same as https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1555, but with a newer version of the SDK.

**Comment by glecaros** [comment]
Closing as the fix to this has is part of the latest release of the SDK.
