### ISSUE TITLE
How to set the recognition result without punctuation?

### ISSUE THREAD

**Issue by zhengxiangw** [Azure-Samples/cognitive-services-speech-sdk#159]
Current recognition results all have punctuation marks. 
How to set the recognition result without punctuation?

**Comment by zhouwangzw** [comment]
If you use Detailed output format (https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.outputformat?view=azure-dotnet), you can get the lexical form (https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.detailedspeechrecognitionresult.lexicalform?view=azure-dotnet#Microsoft_CognitiveServices_Speech_DetailedSpeechRecognitionResult_LexicalForm). Is this something you are looking for?

**Comment by zhengxiangw** [comment]
Thank you!
But how can I get the result "DetailedSpeechRecognitionResult"?

Here's my code:
final Future<SpeechRecognitionResult> task = speechRecognizer.recognizeOnceAsync();

The return type is "SpeechRecognitionResult". Can you tell me how to do it? thank you very much.

**Comment by zhouwangzw** [comment]
SpeechRecognitionResult.Properties.GetProperty(PropertyId::SpeechServiceResponse_JsonResult) will return a JSON string which contains detailed output.
Thanks,
Zhou
