### ISSUE TITLE
Creating SpeechRecognizer suddenly fails: endSilenceTimeoutMs should always be greater than 0

### ISSUE THREAD

**Issue by luksurious** [Azure-Samples/cognitive-services-speech-sdk#1591]
**Describe the bug**
We have been using the Java SDK to create SpeechRecognizers in our system. In a recent [issue](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1132), it was suggested to set the parameter `EndSilenceTimeout` to 0 to avoid the described issue.

A few days ago, our system started to fail due to the following error
```
Connection was closed by the remote host. Error code: 1011. Error details: Protocols.Core.BadClientRequestException: endSilenceTimeoutMs should always be greater than 0.
```

Setting the property to a value greater than 0 works.

However, since this was suggested here to use that value, we are

* unsure why this changed
* what another good value to solve the [issue 1132](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1132#) would be

We were also concerned that this change broke our system suddenly.

**To Reproduce**
1. Use the Demo Application from [1132](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1132) 
2. Change the value for `endSilenceTimeoutMs` to 0

**Expected behavior**
We expect the value to be supported, and a SpeechRecognizer to be created successfully

**Version of the Cognitive Services Speech SDK**
Tested with Java SDK 1.17.0 and 1.22.0

**Platform, Operating System, and Programming Language**
 - OS: macOS
 - Hardware - x64
 - Programming language: Java

**Additional context**

[speechLog.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/9184888/speechLog.txt)

**Comment by brandom-msft** [comment]
Thanks for raising the issue, I'm routing to the appropriate team to investigate further.

**Comment by HenryvanderVegte** [comment]
Hi @luksurious ,

we have stopped supporting 0 as silenceTimeouts as it relies on the silence timeout behaviour of our decoders, which might change in the future and be inconsistent. I have created a hotfix to allow 0 silenceTimeouts again, and we'll look into other solutions.

We sincerely apologize for breaking your system, and I'll post an update as soon as the rollback is rolled out.

Thanks!
Henry

**Comment by luksurious** [comment]
Hi @HenryvanderVegte, thank you!

Also thanks for the explanation on the reasoning, we will investigate what value is most appropriate then.

**Comment by HenryvanderVegte** [comment]
Hi @luksurious ,

we have rolled back the change, silence timeouts of 0 should not result in a BadClientRequestException anymore. Please let me know if it works for you.

However, as you said, I'd recommend you to set a silence timeout that fits your scenario instead of 0.

Thanks!
Henry

**Comment by glecaros** [comment]
Closing this issue based on the latest response.
