### ISSUE TITLE
Issues connecting to microphone using systemd

### ISSUE THREAD

**Issue by michaelshorter** [Azure-Samples/cognitive-services-speech-sdk#1594]
Hello,

I have created a script using speech to text that when run in terminal works perfectly, but when run during startup using systemd gives me an error that I think means it's not finding the microphone.

Here is the error it throws up:

 JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
 JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
 ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
 ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused
 Unhandled exception. System.ApplicationException: Exception with an error code: 0xe (SPXERR_MIC_NOT_AVAILABLE)
    at Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail(IntPtr hr)
   at Microsoft.CognitiveServices.Speech.Recognizer.FromConfig(GetRecognizerFromConfigDelegate fromConfig, SpeechConfig speechConfig, AudioConfig audioConfig)
   at Microsoft.CognitiveServices.Speech.SpeechRecognizer..ctor(SpeechConfig speechConfig, AudioConfig audioConfig)
    at Program.Main(String[] args) in /home/wordcloud/WordCloud/AzureSpeechCC/Program.cs:line 35
   at Program.<Main>(String[] args)

You can find my code here if that's useful - https://github.com/michaelshorter/WordCloud

I've also tried auto starting my script using cron and rc.local but still no joy. I presume the same issue is happening here but I'm not able to debug it so easily.  

Has anyone had this issue before? If so I'd massively appreciate some pointers on how to fix it!

Cheers,
M

**Comment by brandom-msft** [comment]
Hi @michaelshorter 
What are you running this on? Capturing a log might give us more information
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

The error does look to indicate a failure to get microphone access. Since you mentioned this fails when trying to run at startup, I'm wondering if your hardware is active and/or if any sort of microphone access needs to be granted.

**Comment by glecaros** [comment]
Hi @michaelshorter, was your issue resolved, or were you able to capture logs as @brandom-msft suggested?

**Comment by michaelshorter** [comment]
Hi @brandom-msft @glecaros 
It was an issue accessing the right port for the microphone. The problem was fixed by specifying the default sound card that I wanted to use. Still no idea why this was only an issue when running the file with a service file.... Here is a link to the forum post that saved the day:

[(https://askubuntu.com/questions/150851/how-do-i-select-a-default-sound-card-with-alsa
)]

**Comment by glecaros** [comment]
great! glad to you were able to solve it, I'll go ahead and close the issue then
