### ISSUE TITLE
How can i resume the speech from paused position of the provided input to for synthesizer for android.

### ISSUE THREAD

**Issue by harsha-osi** [Azure-Samples/cognitive-services-speech-sdk#1597]
I Am trying to implement text-to-speech functionality.
For that, I am getting an input text string as a response from the web server.
once is received then the user can able to do play and pause and play from the paused position and all.
Please provide how can i handle it.

**Comment by yulin-li** [comment]
For now, the palyback functionality of Android SDK doesn't support `pause` or `resume`. You can get the audio binary and use `AudioTrack` for playback.

**Comment by harsha-osi** [comment]
Thank you for the quick reply, can you please share the piece of code which is used to convert audio binary?

**Comment by pankopon** [comment]
@harsha-osi Please see https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/java/android/SpeechSynthesis for an example of using AudioTrack API with AudioDataStream from the synthesis result.

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
