### ISSUE TITLE
How can i resume the speech from paused position of the provided input to for synthesizer for iOS.

### ISSUE THREAD

**Issue by snomula05** [Azure-Samples/cognitive-services-speech-sdk#1598]
Hi,

I am trying to implement the Text to speech functionality in the iOS Swift application for which I have used the updated pod version of "MicrosoftCognitiveServicesSpeech"

1. While Playing the Audio from the Speech Synthesizer, We didn't find the Speech Resume feature in MicrosoftCognitiveServicesSpeech SDK, please let me know how we can fix this issue.

**Comment by yulin-li** [comment]
For now, the palyback functionality of iOS SDK doesn't support `pause` or `resume`. You can get the audio binary and play it using apple's api

**Comment by snomula05** [comment]
Thank you for the quick reply, can you please share the piece of code which is used to convert audio binary by using apple's API? we didn't find any information on it.

**Comment by pankopon** [comment]
@snomula05 It's the same principle as in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1597.

For how to get `SPXAudioDataStream` from the synthesis result, refer to
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/4af1b8e7f2ff0c47a12d627a0b7a4bb37b7b4063/samples/objective-c/ios/synthesis-samples/synthesis-samples/ViewController.m#L363

For audio playback on iOS, see e.g.
https://stackoverflow.com/questions/50996398/play-audio-on-ios-from-a-memory-data-stream

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
