### ISSUE TITLE
About output file (python)

### ISSUE THREAD

**Issue by ConnorXuHeeee** [Azure-Samples/cognitive-services-speech-sdk#1601]
Hi!

I want to know that the file -captioning.py, its relevant output file according to cmd : 
python captioning.py --key YourSubscriptionKey --region YourServiceRegion --input caption.this.mp4 --format any --output caption.output.txt - --srt --recognizing --threshold 5 --profanity mask --phrases "Contoso;Jessie;Rehaan"

I can't find caption.output.txt, but the program can still go well on cmd, but i want to know where the output file 

Best,
Connor

**Comment by rhurey** [comment]
Thanks for pointing this out, it looks like the helper file has a bug in it.

See if PR #1604 resolves things for you.

**Comment by glecaros** [comment]
Hi @ConnorXuHeeee, were you able to resolve the issue?

**Comment by pankopon** [comment]
Closed as fixed, please open a new issue if more support is needed.
