### ISSUE TITLE
Speech Recognition with Push Stream not providing correct results

### ISSUE THREAD

**Issue by simplyatul** [Azure-Samples/cognitive-services-speech-sdk#1606]
**Describe the bug**
I am using JRE based console sample (https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console) to verify the Speech Recognition.

A same audio file is provided to each of the function call continuousRecognitionWithFileAsync and continuousRecognitionWithPushStream respectively. continuousRecognitionWithFileAsync provides correct result, however  continuousRecognitionWithPushStream result is way off. 

Here is the console output
```
Your choice (0: Stop): 5

Say something...
Press any key to stop

    Session started event.
RECOGNIZING: Text=yeah
RECOGNIZING: Text=yeah the call
RECOGNIZING: Text=yeah the call is connected
RECOGNIZED: Text=Yeah, the call is connected.
RECOGNIZING: Text=again
RECOGNIZING: Text=again we can
RECOGNIZING: Text=again we can see
RECOGNIZING: Text=again we can see data
RECOGNIZING: Text=again we can see data on the wave
RECOGNIZING: Text=again we can see data on the wave files
RECOGNIZED: Text=Again, we can see data on the wave files.
RECOGNIZING: Text=and i'm
RECOGNIZING: Text=and i'm dropping
RECOGNIZING: Text=and i'm dropping the call
RECOGNIZED: Text=And I'm dropping the call.
CANCELED: Reason=EndOfStream

    Session stopped event.


Execution done. Your choice (0: Stop): 
16

Say something...

    Session started event.
Press any key to stop
RECOGNIZING: Text=1
RECOGNIZED: Text=1.
RECOGNIZING: Text=i don't know
RECOGNIZED: Text=
CANCELED: Reason=EndOfStream

    Session stopped event.

```

**To Reproduce**
- Configure the Subscription Key, Region and Audio File
- Run the Java Console application using
```
mvn clean package && java -jar ./target/SpeechSDKDemo-0.0.1-SNAPSHOT-jar-with-dependencies.jar
```
- Select option 5
- Once it finishes, select option 16
- Observe results are different.

**Expected behavior**
Option 16 (continuousRecognitionWithPushStream) should show the correct speech recognition result. 

**Version of the Cognitive Services Speech SDK**
Using the master branch. On Commit ID -
```
commit 367d9dff4dd470243795ab48373ed3053cbb1e78 (HEAD -> master, origin/master, origin/HEAD)
Author: Jason Wells <30323598+v-jaswel@users.noreply.github.com>
Date:   Thu Jul 28 13:01:45 2022 -0700
```

**Platform, Operating System, and Programming Language**
 - OS: Win10
 - Hardware: x64
 - Programming language: Java
 - Browser: not applicable

**Additional context**
Please find attached call_audio.wav file
[call_audio.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/9242212/call_audio.zip)

**Comment by rhurey** [comment]
Thanks for trying the SDK. The wav file was key in solving this one.

The audio in the file is 8Khz, and the file reader will read the wave header and send that information to the Speech Service.

With Stream based audio, the default audio is 16Khz 16 bit mono, but a different format can be specified to the PushAudioInputStream.

`PushAudioInputStream pushStream = AudioInputStream.createPushStream(AudioStreamFormat.getWaveFormatPCM((long)8000, (short)16, (short)1));`

I'll update the sample to have better information in it about this.

**Comment by simplyatul** [comment]
Thank you @rhurey.  Push Stream starts working correctly post the change you have suggested.

Yes, it would be good idea to update the sample with the wave format information.
