### ISSUE TITLE
How can I use the SSML to only get the bookmark audio_offset ?

### ISSUE THREAD

**Issue by Lucien20000118** [Azure-Samples/cognitive-services-speech-sdk#1609]

**Comment by Lucien20000118** [comment]
I use the azure.cognitiveservices.speech.SpeechSynthesisBookmarkEventArgs to get the property(audio_offset).
But, `print(azure.cognitiveservices.speech.SpeechSynthesisBookmarkEventArgs.audio_offset)`, came out this `<property object at 0x000002164397C860>`.
I have no ideal how to sovle this qustion, if I have wrong understand please tell me thank you.

**Comment by ralph-msft** [comment]
```speechsdk.SpeechSynthesisBookmarkEventArgs.audio_offset``` is a property of the ```SpeechSynthesisBookmarkEventArgs``` class.

You can see this using:
```python
import azure.cognitiveservices.speech as speechsdk
print(type(speechsdk.SpeechSynthesisBookmarkEventArgs.audio_offset))
```
This will output
```
<class 'property'>
```

To access the value  of audio_offset property, you need to read the value of the instance returned in the bookmark_reached event handler as you are already doing in your code above:
```python
speech_synthesizer.bookmark_reached.connect(lambda evt: print(
    "audio offset: {}ms".format(evt.audio_offset / 10000)))
```

**Comment by Lucien20000118** [comment]
Thanks your reply.
So I can't read the value only call `speechsdk.SpeechSynthesisBookmarkEventArgs.audio_offset`?
If I want to save those audio_offset to a list, how can I do?
