### ISSUE TITLE
Cognitive Speech Translation - Capturing Audio

### ISSUE THREAD

**Issue by pink2468** [Azure-Samples/cognitive-services-speech-sdk#1612]
Greetings,

We are using the cognitive speech translation service in Xamarin Forms. We would like to capture the spoken audio that resulted int the translation. Is there a way to capture this audio?

Regards

**Comment by pankopon** [comment]
Hi, you would need to capture microphone audio using some (platform/framework specific) audio API in your application, outside the Speech SDK, and stream the captured audio in push mode to the Speech SDK.
We have no Xamarin or translation specific examples of this, but there is a speech-to-text sample (for .NET with NAudio API, but in C# anyway) that demonstrates the principle:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/csharp/dotnet-windows/speechtotext-naudio

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
