### ISSUE TITLE
StatusCode="FailedPrecondition", Detail="Voice does not match"

### ISSUE THREAD

**Issue by MichalWysockiLeonardo** [Azure-Samples/cognitive-services-speech-sdk#1616]
Hi 
We deployed the Cognitive Services container and trying to convert text to speech using SpeechSDK. 

Our code:
var speechConfig = SpeechConfig.FromHost(new Uri("ws://localhost:5000"));

using (var speechSynthesizer = new SpeechSynthesizer(speechConfig))
{
    var speechSynthesisResult = await speechSynthesizer.SpeakSsmlAsync(Ssml);

    OutputSpeechSynthesisResult(speechSynthesisResult, Ssml);
}

SSML:
<speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="en-US"><voice name="en-GB-LibbyNeural">
 Welcome to Microsoft Cognitive Services <break time="100ms" /> Text-to-Speech API.
</voice></speak>

We get the following error:

Connection was closed by the remote host. Error code: 1007. Error details: Status(StatusCode="FailedPrecondition", Detail="Voice does not match") USP state: 3. Received audio size: 0 bytes.

Do you know what is causing this error?

Regards,
Mike

**Comment by chschrae** [comment]
Hi there,

I would guess that the voice specified in the speechConfig or the ssml doesn't exist. Could you share the ssml you are using?

Is there anywhere that you are setting the voice to use?

**Comment by glecaros** [comment]
Hi @MichalWysockiLeonardo, were you able to verify if a voice is being set like @chschrae  suggested?

**Comment by pankopon** [comment]
Ref. https://docs.microsoft.com/azure/cognitive-services/speech-service/speech-container-faq?tabs=stt#could-you-explain-these-errors-from-the-custom-speech-to-text-container-
**Error 2:** "Voice does not match."
> You need to provide the correct voice name in the request, which is case-sensitive. Refer to the full service name mapping.

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
