### ISSUE TITLE
Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 703

### ISSUE THREAD

**Issue by ati-ince** [Azure-Samples/cognitive-services-speech-sdk#1618]
**Is your feature request related to a problem? Please describe.**
When we run TTS and STT methods from azure speech, sometimes receive the **Connection Error**
Using TTS and STT we create an audio file from text (tts) and use an audio file for transformation to text (stt)
The main problem is here success rate of these methods is not predictable, and connection error rate waves between %1-%50 
We want to know why this error is happening and how to avoid that.

**Describe the solution you'd like**
Receiving a more meaningful message from azure, to understand what is causing this. 

**Additional context**
We are using Azure Speech Python SDK, the latest version of **azure-cognitiveservices-speech == 1.19.0**
SDK run on **Win10** machine with **Py3.6** on **Anaconda** virtualization
The PC has a proxy setting like addr='proxy.xx.yy' or '1234.345.56.67' and port=1234 or 8080 etc.  

**How we set proxy:**

```
speech_config = SpeechConfig(subscription=self.keysub, region=self.location)
translation_config = SpeechTranslationConfig(subscription=self.keysub, region=self.location)
speech_config.set_proxy(hostname=self.proxy_addr,port=self.proxy_port, username="", password="")
translation_config.set_proxy(hostname=self.proxy_addr,port=self.proxy_port, username="", password="")
```

**How we use methods**
TTS

```
audio_config = AudioConfig(filename=file_name)
recognizer = TranslationRecognizer(translation_config=translation_config, audio_config=audio_config)
result = recognizer.recognize_once() 
```

STT

```
audio_config = AudioConfig(filename=file_name)
speech_config.speech_recognition_language = language
speech_recognizer = SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)
result = speech_recognizer.recognize_once_async().get() 
```

**Some Error Message for Showing Connection Error:**

`
Connection Error <CancellationErrorCode.ConnectionFailure> [SpeechSynthesisCancellationDetails(reason=CancellationReason.Error, error_details="Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 703. USP state: 2. Received audio size: 0 bytes.")]
`

`
Connection Error <CancellationErrorCode.ConnectionFailure> [CancellationDetails(reason=CancellationReason.Error, error_details="Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 703. SessionId: 5fb3b2b4901a41adbb735f69f39e095d")]
`

**Comment by chschrae** [comment]
Hi there,
The latest version of the speechsdk is 1.23 and the install instructions have a blurb about requiring python > 3.7: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/setup-platform?pivots=programming-language-python&tabs=windows%2Cubuntu%2Cdotnet%2Cjre%2Cmaven%2Cnodejs%2Cmac%2Cpypi

Assuming that upgrading does not solve your problem is it possible to enable logging and upload the file results?
https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/cognitive-services/Speech-Service/how-to-use-logging.md

**Comment by ati-ince** [comment]
Hi @chschrae 

I have been testing with 3.6 and 3.8 for comparison,
Fyi, When I prepared env for 3.8 azure version became  1.17 I hope we can consider the latest version. Or Is it not an approved stable version? 

I did not understand the logging part you shared (why is necessary for using azure speech), I haven't seen in the sample codes. If the first solution doesn't work will try the second too.

**Comment by chschrae** [comment]
Hi @ati-ince,

There should be a speechsdk version for which the latest is 1.23.  1.17 is still available, but of course we continue to improve the SDK and therefore the latest version is usually the best.

The logging is for the sdk library which is running as part of your application, so there is no way to collect logs from the service side. It certainly isn't necessary to run with the logging on, but it is a feature provided in case we need to debug customer issues like this.

**Comment by glecaros** [comment]
Hi @ati-ince, just to follow up, was your issue resolved?

**Comment by ati-ince** [comment]
Hi @glecaros
I have been running some tests, I will update the result in couple of days

**Comment by pankopon** [comment]
@ati-ince Please update with results from testing with the latest Speech SDK.

**Comment by ati-ince** [comment]
Hello, 
After searching similar complaints into other issues I found an issue same behavior/error as mine:

[https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/352](url) issue creator hasn't confirmed yet new releases solve the problem. The only solution looking like deleting manually `del SpeechRecognizer._impl`

Btw, my results after tested 3.6 <-> 3.8 , 1.17.0 <-> 1.23.0 versions py/azure:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/AIN8588/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/AIN8588/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Python--version | azure--version | Language | Total-Test-Case-Number | ConnErr Rate(%) | ConnectionError
-- | -- | -- | -- | -- | --
3.6 | 1.18 | EN | 191 | 17.8 | 34
3.8 | 1.23 | EN | 191 | 15.2 | 29
3.8 | 1.17 | EN | 191 | 23.6 | 45



</body>

</html>

**Comment by ati-ince** [comment]
Dear development team, 

The problem still continues in python3.6-azure 1.19.0 and python 3.8 - azure 1.23.0

Here is my test result, the problem behaves the same in both env and in different usage profiles. 

Below you will see although the test profile differences the results are similar, the test continues for 15 min successfully then the failure starts, and it continues like that. 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/AIN8588/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/AIN8588/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



100 ms sleep time between 2 request | 1 sec sleep time between 2 request | 30 sec sleep time between 2 request
-- | -- | --
success   num | succ minute | fail | fail minute | success | min | fail | min | success | min | fail | min
1870 | 11 | 8 | 1 | 661 | 15 | 90 | 9 | 31 | 15 | 5 | 2
2608 | 15 | 49 | 4.5 | 681 | 15 | 136 | 14 | 60 | 29 | 3 | 1
2481 | 15 | 6 | 0.5 | 684 | 15 | 93 | 10 | 31 | 15 | 9 | 5
2458 | 15 | 93 | 9 | 685 | 15 | 43 | 4 | 31 | 15 | 16 | 9
2358 | 15 | 34 | 3 | 681 | 15 | 51 | 5 | 31 | 15 | 25 | 14
2365 | 15 | 52 | 4.5 | 684 | 19 | 85 | 9 | 31 | 15 | 14 | 8
2318 | 15 | 72 | 6.5 | 688 | 15 | 94 | 10 | 31 | 15 | 11 | 6



</body>

</html>

**Comment by ati-ince** [comment]
Hello, 
I am closing this issue. The cause of the problem -finally- was discovered. 
We are working under VPN/Proxy so when I canceled these settings there was no problem. 

I am writing here for future help.

**Comment by hazelement** [comment]
Hi I'm experience similar issues since yesterday, and I'm not using VPN. Here is the sample code I got from azure site

```
import os
import azure.cognitiveservices.speech as speechsdk
# This example requires environment variables named "SPEECH_KEY" and "SPEECH_REGION"
speech_config = speechsdk.SpeechConfig(subscription=<my_token>,
                                       region='eastus')
audio_config = speechsdk.audio.AudioOutputConfig(use_default_speaker=True)

# The language of the voice that speaks.
speech_config.speech_synthesis_voice_name = 'en-US-JennyNeural'

speech_synthesizer = speechsdk.SpeechSynthesizer(speech_config=speech_config, audio_config=audio_config)

# Get text from the console and synthesize to the default speaker.
print("Enter some text that you want to speak >")
text = ' this is a test'

speech_synthesis_result = speech_synthesizer.speak_text_async(text).get()

if speech_synthesis_result.reason == speechsdk.ResultReason.SynthesizingAudioCompleted:
    print("Speech synthesized for text [{}]".format(text))
elif speech_synthesis_result.reason == speechsdk.ResultReason.Canceled:
    cancellation_details = speech_synthesis_result.cancellation_details
    print("Speech synthesis canceled: {}".format(cancellation_details.reason))
    if cancellation_details.reason == speechsdk.CancellationReason.Error:
        if cancellation_details.error_details:
            print("Error details: {}".format(cancellation_details.error_details))
            print("Did you set the speech resource key and region values?")
```

and here is the error

```
-> % python test.py
Enter some text that you want to speak >
Speech synthesis canceled: CancellationReason.Error
Error details: Connection failed (no connection to the remote host). Internal error: 1. Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED
wss://eastus.tts.speech.microsoft.com/cognitiveservices/websocket/v1
X-ConnectionId: f4713bad8b604f108c1355a4cdf65bd8 USP state: Sending. Received audio size: 0 bytes.
Did you set the speech resource key and region values?
```

Azure status, https://azure.status.microsoft/en-ca/status, shows text to speech has no issues. Can anyone share some insights how to fix this?

I'm using the latest package, 

```
-> % pip freeze
azure-cognitiveservices-speech==1.27.0
```

**Comment by johannes-manner** [comment]
Hi, I had the same problem.
Maybe someone out there is also searching for a solution. The proxy comment gave the right hint, but it took me same time to understand which proxy.
In the code, you can configure the 
`Config = SpeechConfig.FromSubscription(key.ApiKey, key.Region);`.
In our code, we also configured the proxy for the `SpeechConfig`. This is the line you should delete :)
`Config.SetProxy(proxy.Host, proxy.Port);`
After removing this specific proxy configuration - it worked for me :)
Thanks @ati-ince for your thorough investigation!!
