### ISSUE TITLE
How to listen and restore the connection failure when using Azure SDK for JavaScript ConversationTranslator 

### ISSUE THREAD

**Issue by pengchengZhi001** [Azure-Samples/cognitive-services-speech-sdk#1619]
![无标题](https://user-images.githubusercontent.com/74509598/185290320-10708254-871b-4795-a872-bc1029569c06.png
![无标题](https://user-images.githubusercontent.com/74509598/185290409-e07bec6e-bd12-4bf0-aee7-1529636cb360.png)
)

**Comment by chschrae** [comment]
Hi there, 
There are many network related issues that could cause this timeout. Without more information I would check your internet access. 

Assuming everything there is working, can you provide more details on what you are experiencing? I understand this is the javascript SDK. Are you using the latest version? Does this work sometimes or never at all?

Are you willing to provide some sample code?

Can you enable the sdk logging and provide the result here?
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

**Comment by pengchengZhi001** [comment]
It is good at the beginning of the use process. After a period of time, this problem occurs. I need to listen to this situation, and then reconnect

**Comment by pengchengZhi001** [comment]
This situation is relatively easy to appear transnational translation

**Comment by chschrae** [comment]
@pengchengZhi001 How long does it take for the error to appear? Were you able to collect logs on a failure?

**Comment by pankopon** [comment]
@glharper @rhurey Please check when you have time.
