### ISSUE TITLE
Unity Build Following Quick Start Doesn't Have Necessary DLLs

### ISSUE THREAD

**Issue by Brandon-Franklin** [Azure-Samples/cognitive-services-speech-sdk#162]
**Describe the bug**
Following the Quick Start for the Unity (2018.3) implementation for Azure Cognitive Services doesn't included Microsoft.CognitiveServices.Speech.core.dll in the "managed" folder for the unity build but it does include them in the "PlugIns" folder. In order to not have issues I must manually copy that dll over into the managed folder.
**To Reproduce**
1. Start a new project using 2018.3
2. Import the Unity package for Azure Speech Services SDK
3. Follow the set up steps on https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-csharp-unity into a new document
4. Copy the text from Quick Start Guide to a new C# Script in Unity
5. Match the class name to the document name in Unity
6. Make sure you're Player Settings are set to 4.X C#
7. Test to ensure that your UI is working with the speech service in editor
8. Create a Standalone Windows build of the project
9. Run the build that's created
10. Observe the missing DLL error

**Expected behavior**
The service works in the editor, I would expect the service to work as well in the builds created.

**Version of the Cognitive Services Speech SDK**
Using version 1.3.0 for the SDK

**Platform, Operating System, and Programming Language**
 - OS: Windows 10 - up to date
 - Hardware - x64
 - Programming language: C#

**Additional context**
Using Unity 2018.3.

**Comment by jhakulin** [comment]
Thanks for feedback,

For the standalone app, there is currently specific step to copy native dll in order to work, did you do that ?

https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp-unity

**Build and run the sample as a stand-alone desktop application**
Navigate to the HelloWorld_Data/Plugins folder in your build output folder. Copy the DLL Microsoft.CognitiveServices.Speech.core.dll into the HelloWorld_Data/Managed folder.

We will improve this in the later releases.

Regards,
Jarno

**Comment by Brandon-Franklin** [comment]
@jhakulin Yes, I did do that to get it working, though through trial and error. I didn't realize this was known to be in the release. Thanks for the clarification.

**Comment by Brandon-Franklin** [comment]
In case anyone else finds this after having the issue I made an editor script that will automatically copy the missing dll to the right folder when you make a new build.

Just copy this into a c# script of the same name, and then put it into an "Editor" folder.

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.IO;
using UnityEditor.Callbacks;
using UnityEditor;

public class CallOnBuild
{
    [PostProcessBuild(11)]
    public static void OnPostprocessBuild(BuildTarget target, string pathToBuiltProject)
    {
        string sourceFolderName = "Plugins";
        string targetFolderName = "Managed";

        string targetDll = "Microsoft.CognitiveServices.Speech.core.dll";

        string buildPath = pathToBuiltProject;
        string exeName = string.Empty;

        buildPath = buildPath.Replace(".exe", "");

        for (int i = buildPath.Length - 1; i >= 0; i--)
        {
            if (buildPath[i] == '/')
            {
                buildPath = buildPath.Remove(i);
                break;
            }
            else
            {
                exeName = exeName.Insert(0, buildPath[i].ToString());

                buildPath = buildPath.Remove(i);
            }
        }

        string sourcePath = buildPath + "/" + exeName + "_Data/" + sourceFolderName + "/" + targetDll;
        string targetPath = buildPath + "/" + exeName + "_Data/" + targetFolderName + "/" + targetDll;

        Debug.Log(sourcePath);
        Debug.Log(targetPath);

        if (File.Exists(sourcePath))
        {
            if (!File.Exists(targetPath))
            {
                File.Copy(sourcePath, targetPath);
                Debug.Log("Made a copy to another folder.");
            }
        }
    }
}
```
