### ISSUE TITLE
Crash on on_underlying_io_send_complete (uws_client.c:1944:30)

### ISSUE THREAD

**Issue by toddtian** [Azure-Samples/cognitive-services-speech-sdk#1620]
**Describe the bug**
EXC_BAD_ACCESS: Attempted to dereference garbage pointer

**To Reproduce**
The crash reported from user log, we are unable to reproduce it.

But we know the app crashed after app did enter background 25 minutes.
Before app enter background, we have called stopContinuousRecognition().

**Version of the Cognitive Services Speech SDK**
1.23

**Platform, Operating System, and Programming Language**
 - OS: iOS
 - Hardware - iPhone
 - Programming language: Swift

**Additional context**
EXC_BAD_ACCESS: Attempted to dereference garbage pointer 0x2a078bb21c50.

0  MicrosoftCognitiveServicesSpeech on_underlying_io_send_complete (uws_client.c:1944:30)
1  MicrosoftCognitiveServicesSpeech process_and_destroy_head_message (tlsio_appleios.c:128:9)
2  MicrosoftCognitiveServicesSpeech internal_close (tlsio_appleios.c:171:12)
3  MicrosoftCognitiveServicesSpeech xio_destroy (xio.c:68:9)
4  MicrosoftCognitiveServicesSpeech uws_client_destroy (uws_client.c:573:13)
5  MicrosoftCognitiveServicesSpeech WebSocketAdapter::UwsWebSocket::~UwsWebSocket() (uws_web_socket.cpp:37:5)
6  MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::Impl::CSpxWebSocket::Disconnect() (memory:2506:9)
7  MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::Impl::CSpxWebSocket::~CSpxWebSocket() (web_socket.cpp:280:13)
8  MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::Impl::CSpxWebSocket::~CSpxWebSocket() (web_socket.cpp:271:5)
9  MicrosoftCognitiveServicesSpeech std::__1::__packaged_task_func<Microsoft::CognitiveServices::Speech::Impl::CSpxWebSocket::WorkLoop(std::__1::weak_ptr<Microsoft::CognitiveServices::Speech::Impl::CSpxWebSocket>)::$_8::operator()() const::{lambda()#1}, std::__1::allocator<{lambda()#1}>, void ()>::destroy() (memory:2506:9)
10 MicrosoftCognitiveServicesSpeech std::__1::__packaged_task_function<void ()>::~__packaged_task_function() (future:1818:15)
11 MicrosoftCognitiveServicesSpeech std::__1::__deque_base<std::__1::pair<std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::Impl::CSpxThreadService::DelayTask>, std::__1::promise<bool> >, std::__1::allocator<std::__1::pair<std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::Impl::CSpxThreadService::DelayTask>, std::__1::promise<bool> > > >::clear() (memory:2506:9)
12 MicrosoftCognitiveServicesSpeech Microsoft::CognitiveServices::Speech::Impl::CSpxThreadService::Thread::WorkerLoop(std::__1::shared_ptr<Microsoft::CognitiveServices::Speech::Impl::CSpxThreadService::Thread>) (deque:2963:13)
13 MicrosoftCognitiveServicesSpeech _ZNSt3__1L8__invokeIPFvNS_10shared_ptrIN9Microsoft17CognitiveServices6Speech4Impl17CSpxThreadService6ThreadEEEEJS8_EEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOSB_DpOSC_ (type_traits:3694:1)
14 libsystem_pthread.dylib          __pthread_start

**Comment by glecaros** [comment]
Hi @toddtian, thank you for creating this issue. This seems to be a rare race condition in our underlying network stack. As a workaround you can try disposing of the recognizer when going to the background.

**Comment by pankopon** [comment]
Internal work item ref. 4471701.
