### ISSUE TITLE
Voice to text joins up independently spoken numbers.

### ISSUE THREAD

**Issue by OGHinde** [Azure-Samples/cognitive-services-speech-sdk#1621]
Hello. 
We're having an issue where the speech to text service returns a single joined number when numbers are spoken individually. For example saying "fourteen, seven, thirty eight" will result in the speech to text returning "14738" instead of "14 7 38". 

However, if I check the lexical result after setting the detailed output format, it shows the correct final transcription (albeit obviously in lexical instead of numerical form), "fourteen, seven, thirty eight". 

Is there any way of changing this behavior?

Thanks.

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
