### ISSUE TITLE
Javascript function sdk.AudioConfig.fromDefaultSpeakerOutput() not working in text-to-speech

### ISSUE THREAD

**Issue by sudhra** [Azure-Samples/cognitive-services-speech-sdk#1625]
**Describe the bug**

I am using steps in https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-text-to-speech?tabs=terminal&pivots=programming-language-javascript 

When I use sdk.AudioConfig.fromAudioFileOutput(audioFile); to output audio to a file it works. But when I use the sdk.AudioConfig.fromDefaultSpeakerOutput() instead, it does not play on my speaker. It does not give any error either. 

**Version of the Cognitive Services Speech SDK**
I am using the latest version of the SDK

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - x64
 - Programming language: Javascript (node JS)

Below is the full script that I am running. 

(function() {

    "use strict";

    var sdk = require("microsoft-cognitiveservices-speech-sdk");
    var readline = require("readline");

    var key = "";
    var region = "";
    // var audioFile = "YourAudioFile.wav";

    const speechConfig = sdk.SpeechConfig.fromSubscription(key, region);
    // const audioConfig = sdk.AudioConfig.fromAudioFileOutput(audioFile);
    const audioConfig = sdk.AudioConfig.fromDefaultSpeakerOutput();

    // The language of the voice that speaks.
    speechConfig.speechSynthesisVoiceName = "en-US-JennyNeural"; 

    // Create the speech synthesizer.
    var synthesizer = new sdk.SpeechSynthesizer(speechConfig, audioConfig);

    // Start the synthesizer and wait for a result.
    synthesizer.speakTextAsync("hello",
        function (result) {
      if (result.reason === sdk.ResultReason.SynthesizingAudioCompleted) {
        console.log("synthesis finished.");
      } else {
        console.error("Speech synthesis canceled, " + result.errorDetails +
            "\nDid you set the speech resource key and region values?");
      }
      synthesizer.close();
      synthesizer = null;
    },
        function (err) {
      console.trace("err - " + err);
      synthesizer.close();
      synthesizer = null;
    });
}());

Below is the output:

>node SpeechSynthesis.js
synthesis finished.

It does not give any error. But no audio gets played either. 

**Additional note**
The python implementation of the same function (i.e. https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-text-to-speech?tabs=terminal&pivots=programming-language-python) does work for me. Both outputting the audio to a file and playing on default speaker works.

**Comment by yulin-li** [comment]
Hi, you can save the audio to file and use e.g. [play-sound](https://www.npmjs.com/package/play-sound) for playback. This will introduce some latency as streaming is disabled.
