### ISSUE TITLE
Got (SPXERR_RUNTIME_ERROR) error while tried .JoinConversationAsync(conversation);

### ISSUE THREAD

**Issue by dmytrohladyshev** [Azure-Samples/cognitive-services-speech-sdk#1628]
tried to implement a Real-time transcribing but was faced with the 
`ApplicationException: Exception with an error code: 0x1b (SPXERR_RUNTIME_ERROR)
Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail (System.IntPtr hr) (at <17b0ebfb9fc84f04bceeee18201e9628>:0)
Microsoft.CognitiveServices.Speech.Transcription.ConversationTranscriber+<>c__DisplayClass23_0.<JoinConversationAsync>b__1 () (at <17b0ebfb9fc84f04bceeee18201e9628>:0)
Microsoft.CognitiveServices.Speech.Recognizer.DoAsyncRecognitionAction (System.Action recoImplAction) (at <17b0ebfb9fc84f04bceeee18201e9628>:0)`

have no idea what's going wrong :( can anyone help? 
```
private async void StartContinuousTranscribing()
        {
            SpeechConfig config = SpeechConfig.FromSubscription(_speechServiceAPIKey, _speechServiceRegion);
            config.SpeechRecognitionLanguage = _language;
            config.SetProperty("ConversationTranscriptionInRoomAndOnline", "true");
            config.SetProperty("DifferentiateGuestSpeakers", "true");
            config.SetServiceProperty("transcriptionMode", "RealTimeAndAsync", ServicePropertyChannel.UriQueryParameter);
            
            AudioConfig audioConfig = AudioConfig.FromDefaultMicrophoneInput();
            string meetingID = Guid.NewGuid().ToString();
            Conversation conversation = await Conversation.CreateConversationAsync(config, meetingID);
            _transcriber = new ConversationTranscriber(audioConfig);
            if (_transcriber != null)
            {
                _transcriber.SpeechStartDetected += OnSpeechStartedCallback;
                _transcriber.SpeechEndDetected += OnSpeechEndedCallback;
                _transcriber.Transcribing += OnSpeechTranscribingCallback;
                _transcriber.Transcribed += OnSpeechTranscribedCallback;
                _transcriber.Canceled += OnTranscribingCanceledCallback;
                _transcriber.SessionStarted += OnSessionStartedCallback;
                _transcriber.SessionStopped += OnSessionStoppedCallback;
                
                await _transcriber.JoinConversationAsync(conversation);
                await _transcriber.StartTranscribingAsync().ConfigureAwait(false);
            }
        }
```

**Comment by glecaros** [comment]
Hi @dmytrohladyshev, can you please share more details on the setup you are running (i.e OS & SDK version)? Also, if possible could you capture some logs ([instructions](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging))
As an extra point, one of the current limitations of the conversation transcriber ([as stated here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-conversation-transcription?pivots=programming-language-csharp)) is that it requires a 7-channel mic array

**Comment by dmytrohladyshev** [comment]
[logFile.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/9400178/logFile.txt)

**Comment by glecaros** [comment]
From the log it looks like you are missing the `Microsoft.CognitiveServices.Speech.extension.mas` library.

**Comment by dmytrohladyshev** [comment]
I'm using Unity with Microsoft.CognitiveServices.Speech.1.23.0 SDK. So I don't know how to add it another way instead of unity package import. Is there any way to do it? 
the same behavior is observed on iPhone, Android devices, win, and mac PC...

**Comment by jhakulin** [comment]
@dmytrohladyshev We will have a fix for the `Microsoft.CognitiveServices.Speech.extension.mas` dependency problem related to ConversationTranscriber object in the next 1.24.0 version of Speech SDK release, which is currently targeted to be released by the end of September.

Could you please clarify why you are setting this property `config.SetServiceProperty("transcriptionMode", "RealTimeAndAsync", ServicePropertyChannel.UriQueryParameter);`  in your sample ?

**Comment by pankopon** [comment]
Internal work item ref. 3086009.

**Comment by dmytrohladyshev** [comment]
any updates? )

**Comment by jhakulin** [comment]
@dmytrohladyshev Related to your issue, default microphone configuration for ConversationTranscriber is currently under private preview in Speech SDK 1.24.0 release, please contact diarizationrequest@microsoft.com in case you are interested in more details.

**Comment by dmytrohladyshev** [comment]
sounds great ) going to contact
thanks
