### ISSUE TITLE
python/ speech_sample.py  speech_recognize_continuous_from_file()   I  can't get the recognitionResult , It seems not to be an interface

### ISSUE THREAD

**Issue by pieere** [Azure-Samples/cognitive-services-speech-sdk#163]
**Describe the bug**

**To Reproduce**
1. ...
2. ...

**Expected behavior**

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - please be specific
 - Hardware - x64, x86, ARM, ...
 - Programming language: C#, C++, Java, JavaScript, Objective-C, Python
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific

**Additional context**
 - Error messages, log information, stack trace, ...
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by chlandsi** [comment]
For continuous recognition, the recognition result is not delivered as the result of a function call (to start_continuous_recognition, or any other function), but as an event in the callback functions for the `recognizing` and `recognized` function, as demonstrated in the example you mention ([this line](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/258949599ec32c8a7b03fb38a53f2033010b6b26/samples/python/console/speech_sample.py#L203)). Does this solve the issue?

**Comment by pieere** [comment]
I saw you  have mentioned `recognizing` and `recognized` function,and i can also see the recognized result, but i need to get the result and save it to the database, can this happen? I cant save it

**Comment by pieere** [comment]
@chlandsi

**Comment by chlandsi** [comment]
Try replacing the current callback `lambda evt: print('RECOGNIZING: {}'.format(evt))`, which just prints the result, with a function that handles the result (available as `result` property on the event, like `evt.result`) in the way you intend to use it. You can also register multiple callbacks for a signal by calling `connect` multiple times, once for each callback registration.

**Comment by pieere** [comment]
thanks a  lot @chlandsi

**Comment by pieere** [comment]
thanks
