### ISSUE TITLE
azure.cognitiveservices.speech SpeechRecognizer canceled automatically

### ISSUE THREAD

**Issue by MiaZhang17** [Azure-Samples/cognitive-services-speech-sdk#1632]
**Describe the bug**
I am using azure.cognitiveservices.speech Service to convert an wav content into text
It seems to be canceled by some reason and didn't generate any sentences.

I tried 4 different wav files with the same code, but only 1 file worked
I also tried azure sample wav file, and it worked ([whatstheweatherlike.wav](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/whatstheweatherlike.wav))
Each wav file looks fine when I played them

The worked wav file is bigger and longer than the failed wav , so I think it's not the size issue
The successed wav file：125MB、duration 1:08:31
Thi failed wav file：105MB、duration 57:19

Here's the question I asked on MSFT forum, please check the log file from the forum link
 - [MSFT forum](https://docs.microsoft.com/en-us/answers/questions/981171/azurecognitiveservicesspeech-speechrecognizer-canc.html)
1.The sample file wav log (success)
2.The successed wav log (remove confidential log)
3.The failed wav log

- Below are some log content
     [133546]: 47693ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1186 [0x5600551cc730]CSpxAudioStreamSession::StopRecognizing: We've been asked to stop whatever it is we're doing, while we're actively processing audio ...
     [78809]: 47693ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:104 CSpxHandleTable::TrackHandle t=N9Microsoft17CognitiveServices6Speech4Impl21ISpxRecognitionResultE h=0x0x7ff7c006bd70, p=0x0x7ff7c006bd70, tot=1
     [133546]: 47693ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1189 
 [name='RESULT-ErrorDetails'; value='Due to service inactivity, the client buffer exceeded maximum size. Resetting the buffer. SessionId: f63594b7822b42f282574faf38b0eee4'
     [133546]: 47693ms SPX_DBG_TRACE_VERBOSE:  audio_pump.cpp:107 [0x5600551c8820]CSpxAudioPump::StopPump() ... mutex LOCKED

**Version of the Cognitive Services Speech SDK**
azure-cognitiveservices-speech~=1.17.0

**Platform, Operating System, and Programming Language**
Azure Machine Learning pipeline
- OS : ubuntu18
- Programming language : python 3.7
- Hardware : Standard_DS3_v2 (4 cores, 14 GB RAM, 28 GB disk)

 **Any other additional information**
 - Here's my code
```
import azure.cognitiveservices.speech as speechsdk
results = []
def speech_recognize_continuous_from_file():
    speech_config = speechsdk.SpeechConfig(subscription=speech_key, endpoint=url)
    speech_config.request_word_level_timestamps()
    speech_config.set_property(speechsdk.PropertyId.Speech_LogFilename, log_filename)
    audio_config = speechsdk.audio.AudioConfig(filename=audio_path)

    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, language="zh-TW", audio_config=audio_config)

    # Connect callbacks to the events fired by the speech recognizer
    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: results.append(evt))
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
    speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))
    
    # stop continuous recognition on either session stopped or canceled events
    done = False

    def stop_cb(evt):
        """callback that signals to stop continuous recognition upon receiving an event `evt`"""
        print('CLOSING on {}'.format(evt))
        nonlocal done
        done = True
    speech_recognizer.session_stopped.connect(stop_cb)
    speech_recognizer.canceled.connect(stop_cb)

    # Start continuous speech recognition
    speech_recognizer.start_continuous_recognition()
    while not done:
     time.sleep(.5)

    speech_recognizer.stop_continuous_recognition()
```

**Comment by pankopon** [comment]
@MiaZhang17 Speech SDK version 1.17.0 is very old by now, please install the current latest version (1.23.0 as of this writing) and update it regularly. Release notes are published in https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/releasenotes?tabs=speech-sdk.

Also, based on the log
```
[97991]: 694ms SPX_TRACE_INFO:  uspimpl.cpp:664 connectionUrl=wss://centralus.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?endSilenceTimeoutMs=0&format=detailed&initialSilenceTimeoutMs=0&language=zh-TW&wordLevelTimestamps=true
```
and your code, the value of `endpoint` seems to be
```
wss://centralus.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?endSilenceTimeoutMs=0&format=detailed&initialSilenceTimeoutMs=0
```
which means both initial and end silence timeouts are set zero, which is not the default. If this was intentional, you should try recognition with default settings in case issues persist.

Using your code and the latest Speech SDK with Python 3.8, I ran recognition for a wav file of 124 MB and duration 1:08:12 without errors. If there are still problems after the SDK update, please attach a log file and possibly one of your failed wav files.

**Comment by MiaZhang17** [comment]
Thanks for the reply

Like you say, I did set the endpoint parameters
```
url="wss://centralus.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?initialSilenceTimeoutMs=0&endSilenceTimeoutMs=0"
```
After removing the parameters, the failed wav worked !!!
`url="wss://centralus.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1`

Then I checked the wav files, there are 8s initial silence in the successed wav and there are 6 min initial silence in the failed wav
That's why the 6 min wav failed

But I still feel curious that I set the parameter `initialSilenceTimeoutMs=0` & `endSilenceTimeoutMs=0`, why does the wav which has 8s initial silence still work?

I also updated the speech SDK version
Thank you for the help!!

**Comment by pankopon** [comment]
Closed as resolved, please open a new issue if more support is needed.
