### ISSUE TITLE
wrong WordLevelTimestamps with streaming (startContinuousRecognitionAsync)

### ISSUE THREAD

**Issue by vcombey** [Azure-Samples/cognitive-services-speech-sdk#1633]
I am using the timstamp to display the transcription synced with the audio I record. You can see an exemple of the final object here https://spoke.app/share/4n5kfvpyu1db7x9czm6rj083wasge2hq?all.

When you start playing the audio you will see the current word in blue.
they ared synced with the audio.
But if you go to the middle of the video you will see an offset of ~ 3 words.

I am using the code copy pasted from: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js where i request wordLevelTimestamp

    the basic MediaRecorder. : https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API

The bug appear on last version of chrome and firefox on MacOs and android. ( the platform I tested )

This is a hard blocker for us to use the api.
I am suprised to not find any reference of this issue as this is very basic use of the sdk.

Many thanks

**Comment by pankopon** [comment]
@glharper @rhurey Please check when you have time.

**Comment by vcombey** [comment]
Hi,
any updates or indication of time it would take ?
I can provide a minimal example that reproduce the issue, or tell me if I can do anything to help debug that.
We really need this,

thanks

**Comment by glharper** [comment]
@vcombey I believe you've opened the same issue in the JS repo, let's continue the conversation there.
