### ISSUE TITLE
The problem about phoneme （SSML）don't work in zh_TW

### ISSUE THREAD

**Issue by Lucien20000118** [Azure-Samples/cognitive-services-speech-sdk#1638]
In my case, I want to produce audio but there are too much same word  have different pronounce.  I'm trying to use phoneme to specify the pronunciation in zh-TW. 
But use `<phoneme alphabet="sapi" ph="he 1"> 喝 </phoneme>`, it will print out error.
Does it support Mandarin?

**Comment by jhakulin** [comment]
@yulin-li could you please comment on this issue?

**Comment by yulin-li** [comment]
@iajzhan could you help on this?

**Comment by jiajzhan** [comment]
@Lucien20000118 Zh-TW does not support pinyin, should use 'Bopomofo' phones, pls refer to this page: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-ssml-phonetic-sets#zh-tw
