### ISSUE TITLE
Is there any way to use Speech Recognition under android api 19 or on armeabi devices?

### ISSUE THREAD

**Issue by CoderBeanLiang** [Azure-Samples/cognitive-services-speech-sdk#164]
**Is your feature request related to a problem? Please describe.**
I have an android application that supporting minSdk to API17 and armeabi. But I noticed that now the library is not supported.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Thansk! I have tested the speech recognition service and feels great.
But my app is support at least API 17.
I can overrideLibrary of speech, but I want to know that have you planned to expand the API Level in the next few months?

**Comment by fmegen** [comment]
currently, there is a limitation to api levels 21 and above,
there is a plan to support api level 19 for 32bit devices (64bit will require api level 21).
we are testing the changes, stay tuned.

**Comment by CoderBeanLiang** [comment]
Thanks for your reply : )

**Comment by wolfma61** [comment]
closing .... 
in case we can add this in a feature release, it will probably be announced in the release notes ;)
