### ISSUE TITLE
JS:recognized in IntentRecognizer not working

### ISSUE THREAD

**Issue by Aethey** [Azure-Samples/cognitive-services-speech-sdk#1644]
**Describe the bug**
in the JavaScript SDK,when using the `startContinuousRecognitionAsync` method with a `IntentRecognizer`,
the `recognized` is never be called, just `recognizing` can get the callback

**Version of the Cognitive Services Speech SDK**
` "microsoft-cognitiveservices-speech-sdk": "^1.23.0"`

**Comment by glharper** [comment]
@Aethey Thank you for using Speech SDK, and writing this issue up. Would you mind sharing the exact code you're reproducing this with (minus any subscription keys)?

**Comment by Aethey** [comment]
> @Aethey Thank you for using Speech SDK, and writing this issue up. Would you mind sharing the exact code you're reproducing this with (minus any subscription keys)?

sure,the funcation code like this
```
async sttFromMicContinuous() {

    // init recognizer
    const audioConfig = speechsdk.AudioConfig.fromDefaultMicrophoneInput();
    // if change the IntentRecognizer to SpeakerRecognizer, the callback has no problem
    const recognizer = new speechsdk.IntentRecognizer(
      speechConfig,
      audioConfig
    );

    // init intentModel
    var intentModel = speechsdk.LanguageUnderstandingModel.fromAppId(APPID);
    recognizer.addAllIntents(intentModel);

    // no problem
    recognizer.recognizing = (s, e) => {
        // can get log
        console.log(`recognizing: ${e.result.text}`);
        console.log(e.result.reason);
      };

      // never be called
      recognizer.recognized = (s, e) => {
        // nothing, never be called,
        console.log(`recognized: ${e.result.text}`);
        console.log(`recognized: ${e.result.json}`);
      };

    // start
    recognizer.startContinuousRecognitionAsync(
        () => {
          console.log("Recognition started");
        },
        (err) => {
          console.trace("err - " + err);
          recognizer.close();
          // recognizer = undefined;
        }
    );
```

**Comment by glharper** [comment]
@Aethey Is this code being run in a browser environment? (Node does not have support for direct microphone input).

**Comment by Aethey** [comment]
> @Aethey Is this code being run in a browser environment? (Node does not have support for direct microphone input).

run in a browser environment,and the SpeakerRecognizer is work well

**Comment by glharper** [comment]
@Aethey I've tested the sample [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/index.html) and gotten recognized callbacks using Intent Recognition. Would you mind downloading that sample, running it locally, and seeing if you see (recognized) lines in the bottom text area when you perform intent recognition?

**Comment by Aethey** [comment]
> @Aethey I've tested the sample [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/index.html) and gotten recognized callbacks using Intent Recognition. Would you mind downloading that sample, running it locally, and seeing if you see (recognized) lines in the bottom text area when you perform intent recognition?

thanks for your demo,and i have running it locally,but the result like this :
<img width="691" alt="reco_err02" src="https://user-images.githubusercontent.com/17793203/189796194-8f3dd783-d237-43f9-afb8-fbdff4dd99c4.png">

no callback in recognized

about the LUIS part:
`    var intentModel = speechsdk.LanguageUnderstandingModel.fromSubscription(
      APPKEY,
      APPID,
      "westus"
    );
    recognizer.addAllIntents(intentModel);`

i can get result in python with the same APPKEY and the same APPID

**Comment by glharper** [comment]
@Aethey Is the region for your app westus or East Asia? Are you seeing any errors in the JS console?

**Comment by Aethey** [comment]
> @Aethey Is the region for your app westus or East Asia? Are you seeing any errors in the JS console?

the speech sdk region is "japaneast". its not in  select bar and i edit it in code.
the LUIS region is "westus", 

all the log like this:
<img width="1280" alt="new" src="https://user-images.githubusercontent.com/17793203/190041261-43c2ac04-cff0-4db8-9a00-5c9d78809da7.png">

there is no response  and no error and no message about LUIS, i have no way to find the reason

**Comment by glharper** [comment]
@Aethey I've reproduced this, and have an understanding of the root cause. There should be a PR for this within the next few days. Thanks again for letting us know!

**Comment by Aethey** [comment]
> @Aethey I've reproduced this, and have an understanding of the root cause. There should be a PR for this within the next few days. Thanks again for letting us know!

thanks for your reply.

**Comment by glharper** [comment]
@Aethey [JS Speech SDK v1.24](https://github.com/microsoft/cognitive-services-speech-sdk-js/releases/tag/v1.24.0) has been released, with this fix included. Thanks again for submitting this issue!
