### ISSUE TITLE
EmbeddedSpeechConfig 

### ISSUE THREAD

**Issue by adambezecny** [Azure-Samples/cognitive-services-speech-sdk#1647]
hi,

I am the maintainer of rust library wrapping the cognitive speech sdk APIs, see here: https://crates.io/crates/cognitive-services-speech-sdk-rs

Recently we are trying to add support for EmbeddedSpeechConfig class (https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.embeddedspeechconfig?view=azure-dotnet).

Unfortunately I was not able to find any example demonstrating its usage. I mainly miss information how to create the speech model  that could be used with EmbeddedSpeechConfig. Any advice/hint will be greatly appreciated. Also When is class will be available in public release?

regards,

Adam

**Comment by pankopon** [comment]
Hi, as noted in the API description, "This is currently a preview of the API. The functionality is not available in public releases." So it cannot be used with current Speech SDK releases as of now.

We are going to publish documentation and samples in the near future (no exact date yet), but initially the functionality will be only available for selected customers who meet requirements. There will be more information in Speech SDK release notes and documentation pages.

**Comment by pankopon** [comment]
To update, public documentation and samples are now available for embedded speech, see https://aka.ms/embedded-speech. Access to the feature remains limited, however.
