### ISSUE TITLE
Are there plans to support maui?

### ISSUE THREAD

**Issue by singhwong** [Azure-Samples/cognitive-services-speech-sdk#1649]
The sdk doesn't work properly in maui anymore, it fails when instantiating ‘SpeechConfig’ (I remember it was working fine in maui at the beginning of this year.)
`var config = SpeechConfig.FromSubscription(YourSubscriptionKey, YourServiceRegion);`
Tested Platforms: ios, android, maccatalyst

**Comment by dargilco** [comment]
Thank you @singhwong for opening this issue. I'm Darren from the Speech SDK team. By "maui" I'm assuming you are referring to the [.NET MAUI framework](https://docs.microsoft.com/en-us/dotnet/maui/what-is-maui). Which SDK version are you using now (which does not work) and which older SDK version worked? When you say "failed when instantiating" what exception is thrown and what is the exception message? Please use latest version, [turn on SDK logs](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging), run your scenario and share the log file with me here.
Thanks,
Darren

**Comment by singhwong** [comment]
Hello,
I caught the exception, the exception is as follows:
`System.DllNotFoundException: libMicrosoft.CognitiveServices.Speech.core.so
   at Microsoft.CognitiveServices.Speech.SpeechConfig.FromSubscription(String subscriptionKey, String region)
   at MauiSpeechServiceTest.MainPage.OnCounterClicked(Object sender, EventArgs e) in /Volumes/Documents/MauiSpeechServiceTest/MainPage.xaml.cs:line 29`
The speech sdk version I am using is 1.23.0, I can't remember the sdk version number that works fine in maui. The local device I use is macbook, and I use the last released version of maui. Hope this information is helpful to you.

**Comment by dargilco** [comment]
Hi @singhwong I verified .NET MAUI applications work with Speech SDK on Windows. I'm using Visual Studio's .NET MAUI application template app, with a few lines of code to call Speech SDK APIs. I'm having trouble running Android emulator using Visual Studio, as I wanted to see if the same MAUI app works there. 
Meanwhile, in your development environment, can you recursively list all the files named *Microsoft.CognitiveServices.Speech* and share the result? It may be that the native .so files (like libMicrosoft.CognitiveServices.Speech.core.so) are not being copied correctly by the NuGet package manager when you compile the application.
To work around this, please download the Speech SDK NuGet file from https://www.nuget.org/packages/Microsoft.CognitiveServices.Speech (clock on "download package" on the right-side menu). Unzip it. Locate the native binaries corresponding to your target architecture (e.g. \runtimes\linux-x64\native). Copy all those binaries to the same folder where Microsoft.CognitiveServices.Speech.csharp.dll is in your development environment. You probably only need these two files: libMicrosoft.CognitiveServices.Speech.core.so and libMicrosoft.CognitiveServices.Speech.extension.audio.sys.so. The 2nd one is only needed if you use Speech SDK to capture audio directly from the microphone.
Let me know if that fixed the exception and unblocked you for the time being, while we investigate the issue.
Thanks,
Darren

**Comment by dargilco** [comment]
@singhwong It does not look like we support C# Speech SDK on iOS & Android. MacBook should work however, after you do the binary placement suggested above (copy native binaries from the NuGet package folder \runtimes\osx-x64 (or \runtimes\osx-arm64). Please let me know if it works for you on MacBook after copying these binaries. I will open work items to investigate why native binaries are not being placed correctly for C# MAUI project targeted for MacBook, and for adding support for mobile devices.

**Comment by dargilco** [comment]
@singhwong Regarding mobile support, please have a look at this issue from April: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1457 . It's about Xamarin but I believe the workaround discussed there is similar for MAUI. For Android, you can grab native SDK binaries for from the AAR package: https://csspeechstorage.blob.core.windows.net/maven/com/microsoft/cognitiveservices/speech/client-sdk/1.23.0/client-sdk-1.23.0.aar . Unzip it and look at the binaries in the jni folder. Copy the relevant ones (based on the target architecture) and place them in the same folder as the file Microsoft.CognitiveServices.Speech.csharp.dll.
I'm not sure about iOS...

**Comment by singhwong** [comment]
Hi@dargilco, when my maui project is compiled or run, my project folder only contains files related to speech sdk as follows:
> bin/Debug/net6.0-ios/iossimulator-x64/Microsoft.CognitiveServices.Speech.csharp.dll
bin/Debug/net6.0-ios/iossimulator-x64/libMicrosoft.CognitiveServices.Speech.core.dylib (Originally this file didn't exist, it was added later based on your suggestion)
bin/Debug/net6.0-ios/iossimulator-x64/Demo.app/Microsoft.CognitiveServices.Speech.csharp.dll

I moved the decompressed related files to the same directory as "Microsoft.CognitiveServices.Speech.csharp.dll" as you said, but it didn't solve the problem, maybe I didn't do exactly what you meant.

I created a new xamarin.forms example and found that the speech sdk works fine on android(x86_64) and iOS(x64).
I also tested maui project on windows, and found that android (x86_64) will throw similar exceptions, and I cannot use android emulators with other processors. Of course, it can be used normally in winui 3 project, as you have tested.

I think it may have nothing to do with the local device used (whether it is windows pc or macbook), this problem only occurs when the project target framework is android or ios.

There are also some differences between exceptions thrown on android and on ios:

> android: System.DllNotFoundException: libMicrosoft.CognitiveServices.Speech.core.so
iOS/maccatalyst: System.DllNotFoundException: Microsoft.CognitiveServices.Speech.core.dll

**Comment by singhwong** [comment]
@dargilco After adding "speech" nuget reference, VS automatically creates a libs directory in the maui project as shown below.
<img width="286" alt="截屏2022-09-21 13 09 49" src="https://user-images.githubusercontent.com/39898152/191419180-5e75fb91-fa03-4e34-b939-8545cd632b2a.png">

But running maui project on an android emulator with x86_64 architecture will throw a "dll not found" exception, as if maui can't load correct files based on the architecture of the running emulator after running.
I don't have a real android device and can't test further.

**Comment by jhakulin** [comment]
@singhwong We are working on adding the support for MAUI in Speech SDK NuGet package, Support for Android is targeted in the next 1.24.0 Speech SDK release

**Comment by pankopon** [comment]
Internal work items ref. 4592236, 4592237, 4592239.

MAUI support for Android was released in 1.24.0, support for iOS and Android will be in 1.25.0.

**Comment by pankopon** [comment]
Closing the issue as we have corresponding feature request work items on our backlog and continue tracking the status there.

**Comment by sakata-3as** [comment]
Hi, DLLNotFoundException still occurring in 1.25.0 on MAUI on iPhone 12 Pro Max running current iOS 16.

**Comment by jhakulin** [comment]
@sakata-3as I just verified the iOS on MAUI with 1.25.0 release with iOS16.2 device and all worked and should be good with 1.25.0 for MAUI support.
Did you follow the prerequisites instructions here: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/csharp/maui/speech-to-text ?

**Comment by sakata-3as** [comment]
Hi @jhakulin , 
Our app is now using .net7 MAUI. It was using .net6 MAUI when I previously commented.
Unfortunately, DLLNotFoundException occurs on iOS 16.3.1 with 1.25.0.
Keyword recognition works well on Android devices.
Could you check if this reproduces?

**Comment by jhakulin** [comment]
@sakata-3as Could you share the logs from Visual Studio which shows DLLNotFoundException error?
Speech SDK Nuget for iOS is using static libraries (.a), the DLLNotFoundException refers to some dynamic libraries it tries to load, which should be other than Speech SDK.

Also, If you have just switched to .Net 7, I would recommend cleaning all build environments and see if that helps.

Also, for Release build, 1.25.0 NuGet may have following issue. https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1835. Please see the workaround information provided there for the symbol not found issue related to Apple's AudioToolbox.

**Comment by sakata-3as** [comment]
Hi @jhakulin ,
I deleted obj folder and bin folder of Visual Studio, but the exception still occurring. 
Could you tell me if there are any cleaning ways for build environments?
Also, I did workaround no. 1 from #1835.
Attached screenshot logs of the exception.
![screenshot](https://user-images.githubusercontent.com/119636603/221449082-cee17630-032a-4e9c-9c25-518e29ef1481.png)

Also, here is the stacktrace.

------------
   at Microsoft.CognitiveServices.Speech.Audio.AudioConfig.FromDefaultMicrophoneInput()
   at <OurAppName>.App.KeywordListen() in <OurDirectoryPath>App.cs:line 134
------------

**Comment by jhakulin** [comment]
@sakata-3as Your issue might be duplicate to https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1865

**Comment by sakata-3as** [comment]
@jhakulin 
Are there any plans to enable deployment onto iOS devices from Windows Visual Studio 2022 as Local device regarding Microsoft.CognitiveServices.Speech ?
(Visual Studio 2022 mac returns Codesign error (code: 1), so we are yet to deploy via mac.)
