### ISSUE TITLE
French speech

### ISSUE THREAD

**Issue by louloubo** [Azure-Samples/cognitive-services-speech-sdk#165]
Using this file for my code in python: cognitive-services-speech-sdk/quickstart/python/quickstart.py , I would like to transcribe french speech. But using the same code, it doesn't work, it recognizes only English but not french. What can I do in order to recognize french well?
I'm using Python 3.7  on Windows 64.
 
Thanks for help

**Comment by chlandsi** [comment]
Please try setting the `speech_recognition_language` property of the [`SpeechConfig`](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.speechconfig?view=azure-python) to `"fr-FR"` before constructing the recognizer.

**Comment by louloubo** [comment]
It works! Thanks soo much!!!
And do you know how could that be that it only works in Python console et not in Jupyter notebook?

**Comment by chlandsi** [comment]
Glad to be able to help! Can you post the error/issue you see in the Jupyter notebook? I have used the package from Jupyter notebooks successfully in the past.

**Comment by louloubo** [comment]
The problem is at the first line: import azure.cognitiveservices.speech as speechsdk.
The issue of Jupyter:
ImportError                               Traceback (most recent call last)
~\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\azure\cognitiveservices\speech\speech_py_impl.py in swig_import_helper()
     26 
---> 27             return importlib.import_module(mname)
     28 

~\AppData\Local\Continuum\anaconda3\lib\importlib\__init__.py in import_module(name, package)
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _load_unlocked(spec)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in module_from_spec(spec)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap_external.py in create_module(self, spec)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

ImportError: DLL load failed: %1 n’est pas une application Win32 valide.

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-ceac8af4667b> in <module>
----> 1 import azure.cognitiveservices.speech as speechsdk

~\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\azure\cognitiveservices\speech\__init__.py in <module>
      6 """
      7 
----> 8 from .speech import *
      9 from . import audio
     10 from . import intent

~\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\azure\cognitiveservices\speech\speech.py in <module>
      6 
      7 
----> 8 from . import speech_py_impl as impl
      9 from .audio import AudioConfig
     10 

~\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\azure\cognitiveservices\speech\speech_py_impl.py in <module>
     31             return importlib.import_module('_speech_py_impl')
     32 
---> 33     _speech_py_impl = swig_import_helper()
     34 
     35     del swig_import_helper

~\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\azure\cognitiveservices\speech\speech_py_impl.py in swig_import_helper()
     29         except ImportError:
     30 
---> 31             return importlib.import_module('_speech_py_impl')
     32 
     33     _speech_py_impl = swig_import_helper()

~\AppData\Local\Continuum\anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

ModuleNotFoundError: No module named '_speech_py_impl'

**Comment by chlandsi** [comment]
It could be that somehow the environments of two Python installations (one Anaconda, one in ~\AppData\Local\Programs\Python\Python37-32\) got mixed up. Try setting up a [virtualenv](https://virtualenv.pypa.io/en/latest/) or the conda equivalent in one of them, install azure-cognitiveservices-speech in it and then set up a [ipython/jupyter kernel](https://ipython.readthedocs.io/en/stable/install/kernel_install.html) for that environment to make sure that the paths are correct.

**Comment by louloubo** [comment]
ok thanks i'll try
