### ISSUE TITLE
ApiException: (404) Reason: Resource Not Found

### ISSUE THREAD

**Issue by JayR7** [Azure-Samples/cognitive-services-speech-sdk#1651]
Greetings,

I'm trying to run a batch transcription for the first time, i have all the required parameters for transcription class except one is still missing, i can't find it and i don't know to what it refers, which is the ID of the transcription, could someone please tell me what exactly is it? how can i get it?

'def transcribe_from_container(uri, properties):
 """
    Transcribe all files in the container located at `uri` using the settings specified in `properties`
    using the base model for the specified locale.
    """
    transcription_definition = cris_client.Transcription(
        name=NAME,
        description=DESCRIPTION,
        locale=LOCALE,
        recordings_url=uri,
        properties=properties,
        id=  )

    return transcription_definition'

i tried the key of my speech service resource and it showing the same error.
![image](https://user-images.githubusercontent.com/52196205/189736652-3fc7afde-8b78-44f7-b718-defadaec7cff.png)

Your support is highly appreciated,
Jay

**Comment by chlandsi** [comment]
Hi @JayR7 , you don't need to pass an id when creating a transcription; the id is generated by the service. Please have a look at the [sample code](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/python/python-client/main.py#L34) for Python. Thanks!

**Comment by JayR7** [comment]
Hi @chlandsi,
Thanks for your prompt response!
Actually, i tried at the beginning not passing an id, but it was showing me the error below:
![image](https://user-images.githubusercontent.com/52196205/189738465-555afd09-5c30-4e90-b998-f168dfcaf699.png)

so that's why i thought i have to pass an id.

**Comment by chlandsi** [comment]
Hi @JayR7 , it looks like you are using the sample against an outdated version of the swagger client (for the version 2.0 of the API, the sample is for the v3.0 version). Please remove the client package (something like `pip uninstall swagger_client`) and then follow the full [installation instructions](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python) from the sample again.

**Comment by JayR7** [comment]
Oh yeah, you're right!
Thanks a lot, truly appreciate the support!
