### ISSUE TITLE
TTS generating garbled result when requesting Opus encoding

### ISSUE THREAD

**Issue by itaych** [Azure-Samples/cognitive-services-speech-sdk#1653]
Hi, when performing TTS with `SpeechSynthesisOutputFormat::Audio24Khz16Bit48KbpsMonoOpus` I'm having difficulty converting the received data to PCM using the functions provided in `<opus.h>` such as opus_decode, opus_packet_get_nb_frames etc. I've posted more details along with a full example program at the MS Q&A forum [here](https://docs.microsoft.com/en-us/answers/questions/1005079/azure-tts-generating-garbled-result-when-requestin.html). Any help would be appreciated.

**Comment by yulin-li** [comment]
I am looking this and will check your codes later. As a quick response, I want to say that the opus format is a raw opus stream without any header. Maybe you can try the webm format we provide?

**Comment by itaych** [comment]
I'm not familiar with the webm format and wanted to keep both my learning curve and the audio decoding pipeline as simple as possible. Webm and ogg containers seem like a bit of an overkill since I'm already receiving the audio as packets. I will switch to one of them if you tell me that decoding a raw opus stream is not possible, but if that's the case, why do you offer it as an option? Thanks.

**Comment by itaych** [comment]
Hi @yulin-li, did you have a chance to take a look? Really it shouldn't take more than 5 minutes of your time to reproduce the issue.

**Comment by pankopon** [comment]
@yulin-li Is this still valid? Please update with the latest status.

**Comment by itaych** [comment]
Personally I've switched from `Audio24Khz16Bit48KbpsMonoOpus` to `Ogg48Khz16BitMonoOpus` which means the Opus encoding is wrapped in an Ogg container, it's a bit ugly but it works. This is after even the paid support channels failed to come up with an answer.

**Comment by pankopon** [comment]
Closed since a workable alternative was found and no better solution available. @yulin-li Please check whether `Audio24Khz16Bit48KbpsMonoOpus` should be usable as is or if documentation update is needed.
