### ISSUE TITLE
Speaker Diarization without including Words Level in transcription file

### ISSUE THREAD

**Issue by JayR7** [Azure-Samples/cognitive-services-speech-sdk#1654]
Hi,

Since enabling Speaker Diarization requires enabling wordLevelTimestampsEnabled as showing below
![image](https://user-images.githubusercontent.com/52196205/189985052-501746bc-0af6-44dc-ac27-6868f050659c.png)

I was wondering if there's a way to enable wordLevelTimestampsEnabled without including the words in the transcription result file?
![image](https://user-images.githubusercontent.com/52196205/189985509-c587995f-5896-4599-b913-a7481124786f.png)

Thanks!

**Comment by chlandsi** [comment]
Hi @JayR7 , the information that `wordLevelTimestampsEnabled` is required to enable diarization is outdated, diarization can be enabled on its own. We'll remove statements to that effect from the docs.
