### ISSUE TITLE
Can SpeechRecognizer output viseme info?

### ISSUE THREAD

**Issue by andy380743909** [Azure-Samples/cognitive-services-speech-sdk#1656]
Most SpeechToText services only output the final text as result, Azure's speech synthesizer can output viseme info, whether the speech recognizer can also output the viseme info?

**Comment by dargilco** [comment]
Hello and thank you for posting this question. I'm from the Speech SDK team. The speech recognizer cannot output Viseme info. You will need to send the text from the speech recognizer to the text-to-speech service to get Viseme info.

@yulin-li  as FYI

**Comment by andy380743909** [comment]
thanks for your reply.
But I am still wondering why all of the speech recognizer system do not output the phoneme script but only the final words？
