### ISSUE TITLE
TTS JavaScript - play the same text will count the characters repeatedly

### ISSUE THREAD

**Issue by muyu0526** [Azure-Samples/cognitive-services-speech-sdk#1657]
I have tried JavaScript sample for Speech Synthesis and it seems to work as expected.But when I play the same text,it will count the characters repeatedly.I found the characters not counted repeated when I use Speech Studio.How can I solve this problem?

**Comment by dargilco** [comment]
Hello and thank you for posting this question. I'm from the Speech SDK team. I don't understand what you mean by "it will count the characters repeatedly". Please give more details. What is the text you are trying to synthesize? Please point to SDK samples in this repo that worked for you for this text and did not work for you for this text. Or provide example code of your own.
Thanks,
Darren

@yulin-li as FYI.

**Comment by muyu0526** [comment]
Hi,dargilco,
Thank you for your reply.Following the code in the example,https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/synthesis.html
I was able to use Text-to-Speech successfully, but when I clicked the start synthesis button in succession, the number of characters was consumed several times, and the contents of the text box did not change at all. Is there any way to set it to the number of characters that will be consumed only once when the user auditions the same content?

**Comment by dargilco** [comment]
@muyu0526 thank you for the details. @glharper @yulin-li can either one of you take a look at this? Thanks!

**Comment by yulin-li** [comment]
@muyu0526 I didn't quite get your point? Could you share a screen video of this issue?

**Comment by muyu0526** [comment]
when I click the start synthesis button twice,the number of characters was consumed twice,Is there any way to set it to the number of characters that will be consumed only once when the user auditions the same content?

**Comment by muyu0526** [comment]
Sorry,My English is a little rusty.I will repeat the question in Chinese.

我已经成功做出文字转语音的功能，按照这个示例，https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/synthesis.html

当我连续点击两次试听按钮时，会出现重复计算字符数的情况。如图1所示，文本框中原本有28个字符数，在未修改内容的情况下，连续两次点击试听按钮，最终的计费字符数是56个。请问有什么办法可以让用户在未修改文本的情况下，只消耗一次字符数，也就是28个字符数？

**Comment by yulin-li** [comment]
Chinese characters are counted as two characters for billing, including Kanji used in Japanese, Hanja used in Korean, or Hanzi used in other languages. For more information, see [Pricing](https://azure.microsoft.com/pricing/details/cognitive-services/speech-services/).

**Comment by yulin-li** [comment]
See also in this [price note](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/text-to-speech#pricing-note)

**Comment by muyu0526** [comment]
Please see this English example
![11](https://user-images.githubusercontent.com/95582075/190635098-d36e3d63-02a4-4a0e-9f4b-4176e7f90c93.jpg)
![22](https://user-images.githubusercontent.com/95582075/190635163-6b475f25-9d40-46e8-97ee-75edd20e23ab.jpg)

**Comment by muyu0526** [comment]
Is there any way to set it to the number of characters that will be consumed only once when the user auditions the same content?
