### ISSUE TITLE
Continuous Speech Not Working with Unity Integration

### ISSUE THREAD

**Issue by Brandon-Franklin** [Azure-Samples/cognitive-services-speech-sdk#166]
**Describe the bug**
Switching out "var result = await recognizer.RecognizeOnceAsync().ConfigureAwait(false);" with "var result = await recognizer.StartContinuousRecognitionAsync().ConfigureAwait(false);" Does not allow for continuous speech as the documentation states.

**To Reproduce**

1. Start a new project using 2018.3
2. Import the Unity package for Azure Speech Services SDK
3. Follow the set up steps on https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-csharp-unity into a new document
4. Copy the text from Quick Start Guide to a new C# Script in Unity
5. Match the class name to the document name in Unity
6. Make sure you're Player Settings are set to 4.X C#
7. Test to ensure that your UI is working with the speech service in editor
8. Switch the above referenced line to get continuous speech working
9. Enter play mode
10. Observe that continuous speech does not work

**Expected behavior**
Continuous speech service should work as stated in Unity 2018.3.

**Version of the Cognitive Services Speech SDK**
Using version 1.3.0 for the SDK

**Platform, Operating System, and Programming Language**

* OS: Windows 10 - up to date
* Hardware - x64
* Programming language: C#

**Additional context**
Using Unity 2018.3.

**Comment by jhakulin** [comment]
Thanks for feedback!

For continuous recognition, please check the csharp code samples below:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-recognize-speech-csharp

You need to modify the code to fit for the Unity framework, for example 
Start() => Create recognizer and subscribe to events (e.g. recognizing & recognized)
Disable() => Unsubscribe from events and dispose recognizer
ButtonClick() => Do StartContinuousRecognitionAsync and StopContinuousRecognitionAsync action
RecognizedHandler & Update() => Update message text in the UI

I believe the documentation you referred was a comment below in the Unity sample ?
// For long-running multi-utterance recognition, use StartContinuousRecognitionAsync() instead.

We will improve the comment there and will provide more samples for Unity in the future.

**Comment by Brandon-Franklin** [comment]
I've been doing those things though I'm not using any UI at the moment since I'm activating with a key press using just the events and debug statements.

I believe my issue was not having the thread locker code in my script. I'm not entirely sure why that's required for the continuous speech when it isn't for the RecognizeOnceAsync function. But it does seem to be working now, thanks for the help.
