### ISSUE TITLE
Javascript SDK Not Able To Include Filler Words and Profanities In Response

### ISSUE THREAD

**Issue by adammpolak** [Azure-Samples/cognitive-services-speech-sdk#1660]
I am not able to set up azure speech to text to include filler words and profanities.

How can I include these in the transcriptions?

**Comment by dargilco** [comment]
See here for an example on how to set the profanity option:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/2cc99fc90f77930e458623cae43bf28022029ea5/scenarios/javascript/node/captioning/captioning.js#L260

Regarding Disfluency options (e.g. keeping/removing filler words), I'll have to get back to you on this.

**Comment by adammpolak** [comment]
thank you @dargilco , please let me know about keeping filler words. Our use case wants to count and list the number of filler words.

**Comment by adammpolak** [comment]
@dargilco any luck?

**Comment by dargilco** [comment]
Tagging @glharper to assist.

Unfortunately we don't yet have a way to separately control filler words. This is in discussion now with the speech recognition post-processing team. You may want to see what the detailed recognition results give you (there are several formats of the results). You will need to set the SpeechResultFormat to "Detailed" on the SpeechConfig, and then get the detailed recognition result. @glharper are there any code examples we can share showing how to do this?

**Comment by adammpolak** [comment]
@glharper  @dargilco 

Would these "Detailed" results provide the un-redacted text?

We want to provide the transcript and say "you used 3 'ums'", will that be possible?

**Comment by glharper** [comment]
@adammpolak See attached screenshot, using [this sample code](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/index.html). The text with the ums is in the list, but it's not the highest confidence result.

<img width="670" alt="Screen Shot 2022-09-20 at 1 06 05 PM" src="https://user-images.githubusercontent.com/64209257/191321242-528688e5-d649-4eba-88d9-8b6f63ed928f.png">

**Comment by dargilco** [comment]
@adammpolak you should see Lexical, ITN (Inverse Text Normalization), Masked ITN and Display formats for the recognition result. Not sure if the Lexical format will help you. The alternative results (the array of additional results that follow) are of no use to you.

**Comment by adammpolak** [comment]
> @adammpolak See attached screenshot, using [this sample code](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/index.html). The text with the ums is in the list, but it's not the highest confidence result.
> 
> <img alt="Screen Shot 2022-09-20 at 1 06 05 PM" width="670" src="https://user-images.githubusercontent.com/64209257/191321242-528688e5-d649-4eba-88d9-8b6f63ed928f.png">

This is very helpful thank you! I see that it IS possible to see "ummmms"

How would I go about combining using the "lexical" + what is returned as the final answer to get a "full transcript"?

I understand this is an implementation question, but because you are close to understanding how the processing is returned and some hidden "gotchas" how would you go about trying to implement?

**Comment by adammpolak** [comment]
@glharper @dargilco 

If the post-processing team could explain the steps they perform on the lexical result to get to the "final" result we see, I can try and "undo" those steps and get to the "pre-processed" output (that has filler words and double words).

**Comment by dargilco** [comment]
@adammpolak post-processing is a complicated step, not a simple recipe. I will bring this thread to their attention, just in case they have some tips, but it may be that we can't help you further now beyond what is mentioned above. I'm hoping we can release this new setting in the next few months (separately controlling turning on/off filler words). I opened an internal work item to discuss and track the request.

**Comment by adammpolak** [comment]
@dargilco  unfortunately we are looking for filler word count (as a way to help users notice their use)

We also do not have a specific transcript that the user reads from so the Pronunciation assessment won't fit the needs.

Is there any way to know the prioritization of this feature?

We need to make a call on a speech-to-text provider and we are willing to wait because we like ASTT SDK (easy to implement vs. others that need you to worry about audio codecs) but we do need to meet our requirements.

**Comment by pankopon** [comment]
Internal work item ref. 4530260.

**Comment by pankopon** [comment]
Closing the issue as a corresponding feature request has been added to our backlog and we continue internal tracking there.
