### ISSUE TITLE
Azure cognitive-services-speech-SDK in Java for continuous speech recognition is not stopped

### ISSUE THREAD

**Issue by Gaurabawal** [Azure-Samples/cognitive-services-speech-sdk#1664]
What I am trying to do?
I am trying to use cognitive-services-speech-SDK with Java language. The speech-to-text conversion function inside java code will be called from a flutter code when a mic is pressed.  The recording and speech-to-text conversion function should be stopped when I click the mic button. I have used a mic button as a toggle button where for the first button press the recording will be started and stop recording for the next click.

What I have done?
I have added a code from [https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/android/compressed-input/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/compressedinput/MainActivity.java] for continuous sound input from the microphone. I was able to get a transcribed text for the input sound but I was unable to stop the continuous service. 

What do I want to do?
recognizer.stopstopContinuousRecognitionAsync() is not stopping the speech transcribing. 

I have added a snippet of dart file where a java function is called when a button is pressed.
and a .txt file with a code written in java for azure cognitive speech to text transcription.
[java_file.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/9605004/java_file.txt)
<img width="436" alt="dart file" src="https://user-images.githubusercontent.com/105349401/191192149-1893d2d6-4583-46b1-a880-96b92731c6a3.png">

**Comment by glharper** [comment]
@Gaurabawal Thanks for using Speech SDK, and writing this issue up. In the Java code [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/24ee1373f8ce5996d1ed3f1e36a60d4028537054/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java#L305), I'm seeing the code:
```
recognizer.startContinuousRecognitionAsync().get()
...
recognizer.stopContinuousRecognitionAsync().get()
```
But in your attached java file, I'm just seeing you create a Future without actually getting the executed result. Could you change your method invocations to match the above pattern and see if that works for you?

**Comment by Gaurabawal** [comment]
@glharper Thank you for your reply. I have checked with the command that you send me. But still, speech SDK is transcribing speech into text even if I stopped.
[javafile.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/9612620/javafile.txt)

If I use future with recognizer.stopContinuousRecognitionAsync().get() give following error. So that I have removed the future for this moment.

> error: incompatible types: Void cannot be converted to Future<Void>
                                            final Future<Void> task = recognizer.stopContinuousRecognitionAsync().get();

I have attached a java file.

**Comment by glharper** [comment]
@Gaurabawal 
So, to clarify, you are not calling
recognizer.stopContinuousRecognitionAsync().get()?

I'm confused why you need assign the result of recognizer.stopContinuousRecognitionAsync().get() to the "final Future task" variable. Is there any way you could rewrite your code to *just* call recognizer.stopContinuousRecognitionAsync().get() without assigning the result to a variable?

**Comment by Gaurabawal** [comment]
@glharper 
I have applied recognizer.stopContinuousRecognitionAsync().get()  method and now it is working.

Previously, when I used .get() method I got some kind of errors.
We have to use recognizer.stopContinuousRecognitionAsync().get() inside try...catch exception handling. And then it worked.

Thank you for your help.
