### ISSUE TITLE
Inconsistent pronunciation of EUR currency in German

### ISSUE THREAD

**Issue by brknbyt** [Azure-Samples/cognitive-services-speech-sdk#1669]
**Describe the bug**
There is an inconsistency when having sentences with the EUR currency abbreviation in them. Normally an input text like `39.99 EUR` synthesises as _Neununddreizig Euro und neunundneunzig Cent_, which translates to _thirty-nine euros and ninety-nine cents_. 
But if an `.` is added to the end of the input text the pronunciation changes. `39.99 EUR.` synthesises to _Neununddreizig Punkt neun neun europäisch_, which translates to _thirty-nine dot nine nine european_. 
It is pronounced correctly with a dot at the end if text comes before the value like `Preis von 39.99 EUR.`, but the same problem occurs again when double spaces exist before the value like `Preis von  39.99 EUR.`.
I tried a few other currencies, where this problem did not appear. It also does not appear in US English.

**To Reproduce**
1. Paste `39.99 EUR.` to the Azure TTS page as text.
2. Select German as language and Katja (Neural) as voice.
3. Press Play button and listen.

**Expected behavior**
The cases `39.99 EUR.` and `Preis von  39.99 EUR.` are pronounced as whole value currency unit fractional value fractional unit. 

**Version of the Cognitive Services Speech SDK**
1.19.0

**Comment by fabswt** [comment]
I'll jump on this thread to ask a more general question: **what are our options, as developers, when the TTS output is wrong?**

The following sentences are all wrong.

*Generated today, 2022-10-03, via the Azure API, using en-US-ChristopherNeural).*  
*Reproducible with the [official TTS demo](https://azure.microsoft.com/en-us/products/cognitive-services/text-to-speech/#features) (e.g. using US Jenny).*

- Uh oh. This isn't good. [no hyphen]
  - "Uh oh" sounds awkward, the pause between both is too long.
- Uh-oh. I think we're lost! [hyphenated]
  - "Uh-oh" sounds awkward, there's no pause and it sounds much more like "ooh".
- Shh! The previews are starting!
  - "Shh!" is being pronounced as "S H H".
- Do you have any Post-It® Notes?
  - It pronounces the registered sign (as "registered")
- Could you please hand in your homework?
  - It does not pick up on the phrasal verb. Expecting "hand in" to be pronounced in one go, with a rise on "in". But instead  it's pronounced: "Could you please hand (pause) in your homework?"
- Are they into practical or sentimental gifts? [This one is maybe debatable]
  - The intonation pattern sounds a little off to me for a list of options. Would expect a slight pause after "sentimental".

They're easy to check by just listening to them.

**When could we expect a fix, please?** I'm using TTS for a language product and this forces me to edit the content or replace the audio.

FYI, Amazon Polly is getting all of them right.

Thanks!

**Comment by ForrestGumb** [comment]
Thank you for you feedback.
For the currency reading inconsistency issue, Microsoft will fix that. You can also unblock yourself by adding say-as tag like below.
<say-as interpret-as="currency">39.99 EUR</say-as>.

For the break issue, you can fix it by SSML break tag.
For pronunciation issue, you can fix it will SSML phoneme tag or custom lexicon. Also, Microsoft will investigate the “Shh” and “®” reading issue. Do you expect TTS don’t reading “®” or read it as something else?
Please reference SSML doc here: https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup
