### ISSUE TITLE
How to convert received audio stream into wav format (Javascript)

### ISSUE THREAD

**Issue by Marcophono2** [Azure-Samples/cognitive-services-speech-sdk#167]
Hello!

I am using the example code for Javascript and it works well. But I want to be able to get the audio stream (input audio file -> translated audio stream) for laster use in wav format. Is that possible? So if I could "catch" the stream data into a JS variable I could upload it via Ajax to my server to save it as a wav file.

Best regards
Marc

**Comment by wolfma61** [comment]
There is no way currently to split the audio stream inside the sdk. You have to capture the audio from the microphone yourself, and then store it in a file and send it as a stream to the sdk

thx
Wolfgang

**Comment by Marcophono2** [comment]
Thank you, Wolfgang! I'll try that.

Best regards
Marc
