### ISSUE TITLE
Using custom speech model using C++ (How-to question)

### ISSUE THREAD

**Issue by davehorton** [Azure-Samples/cognitive-services-speech-sdk#1683]
I have deployed a custom speech model and am accessing it via C++, but it does not seem to be working.  

> (The custom speech model has product names, like "ecocollect" for instance, but these are being returned in the transcript as "eco collect" which makes me think it is not detecting according to the model).

I have the endpoint id from when I deployed the model, and in my C++ code I am referencing it like this:

```
auto speechConfig  = SpeechConfig::FromSubscription(subscriptionKey, region);
speechConfig->SetEndpointId(endpointId);
```

Is this correct, or is there something more or different I need to do?

**Comment by BrianMouncer** [comment]
That seems correct to me, but I have not used custom models much.
The public sample for this topic can be found at https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/19fe4407c427b161ec628eae5f4c6540f8a7982d/samples/cpp/windows/console/samples/speech_recognition_samples.cpp#L216-L228

I suspect the model just isn't doing what you expect it to.
I will ask about the best ways to test your model to make sure it will behave the way you expect, and get back to you.

**Comment by davehorton** [comment]
great thanks!

**Comment by BrianMouncer** [comment]
@davehorton 

What is your end goal with the custom speech model?
Do you only need to recognize a half dozen product and company names more accurately, or do you need to do something more complex like a large set of terms like medical terms and phrases?

Here is some information that might help.

If you just need to improve recognition of a few product names, you might be able to keep using the general topic public speech endpoint, and add a PhraseListGrammar before you start recognition.  You can find more information on PhraseListGrammars [here](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/improve-accuracy-phrase-list?tabs=terminal&pivots=programming-language-csharp), and it is cheaper and easier to use than creating a custom speech recognition model and deploying it on your own private endpoint.  We have a public sample for PhraseListGrammars [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/19fe4407c427b161ec628eae5f4c6540f8a7982d/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L686).

If you do need a full custom recognition model, try testing your deployed models with the [Speech Command line tool](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/spx-basics?tabs=windowsinstall%2Cterminal)

If you run this SPX command line "spx help csr examples", you will give see some examples to create a Custom Speech Recognition(CSR) endpoint, and how to to test it's recognition output from command line.  I would suggest using SPX to test your current model to ensure it generates the basic output you expect, and then move on to integrate that model/endpoint into your C++ application.
