### ISSUE TITLE
Support python SDK in ARM/Android platform

### ISSUE THREAD

**Issue by flt6** [Azure-Samples/cognitive-services-speech-sdk#1684]
**Is your feature request related to a problem? Please describe.**
I have written a programe, which I want it available in all platforms. However, I found in Android platform(with termux) installing `azure-cognitiveservices-speech` is impossible due to only windows, mac, limux is provided on pypi.

**Describe the solution you'd like**
A `azure-cognitiveservices-speech` version built for Android(ARM) with termux.

**Additional context**
I can't build it myself due to I can't find code for lib `libMicrosoft.CognitiveServices.Speech.core` and so on.

**Comment by BrianMouncer** [comment]
The speech SDK have native library dependencies (libMicrosoft.CognitiveServices.Speech.core.so), so it is not enough to just compile the python bindings for ARM. We refactored our Wheel files, and plan to add ARM support in our upcoming 1.24 release, but this ARM support is for Linux and does not enable Android support for our python wheels.

We can look and see what it would cost us to add Android support for Python at some future point, but it is currently not on our roadmap.

We do support [Java](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/android/sdkdemo/README.md) on android though.

There is also the [Java Script SDK](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/node#readme) that does not have native dll dependencies.
