### ISSUE TITLE
The multi device conversation demo returns a problem

### ISSUE THREAD

**Issue by lenqing6** [Azure-Samples/cognitive-services-speech-sdk#1685]
![BZKmPy3wQ4](https://user-images.githubusercontent.com/96234501/194685070-2dd65a3b-a25e-4fb2-ab00-355e5e8df5f7.jpg)
Multi-device Conversation resultId every sentence is different
![image](https://user-images.githubusercontent.com/96234501/194685256-231c4b89-3dcf-4d6a-8de5-5276de30fc2d.png)
![image](https://user-images.githubusercontent.com/96234501/194685273-517fafe6-ea0f-4ad3-b333-e51fc23e4912.png)
![image](https://user-images.githubusercontent.com/96234501/194685291-1ba43e1f-e110-41a4-9f76-35bfd4f1931d.png)
The resultId of the same sentence has changed

**Comment by jeasonxiexie** [comment]
The TranslatingParticipantSpeech and TranslatedParticipantSpeech results of the same sentence have different resultIds

**Comment by jeasonxiexie** [comment]
can be reproduced in javascript sdk

**Comment by jeasonxiexie** [comment]
> @jeasonxiexie Thank you for using JS Speech SDK, and writing this issue up. So, to summarize, the issue here is that each callback event (from the screenshots, two "translating" events and one "translated" event) has its own resultId, correct? If you investigate other scenarios (speech recognition, text to speech, conversation transcription, etc.), you will find that each event for those (including "recognizing," "recognized," "canceled" for speech recognition) also has a unique resultId.
> 
> Given that this is idiomatic behavior in the SDK, which specific use case does this block for you?

but callback events for the same sentence should have a same unique resultId, right?  in java SDK translating/translated events for the same sentence use the same resultId, so i can update the translation text by this resultId.

**Comment by lenqing6** [comment]
@glharper This is a problem with your demo.
（https://translator.microsoft.com/）

**Comment by glharper** [comment]
> > @jeasonxiexie Thank you for using JS Speech SDK, and writing this issue up. So, to summarize, the issue here is that each callback event (from the screenshots, two "translating" events and one "translated" event) has its own resultId, correct? If you investigate other scenarios (speech recognition, text to speech, conversation transcription, etc.), you will find that each event for those (including "recognizing," "recognized," "canceled" for speech recognition) also has a unique resultId.
> > Given that this is idiomatic behavior in the SDK, which specific use case does this block for you?
> 
> but callback events for the same sentence should have a same unique resultId, right? in java SDK translating/translated events for the same sentence use the same resultId, so i can update the translation text by this resultId.

@jeasonxiexie I asked my team, and they don't believe this is the case. Using the [Speech CLI tool](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/spx-overview), and running the tool using the command line input: `spx recognize --output each resultid --output each file -`, we got:
<img width="512" alt="Screen Shot 2022-10-11 at 2 57 54 PM" src="https://user-images.githubusercontent.com/64209257/195178790-bcda609f-0006-41e1-9acb-076cb6028fa9.png">

Each event gets a unique result id both in Speech SDK and JS Speech SDK.

**Comment by jeasonxiexie** [comment]
in my java sdk, i update my AudioConfig property according to this [https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1566](url)
this is my demonstration， when i say  “hello，this is a speech test” ， results for this sentence share a same resultId，
 D  speech paticipantid:e508600e-dd1d-4c03-9017-5408453bc24d reason: TranslatingSpeech,speech text: Hello ResultId：64f75ff9-b9cf-4cd3-b3f0-d8fbc0da5b03 (SpeechRecognitionModel.java:77)
 D  speech paticipantid:e508600e-dd1d-4c03-9017-5408453bc24d reason: TranslatingSpeech,speech text: Hello, this is speech ResultId：64f75ff9-b9cf-4cd3-b3f0-d8fbc0da5b03 (SpeechRecognitionModel.java:77)
 D  speech paticipantid:e508600e-dd1d-4c03-9017-5408453bc24d reason: TranslatedSpeech,speech text: Hello, this is a speech test. ResultId：64f75ff9-b9cf-4cd3-b3f0-d8fbc0da5b03 (SpeechRecognitionModel.java:77)

**Comment by lenqing6** [comment]
@glharper It was still running normally before September 30, but the problem occurred on October 8.

**Comment by wangzhiming1999** [comment]
> > > @jeasonxiexie感谢您使用 JS Speech SDK 并撰写此问题。所以，总而言之，这里的问题是每个回调事件（从屏幕截图中，两个“翻译”事件和一个“翻译”事件）都有自己的 resultId，对吗？如果您调查其他场景（语音识别、文本转语音、对话转录等），您会发现这些场景的每个事件（包括“正在识别”、“已识别”、“已取消”用于语音识别）也有一个唯一的 resultId . 
> > > 鉴于这是 SDK 中的惯用行为，这会阻止您使用哪个特定用例？
> > 
> > 
> > 但是同一句话的回调事件应该有相同的唯一resultId，对吧？在 java SDK 中，同一个句子的翻译/翻译事件使用相同的 resultId，所以我可以通过这个 resultId 更新翻译文本。
> 
> @jeasonxiexie我问过我的团队，他们不相信是这样。使用[Speech CLI 工具](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/spx-overview)，并使用命令行输入：运行该工具`spx recognize --output each resultid --output each file -`，我们得到： <img alt="屏幕截图 2022-10-11 下午 2 57 54" width="512" src="https://user-images.githubusercontent.com/64209257/195178790-bcda609f-0006-41e1-9acb-076cb6028fa9.png">
> 
> 每个事件在 Speech SDK 和 JS Speech SDK 中都获得一个唯一的结果 ID。

So you think it's normal for a sentence to be recognized as 4 IDs? Aren't you an ID corresponding to a sentence?

**Comment by wangzhiming1999** [comment]
> > > > @jeasonxiexie感谢您使用您并编写此事件问题。 ？如果您已经调查过（译文识别、文本转换、发现场景等），您会这些场景的每个事件（包括“正在语音识别”、“识别”、“取消识别识别”）也有一个的resultId .
> > > > 只能自动实现特定的SDK中的惯用例，这会阻止您使用哪个实例？
> > > 
> > > 
> > > 同一个文本的翻译事件/结果应该有相同的唯一resultId，在java SDK中，同一个翻译事件使用相同的resultId，我可以更新resultId。
> > 
> > 
> > @jeasonxiexie使用该CLI[工具](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/spx-overview)，并询问我们使用技术输入：工具`spx recognize --output each resultid --output each file -`，结果：<img alt="屏幕截图 2022-10-11 下午 2 57 54" width="512" src="https://user-images.githubusercontent.com/64209257/195178790-bcda609f-0006-41e1-9acb-076cb6028fa9.png">
> > 事件在 Speech SDK 和 JS Speech SDK 中都获得了唯一的结果 ID。
> 
> 所以你认为一个句子被识别为4个ID是正常的吗？你不是一个句子对应的ID吗？
Why is the JavaSDK one sentence corresponding to one ID, rather than multiple different IDs you said

**Comment by glharper** [comment]
@ralph-msft Is this a difference between Conversation Translator implementation and the rest of Speech SDK?

**Comment by lenqing6** [comment]
Please give an accurate answer

**Comment by jeasonxiexie** [comment]
inform us if any conclusion

**Comment by lenqing6** [comment]
@ralph-msft Can you help with this problem？

**Comment by pankopon** [comment]
Closed due to the lack of updates. To confirm:

> Aren't you an ID corresponding to a sentence?

The result ID is not a sentence ID, it is a result ID.
For each (recognizable) sentence there may be N intermediate results (*Recognizing*) and 1 final result (*Recognized*).
Each result gets its own ID.
A sentence is being recognized until there's a final result.
