### ISSUE TITLE
iphone 14 doest work with fromDefaultMicrophoneInput 

### ISSUE THREAD

**Issue by sacha-6over6** [Azure-Samples/cognitive-services-speech-sdk#1688]
**Describe the bug**
Speech to text does not open on all iphone 14's (Other models work).   Get the following error in the console.  This is also the case on your live demo.   At least you see the same issue.  For the record createMediaStreamSource works

1. Go to https://azure.microsoft.com/en-us/products/cognitive-services/speech-to-text/#features
2. scroll down to demo.
3. Press speak
4. start talking to microphone
5. Doesnt work as expected
6. check console

**Expected behavior**
The product to run and turn my speech into text

**Version of the Cognitive Services Speech SDK**
Version on my code base is: 1.23.0.  On your code base do not know

**Platform, Operating System, and Programming Language**
 - OS: ios
 - Hardware - iphone 14 pro, iphone 14 pro max
 - Programming language:  JavaScript
 - Browser Safari

**Additional context**
Failed to create MediaStream audio source: No AVAudioSessionCaptureDevice device
© › undefined | undefined | privName: AudioSourceErrorEvent | privEventld:
microsoft.cognitiveservices.speech.sdk.bundle.js:1:2399
F56316DEE97240AAB892D274D78CC876 | privEventTime:2022-10-11T12:36:13.585Z|privEventType:3|privMetadata:0|privAudioSourceld:
AE521210F77E4FE688A6A0AF4B64A959 | privError: Error occurred during microphone initialization: NotReadableError: The 1/0 read operation failed.

**Comment by rhurey** [comment]
Thanks for getting in touch. I'm looking for someone on our team with a 14 to investigate...

**Comment by sacha-6over6** [comment]
Thanks waiting on your findings

**Comment by sacha-6over6** [comment]
Any updates or an eta on this ?

**Comment by pankopon** [comment]
Internal work item ref. 4601341.

**Comment by rhurey** [comment]
Sorry about the delay on this one, I did manage to verify that the latest iOS update (16.2) resolved this issue on the 14 pro I was debugging on.

**Comment by glecaros** [comment]
Closing per @rhurey's comment that it was resolved by an iOS update
