### ISSUE TITLE
Xamarin.Mac doesn't see the dll when running the app

### ISSUE THREAD

**Issue by ivanicin** [Azure-Samples/cognitive-services-speech-sdk#1689]
**Describe the bug**
The package can be added to Xamarin.Mac from nuget and it installs properly. Intelisense works and Visual Studio is aware of all APIs. However when the app gets compiled in runtime any attempt to access the API will result in the exception.

**To Reproduce**
1. Create Xamarin.Mac project
2. Install the package via nuget
3. Put somewhere this code:
                `var config = SpeechConfig.FromSubscription(APIKey, APIRegion);`

When you run it you get:

> System.DllNotFoundException has been thrown
> Microsoft.CognitiveServices.Speech.core.dll assembly:<unknown assembly> type:<unknown type> member:(null)

**Expected behavior**
This should work as it works on all platforms. I've tried to skip the package and reference .dll directly but it appears that iOS .dll doesn't work for this.

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.
1.23.0

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - please be specific
 macOS
 - Hardware - x64, x86, ARM, ...
 x64
 - Programming language: C#, C++, Java, JavaScript, Objective-C, Python
 C#
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific

**Additional context**
 - Error messages, stack trace, sample code to reproduce the issue, ...
 - Please provide full Speech SDK Log, as per the instructions [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging)?
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by trrwilson** [comment]
Thanks for reporting this. If there's a package targeting issue we'd like to narrow down and resolve it!

Three avenues:

1. Can you share the full OS and platform details of the development environment, deployment target, and any intervening hardware? As an example: in our recent release testing for 1.24, we verified our Xamarin quickstart as compiled from Windows 10/11 x64, paired with an x64 MacBook running Monterey, deploying to an iOS 8 emulator image.
2. And as for that validation, it was done using our public Xamarin quickstart. Does this same targeting issue exist if you use that project? https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/xamarin
3. Finally, you mentioned you tried referencing .DLLs directly. Can you share more about which binaries (including their relative packages for platform/architecture) and how they were included?

Thanks for the extra information!

**Comment by ivanicin** [comment]
@trrwilson I think that there is some confusion, though my description is correct. 

I can’t run that sample as you don’t have Xamarin.Mac there. You have only Xamarin.iOS. 

Making Xamarin.iOS packages run on Xamarin.Mac doesn’t require almost anything if you don’t touch UI and I guess you don’t.

Other Azure packages do work, I have used some of them. Also popular 3rd party packages like HTMLAgility and SharpCompress do work though for example SharpCompress developer doesn’t have the Mac at all. I haven’t built such packages myself to say exactly whether you need something like additional declarations, but it should be trivial.

**Comment by jhakulin** [comment]
@ivanicin Speech SDK NuGet do not currently have Xamarin.Mac target, however for Mac there are native libraries under `runtimes/osx-x64/ and runtimes/arm64` folders, which can be used e.g., by .netcore applications. As you have also verified, Xamarin.Mac do not know how to look the native libraries under the NuGet's runtimes folder and sample will not work.

For the next release, we will be adding more support for MAUI e.g., maccatatalyst targets, which you can use for Mac development forward if you are willing to switch from Xamarin to MAUI. Before that it is also possible that you take the C# dll for Mac from NuGet's runtimes\osx-arm64\lib\netstandard2.0 folder and native dylib for Mac from runtimes\osx-arm64\native folder and manually integrate those into your Xamarin.Mac application.

**Comment by pankopon** [comment]
Closed as answered, please create a new issue if more support is needed.
