### ISSUE TITLE
Release notes for v1.24.0

### ISSUE THREAD

**Issue by Tenzer** [Azure-Samples/cognitive-services-speech-sdk#1691]
I can see a new version of the speech SDK is available: https://pypi.org/project/azure-cognitiveservices-speech/1.24.0/. There's, however, no mention of the new version in the release notes at https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/releasenotes?tabs=speech-sdk.

Could they please be updated, so we can know what to expect when updating the library?

**Comment by sibbl** [comment]
Seems like they've been published meanwhile.

**Comment by pankopon** [comment]
Release notes are now available: https://learn.microsoft.com/azure/cognitive-services/Speech-Service/releasenotes?tabs=speech-sdk#speech-sdk-1240-october-2022-release
