### ISSUE TITLE
can't synthesis speech

### ISSUE THREAD

**Issue by litaof** [Azure-Samples/cognitive-services-speech-sdk#1694]
**Describe the bug**
using cogsdk to generate samples error:  Speech synthesis canceled; error details: Error in sending a http request.0

**To Reproduce**
1. using cogsdk to generate production samples.

**Expected behavior**

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - please be specific
 - Hardware - x64, x86, ARM, ...
 - Programming language: C#, C++, Java, JavaScript, Objective-C, Python
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific

**Additional context**
 - Error messages, stack trace, sample code to reproduce the issue, ...
 - Please provide full Speech SDK Log, as per the instructions [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging)?
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by yulin-li** [comment]
Hi, could you please provide full Speech SDK Log, as per the instructions [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging)?

**Comment by litaof** [comment]
add log file: [Logfile.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/9797340/Logfile.txt)

**Comment by yulin-li** [comment]
Are you running this on Windows? If yes, could you try to check if the latest patch is installed as described in #1692? The latest Windows patch has a regression that blocks the TLS connection

**Comment by pankopon** [comment]
Closed since no further update, please refer to the mentioned main issue for the latest status on fixes, or create a new item if other kind of support is needed.
