### ISSUE TITLE
Howto limit length of sentences return in recognized events for JS SDK?

### ISSUE THREAD

**Issue by KevinBarbier2** [Azure-Samples/cognitive-services-speech-sdk#1697]
Is there a way were an option can be set to limit the length of the text  returned by recognized event for continuous recognition in JS SDK?

for example:

```json
{
  "privSessionId": "XXX",
  "privOffset": 615200000,
  "privResult": {
    "privResultId": "XXX",
    "privReason": 3,
    "privText": "De werking van de Vlaamse provincies. Er is ook een afzonderlijk Ocean wp, decreet en een decreet dat de intergemeentelijke samenwerking regelt. Onder de regering bourgeois is er echter in 2017 een decreet lokaal bestuur gekomen ter vervanging van het gemeentedecreet, het Ocean mee decreet en het decreet intergemeentelijke samenwerking. Een van de grootste bekommernissen bij het tot stand komen van het gemeentedecreet was zoveel als mogelijk de autonomie.",
    "privDuration": 307300000,
    "privOffset": 615200000,
    "privLanguage": "nl-NL",
    "privLanguageDetectionConfidence": "Unknown"
  }
}
```
Where PrivText should be shortened and split up to smaller sentences each in it's own recognized event with seperate duration+offsets given.
I tried to have a look at your captioning.js example but there it just turns very long sentences into SRT/VTT, but that's unusable in a web player since it takes up half the video screen when rendering subtitles.

The Java example has a maxlinelength option but this seems to be a not so accurate helper function inside the example itself

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/scenarios/java/jre/console/captioning/Captioning.java#L101

Thanks

**Comment by rhurey** [comment]
Thanks for looking at the SDK's. Today there isn't a way to specify the maximum phrase length, or to have the SDK split a single phrase into multiple phrases. Phrases are segmented by the silence gap between them up to a time based maximum that the SDK doesn't control.
