### ISSUE TITLE
Is it possible to detect when the model is done with processing a given audio file?

### ISSUE THREAD

**Issue by stoney95** [Azure-Samples/cognitive-services-speech-sdk#170]
Hi,

I'm working in python using the `azure-cognitiveservices-speech`-package.

I'm using the `speech_recognition_with_push_stream` example to process some audio files. I adjusted the code in the way that I increased buffer-size (`n_bytes`). This leads to the code processing the file in one iteration and finishing before the file could be processed. In my view one solution would be to block the main-thread and wait for an event that fires when processing the given file is completed. 

I start the recognition by the following:

        def _recognize_with_push(self):
             n_bytes = self._get_available_memory()
             self.speech_recognizer.start_continuous_recognition()

             while(True):
                frames = self.audio_config["input_stream"].readframes(n_bytes // 2)
                print('read {} bytes'.format(len(frames)))
                if not frames:
                    break
                self.audio_config["write_stream"].write(frames)
                time.sleep(.1)

            while(not self.finished):
                time.sleep(0.5)

`self.finished` is set to true in the event-handler `_completed()`:

UPDATE:
```
def _completed(self, evt):
        print('FINISHED {}'.format(evt))
        self.finished = True
        self.speech_recognizer.stop_continuous_recognition()
        self.audio_config["input_stream"].close()
        self.audio_config["write_stream"].close()
```

So far i tried:
 - `self.speech_recognizer.canceled.connect(self._completed)`
 - `self.speech_recognizer.session_stopped.connect(self._completed)`

But in both cases the program hang after the last `recognized` event for the file. Maybe this indicates that these events are not fired when you are working with streams?! Because as i worked with the `filename`-option these events got fired after the file was processed.
Is there an other event i could listen for? Or is there an other possibility to wait until the file is processed completely?

**Comment by chlandsi** [comment]
Can you share the code for your `_completed` handler? Note that it also takes an argument (`evt`). If your function doesn't take an argument, this will currently fail silently.

**Comment by stoney95** [comment]
I updated my initial comment ;)

**Comment by chlandsi** [comment]
The stream should be closed when you are done sending the data, i.e. once the code exits the while loop. That will trigger a canceled and a session stopped event once the data has been processed.

**Comment by stoney95** [comment]
Closing the stream after all bytes have been sent solved the problem. Thanks!
