### ISSUE TITLE
TTS word boundary inconsistencies

### ISSUE THREAD

**Issue by GoncaloBastos** [Azure-Samples/cognitive-services-speech-sdk#1705]
Depending on whether you apply pronunciation changes through the lexicon or using the tag, the returned word boundary will differ.

When using the lexicon, the original text is returned in word boundary, while using the tag, the value inside the alias attribute is what is returned in word boundary.

Based on the example usage for WordBoundary (closed captions/subtitles), I believe the expected behaviour should be to return the original text (i.e. lexicon behaviour).

**Comment by yulin-li** [comment]
Thanks for reporting this and it's known issue. @jiajzhan , could you help on this?

**Comment by pankopon** [comment]
@yulin-li Please assign to the correct person (or yourself), seems I cannot add @jiajzhan.

**Comment by jiajzhan** [comment]
@pankopon, I will follow up, open a task 4681637 to track.
