### ISSUE TITLE
TypeInitializationException when used in Blazor WASM

### ISSUE THREAD

**Issue by alexnesh** [Azure-Samples/cognitive-services-speech-sdk#1709]
Hi,

I'm trying to use the C# Speech SDK within a Blazor WASM application, but I get errors when trying to initialize an `AudioConfig` entity. I've been using the C# sample code for joining a conversation, but can repro this by just trying to initialize an `AudioConfig` entity in my main a la: 

```
using System.Diagnostics;
using Microsoft.CognitiveServices.Speech.Audio;

namespace Application
{
    class Program
    {
        public static async Task Main(string[] args)
        {
            try
            {
                AudioConfig audioConfig = AudioConfig.FromDefaultMicrophoneInput();
            }
            catch (Exception e)
            {
                Debug.WriteLine(e.Message);
            }
        }
    }
}
```

The error details that I get are:

> 'The type initializer for 'Microsoft.CognitiveServices.Speech.Internal.AudioConfig' threw an exception.'

Which leads me to believe that the assembly is missing or isn't available in my environment. Is the C# Speech SDK supported in Blazor WASM? I've tried cleaning + restoring Nuget packages, etc., to no avail. 

Thanks!

**Comment by pankopon** [comment]
Hi, unfortunately WASM is not supported - see #930 and #1349. We have a work item on the backlog to add support, but no ETA.

**Comment by pankopon** [comment]
Internal work item ref. 3218205.

**Comment by pankopon** [comment]
Closing the item as the feature request will be tracked with an internal work item. Please open a new issue if more support is needed.
