### ISSUE TITLE
SpeechSynthesizer: include ResultId in SpeechSynthesisBookmarkEventArgs

### ISSUE THREAD

**Issue by sibbl** [Azure-Samples/cognitive-services-speech-sdk#1711]
The `SpeechSynthesisEventArgs` for `SynthesisStarted`, `Synthesizing`, `SynthesisCompleted` and `SynthesisCanceled` all contain a `SpeechSynthesisResult` with a unique ID of speech synthesis result.

However, `SpeechSynthesisBookmarkEventArgs` does not include this result Id.

When reusing the same `SpeechSynthesizer`, there's no possibility to map bookmarks to the synthesize results by using this unique id.

Is it possible to also include this unique ID in the bookmark event arguments as well, or are these two features so different that it's up to the SDK users to implement such a mapping?

Thanks in advance!

**Comment by ralph-msft** [comment]
Thank you for your input. It is possible to add the ID to the bookmark events as well. This is a feature request/bug. I've added it to our backlog. We will address this in a future release. Once the work is done, we will update this issue to let you know what release the feature/fix will be in.

**Comment by yulin-li** [comment]
As @ralph-msft said, we will add this in future release. And meanwhile, it's guaranteed that all bookmark events are before the `SynthesisStarted` and `SynthesisCompleted` events of the same request.

**Comment by pankopon** [comment]
Internal work item ref. 4615651.

**Comment by pankopon** [comment]
This will be supported in the Speech SDK 1.25.0 release (early 2023).
