### ISSUE TITLE
Audio Processing options for Translation Recognizers

### ISSUE THREAD

**Issue by SGNjogu** [Azure-Samples/cognitive-services-speech-sdk#1717]
The Audio Processing options on here work pretty well with the Speech Recognizer. I do, however, have need for similar processing options, using a Translation Recognizer.

I have attempted to use it, but when compiling using .NET Native tool chain, I get a SPXERR_RUNTIME_ERROR error. I am using the latest version, Microsoft.CognitiveServices.Speech 1.24.1, on a UWP application.

**Comment by chschrae** [comment]
Hi there,

Thanks for reaching out to us. Can you provide some code snippets of exactly what you are attempting to do? Both what is working with the SpeechRecognizer and what is not working with the TranslationRecognizer would be helpful.

**Comment by SGNjogu** [comment]
From the documentation [here](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/audio-processing-speech-sdk?tabs=csharp), using the default options with the SpeechRecognizer like this works:

`var speechConfig = SpeechConfig.FromSubscription("YourSubscriptionKey", "YourServiceRegion");

var audioProcessingOptions = AudioProcessingOptions.Create(AudioProcessingConstants.AUDIO_INPUT_PROCESSING_ENABLE_DEFAULT);
var audioInput = AudioConfig.FromDefaultMicrophoneInput(audioProcessingOptions);

var recognizer = new SpeechRecognizer(speechConfig, audioInput);`

Attempting to use similar audio options with a translation recognizer throws the error  SPXERR_RUNTIME_ERROR

`var speechConfig = SpeechConfig.FromSubscription("YourSubscriptionKey", "YourServiceRegion");

var audioProcessingOptions = AudioProcessingOptions.Create(AudioProcessingConstants.AUDIO_INPUT_PROCESSING_ENABLE_DEFAULT);
var audioInput = AudioConfig.FromDefaultMicrophoneInput(audioProcessingOptions);

var recognizer = new TranslationRecognizer(speechConfig, audioInput);`

**Comment by glecaros** [comment]
Hey @SGNjogu, can you please share logs of a failed run ([enabling logs](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging))

**Comment by SGNjogu** [comment]
Hi @glecaros , for some reason, I can't get the class to log the errors in the file. Below is a snippet of what I have on my end:

```c#
AudioProcessingOptions audioProcessingOptions = AudioProcessingOptions.Create(AudioProcessingConstants.AUDIO_INPUT_PROCESSING_ENABLE_DEFAULT);
AudioConfig audioConfig = AudioConfig.FromMicrophoneInput(_inputDevice.DeviceId, audioProcessingOptions);
Recognizer = new TranslationRecognizer(TranslationConfig, audioConfig);
```

The exception is thrown when creating the TranslationRecognizer with the AudioOptions as above.
```
System.ApplicationException
Message : Exception with an error code: 0x1b (SPXERR_RUNTIME_ERROR)
```

All the examples in the documentation are using the SpeechRecognizer, as below:
``` C#
var recognizer = new SpeechRecognizer(speechConfig, audioInput);
```

**Comment by glharper** [comment]
I've repro-ed this issue in SpeechRecognizer, and here's the log.
[logfile_CARBONGLHARPER.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/10035309/logfile_CARBONGLHARPER.txt)

**Comment by jychoudh** [comment]
I will take a look at this.

**Comment by pankopon** [comment]
@jychoudh Please update with the latest status.

**Comment by jychoudh** [comment]
I could not repro the issue. MAS works fine with TranslationRecognizer if microphone array is used. I used the following code and it worked.

```
using Microsoft.CognitiveServices.Speech;
using Microsoft.CognitiveServices.Speech.Audio;
using Microsoft.CognitiveServices.Speech.Translation;

class Program
{
    static void OutputSpeechRecognitionResult(TranslationRecognitionResult translationRecognitionResult)
    {
        switch (translationRecognitionResult.Reason)
        {
            case ResultReason.TranslatedSpeech:
                Console.WriteLine($"RECOGNIZED: Text={translationRecognitionResult.Text}");
                foreach (var element in translationRecognitionResult.Translations)
                {
                    Console.WriteLine($"TRANSLATED into '{element.Key}': {element.Value}");
                }
                break;
            case ResultReason.NoMatch:
                Console.WriteLine($"NOMATCH: Speech could not be recognized.");
                break;
            case ResultReason.Canceled:
                var cancellation = CancellationDetails.FromResult(translationRecognitionResult);
                Console.WriteLine($"CANCELED: Reason={cancellation.Reason}");

                if (cancellation.Reason == CancellationReason.Error)
                {
                    Console.WriteLine($"CANCELED: ErrorCode={cancellation.ErrorCode}");
                    Console.WriteLine($"CANCELED: ErrorDetails={cancellation.ErrorDetails}");
                    Console.WriteLine($"CANCELED: Did you set the speech resource key and region values?");
                }
                break;
        }
    }

    async static Task Main(string[] args)
    {
        var speechTranslationConfig = SpeechTranslationConfig.FromSubscription("YourSubscriptionKey", "YourServiceRegion");
        speechTranslationConfig.SpeechRecognitionLanguage = "en-US";
        speechTranslationConfig.AddTargetLanguage("es");

        using var audioProcessingOptions = AudioProcessingOptions.Create(AudioProcessingConstants.AUDIO_INPUT_PROCESSING_ENABLE_DEFAULT);
        using var audioConfig = AudioConfig.FromMicrophoneInput("<device_id>", audioProcessingOptions);
        using var translationRecognizer = new TranslationRecognizer(speechTranslationConfig, audioConfig);

        Console.WriteLine("Speak into your microphone.");
        var translationRecognitionResult = await translationRecognizer.RecognizeOnceAsync();
        OutputSpeechRecognitionResult(translationRecognitionResult);
    }
}
```

**Comment by pankopon** [comment]
Closed as tested working with the code above. Please open a new issue if more support is needed.
