### ISSUE TITLE
startContinuousRecognitionAsync not working (Javascript)

### ISSUE THREAD

**Issue by zacktayl** [Azure-Samples/cognitive-services-speech-sdk#172]
**Describe the bug**
I was playing around with the [Javascript SDK Example](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-js-browser), but after switching out recognizeOnceAsync with startContinuousRecognitionAsync, I get the following error: 
```
Cannot read property 'reject' of null
    at microsoft.cognitiveservices.speech.sdk.bundle.js:3386
```
This error seems to occur because `_this.privInitializeDeferral` is null.

**To Reproduce**
1. Follow the [Javascript SDK Example](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-js-browser)
2. Replace recognizeOnceAsync with startContinuousRecognitionAsync
3. Click Start Recognition
4. Enable the Microphone
-> Error occurs in the console

**Expected behavior**
I would expect the startContinuousRecognitionAsync function to process speech to text in a continuous loop.

**Version of the Cognitive Services Speech SDK**
1.3.0

**Platform, Operating System, and Programming Language**
 - OS: Mac OS 10.14.3
 - Programming language: JavaScript
 - Browser Chrome Version 72.0.3626.96 (Official Build) (64-bit)

**Comment by zacktayl** [comment]
Actually nevermind. This was a blunder on my part. I wasn't calling the `startContinuousRecognitionAsync` function correctly.

**Comment by nitishbijalwan01** [comment]
@zacktayl - Could you please share the code sample to use startContinuousRecognitionAsync. Even I am facing the challenge in calling this method.
