### ISSUE TITLE
Error deploying ArmTemplateBatch.json template with SQL parameters for the Ingestion Client project

### ISSUE THREAD

**Issue by alfogo** [Azure-Samples/cognitive-services-speech-sdk#1720]
**Describe the bug**
Error deploying template "ArmTemplateBatch.json" when setting values for Sql Administrator Login and Password to have further analytics for the Ingestion Client project

**To Reproduce**
1. Copy json file https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json
2. Paste in Azure Custom template
3. Fill in mandatory values and set SQL Admininstrator Login and password

**Expected behavior**
Template to be succesfully deployed

**Version of the Cognitive Services Speech SDK**
Last version as of November 2022

**Platform, Operating System, and Programming Language**
N/A
We are deploying a brand new template from scratch

**Additional context**
Getting following error of type "Microsoft.Sql/servers/databases/extensions" for resource "sqlserver20221102t120048z/Database-20221102t120048z/Import":

{
    "status": "Failed",
    "error": {
        "code": "0",
        "message": "Incorrect format for StorageKey of type StorageAccessKey.",
        "details": [
            {
                "code": "0",
                "message": "Incorrect format for StorageKey of type StorageAccessKey."
            }
        ]
    }
}

**Comment by HenryvanderVegte** [comment]
Hey @alfogo,

thanks for bringing this up. I'll have a look at it!

Best,
Henry

**Comment by HenryvanderVegte** [comment]
Hey @alfogo ,

can you try to deploy the Ingestion Client again? The database deployment should be fixed now.

Best,
Henry

**Comment by HenryvanderVegte** [comment]
Closing now. Please reopen if you still experience issues.

**Comment by alfogo** [comment]
Thanks! @HenryvanderVegte. We'll test it and let you know in case any problem.
