### ISSUE TITLE
Request for a subscription to continue my development on `aspeak`

### ISSUE THREAD

**Issue by kxxt** [Azure-Samples/cognitive-services-speech-sdk#1722]
Hi,

I'm the creator and maintainer of [`aspeak`](https://github.com/kxxt/aspeak).

`aspeak` is a simple text-to-speech client which enables you to try out Azure's speech synthesis API directly in your terminal.

It acts as a good frontend for azure tts services.

Recently, it seems that Microsoft has deliberately done some changes to prevent 3rd party tools(such as aspeak) using their trial service.

I do not really want to go against Microsoft.  I plan to make aspeak require an azure subscription to use in the next major version.

I believe 5 audio hours free per month provided by a free subscription is enough for most users of aspeak. However, as an undergraduate  with only a prepaid card, I can't even register a free azure subscription. And the Azure for Students/Microsoft Imagine  subscription doesn't include Speech service. As a result,  I do not have a subscription to test my application.

It would be generous of you to provide a cognitive services subscription for me to continue my development on `aspeak`.

My azure account is rsworktech@outlook.com

**Comment by chschrae** [comment]
Hi there,

Someone from Microsoft will reach out to you directly. I will close this issue since it isn't really an SDK issue, but I have forwarded your request.
