### ISSUE TITLE
How to use microphone instead of wavfile for push stream or pull stream

### ISSUE THREAD

**Issue by e-driver1** [Azure-Samples/cognitive-services-speech-sdk#1733]
Hi there,
I am trying to convert real-time speech into text from a microphone. and need this to work in the cloud.

**The issue**
My current solution works locally, but is not suited for a web app, as it will try and use the server's microphone (to which it has been deployed). The answer to this was given [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1726#issuecomment-1304071431).

I have read up on the topic and it seems the most relevant resources are mentioned [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1215#issuecomment-901507916).

However, both of these examples use already downloaded wavfiles, that the recognizer then converts into text.

What I need to know is, having looked extensively, there doesn't appear to be a python example of using the microphone as a streaming device. Or, is there?

Before moving across to JS, so I can make use of the JS SDK (which could help), just thought I'd check in...

**Version of the Cognitive Services Speech SDK:**
azure-cognitiveservices-speech==1.24.1

**Platform, Operating System, and Programming Language:**

OS: Windows 10
Hardware - x64
Programming languages: Python 3.11.0, HTML, CSS
Framework: Flask
Cloud Platform used for deployment: Heroku
Hosting service: Github
Browser Chrome

**Additional context**
The code I have working locally is here:
`import re
import os
import time
import wave
import string

try:
    import azure.cognitiveservices.speech as speechsdk
except ImportError:
    print("""
    Importing the Speech SDK for Python failed.
    Refer to
    https://docs.microsoft.com/azure/cognitive-services/speech-service/quickstart-python for
    installation instructions.
    """)
    import sys
    sys.exit(1)
# Set up the subscription info for the Speech Service:
# Replace with your own subscription key and service region (e.g., "westus").
os.environ['SPEECH_KEY'] = '[key goes here]'
os.environ['SPEECH_REGION'] = 'uksouth'

def recognize_from_microphone():
    # This example requires environment variables named "SPEECH_KEY" and "SPEECH_REGION"
    speech_config = speechsdk.SpeechConfig(subscription=os.environ.get('SPEECH_KEY'), region=os.environ.get('SPEECH_REGION'))
    speech_config.speech_recognition_language="en-GB"

    audio_config = speechsdk.audio.AudioConfig(use_default_microphone=True)
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)
    
    print("Speak into your microphone.")
    speech_recognition_result = speech_recognizer.recognize_once_async().get()
    speech_recognition_text = speech_recognition_result.text
    num_list = re.findall(r'\d+', speech_recognition_text)
    num_str = ' '.join(map(str, num_list))
    frt_list = ['bananas', 'apples', 'pears', 'oranges']

    if speech_recognition_result.reason == speechsdk.ResultReason.RecognizedSpeech:
        print("Recognized: {}".format(speech_recognition_text))
        print(type("This is the data type: " + speech_recognition_text))
        #time.sleep(5)
        
        if any((match := substring) in speech_recognition_text for substring in frt_list):
            print('You want', num_str, match)
            if ("next" or "Next") in speech_recognition_text:
                print('I have detected you want another')
                time.sleep(2)
                recognize_from_microphone()
            else:
                print('You have finished')
        else:
            print('not detected')
            
    elif speech_recognition_result.reason == speechsdk.ResultReason.NoMatch:
        print("No speech could be recognized: {}".format(speech_recognition_result.no_match_details))
    elif speech_recognition_result.reason == speechsdk.ResultReason.Canceled:
        cancellation_details = speech_recognition_result.cancellation_details
        print("Speech Recognition canceled: {}".format(cancellation_details.reason))
        if cancellation_details.reason == speechsdk.CancellationReason.Error:
            print("Error details: {}".format(cancellation_details.error_details))
            print("Did you set the speech resource key and region values?")

recognize_from_microphone()`

**What I've tried**
Looking at what has been recommended [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1215#issuecomment-906754784) (in using the defined callback, stream and audio_config functions), I have tried the following, but with no success...

`import re
import os
import time
import wave
import string

try:
    import azure.cognitiveservices.speech as speechsdk
except ImportError:
    print("""
    Importing the Speech SDK for Python failed.
    Refer to
    https://docs.microsoft.com/azure/cognitive-services/speech-service/quickstart-python for
    installation instructions.
    """)
    import sys
    sys.exit(1)
# Set up the subscription info for the Speech Service:
# Replace with your own subscription key and service region (e.g., "westus").
os.environ['SPEECH_KEY'] = '[]key goes here'
os.environ['SPEECH_REGION'] = 'uksouth'

def recognize_from_microphone():
    # This example requires environment variables named "SPEECH_KEY" and "SPEECH_REGION"
    speech_config = speechsdk.SpeechConfig(subscription=os.environ.get('SPEECH_KEY'), region=os.environ.get('SPEECH_REGION'))
    speech_config.speech_recognition_language="en-GB"

    stream = speechsdk.audio.PushAudioInputStream()
    audio_config = speechsdk.audio.AudioConfig(stream=stream)
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)
    
    print("Speak into your microphone.")
    speech_recognition_result = speech_recognizer.recognize_once_async().get()
    speech_recognition_text = speech_recognition_result.text
    num_list = re.findall(r'\d+', speech_recognition_text)
    num_str = ' '.join(map(str, num_list))
    frt_list = ['bananas', 'apples', 'pears', 'oranges']

    if speech_recognition_result.reason == speechsdk.ResultReason.RecognizedSpeech:
        print("Recognized: {}".format(speech_recognition_text))
        print(type("This is the data type: " + speech_recognition_text))
        #time.sleep(5)
        
        if any((match := substring) in speech_recognition_text for substring in frt_list):
            print('You want', num_str, match)
            if ("next" or "Next") in speech_recognition_text:
                print('I have detected you want another')
                time.sleep(2)
                recognize_from_microphone()
            else:
                print('You have finished')
        else:
            print('not detected')
            
    elif speech_recognition_result.reason == speechsdk.ResultReason.NoMatch:
        print("No speech could be recognized: {}".format(speech_recognition_result.no_match_details))
    elif speech_recognition_result.reason == speechsdk.ResultReason.Canceled:
        cancellation_details = speech_recognition_result.cancellation_details
        print("Speech Recognition canceled: {}".format(cancellation_details.reason))
        if cancellation_details.reason == speechsdk.CancellationReason.Error:
            print("Error details: {}".format(cancellation_details.error_details))
            print("Did you set the speech resource key and region values?")

recognize_from_microphone()`

**Comment by glecaros** [comment]
Hi @e-driver1,

Just to understand your architecture, you have a backend that is now running the SDK, and a web-based front that is opening the microphone and streaming the audio to your service?

If that is the case, I would recommend using a `PushAudioInputStream` as it is shown [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_sample.py#L555).

Please let me know if that helps (or if I'm missing something)

**Comment by e-driver1** [comment]
Hi @glecaros,
Your synopsis of my architecture is correct. My issue is, I can never get the microphone working in the web app, as it's trying to use the server's microphone.

Thanks for the pointer. I got the code `PushAudioInsputStream` working (as per the example), with a couple of changes (see below), but it requires the `push_stream_writer` function. 

That function requires that you are opening a wav file, and then transcribes the audio from the wav file. What I'm after is something that streams and transcribes simultaneously, based on my architecture...

Do you know what changes need to be made to this code, so that it would stream from a microphone (based on my architecture)?

This is the speech recognition code I got working that uses the wav file and `PushAudioInsputStream`...
```
os.environ['SPEECH_KEY'] = '[key goes here]'
os.environ['SPEECH_REGION'] = '[region goes here]'

def speech_recognition_push_stream():
    # This example requires environment variables named "SPEECH_KEY" and "SPEECH_REGION"
    speech_config = speechsdk.SpeechConfig(subscription=os.environ.get('SPEECH_KEY'), region=os.environ.get('SPEECH_REGION'))
    speech_config.speech_recognition_language="en-GB"
    
    # setup the audio stream
    stream = speechsdk.audio.PushAudioInputStream()
    audio_config = speechsdk.audio.AudioConfig(stream=stream)

    # instantiate the speech recognizer with push stream input
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)
    recognition_done = threading.Event()

    # Connect callbacks to the events fired by the speech recognizer
    def session_stopped_cb(evt):
        """callback that signals to stop continuous recognition upon receiving an event `evt`"""
        print('SESSION STOPPED: {}'.format(evt))
        recognition_done.set()

    def push_stream_writer(stream):
        # The number of bytes to push per buffer
        n_bytes = 3200
        wav_fh = wave.open("whatstheweatherlike.wav")
        # start pushing data until all data has been read from the file
        try:
            while True:
                frames = wav_fh.readframes(n_bytes // 2)
                print('read {} bytes'.format(len(frames)))
                if not frames:
                    break
                stream.write(frames)
                time.sleep(.1)
        finally:
            wav_fh.close()
            stream.close()  # must be done to signal the end of stream     
    
    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(session_stopped_cb)
    speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))

    # start push stream writer thread
    push_stream_writer_thread = threading.Thread(target=push_stream_writer, args=[stream])
    push_stream_writer_thread.start()

    # start continuous speech recognition
    speech_recognizer.start_continuous_recognition()

    # wait until all input processed
    recognition_done.wait()

    # stop recognition and clean up
    speech_recognizer.stop_continuous_recognition()
    push_stream_writer_thread.join()
    
speech_recognition_push_stream()
```

**Comment by glecaros** [comment]
Hi!
The PushAudioInputStream reads from a wav file just to ilustrate how to use it. In your case you would probably need to:

a) Open the microphone in your browser,
b) Stream the bytes read from it to your back end.
c) In your back end call write in the stream.

I wonder if your scenario would be easier to implement using the JS SDK.
