### ISSUE TITLE
Always not match reason when using CreatePushStream

### ISSUE THREAD

**Issue by elrhomariyounes** [Azure-Samples/cognitive-services-speech-sdk#1740]
**Describe the bug**
Hello, when I'm using the speech sdk to extract a text from a wav file I get a NoMatch reason with the CreatePushStream but when using AudioFromWavFile("Path") I get the expected result. Is it 
**To Reproduce**
1. Create a web api in .NET 7
2. Create a post method with an IFormFile (to send the wave file)
3. The method body as follow:
```csharp
public async Task<Results<Ok<string>, BadRequest>> ExtractTextFromAudio(IFormFile waveFile)
{
    var speechConfig = SpeechConfig.FromSubscription(SpeechKey, "westeurope");
    var languageConfig = AutoDetectSourceLanguageConfig.FromLanguages(new string[] { "en-US", "fr-FR" });
    var reader = new BinaryReader(waveFile.OpenReadStream());
    using var audioInputStream = AudioInputStream.CreatePushStream();
    using var audioConfig = AudioConfig.FromStreamInput(audioInputStream);
    using var recoginzer = new SpeechRecognizer(speechConfig, languageConfig, audioConfig);
    byte[] readBytes;
    reader.BaseStream.Position = 0;
    do
    {
         readBytes = reader.ReadBytes(1024);
          audioInputStream.Write(readBytes, readBytes.Length);
    } while (readBytes.Length > 0);
     var result = await recoginzer.RecognizeOnceAsync();
     switch (result.Reason)
    {
                case ResultReason.NoMatch:
                    Console.WriteLine($"NOMATCH: Speech could not be recognized.");
                    break;
                case ResultReason.Canceled:
                    var cancellation = CancellationDetails.FromResult(result);
                    Console.WriteLine($"CANCELED: Reason={cancellation.Reason}");
                    break;
                case ResultReason.RecognizedSpeech:
                    Console.WriteLine($"RECOGNIZED: Text={result.Text}");
                    break;
                default:
                    break;
            }
    return TypedResults.Ok(result.Text);
}
```

**Expected behavior**
Returning the expected text same behavior when using directly:
```csharp
var audioConfig = AudioConfig.FromWavFileInput(@"C:\Users\Younes\Downloads\Enregistrement.wav");
```

**Version of the Cognitive Services Speech SDK**
1.24.1

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - x64
 - Programming language: C#
 - Browser Chrome

**Files**
[logs.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/9996533/logs.txt)

I converted my wave file to MP4 so I can attach it to the issue
https://user-images.githubusercontent.com/47856026/201506847-a8fb325f-5fcb-4011-a21b-a6624b7d66a8.mp4

**Comment by pankopon** [comment]
Closed as answered and no further updates, please open a new issue if more support is needed.
