### ISSUE TITLE
Question for Speech to Text API v3.0

### ISSUE THREAD

**Issue by Darinzhao** [Azure-Samples/cognitive-services-speech-sdk#1742]
Hi there,

I want to ues "Get Custom Model Endpoint Log" in "Speech to Text API v3.0" to get my specific audio log. But I could not get the logid as the request parameters from my source. Could you tell how can I get the specific audio 's logid that I want .

Thank you.

**Comment by glharper** [comment]
@mahilleb-msft Can you help out with this issue?

**Comment by mahilleb-msft** [comment]
@Darinzhao you can enumerate custom models endpoints logs through [Get Custom Model Endpoint Logs](https://westus.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/operations/GetEndpointLogs), check `.values[].self` on the result.

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
