### ISSUE TITLE
 AttributeError: module 'swagger_client' has no attribute 'CustomSpeechTranscriptionsApi'

### ISSUE THREAD

**Issue by nicholasgcotton** [Azure-Samples/cognitive-services-speech-sdk#1743]
**Describe the bug**
API Error when using/adapting Error from https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/python/python-client/main.py

I get the following error

    File "AzureTest20221114.py", line 141, in transcribe
    api = cris_client.CustomSpeechTranscriptionsApi(api_client=client)
    AttributeError: module 'swagger_client' has no attribute 'CustomSpeechTranscriptionsApi'

which reads (with intro comment):

    # create an instance of the transcription api class
    api = cris_client.CustomSpeechTranscriptionsApi(api_client=client)

**To Reproduce**
1. Make local copy of code from https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/python/python-client/main.py
2. Update, susbscription_key, service_region, name, description, locale and recordings_blob_uri with real values.
3. Run Code. 

**Expected behavior**
Should submit file for transcription.

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using: 
API is 3.0
microsoft.cognitiveservices.speech.cli  is 1.24.1

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - Intel X64
 - Programming language: Python 3.7

**Additional context**
 - Error messages, stack trace, sample code to reproduce the issue, ...
 - Please provide full Speech SDK Log, as per the instructions [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging)? 
 - > Sorry that is not implemented in the example code I have and the link at the URL doesn't have enough information for me to add it myself. 
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by zhouwangzw** [comment]
@nicholasgcotton  The problem looks like that the client library generated by Swagger is not available. How did you generate the client library from Swagger specification? The information on [this page](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python) https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python might help. I am able to run the sample by following the instructions there. 

Please let us know if you still have issues after installing the client library.   
Thanks!

**Comment by nicholasgcotton** [comment]
Hmmm. I followed all the swagger steps but I could have missed something, I will re-do that install and try again, thank you.

**Comment by nicholasgcotton** [comment]
I installed Swagger using the instructions here: [Generate a REST API client library for the Speech-to-text REST API](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/swagger-documentation), which uses a different URL for the Speech Services API. 

The page you linked to says to use: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/cognitiveservices/data-plane/Speech/SpeechToText/stable/v3.0/speechtotext.json

The link generated by the other instructions is: https://canadacentral.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0, which seems to autoforward to https://canadacentral.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/operations/CopyModelToSubscription at which point it hangs.

So I have removed the swagger client (pip uninstall swagger_client) and reinstalled using the newly generated download, and the code is now working.

Thank you for your help!

**Comment by kwongtn** [comment]
As of v3.1, afaik the following APIs are being replaced:
```py
transcription_api = cris_client.CustomSpeechTranscriptionsApi(
    api_client=client
)
webhook_api = cris_client.CustomSpeechWebHooksApi(api_client=client)
```

You'll need to replace with the following (yes these 2 unified into 1 endpoint)
```py
default_api = cris_client.DefaultApi(api_client=client)
```
