### ISSUE TITLE
Returning the channel for each utterance. Python SDK

### ISSUE THREAD

**Issue by wbennison** [Azure-Samples/cognitive-services-speech-sdk#1748]
Hi.

We are currently using the batch transcription API endpoint but in order to use phrase boosting, we are experimenting with continuous_recognition in the Python SDK.

We require channel labels for multi-channel audio or the ability to diarize and return speaker labels for mono audio

In the detailed JSON output from the Python SDK, I can see

```
<azure.cognitiveservices.speech.PropertyCollection object at 0x1241c8f40>
{'Id': '50655b89258b409aa9a4228d795b16dr', 'Text': "hi Emma it's John calling from Your Health hi how are you", 'Offset': 11300000, 'Duration': 46800000, 'Channel': 0}
```

This leads me to believe a channel can be returned, but when transcribing a stereo WAV file (6 mins in length with two distinct speakers on separate channels) everything is returned in channel 0.

Furthermore, there doesn't seem to be any turn-by-turn separation between the utterances.

Just curious if it is even possible with the Python SDK. I'd just like to mirror the functionality of the batch-transcription api endpoint but be able to provide a  phrase list. Our audio is not usually longer than 10 mins.

The properties I currently send to the batch endpoint are as follows, and I separate speakers by the `channel` returned in `recognizedPhrases`
`
'properties' => [
                'diarizationEnabled' => false, // For dual channel this must be disabled
                'wordLevelTimestampsEnabled' => true,
                'displayFormWordLevelTimestampsEnabled' => true,
                'punctuationMode' => 'DictatedAndAutomatic',
                'profanityFilterMode' => 'None',
                'channels' => [
                  0,
                  1,
                ],
  ],`

Or if not, does anybody know when/if the phrase list will be supported on the batch endpoint?

The only way I have got around this so far is to transcribe each channel independently but I understand this is double the work/price. Also, doesn't solve the issue for Mono audio.

Let me know

Thanks

**Comment by jhakulin** [comment]
@wbennison In Speech SDK 1.24.0 we have released preview of speaker diarization functionality which allows you to separate the speakers using mono audio. See below example about the transcription of the preview feature (Guest_0, Guest_1 are the separated speakers in the conversation). If you are interested to try this preview functionality out with mono audio, please send the request to diarizationrequest@microsoft.com.

Session started event.
TRANSCRIBED: Text=Good morning, Steve. UserId=Unidentified
TRANSCRIBED: Text=Good morning, Katie. UserId=Unidentified
TRANSCRIBED: Text=Have you heard about the new conversation transcription capability? UserId=Guest_0
TRANSCRIBED: Text=No, tell me more. UserId=Guest_1
TRANSCRIBED: Text=It's the new feature that transcribes our discussion and lets us know who said what. UserId=Guest_0
TRANSCRIBED: Text=That sounds interesting. UserId=Guest_1
TRANSCRIBED: Text=I'm going to give this a try. UserId=Guest_1
CANCELED: Reason=EndOfStream

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.

**Comment by wbennison** [comment]
Thanks, @pankopon, Am I right that we can't get channel labels for stereo audio?. 

I'll check back in with a new issue when I come back to working with the SDK.

Thanks again
