### ISSUE TITLE
C#: Cannot get DetailedSpeechRecognitionResult  even though setting OutputFormat to Detailed

### ISSUE THREAD

**Issue by EberhardSchneider** [Azure-Samples/cognitive-services-speech-sdk#175]
**Describe the bug**
I'm using continous recognition to recognize speech in audio files which are possibly longer than 15sec and cannot be processed from the REST API.
I'm working from the samples here: https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_recognition_samples.cs  
Despite setting the **OutputFormat** Property of SpeechConfig  to **Detailed**, I'm getting only the normal **SpeechRecognitionResult** in the EventHandler, not the **DetailedSpeechRecognitionResult**.

**To Reproduce**
1. Build speechConfig with SpeechConfig.FromSubscription().
2. **Set speechConfig.OutputFormat to OutputFormat.Detailed**
3. In EventHandler **Recognizing** the SpeechRecognitionEventArgs do not contain the DetailedSpeechRecognitionResult.

**Expected behavior**
The recognizing EventHandler should give the detailed results.

**Version of the Cognitive Services Speech SDK**
1.3.1

**Platform, Operating System, and Programming Language**
Azure Function v2 / .NET CORE 2.2.200

**Additional context**
The Audio Data comes from a WAV File  PCM unsigned 16kHz sample rate connected over a PushAudioInputStream.
The Recognizer eventhandler is always called with ResultReason RecognizingSpeech, never with ResultReason RecognizedSpeech.

**Comment by zhouwangzw** [comment]
Thanks for using Speech SDK and Service! 
The detailed output format is only available for Recognized result, but not for Recognizing result. Please subscribe to Recognized event. To get detailed output from a Recognized event, please call e.Result.Best(), as shown in the sample[ here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L66).
