### ISSUE TITLE
SouthCentralUs - Batch - Unable to get PaginatedFiles

### ISSUE THREAD

**Issue by kleindev** [Azure-Samples/cognitive-services-speech-sdk#1750]
Starting this week, we are having challenges getting PaginatedFiles from the REST api.  Is there a possibility something changed on the REST API?

Example:  https://southcentralus.api.cognitive.microsoft.com/speechtotext/v3.0/transcriptions/dba7389b-207b-4c0f-ab5a-710f0861a57e/files

**Comment by andreasjl** [comment]
@kleindev There should be no change on existing API versions. In our logs I see some requests for that URL that look successful. What is exactly the problem that you have? Can you also share the "apim-request-id" header that you get in the response?

**Comment by pankopon** [comment]
Closed since no further info provided. Please open a new issue if more support is needed.
