### ISSUE TITLE
Word Timing Offset is incorrect for direct speech to text translation call. 

### ISSUE THREAD

**Issue by rahulshivajipawar** [Azure-Samples/cognitive-services-speech-sdk#1752]
**Describe the bug**
When I use _speechsdk.translation.TranslationRecognizer_ to get direct speech to text translations, the word offset information for words in the transcribed text is incorrect (compared to directly using the _speechsdk.SpeechRecognizer_).

Example:

Response using _speechsdk.translation.TranslationRecognizer_ (a subset of the overall response is shown)

{'Duration': 141100000, 'Offset': 109800000, 'RecognitionStatus': 'Success', 'Text': 'I worked on speech and audio processing problems during my PhD at Georgia Tech and at Motorola Solutions, and I used to work as a software engineer in a post purchase e Commerce company called Narwar.', 'Confidence': 0.598035, 'Lexical': 'i worked on speech and audio processing problems during my phd at georgia tech and at motorola solutions and i used to work as a software engineer in a post purchase e commerce company called narwar', 'ITN': 'i worked on speech and audio processing problems during my phd at georgia tech and at motorola solutions and i used to work as a software engineer in a post purchase e commerce company called narwar', 'MaskedITN': 'i worked on speech and audio processing problems during my phd at georgia tech and at motorola solutions and i used to work as a software engineer in a post purchase e commerce company called narwar', 'Translation': {'TranslationStatus': 'Success', 'Translations': [{'Language': 'en', 'Text': 'I worked on speech and audio processing problems during my PhD at Georgia Tech and at Motorola Solutions, and I used to work as a software engineer in a post purchase e Commerce company called Narwar.'}]}, 'Words': [{**'Word': 'i', 'Offset': 6200000**, 'Duration': 6900000, 'Confidence': 0.3725279, 'AccuracyScore': 0.0}, {'Word': 'worked', 'Offset': 13400000, 'Duration': 3200000, 'Confidence': 0.54491293, 'AccuracyScore': 0.0}, {'Word': 'on', 'Offset': 16700000, 'Duration': 1200000, 'Confidence': 0.9149399, 'AccuracyScore': 0.0}, {'Word': 'speech', 'Offset': 18000000, 'Duration': 3100000, 'Confidence': 0.6218531, 'AccuracyScore': 0.0}, {'Word': 'and', 'Offset': 21200000, 'Duration': 2700000, 'Confidence': 0.7832383, 'AccuracyScore': 0.0}, {'Word': 'audio', 'Offset': 25600000, 'Duration': 3500000, 'Confidence': 0.5368143, 'AccuracyScore': 0.0}, {'Word': 'processing', 'Offset': 29200000, 'Duration': 4500000, 'Confidence': 0.93425226, 'AccuracyScore': 0.0}, {'Word': 'problems', 'Offset': 33800000, 'Duration': 6500000, 'Confidence': 0.8820754, 'AccuracyScore': 0.0}, {'Word': 'during', 'Offset': 40600000, 'Duration': 4100000, 'Confidence': 0.78244245, 'AccuracyScore': 0.0}, {'Word': 'my', 'Offset': 44800000, 'Duration': 1500000, 'Confidence': 0.9261277, 'AccuracyScore': 0.0}, {'Word': 'phd', 'Offset': 46400000, 'Duration': 4700000, 'Confidence': 0.27190363, 'AccuracyScore': 0.0}, {'Word': 'at', 'Offset': 51200000, 'Duration': 2300000, 'Confidence': 0.8236138, 'AccuracyScore': 0.0}, {'Word': 'georgia', 'Offset': 56400000, 'Duration': 3700000, 'Confidence': 0.046423048, 'AccuracyScore': 0.0}, {'Word': 'tech', 'Offset': 60200000, 'Duration': 3100000, 'Confidence': 0.9126314, 'AccuracyScore': 0.0}, {'Word': 'and', 'Offset': 63600000, 'Duration': 6600000, 'Confidence': 0.59419465, 'AccuracyScore': 0.0}, {'Word': 'at', 'Offset': 76600000, 'Duration': 2500000, 'Confidence': 0.60976774, 'AccuracyScore': 0.0}, {'Word': 'motorola', 'Offset': 79200000, 'Duration': 4500000, 'Confidence': 0.057977468, 'AccuracyScore': 0.0}, {'Word': 'solutions', 'Offset': 83800000, 'Duration': 6300000, 'Confidence': 0.8802925, 'AccuracyScore': 0.0}, {'Word': 'and', 'Offset': 94000000, 'Duration': 4700000, 'Confidence': 0.6089023, 'AccuracyScore': 0.0}, {'Word': 'i', 'Offset': 98800000, 'Duration': 1100000, 'Confidence': 0.71828043, 'AccuracyScore': 0.0}, {'Word': 'used', 'Offset': 100000000, 'Duration': 2000000, 'Confidence': 0.8415009, 'AccuracyScore': 0.0}, {'Word': 'to', 'Offset': 102100000, 'Duration': 800000, 'Confidence': 0.8812361, 'AccuracyScore': 0.0}, {'Word': 'work', 'Offset': 103000000, 'Duration': 2200000, 'Confidence': 0.7820248, 'AccuracyScore': 0.0}, {'Word': 'as', 'Offset': 105300000, 'Duration': 1200000, 'Confidence': 0.8572376, 'AccuracyScore': 0.0}, {'Word': 'a', 'Offset': 106600000, 'Duration': 400000, 'Confidence': 0.88075125, 'AccuracyScore': 0.0}, {'Word': 'software', 'Offset': 107100000, 'Duration': 4000000, 'Confidence': 0.90271163, 'AccuracyScore': 0.0}, {'Word': 'engineer', 'Offset': 111200000, 'Duration': 5100000, 'Confidence': 0.92961735, 'AccuracyScore': 0.0}, {'Word': 'in', 'Offset': 116400000, 'Duration': 1700000, 'Confidence': 0.8717247, 'AccuracyScore': 0.0}, {'Word': 'a', 'Offset': 118200000, 'Duration': 1900000, 'Confidence': 0.33725405, 'AccuracyScore': 0.0}, {'Word': 'post', 'Offset': 120200000, 'Duration': 3100000, 'Confidence': 0.3101881, 'AccuracyScore': 0.0}, {'Word': 'purchase', 'Offset': 123400000, 'Duration': 5800000, 'Confidence': 0.57012534, 'AccuracyScore': 0.0}, {'Word': 'e', 'Offset': 129500000, 'Duration': 2000000, 'Confidence': 0.16259286, 'AccuracyScore': 0.0}, {'Word': 'commerce', 'Offset': 131600000, 'Duration': 3300000, 'Confidence': 0.2378439, 'AccuracyScore': 0.0}, {'Word': 'company', 'Offset': 135000000, 'Duration': 4500000, 'Confidence': 0.7907505, 'AccuracyScore': 0.0}, {'Word': 'called', 'Offset': 139600000, 'Duration': 2700000, 'Confidence': 0.36236432, 'AccuracyScore': 0.0}, {'Word': 'narwar', 'Offset': 142400000, 'Duration': 4900000, 'Confidence': 0.042615473, 'AccuracyScore': 0.0}]} 

Response using _speechsdk.SpeechRecognizer_

{'Id': '6478eaddb7454bb4ab0d24a04384dd88', 'RecognitionStatus': 'Success', 'Offset': 109800000, 'Duration': 141100000, 'Channel': 0, 'DisplayText': 'I worked on speech and audio processing problems during my PhD at Georgia Tech and at Motorola Solutions, and I used to work as a software engineer in a post purchase e Commerce company called Narwar.', 'NBest': [{'Confidence': 0.598035, 'Lexical': 'i worked on speech and audio processing problems during my phd at georgia tech and at motorola solutions and i used to work as a software engineer in a post purchase e commerce company called narwar', 'ITN': 'i worked on speech and audio processing problems during my phd at georgia tech and at motorola solutions and i used to work as a software engineer in a post purchase e commerce company called narwar', 'MaskedITN': 'i worked on speech and audio processing problems during my phd at georgia tech and at motorola solutions and i used to work as a software engineer in a post purchase e commerce company called narwar', 'Display': 'I worked on speech and audio processing problems during my PhD at Georgia Tech and at Motorola Solutions, and I used to work as a software engineer in a post purchase e Commerce company called Narwar.', 'Words': [{**'Word': 'i', 'Offset': 109800000**, 'Duration': 6900000, 'Confidence': 0.3725279}, {'Word': 'worked', 'Offset': 117000000, 'Duration': 3200000, 'Confidence': 0.54491293}, {'Word': 'on', 'Offset': 120300000, 'Duration': 1200000, 'Confidence': 0.9149399}, {'Word': 'speech', 'Offset': 121600000, 'Duration': 3100000, 'Confidence': 0.6218531}, {'Word': 'and', 'Offset': 124800000, 'Duration': 2700000, 'Confidence': 0.7832383}, {'Word': 'audio', 'Offset': 129200000, 'Duration': 3500000, 'Confidence': 0.5368143}, {'Word': 'processing', 'Offset': 132800000, 'Duration': 4500000, 'Confidence': 0.93425226}, {'Word': 'problems', 'Offset': 137400000, 'Duration': 6500000, 'Confidence': 0.8820754}, {'Word': 'during', 'Offset': 144200000, 'Duration': 4100000, 'Confidence': 0.78244245}, {'Word': 'my', 'Offset': 148400000, 'Duration': 1500000, 'Confidence': 0.9261277}, {'Word': 'phd', 'Offset': 150000000, 'Duration': 4700000, 'Confidence': 0.27190363}, {'Word': 'at', 'Offset': 154800000, 'Duration': 2300000, 'Confidence': 0.8236138}, {'Word': 'georgia', 'Offset': 160000000, 'Duration': 3700000, 'Confidence': 0.046423048}, {'Word': 'tech', 'Offset': 163800000, 'Duration': 3100000, 'Confidence': 0.9126314}, {'Word': 'and', 'Offset': 167200000, 'Duration': 6600000, 'Confidence': 0.59419465}, {'Word': 'at', 'Offset': 180200000, 'Duration': 2500000, 'Confidence': 0.60976774}, {'Word': 'motorola', 'Offset': 182800000, 'Duration': 4500000, 'Confidence': 0.057977468}, {'Word': 'solutions', 'Offset': 187400000, 'Duration': 6300000, 'Confidence': 0.8802925}, {'Word': 'and', 'Offset': 197600000, 'Duration': 4700000, 'Confidence': 0.6089023}, {'Word': 'i', 'Offset': 202400000, 'Duration': 1100000, 'Confidence': 0.71828043}, {'Word': 'used', 'Offset': 203600000, 'Duration': 2000000, 'Confidence': 0.8415009}, {'Word': 'to', 'Offset': 205700000, 'Duration': 800000, 'Confidence': 0.8812361}, {'Word': 'work', 'Offset': 206600000, 'Duration': 2200000, 'Confidence': 0.7820248}, {'Word': 'as', 'Offset': 208900000, 'Duration': 1200000, 'Confidence': 0.8572376}, {'Word': 'a', 'Offset': 210200000, 'Duration': 400000, 'Confidence': 0.88075125}, {'Word': 'software', 'Offset': 210700000, 'Duration': 4000000, 'Confidence': 0.90271163}, {'Word': 'engineer', 'Offset': 214800000, 'Duration': 5100000, 'Confidence': 0.92961735}, {'Word': 'in', 'Offset': 220000000, 'Duration': 1700000, 'Confidence': 0.8717247}, {'Word': 'a', 'Offset': 221800000, 'Duration': 1900000, 'Confidence': 0.33725405}, {'Word': 'post', 'Offset': 223800000, 'Duration': 3100000, 'Confidence': 0.3101881}, {'Word': 'purchase', 'Offset': 227000000, 'Duration': 5800000, 'Confidence': 0.57012534}, {'Word': 'e', 'Offset': 233100000, 'Duration': 2000000, 'Confidence': 0.16259286}, {'Word': 'commerce', 'Offset': 235200000, 'Duration': 3300000, 'Confidence': 0.2378439}, {'Word': 'company', 'Offset': 238600000, 'Duration': 4500000, 'Confidence': 0.7907505}, {'Word': 'called', 'Offset': 243200000, 'Duration': 2700000, 'Confidence': 0.36236432}, {'Word': 'narwar', 'Offset': 246000000, 'Duration': 4900000, 'Confidence': 0.042615473}]}

Note: The times cannot be relative in the translation case as the offset for the last word is greater than the duration of the segment.  

**Expected behavior**

The offset times should be identical. 

**Version of the Cognitive Services Speech SDK**

1.23.0

**Platform, Operating System, and Programming Language**
 - OS: Mac OS and Linux
 - Programming Language: Python

**Comment by pankopon** [comment]
It seems there is at least some discrepancy between regions. I attached a Python test script and a wav file for comparison.
[test_offsets.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/10080478/test_offsets.zip)

Using Speech SDK 1.24.2, with **northeurope** and **westus** regions the output is
```
### Recognize ###
SESSION STARTED: SessionEventArgs(session_id=2d752661c13646f9b45995827597cd3d)
RECOGNIZED: ¿Cuál es la distancia entre la Tierra y la luna?
 Word: cuál         Offset: 1000000    Duration: 2300000
 Word: es           Offset: 3400000    Duration: 1300000
 Word: la           Offset: 4800000    Duration: 900000
 Word: distancia    Offset: 5800000    Duration: 4800000
 Word: entre        Offset: 10700000   Duration: 2400000
 Word: la           Offset: 13200000   Duration: 1100000
 Word: tierra       Offset: 14400000   Duration: 3500000
 Word: y            Offset: 18000000   Duration: 700000
 Word: la           Offset: 18800000   Duration: 1100000
 Word: luna         Offset: 20000000   Duration: 3300000
RECOGNIZED: ¿Cuál es la montaña más alta de la Tierra?
 Word: cuál         Offset: 32100000   Duration: 2500000
 Word: es           Offset: 34700000   Duration: 1100000
 Word: la           Offset: 35900000   Duration: 1100000
 Word: montaña      Offset: 37100000   Duration: 4900000
 Word: más          Offset: 42100000   Duration: 2500000
 Word: alta         Offset: 44700000   Duration: 2300000
 Word: de           Offset: 47100000   Duration: 1100000
 Word: la           Offset: 48300000   Duration: 1100000
 Word: tierra       Offset: 49500000   Duration: 3400000
CANCELED: CancellationReason.EndOfStream
SESSION STOPPED: SessionEventArgs(session_id=2d752661c13646f9b45995827597cd3d)

### Translate ###
SESSION STARTED: SessionEventArgs(session_id=76a6e489dd0046319c65a3868151fc34)
RECOGNIZED: ¿Cuál es la distancia entre la Tierra y la luna?
TRANSLATED: What is the distance between the Earth and the moon?
 Word: cuál         Offset: 1000000    Duration: 2300000    (Adj. offset: 1000000   )
 Word: es           Offset: 3400000    Duration: 1300000    (Adj. offset: 3400000   )
 Word: la           Offset: 4800000    Duration: 900000     (Adj. offset: 4800000   )
 Word: distancia    Offset: 5800000    Duration: 4800000    (Adj. offset: 5800000   )
 Word: entre        Offset: 10700000   Duration: 2400000    (Adj. offset: 10700000  )
 Word: la           Offset: 13200000   Duration: 1100000    (Adj. offset: 13200000  )
 Word: tierra       Offset: 14400000   Duration: 3500000    (Adj. offset: 14400000  )
 Word: y            Offset: 18000000   Duration: 700000     (Adj. offset: 18000000  )
 Word: la           Offset: 18800000   Duration: 1100000    (Adj. offset: 18800000  )
 Word: luna         Offset: 20000000   Duration: 3300000    (Adj. offset: 20000000  )
RECOGNIZED: ¿Cuál es la montaña más alta de la Tierra?
TRANSLATED: What is the highest mountain on Earth?
 Word: cuál         Offset: 8800000    Duration: 2500000    (Adj. offset: 32100000  )
 Word: es           Offset: 11400000   Duration: 1100000    (Adj. offset: 34700000  )
 Word: la           Offset: 12600000   Duration: 1100000    (Adj. offset: 35900000  )
 Word: montaña      Offset: 13800000   Duration: 4900000    (Adj. offset: 37100000  )
 Word: más          Offset: 18800000   Duration: 2500000    (Adj. offset: 42100000  )
 Word: alta         Offset: 21400000   Duration: 2300000    (Adj. offset: 44700000  )
 Word: de           Offset: 23800000   Duration: 1100000    (Adj. offset: 47100000  )
 Word: la           Offset: 25000000   Duration: 1100000    (Adj. offset: 48300000  )
 Word: tierra       Offset: 26200000   Duration: 3400000    (Adj. offset: 49500000  )
NO MATCH: NoMatchReason.InitialSilenceTimeout
CANCELED: CancellationReason.EndOfStream
SESSION STOPPED: SessionEventArgs(session_id=76a6e489dd0046319c65a3868151fc34)
```
So it seems that in translation the base offset of recognized words is reset between results, and in order to match it with plain speech recognition you would need to adjust word offsets after the first translation result accordingly (like done above with "Adj. offset").

**However**, at least with **westcentralus** region the word offsets behave like in normal speech recognition and the values are correct by default. @eldakms Is this a known issue with translation? The word offsets in translation results are different between service regions.

**Comment by pankopon** [comment]
@mahilleb-msft Based on a chat with eldakms, you might know about the situation? With **northeurope** and **westus** regions, the base offset of transcribed (recognized) words is reset between translation results as shown above, while with **westcentralus** region offsets are as expected (same as "adjusted" in the example). Is this a known difference between regions or what could be the reason?

@rahulshivajipawar Until this is resolved, a workaround would be to check if the offset of the first word in result N is less than the offset+duration of the last word in result N-1, and in that case add a cumulative base offset (ref. how the adjusted offset is calculated in the example script I attached earlier).

**Comment by rahulshivajipawar** [comment]
@pankopon I have a workaround for now. A slightly different question: Is there a way to get word timing information for all the punctuated/final words that appear in the result of the transcription call? Currently, we only have timing information for raw words which don't necessarily map 1:1 to punctuated words/final words.

**Comment by pankopon** [comment]
@rahulshivajipawar Unfortunately there is no such option, the timing information is only available for words in a lexical form i.e. before any transformations (capitalization, punctuation, numbers, abbreviations...). The JSON result does include the whole sentence in a lexical form (the 'Lexical' field) if that would help with mapping.

**Comment by rahulshivajipawar** [comment]
> @rahulshivajipawar Unfortunately there is no such option, the timing information is only available for words in a lexical form i.e. before any transformations (capitalization, punctuation, numbers, abbreviations...). The JSON result does include the whole sentence in a lexical form (the 'Lexical' field) if that would help with mapping.

Thanks! Yes, some sort of fuzzy mapping could be possible, though it looks like the transformations are a combination of deterministic methods and ML models.

**Comment by pankopon** [comment]
Internal work item ref. 5420189.
