### ISSUE TITLE
SDK 1.24.2 on Xamarin Forms android is breaking

### ISSUE THREAD

**Issue by pasha-o** [Azure-Samples/cognitive-services-speech-sdk#1753]
**Describe the bug**
 @jhakulin: updating to the latest SDK version from **1.24.1** to  **1.24.2** in visual studio 2022 version 17.4.1 and running it on a xamarin form android emulator is resulting in the following error, whenever you call SpeakTextAsync function. calling the function will result in getting the following result set: 

**error code: Microsoft.CognitiveServices.Speech.CancellationErrorCode.ConnectionFailure
error details: Connection failed (no connection to the remote host). Internal error: 1. Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED
wss://westus2.tts.speech.microsoft.com/cognitiveservices/websocket/v1
X-ConnectionId: 0cf1adfd502042c5a0e18969868486d2 USP state: 2. Received audio size: 0 bytes.

reason: Microsoft.CognitiveServices.Speech.CancellationReason.Error**

**To Reproduce**
1. use a xamarin android app
2. update to latest SDK version
3. run the app and try to use the function
4. the result is canceled

**Expected behavior**
it should synthesize with no issue

**Version of the Cognitive Services Speech SDK**
SDK version 1.24.2

**Platform, Operating System, and Programming Language**
Android emulator - SDK 13
Xamarin Forms 5.0.0.2515

**Comment by pasha-o** [comment]
hi @jhakulin , @pankopon , @dragav , @trrwilson is anyone looking at this?

**Comment by jhakulin** [comment]
@pasha-o Thanks for checking, are you still seeing the failure with connection? There has been recently problems with the Azure service and not related to 1.24.2. In case you see the problem still, could you please confirm you do not have any problems with 1.24.1 release? I am asking because in 1.24.2, there should not be any changes impacting to connection problem you reported.

**Comment by pasha-o** [comment]
hi @pankopon I checked and the issue is resolved - so this was the azure service issue? how do we escalate that to them to ensure it doesn't happen?

**Comment by pankopon** [comment]
Hi, there was an Azure service outage which is now resolved. You can get regular updates on the service status through Azure Service Health, please see https://azure.microsoft.com/get-started/azure-portal/service-health/

**Comment by pankopon** [comment]
Closed as resolved, please open a new issue if more support is needed.
