### ISSUE TITLE
Text-to-Speech Audio Duration (privAudioDuration)

### ISSUE THREAD

**Issue by fantinuoli** [Azure-Samples/cognitive-services-speech-sdk#1755]
How is the value `privAudioDuration` returned by a call of the text-to-speech API computed? Is it a calculation based on number of characters and voice features, or it is measured by the API for any emission? We find inconsistencies in the emitted value, and are trying to figure out the mechanisms behind it.

**Comment by yulin-li** [comment]
The value is calculated by service. It should be accurate for raw/riff formats. For compressed audio formats, extra silence might be added for frame padding.

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
