### ISSUE TITLE
iOS Sample Code Bug

### ISSUE THREAD

**Issue by danhalliday** [Azure-Samples/cognitive-services-speech-sdk#1759]
There’s a pretty serious bug in one of the iOS speech samples, at the following line:

```swift
let pcmBuffer = AVAudioPCMBuffer(pcmFormat: recordingFormat!, frameCapacity: AVAudioFrameCount(bufferSize))
```

- https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/swift/ios/from-external-microphone/helloworld/helloworld/ViewController.swift#L84

What’s happening here is you’re creating a new `AVAudioPCMBuffer` to hold audio in the converted format, but initialising it with a `frameCapacity` equivalent to the size of the original buffer from the microphone. This won’t work — the microphone buffer will be sampled (probably) at 48kHz, and your output buffer will be 16kHz. They’re different sizes.

This is a really sticky bug to track down, because the behaviour of `AVAudioConverter` is to fill the output buffer repeatedly until full. So what’s actually happening in this sample code is you’re sending a series of buffers off for recognition that contain little loops and glitches. You’ll get some speech recognised, but on closer inspection the error rate is really high.

The other issue with this sample code is that you don’t actually set the buffer’s `frameLength`, which is also required. The following is more like what you really want.

```swift
let outputBufferCapacity = AVAudioFrameCount(buffer.duration * recordingFormat.sampleRate)

guard let outputBuffer = AVAudioPCMBuffer(pcmFormat: recordingFormat, frameCapacity: outputBufferCapacity) else {
    log.error("Failed to create new audio buffer")
    return
}

outputBuffer.frameLength = outputBufferCapacity
```

With `buffer.duration` calculated as you wish. Here’s what I have in my most recent project.

```swift
extension AVAudioPCMBuffer {
    var duration: TimeInterval {
        format.sampleRate > 0 ? .init(frameLength) / format.sampleRate : 0
    }
}
```

Hope this helps.

**Comment by jhakulin** [comment]
@danhalliday Thanks a lot for letting us know. I will check the changes needed for the sample.

**Comment by jhakulin** [comment]
Internal workitem ref: 3690580, will be fixed in the following Speech SDK update.

**Comment by dargilco** [comment]
@danhalliday Speech SDK 1.26 was released with a fix related to the above issue. See [release notes](https://learn.microsoft.com/azure/cognitive-services/speech-service/releasenotes?tabs=speech-sdk).
