### ISSUE TITLE
onCanceled event missing

### ISSUE THREAD

**Issue by madeInLagny** [Azure-Samples/cognitive-services-speech-sdk#1766]
[In js browser code sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/48447ecc0643f4e04a9287456d29a1306a79f21b/samples/js/browser/public/index.html#L695), e.reason is used in the onCanceled method. 

The issue is that e is not defined in the method args and raises an error.

Should 'e' be 'cancellationEventArgs'?

**Comment by pankopon** [comment]
Hi, thanks for noticing! You are right, `e` should be indeed `cancellationEventArgs`. We have a pull request https://github.com/Azure-Samples/cognitive-services-speech-sdk/pull/1770 to fix it.
