### ISSUE TITLE
Continuous recognition not re-starting after stopping programatically 

### ISSUE THREAD

**Issue by dhavalsoni2001** [Azure-Samples/cognitive-services-speech-sdk#1767]
**Describe the bug**

When first time using startContinuousRecognitionAsync Safari prompts correctly for microphone access, I have a 'microphone active' display next to the url, and speech gets recognized. 

As I am integrated GPT3 I am using stopContinuousRecognitionAsync to stop it until GPT 3 respond and after that I start again using startContinuousRecognitionAsync to listen the user but at that time I do not get a microphone access prompt, and there is no 'microphone active' display next to the URL.

We are using SpeechSDK.TranslationRecognizer's recognized method for the capturing the user input but it's never go into that function second time as microphone is not active.

**Expected behavior**
Once I stop using stopContinuousRecognitionAsync and then I again start it using  startContinuousRecognitionAsync it should show the microphone active again and go to recognized method again.

**Version of the Cognitive Services Speech SDK**
I am  using https://aka.ms/csspeech/jsbrowserpackageraw to load the latest SDK.

**Platform, Operating System, and Programming Language**
 - OS: iOS 16.1
 - Hardware - iPhone 13
 - Programming language: Javascript
 - Browser Chrome, Safari

**Comment by glharper** [comment]
@dhavalsoni2001 See https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/599
