### ISSUE TITLE
Why Session stopped automatically when using speech_recognizer.start_continuous_recognition() by adding phrase?(API by Python)

### ISSUE THREAD

**Issue by rakuwa7** [Azure-Samples/cognitive-services-speech-sdk#1768]
**Describe the bug**
Hi,

When I use api written by python, I found that when I use 'speech_recognizer.start_continuous_recognition()' while adding PhraseListGrammar to recognize an audio file, the session would stop automatically somehow. Therefore, the result text I got is only a part of the full audio. Meanwhile, without adding PhraseListGrammar, the program can run normally that I can obtain a full result text recognized.

Is there any restriction on the length of the audio when utilizing 'speechsdk.PhraseListGrammar.from_recognizer(speech_recognizer)' ??
Or is there any wrong with my programming code?

### **To Reproduce**
1. use 'speech_recognizer.start_continuous_recognition()' while adding PhraseListGrammar to recognize an audio file.
2. length of audio file: 1hour or even 5min.
3. Amount of phrase lists: about 100.

### **Expected behavior**
Session stopped automatically and the result text I got is only a part of the full audio. 

### **Version of the Cognitive Services Speech SDK**
azure-cognitiveservices-speech 1.24.2
### 
**Platform, Operating System, and Programming Language**
 - OS: Windows 10 Pro 22H2
 - Hardware - x64, Intel(R) Core(TM) i3-7130U CPU @ 2.70GHz   2.71 GHz, 4.00 GB
 - Programming language: Python 3.7
 - Browser : Chrome, Microsoft Edge

### 
**Additional context**

 **- Error messages**

>  CANCELED SpeechRecognitionCanceledEventArgs(session_id=2f867f5c0fb74603aad28a01eb210c8b, result=SpeechRecognitionResult(result_id=ee79cee59c4a4c2cb5bcb6f242ef4c1d, text="", reason=ResultReason.Canceled))
> CLOSING on SpeechRecognitionCanceledEventArgs(session_id=2f867f5c0fb74603aad28a01eb210c8b, result=SpeechRecognitionResult(result_id=ee79cee59c4a4c2cb5bcb6f242ef4c1d, text="", reason=ResultReason.Canceled))
> Speech Recognition canceled: CancellationReason.Error
> Error details: Due to service inactivity, the client buffer exceeded maximum size. Resetting the buffer. SessionId: 2f867f5c0fb74603aad28a01eb210c8b
> Did you set the speech resource key and region values?
> SESSION STOPPED SessionEventArgs(session_id=2f867f5c0fb74603aad28a01eb210c8b)
> CLOSING on SessionEventArgs(session_id=2f867f5c0fb74603aad28a01eb210c8b)

**-sample code**
```
def speech_recognize_continuous_from_file_addphrase(audiofile, phraselist):

        # <SpeechRecognitionWithFile>
        audio_filename = audiofile
        audio_input = speechsdk.audio.AudioConfig(filename=audio_filename)
        speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)
        # Ask for detailed recognition result
        speech_config.output_format = speechsdk.OutputFormat.Detailed
        speech_config.set_property(speechsdk.PropertyId.Speech_LogFilename, "f'output/azure_kk20220428_dic_test_log.txt")
        # Creates a recognizer with the given settings
        speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_input, language="ja-JP")

        #Adding phrase list
        phrase_list_grammar = speechsdk.PhraseListGrammar.from_recognizer(speech_recognizer)
        for phrase in phraselist:
            phrase_list_grammar.addPhrase(phrase)

        # Starts speech recognition, and returns after text is recognized.
        done = False
        text =[]
        print("Recognizing...")
        def recognized(evt: speechsdk.SessionEventArgs):
#             result.append(evt.result.text)
            if evt.result.reason == speechsdk.ResultReason.RecognizedSpeech:
                print("Recognized: {}".format(evt.result.text))
                text.append(evt.result.text)
            elif evt.result.reason == speechsdk.ResultReason.NoMatch:
                print("No speech could be recognized: {}".format(evt.result.no_match_details))
            elif result.reason == speechsdk.ResultReason.Canceled:
                cancellation_details = result.cancellation_details
                print("Speech Recognition canceled: {}".format(cancellation_details.reason))
                if cancellation_details.reason == speechsdk.CancellationReason.Error:
                    print("Error details: {}".format(cancellation_details.error_details))
                    print("Did you set the speech resource key and region values?")
            
            return text

#         def start(evt):
#             print('SESSION STARTED: {}'.format(evt))

        def stop(evt: speechsdk.SessionEventArgs):
            print('CLOSING on {}'.format(evt))
            if evt.result.reason == speechsdk.ResultReason.Canceled:
                cancellation_details = evt.result.cancellation_details
                print("Speech Recognition canceled: {}".format(cancellation_details.reason))
                if cancellation_details.reason == speechsdk.CancellationReason.Error:
                    print("Error details: {}".format(cancellation_details.error_details))
                    print("Did you set the speech resource key and region values?")
            nonlocal done
            done = True

        # Connect callbacks to the events fired by the speech recognizer
#         speech_recognizer.recognizing.connect(lambda evt)
        speech_recognizer.recognized.connect(recognized)
        speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
        speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
        speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))  
#         speech_recognizer.session_started.connect(start)
        speech_recognizer.session_stopped.connect(stop)
        speech_recognizer.canceled.connect(stop)

        # Start continuous speech recognition
        try:
            speech_recognizer.start_continuous_recognition()
            while not done:
                time.sleep(.5)
                
            speech_recognizer.stop_continuous_recognition()
            
        except KeyboardInterrupt:
            print("bye.")
            speech_recognizer.recognized.disconnect_all()
            speech_recognizer.session_started.disconnect_all()
            speech_recognizer.session_stopped.disconnect_all()
        

        
        return text
        # </SpeechRecognitionWithFile>
```

 - session_id=2f867f5c0fb74603aad28a01eb210c8b
 - time:recently.(Sorry that I didn't remember the specific time).Timezone:UTC/GMT +9 hours
 - Any other additional information
This problem never been fixed even I try to use shorter audio file and smaller phrase lists.Btw, the language is Japanese.
What's worst is that, even the webpage of realtime speech to text happened this kind of situation. When I try to use webpage to obtain the full text, the conversion of speech-to-text just would't complete the work when adding 100 words phraselist.

For more information about azure resource(speech service):
resource group: shimizu-test
status: active
location: Japan East
Subscription ID: [hidden]
API type: Speech
Pricing tier: Standard
Endpoint: https://japaneast.api.cognitive.microsoft.com/sts/v1.0/issuetoken
I want to evaluate the result of azure's speech to text with adding phrase that how much would it impove comparing with no phrase added.
That's why I cling to using realtime speech-to-text that it can add phrase.

Looking forward to your helping, thank you!

**Comment by pankopon** [comment]
Hi, based on the error message and Japanese input, this appears similar to a known service issue with phrase lists currently in effect, and there's a fix in progress. The latest status is that if tests look good then the fix may be deployed next week.

Just to confirm, can you please attach a full Speech SDK log (preferably in a zip) as well? Does it not work even with a phrase list of only 10 words, for example?

**Comment by pankopon** [comment]
Related service incidents ref. 348902917, 346402706, 352885667. @mahilleb-msft FYI.

**Comment by pankopon** [comment]
Based on the status of service incidents listed, fixes have been deployed on the service side and the issue is now resolved. Please open a new issue if more support is needed.
