### ISSUE TITLE
centos7测试环境环境配置里的SpeechSDK-Linux-<version> 是什么，在哪里下载的？

### ISSUE THREAD

**Issue by hereiam2322** [Azure-Samples/cognitive-services-speech-sdk#1769]
https://learn.microsoft.com/zh-cn/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7
客户这边测试环境是centos7的，安装上面文档链接安装依赖，截图里面最后一步的环境配置里的SpeechSDK-Linux-<version> 是什么，在哪里下载的？文档上没看到
<img width="338" alt="image" src="https://user-images.githubusercontent.com/119578862/205007597-6554f140-9f2f-48dc-818d-d05a7503a7fe.png">

centos7环境报这个错，是依赖没安装好的原因吗？
Caused by: java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V
        at com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Native Method)
        at com.microsoft.cognitiveservices.speech.SpeechConfig.<clinit>(Unknown Source)

**Comment by pankopon** [comment]
Hi,

The part about `SpeechSDK-Linux-<version>` is "*For C++ development only*" as noted in comments. Are you using C++ or Java (or something else)?

For **C++**, you need to download the Speech SDK `tar.gz` package from https://aka.ms/csspeech/linuxbinary. The current latest such package is `SpeechSDK-Linux-1.24.2.tar.gz` so when you extract it, there will be a folder `SpeechSDK-Linux-1.24.2` (i.e. `<version>` becomes `1.24.2`, and the full path prefix `/path/to...` depends on where this folder is).

For **Java**, you need the Speech SDK `jar` package. First ensure that the environment is genuine CentOS (or RHEL) 7:
```
# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
```
Make sure the latest updates are installed (`sudo yum updateinfo`, `sudo yum update`).

Download Speech SDK Java samples from https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/java/jre/console and test that they work in your environment:
```
# git clone https://github.com/Azure-Samples/cognitive-services-speech-sdk
# cd cognitive-services-speech-sdk/samples/java/jre/console/
# sed -i 's/1\.24\.0/1.24.2/g' pom.xml
```
Try, for example, the case with wav file input; edit the source file `src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java` and go to [`continuousRecognitionWithFileAsync()`](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/5b2aa44055b529ec3bd7c961efbe6a151f93ee5e/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java#L257) in that file and replace "*Your...*" strings with your subscription key, service region, and some wav file path. Then build and run (on the command-line):
```
# mvn --version
Apache Maven 3.8.6
Maven home: /opt/apache-maven-3.8.6
Java version: 1.8.0_352, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.352.b08-2.el7_9.x86_64/jre

# mvn clean package

# mvn dependency:tree
...
[INFO] SpeechSDKDemo:SpeechSDKDemo:jar:0.0.1-SNAPSHOT
[INFO] +- com.microsoft.cognitiveservices.speech:client-sdk:jar:1.24.2:compile

# export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH
# java -jar ./target/SpeechSDKDemo-0.0.1-SNAPSHOT-jar-with-dependencies.jar
```
and in case `continuousRecognitionWithFileAsync()` was edited, select and run
```
 5. Speech continuous recognition using events with file.
```
Note that with current CentOS 7 x64 installations, `/etc/ld.so.conf.d/local-x86_64.conf` contains `/usr/local/lib64` as a library search path by default. In that case you don't actually need to set LD_LIBRARY_PATH.

If the Java problem still persists, try one or more of the following:
1. Clear the local Maven repository, then rebuild the app/samples.
   ```
   # rm -rf "$HOME/.m2"
   ```
1. If the Linux distribution in use is not genuine CentOS/RHEL 7 but is based on it (and must be fully compatible), set a special environment variable to force using CentOS 7 specific Speech SDK binaries from the `jar` package.
   ```
   # export SpeechSDK_UseCentos7Binaries=true
   ```
1. One CentOS 7 user recently had an odd issue that required adding `/usr/local/bin` to PATH (although it should be already there by default), even for Java.
   ```
   # export PATH=/usr/local/bin:$PATH
   ```
Please let us know (in English, if possible) if suggestions above help.

**Comment by shenzudan** [comment]
我也遇到这个问题，我用的是1.23.0

LD_DEBUG 发现GLIBCXX版本不对
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/17032816/205368610-9515039b-891d-4602-8127-8e5bd4627fcd.png">

**Comment by pankopon** [comment]
@shenzudan Please write in English on this forum.

[Instructions to install Speech SDK](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/setup-platform?tabs=linux%2Crhel-centos%2Cdotnet%2Cjre%2Cmaven%2Cnodejs%2Cmac%2Cpypi&pivots=programming-language-cpp) on Linux, specifically RHEL/CentOS 7/8, include a note

> On RHEL/CentOS 7, follow the instructions on [how to configure RHEL/CentOS 7 for Speech SDK](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7).

and the linked page provides information on how to build GCC (7.5.0) and C/C++ runtimes that are needed in order to use current Speech SDK releases on CentOS 7. This is how the correct version looks like:
```
# strings /usr/local/lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
...
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
