### ISSUE TITLE
Profanity Filter is buggy

### ISSUE THREAD

**Issue by Marcophono2** [Azure-Samples/cognitive-services-speech-sdk#177]
As far as I understand the profanity filter still cannot be deactivated. That may be a political correctness depending decision but if the filter has the same iq that this political influence it should be adjustable and removable as fast as possible. If I let translate a text from language A to language B such a filter can never make any sense if it filters out a translated word in the target language but not in the source language.

Example:

"Ich esse Nudeln". (german for "I eat Noodles")
  translate to spanish ->
"Como p****."

**Comment by wolfma61** [comment]
we will make it easier to activate / deactivate the profanity feature in one of the next releases. That will allow you to turn it on/off through a property.

Wolfgang

**Comment by aarora-3** [comment]
when will this change be implemented?
