### ISSUE TITLE
Microsoft.Cognitiveservices.Speech returns DllNotFoundException when on iOS16 device and dotnet MAUI

### ISSUE THREAD

**Issue by sakata-3as** [Azure-Samples/cognitive-services-speech-sdk#1771]
Hello,

**Describe the bug**
My app has Keyword recognition function using Microsoft.Cognitiveservices.Speech.
It works fine with Android.
But if deployed onto iOS device, DLLNOTFOUNDEXCEPTION occurs.
iOS device is iPhone X running latest version of the iOS16.

**To Reproduce**

1. Open the attached project in Visual Studio 2022 64bit Version 17.5.0 Preview 1.0
2. Run the project on iOS device
3. Click on "Click me" button
4. Allow Microphone access
5. Re-run the project
6. Click on "Click me" button
7. Say "Hey Computer" using active microphone

**Expected behavior**
Debug.Writeline says "Keyword successfully recognized" instead of the exception above.

**Version of the Cognitive Services Speech SDK**
1.24.2 (current)

**Platform, Operating System, and Programming Language**

- Windows 10 x64
- C#
- iPhone X (iOS 16.1.1)

**Additional context**
[sample project here](https://drive.google.com/file/d/1j7xM6Hiw6lqfdlf51EQHrfoanRAw88L-/view?usp=sharing)
[originally reported thread](https://learn.microsoft.com/en-us/answers/questions/1111223/microsoftcognitiveservicesspeech-returns-dllnotfou-1.html?childToView=1111697#comment-1111697) on learn.microsoft.com

Best regards, 
Shoichi Sakata

**Comment by pankopon** [comment]
Hi, MAUI support on iOS will be added in the Speech SDK 1.25.0 release early next year. See https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1649.
