### ISSUE TITLE
Getting access to the processed audio stream

### ISSUE THREAD

**Issue by cperno** [Azure-Samples/cognitive-services-speech-sdk#1773]
Hello
I can see in these APIs that you allow audio processing like echo cancellation to cleanup the audio delivered to your speech to text step.  

Is there any way to get access to the processed audio stream myself?  I may want to save it to a file or feed it into my own speech to text.

The closest thing I see is with keyword detection, `AudioDataStream.FromResult` you can get the processed audio stream starting at a point in time.

**Comment by dargilco** [comment]
@cperno  thank you for opening this issue. Unfortunately, at the moment there is no way to get processed audio (the audio sent to the cloud for recognition). This has been asked for by other customers and it is a work item in our backlog. If there is any other way we can help you, please don’t hesitate to open a new issue.
