### ISSUE TITLE
iOS - react-native - Invalid WAV header in file, data block was not found.

### ISSUE THREAD

**Issue by baluanand-adoltech** [Azure-Samples/cognitive-services-speech-sdk#1774]
Hi,

Trying to upload the WAV files recorded( with https://www.npmjs.com/package/react-native-audio-record ) to the express-server and feeding that to speech-sdk. The setup successfully works for the recordings from an android device, the same fails with the following error **Invalid WAV header in file, data block was not found**.  while trying from an iPhone. When I checked the file it seems to be identical to the android file(16 bit, 16 Khz, mono). Any idea on this? Please suggest on how to fix this issue.

Thanks in advance.

**Comment by dargilco** [comment]
@baluanand-adoltech thank you for opening this issue! I'm from the Speech SDK team and will try to help you. Can you please provide the following:
1. An example WAV file that came from Android Device
2. An example WAV file that came from iPhone Device
3. An SDK log file taken while you try to process the WAV file from the iPhone Device and get the mentioned error. [See here](https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging) on how to enable SDK logging.

**Comment by glharper** [comment]
@baluanand-adoltech To enable logging in the JS SDK (v1.24.1), use the following two lines:
sdk.Diagnostics.SetLoggingLevel(sdk.LogLevel.Debug);
sdk.Diagnostics.SetLogOutputPath("YOUR_PATH_HERE");

**Comment by baluanand-adoltech** [comment]
> @baluanand-adoltech I run our public quickstart sample [shown here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/javascript/node/from-file). I run it the first time pointing to the Android WAV file. Then again to the iOS WAV file. This was done using latest JS Speech SDK package. In both cases it worked fine, as per the results shown below. Please try to run this sample from your side and let me know what you find. If you are using an older SDK version, it may be that by switching to latest version it will be fixed.
> 
> ```
> d:\GitHub\cognitive-services-speech-sdk\quickstart\javascript\node\from-file>node index.js
> Now recognizing from: C:\Users\dcohen\Downloads\git-hub-issue\16703977983481670397788627androidRecord.wav
> SpeechRecognitionResult {
>   privResultId: 'E19539E9472C453C9D189CEE21854C8E',
>   privReason: 3,
>   privText: 'My voice is my passport. Verify me.',
>   privDuration: 23800000,
>   privOffset: 1500000,
>   privLanguage: undefined,
>   privLanguageDetectionConfidence: undefined,
>   privErrorDetails: undefined,
>   privJson: '{"Id":"bef2927d923d45348a58d7047995d0e6","RecognitionStatus":"Success","DisplayText":"My voice is my passport. Verify me.","Offset":1500000,"Duration":23800000,"Channel":0}',
>   privProperties: PropertyCollection {
>     privKeys: [ 'SpeechServiceResponse_JsonResult' ],
>     privValues: [
>       '{"Id":"bef2927d923d45348a58d7047995d0e6","RecognitionStatus":"Success","DisplayText":"My voice is my passport. Verify me.","Offset":1500000,"Duration":23800000,"Channel":0}'
>     ]
>   },
>   privSpeakerId: undefined
> }
> 
> d:\GitHub\cognitive-services-speech-sdk\quickstart\javascript\node\from-file>node index.js
> Now recognizing from: C:\Users\dcohen\Downloads\git-hub-issue\16704078453461670407835883iosRecord.wav
> SpeechRecognitionResult {
>   privResultId: 'CACB123AC2A24F5EA664800A7EF5AC2F',
>   privReason: 3,
>   privText: 'My voice is my passport. Verify me.',
>   privDuration: 21300000,
>   privOffset: 3900000,
>   privLanguage: undefined,
>   privLanguageDetectionConfidence: undefined,
>   privErrorDetails: undefined,
>   privJson: '{"Id":"65c6e7983add415a98633a667ba91a6d","RecognitionStatus":"Success","DisplayText":"My voice is my passport. Verify me.","Offset":3900000,"Duration":21300000,"Channel":0}',
>   privProperties: PropertyCollection {
>     privKeys: [ 'SpeechServiceResponse_JsonResult' ],
>     privValues: [
>       '{"Id":"65c6e7983add415a98633a667ba91a6d","RecognitionStatus":"Success","DisplayText":"My voice is my passport. Verify me.","Offset":3900000,"Duration":21300000,"Channel":0}'
>     ]
>   },
>   privSpeakerId: undefined
> }
> ```

@dargilco Thanks for testing with the wav files. The [example](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/javascript/node/from-file) you highlighted seems to be using [AudioConfig.fromStreamInput](https://learn.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/audioconfig?view=azure-node-latest#microsoft-cognitiveservices-speech-sdk-audioconfig-fromstreaminput) but I'm using [AudioConfig.fromWavFileInput](https://learn.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/audioconfig?view=azure-node-latest#microsoft-cognitiveservices-speech-sdk-audioconfig-fromwavfileinput). Is it possible this is happening because of this? If you could please elaborate why using StreamInput when we have a function for WavFileInput? Thanks in advance.

**Comment by glharper** [comment]
@baluanand-adoltech There is no applicable difference between those two methods for your use case. fromStreamInput is provided for raw stream input (from another process, for example) or [mediaStream](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream/MediaStream) input. The default format used by fromStreamInput is 16KHz, 16-bit PCM (wav) audio.

Allow us to ask again, which version of the JS SDK are you using? (You should be able to see in the package.json for your project.)

**Comment by dargilco** [comment]
@baluanand-adoltech I modified the public quickstart such that this is called (instead of using a push stream):
```
var audioConfig = sdk.AudioConfig.fromWavFileInput(fs.readFileSync(filename));
```
I can confirm that this works fine with the Android WAV file. When I use the iOS WAV file, I get the error you mentioned (see below). I will consult with @glharper on the next steps.
 
Darren

```
Now recognizing from: C:/Users/dcohen/Downloads/git-hub-issue/16703977983481670397788627androidRecord.wav
d:\GitHub\cognitive-services-speech-sdk\quickstart\javascript\node\from-file\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common.browser\FileAudioSource.js:208
            processHeader(h.buffer.slice(h.byteOffset, h.byteOffset + h.byteLength));
                                   ^

TypeError: Cannot read properties of undefined (reading 'slice')
    at FileAudioSource.readHeader (d:\GitHub\cognitive-services-speech-sdk\quickstart\javascript\node\from-file\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common.browser\FileAudioSource.js:208:36)
    at new FileAudioSource (d:\GitHub\cognitive-services-speech-sdk\quickstart\javascript\node\from-file\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common.browser\FileAudioSource.js:59:44)
    at AudioConfig.fromWavFileInput (d:\GitHub\cognitive-services-speech-sdk\quickstart\javascript\node\from-file\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\sdk\Audio\AudioConfig.js:67:36)
    at d:\GitHub\cognitive-services-speech-sdk\quickstart\javascript\node\from-file\index.js:38:37
    at Object.<anonymous> (d:\GitHub\cognitive-services-speech-sdk\quickstart\javascript\node\from-file\index.js:63:2)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

Node.js v18.12.1
```

**Comment by dargilco** [comment]
@baluanand-adoltech per the above Glenn submitted a work-around that should unblock you. This is expected to be released toward the end of January. You can always follow the instructions here https://github.com/microsoft/cognitive-services-speech-sdk-js and build the SDK package yourself (with the fix). There may be a better fix to the WAV parser later on, as I noticed that we do not properly identify and skip unrecognized WAV header chunks in the WAV file. Your iOS WAV file has the Apple "FLRR" chunk before the "data" chunk, and it needs to be skipped without having to hard-code a max WAV header size as we now do. Thanks again for reporting this!
