### ISSUE TITLE
Real Time Conversation Transcriber

### ISSUE THREAD

**Issue by ankurdhuriya** [Azure-Samples/cognitive-services-speech-sdk#1778]
I was following this sample code [how-to-use-conversation-transcription](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-conversation-transcription?pivots=programming-language-python) 

I tried it on ~8 min audio file **[SR:16000, bits_per_sample:16, channels:8]** It was converted using [ffmpeg](https://ffmpeg.org/)
For voice registration I have used audio sample of two speakers 40 seconds each (monochannel, sr:16 kHz, 16 bits). Code runs without any error, but it doesn't identify speakers from voice signature.

I want to know **how voice registration and speech identification works**. And what is the ideal format of audio data (when i checked audio file using scipy, _**2 channels out of 8 has data in it, rest are zero it means they are just silence**_). 

Another query, how can I transform any audio into (**_7 channel audio + 1 silenced channel_** format) [microphone-geometry](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk-microphone#microphone-geometry) 

**Version of the Cognitive Services Speech SDK**
azure-cognitiveservices-speech~=1.24.2

**Platform, Operating System, and Programming Language**

- OS : macOS Ventura 13.1
- Programming Language : Python 3.9.15

**Comment by ankurdhuriya** [comment]
Also I parsed the transcribed events received to display text. I am getting output like this

```
Guest_0 -> 0.51sec to 20.06sec -> Platform on which she has tried to salvage her premierships and every time she faced a difficult question is like, well I do the energy package but and and more than that in the Commons and the the labour policy. So Keir Starmer's policy was the willful tax on big energy companies to support bills up to 8.

Guest_0 -> 20.14sec to 36.94sec -> For 2023 and she used this to use this as an attack line on saying I've got a two year plan. What about you? So he's just pulled the rug from under her on that as well. The massive reversals I think are a scale.

Guest_0 -> 37.98sec to 49.13sec -> Of the predicting, the government sees itself in in terms of the markets it will, looking at how they're reacting. I think for politically for trust.

Guest_0 -> 49.84sec to 54.17sec -> He's now just undone, another plank, the last plank if you like.

Guest_0 -> 54.87sec to 75.37sec -> Of her entire premiership and Ed, what has been the market reaction so far? So call it looks like I'll bring some charts up in a moment, but it's that that guilty of we were talking about a moment ago. That keep barometer for how it's a very like this, more or less steady. It went down a little bit.

Guest_1 -> 76.01sec to 96.44sec -> When a tiny bit, so being that's reassuring. But as we were discussing just before we, we heard from the the the Chancellor there he that was the interesting thing. He went further than EU turn. He scrapped that income tax, cut that Richard could plant that that really hadn't been speculated on. You know, until this moment.

Guest_1 -> 96.56sec to 100.00sec -> And the price guarantee the facts originally for two years.

Guest_1 -> 54.87sec to 75.37sec -> Of her entire premiership and Ed, what has been the market reaction so far? So call it looks like I'll bring some charts up in a moment, but it's that that guilty of we were talking about a moment ago. That keep barometer for how it's a very like this, more or less steady. It went down a little bit.

```

here 54.87sec to 75.37sec is revisited and it corrected speaker both events have different result_id

**Comment by jhakulin** [comment]
@ankurdhuriya Thanks for the report. In 1.24.0 release, we have released support for single channel (mono 16kHz) input for conversation transcription. You can participate to preview by sending request to diarizationrequest@microsoft.com.

8 channel audio requires special construction in order to work with conversation transcription service and where our documentation is not sufficient. I would recommend using single channel feature.

**Comment by ankurdhuriya** [comment]
> @ankurdhuriya Thanks for the report. In 1.24.0 release, we have released support for single channel (mono 16kHz) input for conversation transcription. You can participate to preview by sending request to [diarizationrequest@microsoft.com](mailto:diarizationrequest@microsoft.com).
> 
> 8 channel audio requires special construction in order to work with conversation transcription service and where our documentation is not sufficient. I would recommend using single channel feature.

Okay, can you answer about the issue of transcriber revisiting older segment and in this time it's predicting correct speaker

**Comment by jhakulin** [comment]
@ankurdhuriya What is the question? Seems sample has following property set
```
speech_config.set_property_by_name("DifferentiateGuestSpeakers", "true")
```
Which is documented here: https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/conversation-transcription. When that property is set voice signature based speaker identification is not active, but speakers are differentiated.

**Comment by ankurdhuriya** [comment]
> 

No this property is not affecting it. When "DifferentiateGuestSpeakers" is set to false . It turns every speakerID to Unidentified

**Comment by jhakulin** [comment]
Could you please clarify your question?

**Comment by jhakulin** [comment]
@ankurdhuriya
1. The problem is very probably due to reason 8 channel audio input is not constructed correctly. I recommend participating to single channel preview and use single channel for the capture.
2. Would it be possible to share the output when you run it using single channel file ?

**Comment by jhakulin** [comment]
@ankurdhuriya Closing the issue as no response back. Please let us know if there are still issues and provide required information and we can reopen the issue.
