### ISSUE TITLE
Can I use ConversationTranscriber from mic

### ISSUE THREAD

**Issue by ankurdhuriya** [Azure-Samples/cognitive-services-speech-sdk#1779]
I am following this sample code [conversation transcriber](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-conversation-transcription?pivots=programming-language-python) . Is there a way to feed audio from mic in this

**Comment by dargilco** [comment]
I'm assuming you are using Python. If you do not specify an audio_config input when creating the ConversationTranscriber object, the default mic on your system will be used.

**Comment by ankurdhuriya** [comment]
> 

I defined audio config input as use_default_microphone=True , but then I'm getting error it doesn't work for mono channel
