### ISSUE TITLE
IntentRecognizer not showing all intent probabilities in JSON response.

### ISSUE THREAD

**Issue by JamesEarle** [Azure-Samples/cognitive-services-speech-sdk#178]
Speech Service SDK (1.3.0) using .NET Core v2.1.104

When "Include all predicted intent scores" is switched on in the LUIS portal, I still don't receive all intent scores in my output from the SDK, only the top intent.

**To Reproduce**
Create a LUIS app and turn on "Include all predicted intent scores" once trained.
Use the `IntentRecognizer` class to capture audio and send to LUIS.
Only the top intent is included in the response.

**Expected behavior**
Probabilities for all intents show.

**Version of the Cognitive Services Speech SDK**
v1.3.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - x64
 - Programming language: C#
 - Browser N/A, using console app.

I'm accessing the JSON response using `e.Result.Properties.GetProperty(PropertyId.LanguageUnderstandingServiceResponse_JsonResult)` where `e` is `IntentRecognitionEventArgs`. The JSON includes `topScoringIntent: { ... }` but not any other intents.

**Comment by chlandsi** [comment]
Thank you for the report. This is currently not possible, but we are working on it and this feature will be part of an upcoming release.
