### ISSUE TITLE
Microsoft.CognitiveServices.Speech SDK create issue in Blazor WebAssesmbly

### ISSUE THREAD

**Issue by kashifasif** [Azure-Samples/cognitive-services-speech-sdk#1780]
I am trying to use the Speech to Text feature using the Microsoft.CognitiveServices.Speech SDK in my Blazor WebAssembly Project that is based on .NET 6, but I am continuously encountering the following error. 

As mentioned in error issue is with Target CPU but for testing i have changed to x64 and x86 but it didn't work for me. 
So clould you please tell me whats wrong with it or Blazor support Microsoft.CognitiveServices.Speech SDK?

**Error When application running**

`blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type initializer for 'Microsoft.CognitiveServices.Speech.Internal.SpeechConfig' threw an exception.
System.TypeInitializationException: The type initializer for 'Microsoft.CognitiveServices.Speech.Internal.SpeechConfig' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Microsoft.CognitiveServices.Speech.Internal.DotNetFrameworkAnyCpuSupport' threw an exception.
 ---> System.DllNotFoundException: kernel32.dll
   at Microsoft.CognitiveServices.Speech.Internal.DotNetFrameworkAnyCpuSupport..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.CognitiveServices.Speech.Internal.SpeechConfig..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.CognitiveServices.Speech.SpeechConfig.FromSubscription(String subscriptionKey, String region)
   at BlazorApp1.Pages.Index.OnInitializedAsync() in C:\Users\kasif\source\repos\BlazorApp1\BlazorApp1\Pages\Index.razor:line 10
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()`

**Comment by pankopon** [comment]
Hi, unfortunately WASM is not supported, see https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/930. We have a work item about it on the backlog but no ETA.
