### ISSUE TITLE
could you make more detailed examples on AudioOutputStream and PullAudioOutputStream?

### ISSUE THREAD

**Issue by reothues** [Azure-Samples/cognitive-services-speech-sdk#1786]
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/f1b5a0eae885104b74ed8d8de98e8570aab3ab8d/quickstart/javascript/node/text-to-speech/index.js#L53

I suppose this demo here means adding the file path to the fourth arg

AudioOutputStream | PushAudioOutputStreamCallback | PathLike

**Comment by yulin-li** [comment]
The file output could be set at synthesizer level, which is shown in the demo codes

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/javascript/node/text-to-speech/index.js#L23

**Comment by yulin-li** [comment]
And you can refer to [this test case](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/tests/SpeechSynthesisTests.ts#L401) to see the usage of saving file of each synthesis request.
