### ISSUE TITLE
Wrong output language Azure Text-To-Speech

### ISSUE THREAD

**Issue by Spixz** [Azure-Samples/cognitive-services-speech-sdk#1787]
Hello everyone,

I use the javascript speech SDK of azure and I modified the [speechSynthesisLanguage](https://learn.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/speechconfig?view=azure-node-latest#microsoft-cognitiveservices-speech-sdk-speechconfig-speechsynthesislanguage) property to change the output language but it does not work. **The output language is still english**. I followed the documentation and use the demo code available on [their repo](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/javascript/node/text-to-speech/index.js).

```
(function() {
  // <code>
  "use strict";
  
  // pull in the required packages.
  var sdk = require("microsoft-cognitiveservices-speech-sdk");
  var readline = require("readline");
  const { exec } = require("child_process");
  
  // replace with your own subscription key,
  // service region (e.g., "westus"), and
  // the name of the file you save the synthesized audio.
  var subscriptionKey = "xxx";
  var serviceRegion = "francecentral"; // e.g., "westus"
  var filename = "test1.wav";

  // we are done with the setup

  // now create the audio-config pointing to our stream and
  // the speech config specifying the language.
  var audioConfig = sdk.AudioConfig.fromAudioFileOutput(filename);
  var speechConfig = sdk.SpeechConfig.fromSubscription(subscriptionKey, serviceRegion);

  speechConfig.setProperty('speechSynthesisLanguage', 'fr-FR')
  speechConfig.setProperty('speechSynthesisVoiceName', 'fr-FR-AlainNeural')
  console.log(speechConfig)
  
  //create the speech synthesizer.
  var synthesizer = new sdk.SpeechSynthesizer(speechConfig, audioConfig);


  var rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  rl.question("Test à saisir :\n", function (text) {
    rl.close();
    // start the synthesizer and wait for a result.
    synthesizer.speakTextAsync(text,
        function (result) {
      if (result.reason === sdk.ResultReason.SynthesizingAudioCompleted) {
        console.log("synthesis finished.");
      } else {
        console.error("Speech synthesis canceled, " + result.errorDetails +
            "\nDid you update the subscription info?");
      }
      synthesizer.close();
      synthesizer = undefined;
    },
        function (err) {
      console.trace("err - " + err);
      synthesizer.close();
      synthesizer = undefined;
    });
    console.log("Now synthesizing to: " + filename);
    exec(`vlc ${filename} vlc://quit`);
  });
  // </code>
  
}());
```

The output language is corretly set to fr-FR [according to the doc](https://learn.microsoft.com/en-us/azure/cognitive-services/Speech-Service/language-support?tabs=stt-tts).

```
console.log(speechConfig.getProperty('speechSynthesisLanguage')) //fr-FR
```

I tried to change the language by german or use the [setServiceProperty(string, string, ServicePropertyChannel)](https://learn.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/speechconfig?view=azure-node-latest#microsoft-cognitiveservices-speech-sdk-speechconfig-setserviceproperty) method but it didn't work.

Do you have a solution? Thank you

**Comment by brandom-msft** [comment]
Hi @Spixz - can you try setting the property directly from the config class? e.g.
`speechConfig.speechSynthesisLanguage  = 'fr-FR'`

**Comment by Spixz** [comment]
> Hi @Spixz - can you try setting the property directly from the config class? e.g. `speechConfig.speechSynthesisLanguage = 'fr-FR'`

Thanks for you answer, it was the correct solution. In the documentation the properties are called `speechSynthesisLanguage` and ` speechSynthesisVoiceName` but in fact, if you want to modify them with the `setProperty() method`, their names are not the same. They are respectively `SpeechServiceConnection_SynthLanguage`  and `SpeechServiceConnection_SynthVoice`. In fact, `speechConfig.speechSynthesisLanguage = "en-FR"` is equal to `speechConfig.setProperty('SpeechServiceConnection_SynthLanguage', 'en-FR')`. Thanks
