### ISSUE TITLE
Definition of Confidence Score used for Cognitive Speech Transcription Service

### ISSUE THREAD

**Issue by mert-kurttutan** [Azure-Samples/cognitive-services-speech-sdk#1789]
Hi,
I am using confidence score for my project.

I am curious about the exact formula used for transcription. Is it possible for you to provide for definition of score used in the service?
More particularly, I want to take a sensible combination of multiple results from continuous speech so that it gives confidence score for the entire transcription.

**Comment by brandom-msft** [comment]
Hi @mert-kurttutan - we don't provide the formula for the confidence score. For the most part, the confidence score is "relativistic" in that it can vary depending on many factors over time (like service updates, input changes, etc). The score is provided as a means for users to evaluate results as they occur and within the same environment of other results.

As for your particular scenario, it sounds like you want to combine multiple score results - can you share more about the end goal with this? You can certainly combine them for your own evaluations but I'm not sure what it is you hope/expect that final number to determine/tell you.

**Comment by mert-kurttutan** [comment]
Thanks for the reply. It is used to translate long audio files. So, I preferred continuous translation. But, of course it gives multiple confidence scores for parts of the same audio file. But, what I want is the confidence score for the entire audio file (not parts of it).

**Comment by pankopon** [comment]
@mert-kurttutan Unfortunately, the details are not public for the time being.

Closing the item as answered. Please open a new issue if more support is needed.
