### ISSUE TITLE
Timeout trying to fetch resolutions from npm

### ISSUE THREAD

**Issue by snippet** [Azure-Samples/cognitive-services-speech-sdk#1791]
Unable to install on Node v18.12.1

LOG
0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@8.19.2
2 info using node@v18.12.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/Users/bob/Projects/flashnews_beta/.npmrc Completed in 0ms
10 timing config:load:project Completed in 5ms
11 timing config:load:file:/Users/bob/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 14ms
19 timing npm:load:configload Completed in 14ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm i microsoft-cognitiveservices-speech-sdk
23 verbose argv "i" "microsoft-cognitiveservices-speech-sdk"
24 timing npm:load:setTitle Completed in 20ms
25 timing config:load:flatten Completed in 3ms
26 timing npm:load:display Completed in 5ms
27 verbose logfile logs-max:10 dir:/Users/bob/.npm/_logs
28 verbose logfile /Users/bob/.npm/_logs/2023-01-04T01_15_15_906Z-debug-0.log
29 timing npm:load:logFile Completed in 4ms
30 timing npm:load:timers Completed in 1ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 46ms
33 timing arborist:ctor Completed in 1ms
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 timing idealTree:init Completed in 95ms
37 timing idealTree:userRequests Completed in 2ms
38 silly idealTree buildDeps
39 silly fetch manifest microsoft-cognitiveservices-speech-sdk@*
40 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
41 http fetch GET 200 https://registry.npmjs.org/microsoft-cognitiveservices-speech-sdk 118ms (cache hit)
42 silly placeDep ROOT microsoft-cognitiveservices-speech-sdk@1.24.1 OK for: flashnews_beta@1.0.0 want: *
43 silly fetch manifest asn1.js-rfc2560@^5.0.1
44 silly fetch manifest asn1.js-rfc5280@^3.0.0
45 silly fetch manifest async-disk-cache@^2.1.0
46 silly fetch manifest bent@^7.3.12
47 silly fetch manifest https-proxy-agent@^4.0.0
48 silly fetch manifest simple-lru-cache@0.0.2
49 silly fetch manifest uuid@^8.3.0
50 http fetch GET 200 https://registry.npmjs.org/uuid 37ms (cache hit)
51 http fetch GET 200 https://registry.npmjs.org/async-disk-cache 47ms (cache hit)
52 http fetch GET 200 https://registry.npmjs.org/simple-lru-cache 63ms (cache hit)
53 http fetch GET 200 https://registry.npmjs.org/asn1.js-rfc2560 66ms (cache hit)
54 http fetch GET 200 https://registry.npmjs.org/https-proxy-agent 66ms (cache hit)
55 http fetch GET 200 https://registry.npmjs.org/asn1.js-rfc5280 71ms (cache hit)
56 http fetch GET 200 https://registry.npmjs.org/bent 74ms (cache hit)
57 timing idealTree:#root Completed in 203ms
58 silly fetch manifest asn1.js@^5.0.0
59 http fetch GET 200 https://registry.npmjs.org/asn1.js 27ms (cache hit)
60 silly placeDep ROOT asn1.js-rfc2560@5.0.1 OK for: microsoft-cognitiveservices-speech-sdk@1.24.1 want: ^5.0.1
61 silly placeDep ROOT asn1.js@5.4.1 OK for: asn1.js-rfc2560@5.0.1 want: ^5.0.0
62 silly placeDep ROOT asn1.js-rfc5280@3.0.0 OK for: microsoft-cognitiveservices-speech-sdk@1.24.1 want: ^3.0.0
63 silly placeDep ROOT async-disk-cache@2.1.0 OK for: microsoft-cognitiveservices-speech-sdk@1.24.1 want: ^2.1.0
64 silly placeDep ROOT bent@7.3.12 OK for: microsoft-cognitiveservices-speech-sdk@1.24.1 want: ^7.3.12
65 silly placeDep node_modules/microsoft-cognitiveservices-speech-sdk https-proxy-agent@4.0.0 OK for: microsoft-cognitiveservices-speech-sdk@1.24.1 want: ^4.0.0
66 silly placeDep ROOT simple-lru-cache@0.0.2 OK for: microsoft-cognitiveservices-speech-sdk@1.24.1 want: 0.0.2
67 silly placeDep ROOT uuid@8.3.2 OK for: microsoft-cognitiveservices-speech-sdk@1.24.1 want: ^8.3.0
68 silly fetch manifest bn.js@^4.0.0
69 silly fetch manifest minimalistic-assert@^1.0.0
70 silly fetch manifest safer-buffer@^2.1.0
71 silly fetch manifest heimdalljs@^0.2.3
72 silly fetch manifest istextorbinary@^2.5.1
73 silly fetch manifest mkdirp@^0.5.0
74 silly fetch manifest rsvp@^4.8.5
75 silly fetch manifest username-sync@^1.0.2
76 silly fetch manifest bytesish@^0.4.1
77 silly fetch manifest caseless@~0.12.0
78 silly fetch manifest is-stream@^2.0.0
79 silly fetch manifest agent-base@5
80 http fetch GET 200 https://registry.npmjs.org/minimalistic-assert 44ms (cache hit)
81 http fetch GET 200 https://registry.npmjs.org/bn.js 52ms (cache hit)
82 http fetch GET 200 https://registry.npmjs.org/istextorbinary 57ms (cache hit)
83 http fetch GET 200 https://registry.npmjs.org/caseless 68ms (cache hit)
84 http fetch GET 200 https://registry.npmjs.org/heimdalljs 75ms (cache hit)
85 http fetch GET 200 https://registry.npmjs.org/safer-buffer 76ms (cache hit)
86 http fetch GET 200 https://registry.npmjs.org/username-sync 75ms (cache hit)
87 http fetch GET 200 https://registry.npmjs.org/rsvp 75ms (cache hit)
88 http fetch GET 200 https://registry.npmjs.org/is-stream 77ms (cache hit)
89 http fetch GET 200 https://registry.npmjs.org/agent-base 77ms (cache hit)
90 http fetch GET 200 https://registry.npmjs.org/mkdirp 81ms (cache hit)
91 http fetch GET 200 https://registry.npmjs.org/bytesish 81ms (cache hit)
92 timing idealTree:node_modules/microsoft-cognitiveservices-speech-sdk Completed in 127ms
93 silly placeDep ROOT bn.js@4.12.0 OK for: asn1.js@5.4.1 want: ^4.0.0
94 silly placeDep ROOT minimalistic-assert@1.0.1 OK for: asn1.js@5.4.1 want: ^1.0.0
95 silly placeDep ROOT safer-buffer@2.1.2 OK for: asn1.js@5.4.1 want: ^2.1.0
96 timing idealTree:node_modules/asn1.js Completed in 5ms
97 timing idealTree:node_modules/asn1.js-rfc2560 Completed in 0ms
98 timing idealTree:node_modules/asn1.js-rfc5280 Completed in 0ms
99 silly placeDep ROOT heimdalljs@0.2.6 OK for: async-disk-cache@2.1.0 want: ^0.2.3
100 silly placeDep ROOT istextorbinary@2.6.0 OK for: async-disk-cache@2.1.0 want: ^2.5.1
101 silly placeDep ROOT mkdirp@0.5.6 OK for: async-disk-cache@2.1.0 want: ^0.5.0
102 silly placeDep ROOT rsvp@4.8.5 OK for: async-disk-cache@2.1.0 want: ^4.8.5
103 silly placeDep ROOT username-sync@1.0.3 OK for: async-disk-cache@2.1.0 want: ^1.0.2
104 silly fetch manifest rsvp@~3.2.1
105 silly fetch manifest binaryextensions@^2.1.2
106 silly fetch manifest editions@^2.2.0
107 silly fetch manifest textextensions@^2.5.0
108 http fetch GET 200 https://registry.npmjs.org/textextensions 31ms (cache hit)
109 http fetch GET 200 https://registry.npmjs.org/binaryextensions 41ms (cache hit)
110 http fetch GET 200 https://registry.npmjs.org/editions 47ms (cache hit)
111 timing idealTree:node_modules/async-disk-cache Completed in 59ms
112 silly placeDep ROOT bytesish@0.4.4 OK for: bent@7.3.12 want: ^0.4.1
113 silly placeDep ROOT caseless@0.12.0 OK for: bent@7.3.12 want: ~0.12.0
114 silly placeDep ROOT is-stream@2.0.1 OK for: bent@7.3.12 want: ^2.0.0
115 timing idealTree:node_modules/bent Completed in 5ms
116 timing idealTree:node_modules/bn.js Completed in 0ms
117 timing idealTree:node_modules/bytesish Completed in 0ms
118 timing idealTree:node_modules/caseless Completed in 0ms
119 silly placeDep node_modules/heimdalljs rsvp@3.2.1 OK for: heimdalljs@0.2.6 want: ~3.2.1
120 timing idealTree:node_modules/heimdalljs Completed in 2ms
121 timing idealTree:node_modules/is-stream Completed in 0ms
122 silly placeDep ROOT binaryextensions@2.3.0 OK for: istextorbinary@2.6.0 want: ^2.1.2
123 silly placeDep ROOT editions@2.3.1 OK for: istextorbinary@2.6.0 want: ^2.2.0
124 silly placeDep ROOT textextensions@2.6.0 OK for: istextorbinary@2.6.0 want: ^2.5.0
125 silly fetch manifest errlop@^2.0.0
126 silly fetch manifest semver@^6.3.0
127 http fetch GET 200 https://registry.npmjs.org/errlop 29ms (cache hit)
128 http fetch GET 200 https://registry.npmjs.org/semver 34ms (cache hit)
129 timing idealTree:node_modules/istextorbinary Completed in 41ms
130 timing idealTree:node_modules/binaryextensions Completed in 0ms
131 silly placeDep ROOT errlop@2.2.0 OK for: editions@2.3.1 want: ^2.0.0
132 silly placeDep ROOT semver@6.3.0 OK for: editions@2.3.1 want: ^6.3.0
133 timing idealTree:node_modules/editions Completed in 2ms
134 timing idealTree:node_modules/errlop Completed in 0ms
135 timing idealTree:node_modules/minimalistic-assert Completed in 0ms
136 timing idealTree:node_modules/mkdirp Completed in 0ms
137 timing idealTree:node_modules/rsvp Completed in 0ms
138 timing idealTree:node_modules/safer-buffer Completed in 0ms
139 timing idealTree:node_modules/semver Completed in 1ms
140 timing idealTree:node_modules/simple-lru-cache Completed in 0ms
141 timing idealTree:node_modules/textextensions Completed in 0ms
142 timing idealTree:node_modules/username-sync Completed in 0ms
143 timing idealTree:node_modules/uuid Completed in 0ms
144 timing idealTree:node_modules/heimdalljs/node_modules/rsvp Completed in 0ms
145 silly placeDep node_modules/microsoft-cognitiveservices-speech-sdk/node_modules/https-proxy-agent agent-base@5.1.1 OK for: https-proxy-agent@4.0.0 want: 5
146 timing idealTree:node_modules/microsoft-cognitiveservices-speech-sdk/node_modules/https-proxy-agent Completed in 1ms
147 timing idealTree:node_modules/microsoft-cognitiveservices-speech-sdk/node_modules/https-proxy-agent/node_modules/agent-base Completed in 0ms
148 timing idealTree:buildDeps Completed in 450ms
149 timing idealTree:fixDepFlags Completed in 2ms
150 timing idealTree Completed in 551ms
151 timing reify:loadTrees Completed in 552ms
152 timing reify:diffTrees Completed in 4ms
153 silly reify mark retired [ '/Users/bob/Projects/flashnews_beta/node_modules/asn1.js' ]
154 silly reify mark retired [ '/Users/bob/Projects/flashnews_beta/node_modules/heimdalljs' ]
155 silly reify mark retired [
155 silly reify   '/Users/bob/Projects/flashnews_beta/node_modules/microsoft-cognitiveservices-speech-sdk'
155 silly reify ]
156 silly reify mark retired [ '/Users/bob/Projects/flashnews_beta/node_modules/rsvp' ]
157 silly reify moves {
157 silly reify   '/Users/bob/Projects/flashnews_beta/node_modules/asn1.js': '/Users/bob/Projects/flashnews_beta/node_modules/.asn1.js-YC7qLFcV',
157 silly reify   '/Users/bob/Projects/flashnews_beta/node_modules/heimdalljs': '/Users/bob/Projects/flashnews_beta/node_modules/.heimdalljs-lbGX2ss9',
157 silly reify   '/Users/bob/Projects/flashnews_beta/node_modules/microsoft-cognitiveservices-speech-sdk': '/Users/bob/Projects/flashnews_beta/node_modules/.microsoft-cognitiveservices-speech-sdk-I4qu3Y5R',
157 silly reify   '/Users/bob/Projects/flashnews_beta/node_modules/rsvp': '/Users/bob/Projects/flashnews_beta/node_modules/.rsvp-36xcPFLC'
157 silly reify }
158 timing reify:retireShallow Completed in 4ms
159 timing reify:createSparse Completed in 10ms
160 timing reify:loadBundles Completed in 0ms
161 silly audit bulk request {
161 silly audit   'html-to-text': [ '7.1.3' ],
161 silly audit   tr46: [ '0.0.3' ],
161 silly audit   '@types/filewriter': [ '0.0.29' ],
161 silly audit   openai: [ '3.1.0' ],
161 silly audit   '@types/chrome': [ '0.0.197', '0.0.91' ],
161 silly audit   'fs.realpath': [ '1.0.0' ],
161 silly audit   '@types/yauzl': [ '2.10.0' ],
161 silly audit   'puppeteer-extra-plugin': [ '3.2.2' ],
161 silly audit   '@cliqz/adblocker-puppeteer': [ '1.18.7' ],
161 silly audit   'mkdirp-classic': [ '0.5.3' ],
161 silly audit   chownr: [ '1.1.4' ],
161 silly audit   buffer: [ '5.7.1' ],
161 silly audit   'get-stream': [ '5.2.0' ],
161 silly audit   entities: [ '2.2.0' ],
161 silly audit   'node-fetch': [ '2.6.7' ],
161 silly audit   glob: [ '7.2.3' ],
161 silly audit   pump: [ '3.0.0' ],
161 silly audit   domutils: [ '2.8.0' ],
161 silly audit   'lazy-cache': [ '0.2.7', '1.0.4' ],
161 silly audit   '@types/debug': [ '4.1.7' ],
161 silly audit   domhandler: [ '4.3.1' ],
161 silly audit   'path-is-absolute': [ '1.0.1' ],
161 silly audit   'mime-types': [ '2.1.35' ],
161 silly audit   'balanced-match': [ '1.0.2' ],
161 silly audit   axios: [ '0.26.1' ],
161 silly audit   jsonfile: [ '6.1.0' ],
161 silly audit   '@remusao/smaz': [ '1.9.1' ],
161 silly audit   'find-up': [ '4.1.0' ],
161 silly audit   inherits: [ '2.0.4' ],
161 silly audit   'puppeteer-extra': [ '3.1.18' ],
161 silly audit   deepmerge: [ '4.2.2' ],
161 silly audit   he: [ '1.2.0' ],
161 silly audit   string_decoder: [ '1.3.0' ],
161 silly audit   'is-buffer': [ '1.1.6' ],
161 silly audit   'fd-slicer': [ '1.1.0' ],
161 silly audit   debug: [ '4.3.4' ],
161 silly audit   'arr-union': [ '3.1.0' ],
161 silly audit   'clone-deep': [ '0.2.4' ],
161 silly audit   'is-plain-object': [ '2.0.4' ],
161 silly audit   'p-try': [ '2.2.0' ],
161 silly audit   once: [ '1.4.0' ],
161 silly audit   '@remusao/small': [ '1.2.1' ],
161 silly audit   isobject: [ '3.0.1' ],
161 silly audit   'for-in': [ '1.0.2', '0.1.8' ],
161 silly audit   'locate-path': [ '5.0.0' ],
161 silly audit   '@types/firefox-webext-browser': [ '94.0.1' ],
161 silly audit   'puppeteer-extra-plugin-stealth': [ '2.7.8' ],
161 silly audit   'unbzip2-stream': [ '1.4.3' ],
161 silly audit   'tar-stream': [ '2.2.0' ],
161 silly audit   '@types/filesystem': [ '0.0.32' ],
161 silly audit   'p-limit': [ '2.3.0' ],
161 silly audit   'mixin-object': [ '2.0.1' ],
161 silly audit   'shallow-clone': [ '0.1.2' ],
161 silly audit   pend: [ '1.2.0' ],
161 silly audit   'base64-js': [ '1.5.1' ],
161 silly audit   '@remusao/trie': [ '1.4.1' ],
161 silly audit   '@types/node': [ '18.11.18' ],
161 silly audit   '@remusao/guess-url-type': [ '1.2.1' ],
161 silly audit   'puppeteer-extra-plugin-user-preferences': [ '2.4.0' ],
161 silly audit   'mime-db': [ '1.52.0' ],
161 silly audit   'fs-extra': [ '10.1.0' ],
161 silly audit   'https-proxy-agent': [ '5.0.1', '4.0.0' ],
161 silly audit   ieee754: [ '1.2.1' ],
161 silly audit   'agent-base': [ '5.1.1', '6.0.2' ],
161 silly audit   'end-of-stream': [ '1.4.4' ],
161 silly audit   'devtools-protocol': [ '0.0.818844', '0.0.869402' ],
161 silly audit   minimatch: [ '3.1.2' ],
161 silly audit   through: [ '2.3.8' ],
161 silly audit   ms: [ '2.1.2' ],
161 silly audit   rimraf: [ '3.0.2' ],
161 silly audit   'puppeteer-extra-plugin-adblocker': [ '2.11.11' ],
161 silly audit   asynckit: [ '0.4.0' ],
161 silly audit   'util-deprecate': [ '1.0.2' ],
161 silly audit   'path-exists': [ '4.0.0' ],
161 silly audit   '@cliqz/adblocker': [ '1.25.1' ],
161 silly audit   'extract-zip': [ '2.0.1' ],
161 silly audit   'puppeteer-extra-plugin-block-resources': [ '2.2.9' ],
161 silly audit   '@types/ms': [ '0.7.31' ],
161 silly audit   'combined-stream': [ '1.0.8' ],
161 silly audit   'tar-fs': [ '2.1.1' ],
161 silly audit   'whatwg-url': [ '5.0.0' ],
161 silly audit   'puppeteer-extra-plugin-user-data-dir': [ '2.4.0' ],
161 silly audit   'pkg-dir': [ '4.2.0' ],
161 silly audit   htmlparser2: [ '6.1.0' ],
161 silly audit   yauzl: [ '2.10.0' ],
161 silly audit   'delayed-stream': [ '1.0.0' ],
161 silly audit   'merge-deep': [ '3.0.3' ],
161 silly audit   '@types/har-format': [ '1.2.10' ],
161 silly audit   'buffer-crc32': [ '0.2.13' ],
161 silly audit   'webidl-conversions': [ '3.0.1' ],
161 silly audit   'is-extendable': [ '0.1.1' ],
161 silly audit   'for-own': [ '0.1.5' ],
161 silly audit   'proxy-from-env': [ '1.1.0' ],
161 silly audit   'readable-stream': [ '3.6.0' ],
161 silly audit   '@cliqz/adblocker-content': [ '1.25.1' ],
161 silly audit   progress: [ '2.0.3' ],
161 silly audit   inflight: [ '1.0.6' ],
161 silly audit   'tldts-core': [ '5.7.103' ],
161 silly audit   minimist: [ '1.2.7' ],
161 silly audit   'tldts-experimental': [ '5.7.103' ],
161 silly audit   'p-locate': [ '4.1.0' ],
161 silly audit   universalify: [ '2.0.0' ],
161 silly audit   puppeteer: [ '5.5.0', '9.1.1' ],
161 silly audit   '@remusao/smaz-compress': [ '1.9.1' ],
161 silly audit   'brace-expansion': [ '1.1.11' ],
161 silly audit   'fs-constants': [ '1.0.0' ],
161 silly audit   'graceful-fs': [ '4.2.10' ],
161 silly audit   'follow-redirects': [ '1.15.2' ],
161 silly audit   domelementtype: [ '2.3.0' ],
161 silly audit   'concat-map': [ '0.0.1' ],
161 silly audit   'kind-of': [ '3.2.2', '2.0.1' ],
161 silly audit   '@cliqz/adblocker-extended-selectors': [ '1.25.1' ],
161 silly audit   'safe-buffer': [ '5.2.1' ],
161 silly audit   '@remusao/smaz-decompress': [ '1.9.1' ],
161 silly audit   'form-data': [ '4.0.0' ],
161 silly audit   '@types/puppeteer': [ '5.4.3' ],
161 silly audit   wrappy: [ '1.0.2' ],
161 silly audit   ws: [ '7.5.9' ],
161 silly audit   'dom-serializer': [ '1.4.1' ],
161 silly audit   bl: [ '4.1.0' ],
161 silly audit   'microsoft-cognitiveservices-speech-sdk': [ '1.24.1' ],
161 silly audit   'asn1.js-rfc2560': [ '5.0.1' ],
161 silly audit   'asn1.js': [ '5.4.1' ],
161 silly audit   'asn1.js-rfc5280': [ '3.0.0' ],
161 silly audit   'async-disk-cache': [ '2.1.0' ],
161 silly audit   bent: [ '7.3.12' ],
161 silly audit   'simple-lru-cache': [ '0.0.2' ],
161 silly audit   uuid: [ '8.3.2' ],
161 silly audit   'bn.js': [ '4.12.0' ],
161 silly audit   'minimalistic-assert': [ '1.0.1' ],
161 silly audit   'safer-buffer': [ '2.1.2' ],
161 silly audit   heimdalljs: [ '0.2.6' ],
161 silly audit   istextorbinary: [ '2.6.0' ],
161 silly audit   mkdirp: [ '0.5.6' ],
161 silly audit   rsvp: [ '4.8.5', '3.2.1' ],
161 silly audit   'username-sync': [ '1.0.3' ],
161 silly audit   bytesish: [ '0.4.4' ],
161 silly audit   caseless: [ '0.12.0' ],
161 silly audit   'is-stream': [ '2.0.1' ],
161 silly audit   binaryextensions: [ '2.3.0' ],
161 silly audit   editions: [ '2.3.1' ],
161 silly audit   textextensions: [ '2.6.0' ],
161 silly audit   errlop: [ '2.2.0' ],
161 silly audit   semver: [ '6.3.0' ]
161 silly audit }
162 notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
163 http fetch POST 426 http://registry.npmjs.org/-/npm/v1/security/advisories/bulk 169ms
164 silly audit bulk request failed Beginning October 4, 2021, all connections to npm websites and the npm registry - including for package installation - must use HTTPS and TLS 1.2 or higher.
164 silly audit
164 silly audit For more information see this blog post: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
165 notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
166 http fetch POST 426 http://registry.npmjs.org/-/npm/v1/security/audits/quick 25ms
167 verbose audit error HttpErrorGeneral: 426 Upgrade Required - POST http://registry.npmjs.org/-/npm/v1/security/audits/quick
167 verbose audit error     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
167 verbose audit error     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
167 verbose audit error     at async [getReport] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:335:21)
167 verbose audit error     at async AuditReport.run (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:106:19) {
167 verbose audit error   headers: [Object: null prototype] {
167 verbose audit error     date: [ 'Wed, 04 Jan 2023 01:15:16 GMT' ],
167 verbose audit error     'content-type': [ 'text/plain' ],
167 verbose audit error     'content-length': [ '271' ],
167 verbose audit error     connection: [ 'keep-alive' ],
167 verbose audit error     'npm-notice': [
167 verbose audit error       'Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/'
167 verbose audit error     ],
167 verbose audit error     vary: [ 'Accept-Encoding' ],
167 verbose audit error     server: [ 'cloudflare' ],
167 verbose audit error     'cf-ray': [ '78401f463ed27acb-LAX' ],
167 verbose audit error     'x-fetch-attempts': [ '1' ]
167 verbose audit error   },
167 verbose audit error   statusCode: 426,
167 verbose audit error   code: 'E426',
167 verbose audit error   method: 'POST',
167 verbose audit error   uri: 'http://registry.npmjs.org/-/npm/v1/security/audits/quick',
167 verbose audit error   body: <Buffer 42 65 67 69 6e 6e 69 6e 67 20 4f 63 74 6f 62 65 72 20 34 2c 20 32 30 32 31 2c 20 61 6c 6c 20 63 6f 6e 6e 65 63 74 69 6f 6e 73 20 74 6f 20 6e 70 6d 20 ... 221 more bytes>,
167 verbose audit error   pkgid: undefined
167 verbose audit error }
168 silly audit error Beginning October 4, 2021, all connections to npm websites and the npm registry - including for package installation - must use HTTPS and TLS 1.2 or higher.
168 silly audit error
168 silly audit error For more information see this blog post: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
169 timing auditReport:getReport Completed in 233ms
170 silly audit report null
171 timing reify:audit Completed in 233ms
172 timing reifyNode:node_modules/asn1.js-rfc2560 Completed in 232ms
173 timing reifyNode:node_modules/username-sync Completed in 235ms
174 timing reifyNode:node_modules/minimalistic-assert Completed in 237ms
175 timing reifyNode:node_modules/asn1.js-rfc5280 Completed in 237ms
176 timing reifyNode:node_modules/is-stream Completed in 239ms
177 timing reifyNode:node_modules/caseless Completed in 240ms
178 timing reifyNode:node_modules/async-disk-cache Completed in 241ms
179 timing reifyNode:node_modules/mkdirp Completed in 242ms
180 timing reifyNode:node_modules/safer-buffer Completed in 246ms
181 timing reifyNode:node_modules/binaryextensions Completed in 247ms
182 timing reifyNode:node_modules/microsoft-cognitiveservices-speech-sdk/node_modules/https-proxy-agent Completed in 248ms
183 timing reifyNode:node_modules/textextensions Completed in 249ms
184 timing reifyNode:node_modules/microsoft-cognitiveservices-speech-sdk/node_modules/https-proxy-agent/node_modules/agent-base Completed in 250ms
185 timing reifyNode:node_modules/semver Completed in 252ms
186 timing reifyNode:node_modules/bn.js Completed in 250ms
187 timing reifyNode:node_modules/bytesish Completed in 251ms
188 timing reifyNode:node_modules/bent Completed in 252ms
189 timing reifyNode:node_modules/errlop Completed in 254ms
190 timing reifyNode:node_modules/simple-lru-cache Completed in 255ms
191 timing reifyNode:node_modules/istextorbinary Completed in 258ms
192 timing reifyNode:node_modules/heimdalljs Completed in 260ms
193 timing reifyNode:node_modules/editions Completed in 265ms
194 timing reifyNode:node_modules/asn1.js Completed in 268ms
195 timing reifyNode:node_modules/heimdalljs/node_modules/rsvp Completed in 292ms
196 timing reifyNode:node_modules/uuid Completed in 322ms
197 timing reifyNode:node_modules/rsvp Completed in 322ms
198 timing reifyNode:node_modules/microsoft-cognitiveservices-speech-sdk Completed in 1092ms
199 timing reify:unpack Completed in 1094ms
200 timing reify:unretire Completed in 0ms
201 timing build:queue Completed in 3ms
202 info run microsoft-cognitiveservices-speech-sdk@1.24.1 preinstall node_modules/microsoft-cognitiveservices-speech-sdk npm install --package-lock-only --ignore-scripts --no-audit && npx npm-force-resolutions
203 info run microsoft-cognitiveservices-speech-sdk@1.24.1 preinstall { code: 1, signal: null }
204 timing reify:rollback:createSparse Completed in 357ms
205 timing reify:rollback:retireShallow Completed in 2ms
206 timing command:i Completed in 25561ms
207 verbose stack Error: command failed
207 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
207 verbose stack     at ChildProcess.emit (node:events:513:28)
207 verbose stack     at maybeClose (node:internal/child_process:1091:16)
207 verbose stack     at Socket.<anonymous> (node:internal/child_process:449:11)
207 verbose stack     at Socket.emit (node:events:513:28)
207 verbose stack     at Pipe.<anonymous> (node:net:313:12)
208 verbose pkgid microsoft-cognitiveservices-speech-sdk@1.24.1
209 verbose cwd /Users/bob/Projects/flashnews_beta
210 verbose Darwin 21.1.0
211 verbose node v18.12.1
212 verbose npm  v8.19.2
213 error code 1
214 error path /Users/bob/Projects/flashnews_beta/node_modules/microsoft-cognitiveservices-speech-sdk
215 error command failed
216 error command sh -c -- npm install --package-lock-only --ignore-scripts --no-audit && npx npm-force-resolutions
217 error up to date in 13s
217 error
217 error 118 packages are looking for funding
217 error   run `npm fund` for details
218 error /Users/bob/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:61
218 error   (go
218 error   ^
218 error Error: Timeout trying to fetch resolutions from npm
218 error     at switch__2144__auto__ (/Users/bob/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:61:3)
218 error     at /Users/bob/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:61:3
218 error     at npm_force_resolutions$core$find_resolutions_$_state_machine__2145__auto____1 (/Users/bob/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:476:4)
218 error     at cljs.core.async.impl.ioc-helpers/FN-IDX (/Users/bob/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:492:85)
218 error     at cljs.core.async.impl.ioc-helpers/run-state-machine (/Users/bob/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:35:23)
218 error     at cljs.core.async.impl.ioc-helpers/run-state-machine-wrapped (/Users/bob/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:39:6)
218 error     at fret (/Users/bob/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolutions/out/cljs/core/async.cljs:490:22)
218 error     at take-cb (/Users/bob/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolutions/out/cljs/core/async.cljs:188:63)
218 error     at /Users/bob/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolutions/out/cljs/core/async/impl/channels.cljs:160:45
218 error     at Immediate.cljs$core$async$impl$dispatch$process_messages (/Users/bob/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolutions/out/cljs/core/async/impl/dispatch.cljs:18:7)
219 verbose exit 1
220 timing npm Completed in 25695ms
221 verbose unfinished npm timer reify 1672794916036
222 verbose unfinished npm timer reify:build 1672794917720
223 verbose unfinished npm timer build 1672794917720
224 verbose unfinished npm timer build:deps 1672794917721
225 verbose unfinished npm timer build:run:preinstall 1672794917724
226 verbose unfinished npm timer build:run:preinstall:node_modules/microsoft-cognitiveservices-speech-sdk 1672794917725
227 verbose code 1
228 error A complete log of this run can be found in:
228 error     /Users/bob/.npm/_logs/2023-01-04T01_15_15_906Z-debug-0.log

**Comment by brandom-msft** [comment]
Hi @snippet - this looks like an issue on the connection between your client and the npm service. From the error log you posted, I noticed this line
`167 verbose audit error 'Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information:`

[Here's the blog post](https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/#ensuring-your-compatibility) mentioned in that error - please let me know if that helps!

**Comment by brandom-msft** [comment]
closing due to no updates
