### ISSUE TITLE
SpeechRecognizer stops receiving events and hangs

### ISSUE THREAD

**Issue by gunpuz** [Azure-Samples/cognitive-services-speech-sdk#1792]
**Describe the bug**
SpeechRecognizer stops receiving events and audio is not processed for larger audio files

**To Reproduce**
1. Publish service in Kubernetes env
2. Upload long audio, in this case 1h 10min
3. Wait, it can hang when audio processing is done ~50min of audio. It can hang in random place, but it seems that it needs longer audio to hang and longer time for hang to occur

```cs
using var audioConfig = AudioConfig.FromWavFileInput(audioPath);

...
var recognizer = new SpeechRecognizer(_speechConfig, audioConfig);

recognizer.SessionStopped += (s, e) =>
{
    _logger.LogDebug("SESSION-END {sessionID}", e.SessionId);
};
recognizer.Canceled += (s, e) =>
{
    _logger.LogDebug("SESSION-CANCELED {sessionID}: {Reason} - {errorCode}", e.SessionId, e.Reason, e.ErrorCode);
};
```

**Expected behavior**
There could be some error event or process could continue even if network events have occured.
No finish events (SessionStopped/Canceled) are fired, and audio processing is not done. The audio has not been processed fully. 

*Shorter audio files are processed sucessfully

**Version of the Cognitive Services Speech SDK**
1.23.0

**Platform, Operating System, and Programming Language**
 - OS: `Linux 5.15.0-1022-azure #27~20.04.1-Ubuntu SMP Mon Oct 17 02:03:50 UTC 2022 x86_64`
 - Hardware: `Linux-x64`
 - Programming language: `C#`

**Additional context**
 - No error messages or stack traces, because the recognition hangs
 - SDK log The full log is ~60MB large, so here is small fragment of it. 
 [filtred_sdk.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/10342307/filtred_sdk.log)
 - Session id: 57eec121c12a482d8b5e8d17eeed8386. From `2023-01-03T18:01:34.910350568+02:00` - `2023-01-03T18:25:01.865892907+02:00` (no results after this time)

**Comment by rhurey** [comment]
Thanks for the log.

From the tail end of it the .Net GC is garbage collecting and finalizing objects in the C# projection. 

While the exact line corresponding to the recognizer's object isn't in the log, there's enough to make me suspect that the recognizer itself has been collected as its termination is being run on the same thread as other objects are being finalized on.

If you have the full log you can search for a log entry from thread [783591] that reads something like:
[783591]: <time>ms SPX_TRACE_VERBOSE interop_factory.cs:104 InteropSafeHandle Finalizer for 7f9548101280
(I believe that's the object handle that the native code layer has sent the C# layer.)

and
[783591]: <time>ms SPX_TRACE_VERBOSE recognizer.cs:~131 Finalizer for 7f9548101280

There won't be any events raised, as the GC has decided the object is gone, and the first thing done is to remove all event hooks.

**Comment by gunpuz** [comment]
Sure, here are more logs from the end. 
[filtred-longer.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/10443756/filtred-longer.log)

There are these lines that seems suspicious, would you say so?:
```yaml
[783591]: 1602601ms SPX_DBG_TRACE_FUNCTION:  audio_stream_session.cpp:728 SetDisposing
[783591]: 1602601ms SPX_DBG_TRACE_FUNCTION:  audio_stream_session.cpp:1114 StopRecognitionAsync
```

**Comment by rhurey** [comment]
The GC is collecting recognizers.
One of which was already stopped and idle, one of which was running.

The running one:
[783591]: 1602592ms SPX_TRACE_VERBOSE recognizer.cs:169 Dispose(False) called for 7f952c014560
[783591]: 1602592ms SPX_TRACE_VERBOSE recognizer.cs:131 Finalizer for 7f952c014560
...
[783591]: 1602601ms SPX_TRACE_VERBOSE interop_factory.cs:104 InteropSafeHandle Finalizer for 7f952c014560
[783591]: 1602601ms SPX_TRACE_VERBOSE interop_factory.cs:83 Dispose(False) called for 7f952c014560
[783591]: 1602601ms SPX_DBG_TRACE_FUNCTION:  audio_stream_session.cpp:728 SetDisposing
[783591]: 1602601ms SPX_DBG_TRACE_FUNCTION:  audio_stream_session.cpp:1114 StopRecognitionAsync

Finding out why the GC thought that recognizer wasn't rooted is the key thing to solve.

**Comment by gunpuz** [comment]
More logs needed @rhurey, can I somehow help to solve this issue?

**Comment by rhurey** [comment]
In past incarnations of this problem it's been a review of the application code that finds the reason the recognizer object isn't considered rooted by the GC.

You don't happen to be using a TaskCompletionSource with async / await to wait for recognition to complete? There's a pattern there we've seen have a sharp edge.

I'll also offer if you'd like you can contact me @microsoft.com (same alias)

**Comment by gunpuz** [comment]
Yes, `TaskCompletionSource` is involved to wait for transciption to finish. I will contact you in email

**Comment by gunpuz** [comment]
Seems like the pattern to use speech recognizer and TaskCompletionSource in single function can cause issues with GC. After storing the reference of speechRecognizer more carefull, this issue goes away. 

P.S. It would be nice to see API that you can wait transcription to finish.

**Comment by gfreezy** [comment]
I have encountered the same problem using `TaskCompletionSource`. Any clues to solve the problem?

```c#
using AiTalker.Meters;
using AiTalker.Settings;
using Microsoft.CognitiveServices.Speech;
using Microsoft.CognitiveServices.Speech.Audio;
using Sentry;
using Serilog.Context;

namespace AiTalker.Services;

public class AzureSpeechToTextService : IDisposable
{
    private readonly ILogger _logger;

    // ReSharper disable once PrivateFieldCanBeConvertedToLocalVariable
    private readonly AzureMeters _meters;
    private readonly IDisposable _enricher;
    private readonly SpeechRecognizer _speechRecognizer;
    private readonly AudioConfig _audioConfig;
    private readonly PushAudioInputStream _audioStream;
    private readonly TaskCompletionSource<bool> _task;
    private string _text = "";

    public AzureSpeechToTextService(
        ILogger logger, AzureSpeechSettings azureSpeechSettings,
        AudioStreamFormat audioStreamFormat, string language,
        AzureMeters meters
    )
    {
        _logger = logger;
        _meters = meters;
        _meters.InitializeSttInstance();
        _enricher = LogContext.PushProperty("UniqueId", Guid.NewGuid().ToString("N"));
        var speechConfig =
            SpeechConfig.FromSubscription(azureSpeechSettings.SubscriptionKey, azureSpeechSettings.Region);
        speechConfig.SetProperty(PropertyId.Speech_SegmentationSilenceTimeoutMs, "5000");
        speechConfig.SetProperty(PropertyId.Speech_LogFilename, "/tmp/speech.log");
        speechConfig.SpeechRecognitionLanguage = language;
        // speechConfig.RequestWordLevelTimestamps();
        // speechConfig.OutputFormat = OutputFormat.Detailed;

        _audioStream = new PushAudioInputStream(audioStreamFormat);
        _audioConfig = AudioConfig.FromStreamInput(_audioStream);
        _speechRecognizer = new SpeechRecognizer(speechConfig, _audioConfig);

        _task = new TaskCompletionSource<bool>(TaskCreationOptions.RunContinuationsAsynchronously);
        var parent = LogContext.Clone();
        _speechRecognizer.Recognized += (_, args) =>
        {
            using var e = LogContext.Push(parent);
            _logger.LogInformation("Recognized: {text}, sessionId: {sessionId}, duration: {duration}", args.Result.Text,
                args.SessionId, args.Result.Duration);
            _text += args.Result.Text;
        };
        _speechRecognizer.Canceled += (_, args) =>
        {
            using var e = LogContext.Push(parent);
            if (args.Reason == CancellationReason.EndOfStream)
            {
                _logger.LogInformation("Canceled: {reason}, sessionId: {sessionId}", args.Reason, args.SessionId);
                _task.TrySetResult(true);
            }
            else
            {
                _logger.LogError("Canceled: {reason}, sessionId: {sessionId}, error: {error}", args.Reason,
                    args.SessionId, args.ErrorDetails);
                _task.SetException(new Exception(args.ErrorDetails));
            }
        };
        _speechRecognizer.Recognizing += (_, args) =>
        {
            using var e = LogContext.Push(parent);
            _logger.LogDebug("Recognizing: {text}, sessionId: {sessionId}, duration: {duration}",
                args.Result.Text, args.SessionId, args.Result.Duration);
        };
        _speechRecognizer.SessionStarted += (_, args) =>
        {
            using var e = LogContext.Push(parent);
            _meters.OpenSttConnection();
            _logger.LogInformation("SessionStarted, sessionId: {sessionId}", args.SessionId);
        };
        _speechRecognizer.SessionStopped += (_, args) =>
        {
            using var e = LogContext.Push(parent);
            _meters.CloseSttConnection();
            _logger.LogInformation("SessionStopped: sessionId: {sessionId}", args.SessionId);
            _task.TrySetResult(true);
        };
    }

    public async Task StartRecognition()
    {
        _logger.LogInformation("call StartRecognition");
        await _speechRecognizer.StartContinuousRecognitionAsync();
    }

    public void Write(byte[] dataBuffer)
    {
        _logger.LogDebug("write bytes: {bytes}", dataBuffer.Length);
        _audioStream.Write(dataBuffer);
    }

    public void Finish()
    {
        _logger.LogInformation("call Finish");
        _audioStream.Close();
    }

    public Task StopRecognition()
    {
        _logger.LogInformation("call StopRecognition");
        return _speechRecognizer.StopContinuousRecognitionAsync();
    }

    public async Task<string> Result()
    {
        _logger.LogInformation("call Result, before await");
        try
        {
            await _task.Task;
            _logger.LogInformation("call Result, done await");
        } catch (Exception e)
        {
            SentrySdk.CaptureException(e);
            _logger.LogError(e, "error in Result");
        }

        return _text;
    }

    public void Dispose()
    {
        _meters.DisposeSttInstance();
        _logger.LogInformation("call Dispose");
        _speechRecognizer.Dispose();
        _audioConfig.Dispose();
        _audioStream.Dispose();
        _enricher.Dispose();
    }
}
```
