### ISSUE TITLE
How to prevent speech to text picking up text to speech? :)

### ISSUE THREAD

**Issue by bbence84** [Azure-Samples/cognitive-services-speech-sdk#1793]
I am building a device which responds to voice commands using Azure TTS. The question is if there's a way to "pause" speech to text for the duration of the TTS audio? 
I am using streaming recognize (start_continuous_recognition) and I have an event handler for speech_recognizer.recognized.connect which detects the utterance and then responds using speak_ssml_async. But even the non-async version is still not blocking the continuous_recognition from picking up the TTS voice.
I thought using stop_continuous_recognition and then restarting with start_continuous_recognition, but this does not seem to work very well, as it has a quite big overhead and causes a delay.

A pause for the continuous_recognition might be a good solution.

Thanks for any hints and suggestions!

**Comment by brandom-msft** [comment]
Hi @bbence84 - the best recommendation would be to use echo cancellation, which [the SDK has limited support for with MAS](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/audio-processing-speech-sdk?tabs=csharp). Unfortunately, I suspect (based on the method naming you shared) this won't be helpful guidance for you as Python doesn't have MAS support.

Regarding the delay, I wondered if it could be related to [this issue](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1506#issuecomment-1140045602). I'll need to check with the team if there were updates to Python to resolve that, but in the meantime thought I could share to see if it applies as a workaround for your scenario.

**Comment by bbence84** [comment]
> Hi @bbence84 - the best recommendation would be to use echo cancellation, which [the SDK has limited support for with MAS](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/audio-processing-speech-sdk?tabs=csharp). Unfortunately, I suspect (based on the method naming you shared) this won't be helpful guidance for you as Python doesn't have MAS support.
> 
> Regarding the delay, I wondered if it could be related to [this issue](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1506#issuecomment-1140045602). I'll need to check with the team if there were updates to Python to resolve that, but in the meantime thought I could share to see if it applies as a workaround for your scenario.

Thanks! I have been experimenting with this workaround, but ultimately I have realized that there's a much easier solution: I programmatically mute the microphone till TTS has finished speaking. :) I am using a python package that makes this pretty simple. So again, my solution is - instead of switching recognition off and on - to mute the mic temporarily. :)

**Comment by ck123pm** [comment]
> > Hi @bbence84 - the best recommendation would be to use echo cancellation, which [the SDK has limited support for with MAS](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/audio-processing-speech-sdk?tabs=csharp). Unfortunately, I suspect (based on the method naming you shared) this won't be helpful guidance for you as Python doesn't have MAS support.
> > Regarding the delay, I wondered if it could be related to [this issue](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1506#issuecomment-1140045602). I'll need to check with the team if there were updates to Python to resolve that, but in the meantime thought I could share to see if it applies as a workaround for your scenario.
> 
> Thanks! I have been experimenting with this workaround, but ultimately I have realized that there's a much easier solution: I programmatically mute the microphone till TTS has finished speaking. :) I am using a python package that makes this pretty simple. So again, my solution is - instead of switching recognition off and on - to mute the mic temporarily. :)

I have the same question like you. Can you please show me the code how to mute the mic temporarily? Thanks a lot.
