### ISSUE TITLE
Batch Transcription Speaker Diarization

### ISSUE THREAD

**Issue by hemnaathR** [Azure-Samples/cognitive-services-speech-sdk#1794]
Hello,

Does batch transcription speaker diarization still identify 2 speakers or has that been improved? Also does it still require `wordLevelTimestampsEnabled` to be set to true?

There was documentation on this before on the microsoft learn page but I cant find it anymore.

**Comment by zhouwangzw** [comment]
With V3.1 API, speaker diarization supports more than 2 speakers, and wordLevelTimestampsEnabled is not required anymore. You can find migration guide [here](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/migrate-v3-0-to-v3-1). And the swagger definition can be found [here](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cognitiveservices/data-plane/Speech/SpeechToText/stable/v3.1)

Thanks.

**Comment by hemnaathR** [comment]
Thanks @zhouwangzw . Are there C# samples of using the V3.1 API like there is for 3.0 over here?
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/csharp/batchclient

**Comment by zhouwangzw** [comment]
@hemnaathR  Yes, we are working on updating the C# samples to V3.1, and hope to be available very soon. Thanks.

**Comment by hemnaathR** [comment]
Thanks @chlandsi
