### ISSUE TITLE
Long running speech recognition without speech start/end detection, multiple recognitions within same session and speaker diarization

### ISSUE THREAD

**Issue by sibbl** [Azure-Samples/cognitive-services-speech-sdk#1797]
**Describe the bug**
I'm currently working on a kind of "push to talk" speech to text C# app.
As I want to support long audio as well, I went for the `StartContinuousRecognitionAsync` API.

1. Since I know exactly when audio started and stopped via the push to talk mechanism, I want to disable the start and end of speech detection on your side.
2. I want to allow consecutively recognitions immediately after one recognition stopped. Basically this: push button... talk... release button, then immediately push button again... talk... release button, and so on should work as fast as possible. It should return 2 distinct results in this scenario.
3. Ideally I want to reuse the same recognition session to use speaker diarization even across several phrases. If somebody else taps the button the 2nd time, I want to be able to detect this.

I feel like the parts are all there and it should be possible to build this. However, I found some inconsistencies and wonder how it's recommeded to be solved.

### 1. How to disable silence detection?

**To reproduce**
1. Use `config.SetProperty(PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs, "0");`

**Expected behavior**
As described [in the documentation](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-recognize-speech?pivots=programming-language-csharp#change-how-silence-is-handled), it should "disable it entirely":

> Initial silence timeout [...] This timeout can be set to any non-negative integer value, in milliseconds, or set to 0 to disable it entirely; 

**Actual behavior**

> Error code: 1007. Error details: Client initial silence timeout should be always greater than 0.

### 2. How to continue speech recognition directly after a recognition was requested

As far as I understand the API, I need to do call `await recognizer.StopContinuousRecognitionAsync` to tell the Websocket to recognize the audio stream it received so far. However, this seems to stop the whole session and I found no way to reuse the same websocket connection for further speech recognition. Calling `await recognizer.StartContinuousRecognitionAsync` right away again, results in `SPXERR_START_RECOGNIZING_INVALID_STATE_TRANSITION` being thrown. Calling it inside `OnRecognized` doesn't do anything since the session was stopped.

Is this scenario even possible and supported, or do I need to create a new recognizer anyway and open a new connection to your servers? I guess no speaker diarization across these sessions is then possible?

**Expected behavior / feature request**
I can tell the recognizer to detect speech in the audio I've streamed to it and can right away continue with another recognition within the same session supporting speaker diarization.

**Version of the Cognitive Services Speech SDK**
1.24.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 11
 - Hardware: x64
 - Programming language: C#

**Comment by trrwilson** [comment]
Thank you for the great breakdown!

For (1): that documentation tip definitely doesn't seem to work. I'll follow up on getting the documentation and/or service logic updated. As a workaround, using a suitably large value (e.g. 3600000, one hour) should achieve the same intended effect. It's also an option to just ignore empty recognition results (empty string in Result.Text).

For (2): it's completely attainable to achieve what you mention, but speech-to-text unfortunately doesn't have a "segment and  continue" instruction built in to make it trivial. That means that manually ending recognition (in response to the release signal) will need to finish the current recognition operation to forcibly generate a result. You don't need to re-create the recognizer each time, but you'll need to stop/start and also use one of the stream objects (PushAudioInputStream or PullAudioInputStream) to ensure that no audio is lost between recognition operations -- default microphone input will stop collecting audio as soon as the recognition operation finishes, and thus there will always be a bit of a gap (even if small) before capture starts again.

The simplest way to achieve this is likely using a PullAudioInputStreamCallback implementation. In that, the stream would use a system-appropriate audio API to collect and buffer audio, and the Read() implementation would dequeue the appropriate amount of data whenever it's available. When you want to stop, waiting for StopContinuousRecognitionAsync will end the current recognition but *not* stop buffering the audio, meaning the next call to Start (whether it's milliseconds or minutes later) would pick right back up where the last recognition ended.

With the above, a possible alternative to stopping and restarting would be to use the "release" signal to tell that stream implementation to read a second or two of artificial silence (requested arrays filled with 0s) such that the recognition would end "naturally" before resuming again. That'd possibly provide an easier integration, but may have some unexpected recognition results if the forced stop happened right in the middle of a word or similar -- stop/restart handles this a bit more gracefully.

**Comment by sibbl** [comment]
@trrwilson thanks a lot for the quick and detailed response.

For (1), I can confirm that setting the `InitialSilenceTimeoutMs` and `EndSilenceTimeoutMs` to a high value works as intended. However, I cannot really disable end of speech recognition, is this correct? Is there anything better than these 2 workarounds?
1. Set `SegmentationSilenceTimeoutMs` to 5000, so it only detects really long speech gaps.
2. Simply collect all recognitions within the same "button push" and then concatenate them. So multiple recognitions within one "button push" (where I didn't release anything) end up in one single string again.

For (2), it indeed made a huge difference to use a pull stream instead of a push stream. Seems like pushing audio gets lost somewhere in between. 

However, some words from the first button push still end up being detected in the second button push. I'm not sure where the problem is: all the audio bytes are definitely being read before I call `StopContinuousRecognitionAsync`. I assume that this is currently caused by my small prototype application, where I get 4 raw wav files, send 20ms chunks without any delay and call the "release" after each file. With some "artificial" delays, it works fine and I assume it will as well in real life scenarios.

Please let me know if you're interested in further findings and/or the small prototype application's source code. If not, I'd suggest to close the comment if you don't need it for tracking the (probably minor) documentation updates on your side.

Thanks again! 👍

**Comment by pankopon** [comment]
Closing the item as it's understood a working solution was found. Please open a new issue if more support is needed.
