### ISSUE TITLE
Python STT AutoDetectSourceLanguageConfig does not work?

### ISSUE THREAD

**Issue by bbence84** [Azure-Samples/cognitive-services-speech-sdk#1798]
**Describe the bug**
Seems that even if I specify multiple languages in the AutoDetectSourceLanguageConfig, speech to text only recognizes the first language specified. 

**To Reproduce**
I tried the following to approaches, none of them worked (only the first language seems to used for recognition):

```
src_lang_hu = speechsdk.languageconfig.SourceLanguageConfig(language="hu-HU")
src_lang_en = speechsdk.languageconfig.SourceLanguageConfig(language="en-US")
auto_src_lang_config = speechsdk.languageconfig.AutoDetectSourceLanguageConfig(sourceLanguageConfigs=[src_lang_en, src_lang_hu])
speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config_input, auto_detect_source_language_config=auto_src_lang_config)

```
OR

```
auto_src_lang_config = speechsdk.languageconfig.AutoDetectSourceLanguageConfig(languages=["hu-HU", "en-US"])
speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config_input, auto_detect_source_language_config=auto_src_lang_config)
```

(In the speech config SpeechConfig object, I did remove the speech_recognition_language)

**Expected behavior**
All specified languages are considered and detected.

**Version of the Cognitive Services Speech SDK**
Latest Python SDK

**Platform, Operating System, and Programming Language**
 - OS: DietPi OS
 - Hardware: ARM64 RPi4
 - Programming language: Python
 -

**Comment by trrwilson** [comment]
Would it be possible to capture and share an SDK log when this happens, per the instructions here?
https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

That could help us quickly see if request payloads match expectations.

**Comment by dargilco** [comment]
@bbence84 does your audio include a single sentence or multiple sentences? If it's multiple sentences, are the sentences from multiple languages (some in Hungarian, some in English), or are all sentences from the same language (one of the two).
Please also provide your (simplified) source code exhibiting the issue with an example WAV file.
Thanks,
Darren

**Comment by pankopon** [comment]
Closed since no update, please open a new issue if more support is needed.
