### ISSUE TITLE
how to recognise sentence by sentence

### ISSUE THREAD

**Issue by yangzhongke** [Azure-Samples/cognitive-services-speech-sdk#180]
I use CognitiveServices.Speech to recognise a long audio file.
When the Recognized event fired,I got a long sentence.like:
"We live in the age of travel and a country of travelers Australians love to travel overseas and there are also millions of overseas tourists. Visiting Australia each year. This means a huge task for Corentin. Here are just some of the corentine tasks that happen at international passenger terminals around Australia each."

How can I get them sentence by setence instead of as a whole one.
I'm afraid that "Splitting the string by s.Split('.')" is not a good idea,because I want to get Duration and OffsetInTicks of each sentence.

thanks!

**Comment by madkote** [comment]
Sentences are recognized by silence.
you need to use continuous recognition and register callback for `speech_recognizer.recognized.connect(on_recognized)`. Then you get your sentences.
