### ISSUE TITLE
TTS: English pronunciation of words in German

### ISSUE THREAD

**Issue by luksurious** [Azure-Samples/cognitive-services-speech-sdk#1801]
**Describe the bug**
When pronouncing common words like “Coca Cola”, “Demo” and “Assistance” at the end of a sentence, there is inconsistency in the pronunciation when the selected language is German (Germany) and the selected voice is either Katja (Neural) or Conrad (Neural). The problem is not present in the newer voices (e.g. Amala, Bernd, …).

Depending on the capitalization and the presence of a period at the end of the sentence, the pronunciation is either German or English:

The word “Coca-cola”
* Coca Cola. -> English Pronunciation
* Coca-Cola. -> English Pronunciation
* coca cola. -> English Pronunciation
* Coca-cola. -> English Pronunciation
* Coca-cola. -> German Pronunciation
* coca cola -> German Pronunciation
* Coca Cola -> German Pronunciation

The word “Demo”
* Dies ist die Live-Demo. -> German Pronunciation
* Dies ist die Live Demo. -> English Pronunciation
* Dies ist die live demo -> English Pronunciation
* Dies ist die Live Demo -> English Pronunciation
* Dies ist die live-demo -> different English pronunciation

The word “Assistance”
* Assistance. -> English Pronunciation
* assistance -> English Pronunciation
* Deutsche Assistance. -> English Pronunciation
* Deutsche assistance. -> German Pronunciation
* deutsche assistance -> German Pronunciation

**To Reproduce**
1. Paste “coca cola. coca cola" to the [Azure TTS demo page](https://azure.microsoft.com/en-us/products/cognitive-services/text-to-speech) as text.
2. Select German as language and Katja (Neural)/Conrad (Neural)  as voice.
3. Press the Play button and listen.

**Expected behavior**
The pronunciation of the words should be consistently German and not change depending on their position. 

**Version of the Cognitive Services Speech SDK**
Presumably latest version when using the TTS demo page, but also in our system using version 1.19.0

https://user-images.githubusercontent.com/1231010/213438812-60ca67ad-a8a3-40c9-a563-ae64d926fed8.mp4

**Comment by rhurey** [comment]
@yulin-li can you have a look at this?

**Comment by yulin-li** [comment]
Thank you @luksurious for using Azure TTS and reporting this issue. I forwarded this to the right engineers for investigating. But they are taking holidays for Chinese new year it may take a longer time.

**Comment by bayesrule** [comment]
Thank you @luksurious for reporting this issue. We're looking into this and will fix ASAP. In the meantime, you can use SSML language tag to wrap the word/phrase with the language you like. For SSML language tag, please refer to https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup-voice#adjust-speaking-languages

**Comment by pankopon** [comment]
@bayesrule Please update with the latest status.

**Comment by pankopon** [comment]
Internal work item ref. 4835613.

**Comment by pankopon** [comment]
@bayesrule @yulin-li Based on the work item 4835613 a fix has been made, is it already deployed? If yes then we can close this.

**Comment by bayesrule** [comment]
@pankopon deployed, please close.

**Comment by bayesrule** [comment]
@lukas-parloa it looks like part of my original fix got reverted by accident for unknow reason. I'll fix again and sync to Conrad as well.

And again, in the meantime, you can always use SSML language tag to wrap the word/phrase with the language you like. For SSML language tag, please refer to https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup-voice#adjust-speaking-languages

**Comment by pankopon** [comment]
@bayesrule Can you please confirm if the fix has been deployed by now?

**Comment by pankopon** [comment]
@bayesrule Has the fix been deployed?

**Comment by Kerry-LinZhang** [comment]
Hi @pankopon Yes, the fix has been deployed, please try it and any further feedback, please feel free to let us know

**Comment by glecaros** [comment]
Closing the issue as the service fix is already deployed. @luksurious thanks for reporting the issue and please open a new issue if you need any help.
