### ISSUE TITLE
Unclear how to activate noise reduction in python.

### ISSUE THREAD

**Issue by OGHinde** [Azure-Samples/cognitive-services-speech-sdk#1803]
Hello. I'm trying to activate noise reduction in a speech to text application written in python but the documentation is very obscure. I know in java scrpit this can be achieved by calling setServiceProperty('NoiseReduction', 'Enhanced'). 

In python, I've gotten as far as finding the speechsdk.audio.PropertyId.AudioConfig_AudioProcessingOptions property, but I'm not sure what method I must call to set it. AudioConfig has no set_property() method and SpeechConfig won't accept it as a valid property.

Any tips? Thanks in advance.

**Comment by rhurey** [comment]
Assuming you're calling setServiceProperty on a SpeechConfig object, the equivalent in python would be set_service_property on the SpeechConfig object.

If that's not it, could you provide some more context about the scenario?
