### ISSUE TITLE
Get Audio Device ID in Python on Mac OS

### ISSUE THREAD

**Issue by hendryman** [Azure-Samples/cognitive-services-speech-sdk#1805]
I would like to set the microphone from Python on a Mac by using
`audio_config = AudioConfig(device_name="<device id>");`
as per the [official Speech Service docs](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-select-audio-input-devices).

However, the example code given to **get** the Device ID is only available for C++. 

What is the equivalent in python?

**Comment by pankopon** [comment]
Hi, in case the question is still valid - one option is portaudio (see https://stackoverflow.com/questions/20760589/list-all-audio-devices-with-pythons-pyaudio-portaudio-binding) although it may need a specific build. Alternatively you could parse `/Library/Preferences/Audio/com.apple.audio.DeviceSettings.plist` (xml) for the info.

We also have a work item on the backlog to add a way of reading audio device IDs from the Speech SDK, but currently there is no plan for implementation.

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
