### ISSUE TITLE
STT: Phrase List in English not working as expected with names

### ISSUE THREAD

**Issue by lukas-parloa** [Azure-Samples/cognitive-services-speech-sdk#1806]
**Describe the bug**
Phrase Lists do not get matched with similar sounding names in English (USA). For example, if the Phrase List is set to “Jon”, the service still transcribes “John”. Some more examples are given below. The same behavior is observed using English (United Kingdom).

This was tested both in the [Azure Cognitive Services Speech Studio](https://speech.microsoft.com/portal), and through a custom application using the JavaScript SDK.
Interestingly, one can see that the correct spelling of the names is present in the intermediate results often, but the final recognition seems to revert to a different spelling.
Also, when saying only the names, i.e., not embedding them in a sentence, the probability increases significantly.

Using the German STT, the results with Phrase Lists and names are much more consistent.

**To Reproduce**

1. Visit the Azure Cognitive Services Speech Studio 
2. Click on Real Time Speech to Text
3. Under “Use with your resource” click on “Show Advanced Options”
4. In the Phrase List enter the text as described per test case below
5. Record with microphone/drop a file that contains the test sentence
6. Check the STT transcript.

**Test cases**

***Jon***

* Phrase List: “Jon, Seifert, Jon Seifert”
* Utterance: “My name is Jon Seifert”
* Output: “My name is John Seifert”

Audios: 
* https://stproductsharingwesteu.blob.core.windows.net/github-share/jon-seifert-1.wav
* https://stproductsharingwesteu.blob.core.windows.net/github-share/jon-seifert-2.wav

***Sjoerd***

* Phrase List: “Sjoerd”
* Utterance: “Hi, I’m Sjoerd”
* Output: “Hi I’m short/Stuart”

Audios:
* https://stproductsharingwesteu.blob.core.windows.net/github-share/sjoerd-1.wav
* https://stproductsharingwesteu.blob.core.windows.net/github-share/sjoerd-2.wav

***Kantzow***

* Phrase List: “Hans;Kantzow;Hans Kantzow”
* Utterance: “I’m Hans Kantzow”
* Output: “I’m Hans cancel”

Audios:
* https://stproductsharingwesteu.blob.core.windows.net/github-share/hans-kantzow.wav

**Comment by jhakulin** [comment]
@lukas-parloa Thanks for the report, I am checking with relevant service engineers to see if there are any solution to your issue.

**Comment by ut-karsh** [comment]
Hi @lukas-parloa, thanks a lot for surfacing this! This is a known bug for some corner cases. The fix is underway with an ETA by the end of April. Please let me know if you have any other questions.

**Comment by tbonebehr** [comment]
Hey there, just wondering if there is any update on whether this fix will be done in the next couple of weeks...? Thanks for any information that can be provided!

**Comment by ut-karsh** [comment]
Hi @tbonebehr, thank you for reaching out. We're still working towards the update and I will make sure to update this thread when we make it available. If you have any other questions or concerns, please don't hesitate to ask.

**Comment by MurlocTW** [comment]
The situation has also occurred in Traditional Chinese.

**Comment by dargilco** [comment]
Closing this issue, but @ut-karsh please mention any updates when available.
