### ISSUE TITLE
Python -  how to perform speech-to-text using BlobClient without saving a file.

### ISSUE THREAD

**Issue by decadance-dance** [Azure-Samples/cognitive-services-speech-sdk#1807]
Hello, I am using azure python sdk to perform speech-to-text on my data. 
I am getting files from azure blob storage. These files can be either mp3 or wav. But in this case, I will only talk about wav.
I don't save (write) files locally. I do not need it. I can't figure out how to correctly pass the file object that I receive to the stream. I really looked at a lot of topics here, but nothing helped me.
```
sas_url = "..."
blob_client = BlobClient.from_blob_url(sas_url)
blob = blob_client.download_blob()  # type: <class 'azure.storage.blob._download.StorageStreamDownloader'>

speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)

stream = speechsdk.audio.PushAudioInputStream()
audio_config = speechsdk.audio.AudioConfig(stream=stream)
speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)

done = False
def stop_cb(evt: speechsdk.SessionEventArgs):
      """callback that signals to stop continuous recognition upon receiving an event `evt`"""
      print('CLOSING on {}'.format(evt))
      nonlocal done
      done = True

speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))
speech_recognizer.session_stopped.connect(stop_cb)
speech_recognizer.canceled.connect(stop_cb)

blob.download_to_stream(stream)          # OR stream.write(blob.readall()) OR blob.readinto(stream)

speech_recognizer.start_continuous_recognition()
while not done:
      time.sleep(.5)
speech_recognizer.stop_continuous_recognition()
```
As you can see from the code, I tried different options `blob.download_to_stream(stream)   OR   stream.write(blob.readall())   OR  blob.readinto(stream)`, but any of them gives the same behavior.
_Received behavior:_
The session starts. Every time interval, `recognized` event occurs with an empty text field. And this continues indefinitely until I abort the execution.
Here is an example of a log:
```
SESSION STARTED: SessionEventArgs(session_id=4a3868fa310d4e488855b0c92c5ab979)
RECOGNIZED: SpeechRecognitionEventArgs(session_id=4a3868fa310d4e488855b0c92c5ab979, result=SpeechRecognitionResult(result_id=f862b2737bf042249c86f12ab650fed5, text="", reason=ResultReason.RecognizedSpeech))
RECOGNIZED: SpeechRecognitionEventArgs(session_id=4a3868fa310d4e488855b0c92c5ab979, result=SpeechRecognitionResult(result_id=2edc265377894e82b780deecf7730aa9, text="", reason=ResultReason.RecognizedSpeech))
```
I hope somebody will help. Peace for everyone.

**Comment by ralph-msft** [comment]
What is sampling rate, bits per sample, and number of channels in the wave file you are trying to download as a blob? By default a push audio input stream assumes 16KHz, 16 bits/sample, and mono (single channel) audio. If your audio file differs from this, you'll need to explicitly specify the [AudioStreamFormat ](https://learn.microsoft.com/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.audio.audiostreamformat?view=azure-python) in your call to ```speechsdk.audio.PushAudioInputStream(...)```.

In addition, calling ```blob.download_to_stream(stream)```, nor ```blob.readinto(stream)``` will work since the PushAudioInputStream is neither a file handle nor a writable stream in the way the Azure Blob SDK expects.

Instead, you will need to read from the blob and write the to stream in a loop. You can see an example of how to do this here:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_sample.py#L555

**Comment by ralph-msft** [comment]
Generally speaking you should avoid recasting to/from different audio formats. Doing so could easily introduce audio artifacts that can significantly reduce the quality of the speech to text recognitions.

You can find more information about the supported WAV audio formats here:
https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-use-audio-input-streams
For WAV audio files, you can determine the sampling rate, bits per sample, and number of channels from the WAV file header at the start of each .wav file (usually first 44 bytes). You can use PyAudio to extract this information:
https://people.csail.mit.edu/hubert/pyaudio/docs/

Compressed audio formats are also supported. You can find more information here:
https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams?pivots=programming-language-python

For your scenario though, you may want to consider using batch transcription. This supports performing speech to text on audio files stored in Azure Blob Storage and can handle different formats:
https://learn.microsoft.com/azure/cognitive-services/speech-service/batch-transcription
