### ISSUE TITLE
TTS with captions?

### ISSUE THREAD

**Issue by sy-huss** [Azure-Samples/cognitive-services-speech-sdk#1809]
I have generated multiple audio files, but it has occurred to me that when I run TTS, can I also output SRT captions?

**Comment by ralph-msft** [comment]
You may be able to use the SpeechSynthesizer.WordBoundary events to generate the SRT captions yourself.

There is some sample code for generating SRT captions from speech to text recognitions that might be helpful to you:
https://learn.microsoft.com/azure/cognitive-services/speech-service/captioning-quickstart

**Comment by yulin-li** [comment]
We have samples for generation SRT from TTS word boundary events too https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechSynthesisSamples.java#L705

The sample is only available in Java, you can re-write using your own language.
