### ISSUE TITLE
BatchSynthesisSample | Error - Unsupported output format audio-24khz-48kbitrate-mono-mp3.

### ISSUE THREAD

**Issue by sushantjadhav21** [Azure-Samples/cognitive-services-speech-sdk#1813]
BatchSynthesisSample is throwing the error below for audio-24khz-48kbitrate-mono-mp3 output format.

{
  "code": "InvalidRequest",
  "message": "Unsupported output format audio-24khz-48kbitrate-mono-mp3.",
  "innerError": {
    "code": "InvalidPayload",
    "message": "Unsupported output format audio-24khz-48kbitrate-mono-mp3."
  }
}

**Expected behavior**
As per the MS documentation audio-24khz-48kbitrate-mono-mp3 is correct output format. BatchSynthesis should not throw exception for it.

**Version of the Cognitive Services Speech SDK**
I am using the BatchSynthesis REST API - /api/texttospeech/3.1-preview1/batchsynthesis

**Comment by yulin-li** [comment]
Thanks for using batch synthesis and reporting this issue. We are investigating.

**Comment by yulin-li** [comment]
Hi, we confirmed this bug and the fix ETA is about two weeks. I will update this issue after the fix done

**Comment by yulin-li** [comment]
The issue should be fixed now. Closing this issue.
