### ISSUE TITLE
Using SegmentationSilenceTimeoutMs from Python

### ISSUE THREAD

**Issue by hendryman** [Azure-Samples/cognitive-services-speech-sdk#1814]
I try to configure one-shot speech recognition for speakers with longer (5s) pauses. In Python, I use:

`speech_config.set_property(speechsdk.PropertyId.SpeechServiceConnection_SegmentationSilenceTimeoutMs, 5000)`

However, Python gives me an error:

`Using AttributeError: SpeechServiceConnection_SegmentationSilenceTimeoutMs. Did you mean: 'SpeechServiceConnection_InitialSilenceTimeoutMs`

What is the correct Python syntax to address  to set `SegmentationSilenceTimeoutMs`?

**Comment by chschrae** [comment]
Hi there! Thanks for reaching out.

I believe the property you are looking for is titled ` SpeechServiceConnection_EndSilenceTimeoutMs ` could you try that?

**Comment by hendryman** [comment]
Thanks. I've tried `SpeechServiceConnection_EndSilenceTimeoutMs` with up to 10'000 ms but I keep getting the same results: recording stops after about 1.5 sec pause. `SpeechServiceConnection_InitialSilenceTimeoutMs` works fine, so I really wonder where the problem is... any idea?

**Comment by hendryman** [comment]
[This reply](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1804#issuecomment-1405718759) from @ralph-msft linked to a Microsoft [doc page](https://learn.microsoft.com/en-gb/azure/cognitive-services/speech-service/how-to-recognize-speech?pivots=programming-language-csharp#change-how-silence-is-handled) that mentioned `SegmentationSilenceTimeoutMs` but not `SpeechServiceConnection_InitialSilenceTimeoutMs`.  And [this page](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/505) says `SpeechServiceConnection_InitialSilenceTimeoutMs` does not work at all... 

Any clarification/solution would be much appreciated. Thanks!

**Comment by chschrae** [comment]
Oh I think the python property does not have the service name. It should be `Speech_SegmentationSilenceTimeoutMs` could you try that?

**Comment by hendryman** [comment]
That's it, thanks you. It works now!
For posterity:
`speech_config.set_property(speechsdk.PropertyId.Speech_SegmentationSilenceTimeoutMs, "5000")`
(value between 100 and 5000)

Seems like `SpeechServiceConnection_InitialSilenceTimeoutMs` does nothing, would be good to update that fact in the docs.

**Comment by chschrae** [comment]
Great! 

InitialSilenceTimeouts should change how long silence could be sent at the beginning of a recognition before the service shuts you off and says "nothing was recognized"

**Comment by hendryman** [comment]
yes, sorry - I meant `SpeechServiceConnection_EndSilenceTimeoutMs`. Thanks again!
