### ISSUE TITLE
Writing Audio to Disk when using recognize_once_async().get()

### ISSUE THREAD

**Issue by hendryman** [Azure-Samples/cognitive-services-speech-sdk#1815]
Is there any mechanism by which I can capture the audio analyzed while using `recognize_once_async().get()` and write it to disk?

**Comment by chschrae** [comment]
Hi there! Thanks for reaching out to us.

It is a bit complicated but this should be possible in 2 ways:

First you could enable audio logging in the service and then retrieve the audio logs. There is another answer here that describes it: https://learn.microsoft.com/en-us/answers/questions/267038/file-location-when-audio-logging-is-enabled-in-spe

Secondly, you could capture the audio yourself and write it to a file, and write it to the SDK using a stream. This would be a lot more code on your part, but would cut out the service. https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/cpp/windows/console/samples/speech_recognition_samples.cpp

**Comment by hendryman** [comment]
Thanks. I found a solution with PyAudio - see my post here: https://stackoverflow.com/a/75273974/21052377
