### ISSUE TITLE
sample code failing on real device 

### ISSUE THREAD

**Issue by guris12** [Azure-Samples/cognitive-services-speech-sdk#1817]
I am trying to run sample code on real device , apple iPhone 14 , running iOS 16 but it is giving error , cancelled, detail: Error decoding audio stream, error code: -50 

But the same code is running on Simulator ? 

can Any one help

**Comment by chschrae** [comment]
Hi @guris12 , I'd be glad to help. 

Can you tell me which sample you are running? And any changes you have made to the sample for your case? Thanks.

**Comment by guris12** [comment]
HI 

I am running code , "Quickstart: Synthesize audio in Swift on iOS using the Speech SDK" 

I am running on iPhone 14 running iOS 16 

I read a few other issue which people were facing and have made the changes  setSpeechSynthesisOutputFormat(raw8Khz16BitMonoPcm) and now the code is working fine ....

Thanks

**Comment by chschrae** [comment]
Glad you got it working. Feel free to reach out if you have any questions.
