### ISSUE TITLE
How to enable displayFormWordLevelTimestampsEnabled in python sdk?

### ISSUE THREAD

**Issue by qGentry** [Azure-Samples/cognitive-services-speech-sdk#1818]
Is there a way to enable displayFormWordLevelTimestampsEnabled in python sdk? I've digged into source code to check how similar wordLevelTimestampsEnabled is implemented:
```
    def request_word_level_timestamps(self):
        """
        Includes word level timestamps in response result.

        .. note::
          Added in version 1.5.0.

        """
        self.set_property(PropertyId.SpeechServiceResponse_RequestWordLevelTimestamps, "true") 
```
ProperyID is a enum with seems to be random numbers (for example, `PropertyId.SpeechServiceResponse_RequestWordLevelTimestamps` equals `4004`). How can i patch sdk/find value for corresponding to displayFormWordLevelTimestampsEnabled property to enable this feature in python sdk?

**Comment by chschrae** [comment]
Hi @qGentry , thanks for asking. You should be able to set the property on the speech config object. That enum is there as an easy way for users to identify which property they would like to set.

`config.set_property(SpeechServiceResponse_RequestWordLevelTimestamps, "true")`

Let me know if that doesn't work and we can dig into your issue more comprehensively.

**Comment by qGentry** [comment]
@chschrae the example above is to set property "wordLevelTimestampsEnabled" to true, this is easy and implemented in python SDK while i need to set property "displayFormWordLevelTimestampsEnabled" to true which is different and was added recently in 3.1 rest api. The problem is that there is no corresponding field in PropertyID class so i can't use config.set_property(..., "true")

**Comment by chschrae** [comment]
@qGentry My mistake. 

I'm only seeing that property as available for batch transcription. If you are doing batch transcription you should use the REST API directly (not using the SDK) which would allow you to set the property. Is that what you are trying to do?

**Comment by qGentry** [comment]
Okay, i'll use rest api directly then :(
