### ISSUE TITLE
Speech recognition fails on Linux with SPXERR_AUDIO_SYS_LIBRARY_NOT_FOUND

### ISSUE THREAD

**Issue by simonziegler** [Azure-Samples/cognitive-services-speech-sdk#1820]
**Describe the bug**
I have followed your examples closely and can successfully run speech to text (no translation, all in en-GB) running locally on my Windows dev machine (it's a great result by the way). When I deploy to Azure as a linux container, I get an exception thrown (see below) when I try to create a new `SpeechRecogniser`.

**To Reproduce**
Deploy an ASP.NET app to Azure Container Services using the `mcr.microsoft.com/dotnet/aspnet:7.0` linux container.

**Expected behaviour**
No exception!

**Version of the Cognitive Services Speech SDK**
1.25.0

**Platform, Operating System, and Programming Language**
 - OS: 5.10.155.1-1.cm1
 - Hardware - x64 I think
 - Programming language: C# / ASP.NET 7.0.2
 - Browser: Edge

**Additional context**

```
System.ApplicationException: Exception with an error code: 0x38 (SPXERR_AUDIO_SYS_LIBRARY_NOT_FOUND)
   at Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail(IntPtr hr)
   at Microsoft.CognitiveServices.Speech.Recognizer.FromConfig(GetRecognizerFromConfigDelegate fromConfig, SpeechConfig speechConfig)
   at Microsoft.CognitiveServices.Speech.SpeechRecognizer..ctor(SpeechConfig speechConfig)
```

I am unsure how to use your [logging](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging) because I don't have good access to the deployed container file system.

**Comment by chschrae** [comment]
Hi there! Thanks for asking about this.

Typically this is due to a dependency of the audio sys extension. Make sure you have installed on your container the libasound2 so it can access the microphone.

I've used this in my Dockerfile ` RUN apt-get update && apt-get install -y --no-install-recommends libasound2 `

Could you try that and see if it works?

**Comment by pankopon** [comment]
@simonziegler Was the information helpful, do you need more support? Please update, otherwise we'll close this issue in a few days.

**Comment by pankopon** [comment]
Closed as presumed resolved, please open a new issue if more support is needed.
