### ISSUE TITLE
Request to support HTTPS_PROXY

### ISSUE THREAD

**Issue by kmeng1219** [Azure-Samples/cognitive-services-speech-sdk#1825]
Request to support HTTPS_PROXY. 

Many scenarios request the client to have a secured connection to the proxy. Could you please support the https proxy for cognitive services?

Related Q&A: https://learn.microsoft.com/en-us/answers/questions/1168161/does-azure-cognitive-services-support-https-proxy

**Comment by pankopon** [comment]
Hi, we actually have a work item on the backlog for this and other Azure SDK proxy environment variables, but no ETA so far.

**Comment by pankopon** [comment]
Internal work item no. 3061478.

**Comment by pankopon** [comment]
Closing this as there's a work item for this feature, no ETA. We'll update the status here when there is a release plan.
