### ISSUE TITLE
Exception with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED) in azure  (win10)

### ISSUE THREAD

**Issue by sihaixuan** [Azure-Samples/cognitive-services-speech-sdk#1827]
python test code:
        speechConfig = speechSdk.SpeechConfig(subscription=self._accessKey, region=self._region) 
        speechConfig.speech_synthesis_language = "zh-CN"
        audioConfig = speechSdk.audio.AudioOutputConfig(filename=cachePath)
        speecher = speechSdk.SpeechSynthesizer(speech_config=speechConfig, audio_config=audioConfig)

traceback log:
  speecher = speechSdk.SpeechSynthesizer(speech_config=speechConfig, audio_config=audioConfig)
  File "D:\dev\python38\venv\common\lib\site-packages\azure\cognitiveservices\speech\speech.py", line 2147, in __init__
    _call_hr_fn(fn=_sdk_lib.synthesizer_create_speech_synthesizer_from_config, *[
  File "D:\dev\python38\venv\common\lib\site-packages\azure\cognitiveservices\speech\interop.py", line 62, in _call_hr_fn
    _raise_if_failed(hr)
  File "D:\dev\python38\venv\common\lib\site-packages\azure\cognitiveservices\speech\interop.py", line 55, in _raise_if_failed
    __try_get_error(_spx_handle(hr))
  File "D:\dev\python38\venv\common\lib\site-packages\azure\cognitiveservices\speech\interop.py", line 50, in __try_get_error
    raise RuntimeError(message)
RuntimeError: Exception with error code: 
[CALL STACK BEGIN]

    > pal_string_to_wstring
    - pal_string_to_wstring
    - synthesizer_create_speech_synthesizer_from_config
    - synthesizer_create_speech_synthesizer_from_config
    - ffi_prep_go_closure
    - ffi_call_go
    - ffi_call
    - 00007FFE3B173E42 (SymFromAddr() error: 试图访问无效的地址。)
    - 00007FFE3B173B55 (SymFromAddr() error: 试图访问无效的地址。)
    - 00007FFE3B1738B2 (SymFromAddr() error: 试图访问无效的地址。)
    - PySequence_GetItem
    - PyEval_EvalFrameDefault
    - PyEval_EvalCodeWithName
    - PyFunction_Vectorcall
    - PyVectorcall_Call
    - PySequence_GetItem

[CALL STACK END]

Exception with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED)

Version: azure-cognitiveservices-speech 1.24.2

**Platform, Operating System, and Programming Language**
 - OS: Win10 Professional
 - Hardware - x64
 - Programming language:  Python

**Comment by pankopon** [comment]
@sihaixuan Hi, what is the value of `cachePath`? Please provide also a log file: https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging

**Comment by pankopon** [comment]
Since there's been no update - in general this error can occur if a file path contains non-Latin characters (e.g. Chinese). So please avoid those in Speech SDK input/output file/folder path names.

**Comment by pankopon** [comment]
Closing the item, please open a new issue if further support is needed.
