### ISSUE TITLE
Windows 7 Fail

### ISSUE THREAD

**Issue by brutm** [Azure-Samples/cognitive-services-speech-sdk#183]
The application when i call RecognizeOnceAsync() to start recognizing, the application show me the following error:

CANCELED: Reason=Error
CANCELED: ErrorCode=ConnectionFailure
CANCELED: ErrorDetails=Connection failed (no connection to the remote host). Internal error: 8. Error details: 998. Please check network connection, firewall setting, and the region name used to create speech factory.
CANCELED: Did you update the subscription info?

This works on windows 10. 

I tried in different windows 7 machines with SP1 and all updates installed (i need this working in windows 7 enterprise x86). The connection is working and i tried to call the api by curl and i can connect successfully. All firewalls are down. I tried with dot.net 4.7.1 and 4.6.1 with the last version of Microsoft.CognitiveServices.Speech 1.3.1 and tried all versions downgrading to 1.0.0 but i have the same problem.

**Comment by wolfma61** [comment]
sorry for you trouble. Windows 7 is not a supported platform of the SDK
I don't have a Windows7 version available to test.

thx
Wolfgang
