### ISSUE TITLE
Python sample returns empty results for transcription

### ISSUE THREAD

**Issue by d-Rickyy-b** [Azure-Samples/cognitive-services-speech-sdk#1831]
**Describe the bug**
I am using the [transcription_sample.py](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/transcription_sample.py) and tried to transcribe the `en-us_zh-cn.wav` file. Sadly I am not able to get any results.

On the one hand, the text within `ConversationTranscriptionResult` is empty, on the other hand I receive `ResultReason.Canceled`.

I'd appreciate any help.

**To Reproduce**
See above.

**Expected behavior**
I expected to receive transcription results, but I am not receiving any result.

**Version of the Cognitive Services Speech SDK**
azure-cognitiveservices-speech==1.24.2

I also tested 1.25.0 - same result.

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - x64
 - Programming language: Python
 - Browser: N/A

**Additional context**
 - Error messages, stack trace, sample code to reproduce the issue, ...
 ```
Conversation ID: 98aba0af-69e5-4af1-8c6c-74a5ec2dc487
SESSION STARTED: SessionEventArgs(session_id=0cde6591651e43d1941fbf2365813386)
TRANSCRIBED: ConversationTranscriptionEventArgs(session_id=0cde6591651e43d1941fbf2365813386, result=ConversationTranscriptionResult(result_id=aef2063e138748a09b9f38ae9c62ca6f, user_id=Guest_0, utterance_id=1_Guest_0_400000, text=, reason=ResultReason.RecognizedSpeech))
CANCELED ConversationTranscriptionCanceledEventArgs(session_id=0cde6591651e43d1941fbf2365813386, result=ConversationTranscriptionResult(result_id=aaf99ffcd8984dec8c0833021bab6898, user_id=, utterance_id=, text=, reason=ResultReason.Canceled))
CLOSING ConversationTranscriptionCanceledEventArgs(session_id=0cde6591651e43d1941fbf2365813386, result=ConversationTranscriptionResult(result_id=aaf99ffcd8984dec8c0833021bab6898, user_id=, utterance_id=, text=, reason=ResultReason.Canceled))
SESSION STOPPED SessionEventArgs(session_id=0cde6591651e43d1941fbf2365813386)
CLOSING SessionEventArgs(session_id=0cde6591651e43d1941fbf2365813386)
```
 - Please provide full Speech SDK Log, as per the instructions [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging)? -> [speechsdk.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/10703543/speechsdk.log)
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive. -> session_id=0cde6591651e43d1941fbf2365813386 / 10.02.2023 ~04:55 UTC+1

**Comment by jhakulin** [comment]
@d-Rickyy-b Thanks for the report. Based on the log, the audio format looks to be 2-channels, 16kHz. 

The ConversationTranscriber is unfortunately currently in preview state and do not support all channel configurations.

The sample there is configured for 8 channels audio, which should work, however I would recommend joining to conversation transcriber single channel private preview by sending email to diarizationrequest@microsoft.com.

If you try with single channel configuration (1-channel. 16kHz), you will get an error message from the API that asks you to join to this private preview.

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
