### ISSUE TITLE
Maui App Released for IOS and I have get this Issue Error

### ISSUE THREAD

**Issue by MahmoudFareed** [Azure-Samples/cognitive-services-speech-sdk#1835]
I used this Microsoft.CognitiveServices.Speech when Released for IOS and I have get this Issue Error:
clang++ exited with code 1: Undefined symbols for architecture arm64: "_AudioConverterDispose", referenced from: l002 in libMicrosoft.CognitiveServices.Speech.core.a(apple_codec_adapter.cpp.o) "_AudioConverterFillComplexBuffer", referenced from: l002 in libMicrosoft.CognitiveServices.Speech.core.a(apple_codec_adapter.cpp.o) "_AudioConverterGetProperty", referenced from: l002 in libMicrosoft.CognitiveServices.Speech.core.a(apple_codec_adapter.cpp.o) "_AudioConverterNew", referenced from: l002 in libMicrosoft.CognitiveServices.Speech.core.a(apple_codec_adapter.cpp.o) "_AudioQueueAddPropertyListener", referenced from: audio_output_create_with_parameters(_AUDIO_SETTINGS*) in libMicrosoft.CognitiveServices.Speech.core.a(audio_sys.cpp.o) "_AudioQueueAllocateBuffer", referenced from: audio_input_create_with_parameters(_AUDIO_SETTINGS*) in libMicrosoft.CognitiveServices.Speech.core.a(audio_sys.cpp.o) _audio_output_startasync in libMicrosoft.CognitiveServices.Speech.core.a(audio_sys.cpp.o)

**Comment by jhakulin** [comment]
@MahmoudFareed Could you let us know the Speech SDK version you have ? 
Also could you confirm you meet the prerequisites described in https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/csharp/maui/speech-to-text ?

**Comment by MahmoudFareed** [comment]
> @MahmoudFareed Could you let us know the Speech SDK version you have ? Also could you confirm you meet the prerequisites described in https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/csharp/maui/speech-to-text ?
 
**1.25.0 SDK version,
it is worked 100% when Debug but when released for IOS i have that error**

**Comment by jhakulin** [comment]
@MahmoudFareed Thanks for the information and sorry about the issue with the Release version.

Release version of IOS MAUI project is configured differently for linking and AudioToolbox component does not get linked to the app.

To fix the issue, you can do either one of the following.

1. Change Release Link setting under project properties ->IOS->Build to "Don't Link"

![image](https://user-images.githubusercontent.com/16473503/219487651-93d1cbb8-b37d-4c70-a151-8a9d1575af3e.png)

2. Keep Link setting for Release as "Link Framework SDKs Only" and add following mtouch arguments to the csproj file for net7.0-ios
```
<PropertyGroup Condition="'$(TargetFramework)'=='net7.0-ios'">
      <MtouchExtraArgs>-gcc_flags="-framework AudioToolbox"</MtouchExtraArgs>
</PropertyGroup>
```
We will update the MAUI sample for this. Thanks for reporting the issue!

**Comment by jhakulin** [comment]
Internal workitem ref: 4900377

Closing the issue, let us know if more help is needed.

**Comment by MahmoudFareed** [comment]
> Internal workitem ref: 4900377
> 
> Closing the issue, let us know if more help is needed.

> @MahmoudFareed Thanks for the information and sorry about the issue with the Release version.
> 
> Release version of IOS MAUI project is configured differently for linking and AudioToolbox component does not get linked to the app.
> 
> To fix the issue, you can do either one of the following.
> 
>     1. Change Release Link setting under project properties ->IOS->Build to "Don't Link"
> 
> 
> ![image](https://user-images.githubusercontent.com/16473503/219487651-93d1cbb8-b37d-4c70-a151-8a9d1575af3e.png)
> 
>     2. Keep Link setting for Release as "Link Framework SDKs Only" and add following mtouch arguments to the csproj file for net7.0-ios
> 
> 
> ```
> <PropertyGroup Condition="'$(TargetFramework)'=='net7.0-ios'">
>       <MtouchExtraArgs>-gcc_flags="-framework AudioToolbox"</MtouchExtraArgs>
> </PropertyGroup>
> ```
> 
> We will update the NuGet (to include the setting) or MAUI sample for this. Thanks for reporting the issue!

**It is released now**,Thank you for help me @jhakulin

**Comment by dargilco** [comment]
@MahmoudFareed Speech SDK 1.26 was released with a fix related to the above issue. See (release notes](https://learn.microsoft.com/azure/cognitive-services/speech-service/releasenotes?tabs=speech-sdk).

**Comment by rburnashev85** [comment]
same issue for .NET 8
<MtouchExtraArgs>-gcc_flags="-framework AudioToolbox"</MtouchExtraArgs> works as workaround
