### ISSUE TITLE
my synthesizer doesn't get stopped

### ISSUE THREAD

**Issue by eduardoagr** [Azure-Samples/cognitive-services-speech-sdk#1836]
**Describe the bug**

**To Reproduce**
1. Create a simple WPF application with a UI with to buttons play and stop
2. Use this class and call each method accordingly

class

```
    SpeechSynthesizer speechSynthesizer;

        public async Task ReadOutLoudAsync(string text) {

            var key = ConstantsHelpers.AZURE_LANGUAGE_KEY;
            var endpoint = new Uri(ConstantsHelpers.AZURE_LANGUAGE_URL);

            AzureKeyCredential credentials = new(key);
            TextAnalyticsClient textClient = new(endpoint, credentials);

            Response<DetectedLanguage> response = textClient.DetectLanguage(text);

            DetectedLanguage lang = response.Value;

            var config = SpeechConfig.FromSubscription(
            ConstantsHelpers.AZURE_SPEECH_KEY,
            ConstantsHelpers.AZURE_SPEECH_REGION);


            string logFile = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "logFile.log");
            config.SetProperty(PropertyId.Speech_LogFilename, logFile);

            switch (lang.Iso6391Name) {
                case "en":
                    config.SpeechSynthesisVoiceName = "Microsoft Server Speech Text to Speech Voice (en-US, SaraNeural)";
                    config.SpeechSynthesisLanguage = "en-us";
                    break;
                case "es":
                    config.SpeechSynthesisVoiceName = "Microsoft Server Speech Text to Speech Voice (es-VE, PaolaNeural)";
                    config.SpeechSynthesisLanguage = "es-VE";
                    break;
                default:
                    break;
            }



            speechSynthesizer = new SpeechSynthesizer(config);
            await speechSynthesizer.StartSpeakingTextAsync(text);

        }


        public async Task StopSpeechAsync() {
            await speechSynthesizer.StopSpeakingAsync();
        }

```

Viewodel

 ```
private async Task StopSpeakButtonAction() {
            await AzureTextToSpeech.StopSpeechAsync();
            IsPlayingEnabled = true;
            IsStopEnabled = false;
        }

        private async Task SpeakButtonction() {
            await AzureTextToSpeech.ReadOutLoudAsync(Text!);
            IsPlayingEnabled = false;
            IsStopEnabled = true;
        }
```

UI

```
 <ComboBox
                VerticalAlignment="Center"
                ui:ControlHelper.PlaceholderText="{x:Static res:Lang.ColorSelect}"
                ItemsSource="{Binding ColorPairs}">
                <ComboBox.ItemTemplate>
                    <DataTemplate>
                        <StackPanel Orientation="Horizontal">
                            <Rectangle
                                Width="20"
                                Height="20"
                                Fill="{Binding Key}" />
                            <TextBlock
                                Margin="5,0,0,0"
                                Text="{Binding Value}" />
                        </StackPanel>
                    </DataTemplate>
                </ComboBox.ItemTemplate>
            </ComboBox>

            <Button
                Margin="10,0,0,0"
                Command="{Binding SpeakButtonCommand}"
                Content="{x:Static res:Lang.Read}"
                FocusVisualStyle="{x:Null}"
                IsEnabled="{Binding IsPlayingEnabled}" />

            <Button
                Margin="10,0,0,0"
                Command="{Binding StopSpeakButtonCommand}"
                Content="{x:Static res:Lang.Stop}"
                FocusVisualStyle="{x:Null}"
                IsEnabled="{Binding IsStopEnabled}" />
```

**Expected behavior**
I have a UI with two buttons play and pause.

The play buttons call my service, to read my text, but when I press the stop, even though I am calling await synthesizer.StopSpeakingAsync(); 

**Version of the Cognitive Services Speech SDK**
1.25.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 8.1, Windows 10 and 11
 - Hardware - x64, x86
 - Programming language: C#, WPF
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific

**Additional context**
 - Error messages, there is no error, it just does not stop

**Comment by yulin-li** [comment]
Could you please share the SDK log?

**Comment by eduardoagr** [comment]
How can I get the logs

**Comment by pankopon** [comment]
@eduardoagr Please see https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging - in brief, add right after your `var config = SpeechConfig.FromSubscription(...);` the following
```
config.SetProperty(PropertyId.Speech_LogFilename, "SpeechSDK.log");
```
Optionally you can add a path to some writable folder as a prefix to the filename; the default location is the application's current working directory (the output of `System.IO.Directory.GetCurrentDirectory()`).

**Comment by eduardoagr** [comment]
I did this

`   string logFile = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "logFile.log");
            config.SetProperty(PropertyId.Speech_LogFilename, logfile);`

and I cannot see the log file

Also I found out, that sometimes it will do it

**Comment by eduardoagr** [comment]
I did this

`   string logFile = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "logFile.txt");
            config.SetProperty(PropertyId.Speech_LogFilename, logfile);`

and I cannot see the log file

**Comment by eduardoagr** [comment]
[logFile.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/10832778/logFile.log)


The stranger part is that sometimes, it works and sometimes doesn't

Demo

https://reccloud.com/u/joxolbw

**Comment by pankopon** [comment]
@yulin-li Please review the log that was attached.

**Comment by eduardoagr** [comment]
any update on the error

**Comment by eduardoagr** [comment]
I just don't understand why the documentation says to call Stop, and it doesn't stop

**Comment by pankopon** [comment]
@yulin-li Can you please check and update.

**Comment by yulin-li** [comment]
sorry for the delayed reply, I will check ASAP.

**Comment by pankopon** [comment]
@yulin-li Any update?

**Comment by pankopon** [comment]
Closed since no update in 6 months -> either obsolete or unsupported. @yulin-li FYI
