### ISSUE TITLE
mts.v1.InputChannel websocket error code: 1013

### ISSUE THREAD

**Issue by huwenkai26** [Azure-Samples/cognitive-services-speech-sdk#1839]
use nodejs sdk error

{"privResultId":"5B2ADF0F28414C68A3F3395D5E00A2FB","privReason":1,"privErrorDetails":"Status(StatusCode=\"ResourceExhausted\", Detail=\"the duration of the data sent in `mts.v1.InputChannel websocket error code: 1013","privProperties":{"privKeys":["CancellationErrorCode"],"privValues":["ConnectionFailure"]}}

**Comment by pankopon** [comment]
Hi, is your use case the same as in https://learn.microsoft.com/answers/questions/1055465/text-to-speech-service-return-error-code-1013 ? If not then please add more information about what you are trying to do, not just the error message.

**Comment by pankopon** [comment]
Closed as presumed the same as an older case that's been answered, please open a new issue if more support is needed.
