### ISSUE TITLE
Unable to proceed to speech-to-text conversion

### ISSUE THREAD

**Issue by krisalay** [Azure-Samples/cognitive-services-speech-sdk#184]
Hello,
I am referencing to the sample at: [https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/node/speech.js](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/node/speech.js) for speech to text conversion.

But its behaving abruptly. Sometimes the process starts, and sometimes I get the following error.

```
SpeechRecognitionCanceledEventArgs {
  privSessionId: '3309E8B386C94CEEB733BB4ED8DA5895',
  privOffset: undefined,
  privReason: 0,
  privErrorDetails: undefined,
  privErrorCode: 6
}
```

What does this error mean, and how can I resolve it?

**Expected behavior**
The speech to text conversion should start.

**Version of the Cognitive Services Speech SDK**
1.3.0

**Platform, Operating System, and Programming Language**
 - OS: [linux-mint 18.04]
 - Hardware - x86
 - Programming language: Nodejs

Also, according to the documentation at: [https://docs.microsoft.com/en-gb/javascript/api/microsoft-cognitiveservices-speech-sdk/cancellationerrorcode?view=azure-node-latest](https://docs.microsoft.com/en-gb/javascript/api/microsoft-cognitiveservices-speech-sdk/cancellationerrorcode?view=azure-node-latest) the errorCode = 6 Indicates that an error is returned by the service.

**Comment by wolfma61** [comment]
@krisalay - sorry ... is this this happening with the latest bits in this environment?

**Comment by wolfma61** [comment]
closing due to missing follow up
if you have a similar issue with a supported platform, please create a new issue using the latest SDK

thx
Wolfgang
