### ISSUE TITLE
No text being identified while using Conversation Transcription service

### ISSUE THREAD

**Issue by kunalgkjoshi** [Azure-Samples/cognitive-services-speech-sdk#1840]
I am following the steps mentioned in "https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-conversation-transcription?pivots=programming-language-python" to perform real time conversation transcription.
I am using the code without registering voice signatures. I think the code should work but I am not getting any text in the output of the code.
I am using the following code

import azure.cognitiveservices.speech as speechsdk
import time
import uuid
from scipy.io import wavfile

speech_key, service_region="SPEECH_KEY","SPEECH_REGION"
conversationfilename= "file_name.wav" # 8 channel, 16 bits, 16kHz audio

def conversation_transcription_differentiate_speakers():`
   
    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)
    speech_config.set_property_by_name("ConversationTranscriptionInRoomAndOnline", "true")
    speech_config.set_property_by_name("DifferentiateGuestSpeakers", "true")

    channels = 8
    bits_per_sample = 16
    samples_per_second = 16000
    
    wave_format = speechsdk.audio.AudioStreamFormat(samples_per_second, bits_per_sample, channels)
    stream = speechsdk.audio.PushAudioInputStream(stream_format=wave_format)
    audio_config = speechsdk.audio.AudioConfig(stream=stream)
    
    transcriber = speechsdk.transcription.ConversationTranscriber(audio_config)

    conversation_id = str(uuid.uuid4())
    conversation = speechsdk.transcription.Conversation(speech_config, conversation_id)
    done = False

    def stop_cb(evt: speechsdk.SessionEventArgs):
        """callback that signals to stop continuous transcription upon receiving an event `evt`"""
        print('CLOSING {}'.format(evt))
        nonlocal done
        done = True
        
    # transcriber.transcribed.connect(lambda evt: print('TRANSCRIBED: {} {}'.format(evt.result.text, evt.result.utterance_id)))
    transcriber.transcribed.connect(lambda evt: print('TRANSCRIBED: {}'.format(evt)))
    transcriber.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    transcriber.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
    transcriber.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))
    # stop continuous transcription on either session stopped or canceled events
    transcriber.session_stopped.connect(stop_cb)
    transcriber.canceled.connect(stop_cb)

    # Note user voice signatures are not required for speaker differentiation.
    # Use voice signatures when adding participants when more enhanced speaker identification is required.
    user1 = speechsdk.transcription.Participant("user1@example.com", "en-us")
    user2 = speechsdk.transcription.Participant("user2@example.com", "en-us")

    conversation.add_participant_async(user1)
    conversation.add_participant_async(user2)
    transcriber.join_conversation_async(conversation).get()
    transcriber.start_transcribing_async()
    
    sample_rate, wav_data = wavfile.read(conversationfilename)
    stream.write(wav_data.tobytes())
    stream.close()
    while not done:
        time.sleep(.5)

    transcriber.stop_transcribing_async()

conversation_transcription_differentiate_speakers()`

I have created the resource in Central US region
And following are the specifications of wav file:

`codec_tag_string=[1][0][0][0]
codec_tag=0x0001
sample_fmt=s16
sample_rate=16000
channels=8
channel_layout=7.1
bits_per_sample=16
initial_padding=0
id=N/A
r_frame_rate=0/0
avg_frame_rate=0/0
time_base=1/16000`

Thanks in advance for the help

**Comment by M-Hietala** [comment]
I tested the code and was able to see the text results using this file: https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/cpp/windows/console/samples/katiesteve.wav

Could you test with that file to see if you are able to get the results?

**Comment by jimxiei** [comment]
Hello @kunalgkjoshi, if you want to use 8-channel scenario, the first 7 channels should be your audio, but the last one should be empty or your playback: https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk-microphone#:~:text=The%20Microsoft%20Audio%20Stack%20will%20require%20an%20additional%20reference%20stream%20of%20audio%20playback%20to%20perform%20echo%20cancellation.

On the other hand, if 8-channel is not your hard requirement, I would suggest you to try our single channel and you could avoid any potential issues while mimicking the 8-channel audio.

**Comment by kunalgkjoshi** [comment]
Thank you for your suggestion. I created the 8 channel audio file using your mentioned specifications and I was able to get the output. How can I use your single channel service?

**Comment by jimxiei** [comment]
Hello @kunalgkjoshi , if you would like to have a try on the single channel, please make sure your SDK version is 1.24 (1.24.1 if using javascript) or higher. Then feed the single channel file or specified channels=1. Following the prompt messages while running to setup the single channel usage.

**Comment by jhakulin** [comment]
Closing this issue as answered.

**Comment by kunalgkjoshi** [comment]
Thank You for your assistance!
