### ISSUE TITLE
MicrosoftCognitiveServicesSpeech.xcframework not found installing via pod

### ISSUE THREAD

**Issue by willwade** [Azure-Samples/cognitive-services-speech-sdk#1841]
**Describe the bug**
Installing with cocoapods leads to a "There is no XCFramework found at '/Users/...ProjectFolder/MicrosoftCognitiveServicesSpeech.xcframework'."

**To Reproduce**
1. xcode 14.2
2. Build a pod file like so:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.3'

target 'TextAloud' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'MicrosoftCognitiveServicesSpeech-iOS', '~> 1.25.0'
end
```
3. Run pod install in the Project directory. This runs fine
4. Try and build your project - you get this

`There is no XCFramework found at '/Users/...ProjectFolder/MicrosoftCognitiveServicesSpeech.xcframework'.`

If I download the xcframework and place in the projectFolder root it works fine. 

**Expected behavior**
You Shouldnt get this errtor

**Version of the Cognitive Services Speech SDK**

**Platform, Operating System, and Programming Language**
 - OS:MacOS
 - Hardware - x64 
 - Programming language: swift/N/A

**Additional context**
 - Error messages, stack trace, sample code to reproduce the issue, ...
 - Please provide full Speech SDK Log, as per the instructions [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging)?
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by jhakulin** [comment]
@willwade Thanks for the report. When you run the `pod install`, does the Pods folder gets created under your `/Users/.../ProjectFolder/` ?

After `pod install` command, XCFramework is located in the Pods/[Target_Name] directory, where [Target_Name] is the name of your Xcode project's target for which you installed the pod.

**Comment by willwade** [comment]
So if I do pod install - it installs in the obvious place: ProjectFolder/Pods/MicrosoftCognitiveServicesSpeech-iOS 

But if I download it and place the xcframework in ProjectFolder/ it works fine. Is there a flag for pods to install it at ProjectFolder/ instead of Pods/ that I might be missing maybe?

<img width="1153" alt="Screenshot 2023-02-22 at 08 38 41" src="https://user-images.githubusercontent.com/229352/220566916-bfd46502-7e54-4053-8f49-664e4ea2596b.png">

**Comment by pankopon** [comment]
@jhakulin Any update?

**Comment by jhakulin** [comment]
Closing this old issue as we have not been able to repro the issue. When tested recently, the pod installation was successful with the latest Speech SDK and https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/swift/ios/text-to-speech
