### ISSUE TITLE
Speech_SegmentationSilenceTimeoutMs on REST API

### ISSUE THREAD

**Issue by fabswt** [Azure-Samples/cognitive-services-speech-sdk#1844]
The Python SDK supports [`Speech_SegmentationSilenceTimeoutMs`](https://learn.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.propertyid?view=azure-python) (documented [here for C#](https://learn.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.propertyid?view=azure-dotnet) and [here](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-recognize-speech?pivots=programming-language-csharp#change-how-silence-is-handled)).

I need to use the REST API.

My question is: is this property supported on the REST API and, if so, how can I set it?

Did not find any documentation for it.

Thanks!

**Comment by pankopon** [comment]
@chlandsi @zhouwangzw Can you please advise?

**Comment by zhouwangzw** [comment]
I believe the customer is asking for REST API for short audio, but not batch transcription. Adding @mahilleb-msft for help.

**Comment by mahilleb-msft** [comment]
@fabswt if you're using the endpoint `https://<region>.stt.speech.microsoft.com/speech/recognition/interactive/cognitiveservices/v1` please try adding `&SpeechContext-phraseDetection.interactive.segmentation.mode=custom&SpeechContext-phraseDetection.interactive.segmentation.segmentationSilenceTimeoutMs=<X>` to the URL.

(for `/speech/recognition/conversation/cognitiveservices/v1` use `&SpeechContext-phraseDetection.conversation.segmentation.mode=custom&SpeechContext-phraseDetection.conversation.segmentation.segmentationSilenceTimeoutMs=<X>`.

Hope that helps,

Mark

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
