### ISSUE TITLE
stopSpeakingAsync for iOS (Swift)

### ISSUE THREAD

**Issue by Lirry18** [Azure-Samples/cognitive-services-speech-sdk#1848]
Desired behaviour: stopSpeaking immediately stops the synthesis. 

We are making an application for both Android and iOS. Sometimes the TTS needs to be stopped immediately. The SDK provides a nice function called stopSpeakingAsync, which stops the synthesis immediately. But for iOS/Swift there is only stopSpeaking, which will not stop de TTS immediately. 

Is there any plans to make stopSpeakingAsync for Swift?

**Comment by yulin-li** [comment]
Hi, could you share a [speech SDK log](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging) when you calling `stopSpeaking` on iOS?

**Comment by Lirry18** [comment]
I am having trouble turning on the SDK logs. The swift code is being called from flutter and my primary developing device is a windows system.

**Comment by pankopon** [comment]
@Lirry18 Have you had any success with getting logs? Please update.

**Comment by pankopon** [comment]
Closed since no further information received. Please open a new issue if more support is needed.
