### ISSUE TITLE
「JS」How to use autodetect in the ConversationTranslator Class?

### ISSUE THREAD

**Issue by justzero** [Azure-Samples/cognitive-services-speech-sdk#1850]
Does the ConversationTranslator Class support configuration of autoDetect?
I want to auto-detect the user's language in the ConversationTranslator Class, just like configuring AutoDetectSourceLanguageConfig in SpeechRecognizer.
```
    // like this...
    const languages: string[] = ["ja-JP", "en-US"];
    const autoDetectConfig = sdk.AutoDetectSourceLanguageConfig.fromLanguages(languages);
    const recognizer = sdk.SpeechRecognizer.FromConfig(speechConfig, autoDetectConfig, audioConfig);
```
Does anyone know?

**Comment by glharper** [comment]
@justzero Thanks for using JS Speech SDK, and writing this issue up. The ConversationTranslator class does not support Language Identification currently, in any language. @ralph-msft Is this any plan to add LID to ConversationTranslation? Does the backend service even support LID?

**Comment by pankopon** [comment]
Based on discussion with @ralph-msft there is no plan to add this functionality, so I'm closing the item. Please open a new issue if more support is needed.
