### ISSUE TITLE
Play Pause Feature in TTS Python SDK

### ISSUE THREAD

**Issue by prakhs123** [Azure-Samples/cognitive-services-speech-sdk#1854]
**Is your feature request related to a problem? Please describe.**
Hi, Play/Pause feature is supported in other languages eg,
https://stackoverflow.com/questions/62523344/how-to-stop-microsoft-cognitive-tts-audio-playing 
```
var player = new SpeechSDK.SpeakerAudioDestination();
var audioConfig  = SpeechSDK.AudioConfig.fromSpeakerOutput(player);
var synthesizer = new SpeechSDK.SpeechSynthesizer(speechConfig, audioConfig);
synthesizer.speakTextAsync(
...
);
```
But I cannot find SpeakerAudioDestination class in python

**Describe the solution you'd like**
An appropriate class or function for the same.

**Comment by jhakulin** [comment]
@prakhs123 It is correct that pause/resume functionality is not currently available in Python SDK. We will consider adding the support in future releases.

Created internal workitem ref: 4939447
