### ISSUE TITLE
German TTS voice not working properly (C#, Unity)

### ISSUE THREAD

**Issue by SaffronSolid935** [Azure-Samples/cognitive-services-speech-sdk#1855]
**Describe the bug**
I currently work with the SpeechSDK in Unity and the TTS voice of Katja (de-DE, KatjaNeural). A few days ago everything worked properly, but today I get not understandable output of English words via Katja. The german speech still works without any problems, only the output of english words seems to have a problem.

**To Reproduce**
1. Create an Unity-project (2019.4.15f1)
2. Import the newest SpeechSDK 
3. Create and Assign a speechSynthesis script, which uses the voice (de-DE, KatjaNeural)
4. Try english words like Mixed-Reality.

**Expected behavior**
The output of English and German words should work with Katja

**Version of the Cognitive Services Speech SDK**
Microsoft.CognitiveServices.Speech.1.25.1-beta.1 ([downloaded from Microsoft](https://learn.microsoft.com/de-de/azure/cognitive-services/speech-service/quickstarts/setup-platform?tabs=windows%2Cubuntu%2Cunity%2Cjre%2Cmaven%2Cnodejs%2Cmac%2Cpypi&pivots=programming-language-csharp))

**Platform, Operating System, and Programming Language**
 - OS: Windows 11
 - Hardware - x64
 - Programming language: C# (Unity)

**Comment by yulin-li** [comment]
Hi, thanks for using Azure speech and reporting this issue. @bayesrule could you take a look?

**Comment by jiajzhan** [comment]
Thanks for using Azure speech and reporting this issue. I am working on the investigation.

**Comment by D33TW0** [comment]
Hey there, i can report the same issue :-)

**Comment by jiajzhan** [comment]
@SaffronSolid935 we do not have any updates on 'Mixed-Reality' for Katja voice.  So do you want this word to be read in English way or native German way?  What's the current status from your opinion?  Besides, could you also give a whole input sentence here?

**Comment by SaffronSolid935** [comment]
@jiajzhan the English words in the German sentences should be pronounced in English (there is no problem with the German words). I haven't found a proper solution to this yet, but I have a workaround. If I used the square brackets (example: "Willkommen im [augmented] [business] [cockpit].") the words are pronounced correctly, at least to some extent.
Here are more accurate sentences pronounced with TTS (voice Katja):
1. Willkommen  im augmented business cockpit.
2. Willkommen im Dialog zu Mixed Reality.

Also, in the video I attached here is a third sentence that is completely in English and not pronounced correctly (we do not use such sentences, but only German sentences with English words).

https://user-images.githubusercontent.com/98280209/223383699-433926ba-f679-43b3-a653-084fe46da60b.mp4

**Comment by D33TW0** [comment]
> @jiajzhan the English words in the German sentences should be pronounced in English (there is no problem with the German words). I haven't found a proper solution to this yet, but I have a workaround. If I used the square brackets (example: "Willkommen im [augmented] [business] [cockpit].") the words are pronounced correctly, at least to some extent. Here are more accurate sentences pronounced with TTS (voice Katja):
> 
> 1. Willkommen  im augmented business cockpit.
> 2. Willkommen im Dialog zu Mixed Reality.
> 
> Also, in the video I attached here is a third sentence that is completely in English and not pronounced correctly (we do not use such sentences, but only German sentences with English words).

That is exactly how it sounds to me, strangely speaking

**Comment by SaffronSolid935** [comment]
Thanks @jiajzhan, I will try it out. In my project, the region Western Europe (westeurope) is used.

**Comment by jiajzhan** [comment]
@SaffronSolid935  I have repo the issue on WestEurope region. Other region should be OK. Thanks for your reporting. We will fix it ASAP.

**Comment by pankopon** [comment]
@jiajzhan Please update with the latest status - has the fix been deployed yet or is it in the works?

**Comment by yulin-li** [comment]
@jiajzhan could you help to verify?

**Comment by jiajzhan** [comment]
@pankopon this issue have been fixed, thanks

**Comment by yulin-li** [comment]
closing as fixed.
