### ISSUE TITLE
Custom Microphone Geometry Question

### ISSUE THREAD

**Issue by danieljlevine** [Azure-Samples/cognitive-services-speech-sdk#1856]
Hi,

I have the Speech Service working, but we are using a provided geometry that doesn't really our _actual_ microphone geometry and I think I'd like to rectify that so that the audio processing can help our application as much as possible.  I found this documentation:

https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/audio-processing-speech-sdk?tabs=csharp#custom-microphone-geometry

So, from the above documentation, I see that the mic arrays are defined using millimeter units and XYZ position values ranging from approximately -32768 to 32767 (I think I have that right).  This means that I can represent mics located within ~64 meters coordinate space with millimeter precision. The default mic arrays are defined with the mics relatively close together (i.e., less that one meter aware from each other), and the speaker is located outside of the mic array, so a beam forming angle makes sense.

However in our case, we have 4 mics placed in all 4 corners of a room, each contributing to a different channel.  The room is about 10 meters x 10 meters with high ceilings so it's _not_ challenging the ~64-meter max distance at all. Suppose I could get the location of the mics in this room and configure the appropriate microphone geometry and us that for our Azure Cognitive Speech capability. Is there reason to believe that this would improve the audio processing over using the predefined 7 mic-array?  Is this type of configuration (i.e., the speaker located within the microphone volume) expected to work?  I'd love to hear your perspective.

Also, we're actually using this for Conversation Transcription, so beam forming would be useful to help pull the speakers apart.  Would the Azure Conversation Transcription capability already do that using beam forming?  Perhaps speaker identification would improve if we used our custom mic geometry as proposed above?

**Comment by jhakulin** [comment]
Added internal workitem for doc update: 4944155
