### ISSUE TITLE
Pronunciation Assessment SDK return wrong result compare with api call

### ISSUE THREAD

**Issue by ducthong230497** [Azure-Samples/cognitive-services-speech-sdk#1857]
**Describe the bug**
I'm using azure speech sdk to do pronunciation assessment, it works fine when i used api provide by azure, but when i use speech sdk the result is not correct.

here is the code that i used

`    def speech_recognition_with_pull_stream(self):
        class WavFileReaderCallback(speechsdk.audio.PullAudioInputStreamCallback):
            def __init__(self, filename: str):
                super().__init__()
                self._file_h = wave.open(filename, mode=None)

                self.sample_width = self._file_h.getsampwidth()

                assert self._file_h.getnchannels() == 1
                assert self._file_h.getsampwidth() == 2
                # assert self._file_h.getframerate() == 16000  #comment this line because every .wav file read is 48000
                assert self._file_h.getcomptype() == 'NONE'

            def read(self, buffer: memoryview) -> int:
                size = buffer.nbytes
                frames = self._file_h.readframes(len(buffer) // self.sample_width)

                buffer[:len(frames)] = frames

                return len(frames)

            def close(self):
                self._file_h.close()

        speech_key = os.getenv('AZURE_SUBSCRIPTION_KEY')
        service_region = os.getenv('AZURE_REGION')
        speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)
        speech_config.set_property(speechsdk.PropertyId.Speech_LogFilename, "/Users/146072/Downloads/log.txt")

        # specify the audio format
        wave_format = speechsdk.audio.AudioStreamFormat(samples_per_second=16000, bits_per_sample=16, channels=1)

        # setup the audio stream
        callback = WavFileReaderCallback('/Users/146072/Downloads/58638f26-ed07-40b7-8672-1948c814bd69.wav')
        stream = speechsdk.audio.PullAudioInputStream(callback, wave_format)
        audio_config = speechsdk.audio.AudioConfig(stream=stream)

        # instantiate the speech recognizer with pull stream input
        speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config, language='en-US')

        reference_text = 'We had a great time taking a long walk outside in the morning'
        pronunciation_assessment_config = speechsdk.PronunciationAssessmentConfig(
            reference_text=reference_text,
            grading_system=PronunciationAssessmentGradingSystem.HundredMark,
            granularity=PronunciationAssessmentGranularity.Word,
        )
        # pronunciation_assessment_config.phoneme_alphabet = "IPA"
        pronunciation_assessment_config.apply_to(speech_recognizer)
        speech_recognition_result = speech_recognizer.recognize_once()
        print(speech_recognition_result.text)

        # The pronunciation assessment result as a Speech SDK object
        pronunciation_assessment_result = speechsdk.PronunciationAssessmentResult(speech_recognition_result)
        print(pronunciation_assessment_result)

        # The pronunciation assessment result as a JSON string
        pronunciation_assessment_result_json = speech_recognition_result.properties.get(
            speechsdk.PropertyId.SpeechServiceResponse_JsonResult
        )
        print(pronunciation_assessment_result_json)

        return json.loads(pronunciation_assessment_result_json)`

The result return is "AccuracyScore": 26, "FluencyScore": 9, "CompletenessScore": 46, "PronScore": 19.8 here is the full result:

`{"Id":"c6a71615db3048ebae7855e41de7b1fa","RecognitionStatus":"Success","Offset":16400000,"Duration":110500000,"Channel":0,"DisplayText":"We had a great time taking a long walk outside in the morning.","SNR":21.523027,"NBest":[{"Confidence":0.8135016,"Lexical":"We had a great time taking a long walk outside in the morning","ITN":"We had a great time taking a long walk outside in the morning","MaskedITN":"we had a great time taking a long walk outside in the morning","Display":"We had a great time taking a long walk outside in the morning.","PronunciationAssessment":{"AccuracyScore":26.0,"FluencyScore":9.0,"CompletenessScore":46.0,"PronScore":19.8},"Words":[{"Word":"We","Offset":16400000,"Duration":500000,"PronunciationAssessment":{"AccuracyScore":40.0,"ErrorType":"None"}},{"Word":"had","Offset":17000000,"Duration":800000,"PronunciationAssessment":{"AccuracyScore":0.0,"ErrorType":"Mispronunciation"}},{"Word":"a","Offset":17900000,"Duration":200000,"PronunciationAssessment":{"AccuracyScore":40.0,"ErrorType":"None"}},{"Word":"great","Offset":18200000,"Duration":1100000,"PronunciationAssessment":{"AccuracyScore":0.0,"ErrorType":"Mispronunciation"}},{"Word":"time","Offset":19400000,"Duration":800000,"PronunciationAssessment":{"AccuracyScore":0.0,"ErrorType":"Mispronunciation"}},{"Word":"taking","Offset":20300000,"Duration":1400000,"PronunciationAssessment":{"AccuracyScore":0.0,"ErrorType":"Mispronunciation"}},{"Word":"a","Offset":21800000,"Duration":200000,"PronunciationAssessment":{"AccuracyScore":40.0,"ErrorType":"None"}},{"Word":"long","Offset":27500000,"Duration":12300000,"PronunciationAssessment":{"AccuracyScore":37.0,"ErrorType":"Mispronunciation"}},{"Word":"walk","Offset":44100000,"Duration":7000000,"PronunciationAssessment":{"AccuracyScore":63.0,"ErrorType":"None"}},{"Word":"outside","Offset":75000000,"Duration":3800000,"PronunciationAssessment":{"AccuracyScore":18.0,"ErrorType":"Mispronunciation"}},{"Word":"in","Offset":78900000,"Duration":500000,"PronunciationAssessment":{"AccuracyScore":40.0,"ErrorType":"None"}},{"Word":"the","Offset":79500000,"Duration":500000,"PronunciationAssessment":{"AccuracyScore":40.0,"ErrorType":"None"}},{"Word":"morning","Offset":120700000,"Duration":6200000,"PronunciationAssessment":{"AccuracyScore":25.0,"ErrorType":"Mispronunciation"}}]}]}`

here is the code i use to call api:
`
    def ackaud(self):
        #    f.save(audio)
        # print('file uploaded successfully')

        # a generator which reads audio data chunk by chunk
        # the audio_source can be any audio input stream which provides read() method, e.g. audio file, microphone, memory stream, etc.
        def get_chunk(audio_source, chunk_size=1024):
            while True:
                # time.sleep(chunk_size / 32000) # to simulate human speaking rate
                chunk = audio_source.read(chunk_size)
                if not chunk:
                    # global uploadFinishTime
                    # uploadFinishTime = time.time()
                    break
                yield chunk

        # build pronunciation assessment parameters
        referenceText = 'We had a great time taking a long walk outside in the morning. '

        pronAssessmentParamsJson = "{\"ReferenceText\":\"%s\",\"GradingSystem\":\"HundredMark\",\"Dimension\":\"Comprehensive\",\"EnableMiscue\":\"True\"}" % referenceText
        pronAssessmentParamsBase64 = base64.b64encode(bytes(pronAssessmentParamsJson, 'utf-8'))
        pronAssessmentParams = str(pronAssessmentParamsBase64, "utf-8")

        subscription_key = os.getenv('AZURE_SUBSCRIPTION_KEY')
        region = os.getenv('AZURE_REGION')

        # build request
        url = "https://%s.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?language=%s&usePipelineVersion=0" % (
        region, 'en-US')
        headers = {'Accept': 'application/json;text/xml',
                   'Connection': 'Keep-Alive',
                   'Content-Type': 'audio/wav; codecs=audio/pcm; samplerate=16000',
                   'Ocp-Apim-Subscription-Key': subscription_key,
                   'Pronunciation-Assessment': pronAssessmentParams,
                   'Transfer-Encoding': 'chunked',
                   'Expect': '100-continue'}

        audioFile = open('/Users/146072/Downloads/58638f26-ed07-40b7-8672-1948c814bd69.wav', 'rb')
        # audioFile = f
        # send request with chunked data
        response = requests.post(url=url, data=get_chunk(audioFile), headers=headers)
        # getResponseTime = time.time()
        audioFile.close()

        # latency = getResponseTime - uploadFinishTime
        # print("Latency = %sms" % int(latency * 1000))

        return response.json()
`

**Expected behavior**
I expect the result return "AccuracyScore": 100, "FluencyScore": 100, "CompletenessScore": 100, "PronScore": 100 as api call

**Version of the Cognitive Services Speech SDK**
I'm using azure-cognitiveservices-speech version 1.25.0

**Platform, Operating System, and Programming Language**
 - OS: Mac OS
 - Hardware - ARM M1
 - Programming language: Python 3.10.8

[log.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/10866632/log.txt)

**Comment by pankopon** [comment]
@yulin-li Can you please check this.

**Comment by ducthong230497** [comment]
@yulin-li please help me check this.

**Comment by yulin-li** [comment]
Hi @ducthong230497 I am investigating. BTW, could you also share the wave file, if you don't mind?

**Comment by ducthong230497** [comment]
Hi @yulin-li, 
I have change the code from `speechsdk.audio.AudioStreamFormat(samples_per_second=16000, bits_per_sample=16, channels=1)` to `speechsdk.audio.AudioStreamFormat(samples_per_second=16000, bits_per_sample=16, channels=1)` and the result is pretty the same with calling api. Is this the correct way to to it?
