### ISSUE TITLE
ServiceTimeout. Due to service inactivity, the client buffer exceeded maximum size. Resetting the buffer.

### ISSUE THREAD

**Issue by Arnei** [Azure-Samples/cognitive-services-speech-sdk#1858]
**Describe the bug**
We are trying to using the Azure Speech SDK for Java for transcription in our service. Occasionally the transcription fails with a ServiceTimeout (see below for the full error). Based on our monitoring, our current hypothesis is that gstreamer is running out of memory, somehow causing the Timeout. We would greatly appreciate if you could corroborate or deny this assessment, and give some pointers on how much memory should be slated for transcription on a server.

**To Reproduce**
Our code is losely based off of https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java. The files to transcribe can be quite long (~1 hour), and multiple transcription may run at the same time independently from each other. If you need the exact code I can provide that as well.

**Expected behavior**
The transcription completes without error.

**Version of the Cognitive Services Speech SDK**
```
    <dependency>
      <groupId>com.microsoft.cognitiveservices.speech</groupId>
      <artifactId>client-sdk</artifactId>
      <version>1.21.0</version>
    </dependency>
 ```

**Platform, Operating System, and Programming Language**
 - OS: Linux based, recent Fedora and Ubuntu distributions
 - Programming language: Java

**Additional context**
- From our logs:
```
2023-03-01T19:48:41,028 | ERROR | (MicrosoftAzureTranscriptionService:874) - Encountered error.
Error code: ServiceTimeout
Error details: Due to service inactivity, the client buffer exceeded maximum size. Resetting the buffer. SessionId: ab59e3dc9a734844877034ceeec74dbc
2023-03-01T19:48:41,840 | ERROR | (BinaryFileReader:52) - Read: java.io.IOException: Stream Closed
2023-03-01T19:48:42,133 | WARN  | (MicrosoftAzureTranscriptionService:505) - Error received for media package 7cf5696d-c077-4cf8-92bb-976ebda6744b, job id 91897
```
- Speech SDK Log for the error above [azurespeechsdklogfile+7cf5696d-c077-4cf8-92bb-976ebda6744b.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/10872336/azurespeechsdklogfile%2B7cf5696d-c077-4cf8-92bb-976ebda6744b.txt)
- Session Id: ab59e3dc9a734844877034ceeec74dbc, 01.03.2023, 19:48 (GMT+1)

**Comment by dargilco** [comment]
Hi @Arnei, this is Darren from the Speech SDK team. I'm looking at the logs and service-side telemetry now.

**Comment by dargilco** [comment]
@Arnei I will contact the service team to see if they have some insight on what is wrong based on telemetry. 

From the log I see you run multiple recognizers in parallel, and the log is only for about 5 seconds and does not include the error. Will you be able to set up a run with a single recognizer, and take SDK log for the whole session?

I also have a question about your scenario and why you selected to use Speech SDK and not REST APIs to do the language identification and transcription. Speech SDK is mostly targeted for live transcription scenarios, or short audio files. Are you transcribing live audio streams or are you processing pre-recorded WAV files? If these are WAV files, please consider using REST APIs instead of Speech SDK.

**Comment by dargilco** [comment]
@Arnei can you also please update to Speech SDK 1.26, and see if you still see this issue there?

**Comment by Arnei** [comment]
Hi Darren, thanks for your response!

At this point, I agree that we should be using the REST APIs instead of the Speech SDK. We have mostly large, single pre-recorded files in potentially multiple different formats. However, when I was initially researching on which to use, this was not at all clear to me. Back then, it seemed to me like the API was only useful for batch transcription and the SDK would be superior in every way (more features, possibly synchronous execution). And now we're kind of stuck in a sunken cost fallacy :').

We should be able to update the SDK to 1.26 and then set up a run with a single recognizer. Will keep you posted.

**Comment by dargilco** [comment]
Thank you for the update @Arnei.

**Comment by Arnei** [comment]
Closing this as it is likely a problem on our end. Updating to 1.26 did not alleviate the problem. Thanks again for all your help.
