### ISSUE TITLE
startContinuousRecognitionAsync segmenting tuner parameter?

### ISSUE THREAD

**Issue by sb07** [Azure-Samples/cognitive-services-speech-sdk#186]
**Is your feature request related to a problem? Please describe.**
I would like the segmentation on startContinuousRecognitionAsync to be quicker is their a parameter i can tune?

**Describe the solution you'd like**
a parameter to tune to the segmentation of speech under continuous.

**Describe alternatives you've considered**
None

**Comment by wolfma61** [comment]
we are constantly re-evaluating the service side performance of speech recognition. 

what are you trying to achieve through faster segmentation?

**Comment by sb07** [comment]
Faster segmentation would yield greater efficiency in post processing such as translation or inferential logic.

Sent from Yahoo Mail on Android 
 
  On Mon, Apr 8, 2019 at 6:18 PM, Wolfgang Manousek<notifications@github.com> wrote:   
we are constantly re-evaluating the service side performance of speech recognition.

what are you trying to achieve through faster segmentation?

**Comment by wolfma61** [comment]
I see - segementation time has been reduced lately, but isn't configurable from the caller ...

**Comment by chrisbasoglu** [comment]
Yes, Segmentation time was reduced significantly on April 5, 2019.
