### ISSUE TITLE
Change Microphone in existing speechsdk.SpeechRecognizer instance

### ISSUE THREAD

**Issue by hendryman** [Azure-Samples/cognitive-services-speech-sdk#1860]
In a python script, I would like to change the microphone input of an already initialized `SpeechRecognizer`. Is that possible, or would I have to create a "fresh" `SpeechRecognizer` with the new `device_name` property in its `AudioConfig`?

**Comment by dargilco** [comment]
Hi @hendryman, this is Darren from the Speech SDK team. If you want to change the input microphone, you will have to re-create the `SpeechRecognizer` object.
