### ISSUE TITLE
embedded.tts.dylib does not support run by Rosetta

### ISSUE THREAD

**Issue by czkoko** [Azure-Samples/cognitive-services-speech-sdk#1864]
**Describe the bug**
When I run a program with x86_64 architecture under the Apple M1, if there is libMicrosoft.CognitiveServices.Speech.extension.embedded.tts.dylib in the lib directory,
Then the program will crash. Whether I use it or not, it will work normally after deleting it.
The program of the arm64 architecture does not have this problem.

**Version of the Cognitive Services Speech SDK**
1.24-1.26

**Platform, Operating System, and Programming Language**
 - OS: Mac OS 13.2
 - Hardware: M1
 - Programming language: C++

**Additional context**
return information：
`zsh: illegal hardware instruction`

lldb debug:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x000000010b009070 libMicrosoft.CognitiveServices.Speech.extension.embedded.tts.dylib`___lldb_unnamed_symbol3625 + 32
libMicrosoft.CognitiveServices.Speech.extension.embedded.tts.dylib`___lldb_unnamed_symbol3625:
->  0x10b009070 <+32>: vxorps %xmm0, %xmm0, %xmm0
    0x10b009074 <+36>: vmovups %ymm0, 0x5ec79c(%rip)
    0x10b00907c <+44>: leaq   0x5199c1(%rip), %rbx
    0x10b009083 <+51>: movq   %rbx, %rdi
Target 0: (s) stopped.
```

**Comment by dargilco** [comment]
Hi @czkoko I'm Darren from the Speech SDK team. Thank you for reporting this. What does your C++ program do? Can you share example code? Are you using the SpeechSynthesizer object?

Please do a run of a single session, while taking [Speech SDK logs]( https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging) leading up to the crash, and attach the SDK logs here.

Thanks,

Darren

**Comment by pankopon** [comment]
@czkoko Since you are using `SpeechConfig` (for cloud services), do you not expect to need embedded speech? In that case your project should have only `Microsoft.CognitiveServices.Speech` nupkg installed, not any of `Microsoft.CognitiveServices.Speech.Extension.Embedded.*` packages. We've verified x64 dylibs on native x64 platform, not with Rosetta, so there could be some incompatibility.

**Comment by czkoko** [comment]
@pankopon  Yes, I know how to avoid this problem. I also tested that there is no problem running on Intel CPU, It's just report the potential incompatibility problems. Maybe I will use embedded speech in the future. After all, only compiling x86_64 can reduce part of the program size, and it can run on apple and intel CPU at the same time.

**Comment by pankopon** [comment]
@yulin-li Can you please check.

**Comment by yulin-li** [comment]
Hi @czkoko , thanks for reporting this issue and we will investigate and try to fix. We have created an internal work item (id 5264814) to track. We will update this issue once it's addressed.

I am closing this issue for now as it's tracked internally and needs some time.
