### ISSUE TITLE
System.DllNotFoundException: at Microsoft.CognitiveServices.Speech.Audio.AudioConfig.FromDefaultMicrophoneInput() on iOS only

### ISSUE THREAD

**Issue by jenka-yap** [Azure-Samples/cognitive-services-speech-sdk#1865]
I create a sample sample MauiApp1 using VS 2022 Comm:-

1 Deploy on iOS iPhone 14 Max Pro, everything works fine.
2 In MainPage.xaml.cs added the following lines:-
3 Note the "Added the following lines */
    	private void OnCounterClicked(object sender, EventArgs e)
	{
		count++;

		if (count == 1)
			CounterBtn.Text = $"Clicked {count} time";
		else
			CounterBtn.Text = $"Clicked {count} times";

		SemanticScreenReader.Announce(CounterBtn.Text);

               /* Added the following lines */
		try
		{
                       AudioConfig audioConfig = AudioConfig.FromDefaultMicrophoneInput();
                } 
		catch (Exception ex)
		{
			Debug.WriteLine(ex.Message + e.ToString()) ;
			Error.Text = ex.Message + e.ToString();
		}	

        
	}

4. When I click the "Click Me" to generate the even.
5. This line "AudioConfig audioConfig = AudioConfig.FromDefaultMicrophoneInput();" throw exception
6. ex = {System.DllNotFoundException: __Internal
   at Microsoft.CognitiveServices.Speech.Audio.AudioConfig.FromDefaultMicrophoneInput()
   at MauiApp1.MainPage.OnCounterClicked(Object sender, EventArgs e) .....
7. I have "Microsoft.CognitiveServices.Speech" 1.26.0
8. On Android it works fine.
9. On Windows, it works fine.

**Comment by jhakulin** [comment]
@jenka-yap Thanks for the report. Could you confirm your environment meets the following prerequisites?
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/csharp/maui/speech-to-text#prerequisites
I double checked and 1.26.0 works on my iOS device in MAUI. To understand better what might be issue on your side, could you please also share following?
1) the iOS settings under your application's project properties (right click project under Solution Explorer), 
- iOS Targets settings, e.g. Target .NET Runtime for iOS
- iOS build settings. 
2) Full Visual Studio output when building and deploying the app, including the details of the exception

**Comment by jenka-yap** [comment]
sure, here are the info:-
1.1 Enable targeting of the iOS platform == checked
1.2 Target .NET Runtime == net7.0
1.3 Target iOS Framework == blank
1.4 Minimum Target 1OS Framework == 11.0

2.
Build started...
1>------ Build started: Project: MauiApp2, Configuration: Debug Any CPU ------
1>Detected signing identity:
1>  Code Signing Key: "Apple Development: Created via API (DKW4W8H49F)" (C:\Users\joeya\AppData\Local\Xamarin\iOS\Provisioning\Certificates\432718BC3F38C450599EDA0CB920AA91.p12)
1>  Provisioning Profile: "VS: WildCard Development" (C:\Users\joeya\AppData\Local\Xamarin\iOS\Provisioning\Profiles\b1fd2c89-1bdd-4626-9eb7-ae74cab15b68.mobileprovision)
1>MauiApp2 -> C:\Users\joeya\source\repos\Talk2Me\MauiApp2\MauiApp2\bin\Debug\net7.0-maccatalyst\maccatalyst-x64\MauiApp2.dll
1>MauiApp2 -> C:\Users\joeya\source\repos\Talk2Me\MauiApp2\MauiApp2\bin\Debug\net7.0-android\MauiApp2.dll
1>MauiApp2 -> C:\Users\joeya\source\repos\Talk2Me\MauiApp2\MauiApp2\bin\Debug\net7.0-ios\ios-arm64\MauiApp2.dll
1>MauiApp2 -> C:\Users\joeya\source\repos\Talk2Me\MauiApp2\MauiApp2\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\MauiApp2.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Elapsed 00:03.269 ==========


>>>>> Here is the execution trace including the Debug.WriteLine of the exception thrown.

Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/Microsoft.iOS.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Runtime.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Collections.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Runtime.InteropServices.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Threading.Thread.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Threading.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Net.Http.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Net.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Numerics.Vectors.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Net.Sockets.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Drawing.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Private.Uri.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/Xamarin.PreBuilt.iOS.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/Xamarin.iOS.HotRestart.Application.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/netstandard.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.IO.MemoryMappedFiles.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.IO.Pipes.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Memory.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Diagnostics.Tracing.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Collections.NonGeneric.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/Microsoft.Win32.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Net.NameResolution.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Threading.ThreadPool.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Collections.Concurrent.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Diagnostics.Process.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.ComponentModel.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.ComponentModel.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.ObjectModel.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Diagnostics.FileVersionInfo.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Reflection.Metadata.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Collections.Immutable.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Linq.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.IO.Compression.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Text.Encoding.Extensions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Collections.Specialized.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Security.Cryptography.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Formats.Asn1.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Runtime.Numerics.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.ComponentModel.TypeConverter.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Runtime.Loader.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Text.RegularExpressions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Reflection.Emit.ILGeneration.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Reflection.Emit.Lightweight.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Reflection.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Net.Security.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Security.Claims.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Runtime.Serialization.Formatters.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Resources.Writer.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Xml.XDocument.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Private.Xml.Linq.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Private.Xml.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Diagnostics.TraceSource.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Diagnostics.DiagnosticSource.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Net.Quic.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.IO.Compression.Brotli.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Threading.Channels.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Net.NetworkInformation.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Reflection.Emit.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Linq.Expressions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.ComponentModel.EventBasedAsync.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Console.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Data.Common.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Xml.ReaderWriter.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Xml.XmlSerializer.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Transactions.Local.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Diagnostics.Contracts.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Diagnostics.TextWriterTraceListener.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Diagnostics.StackTrace.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.IO.Compression.ZipFile.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.IO.FileSystem.DriveInfo.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.IO.FileSystem.Watcher.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.IO.IsolatedStorage.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Linq.Queryable.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Linq.Parallel.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Net.Requests.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Net.WebHeaderCollection.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Net.ServicePoint.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Net.HttpListener.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Net.WebSockets.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Security.Principal.Windows.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Net.WebClient.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Net.WebProxy.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Net.Mail.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Net.Ping.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Net.WebSockets.Client.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Reflection.DispatchProxy.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Runtime.CompilerServices.VisualC.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Runtime.Serialization.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Runtime.Serialization.Xml.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Private.DataContractSerialization.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Runtime.Serialization.Json.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Threading.Overlapped.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Threading.Tasks.Parallel.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Web.HttpUtility.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Xml.XPath.XDocument.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Xml.XPath.dll [External]
Thread started:  #2
Thread started: .NET Timer #3
2023-03-05 14:08:37.569 Xamarin.PreBuilt.iOS[1075:8800106] Content folder: /var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content

2023-03-05 14:08:37.571 Xamarin.PreBuilt.iOS[1075:8800106] App path /var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/MauiApp2.dll

Loaded assembly: /private/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/MauiApp2.dll
Loaded assembly: /private/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Microsoft.Maui.Controls.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Microsoft.Maui.dll [External]
2023-03-05 14:08:37.658 Xamarin.PreBuilt.iOS[1075:8800106] AppDelegate name: AppDelegate

Loaded assembly: /private/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Microsoft.Maui.Graphics.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Microsoft.Maui.Controls.Compatibility.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Microsoft.CognitiveServices.Speech.csharp.dll [External]
[0:] Failed to force load assembly /var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Microsoft.CognitiveServices.Speech.csharp.dll. Type:Azure.AI.Vision.Core.Internal.JsonBuilder. Exception: '__Internal'. Callstack: '   at Azure.AI.Vision.Core.Internal.ai_core_json.ai_core_json_builder_create(InteropSafeHandle& builder)
   at Azure.AI.Vision.Core.Internal.JsonBuilder..ctor()
   at System.Reflection.ConstructorInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)'
Loaded assembly: /private/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Microsoft.Extensions.DependencyInjection.Abstractions.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Microsoft.Extensions.Logging.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Microsoft.Extensions.Logging.Abstractions.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Microsoft.Extensions.Options.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Microsoft.Maui.Controls.Xaml.dll [External]
Thread started: <Thread Pool> #4
Loaded assembly: /private/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Microsoft.Extensions.Configuration.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Microsoft.Extensions.Configuration.Abstractions.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Microsoft.Extensions.Primitives.dll [External]
Thread started: .NET ThreadPool Gate #5
Thread started: <Thread Pool> #6
Loaded assembly: /private/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Microsoft.Extensions.Logging.Debug.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Microsoft.Maui.Essentials.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Microsoft.Extensions.DependencyInjection.dll [External]
Resolved pending breakpoint for 'MauiApp2.Program.Main(System.String[])' to C:\Users\joeya\source\repos\Talk2Me\MauiApp2\MauiApp2\Platforms\iOS\Program.cs:10 [0x00000].
Thread started: <Thread Pool> #7
Loaded assembly: data-0x10f348000 [External]
Loaded assembly: data-0x10f35c000 [External]
Loaded assembly: data-0x10f470000 [External]
Loaded assembly: data-0x10f4c4000 [External]
Thread started: <Thread Pool> #8
2023-03-05 14:08:38.010 Xamarin.PreBuilt.iOS[1075:8800106] Could not resolve assembly Microsoft.VisualStudio.DesignTools.TapContract, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null. Details: Could not load file or assembly '/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Microsoft.VisualStudio.DesignTools.TapContract.dll' or one of its dependencies.

2023-03-05 14:08:38.014 Xamarin.PreBuilt.iOS[1075:8800106] Could not resolve assembly Xamarin.HotReload.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. Details: Could not load file or assembly '/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Xamarin.HotReload.Contracts.dll' or one of its dependencies.

Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointSendToIde(System.String)' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:423 [0x00000].
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Text.Json.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Text.Encodings.Web.dll [External]
2023-03-05 14:08:38.108 Xamarin.PreBuilt.iOS[1075:8800106] Could not resolve assembly Xamarin.HotReload.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. Details: Could not load file or assembly '/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Xamarin.HotReload.Contracts.dll' or one of its dependencies.

2023-03-05 14:08:38.109 Xamarin.PreBuilt.iOS[1075:8800106] Could not resolve assembly Microsoft.VisualStudio.DesignTools.TapContract, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null. Details: Could not load file or assembly '/var/mobile/Containers/Data/Application/5CA44A79-1CD1-4B33-A949-BBFA6EA03AC4/Documents/MauiApp2.content/Microsoft.VisualStudio.DesignTools.TapContract.dll' or one of its dependencies.

Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:418 [0x00000].
Thread started:  #9
Thread started:  #10
Thread started:  #11
Resolved pending breakpoint at 'MainPage.xaml.cs:28,1' to void MauiApp2.MainPage.OnCounterClicked (object sender, System.EventArgs e) [0x000ba].
2023-03-05 14:08:39.557 Xamarin.PreBuilt.iOS[1075:8800147] Warning: observer object was not disposed manually with Dispose()

2023-03-05 14:08:39.557 Xamarin.PreBuilt.iOS[1075:8800147] Warning: observer object was not disposed manually with Dispose()

Loaded assembly: /private/var/containers/Bundle/Application/E7007C49-2795-48BC-AB70-3CC55C5385DC/MauiApp2.app/System.Runtime.Intrinsics.dll [External]
[0:] ex.Message: __Internal
[0:] ex.StackTrace    at Microsoft.CognitiveServices.Speech.Audio.AudioConfig.FromDefaultMicrophoneInput()
   at MauiApp2.MainPage.OnCounterClicked(Object sender, EventArgs e) in C:\Users\joeya\source\repos\Talk2Me\MauiApp2\MauiApp2\MainPage.xaml.cs:line 28
[0:] ex.InnerException 
[0:] ex.Source <unknown>

**Comment by jhakulin** [comment]
Thanks, could you tell me still following:
1) What is the version of Visual Studio?
2) Are you using Mac or Windows as development environment?

Based on 2 MAUI specific errors in the deployment log, this issue looks similar to your issue: https://stackoverflow.com/questions/73809169/net-maui-i-can-not-debug-in-ios-because-of-could-not-load-file-or-assembly-xa

**Comment by jenka-yap** [comment]
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.5.1

I am using Windows 11 for my development, I don’t actually have a Mac.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by jhakulin** [comment]
@jenka-yap Ok, that helps, Speech SDK NuGet for iOS contains static native libraries for iOS targets and build those to your application, you need to use Mac either remotely by pairing it with your Windows machine or building the MAUI app using Mac directly.
https://learn.microsoft.com/en-us/dotnet/maui/ios/pair-to-mac?view=net-maui-7.0

**Comment by jenka-yap** [comment]
Oh, ok. I will look into this.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by jhakulin** [comment]
ok, closing the issue, please let us know if there are other issues with our SDK.

**Comment by jenka-yap** [comment]
Ok. Will do. Thanks a bunch for the quick respond!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
