### ISSUE TITLE
Error code: 1007 - Unsupported Locale "fr-fr"

### ISSUE THREAD

**Issue by CarteKiwi** [Azure-Samples/cognitive-services-speech-sdk#1867]
**Describe the bug**
When setting the "commandsConfig.SetProperty(PropertyId.SpeechServiceConnection_RecoLanguage, "fr-fr");" property, after recognition started, the Canceled event is raised with the following error message:

### **"Connection was closed by the remote host. Error code: 1007. Error details: Status(StatusCode="InvalidArgument", Detail="Bad client request: Unsupported Locale "fr-fr".... "**

I am saying "mirror" (my keyword), it's being recognized, but right after, I got the canceled event.
Notice that without the "SpeechServiceConnection_RecoLanguage", it's working, but not in French, even if my application (in speech studio) is in fr-fr.

Thanks

**To Reproduce**
1. Create a  CustomCommandsConfig
```
 var commandsConfig = CustomCommandsConfig.FromSubscription(applicationId, subscription, region);
 commandsConfig.SetProperty(PropertyId.SpeechServiceConnection_RecoLanguage, "fr-fr");
```
2. Instanciate a new DialogServiceConnector using this config

```
var config = AudioConfig.FromMicrophoneInput(micro.Id);
_dialogServiceConnector = new DialogServiceConnector(commandsConfig, config);
_dialogServiceConnector.ActivityReceived += OnActivityReceived;
_dialogServiceConnector.Recognizing += OnRecognizing;
_dialogServiceConnector.Recognized += OnRecognized;
_dialogServiceConnector.Canceled += OnCanceled;
_dialogServiceConnector.SessionStarted += OnSessionStarted;
_dialogServiceConnector.SessionStopped += OnSessionStopped;
```
3. Call ConnectAsync()

`await _dialogServiceConnector.ConnectAsync();`

**Expected behavior**
Say "mirror" (my keyword), and continue speaking will raise the "recognized" event from the API, in French.
This code was working on 1.24 before you made change to the Speech API I guess.

**Version of the Cognitive Services Speech SDK**
1.24 and 1.26, both not working.

**Platform, Operating System, and Programming Language**
 - OS: Windows 11
 - Hardware - x64
 - Programming language: C#
 - UWP app using Speech SDK

**Additional context**
Error Connection was closed by the remote host. Error code: 1007. Error details: Status(StatusCode="InvalidArgument", Detail="Bad client request: Unsupported Locale 'fr-fr'..") SessionId: a3f8aa3bb94e4d73a7c33ac322ac4830

**Comment by dargilco** [comment]
Hi @CarteKiwi, this is Darren from the Speech SDK team. I will reach out to Custom Commands service folks to see if they can help diagnose your issue.

**Comment by CarteKiwi** [comment]
Hi Darren. Thanks.

**Comment by mswellsi** [comment]
Hi @CarteKiwi, this is Ian also from the Speech team. Thanks for the feedback, and sorry to hear of the problem. After investigation the issue should now be resolved. Have you tried this again lately?

**Comment by CarteKiwi** [comment]
Hi Ian, it's working. Thanks both for your reactivity.
