### ISSUE TITLE
azure-cognitiveservices-speech for ARMv8 arch

### ISSUE THREAD

**Issue by zoro16** [Azure-Samples/cognitive-services-speech-sdk#187]
Hi,

Is it possible to build  "azure-cognitiveservices-speech" to support ARM arch ? 

I was trying to run my Bot client from Linux on [NanoPi A64](https://www.friendlyarm.com/index.php?route=product/product&product_id=159), which has 64-bit Quad-core Cortex-A53 with no luck.

**Comment by wolfma61** [comment]
There are plans for Linux ARM64 support, but no ETA we can promise right now.
Keep in mind, we currently support only these distros for Linux: Ubuntu 16.04, Ubuntu 18.04, Debian 9
It is not clear if others will be available for ARM
Also not clear what HW will be available in our test environment ...
