### ISSUE TITLE
WinUI + DialogServiceConnector + AudioConfig = ApplicationException (SPXERR_MIC_NOT_AVAILABLE)

### ISSUE THREAD

**Issue by CarteKiwi** [Azure-Samples/cognitive-services-speech-sdk#1870]
Hi,
I ported my UWP app to WinUI, and my DialogServiceConnector now raise an exception in the constructor, telling the microphone is not available (It was in my UWP app).

1. Instantiate
```
var commandsConfig = CustomCommandsConfig.FromSubscription(applicationId, subscription, region);
commandsConfig.SetProperty(PropertyId.SpeechServiceConnection_RecoLanguage, "fr-fr");

var devices = await DeviceInformation.FindAllAsync(DeviceClass.AudioCapture);
var micro = devices.FirstOrDefault((c) => c.Name.Contains("Cinema"));

var config = AudioConfig.FromMicrophoneInput(micro.Id);
_dialogServiceConnector = new DialogServiceConnector(commandsConfig, config);
```
(microID is something like: "\\?\SWD#MMDEVAPI#......"

![image](https://user-images.githubusercontent.com/12309245/223679051-6af089ea-bb0a-4f2c-bad3-9b4b5454188e.png)

**Expected behavior**
No exception.

**Version of the Cognitive Services Speech SDK**
1.26

**Platform, Operating System, and Programming Language**
 - OS: Windows 11
 - Hardware - x64, x86
 - Programming language: C#

**Comment by dargilco** [comment]
Hello again @CarteKiwi ! The string `\?\SWD#MMDEVAPI#......` does not look like the correct ID of an audio device Speech SDK expects to receive. Can you please compile one of these two projects (pick C++ or C#, does not matter), and run it on the same machine to see what device Ids it returns?
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/tools/enumerate-audio-devices
I see IDs similar to (in the format of): `{0.0.1.00000000}.{8344c489-9378-4485-b38c-08a7df204e86}`

**Comment by CarteKiwi** [comment]
Hi again :)
Sorry, I was hurry so I have not been exact in my description: the exact ID is: 
`\\?\SWD#MMDEVAPI#{0.0.1.00000000}.{4ad4b30a-7e04-427d-9ff4-d8a458ded48a}#{2eef81be-33fa-4800-9670-1cd474972c3f}`

This ID (device) is working fine in my UWP app, but not in the WinUI app, with exact same code.

I will try the C# project you shared. Let you know in a minute.

**Comment by CarteKiwi** [comment]
Interesting...  from the tool you provided, the output is:
`Capture endpoint: Microphone de bureau (2- Microsoft® LifeCam Cinema(TM)) ({0.0.1.00000000}.{4ad4b30a-7e04-427d-9ff4-d8a458ded48a})`

So the ID seems to be only part of the previous one ? 
`{0.0.1.00000000}.{4ad4b30a-7e04-427d-9ff4-d8a458ded48a}`

**Comment by CarteKiwi** [comment]
Ok.... It's working using the "small" ID. 

I am retrieving my devices ID using this:
`var devices = await DeviceInformation.FindAllAsync(DeviceClass.AudioCapture);`

Which give "full" IDs.
So I had to split my "full" ID into a "small" one: 

FROM THIS: 
`\\?\SWD#MMDEVAPI#{0.0.1.00000000}.{4ad4b30a-7e04-427d-9ff4-d8a458ded48a}#{2eef81be-33fa-4800-9670-1cd474972c3f}`
TO THIS:
`{0.0.1.00000000}.{4ad4b30a-7e04-427d-9ff4-d8a458ded48a}`


Maybe the good fix is to use the NAudio stuff from the tool ? Using the `MMDeviceEnumerator` ?

Thanks again Darren for your reactivity 👍
