### ISSUE TITLE
SynthesisWordBoundary not synchronized with actual spoken text

### ISSUE THREAD

**Issue by andrzejwiech** [Azure-Samples/cognitive-services-speech-sdk#1872]
**Describe the bug**
When adding a handler to get the boundary of words, all word events are triggered immediately as soon as the synthesizer starts to speak, rather than when each actual word is spoken. This makes the SDK unusable for iOS text-to-speech apps where the goal is to highlight the spoken word or sentence.

``self.speechSynthesizer?.addSynthesisWordBoundaryEventHandler { (synthesizer: SPXSpeechSynthesizer?, eventArgs: SPXSpeechSynthesisWordBoundaryEventArgs?) in
            if let args = eventArgs {
                let audioOffset = args.audioOffset
                let textOffset = args.textOffset
                let wordLength = args.wordLength
                print("Word boundary reached at audio offset \(audioOffset), text offset \(textOffset), word length \(wordLength)")
         }
  }``

**To Reproduce**
1. Register the addSynthesisWordBoundaryEventHandler handler with the Speech Synthesizer.
2. Start the synthesizer to speak some text.
3. Check the log and observe that events for all words are triggered immediately instead of in sync with the actual word spoken.

**Expected behavior**
Events are triggered in synch with spoken word.

**Version of the Cognitive Services Speech SDK**
1.26

**Platform, Operating System, and Programming Language**
 - OS: iOS 16.1.1
 - Hardware - iPhone 11 Pro
 - Programming language: Swift

**Comment by dargilco** [comment]
Hi @andrzejwiech, this is Darren from the Speech SDK team. Based [on this document](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-speech-synthesis?tabs=browserjs%2Cterminal&pivots=programming-language-csharp#subscribe-to-synthesizer-events), this seems like the expected behaviour: `Note: Events are raised as the output audio data becomes available, which will be faster than playback to an output device. The caller must appropriately synchronize streaming and real time.`

@yulin-li  to confirm.

**Comment by andrzejwiech** [comment]
Hi @dargilco, are you sure? Looking at documentation:

"Signals that a word boundary was received. **_This event is raised at the beginning of each new spoken word, punctuation, and sentence_**. The event reports the current word's time offset (in ticks) from the beginning of the output audio. This event also reports the character position in the input text (or [SSML](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup)) immediately before the **word** (Andrzej: so before each word, and in my case events for all words are triggered at the beginning of synthesis ) that's about to be spoken."

which would actually make sense, same as AVSpeechSynthesizerDelegate of Apple where you can get that over speechSynthesizer, which is triggered with every word.

If possible, it would be great to get an example of how to use this feature, as it seems like a must-have for text-to-speech applications to highlight spoken words. I really appreciate your help, as I love the voices in your SDK, especially the impressive Swiss German one :).

**Comment by yulin-li** [comment]
Hi, the documentation misleads you here and we will fix it. Darren is right that `Events are raised as the output audio data becomes available, which will be faster than playback to an output device. The caller must appropriately synchronize streaming and real time`

for the sample, you can colloect the word boundary events and put them into a queue, and then sync them to audio playback in another thread (see the js sample as a reference  https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/synthesis.html#L276)

**Comment by andrzejwiech** [comment]
@yulin-li, thank you for the answer. However, I am using Swift on iOS, where I simply use self.speechSynthesizer.startSpeakingText(text) to start the speech. I am not using any player that I handle on my own. I have to say that it is a bit disappointing that those events have to be synchronized by consume. It does seem to defeat the purpose of an event, which is a bit misleading, I have to say. Nevertheless, I would appreciate it if you could point me to a resource that could explain how I could achieve what I intend to do on iOS ideally using Swift.

**Comment by andrzejwiech** [comment]
@yulin-li , I played bit more to see how I can stream data rather then play it in default speaker. However I encountered issue playing WAV in AVAudioPlayer. Raised another defect: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1874. 

When it comes to this issue I still believe it is confusing to call  [these:]( https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-speech-synthesis?tabs=browserjs%2Cterminal&pivots=programming-language-csharp#subscribe-to-synthesizer-events) events, from what I now understand they are rather infos about events that will happen and **not actual events**.

**Comment by yulin-li** [comment]
> @yulin-li, thank you for the answer. However, I am using Swift on iOS, where I simply use
> 
> `self.speechSynthesizer.startSpeakingText(text)`
> 
> to start the speech. I am not using any player that I handle on my own. I have to say that it is a bit disappointing that those events have to be synchronized by consumer. It does seem to defeat the purpose of an event, which is a bit misleading, I have to say. Nevertheless, I would appreciate it if you could point me to a resource that could explain how I could achieve what I intend to do on iOS ideally using Swift.
> 
> I though also that if I would new exact start of synthesis, I could then handle the rest myself, but to get that info you have to also use an event (addSynthesisStartedEventHandler), which has the same problem as other events. What would be the purpose of that event then btw if it is not really signalling speech start?

I understand this a gap that make the SDK customers spend time on sync these events with the audio time. We appreciate your suggestion and I opened an internal work item to track and we will imporve this in the future releases.

**Comment by pankopon** [comment]
@yulin-li Thanks for the update. Can you please mention the internal work item id here?

**Comment by pankopon** [comment]
Closing the issue as there is now a work item on the backlog for future improvement, no schedule estimate.
