### ISSUE TITLE
SDK not able access model files on Android 29+ API

### ISSUE THREAD

**Issue by HunterPillu** [Azure-Samples/cognitive-services-speech-sdk#1873]
**SDK not able access model files on Android 29+ API**

**To Reproduce**
1. Upgrade sample app to 30+ target/compile sdk
2. Observe 

**Expected behavior**
App should access model files from SD Card.

**Version of the Cognitive Services Speech SDK**
com.microsoft.cognitiveservices.speech:client-sdk:1.25.0

**Platform, Operating System, and Programming Language**
 - OS: Android
 - Programming language: Kotlin

**Comment by jhakulin** [comment]
@HunterPillu Thanks for the report. Firstly, we need to update our sample documentation to inform better about this limitation.

Direct SD card access will not work if the application specifies a target API level 30 (Android 11) or higher.
See https://developer.android.com/about/versions/11/privacy/storage for information on alternatives how to solve the issue in your application. 

In this sample https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/java/android/embedded-speech, requestLegacyExternalStorage property (https://developer.android.com/about/versions/11/privacy/storage#scoped-storage) is used avoid the issue when running devices on Android 11 or higher, however the limitation is that application need to targets at max 29 API level.

**Comment by jhakulin** [comment]
Closing as answered, let us know if there are any questions further.

**Comment by jhakulin** [comment]
Internal workitem reference: 4986589 for sample documentation update
