### ISSUE TITLE
WAV created with SPXAudioDataStream not playable in AVAudioPlayer

### ISSUE THREAD

**Issue by andrzejwiech** [Azure-Samples/cognitive-services-speech-sdk#1874]
**Describe the bug**
Not able to play dataStream.wav with AVAudioPlayer from "Start synth to file with audio data stream" of https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/objective-c/ios/synthesis-samples 

**To Reproduce**
1. add below code to `synthesisToAudioDataStream` of `ViewController` before `[self updateResultText:@"Speech synthesis was completed."];` line
   ` AVAudioPlayer *audioPlayer = [[AVAudioPlayer alloc] initWithContentsOfURL:fileURL error:&error];
    if (error) {
        NSLog(@"Error creating AVAudioPlayer: %@", [error localizedDescription]);
        return;
    }`
2. Run sample App
3. Enter text in input field
4. Select "Start synth to file with audio data stream"
5. Observe log
6. Looks like WAV file is corrupted: 
    Error creating AVAudioPlayer: The operation couldn’t be completed. (OSStatus error 1954115647.) - code indicates that WAV is corrupted

**Expected behavior**
Generated  dataStream.wav should be played.

**Version of the Cognitive Services Speech SDK**
1.26

**Platform, Operating System, and Programming Language**
 - OS: iOS 16.1.1
 - Hardware - iPhone 11 Pro
 - Programming language: Swift

**Comment by BrianMouncer** [comment]
@andrzejwiech 

I suspect creating the av player inside the SynthesisCompletedEventHandler callback, av engine will try to read the file before the file is flushed and closed yet.

Try moving your av play calls outside of the event callback (line 433), and put it right after lines 401-402

    [file closeFile];
    [self updateResultText:@"Speech synthesis was completed."];
    
That will ensure the synthesizers main thread is unblocked, the while loop has finished copying bytes to the file, and the file has been properly close... before the av player tries to open and read the file.

If that does not help, let me know and I can ask a teammate that is better with the objective-c projection layers,

Brian.

**Comment by andrzejwiech** [comment]
hi @BrianMouncer 

Actually that is where I had it. But I started to think that it might be overall WAV issue of AVAudioPlayer, as I tested two scenarios:

- play WAV bundled with app - OK
- play same WAV but dowloaded from Internet - NO OK (OSStatus error 1954115647)

So second scenario would be mimic scenario I described in here with SPXAudioDataStream usage and issue is the same.
Interesting thing is that when I do second scenario for all works OK so somehow there is an issue only with downloaded WAV.
I will still play around if I can somehow resolve it and let you know.

**Comment by andrzejwiech** [comment]
Actually regarding downloaded WAV I managed to make it work by adding fileTypeHint: AVFileType.wav.rawValue (Swift). Unfortunately for SPXAudioDataStream I still cannot make it work.

**Comment by andrzejwiech** [comment]
OK got it working by changing to mp3 extension with file creation and setting:

`self.speechConfig?.setSpeechSynthesisOutputFormat(SPXSpeechSynthesisOutputFormat(rawValue: 5)!)`

**Comment by pankopon** [comment]
@yulin-li Please advise on the question about how to get a playable WAV file from synthesis output on iOS with Swift.

**Comment by yulin-li** [comment]
@andrzejwiech thanks for reporting this issue. I am checking it.

**Comment by pankopon** [comment]
@yulin-li Any update?

**Comment by pankopon** [comment]
Closed since no update in 6 months -> either obsolete or unsupported. @yulin-li FYI

**Comment by margox** [comment]
Facing the same issue as I am using `scheduleBuffer` of `AVAudioPlayerNode` to play `SPXAudioDataStream` which `initFromSynthesisResult`,the player makes a harsh and loud howling sound instead of normal synthesized voice when playing.

**Comment by margox** [comment]
> 启动

大佬，这个问题有解决方案吗？
