### ISSUE TITLE
About the impact of audio loudness on speech recognition results

### ISSUE THREAD

**Issue by czkoko** [Azure-Samples/cognitive-services-speech-sdk#1875]
I use speech recognition for pre-recorded audio files, I use ffmpeg to convert wav that meets the requirements.

`ffmpeg -ac 1 -ar 16000 -af loudnorm=I=-23.0:TP=-2.0`

At first, I didn't use the -af command to adjust the loudness, but later I found that different loudnesss affect the recognition results, and some words may be different.

Is there an officially recommended loudness value?

**Comment by BrianMouncer** [comment]
@czkoko It hass been a few days, so I want to give you at least a partial reply.

I am not that familiar with ffmpe command line options. In general SNR matters more than overall volume, so my quick advice is to make the audio as loud as possible without introducing any clipping of the high energy peaks in your sample files.

I've asked our SR Engine team to see if they have any recommendation on what normalization settings to use if using ffmpeg to preprocess a bunch of input files, but it may take them a little longer to reply.

Hope this help, and I will update this when I get more information from my teammates.

**Comment by BrianMouncer** [comment]
More detailed answer from speech science and engine team:

- Our models are trained with a large variation of volumes, so in general, accuracy vs. volume variation curve is pretty flat and drops off sharply at either end. e.g. too weak audio could lead Voice Activity Detection could reject the audio entirely, too high leads to distortion (popping and clipping sound). 

- If you are normalizing your audio, we recognize best when long term (e.g. 1 minutes) speech amplitude histogram does not show significant "cut-off" in both low and high value areas.
