### ISSUE TITLE
SDK sends back recognised text every 30s, how can I extend this duration?

### ISSUE THREAD

**Issue by yeyutong811** [Azure-Samples/cognitive-services-speech-sdk#1877]
I am using this SDK on Unity on Mac.
Desired behaviour: When button is clicked, if speech haven't start, start speech to text recognition. If speech has started, stop speech to text recognition. In another script, the message is being read off when it is not empty or same as the previous message.
Actual behaviour: When speech is longer than 30s, message only shows up to 30s of what was being spoken. When the next 30s is recognised, the new 30s message replaces the first 30s message. The message only stores 30s worth of message every time, when the button has not been pressed again to stop the speech to text. The speech to text is successful and not cancelled, as the result.Reason always shows RecognizedSpeech. After asking on Azure Forum, I also tried shifting the speechConfig and AudioConfig to the top of ButtonClick(), but this seem to prevent the startRecordButton from working properly after one recognition.
How can I allow speech of more than 30s to be recognized at one go? Is it a setting of the SDK that I can change, or how can I change my code accordingly? I'm quite a newbie in this, would really appreciate some detailed explanations. Thank you.

My code:
`using UnityEngine;
using UnityEngine.UI;
using Microsoft.CognitiveServices.Speech;
using Microsoft.CognitiveServices.Speech.Audio;
using TMPro;
public class SpeechToText : MonoBehaviour
{
    public TextMeshProUGUI outputText;
    public Button startRecordButton;
    SpeechRecognizer recognizer;
    SpeechConfig speechConfig;
    AudioConfig audioConfig;
    private object threadLocker = new object();
    private bool speechStarted = false;
    public string message;
    public bool sentenceIsRecognized = false;
    private void RecognizedHandler(object sender, SpeechRecognitionEventArgs e)
    {
        lock (threadLocker)
        {
            message = e.Result.Text;
            Debug.Log("threadlocker message :" + message);
            Debug.Log("Cancellation reason:" + e.Result.Reason);
        }
        
    }
    public async void ButtonClick()
    {
        if (ChatGPTTester.executeCount >= 2) {
            if (speechStarted)
            {
                await recognizer.StopContinuousRecognitionAsync().ConfigureAwait(false);
                lock(threadLocker)
                {
                    speechStarted = false;
                    Debug.Log("STT message :" + message);
                    
                    sentenceIsRecognized = true;
                }
            }
            else
            {
                await recognizer.StartContinuousRecognitionAsync().ConfigureAwait(false);
                lock (threadLocker)
                {
                    speechStarted = true;
                }
            }
        }
    }
    void Start()
    {
        startRecordButton.onClick.AddListener(ButtonClick);
        speechConfig = SpeechConfig.FromSubscription("", "");
        speechConfig.SetProperty(PropertyId.Speech_SegmentationSilenceTimeoutMs, "4500");
        audioConfig = AudioConfig.FromDefaultMicrophoneInput();
        recognizer = new SpeechRecognizer(speechConfig, audioConfig);
        recognizer.Recognized += RecognizedHandler;
    }
    void Update()
    {
        lock (threadLocker)
        {
            if (outputText != null)
            {
                outputText.text = message;
            }
        }
    }
}`

**Comment by jhakulin** [comment]
Closed as answered, let us know if you have any further questions.
