### ISSUE TITLE
[JS]ConversationTranslator join the conversation

### ISSUE THREAD

**Issue by lenqing6** [Azure-Samples/cognitive-services-speech-sdk#1880]
**Describe the bug**
[A clear and concise description of what the bug is.](error: Error: Invalid operation: the conversation is not in a connected state.)

**Expected behavior**
1. I want to know why this error occurs frequently when I join conversation.
2. How to modify the source language after I join conversation.

**Version of the Cognitive Services Speech SDK**
"microsoft-cognitiveservices-speech-sdk": "1.23.0"

**Platform, Operating System, and Programming Language**
 - OS:Windows
 - Hardware -  x86
 - Programming language: JavaScript
 - Browser Chrome

**Comment by glharper** [comment]
@lenqing6 Thank you for using the JS Speech SDK, and writing this issue up. 
For question 1:
Could you supply example code you are using to reproduce this error? How are you creating the conversation that conversation translator is joining?
For question 2:
I don't believe the source language can be changed once conversation translation begins.

**Comment by jhakulin** [comment]
@lenqing6 Please provide further details on the issue and we will investigate further.

**Comment by pankopon** [comment]
Closed since no further information provided, please open a new issue if more support is needed.
