### ISSUE TITLE
Conversation Translation with Stream Input from WSS

### ISSUE THREAD

**Issue by rajeshr6r** [Azure-Samples/cognitive-services-speech-sdk#1882]
**Describe the bug**
Audio format handling issues when speech translation recognition with WSS stream

**To Reproduce**
1. Run this code in Flask : https://gist.github.com/rajeshr6r/349d32e9b565159fe07e1dfc80f5b1d2

**Expected behavior**
Expect the media payload to be sent through the recognizer and the translation happening.

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using. '1.26.0'

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - **Linux on Chrome**
 - Hardware - x64, x86, ARM, ... **x86**
 - Programming language: C#, C++, Java, JavaScript, Objective-C, **Python**
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific

**Additional context**
 - Error messages, stack trace, sample code to reproduce the issue, ...
 
Error Log :  https://gist.github.com/rajeshr6r/69ab3a2b8442ffd6117aa346b648b2bf
 
 - Please provide full Speech SDK Log, as per the instructions [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging)?
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by chschrae** [comment]
Hi @rajeshr6r 

I looked at your error log and code and I can't see anything particularly wrong with it. I did notice that you don't have a spot closing your push_stream when you are complete which you should do at the end of a stream according to the sample here: https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_sample.py

Could you also collect some SDK logs via the mechanism described here: https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

**Comment by jhakulin** [comment]
@rajeshr6r Could you please provide SDK log as instructed above?

**Comment by pankopon** [comment]
Closed since no further information provided, please open a new issue if more support is needed.
