### ISSUE TITLE
ITN performance for Icelandic

### ISSUE THREAD

**Issue by HaukurPall** [Azure-Samples/cognitive-services-speech-sdk#1884]
**Describe the bug**
The ITN process is terribly implemented for Icelandic:

Given the speech:
"Einar fór einu sinni út í búð með Kofi Annan" which roughly translates to "Einar once went to the store with Kofi Annan".

The returned DisplayText is "1 fór 1 sinni út í búð með kofi 2." this result is wrong because the Inverse Text Normalization (ITN) which should convert numbers written with text to digits is applied **without consideration** to the actual meaning of the text. None, of the text converted, is actually a number. "Einar" is a name of a person, "einu [sinni]" means once and "Annan" is also a name. All of these words have the same surface form as words which **could** mean a number in Icelandic.

Compare this to the English version which handles these cases a lot better:
"Once every one of them was ready for one battle." does not change a single word to the digit variant. Clearly, if the server would return "1 every 1 of them was ready for 1 battle." the service would not be acceptible.

**To Reproduce**
1. State the sentence "Einar fór einu sinni út í búð með Kofi Annan"  in Icelandic and process the result using the SDK.

**Expected behavior**
The DisplayText "Einar fór einu sinni út í búð með Kofi Annan".

**Version of the Cognitive Services Speech SDK**
Not applicable

**Platform, Operating System, and Programming Language**
Not applicable

**Additional context**
This is probably not the correct place to report this bug but it seems to be the only place where we (Icelandic speakers) can get this important point across. Currently, this speech-to-text service is the best available for Icelandic (according to WER over multiple test sets) but this handling makes the service unusable.

According to the SDK documentation at https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/display-text-format#itn the Inverse Text Normalization (ITN) is not configurable.

I have tested the REST API and it supports returning text without ITN, which produces text without ITN, making the service usable. Sadly, it does not support (to my knowledge) streaming which is our use-case and many of our customers.

Please forward this bug report to the relevant people.

**Comment by chschrae** [comment]
Hi there,

Thanks for reaching out to us and I can understand how this would be frustrating. In our SDK there is the ability to request detailed results which should include lexical and other forms that might be better suited for your scenario. 

Could you try that?

I'm not sure which programming language you are using but here is the c# sample: https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L80

I will also forward this to our speech service team to hopefully help fix the display text issue.

**Comment by chschrae** [comment]
No problem! Glad you have it working! Feel free to open another issue if you run into any problems.
