### ISSUE TITLE
add react native support

### ISSUE THREAD

**Issue by Mootbing** [Azure-Samples/cognitive-services-speech-sdk#1886]
**Is your feature request related to a problem? Please describe.**
Write an example to be done on react native please. The official Microsoft repository has been long outdated and no longer works

**Describe the solution you'd like**
Like the javascript browser demo but better

**Describe alternatives you've considered**
I've considered using other TTS apis for react native but none are as flushed out as CSSDK

**Additional context**

**Comment by glharper** [comment]
@Mootbing Thank you for using JS Speech SDK, and for writing this issue up. I've just pushed a new branch to the official integration repo [here](https://github.com/microsoft/cognitive-services-sdk-react-native-example/tree/react-18) that works with React Native 18. If you could pull it and give your feedback, that would be much appreciated!

**Comment by glharper** [comment]
Closing as this has been addressed in the integration example repo.

**Comment by ZanPerse** [comment]
hey could u share a link this repo does not exist?
