### ISSUE TITLE
SPXSpeechRecognizer events for start and end of speech are irregular

### ISSUE THREAD

**Issue by sagarmahewar** [Azure-Samples/cognitive-services-speech-sdk#1888]
The ideal sequence for the speech recognition events is
 
#1 addSpeechStartDetectedEventHandler
#2 addSpeechEndDetectedEventHandler
#3 Result for block of SPXSpeechRecognizer->recognizeOnceAsync with uttered string
 
But intermittently, it raises addSpeechEndDetectedEventHandler without addSpeechStartDetectedEventHandler and then control pass in to recognizeOnceAsync result block without string.

This behaviour can be seen in latest version 1.26.

**Comment by chschrae** [comment]
Hi there,

Thanks for reaching out. There is in fact a scenario where this can happen and it relates to audio being captured that does not produce a speech result such as just white noise being recorded. In this case a Speech End detected event will fire before a Recognized event with a NOMATCH reason and no Speech Start event would fire.

Although I agree it is a bad name, the speech end detected event is really about the speech service telling the client to stop streaming audio.

Let me know if there is anything else we can do to help.

**Comment by sagarmahewar** [comment]
- If it is a "White noise" and firing the Speech end detected event, then logically thinking, I would say there should also be Speech start detected event fired.
- Because without start, the end won't sound like a complete process.
- For "white noise", we are sending NOMATCH, so Start speech detected event can be fired with End speech detected event.
- OR else don't send both the events at all, Just doing speech recognition with NOMATCH is enough.

**Comment by sagarmahewar** [comment]
While reworking, it will be really helpful, if you could either send both the events or do not send any event, for white noise. Thank you.

**Comment by sagarmahewar** [comment]
I see ticket closed without an update on rework status. Any update on it's rework? Thanks.
