### ISSUE TITLE
About network 

### ISSUE THREAD

**Issue by hold-my-hand** [Azure-Samples/cognitive-services-speech-sdk#189]
When there is no network, it will not work. 
When the network is restored, how to restore the identification?

**Comment by wolfma61** [comment]
the sdk requires connection to the speech service to perform its operations. 
for short network outages the SDK might be able to recover. Otherwise you will have to create a new recognizer.

thx
Wolfgang

**Comment by hold-my-hand** [comment]
yes I have done as you say
