### ISSUE TITLE
Extract the keyword text from a keyword model file?

### ISSUE THREAD

**Issue by jens-totemic** [Azure-Samples/cognitive-services-speech-sdk#1890]
Not sure if this is the best place to ask: when we generate a keyword model in Speech Studio, we enter the keyword as a string before training. When we load this model in the C++ Client Speech SDK, I didn't find a way to extract that string from the model. Is there a way to do so? Since we are using a couple of keyword models and need the keyword for further post-processing, this would kind of access would be helpful as hard-coding the keyword in our code is not feasible.

**Comment by jhakulin** [comment]
@jens-totemic Currently Speech SDK API do not provide a way to read keyword string from the model.
@hasyashah Would you comment is there a way to read the keyword string from .table file?

**Comment by hasyashah** [comment]
Tagging @aazeez442 to help with this.

**Comment by pankopon** [comment]
@hasyashah Any update from @aazeez442?

**Comment by aazeez442** [comment]
Hi @jens-totemic. Can you kindly provide us with more detail on your specific use-case for the on-device Keyword model. Keyword models do generate a text output(string) anytime there is a detection event within a stream of audio. Can you explain in more detail what you mean by needing the keyword text output(string) for further post-processing? Are you looking to pass on the keyword text output to another keyword verification stage? Also are you looking for a programmatic way to output a keyword text output without passing audio to the model? Providing us with more details on your use case will enable us better guide here. Thanks

**Comment by jens-totemic** [comment]
Hi @aazeez442 , thank you for looking into this question. We are processing the recognized text and a simple use-case that we are implementing is removing the keyword from the recognized text - if it is present (which is not always the case). Right now, we need to hard-code the keyword text for that. But in our system, we allow switching the keyword model and hence, we need to build additional functionality that associates each keyword model file with the keyword text it is triggered by. If there was a way to read the text string for the keyword straight out of the model, this would simplify this.

**Comment by jhakulin** [comment]
Closing as answered and your input is being considered in future plans of keyword recognition.

**Comment by aazeez442** [comment]
Hi @jens-totemic. If the goal is to retrieve the text string for the respective keyword models using the Speech SDK. Kindly refer to the "Text" property config for both Keyword Recognition and Speech Recognition API's.     
	• Details on KeywordRecognitionResult. "Text" output property for keyword text only: 
	[https://learn.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.keywordrecognitionresult?view=azure-dotnet#properties](url)
	• Details on SpeechRecognitionResult.  "Text" output property for keyword text + speech recognition result: 
	[https://learn.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechrecognitionresult?view=azure-dotnet#properties](url)	
Kindly let me know if the above properties help. 
Thanks
