### ISSUE TITLE
Problem of Revisiting in Long audio stream

### ISSUE THREAD

**Issue by ankurdhuriya** [Azure-Samples/cognitive-services-speech-sdk#1892]
I am using TranslationRecognizer continuous . I have seen an issue during transcribing and translating long audios.

Eg.
I am listing all the recognized phrases timestamp

3.200:15.000,
15.200:17.000
17.200:18.100
then it will start at
4.100: 6:200
14.600:17:600

and the results are not consistent every time i try

**Comment by jhakulin** [comment]
@ankurdhuriya Thanks for the report, just to confirm you are using file input and the recognized result offsets vary (as in your report) between the different runs when using the same input?

**Comment by ankurdhuriya** [comment]
> @ankurdhuriya Thanks for the report, just to confirm you are using file input and the recognized result offsets vary (as in your report) between the different runs when using the same input?

yes

**Comment by jhakulin** [comment]
Internal workitem ref: 5301525

**Comment by jhakulin** [comment]
@ankurdhuriya Sorry for the delayed response, could you still clarify following questions?
1. Did you use the long audio file as an input to FromStreamInput method by reading the bytes from the file to stream or directly using FromWavFileInput method (from AudioConfig object) where you give the file path to SDK?
2. What is the programming language you are using?
3. Could you please provide Speech SDK log for consecutive runs using the same file input?
https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

**Comment by pankopon** [comment]
@ankurdhuriya Can you please provide additional information as requested in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1892#issuecomment-1602043808?

**Comment by pankopon** [comment]
Closed since no further information received. Please create a new issue if more support is needed. In case the **offsets** of transcribed words are wrong, there is https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1752 about it.
