### ISSUE TITLE
TTS Audio Opus To PCM

### ISSUE THREAD

**Issue by litao09h** [Azure-Samples/cognitive-services-speech-sdk#1893]
How to convert TTS Audio Opus to PCM? Any Example?
TTS  OutputFormat:  audio-24khz-16bit-24kbps-mono-opus

[https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1653](url)

**Comment by trrwilson** [comment]
Hello!

Could you please share a bit more about how the TTS audio is requested and where the conversion needs to occur?

If you'd like text-to-speech to generate PCM audio instead of OPUS, you can provide a corresponding format tag (like `riff-16khz-16bit-mono-pcm`).

If you need to use OPUS as the output format and then later want to convert it to PCM on the client, you'll need to use an external tool like `gstreamer` -- the Speech SDK unfortunately can't provide OPUS encode/decode capabilities directly.

**Comment by litao09h** [comment]
> and



> Hello!
> 
> Could you please share a bit more about how the TTS audio is requested and where the conversion needs to occur?
> 
> If you'd like text-to-speech to generate PCM audio instead of OPUS, you can provide a corresponding format tag (like `riff-16khz-16bit-mono-pcm`).
> 
> If you need to use OPUS as the output format and then later want to convert it to PCM on the client, you'll need to use an external tool like `gstreamer` -- the Speech SDK unfortunately can't provide OPUS encode/decode capabilities directly.

We use the rest api method to request tts. opus is the highest compression rate and the most commonly used encoding method. Please specify the format as "audio 24 khz 16 bit 24 kbps mono opus"

When playing on the client, we need to transcode the OPUS audio to PCM format before playing Can audio-opus be played directly without transcoding?

 We use the rest api method to request tts. opus is the highest compression rate and the most commonly used encoding method. The "format"  parameter is "audio-24khz-16bit-24kbps-mono-opus".

When playing on the client, we need to transcode the OPUS audio to PCM format.  Can audio-opus be played directly without transcoding on andriod platform?

**Comment by litao09h** [comment]
> Hello!
> 
> Could you please share a bit more about how the TTS audio is requested and where the conversion needs to occur?
> 
> If you'd like text-to-speech to generate PCM audio instead of OPUS, you can provide a corresponding format tag (like `riff-16khz-16bit-mono-pcm`).
> 
> If you need to use OPUS as the output format and then later want to convert it to PCM on the client, you'll need to use an external tool like `gstreamer` -- the Speech SDK unfortunately can't provide OPUS encode/decode capabilities directly.

We use the rest api method to request tts. opus is the highest compression rate and the most commonly used encoding method. The "format" parameter is "audio-24khz-16bit-24kbps-mono-opus".

When playing on the client, we need to transcode the OPUS audio to PCM format. Can audio-opus be played directly without transcoding on andriod platform?

**Comment by yulin-li** [comment]
The speech SDK requests `mp3` format and decoding it to pcm on Android. We suggest you using this built in ability.

**Comment by jhakulin** [comment]
Closing as answered, let us know if you have any further questions
