### ISSUE TITLE
In Android, how to implement ContinuousRecognitionAsync for a wav file which is stored on a server?

### ISSUE THREAD

**Issue by ominfowave** [Azure-Samples/cognitive-services-speech-sdk#1895]
Speech SDK: com.microsoft.cognitiveservices.speech:client-sdk:1.25.0

I want to transcribe/recognize a wav file that is stored on our Google cloud bucket, I couldn't find any demo code to implement this.

**Comment by trrwilson** [comment]
Hello!

There are a few potential approaches.

If it's viable to expose these .wav files as externally-visible URLs, batch transcription is explicitly designed for this asynchronous transcription of a file stored elsewhere: https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription-audio-data?tabs=portal

Batch *does not* support generalized pass-through authentication, though, so it's not a good fit if login or other steps are required to retrieve the files of interest.

Moving to the SDK, the simplest option is to download the files locally and then use file input as the audio configuration source. You can see examples of this in the Java speech recognition samples:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java#L258

If more real-time behavior is needed (you'd like recognition to take place before downloading the entire file), the Speech SDK also supports audio input from arbitrary sources via its PushAudioInputStream and PullAudioInputStream classes. You can configure a recognizer with an `AudioConfig` made from an input stream source and then either write the audio data to the stream (in the case of "push" streams) or provide data on a callback upon request (for "pull" streams).

You can see an Android example of this with one of the keyword recognition samples:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/java/android/keyword-recognizer-stream/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/quickstart/MainActivity.java#L122

There, a stream is created from a keyword recognition result for use in a subsequent (open-ended) speech recognition operation; the pattern is equally applicable to data coming from another source.

We can't advise on how to best retrieve data from Google Cloud, but once you have the file or bytes you should be able to use that file or push its data into a stream per the above.

**Comment by ominfowave** [comment]
@trrwilson I understand that Azure can not get audio data directly from the Google Cloud bucket service. But what if an audio file is on an open server? Is there any way to use a streamable open URL of an audio file directly with any of the Azure STT methods without downloading the data on the client side?

**Comment by rhurey** [comment]
Hey @ominfowave!

The Azure Speech Service's Batch API's can read audio from a publicly accessible URL and provide the transcription when complete.

The Speech SDK is more oriented towards real-time use on devices that are both the source or audio and destinations for the transcription.

You can read more about Batch [here](https://learn.microsoft.com/azure/cognitive-services/speech-service/batch-transcription-audio-data?tabs=portal).

There's a sample of creating a batch request for audio stored at a URL here: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/csharp/batchclient

**Comment by jpalvarezl** [comment]
Closed due to inactivity
