### ISSUE TITLE
Recording audio with Javascript and using it with Microsoft Cognitive Services

### ISSUE THREAD

**Issue by GuiOliv** [Azure-Samples/cognitive-services-speech-sdk#1898]
As the title suggests, I am making a web application in ASP.Net Core MVC that records the audio from the user's computer:

```
`function startRecording(btn) {
    var countdown = 5;
    var audioChunks = [];
    var audioContext = new AudioContext();
    var mediaRecorder = null;
    var options = { mimeType: 'audio/webm' }; //I tried changing it to audio/wav but it doesn't work

```
    navigator.mediaDevices.getUserMedia({ audio: true })
        .then(function (stream) {
            mediaRecorder = new MediaRecorder(stream, options);
            mediaRecorder.start();

            setTimeout(function () {
                mediaRecorder.stop();
                stream.getTracks().forEach(track => track.stop());
                btn.text("Waiting for the results");
            }, countdown * 1000);

            mediaRecorder.addEventListener("dataavailable", function (event) {
                audioChunks.push(event.data);
            });

            mediaRecorder.addEventListener("stop", function () {
                var blob = new Blob(audioChunks, { type: 'audio/wav' });
                var formData = new FormData();
                formData.append('audioBlob', blob);

                $.ajax({
                    url: '@Url.Action("ProcessAudio", "Home")',
                    type: 'POST',
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function (data) {
                        // Display the result in the modal
                        $('#modalContent').html(data);

                        // Show the modal
                        $('#myModal').modal('show');
                    },
                    error: function () {
                        console.log('Error processing audio');
                    }
                });
            });
        })
        .catch(function (error) {
            console.log('Error starting recording:', error);
        });
}`

Then I process and save the audio into a file within the server:

`[HttpPost]
    public IActionResult ProcessAudio(IFormFile audioBlob)
    {
        string filePath = Path.Combine(_env.WebRootPath, "Resources", "recording.wav");

        if (audioBlob != null && audioBlob.Length > 0)
        {
            using (var stream = audioBlob.OpenReadStream())
            {
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    stream.CopyTo(fileStream);
                }
            }
        }

        var model = new AudioReadingModel(filePath);

        model.RecordAndCalculate();
        return PartialView("ShowResults", model);
    }`
    
However, when I hit the following line in my code:

`var recognizer = new Microsoft.CognitiveServices.Speech.SpeechRecognizer(config, AudioConfig.FromWavFileInput(AudioPath));`

It gives me the following exception:

> System.AggregateException: 'One or more errors occurred. (Exception with an error code: 0xa (SPXERR_INVALID_HEADER))'

The file has the .wav extension and I can listen to it on my computer so I really need help finding out what is going on. Can anybody help me?

**Comment by jhakulin** [comment]
@GuiOliv The recorded audio format inside wave container is probably not supported and that causes the error. The supported audio format inside the wave container shall be PCM 16kHz, 16bit, mono. Would you mind sharing the audio file recorded by MediaRecorder?

**Comment by pankopon** [comment]
@glharper Please advise on this question.

**Comment by pankopon** [comment]
@GuiOliv Sorry for the delay with this, but in case your question is still valid, it seems the file you uploaded has expired - can you please re-upload?
To set a specific format, you could try audio constraints (see e.g. https://stackoverflow.com/questions/62392352/mediadevices-getusermedia-how-can-i-set-audio-constraints-sampling-rate-bit-d).

**Comment by pankopon** [comment]
Closed as suggestions have been provided. Please open a new issue if more support is needed.

**Comment by jigarcognino** [comment]
https://www.npmjs.com/package/@types/react-mic and
const startRecording = () => {
        setRecord(true);
    };

    const stopRecording = () => {
        setRecord(false);
    };

    const onData = (recordedBlob: any) => {
        console.log("chunk of real-time data is: ", recordedBlob);
    };

    const onStop = (recordedBlob: any) => {
        console.log("recordedBlob is: ", recordedBlob);
        makeApiRequest(recordedBlob);
    };
const makeApiRequest = async (recordedBlob: any) => {
        const audioFile = new File([recordedBlob.blob], "audio.wav", recordedBlob.options);
        const result = await speechApi(audioFile);
        console.log(result);
    };
<ReactMic
                className="sound-wave"
                strokeColor="#000000"
                backgroundColor="#FF4081"
                mimeType="audio/wav"
                record={record}
                onStop={onStop}
                onData={onData}
                channelCount={1}
            />
[audio.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/12803892/audio.zip)
weatherfilename='audio.wav'
def speech_recognize_once_from_file():
    """performs one-shot speech recognition with input from an audio file"""
    # <SpeechRecognitionWithFile>
    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)
    audio_config = speechsdk.audio.AudioConfig(filename=weatherfilename)
    # Creates a speech recognizer using a file as audio input, also specify the speech language
    speech_recognizer = speechsdk.SpeechRecognizer(
        speech_config=speech_config, language="de-DE", audio_config=audio_config)

    # Starts speech recognition, and returns after a single utterance is recognized. The end of a
    # single utterance is determined by listening for silence at the end or until a maximum of 15
    # seconds of audio is processed. It returns the recognition text as result.
    # Note: Since recognize_once() returns only a single utterance, it is suitable only for single
    # shot recognition like command or query.
    # For long-running multi-utterance recognition, use start_continuous_recognition() instead.
    result = speech_recognizer.recognize_once()

    # Check the result
    if result.reason == speechsdk.ResultReason.RecognizedSpeech:
        print("Recognized: {}".format(result.text))
    elif result.reason == speechsdk.ResultReason.NoMatch:
        print("No speech could be recognized: {}".format(result.no_match_details))
    elif result.reason == speechsdk.ResultReason.Canceled:
        cancellation_details = result.cancellation_details
        print("Speech Recognition canceled: {}".format(cancellation_details.reason))
        if cancellation_details.reason == speechsdk.CancellationReason.Error:
            print("Error details: {}".format(cancellation_details.error_details))
    # </SpeechRecognitionWithFile>


give me Error(Exception with an error code: 0xa (SPXERR_INVALID_HEADER)
