### ISSUE TITLE
use texttospeech in linux 64(CentOS 7.6.1810 x86_64(Py3.7.9)) error,how can I do?

### ISSUE THREAD

**Issue by renrenduxing** [Azure-Samples/cognitive-services-speech-sdk#1899]
in linux 64(CentOS 7.6.1810 x86_64(Py3.7.9))
by debug and log，find the error Occurring at that code:
SpeechConfig.FromSubscription(key, regin)
error message:One or more errors occurred. (Unable to load shared library 'libMicrosoft.CognitiveServices.Speech.core.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibMicrosoft.CognitiveServices.Speech.core.so: cannot open shared object file: No such file or directory) 
but i use in windows to debug is normal
how to deal this error

**Comment by yulin-li** [comment]
Hi, could you follow [this instruction](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7) to set up the environment on CentOS 7?

**Comment by renrenduxing** [comment]
> Hi, could you follow [this instruction](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7) to set up the environment on CentOS 7?

thanks，I‘ll try

**Comment by renrenduxing** [comment]
> Hi, could you follow [this instruction](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7) to set up the environment on CentOS 7?
I have configured C++according to the documentation, but it still does not work, with the same error reported

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
