### ISSUE TITLE
System.AggregateException: 'One or more errors occurred.'

### ISSUE THREAD

**Issue by bluemonk482** [Azure-Samples/cognitive-services-speech-sdk#19]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>I simply downloaded the repo, didn't change any code, and tried to build the solution in the "Windows/csharp_samples" directory, following the instructions provided on the webpage. 

### Any log messages given by the failure
```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at MicrosoftSpeechSDKSamples.Program.Main(String[] args) in C:\Users\bwang\Downloads\cognitive-services-speech-sdk-master\Windows\csharp_samples\Program.cs:line 43

Inner Exception 1:
ApplicationException: Exception with an error code: 0x8
[CALL STACK]

    > CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - SpeechFactory_CreateSpeechRecognizer_With_FileInput

    - CSharp_MicrosoftfCognitiveServicesfSpeechfInternal_IntentRecognitionEventArgs_SWIGUpcast___

    - CSharp_MicrosoftfCognitiveServicesfSpeechfInternal_ICognitiveServicesSpeechFactory_CreateSpeechRecognizerWithFileInput__SWIG_0___

    - 00007FFB7C3B7030 (SymFromAddr() error: The specified module could not be found.)
```

Screenshot: http://i63.tinypic.com/2zp59hz.png

### Expected/desired behavior
>

### OS and Version?
> Windows 10 Enterprise. 

### Versions
>Version	10.0.16299 Build 16299

### Mention any other details that might be useful
> http://i68.tinypic.com/125mmme.png

**Comment by bluemonk482** [comment]
Can I also please ask the difference between the speech model used here and the one used in the [Bing SDK](https://github.com/Azure-Samples/Cognitive-Speech-STT-ServiceLibrary) ?? Is this one the new and updated one that in theory should give better transcription performance? thanks!

**Comment by zhouwangzw** [comment]
Were you doing recognition from a file? The error could be that the file cannot be accessed.

This the new speech SDK support customized model and other new features like translation. We recommend to use this new speech SDK, and the Bing SDK will be deprecated in future.

**Comment by bluemonk482** [comment]
The error comes from selecting "3" for transcription from a file. As soon as I press "3", I get the error message. I was given no chance for entering the file path.

Thanks very much! I want to use Speech API for transcribing our audio files. Is the transcription model used by the new speech SDK the same as the Bing SDK? We definitely want to use the newest model but we have already tested the Bing SDK so we need to know the difference. Thanks.

**Comment by zhouwangzw** [comment]
In order to use samples, you first need to replace "YourLuisSubscriptionKey", "YourLuisServiceRegion", and "YourAudioFile.wav" with your own key, service region, and audio file in the sample code you cloned. We will add documentation for that in README.md. Sorry for the inconvenience. 

The model used by new speech service is not exactly the same as the Bing SDK, but should provide same or better result in general. If you see unmatched results, please let us know.

**Comment by mahilleb-msft** [comment]
I've added READMEs for the samples. Closing this issue here, please re-open (or open a new one) if questions / issue remain.

Thanks, Mark
