### ISSUE TITLE
Speech ot text Batch API for CustomSpeechModel with python. api.getmodel(MODELREFERENCE) missing

### ISSUE THREAD

**Issue by avinashtarale** [Azure-Samples/cognitive-services-speech-sdk#1903]
**Describe the bug**

**To Reproduce**
1. Followed the steps mentioned in the link: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python
2. Replaced the variables for the custom speech model. Uploaded 10 audio files in blob storage and added Blob SAS uri in the python script.

**Expected behavior**
I get a error while using the function 'transcribe_with_custom_model', I get the error for method get_model.
Provided below the error message.

 File "C: sample_folder\main.py", line 60, in transcribe_with_custom_model
    model = api.get_model(MODEL_REFERENCE)
            ^^^^^^^^^^^^^
AttributeError: 'CustomSpeechTranscriptionsApi' object has no attribute 'get_model'

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using. : 3.1

**Platform, Operating System, and Programming Language**
 - OS: Windows
 - Hardware - x64,
 - Programming language:  Python

**Comment by chlandsi** [comment]
Hi @avinashtarale , there is indeed an error in the sample. There is an updated working version in #1905, it will be merged soon. Thanks for reporting and sorry for the inconvenience!

**Comment by pankopon** [comment]
Closed as resolved, please open a new issue if more support is needed.
