### ISSUE TITLE
I have brand new keys from azure but speaker recognition will not work

### ISSUE THREAD

**Issue by mycloudvip** [Azure-Samples/cognitive-services-speech-sdk#1906]
I can pretty much try any service: TTS, STT, but speaker recognition will not work:

I get this error

Unable to contact server. StatusCode: 1006, undefined Reason:  undefined

**Comment by jhakulin** [comment]
@mycloudvip Speaker recognition is under limited access preview which you need to apply separately, did you do that?
See the instructions on how to apply here
https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speaker-recognition-overview

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
