### ISSUE TITLE
SpeechRecognizer.finalize() timed out after 10 seconds This Crash Caused By ANR 

### ISSUE THREAD

**Issue by ytunique** [Azure-Samples/cognitive-services-speech-sdk#191]
In the case of a weak net, a crash often occurs

1 com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.delete_Recognizer(Native Method)
--
2 com.microsoft.cognitiveservices.speech.internal.Recognizer.delete(Recognizer.java:32)
3 com.microsoft.cognitiveservices.speech.internal.SpeechRecognizerBase.delete(SpeechRecognizerBase.java:37)
4 com.microsoft.cognitiveservices.speech.internal.SpeechRecognizer.delete(SpeechRecognizer.java:37)
5 com.microsoft.cognitiveservices.speech.internal.SpeechRecognizer.finalize(SpeechRecognizer.java:26)
6 java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:229)
7 java.lang.Daemons$FinalizerDaemon.run(Daemons.java:207)
8 java.lang.Thread.run(Thread.java:818)

**Comment by mahilleb-msft** [comment]
Hi @ytunique, do you have any additional information to share, for example a session ID when this occurs?

**Comment by mahilleb-msft** [comment]
Before this happens, do you see any error message from the service ? 
If you're using continuous recognition, please add an event handlers to print this (similar to here https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java#L176)
As soon as an error occurs, you should be destroying the recognizer and use a new one.

**Comment by cuizehui** [comment]
any update? 
As soon as an error occurs, my Application was crashed ,so I can't Use a new One

**Comment by cuizehui** [comment]
> Before this happens, do you see any error message from the service ?
> If you're using continuous recognition, please add an event handlers to print this (similar to here https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java#L176)
> As soon as an error occurs, you should be destroying the recognizer and use a new one.

any update?
As soon as an error occurs, my Application was crashed ,so I can't Use a new One

**Comment by wolfma61** [comment]
closing due to missing feedback

**Comment by wall3001** [comment]
> In the case of a weak net, a crash often occurs
> 
> ## 1 com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.delete_Recognizer(Native Method)
> 2 com.microsoft.cognitiveservices.speech.internal.Recognizer.delete(Recognizer.java:32)
> 3 com.microsoft.cognitiveservices.speech.internal.SpeechRecognizerBase.delete(SpeechRecognizerBase.java:37)
> 4 com.microsoft.cognitiveservices.speech.internal.SpeechRecognizer.delete(SpeechRecognizer.java:37)
> 5 com.microsoft.cognitiveservices.speech.internal.SpeechRecognizer.finalize(SpeechRecognizer.java:26)
> 6 java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:229)
> 7 java.lang.Daemons$FinalizerDaemon.run(Daemons.java:207)
> 8 java.lang.Thread.run(Thread.java:818)
Can you resolve it？

**Comment by Ulises2192** [comment]
In my case it was solved by updating to `implementation 'com.microsoft.cognitiveservices.speech:client-sdk:1.30.0'`
