### ISSUE TITLE
SpeechRecognizer cannot start from javascript after audio was played.

### ISSUE THREAD

**Issue by Thet-Ngon-Tun** [Azure-Samples/cognitive-services-speech-sdk#1910]
**SpeechRecognizer cannot start from javascript after audio was played.**

**To Reproduce**

1. play audio from javascript on [**Start**] button click
2. start recognition on audio **onEnded** event ( recognizeOnceAsync and startContinuousRecognitionAsync  )

**Expected behavior**
Start Speech To Text Recognition after Annoucemnet Audio End.

**Version of the Cognitive Services Speech SDK**
1.26.0

**Platform, Operating System, and Programming Language**
 - iOS 16.4
 - Programming language: javascript
 - Browser [Safari] 

**Additional context**
Speech Recognition cannot start without user action.

        startButton.addEventListener("click", function () {
          audio.play();
        });
        audio.addEventListener("ended", async function () {
          StartRecognition..................
        });

**Comment by rhurey** [comment]
First, thanks for trying the speech sdk!

What type is "audio" in the code block above?

**Comment by Thet-Ngon-Tun** [comment]
> First, thanks for trying the speech sdk!
> 
> What type is "audio" in the code block above?

@rhurey 
I'm sorry . I dind't mention it well. It's HTMLAudioObject.
audio = document.getElementById("announceAudio");

**Comment by glharper** [comment]
Closing this to avoid duplicate with IcM 379409329
