### ISSUE TITLE
Connection failed (no connection to the remote host)  WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED

### ISSUE THREAD

**Issue by tianyi14** [Azure-Samples/cognitive-services-speech-sdk#1911]
**Describe the bug**
Using the speech recognition text function, this error will be reported starting from April 7th

This is the error log

[logspeech.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/11188995/logspeech.txt)

**Comment by tianyi14** [comment]
Connection failed (no connection to the remote host). Internal error: 1. Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED
wss://eastasia.stt.speech.microsoft.com/speech/recognition/interactive/cognitiveservices/v1?language=en-us
X-ConnectionId: fbeac57c5c814e82bdbc9ca1d5336be5 SessionId: fbeac57c5c814e82bdbc9ca1d5336be5

**Comment by tianyi14** [comment]
The client sdk used is 1.25.0 in Java language, running on Windows

**Comment by rhurey** [comment]
Thanks for adding the SDK log, the underlying error from it was:
[912532]: 5075ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  socketio_win32.c:543 Socketio_Failure: Receiving data from endpoint: 10054.

Adn 10054 translates to:
WSAECONNRESET10054 | Connection reset by peer.
An existing connection was forcibly closed by the remote host. This normally results if the peer application on the remote host is suddenly stopped, the host is rebooted, the host or remote network interface is disabled, or the remote host uses a hard close (see setsockopt for more information on the SO_LINGER option on the remote socket). This error may also result if a connection was broken due to keep-alive activity detecting a failure while one or more operations are in progress. Operations that were in progress fail with WSAENETRESET. Subsequent operations fail with WSAECONNRESET.

So something between the client and the service reset the connection.

Can you connect using curl to download the list of supported languages?
curl https://eastasia.stt.speech.microsoft.com/api/v1.0/languages/recognition

Does the connection always fail?

**Comment by tianyi14** [comment]
curl https://eastasia.stt.speech.microsoft.com/api/v1.0/languages/recognition It can be connected.

**Comment by tianyi14** [comment]
oh,no, I just tried it for the first time and it was okay. After 20 minutes of testing, I was told that the SSL connection failed 
![飞书20230411-105352](https://user-images.githubusercontent.com/33484216/231043764-2f0993f6-b1ff-4bd4-a8e7-c2085f0741ae.jpg)

**Comment by czkoko** [comment]
[https://learn.microsoft.com/zh-cn/azure/cognitive-services/speech-service/troubleshooting?tabs=powershell#connection-closed-or-timeout](https://learn.microsoft.com/zh-cn/azure/cognitive-services/speech-service/troubleshooting?tabs=powershell#connection-closed-or-timeout)

**Comment by czkoko** [comment]
Windows 11 上存在一个已知问题，该问题可能会影响某些类型的安全套接字层 (SSL) 和传输层安全性 (TLS) 连接。 这些连接可能会出现握手失败。 对于开发人员，受影响的连接可能会在单个输入缓冲区中发送多个帧，然后发送大小小于 5 个字节的部分帧。 如果连接失败，你的应用将收到“USP 错误”、“连接关闭”、“服务超时”或“SEC_E_ILLEGAL_MESSAGE”等错误。
有一个适用于 Windows 11 的带外更新可以解决这些问题。 可以按照以下说明手动安装此更新：
[Windows 11 21H2](https://support.microsoft.com/topic/october-17-2022-kb5020387-os-build-22000-1100-out-of-band-5e723873-2769-4e3d-8882-5cb044455a92)
[Windows 11 22H2](https://support.microsoft.com/topic/october-25-2022-kb5018496-os-build-22621-755-preview-64040bea-1e02-4b6d-bad1-b036200c2cb3)

**Comment by tianyi14** [comment]
But my computer is Win10. Do I need to update to 11？

**Comment by tianyi14** [comment]
Just now I re executed the code and found that the speech recognition text is working. I didn't do anything. After restarting my computer, I ran it again and found that an error was reported again. Since then, I have never been successful again

**Comment by tianyi14** [comment]
我使用的是这里的示例代码 https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/scenarios/java/jre/console/captioning/

**Comment by tianyi14** [comment]
I am using the sample code here
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/scenarios/java/jre/console/captioning/

**Comment by czkoko** [comment]
After testing, this is a network failure in China, and I can't connect to the eastasia server too (will connect by vpn).
Connect to  [https://eastus.stt.speech.microsoft.com/api/v1.0/languages/recognition](https://eastus.stt.speech.microsoft.com/api/v1.0/languages/recognition) for test, There should be no problem.

**Comment by tianyi14** [comment]
But the audio synthesis function can be successfully called, and adding subtitles for voice to text is the only problem. Is the service accessed by the two different

**Comment by tianyi14** [comment]
yes,  Connect to https://eastus.stt.speech.microsoft.com/api/v1.0/languages/recognition，Sometimes it's possible, But even if the curl successfully responds, there are still issues with speech recognition execution

**Comment by czkoko** [comment]
Turn on the vpn for test, or create a new Subscription-Key for other regions.

**Comment by rhurey** [comment]
Speech Synthesis and Speech Recognition use different endpoints.

**Comment by tianyi14** [comment]
If it is due to network issues, audio synthesis is possible, but audio recognition failed. Although it is two endpoints, I still feel a bit strange

**Comment by tianyi14** [comment]
And even though I switched to Japan using VPN, I still reported the same error. I don't understand what caused it. This is the log of my VPN switching to Japan

[logspeech2.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/11206908/logspeech2.txt)

**Comment by tianyi14** [comment]
My system is Win10, JDK 17, language Java, SDK is 1.25.0, and I have tried both 1.26.0 and 1.27.0, but the same problem,

**Comment by rhurey** [comment]
Thanks for the additional log, it's still the same error of a peer reset happening.

Unfortunately, it's typically difficult to determine which component is resetting connections unless it's killing a lot of them, and there's usually a good number of devices between data centers.

At this point the usual path is to take a WireShark trace, find the TCP RST packets that are coming back and compare their TTL numbers to a traceroute to the service and see if we can match up a device.

**Comment by tianyi14** [comment]
I don't know if this information contains the data you need. Could you please take a look
![b51f3fa1d987f7ec6cd7b62f8f17999](https://user-images.githubusercontent.com/33484216/231642401-9e899f8a-1748-4932-8e37-587750e6cab4.png)
![fbe6295ea226fa8dbb42f3266c9e64a](https://user-images.githubusercontent.com/33484216/231642413-45fb6489-1f4b-4003-817b-a7d15d5bb198.png)

**Comment by tianyi14** [comment]
Today, I encountered a situation where I successfully called speech recognition for the first time, but when I called it again after a minute, it failed and seemed very unstable. Since then, there have been more and more failures, and I have never called it again successfully.Captioning () is a function that I encapsulate, but it is actually internally provided by Microsoft

![2ebf77fe19b32655c25e5733b2975f5](https://user-images.githubusercontent.com/33484216/231671410-fe31fd29-22f0-4982-bf4a-0ce36b4e484d.png)
![b4da1ae1407cea8fd41f2203605e95b](https://user-images.githubusercontent.com/33484216/231671445-d9bd8d56-23d8-4bd5-873d-42debd2d83ec.png)

**Comment by rhurey** [comment]
If 198.18.9.179 is the device resetting the connection it's a device in a private network address space. Perhaps a proxy between the client and the internet?

Have you tried using a China region?

**Comment by tianyi14** [comment]
We have solved this problem due to network proxies. Currently, there are issues with the Chinese network, and we have applied for a new secret key using Southeast Asia in the future

**Comment by alex-pythonista** [comment]
@tianyi14 Hello there, I am currently facing this issue with the `centralindia` region. How did you solve the problem?

**Comment by Sirorezka** [comment]
I had same problem when running 'speech sdk' through `gunicorn`. This error may be triggered when sdk can't find certificates path. What you should try to do:
1. Check that you've installed OpenSSL v1.x as it is described [setup_guide](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/quickstarts/setup-platform)
2. check that you have `SSL_CERT_DIR` env variable configured as it described in setup_guide
3. if starting server-side process as another user (using `sudo` ... or `sudo -u username`) set env variable `SSL_CERT_DIR` directly in the code to be sure that this user have the env variable correctly configured.
