### ISSUE TITLE
WasapiCapture is not recognized in the sample code

### ISSUE THREAD

**Issue by securigy** [Azure-Samples/cognitive-services-speech-sdk#1912]
I am trying to run your sample from:
[https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/dotnet-windows/speechtotext-naudio/speechtotext-naudio/Program.cs](url)

However, I cannot build it - WasapiCapture function from NAudio is not recognized. I do have at the top of the file:
`using NAudio.CoreAudioApi;`

The project references include NAudio.Core, NAudi.WinFormsm and NAudio.WinMM.

So where is the WasapiCapture coming from?

**Comment by securigy** [comment]
Nope. It does not... Besides, searching NuGet - no such package exists, despite that NAudio itself has a file WasapiCapture.cs

<packages>
  <package id="AWSSDK.Core" version="3.7.106.16" targetFramework="net48" />
  <package id="AWSSDK.Polly" version="3.7.106.37" targetFramework="net48" />
  <package id="AWSSDK.S3" version="3.7.103.46" targetFramework="net48" />
  <package id="AWSSDK.TranscribeService" version="3.7.104.25" targetFramework="net48" />
  <package id="LibVLCSharp" version="3.7.0" targetFramework="net48" />
  <package id="Microsoft.CognitiveServices.Speech" version="1.27.0" targetFramework="net48" />
  <package id="Microsoft.Win32.Registry" version="4.7.0" targetFramework="net48" />
  <package id="NAudio.Core" version="2.1.0" targetFramework="net48" />
  <package id="NAudio.WinForms" version="2.1.0" targetFramework="net48" />
  <package id="NAudio.WinMM" version="2.1.0" targetFramework="net48" />
  <package id="System.Buffers" version="4.5.1" targetFramework="net48" />
  <package id="System.Memory" version="4.5.4" targetFramework="net48" />
  <package id="System.Numerics.Vectors" version="4.5.0" targetFramework="net48" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.5.3" targetFramework="net48" />
  <package id="System.Security.AccessControl" version="4.7.0" targetFramework="net48" />
  <package id="System.Security.Principal.Windows" version="4.7.0" targetFramework="net48" />
  <package id="VideoLAN.LibVLC.Windows" version="3.0.18" targetFramework="net48" />
</packages>

**Comment by trrwilson** [comment]
Hello, @securigy -- can you tell us a bit about how you're building the sample?

I just ran through fresh attempts with Visual Studio 2022 (C# workloads installed) as well as the .NET CLI (`dotnet build` in the folder with the `.csproj`, with `dotnet --version` reporting `7.0.202`) and both successfully restored all the required packages before generating the expected executable.

This often ends up as a nuget restore step getting somehow confused; fully cleaning bin/obj folders and doing a fresh rebuild sometimes resolves the "I'm not really restored" problem.

**Comment by glecaros** [comment]
hi @securigy, is there anything you need about this issue?

**Comment by securigy** [comment]
nope, got it resolved.
