### ISSUE TITLE
Pronunciation Assessment with Custom Model

### ISSUE THREAD

**Issue by SagarK-TI** [Azure-Samples/cognitive-services-speech-sdk#1915]
We have trained a custom model using audio+human labelled transcript. When we use the pronunciation sdk on custom model endpoint the score reduces dramatically.  For example, if the term is "Fovea Centralis" the "pronScore" from baseline endpoint is 91 whereas on custom endpoint is 31.8 for the same audio. The audio I used for testing(this term) is same which is used for training the custom model.

Also tried other methods of uploading dataset using pronunciation (A list of uncommon terms without standard pronunciations in a text (.txt) file, where each term should be designated with a displayed form and a spoken form), simple text file but still on testing with the sdk on this custom model endpoint the score is on lower side, 30.8 for "Fovea Centralis" and same audio.

Is there any specific reason on why it's happening? 

Does custom model work for pronunciation assessment or is it just to improve speech to text, speech translation and batch transcription?? @yinhew @sally-baolian

**Comment by wangkenpu** [comment]
For our [official supported locales](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support?tabs=pronunciation-assessment), Pronunciation Assessment doesn't support the custom STT model now. Using a custom STT model will cause serious mismatch issues and may result in huge performance degradation. @SagarK-TI

**Comment by pankopon** [comment]
Closed as answered since no further updates in 3 weeks, please open a new issue if more support is needed.
