### ISSUE TITLE
AttributeError: module 'swagger_client' has no attribute 'CustomSpeechTranscriptionsApi'

### ISSUE THREAD

**Issue by yoonichoi** [Azure-Samples/cognitive-services-speech-sdk#1916]
Hi all! I'm following the [tutorial](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python) given in this repository and followed the exact steps that were listed, however am facing ```AttributeError: module 'swagger_client' has no attribute 'CustomSpeechTranscriptionsApi'``` error. I tried to follow what was discussed in the [previous issue](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/477), but since it was 2 years ago, I didn't find it quite useful to debug my issue. I have checked that my ```swagger-client``` is installed correctly, and have also checked that downloaded ```python-client/swagger_client/api``` folder has ```custom_speech_transcriptions_api.py``` file as well. 

This happens within the ```transcribe()``` function in [main.py](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/python/python-client/main.py), in this specific line:
```
api = swagger_client.CustomSpeechTranscriptionsApi(api_client=client)
```

I tried importing that specific attribute from the ```swagger_client``` like shown in the screenshot below, but it wasn't successful. I found out that ```__init__.py``` is not functioning correctly as I also wasn't able to import all the attributes that were mentioned in the ```__init__.py```.
<img width="1025" alt="Screen Shot 2023-04-12 at 7 39 45 PM" src="https://user-images.githubusercontent.com/111607447/231609366-cef900f8-498c-43ef-835a-7bb4d474df49.png">
How should I workaround this?

**Comment by DreamInTheMazeCZ** [comment]
CustomSpeechTranscriptionsApi를 DefaultApi로 바꾸면 해결됩니다.

api = swagger_client.CustomSpeechTranscriptionsApi(api_client=client)
→ api = swagger_client.DefaultApi(api_client=client)

https://learn.microsoft.com/en-us/answers/questions/1073397/batch-transcription-python

**Comment by zhouwangzw** [comment]
I have just tried to run the python samples, following the steps described [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python), in particular, I am using the swagger definition file
"Enter the Swagger URL for the Speech Services API: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/cognitiveservices/data-plane/Speech/SpeechToText/stable/v3.1/speechtotext.json.".

I am using python 3.10 in Anaconda.
I am able to run the samples without any issues.

![image](https://user-images.githubusercontent.com/19703521/236660837-42d8692a-c7a1-4c42-acd8-322e32788f50.png)

Please use API 3.1 which is the currently supported version. and API 2.0 is being deprecated.

**Comment by pankopon** [comment]
Closed as resolve since no further updates in 2 weeks, please open a new issue if more support is needed.

**Comment by kwongtn** [comment]
As of v3.1, afaik the following APIs are being replaced:
```py
transcription_api = cris_client.CustomSpeechTranscriptionsApi(
    api_client=client
)
webhook_api = cris_client.CustomSpeechWebHooksApi(api_client=client)
```

You'll need to replace with the following (yes these 2 unified into 1 endpoint)
```py
default_api = cris_client.DefaultApi(api_client=client)
```
