### ISSUE TITLE
 Unity - SpeechSynthesisResult AudioDuration

### ISSUE THREAD

**Issue by GrishTad** [Azure-Samples/cognitive-services-speech-sdk#1918]
In Unity editor Text to speech
AudioDuration is always 0 from SpeechSynthesisResult, but audio exists.
**To Reproduce**
1. Download Unity Cognitive Services Speech SDK Text-to-Speech [Example](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/unity/text-to-speech)
2.  Add this line in `HelloWorld.cs` on line 49
` Debug.Log(result.AudioDuration);`
3.  Result will be printed inside Unity Console

**Expected behavior**
Expected the duration of generated audio.

**Version of the Cognitive Services Speech SDK**
1.27.0.

**Platform, Operating System, and Programming Language**
 - Windows 10 Pro
 - Hardware - x64
 - Programming language: C#

**Comment by pankopon** [comment]
@yulin-li Can you please check.

**Comment by yulin-li** [comment]
Sorry for the late reply and I will take a look

**Comment by pankopon** [comment]
@yulin-li Please update the status.

**Comment by yulin-li** [comment]
This is still under investigating.

**Comment by pankopon** [comment]
@yulin-li Any update?

**Comment by pankopon** [comment]
Closed since no update in 6 months -> either obsolete or unsupported. @yulin-li FYI
