### ISSUE TITLE
PCM audio cannot be recognized.

### ISSUE THREAD

**Issue by wukun2015** [Azure-Samples/cognitive-services-speech-sdk#192]
**Describe the bug**
PCM audio cannot be recognized by sdk 1.3.1. 

**To Reproduce**
In C++ sample, when i feed mono 16bit/16KHz pcm file via AudioConfig::FromWavFileInput() in SpeechContinuousRecognitionWithFile (), exceptions are thrown as invalid header.  Same issue in Python samples and speech device SDK. 

**Expected behavior**
PCM audio shall be recognized per [AudioConfig::FromWavFileInput() declaration](https://docs.microsoft.com/en-us/cpp/cognitive-services/speech/audio-audioconfig#fromwavfileinput)  

**Version of the Cognitive Services Speech SDK**
1.3.1

**Platform, Operating System, and Programming Language**
 - OS: Windows 10 Enterprise
 - Hardware - x64
 - Programming language: C++, Python
 - Browser: N/A

**Additional context**
 - callstack, output and audio(contained in zip file) attached. 

[Callstack and Output.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/3016971/PCM_callstackOutput.txt)

[Sample PCM audio: signed 16bit, little-endian, mono, 16K Hz ](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/3016980/2019_03_28_16_07_41.zip)

**Comment by chlandsi** [comment]
The Speech SDK only understands PCM-encoded wave files, i.e. a [WAV header](http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/WAVE.html) needs to be present in the file. This doesn't seem to be the case for your sample audio file. Can you try adding a header to your data, or using a different file like [our sample](https://raw.githubusercontent.com/Azure-Samples/cognitive-services-speech-sdk/f9807b1079f3a85f07cbb6d762c6b5449d536027/samples/cpp/windows/console/samples/whatstheweatherlike.wav)? Thanks!

**Comment by wukun2015** [comment]
Got it, thanks. 

Suggest 1 is more clarification in doc [AudioConfig::FromWavFileInput() declaration](https://docs.microsoft.com/en-us/cpp/cognitive-services/speech/audio-audioconfig#fromwavfileinput). And suggest 2 is to support raw pcm directly :)

**Comment by chlandsi** [comment]
We'll clarify in the docs. If you are working with raw PCM audio, maybe the [PullAudioInputStream](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.audio.pullaudioinputstream?view=azure-python) and [PushAudioInputStream](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.audio.pushaudioinputstream?view=azure-python) are handy as well.
