### ISSUE TITLE
How to use TranslationRecognizer with AutoDetectSourceLanguageConfig for dynamic language recognition on mobile SDKs (Java and iOS)

### ISSUE THREAD

**Issue by jeasonxiexie** [Azure-Samples/cognitive-services-speech-sdk#1920]
Hello,

I'm having trouble using the TranslationRecognizer together with AutoDetectSourceLanguageConfig for dynamic language recognition in the mobile SDKs (Java and iOS). I found that in the JavaScript SDK, it is possible to set the mode for AutoDetectSourceLanguageConfig to LanguageIdMode.Continuous. However, I cannot find this mode setting in the mobile Java and iOS SDKs.

Could you please guide me on how to implement dynamic language recognition and transcription of speech in these SDKs? Your help would be greatly appreciated.

Thank you.

**Comment by rhurey** [comment]
Thanks for trying out the Speech SDK and interest in source language detection...

Unfortunately, as a preview feature Source Language Detection support hasn't yet made it to the Java and Objective-C versions of the Speech SDK for TranslationRecognizer scenarios.

**Comment by jeasonxiexie** [comment]
> Thanks for trying out the Speech SDK and interest in source language detection...
> 
> Unfortunately, as a preview feature Source Language Detection support hasn't yet made it to the Java and Objective-C versions of the Speech SDK for TranslationRecognizer scenarios.

Thank you for your response. Could you please provide an estimated timeline for when this feature will be added to the mobile SDKs? It would be very helpful for my project.

**Comment by pankopon** [comment]
Internal work item ref. 5256732.

**Comment by pankopon** [comment]
Closing this since a work item has been added to the backlog but there is no ETA. We will update here if more information becomes available. Please open a new issue if more support is needed.
