### ISSUE TITLE
China Android cognitiveservices.speech WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED

### ISSUE THREAD

**Issue by StephenDai** [Azure-Samples/cognitive-services-speech-sdk#1921]
Android App. SpeechTranslate. ConnectionFail using China network but works well with VPN. It happens a few days ago.

CANCELED: ErrorCode=ConnectionFailure
CANCELED: ErrorDetails=Connection failed (no connection to the remote host). Internal error: 1. Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED
wss://eastasia.s2s.speech.microsoft.com/speech/translation/cognitiveservices/v1?features=texttospeech&from=zh-CN&to=en-US&voice=Microsoft%20Server%20Speech%20Text%20to%20Speech%20Voice%20(en-US,%20ZiraRUS)
X-ConnectionId: f11743fb8f6f48adbc686cfed60ce606 SessionId: f11743fb8f6f48adbc686cfed60ce606
CANCELED: Did you update the subscription info?

It looks similar to issue #1911
Is it because any policy change in China? What can I do on App side?

**Comment by pankopon** [comment]
@StephenDai In case this is still a valid issue for you - please refer to the linked issues for suggested solutions, or if they are not applicable, please post a full Speech SDK log (see https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging).

**Comment by StephenDai** [comment]
@pankopon it's solved! Thanks a lot!
