### ISSUE TITLE
HelloWorld.cs will block the main thread in Unity

### ISSUE THREAD

**Issue by wxp0821** [Azure-Samples/cognitive-services-speech-sdk#1922]
**Describe the bug**
[cognitive-services-speech-sdk](https://github.com/Azure-Samples/cognitive-services-speech-sdk)/[quickstart](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart)/[csharp](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp)/[unity](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/unity)/[text-to-speech](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/unity/text-to-speech)/[Assets](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/unity/text-to-speech/Assets)/[Scripts](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/unity/text-to-speech/Assets/Scripts)/HelloWorld.cs

**To Reproduce**
1. ...
2. ...

**Expected behavior**

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - please be specific
 - Hardware - x64, x86, ARM, ...
 - Programming language: C#, C++, Java, JavaScript, Objective-C, Python
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific

**Additional context**
 - Error messages, stack trace, sample code to reproduce the issue, ...
 - Please provide full Speech SDK Log, as per the instructions [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging)?
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by pankopon** [comment]
Thanks for the feedback. If you refer to the implementation of `ButtonClick()` in that sample, it's just one possible example. You could also call the synthesizer like done in https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/2fd035aa67d18fa06941394b6d7c9a4a923ae72a/samples/csharp/unity/embedded-speech/Assets/Scripts/HelloWorld.cs#L320 which works at least on platforms where native playback is supported.

**Comment by pankopon** [comment]
Closing the item as answered. Please open a new issue if more support is needed.
