### ISSUE TITLE
需要哪些lib呢  提示一堆无法解析的外部符号

### ISSUE THREAD

**Issue by pww1971** [Azure-Samples/cognitive-services-speech-sdk#1925]
**Describe the bug**

**To Reproduce**
1. ...
2. ...

**Expected behavior**

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - please be specific
 - Hardware - x64, x86, ARM, ...
 - Programming language: C#, C++, Java, JavaScript, Objective-C, Python
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific

**Additional context**
 - Error messages, stack trace, sample code to reproduce the issue, ...
 - Please provide full Speech SDK Log, as per the instructions [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging)?
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by glecaros** [comment]
Hi @pww1971, can you please provide more details about the issue you are having?

**Comment by pww1971** [comment]
缺少这两个lib文件导致的一堆无法解析的外部符号

**Comment by pww1971** [comment]
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_error_get_message，函数 "void __cdecl __azac_handle_native_ex(unsigned __int64,bool)" (?__azac_handle_native_ex@@YAX_K_N@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_error_get_call_stack，函数 "void __cdecl __azac_handle_native_ex(unsigned __int64,bool)" (?__azac_handle_native_ex@@YAX_K_N@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_error_get_error_code，函数 "void __cdecl __azac_handle_native_ex(unsigned __int64,bool)" (?__azac_handle_native_ex@@YAX_K_N@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_error_release，函数 "void __cdecl __azac_handle_native_ex(unsigned __int64,bool)" (?__azac_handle_native_ex@@YAX_K_N@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_property_bag_is_valid，函数 "public: __cdecl Microsoft::CognitiveServices::Speech::PropertyCollection::~PropertyCollection(void)" (??1PropertyCollection@Speech@CognitiveServices@Microsoft@@QEAA@XZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_property_bag_set_string，函数 "public: void __cdecl Microsoft::CognitiveServices::Speech::SpeechConfig::SetSpeechRecognitionLanguage(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?SetSpeechRecognitionLanguage@SpeechConfig@Speech@CognitiveServices@Microsoft@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_property_bag_get_string，函数 "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl Microsoft::CognitiveServices::Speech::PropertyCollection::GetProperty(enum Microsoft::CognitiveServices::Speech::PropertyId,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?GetProperty@PropertyCollection@Speech@CognitiveServices@Microsoft@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4PropertyId@234@AEBV56@@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_property_bag_free_string，函数 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl Microsoft::CognitiveServices::Speech::Utils::CopyAndFreePropertyString(char const *)" (?CopyAndFreePropertyString@Utils@Speech@CognitiveServices@Microsoft@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBD@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_property_bag_release，函数 "public: virtual __cdecl Microsoft::CognitiveServices::Speech::Audio::AudioConfig::~AudioConfig(void)" (??1AudioConfig@Audio@Speech@CognitiveServices@Microsoft@@UEAA@XZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_speech_config_from_subscription，函数 "public: static class std::shared_ptr<class Microsoft::CognitiveServices::Speech::SpeechConfig> __cdecl Microsoft::CognitiveServices::Speech::SpeechConfig::FromSubscription(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?FromSubscription@SpeechConfig@Speech@CognitiveServices@Microsoft@@SA?AV?$shared_ptr@VSpeechConfig@Speech@CognitiveServices@Microsoft@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@6@0@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_speech_config_release，函数 "public: virtual __cdecl Microsoft::CognitiveServices::Speech::SpeechConfig::~SpeechConfig(void)" (??1SpeechConfig@Speech@CognitiveServices@Microsoft@@UEAA@XZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_speech_config_get_property_bag，函数 "protected: __cdecl Microsoft::CognitiveServices::Speech::SpeechConfig::SpeechConfig(struct _azac_empty *)" (??0SpeechConfig@Speech@CognitiveServices@Microsoft@@IEAA@PEAU_azac_empty@@@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_result_get_reason，函数 "private: void __cdecl Microsoft::CognitiveServices::Speech::RecognitionResult::PopulateResultFields(struct _azac_empty *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,enum Microsoft::CognitiveServices::Speech::ResultReason *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?PopulateResultFields@RecognitionResult@Speech@CognitiveServices@Microsoft@@AEAAXPEAU_azac_empty@@PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAW4ResultReason@234@1@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_result_get_reason_canceled，函数 "private: enum Microsoft::CognitiveServices::Speech::CancellationReason __cdecl Microsoft::CognitiveServices::Speech::CancellationDetails::GetCancellationReason(class Microsoft::CognitiveServices::Speech::RecognitionResult *)" (?GetCancellationReason@CancellationDetails@Speech@CognitiveServices@Microsoft@@AEAA?AW4CancellationReason@234@PEAVRecognitionResult@234@@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_result_get_canceled_error_code，函数 "private: enum Microsoft::CognitiveServices::Speech::CancellationErrorCode __cdecl Microsoft::CognitiveServices::Speech::CancellationDetails::GetCancellationErrorCode(class Microsoft::CognitiveServices::Speech::RecognitionResult *)" (?GetCancellationErrorCode@CancellationDetails@Speech@CognitiveServices@Microsoft@@AEAA?AW4CancellationErrorCode@234@PEAVRecognitionResult@234@@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_result_get_result_id，函数 "private: void __cdecl Microsoft::CognitiveServices::Speech::RecognitionResult::PopulateResultFields(struct _azac_empty *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,enum Microsoft::CognitiveServices::Speech::ResultReason *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?PopulateResultFields@RecognitionResult@Speech@CognitiveServices@Microsoft@@AEAAXPEAU_azac_empty@@PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAW4ResultReason@234@1@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_result_get_text，函数 "private: void __cdecl Microsoft::CognitiveServices::Speech::RecognitionResult::PopulateResultFields(struct _azac_empty *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,enum Microsoft::CognitiveServices::Speech::ResultReason *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?PopulateResultFields@RecognitionResult@Speech@CognitiveServices@Microsoft@@AEAAXPEAU_azac_empty@@PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAW4ResultReason@234@1@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_result_get_offset，函数 "private: void __cdecl Microsoft::CognitiveServices::Speech::RecognitionResult::PopulateResultFields(struct _azac_empty *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,enum Microsoft::CognitiveServices::Speech::ResultReason *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?PopulateResultFields@RecognitionResult@Speech@CognitiveServices@Microsoft@@AEAAXPEAU_azac_empty@@PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAW4ResultReason@234@1@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_result_get_duration，函数 "private: void __cdecl Microsoft::CognitiveServices::Speech::RecognitionResult::PopulateResultFields(struct _azac_empty *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,enum Microsoft::CognitiveServices::Speech::ResultReason *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?PopulateResultFields@RecognitionResult@Speech@CognitiveServices@Microsoft@@AEAAXPEAU_azac_empty@@PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAW4ResultReason@234@1@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_result_get_property_bag，函数 "public: __cdecl <lambda_7461ff4b221640c7eff5b6fcd211ae6a>::operator()(void)const " (??R<lambda_7461ff4b221640c7eff5b6fcd211ae6a>@@QEBA@XZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_audio_config_create_audio_input_from_default_microphone，函数 "public: static class std::shared_ptr<class Microsoft::CognitiveServices::Speech::Audio::AudioConfig> __cdecl Microsoft::CognitiveServices::Speech::Audio::AudioConfig::FromDefaultMicrophoneInput(void)" (?FromDefaultMicrophoneInput@AudioConfig@Audio@Speech@CognitiveServices@Microsoft@@SA?AV?$shared_ptr@VAudioConfig@Audio@Speech@CognitiveServices@Microsoft@@@std@@XZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_audio_config_release，函数 "public: void __cdecl Microsoft::CognitiveServices::Speech::SmartHandle<struct _azac_empty *,&unsigned __int64 __cdecl audio_config_release(struct _azac_empty *)>::reset(void)" (?reset@?$SmartHandle@PEAU_azac_empty@@$1?audio_config_release@@YA_KPEAU1@@Z@Speech@CognitiveServices@Microsoft@@QEAAXXZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_audio_config_get_property_bag，函数 "protected: __cdecl Microsoft::CognitiveServices::Speech::Audio::AudioConfig::AudioConfig(struct _azac_empty *)" (??0AudioConfig@Audio@Speech@CognitiveServices@Microsoft@@IEAA@PEAU_azac_empty@@@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_handle_release，函数 "protected: virtual void __cdecl Microsoft::CognitiveServices::Speech::Recognizer::TermRecognizer(void)" (?TermRecognizer@Recognizer@Speech@CognitiveServices@Microsoft@@MEAAXXZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_async_handle_is_valid，函数 "protected: virtual void __cdecl Microsoft::CognitiveServices::Speech::AsyncRecognizer<class Microsoft::CognitiveServices::Speech::SpeechRecognitionResult,class Microsoft::CognitiveServices::Speech::SpeechRecognitionEventArgs,class Microsoft::CognitiveServices::Speech::SpeechRecognitionCanceledEventArgs>::TermRecognizer(void)" (?TermRecognizer@?$AsyncRecognizer@VSpeechRecognitionResult@Speech@CognitiveServices@Microsoft@@VSpeechRecognitionEventArgs@234@VSpeechRecognitionCanceledEventArgs@234@@Speech@CognitiveServices@Microsoft@@MEAAXXZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_async_handle_release，函数 "public: void __cdecl <lambda_182944c0f63490d4e4034f67af3748db>::operator()(void)const " (??R<lambda_182944c0f63490d4e4034f67af3748db>@@QEBAXXZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_result_handle_release，函数 "public: virtual __cdecl Microsoft::CognitiveServices::Speech::RecognitionResult::~RecognitionResult(void)" (??1RecognitionResult@Speech@CognitiveServices@Microsoft@@UEAA@XZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_event_handle_release，函数 "public: virtual __cdecl Microsoft::CognitiveServices::Speech::SpeechRecognitionEventArgs::~SpeechRecognitionEventArgs(void)" (??1SpeechRecognitionEventArgs@Speech@CognitiveServices@Microsoft@@UEAA@XZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_get_property_bag，函数 "public: __cdecl <lambda_c5d40b5a495e8b4a8e5426d898102a5b>::operator()(void)const " (??R<lambda_c5d40b5a495e8b4a8e5426d898102a5b>@@QEBA@XZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_recognize_once，函数 "public: class std::shared_ptr<class Microsoft::CognitiveServices::Speech::SpeechRecognitionResult> __cdecl <lambda_8a53eb870237747dc60f0b34e0d17a5c>::operator()(void)const " (??R<lambda_8a53eb870237747dc60f0b34e0d17a5c>@@QEBA?AV?$shared_ptr@VSpeechRecognitionResult@Speech@CognitiveServices@Microsoft@@@std@@XZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_start_continuous_recognition_async，函数 "public: void __cdecl <lambda_182944c0f63490d4e4034f67af3748db>::operator()(void)const " (??R<lambda_182944c0f63490d4e4034f67af3748db>@@QEBAXXZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_start_continuous_recognition_async_wait_for，函数 "public: void __cdecl <lambda_182944c0f63490d4e4034f67af3748db>::operator()(void)const " (??R<lambda_182944c0f63490d4e4034f67af3748db>@@QEBAXXZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_stop_continuous_recognition_async，函数 "public: void __cdecl <lambda_8fef719be17c39b60bd435df5306417f>::operator()(void)const " (??R<lambda_8fef719be17c39b60bd435df5306417f>@@QEBAXXZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_stop_continuous_recognition_async_wait_for，函数 "public: void __cdecl <lambda_8fef719be17c39b60bd435df5306417f>::operator()(void)const " (??R<lambda_8fef719be17c39b60bd435df5306417f>@@QEBAXXZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_start_keyword_recognition_async，函数 "public: void __cdecl <lambda_5b68a05b4082e9889b3a4bfa99d17e57>::operator()(void)const " (??R<lambda_5b68a05b4082e9889b3a4bfa99d17e57>@@QEBAXXZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_start_keyword_recognition_async_wait_for，函数 "public: void __cdecl <lambda_5b68a05b4082e9889b3a4bfa99d17e57>::operator()(void)const " (??R<lambda_5b68a05b4082e9889b3a4bfa99d17e57>@@QEBAXXZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_stop_keyword_recognition_async，函数 "public: void __cdecl <lambda_5c733c1ff3199b46d9d2357fdacf7006>::operator()(void)const " (??R<lambda_5c733c1ff3199b46d9d2357fdacf7006>@@QEBAXXZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_stop_keyword_recognition_async_wait_for，函数 "public: void __cdecl <lambda_5c733c1ff3199b46d9d2357fdacf7006>::operator()(void)const " (??R<lambda_5c733c1ff3199b46d9d2357fdacf7006>@@QEBAXXZ) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_session_started_set_callback，函数 "protected: virtual void __cdecl Microsoft::CognitiveServices::Speech::AsyncRecognizer<class Microsoft::CognitiveServices::Speech::SpeechRecognitionResult,class Microsoft::CognitiveServices::Speech::SpeechRecognitionEventArgs,class Microsoft::CognitiveServices::Speech::SpeechRecognitionCanceledEventArgs>::SessionEventConnectionsChanged(class Microsoft::CognitiveServices::Speech::EventSignal<class Microsoft::CognitiveServices::Speech::SessionEventArgs const &> const &)" (?SessionEventConnectionsChanged@?$AsyncRecognizer@VSpeechRecognitionResult@Speech@CognitiveServices@Microsoft@@VSpeechRecognitionEventArgs@234@VSpeechRecognitionCanceledEventArgs@234@@Speech@CognitiveServices@Microsoft@@MEAAXAEBV?$EventSignal@AEBVSessionEventArgs@Speech@CognitiveServices@Microsoft@@@234@@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_session_stopped_set_callback，函数 "protected: virtual void __cdecl Microsoft::CognitiveServices::Speech::AsyncRecognizer<class Microsoft::CognitiveServices::Speech::SpeechRecognitionResult,class Microsoft::CognitiveServices::Speech::SpeechRecognitionEventArgs,class Microsoft::CognitiveServices::Speech::SpeechRecognitionCanceledEventArgs>::SessionEventConnectionsChanged(class Microsoft::CognitiveServices::Speech::EventSignal<class Microsoft::CognitiveServices::Speech::SessionEventArgs const &> const &)" (?SessionEventConnectionsChanged@?$AsyncRecognizer@VSpeechRecognitionResult@Speech@CognitiveServices@Microsoft@@VSpeechRecognitionEventArgs@234@VSpeechRecognitionCanceledEventArgs@234@@Speech@CognitiveServices@Microsoft@@MEAAXAEBV?$EventSignal@AEBVSessionEventArgs@Speech@CognitiveServices@Microsoft@@@234@@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_recognizing_set_callback，函数 "protected: virtual void __cdecl Microsoft::CognitiveServices::Speech::AsyncRecognizer<class Microsoft::CognitiveServices::Speech::SpeechRecognitionResult,class Microsoft::CognitiveServices::Speech::SpeechRecognitionEventArgs,class Microsoft::CognitiveServices::Speech::SpeechRecognitionCanceledEventArgs>::RecoEventConnectionsChanged(class Microsoft::CognitiveServices::Speech::EventSignal<class Microsoft::CognitiveServices::Speech::SpeechRecognitionEventArgs const &> const &)" (?RecoEventConnectionsChanged@?$AsyncRecognizer@VSpeechRecognitionResult@Speech@CognitiveServices@Microsoft@@VSpeechRecognitionEventArgs@234@VSpeechRecognitionCanceledEventArgs@234@@Speech@CognitiveServices@Microsoft@@MEAAXAEBV?$EventSignal@AEBVSpeechRecognitionEventArgs@Speech@CognitiveServices@Microsoft@@@234@@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_recognized_set_callback，函数 "protected: virtual void __cdecl Microsoft::CognitiveServices::Speech::AsyncRecognizer<class Microsoft::CognitiveServices::Speech::SpeechRecognitionResult,class Microsoft::CognitiveServices::Speech::SpeechRecognitionEventArgs,class Microsoft::CognitiveServices::Speech::SpeechRecognitionCanceledEventArgs>::RecoEventConnectionsChanged(class Microsoft::CognitiveServices::Speech::EventSignal<class Microsoft::CognitiveServices::Speech::SpeechRecognitionEventArgs const &> const &)" (?RecoEventConnectionsChanged@?$AsyncRecognizer@VSpeechRecognitionResult@Speech@CognitiveServices@Microsoft@@VSpeechRecognitionEventArgs@234@VSpeechRecognitionCanceledEventArgs@234@@Speech@CognitiveServices@Microsoft@@MEAAXAEBV?$EventSignal@AEBVSpeechRecognitionEventArgs@Speech@CognitiveServices@Microsoft@@@234@@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_canceled_set_callback，函数 "protected: virtual void __cdecl Microsoft::CognitiveServices::Speech::AsyncRecognizer<class Microsoft::CognitiveServices::Speech::SpeechRecognitionResult,class Microsoft::CognitiveServices::Speech::SpeechRecognitionEventArgs,class Microsoft::CognitiveServices::Speech::SpeechRecognitionCanceledEventArgs>::RecoCanceledEventConnectionsChanged(class Microsoft::CognitiveServices::Speech::EventSignal<class Microsoft::CognitiveServices::Speech::SpeechRecognitionCanceledEventArgs const &> const &)" (?RecoCanceledEventConnectionsChanged@?$AsyncRecognizer@VSpeechRecognitionResult@Speech@CognitiveServices@Microsoft@@VSpeechRecognitionEventArgs@234@VSpeechRecognitionCanceledEventArgs@234@@Speech@CognitiveServices@Microsoft@@MEAAXAEBV?$EventSignal@AEBVSpeechRecognitionCanceledEventArgs@Speech@CognitiveServices@Microsoft@@@234@@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_speech_start_detected_set_callback，函数 "protected: virtual void __cdecl Microsoft::CognitiveServices::Speech::AsyncRecognizer<class Microsoft::CognitiveServices::Speech::SpeechRecognitionResult,class Microsoft::CognitiveServices::Speech::SpeechRecognitionEventArgs,class Microsoft::CognitiveServices::Speech::SpeechRecognitionCanceledEventArgs>::RecognitionEventConnectionsChanged(class Microsoft::CognitiveServices::Speech::EventSignal<class Microsoft::CognitiveServices::Speech::RecognitionEventArgs const &> const &)" (?RecognitionEventConnectionsChanged@?$AsyncRecognizer@VSpeechRecognitionResult@Speech@CognitiveServices@Microsoft@@VSpeechRecognitionEventArgs@234@VSpeechRecognitionCanceledEventArgs@234@@Speech@CognitiveServices@Microsoft@@MEAAXAEBV?$EventSignal@AEBVRecognitionEventArgs@Speech@CognitiveServices@Microsoft@@@234@@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_speech_end_detected_set_callback，函数 "protected: virtual void __cdecl Microsoft::CognitiveServices::Speech::AsyncRecognizer<class Microsoft::CognitiveServices::Speech::SpeechRecognitionResult,class Microsoft::CognitiveServices::Speech::SpeechRecognitionEventArgs,class Microsoft::CognitiveServices::Speech::SpeechRecognitionCanceledEventArgs>::RecognitionEventConnectionsChanged(class Microsoft::CognitiveServices::Speech::EventSignal<class Microsoft::CognitiveServices::Speech::RecognitionEventArgs const &> const &)" (?RecognitionEventConnectionsChanged@?$AsyncRecognizer@VSpeechRecognitionResult@Speech@CognitiveServices@Microsoft@@VSpeechRecognitionEventArgs@234@VSpeechRecognitionCanceledEventArgs@234@@Speech@CognitiveServices@Microsoft@@MEAAXAEBV?$EventSignal@AEBVRecognitionEventArgs@Speech@CognitiveServices@Microsoft@@@234@@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_session_event_get_session_id，函数 "protected: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const __cdecl Microsoft::CognitiveServices::Speech::SessionEventArgs::GetSessionId(struct _azac_empty *)" (?GetSessionId@SessionEventArgs@Speech@CognitiveServices@Microsoft@@KA?BV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAU_azac_empty@@@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_recognition_event_get_offset，函数 "protected: static unsigned __int64 __cdecl Microsoft::CognitiveServices::Speech::RecognitionEventArgs::GetOffset(struct _azac_empty *)" (?GetOffset@RecognitionEventArgs@Speech@CognitiveServices@Microsoft@@KA_KPEAU_azac_empty@@@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_recognition_event_get_result，函数 "private: struct _azac_empty * __cdecl Microsoft::CognitiveServices::Speech::SpeechRecognitionEventArgs::ResultHandleFromEventHandle(struct _azac_empty *)" (?ResultHandleFromEventHandle@SpeechRecognitionEventArgs@Speech@CognitiveServices@Microsoft@@AEAAPEAU_azac_empty@@PEAU5@@Z) 中引用了该符号
1>test2.obj : error LNK2019: 无法解析的外部符号 __imp_recognizer_create_speech_recognizer_from_config，函数 "public: static class std::shared_ptr<class Microsoft::CognitiveServices::Speech::SpeechRecognizer> __cdecl Microsoft::CognitiveServices::Speech::SpeechRecognizer::FromConfig(class std::shared_ptr<class Microsoft::CognitiveServices::Speech::SpeechConfig>,class std::shared_ptr<class Microsoft::CognitiveServices::Speech::Audio::AudioConfig>)" (?FromConfig@SpeechRecognizer@Speech@CognitiveServices@Microsoft@@SA?AV?$shared_ptr@VSpeechRecognizer@Speech@CognitiveServices@Microsoft@@@std@@V?$shared_ptr@VSpeechConfig@Speech@CognitiveServices@Microsoft@@@6@V?$shared_ptr@VAudioConfig@Audio@Speech@CognitiveServices@Microsoft@@@6@@Z) 中引用了该符号

**Comment by brandom-msft** [comment]
Closing with no further info provided.
