### ISSUE TITLE
Why StopSpeakingAsync is asynchronously in Java (Android Platform)?

### ISSUE THREAD

**Issue by HaizhiH** [Azure-Samples/cognitive-services-speech-sdk#1927]
Hello guys, as the title said, I don't understand why the `StopSpeakingAsync()` method is asynchronously. 

When I try to convert a new text to speech, I need to stop previous one if playback is playing. My code below:
```
speechSynthesizer.StopSpeakingAsync().get()
speechSynthesizer.StartSpeakingTextAsync("foo") 
```

But it may cause the text "foo" won't convert to speech sometimes.

How should I solve this problem?

**Comment by BrianMouncer** [comment]
rather than just getting the StopSpeakingAsych task with get(), can you call Wait() on the StopSpeakingAsync task before calling the next StartSpeakingTextAsync(), otherwise there will be a race condition between stopping the previous spoken prompt, and adding the new prompt to the queue prompts to speak.

**Comment by HaizhiH** [comment]
@BrianMouncer  Thanks for reply. But the `get()` method is synchronously, the method will wait for `StopSpeakingAsync()` execute completed and get it's result(void), is the Wait() method means like `speechSynthesizer.StopSpeakingAsync().get().wait()` ?

I think the `SpeechSynthesizer` should provide a synchronously method (for example named 'StopSpeaking()') , It should stop playback right now, and do other things background(clear audio stream, notify server ... ).

sorry for bad english.

**Comment by yulin-li** [comment]
`StopSpeakingAsync().get()` should work as your expected. Notifying the underlying audio driver to stop playback takes time so we implement the asynchronous method.

**Comment by pankopon** [comment]
Closed as resolved since no further updates in 2 weeks, please open a new issue if more support is needed.
