### ISSUE TITLE
Centos 7 java.lang.UnsatisfiedLinkError with java speech sdk 

### ISSUE THREAD

**Issue by repoleved25** [Azure-Samples/cognitive-services-speech-sdk#1928]
Getting
`java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V
        at com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Native Method)
        at com.microsoft.cognitiveservices.speech.SpeechConfig.<clinit>(Unknown Source)
`
We are running jar which is build using maven and building docker image of it 

SDK version
` 
<dependency>
      <groupId>com.microsoft.cognitiveservices.speech</groupId>
      <artifactId>client-sdk</artifactId>
      <version>1.27.0</version>
  </dependency>
`

Using CentOS Linux release 7.6.1810 (Core) 
java lib path is /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib

nothing was there in /usr/local/lib64 so removed
# export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH
Tried explicitly loading the library as well, it didn't work

Tried 

`
sudo yum update
sudo yum groupinstall "Development tools"
sudo yum install alsa-lib openssl wget`
as well

am I missing something obvious here 

Guides referring 
https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7
https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/setup-platform?tabs=linux%2Crhel-centos%2Cdotnet%2Cjre%2Cmaven%2Cnodejs%2Cmac%2Cpypi&pivots=programming-language-java

**Comment by glecaros** [comment]
Hi @repoleved25, did you follow the instructions to update the C/C++ runtimes? ([link](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7#cc-compiler-and-runtime-libraries))

**Comment by repoleved25** [comment]
@glecaros 
yes tried that

getting this on explicit loading 

`System.loadLibrary("Microsoft.CognitiveServices.Speech.java.bindings");
`

`java.lang.UnsatisfiedLinkError: /opt/platform-tf-orch/centos7-x64/libMicrosoft.CognitiveServices.Speech.java.bindings.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21`

centos version is CentOS Linux release 7.9.2009 (Core)

can you confirm if 1.27.0 is compatible with centos 7
or to which version I need to downgrade

**Comment by pankopon** [comment]
@repoleved25 You wrote

> Using CentOS Linux release 7.6.1810 (Core)

and

> centos version is CentOS Linux release 7.9.2009 (Core)

so which one is it?

Where is your application run - a real Linux machine, a virtual Linux machine, or a docker container? What is the Linux version in that?

If it's CentOS 7, ensure that the output of following commands is exactly the same:
```
# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)

# cat /etc/ld.so.conf.d/local-x86_64.conf
/usr/local/lib64

# strings /usr/local/lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
...
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by repoleved25** [comment]
I was trying on multiple docker images(so running on docker container)
one had CentOS Linux release 7.6.1810 (Core)
other had CentOS Linux release 7.9.2009 (Core)

for me issue was in setting LD_LIBRARY_PATH, which was found out when loading the libraries explicitly
