### ISSUE TITLE
Microsoft.CognitiveServices.Speech can't spell

### ISSUE THREAD

**Issue by maivanchuong95** [Azure-Samples/cognitive-services-speech-sdk#1929]
Hi there,

Are there plans to fix the spelling issues with Microsoft Microsoft.CognitiveServices.Speech. I'd forgive using Australia English vs British English but it just plain can't spell. There is no English where the word "connection" is spelled "connexion" or where "check" is spelled "cheque" but these are just some of the examples of how terrible it is. I'm a writer and have been having some issues so was hoping to fix it. Will Microsoft be addressing these issues?

Thanks,

**Comment by trrwilson** [comment]
Hello! Thanks for reaching out.

Can you share a bit more about how you're using the Microsoft.CognitiveServices.Speech library (e.g. sample code or logs collected via the steps documented at https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging) when you get the undesirable spellings?

"Connexion" and "cheque" *are* valid spellings in UK English, as corroborated by sources like good ol' Merriam-Webster:

https://www.merriam-webster.com/dictionary/connexion
https://www.merriam-webster.com/dictionary/cheque

For that reason, if a recognizer is configured for en-GB or a similarly British-influenced orthographic system, these variant spellings may be expected and desirable. But if configured for another locale like en-US, this likely isn't intended.

**Comment by pankopon** [comment]
Closed since no further information received, please open a new issue if more support is needed.
