### ISSUE TITLE
JS SDK - IntentRecognizer.addIntent(string, string) Not Working

### ISSUE THREAD

**Issue by Code-Reaper** [Azure-Samples/cognitive-services-speech-sdk#1933]
I am trying to use the JavaScript SDK in a Node environment. The setup builds and the core speech-to-text service is functional and working.  The setup is simple (see below) and no matter how I try to phrase the spoken form of the intent it just will not fire and always shows up as text.

[Code]
```
private speechConfig: SpeechConfig = SpeechConfig.fromSubscription("some_key", "some_region")
recognizer: IntentRecognizer = new IntentRecognizer(this.speechConfig, AudioConfig.fromDefaultMicrophoneInput())
recognizer.addIntent('test intent', 'id_001')
recognizer.recognized = (_, _event) => {
    if (_event.result.reason === ResultReason.RecognizedSpeech) { this.onRecognizedSpeech(_event.result.text) }
    else if (_event.result.reason === ResultReason.RecognizedIntent) { this.onRecognizedGesture(_event.result.intentId) }
};
```

No matter what I do or how I try to call the intent it is never recognized. This is in a brand new up-to-date Node environment and as noted above the speech recognition part works flawlessly. It simply will not detect the intent. I had noted that all of the examples in the JS SDK use a LUIS model for intents, but the SDK docs show the function is there and I do not see any notes that it is deprecated or has an issue. The project is using TypeScript, but as a test I did try this same setup in plain old JavaScript and it didn't work there either.

Any guidance would be appreciated. 

Thank you.

**Comment by brandom-msft** [comment]
Hi @Code-Reaper, thanks for using the SDK and for your question.
At this time, intent recognition with pattern matching is not supported in JS/TS.

(Cross-referencing JS Issues hub for future lookups - https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/653)

**Comment by Code-Reaper** [comment]
Hello @brandom-msft. Thank you for that information. I also wanted to say thanks for linking that issue HUB. I hadn't seen any other repos/hubs so I posted here since this is where the Azure website sends you. I also don't see that it is unsupported anywhere. Since I didn't see the JS specific issue hub I was wondering if there was documentation that stated this that I missed? Anything you can provide would be appreciated.

**Comment by brandom-msft** [comment]
You didn't miss any documentation that _explicitly_ states the above, it's more of an implicit statement via omission. For example, in the [Intent Recognition documentation](https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-use-simple-language-pattern-matching?tabs=jre%2Cwindows%2Cubuntu%2Cmaven&pivots=programming-language-csharp) only Java, C#, and C++ are listed.

**Comment by Code-Reaper** [comment]
I appreciate that information. I must admit that is disappointing to here. I have been working on what is supposed to be a commercial project that requires the ability to use the intent system to fire of specific command style functionality with the voice. Since the docs didn't say it wasn't available for JS and the API docs do not have any notes about this in the [Intent Recognizer docs](https://learn.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/intentrecognizer?view=azure-node-latest#microsoft-cognitiveservices-speech-sdk-intentrecognizer-addintent) I thought it would be good to go.

Looking at the ticket you linked it doesn't show any updates or notes about when this type of functionality may be available. Is there any place I can go that may have more up-to-date information about when this will be available in the JS SDK?

Thank you.

**Comment by brandom-msft** [comment]
We don't publish timelines for feature releases, but we do give detailed release notes for each release. 

I've added your feedback to our backlog ticket to help with future prioritization.
