### ISSUE TITLE
Removing audio feedback loop from speech synthesis.

### ISSUE THREAD

**Issue by aaronn** [Azure-Samples/cognitive-services-speech-sdk#1935]
Does the Azure Speech SDK have any builtin way to remove speech synthesis from text-to-speech being fed back in and producing speech-to-text results in a use case where both are running at the same time?

**Comment by brandom-msft** [comment]
Hi @aaronn - thanks for using the SDK. 

Echo cancellation is supported using the Microsoft Audio Stack (MAS), you can [read more about it here](https://learn.microsoft.com/azure/cognitive-services/speech-service/audio-processing-overview) and on this [usage article](https://learn.microsoft.com/azure/cognitive-services/speech-service/audio-processing-speech-sdk?tabs=csharp).

**Comment by brandom-msft** [comment]
Closing as answered, please reach out again with any further issues.
