### ISSUE TITLE
Error when running the script

### ISSUE THREAD

**Issue by barne77** [Azure-Samples/cognitive-services-speech-sdk#1937]
Traceback (most recent call last):
  File "c:\Users\phbarnet\AzureFun\convert\call_center.py", line 421, in <module>
    run()
  File "c:\Users\phbarnet\AzureFun\convert\call_center.py", line 413, in run
    conversation_analysis_url = request_conversation_analysis(conversation_items, user_config)
  File "c:\Users\phbarnet\AzureFun\convert\call_center.py", line 254, in request_conversation_analysis
    response = rest_helper.send_post(uri=uri, content=content, key=user_config["language_subscription_key"], expected_status_codes=[HTTPStatus.ACCEPTED])
  File "c:\Users\phbarnet\AzureFun\convert\rest_helper.py", line 28, in send_post
    raise Exception(f"The POST request to {uri} returned a status code {response.status_code} that was not in the expected status codes: {expected_status_codes}")
Exception: The POST request to https://ukstestv2.cognitiveservices.azure.com/language/analyze-conversations/jobs?api-version=2022-10-01-preview returned a status code 400 that was not in the expected status codes: [<HTTPStatus.ACCEPTED: 202>]

I have checked and my Key and Endpoint is right

I also have approved the rights to use the services needed, and when testing on the speech studio using same file and sam 
language and speech service works fine

**Comment by barne77** [comment]
I have checked and my Key and Endpoint is right

**Comment by barne77** [comment]
This is the output i get from the conversation_items is 

{'displayName': 'call_center_2023-05-02 13:59:58.549466', 'analysisInput': {'conversations': [{'id': 'conversation1', 'language': 'en', 'modality': 'transcript', 'conversationItems': [{'id': 0, 'text': "Hello, you to the NHS11 service. My name is billing. I'm a health advisor. Can I ask if you're calling about yourself or somebody else?", 'itn': "hello you to the NHS11 service my name is billing i'm a health advisor can i ask if you're calling about yourself or somebody else", 'lexical': "hello you to the nhs one one service my name is billing i'm a health advisor can i ask if you're calling about yourself or somebody else", 'role': 'Agent', 'participantId': 0}, {'id': 1, 'text': "I've called about myself.", 'itn': "i've called about myself", 'lexical': "i've called about myself", 'role': 'Customer', 'participantId': 1}, {'id': 2, 'text': 'Calling about yourself. Thank you. Can I take some details? Can I take your contact number please?', 'itn': 'calling about yourself thank you can i take some details can i take your contact number please', 'lexical': 'calling about yourself thank you can i take some details can i take your contact number please', 'role': 'Agent', 'participantId': 0}, {'id': 3, 'text': 'Yes, 07123.', 'itn': 'yes 07123', 'lexical': 'yes oh seven one two three', 'role': 'Customer', 'participantId': 1}, {'id': 4, 'text': '07123.', 'itn': '07123', 'lexical': 'oh seven one two three', 'role': 'Agent', 'participantId': 0}, {'id': 5, 'text': '456.', 'itn': '456', 'lexical': 'four five six', 'role': 'Customer', 'participantId': 1}, {'id': 6, 'text': '456.', 'itn': '456', 'lexical': 'four five six', 'role': 'Agent', 'participantId': 0}, {'id': 7, 'text': '789.', 'itn': '789', 'lexical': 'seven eight nine', 'role': 'Customer', 'participantId': 1}, {'id': 8, 'text': '789 Can I take your surname please?', 'itn': '789 can i take your surname please', 'lexical': 'seven eight nine can i take your surname pleCan I ask, are you a passenger at all? Are you the are you the actual driver?', 'itn': 'on the M6 driving yeah can i ask are you a passenger at all are you the are you the actual driver', 'lexical': 'od': 'ConversationalSummarizationTask', 'parameters': {'modelVersion': '2022-05-15-preview', 'summaryAspects': ['Issue', 'Resolution']}}, {'taskName': 'PII_1', 'kind': 'ConversationalPIITask', 'parameters': {'piiCategories': ['All'], 'includeAudioRedaction': False, 'redactionSource': 'text', 'modelVersion': '2022-05-15-preview', 'loggingOptOut': False}}]}

**Comment by brandom-msft** [comment]
Hi @barne77 - can you share some information about your setup?

**To Reproduce**
Steps to reproduce the behavior:
1. ...
2. ...

**Expected behavior**
A clear and concise description of what you expected to happen.

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - please be specific
 - Hardware - x64, x86, ARM, ...
 - Programming language: C#, C++, Java, JavaScript, Objective-C, Python
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific

**Additional context**
 - Error messages, stack trace, sample code to reproduce the issue, ...
 - Please provide full Speech SDK Log, as per the instructions [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging)?

**Comment by barne77** [comment]
To Reproduce
Steps to reproduce the behaviour:

I have copied the latest code from - cognitive-services-speech-sdk-master\scenarios\python\console\call-center
Added to Visual Studio 

Run the call-center.py with the keys and endpoint details

Expected behavior
     Code to run and provide the simple and detailed output
     
 Version of the Cognitive Services Speech SDK
 Latest
 
 Platform, Operating System, and Programming Language
 Windows
 11
 Python

**Comment by barne77** [comment]
SENTIMENT_ANALYSIS_PATH = "/language/:analyze-text";
SENTIMENT_ANALYSIS_QUERY = "?api-version=2022-05-01";
CONVERSATION_ANALYSIS_PATH = "/language/analyze-conversations/jobs";
CONVERSATION_ANALYSIS_QUERY = "?api-version=2022-05-15-preview";
CONVERSATION_SUMMARY_MODEL_VERSION = "2022-05-15-preview";

**Comment by barne77** [comment]
Resolved changing the code to 

"tasks" : [

            {

                "taskName" : "summary_1",

                "kind" : "ConversationalSummarizationTask",

                "parameters" : {

                    "summaryAspects" : ["Issue"]

                }

            },

            {

                "taskName" : "summary_2",

                "kind" : "ConversationalSummarizationTask",

                "parameters" : {

                    "summaryAspects" : ["resolution"],

                    "sentenceCount" : 1

                }

            },

            {

                "taskName" : "PII_1",

                "kind" : "ConversationalPIITask",

                "parameters" : {

                    "piiCategories" : [

                        "All",

                    ],

                    "includeAudioRedaction" : False,

                    "redactionSource" : "text",

                    "modelVersion" : CONVERSATION_SUMMARY_MODEL_VERSION,

                    "loggingOptOut" : False

                }

            }

        ]

    }
