### ISSUE TITLE
java.lang.UnsatisfiedLinkError: 'void com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(java.lang.String)'

### ISSUE THREAD

**Issue by meliauk** [Azure-Samples/cognitive-services-speech-sdk#1939]
environment：CentOS Linux release 7.5.1804 (Core），jdk11，com.microsoft.cognitiveservices.speech-1.27.0（java）
Successfully run on window10，CentOS7 failed to run
errors：java.lang.UnsatisfiedLinkError: 'void.com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(java.lang.String)'
java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.cognitiveservices.speech.SpeechConfig

Reference has been made to “https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7” for environmental configuration

But There is no such file（ /etc/ld.so.conf.d/local-x86_64.conf）
Strings/usr/local/lib64/libstdc++. so. 6 | grep The execution of GLIBCXX is the same

![image](https://user-images.githubusercontent.com/38574147/236382263-b0e205bc-753a-4400-8caf-243e5fea4a49.png)
![image](https://user-images.githubusercontent.com/38574147/236382337-62eaa44a-3c71-4b31-9699-4c2ff02d8796.png)

**Comment by pankopon** [comment]
@meliauk Please upgrade to the latest CentOS 7 point release:
```
# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
```
Then follow the instructions to [Configure RHEL/CentOS 7](https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7). You need to build GCC 7.5.0 compiler and runtimes on CentOS 7.9.

Ref. https://learn.microsoft.com/azure/cognitive-services/speech-service/quickstarts/setup-platform?pivots=programming-language-java&tabs=linux :

> Use the most recent LTS release of the Linux distribution. For example, if you are using Ubuntu 20.04 LTS, use the latest release of Ubuntu 20.04.X.

**Comment by pankopon** [comment]
Closed as resolved since no further updates in 2 weeks, please open a new issue if more support is needed.

**Comment by chenjunhua8080** [comment]
@meliauk 解决了么哥

**Comment by meliauk** [comment]
没哩，卡着的状态，建议说是 升级linux系统
&nbsp;


王余凡
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月7日(星期一) 下午5:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Azure-Samples/cognitive-services-speech-sdk] java.lang.UnsatisfiedLinkError: &#39;void com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(java.lang.String)&#39; (Issue #1939)





 
@meliauk 解决了么哥

**Comment by chenjunhua8080** [comment]
可恶(〃＞皿＜)，最新版centos 7了也不行

**Comment by meliauk** [comment]
还有什么办法嘛？解决了告知我下哩&nbsp;


王余凡
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月7日(星期一) 晚上6:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Azure-Samples/cognitive-services-speech-sdk] java.lang.UnsatisfiedLinkError: &#39;void com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(java.lang.String)&#39; (Issue #1939)





 
可恶(〃＞皿＜)，最新版centos 7了也不行

**Comment by cikichen** [comment]
springboot+docker. centos7. java.lang.NoClassDefFoundError: com.microsoft.cognitiveservices.speech.SpeechConfig
