### ISSUE TITLE
speech_recognize_continuous_from_file , sample code from here, ValueError: read of closed file

### ISSUE THREAD

**Issue by km-azure-hku** [Azure-Samples/cognitive-services-speech-sdk#1940]
it works quite ok for a while, but experiencing error as below.
sometimes, The program can be run again after 4-5 times retries.

using Python 

RECOGNIZED: SpeechRecognitionEventArgs(session_id=17ec25efbf0d4832a9e9dbd87a9ae76e, result=SpeechRecognitionResult(result_id=441e73dea59f4945917559a9c22fadc7, text="  。", reason=ResultReason.RecognizedSpeech))
CANCELED SpeechRecognitionCanceledEventArgs(session_id=17ec25efbf0d4832a9e9dbd87a9ae76e, result=SpeechRecognitionResult(result_id=9842e5feecf144b398b0337cbb2677a0, text="", reason=ResultReason.Canceled))
CLOSING on SpeechRecognitionCanceledEventArgs(session_id=17ec25efbf0d4832a9e9dbd87a9ae76e, result=SpeechRecognitionResult(result_id=9842e5feecf144b398b0337cbb2677a0, text="", reason=ResultReason.Canceled))
SESSION STOPPED SessionEventArgs(session_id=17ec25efbf0d4832a9e9dbd87a9ae76e)
CLOSING on SessionEventArgs(session_id=17ec25efbf0d4832a9e9dbd87a9ae76e)
closing file
Exception in `read`: read of closed file
Exception ignored on calling ctypes callback function: <function PullAudioInputStream.__read_callback at 0x0000020B4EFBAB60>
Traceback (most recent call last):
  File "C:\Users\PycharmProjects\speechto-text\Lib\site-packages\azure\cognitiveservices\speech\audio.py", line 212, in __read_callback
    return obj.read(view)
           ^^^^^^^^^^^^^^
  File "C:\Users\\PycharmProjects\pythonProject1\main.py", line 1146, in read
    frames = self._file_h.read(size)
             ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: read of closed file

The code :

def speech_recognize_continuous_from_file(filename):
    """performs continuous speech recognition with input from an audio file"""
    # <SpeechContinuousRecognitionWithFile>

    with open(filename + '.json', 'w', encoding='utf-8') as outfile:
        outfile.write('{\n    "caption": [\n')
    outfile.close()

    with open(filename + '.txt', 'w', encoding='utf-8') as outfile:
        outfile.write('')
    outfile.close()

    class BinaryFileReaderCallback(speechsdk.audio.PullAudioInputStreamCallback):
        def __init__(self, filename: str):
            super().__init__()
            self._file_h = open(filename, "rb")

        def read(self, buffer: memoryview) -> int:
            try:
                size = buffer.nbytes
                frames = self._file_h.read(size)

                buffer[:len(frames)] = frames

                return len(frames)
            except Exception as ex:
                print('Exception in `read`: {}'.format(ex))
                raise

        def close(self) -> None:
            print('closing file')
            try:
                self._file_h.close()
            except Exception as ex:
                print('Exception in `close`: {}'.format(ex))
                raise
        # Creates an audio stream format. For an example we are using MP3 compressed file here

    compressed_format = speechsdk.audio.AudioStreamFormat(
        compressed_stream_format=speechsdk.AudioStreamContainerFormat.MP3)
    callback = BinaryFileReaderCallback(filename= filename + '.mp3')
    stream = speechsdk.audio.PullAudioInputStream(stream_format=compressed_format, pull_stream_callback=callback)

    auto_detect_source_language_config = \
        speechsdk.languageconfig.AutoDetectSourceLanguageConfig(languages=["zh-HK", "zh-CN", "en-US"])

    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)

    # Set continuous language detection (override the default of "AtStart")
    speech_config.set_property(property_id=speechsdk.PropertyId.SpeechServiceConnection_LanguageIdMode, value='Continuous')
    speech_config.output_format = speechsdk.OutputFormat.Detailed
    audio_config = speechsdk.audio.AudioConfig(stream=stream)

    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config,
                                                   auto_detect_source_language_config=auto_detect_source_language_config,
                                                   audio_config=audio_config)

    done = False

    def stop_cb(evt: speechsdk.SessionEventArgs):
        """callback that signals to stop continuous recognition upon receiving an event `evt`"""
        print('CLOSING on {}'.format(evt))
        nonlocal done
        done = True
        stream.close()

    def handle_result(evt: speechsdk.SpeechRecognitionEventArgs):
        import json

        results = json.loads(evt.result.json)
        print('===', filename, ' JSON ', evt.result.json)
        # print('&&&JSON ',results)
        print("**** ", results["DisplayText"])

        with open(filename + '.json', 'a', encoding='utf-8') as outfile:
            json.dump(results, outfile, sort_keys=True, indent=4, ensure_ascii=False)
            outfile.write('\n,\n')
            outfile.close()
        with open(filename + '.txt', 'a', encoding='utf-8') as outfile1:
            outfile1.write(results["DisplayText"])
            outfile1.close()

    speech_recognizer.recognized.connect(handle_result)
    # Connect callbacks to the events fired by the speech recognizer
    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
    speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))
    # stop continuous recognition on either session stopped or canceled events
    speech_recognizer.session_stopped.connect(stop_cb)
    speech_recognizer.canceled.connect(stop_cb)

    # Start continuous speech recognition
    speech_recognizer.start_continuous_recognition()
    while not done:
        time.sleep(.5)

    speech_recognizer.stop_continuous_recognition()
    # </SpeechContinuousRecognitionWithFile>

**Comment by km-azure-hku** [comment]
checked that there was a  quota issue.

[115874]: 1444ms SPX_TRACE_ERROR:  usp_reco_engine_adapter.cpp:1946 CSpxUspRecoEngineAdapter::OnError: site->Error() ... error='Connection was closed by the remote host. Error code: 1007. Error details: Quota exceeded. Cid: '

i am using S0 tier

**Comment by brandom-msft** [comment]
Hi @km-azure-hku - you can read more about the quotas for S0 here. https://learn.microsoft.com/azure/cognitive-services/speech-service/speech-services-quotas-and-limits

If you are experiencing a different behavior than expected from the above, please reach out and share any relevant details.

**Comment by pankopon** [comment]
Closed as resolved since no further updates in 2 weeks, please open a new issue if more support is needed.
