### ISSUE TITLE
Text to speech function, does it support iPhone mobile browser?

### ISSUE THREAD

**Issue by wusan** [Azure-Samples/cognitive-services-speech-sdk#1941]
I created a web version of the 'question list' to ask customers and have them answer questions,
It is normal to use the Google browser on Mac. But when I deploy the code to an HTTPS environment and perform a "Q&A" operation on an iPhone, only the first question is played by AI, and the second question is not played by voice. However, I can still answer the question. The text to speech function failed and cannot be played through the microphone.
I would like to know if the text-to-speech feature supports Google and Safari browsers on iPhone phones

**Comment by brandom-msft** [comment]
Hi @wusan - Is your scenario only for browsers? If so, I'd suggest taking a look at the [browser quickstarts](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/javascript/browser) and [browser samples](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/browser) for some good examples of running in a browser.

**Comment by wusan** [comment]
@

> Hi @wusan - Is your scenario only for browsers? If so, I'd suggest taking a look at the [browser quickstarts](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/javascript/browser) and [browser samples](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/browser) for some good examples of running in a browser.

It is normal to use Google Chrome on Mac and Windows systems, but there is a problem using the browser on iPhone 8/14 on the phone. The first question is normal voice, but after answering the question, there is no voice playback for the second question, but the user can answer the question (I have set the text display to allow the user to browse the current question content).
thanks

**Comment by yulin-li** [comment]
Safari has a special limitation that it requires a user inter action (e.g., pressing a button) before every audio playback. If there is no user input between fisrt and remaining anwser, Safari blocks the playback.

**Comment by pankopon** [comment]
Closed as answered since no further updates in 2 weeks, please open a new issue if more support is needed.
