### ISSUE TITLE
AttributeError: module 'swagger_client' has no attribute 'CustomSpeechTranscriptionsApi'

### ISSUE THREAD

**Issue by indrajithekanayake** [Azure-Samples/cognitive-services-speech-sdk#1943]
I'm using Microsoft's official GitHub repository to set up [Azure Speech Services Batch Transcription API from Python][1]

I receive an error from line number 142 in main.py which states

    AttributeError: module 'swagger_client' has no attribute 'CustomSpeechTranscriptionsApi'

I  suppose this has to do with the recent changes made to the swagger_client. How to fix this issue any thoughts?

I already followed the below threads and noticed a few others also reported the same issue but nothing helped,<br>
[Thread 1][2], [Thread 2][3]

To debug I gave `print(dir(swagger_client))` before it throws above error and here is the output

    ['ApiClient', 'ApiSpeechtotextV30DatasetsLocalesGet200ApplicationJsonResponse', 'ApiSpeechtotextV30EndpointsLocalesGet200ApplicationJsonResponse', 'ApiSpeechtotextV30EvaluationsLocalesGet200ApplicationJsonResponse', 'ApiSpeechtotextV30ModelsLocalesGet200ApplicationJsonResponse', 'ApiSpeechtotextV30ProjectsLocalesGet200ApplicationJsonResponse', 'ApiSpeechtotextV30TranscriptionsLocalesGet200ApplicationJsonResponse', 'Component', 'Configuration', 'Dataset', 'DatasetProperties', 'DatasetUpdate', 'DefaultApi', 'Endpoint', 'EndpointLinks', 'EndpointProperties', 'EndpointPropertiesUpdate', 'EndpointUpdate', 'EntityError', 'EntityReference', 'Error', 'ErrorContent', 'ErrorDetail', 'Evaluation', 'EvaluationProperties', 'EvaluationUpdate', 'File', 'FileLinks', 'FileProperties', 'HealthStatus', 'InnerError', 'InnerErrorV2', 'InternalModel', 'Links', 'ManagementModel', 'ManagementModelArray', 'ManagementModelProperties', 'Model', 'ModelCopy', 'ModelDeprecationDates', 'ModelFile', 'ModelLinks', 'ModelManifest', 'ModelProperties', 'ModelUpdate', 'PaginatedDatasets', 'PaginatedEndpoints', 'PaginatedEvaluations', 'PaginatedFiles', 'PaginatedModels', 'PaginatedProjects', 'PaginatedTranscriptions', 'PaginatedWebHooks', 'Project', 'ProjectLinks', 'ProjectProperties', 'ProjectUpdate', 'Transcription', 'TranscriptionProperties', 'TranscriptionUpdate', 'WebHook', 'WebHookEvents', 'WebHookEvents1', 'WebHookLinks', 'WebHookProperties', 'WebHookPropertiesUpdate', 'WebHookUpdate', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'api', 'api_client', 'configuration', 'models', 'rest']

  [1]: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python
  [2]: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/477
  [3]: https://github.com/MicrosoftDocs/azure-docs/issues/50995

**Comment by zhouwangzw** [comment]
I have just tried to run the python samples, following the steps described [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python), in particular, I am using the swagger definition file 
             "Enter the Swagger URL for the Speech Services API: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/cognitiveservices/data-plane/Speech/SpeechToText/stable/v3.1/speechtotext.json.". 

I am using python 3.10 in Anaconda. 
I am able to run the samples without any issues. 

![image](https://user-images.githubusercontent.com/19703521/236660411-23f25c77-4d19-4c15-9988-8843a60f88aa.png)

Please use API 3.1 which is the currently supported version. and API 2.0 is being deprecated.
Please check your environments, better to remove any other "swagger_client" modules if they have been installed in the past.
You can also go the folder where the "swagger_client" module is installed and there should be an __init_.py which contains the line like below
   from swagger_client.api.custom_speech_transcriptions_api import CustomSpeechTranscriptionsApi

**Comment by pankopon** [comment]
Closed as resolved since no further updates in 2 weeks, please open a new issue if more support is needed.

**Comment by kwongtn** [comment]
As of v3.1, afaik the following APIs are being replaced:
```py
transcription_api = cris_client.CustomSpeechTranscriptionsApi(
    api_client=client
)
webhook_api = cris_client.CustomSpeechWebHooksApi(api_client=client)
```

You'll need to replace with the following (yes these 2 unified into 1 endpoint)
```py
default_api = cris_client.DefaultApi(api_client=client)
```
