### ISSUE TITLE
Unity how to avoid keywordrecognizer auto SessionStopped after recognized

### ISSUE THREAD

**Issue by JackLiangTW** [Azure-Samples/cognitive-services-speech-sdk#1946]
I am using this to test.
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/csharp/unity/keywordrecognizer

 I'm experiencing a problem where there is only a short interval to continue speaking after the keyword is detected.
My ideal situation is that user ask:
HeyBot, (Wait about 0.5s ~ 1s let UI shows it's allow to ask)   How to buy items in this game?

But the "recognizer.Recognized" oftens return:
"HeyBot, 。"

The empty space allowed after keyword detected is too short.
Is there has any parameter to set to increase empty detection time or other solutions?

**Comment by jhakulin** [comment]
@JackLiangTW Possible solution on how you can control when to start speech recognition in your scenario, is to use standalone KeywordRecognizer, see https://learn.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.keywordrecognizer?view=azure-dotnet to make keyword detection and once detected, start speech recognition with SpeechRecognizer when UI is ready for that.

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
