### ISSUE TITLE
JS: How to lower the silent delay in TTS?

### ISSUE THREAD

**Issue by Naozumi520** [Azure-Samples/cognitive-services-speech-sdk#1949]
As title, every Text-to-speech audio have about 2 second of silent at the end. How can I lower the value or remove completely?

**Comment by glharper** [comment]
@yulin-li Could you answer this question?

**Comment by yulin-li** [comment]
Hi @Naozumi520 could you please use `mstts:silence` tag with type of `Tailing-exact` to specify the tailing silence of the synthesized audio?

Refer to [this doc](https://learn.microsoft.com/azure/cognitive-services/speech-service/speech-synthesis-markup-structure#add-silence)

**Comment by Naozumi520** [comment]
Yes, it's working! Thanks!
