### ISSUE TITLE
Phrase cannot be recognized if no silence before end

### ISSUE THREAD

**Issue by wukun2015** [Azure-Samples/cognitive-services-speech-sdk#195]
**Describe the bug**
Phrase cannot be recognized if no silence followed before end of audio file

**To Reproduce**
1. Feed sdk with wav file via AudioConfig::FromWavFileInput [recognition sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/cpp/windows/console/samples/speech_recognition_samples.cpp)

2. Lack of silence b/w audio and the end results in service's "NOMATCH: Speech could not be recognized." message and missing of last phrase transcription, though content is already recognized (almost) correctly as intermediate result. 

3. Add silence in audio will get full transcription as expected.

**Expected behavior**
Audio full content shall be transcribed no matter silence followed before end of audio.  

**Version of the Cognitive Services Speech SDK**
1.3.1

**Platform, Operating System, and Programming Language**
 - OS: Windows 10 Enterprise
 - Hardware - x64
 - Programming language: C++, Python
 - Browser: NA

**Additional context**
[zh_cn_dictation_transcription.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/3020900/zh_cn_dictation_transcription.txt)

[zh_cn_dictatoin_audio.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/3020902/zh_cn_dictatoin_audio.zip)

**Comment by wolfma61** [comment]
this is not an SDK issue, it is a speech service issue
unfortunately nothing we can do from the sdk side, we are passing the audio to the service and are receiving the NOMATCH, not a final result,

the issue has been reported to the speech service team. they are investigating and will provide a fix.
