### ISSUE TITLE
[Azure speech to text real-time] Disfluency removal

### ISSUE THREAD

**Issue by maivanchuong95** [Azure-Samples/cognitive-services-speech-sdk#1950]
Currently I want to use the Disfluency removal function for Speech To Text real-time but I don't see any official documentation on how to configure it. So is this functionality released yet? Is it available for .NET use?
Thanks.

**Comment by pankopon** [comment]
Hi, this feature should be enabled by default, and non-configurable. Do you see it not working in some conditions? Ref. https://learn.microsoft.com/azure/cognitive-services/speech-service/display-text-format?pivots=programming-language-csharp#disfluency-removal for the expected behavior.

**Comment by maivanchuong95** [comment]
> Hi, this feature should be enabled by default, and non-configurable. Do you see it not working in some conditions? Ref. https://learn.microsoft.com/azure/cognitive-services/speech-service/display-text-format?pivots=programming-language-csharp#disfluency-removal for the expected behavior.

I have this enabled but the real-time speech-to-text from the microphone on .NET still doesn't remove all the non-fluent words, it still has words like "uh, umm, etc". It still doesn't work as I expected. Is there anything else I need to do?

**Comment by pankopon** [comment]
@maivanchuong95 It seems this feature may need to be explicitly enabled after all - please apply the following setting before creating a recognizer
```
speechConfig.SetProperty(PropertyId.SpeechServiceResponse_PostProcessingOption, "TrueText");
```
(where `speechConfig` is a `SpeechConfig` object)

This property is described in https://learn.microsoft.com/dotnet/api/microsoft.cognitiveservices.speech.propertyid?view=azure-dotnet.

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.

**Comment by ahotrod** [comment]
Is there a method to disable Disfluency Removal via the Python _swagger_client properties_ for any of the Azure AI Speech STT models for .mp4 batch or blob transcription?  My use case includes analyzing presentations for filler words (um, uh, er, hmm, etc.) which requires a verbatim transcript from Azure AI Speech.
