### ISSUE TITLE
WS_OPEN_ERROR_UNDERLYING_IO_ERROR error when testing speech to text sample code

### ISSUE THREAD

**Issue by altazar0456** [Azure-Samples/cognitive-services-speech-sdk#1955]
**Describe the bug**
Can't use [Quickstart C# .NET for Windows](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/dotnet/from-microphone), receive WS_OPEN_ERROR_UNDERLYING_IO_ERROR error

`CANCELED: Reason=Error
CANCELED: ErrorCode=ConnectionFailure
CANCELED: ErrorDetails=Connection failed (no connection to the remote host). Internal error: 11. Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_ERROR
wss://eastus.stt.speech.microsoft.com/speech/recognition/interactive/cognitiveservices/v1?language=en-US
X-ConnectionId: c9bf458e020644b0b4f831a09fdf77cd SessionId: c9bf458e020644b0b4f831a09fdf77cd
CANCELED: Did you set the speech resource key and region values?`

**To Reproduce**
1. [Download the sample code to your development PC.](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/README.md#get-the-samples)
2. Start Microsoft Visual Studio 2022 with \quickstart\csharp\dotnet\from-microphone\helloworld.sln project
3. Change "YourSubscriptionKey" and "YourServiceRegion" to correct ones
4.  Run application and receive error

**Expected behavior**
It's expected to run without errors and to recognize text from my speech

**Version of the Cognitive Services Speech SDK**
the latest one (1.28.0 from Nuget package)

**Platform, Operating System, and Programming Language**
 - OS: Windows 11 with all updates
 - Hardware - x64
 - Programming language: C#, Also tested on Python

**Additional context**
 - Error message with ConnectionFailure 
 `CANCELED: Reason=Error
CANCELED: ErrorCode=ConnectionFailure
CANCELED: ErrorDetails=Connection failed (no connection to the remote host). Internal error: 11. Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_ERROR
wss://eastus.stt.speech.microsoft.com/speech/recognition/interactive/cognitiveservices/v1?language=en-US
X-ConnectionId: c9bf458e020644b0b4f831a09fdf77cd SessionId: c9bf458e020644b0b4f831a09fdf77cd
CANCELED: Did you set the speech resource key and region values?`
 - full Speech SDK Log 
[recordLog1.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/11544227/recordLog1.txt)
 - I tried it during several days, no success
 - These [steps](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/troubleshooting?WT.mc_id=Portal-Microsoft_Azure_Support&tabs=powershell#error-http-408-request-timeout) works correctly
 - Steps from [this ](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1923)didn't help me

**Comment by jhakulin** [comment]
@altazar0456 Thanks for the report. Could you please confirm, are you still seeing the connection issue?

**Comment by yangnoahlin** [comment]
I am encountering the same issue on both Raspberry Pi 3 and Pi 4. The code, which usually runs without any problems, suddenly started showing this error.

**Comment by dargilco** [comment]
Hi @altazar0456 this is Darren from the Speech SDK team. Just to confirm, you tried to edit the reg key HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\CProPatches\SCHANNEL as mentioned [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1923), and this did not solve the problem? Even after reboot? For testing purposes, can you uninstall Crypto-Pro, reboot, and re-run the Speech SDK sample? This is the first time I've learned about Crypto-Pro. Or is there another way you can think of to show that the Speech SDK error is a result of Crypto-Pro running?

**Comment by altazar0456** [comment]
Hi @dargilco , thanks for helping here.

> Just to confirm, you tried to edit the reg key HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\CProPatches\SCHANNEL as mentioned https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1923, and this did not solve the problem? Even after reboot?

I tried to edit it and even delete it
<img width="696" alt="image" src="https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/21237223/ec1ed153-419e-49b5-a51c-e15f2fa570f6">

>  For testing purposes, can you uninstall Crypto-Pro, reboot, and re-run the Speech SDK sample?

I will try to uninstall Crypto-Pro and reboot. 

> is there another way you can think of to show that the Speech SDK error is a result of Crypto-Pro running?
I don't have any reasons that it's result of Crypto-Pro running except of mentioned link.

**Comment by altazar0456** [comment]
After uninstalling Crypto-Pro application and rebooting I'm able to run Speech SDK sample

**Comment by pankopon** [comment]
Closed as resolved, please open a new issue if more support is needed.
