### ISSUE TITLE
Javascript example (Browser) of Language Identification

### ISSUE THREAD

**Issue by fantinuoli** [Azure-Samples/cognitive-services-speech-sdk#1957]
Can you provide a minimalistic working example of language detection (continuous) for Javascript? Especially the configuration: calling 

Calling SDK as this:
````
<script src="https://cdn.jsdelivr.net/npm/microsoft-cognitiveservices-speech-sdk@latest/distrib/browser/microsoft.cognitiveservices.speech.sdk.bundle-min.js"></script>
````
This is what we have sofar in JS. 

````
subscriptionKey = "xxxx";
speechConfig = SpeechSDK.SpeechTranslationConfig.fromSubscription(
      subscriptionKey,
      "eastus"
);

let audioConfig = SpeechSDK.AudioConfig.fromDefaultMicrophoneInput();
recognizer = new SpeechSDK.SpeechRecognizer(speechConfig, audioConfig);

var autoDetectSourceLanguageConfig =
    SpeechSDK.AutoDetectSourceLanguageConfig.fromLanguages([
      "en-US",
      "fr-FR",
      "de-DE",
      "es-ES",
]);

var speechRecognizer = SpeechSDK.SpeechRecognizer.FromConfig(
    speechConfig,
    autoDetectSourceLanguageConfig,
    audioConfig
 );

speechRecognizer.startContinuousRecognitionAsync();
````
It obviously misses the end point "wss://{region}.stt.speech.microsoft.com/speech/universal/v2" and the property "SpeechServiceConnection_LanguageIdMode". However no clear indication are given on how to set them.

**Comment by pankopon** [comment]
@glharper Please check.

**Comment by glharper** [comment]
@fantinuoli Thank you for using JS Speech SDK, and writing this issue up. For a usage example, see [this (currently disabled) test ](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/04a442d9d79cd5b177547f16e130d5c147a91732/tests/AutoSourceLangDetectionTests.ts#L538) in the JS repo. 
The main idea is to set the mode property on the AutoDetectSourceLanguageConfig object to LanguageIdMode.Continuous.

The SDK will automatically set the service endpoint to universal/v2 if that property is set to LanguageIdMode.Continuous.

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.

**Comment by glharper** [comment]
@amin45666 Could you check the actual JSON of the recognizing result and see if languageDetectionConfidence is being returned from the service? If it is being returned, but we're not exposing it correctly in the SpeechRecognitionResult, that's a bug in JS SDK.

If it's not being returned, I'll ask services to investigate.

**Comment by amin45666** [comment]
It is not being returned in recognizing, it is undefined and due to this reason it does not work in recognizing due to anguageDetectionConfidence is null/undefined

<img width="372" alt="Screenshot 2023-06-05 at 4 57 13 PM" src="https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/99399754/74bf7057-5c35-46c9-b7be-1957cb78be40">

**Comment by glharper** [comment]
@ut-karsh Would you care to comment on why no confidence value is returned by the service for intermediate recognition results?

**Comment by amin45666** [comment]
@glharper @ut-karsh Any update on this? Was working on it for the past week but couldn't find any solution for intermediate recognition other than to wait for the whole sentence to complete and get in final recognition. 
Thankyou

**Comment by glharper** [comment]
@amin45666 I've reached out to the service team to update this issue, but it does not appear the JS SDK has any support for confidence values for intermediate results in continuous language id scenarios. Any future support would depend on service side updates, which the SDK team has limited visibility into. Closing this issue.
