### ISSUE TITLE
java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V

### ISSUE THREAD

**Issue by jianbo945** [Azure-Samples/cognitive-services-speech-sdk#1958]
I'm using client-sdk-1.28.0.jar in my project,but it doesn't effect on Centos7. I have set the environment variable according to this link "https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7".
When I use TTS, it shows the following info:
java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V

Version of the Cognitive Services Speech SDK
client-sdk-1.28.0.jar
client-sdk-1.27.0.jar

Platform, Operating System, and Programming Language

OS: Linux Centos7
Hardware: x64
Programming language: Java
Browser: Chrome
Or Is there anything wrong with my setting on Centos7?

and i try my program in another machine,it can works,all the same enviorment

it is not the enviorment problem,and i search for many questions ,all of them has the problem,but no one can fix the problem

**Comment by pankopon** [comment]
Please see
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1939
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1769

**Comment by pankopon** [comment]
Closed as duplicate. Please open a new issue if more support is needed.

**Comment by jianbo945** [comment]
i have see those question ,but it doesn't work,and for my machine, it doesn't have any settings,but it can works,for the same enviorment,one can works ,another doesn't work

**Comment by jianbo945** [comment]
for the enviorment ,after export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH,it can be work,but it maybe not the reason for the gcc version ,it can be used when the gcc version is 4.8.5 ,and in another enviorment the LD_LIBRARY_PATH has nothing ,but it can also works

**Comment by tomscheney** [comment]
I have same problem
