### ISSUE TITLE
WAV file recognition in stream mode met runtime exception

### ISSUE THREAD

**Issue by wukun2015** [Azure-Samples/cognitive-services-speech-sdk#196]
**Describe the bug**
WAV file recognition in stream mode met exception

**To Reproduce**
1. Transform mono 16bit/16khz pcm to wav by adding wav header, as attached;
2. Feed wav into AudioInputFromFileCallback in [
        cognitive-services-speech-sdk/samples/cpp/windows/console/samples/speech_recognition_samples.cpp
      ](url)
3. Run the sample
4. Runtime exception is thrown.

**Expected behavior**
wav shall be transcribed without exception in stream mode.

**Version of the Cognitive Services Speech SDK**
1.3.1

**Platform, Operating System, and Programming Language**
 - OS: Window 10 enterprise
 - Hardware - x64
 - Programming language: C++
 - Browser: NA

**Additional context**
[stream_output_callstack.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/3021384/stream_output_callstack.txt)
[sample audio](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/3021385/zh_cn_dictation_le_sign16bit_16khz_mono_audio.zip)

**Comment by chlandsi** [comment]
The error originates in the code that reads the wav file for the stream used in the sample, [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/fde5304e050f3e71c83a4e0d66dea168469ce9fe/samples/cpp/windows/console/samples/wav_file_reader.h#L96). This simple wav file reader cannot handle this specific header. This could be solved either by re-encoding the file (after opening and saving the file in Audacity, it works), using the SDK's API to read wav files (which handles the file without problems) or using a more fully functional wav file reader for stream input.

**Comment by wukun2015** [comment]
i confirm re-encoding pcm works but it‘ll impact the originality of pcm content, compared w/ simply add a clean header.

**Comment by chlandsi** [comment]
In that case, it's probably easiest to not add a header at all, but just pass the raw PCM data into the Push/Pull audio stream (not loading the data file as a wave file, as in the sample, but rather as raw data). The streams expect no header to be present at the beginning of the data, so raw PCM can be passed in without any preprocessing.

**Comment by wolfma61** [comment]
closing
