### ISSUE TITLE
ITN feature not working with Number recognition - Java Speech SDK

### ISSUE THREAD

**Issue by jeromelarman** [Azure-Samples/cognitive-services-speech-sdk#1962]
I use recognizer.startContinuousRecognitionAsync().get(); from java speech sdk and i can not be able to works with ITN.

Below an example of the processed speech.

For example, I want that neuf will be processed as 9. French language.

Following the documentation i activate Detailed Output, I can see the ITN property but it contains not processed data.

time=2023-05-26T19:46:26.624+0200|level=INFO |env=d2|event_cod=|event_typ=|app_id=ress-scog|app_version=develop.2451334|component_id=fr.SpeechServiceImpl|thread_id=Thread-8640|req_id=|uom_cod=|corr_id=|usr_id=|message=result property {"Id":"f962c3fbf9d3472c8a770793eeb55a2d","RecognitionStatus":"Success","Offset":14000000,"Duration":28800000,"DisplayText":"Acheter Z?ro Neuf Vingt et UN.","NBest":[{"Confidence":0.7337445,"Lexical":"acheter z?ro neuf vingt et un","ITN":"acheter z?ro neuf vingt et un","MaskedITN":"acheter z?ro neuf vingt et un","Display":"Acheter Z?ro Neuf Vingt et UN.","Words":[{"Word":"acheter","Offset":14000000,"Duration":9600000,"Confidence":0.5867987},{"Word":"z?ro","Offset":26700000,"Duration":2700000,"Confidence":0.5847685},{"Word":"neuf","Offset":29500000,"Duration":6100000,"Confidence":0.879264},{"Word":"vingt","Offset":36600000,"Duration":4000000,"Confidence":0.8646985},{"Word":"et","Offset":40700000,"Duration":1100000,"Confidence":0.9175117},{"Word":"un","Offset":41900000,"Duration":900000,"Confidence":0.9165993}]},{"Confidence":0.6940139,"Lexical":"acheter z?ro neuf vingt-et-un","ITN":"acheter z?ro **neuf** vingt-et-un","MaskedITN":"acheter z?ro neuf vingt-et-un","Display":"acheter z?ro **neuf** vingt-et-un","Words":[{"Word":"acheter","Offset":14000000,"Duration":9600000,"Confidence":0.5867987},{"Word":"z?ro","Offset":26700000,"Duration":2700000,"Confidence":0.5847685},{"Word":"neuf","Offset":29500000,"Duration":6100000,"Confidence":0.879264},{"Word":"vingt-et-un","Offset":36600000,"Duration":6200000,"Confidence":0.725335}]},{"Confidence":0.7571742,"Lexical":"acheter ? z?ro neuf vingt et un","ITN":"acheter ? z?ro neuf vingt et un","MaskedITN":"acheter ? z?ro neuf vingt et un","Display":"acheter ? z?ro neuf vingt et un","Words":[{"Word":"acheter","Offset":14000000,"Duration":8300000,"Confidence":0.5739925},{"Word":"?","Offset":22400000,"Duration":800000,"Confidence":0.55187005},{"Word":"z?ro","Offset":26700000,"Duration":2700000,"Confidence":0.8048903},{"Word":"neuf","Offset":29500000,"Duration":6100000,"Confidence":0.88104177},{"Word":"vingt","Offset":36600000,"Duration":4000000,"Confidence":0.8718687},{"Word":"et","Offset":40700000,"Duration":1100000,"Confidence":0.9173769},{"Word":"un","Offset":41900000,"Duration":900000,"Confidence":0.9165993}]},{"Confidence":0.7264791,"Lexical":"acheter e z?ro neuf vingt et un","ITN":"acheter e z?ro neuf vingt et un","MaskedITN":"acheter e z?ro neuf vingt et un","Display":"acheter e z?ro neuf vingt et un","Words":[{"Word":"acheter","Offset":14000000,"Duration":8600000,"Confidence":0.48904553},{"Word":"e","Offset":22700000,"Duration":300000,"Confidence":0.7638467},{"Word":"z?ro","Offset":26700000,"Duration":2700000,"Confidence":0.77111447},{"Word":"neuf","Offset":29500000,"Duration":6100000,"Confidence":0.879264},{"Word":"vingt","Offset":36600000,"Duration":4000000,"Confidence":0.86284995},{"Word":"et","Offset":40700000,"Duration":1100000,"Confidence":0.9175117},{"Word":"un","Offset":41900000,"Duration":900000,"Confidence":0.9165993}]},{"Confidence":0.600041,"Lexical":"ach?ter z?ro neuf vingt et un","ITN":"ach?ter z?ro neuf vingt et un","MaskedITN":"ach?ter z?ro neuf vingt et un","Display":"ach?ter z?ro neuf vingt et un","Words":[{"Word":"ach?ter","Offset":14000000,"Duration":9600000,"Confidence":0.19979793},{"Word":"z?ro","Offset":26700000,"Duration":2700000,"Confidence":0.7306709},{"Word":"neuf","Offset":29500000,"Duration":6100000,"Confidence":0.87971413},{"Word":"vingt","Offset":36600000,"Duration":4000000,"Confidence":0.8646985},{"Word":"et","Offset":40700000,"Duration":1100000,"Confidence":0.9175117},{"Word":"un","Offset":41900000,"Duration":900000,"Confidence":0.9165993}]}]}|exception=

Thanks in advance.

Jérôme.

**Comment by jeromelarman** [comment]
Another example with a new sentence and with recognizer.recognizeOnceAsync().get(); API wich reproduce the issue.

We can notice that the 6 is correctly formated  ( not six ) ... maybe because 6 = six ( english ) = six ( french ) ..

The french locale is set : 		msSpeechConfig.setSpeechSynthesisLanguage("fr-FR");

{"Id":"b067a145e96d468ca21c914af0735582","RecognitionStatus":"Success","Offset":600000,"Duration":46600000,"DisplayText":"Non IBZéro **6** quatre-vingt-onze.","NBest":[{"Confidence":0.8018011,"Lexical":"non i b zéro **six** quatre-vingt-onze","ITN":"non IBZéro 6 quatre-vingt-onze","MaskedITN":"non ibzéro 6 quatre-vingt-onze","Display":"Non IBZéro 6 quatre-vingt-onze.","Words":[{"Word":"non","Offset":600000,"Duration":3200000,"Confidence":0.80226845},{"Word":"i","Offset":20100000,"Duration":2400000,"Confidence":0.42969567},{"Word":"b","Offset":22600000,"Duration":4400000,"Confidence":0.6683084},{"Word":"zéro","Offset":28500000,"Duration":3900000,"Confidence":0.8044615},{"Word":"six","Offset":32500000,"Duration":4900000,"Confidence":0.8342428},{"Word":"quatre-vingt-onze","Offset":37500000,"Duration":9700000,"Confidence":0.94022846}]},{"Confidence":0.7888657,"Lexical":"non i b zéro six quatre vingt onze","ITN":"non i b zéro six quatre vingt onze","MaskedITN":"non i b zéro six quatre vingt onze","Display":"non i b zéro six quatre vingt onze","Words":[{"Word":"non","Offset":600000,"Duration":3200000,"Confidence":0.80226845},{"Word":"i","Offset":20100000,"Duration":2400000,"Confidence":0.42969567},{"Word":"b","Offset":22600000,"Duration":4400000,"Confidence":0.6683084},{"Word":"zéro","Offset":28500000,"Duration":3900000,"Confidence":0.8044615},{"Word":"six","Offset":32500000,"Duration":4900000,"Confidence":0.8342428},{"Word":"quatre","Offset":37500000,"Duration":3000000,"Confidence":0.90770054},{"Word":"vingt","Offset":40600000,"Duration":2000000,"Confidence":0.93341875},{"Word":"onze","Offset":42700000,"Duration":4500000,"Confidence":0.8834277}]},{"Confidence":0.84320134,"Lexical":"non r i b zéro six quatre-vingt-onze","ITN":"non r i b zéro six quatre-vingt-onze","MaskedITN":"non r i b zéro six quatre-vingt-onze","Display":"non r i b zéro six quatre-vingt-onze","Words":[{"Word":"non","Offset":600000,"Duration":3200000,"Confidence":0.80226845},{"Word":"r","Offset":20000000,"Duration":200000,"Confidence":0.4424577},{"Word":"i","Offset":20300000,"Duration":2100000,"Confidence":0.8386096},{"Word":"b","Offset":22500000,"Duration":4500000,"Confidence":0.74848354},{"Word":"zéro","Offset":28500000,"Duration":3900000,"Confidence":0.79195964},{"Word":"six","Offset":32500000,"Duration":4900000,"Confidence":0.8342428},{"Word":"quatre-vingt-onze","Offset":37500000,"Duration":9700000,"Confidence":0.94022846}]},{"Confidence":0.8389546,"Lexical":"non c i b zéro six quatre-vingt-onze","ITN":"non c i b zéro six quatre-vingt-onze","MaskedITN":"non c i b zéro six quatre-vingt-onze","Display":"non c i b zéro six quatre-vingt-onze","Words":[{"Word":"non","Offset":600000,"Duration":3200000,"Confidence":0.80226845},{"Word":"c","Offset":19800000,"Duration":200000,"Confidence":0.50918984},{"Word":"i","Offset":20100000,"Duration":2300000,"Confidence":0.7929598},{"Word":"b","Offset":22500000,"Duration":4500000,"Confidence":0.74414927},{"Word":"zéro","Offset":28500000,"Duration":3900000,"Confidence":0.7883455},{"Word":"six","Offset":32500000,"Duration":4900000,"Confidence":0.8342428},{"Word":"quatre-vingt-onze","Offset":37500000,"Duration":9700000,"Confidence":0.94022846}]},{"Confidence":0.78406274,"Lexical":"non i b zéro six quatre-vingt onze","ITN":"non i b zéro six quatre-vingt onze","MaskedITN":"non i b zéro six quatre-vingt onze","Display":"non i b zéro six quatre-vingt onze","Words":[{"Word":"non","Offset":600000,"Duration":3200000,"Confidence":0.80226845},{"Word":"i","Offset":20100000,"Duration":2400000,"Confidence":0.42969567},{"Word":"b","Offset":22600000,"Duration":4400000,"Confidence":0.6683084},{"Word":"zéro","Offset":28500000,"Duration":3900000,"Confidence":0.8044615},{"Word":"six","Offset":32500000,"Duration":4900000,"Confidence":0.8342428},{"Word":"quatre-vingt","Offset":37500000,"Duration":5100000,"Confidence":0.8979473},{"Word":"onze","Offset":42700000,"Duration":4500000,"Confidence":0.8758101}]}]}

**Comment by jhakulin** [comment]
@jeromelarman Thanks for the report, this is currently under investigation.

**Comment by jhakulin** [comment]
Closing the issue as answered, let us know if more needed
