### ISSUE TITLE
Intermediate recognition results do not contain punctuation

### ISSUE THREAD

**Issue by pengchengZhi001** [Azure-Samples/cognitive-services-speech-sdk#1963]
I use the ConversationTranslator class in JavaScript, and the intermediate recognition results obtained using the recognition method are punctuated.

Using SpeechRecognizer class, the intermediate recognition result obtained by using the recognition method is without punctuation.

Is it possible for SpeechRecognizer class to include punctuation in the intermediate recognition result like ConversationTranslator class?

For example, is it possible to add punctuation to long intermediate recognition results like the following.

 articles or newsletters the focus here is on absorbing grammatical structures learning spelling and vocabulary acquisition and my pro tip for you is to read aloud because this can help you with your pronunciation muscles and your speaking endurance you'll notice that you might get tired in your mouth in your jaw in your throat and that's because it's a different language and you might not be used

Or is there any other way to make the final result of the transcription shorter, I don't want it to return a long piece of content

**Comment by pankopon** [comment]
This was probably already addressed in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1960, maybe @glharper can confirm.

**Comment by glharper** [comment]
@pengchengZhi001 The SDK does not allow the user to control the text length of the intermediate results, no. One client side modification that may help is throttling the input audio stream, but no guarantees on how effective that approach would be.
