### ISSUE TITLE
The specified blob does not exist

### ISSUE THREAD

**Issue by zen37** [Azure-Samples/cognitive-services-speech-sdk#1964]
**Describe the bug**
Audio file not found

`<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:8b944e1e-e01e-0045-55ab-94d79b000000 Time:2023-06-01T17:06:51.5217809Z</Message>
</Error>`

**To Reproduce**
Run batch-synthesis/csharp/BatchSynthesisSample

**Expected behavior**
Blob to exist

**Version of the Cognitive Services Speech SDK**
latest

**Platform, Operating System, and Programming Language**
Windows

**Additional context**
Synthesis edabb760-9b22-4fb2-b263-e7a7fa5c40bb. Status: NotStarted
Synthesis edabb760-9b22-4fb2-b263-e7a7fa5c40bb. Status: Succeeded //the only change made in the program
Please download result from this URL before you delete the synthesis.
https://cvoiceprodusw.blob.core.windows.net/batch-synthesis-output/edabb760-9b22-4fb2-b263-e7a7fa5c40bb/results.zip?skoid=85130dbe-2390-4897-a9e9-5c88bb59daff&sktid=33e01921-4d64-4f8c-a055-5bdaffd5e33d&skt=2023-06-01T16%3A53%3A19Z&ske=2023-06-07T16%3A58%3A19Z&sks=b&skv=2022-11-02&sv=2022-11-02&st=2023-06-01T16%3A53%3A19Z&se=2023-06-02T16%3A58%3A19Z&sr=b&sp=rl&sig=5n2kg4J7ao5xUyfCLLTp6vLbmBabIdV6ZE1Gu0uCBk8%3D
Deleted synthesis edabb760-9b22-4fb2-b263-e7a7fa5c40bb.

**Comment by pankopon** [comment]
@yulin-li Can you please check.

**Comment by yulin-li** [comment]
Hi @zen37 I checked the job you mentioned and our log shows it finished successfully. 

The sample deletes the job as well as the generated files in the last step, as you can see in the logs `Please download result from this URL before you delete the synthesis.`
I am not sure when did you try to download the generated files from blob, before or after the delete?

If you don't want to delete the job, you can remove the corresponding line
