### ISSUE TITLE
API to manage Models

### ISSUE THREAD

**Issue by alt95** [Azure-Samples/cognitive-services-speech-sdk#1965]
**Is your feature request related to a problem? Please describe.**
There is currently no API to just add, delete or update models in a granular way.

**Describe the solution you'd like**
LUIS Allowed so much more granularity in it's API with being able to manipulate intents, utterances, patterns etc. CLU - Language offers none of this API.

https://learn.microsoft.com/en-us/rest/api/cognitiveservices-luis/authoringv2.0/model/add-intent?tabs=HTTP
Compared to
https://learn.microsoft.com/en-us/rest/api/language/2022-10-01-preview/conversational-analysis-authoring

**Additional context**
This would be great for anyone wanting to build more abstractions over CLU - Language.

**Comment by pankopon** [comment]
@zhouwangzw @mahilleb-msft Do you know who could best comment on this?

**Comment by ahmedaashour** [comment]
Hello @alt95 ,

While LUIS authoring APIs were designed with a CRUD paradigm in mind, the CLU authoring APIs were designed to handle changes to the schema and training data through importing and exporting the project.

This made it easier for users to manipulate snapshots of their projects while they were being authored, whether through version control or manual versioning.

We have the CRUD APIs support in our backlogs, but it's not one of the features we're currently working on. So it may be a little ways down the road before they're made available.

Thank you.
