### ISSUE TITLE
[python] Manage microphone input on backend from frontend websocket

### ISSUE THREAD

**Issue by TanikuDev** [Azure-Samples/cognitive-services-speech-sdk#1967]
Hi team,

Sorry to bother you. I'm using since few weeks the SDK for speech-cognitive services. Working fine until now :).

I'm now trying to manage the websockets as input and I face some issues. For context, I'm using flask_socketio for websockets.

In my app.py I declare everything needed to catch my events, working fine.

Following the sample "[speech_sample.py](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_sample.py#LL555C5-L555C40)", I built my event classes to add the speech sdk init.

Here is my event class managing my audio:

```python
class AudioSio(Namespace):
   """
   Initialize the websocket at start or my namespace '/audio'
   """
    def __init__(self, namespace: str = "/audio", socketio=None, logger=None):
        self.speech_config = speechsdk.SpeechConfig(
            subscription=speech_key, region=service_region
        )
        self.recognizer = None
        self.audio_stream = None
    
    def on_speech_result(self, data):
        result = data.result
        if result.reason == speechsdk.ResultReason.RecognizedSpeech:
            text = result.text
            self.logger.info("Speech recognized: " + text)

     # Catch event name called audio
     def on_audio(self, data):
        if data == "start":
            self.logger.info("Starting speech recognition")
            self.audio_stream = speechsdk.audio.PushAudioInputStream()
            self.recognizer = speechsdk.SpeechRecognizer(
                speech_config=self.speech_config,
                audio_config=speechsdk.audio.AudioConfig(stream=self.audio_stream),
            )
            self.recognizer.recognized.connect(self.on_speech_result)
            self.recognizer.start_continuous_recognition_async()

        elif data == "stop":
            self.logger.info("Stopping speech recognition")
            if self.recognizer:
                self.recognizer.stop_continuous_recognition_async()
                self.recognizer.recognized.disconnect_all()
            self.recognizer = None

        else:
            # Data is a structure with information (channel,length,...) and the stream in bytes
            for audio in data:
                if not audio:
                    continue
                self.audio_stream.write(audio["stream"])
```
The result text is always empty and with the status ResultReason.RecognizedSpeech.

To check if everything was ok, instead of writing in `self.audio_stream.write`, I pushed into a wav file (with pyaudio) my `audio["stream"]`. Working with a file and the sdk, I can decode everything and the generated text is ok.

Do you have any idea on how I can go further please ?
Many thanks for your support

**Comment by jhakulin** [comment]
@TanikuDev Thanks for the report. Could you please provide us Speech SDK log?
https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

Speech SDK by default assumes streams are in 16-bit, 16kHz, 1 channel PCM. Could you please confirm audio format
of the stream data?

**Comment by TanikuDev** [comment]
Thanks for your feedback @jhakulin.
Here are the logs:

[LogfilePathAndName.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/11636337/LogfilePathAndName.txt)

```
$ file edc60309d5574739b667c36acab90262.wav
> edc60309d5574739b667c36acab90262.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 48000 Hz
```
There is only 1 channel.

Do you think I need to redo in precising the 48kHz instead of 16hHz ? I needed I can give you the wav file.

**Comment by jhakulin** [comment]
@TanikuDev 
With stream by default wave header gets filled as 1ch, 16bit, 16kHz. Seems your stream data is 1ch, 16bit, 48kHz.
Could you please test configuring the push stream as follows?
channels = 1
bits_per_sample = 16
samples_per_second = 48000
wave_format = msspeech.audio.AudioStreamFormat(samples_per_second, bits_per_sample, channels)
stream = msspeech.audio.PushAudioInputStream(stream_format=wave_format)

**Comment by TanikuDev** [comment]
I just did:
```python
            self.audio_stream = speechsdk.audio.PushAudioInputStream(
                speechsdk.audio.AudioStreamFormat(
                    samples_per_second=48000, bits_per_sample=16, channels=1
                )
            )
```           
I have the exact same result for now (I clean everything I relaunch my server...just in case).

Here are my logs:
[LogfilePathAndName.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/11636702/LogfilePathAndName.txt)

**Comment by TanikuDev** [comment]
Hi @jhakulin, I have some question. I'm continuing debugging (try to do my best at least :) )
*  Is there any way to check what is sent via the socket to the speech cognitive ?
*  Do you expect a minimal size for chunks (for now 512 bytes are sent from the frontend?
* Do I need maybe to stack or do you already perform it on the SDK ?
Again many thanks for your time.

**Comment by jhakulin** [comment]
@TanikuDev Checked more and the issue could be that streaming audio is base64 encoded and in order to get the streaming working you need to decode it before writing to push audio input stream. Please see the following old issue to see how to base64 decode https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1065#issuecomment-834720779

**Comment by TanikuDev** [comment]
Thanks for your  feedback @jhakulin. Sorry to bother again, I have one more question to better understand. 
Which kind of format is expected on the write method? Today, I have a Float32Array type on the JS side send directly via a websocket.

**Comment by jhakulin** [comment]
@TanikuDev See https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-audio-input-streams#identify-the-format-of-the-audio-stream for the stream audio input format

**Comment by TanikuDev** [comment]
Hi @jhakulin,

Thanks for the update and your precious help.

We succeed on our side. I put the code just in case:

```python
def float2pcm(audio_from_ws, dtype="int16"):
    res = audio_from_ws.split(",")

    audio_in_float = []
    for a in res:
        audio_in_float.append(float(a))
    arr = np.array(audio_in_float, dtype=np.float32)

    # Scale between -1 and 1
    arr_scaled = np.interp(arr, (np.min(arr), np.max(arr)), (-1, 1))

    # Convert to int16
    arr_int16 = (arr_scaled * 32767).astype(np.int16)

    return arr_int16.tobytes()
```

On the frontend side:
```typescript
workletNodeRef.current.port.onmessage = (event: MessageEvent) => {
     if (audioStatus === AudioStatus.Started || audioStatus === AudioStatus.Starting) {
            let data = [{}];
            for (let i = 0; i < event.data.length; i++) {
                if (audioInput && ... ) {
                       let settings = audioInput.mediaStream.getAudioTracks()[i].getSettings();
                        var baseInString = event.data[i].toString('base64');
                        data.push({
                            "sampleRate": settings.sampleRate,
                            "sampleSize": settings.sampleSize,
                            "channelCount": data.length,
                            "framesNumber": event.data[i].length,
                            "stream": baseInString,
                            "type": "audio",
                            "channel": i,
                        });
                }
           }
          send(data);
     }
}
```

I close the case.

**Comment by jhakulin** [comment]
@TanikuDev Thank you for sharing the solution!
