### ISSUE TITLE
Support for watchOS

### ISSUE THREAD

**Issue by bobbyrehm** [Azure-Samples/cognitive-services-speech-sdk#1968]
Hello,

We are enjoying the Speech SDK in our iOS app, but we also have an Apple Watch app that we would love to be able to use the Speech SDK in. Is this something that you could add support for? 

Here is the relevant documentation under the man page for xcodebuild. I believe you would need to update your existing scheme or add a new scheme with a WatchKit app so that the watchOS architectures (both device and simulator) are included. Then they can be integrated into the xcframework along with the other architectures/destinations you are already using.

> Destinations
>      The -destination option takes as its argument a destination specifier describing the device (or devices) to use as a destination.  A destination specifier is a single argument consisting of a set of comma-separated key=value pairs.  The
>      -destination option may be specified multiple times to cause xcodebuild to perform the specified action on multiple destinations.
> 
>      watchOS            A watchOS app is always built and deployed nested inside of an iOS app. To use a watchOS device as your destination, specify a scheme which is configured to run a WatchKit app, and specify the iOS platform destination that is
>                         paired with the watchOS device you want to use.
> 
>      watchOS Simulator  A watchOS Simulator app is always built and deployed nested inside of an iOS Simulator app. To use a watchOS Simulator device as your destination, specify a scheme which is configured to run a WatchKit app, and specify the iOS
>                         Simulator platform destination that is paired with the watchOS Simulator device you want to use. 

Thank you!

**Comment by jhakulin** [comment]
@bobbyrehm Thanks for the request, We will evaluate this and let you know.
Internal workitem ref: 5282747

**Comment by pankopon** [comment]
Closed as there is now a work item on the backlog and we are tracking the feature request there, no ETA for the time being. Please open a new issue if more support is needed.

**Comment by bobbyrehm** [comment]
@jhakulin we would need support for watchOS 8.0 and later. Thanks!

**Comment by jhakulin** [comment]
@bobbyrehm Thanks, I learnt that WatchOS does not support AudioToolbox, which would provide audio APIs (access to microphone) and seems audio input options would be stream audio bytes/file input. Is that what you expect also?

**Comment by bobbyrehm** [comment]
@jhakulin yes that looks to be correct, it doesn't look like AudioToolbox is available for watchOS. You should still be able to access the microphone on the watch using the [AVFAudio](https://developer.apple.com/documentation/avfaudio) APIs (AVAudioRecorder for basic recording and AVAudioEngine for more control).
