### ISSUE TITLE
Speech To Text Displayed Word Offset/Duration incorrect after saying 'new line' or 'new paragraph'

### ISSUE THREAD

**Issue by derevell** [Azure-Samples/cognitive-services-speech-sdk#1971]
Version: 1.29
Windows 10 x64
C#

To clarify a bit more about the bug with “new line” and “new paragraph”.  In testing we found these bugs with the offset/duration between the DisplayedWords and Words.

If you say “new line”
displayed.word = ‘\n’
displayed.Offset=3500000
displayed.Duration=5200000

word. Word =new
word.Offset=3500000
word.Duration=2900000

word.Word=line
word.Offset=6500000
word.Duration=2200000

As you can see the sum of the word.durations = 5100000 which is different than the displayed.Duration
This difference seems to grow with the more words that our outputted.  The expected would be the sum of the two words duration
'new' and 'line' would equal the displayed word duration

If you say “good morning new line today is a great day”  see JSON below
You will get on the DisplayedWords 
“morning\nToday” on the second displayed word which causes problems trying to match up the offset/durations as it appears that the word after the \n (Today) is not counted in the displayed duration.

displayed .word=morning\nToday
displayed .Offset=114600000
displayed .Duration=7200000

word.word=morning
word.Offset= 114600000
word.Duration= 3300000

word.word=new
word.Offset= 118000000
word.Duration= 1700000

word.word=line
word.Offset= 119800000
word.Duration= 2000000

word.word=Today
word.Offset= 121900000
word.Duration= 2600000

If you look the word durations total 9600000 which is a lot larger than the displayed.Duration of 7200000

This causes a bunch of issues with trying to match up audio w/ outputted text.

Ideally, 
-	The displayed word should be broken up into 3 displayed words instead of 1 to maintain consistency between saying new line as phrase or saying it mid phrase.
-	There usually is a 1 to many displayed to phonetic word but the offset/durations should match up.

This is a deal breaker for me, so I hope you can help.

"{\"Id\":\"36e0050d1d55441ab896b04039a59a96\",\"RecognitionStatus\":\"Success\",\"Offset\":111600000,\"Duration\":24900000,\"Channel\":0,\"DisplayText\":\"Good morning\\nToday will be a great day\",\"NBest\":[{\"Confidence\":0.8615821,\"Lexical\":\"good morning new line today will be a great day\",\"ITN\":\"good morning new line today will be a great day\",\"MaskedITN\":\"\",\"Display\":\"Good morning\\nToday will be a great day\",\"Words\":[{\"Word\":\"good\",\"Offset\":111600000,\"Duration\":2900000,\"Confidence\":0.89899564},{\"Word\":\"morning\",\"Offset\":114600000,\"Duration\":3300000,\"Confidence\":0.91725844},{\"Word\":\"new\",\"Offset\":118000000,\"Duration\":1700000,\"Confidence\":0.66198134},{\"Word\":\"line\",\"Offset\":119800000,\"Duration\":2000000,\"Confidence\":0.9035119},{\"Word\":\"today\",\"Offset\":121900000,\"Duration\":2600000,\"Confidence\":0.7823628},{\"Word\":\"will\",\"Offset\":124600000,\"Duration\":1700000,\"Confidence\":0.6174337},{\"Word\":\"be\",\"Offset\":126400000,\"Duration\":1100000,\"Confidence\":0.97503865},{\"Word\":\"a\",\"Offset\":127600000,\"Duration\":700000,\"Confidence\":0.71079135},{\"Word\":\"great\",\"Offset\":128400000,\"Duration\":2100000,\"Confidence\":0.9032738},{\"Word\":\"day\",\"Offset\":130600000,\"Duration\":5900000,\"Confidence\":0.9475509}],\"DisplayWords\":[{\"Word\":\"Good\",\"Offset\":111600000,\"Duration\":2900000},{\"Word\":\"morning\\nToday\",\"Offset\":114600000,\"Duration\":7200000},{\"Word\":\"will\",\"Offset\":121900000,\"Duration\":2600000},{\"Word\":\"be\",\"Offset\":124600000,\"Duration\":1700000},{\"Word\":\"a\",\"Offset\":126400000,\"Duration\":1100000},{\"Word\":\"great\",\"Offset\":127600000,\"Duration\":700000},{\"Word\":\"day\",\"Offset\":128400000,\"Duration\":2100000}]},{\"Confidence\":0.80006325,\"Lexical\":\"good morning newline today will be a great day\",\"ITN\":\"good morning newline today will be a great day\",\"MaskedITN\":\"\",\"Display\":\"good morning newline today will be a great day\",\"Words\":[{\"Word\":\"good\",\"Offset\":111600000,\"Duration\":2900000,\"Confidence\":0.89899564},{\"Word\":\"morning\",\"Offset\":114600000,\"Duration\":3300000,\"Confidence\":0.91725844},{\"Word\":\"newline\",\"Offset\":118000000,\"Duration\":3800000,\"Confidence\":0.38254952},{\"Word\":\"today\",\"Offset\":121900000,\"Duration\":2600000,\"Confidence\":0.77583003},{\"Word\":\"will\",\"Offset\":124600000,\"Duration\":1700000,\"Confidence\":0.66002476},{\"Word\":\"be\",\"Offset\":126400000,\"Duration\":1100000,\"Confidence\":0.97503865},{\"Word\":\"a\",\"Offset\":127600000,\"Duration\":700000,\"Confidence\":0.71079135},{\"Word\":\"great\",\"Offset\":128400000,\"Duration\":2100000,\"Confidence\":0.9032738},{\"Word\":\"day\",\"Offset\":130600000,\"Duration\":5900000,\"Confidence\":0.9475509}]},{\"Confidence\":0.8243587,\"Lexical\":\"good morning new line today we'll be a great day\",\"ITN\":\"good morning new line today we'll be a great day\",\"MaskedITN\":\"\",\"Display\":\"good morning new line today we'll be a great day\",\"Words\":[{\"Word\":\"good\",\"Offset\":111600000,\"Duration\":2900000,\"Confidence\":0.89899564},{\"Word\":\"morning\",\"Offset\":114600000,\"Duration\":3300000,\"Confidence\":0.91725844},{\"Word\":\"new\",\"Offset\":118000000,\"Duration\":1700000,\"Confidence\":0.66198134},{\"Word\":\"line\",\"Offset\":119800000,\"Duration\":2000000,\"Confidence\":0.9035119},{\"Word\":\"today\",\"Offset\":121900000,\"Duration\":2600000,\"Confidence\":0.7823628},{\"Word\":\"we'll\",\"Offset\":124600000,\"Duration\":1700000,\"Confidence\":0.33295888},{\"Word\":\"be\",\"Offset\":126400000,\"Duration\":1100000,\"Confidence\":0.94016755},{\"Word\":\"a\",\"Offset\":127600000,\"Duration\":700000,\"Confidence\":0.798125},{\"Word\":\"great\",\"Offset\":128400000,\"Duration\":2100000,\"Confidence\":0.74979967},{\"Word\":\"day\",\"Offset\":130600000,\"Duration\":5900000,\"Confidence\":0.92939925}]},{\"Confidence\":0.8254448,\"Lexical\":\"good morning new line today would be a great day\",\"ITN\":\"good morning new line today would be a great day\",\"MaskedITN\":\"\",\"Display\":\"good morning new line today would be a great day\",\"Words\":[{\"Word\":\"good\",\"Offset\":111600000,\"Duration\":2900000,\"Confidence\":0.89899564},{\"Word\":\"morning\",\"Offset\":114600000,\"Duration\":3300000,\"Confidence\":0.91725844},{\"Word\":\"new\",\"Offset\":118000000,\"Duration\":1700000,\"Confidence\":0.66198134},{\"Word\":\"line\",\"Offset\":119800000,\"Duration\":2000000,\"Confidence\":0.9035119},{\"Word\":\"today\",\"Offset\":121900000,\"Duration\":2600000,\"Confidence\":0.7823628},{\"Word\":\"would\",\"Offset\":124600000,\"Duration\":1800000,\"Confidence\":0.1473946},{\"Word\":\"be\",\"Offset\":126500000,\"Duration\":1000000,\"Confidence\":0.9643255},{\"Word\":\"a\",\"Offset\":127600000,\"Duration\":700000,\"Confidence\":0.78440297},{\"Word\":\"great\",\"Offset\":128400000,\"Duration\":2100000,\"Confidence\":0.92159015},{\"Word\":\"day\",\"Offset\":130600000,\"Duration\":5900000,\"Confidence\":0.93721753}]},{\"Confidence\":0.76206183,\"Lexical\":\"good morning newline today would be a great day\",\"ITN\":\"good morning newline today would be a great day\",\"MaskedITN\":\"\",\"Display\":\"good morning newline today would be a great day\",\"Words\":[{\"Word\":\"good\",\"Offset\":111600000,\"Duration\":2900000,\"Confidence\":0.89899564},{\"Word\":\"morning\",\"Offset\":114600000,\"Duration\":3300000,\"Confidence\":0.91725844},{\"Word\":\"newline\",\"Offset\":118000000,\"Duration\":3800000,\"Confidence\":0.38254952},{\"Word\":\"today\",\"Offset\":121900000,\"Duration\":2600000,\"Confidence\":0.77583003},{\"Word\":\"would\",\"Offset\":124600000,\"Duration\":1800000,\"Confidence\":0.16321677},{\"Word\":\"be\",\"Offset\":126500000,\"Duration\":1000000,\"Confidence\":0.9643255},{\"Word\":\"a\",\"Offset\":127600000,\"Duration\":700000,\"Confidence\":0.78440297},{\"Word\":\"great\",\"Offset\":128400000,\"Duration\":2100000,\"Confidence\":0.92159015},{\"Word\":\"day\",\"Offset\":130600000,\"Duration\":5900000,\"Confidence\":0.93721753}]}]}"

**Comment by dargilco** [comment]
@derevell I got word from the service team that they are able to reproduce the issue under certain conditions. To learn more about your usage case, can you please take SDK  logs while this happens and share it here? See
https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

**Comment by derevell** [comment]
[RadiaAzureVoiceRecognition.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/11709333/RadiaAzureVoiceRecognition.log)
Here is the log

**Comment by derevell** [comment]
[RadiaAzureVoiceRecognition.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/11709516/RadiaAzureVoiceRecognition.log)
Another example log of saying the sigmoid colon and it outputs sigmoid:
I would say that all explicit punctuation for the displayed word list should be it own item vs tacked on to the preceding word.  In this case the formatting : is incorrect and should be 'colon'.  I need to be able to have the punctuation offset/duration separated so that I can change that.

**Comment by issaca** [comment]
Are you using "custom speech" text normalization or reformulation to convert "new line" to "\n"? I ask because the mapping from "new line" -> "\n" is not the default behavior.

**Comment by pankopon** [comment]
@issaca Based on the log, a custom endpoint is used - from RadiaAzureVoiceRecognition.log :
```
[514143]: 42ms SPX_TRACE_INFO:  usp_connection.cpp:527 connectionUrl=wss://westus2.stt.speech.microsoft.com/speech/recognition/dictation/cognitiveservices/v1?cid=4ce80c8c-07a9-426a-8278-ca01b31eec18&displayWordTimings=true&endSilenceTimeoutMs=250&format=detailed&initialSilenceTimeoutMs=15000&language=en-US&profanity=raw&punctuation=explicit&wordLevelConfidence=true&wordLevelTimestamps=true
```
cid=4ce80c8c-07a9-426a-8278-ca01b31eec18
displayWordTimings=true
endSilenceTimeoutMs=250
format=detailed
initialSilenceTimeoutMs=15000
language=en-US
profanity=raw
punctuation=explicit
wordLevelConfidence=true
wordLevelTimestamps=true

**Comment by pankopon** [comment]
Closed since no update since July -> either obsolete or unsupported. @issaca FYI
