### ISSUE TITLE
BookmarkReached Event Not Firing for Adjacent Bookmark Tags

### ISSUE THREAD

**Issue by aamoronatti** [Azure-Samples/cognitive-services-speech-sdk#1972]
**Describe the bug**
When multiple bookmark tags are next to each other the bookmark reached event is only fired once:

**To Reproduce**

Input SSML

`<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="es-ES"><voice name="es-ES-AlvaroNeural"><prosody rate="1"><bookmark mark="123423"/>Una montaña es una figurita <bookmark mark="99"/><bookmark mark="98"/> topográfica <bookmark mark="1"/> del relieve terrestre positiva.</prosody></voice></speak>`

```
def bookmark_reached(evt):
        print('BookmarkReached event:')
        print('\tAudioOffset: {}ms'.format(
            (evt.audio_offset + 5000) / 10000 + audio_position))
        print('\tText: {}'.format(evt.text))
        animationPositions.append(
            {"id": evt.text, "ms": (evt.audio_offset + 5000) / 10000 + audio_position})

    speech_config.speech_synthesis_voice_name = voiceId
    speech_config.set_speech_synthesis_output_format(
        speechsdk.SpeechSynthesisOutputFormat.Audio48Khz192KBitRateMonoMp3)
    speech_synthesizer = speechsdk.SpeechSynthesizer(
        speech_config=speech_config, audio_config=None)

    speech_synthesizer.bookmark_reached.connect(bookmark_reached)

    result = speech_synthesizer.speak_ssml(text)
```

**Expected behavior**
BookmarkReached event:
        AudioOffset: 0.5ms
        Text: 123423
 BookmarkReached event:
        AudioOffset: 1700.5ms
        Text: 99
BookmarkReached event:
        AudioOffset: 1700.5ms
        Text: 98
BookmarkReached event:
        AudioOffset: 2363.0ms
        Text: 1

**Actual behavior**
BookmarkReached event:
        AudioOffset: 0.5ms
        Text: 123423
BookmarkReached event:
        AudioOffset: 1700.5ms
        Text: 98
BookmarkReached event:
        AudioOffset: 2363.0ms
        Text: 1

**Version of the Cognitive Services Speech SDK**
Python azure-cognitiveservices-speech 1.29.0

**Platform, Operating System, and Programming Language**
 - OS: Windows
 - Programming language: Python

**Comment by dargilco** [comment]
Hi @anton-vidext thank you for opening this issue and providing detailed description. @yulin-li can you please have a look?

**Comment by yulin-li** [comment]
I think this's a known issue. @newhillchan could you help check if it's fixed? If not, could you share the plan?

**Comment by anton-vidext** [comment]
Any update?

**Comment by pankopon** [comment]
@newhillchan @yulin-li Please confirm the status and update, are there any fixes still expected?

**Comment by Kerry-LinZhang** [comment]
@newhillchan could you please help to follow up with the feedback, any update, please feel free to comment here.

**Comment by Kerry-LinZhang** [comment]
Tracked as long-term fix, we have put it into backlog for future plan. Will continue follow up with it.

**Comment by Kerry-LinZhang** [comment]
Hi @aamoronatti we have fix this issue already, please try again.

**Comment by pankopon** [comment]
Closing the item since no changes to current design are planned.
