### ISSUE TITLE
Date/Time formatting on displayed text not correct

### ISSUE THREAD

**Issue by derevell** [Azure-Samples/cognitive-services-speech-sdk#1975]
C#
Version: 1.29.0

There is a bug when dictated a date and time together in long format or short format.  If you dictate the date and time separately it appears to work but if you dictate
- January twenty-fifth nineteen seventy-five four thirty pm  the displayed text outputs January 25th 1970 five 4:30 PM
- One twenty-five seventy-five four thirty pm it outputs 12570 five 4:30 PM
- One twenty-five nineteen seventy-five four thirty pm outputs 1/25/1970 five 4:30 PM

[RadiaAzureVoiceRecognition.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/11709956/RadiaAzureVoiceRecognition.log)

**Comment by derevell** [comment]
The output for other speech to text engines has been 1/25/1975 4:30PM in our testing.  This is a fairly common way to output date/times that are spoken when documenting legal/medical events (examples date/time of birth, exam, event) among our users since they have been using other speech to text engines.  Testing and saying 'at' does seem to output correctly but retraining a user population to change the way they speak would be a challenge.

**Comment by BrianMouncer** [comment]
I will give this feedback to our text normalization team, and see what they say.

Do you have a more complete list of spoken and lexical forms, so that if they make changes to improve these results, it's more than just the few example cases you listed above?

**Comment by glecaros** [comment]
This issue has been fixed by the service team and it should be deployed soon.
