### ISSUE TITLE
Please tell me what is the evt parameter in the stop_cb function, and how can I stop the recognition at a specified time?

### ISSUE THREAD

**Issue by Bruce337f** [Azure-Samples/cognitive-services-speech-sdk#1976]
这是我的代码:
def speech_recognize_continuous_from_file():
    """performs continuous speech recognition with input from an audio file"""
    # <SpeechContinuousRecognitionWithFile>
    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)
    audio_config = speechsdk.audio.AudioConfig(filename=weatherfilename)

    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)

    done = False

    def stop_cb(evt: speechsdk.SessionEventArgs):
        """callback that signals to stop continuous recognition upon receiving an event `evt`"""
        print('CLOSING on {}'.format(evt))
        nonlocal done
        done = True

    # Connect callbacks to the events fired by the speech recognizer
    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
    speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))
    # stop continuous recognition on either session stopped or canceled events
    speech_recognizer.session_stopped.connect(stop_cb)
    speech_recognizer.canceled.connect(stop_cb)

    # Start continuous speech recognition
    speech_recognizer.start_continuous_recognition()
    while not done:
        time.sleep(.5)

    speech_recognizer.stop_continuous_recognition()

**Comment by BrianMouncer** [comment]
[SessionEventArgs](https://learn.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.sessioneventargs?view=azure-python) will have a session ID, so if you have multiple recognition sessions running at the same time, you can tell which one was canceled or stopped.  In most scenarios, you would not use the SessionEvendArgs that is provided when the engine fires the "session_stopped" or "canceled" event callback.

Can you provide more detail about what you want to do?

Here are three common scenarios:

If you want to perform continuous recognition, but "stop" when a specific word is detected, you could replace the simple inline lambda in your code above, with an actual call back function that checks the recognized test for a specific word, and then call speech_recognizer.stop_continuous_recognition() when the word is recognized.

If you want to recognize for only a set amount of time, you could start a dead man timer on another thread, and call stop_continuous_recognition() when it fires after X seconds of wall clock time.

You could also check the ["offset" attribute on the "recognizing" event args](https://learn.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.recognitioneventargs?view=azure-python) as the engine starts making hypotheses about what the speaker is saying, it will report back at what time in the audio the word was detected.  Then after a certain number of milliseconds of actual processed audio, you could call stop on the engine.

Hope one of those helps...

**Comment by BrianMouncer** [comment]
Feel free to reopen or create new issue if you run into troubles on a different topic..
