### ISSUE TITLE
how to use speech to text while files are in other cloud

### ISSUE THREAD

**Issue by yigubigu** [Azure-Samples/cognitive-services-speech-sdk#1977]
Background: have files in other cloud, and want to convert them into text.
Testing have been done: have done testing with  speech studio, https://speech.microsoft.com/portal/611bd93d7a37431c9f11afa2281be81b/speechtotexttool.
After uploading files to this website, the system can return correct text content. 

Question: how to parse this file in java code?
I follow SpeechRecognitionSamples to parse wav file, system throw exception 
java.lang.IllegalArgumentException: RIFF

**Comment by yigubigu** [comment]
The file format is  audio/opus

**Comment by yigubigu** [comment]
@Test
    public void verifyAudioFileFormat() {
        String filePath = "download";
        File audioFile = new File(filePath);

        try (InputStream inputStream = new FileInputStream(audioFile)) {
            AutoDetectParser parser = new AutoDetectParser();
            Metadata metadata = new Metadata();
            BodyContentHandler handler = new BodyContentHandler();

            parser.parse(inputStream, handler, metadata);

            String format = metadata.get("Content-Type");
            System.out.println("Audio format: " + format);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

**Comment by pankopon** [comment]
Closed since no logs provided, please open a new issue if more support is needed.
