### ISSUE TITLE
java.lang.UnsatisfiedLinkError using TTS in Windows 10 development environment

### ISSUE THREAD

**Issue by Kyle-Kinney** [Azure-Samples/cognitive-services-speech-sdk#1984]
**Describe the bug**
I'm trying to get the Java text-to-speech quickstart at https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-text-to-speech?tabs=windows%2Cterminal&pivots=programming-language-java working on my Windows 10 development environment using IntelliJ, but it keeps throwing this error: java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V. I've seen people reporting seeing this error when running under Linux, but I'm using Windows. I have no idea what DLL it's failing to find or where it's supposed to be found.

**To Reproduce**
I don't know how to reproduce this on any machine but my own.

**Version of the Cognitive Services Speech SDK**
1.29.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - x64
 - Programming language: Java

**Comment by yulin-li** [comment]
On Windows, you must use the 64-bit target architecture. Windows 10 or later is required.

You must install the [Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017, 2019, and 2022](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170&preserve-view=true) for your platform. Installing this package for the first time might require a restart.

**Comment by Kyle-Kinney** [comment]
Aha. Thanks, that did the trick; I had an older version of the redistributable, and it's working now that I installed the new version. Not sure why I couldn't find that in the documentation, but now that I'm looking for it specifically, there it is.
