### ISSUE TITLE
How do I use ConversationTranscriber service on mobile application?

### ISSUE THREAD

**Issue by imaiya** [Azure-Samples/cognitive-services-speech-sdk#1985]
Hello
 I am a mobile application developer. Our application wants automatic speech recognition and tagging of speakers in multi-person speaking scenarios. I think the azure Conversation transcription solution can be achieved, but it seems that it can only be used on multi-channel microphone array devices at present. How should I use it in the mobile application?

My English is not very good, sorry

**Comment by brandom-msft** [comment]
Hi @imaiya - thanks for the interest in Microsoft Speech SDK. As you mentioned, our documentation for Conversation Transcription does specify a [limitation on a multi-channel microphone](https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-use-conversation-transcription?pivots=programming-language-csharp#limitations). 

There is another offering (currently as a preview feature) for [multi-device conversation](https://learn.microsoft.com/azure/cognitive-services/speech-service/multi-device-conversation), does that align with your scenario?

**Comment by YanMicrosoft** [comment]
Hi, @imaiya ,
Thanks for reaching out. We now have the Real-time Diarization feature ready in Private Preview that I think could satisfy your scenario requirements. Could you please email AzureSpeechMonochannelDiarizationRequest <diarizationrequest@microsoft.com> to request the Private Preview? Thanks.

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
