### ISSUE TITLE
First Bookmark's audio_offset Incorrectly Includes Following Break Time Duration

### ISSUE THREAD

**Issue by aamoronatti** [Azure-Samples/cognitive-services-speech-sdk#1987]
**Describe the bug**
When a bookmark is placed at the very beginning of the SSML string and is followed by a <break> tag, the evt.audio_offset value of the bookmark incorrectly includes the break time. This does not occur when the bookmark is placed elsewhere in the SSML string.

**To Reproduce**

1. Generate SSML that starts with a bookmark followed by a break, e.g., <bookmark mark="1"/> <break time="2s"/>.
2. Process the SSML with the Azure Text to Speech service.
3. In the bookmark_reached callback, log the evt.audio_offset value.

Example SSML:

`<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="es-ES"><voice name="es-ES-AlvaroNeural"><prosody rate="1"><bookmark mark="1"/> <break time="2s"></break> ¡Hola! ¿Qué tal? <bookmark mark="2"/> <break time="2s"></break></prosody></voice></speak>`

**Expected behavior**
The _evt.audio_offset value_ of the bookmark should not include the subsequent break time. As the bookmark is placed at the very start of the SSML, the evt.audio_offset should be 0.

**Version of the Cognitive Services Speech SDK**
azure-cognitiveservices-speech 1.29.0

**Platform, Operating System, and Programming Language**
 - OS: Any
 - Programming language: Python

**Comment by yulin-li** [comment]
@newhillchan could you please help to take a look?

**Comment by pankopon** [comment]
@newhillchan @yulin-li Any update?

**Comment by anton-vidext** [comment]
> @newhillchan @yulin-li Any update?

Yes, please. Any update?

**Comment by Kerry-LinZhang** [comment]
@newhillchan could you please help to follow up with the feedback, any update, please feel free to comment here.

**Comment by anton-vidext** [comment]
Can't this be asigned to anyone else?

**Comment by Kerry-LinZhang** [comment]
Tracked as long-term fix, we have put it into backlog for future plan. Will continue follow up with it.

**Comment by Kerry-LinZhang** [comment]
Hi @anton-vidext to help us reprioritize the issue, would you mind further clarifiy the impact on you, and how urgent you would like it to be fixed?

**Comment by anton-vidext** [comment]
We are an AI video generator platform, we use various TTS providers to generate the voice of the videos. We use bookmark tags to receive the exact moment an animation has to animate in a vídeo.

We currently made a "fix" that basically adds

`<prosody volume="0" rate="100">a.</prosody>`

before every bookmark so the timestamp is OK.

So I guess it will impact on the pricing as we have to insert some useless characters before every bookmark.

**Comment by Kerry-LinZhang** [comment]
Hi @anton-vidext thanks for your feedback, yes, this will incur additional costs as the doc shows, 
https://learn.microsoft.com/en-us/azure/ai-services/speech-service/text-to-speech#pricing-note

We will figure out if there will be any other workarond for it.

**Comment by Kerry-LinZhang** [comment]
Hi @anton-vidext another way for your reference,

<speak version="1.0" xmlns="[http://www.w3.org/2001/10/synthesis"](http://www.w3.org/2001/10/synthesis%22) xmlns:mstts='[https://www.w3.org/2001/mstts'](https://www.w3.org/2001/mstts%27) xml:lang="es-ES"><voice name="es-ES-AlvaroNeural"><bookmark mark="1"/>**<mstts:audioduration value="2s"><prosody volume="0">hola hola hola hola hola</prosody></mstts:audioduration>**</voice><voice name="es-ES-AlvaroNeural"><prosody rate="1"> ¡Hola! ¿Qué tal? <bookmark mark="2"/> <break time="2s"></break></prosody></voice></speak>

**Comment by Kerry-LinZhang** [comment]
<speak version="1.0" xmlns="[http://www.w3.org/2001/10/synthesis"](http://www.w3.org/2001/10/synthesis%22) xmlns:mstts='[https://www.w3.org/2001/mstts'](https://www.w3.org/2001/mstts%27) xml:lang="es-ES"><voice name="es-ES-AlvaroNeural"><bookmark mark="1"/> <mstts:audioduration value="2s"><prosody volume="0">hola hola hola hola hola</prosody></mstts:audioduration></voice><voice name="es-ES-AlvaroNeural"><prosody rate="1"> ¡Hola! ¿Qué tal? <bookmark mark="2"/> <break time="2s"></break></prosody></voice></speak>

**Comment by Kerry-LinZhang** [comment]
Hi @anton-vidext here is another workaround for your reference,

<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts='https://www.w3.org/2001/mstts' xml:lang="es-ES">**<voice name="es-ES-AlvaroNeural"><bookmark mark="1"/> <mstts:audioduration value="2s"><prosody volume="0">hola hola hola hola hola</prosody></mstts:audioduration></voice>**<voice name="es-ES-AlvaroNeural"><prosody rate="1"> ¡Hola! ¿Qué tal? <bookmark mark="2"/> <break time="2s"></break></prosody></voice></speak>

**Comment by Kerry-LinZhang** [comment]
Hi @anton-vidext currently we have 2 workaround for you to try,

1. <prosody volume="0" >a.</prosody>              
     According to your workaround, you can also try this one without 'rate'
2. Using '<voice name="es-ES-AlvaroNeural"><bookmark mark="1"/> <mstts:audioduration value="2s"><prosody volume="0">hola hola hola hola hola</prosody></mstts:audioduration></voice>' to replace break
![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/122077766/1f6dd3f3-0bf4-4370-9430-b2c3ddb003c7)

**Comment by anton-vidext** [comment]
This workaround doesn't work with en-US-JennyMultilingualV2Neural

<speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="en-US"><voice name="en-US-JennyMultilingualV2Neural">Hola, <prosody volume="0" rate="100">a.</prosody> ¿Qué tal estás?</voice></speak>

It says "a" even if volume is 0

**Comment by anton-vidext** [comment]
This is quite urgent for us @Kerry-LinZhang

Any guess when it will be fixed?

**Comment by Kerry-LinZhang** [comment]
@anton-vidext We are debugging for the case, and I will keep you updated for it here.

**Comment by Kerry-LinZhang** [comment]
Hi @anton-vidext As the tag <prosody volume> works for sentence level as our doc: https://learn.microsoft.com/en-us/azure/ai-services/speech-service/speech-synthesis-markup-voice
volume | Indicates the volume level of the speaking voice. **Volume changes can be applied at the sentence level.**

You can try to use full stop instead of comma after 'Hola' as a workaround.

**Comment by Kerry-LinZhang** [comment]
Currently we have no further plan for it

**Comment by pankopon** [comment]
Closing the issue since no fixes planned, and a workaround has been provided.
