### ISSUE TITLE
Speech to Text profanity_filter "Raw" mode not available? 

### ISSUE THREAD

**Issue by Mirrorzoom** [Azure-Samples/cognitive-services-speech-sdk#1988]
I'm running the sample code in Python for transcribing one blob. Both "Masked" and "Removed" options are working, but "Raw" is considered a bad request.  

If this is by design, can we have the documentation reflect that?

**Comment by chlandsi** [comment]
The value to request no masking of profanity is `None`.

From the docs [here](https://learn.microsoft.com/en-gb/azure/cognitive-services/speech-service/batch-transcription-create?pivots=rest-api#request-configuration-options):

> Accepted values are `None` to disable profanity filtering, `Masked` to replace profanity with asterisks, `Removed` to remove all profanity from the result, or `Tags` to add profanity tags. The default value is `Masked`.

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
