### ISSUE TITLE
Builds for visionOS

### ISSUE THREAD

**Issue by willwade** [Azure-Samples/cognitive-services-speech-sdk#1990]
**Is your feature request related to a problem? Please describe.**
You cant currently use Speech SDK with visionOS 

**Describe the solution you'd like**
We'd love a visionOS target and SDKs for that platform

**Describe alternatives you've considered**
I guess we'd have to figure out how to build it ourselves. 

**Additional context**

**Comment by jhakulin** [comment]
@willwade Thanks for the request. Currently we do not have made support (testing etc.) for visionOS particularly. however you may be able to utilize the C++ native binaries and C++ API to integrate the required functionality using Speech SDK.
Which programming language you are using?

**Comment by willwade** [comment]
Cool. I'm using swift. 

I havent tried it yet - but I do see there is a conversion tool built into MacOS

(from @steventroughtonsmith on mastodon )

> PSA: If you're really stuck compiling your project for visionOS because of iOS-only third-party frameworks you do have a commandline way to ‘convert’ binaries between platforms built right into macOS these days. There may be other platform issues you run into, but this might get you up and running.
> 
> "12" here is visionOS Simulator.
> "11" would be visionOS.
> “1.0” is the minimum deployment target
> “1.0" is the SDK version
> 
> vtool -set-build-version 12 1.0 1.0 -replace -output

**Comment by pankopon** [comment]
@willwade Please confirm if the conversion works.

**Comment by pankopon** [comment]
Internal work item ref. 5423211.

**Comment by pankopon** [comment]
Closing the item as we now have a work item on the backlog and will use that to track this feature request (no ETA). Please open a new issue if support on other topics is needed.

**Comment by curtisshipley** [comment]
Fyi, I was neither able to get vtool to work or the Cocoapod "cocoapods-expert-difficulty" (which tells cocoapod to ignore platform restrictions.) This is a blocking issue for us from using the Cognative Speech SDK on VisionOs.
