### ISSUE TITLE
configuration parameter EnableMiscue not working

### ISSUE THREAD

**Issue by hwanginyeop** [Azure-Samples/cognitive-services-speech-sdk#1995]
**Describe the bug**

To get ErrorType "Omission" or "Insertion" using SpeechSDK, 
I set configuration parameter EnableMiscue as true.

But I can't get ErrorType both.
(even if I set the parameter as "true" or "True", same)

**To Reproduce**
1. 
```javascript
// STEP 1) Execute STT
var speechConfig = SpeechSDK.SpeechConfig.fromSubscription(subscriptionKey, serviceRegion);

speechConfig.speechRecognitionLanguage = "en-US";
var audioConfig = SpeechSDK.AudioConfig.fromWavFileInput(new File([blob], "test.wav"));
recognizer = new SpeechSDK.SpeechRecognizer(speechConfig, audioConfig);

recognizer.recognizeOnceAsync(
    function (result) {       
        // STEP 2) Execute pronunciation assessment
        var pronunciationAssessmentConfig = SpeechSDK.PronunciationAssessmentConfig.fromJSON("{\"referenceText\": \"{SENTENCE FROM STT}\", \"gradingSystem\": \"HundredMark\", \"granularity\": \"Phoneme\", \"EnableMiscue\": true, \"phonemeAlphabet\":\"IPA\", \"nBestPhonemeCount\": 5}");
        pronunciationAssessmentConfig.applyTo(recognizer);
        recognizer.recognizeOnceAsync(function (speechRecognitionResult) {
            var result = speechRecognitionResult.properties.getProperty(SpeechSDK.PropertyId.SpeechServiceResponse_JsonResult);
        });
    }
);
```

**Expected behavior**
Word of ErrorType "Ommission" or "Insertion" must be included in result.

**Version of the Cognitive Services Speech SDK**
```javascript
<script src="https://aka.ms/csspeech/jsbrowserpackageraw"></script>
```

**Platform, Operating System, and Programming Language**
 - OS: iMac (macOS BigSur, version 11.6.1)
 - Hardware: x64,
 - Programming language: PHP
 - Browser: Chrome (Version 114.0.5735.198 (Official Build) (x86_64))

**Additional context**
 - In Speech Studio, ErrorType "Ommission" or "Insertion" Included.

**Comment by glharper** [comment]
@hwanginyeop Thank you for using JS Speech SDK, and writing this issue up. Could you provide your test.wav file so that I can see what's going on?

**Comment by yulin-li** [comment]
cc @yinhew and @wangkenpu

**Comment by wangkenpu** [comment]
Thanks for reporting the issue. We are working on it and will update the progress.

**Comment by wangkenpu** [comment]
Looks like it's a bug for JS SDK. We will fix it soon. You can use the following code to get the "Insertion" and "Omission" tags. @hwanginyeop 

```
var pronunciationAssessmentConfig = SpeechSDK.PronunciationAssessmentConfig.fromJSON("{\"gradingSystem\": \"HundredMark\", \"granularity\": \"Phoneme\", \"phonemeAlphabet\":\"IPA\", \"nBestPhonemeCount\": 5}");
pronunciationAssessmentConfig.referenceText = SENTENCE FROM STT;
pronunciationAssessmentConfig.enableMiscue = true;
```

**Comment by yulin-li** [comment]
should be addressed by https://github.com/microsoft/cognitive-services-speech-sdk-js/pull/695

**Comment by glecaros** [comment]
Closing the issue as https://github.com/microsoft/cognitive-services-speech-sdk-js/pull/695 has already been merged
