### ISSUE TITLE
stop a continuous async recognition immediately

### ISSUE THREAD

**Issue by i-bing** [Azure-Samples/cognitive-services-speech-sdk#1997]
I use StartContinuousRecognitionAsync for start a  recognition ,when call StopContinuousRecognitionAsync().get() sometimes will block 10 secs .  before call  StopContinuousRecognitionAsync,  i already call PushAudioInputStream.Close() to close PushAudioInputStream.

sdk version:  
c++   linux 1.23.0.  

I have search the history issuse like this question ,  https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1388  , the reply said has fixed  in 1.20 .  Is this really fixed?

**Comment by pankopon** [comment]
@i-bing Please update to the current SDK version (1.30.0 as of this writing), do you still see the same issue when using the latest?

**Comment by pankopon** [comment]
Closed since no further updates received, please open a new issue if more support is needed. (Be sure to use the latest Speech SDK release.)
