### ISSUE TITLE
Speakers being separated into new arrays if they pause speaking

### ISSUE THREAD

**Issue by cspbs** [Azure-Samples/cognitive-services-speech-sdk#2001]
In the API, we're currently parsing the JSON response and populating a file with the transcription, however, if a person is speaking and pauses then this is added into a new array. This issue doesn't seem to happen on the Azure Speech studio with the same audio.

This is causing the following when we're parsing the data. I'd expect it to stay under the first speaker 1 until speaker 2 speaks. 

Speaker 1

Some text

Speaker 1

Some more text

Speaker 2

**Comment by pankopon** [comment]
@cspbs What is the API you are using? Please provide more context and detail (incl. programming language, platform, SDK version).

**Comment by pankopon** [comment]
Closed since no details provided. Please open a new issue (Bug report or Feature request - be sure to fill in the template) if support is still needed.
