### ISSUE TITLE
Android will report an error after performing multiple recognition.  libOpenSLES              E  Too many objects       Leaving Engine::CreateAudioRecorder (SL_RESULT_MEMORY_FAILURE)

### ISSUE THREAD

**Issue by luojt** [Azure-Samples/cognitive-services-speech-sdk#2007]
When I use microphone recognition, Android will not be able to continue to recognize after continuous recognition exceeds a certain number of times, and the error content is as follows:
`libOpenSLES              E  Too many objects`
`Leaving Engine::CreateAudioRecorder (SL_RESULT_MEMORY_FAILURE)`
**Even if I use the close function, it still doesn't work.**
SDK failed to release OpenSL ES-related resources, this is a bad experience, please fix the bug immediately

`com.microsoft.cognitiveservices.speech:client-sdk:1.30.0`

**Comment by amelons** [comment]
It happened to me, too, and I still can't work it out

**Comment by pankopon** [comment]
@luojt @amelons Thanks for reporting the issue. Do you get the same error with earlier Speech SDK releases or is 1.30.0 the first one you've tried with?

**Comment by pankopon** [comment]
@luojt @amelons We've tested continuous recognition of up to 100 phrases without errors, using https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/java/android/sdkdemo (scenario "Recognize continuously") on Google Pixel 7 with Android 13.

Can you reproduce the error with the linked sample? If yes, how many phrases does it take before the error occurs? What is the device you are using and the Android version? Also please provide a log file of a run where the error occurs, see https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging#android for instructions.

**Comment by luojt** [comment]
> 感谢您报告问题。在早期的语音 SDK 版本中是否遇到相同的错误，或者 1.30.0 是你尝试过的第一个版本？

It can be repeated in any version of Android, and the number of times the recognition varies according to the device, and versions before 1.30.0 can also appear.

**Comment by luojt** [comment]
> 我们已经在装有 Android 100 的 Google Pixel 7 上使用 https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/java/android/sdkdemo（场景“连续识别”）测试了多达 13 个短语的连续识别功能，没有错误。
> 
> 您可以使用链接的示例重现错误吗？如果是，在发生错误之前需要多少个短语？您使用的设备和安卓版本是什么？另请提供发生错误的运行的日志文件，有关说明，请参阅 https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging#android。

Not continuous identification, but need to disconnect the identification, open the identification, loop several times can appear this error: ```
libOpenSLES E Too many objects
Leaving Engine::CreateAudioRecorder (SL_RESULT_MEMORY_FAILURE)
```

**Comment by amelons** [comment]
> @luojt @amelons We've tested continuous recognition of up to 100 phrases without errors, using https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/java/android/sdkdemo (scenario "Recognize continuously") on Google Pixel 7 with Android 13.
> 
> Can you reproduce the error with the linked sample? If yes, how many phrases does it take before the error occurs? What is the device you are using and the Android version? Also please provide a log file of a run where the error occurs, see https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging#android for instructions.

Version 1.29.0 also has this error, which is caused by the following lines of code, which occurs when the text of speech recognition is frequently called multiple times:

`speechConfig = SpeechConfig.fromSubscription(speechSubscriptionKey,serviceRegion)
        speechConfig?.speechRecognitionLanguage = "zh-CN"
        voiceSpeechRecognizer = SpeechRecognizer(speechConfig)`

**Comment by luojt** [comment]
> > @luojt @amelons We've tested continuous recognition of up to 100 phrases without errors, using https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/java/android/sdkdemo (scenario "Recognize continuously") on Google Pixel 7 with Android 13.
> > Can you reproduce the error with the linked sample? If yes, how many phrases does it take before the error occurs? What is the device you are using and the Android version? Also please provide a log file of a run where the error occurs, see https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging#android for instructions.
> 
> Version 1.29.0 also has this error, which is caused by the following lines of code, which occurs when the text of speech recognition is frequently called multiple times:
> 
> `speechConfig = SpeechConfig.fromSubscription(speechSubscriptionKey,serviceRegion) speechConfig?.speechRecognitionLanguage = "zh-CN" voiceSpeechRecognizer = SpeechRecognizer(speechConfig)`

You can customize the recording.

**Comment by pankopon** [comment]
@luojt @amelons The first post https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2007#issue-1798219566 said

> not be able to continue to recognize after **continuous recognition** exceeds a certain number of times

(Speech SDK continuous recognition = `startContinuousRecognitionAsync`)

but then it was added in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2007#issuecomment-1631718124

> Not continuous identification, but need to disconnect the identification, open the identification, loop several times

Presuming "identification" = "recognition", this is ambiguous. (Otherwise, even more so.)

So are you doing
```
create recognizer
recognizer.startContinuousRecognitionAsync
get result1
get result2
...
get resultN
recognizer.stopContinuousRecognitionAsync
```
or
```
create recognizer
recognizer.startContinuousRecognitionAsync
get result1
recognizer.stopContinuousRecognitionAsync
recognizer.startContinuousRecognitionAsync
get result2
recognizer.stopContinuousRecognitionAsync
...
recognizer.startContinuousRecognitionAsync
get resultN
recognizer.stopContinuousRecognitionAsync
```
or
```
create recognizer1
recognizer1.startContinuousRecognitionAsync
get result1
recognizer1.stopContinuousRecognitionAsync
create recognizer2
recognizer2.startContinuousRecognitionAsync
get result2
recognizer2.stopContinuousRecognitionAsync
...
create recognizerN
recognizerN.startContinuousRecognitionAsync
get resultN
recognizerN.stopContinuousRecognitionAsync
```
or are you calling `recognizeOnceAsync` instead of `startContinuousRecognitionAsync`
or is your code something completely different?

**Please describe your code** (see above for examples). Try to write as clearly as possible. 
Also please provide a **log file** (that was already requested in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2007#issuecomment-1631541853) where the error occurs, see https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging#android for instructions.
Otherwise it will be difficult to proceed - there hasn't been any other report of this kind.

**Comment by luojt** [comment]
> @luojt @amelons The first post [#2007 (comment)](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2007#issue-1798219566) said
> 
> > not be able to continue to recognize after **continuous recognition** exceeds a certain number of times
> 
> (Speech SDK continuous recognition = `startContinuousRecognitionAsync`)
> 
> but then it was added in [#2007 (comment)](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2007#issuecomment-1631718124)
> 
> > Not continuous identification, but need to disconnect the identification, open the identification, loop several times
> 
> Presuming "identification" = "recognition", this is ambiguous. (Otherwise, even more so.)
> 
> So are you doing
> 
> ```
> create recognizer
> recognizer.startContinuousRecognitionAsync
> get result1
> get result2
> ...
> get resultN
> recognizer.stopContinuousRecognitionAsync
> ```
> 
> or
> 
> ```
> create recognizer
> recognizer.startContinuousRecognitionAsync
> get result1
> recognizer.stopContinuousRecognitionAsync
> recognizer.startContinuousRecognitionAsync
> get result2
> recognizer.stopContinuousRecognitionAsync
> ...
> recognizer.startContinuousRecognitionAsync
> get resultN
> recognizer.stopContinuousRecognitionAsync
> ```
> 
> or
> 
> ```
> create recognizer1
> recognizer1.startContinuousRecognitionAsync
> get result1
> recognizer1.stopContinuousRecognitionAsync
> create recognizer2
> recognizer2.startContinuousRecognitionAsync
> get result2
> recognizer2.stopContinuousRecognitionAsync
> ...
> create recognizerN
> recognizerN.startContinuousRecognitionAsync
> get resultN
> recognizerN.stopContinuousRecognitionAsync
> ```
> 
> or are you calling instead of or is your code something completely different?`recognizeOnceAsync``startContinuousRecognitionAsync`
> 
> **Please describe your code** (see above for examples). Try to write as clearly as possible. Also please provide a **log file** (that was already requested in [#2007 (comment)](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2007#issuecomment-1631541853)) where the error occurs, see https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging#android for instructions. Otherwise it will be difficult to proceed - there hasn't been any other report of this kind.

```
create recognizer
recognizer.startContinuousRecognitionAsync
get result1 =“”
get result2=“”
get result3=“”
get result4=“”
get result5=“”
...
get resultN=“hello,world”
recognizer.stopContinuousRecognitionAsync
```

**Comment by pankopon** [comment]
@luojt This case is what we've tested without errors as noted in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2007#issuecomment-1631541853. So it's possible the issue depends on vendor specific Android HW and/or OS configuration. To proceed, we would need more information (incl. **logs** that have been requested several times by now) from you.

**Comment by pankopon** [comment]
Closed since not reproduced and no logs. If you get a log file, please create a new Bug report (be sure to fill in the template) and attach the log.
