### ISSUE TITLE
Speech SDK Not Compiling on "My Mac (Mac Catalyst)" Run Destination

### ISSUE THREAD

**Issue by b-lester** [Azure-Samples/cognitive-services-speech-sdk#2013]
**Describe the bug**
When the "My Mac (Mac Catalyst)" run destination is selected, compilation fails with error, No such module 'MicrosoftCognitiveServicesSpeech'. However when the "My Mac (Designed for iPad)" destination is selected, compilation succeeds.

**To Reproduce**
1. Select "My Mac (Mac Catalyst)" destination and build

**Expected behavior**
I expect the project to compile successfully 

**Version of the Cognitive Services Speech SDK**
1.30.0

**Platform, Operating System, and Programming Language**
Project is compatible with iOS and Mac Catalyst

**Additional context**
Compilation fails with error, "No such module 'MicrosoftCognitiveServicesSpeech'"
NOTE: make sure to add the Mac (Mac Catalyst) run destination under the target's, "General" tab.

**Comment by pankopon** [comment]
@jhakulin Please check.

**Comment by b-lester** [comment]
I was able to get it to compile by putting this in my bridging header:
`#import <MicrosoftCognitiveServicesSpeech/SPXSpeechAPI.h>`

**Comment by pankopon** [comment]
Closed as resolved.

**Comment by b-lester** [comment]
@pankopon Upon further investigation, perhaps this should not be closed because the problem still persists when linking the library manually. The solution above only works with a CocoaPods integration. I would prefer not to add CocoaPods to my project if I don't have to.
