### ISSUE TITLE
WordBoundary Events Missing for Words with Apostrophe and Alias 

### ISSUE THREAD

**Issue by b-lester** [Azure-Samples/cognitive-services-speech-sdk#2015]
**Describe the bug**
WordBoundary Events are missing when the SSML has words with an apostrophe. Also, when an alias is present in the SSML, there is no word boundary event for the substituted word. For example please consider the following SSML:

`<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="en-US"><voice name="en-US-AmberNeural">Hello. I&apos;m the king of <sub alias="New York">Fantasy Land</sub>.</voice></speak>`

The following word boundary events are generated where each line represents time in seconds, start, end and text:

```
50.0 114 119 Hello
600.0 119 120 .
1687.5 130 133 the
1800.0 134 138 king
2075.0 139 141 of
2825.0 182 183 .
```

As you can see, an event for "I'm" is missing. Also the alias phrase is missing.

**To Reproduce**
Use the above example SSML and observe word boundary events for "I'm" and the alias are missing.

**Expected behavior**
Correct word boundary events to occur for every word spoken.

**Version of the Cognitive Services Speech SDK**
1.30

**Platform, Operating System, and Programming Language**
 MacOS/Swift

**Comment by pankopon** [comment]
@yulin-li Please check this one, too.

**Comment by yulin-li** [comment]
Hi, this is a known issue. We don't have an ETA for this bug but you can replace `I&apos;m` with `I'm` as a workaround, i.e. the `'` character should not be escaped.

**Comment by Kerry-LinZhang** [comment]
Tracked as long-term fix, we have put it into backlog for future plan. Will continue follow up with it.

**Comment by trrwilson** [comment]
Given there's a workaround available, I'm going to close this issue. If there are further concerns that the preprocessing can't address, please reopen or file a new issue referencing this one.

@yulin-li / @Kerry-LinZhang  -- please ensure that the internal work items crosslink to this GH issue so we can report here (even closed) once the unretouched capability is available. Thank you!

**Comment by b-lester** [comment]
This shouldn't be closed. There is a supposed workaround for the apostrophes issue, but aliases are still ignored by the word highlighting. This behavior is incorrect and should be fixed.

**Comment by Kerry-LinZhang** [comment]
Yes, we will track it as a backlog item.
