### ISSUE TITLE
TTS: incorrect WordBoundary information in specific cases ("Aww")

### ISSUE THREAD

**Issue by Trunksome** [Azure-Samples/cognitive-services-speech-sdk#2016]
**Describe the bug**
I subscribe to the [WordBoundary event](https://learn.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechsynthesizer.wordboundary?view=azure-dotnet&viewFallbackFrom=netframework-4.6.2) of the SpeechSynthesizer to get information about when the words of the text are spoken; I then highlight those words at the right time in the UI. So far so good. But i noticed that with some voices and texts, the information returned by the event do not correlate correctly to the input text.

 I have noticed the WordBoundaries are incorrect every time a neural voice has a "special pronunciation" of a word, like "Aww" in English. The voice does a fine job of speaking this word, but all WordBoundary information seems messed up.

I noticed this problem in other languages and voices too; and every time I encountered the problem, there was one of these "special intonations" in the synthesis; I don't know how to properly call them, but I remember it happening with a "Hm" as well.

**To Reproduce**
1. Use "en-US-SaraNeural" 
2. Synthesize text "Aww, thank you so much! You're pretty cool yourself. So, what else do you like to do besides trying new foods?"
3. Look at results returned by the WordBoundary event 

**Expected behavior**
The word boundaries described in the results should match the input text, to give clues about which word is spoken at what time.
In this case though, it doesn't seem to relate properly.

This is what I found:

<img width="663" alt="incorrect_results" src="https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/16858868/9abc2c64-95e6-47bd-a2d0-cb666ab811c3">

**Version of the Cognitive Services Speech SDK**
Speech SDK 1.24.2

**Platform, Operating System, and Programming Language**
 - OS: Windows, Android, iOS
 - Programming language: C#
 - Unity3D

**Comment by yulin-li** [comment]
Thanks for reporting this, I can reproduce this issue and will ask the service guy to check.

**Comment by Nanana2023** [comment]
I am investigating the issue.

**Comment by Kerry-LinZhang** [comment]
Targeting ETA 8/4 for the fix

**Comment by Kerry-LinZhang** [comment]
ETA delayed, we are under reevaluate for the fix release time

**Comment by glecaros** [comment]
@Kerry-LinZhang is there any updates on this?

**Comment by pankopon** [comment]
@Kerry-LinZhang What is the latest ETA for the fix?

**Comment by Kerry-LinZhang** [comment]
@Nanana2023 could you please provide fix plan for this issue?

**Comment by Kerry-LinZhang** [comment]
Hi @Trunksome we have already fixed the issue last year, would you please try again. If there is still any question, please feel free to let us know.

**Comment by pankopon** [comment]
Closed as fixed.
