### ISSUE TITLE
MacOS Min OS Version bumped 12

### ISSUE THREAD

**Issue by Michael-Picerno** [Azure-Samples/cognitive-services-speech-sdk#2017]
**Describe the bug**
It seems with 13.1 the minimum supported version of Mac was bumped to 12. 

**To Reproduce**
Fails to load on MacOS 11 or 10.15

**Expected behavior**
To load on 10.15 and 11

**Version of the Cognitive Services Speech SDK**
13.1

**Platform, Operating System, and Programming Language**
Intel based macs below MacOS 12 and above 10.14

**Additional context**
Inspecting the dylib I'm getting the version bump but not on any forward facing documentation that I can find on github or the Speech SDK release notes. 

otool -l libMicrosoft.CognitiveServices.Speech.core.dylib | grep -E -A4 '(LC_VERSION_MIN_MACOSX|LC_BUILD_VERSION)' | grep -B1 sdk
    minos 12.0
      sdk 13.1
--
    minos 12.0
      sdk 13.1

Was this just rebuilt wrong or did I miss something that the min supported version is now 12+?

**Comment by jpalvarezl** [comment]
Thank you for opening this issue. I will investigate and get back to you as soon as I can regarding this.

**Comment by jhakulin** [comment]
@Michael-Picerno Thanks for the report! We do set minimum deployment version to 10.14 for x64 Mac builds and 11.0 for Mac ARM64 builds, however there seems to be an issue with the toolchain file that ignores the setting on Mac! I am working on to fix it.

**Comment by jhakulin** [comment]
@Michael-Picerno Target is to fix the issue in 1.31.0 Speech SDK release coming at the beginning of August 2023.

**Comment by jhakulin** [comment]
closing the issue as fix delivered in 1.31.0
