### ISSUE TITLE
python :: speech :: keyword_recognition

### ISSUE THREAD

**Issue by madkote** [Azure-Samples/cognitive-services-speech-sdk#202]
Has anyone tried?
I was looking at cognitive services and was not able to find a place where I can create keyword recognition model..
* should it be stored locally?
* or is at also an endpoint where speech is sent permanently?

thx!

**Comment by wolfma61** [comment]
This is currently only supported in the Device SDK ... 
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-devices-sdk-qsg

sorry for the trouble ...

Wolfgang

**Comment by madkote** [comment]
@wolfma61 thx for reply.

so I would not be able to use it with python or/and at any other device then described in the url above? E.g. I do arduino dev and would like to use keyword recognition...  additionally, as I wrote, there is no cris service for custom keywords.

Means, is there a general description how to implement keyword recognition with cris / azure?

**Comment by wolfma61** [comment]
yes, sorry - at the current time keword recognition (like 'hey cortana') is only available through the device sdk (the speech sdk is a subset of the device sdk, the device sdk is tuned for usage of kws/speech/device-audio).

We are evaluating other options, but nothing ready to announce 

Wolfgang

**Comment by wolfma61** [comment]
closing

**Comment by baldesco** [comment]
This may be helpful:

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-devices-sdk-create-kws
