### ISSUE TITLE
Unable to contact server. StatusCode: 1006, undefined Reason:  getaddrinfo ENOTFOUND undefined.tts.speech.microsoft.com

### ISSUE THREAD

**Issue by jrichardsz** [Azure-Samples/cognitive-services-speech-sdk#2020]
**Describe the bug**

I can't use my custom url to try the speech to text nodejs sample: 
```
sdk.SpeechConfig.fromEndpoint(url, subscriptionKey);
```

**To Reproduce**

1. download the sample https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/javascript/node/text-to-speech
2. npm install
3. set the url and subcription key

![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/11056031/d9c35b95-8efb-4455-b5f3-5a5084c71bd7)

4. node index.js
5. I got this error after enter the word

```
Type some text that you want to speak...
> Hello
Now synthesizing to: YourAudioFile.wav
Speech synthesis canceled, Unable to contact server. StatusCode: 1006, undefined Reason:  getaddrinfo ENOTFOUND undefined.tts.speech.microsoft.com
Did you update the subscription info?
```

**Expected behavior**

Get the wav file

**Attempts**

- If I use the default `fromSubscription` method in which the url is not required, the wav is created

**Version of the Cognitive Services Speech SDK**

` "microsoft-cognitiveservices-speech-sdk": "^1.30.0",`

**Platform, Operating System, and Programming Language**
 - OS: Linux 22
 - Hardware - x64
 - Programming language: JavaScript

**Comment by jpalvarezl** [comment]
Thank you for opening an issue. I am gathering more information to see how we can best assist. On the meantime, I would wholeheartedly recommend not posting subscription information publicly.

**Comment by glharper** [comment]
@jrichardsz I believe your original comment will be edited to remove your subscription info, but you don't appear to be setting the subscription key properly, as the image appeared to show a subscription id, not a key. See [here](https://learn.microsoft.com/en-us/azure/ai-services/multi-service-resource?pivots=azportal&tabs=windows#get-the-keys-for-your-resource) for how to find your subscription key.

**Comment by jrichardsz** [comment]
Thank you so much. 

Sensitive values ​​had already been obfuscated using an uuid generator before posting.

I will share a runnable sample.
