### ISSUE TITLE
continuous_recognition works in .ipynb notebook but not in .py script... session gets cancelled

### ISSUE THREAD

**Issue by HerrDoctorPep** [Azure-Samples/cognitive-services-speech-sdk#2022]
Python method based on MS sample code for continuous recognition from wav file works when called in an ipython notebook.
```
SESSION STARTED: SessionEventArgs(session_id=05af48cc9dba463d8a696c36011c242e)
RECOGNIZING: SpeechRecognitionEventArgs(session_id=05af48cc9dba463d8a696c36011c242e, result=SpeechRecognitionResult(result_id=fa3acba6204f472f9a448d0975e4d629, text="listen a minute", reason=ResultReason.RecognizingSpeech))
RECOGNIZING: SpeechRecognitionEventArgs(session_id=05af48cc9dba463d8a696c36011c242e, result=SpeechRecognitionResult(result_id=3f11c3cbaed04d31ac989489dba6df40, text="listenaminute.com", reason=ResultReason.RecognizingSpeech))
RECOGNIZED: SpeechRecognitionEventArgs(session_id=05af48cc9dba463d8a696c36011c242e, result=SpeechRecognitionResult(result_id=d495f67e3a434e84b57c6dd85b3f465c, text="Listenaminute.com.", reason=ResultReason.RecognizedSpeech))
```

Etc. This is how it should be...

The very same method, when called in a python script from command line leads to cancelled session
```
SESSION STARTED: SessionEventArgs(session_id=06835b1e6e4648eebd78f58bc0c2020f)
CANCELED SpeechRecognitionCanceledEventArgs(session_id=06835b1e6e4648eebd78f58bc0c2020f, result=SpeechRecognitionResult(result_id=b1a7c21f250142ea854110b82aa60105, text="", reason=ResultReason.Canceled))
```
### The script `speech2text.py` with the relevant method `make_transcript(wav_file)`:
https://github.com/HerrDoctorPep/speech2text/blob/feature_script/speech2text.py
Calling the script from the command line with `python -m speech2text.py` leads to cancelled session.

### The notebook in which the same method is called:
https://github.com/HerrDoctorPep/speech2text/blob/feature_script/notebooks/try_stuff.ipynb
The cells in the notebook lead to a successful transcription of the full `.wav` file.

**Comment by HerrDoctorPep** [comment]
For testing I took `mp3` from [here](https://www.listenaminute.com/a/actors.html) and converted it to `.wav` using `pydub`.

**Comment by ralph-msft** [comment]
To be able to properly diagnose the cause of your issue, could you please share the SDK logs? Instructions to enable logging can be found here: https://learn.microsoft.com/azure/ai-services/speech-service/how-to-use-logging

**Comment by HerrDoctorPep** [comment]
@ralph-msft Apologies for missing this. Please find below the logs of both working (ipynb) and failing (py) versions.
[speechsdk.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/12264346/speechsdk.log)
[speechsdk_py.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/12264356/speechsdk_py.log)

**Comment by ralph-msft** [comment]
From the logs the SDK is failing to load the OpenSSL 1.1.1 libraries:
`[669462]: 64ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  shim_openssl.c:51 libssl could not be loaded`

I can also see from the logs that you are running Ubuntu 22.04 which has moved to version 3.X of the the OpenSSL libraries. As a workaround you can install the 1.1.1 version of the library as follows:
```bash
wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
```
