### ISSUE TITLE
Transciption not returning any results

### ISSUE THREAD

**Issue by JennyPre** [Azure-Samples/cognitive-services-speech-sdk#2023]
**Describe the bug**
I cant the the example from https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/transcription_sample.py running.

I did some adjustemts so the code looks like this (using python 3.10, eastus region)

It returns for different .wav files different error messages.

**To Reproduce**
1. RUN the code from https://learn.microsoft.com/en-us/answers/questions/1333859/speech-to-text-does-not-return-text?comment=question#newest-question-comment (python 3.10) with region eastus
2.  I used different .wav files, e.g. from this site https://www.uclass.psychol.ucl.ac.uk/Release2/Conversation/AudioOnly/sfs/. I also adjusted the audio format for some files, but still didn't get it running

**Expected behavior**
returns a transcript of the audiofile, with different speakers being recognized 

**Version of the Cognitive Services Speech SDK**
azure_cognitiveservices_speech-1.30.0.

**Platform, Operating System, and Programming Language**
 - OS: Windows 11 (22H2)
 -  Hardware - 64-Bit-Betriebssystem, x64-basierter Prozessor
 - Programming language: Python
 - Chrome

[log_transcription_take3_F_0111_9y6m_1.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/12142798/log_transcription_take3_F_0111_9y6m_1.log)
[log_transcription_take3_conv_S_Jost_14-07-2023_9_32_13.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/12142818/log_transcription_take3_conv_S_Jost_14-07-2023_9_32_13.log)

**Comment by glharper** [comment]
The logs show this line: 
[6062]: 2358ms SPX_TRACE_ERROR:  usp_reco_engine_adapter.cpp:1934 Response: On Error: Code:7, Message: Connection was closed by the remote host. 
Error code: 1013. Error details: Unable to service the request due to resource constraints. Please try again later..

I'll ask our service contact about this 1013 websocket error.

**Comment by glharper** [comment]
@JennyPre Our service contact tried converting the sfs files and got an error. Could you repro this with actual wav files, instead of converted sfs files?

**Comment by jhakulin** [comment]
@JennyPre Could you please let us know if you still have the issue, the issue you pointed out could be occasional in nature. I will set this pending close state and issue will be closed if there are no further information/help needed.
