### ISSUE TITLE
Unity plugin should include a working visemes 3d character demo 

### ISSUE THREAD

**Issue by yosun** [Azure-Samples/cognitive-services-speech-sdk#2033]
https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-speech-synthesis-viseme?tabs=3dblendshapes&pivots=programming-language-csharp

**Comment by glharper** [comment]
@yosun Thank you for using Speech SDK, and for writing this issue up. How detailed of a demo would accelerate learning our viseme features in Unity? Could you point to a great example demo that another SDK includes for their Unity plugin?

**Comment by jhakulin** [comment]
@yosun Are you asking a new sample for Unity which contains visemes 3d feature or are you hoping that Unity Speech SDK package would contain some demos inside?
