### ISSUE TITLE
SPXERR_MIC_ERROR in MAUI Application while using Microsoft.CognitiveServices.Speech 1.30.0

### ISSUE THREAD

**Issue by MithileshSwarge** [Azure-Samples/cognitive-services-speech-sdk#2034]
**Describe the bug**
I am creating simple MAUI application using Microsoft.CognitiveServices.Speech service version 1.30.0. I'm getting below error message whenever RecognizeOnceAsync is called.
Error - 0x15 (SPXERR_MIC_ERROR) SessionId: a374a9ab13134cb281cbfe8b4d50e50a

**To Reproduce**
1. Create a MAUI Application 
2. Add Microsoft.CognitiveServices.Speech Nuget version .130.0
3. Add Xamarin.Essentials Nuget version 1.7.7
4. Add Android Emulator - Pixel 5 - API 33 (Android 13)
5. On button click call RecognizeOnceAsync 

**Expected behavior**
Same code is working fine in console application and it is returning Speech to Text as expected

**Version of the Cognitive Services Speech SDK**
I'm using 1.30.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 11
 - Hardware - x64
 - Programming language: C# MAUI

**Additional context**
Using below code : 
private async void TranscribeClicked(object sender, EventArgs e)
        {
            bool isMicrophoneEnabled = await CheckMicrophonePermissionAsync();
            if (!isMicrophoneEnabled)
            {
                await DisplayAlert("Need Permission", "Grant access to microphone", "OK");
                return;
            }

            var audioConfig = AudioConfig.FromDefaultMicrophoneInput();
            string subscriptionKey = "subscriptionKey ";
            string serviceRegion = "serviceRegion ";

            var config = SpeechConfig.FromSubscription(subscriptionKey, serviceRegion);
            config.SpeechSynthesisVoiceName = "en-US-AriaNeural";

            using (var recognizer = new SpeechRecognizer(config,audioConfig))
            {
                var result = await recognizer.RecognizeOnceAsync();

                if (result.Reason == ResultReason.RecognizedSpeech)
                {
                    await DisplayAlert("Transcription", $"Recognized Text: {result.Text}", "OK");
                }
                else if (result.Reason == ResultReason.NoMatch)
                {
                    await DisplayAlert("Transcription", "NOMATCH: Speech could not be recognized.", "OK");
                }
                else if (result.Reason == ResultReason.Canceled)
                {
                    var cancellation = CancellationDetails.FromResult(result);
                    await DisplayAlert("Transcription", $"CancellationReason: {cancellation.Reason}", "OK");
                    if (cancellation.Reason == CancellationReason.Error)
                    {
                        await DisplayAlert("Transcription", $"ErrorDetails: {cancellation.ErrorDetails}", "OK");
                        
                    }
                }
            }
        }

        private Task<bool> CheckMicrophonePermissionAsync()
        {
            return Task.FromResult(true);
        }

**Comment by jhakulin** [comment]
@MithileshSwarge Thanks for the report. We have seen similar issues with API 33, however those have end up being more general problems with Android emulator than Speech SDK. Could you please check if built-in Google Voice search work in the emulator? That uses microphone as well.

**Comment by jhakulin** [comment]
Closing the issue, let us know if you experience the issue specific to speech sdk and we can take a look.
