### ISSUE TITLE
I got an error when deploying the ARM template which I downloaded and created a new deployment

### ISSUE THREAD

**Issue by Prasadnair** [Azure-Samples/cognitive-services-speech-sdk#2038]
**Describe the bug**
The requested resource FetchTranscription does not exist

{
  "code": "DeploymentFailed",
  "target": "/subscriptions/08ab2d96-9457-4d92-8ed4-d95f22337a7e/resourceGroups/PRAIGroup/providers/Microsoft.Resources/deployments/Microsoft.Template-20230804130701",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "code": "NotFound",
      "message": "The requested resource FetchTranscription does not exist."
    }
  ]
}
**To Reproduce**
1. downloaded the file from https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json
2. create a custom deployment using this json. and while deploying i got the above error.

**Expected behavior**

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - please be specific
 - Hardware - x64, x86, ARM, ...
 - Programming language: C#, C++, Java, JavaScript, Objective-C, Python
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific

**Additional context**
 - Error messages, stack trace, sample code to reproduce the issue, ...
 - Please provide full Speech SDK Log, as per the instructions [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging)?
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by glecaros** [comment]
@HenryvanderVegte can you please take a look at this issue?

**Comment by HenryvanderVegte** [comment]
Hi @Prasadnair ,

sorry for the (very) late response.
I completed a PR which should fix the issue: https://github.com/Azure-Samples/cognitive-services-speech-sdk/pull/2055 

Could you try and deploy the ingestion client with my update and check if it is resolved for you as well?

Thanks!

**Comment by Prasadnair** [comment]
Hello @HenryvanderVegte , I apologize for the late response. I will try this and keep you posted the feedback

**Comment by brandom-msft** [comment]
Closing with no new activity.
