### ISSUE TITLE
TTS: Unclear / Inconsistent behavior of nesting prosody

### ISSUE THREAD

**Issue by lukas-parloa** [Azure-Samples/cognitive-services-speech-sdk#2039]
## Request

_this is a copy of https://github.com/Azure-Samples/Cognitive-Speech-TTS/issues/295 since I got no response there, I thought that repo was not in use anymore_

Need clarification and / or documentation on expected TTS behavior with `prosody` tag, applying different settings to different parts of a prompt.

Nesting prosody with different combinations seems to apply the properties to a complete prompt (rate & pitch), while in other cases it seems to work as expected (rate & contour).

If you could clarify and explain what the expected behavior and recommended usage is, it would help produce correct SSML from our application in various scenarios.

## Context

The goal is to have a faster/slower voice, and still allow prosody adjustments on individual words or sentences.

According to the documentation, `prosody` is a valid tag inside of `prosody`: https://learn.microsoft.com/en-us/azure/ai-services/speech-service/speech-synthesis-markup-voice#adjust-prosody

All tests are performed in the Speech Studio, the actual use case is an application via the JavaScript SDK.

_Flattening and merging prosody tags is something we would ideally like to avoid to save the effort_

## Case 1: Rate & Pitch 

_extreme values are used for demonstration purposes_

**Prompt description**

* Say "Hello. How are you doing?" in English
* Applying -20% rate
* "How are you doing?" should have a pitch "+30%"

### Test case

Using the following SSML, we can test

1. Nesting the pitch change inside of the rate tag (manually created)
2. Using the Speech Studio UI, a flat prosody structure is produced 

```
<speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="en-US"><voice name="en-US-JennyNeural"><bookmark mark="nested" />
<prosody rate="-20.00%">Hello. <prosody pitch="+30%">How are you doing?</prosody></prosody>
<bookmark mark="flat" />
<prosody rate="-20.00%">Hello. </prosody><prosody rate="-20.00%" pitch="+30.00%">How are you doing?</prosody>
</voice></speak>
```

### Result

* The nested SSML applies the pitch change to the full paragraph.
* The flat SSML applies the rate correctly only to the wrapped sentence

### Expectation

Both produce the same result.

## Case 2: Rate & Contour

**Prompt description**

* Applying -20% rate
* Custom contour on "Verstanden."

### Test case

Using the following SSML, we can test

1. Original pronunciation without contour (baseline)
2. Nesting the cntour change inside of the rate tag (manually created)
3. Using the Speech Studio UI, a flat prosody structure is produced 

```
<speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="de-DE"><voice name="de-DE-KatjaNeural">
<bookmark mark="no contour" />
<prosody pitch="-20.00%">Alles klar was geht ab bei dir. Verstanden.</prosody>
<bookmark mark="nested" />
<prosody pitch="-20.00%">Alles klar was geht ab bei dir. <prosody contour="(8%, +85%) (47%, -10%) (100%, -18%)">Verstanden.</prosody></prosody>
<bookmark mark="flat" />
<prosody pitch="-20.00%">Alles klar was geht ab bei dir. </prosody><prosody pitch="-20.00%" contour="(8%, +85%) (47%, -10%) (100%, -18%)">Verstanden.</prosody></voice></speak>
```

### Result

Both contour variations seem to produce the same results

<img width="914" alt="image" src="https://github.com/Azure-Samples/Cognitive-Speech-TTS/assets/123259762/b8852c15-578c-4e4e-8b5f-72c9ed8d4979">

**Comment by yulin-li** [comment]
@lukas-parloa thank you for using Azure Speech and raise this issue.

@Kerry-LinZhang could you help to triage?

**Comment by Kerry-LinZhang** [comment]
Thanks for the feedback,

let me make it clear:
1. both pitch and rate tag are expected to be applied to the full paragraph, right? @lukas-parloa 
2. for the inconsistent behavior of nesting prosody reported in 【Case 2: Rate & Contour】 @newhillchan could you please take a look

**Comment by Kerry-LinZhang** [comment]
Hi @lukas-parloa issue is under investigation, I will keep you updated for the progress

**Comment by Kerry-LinZhang** [comment]
investigation ETA 9/15

**Comment by Kerry-LinZhang** [comment]
Hi @lukas-parloa it seems we cannot repro it now, would you please double confirm it, and if you can still repro the issue, please send us again the SSML, thanks a lot.

**Comment by Kerry-LinZhang** [comment]
Well received, keep tracking on it, will keep you updated for it

**Comment by Kerry-LinZhang** [comment]
Debug ongoing, these two tags should have the same behavior.

**Comment by Kerry-LinZhang** [comment]
Tracking with owner for it

**Comment by pankopon** [comment]
@Kerry-LinZhang Any update by now?

**Comment by pankopon** [comment]
Closing as unsupported because of no update since November. @Kerry-LinZhang @yulin-li FYI
