### ISSUE TITLE
iOS (Swift 3)'MicrosoftCognitiveServicesSpeech/SPXSpeechApi.h' file not found

### ISSUE THREAD

**Issue by Vliosgep** [Azure-Samples/cognitive-services-speech-sdk#204]
Hello, 
I dowloaded latest version of the SDK , the Xcode project does not open and showed up pop up for incompatible project version, then I checked older released which suppose to be compatible with Xcode below than 9.3 , but it had same issue. So I made change in project files  for compatibility version and object version to support from Xcode 8.0 and beyond. Now file opened but it shows above error.Suggest what I can do , it show framework in red which is deleted mode, How can I find framework file?

**Comment by chlandsi** [comment]
Hi, please follow the instructions in the quickstart articles for [iOS](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-objective-c-macos) or [macOS](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-objective-c-macos), in particular on where to put the framework in relation to the project file. The SDK is compatible with iOS 9.3 and later; we tested the quickstart projects on Xcode 11.4 and later. Thanks!

**Comment by Vliosgep** [comment]
I need to work it on Xcode 9.2.

**Comment by Vliosgep** [comment]
Where I can find this framework "MicrosoftCognitiveServicesSpeech"?

**Comment by chlandsi** [comment]
You can download the iOS framework [here](https://aka.ms/csspeech/iosbinary).

**Comment by Vliosgep** [comment]
This solution worked, I was able to get it work in Objective C with lower version if Xcode, but now when I try to use the same files in swift project via bridging header , it shows the same error. How I can make it run with Swift?

**Comment by chlandsi** [comment]
The SDK does not officially support Swift (yet). However, some users have reported success with using the autogenerated headers for Swift applications in recent Xcode versions. Unfortunately, we can't currently give support for older Xcode versions. Please excuse the inconvenience.

**Comment by Vliosgep** [comment]
autogenerated headers means?

**Comment by chlandsi** [comment]
I was referring to the bridging headers, which are autogenerated by Xcode.

**Comment by Vliosgep** [comment]
Its throwing error there itself, and this is why I am seeking support in this regard.

**Comment by Vliosgep** [comment]
In my comment , I already mentioned that I am also using bridging header.
-  when I import direct framework file in bridging header its throws error , 
-  when I import the ViewController class (in which the main code is written) into bridging header then its imported successfully but in that case the framework import statement gives error in ViewController class file
I tried either ways , if there is any other way suggest me. I checked few blogs to check the process of importing objective C files into swift project, but nothing helped.

**Comment by chlandsi** [comment]
Please make sure that the settings of the "Framework Search Path" and the "Header Search Path" point to the framework you downloaded, and the Headers directory therein, respectively.

**Comment by nenzitre** [comment]
You are forced to integrate this framework directly into the app via bridging header, so u don't need to import module: just type class you need, you should find em available in your intellisense.

**Comment by chlandsi** [comment]
A full sample on how to integrate the Speech SDK with Swift can be found [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/swift-ios).
