### ISSUE TITLE
Conversation Summarization Options

### ISSUE THREAD

**Issue by Tenopalad** [Azure-Samples/cognitive-services-speech-sdk#2051]
I see the conversation summaries in the output json files. How do I extract that information to see the most common topics?

**Comment by chschrae** [comment]
Hi there,

Thanks for reaching out. 

Can you give more specifics about what you are trying to accomplish? What sample did you start from?

Can you give details on what kind of information you are trying to extract?

**Comment by Tenopalad** [comment]
I am using the Ingestion Client for post call analytics as I am not proficient in writing code. To my knowledge the Ingestion Client analyzes my call recordings and outputs the information to a json, then it automatically takes the data from the output json files and adds it to the azure database. The Power BI template connects to the database and shows me sentiment insights and call details insights (ex-call length, silence time, words per min). All of this works fine but It doesnt show me summaries of the calls even though they are in the json files.

What I want is to be able to take the summarization results data from the json files and be able to see what the most common reasons for calling are. (ex- paying a bill, scheduling an appointment) I attached a screenshot of my json file to show I have the summary data already I just dont know how to use it.


![Capture](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/138081792/103d213c-0546-473d-938c-08aa5a3b6305)

**Comment by HenryvanderVegte** [comment]
Hey @Tenopalad 

```
To my knowledge the Ingestion Client analyzes my call recordings and outputs the information to a json, 
then it automatically takes the data from the output json files and adds it to the azure database. 
```

Yes - the ingestion client fetches the transcript, and then afterwards extends it with Text Analytics Info, like sentiment/Summarization etc.. 
However, the Conversational Text Analytics results (ConversationSummarization/ConversationPii) are not pushed to the SQL database, and therefore can't be used in the Power BI template. 
Only the "SentimentAnalysis" and "PiiRedaction" settings you can find here 
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/0b66f2ad693f7f6840221f98d61f524813e96d0a/samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json#L184C1-L206C11 are being used - and all the other features like call-length, words per min. etc.. are calculated based on the transcript.

As of today, you would have to adapt the ingestion client to push the conversation summarization results to the database... 

Thanks!

CC @bidisha-c
