### ISSUE TITLE
How to pass a list of bytes, received from twilio to Azure speech to text in python

### ISSUE THREAD

**Issue by shrimad-mishra** [Azure-Samples/cognitive-services-speech-sdk#2052]
Hi I am trying to grab the twilio response which is bytes form and pass it to the Azure speech to text services but there is no provide documention or sample code in python to look at.
The sample rate is 8000 of the stream of voice in form of list of bytes received from twilio.

Can you please help it's urgent 🙏

**Comment by chschrae** [comment]
Hi there!

Thanks for reaching out to us. 

There is some audio configuration you could try:

# setup the audio stream

    audio_format = speechsdk.audio.AudioStreamFormat(samples_per_second=8000, bits_per_sample=16,

                                                      channels=1, wave_stream_format=speechsdk.AudioStreamWaveFormat.MULAW)

    stream = speechsdk.audio.PushAudioInputStream(stream_format=audio_format)

    audio_config = speechsdk.audio.AudioConfig(stream=stream)


Can you let me know if that works?

**Comment by shrimad-mishra-cognoai** [comment]
from pydub import AudioSegment

def mp3_to_bytes(mp3_file_path):
    audio = AudioSegment.from_mp3(mp3_file_path)   
    byte_data = audio.raw_data   
    return byte_data

mp3_file_path = ..path
byte_data = mp3_to_bytes(mp3_file_path)

audio_format = speechsdk.audio.AudioStreamFormat(samples_per_second=8000, bits_per_sample=16, 
    channels=1, wave_stream_format=speechsdk.AudioStreamWaveFormat.MULAW)

stream = speechsdk.audio.PushAudioInputStream(stream_format=audio_format)

stream.write(byte_data)

audio_config = speechsdk.audio.AudioConfig(stream=stream)

speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)

transcriptions = []

def continuous_recognition_handler(evt):
    if evt.result.reason == speechsdk.ResultReason.RecognizedSpeech:
        transcriptions.append(evt.result.text)

speech_recognizer.recognized.connect(continuous_recognition_handler)
speech_recognizer.start_continuous_recognition()

timeout_seconds = 10
timeout_expiration = time.time() + timeout_seconds

while time.time() < timeout_expiration:
    time.sleep(.5)

speech_recognizer.stop_continuous_recognition()

transcription = ' '.join(transcriptions)
 
print(transcription)


For testing, I tried this by converting an mp3 file to byte and the audio format which you have given, but somehow the Azure sdk is not able to transcribe, it is sending an empty string.

Check if my code is correct or if I need to make some changes 
@chschrae

**Comment by jhakulin** [comment]
@shrimad-mishra-cognoai When you originally mentioned that you were trying to pass bytes from Twilio to Speech SDK, do you know in which audio format it is? Is it really MP3? Based on the earlier issues I have seen the format normally has been 8kHz MULAW, thus we proposed to try that format.

**Comment by shrimad-mishra-cognoai** [comment]
@jhakulin no but to test that I converted MP3 to bytes

**Comment by jhakulin** [comment]
@shrimad-mishra-cognoai In order to test MULAW encoded 8kHz audio, you need to convert MULAW encoded audio (not MP3) to bytes and pass that into Speech SDK using the configuration we provided.

**Comment by shrimad-mishra-cognoai** [comment]
@jhakulin can you please let me know if the code which I am using is correct or not if I do not use any MP3 file and directly send the stream chunk itself,
Sample Rate is 8000
Bits per sec is 128
The format is mono PCM
please confirm it.

**Comment by jhakulin** [comment]
@shrimad-mishra As you noted from your test experiments the test fails because you have used MP3 as input and configured Speech SDK for MULAW, so that part of the code is not correct. Also, in your example all bytes are written from the file before speech recognition has been started, I am not sure if that works with the Twilio scenario. If you need to continuously write data to the Speech SDK, you could create separate thread to write bytes like in this example https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_sample.py#L555

**Comment by jhakulin** [comment]
closing the issue, please let us know if there are more information needed.
