### ISSUE TITLE
Problem with .svg for Viseme Id 3

### ISSUE THREAD

**Issue by riiight** [Azure-Samples/cognitive-services-speech-sdk#2054]
Viseme Id 3 is for the IPA phoneme "ɔ". If you look at your [documentation](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-speech-synthesis-viseme?tabs=visemeid&pivots=programming-language-csharp#map-phonemes-to-visemes), you can see what the image is supposed to look like.

Using your .NET SDK and calling speechSynthesizer.SpeakSsmlAsync() being sure to include the element <mstts:viseme type="redlips_front"/>per your documentation, it returns SpeechSynthesisVisemeEventArgs with an Animation as expected. It works well, except that any word that uses viseme Id 3 will show the incorrect viseme. I've tried it with many words that include "ɔ" and Viseme Id 3 is always incorrect. Here's an example of the animation return via SpeechSynthesisVisemeEventArgs for the word "quarter". 

![FULL_FromAzure_Word_quarter](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/1669082/c36a4582-0f63-4bd6-8d97-bd74d8c19816)

Look at the frame for where Viseme Id 3 should show and you'll see it looks like viseme Id 0 (aka the "silent" viseme).

The same is thing happens with any other word that uses  "ɔ".

**Comment by rhurey** [comment]
Thanks for reporting this issue, I see the same thing and am looking into the cause.

**Comment by yulin-li** [comment]
Thanks for reporting this issue, we have found the root cause and the fix will be deployed in two weeks.
