### ISSUE TITLE
ApplicationException: Exception with an error code: 0x13 (SPXERR_START_RECOGNIZING_INVALID_STATE_TRANSITION)

### ISSUE THREAD

**Issue by hrishmu** [Azure-Samples/cognitive-services-speech-sdk#2056]
I am trying to create a AR-based face-tracking speech recognition enabled face tracking app in Unity. I am using Google ARCore for face tracking. While the speech recognition works well in Unity on my PC, it fails when I run it on my android device. I keep getting the error below, which does not appear in Unity on my PC:

2023/08/22 17:24:31.778 21469 21487 Error Unity ApplicationException: Exception with an error code: 0x13 (SPXERR_START_RECOGNIZING_INVALID_STATE_TRANSITION)
2023/08/22 17:24:31.778 21469 21487 Error Unity   at Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail (System.IntPtr hr) [0x00000] in <00000000000000000000000000000000>:0 
2023/08/22 17:24:31.778 21469 21487 Error Unity   at Microsoft.CognitiveServices.Speech.Recognizer.StartContinuousRecognition () [0x00000] in <00000000000000000000000000000000>:0 
2023/08/22 17:24:31.778 21469 21487 Error Unity   at Microsoft.CognitiveServices.Speech.Recognizer.DoAsyncRecognitionAction (System.Action recoImplAction) [0x00000] in <00000000000000000000000000000000>:0 
2023/08/22 17:24:31.778 21469 21487 Error Unity   at System.Threading.Tasks.Task.Execute () [0x00000] in <00000000000000000000000000000000>:0 
2023/08/22 17:24:31.778 21469 21487 Error Unity   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0 
2023/08/22 17:24:31.778 21469 21487 Error Unity   at System.Threading.Tasks.Task.ExecuteWithThreadLocal (System.Threading.Tasks.Task& currentTaskSlot) [0x00000] in <0000000000

My C# code is the same as the one provided in one of the samples:

`using UnityEngine;
using UnityEngine.UI;
using Microsoft.CognitiveServices.Speech;

public class HelloWorld2 : MonoBehaviour
{
    public Text outputText;
    public Button startRecordButton;

    // PULLED OUT OF BUTTON CLICK
    SpeechRecognizer recognizer;
    SpeechConfig config;

    private object threadLocker = new object();
    private bool speechStarted = false; //checking to see if you've started listening for speech
    private string message;

    private bool micPermissionGranted = false;

    private void RecognizingHandler(object sender, SpeechRecognitionEventArgs e)
    {
        lock (threadLocker)
        {
            message = e.Result.Text;
        }
    }
    public async void ButtonClick()
    {
        if (speechStarted)
        {
            await recognizer.StopContinuousRecognitionAsync().ConfigureAwait(false); // this stops the listening when you click the button, if it's already on
            lock (threadLocker)
            {
                speechStarted = false;
            }
        }
        else
        {
            await recognizer.StartContinuousRecognitionAsync().ConfigureAwait(false); // this will start the listening when you click the button, if it's already off
            lock (threadLocker)
            {
                speechStarted = true;
            }
        }

    }

    void Start()
    {
        startRecordButton.onClick.AddListener(ButtonClick);
        config = SpeechConfig.FromSubscription("*Key removed for security reasons*", "eastus");
        recognizer = new SpeechRecognizer(config);
        recognizer.Recognizing += RecognizingHandler;
    }

    void Update()
    {

        lock (threadLocker)
        {
            if (outputText != null)
            {
                outputText.text = message;
            }
        }
    }
}`

OS: Android, Development in Unity 2022.3.5f1 on Windows 11 Home PC
Hardware: ARMv7, ARM64
Programming Language: C#

I'd really appreciate it if you could help me in this regard to resolve this issue. Thanks a lot!

**Comment by rhurey** [comment]
Thanks for getting in touch and sorry about the lack of consistent behavior. This issue is one that would be quicker to diagnose with an [SDK log ](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-use-logging)from when the failure happens, could you provide one?

A couple of other comments from just reviewing the code...

- I'm not sure that the output and start / stop variables need to be protected by the same lock, having different locking variables could reduce conflicts, especially during stop calls. (See next....)

- The lock protecting the speechStarted variable can be subject to a time of check / time of use bug where multiple starts could occur in parallel since speechStarted hasn't been updated yet, but could still be read again. This possibly could explain the error.

**Comment by hrishmu** [comment]
Hello,

I just found out that I did not add some bits required in my code regarding microphone access permissions in android, resulting in my app never asking the permission to access the microphone, which in turn meant that the microphone was not being accessed. 

The issue is now resolved. Thanks a lot of for your cooperation! :)
