### ISSUE TITLE
Diarization never able to separate speakers at the beginning

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [Azure-Samples/cognitive-services-speech-sdk#2060]
Hi there :wave:

So I am using the diarization service because I need to seperate the spakers. Using the `katiesteve.wav` file and following the [doc](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/get-started-stt-diarization?tabs=macos&pivots=programming-language-javascript) I notice that the first two messages have spaker "unknown" - how come?

<img width="452" alt="Screenshot 2023-08-27 at 16 01 55" src="https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/15908060/f732557b-fa81-41da-ab53-a1cbfdb86d27">

In my demo, `1` means "unkown", "2" = "Guest-1" and "3" = "Guest-2"

This is the JSON

```json
[
  {
    "ResultId": "081F1D29D0064538974794D85995B5DD",
    "Reason": 3,
    "Text": "Good morning, Steve.",
    "Duration": 10400000,
    "Offset": 1100000,
    "SpeakerId": "Unknown"
  },
  {
    "ResultId": "081F1D29D0064538974794D85995B5DD",
    "Reason": 3,
    "Text": "Good morning, Katie.",
    "Duration": 10000000,
    "Offset": 20200000,
    "SpeakerId": "Unknown"
  },
  {
    "ResultId": "081F1D29D0064538974794D85995B5DD",
    "Reason": 3,
    "Text": "Have you tried the latest real time diarization in Microsoft Speech Service which can tell you who said what in real time?",
    "Duration": 76200000,
    "Offset": 38800000,
    "SpeakerId": "Guest-1"
  },
  {
    "ResultId": "081F1D29D0064538974794D85995B5DD",
    "Reason": 3,
    "Text": "Not yet. I've been using the batch transcription with diarization functionality, but it produces diarization result until whole audio get processed.",
    "Duration": 80800000,
    "Offset": 123900000,
    "SpeakerId": "Guest-2"
  }
]
```

Thanks

**Comment by jhakulin** [comment]
@FrancescoSaverioZuppichini Thanks for the report. Currently The service performs best with at least 7 seconds of continuous audio from a single speaker. This allows the system to differentiate the speakers properly. Otherwise, the Speaker ID is returned as Unknown.
See the documentation note in:
https://learn.microsoft.com/en-us/azure/ai-services/speech-service/get-started-stt-diarization?tabs=windows&pivots=programming-language-java

The issue here is probably caused by the performance limitation above. I will deliver the feedback to service team and see if there are any suggestions /  future plans on improving the service.

**Comment by FrancescoSaverioZuppichini** [comment]
> @FrancescoSaverioZuppichini Thanks for the report. Currently The service performs best with at least 7 seconds of continuous audio from a single speaker. This allows the system to differentiate the speakers properly. Otherwise, the Speaker ID is returned as Unknown. See the documentation note in: https://learn.microsoft.com/en-us/azure/ai-services/speech-service/get-started-stt-diarization?tabs=windows&pivots=programming-language-java
> 
> The issue here is probably caused by the performance limitation above. I will deliver the feedback to service team and see if there are any suggestions / future plans on improving the service.

Why you don't keep a queue of "Unknown" messages and you detect a new speaker you check if you can assign an old message to that speaker?

**Comment by jhakulin** [comment]
@FrancescoSaverioZuppichini Thanks for comment, we do have something like that under development/evaluation to provide corrected results in near real-time, however this functionality is not yet supported by ConversationTranscriber. Also, I do not have ETA when this will be supported. It is acknowledged as a requirement and that the current performance needs improvement to serve customers optimally.
