### ISSUE TITLE
speakTextAsync returns 0 byteLength when sending the same text to be synthesized.

### ISSUE THREAD

**Issue by geoff-mathspathway** [Azure-Samples/cognitive-services-speech-sdk#2062]
In our project when we send the same text to be synthesized twice, we get the correct duration returned, but a byteLength of 0.

If you change the text to something different, it will work correctly.

I tested with this exact project https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/node (synthesis) and just changed my subscription key and region 'australiaeast', and had the exact same problem.

This happens with speakTextAsync and speakSsmlAsync - please help this is affecting our users!

**Comment by dsreitan** [comment]
Exact same issue here. Region West Europe. Unusable at the moment.

@rhurey @yulin-li  ++

**Comment by jhakulin** [comment]
Thanks for the reports! We are currently investigating the issue and will report back soon once we have a resolution.

**Comment by dsreitan** [comment]
Yes! It seems to be resolved. Thank you. Any insight you could share about what went wrong?

**Comment by jhakulin** [comment]
@dsreitan Thanks for confirming, the issue is suspected to be caused by new synthesis cache feature (which was in flight) and that has been now disabled. We will make the further analysis and see what are required actions to prevent the regression in future.

**Comment by geoff-mathspathway** [comment]
Yes this have been resolved. That caused me major pain as the last thing you suspect is MS is broken on the backend.
