### ISSUE TITLE
Different ASR result between python sdk and speech studio.

### ISSUE THREAD

**Issue by coreeey** [Azure-Samples/cognitive-services-speech-sdk#2063]
I deployed a model in a speech studio service and used its endpoint_id for deployment in Python. However, when I tried to recognize a wav file in Python using both "speech_recognize_continuous_from_file()" and "speech_recognize_async_from_file()", I found that the results in Python were inconsistent with the results obtained by uploading the file through the UI. What could be the reason for this??

**Comment by heikora** [comment]
What is the audio format of the audio file you are using? Speech Studio is leveraging gstreamer to support a range of audio formats and you may for example get slightly different results (over a large corpus) if you have 8kHz data since gstreamer will convert that to 16kHz first before sending it to the service instead of sending it directly.

**Comment by coreeey** [comment]
I test the result in librispeech dataset, the audio format information of  which is "Codec: WAV, Channels: Mono, Sample rate: 16000Hz, Bit rate: 256kbps". More specifically, i test the "61-70968-0022.wav" in speech studio, speech_recognize_once_from_file() and speech_recognize_continuous_from_file(). The result of them are "OLD MAN ANSWERED THE LEAD SOLDIER", "OLD MAN ANSWERED THE LEAN SOLELY PRENTICE" and "OLD MAN ANSWERED THE LEAN SOLELY"  respectively. furthermore, the result of the most of audio in librispeech dev dataset is a bit different. So, which function should I use if I want to get the most similar result between python and speech studio?

**Comment by heikora** [comment]
When you run this in Speech Studio, which of these are you using: The Real-time speech to text try-out, The Batch speech to text try out, or are you running a test in a Custom Speech project?
Are you using en-US as the locale? Also how did you convert the original .flac file to wav?
When I run 61-70968-0022.wav from librispeech I get consistent results. I assume for the Python code you run our github sample:
Real-time try-out: "Tis fine for you to talk, old man, answered the lean, sullen apprentice. "
Batch try-out: "'Tis fine for you to talk, old man," answered the lean, sullen apprentice. 
Python speech_recognize_once_from_file(): "Tis fine for you to talk, old man, answered the lean, sullen apprentice."
Python speech_recognize_continuous_from_file(): "Tis fine for you to talk, old man, answered the lean, sullen apprentice."

**Comment by heikora** [comment]
[61-70968-0022.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/12482265/61-70968-0022.zip)
Here is the wav file I am using.

**Comment by coreeey** [comment]
In Speech Studio, I am running a test in a Custom Speech project,  using en-US as the locale and 'eastus' as the location, the model i am using is 20221013. What I forgot to mention just now is that my audio has added some noise for enhancement.
when I run the "61-70968-0022.wav" in Speech Studio UI, the output is "Old man, answered the lead soldier".
Python speech_recognize_once_from_file(): "Old Man answered the lean solely Prentice."
Python speech_recognize_continuous_from_file(): " Old Man answered the lean solely Prentice."
the result in speech_recognize_once_from_file() and speech_recognize_continuous_from_file() are the same, but both of them are different with Speech Studio UI.
[61-70968-0041.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/12483002/61-70968-0041.zip)

futhermore, i also run the '61-70968-0041.wav' in above three ways:
Speech Studio: "I like you, Will, that i have met in life within two days doing that"
Python speech_recognize_once_from_file(): "I like you."
Python speech_recogniz
[61-70968-0022.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/12483004/61-70968-0022.zip)
e_continuous_from_file(): "I like you. Will that I have met in like within two days? In that."
the result of three ways have a big difference.

**Comment by trrwilson** [comment]
@coreeey -- apologies for this falling off the radar. Given the contrast between the results you observed and what @heikora reported, I think we need further details to advise:

- You mention that you've modified the reference input audio to add noise; can you share either the audio or the method to reconstruct it? And is the input consistent across test scenarios?
- Do you observe the same discrepancies when using the default speech endpoint or is this unique to your custom speech project?
- Is the code exercising the API calls for recognize_once and recognize_continuous unmodified from the quickstart?
