### ISSUE TITLE
Configure TTS pitch in python sdk

### ISSUE THREAD

**Issue by shrimad-mishra-cognoai** [Azure-Samples/cognitive-services-speech-sdk#2065]
Hey I want to alter the rate and pitch in Python SDK by making use of speak_text, can you provide any samples

**Comment by jhakulin** [comment]
@shrimad-mishra-cognoai Please see the following SO answer that might be helpful https://stackoverflow.com/questions/70384401/how-to-setting-the-speech-rate-in-azure-text-to-speech

I will check further if we can provide samples, currently we seem not to have any sample to provide.

@yulin-li for awareness

**Comment by yulin-li** [comment]
Add the official doc is [here](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/speech-synthesis-markup-voice#adjust-prosody). You need to use SSML to control the pitch and then `speak_ssml` api.

**Comment by jhakulin** [comment]
Closing the issue, let us know if need more information
