### ISSUE TITLE
Confusion Regarding the Two Voice Models, zh-CN-YunxiNeural and zh-CN-YunxiLTSNeural

### ISSUE THREAD

**Issue by SingleDog11** [Azure-Samples/cognitive-services-speech-sdk#2066]
I have come across two voice models for Yunxi, namely YunxiNeural and YunxiLTSNeural. YunxiLTSNeural appears to be unique and is predominantly available in the Asian region (I have tested specifically in East Asia and Southeast Asia). Comparatively, YunxiLTSNeural produces much more standardized voice output than YunxiNeural. I have noticed that some apps offer a smoother version of Yunxi, and upon further investigation through network sniffing, I discovered that they are utilizing YunxiLTSNeural. This differs from my experience of accessing YunxiLTSNeural through the API, as it lacks the same level of smoothness and does not maintain continuity within a complete sentence. I would like to inquire about how I can find the smoother version of YunxiLTSNeural.
![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/10295379/a3f6da9b-f60e-40b3-954b-895b105a3e68)
云飞羽 -： YunxiNeural
云飞羽流利版-：YunxiLTSNeura

**Comment by jhakulin** [comment]
@SingleDog11 Thanks for the report, we have assigned the issue to the service side engineer and will let you know with more information.

**Comment by Kerry-LinZhang** [comment]
@SingleDog11 thanks for your feedback, to help us debug the issue, would you please share with us more details, for example some sentence examples (5+ is preffered) , what is the current bad behavior, how would you like it could be... to help us repro and analyze the problem.

**Comment by Kerry-LinZhang** [comment]
And currently, for YunxiLTS version, if there are no significant issues, we will no longer provide further support.

**Comment by trrwilson** [comment]
Given the elapsed time without new information, I'll close this issue to keep open issues tidy. If the requested information can provided or further questions can be answered, please reopen this issue or file a new one referencing it. Thank you!
