### ISSUE TITLE
TimeoutException: com.microsoft.cognitiveservices.speech.util.SafeHandle.finalize() timed out after 10 seconds

### ISSUE THREAD

**Issue by mackwu828** [Azure-Samples/cognitive-services-speech-sdk#2068]
```
09-04 08:57:17.109  3437  3449 E AndroidRuntime: FATAL EXCEPTION: FinalizerWatchdogDaemon
09-04 08:57:17.109  3437  3449 E AndroidRuntime: Process: com.xxx.xxx, PID: 3437
09-04 08:57:17.109  3437  3449 E AndroidRuntime: java.util.concurrent.TimeoutException: com.microsoft.cognitiveservices.speech.util.SafeHandle.finalize() timed out after 10 seconds
09-04 08:57:17.109  3437  3449 E AndroidRuntime: 	at com.microsoft.cognitiveservices.speech.util.SafeHandle.releaseRecognizerHandle(Native Method)
09-04 08:57:17.109  3437  3449 E AndroidRuntime: 	at com.microsoft.cognitiveservices.speech.util.SafeHandle.close(Unknown Source:29)
09-04 08:57:17.109  3437  3449 E AndroidRuntime: 	at com.microsoft.cognitiveservices.speech.util.SafeHandle.finalize(Unknown Source:0)
09-04 08:57:17.109  3437  3449 E AndroidRuntime: 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:319)
09-04 08:57:17.109  3437  3449 E AndroidRuntime: 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:306)
09-04 08:57:17.109  3437  3449 E AndroidRuntime: 	at java.lang.Daemons$Daemon.run(Daemons.java:140)
09-04 08:57:17.109  3437  3449 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
```

when start recognize use `recognizeOnceAsync` , but sometimes this error occur. please help
```
	pushStream = AudioInputStream.createPushStream();
	// customize audio record
        AudioRecordManager.getInstance().startRecord(audioChunk -> {
            pushStream.write(audioChunk.toBytes());
        });
        AudioConfig audioConfig = AudioConfig.fromStreamInput(pushStream);
        SpeechRecognizer speechRecognizer = new SpeechRecognizer(speechConfig, audioConfig);
        task = speechRecognizer.recognizeOnceAsync();
```

when stop recognize call  `pushStream.close()`
```
        try {
            AudioRecordManager.getInstance().stopRecord();
	    if (pushStream != null) {
                pushStream.close();
	    }
            if (task != null) {
                try {
                    SpeechRecognitionResult result = task.get(15, TimeUnit.SECONDS);
                } catch (Exception ignored) {
                }
            }
        } catch (Exception ignored) {
        }
```

**Comment by mackwu828** [comment]
[logfile.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/12510016/logfile.txt)

**Comment by dargilco** [comment]
Hi @mackwu828 this is Darren from the Speech SDK team. Please try the following change in your code: BEFORE the line `pushStream.close()`, add this line: `speechRecognizer.stopContinuousRecognitionAsync().get();`. And yes, I see that you use recognizeOnceAsync() and not startContinuousRecognitionAsync()... calling stopContinuousRecognitionAsync should work to stop both.

Also note that you need to explicilty call `.close()` on  audioConfig, speechRecognizer when you are done using the recognizer, or define them in a try-with-resources block such that `.close()` is automatically called.

**Comment by mackwu828** [comment]
thanks! i will try this

**Comment by jieqiudede** [comment]
> Hi @mackwu828 this is Darren from the Speech SDK team. Please try the following change in your code: BEFORE the line `pushStream.close()`, add this line: `speechRecognizer.stopContinuousRecognitionAsync().get();`. And yes, I see that you use recognizeOnceAsync() and not startContinuousRecognitionAsync()... calling stopContinuousRecognitionAsync should work to stop both.
> 
> Also note that you need to explicilty call `.close()` on audioConfig and speechRecognizer when you are done using the recognizer, or define them in a try-with-resources block such that `.close()` is automatically called.

Can you help me? I have the same question in my app.
          
Fatal Exception: java.util.concurrent.TimeoutException: com.microsoft.cognitiveservices.speech.util.SafeHandle.finalize() timed out after 60 seconds
       at com.microsoft.cognitiveservices.speech.util.SafeHandle.releasePropertyHandle()
       at com.microsoft.cognitiveservices.speech.util.SafeHandle.close(:55)
       at com.microsoft.cognitiveservices.speech.util.SafeHandle.finalize()
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:339)
       at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:324)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:300)
       at java.lang.Daemons$Daemon.run(Daemons.java:145)
       at java.lang.Thread.run(Thread.java:1012)
       
       
       And my code: 
      withContext(Dispatchers.IO) {
             SpeechSynthesizer synthesizer = new SpeechSynthesizer(speechConfig, audioConfig);
             SpeechSynthesisResult result = result = synthesizer.SpeakSsmlAsync(ssml).get();
             result.close();
      }
