### ISSUE TITLE
C# CognitiveServices.Speech.SpeechSynthesizer always fail to open http API when working behind a proxy server

### ISSUE THREAD

**Issue by Acetylen3** [Azure-Samples/cognitive-services-speech-sdk#207]
**Describe the bug**
When using SpeechSynthesizer behind a Proxy server, it always fail to reach the Azure server.
I have configured the same proxy setting and it works with Speech**Recognizer**, but it fail with SpeechSynthesizer.

**To Reproduce**
1. Set proxy setting in SpeechConfig
2. var synthesizer = new SpeechSynthesizer(config) -> no exception
3. var result = await synthesizer.SpeakTextAsync(text) -> result.Reason is "Canceled", Error Details is "HTTPAPI result code = HTTPAPI_OPEN_REQUEST_FAILED."
4. If I execute same code without seating behind a proxy server, no error.
5. Speech**Recognizer** works fine with the same proxy setting under the same environment, I suggest to compare code between this 2 classes.

**Expected behavior**
SpeechSynthesizer works fine under a proxy server

**Version of the Cognitive Services Speech SDK**
Latest stable version 1.4.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 10 Pro
 - Hardware - x64
 - Programming language: C# .NET Windows Form

**Comment by wolfma61** [comment]
we will take a look -
can you try without a proxy in your network?

**Comment by Acetylen3** [comment]
> we will take a look -
> can you try without a proxy in your network?

As I mentioned in step 4 "If I execute same code without seating behind a proxy server, no error."

**Comment by dotnetdude** [comment]
Just got the same issue. I can confirm its not working behind the proxy but working without proxy.

**Comment by wolfma61** [comment]
this will get fixed in a future release (not in the upcoming 'early May' refresh.
sorry about the trouble

Wolfgang

**Comment by yinhew** [comment]
@Acetylen3 @dotnetdude FYI, the proxy for SpeechSynthesizer is now supported in release 1.6.0. The usage is same as SpeechRecognizer.
