### ISSUE TITLE
Profanity Option not working

### ISSUE THREAD

**Issue by kylefoley76** [Azure-Samples/cognitive-services-speech-sdk#2070]
Using Python 3.9, the following code does not work.  No error is thrown it's just that SDK continues to replace certain words with asterisks.  In this case, the name 'Fanny' was replaced with '*****'  In the code below I have:

```
    import azure.cognitiveservices.speech as speechsdk
    sconfig = speechsdk.SpeechConfig(
        subscription=skey,
        endpoint=endpoint,
    )
    sconfig.ProfanityOption=False
    
```

When I try 

```
sconfig.set_profanity(profanity_option=False) 
```

that results in an error message:

```
TypeError: bad option, must be ProfanityOption
```

Which I find strange since when I type `help(sconfig)` I get:

 |  set_profanity(self, profanity_option: azure.cognitiveservices.speech.ProfanityOption) -> None
 |      Set the profanity option.
 |      
 |      .. note::
 |        Added in version 1.5.0.
 |      
 |      :param profanity_option: The profanity level to set.

I also tried setting 

sconfig.ProfanityOption=True

with the same result.

**Comment by dargilco** [comment]
@kylefoley76 this is Darren from the Speech SDK team. Thank you for reporting this issue. I am checking and will post an update here shortly.

**Comment by dargilco** [comment]
Per the reference documents:

- https://learn.microsoft.com/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.speechconfig?view=azure-python#azure-cognitiveservices-speech-speechconfig-set-profanity

- https://learn.microsoft.com/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.profanityoption?view=azure-python

the correct syntax is the following:

`
 import azure.cognitiveservices.speech as speechsdk
 sconfig = speechsdk.SpeechConfig(
        subscription=skey,
        endpoint=endpoint,
  )
  sconfig.set_profanity(speechsdk.ProfanityOption.Raw)
`

**Comment by kylefoley76** [comment]
Thanks.  That did it.
