### ISSUE TITLE
SRT Caption files generated using python have many broken sentences.

### ISSUE THREAD

**Issue by shawnCaza** [Azure-Samples/cognitive-services-speech-sdk#2071]
- Speech SDK log: [log.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/12561619/log.txt)

- Using the python [sample captioning files here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/scenarios/python/console/captioning). I ran this command `python ./captioning/captioning.py --input ./captioning/caption_test_fast_talking.wav --output caption.output.txt --srt --offline remainTime 1000 --profanity raw --maxLineLength 80 --lines 1`

I also uploaded the same wav file, with the same setting to the [speech studio web ui for generating captions here](https://speech.microsoft.com/portal/captioning).

- If relevant, a WAV file of your input audio.
[caption_test_fast_talking.wav.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/12561765/caption_test_fast_talking.wav.zip)

- Additional information as shown below

**Describe the bug**

After testing a handful of files, I'm under the impression that generating srt files online with Speech Studio generally produces much better results than when I use python to generate srt files. Even when using the same audio file and settings I consistently get different results from Speech Studio than I get when using Python. 

In particular, Speech Studio seems to be better at preserving full sentences when possible, and is more likely to start a new caption at the start of a sentence. For example, using the attached audio file Speech Studio gives me the following:

```
15
00:00:53,610 --> 00:00:57,230
One will choose to output it in a different way than the other one. 

16
00:00:57,230 --> 00:00:59,910
And that's what I'm trying to overcome. 

17
00:00:59,910 --> 00:01:04,070
It seems like maybe there is a bit something different going on behind the 

18
00:01:04,070 --> 00:01:04,570
scenes.
```

Whereas when using python, I'm more likely to have a caption start in the middle of a sentence. Python returned the following for the above audio sequence:

```
14
00:00:50,476 --> 00:00:55,894
one by both methods. One will choose to output it in a different way than the

15
00:00:55,894 --> 00:00:57,230
other one.

16
00:00:57,230 --> 00:01:02,081
And that's what I'm trying to overcome. It seems like maybe there is a bit

17
00:01:02,081 --> 00:01:07,062
something different going on behind the scenes. Maybe there's a more updated
```

**Expected behavior**

To produce an SRT file that is less reckless in regards to breaking sentences and sentence units apart. Captions should preserve sentences when possible. if not possible it should attempt to break sentences up on commas.

**Version of the Cognitive Services Speech SDK**

1.32.1

**Platform, Operating System, and Programming Language**

 - OS: MacOS 13.3.1 
 - Hardware - x64, 
 - Programming language: Python

**Comment by dargilco** [comment]
Hi @shawnCaza this is Darren from the Speech SDK team. Thank you for the detailed description! This is very helpful. I will look at it shortly and give an update here.

**Comment by dargilco** [comment]
@shawnCaza what were your settings when you do captioning for the WAV file in Speech Studio? (caption mode, Stable partial threshold, lines, length). Also how did you get the SRT format output from Speech Studio? All it has is the text result (under "Developer resources" -> "Detection caption" tab.

**Comment by dargilco** [comment]
@shawnCaza the code that runs in Speech Studio captioning is the Java Script code that's available in the Speech SDK GitHub samples repo ([direct link here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/scenarios/javascript/node/captioning)). I run that Node JS code from a console window, using the WAV file you provided, and the run-time flags you provided. I compared the result to what I get from the C# and Python versions of the same captioning tool (direct link [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/scenarios/csharp/dotnetcore/captioning) and [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/scenarios/python/console/captioning)).
Recognized words are the same for all runs. However, the way the utterances are broken in the SRT output is very different. The result from C# and Python run are very very similar. But both are different from the Java Script results. The Java Script results give me longer utterances in the SRT output.
I'm trying to figure out why I see a difference between the tool implemented in different programming languages. If I figure this out it may be a clue to your issue.

**Comment by shawnCaza** [comment]
> settings when you do captioning for the WAV file in Speech Studio? (caption mode, Stable partial threshold, lines, length)

caption mode: offline, lines: 1, length: 80.

>  All it has is plain text output (under "Developer resources" -> "Detection caption" tab.

When I first looked at this a few weeks ago I thought plain text was the only option too. I believe you need to be on 'offline' caption mode to get srt. [I've attached a screen recording.](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/15076753/53fa0936-c7e2-4034-a65b-b93227fdee36)

>  If I figure this out it may be a clue to your issue.

Thanks. Much appreciated. I'll take a closer look at the python code to try to better understand how the utterances are broken up too.

> Recognized words are the same for all runs

That may have been the case for this file. But with at least one of my client audio files (which I can't share), very different words do come up in python vs Speech Studio.

This is an example from Speech Studio:

> 11
> 00:00:26,200 --> 00:00:30,680
> This team has gone 217 days **_save_** special **_shout out to our_** amazing **_store_**. 

Compared to the python output:

> 9
> 00:00:26,494 --> 00:00:30,325
> redacted. This team has gone 217 days **_safe_**. Special **_shots were_** amazing
> 
> 10
> 00:00:30,325 --> 00:00:30,690
> **_storm._**

That said, [one of the test audio files I recorded](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/12564596/caption_test.wav.zip) with my own voice got [perfectly identical results aside from minor variations on timing and one contraction in the caption text](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/15076753/6829f7b9-3b11-4427-9bc1-0a33c6d8afab). 

Speech Studio doesn't seem to have a 'remainTime' option in the UI, but I'm not sure that accounts for the way sentences are broken up. I don't see text variations if I change that option in Python. I only see timing variations.

**Comment by dargilco** [comment]
Hi @shawnCaza, thank you for the additional information above. I spent some time tonight looking into the issue. Here are my findings:
- We have real-time captioning samples for C++, C#, Python, JavaScript and Go in this repo (https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/scenarios).
- The C++, C#, Python & JavaScript define flag `--maxLineLength`. However, only the C++, C# and Python actually implement this feature, by breaking apart long Recognizing & Recognized results into multiple lines in the SRT output, each line shorter than `maxLineLength`. This line breakup is part of the sample. It is not done inside the Speech SDK. This line splitting implementation is unfortunately missing from the Java & JavaScript samples.
- Go sample does not even define `--maxLineLengh`.
- I open an internal work item to discuss this missing feature. It's not good that this work os not complete and we don't have parity between the samples in the different programing languages.
- As you've seen, Speech Studio has a real-time demo and an offline demo. Real-time uses the JavaScript Speech SDK. Offline uses REST APIs (aka [Batch Transcription](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/batch-transcription)). So when you compare the two (1) running Python captioning samples and (2) Speech Studio offline captioning demo, you are comparing real-time Speech SDK, with the line split done in the captioning sample, to results from REST APIs. 

I'm less familiar with the REST APIs and Speech Studio code. I will find out where the line splitting (conforming to max line width) is done for the offline captioning demo in Speech Studio.  It's either in Speech Studio (done in the browser) or it's on the Speech Service, and the SRT result conforming to max line width is part of the REST response. I suspect we have two different implementations of the line splitting, hence the differences you see.

**Comment by dargilco** [comment]
@shawnCaza I discussed this with the folks who own Speech Studio. Speech Studio has Java Script code to split speech recognition results to fit the max caption line length, similar to the code that you see in the public caption samples in this repo. However the code in Speech Studio is more recent and has some improvements. For example, it tries to break the lines based on location of punctuation. We need to update the line-splitting code in the public samples to match this new version that runs in Speech Studio.

**Comment by pankopon** [comment]
Internal work item ref. 5633740 (no ETA).

**Comment by pankopon** [comment]
Closing this issue since the work item to update Java and JavaScript samples is still without ETA and there is no target schedule. We will update this when there's a release plan.
