### ISSUE TITLE
Inaccurate results when reading file from httpstream versus good results with same file loaded as wav file

### ISSUE THREAD

**Issue by borrmann** [Azure-Samples/cognitive-services-speech-sdk#2074]
I will add the logs and wav file in the comments

```
using System.Net.Http;
using Microsoft.CognitiveServices.Speech;
using Microsoft.CognitiveServices.Speech.Audio;

var _httpClient = new HttpClient();
var speechConfig = SpeechConfig.FromSubscription("{my azure speech key}", "germanywestcentral");
speechConfig.SpeechRecognitionLanguage = "de-DE";
speechConfig.SetProperty(PropertyId.Speech_LogFilename, "{path}\\audiolog.txt");


HttpResponseMessage wavresponse = await _httpClient.GetAsync($"{https link to twilio audio file (wav)}").ConfigureAwait(continueOnCapturedContext: false);
using var httpStream = await wavresponse.Content.ReadAsStreamAsync();

using var memoryStream = new MemoryStream();
await httpStream.CopyToAsync(memoryStream);
memoryStream.Position = 0;
var reader = new BinaryReader(memoryStream);

using var audioInputStream = AudioInputStream.CreatePushStream();

//OPTION 1:
using var audioConfig = AudioConfig.FromStreamInput(audioInputStream);

//OPTION 2:
using var audioConfig = AudioConfig.FromWavFileInput("{path to same downloaded file}\\voice.wav");

using var recognizer = new SpeechRecognizer(speechConfig, audioConfig);


byte[] readBytes;
do
{
    readBytes = reader.ReadBytes(1024);
    audioInputStream.Write(readBytes, readBytes.Length);
} while (readBytes.Length > 0);

var stopRecognition = new TaskCompletionSource<int>(TaskCreationOptions.RunContinuationsAsynchronously);

var textRecognition = "";

recognizer.Recognized += (s, e) =>
{
    if (e.Result.Reason == ResultReason.RecognizedSpeech)
    {
        textRecognition += e.Result.Text;
        Console.WriteLine(e.Result.Text);
    }
};

recognizer.Canceled += (s, e) =>
{
    stopRecognition.TrySetResult(0);

};

recognizer.SessionStopped += (s, e) =>
{
    stopRecognition.TrySetResult(0);
};

// Starts continuous recognition. Uses StopContinuousRecognitionAsync() to stop recognition.
await recognizer.StartContinuousRecognitionAsync().ConfigureAwait(false);

// Waits for completion.
// Use Task.WaitAny to keep the task rooted.
System.Threading.Tasks.Task.WaitAny(new[] { stopRecognition.Task });

// Stops recognition.
await recognizer.StopContinuousRecognitionAsync().ConfigureAwait(false);

Console.WriteLine(textRecognition);
```

- WAV file in comments

**Describe the bug**
I am trying to transcribe audio files that were recorded using twilio api. When I try to transribe the files from http stream (OPTION 1 in code snippet) I get inaccurate results. When I download the same file from the recording url to my desktop and the load the file instead a http stream (OPTION 2 in code) I get immaculate results. 

1. Run code with option 1
2. Run code with option 2

**Expected behavior**

I would expect to receive the same results from wav file and from http stream.

**Version of the Cognitive Services Speech SDK**
Nuget Microsoft.CognitiveServices.Speech 1.32.1 

**Platform, Operating System, and Programming Language**

 - OS: Windows
 - Hardware - x64
 - Programming language: C#

**Comment by borrmann** [comment]
here is the log file from option 1
[audiolog.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/12589155/audiolog.txt)

**Comment by borrmann** [comment]
here is the log file from option 2
[audiolog.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/12589165/audiolog.txt)

**Comment by borrmann** [comment]
Here is the WAV file that was used in ZIP as WAV is unsupported here:
[speechsdktest.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/12589176/speechsdktest.zip)

Transcription Result of Option 1 (bad):
"Was zwischen uns.Die konstatieren unter 500 Quadratmeter Tschüss."


Transcription Result of Option 2 (great):
"Hallo, hier ist Max. Ich rufe nur an um.Die Transkription auszuprobieren, funktioniert das jetzt endlich mal?500 Quadratmeter, Tschüss."

**Comment by BrianMouncer** [comment]
The wav file you sent appears to be mono 8khz, 32bit formatted data.
The default input for the SDK is mono, 16khz, 16bit.

When you set input from the file on disk, the SDK will read the wave header in the file, and set the audio format correctly.
But when passing in a buffer of bytes, you need to tell the engine the format you are writing to the stream.

you should update your code to pass in the audio format.
e.g. 

// Define the audio format (modify with your actual format)
var audioFormat = AudioStreamFormat.GetWaveFormatPCM(16000, 16, 1);
using var audioInputStream = AudioInputStream.CreatePushStream(audioFormat);

or in the case of your example audio file...

// Define the audio format (modify with your actual format)
var audioFormat = AudioStreamFormat.GetWaveFormatPCM(8000, 32, 1);

using var audioInputStream = AudioInputStream.CreatePushStream(audioFormat);

two other issue, you should probably skip the initial 44 bytes of the file, so the wave header does not get sent to the recognizer as "audio data", and then close the push stream when you finish with it.

Hope that helps,

**Comment by borrmann** [comment]
@BrianMouncer that makes sense, thank you!
Is there an alternative approach to read the info dynamically? 
I guess the information is then probably stored in those 44 bytes?
The function that loads directly from WAV seems to already handle all that dynamically which would be great when I have to deal with different sources, but last time I checked that one only works on Windows.

Would it be possible to somehow extend the API so that you can also pass bytes to the read from wav function?

I am sure I can figure it out now eventually though so thank you very much.

**Comment by borrmann** [comment]
this one worked for me (bits per sample are 16, not 32)
var audioFormat = AudioStreamFormat.GetWaveFormatPCM(8000, 16, 1);

**Comment by BrianMouncer** [comment]
@borrmann if you look up the wave header spec, its not too hard to read in the 44 bytes with a BinaryReader....
but if you just want some code that will work, take a look at our helper classes in our public camples.

[AudioConfig OpenWavFile(BinaryReader reader, AudioProcessingOptions audioProcessingOptions = null)](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/04e4fbdee065978ea0bff09b6de26fe7b80cf2a7/samples/csharp/sharedcontent/console/helper.cs#L17C15-L17C15)

**Comment by borrmann** [comment]
Thank you for the hint! That'll do.
