### ISSUE TITLE
Speech diarization through swift

### ISSUE THREAD

**Issue by kelayamatoz** [Azure-Samples/cognitive-services-speech-sdk#2077]
Great work on the SDK! Appreciate it. 

I noticed that there are several examples for speech diarization in c#, java, and python. There's no swift example, though. 

I'm wondering if it is even possible to access diarization from the swift package? If not, is there a plan on supporting swift?

Thanks!

**Comment by albin3** [comment]
@kelayamatoz  Mixing Swift and C++ may helps

https://www.swift.org/documentation/cxx-interop/

**Comment by kelayamatoz** [comment]
@albin3 Thank you! 

Could I ask for a pointer to accessing the speech cloud SDK in C++ for speech diarization? I'm still ramping up on learning this SDK and a few more pointers would be really helpful!

**Comment by jhakulin** [comment]
@kelayamatoz We have added speaker diarization sample for Swift in recent 1.32.1 release, please see
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/swift/ios/conversation-transcription

**Comment by kelayamatoz** [comment]
That looks great, thank you!

**Comment by albin3** [comment]
@jhakulin any info to #2076 ? thx 😃
