### ISSUE TITLE
delete_Recognizer; line: -2; Exception: java.util.concurrent.TimeoutException: 

### ISSUE THREAD

**Issue by wall3001** [Azure-Samples/cognitive-services-speech-sdk#208]
HUAWEI
HUAWEI GRA-CL10
OS Version: 6.0
**********************************************
class: com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI; method: delete_Recognizer; line: -2; Exception: java.util.concurrent.TimeoutException: com.microsoft.cognitiveservices.speech.internal.TranslationRecognizer.finalize() timed out after 30 seconds
class: com.microsoft.cognitiveservices.speech.internal.Recognizer; method: delete; line: 32; Exception: java.util.concurrent.TimeoutException: com.microsoft.cognitiveservices.speech.internal.TranslationRecognizer.finalize() timed out after 30 seconds
class: com.microsoft.cognitiveservices.speech.internal.TranslationRecognizerBase; method: delete; line: 37; Exception: java.util.concurrent.TimeoutException: com.microsoft.cognitiveservices.speech.internal.TranslationRecognizer.finalize() timed out after 30 seconds
class: com.microsoft.cognitiveservices.speech.internal.TranslationRecognizer; method: delete; line: 37; Exception: java.util.concurrent.TimeoutException: com.microsoft.cognitiveservices.speech.internal.TranslationRecognizer.finalize() timed out after 30 seconds
class: com.microsoft.cognitiveservices.speech.internal.TranslationRecognizer; method: finalize; line: 26; Exception: java.util.concurrent.TimeoutException: com.microsoft.cognitiveservices.speech.internal.TranslationRecognizer.finalize() timed out after 30 seconds
class: java.lang.Daemons$FinalizerDaemon; method: doFinalize; line: 202; Exception: java.util.concurrent.TimeoutException: com.microsoft.cognitiveservices.speech.internal.TranslationRecognizer.finalize() timed out after 30 seconds
class: java.lang.Daemons$FinalizerDaemon; method: run; line: 185; Exception: java.util.concurrent.TimeoutException: com.microsoft.cognitiveservices.speech.internal.TranslationRecognizer.finalize() timed out after 30 seconds
class: java.lang.Thread; method: run; line: 833; Exception: java.util.concurrent.TimeoutException: com.microsoft.cognitiveservices.speech.internal.TranslationRecognizer.finalize() timed out after 30 seconds
java.util.concurrent.TimeoutException: com.microsoft.cognitiveservices.speech.internal.TranslationRecognizer.finalize() timed out after 30 seconds
at com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.delete_Recognizer(Native Method)
at com.microsoft.cognitiveservices.speech.internal.Recognizer.delete(Recognizer.java:32)
at com.microsoft.cognitiveservices.speech.internal.TranslationRecognizerBase.delete(TranslationRecognizerBase.java:37)
at com.microsoft.cognitiveservices.speech.internal.TranslationRecognizer.delete(TranslationRecognizer.java:37)
at com.microsoft.cognitiveservices.speech.internal.TranslationRecognizer.finalize(TranslationRecognizer.java:26)
at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
at java.lang.Thread.run(Thread.java:833)
**********************************************

**Comment by mahilleb-msft** [comment]
Hi @wall3001,

could you give a bit more details:
- which code (or sample) are you running.
- does this happen always, or only sometimes.
- which OS version / API level version are you running with? Officially, we're supporting API level 23 or up (Android 6.0 Marshmallow).

Best, Mark

**Comment by wall3001** [comment]
try {
    if (reco != null) {
        reco.close();
        reco = null;
    }
} catch (Exception e) {
    Log.d(TAG, "close: " + e.getMessage());
}
1、invoke above code 
2、sometimes3、Android 6.0 








------------------ 原始邮件 ------------------
发件人: "Mark Hillebrand"<notifications@github.com>; 
发送时间: 2019年4月16日(星期二) 下午5:10
收件人: "Azure-Samples/cognitive-services-speech-sdk"<cognitive-services-speech-sdk@noreply.github.com>; 
抄送: "Nightsong"<wall137@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [Azure-Samples/cognitive-services-speech-sdk] delete_Recognizer;line: -2; Exception: java.util.concurrent.TimeoutException:  (#208)




Hi @wall3001,
 
could you give a bit more details:
  
which code (or sample) are you running.
 
does this happen always, or only sometimes.
 
which OS version / API level version are you running with? Officially, we're supporting API level 23 or up (Android 6.0 Marshmallow).
  
Best, Mark

**Comment by wall3001** [comment]
Error CancellationErrorCode:ServiceTimeout Error details:Due to service inactivity the client buffer size exceeded. Resetting the buffer.
What's the matter?Could you help me? Thanks！




------------------ 原始邮件 ------------------
发件人: "Mark Hillebrand"<notifications@github.com>; 
发送时间: 2019年4月16日(星期二) 下午5:10
收件人: "Azure-Samples/cognitive-service"<cognitive-services-speech-sdk@noreply.github.com>; 
抄送: "Nightsong"<wall137@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [Azure-Samples/cognitive-services-speech-sdk] delete_Recognizer;line: -2; Exception: java.util.concurrent.TimeoutException:  (#208)




Hi @wall3001,
 
could you give a bit more details:
  
which code (or sample) are you running.
 
does this happen always, or only sometimes.
 
which OS version / API level version are you running with? Officially, we're supporting API level 23 or up (Android 6.0 Marshmallow).
  
Best, Mark

**Comment by mahilleb-msft** [comment]
Hi @wall3001, is this correlated with the error above? If it's a new issue, please open a new item. Otherwise it's hard to keep those apart :|

If this errors occurs with the above problem (before the closed), do you have a session ID to share? Is there any indication that it might related (or caused) by networking (in which case #191 may be related)?

**Comment by wall3001** [comment]
SessionId:75C23029B4A0F1F48867B42B433F162E ResultId:467878EF42902714BBD2A20832288602 I got it just now.




------------------ 原始邮件 ------------------
发件人: "Mark Hillebrand"<notifications@github.com>; 
发送时间: 2019年4月18日(星期四) 下午4:28
收件人: "Azure-Samples/cognitive-service"<cognitive-services-speech-sdk@noreply.github.com>; 
抄送: "Nightsong"<wall137@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [Azure-Samples/cognitive-services-speech-sdk] delete_Recognizer;line: -2; Exception: java.util.concurrent.TimeoutException:  (#208)




Hi @wall3001, is this correlated with the error above? If it's a new issue, please open a new item. Otherwise it's hard to keep those apart :|
 
If this errors occurs with the above problem (before the closed), do you have a session ID to share? Is there any indication that it might related (or caused) by networking (in which case #191 may be related)?

**Comment by wolfma61** [comment]
You are trying to translate an audio file?
Are you using RecognizeOnce or RecognizeContinuous?
How long is the file? It starts with some extended silence period? 
Anything else you can tell us about the file? Length and other content?

**Comment by wall3001** [comment]
1、pushAudioSteam push AudioRecord PCM data
2、RecognizeContinuous 
3、Always recording




------------------ 原始邮件 ------------------
发件人: "Wolfgang Manousek"<notifications@github.com>; 
发送时间: 2019年4月18日(星期四) 晚上7:15
收件人: "Azure-Samples/cognitive-service"<cognitive-services-speech-sdk@noreply.github.com>; 
抄送: "Nightsong"<wall137@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [Azure-Samples/cognitive-services-speech-sdk] delete_Recognizer;line: -2; Exception: java.util.concurrent.TimeoutException:  (#208)




You are trying to translate an audio file?
 Are you using RecognizeOnce or RecognizeContinuous?
 How long is the file? It starts with some extended silence period?
 Anything else you can tell us about the file? Length and other content?

**Comment by wall3001** [comment]
SDK1.5.1 also has this bug when used on weak network.

**Comment by wall3001** [comment]
And the timeout times is 10 seconds.

**Comment by wall3001** [comment]
@wolfma61

**Comment by wolfma61** [comment]
it is still difficult to reproduce you behavior in this code. 
Is it correct to assume that you see this behavior once you stop the recognition and are trying to close the recognizer?

and this is only happening on the mobile network with possible bad connectivity?

**Comment by wolfma61** [comment]
no feedback - closing
