### ISSUE TITLE
CreateBatchSynthesis request returning 400 status code

### ISSUE THREAD

**Issue by sushantjadhav21** [Azure-Samples/cognitive-services-speech-sdk#2084]
- batchsynthesis API used /api/texttospeech/3.1-preview1/batchsynthesis

- Additional information as shown below
When creating the Create Batch Synthesis request we are getting the 400 response status code back from API
{
    "$type": "TextToSpeech.BatchSynthesis.BatchSynthesisException, TextToSpeech.BatchSynthesis",
    "HttpStatusCode": 400,
    "ErrorResponse": "{\r\n  \"errors\": {\r\n    \"Properties.DestinationContainerUrl\": [\r\n      \"The property DestinationContainerUrl is an expired SAS URI.\"\r\n    ]\r\n  },\r\n  \"type\": \"https://tools.ietf.org/html/rfc7231#section-6.5.1\",\r\n  \"title\": \"One or more validation errors occurred.\",\r\n  \"status\": 400,\r\n  \"traceId\": \"00-1ac0b26f4d85dab1d37f2e3d3a7e0f7c-0fd76a8d816bf923-00\"\r\n}",
    "Message": "CreateBatchSynthesisAsync request failed.",
    "Data": {
       "$type": "System.Collections.ListDictionaryInternal, System.Private.CoreLib"
    }
} 

SAS URL expires in 10 minutes

We haven't made any changes to this integration in months and it stopped working from 07/13/2023. Could you please check what could be the problem?

**Expected behavior**

Create batch synthesis request should be accepted withourt any error.

**Version of the Cognitive Services Speech SDK**

/api/texttospeech/3.1-preview1/batchsynthesis

**Platform, Operating System, and Programming Language**
.NET Azure functions

**Comment by Ling-Cao** [comment]
Can you provide one of the SAS token without the **sig** part? 

e.g. https:// xxxxxx.blob.core.windows.net/batch-synthesis-output-test?sv=2021-04-10&st=2023-09-22T03%3A03%3A32Z&**se=2023-09-22T04%3A03%3A00**Z&sr=c&sp=rwl&sig=*******

Or, can you double check the **"se=" parameter** in your `DestinationContainerUrl` with the **timestamp** you are creating the job to see if it's really expired?

**Comment by sushantjadhav21** [comment]
Thank you for your help! This issue is resolved after adding the StartOn datetime. Has there been any change the way batch synthesis validates the DestinationContainerUrl.

**Comment by Ling-Cao** [comment]
> Thank you for your help! This issue is resolved after adding the StartOn datetime. Has there been any change the way batch synthesis validates the DestinationContainerUrl.

Great. We have bug fixes addressing the absence of validation to ensure the `DestinationContainerUrl` is valid before the job being processed.
