### ISSUE TITLE
Speech: Xamarin.iOS 17 noticeable delays on subsequent calls to StartSpeakingTextAsync - Speech Synthesizer

### ISSUE THREAD

**Issue by pasha-o** [Azure-Samples/cognitive-services-speech-sdk#2085]
**IN ORDER TO ASSIST YOU, PLEASE PROVIDE THE FOLLOWING:**

Apple just released iOS 17 -  the published Xamarin forms application now behaves strangely with excessive delays with subsequent calls to StartSpeakingTextAsync. eventually, they all go through but the delay is noticeable.

this only happens on the new release of ios 17 and prior versions are ok. This also doesn't happen on Android.

the behavior only happens when in the middle of synthesizing, you cancel the stream by calling StopSpeakingAsync(); and again call SpeakTextAsync for some reason, there is going to be a 13-second delay to hear the next prompt. If you allow the first prompt to be completed and not canceled then delay doesn't happen.

**the issue resides within StopSpeakingAsync() call and needs to be looked at closely why it take 13 seconds to discard audio data**

here is the code in production
public void init()
{
`                _speechClient = new SpeechApiClient(SubscriptionKey, SpeechRegion.WestUS2);
                _speechClient.AuthenticateWithToken(true);
                _speechConfig = SpeechConfig.FromSubscription(SubscriptionKey, "westus2");
                _synth = new SpeechSynthesizer(_speechConfig);
{

public async Task TextToSpeech(string text)
{
                _speechConfig.SpeechSynthesisLanguage = "en-US";
                _speechConfig.SpeechSynthesisVoiceName = "en-US-JennyNeural";
                 **var result = await _synth.SpeakTextAsync(text).ConfigureAwait(false);** / /delay will happen here now, 
}
        public async Task CancelSpeech()
        {
            await _synth.StopSpeakingAsync();
        }

**Expected behavior**

there shouldn't be any delay.

**Version of the Cognitive Services Speech SDK**

Microsoft.CognitiveServices.Speech 1.32.1
Xamarin.iOs & Xamarin.Mac.SDK:16.4.0.16
Xamarin: 17.8.0.118
Xamarin.Forms:5.0.0.8526
Visual Studio: Version 17.8.0 Preview 2.0

**Platform, Operating System, and Programming Language**

 - OS:  iOS17
 - Hardware - iPhone simulator x86_64, and iPhone arm64
 - Programming language: C#

**Comment by yulin-li** [comment]
Thanks for reporting this issue. We will investigate this issue.

**Comment by yulin-li** [comment]
duplication of #2081

**Comment by trrwilson** [comment]
Per @yulin-li noting the earlier issue filed, closing this one to keep the conversation on a single thread.
