### ISSUE TITLE
sr-Latn-RS-NicholasNeural voice does not work

### ISSUE THREAD

**Issue by matyushinleonid** [Azure-Samples/cognitive-services-speech-sdk#2086]
sr-Latn-RS-NicholasNeural voice does not work

```python
ssml = (
            "<speak version='1.0' xmlns='http://www.w3.org/2001/10/synthesis' xml:lang='sr-Latn-RS'>"
            "<voice name='sr-Latn-RS-NicholasNeural'>"
            "Kad biste samo znali da će moć mračne strane biti jedan nikada vam nije rekao šta se dogodilo tvom ocu.}"
            "</voice>"
            "</speak>"
        )
response = client.speak_ssml(ssml)
print(response.reason.name, response.cancellation_details.error_details)
```
`Canceled Connection was closed by the remote host. Error code: 1007. Error details: Unsupported voice sr-Latn-RS-NicholasNeural. USP state: TurnStarted. Received audio size: 0 bytes.`

While, say, sr-Latn-RS-SophieNeural works just fine

```python
ssml = (
            "<speak version='1.0' xmlns='http://www.w3.org/2001/10/synthesis' xml:lang='sr-Latn-RS'>"
            "<voice name='sr-Latn-RS-SophieNeural'>"
            "Kad biste samo znali da će moć mračne strane biti jedan nikada vam nije rekao šta se dogodilo tvom ocu.}"
            "</voice>"
            "</speak>"
        )
response = client.speak_ssml(ssml)
print(response.reason.name)
```
`SynthesizingAudioCompleted `

**Comment by trrwilson** [comment]
@matyushinleonid -- thanks for contacting us.

I observe that same error for `sr-Latn-RS-SophieNeural`, too, and I believe our [language support page](https://learn.microsoft.com/azure/ai-services/speech-service/language-support?tabs=tts) is incorrect. From using the `GetVoicesAsync()` API via the SDK, I see that these are the two ShortNames of the available Serbian voices:

```
sr-RS-SophieNeural
sr-RS-NicholasNeural
```

(Note: the LATN script designator is not present)

Could you please attempt with those reported voice names to see if it resolves the issue?

@yulin-li -- would you agree with the assessment that our documented names are inaccurate? I don't see the `latn` substring in any voice's `ShortName` as reported via `GetVoicesAsync().`

**Comment by matyushinleonid** [comment]
```
client = speechsdk.SpeechSynthesizer(speech_config=speech_config, audio_config=audio_config)
client.get_voices_async().get()
```
returns `-Latn` voices as well. I use `azure-cognitiveservices-speech 1.31.0` btw.

Regarding your advice to remove LATN script designator. Well, I'm not sure if it is a solution: Serbian can be written using Cyrillic or Latin alphabets, and I believe that `sr-RS` is for Cyrillic while `sr-Latn-RS` if for Latin.

Try to synthesize smthng like `Jedan dva tri četiri pet` via sr-RS. It sounds terrible (like it has heavy English accent), while `Један два три четири пет` sounds okay.

**Comment by trrwilson** [comment]
@matyushinleonid -- thanks! I missed the important note that these voices are in preview in only a few regions, which is why I only saw the Cyrillic voices. And totally understood that they're not a replacement when you have Latin script.

@yulin-li , I can reproduce this reported behavior on both `eastus` as well as `westeurope`; `sr-Latn-RS-NicholasNeural` is reported as a voice name by `GetVoicesAsync`, but reports unsupported when using it (Sophie works on both). Could you please check on Nicholas?

**Comment by yulin-li** [comment]
@M-Hietala thanks for reporting this issue. We were on Chinese National Day holiday so sorry for the delayed response.

@Kerry-LinZhang could you help to check?

**Comment by Kerry-LinZhang** [comment]
Sure, @matyushinleonid we are working on it, and it will be fixed in the following two week, we are targeting ETA 10/27 to release our fix on it.

**Comment by Kerry-LinZhang** [comment]
Hi @matyushinleonid we have fixed and released it, please try again, and feel free to let us know if there is still any problem, thanks!
