### ISSUE TITLE
synthesize audio output is not stable on IOS. Audio is coming out of earpiece instead of speaker

### ISSUE THREAD

**Issue by Mr-Cold** [Azure-Samples/cognitive-services-speech-sdk#2087]
**IN ORDER TO ASSIST YOU, PLEASE PROVIDE THE FOLLOWING:**

- Speech SDK log taken from a run that exhibits the reported issue. 
See [instructions on how to take logs](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging).
N/A

- A stripped down, simplified version of your source code that exhibits the issue. Or, preferably, try to reproduce the problem with one of the public samples in this repository (or a minimally modified version of it), and share the code.

- If relevant, a WAV file of your input audio.

- Additional information as shown below

**Describe the bug**
In our NextJs app, we are using SpeechSynthesizer.speakTextAsync to speak out text messages. It works well on desktop and Android, but we consistently encounter the bug that the audio comes out of the earpiece instead of speaker, we tried both on Chrome and Safari and multiple IOS devices both observed the same behavior. One of the device will first output from the speaker but then for the second time it switches to the earpiece. Not sure if this is related to we are also using SpeechRecognizer listening on the input. We hope the output can be consistenly being outputed from the speaker. Here are the code snippet we have for the textToSpeech 
```
const textToSpeechAsync = async (text: string) => {
    const tokenObj = await getTokenOrRefresh();
    const speechConfig = speechsdk.SpeechConfig.fromAuthorizationToken(
      tokenObj.authToken,
      tokenObj.region
    );
    speechConfig.speechSynthesisVoiceName = 'en-US-AIGenerate2Neural';
    // Define a default audio output configuration.
    const audioConfig = speechsdk.AudioConfig.fromDefaultSpeakerOutput();

    const synthesizer = new speechsdk.SpeechSynthesizer(
      speechConfig,
      audioConfig
    );

    await new Promise((resolve, reject) => {
      setIsTalking(true);
      synthesizer.speakTextAsync(
        text,
        (result) => {
          if (result) {
            resolve(result);
          } else {
            appInsights.trackTrace({
              message: 'Text to speech failed',
              severityLevel: SeverityLevel.Error,
              properties: {
                sessionId
              }
            });
            reject('Text to speech failed.');
          }
          setIsTalking(false);
        },
        (error) => {
          reject(error);
          setIsTalking(false);
        }
      );
    })
      .then((result) => {
        // console.log('Speech synthesis result:');
        // console.log(result);
      })
      .catch((reason) => {
        // console.log('Promise rejected with reason: ' + reason);
        appInsights.trackTrace({
          message:
            'Text to speech Promise rejected with reason:' + (reason as string),
          severityLevel: SeverityLevel.Error,
          properties: {
            sessionId
          }
        });
      })
      .finally(() => {
        synthesizer.close();
      });
  };
  ```

**Expected behavior**

We are hoping to have audio output on the IOS device to be consistenly coming out of the speaker instead of earpiece and being stable on speaker. Sometimes it will come out of speaker for the first time and then for the next time the code gets triggered it comes out of earpiece and stays at outputing from earpiece. 

**Version of the Cognitive Services Speech SDK**

"microsoft-cognitiveservices-speech-sdk": "^1.32.0",

**Platform, Operating System, and Programming Language**

 - OS: IOS
 - Hardware - iPhone 12, iPhone 13
 - Programming language: Typescript, NextJS
 - Browser : Chrome & Safari

**Additional context**

we are happy to privde a demo link of our product via DM or setup a call to further debug on this.

**Comment by trrwilson** [comment]
Hello @Mr-Cold -- thanks for contacting us.

Tagging @glharper : are you aware of any strategies to handle/stabilize device selection given the Node.js limitations around explicit device selection (I believe NextJs is built atop Node)?

Generally, "default audio output" will bind to the system-specified default device. I suspect that something like a hybrid input/output device profile switch (e.g. A2DP) for a capture operation (the recognition) is "bumping" the output device to become the default output device for the system, and the Speech SDK is faithfully following that environment-specified default.

In most situations, the recommended course is to use explicit device selection as outlined on this page:
https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-select-audio-input-devices

Node.js doesn't present device identifiers in the same manner, however, and I suspect NextJs may have the same propagated limitation that bars that strategy.

As a potential mitigation: I believe device acquisition is "sticky" once an instance has been initialized, so creating (and maybe "using" it via a mocked operation) may help lock in the desired output device prior to a hybrid I/O device stealing default status after a capture operation.

@glharper may be able to recommend more comprehensive strategies.

**Comment by glharper** [comment]
@Mr-Cold (Note that JS Speech SDK explicitly does not support audio I/O in Node. All support for mic input and speaker output assumes access to web APIs like MediaDevices and AudioContext.) Using the [MediaDevices.enumerateDevices API](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices) seems like your best bet here. The Speech SDK doesn't have any control over which speaker output iOS Chrome designates as default.

**Comment by trrwilson** [comment]
Given the answers around Node and the suggested enumerateDevices angle, I'll close this issue as answered to keep tickets tidy. If there's more we can help with, please reopen the issue or open a new item referencing this one. Thank you!
