### ISSUE TITLE
How to detect when visemes are received completely?

### ISSUE THREAD

**Issue by ashikns** [Azure-Samples/cognitive-services-speech-sdk#2093]
I'm using the C# sdk on on a ASP .Net 7 app. `VisemeReceived` event sometimes fires after the `SynthesisCompleted` event, and there is no `VisemeCompleted` event so how to identify when all visemes have been received? Note that I'm taking the result data from `AudioData` field of the synthesizer (i.e. I am not waiting for the audio playback duration). The goal is to take both audio data and viseme data and send it as api response.

Similar question asked here but no answers: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1832

Cognitive SDK (nuget): 1.32.1

 - OS: Running on Azure App Service (Windows)
 - Hardware - 32 bit
 - Programming language: C#

**Comment by yulin-li** [comment]
Hi, thanks for reporting this issue and sorry for the delayed response as I took vacation last week. You are right that we don't have a signal to indicate the viseme data have been received. We will discuss internally and come back to you.

**Comment by yulin-li** [comment]
The issue will be fixed in next release (1.33.0), where the `SynthesisCompleted` is guaranteed to be fired after all metadata events.

**Comment by pankopon** [comment]
Closed as fixed.
