### ISSUE TITLE
diarization-7 seconds 

### ISSUE THREAD

**Issue by AbhinavShaw09** [Azure-Samples/cognitive-services-speech-sdk#2094]
The service performs best with at least 7 seconds of continuous audio but this is not the ideal case for most of the cases , can u guys improve this

**Comment by jhakulin** [comment]
@AbhinavShaw09 Thanks for the feedback, improving the performance here is under planning currently on our service teams. There is no ETA yet. The service currently requires 7seconds audio to be collected from the speaker during the conversation in order to be able to diarize the speaker.

**Comment by pankopon** [comment]
Closed since no further update in 3 weeks. Under consideration as a future improvement, no ETA.
