### ISSUE TITLE
handling audio buffer stream for speech to text nodejs

### ISSUE THREAD

**Issue by voxrox** [Azure-Samples/cognitive-services-speech-sdk#2097]
Hi I am getting data externally in the form of PCMU(8000, 8, 2) which is a audio buffer streaming. I have tried it using 
const waveFormat = AudioStreamFormat.getWaveFormatPCM(8000, 8, 2);
const audioStreamCallback = {
                        read: (dataBuffer: any) => {
                            
                            const bytesRead = Math.min(dataBuffer.byteLength, frame.audio.data.length);
                
                            // Copy the binary data to the dataBuffer
                            for (let i = 0; i < bytesRead; i++) {
                                dataBuffer[i] = frame.audio.data[i];
                                //  console.log("dataBuffer",dataBuffer);
                            }
                            return bytesRead;
                        },
                        close: () => {
                            // Perform any cleanup if needed
                        },
                    };
                
                    const audioStream = AudioInputStream.createPullStream(audioStreamCallback, waveFormat);
                  const speechConfig = SpeechConfig.fromSubscription("key", "region");
                
                    // Create an audio configuration from the audio stream
                    const audioConfig = AudioConfig.fromStreamInput(audioStream);
                
                    const speechRecognizer = new SpeechRecognizer(speechConfig, audioConfig);
                
                    // Recognize the speech
                    speechRecognizer.recognizeOnceAsync(
                        (result: any) => {
                            console.log('Result:', result.reason);
                
                            if (result.reason === ResultReason.RecognizedSpeech) {
                                console.log('Recognized text:', result.text);
                            } else if (result.reason === ResultReason.NoMatch) {
                                console.log('No speech could be recognized.');
                            } else if (result.reason === ResultReason.Canceled) {
                                
                                console.log('Speech recognition canceled:');
                            }
                        },
                        (error: any) => {
                            console.error('Speech recognition error:', error);
                        }
                    );
                    I am getting result
                    No speech could be recognized.
Result: 0. but it is not recognizing or converting speech to text

**Comment by glharper** [comment]
@voxrox Thank you for using the JS Speech SDK and writing this issue up. PCMU translates to MuLaw in our SDK, so could you try using: `const waveFormat = AudioStreamFormat.getWaveFormat(8000, 8, 2, AudioFormatTag.MuLaw);` and see if that works?

**Comment by varunraj-tuduru** [comment]
Hi still showing response with result 0
No speech could be recognized.

**Comment by voxrox** [comment]
@glharper still showing same 
No speech could be recognized.

**Comment by glharper** [comment]
@voxrox Here is pullStream code adapted from tests in the [JS SDK repo](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/6848253d1d9b619dd497ce302ee1ee6212f56b20/tests/Utilities.ts#L99C1-L129C12):
```
    let bytesSent = 0;

    const pullStream = AudioInputStream.createPullStream(
    {
        close: () => { return; },
        read: (buffer: ArrayBuffer): number => {

            const copyArray: Uint8Array = new Uint8Array(buffer);
            const frameLength = frame.audio.data.length;
            const start: number = bytesSent;
            const end: number = buffer.byteLength > (frameLength - bytesSent) ? (frameLength) : (bytesSent + buffer.byteLength);
            copyArray.set(new Uint8Array(frame.audio.data.slice(start, end)));
            const readyToSend: number = (end - start);
            bytesSent += readyToSend;

            if (readyToSend < buffer.byteLength) {
                bytesSent = 0;
            }

            return readyToSend;
        },
    });
  ```

**Comment by voxrox** [comment]
@glharper still same issue I have tried to replace this and tested

**Comment by glharper** [comment]
@voxrox If you could record a sample wav file that's not being recognized properly, and share it here, perhaps we can figure out what's going on? Also, do 8K, 8-bit, stereo PCMU wav files get recognized properly for you using AudioConfig.fromWavFileInput()?

**Comment by voxrox** [comment]
@glharper please download .wav file http://www.sndup.net/mdh5 as I was not able to upload audio file here.
Yes from audiofile speech to text it works. 

thanks

**Comment by voxrox** [comment]
Here is the sample buffer stream
<Buffer fe ad fe af fe b8 fe cc fe 57 fe 4c fe 47 fe 4a fe 57 fe 3f fe 2d fe 23 fe 18 fd 18 fd 2b fd c1 fd a6 fd a6 fe c0 fe 40 ff 3c ff 3d ff 4f ff c8 7e b3 ... 3150 more bytes>

**Comment by glharper** [comment]
Closing as this has been responded to via customer support
