### ISSUE TITLE
How to obtain the real-time recognition results in recongnizing?

### ISSUE THREAD

**Issue by Bruce337f** [Azure-Samples/cognitive-services-speech-sdk#2099]
```
    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
    speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))
    # stop continuous recognition on either session stopped or canceled events
    speech_recognizer.session_stopped.connect(stop_cb)
    speech_recognizer.canceled.connect(stop_cb)
```
What I mean is how to obtain the generated speech recognition results through the evt event to achieve the same effect as Microsoft's official speech-to-text interface?
Do I need to add or modify some parameters?

**Comment by rhurey** [comment]
The problem in the 2nd block of code is that the if statement is conditioned on the result reason being speechsdk.ResultReason.Recogniz**ed**Speech, but the recognizing event handler will only get speechsdk.ResultReason.Recogniz**ing**Speech result reasons.

If that's not the cause of the problem, can you share some more information about the code that's having problems?
