### ISSUE TITLE
Missing CANCELED-Event "Too many requests"

### ISSUE THREAD

**Issue by stoney95** [Azure-Samples/cognitive-services-speech-sdk#210]
Hi,

I'm working with the python `azure-speech-sdk 1.3.0` using the `speech_recognizer` with `continous_recognition`. 
I'm trying to transcript multiple files (hundreds or thousand) and therefore I'm starting a lot of sessions to process as many files as possible in parallel. Usually the `speech_recognizer` fired a CANCELED-Event with the message "Too many requests" and `Error-Code: 3` and I used this to handle how many parallel requests I'm starting. This worked so far but now I'm not receiving this event anymore - instead I'm getting two kinds of errors: 

```
1. WebSocket operation failed. Internal error: 3. Error details: WS_ERROR_UNDERLYING_IO_ERROR. Reason: CancellationReason.Error
2. Connection was closed by the remote host. Error code: 1000. Error details: Idle timeout. Reason: CancellationReason.Error
```

The cognitive service is located in `westeurope` and has pricing tier `Standard`.
Did anything change on the API or why do I not receive the original message anymore? And is there a different why to dynamically get the limit of parallel requests?

**Comment by wolfma61** [comment]
There is a maximum number of parallel request you can send. I think the default is 20. You can ask support to have this number elevated. 

If you have lots of files, I would recommend the batch transcription service. This might be more efficient

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription
and
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch

thx
Wolfgang

**Comment by stoney95** [comment]
Thanks for the fast reply! 
Do you mean by asking the support for an adjustment to increase the number of parallel requests in general or would this be done specifically for my subscription?

I just tried the `batch-transcription-service` and I hope I'm free to bring up a suggestion: It would be nice to be able to install the package `swagger_client` using pip. 
Also when following the instructions from [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python) I ran into an error trying to import `swagger_client`:

```
>>> import swagger_client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/simons/anaconda3/envs/call-analyzer-ap1/lib/python3.6/site-packages/swagger_client/__init__.py", line 19, in <module>
    from swagger_client.api.custom_speech_accuracy_tests_api import CustomSpeechAccuracyTestsApi
  File "/Users/simons/anaconda3/envs/call-analyzer-ap1/lib/python3.6/site-packages/swagger_client/api/__init__.py", line 6, in <module>
    from swagger_client.api.custom_speech_accuracy_tests_api import CustomSpeechAccuracyTestsApi
  File "/Users/simons/anaconda3/envs/call-analyzer-ap1/lib/python3.6/site-packages/swagger_client/api/custom_speech_accuracy_tests_api.py", line 21, in <module>
    from swagger_client.api_client import ApiClient
  File "/Users/simons/anaconda3/envs/call-analyzer-ap1/lib/python3.6/site-packages/swagger_client/api_client.py", line 27, in <module>
    import swagger_client.models
  File "/Users/simons/anaconda3/envs/call-analyzer-ap1/lib/python3.6/site-packages/swagger_client/models/__init__.py", line 23, in <module>
    from swagger_client.models.endpoint import Endpoint
  File "/Users/simons/anaconda3/envs/call-analyzer-ap1/lib/python3.6/site-packages/swagger_client/models/endpoint.py", line 19, in <module>
    from swagger_client.models.model import Model  # noqa: F401,E501
  File "/Users/simons/anaconda3/envs/call-analyzer-ap1/lib/python3.6/site-packages/swagger_client/models/model.py", line 20, in <module>
    from swagger_client.models.model import Model  # noqa: F401,E501
ImportError: cannot import name 'Model'
```

Is there anything I can do about this error?

**Comment by chlandsi** [comment]
The concurrency limit is specific to each subscription.

Regarding the error with the swagger client: This seems to be a [known issue](https://github.com/swagger-api/swagger-codegen/issues/8882) with the autogenerated swagger bindings. You can work around it by deleting the offending lines (`from swagger_client.models.model import Model  # noqa: F401,E501` and another, similar one) from the file in the autogenerated package.

@PanosPeriorellis for attention.

**Comment by stoney95** [comment]
Who do I have to ask to adjust the concurrency limit? 

How is the provided example a batch service? As far as I understand the documentation you can provide a link to one specific audio-file. Would this include merging all audio-files into one and then transcribe this single file?

**Comment by PanosPeriorellis** [comment]
Are you looking to use the SDK or REST. The concurrencly limit of an endpoint is relevant for the real time usage of the endpoint. batch does not require you to set up an endpoint

**Comment by stoney95** [comment]
I'm looking for a Batch Transcription, but I implemented a service using the continous_recognition (real transcription). So I have two options: Elevating the concurrency limit so this works efficient enough or switching to the batch transcription. 
Also I think the batch-service is far from being ready to be used.

**Comment by PanosPeriorellis** [comment]
Through our support channels you can request for us to increase the concurrency limit. Batch has been production ready for sometime now.
