### ISSUE TITLE
What is your roadmap for Cognitive Speech Services?

### ISSUE THREAD

**Issue by Trunksome** [Azure-Samples/cognitive-services-speech-sdk#2102]
Hi there! I integrated text-to-speech and speech-to-text into our product and I'm happy with the results. I am especially fond of how many different languages you support and the quality of the speech synthesis is also still quite impressive.

With that being said, I do wonder if there is any place where you share your plans for the future? I check the news page regularly, but it would be really helpful to have an idea of what you are planning to extend on in the coming months. In my case, i'm specifically curious about:
- There is some pressure to migrate speech detection to **Whisper**. I do believe that giving a prompt with the speech recognition is incredibly useful, and so much harder with just phrase lists. I saw that Whisper technology is starting to be used by batch transcription, and i would love to see it in regular speech recognition too. What are your plans here?
- Do you have plans do support more languages in your **pronunciation assessment**? I would love to integrate the service, but it is hard to know if you will eventually extend the supported languages (so that it makes sense for me to build the feature).

Thank you!

**Comment by rhurey** [comment]
Right now Whisper isn't optimized for real-time scenarios that the speech service targets, so there aren't any plans I can share about making it an option for real-time speech.

I've asked someone from our pronunciation assessment team about their language plans.

**Comment by rhurey** [comment]
On a language support, there will be new languages announced soon, with more in development and private preview. If you'd like to reach out directly to the team at mspafeedback@microsoft.com and ask about particular languages or share ones you'd be interested in.

**Comment by rhurey** [comment]
I'm going to close this as I think the questions have been answered, if not, comment / reopen. Thanks!
