### ISSUE TITLE
When setting specific languages=[en-US, zh-CN-sichuan], recognizeOnceAsync not working

### ISSUE THREAD

**Issue by mackwu828** [Azure-Samples/cognitive-services-speech-sdk#2105]
start recognize use recognizeOnceAsync , and set languages=[en-US, zh-CN-sichuan] , but task.get return null. please help..
```
	pushStream = AudioInputStream.createPushStream();
	// customize audio record
        AudioRecordManager.getInstance().startRecord(audioChunk -> {
            pushStream.write(audioChunk.toBytes());
        });
        AudioConfig audioConfig = AudioConfig.fromStreamInput(pushStream);
        AutoDetectSourceLanguageConfig autoDetectSourceLanguageConfig = AutoDetectSourceLanguageConfig.fromLanguages(languages);
        SpeechRecognizer speechRecognizer = new SpeechRecognizer(speechConfig, autoDetectSourceLanguageConfig, audioConfig);
        task = speechRecognizer.recognizeOnceAsync();
```

Currently known language combination exceptions:
1. English (United States)/Chinese（Southwestern Mandarin，Simplified）
2. English (United States)/Chinese（Wu，Simplified）

**Comment by mackwu828** [comment]
[logfile.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/12891015/logfile.txt)

**Comment by rhurey** [comment]
Thanks for the log file, that should make determining what happened easier.

If you could help me out just a bit, there's ~20 recognition calls in the file, and the first one looks to have failed generating a unique ID for the connection, many of the others (I didn't check each) seem to have worked. Is there a specific call that was problematic?

**Comment by mackwu828** [comment]
[logfile.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/12926717/logfile.txt)

this logfile only contains one recognition

**Comment by jpalvarezl** [comment]
Hi,

After close inspection, as you can see from line 791 in the log you've linked, the reason for the lack of detection is that the language code supplied is not supported.

```
[848896]: 19854ms SPX_TRACE_INFO:  usp_connection.cpp:908 TS:8415, TransportError: connection:0x9e33e650, code=2, string=Connection was closed by the remote host. Error code: 1007. Error details: Status(StatusCode="InvalidArgument", Detail="Language Identification doesn't support zh-cn-sichuan")
```

[Here](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/language-support?tabs=language-identification) you can find the list of the languages supported for the language identification feature, for your reference.

**Comment by mackwu828** [comment]
https://learn.microsoft.com/en-us/azure/ai-services/speech-service/language-support?tabs=stt

why not use Speech to text Language

**Comment by jpalvarezl** [comment]
From your original code snippet it seems like you are using the language identification feature:

```
AutoDetectSourceLanguageConfig autoDetectSourceLanguageConfig = AutoDetectSourceLanguageConfig.fromLanguages(languages);
```

Which does not support `zh-cn-sichuan` as you can see from the log and the list in the documentation:  https://learn.microsoft.com/en-us/azure/ai-services/speech-service/language-support?tabs=language-identification

**Comment by mackwu828** [comment]
i wanna support two languages for recognition，but speechConfig can only set one language. so i use AutoDetectSourceLanguageConfig instead.
```
speechConfig.setSpeechRecognitionLanguage("en-US")
```
