### ISSUE TITLE
When I run the Unity sample on an Android phone, I get an error that the .so file unable to lookup.

### ISSUE THREAD

**Issue by ManabuKamiya** [Azure-Samples/cognitive-services-speech-sdk#2107]
**Describe the bug**
When I run the Unity sample on an Android phone, I get an error message "Failed to load native plugin: Unable to lookup library path for 'Microsoft.CognitiveServices.Speech.core.so'".

**To Reproduce**
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/unity/from-microphone
↑
I built this sample project and ran it on an Android phone.
push "Recognize!"button.

Cognitive Services Speech SDK version : Microsoft.CognitiveServices.Speech.1.32.1.unitypackage
Android phone : Galaxy S20+ 5G
Android OS version : 13
Unity version : 2020.3.36.f1

**Additional context**
I have confirmed that there is a .so file in the lib folder within the apk file.

**Comment by jhakulin** [comment]
@ManabuKamiya Thanks for the report, could you please confirm that you have libMicrosoft.CognitiveServices.Speech.core.so under the **YourApkName.apk\lib\arm64-v8a** folder? I assume Galaxy S20+ 5G is having ARM64 chipset inside.

**Comment by ManabuKamiya** [comment]
@jhakulin Yes. That's right.

**Comment by jhakulin** [comment]
@ManabuKamiya Ok, if you have the .so files under arm64-v8a folder in the apk, the error you are facing is unexpected.
I'll try to see if I can find Android 13 device or try with emulator to see if problem can be reproduced.

**Comment by ManabuKamiya** [comment]
@jhakulin  
I am sorry. I found that the SubscriptionKey and Region values ​​were not set correctly on the Android device.
I can now confirm that it works correctly.
I apologize for the inconvenience.

**Comment by jhakulin** [comment]
@ManabuKamiya Thanks for information! Closing the case
