### ISSUE TITLE
Using Continuous Recognition with Microphone - Console App vs Winforms 

### ISSUE THREAD

**Issue by GaryBeasley88** [Azure-Samples/cognitive-services-speech-sdk#2108]
Hello! I have been testing the ContinuousRecognitionFromDefaultMicrophoneWithMASEnabled() sample app to recognize long running dictation and show the user in Winforms the result. It works in the Console App example on my Win10 machine using VS2019. 
However, when I take essentially the same code and try to initialize it by a button press in Winforms, the following recognizer init gives a very cryptic error:

           using (var audioProcessingOptions = AudioProcessingOptions.Create(AudioProcessingConstants.AUDIO_INPUT_PROCESSING_ENABLE_DEFAULT))
            using (var audioInput = AudioConfig.FromDefaultMicrophoneInput(audioProcessingOptions))
            {
                // Creates a speech recognizer.
                **using (var recognizer = new SpeechRecognizer(config, audioInput))**

Error:
Exception with an error code: 0x1b (SPXERR_RUNTIME_ERROR)

My research seems to point to enabling microphone access, but I don't understand what a console app ( where it works great ) has more access than a Winforms app. 

Stumped!!

**Comment by ralph-msft** [comment]
SPXERR_RUNTIME_ERROR is a more generic error code that could have multiple causes and is not necessarily related to not having access to the microphone. Could you please capture and share your SDK logs so we can diagnose this issue further? You can find instructions on how to enable logging here:
https://learn.microsoft.com/azure/ai-services/speech-service/how-to-use-logging

**Comment by pankopon** [comment]
Closed since no update in 3 weeks, please open a new issue if further support is needed.
