### ISSUE TITLE
Azure TTS does not synthesize empty string correctly

### ISSUE THREAD

**Issue by matyushinleonid** [Azure-Samples/cognitive-services-speech-sdk#2111]
When I try to synthesize an empty string (`text=""`), or string that contains only punctuation marks (say, `text="."`) I get incorrect (invalid) results (and do not get any error codes):
* speech sdk returns an empty bytestring, which is not a correct .wav content
* I tried raw REST api as well, and it returns a bytestring that contains wav-like headers, however this data is not valid (for example, [pydub](https://github.com/jiaaro/pydub) does not parse it)

I believe that in both cases you should return a valid 0-length wav data.

Hope the following code snippet will illustrate the problem:
```python
ssml = (
    f"<speak version='1.0' xmlns='http://www.w3.org/2001/10/synthesis' xml:lang='en-US'>"
    f"<voice name='en-US-JennyNeural'>"
    f""
    f"</voice>"
    f"</speak>"
)

# sdk
speech_config = speechsdk.SpeechConfig(
    subscription=secret, 
    region="westeurope",
    speech_recognition_language='en-US'
)

audio_config = speechsdk.audio.AudioOutputConfig(filename='/dev/null')
client = speechsdk.SpeechSynthesizer(speech_config=speech_config, audio_config=audio_config)
response = client.speak_ssml(ssml)
print((response.reason, response.audio_data))
# (<ResultReason.SynthesizingAudioCompleted: 9>, b'')


# REST api
headers = {
    "Authorization": "Bearer " + token,
    "Content-Type": "application/ssml+xml",
    "X-Microsoft-OutputFormat": "riff-24khz-16bit-mono-pcm",
    "User-Agent": "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
}
response = requests.post(
    "https://westeurope.tts.speech.microsoft.com/cognitiveservices/v1", headers=headers, data=ssml.encode()
)
synthesised_wav = response.content
print((response.status_code, synthesised_wav))
# (200, b'RIFF$\x00\xff\x7fWAVEfmt \x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00data\x00\x00\xff\x7f')
try: 
    pydub.AudioSegment(synthesised_wav)
except pydub.audio_segment.CouldntDecodeError as exception:
    print(exception)
# Unknown audio format 0x0 in wav data
```

**Comment by chschrae** [comment]
Hi there!

Thanks for reaching out to us. 

Are you saying you are expecting there to be a wav header for a 0 length audio to be returned? I just want to clarify that is the result you expect.

@yulin-li  are you aware of this being desired behavior or not?

**Comment by matyushinleonid** [comment]
> Hi there!
> 
> Thanks for reaching out to us. 
> 
> Are you saying you are expecting there to be a wav header for a 0 length audio to be returned? I just want to clarify that is the result you expect.
> 
> @yulin-li  are you aware of this being desired behavior or not?

I expect a correct wav content to be returned, which is not the case for a `b""`. So yes, I expect a wav header for a 0 length audio. 

And, as I already mentioned, sdk and raw rest api produce two different results, which is bad regardless of what I expect as a result.

**Comment by yulin-li** [comment]
Hi, thanks for asking but this is an undefined behavior as empty input text is somehow a bad request and we don't support it well.

**Comment by pankopon** [comment]
Closed as a known "undefined behavior" and no update since last month. Please open a new issue if more support is needed.
