### ISSUE TITLE
iOS SDK x2 times binary size growth

### ISSUE THREAD

**Issue by balavor** [Azure-Samples/cognitive-services-speech-sdk#2113]
## Description

I'd like to open an issue to track the problem of the **x2** binary size growth of SDK for iOS. 

MicrosoftCognitiveServicesSpeech => 1.26.0 == 5.9 Mb binary size (arm-64)

MicrosoftCognitiveServicesSpeech => 1.32.1 (latest) == 12.7 Mb binary size (arm-64)

We are looking forward to your team to resolve the issue since it is a blocker for us to update SDK to the latest version.

**Comment by chschrae** [comment]
Hi there,

It is true that the SDK has grown in size and right now unfortunately there is no way to reduce it. There may be work in the future to reduce the size, but currently it is unplanned.

**Comment by jhakulin** [comment]
We have work ongoing to make the standard Speech SDK iOS framework size back to 1.26.0 level and then introduce another framework (with new embedded functionalities) which includes the functionality which was adding the size.

**Comment by jhakulin** [comment]
1.34.0 release will have an update where the standard Speech SDK framework size is in 1.26.0 level.

**Comment by balavor** [comment]
Sounds great! Appreciate that @jhakulin

**Comment by jhakulin** [comment]
Fix has been released in 1.34.0 MicrosoftCognitiveServicesSpeech-iOS Cocoapod.
