### ISSUE TITLE
[Unity] error SPXERR_MIC_NOT_AVAILABLE when not using the default microphone

### ISSUE THREAD

**Issue by kaioduarte** [Azure-Samples/cognitive-services-speech-sdk#2116]
**Describe the bug**

I'm using the Speech Recognition service in my Unity app, and the user has the ability to pick a microphone. However, I'm getting the following error when using anything other than an empty string as the microphone name.

```
ApplicationException: Exception with an error code: 0xe (SPXERR_MIC_NOT_AVAILABLE)
Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail (System.IntPtr hr) (at <d0ceedf3fb224537bf09e708a3e455fc>:0)
Microsoft.CognitiveServices.Speech.Recognizer.FromConfig (Microsoft.CognitiveServices.Speech.Recognizer+GetRecognizerFromConfigDelegate fromConfig, Microsoft.CognitiveServices.Speech.SpeechConfig speechConfig, Microsoft.CognitiveServices.Speech.Audio.AudioConfig audioConfig) (at <d0ceedf3fb224537bf09e708a3e455fc>:0)
Microsoft.CognitiveServices.Speech.SpeechRecognizer..ctor (Microsoft.CognitiveServices.Speech.SpeechConfig speechConfig, Microsoft.CognitiveServices.Speech.Audio.AudioConfig audioConfig) (at <d0ceedf3fb224537bf09e708a3e455fc>:0)
```

It's worth mentioning that the other microphones work without any problems, so the devices are available.

**To Reproduce**

My code is based on [this sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/unity/speechrecognizer/Assets/SpeechSDKSample/Scripts/SpeechRecognition.cs#L145) on this repository, with the exception I have an `AudioConfig`. This is the relevant part of the code.
```csharp
audioConfig = AudioConfig.FromMicrophoneInput(micDeviceName ?? "");
speechRecognizer = new SpeechRecognizer(speechConfig, audioConfig);
```

**Expected behavior**

Be able to get speech transcriptions from any microphone available.

**Version of the Cognitive Services Speech SDK**

1.32.1

**Platform, Operating System, and Programming Language**

 - OS: Windows 11
 - Hardware - x64, x86
 - Programming language: C#
 - Unity 2022.3.11f1

**Comment by chschrae** [comment]
Hi @kaioduarte ,

Thanks for reaching out to us. @jhakulin could you take a look?

In the meantime, @kaioduarte can you collect a log based on these instructions? https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-use-logging

**Comment by kaioduarte** [comment]
@chschrae I'm unable to collect logs using the linked approach, I assume it's because the code throws before some initialization of the SDK.

**Comment by jhakulin** [comment]
@kaioduarte 
Based on your report, you want to be able to use specific microphone as device name and that do not work. 
Could you please share the exact device name you are using?
Could you please confirm also the platform you are running the Unity application? Windows, Android, Linux, Mac or iOS?

Just in case, you do not need to specify the microphone, you can use AudioConfig.FromDefaultMicrophoneInput method https://learn.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.audio.audioconfig.fromdefaultmicrophoneinput?view=azure-dotnet

**Comment by kaioduarte** [comment]
@jhakulin I'm running my app on Windows 11, and these are the devices I have:
- `Microphone (Logi C270 HD WebCam)`
- `Microphone Array (Realtek(R) Audio)`
- `Microphone (Realtek(R) Audio)`

I'm aware of the `FromDefaultMicrophoneInput` method, but it's not an option for my use case as the user can change the selected mic.

**Comment by jhakulin** [comment]
@kaioduarte Could you please take a look on the following article how to enumerate device names on Windows UWP which Unity uses.

https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-select-audio-input-devices#audio-device-ids-on-uwp

A sample device ID there is \\\\?\\SWD#MMDEVAPI#{0.0.1.00000000}.{5f23ab69-6181-4f4a-81a4-45414013aac8}#{2eef81be-33fa-4800-9670-1cd474972c3f}.

Now I am not 100% certain (and which means we should improve our API documentation) if the above is exact name you need to give to FromMicrophoneInput method. I would guess, the device name given as "{0.0.1.00000000}.{5f23ab69-6181-4f4a-81a4-45414013aac8}" should work.

**Comment by kaioduarte** [comment]
I see, so it's indeed a different device name.

Okay, I can take a look at this approach later. I'll keep you posted.

**Comment by jhakulin** [comment]
Closing as answered, let us know if there are any other problems.
