### ISSUE TITLE
PhraseList no longer working for real-time speech-to-text (STT) service

### ISSUE THREAD

**Issue by kokovoj** [Azure-Samples/cognitive-services-speech-sdk#2119]
**Describe the bug**

PhraseList feature stopped working ~ Oct 30th, 2023 - with special phrases no longer included in the transcription to improve its accuracy. 
We've noticed this by using Java SDK version 1.31.0 (also 1.30.0), but same issue is reproducible through [Azure Speech Studio](https://speech.microsoft.com/portal/speechtotexttool), hence this is probably a bug in the service itself.

**To Reproduce**

1. Go to Real-time Speech to text in [Speech Studio](https://aka.ms/speechstudio/speechtotexttool).
2. Select Show advanced options, turn on Phrase list and enter  `Contoso;Jessie;Rehaan;bankovation;loanovation;helocovation;flexspend-it;pay-as-you-go` in the phrase list text box
3. Use microphone and utter the following phrase `hi Rehaan this is jesse from Contoso bank we have bankovation going on at the bank including loanovation helocovation flexspend-it business credit cards and pay-as-you-go personal credit cards`
4. Resulting transcription below is inaccurate since it doesn't take entire PhraseList into account `Hi Reehan. This is Jesse from. Contoso Bank. We have Bank of Asia going on at the bank. Including loan ovation. Hill location. Flex Expanded business credit cards and pay-as-you-go personal credit cards.`. 

**Expected behavior**

We expected transcription to take PhraseList into account and be `hi Rehaan this is jesse from Contoso bank we have bankovation going on at the bank including loanovation helocovation flexspend-it business credit cards and pay-as-you-go personal credit cards`. This was working  for the last ~8 months but stopped working ~ Oct 30th, 2023.

**Version of the Cognitive Services Speech SDK**

Java SDK version 1.31.0 (also 1.30.0)

**Platform, Operating System, and Programming Language**

 - OS: Amazon Linux
 - Hardware - x64
 - Programming language: Java

**Additional info**

Please see screenshot attached
![Azure-Phrase-List-Stopped-Working](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/4805699/0ab5af31-1204-466e-8ebe-bbc050dcda42)

**Comment by ralph-msft** [comment]
Thanks for using the Speech Service and reporting the issue to us. The Speech Service does update the Speech Recognition (SD) models over time and constantly evaluates the quality model changes. I've already passed your feedback to the team that owns recognition quality.

**Comment by pankopon** [comment]
Current I-438337567 (previous I-437394077 set as duplicate). Issue acknowledged by a service team, no update yet. Assigning this to @fmegen for now.

**Comment by JayWolfPower** [comment]
Is there any update on this issue? It seems to be affecting our customers since a while now.

**Comment by ralph-msft** [comment]
The `PhraseList` service issues are now resolved!

Closing this out to keep our issue list current. If you continue to experience issues, please feel free to re-open this issue, or file new one.

**Comment by CHENGLING-QIU** [comment]
I honestly believe this issue is still occurring and needs to be fixed in May 2024. The speech recognition still didn't take PhraseList into account at all. 
I have verified through both
1. the web GUI Speech Studio quick demo page; 
2. the python Speech SDK

**Comment by JayWolfPower** [comment]
> I honestly believe this issue is still occurring and needs to be fixed in May 2024. The speech recognition still didn't take PhraseList into account at all. I have verified through both
> 
> 1. the web GUI Speech Studio quick demo page;
> 2. the python Speech SDK
> 
Can only confirm, we did a lot of testing after this was marked as resolved but the outcome was never as satisfying as before.

**Comment by rasteiner** [comment]
I have the same issue, verified on the speech studio demo page. The phrases only work when they're the only word / phrase said in an utterance. As soon as you use them in a longer phrase (like 1 additional word) they **never** seem to work.

**Comment by zarkitapple** [comment]
I have the same issue using the SDK and Speech Studio. Phrase lists are not taken into account at all.

**Comment by anastasia-enot** [comment]
I also have the same issue, adding words to phrase list does not work in SDK (Python)

**Comment by bradleywehmeier** [comment]
This is especially noticeable for proper nouns. Names can have various spellings and PhraseLists should allow us to influence the transcription when we provide the context. Right now however, Microsoft just doesn't perform as well as Google so we can't recommend customers use Microsoft for these use cases.

**Comment by Nek-11** [comment]
STILL the same issue in 2026, for fast transcription asynchronous. Is this going to get fixed anytime soon for good?
@fmegen @ralph-msft
