### ISSUE TITLE
WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED error often occurs on Android

### ISSUE THREAD

**Issue by cl-6666** [Azure-Samples/cognitive-services-speech-sdk#2122]
Added Microsoft log
![WX20231102-152407@2x](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/51937265/1d15b0fc-e9ee-4421-8442-441fe7f81a68)
Our network is normal. When this problem occurs, it gets better after a while. Sometimes it takes a long time. I don’t know what caused the problem.

**Comment by cl-6666** [comment]
Basically, it will appear after a while.
CancellationReason:Error ErrorCode: ConnectionFailure ErrorDetails:Connection failed (no connection to the remote host). Internal error: 1. Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED
                                                                                                    wss://chinaeast2.tts.speech.azure.cn/cognitiveservices/websocket/v1
                                                                                                    X-ConnectionId: 5fa4455c1ef743b4adc7e8ef29715cb8 USP state: Sending. Received audio size: 0 bytes.

**Comment by cl-6666** [comment]
Platform: Android8.0 system
Speech sdk version: api 'com.microsoft.cognitiveservices.speech:client-sdk:1.31.0'

**Comment by ralph-msft** [comment]
From the logs in the screenshot above, there was a DNS lookup failure:
```
112432]: 3960252ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  socketio_berkley.c:634 Failure: getaddrinfo failure 7
```
This can be caused by network congestion, intermittent network reliability issues, etc...

**Comment by cl-6666** [comment]
> 从上面截图中的日志来看，DNS 查找失败：
> 
> ```
> 112432]: 3960252ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  socketio_berkley.c:634 Failure: getaddrinfo failure 7
> ```
> 
> 这可能是由网络拥塞、间歇性网络可靠性问题等引起的......

This problem occurs basically every day, and the frequency is quite high. Every time it occurs, I check that the network is normal. Is there any good solution?

**Comment by cl-6666** [comment]
What is certain is that when this problem occurs, my network is normal and I can access the Internet normally.

**Comment by pankopon** [comment]
Based on the above the issue is due to intermittent DNS lookup failures, so you could try changing the DNS server that the client device uses, if possible. To @yulin-li for any additional insights regarding the TTS endpoint used here.

**Comment by pankopon** [comment]
Closed since no further updates, please open a new issue if more support is needed.
