### ISSUE TITLE
SpeechServiceResponse_StablePartialResultThreshold has no effect

### ISSUE THREAD

**Issue by CarlLindqvist** [Azure-Samples/cognitive-services-speech-sdk#2126]
SpeechServiceResponse_StablePartialResultThreshold property setting has no effect.

Setting this property still sends partial results at the same rate with the same unfinished words.

Tested in both the Go SDK and the C# example app/code.

**Comment by glharper** [comment]
@CarlLindqvist Thanks for using Speech SDK, and writing this issue up. Are you using this property for speech recognition (SpeechRecognizer), or for a different scenario?

**Comment by CarlLindqvist** [comment]
This is for speech recognition, yes. The documentation states that this value is the amount of times a word needs to be in the result before being returned as a Recognizing event. https://learn.microsoft.com/en-us/azure/ai-services/speech-service/captioning-concepts?pivots=programming-language-csharp#get-partial-results

This is not working. It will push the exact same partial results with unfinished words no matter what value it is set to.

**Comment by jhakulin** [comment]
@CarlLindqvist Would it be possible for you to provide Speech SDK trace? The issue might be in service side but I would like to see the SDK log first. Here are instructions how to take the log https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-use-logging

**Comment by jhakulin** [comment]
@CarlLindqvist Thanks for the logs! we will investigate more.

**Comment by jhakulin** [comment]
@CarlLindqvist As an interim report, there might be an issue (we are investigating) in speech service side related to Language Identification and which may impact to stable partial result functionality. Could you inform if you get more stable results if you do not enable language identification?

**Comment by jhakulin** [comment]
@mahilleb-msft Could you please check this issue on service side? The logs customer has provided indicates that SpeechServiceResponse_StablePartialResultThreshold value has been sent to service side, however there is no change detected on hypothesis results.

**Comment by jhakulin** [comment]
@CarlLindqvist According to service team the fix has been rolled out, could you please let us know if you still see the issue?

**Comment by CarlLindqvist** [comment]
Thank you. It does look like it's working better now. I no longer get the half word "välkom" in my test file when increasing the threshold. 👍

**Comment by jhakulin** [comment]
Thanks for verifying, I'll close this issue now, let us know if there are other problems.
