### ISSUE TITLE
How to set the volume text to speech SpeakerAudioDestination 

### ISSUE THREAD

**Issue by marieesss** [Azure-Samples/cognitive-services-speech-sdk#2131]
Hello, 
I saw since [january 2022](https://learn.microsoft.com/fr-fr/azure/ai-services/speech-service/releasenotes?tabs=speech-sdk#speech-sdk-1200-january-2022-release) we can change the volume for text to speech with SpeakerAudioDestination class.
However, I can't see an example using it. 
I want to be able to mute the audio, I did this but this is not working. 

```
const simulateSpeechMicrosoft =  async function () {
    let sdk = require("microsoft-cognitiveservices-speech-sdk");
    const speechConfig = await sdk.SpeechConfig.fromSubscription(speechSynthMsKey, speechSynthMsServer);
    speechConfig.speechSynthesisLanguage =  "si-LK"; 
    const player = new sdk.SpeakerAudioDestination()
    player.volume = 0

    const synthesizer = new sdk.SpeechSynthesizer(speechConfig, 
        sdk.AudioConfig.fromSpeakerOutput(player));
    await synthesizer.speakTextAsync("txt", (result:boolean) => {
        if (result) {
            synthesizer.close();
            return result.valueOf;
        }
    },
        (error:boolean) => {
            console.log(error);
            synthesizer.close();
        }
    );
  }
```

I also tried with this code below but still doesn't work

```
const player = new sdk.SpeakerAudioDestination()
player.mute()
```

Thanks for your help.

**Comment by glharper** [comment]
@marieesss Thank you for using Azure Speech SDK, and writing this issue up. 
- This is for JS, correct?
- If yes, are you running this on Node or in a browser?
- Which version of the JS SDK are you using?

**Comment by marieesss** [comment]
Hello,
Sorry for the lack of informations,

- In JS,
- Running in a browser, 
- JS SDK version ^1.29

**Comment by glharper** [comment]
@marieesss Here's an example of using the volume and mute functions on the audio output. Let me know if it works for you.
[set_volume_example.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/13340571/set_volume_example.zip)

**Comment by pankopon** [comment]
Closed since a solution example was provided weeks ago and no more updates. Please open a new issue if more support is needed.
