### ISSUE TITLE
Connection issue when connecting azure speech to text service from an angular application -1006 status code

### ISSUE THREAD

**Issue by nkiranraj** [Azure-Samples/cognitive-services-speech-sdk#2137]
Hi All,
For one of my projects, I am using azure's speech to text service in angular app.  Both Speech service and Angular app are in same vnet but in different subnets. Angular app is VNet Integrated.

Speech service is working as expected when it is publicly exposed but failing when using private endpoint. On troubleshooting, I could see 1006 status code.

I have tested private end point connectivity by spinning VM from same VNET which is working. Please advice on how to troubleshoot further.

Thanks

**Comment by nkiranraj** [comment]
Please find console logs - 
CANCELED: Reason=0
CANCELED: ErrorCode=4
CANCELED: ErrorDetails=Unable to contact server. StatusCode: 1006, wss://abc-sphsvc.cognitiveservices.azure.com/stt/speech/recognition/conversation/cognitiveservices/v1 
Reason:  undefined

**Comment by pankopon** [comment]
Hi, please attach a full Speech SDK log: https://learn.microsoft.com/azure/ai-services/speech-service/how-to-use-logging

**Comment by pankopon** [comment]
Closed since no logs provided, please open a new issue if more support is needed.
