### ISSUE TITLE
Korean speech-to-text always outputs with a question mark at the end.

### ISSUE THREAD

**Issue by riiight** [Azure-Samples/cognitive-services-speech-sdk#2138]
If you use speech-to-text with Korean language, the output will almost always be in the form of a question (i.e. with a question mark at the end) even if you do not say it as a question. I first noticed this when using your api, but you can also see it happening on your own [Speech Studio site](https://speech.microsoft.com/).

- Go to https://speech.microsoft.com.
- Select "Real-time speech to text"
- Choose "Korean" as the language.
- Make a statement in Korean using your microphone. It will almost always output as a question even if you do not say it as a question (e.g. 나 밥 먹었어 => 나 밥 먹었어?).

I don't believe this was happening a month or two ago (but I could be wrong about that). This makes Korean STT pretty much unusable now. Thanks for your help.

**Comment by pankopon** [comment]
Hi, this is likely related to the same cause as https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2101 which is under investigation on the service side. Set as duplicate, please follow the main issue for updates. @mahilleb-msft FYI
