### ISSUE TITLE
ValueError: read of closed file with newer SDK

### ISSUE THREAD

**Issue by GabrieleCastellani** [Azure-Samples/cognitive-services-speech-sdk#2139]
**IN ORDER TO ASSIST YOU, PLEASE PROVIDE THE FOLLOWING:**

- Speech SDK log Attached

- A stripped down, simplified version of your source code that exhibits the issue.
```
    done = False
    def stop_cb(evt):
        print('CLOSING on {}'.format(evt))
        
        speech_recognizer.stop_continuous_recognition()
        nonlocal done
        done = True
    compressed_format = speechsdk.audio.AudioStreamFormat(compressed_stream_format=speechsdk.AudioStreamContainerFormat.OGG_OPUS)
    callback = BinaryFileReaderCallback(filename=fnm)
    stream = speechsdk.audio.PullAudioInputStream(stream_format=compressed_format, pull_stream_callback=callback)

    speech_config = speechsdk.SpeechConfig(subscription='xxxxxxxxxxxxxx', region='westeurope')
    speech_config.set_property(speechsdk.PropertyId.Speech_LogFilename, "speech-log.txt")
    audio_config = speechsdk.audio.AudioConfig(stream=stream)

    # Creates a speech recognizer using a file as audio input, also specify the speech language
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config,language="it-IT", audio_config=audio_config)
    testo=[]
    speech_recognizer.recognized.connect(lambda evt: testo.append (evt.result.text))
    
    speech_recognizer.session_stopped.connect(stop_cb)
    speech_recognizer.canceled.connect(stop_cb)
    
    speech_recognizer.start_continuous_recognition()
    while not done:
        time.sleep(.5)
        #check if testo has elements
        # if len(testo)>0:
        #     print('|'.join(testo))
```
**Describe the bug**
Upgrading from speech sdk azure-cognitiveservices-speech==1.15.0 to one of the lastest eg 1.24 or 1.33 . No code changes

got:
```
  File "./stl_bot.py", line 29, in read
    frames = self._file_h.read(size)
ValueError: read of closed file
```

**Expected behavior**
Beeing able to retrive the transcription

**Version of the Cognitive Services Speech SDK**

Which version of the SDK are you using: 1.33

**Platform, Operating System, and Programming Language**
DOCKER
FROM mcr.microsoft.com/devcontainers/python:3.8

[speech-log.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/13424492/speech-log.txt)

**Comment by pankopon** [comment]
From the log
```
[944128]: 2153ms SPX_DBG_TRACE_VERBOSE:  resource_manager.cpp:133 Created 'CSpxUspConnection' as '792041254'
[944128]: 2154ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  shim_openssl.c:55 libssl could not be loaded
[944128]: 2154ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:2175 Could not load libssl
[944128]: 2154ms SPX_TRACE_ERROR:  exception.cpp:130 About to throw Runtime error: Failed to initialize platform (azure-c-shared). Error: 2176 
```
The file error is just a side effect.

What is the Ubuntu version your docker image is based on? (run `lsb_release -a` or `cat /etc/os-release` in the container)

Your previous SDK version 1.15.0 was released in January 2021 which is almost 3 years ago. See current setup instructions:
- https://learn.microsoft.com/en-us/azure/ai-services/speech-service/quickstarts/setup-platform?tabs=linux
- https://learn.microsoft.com/azure/ai-services/speech-service/how-to-configure-openssl-linux

Note that the Speech SDK still requires OpenSSL 1.x for the time being (ref. https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2048).

**Comment by GabrieleCastellani** [comment]
Thank you your suggestions solved the issue
