### ISSUE TITLE
error CS0234: The type or namespace name 'CognitiveServices' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by tslug** [Azure-Samples/cognitive-services-speech-sdk#214]
I'm trying to build a Unity player w/ settings: Target Platform: Linux, Architecture x86_64, Server Build, and I'm getting errors like this for every attempt in my code to reference a CognitiveServices class or namespace:

error CS0234: The type or namespace name 'CognitiveServices' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

To reproduce, using the CognitiveServices SDK 1.4.0 on Windows 10 Home, using Unity 2018.3.5f1, do a Linux Player build w/ x86_64 and Server Build, and in your code, include the line:
using Microsoft.CognitiveServices.Speech;

Doing the same but with a Windows target and Server Build works fine.

**Comment by BrianMouncer** [comment]
We currently support Windows and Android, but do not currently have a Unity plug-in for Linus or OSx.
Both are in our back log of items to add, but at this time I do not have an ETA on when Mac and Linux will be added.

Thanks,

Brian.

**Comment by tslug** [comment]
Thanks for your quick reply, Brian.  Might want to update your docs.  They say Linux is supported.

**Comment by tslug** [comment]
Wait, no they don't.  My bad.

**Comment by BrianMouncer** [comment]
We support Linux for many other areas, so sometimes its easy to miss.

Thanks for reporting it.
It is always good to know what users are actively working on and the problems they hit.

**Comment by gurpreet48** [comment]
I am getting issue in framework 4.5 C# on windows system. Can you please guide me can i implement in .net framework 4.5 in Visual studio 2017

**Comment by jhakulin** [comment]
@gurpreet48 Could you provide more information (detailed output od error messages) what kind of issue you are getting ? Thanks

**Comment by jhakulin** [comment]
Unity support for Linux is not yet available in Speech SDK, we have created item in our backlog to support this is the future release.

**Comment by apouche** [comment]
Have the exact same problem for Unity on MacOS. Any news on this ?

**Comment by jhakulin** [comment]
@apouche Unity on MacOS is not yet supported either. The Speech SDK for Unity supports currently Windows Desktop (x86 and x64) or Universal Windows Platform (x86, x64, ARM32/ARM64), Android (x86, ARM32/64) and iOS (x64 simulator and ARM64). We have plans to support MacOS later this year.

**Comment by hyper-active** [comment]
@jhakulin Thanks for clarifying that. I was going around in circles wondering why I couldn't get it working on my Mac. So really currently the only way to develop with Speech SDK on Unity is with a Windows machine?

**Comment by mathyouf** [comment]
Shouldn't I be able to build my project to Android using my Mac as my development machine as long as I don't try to run it in the editor?

**Comment by jhakulin** [comment]
@mathyouf Yes Mac can be used as development environment, however currently Speech SDK does not support MacOS in native plugins which means you cannot run it directly using editor

**Comment by mathyouf** [comment]
@jhakulin I keep getting an error when trying to build to Android because there are errors in the editor. Should I do conditional compiling or is there a way to have my Android build ignore build errors that are only error specific on a mac?

<img width="1162" alt="Screen Shot 2020-10-01 at 10 50 03" src="https://user-images.githubusercontent.com/19615875/94756929-de731980-03d3-11eb-97be-0d12b208d911.png">

**Comment by jhakulin** [comment]
@mathyouf One more check before I will look more detailed, does it help if you tag iOS csharp dll to Editor as instructed here ?

https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/unity/from-microphone#build-and-run-the-sample-for-ios-platform

Under Project > Assets > SpeechSDK > Plugins > iOS, check that Microsoft.CognitiveServices.Speech.csharp.dll target is enabled for Editor and iOS platforms.

We have an item on our backlog for Mac support for Unity, so we will complete the support there in future releases.

**Comment by mathyouf** [comment]
When I download the link from below
<img width="936" alt="Screen Shot 2020-10-07 at 12 34 17" src="https://user-images.githubusercontent.com/19615875/95284562-6c01ae00-0899-11eb-8ddb-c5085a282a9e.png">

the iOS folder in the path isn't included
<img width="366" alt="Screen Shot 2020-10-07 at 12 26 34" src="https://user-images.githubusercontent.com/19615875/95284587-7d4aba80-0899-11eb-93f6-bc1cc154433a.png">

**Comment by mathyouf** [comment]
Found it here, but the error `The type or namespace name 'CognitiveServices' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)` remains.
<img width="1112" alt="Screen Shot 2020-10-07 at 12 37 22" src="https://user-images.githubusercontent.com/19615875/95284736-e6323280-0899-11eb-851d-d4bb412486b5.png">

**Comment by mathyouf** [comment]
Adding Editor and Android solved my problem, as you said. 
<img width="1119" alt="Screen Shot 2020-10-07 at 12 47 31" src="https://user-images.githubusercontent.com/19615875/95285233-4675a400-089b-11eb-8ee0-41d7179d85a5.png">


When I imported the link from the project though only under the `Third Party` path was the iOS folder included, not under the path in the first one.
![image](https://user-images.githubusercontent.com/19615875/95285303-6efd9e00-089b-11eb-8500-ca3e5a03e9d8.png)

**Comment by janaram22** [comment]
![image](https://user-images.githubusercontent.com/40597812/230019117-4b9be92a-1708-4ce7-97d7-b46b28ba6b13.png)


i cant able to build webgl having these issues !
