### ISSUE TITLE
Is SpeechServiceConnection_InitialSilenceTimeoutMs  Work on Javascript SDK

### ISSUE THREAD

**Issue by Yukari-Tryhard** [Azure-Samples/cognitive-services-speech-sdk#2142]
![Code Snippet](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/61675970/95684d2e-079c-4fe8-b940-727183c74fc2)

I'm currently setting it at 10. It should be 10ms and when I call to my service. it opens the stream to Azure Cognitive and it will close ASAP. Is that the correct behavior we would expect right? 

Relate information:
**Version: 1.29.0**
**NodeJs Version: 16**

**Comment by glharper** [comment]
@Yukari-Tryhard Thank you for using JS Speech SDK, and writing this issue up. With an initial silence timeout of 10ms, I would expect an immediate return of an Initial Silence Timeout cancellation from the service, yes. The default for initial silence timeout is service dependent per scenario, but you may see something like 5s for recognizeOnceAsync, 15s for startContinuousRecognitionAsync.

**Comment by Yukari-Tryhard** [comment]
@glharper  thank you for your reply. But the current interaction we have is not like that. We open the stream to Azure and wait but it never closes.

The current implementation of our service is

**Some voice service**  ----Web socket---> **Our middle service** ----> **Write Stream NodeJS** ---> **write(data) to sdk.AudioInputStream.createPushStream.**

So I believe the write function in Write Stream NodeJS API is always writing something. By default it writes empty bit data.

So I have two questions:

1. Can you please confirm that it works on your side. so that we know it's our side problem.
2. If this property is not working do we have other alternative solution for initial silence detection and closing stream. For example **Conversation_Initial_Silence_Timeout**

**Comment by glharper** [comment]
> @glharper thank you for your reply. But the current interaction we have is not like that. We open the stream to Azure and wait but it never closes.
> 
> The current implementation of our service is
> 
> **Some voice service** ----Web socket---> **Our middle service** ----> **Write Stream NodeJS** ---> **write(data) to sdk.AudioInputStream.createPushStream.**
> 
> So I believe the write function in Write Stream NodeJS API is always writing something. By default it writes empty bit data.
> 
> So I have two questions:
> 
> 1. Can you please confirm that it works on your side. so that we know it's our side problem.
> 2. If this property is not working do we have other alternative solution for initial silence detection and closing stream. For example **Conversation_Initial_Silence_Timeout**

The initial silence timeout result will not close the stream. The Speech SDK will keep waiting for speech, and merely pass the initial silence timeout on as a recognized result code. If you want to close the stream on initial silence timeout, you'll have to do so in your own code upon seeing that recognized result.

**Comment by jpalvarezl** [comment]
To keep our open issues list up to date, this item will be closed since it's been inactive and needs more information to proceed. Please file a new issue (and feel free to reference this one) if there's new information we can follow up on. Thank you!
