### ISSUE TITLE
iOS - Delayed callback and event not triggered in Keyword Recognizer of Speech SDK

### ISSUE THREAD

**Issue by bptstmlgt** [Azure-Samples/cognitive-services-speech-sdk#2143]
**Describe the bug**  
   
The Microsoft Speech SDK's keyword recognition functionality is behaving unexpectedly. The `addRecognizedEventHandler` completion block is not being called when the keyword is recognized and there's a delay of 10 seconds before `recognizeOnceAsync`'s `recognitionResult` is called after the keyword is recognized.  
   
**To Reproduce**  
   
Here's a simplified version of the source code being used:  
   
```swift  
import MicrosoftCognitiveServicesSpeech  
   
extension AskDummyCentral {  
    func recognizeFromKeyword() {  
        var keywordRecognizer: SPXKeywordRecognizer?  
        let audioConfig = SPXAudioConfiguration()  
  
        do {  
            keywordRecognizer = try SPXKeywordRecognizer(audioConfig)  
        } catch {  
            keywordRecognizer = nil  
        }  
  
        guard let keywordRecognizer = keywordRecognizer else {  
            return  
        }  
  
        guard let keywordModelFile = Bundle.main.path(forResource: "hey-dummy", ofType: "table") else {  
            return  
        }  
  
        keywordRecognizer.addRecognizedEventHandler { recognizer, args in  
            DispatchQueue.main.async { [weak self] in  
                guard let self = self else { return }  
                // This block is never called.  
                self.recognizeFromMic()  
            }  
        }  
  
        keywordRecognizer.addCanceledEventHandler { recognizer, args in  
            DispatchQueue.main.async {  
                print("Recognition canceled: \(args.errorDetails ?? "No details available")")  
            }  
        }  
  
        do {  
            try keywordRecognizer.recognizeOnceAsync({ recognitionResult in  
                if recognitionResult.text != nil {  
                    print("Did recognize something: \(recognitionResult.text ?? "")")  
                }  
            }, keywordModel: SPXKeywordRecognitionModel(fromFile: keywordModelFile))  
        } catch {  
            print("Didn't work")  
        }  
    }  
}  
```  
   
   
1. Open the screen where the recognition starts. The microphone is open and waiting for the keyword (orange light showing)
2. Say the keyword ("Hey Dummy"). The microphone orange indicator immediately goes off, indicating the keyword is recognized.  
3. Observe that the `addRecognizedEventHandler` completion is never called.  
4. Observe that the `recognitionResult` from `recognizeOnceAsync` is eventually called, but only 10 seconds after the microphone stopped recording / after the keyword got recognized.  
   
**Expected behavior**  
   
When the keyword is recognized, the `addRecognizedEventHandler` should be called and the `recognitionResult` from `recognizeOnceAsync` should be called immediately, not 10 seconds after.  
   
**Version of the Cognitive Services Speech SDK**  
   
Version 1.33.0  
   
**Platform, Operating System, and Programming Language**  
   
- OS: iOS 15.0.3  
- Hardware: ARM (running on a real device)  
- Programming language: Swift  
- Xcode version: 15.0  
- Device: MacBook Pro M1  
   
**Additional context**  
   
No error messages or stack trace are available since the program doesn't crash, but the delayed callback and the event handler not being called are causing issues with the application's performance.

**Comment by jhakulin** [comment]
@bptstmlgt Thanks for the detailed report and sample code, will check the issue on our side and let you know.

**Comment by bptstmlgt** [comment]
Thank you! 
FYI, region for the Speech configuration is `francecentral`.

**Comment by jhakulin** [comment]
@bptstmlgt One problem in the code you provided is that there is no wait and signaling when the keywordRecognizer.recognizeOnceAsync operation completes, this causes keyword is not recognized as the objects are destructed when execution goes out of context. In the code below, I added as an example keywordRecognizedSemaphore to signal when keyword recognition completes and wait for it.

```
func recognizeKeyword() {
        var keywordRecognizedSemaphore: DispatchSemaphore = DispatchSemaphore(value: 0)
        var keywordRecognizer: SPXKeywordRecognizer?
        let audioConfig = SPXAudioConfiguration()
          
        do {
            keywordRecognizer = try SPXKeywordRecognizer(audioConfig)
        } catch {
            keywordRecognizer = nil
        }
          
        guard let keywordRecognizer = keywordRecognizer else {
            return
        }
          
        guard let keywordModelFile = Bundle.main.path(forResource: "kws", ofType: "table") else {
            return
        }
          
        keywordRecognizer.addRecognizedEventHandler { recognizer, args in
            DispatchQueue.main.async { [weak self] in
                guard let self = self else { return }
                print("recognized keyword")
                // This block is never called.
                self.recognizeFromMic()
            }
        }
          
        keywordRecognizer.addCanceledEventHandler { recognizer, args in
            DispatchQueue.main.async {
                print("Recognition canceled: \(args.errorDetails ?? "No details available")")
            }
        }
          
        do {
            updateLabel(text: "Listening keyword ...", color: .gray)
            print("Listening keyword...")
            try keywordRecognizer.recognizeOnceAsync({ recognitionResult in
                if recognitionResult.text != nil {
                    print("Did recognize something: \(recognitionResult.text ?? "")")
                    keywordRecognizedSemaphore.signal()
                }
            }, keywordModel: SPXKeywordRecognitionModel(fromFile: keywordModelFile))
            
            let result = keywordRecognizedSemaphore.wait(timeout: .now() + .seconds(10))
            if result != .success {
                print("keyword recognition times out")
            }
        } catch {
            print("Didn't work")
        }
    }
```

**Comment by bptstmlgt** [comment]
@jhakulin thank you Jarno -- works fine now!
