### ISSUE TITLE
Connection error to speech service | Connection failed (no connection to the remote host). Internal error: 1

### ISSUE THREAD

**Issue by havu95** [Azure-Samples/cognitive-services-speech-sdk#2149]
Hello all,

Speech SDK log taken from the run:
[speechlog (1).txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/13435413/speechlog.1.txt)

- source code:
https://learn.microsoft.com/en-us/azure/ai-services/speech-service/get-started-text-to-speech?tabs=windows%2Cterminal&pivots=programming-language-python

**Describe the bug**

I am trying to run the above the script, but I get an error (see below). I am using a proxy and also tried set it up based on
https://learn.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-configure-proxy?tabs=bash

Speech service is open for all networks and also tried to reinstall the SDK. Based on the logs the proxy is not used properly?

**Version of the Cognitive Services Speech SDK**

1.32.1

**Platform, Operating System, and Programming Language**

 - OS: Windows 10
 - Hardware - x86
 - Programming language: Python

 - Error messages, stack trace:
![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/64212632/ef1c7f7f-3b1b-4934-abdc-551893fa02c7)

**Comment by pankopon** [comment]
Hi, Speech SDK for Python is not the same as "Azure SDK for Python". You need to use the [set_proxy](https://learn.microsoft.com/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.speechconfig?view=azure-python#azure-cognitiveservices-speech-speechconfig-set-proxy) method, like
```
speech_config.set_proxy("YourProxyHostname", YourProxyPortNumber, "YourProxyUsername", "YourProxyPassword")
```

**Comment by havu95** [comment]
Hi, this was the solution. Now it works :)

**Comment by pankopon** [comment]
Closed as resolved.
