### ISSUE TITLE
Switching RecognizeOnceAsync to StartContinuousRecognitionAsync in Unity

### ISSUE THREAD

**Issue by AAvrilML** [Azure-Samples/cognitive-services-speech-sdk#215]
I started out with the Unity Quickstart, which worked great. There's a comment in the script:             // For long-running multi-utterance recognition, use StartContinuousRecognitionAsync() instead.

But just switching the function call results in an error for result 'Cannot assign void to an implicitly-typed variable'. From looking at a Xamarin sample, I think possibly I need to add an event handler for grabbing the output text instead of using a result, is that the case? Do you have any sample or guidance on how to make this switch in a Unity project?

**Comment by joshthor3222** [comment]
the recognizeonce and recognizecontinuous have different result functionality. try something like this:

`
                recognizer.recognizing = (s, e) => {
                    console.log(e.result.text); //view text as it comes in
                };

                recognizer.recognized = function(s, e){
                    if (e.result.text != null && e.result.text.trim() != "") {
                     //do something with final result.
                     }
                 };

`

**Comment by jhakulin** [comment]
Thanks for asking, you can for example modify quick start sample code as follows to use StartContinuousRecognitionAsync and StopContinuousRecognitionAsync

```csharp
public class HelloWorld : MonoBehaviour
{
    public Text outputText;
    public Button recoButton;
    SpeechRecognizer recognizer;
    SpeechConfig config;

    private object threadLocker = new object();
    private bool recognitionStarted = false;
    private string message;

    private void RecognizingHandler(object sender, SpeechRecognitionEventArgs e)
    {
        lock (threadLocker)
        {
            message = e.Result.Text;            
        }
    }

    public async void ButtonClick()
    {
        if (recognitionStarted)
        {
            await recognizer.StopContinuousRecognitionAsync().ConfigureAwait(false);
            lock (threadLocker)
            {
                recognitionStarted = false;
            }
        }
        else
        {
            await recognizer.StartContinuousRecognitionAsync().ConfigureAwait(false);
            lock (threadLocker)
            {
                recognitionStarted = true;
            }
        }
    }

    void Start()
    {
        recoButton.onClick.AddListener(ButtonClick);
        config = SpeechConfig.FromSubscription("your key", "your region");
        recognizer = new SpeechRecognizer(config);
        recognizer.Recognizing += RecognizingHandler;
    }

    void Disable()
    {
        recognizer.Recognizing -= RecognizingHandler;
        recognizer.Dispose();
    }

    void Update()
    {
        lock (threadLocker)
        {
            if (outputText != null)
            {
                outputText.text = message;
            }
        }
    }
}
```
