### ISSUE TITLE
so error

### ISSUE THREAD

**Issue by wall3001** [Azure-Samples/cognitive-services-speech-sdk#216]
**It happens when I recreate TranslationRecognizer frequently.**

SIGSEGV(SEGV_ACCERR)
    0x55c6671658
    #00    pc 00000000004e4658    [heap]
    #01    pc 00000000000a6ed0    /data/app/com.speech.test-2/lib/arm64/libMicrosoft.CognitiveServices.Speech.java.bindings.so (_ZNK40SwigDirector_TranslationTexEventListener7ExecuteERKN9Microsoft17CognitiveServices6Speech11Translation31TranslationRecognitionEventArgsE+628) [arm64-v8a::02dbfcc7dc3d2a65e6f797c2285769b6]
    #02    pc 000000000011cabc    /data/app/com.speech.test-2/lib/arm64/libMicrosoft.CognitiveServices.Speech.java.bindings.so (_ZN9Microsoft17CognitiveServices6Speech11EventSignalIRKNS1_11Translation31TranslationRecognitionEventArgsEE6SignalES6_+436) [arm64-v8a::02dbfcc7dc3d2a65e6f797c2285769b6]
    #03    pc 000000000011c824    /data/app/com.speech.test-2/lib/arm64/libMicrosoft.CognitiveServices.Speech.java.bindings.so (_ZN9Microsoft17CognitiveServices6Speech15AsyncRecognizerINS1_11Translation28TranslationRecognitionResultENS3_31TranslationRecognitionEventArgsENS3_39TranslationRecognitionCanceledEventArgsEE20FireEvent_RecognizedEP10_spx_emptyS9_Pv+72) [arm64-v8a::02dbfcc7dc3d2a65e6f797c2285769b6]
    #04    pc 0000000000201188    /data/app/com.speech.test-2/lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so [arm64-v8a::b22051423228d781c31b23837620848c]
    #05    pc 00000000002988fc    /data/app/com.speech.test-2/lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so (_ZN9Microsoft17CognitiveServices6Speech11EventSignalINSt6__ndk110shared_ptrINS1_4Impl24ISpxRecognitionEventArgsEEEE6SignalES7_+476) [arm64-v8a::b22051423228d781c31b23837620848c]
    #06    pc 0000000000296340    /data/app/com.speech.test-2/lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so (_ZN9Microsoft17CognitiveServices6Speech4Impl14CSpxRecognizer13FireRecoEventEPNS1_11EventSignalINSt6__ndk110shared_ptrINS2_24ISpxRecognitionEventArgsEEEEERKNS5_12basic_stringIwNS5_11char_traitsIwEENS5_9allocatorIwEEEENS6_INS2_21ISpxRecognitionResultEEEm+288) [arm64-v8a::b22051423228d781c31b23837620848c]
    #07    pc 00000000002966b0    /data/app/com.speech.test-2/lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so (_ZN9Microsoft17CognitiveServices6Speech4Impl14CSpxRecognizer15FireResultEventERKNSt6__ndk112basic_stringIwNS4_11char_traitsIwEENS4_9allocatorIwEEEENS4_10shared_ptrINS2_21ISpxRecognitionResultEEE+264) [arm64-v8a::b22051423228d781c31b23837620848c]
    #08    pc 00000000002bc6b0    /data/app/com.speech.test-2/lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so (_ZN9Microsoft17CognitiveServices6Speech4Impl22CSpxAudioStreamSession13DispatchEventERKNSt6__ndk14listINS4_8weak_ptrINS2_14ISpxRecognizerEEENS4_9allocatorIS8_EEEERKNS4_12basic_stringIwNS4_11char_traitsIwEENS9_IwEEEENS3_9EventTypeEmRKNS4_10shared_ptrINS2_21ISpxRecognitionResultEEE+568) [arm64-v8a::b22051423228d781c31b23837620848c]
    #09    pc 00000000002da4c0    /data/app/com.speech.test-2/lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so (_ZNSt6__ndk113packaged_taskIFvvEEclEv+76) [arm64-v8a::b22051423228d781c31b23837620848c]
    #10    pc 00000000002d97b8    /data/app/com.speech.test-2/lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so (_ZN9Microsoft17CognitiveServices6Speech4Impl17CSpxThreadService4Task3RunEv+36) [arm64-v8a::b22051423228d781c31b23837620848c]
    #11    pc 00000000002d9ad0    /data/app/com.speech.test-2/lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so (_ZN9Microsoft17CognitiveServices6Speech4Impl17CSpxThreadService6Thread10WorkerLoopENSt6__ndk110shared_ptrIS4_EE+416) [arm64-v8a::b22051423228d781c31b23837620848c]
    #12    pc 00000000002dc180    /data/app/com.speech.test-2/lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so (_ZNSt6__ndk114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEPFvNS_10shared_ptrIN9Microsoft17CognitiveServices6Speech4Impl17CSpxThreadService6ThreadEEEESE_EEEEEPvSI_+64) [arm64-v8a::b22051423228d781c31b23837620848c]
    #13    pc 0000000000068474    /system/lib64/libc.so (_ZL15__pthread_startPv+52) [arm64-v8a::fb40850783bd9cd558b051dc100a9952]
    #1

**Comment by wolfma61** [comment]
what does frequently mean? one every second? thousands at once?

do you create new recognizer after closing the old recognizers?
this is also Android?

**Comment by wolfma61** [comment]
no feedback - closing
