### ISSUE TITLE
How to interrupt recognition in the Microsoft speech-to-text interface but retain the completed recognition results after the interruption?

### ISSUE THREAD

**Issue by Bruce337f** [Azure-Samples/cognitive-services-speech-sdk#2163]
Is there any solution?

**Comment by jhakulin** [comment]
@Bruce337f Not sure if I understand fully the ask, could you please specify more the scenario and problem you are facing?

**Comment by jhakulin** [comment]
Closing the issue as answered, let us know if there are any other issues.
