### ISSUE TITLE
STT Triggering the speech-end event manually

### ISSUE THREAD

**Issue by anunayajoshi** [Azure-Samples/cognitive-services-speech-sdk#2167]
I am making use of the speechsdk's continuous_recognition_async method, and capturing the following events - recognizing/recognized/speech started/speech end.

now, in the following scenario where the user utters something, takes a pause, and then utters something else, i'd expect the flow of events to be something like this 

Expected output:

\<user begins speaking>
\<speech started>
\<recognizing>
\<recognixing>
\<pause>
\<speech end>
\<recognized>
\<user begins speaking again>
\<speech started>
\<recognizing>
\<recognized>
...

however, i am getting something like this currently 

Current output:
\<user begins speaking>
\<speech started>
\<recognizing>
\<recognixing>
\<pause>
\<recognized>
\<user begins speaking again>
\<recognizing>
\<recognized>
\<user long 10s pause>
\<speech end>
\<user speaks again>
\<speech started>

so the issue is that the speech end doesn't trigger immediately after the recognized is received, which is what i'd like. i  assume it's because azure is checking for a longer period of silence to determine the speech has ended. 

I have also tried using the recognize_once_async method, as I thought I can restart that connection everytime it recognizes an utterance, but that didn't work out. 

What I actually need, is just the speech_started event to trigger correctly, when the user speaks again after a pause. As I expect the speech to be ended when the recognized event is triggered, is there a way for me to set that event of speech ended, once the recognized event is fired?

**Comment by jhakulin** [comment]
@anunayajoshi Thanks for the report, currently there is no good way to control speech end event for your need. You can try to experiment with PropertyId SpeechServiceConnection_EndSilenceTimeoutMs and see how that impact to behavior. 

Could you please provide more information for what purpose you need more accurate speech end signal? Maybe use that information in UI?

**Comment by anunayajoshi** [comment]
Yeah sure, it's a slightly complicated pipeline. I'll try to simplify it. 

Essentially, I'm building a pipeline that streams chunks from STT -> LLM -> TTS

When I receive the recognized event from azure STT, i send the transcription to the LLM. 
When I receive the recognizing event from azure STT, I cancel any generation from the LLM/TTS (which means if I detect that the human started speaking again, I cancel my synthesis). 

However, the problem I am facing is that I am not cancelling the synthesis fast enough, because the recognizing event takes too long (granted we are talking 600-700 milliseconds), to detect that the human started speaking. What would work instead would be if I use the speech_started event, whose event will trigger before the recognizing event. 


As such, I am expecting that the speech_start event will fire off when a user starts speaking again after a short pause, where the recognized event was fired off too. 

However, the problem I am facing is as I mentioned above in the initial issue. So all I need is the speech_start event to trigger everytime the human starts speaking again after a 1-2 second pause, but that's not the case. is there any property for me to adjust for that?

My assumption is that SpeechServiceConnection_EndSilenceTimeoutMs is a way to just increase the endpointing, not to speed up the speech_started_event trigger?

Appreciate the response regardless, @jhakulin

**Comment by jhakulin** [comment]
@anunayajoshi One way to do this so that you have also full control is to use some voice activity detector on application side. 
For that you would need to use AudioInputStream object from Speech SDK to stream the audio from the source (could be file, microphone or another stream) to Speech SDK. Before streaming the audio to Speech SDK, you would run it through voice activity detector (VAD), which would tell you when user is speaking. Depending on platform and programming language there might be available libraries to do this or if very simple energy based VAD is sufficient you could implement that yourself.

What is the platform and programming language in use?

**Comment by anunayajoshi** [comment]
Thanks for the advice. I have tried using VADs such as sileroVAD and webrtcVAD. It had some success, but would have quite a number of false positives. I imagined if I were using the same VAD system which azure used for their STT, it would be much better, and not conflict as much. 

I am using Python. Not sure what you mean by platform. Would be happy to chat more!

**Comment by dargilco** [comment]
Hi @anunayajoshi, your ideal solution would be an on-device VAD that will react fast to start of speech so you can immediately cut TTS playback. The Microsoft speech service does not expose this information, and therefore Speech SDK does not have an event for it. The best you can do, and it sounds like you already tried it, is to stop playback when you get a first "Recognizing" event.
