### ISSUE TITLE
Unable to Transcribe the audio stream | React JS, Node JS, Azure STT

### ISSUE THREAD

**Issue by manosec** [Azure-Samples/cognitive-services-speech-sdk#2169]
Hi there,

I have a frontend(Reactjs) and a backend (Nodejs), I want to convert my audio into text that comes from the frontend, For that I'm using AudioStreamInput in the node js app(Code given below). Here I'm able to console the audio buffers coming from the frontend but unable to transcribe it. As of now, I believe that the issue is something I need to do with,

1.  Audio data I'm receiving from the frontend.
2. Sending the same to Azure STT service. 
3.  Configuration related to the audio format. 

Please help me with this. 

My Reactjs Functional Component and Nodejs Code are mentioned below FYR.

**React JS Component:**

```
import { ReactMic } from 'react-mic';
import React, { useState, useEffect, useRef } from 'react';
import io from 'socket.io-client';


const Mic = () => {
  const [record, setRecord] = useState(false);
  const socketRef = useRef(null);
  const [result, setResult] = useState("")

  useEffect(() => {
    const socket = io('http://localhost:3000');
    socket.on('connect', () => {
      console.log('Socket connected:', socket.connected);
      socketRef.current = socket;
    });

    socket.on("result", data=>{
      setResult(data)
    })
    return () => {
      if (socketRef.current) {
        socketRef.current.disconnect();
      }
    };
  }, []);

  const startRecording = () => {
    setRecord(true);
  };

  const stopRecording = () => {
    setRecord(false);
    if (socketRef.current) {
      socketRef.current.disconnect();
    }
  };

  const onData = (recordedBlob) => {
    if (socketRef.current && socketRef.current.connected) {
      socketRef.current.emit('binaryData', recordedBlob);
    } else {
      console.log('Socket not connected');
    }
  };

  const onStop = (recordedBlob) => {
    console.log('recordedBlob is: ', recordedBlob);
  };

  return (
    <div>
      <ReactMic
        record={record}
        className="sound-wave"
        onStop={onStop}
        onData={onData}
        strokeColor="#000000"
        backgroundColor="#FF4081"
      />
      <button onClick={startRecording} type="button">
        Start
      </button>
      <button onClick={stopRecording} type="button">
        Stop
      </button>
    </div>
  );
};

export default Mic;
```

**Node JS:**

```
const io = require('socket.io')({
  cors: {
    origin: '*',
    methods: ['GET', 'POST', 'PUT'],
  },
});

io.sockets.setMaxListeners(0);

const sdk = require("microsoft-cognitiveservices-speech-sdk");
const { TextAnalyticsClient, AzureKeyCredential } = require("@azure/ai-text-analytics");
const { base64encode, base64decode } = require('nodejs-base64');

const key = 'redacted';
const endpoint = 'redacted'

const sentiment = new TextAnalyticsClient(endpoint, new AzureKeyCredential(key));

io.on('connect', (socket) => {

  function SpeechToText () {
    const { region, samplesPerSecond, bitsPerSample, channels } = {
    "region": "redacted",
    "samplesPerSecond": 16000,
    "bitsPerSample": 16,
    "channels": 1
    };
    
    var speechConfig = sdk.SpeechConfig.fromSubscription(redacted, region);
    
    const format = sdk.AudioStreamFormat.getWaveFormat(samplesPerSecond, bitsPerSample, channels);
    
    this.pushStream = sdk.AudioInputStream.createPushStream(format)
    
    this.recognizeAsync = function () {

    let audioConfig = sdk.AudioConfig.fromStreamInput(this.pushStream);

    speechConfig.setProperty("SpeechServiceConnection_LanguageIdMode", "Continuous")

    autoDetectSourceLanguageConfig = sdk.AutoDetectSourceLanguageConfig.fromLanguages(["en-IN"]);

    this.recognizer = sdk.SpeechRecognizer.FromConfig(speechConfig, autoDetectSourceLanguageConfig, audioConfig);

    this.recognizer.canceled = (o, e) => {
      try {
      console.log("canceled", e)
  
      } catch (error) {
      console.log("canceled error", error)
  
      }
    };

    this.recognizer.recognized = (rec, { result }) => {
      try{
        console.log('recognized: ', result.text)
        socket.emit('result', result.text)
      }
      catch(err){
        console.log(err);
      }
    
    };

    this.recognizer.recognizing = (rec, { result }) => {
      try{
        console.log('recognizing', result.text)
      }
      catch(err){
        console.log(err)
      }
    };
    
    this.recognizer.startContinuousRecognitionAsync();
    
    }
  }


  var speechToText = new SpeechToText();
  speechToText.recognizeAsync()

  console.log(`Client Connected to server ${socket.id}`);

  socket.on('binaryData', (data) => {
    if (data !== null) {
      try{
        speechToText.pushStream.write(data.slice());
      }
       catch(err){
        console.log(err)
       } 
    }

  socket.on('disconnect',()=>{
    console.log("Client disconnected")
    speechToText.recognizer.stopContinuousRecognitionAsync();
  })
  });
});

const PORT = 3000;
io.listen(PORT, ()=>{
  console.log(`Socket Server Started at ${PORT}`)
});

```

**Comment by manosec** [comment]
The below NodeJS code is reference from this issue #https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/703

**Comment by manosec** [comment]
Hi @dargilco, thanks for your response. 

My scenario is that I can get the recognized events but the recognition is wrong and sometimes it says undefined, also the latency is high.

I know that somewhere I'm doing wrong, please guide me on this. I think the problem was related to the format of the audio stream I'm sending from the React app, please look into my above code.

I have attached the sample recognized screenshot FYR, Here when I spoke in my microphone it transcribed into the same text which you can see in the screenshot.

![node_socket](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/86837128/1ae3ce72-cd2f-483a-9264-083c81ce608a)

**Comment by manosec** [comment]
And Sure I'll try the sample you have mentioned above, Thanks.

**Comment by manosec** [comment]
@dargilco, Two things I want to mention here regarding the sample code. I have followed the steps to set up and it was a success.

1. Unable to detect the audio microphone, the dropdown is empty(When hosting the index.html on the remote server using Python).
2. Error on connecting to the azure socket server

**Reference:**
![audio_input](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/86837128/56a195af-64c7-4cc6-99ba-ee98d38050b8)

I have noted this is in the console error I have attached below,

![socket_error](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/86837128/08c377fb-8a1b-4b4d-b392-dd9d67a031e5)

**Note:**
When opening the index.html file locally in my browser, I'm able to use the default microphone. but unable to connect to the Azure STT socket server. the second error mentioned above persists.

**Scenario:**
I'm hosting this solution in my local network to be used by everyone on the network. So I'm testing index.html by hosting using Python.

**Comment by manosec** [comment]
@dargilco, Able to see some debug info while loading the index.html file, FYR below.

![error_sdk](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/86837128/b3e527c8-3ce9-462b-b24c-b8137448732b)

**Comment by manosec** [comment]
I also want to mention that, at the initial stage of this project I used **fromDefaultMicrohpone()**  to test but it is not working when deployed on the server.  

1. Can we use the **fromDefaultMicrophone()** when deploying remotely in the server or we have to use audio stream method?

**Comment by glharper** [comment]
Hi @manosec A lot of issues here:
- You cannot use fromDefaultMicrophone when deploying remotely, it assumes client hardware access from the browser
- Could you tell me more about the connection error you're seeing when deploying locally? (The "websocket connection to 'wss://centralindia.stt..." message)? What happens when you ping that host (centralindia.stt.speech.microsoft.com) from that machine?
- For streaming from client to server to Azure, that's a viable pattern. If you were getting recognized events, that's a good sign. The bad results could indicate the audio format is incorrect. Many microphones use a 44.1 kHz bitrate, and I see your bitrate is 16 kHz.

**Comment by manosec** [comment]
Hey there, sorry for the long delay. The issue is due to running the app on the HTTP scheme and not on HTTPS. Javascript uses **getUserMedia()** method to access the user devices mic which is only able to access the mic from a trusted source(HTTPS). Since I'm using a development server HTTP. I couldn't able to use the client's mic. Thanks for your assistance @glharper  @dargilco.
