### ISSUE TITLE
how to save the audio data to file with C++ after calling text to speech service?

### ISSUE THREAD

**Issue by tjliupeng** [Azure-Samples/cognitive-services-speech-sdk#217]
Hi, I try to modify the sample code quickstart/text-to-speech/cpp-linux/helloworld.cpp to save the audio data to file, but the wav file can't be displayed.

`
void synthesizeSpeech()
{
    // Creates an instance of a speech config with specified subscription key and service region.
    // Replace with your own subscription key and service region (e.g., "westus").
    auto config = SpeechConfig::FromSubscription("xxxx_key", "eastasia");
    //config->SetSpeechSynthesisLanguage("zh-CN");
    config->SetSpeechSynthesisVoiceName("Microsoft Server Speech Text to Speech Voice (en-US, ZiraRUS)");

    // Creates a speech synthesizer using the default speaker as audio output. The default spoken language is "en-us".
    auto synthesizer = SpeechSynthesizer::FromConfig(config);

    // Receive a text from console input and synthesize it to speaker.
    cout << "Type some text that you want to speak..." << std::endl;
    cout << "> ";
    std::string text;
    getline(cin, text);

    auto result = synthesizer->SpeakTextAsync(text).get();

    // Checks result.
    if (result->Reason == ResultReason::SynthesizingAudioCompleted)
    {
        cout << "Speech synthesized to speaker for text [" << text << "]" << std::endl;

        auto audiolen = result->GetAudioLength();

        cout << "The audio length is " << audiolen;

        auto audiodata = result->GetAudioData();

        ofstream fout("test.wav", ios::out | ios::binary);
        fout.write((char*)&(*audiodata)[0], audiolen);
        fout.close();
    }
    else if (result->Reason == ResultReason::Canceled)
    {
        auto cancellation = SpeechSynthesisCancellationDetails::FromResult(result);
        cout << "CANCELED: Reason=" << (int)cancellation->Reason << std::endl;

        if (cancellation->Reason == CancellationReason::Error)
        {
            cout << "CANCELED: ErrorCode=" << (int)cancellation->ErrorCode << std::endl;
            cout << "CANCELED: ErrorDetails=[" << cancellation->ErrorDetails << "]" << std::endl;
            cout << "CANCELED: Did you update the subscription info?" << std::endl;
        }
    }

    // This is to give some time for the speaker to finish playing back the audio
    cout << "Press enter to exit..." << std::endl;
    cin.get();
}
`

**Comment by chrisbasoglu** [comment]
The API creates a raw PCM stream by default.  So by default it is not in wav format.  If you want wav, change the output format to riff.  https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechconfig.setspeechsynthesisoutputformat?view=azure-dotnet#Microsoft_CognitiveServices_Speech_SpeechConfig_SetSpeechSynthesisOutputFormat_Microsoft_CognitiveServices_Speech_SpeechSynthesisOutputFormat_
