### ISSUE TITLE
[.NET 8] Warning: "Found version-specific or distribution-specific runtime identifiers"

### ISSUE THREAD

**Issue by ladenedge** [Azure-Samples/cognitive-services-speech-sdk#2170]
### **Describe the bug**

Including the [Microsoft.CognitiveServices.Speech NuGet package](https://www.nuget.org/packages/Microsoft.CognitiveServices.Speech) yields a build warning.

```
C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(284,5):
  warning NETSDK1206: Found version-specific or distribution-specific runtime identifier(s):
  centos7-x64, win10-arm, win10-arm64. Affected libraries: Microsoft.CognitiveServices.Speech.
  In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers
  will not be found by default. See https://aka.ms/dotnet/rid-usage for details.
```
### **To Reproduce**

1. Create an empty .NET 8 Console App.
2. Install the Microsoft.CognitiveServices.Speech NuGet package.
3. Build the solution.

### **Expected behavior**

No warnings!

### **Version of the Cognitive Services Speech SDK**

Microsoft.CognitiveServices.Speech **v1.33.0**.

### **Platform, Operating System, and Programming Language**

 - OS: Windows
 - Hardware: x64
 - Programming language: C#
 - Visual Studio 2022, .NET 8

I hope I'm posting this to the right place.  Thanks for your time!

**Comment by dargilco** [comment]
Hi @ladenedge , this is Darren from the Speech SDK team. Thank you for opening this issue. I will look into this and report back here shortly.

**Comment by dargilco** [comment]
@ladenedge we have an internal work item to switch to portable RIDs (per [NTESDK1206](https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1206)). Meanwhile, your application should work fine other than seeing this warning. If you like, you can suppress this warning by adding this to your .csproj file:

```xml
<ItemGroup>
  <RuntimeHostConfigurationOption Include="System.Runtime.Loader.UseRidGraph" Value="true" />
</ItemGroup>
```

(Internal work task number 6023463)

**Comment by ladenedge** [comment]
Thank you.  Looking forward to the new version!

**Comment by dargilco** [comment]
@ladenedge The upcoming release (due out next week, version 1.34) will include a fix for this. Thank you again for reporting this issue!

**Comment by aherrick** [comment]
@dargilco not fixed in 1.34.1

**Comment by ladenedge** [comment]
The warning is still there, but the content is a bit different.  Now instead of showing many RIDs, I only see **centos7-x64**:

```
C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(284,5):
   warning NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): centos7-x64.
   Affected libraries: Microsoft.CognitiveServices.Speech. In .NET 8.0 and higher, assets for version-specific
   and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details.
```

Just to confirm, I have the following in my build log showing the version number:

```
C:\Users\laden\.nuget\packages\microsoft.cognitiveservices.speech\1.34.1\lib\netstandard2.0
```

**Comment by ladenedge** [comment]
I went ahead and opened a new ticket: #2244.  (Please feel free to close that one and re-open this one if that's the preferred way to handle this sort of thing.)

Thank you!
