### ISSUE TITLE
[Android] SPXERR_RUNTIME_ERROR when using the Microsoft Audio Stack (MAS) 

### ISSUE THREAD

**Issue by tyoh-love** [Azure-Samples/cognitive-services-speech-sdk#2171]
I'm getting below error message when I try to run the quickstart sample "Keyword-recognizer" under  "quickstart/java/android/keyword-recognizer"

-- Error messages
2023-12-07 17:54:41.372 20946-21004 SpeechSDKDemo           com...ces.speech.samples.quickstart  E  unexpected Exception with an error code: 0x1b (SPXERR_RUNTIME_ERROR)

-- modified parts described as below 
-----------------------------------
    public void onSpeechButtonClicked(View v) {
        TextView txt = (TextView) this.findViewById(R.id.hello); // 'hello' is the ID of your text view
        txt.setText("Say \"Computer\"");

        Runnable asyncTask = () -> {

            try (

             //* code modification begin *//
                AudioProcessingOptions audioProcessingOptions = AudioProcessingOptions.create(
                        AudioProcessingConstants.AUDIO_INPUT_PROCESSING_ENABLE_DEFAULT, 
                        PresetMicrophoneArrayGeometry.Mono);

                AudioConfig config = AudioConfig.fromDefaultMicrophoneInput(audioProcessingOptions);
           //*  code modification end *//

                 KeywordRecognizer reco = new KeywordRecognizer(config);
                 InputStream is = assetManager.open("kws.table");
                 KeywordRecognitionModel model = KeywordRecognitionModel.fromStream(is, "computer", false);
                 ) {
                .....
---------------------------------------------------

1. open "Keyword-recognizer" sample under  "quickstart/java/android/keyword-recognizer"
2. Add   AudioProcessingConstants.AUDIO_INPUT_PROCESSING_ENABLE_DEFAULT,   -> code listed above 

-- SDK version : 1.33

-- Platform
 * OS: Windows11 23H2
 * Hardware - 13th Gen Intel(R) Core(TM) i9-13980HX  , RAM 64GB
 * Programming language: Java (Android Studio Iguana | 2023.2.1 Canary 16)

**Comment by dargilco** [comment]
@tyoh-love On devices with Android 10 and later, audio processed with Acoustic Echo Cancellation (AEC), Noise Suppression (NS) and Adaptive Gain Control (AGC) can be captured if it is available. These articles provide more information:
 
https://developer.android.com/reference/android/media/audiofx/AcousticEchoCanceler.html
https://developer.android.com/reference/android/media/audiofx/AutomaticGainControl.html
https://developer.android.com/reference/android/media/audiofx/NoiseSuppressor.html

**Comment by BigVeila** [comment]
@dargilco how about iOS?

**Comment by dargilco** [comment]
@rhurey @pankopon for triage
