### ISSUE TITLE
How to train custom speech to text avatar? Please guide us in the way 😄 

### ISSUE THREAD

**Issue by furo-ops** [Azure-Samples/cognitive-services-speech-sdk#2175]
**Is your feature request related to a problem? Please describe.**
I would love how to train my own avatar to create a custom speech avatar, i saw there are a few indications but no samples, demo files or a clear guide to implement it.

**Describe the solution you'd like**
I would love to have an easier path to create my custom speech avatar . I would like to know where and how should i train my avatar model, and if i have to do it on my own to let me know. Also in that case to know where and how should i upload this new custom model to use it properly.

**Describe alternatives you've considered**
I considered switching to other ai avatars like D-ID but the pose-control and connection to LLMs makes it great for integration with a couple of ideas me and my team have

**Comment by brandom-msft** [comment]
Hi @furo-ops, thanks for your interest in Custom Speech! Your feedback is helpful for us to capture what people are interested in. We don't have a single guide that walks through everything you mentioned, but here are some resources you can review:

- [Text to Speech avatar overview (preview)](https://learn.microsoft.com/azure/ai-services/speech-service/text-to-speech-avatar/what-is-text-to-speech-avatar) on Microsoft Learn
- [Speech Studio](https://speech.microsoft.com/portal) also has a preview hub for "Text to speech avatar" where you can try running a sample against your own resource.
- For training a custom model, have a look at the [Custom Neural Voice](https://learn.microsoft.com/azure/ai-services/speech-service/custom-neural-voice) documentation (which also has a sub-section for how to create, train, deploy and use your  model)

**Comment by jpalvarezl** [comment]
To keep our open issues list up to date, this item will be closed since it's been inactive and needs more information to proceed. Please file a new issue (and feel free to reference this one) if there's new information we can follow up on. Thank you!
