### ISSUE TITLE
Store Input audio from "fromMicrophoneInput"

### ISSUE THREAD

**Issue by priyanshusingh18** [Azure-Samples/cognitive-services-speech-sdk#2177]
I am using ContinuousRecognitionAsync to assess pronunciation with audio from microphone. I want to store the audio recorder and play it back to the user or upload the audio to storage. 
I could not find a way to achieve that?
Here is my code.
```
const audioConfig = SpeechSDK.AudioConfig.fromMicrophoneInput();
            const pronunciationAssessmentConfig = new SpeechSDK.PronunciationAssessmentConfig("",
                SpeechSDK.PronunciationAssessmentGradingSystem.HundredMark,
                SpeechSDK.PronunciationAssessmentGranularity.Phoneme,
                false);
            pronunciationAssessmentConfig.enableProsodyAssessment = true;
            pronunciationAssessmentConfig.enableContentAssessmentWithTopic(topic);
            recognizer = new SpeechSDK.SpeechRecognizer(speechConfig, audioConfig);

            pronunciationAssessmentConfig.applyTo(recognizer);
```

**Comment by brandom-msft** [comment]
Hi @priyanshusingh18, unfortunately this is not directly supported by the SDK. One way you could go about this would be to capture the microphone input to audio stream and use that stream to save to file, playback audio, and/or feed into a recognizer.

(marking semi-related Issue #1773)
