### ISSUE TITLE
IntentRecognizer does not process speech if model is used with it

### ISSUE THREAD

**Issue by demongolem** [Azure-Samples/cognitive-services-speech-sdk#218]
**Describe the bug**
With SpeechRecognizer, my microphone is recognized.  With IntentRecognizer and no intents, my microphone is recognized.  With IntentRecognizer and intents not involving a LanguageUnderstadningModel, my microphone is recognized.  I reference any of my intents from LanguageUnderstandingModel and `recognize_once` times out after 15 seconds having not processed any speech.

**To Reproduce**
1. Invoke `intent_recognizer.add_intent(model, 'My Intent', 'my intent')` before performing ` recognize_once ` where intent_recognizer is a IntentRecognizer and model is a LanguageUnderstandingModel.

**Expected behavior**
Not only is the speech processed, but in this case the intent_id my intent should be recognized should I speak an appropriate utterance.

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

1.4.0

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - please be specific
Windows 10
 - Hardware - x64, x86, ARM, ...
x64
 - Programming language: C#, C++, Java, JavaScript, Objective-C, Python
Python 
- Browser [e.g. Chrome, Safari] (if applicable) - please be specific
N/A

**Additional context**
 - Error messages, log information, stack trace, ...
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

```
	intent_recognizer = intentsdk.IntentRecognizer(speech_config=speech_config, audio_config=audio_config)
	model = intentsdk.LanguageUnderstandingModel(app_id=nlu_application_key)
	intent_recognizer.add_all_intents(model)
	# hangs on this line
	result = intent_recognizer.recognize_once()
```

**Comment by demongolem** [comment]
I figured out why it was hanging for me.  I had my app deployed on staging but not production  If I deploy on production, the model will work (I use the add_all_intents call as above to add all intents from my model).  Is that a requirement and is it documented anywhere: you have to use production and cannot use staging?  Other methods within the LUIS api (for example the endpoint GET call) allow a boolean to be passed to say if it is staging or not.  Also, a better error message would be appreciated in the case that a deployed app cannot be found instead of just simply timing out.

**Comment by rhurey** [comment]
Thanks for the request, I've added a task to support staging into our backlog.

**Comment by MaheshSasidharan** [comment]
I am still having this problem. I deployed my  LUIS model to production, and in my node app [github](https://github.com/MaheshSasidharan/cognitive-service/blob/f261d583df394461e09998a698ccc61ae127ed17/server/cognitive/intent.js#L36) I added `recognizer.addAllIntents(lm);`,

Strangely, the recognizer works, add calls back `sessionStarted`, `speechStartDetected` and `recognizing` but never calls back `recognized` `speechEndDetected`  or success method of `recognizeOnceAsync`. It kind of behaves as if it's in `StartContinuousRecognitionAsync` mode.

**Comment by rhurey** [comment]
Couple of things:
1) Your sample code has a key in it. You should remove the key from the sample and regenerate the key.

2) From your symptoms, I'm going to suspect the push stream isn't ever being closed. This will result in the SDK not sending and end of audio packet to the service. Which depending on where audio stopped can result in the speech service waiting for more audio to complete recognition.

**Comment by welliot** [comment]
I have been experiencing similar problems to what @MaheshSasidharan described in JS except I was getting in objective-c/Swift -  I posted to [stackoverflow] (https://stackoverflow.com/questions/59352564/cant-get-speech-sdk-to-return-luis-intents-in-swift).  Have yet to find a solution.

**Comment by rhurey** [comment]
With a session ID and an approximate time I can look at telemetry and see if I can find out what's happening.

**Comment by welliot** [comment]
Thanks @rhurey  - I managed to track down issue; ironic as I had battled for a day and found solution 10 minutes after posting here.  

Solution: I created a new LUIS (All In One) resource on S0 tier and assigned to my LUIS model and then it started to work.  Need to figure out if it was because I changed pricing tier from F0 or something else.    Its Kinda strange as speech had been working fine with subscription key in BotFramework but just happy it worked.

**Comment by Hariomagr** [comment]
I am facing a similar issue. In my case the success or error method of `recognizeOnceAsync` is never called in javascript.
I also tried to do similar in java sdk (android), and there I get the result reason as `RecognizedSpeech`  but I'm expecting result reason to be `RecognizedIntent`.
