### ISSUE TITLE
Error code: 1007. Error details: Invalid audio channel configuration

### ISSUE THREAD

**Issue by yongdaimi** [Azure-Samples/cognitive-services-speech-sdk#2180]
Describe the bug

Transcribing audios using Azure Speech To Text SDK in Java. For one audio getting the transcription correctly, while for the other getting the error: Recognition failed with Canceled, Error details: Connection was closed by the remote host. Error code: 1007. Error details: Invalid audio channel configuration. SessionId: 82f7493f2cc04140ae8c216b8b939ea0.

out1.wav - Getting the correct transcription
pronunciation_assessment.wav - Getting the correct transcription
out.wav - Geting the above error
out2.wav - Geting the above error

[sample-audio.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/13692376/sample-audio.zip)

**Comment by yongdaimi** [comment]
The sample is as follows:
```java
                final AudioConfig audioInput = AudioConfig.fromWavFileInput(copyAssetToCacheAndGetFilePath("out2.wav"));
                final SpeechRecognizer reco = new SpeechRecognizer(speechConfig, audioInput);

                final Future<SpeechRecognitionResult> task = reco.recognizeOnceAsync();
                setOnTaskCompletedListener(task, result -> {
                    String s = result.getText();
                    if (result.getReason() != ResultReason.RecognizedSpeech) {
                        String errorDetails = (result.getReason() == ResultReason.Canceled) ? CancellationDetails.fromResult(result).getErrorDetails() : "";
                        s = "Recognition failed with " + result.getReason() + ". Did you enter your subscription?" + System.lineSeparator() + errorDetails;
                    }

                    reco.close();
                    Log.i(logTag, "Recognizer returned: " + s);
                    setRecognizedText(s);
                    enableButtons();
                });
```
Can anyone help me?

**Comment by yongdaimi** [comment]
I have found the problem：
![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/8119766/4008f49f-9e54-4cd9-8902-892f1e159c3f)

Close this question, thank you all

**Comment by yongdaimi** [comment]
Close this issure.

**Comment by hijackwust** [comment]
thank you, resolved my problem
