### ISSUE TITLE
Language Identification not working for Javascript SDK on recognizing part.

### ISSUE THREAD

**Issue by amin45666** [Azure-Samples/cognitive-services-speech-sdk#2187]
**JS SDK speech recognition**
- I would like to inquire whether the intermediate confidence level for speech recognition in the JS SDK is currently in progress or if it is already available.

**Describe the bug**

- When utilizing the speech recognition feature, the intermediate part still does not function correctly. Based on my research, it appears that there is no support for the JS SDK for the intermediate part, as I continue to encounter the issue of `privLanguageDetectionConfidence` being undefined.
- This is what we have so far in JS.
```javascript
let audioConfig = SpeechSDK.AudioConfig.fromDefaultMicrophoneInput();
recognizer = SpeechSDK.SpeechRecognizer.FromConfig(
  speechConfig,
  autoDetectSourceLanguageConfig,
  audioConfig
);

 recognizer.recognizing = (s, e) => {
    let asr = e.result.text;
    var languageDetectionResult =
      SpeechSDK.AutoDetectSourceLanguageResult.fromResult(e.result);
    detectedLanguage = languageDetectionResult.language;
    console.log(
      detectedLanguage
    );

recognizer.recognized = (s, e) => {
    let asr = e.result.text;
    var languageDetectionResult =
      SpeechSDK.AutoDetectSourceLanguageResult.fromResult(e.result);
    detectedLanguage = languageDetectionResult.language;
    console.log(
      detectedLanguage
    ); 
```
<img width="546" alt="Screenshot 2023-12-19 at 1 29 32 PM" src="https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/99399754/14f2eefe-80fa-41a0-815e-80875570b20b">

**To Reproduce**

1. We incorporate audio input in the script, but after receiving the input, the recognizing process fails and displays an undefined detected value.

**Expected behavior**

- Upon receiving the audio input, the recognizing module is designed to identify and detect the language embedded in the audio content. However, currently, there seems to be an issue, as the recognizing process fails to perform this language detection, resulting in an undefined value for the detected language. This limitation is affecting the accurate interpretation of the audio content in terms of language identification. Interestingly, we're getting results using the Python SDK.

**Additional context**

 - This refers to our earlier discussion in which you mentioned that `final confidence == intermediate confidence`. This is the issue [link](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1957)

**Comment by BrianMouncer** [comment]
@glharper 

Can you answer about the current state of language autodetection API in the JS SDK?


Thanks

**Comment by glharper** [comment]
@amin45666 From my services contact: "Intermediate LID confidence is not technically possible today and not in the pipeline. Language detection itself only happens at segmentation (as in only when a Recognized event is sent back from the service)."

I wonder if the Python SDK is saving the previous recognized value and carrying it to each intermediate result before the next recognized result. Would such behavior be helpful for your use case in the JS SDK?

**Comment by jpalvarezl** [comment]
To keep our open issues list up to date, this item will be closed since it's been inactive and needs more information to proceed. Please file a new issue (and feel free to reference this one) if there's new information we can follow up on. Thank you!
