### ISSUE TITLE
 MAUI iOS devices. RecognizeOnceAsync returns SPXERR_MIC_ERROR starting from the second call. 

### ISSUE THREAD

**Issue by rburnashev85** [Azure-Samples/cognitive-services-speech-sdk#2188]
**Describe the bug**

- First call. Everythink is ok. await speechRecognizer.RecognizeOnceAsync() returns  Reason = RecognizedSpeech and recognized text.
- Second and following calls. await speechRecognizer.RecognizeOnceAsync() hangs device for a second and then returns Reason = Cancelled. CancellationDetails = Reason: Error ErrorDetails: 0x15 (SPXERR_MIC_ERROR)

**To Reproduce**

```
var speechConfig = SpeechConfig.FromSubscription(_configurations.Value.Key, _configurations.Value.Region);
speechConfig.SpeechRecognitionLanguage = _configurations.Value.Language;

using (var audioConfig = AudioConfig.FromDefaultMicrophoneInput())
{
    using (var speechRecognizer = new SpeechRecognizer(speechConfig, audioConfig))
    {
        var speechRecognitionResult = await speechRecognizer.RecognizeOnceAsync();
        var cancellationDetails = CancellationDetails.FromResult(speechRecognitionResult);
        if (speechRecognitionResult.Reason == ResultReason.RecognizedSpeech)
        {
            return new SpeechSynthesisRecognizeSpeechResultDto
            {
                Status = SpeechSynthesisStatus.Ok,
                Text = speechRecognitionResult.Text,
                Duration = speechRecognitionResult.Duration
            };
        }
        else
        {
            return new SpeechSynthesisRecognizeSpeechResultDto
            {
                Status = SpeechSynthesisStatus.Error,
                ErrorMessage = $"Reason = {speechRecognitionResult.Reason}; CancellationDetails = {cancellationDetails}",
                Duration = speechRecognitionResult.Duration
            };
        }
    }
}
```

**Version of the Cognitive Services Speech SDK**

 - Microsoft.CognitiveServices.Speech nuget 1.32.1

**Platform, Operating System, and Programming Language**

 - .NET 7. MAUI. Real iOS devices. Tested on iPhone 12 and iPad 6

**Additional context**

- on Windows and Android is working fine.

**Comment by rburnashev85** [comment]
Sorry. I found out that the errors happens after I first time call this library https://github.com/jfversluis/Plugin.Maui.Audio.
It seems that the library doesn't release microphone correctly in iOS.

So the bug doesn' related to the cognitive services.

How it happens in my app:
1) I call  speechRecognizer.RecognizeOnceAsync(). I get Text
2) Then I call  speechSynthesizer.SpeakTextAsync(Text) and save result to byte[]
3) Then I call Plugin.Maui.Audio to play the sound byte[]
4) Then I call  speechRecognizer.RecognizeOnceAsync() again and it returns SPXERR_MIC_ERROR

**Comment by rburnashev85** [comment]
I removed all Plugin.Maui.Audio stuff and still get the SPXERR_MIC_ERROR error! It seems that SpeakTextAsync somehow breaks microphone on iOS:

1. I call speechRecognizer.RecognizeOnceAsync(). I get Text
2. Then I call speechSynthesizer.SpeakTextAsync(Text) and save result to byte[]
4. Then I call speechRecognizer.RecognizeOnceAsync() again and it returns SPXERR_MIC_ERROR

Step 2 code is similar to SynthesisToResultAsync() example from https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_synthesis_samples.cs

```
var speechConfig = SpeechConfig.FromSubscription(_configurations.Value.Key, _configurations.Value.Region);
speechConfig.SpeechSynthesisVoiceName = _configurations.Value.Voices.FirstOrDefault(x => x.DisplayName == voiceDisplayName)?.Name;

using (var speechSynthesizer = new SpeechSynthesizer(speechConfig, null))
{
    var speechSynthesisResult = await speechSynthesizer.SpeakTextAsync(text);
    if (speechSynthesisResult.Reason == ResultReason.SynthesizingAudioCompleted)
    { 
        return new SpeechSynthesisSpeakTextResultDto
        {
            Status = SpeechSynthesisStatus.Ok,
            AudioData = speechSynthesisResult.AudioData
        };
    }
    else
    {
        return new SpeechSynthesisSpeakTextResultDto
        {
            Status = SpeechSynthesisStatus.Error,
            ErrorMessage = $"Reason = {speechSynthesisResult.Reason};"
        };
    }
}
```

**Comment by BrianMouncer** [comment]
My first guess would be a thread context issue with the audio config object.

using (var audioConfig = AudioConfig.FromDefaultMicrophoneInput())

Is it possible that audioConfig is disposed of by the time the second call to RecognizeOnceAsync() is made?

**Comment by rburnashev85** [comment]
> My first guess would be a thread context issue with the audio config object.
> 
> using (var audioConfig = AudioConfig.FromDefaultMicrophoneInput())
> 
> Is it possible that audioConfig is disposed of by the time the second call to RecognizeOnceAsync() is made?

No it is not possible. Anyway I can call RecognizeOnceAsync many times in a row and it works fine. But after I make a single call to SpeakTextAsync RecognizeOnceAsync starts to return SPXERR_MIC_ERROR

**Comment by rburnashev85** [comment]
Finally, I found the source of the issue. 

I used this snippet of code https://github.com/jfversluis/Plugin.Maui.Audio/wiki :

> How to make the audio play even though the hardware silent/mute switch is toggled?
> Add this snippet before you start playing audio in your .NET MAUI app:

```
#if IOS
    AVFoundation.AVAudioSession.SharedInstance().SetCategory(AVAudioSessionCategory.Playback);
#endif
```

And it somehow breaks microphone. So it is not related to cognitive speech services from azure team.
