### ISSUE TITLE
Create a sample or quickstart for python async operation

### ISSUE THREAD

**Issue by demongolem** [Azure-Samples/cognitive-services-speech-sdk#219]
**Is your feature request related to a problem? Please describe.**

There is a c# example for async operation involving the IntentRecognizer, however the way to go about registering callbacks is quite different in c# than python.  It took me a good while to figure out how to do it in python, especially without source code access.  Therefore an example that shows how to properly register and use callbacks for python.

**Describe the solution you'd like**

A new file constituting a working example under the samples directory in the python subfolder.

**Describe alternatives you've considered**

Scream real loud?  No seriously, I have the blocking case working just fine, however there are cases when the async is preferred in my setup and so using blocking is only partially good.

**Additional context**

I see #148, which was closed, however nothing was explicitly discussed as what needs to be done.  It will be far clearer to future users of this library if they have an example to look at which fills in a gap of the how-to examples.

**Comment by chlandsi** [comment]
Hi @demongolem, did you have a look at e.g. [this sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/9bfc8798d88a4c44759847635bab15b4778eb0e5/samples/python/console/speech_sample.py#L193)? If there is anything concrete that is missing, we'll be happy to add it. And the repo is open-source, so if there is something you found particularly helpful that is missing, you are welcome to add it ;)

Thanks!

**Comment by demongolem** [comment]
Thanks for the reply @chlandsi.  This is half the story, the sample you share.  There are two ways to handle the async family of functions.  One is to use the .get() blocker call as you have.  Second is to register the recognizer (whether it be Speech or Intent) with callbacks like `	intent_recognizer.recognized.connect(foo)` and then to implement the `foo` method which contains a single args parameter.  For my usage, this second version is the only of the two that makes sense, but both are perfectly valid.  Thanks for the invitation, I may well later today add a sample that covers this callback path which is missing.

**Comment by demongolem** [comment]
Actually, some of the callback stuff was covered in the continuous case it looks like.  I think having a sample for the once case as well will be useful, so I have created a pull requested for what that looks like.  I have run it with my own keys and I get the expected results, that is the speech from the mic is recognized and the test id in the code is returned as the predicted intent

**Comment by chlandsi** [comment]
Hi @demongolem, thank you for the pull request #220 ! I guess the underlying problem is that the docs don't make it sufficiently clear that the event/callback mechanisms are the same for one-shot and for continuous recognition. It is good to have this additional example for intent, I will adapt it into an example case for all recognizer types, which illustrates that one-shot can be used with callbacks. It might take a few days though.

**Comment by chlandsi** [comment]
Closed by #220.
