### ISSUE TITLE
WebRTC channel does not connect or disconnects after sometime even when the canonical example is used

### ISSUE THREAD

**Issue by enestaylan** [Azure-Samples/cognitive-services-speech-sdk#2190]
We are using Azure speech services with Microsoft communication services for webrtc connection in order to use the text to speech avatar in our application; this is our azure link for the talking avatar:
https://speech.microsoft.com/portal/4066aae6c039458c9da1829eecd71f81/talkingavatar

We have a speech resource in WestUs2 which appears to be the only region allowed for avatar, so we use the endpoint https://westus2.api.cognitive.microsoft.com/

We are using ice server from Microsoft communication services with the endpoint turn:relay.communication.microsoft.com:3478.

However, even when we use Microsoft's avatar example here in https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/c648407902b32ce722df681086bf558fb39ba7b3/samples/js/browser/avatar we have lots of connection issues, either as not connecting in the first place, or disconnection after a few minutes.

We use this turn server 'turn:relay.communication.microsoft.com:3478' from Turkey and Argentina, where our developers are located, and they all have the same problems.

Would anyone know if these connection problems are due to the fact that Avatar API is in public preview, or is this a common problem in turn:relay.communication.microsoft.com:3478 connections?
Perhaps worth mentioning that 10 days ago we had much fewer issues, but things seem to be getting worse now unfortunately.

Any ideas or thoughts on how to address these connection issues would be greatly appreciated!!

**Comment by yulin-li** [comment]
Thanks for reporting this. We are investigating.

cc @yinhew

**Comment by nacartwright** [comment]
Experiencing the same thing but it seems to vary by machine. It runs fine on my primary, however, on others it just never connects.   Firefox seems to be the most reliable and connects the fastest.

**Comment by yinhew** [comment]
Can you ping relay.communication.microsoft.com and see which region is showing?

Like below:

ping relay.communication.microsoft.com
Pinging b-tr-skysc-asse-01.**southeastasia**.cloudapp.azure.com [20.202.43.102] with 32 bytes of data

Support the region should be near to your location.
