### ISSUE TITLE
Call the personal voice api and return You don’t have permission to access this resource

### ISSUE THREAD

**Issue by MIMI180306** [Azure-Samples/cognitive-services-speech-sdk#2191]
I have successfully applied for the api permission of personal voice, but when I call the Projects_Create and PersonalVoices_Create api, it returns You don’t have permission to access this resource, when I call the Consents_Create api, it works good, I call the Projects_Create api like this: 
curl --location --request PUT 'https://westeurope.api.cognitive.microsoft.com/customvoice/projects/abc?api-version=2023-12-01-preview' \
--header 'Ocp-Apim-Subscription-Key: MyKey' \
--header 'Content-Type: application/json' \
--data '{
  "description": "test personal voice",
  "kind": "PersonalVoice"
}'

**Comment by yulin-li** [comment]
Thanks for reporting this. We are reviewing.

**Comment by ForrestGumb** [comment]
Personal Voice API permission is ready on 2023/12/22. If you tried before that, please try again.

**Comment by MIMI180306** [comment]
> Personal Voice API permission is ready on 2023/12/22. If you tried before that, please try again.

I tried the Projects_Create api again today and still returned You don’t have permission to access this resource

**Comment by MIMI180306** [comment]
> Personal Voice API permission is ready on 2023/12/22. If you tried before that, please try again.

I tried the Projects_Create api again and now it works well
