### ISSUE TITLE
startContinuousRecognition will automatically stop

### ISSUE THREAD

**Issue by Zuckjet** [Azure-Samples/cognitive-services-speech-sdk#2192]
I downloaded the official iOS SDK "MicrosoftCognitiveServicesSpeech-XCFramework-1.34.0.zip" from your official website.
 
I want to use `[speechRecognizer startContinuousRecognition]` to implement real-time continuous  recognition, that the speech source come from microphone.  

here is my relevant code:

```
    SPXPushAudioInputStream *stream = [[SPXPushAudioInputStream alloc] init];
    AudioRecorder *recorder = [[AudioRecorder alloc]initWithPushStream:stream];
    SPXAudioConfiguration *audioConfig = [[SPXAudioConfiguration alloc]initWithStreamInput:stream];

    speechRecognizer = [[SPXSpeechRecognizer alloc] initWithSpeechConfiguration:speechConfig language:lang audioConfiguration:audioConfig];

  [speechRecognizer startContinuousRecognition];
```

when I call `[speechRecognizer startContinuousRecognition]`, it will begin recognizing, but will soon stop immediately.(even though i don't call `[speechRecognizer stopContinuousRecognition]` )
but if i sleep for N seconds, it will recognize N seconds, and then stop.

```
 SPXPushAudioInputStream *stream = [[SPXPushAudioInputStream alloc] init];
    AudioRecorder *recorder = [[AudioRecorder alloc]initWithPushStream:stream];
    SPXAudioConfiguration *audioConfig = [[SPXAudioConfiguration alloc]initWithStreamInput:stream];

    speechRecognizer = [[SPXSpeechRecognizer alloc] initWithSpeechConfiguration:speechConfig language:lang audioConfiguration:audioConfig];

  [speechRecognizer startContinuousRecognition];


  [NSThread sleepForTimeInterval:3.0f];      // add this code will delay stop
```

### What I expected 
if i don't call  `[speechRecognizer stopContinuousRecognition];`,    I expect continuous recognition not stopping.

**Comment by M-Hietala** [comment]
Could you please make sure that the speech recognizer instance you create does not go out of scope before recognition has been completed.

**Comment by Zuckjet** [comment]
Thanks, this issue has already be solved.

**Comment by DoubleLihui** [comment]
hi~ @Zuckjet ,  How to resolve this issue? i get the same issue recently.
