### ISSUE TITLE
In Linux, when using conda to create a new environment, text-to-speech generation is not working, but it works fine in the base environment.

### ISSUE THREAD

**Issue by zhaopu0710** [Azure-Samples/cognitive-services-speech-sdk#2193]
In Linux, when using conda to create a new environment, text-to-speech generation is not working, but it works fine in the base environment.

Error：**Speech synthesis canceled: CancellationReason.Error
Error details: Connection failed (no connection to the remote host). Internal error: 1. Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED wss://eastasia.tts.speech.microsoft.com/cognitiveservices/websocket/v1**

Code：

![111](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/50993924/b5b7f361-31d7-48f3-89b8-7aefb683da01)

Log：[LogfilePathAndName.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/13771521/LogfilePathAndName.log)

python 3.10

**Comment by yulin-li** [comment]
could you follow [this doc] to check?

especially

![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/12013783/8f382dac-640d-4fe4-9149-8e1474d6defc)

**Comment by xuxianren** [comment]
same issue in windows python3.10.  after upgrade 1.32.1 to 1.34.0

**Comment by zhaopu0710** [comment]
> 您可以按照[此文档]检查吗？
> 
> 尤其
> 
> ![图像](https://private-user-images.githubusercontent.com/12013783/292882067-8f382dac-640d-4fe4-9149-8e1474d6defc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNjIyMjMsIm5iZiI6MTcwNDI2MTkyMywicGF0aCI6Ii8xMjAxMzc4My8yOTI4ODIwNjctOGYzODJkYWMtNjQwZC00ZmU0LTkxNDktOGUxNDc0ZDZkZWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA2MDUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZTI1YWFmMTUzMDU4Njk1ZDYyYmJiN2ZlMTBkZTI1ZWU2MjRkYjBhZTU5ZWI3ZjgwOWQ5YzEyOGE2MjBmZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tLum1bc5L3PIzuB9p2aSvX0rYDqxABRzcIYGO0bBU8w)

This is very effective, thank you.

**Comment by zhaopu0710** [comment]
> same issue in windows python3.10. after upgrade 1.32.1 to 1.34.0

you can try the following：
` conda install openssl==1.1.1t`
