### ISSUE TITLE
Suspending custom endpoint model

### ISSUE THREAD

**Issue by anne-a** [Azure-Samples/cognitive-services-speech-sdk#2194]
I have a custom speech-to-text model deployed to an endpoint, however I only need it for a few hours a week. To limit the spending, is there a way to suspend and resume the endpoint? It looks like this is possible for the custom voice endpoint (https://learn.microsoft.com/en-us/azure/ai-services/speech-service/professional-voice-deploy-endpoint?pivots=rest-api#suspend-an-endpoint) but I can't see how to do this for the speech to text endpoint. Are there any other recommendations please to avoid paying for the endpoint to be running 24/7 if it's only needed during specific hours? Would the only option be to keep deleting the endpoint and recreating it when needed?

**Comment by pankopon** [comment]
Hi, to quote an answer from @heikora :

> We currently don’t have a concept of suspending a custom speech endpoint as the cost is fairly low at around $40/month. (...) So I think all you can do is delete the endpoint and create a new one, but up will end up with a new endpoint ID every time.

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
