### ISSUE TITLE
Fatal Exception: std::runtime_error - iOS [Swift SDK]

### ISSUE THREAD

**Issue by devSC** [Azure-Samples/cognitive-services-speech-sdk#2195]
Version:
- MicrosoftCognitiveServicesSpeech-iOS (1.33.0)

iOS
 - Hardware - x64
 - Programming language: Swift

**Additional context**
Exception with an error code: 0x1b (SPXERR_RUNTIME_ERROR) [CALL STACK BEGIN] 
3 MicrosoftCognitiveServicesSpeech 0x0000000108b81ef8 
GetModuleObject + 2164744 4 MicrosoftCognitiveServicesSpeech 0x0000000108b82024 
GetModuleObject + 2165044 5 MicrosoftCognitiveServicesSpeech 0x00000001087ef524 connection_close + 112 6 MicrosoftCognitiveServicesSpeech 0x000000010889e960 pal_string_to_wstring + 70504

**Comment by jpalvarezl** [comment]
To keep our open issues list up to date, this item will be closed since it's been inactive and needs more information to proceed. Please file a new issue (and feel free to reference this one) if there's new information we can follow up on. Thank you!
