### ISSUE TITLE
How to maintain socket connection in iOS and Android

### ISSUE THREAD

**Issue by Zhuoyi2015** [Azure-Samples/cognitive-services-speech-sdk#2198]
Hi,

Our staff are working on Azure speech translation with language detection. They implement functions based on sample code but they want to keep the socket connection alive. For example, the user may stay on that page but start to speak after several minutes. If we initialize the socket when opening page, would the socket automatically close? And they also do not know how to maintain the socket connection by themselves. Could you please give us some suggestions?

Wishes,
Zhuoyi

**Comment by rhurey** [comment]
Assuming Java, you could subscribe to the [disconnected event on the connection object](https://learn.microsoft.com/java/api/com.microsoft.cognitiveservices.speech.connection?view=azure-java-stable#com-microsoft-cognitiveservices-speech-connection-disconnected
)
And then open the connection when it disconnects. (you'll likely want to open it on a different thread)

**Comment by pankopon** [comment]
Closed as answered.
