### ISSUE TITLE
Challenges in auto-detecting certain languages with speech-to-text

### ISSUE THREAD

**Issue by theisof** [Azure-Samples/cognitive-services-speech-sdk#2202]
I'm using the Speech SDK in the browser and encountering an issue with `AutoDetectSourceLanguageConfig`. Specifically, it fails to function when certain languages, such as Bosnian, Serbian, and Albanian, are included in the `fromLanguages` list. Notably, no events are triggered for `recognizing`, `recognized`, or `canceled` when these languages are present.

While it operates correctly for most other languages, I'm curious if this is expected behavior. If so, how can I obtain a list of supported languages?

```js
const audioConfig = AudioConfig.fromDefaultMicrophoneInput();

// Working for most languages but not bs-BA, sr-RS, sq-AL and possible other languages
const autoDetectSourceLanguageConfig = AutoDetectSourceLanguageConfig.fromLanguages(['bs-BA', 'en-US']);
const speechRecognizer = SpeechRecognizer.FromConfig(
  speechConfig,
  autoDetectSourceLanguageConfig,
  audioConfig
);

// Working for all languages
speechConfig.speechRecognitionLanguage = 'bs-BA'
const speechRecognizer = new SpeechRecognizer(speechConfig, audioConfig);
```
Log:
[stt-log.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/13818854/stt-log.log)

Version: 1.34.0 npm package, used in the browser
OS: macOS and possible others
Hardware: ARM and possible others
Programming language: JavaScript
Browser: Chrome and possible others

**Comment by M-Hietala** [comment]
Please find the list of supported languages here https://learn.microsoft.com/en-us/azure/ai-services/speech-service/language-support?tabs=language-identification

The languages you mention are not supported.

**Comment by theisof** [comment]
Thanks! How can I obtain this list dynamically? Would love to avoid having to copy-paste language codes from the documentation page.
