### ISSUE TITLE
Not able to find code preview in UI nor in Repo for Whisper Model via Azure OpenAI Service. 

### ISSUE THREAD

**Issue by vishvas-chauhan** [Azure-Samples/cognitive-services-speech-sdk#2203]
I am not able to see codes preview into UI neither in repo. Can you please show us , how to use whisper model deployed in **Azure AI service** deployed in westeurope which is OK for deployment.

**Comment by heikora** [comment]
Hi, please find the link to the quickstart for using Whisper in Azure OpenAI here: https://learn.microsoft.com/en-us/azure/ai-services/openai/whisper-quickstart?tabs=command-line&pivots=rest-api

**Comment by pankopon** [comment]
Closed as answered.
