### ISSUE TITLE
TTS Avatar has sporadic loading times making WebRTC connection in Angular web app

### ISSUE THREAD

**Issue by jhoncue7** [Azure-Samples/cognitive-services-speech-sdk#2206]
### Overview of the Issue
We are facing long loading times with the WebRTC connection inside an Angular 17 web app. We are able to get the Avatar to make a WebRTC connection in an acceptable time when running the [basic.html](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/avatar/basic.html) sample in multiple browsers in both normal and incognito mode. We have ported the basic.html code into an Angular 17 component. Using the same configuration values as used in the basic.html sample we get sporadic WebRTC behaviors in different browsers. In some browsers, the Avatar loads just as fast as the basic.html sample and in other browsers it can take up to 40 - 45 seconds for the connection to be established and the avatar video to start streaming. We have also observed that for the browsers that take longer to connect, they also have more RTCPeerConnection errors. 

**Attached Files:**
* Find attached example code that can demonstrate the issue: [avatar-angular-mvp.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/13867569/avatar-angular-mvp.zip)
* Find attached Speech SDK logs: [speech-sdk-log-avatar-long-load-times.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/13867518/speech-sdk-log-avatar-long-load-times.txt)
* Diagnostic packet recordings from edge://webrtc-internals/: [webrtc_event_log_20240108_1818_8801_1.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/13867519/webrtc_event_log_20240108_1818_8801_1.log)
* Dump file from edge://webrtc-internals/: [webrtc_internals_dump.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/13867520/webrtc_internals_dump.txt)

### Version
**JavaScript SDK:** 
microsoft-cognitiveservices-speech-sdk: 1.34.0

### Use Case
Incorporating Text-To-Speech Avatar in an Angular 17 web app. By converting to an Angular component, we would be able to seamlessly utilize the Avatar in our main web application as a plug and play component wherever needed. For production we would be able to build the Angular application for prod and deploy to a static web site in Azure.

#### Expected behavior
The expected behavior is that once the Avatar is provided the necessary configuration information and the start session button is pressed, the avatar will load within 4 - 5 seconds. 

### Platform, Operating System, and Programming Language
* OS: Windows 11
* Hardware: x64
* Programming language: TypeScript
* Browsers: Microsoft Edge, Google Chrome

### Reproduce the Error

Find attached a zip file, avatar-angular-mvp.zip, which is a simple example that we have found to be able to reproduce the behavior explained above.
**Setup and configure example:**
* Unzip the file avatar-angular-mvp.zip 
* Navigate to avatar-angular-mvp/src/app/app.component.ts
* To run the app several configuration values need to be provided in the component inside of a commented section called **START MANUAL CONFIGURATION**, which is on line 48 in app.component.ts. The following configuration values need to be provided: 
  * iceServerUrl
  * iceServerUsername
  * iceServerCredential
  * speechServiceRegion
  * speechServiceKey

**Steps to reproduce the behavior:**
* Open a terminal at the root directory of the sample at: avatar-angular-mvp/
* Run command "npm install"
* Run command "ng serve" - start angular web app
* Open various browsers and navigate to: [http://localhost:4200/](http://localhost:4200/)
  * Because the behavior is sporadic, you may need to try several different browsers including different

**Comment by rhurey** [comment]
The error from the log shows the request are being throttled.

ConnectionClosedEvent | privReason: Protocols.Core.BadClientRequestException: The request is throttled because you have exceeded the con | privStatusCode: 1011

@yulin-li can you help out here?

**Comment by jhoncue7** [comment]
> The error from the log shows the request are being throttled.

You are right, those aren't the logs I intended to attach.  However, this is another issue we have also been seeing and it would be great to learn more about this issue as well. 

Find attached Speech SDK logs for a successful connection after WebRTC took a long time to connect: 
[speech-sdk-log-avatar-long-load-times-successful.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/13889566/speech-sdk-log-avatar-long-load-times-successful.txt)

**Comment by jhoncue7** [comment]
@rhurey, is there any update regarding my issue? Also, were you able to review the correct log file I included in my last comment?

**Comment by pankopon** [comment]
@yulin-li @yinhew Can you comment on this - any relation to https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2190?

**Comment by yinhew** [comment]
Hi, @jhoncue7 

We are able to reproduce the issue following your "Reproduce the Error" section.
And we found the issue is gone after commenting below lines in your code:

this.peerConnection.onicecandidate = (e: RTCPeerConnectionIceEvent) => {
      this.log(`onicecandidate status: ${JSON.stringify(e)}`);
    };

You can give it a try if it's still an issue for you.

Thanks,
Yinhe

**Comment by yinhew** [comment]
Hi, @jhoncue7 

We have a default limitation on the connection frequency: 2 new connections per minute.
Please refer to https://learn.microsoft.com/en-us/azure/ai-services/speech-service/speech-services-quotas-and-limits#real-time-text-to-speech-avatar

For further support regarding to this, you can contact avatarvoice@microsoft.com.

Thanks,
Yinhe
