### ISSUE TITLE
en-US Andrew Multilingual Neural voice inconsistent speaking rate after synthesis (sounds like a 🐿️ sometimes)

### ISSUE THREAD

**Issue by troyshu** [Azure-Samples/cognitive-services-speech-sdk#2208]
**Describe the bug**

Using the `en-US-AndrewMultilingualNeural` voice to synthesize speech results in speech spoken either at a "normal" rate, or a fast rate (sounds like a chipmunk 🐿️), depending on the input text and config. Unsure if this inconsistency affects other voices.

For example:

1. The text `This is a test sentence.` is spoken at a normal rate, whereas the text `This is a test sentence` (no period) is spoken at the fast "chipmunk" rate.
2. With the text `This is a test sentence.` and `speechSynthesisOutputFormat =
  SpeechSynthesisOutputFormat.Audio16Khz32KBitRateMonoMp3`, the text is spoken at a normal rate. With a higher sampling and bit rate, e.g. `speechSynthesisOutputFormat = SpeechSynthesisOutputFormat.Audio48Khz192KBitRateMonoMp3`, the text is spoken at the fast "chipmunk" rate.

**To Reproduce**

1. Run the following script (use your own Azure speech key and region)
2. Play the audio file that was generated, "test.mp3". It'll sound like a chipmunk
5. Or, use [Speech Studio](https://speech.microsoft.com/), find "AndrewMultilingualNeural", and try the text `This is a test sentence.` It'll sound like a chipmunk. Then, `This is a test sentence. This is another one.`. It'll speak it at a normal rate.

```
import {
  AudioConfig,
  ResultReason,
  SpeechConfig,
  SpeechSynthesisOutputFormat,
  SpeechSynthesizer,
} from 'microsoft-cognitiveservices-speech-sdk'
import { AZURE_SPEECH_KEY, AZURE_SPEECH_REGION } from '../tts/config'

const voice = 'en-US-AndrewMultilingualNeural'
// const voice = 'en-US-AvaMultilingualNeural'

const text = 'This is a test sentence'
// const text = 'This is a test sentence.'

const speechConfig = SpeechConfig.fromSubscription(
  AZURE_SPEECH_KEY,
  AZURE_SPEECH_REGION
)

speechConfig.speechSynthesisOutputFormat =
  SpeechSynthesisOutputFormat.Audio16Khz32KBitRateMonoMp3
// speechConfig.speechSynthesisOutputFormat =
//   SpeechSynthesisOutputFormat.Audio48Khz192KBitRateMonoMp3
speechConfig.speechSynthesisVoiceName = voice

const outputFile = './test.mp3'
const audioConfig = AudioConfig.fromAudioFileOutput(outputFile)
const synthesizer = new SpeechSynthesizer(speechConfig, audioConfig)

synthesizer.wordBoundary = function (s, e) {
  // audioOffset, duration are in ticks (100 nanoseconds)
  const timepointMs = e.audioOffset / 10000
  const durationMs = e.duration / 10000
  console.log(
    `Word "${e.text}" with type ${e.boundaryType}": ${timepointMs} ms timepoint, ${durationMs} ms duration, ${e.textOffset} text offset`
  )
}

// synthesize speech to file
synthesizer.speakTextAsync(
  text,
  (result) => {
    if (result) {
      // Check if the result is successful
      if (result.reason === ResultReason.SynthesizingAudioCompleted) {
        console.log(
          `Speech synthesis was successful. Audio written to file: ${outputFile}`
        )
      } else {
        console.error(`Speech synthesis canceled, ${result.errorDetails}`)
      }
      // Close the synthesizer to release resources
      synthesizer.close()
    }
  },
  (error) => {
    console.log(error)
    synthesizer.close()
  }
)
```

**Expected behavior**

Audio synthesized with the same speaking rate, regardless of the input text or speech config settings.

**Version of the Cognitive Services Speech SDK**

1.33.1

**Platform, Operating System, and Programming Language**

 - OS: macOS 13.5.1 Ventura
 - Hardware - M2 Max
 - Programming language: Javascript/Typescript

**Comment by rhurey** [comment]
Thanks for trying out en-US-AndrewMultilingualNeural.

I'll pass this on to the modeling team, and yes the same problem does repro for me.

**Comment by pankopon** [comment]
Service incident ref. 458373444 (@yulin-li FYI)

**Comment by Kerry-LinZhang** [comment]
Following up with voice owner for it

**Comment by Kerry-LinZhang** [comment]
Hi @troyshu thanks for the feedback, we have improved our model after, and the rate issue has been fixed, would you please try again, if there is still any problem, please feel free to let us know.

**Comment by pankopon** [comment]
Closed as fixed, please create a new issue if more support is needed.
