### ISSUE TITLE
Recognizer cannot be stopped and started

### ISSUE THREAD

**Issue by joshthor3222** [Azure-Samples/cognitive-services-speech-sdk#221]
I am using the speech SDK to convert user speech to text. We have found in loud environments using StartRecognitionOnce will never finish recognition, so we switched to StartContinuousRecognition because its recognizing functionality gives us context results with about a second delay. using this and a push to talk functionality we can effectively create push to talk functionality without worrying too much about ambient noise. 

The ideal functionality would be to set the recognizer and call startcontinuousrecognitionasync and endcontinuousrecognitionasync. however, if you call stop, calling start no longer works, you have to create an entirely new recognizer and destroy the old one.

**Comment by rhurey** [comment]
Sorry things aren't working well.

From your other questions I'm inferring that you're using the JavaScript binding, and trying to recognize speech from a browser using a microphone as the audio source. If any of that's wrong, let me know.

I'll take a look in our implementation and see if I can reproduce the problem, you should be able to call start / stop multiple times and each call should use the same connection resulting in improved performance.

**Comment by rhurey** [comment]
I spent some time with our sample app having modified it to cache the recognizer for continuous recognition and wasn't able to reproduce this problem.

Can you supply some more information that may help me out?
Was my assumption on this being a browser based implementation correct?
If so, what browser?
And is there any code you can share?

Thanks.

**Comment by wolfma61** [comment]
closing based on missing additional information

please reopen if you can supply the missing information.
