### ISSUE TITLE
[es-US Bilingual] Newly introduced models should not break compatibility

### ISSUE THREAD

**Issue by RomanValov** [Azure-Samples/cognitive-services-speech-sdk#2214]
This is a follow up for #2213 . Whereas original ticket is for specific recognition issue. This one is about change management.

The problem is that we have used "es-US" recognition local for some time and apparently it breaks without any changes/actions made on ours side. Introduction of bilingual feature possibly introduced breaking in our established workflows and required notable time to recognize, analyze and workaround changes.

It's desired that newly introduced models (at least those that could change recognition results in established production environments) should not override/break ones currently used. They should require explicit developer intent to be used.

Possible suggestions:

1) Use distinct names for bilingual models, i.e.:

```
es-US-Bilingual
es-en-US
```

or use properties like:

```
speechConfig.setProperty(PropertyId.SpeechServiceConnection_BiLingual, "true")
```

2) Use some kind of versioning, i.e.:

```
es-US-v1
es-US-v2
```

or use properties like:

```
speechConfig.setProperty(PropertyId.SpeechServiceConnection_Version, "202312")
speechConfig.setProperty(PropertyId.SpeechServiceConnection_Version, "stable")
speechConfig.setProperty(PropertyId.SpeechServiceConnection_Version, "latest")
```

---

Finally it would be nice if docs clearly point out which non-bilingual model could be used instead of bilingual ones. I.e. intuitively we have considered that "es-MX" may substitute "es-US" because regions are neighbored. However we also plan to use "fr-CA" in the future and in this case it's not obvious which model/locale should be used as a non-bilingual counter-part for it.

**Comment by BrianMouncer** [comment]
I'm not DRI this week, but happened to see your question.
I forwarded the other GH Issue to the owner of the Bilingual feature, and the DRI for next week will get back to you when they have more data.

I just wanted to ask if you are aware of, and considered using a custom speech endpoint?

https://speech.microsoft.com/portal/ea8a883cdde942bf90665ce6d55345b2/customspeech/overview

At the speech studio portal, you could create a new "speech project" and select es-US as the language.

![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/48774897/f0cb6fae-d741-432d-b153-d8e4c6e9d45b)


https://speech.microsoft.com/portal/ea8a883cdde942bf90665ce6d55345b2/customspeech/projects

When you deploy a new endpoint you can just select one of the currently available public models, or select any of the custom models you have built.
Selecting and deploying an unmodified baseline model would allow you to lock your custom endpoint to that specific "baseline" model, even if the public general purpose endpoint later deployed and started using a new model with additional features.

![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/48774897/bdfa315e-8d73-4471-84bb-82b327d66c07)

But more importantly, that would also give you the ability to test your application with specific models and changes before deploying them to the endpoint your production app is using. If you did not like the performance of the baseline model around specific words, you could add those words to your training data set, and test and deploy a custom model that adapted the baseline model to meet your exact needs...

**Comment by BrianMouncer** [comment]
If you do not want the heavier process control of a custom endpoint, and just want to get better recognition for a hand full of words used in the navigation of your app flow, you might take a look a providing PhraseListGrammars with your recognition to the public endpoint...

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/93872ce046f78bda2646c0c017ba1393e58b4f30/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L690C15-L690C15

Those will remove provide higher "weights" to the words you expect the user to say, and the remove the ambiguous text normalization choices the service can make between returning say "one two three four" versus "1234" or "1,234".  I think that would be enough to fix the cases where the bilingual engine will choose "See" or "C" when you would prefer "Si".

**Comment by RomanValov** [comment]
Hey @BrianMouncer . Thanks a lot for your comments dropped in a so quick manner. Due to that I was able to test custom endpoint with the old model before it had expired today. It looks like base model versions are a good groundwork to retain compatibility while upgrading models and looks similar to what I have proposed as version-based models.

There are several considerations/proposals/wishes that could make this more transparent and convenient to use:

1. As I've noted the old model had expired today and I no longer able to deploy/use it. However there were several hours when I was able to test it and it worked. I don't know when new bilingual model started to be available since according to it's name it was introduced in March of 2023. But What's New page on docs mentions it only with November update. Ideally it would be nice if there will be two model versions available any time. Or at least 6 or 12 month model versions overlap period.

2. Provide a way to choose model version on SDK side. I.e. using properties as proposed in my initial message. Tbh I wasn't aware about possibility to choose base model version using custom speech endpoints since I mostly work with client SDK and managing custom endpoints looks like an overkill to use older model versions.

3. Provide a way to get information about models available other than digging into Speech Studio. Indeed mentioning exact model versions on What's New page should be sufficient. It may also be a good idea to be able to obtain model version from code, i.e. from recognition result property.

4. Finally it would be nice to have aliases/labels like "stable" and "latest" for model versions for those who don't bother with exact versions.

**Comment by BrianMouncer** [comment]
I will send feedback about keeping older models available longer.
Maybe always have N and N-1 available?
Our DRI will get back to you about the poor results for "Si", when the bilingual model team has a chance to get back to us.

Yah, using custom endpoints also have different cost associated with it, as you're hosting your own private endpoint rather than using the shared public one, so a little over kill just to lock model version. I would be curious how it works for adding training data and adapting the latest bilingual models to get the desired performance you want for the specific words used in your app navigation flow though.

Were you able to try adding phrase list grammars to your app, to change the weights the engine uses for those words in the general purpose bilingual models?  I am guessing that is the simplest and quickest way to work around the current issue with "Si" and other very short words.

**Comment by RomanValov** [comment]
> I will send feedback about keeping older models available longer. Maybe always have N and N-1 available?
Keeping two model versions available at any moment is an ideal from my perspective.

I have commented Phrase List proposal on original ticket thread (#2213) since it's more related to the certain recognition issue than to model version management.

**Comment by glharper** [comment]
It appears this issue has an accepted workaround, so I'm closing it.
