### ISSUE TITLE
TTS with avatar has high security problems

### ISSUE THREAD

**Issue by palagonKevo** [Azure-Samples/cognitive-services-speech-sdk#2218]
I've been searching for a secure solution to use the Avatar with the TTS service, since the only way to use this service with React is developing it within the fronted part. This is so risky as people could get your API keys and since it's a web page you can't restrict the resource via IP, it should be able to be restricted via domain name, but there is no option to do that. Is there any way to restrict the access of the API keys to the domain name? If not, this product is not secure to use.

**Comment by yulin-li** [comment]
adding @yinhew

**Comment by yinhew** [comment]
@palagonKevo you can do the auth on your server side, following below order:
1. Client side: generate local SDP, pass it to server side
2. Server side: call speech SDK to auth, with the local SDP received from client
3. Server side: receive remote SDP from speech SDK, and pass the remote SDP to client side
4. Client side: setup WebRTC connection with local SDP and remote SDP.

**Comment by yinhew** [comment]
@palagonKevo you can encode the SDP to a base64 string and then send it, and then decode.
