### ISSUE TITLE
Mute button for the recognizer

### ISSUE THREAD

**Issue by joshthor3222** [Azure-Samples/cognitive-services-speech-sdk#222]
It seems impossible to pass a WebRTC compatible microphone stream to the audioconfig.fromstreaminput() function and have it actually recognize. to deal with loud ambient noise i was looking to mute the audio input going to the recognizer. something like a mute function in the audioconfig or recognizer could massively improve functionality.

**Comment by rhurey** [comment]
The WebRTC stream is fundamentally a different stream type from the Speech SDK streams. 

If you wanted to proxy a WebRTC stream as a stream input to the SDK so you could silence it, the best bet would be to inject a PullStream into the middle and buffer audio until the callback was fired and either return silence or the accumulated audio.

This isn't the preferable approach, though as it would continue to send audio to the speech service when  "muted" even though you'd not want any recognition preformed.

The best bet would be to start / stop recognition.
