### ISSUE TITLE
Speech Recognizer doesn't indicate if incorrect EndpointId is used

### ISSUE THREAD

**Issue by RomanValov** [Azure-Samples/cognitive-services-speech-sdk#2220]
**Describe the bug**

Both, Speech Synthesizer and Speech Recognizer provide a way to specify custom EndpointId.

When incorrect EndpointId is specified Speech Synthesizer ends up with Canceled result:

Here is an example of running `synthesisUsingCustomVoiceAsync` sample from `samples/java/jre/console`:

```
Your choice (0: Stop): 50

Enter some text that you want to speak, or enter empty text to exit.
> hello
CANCELED: Reason=Error
CANCELED: ErrorCode=BadRequest
CANCELED: ErrorDetails=Connection was closed by the remote host. Error code: 1007. Error details: Invalid deploymentId test. USP state: TurnStarted. Received audio size: 0 bytes.
CANCELED: Did you update the subscription info?
```

Log: [speech.synth.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/13941412/speech.synth.log)

But when incorrect EndpointId is used with Speech Recognizer there is no any indication of error.
And it seems that default non-custom endpoint is silently used:

Here is an example of running `recognitionUsingCustomizedModelAsync` sample from `samples/java/jre/console`:

```
Your choice (0: Stop): 4

Say something...
RECOGNIZED: Text=Hello.
```

Log: [speech.recog.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/13941414/speech.recog.log)

**To Reproduce**

1. Specify non existent custom endpoint id with `SpeechConfig.setEndpointId`
2. Run recognition

**Expected behavior**

Incorrect Endpoint Id leads to an error

**Version of the Cognitive Services Speech SDK**

1.34.0

**Platform, Operating System, and Programming Language**

 - OS: Ubuntu 22.04
 - Hardware - x64
 - Programming language: Java (OpenJDK 11)

**Comment by ralph-msft** [comment]
Thanks for using the Cognitive Services Speech SDK and reporting this issue. I have been able to reproduce the issue you are seeing and am following up with owners of the service to get more details on what the expected behaviour should be here.

**Comment by dargilco** [comment]
Tracked via internal ICM 463219927
