### ISSUE TITLE
503 during TTS 

### ISSUE THREAD

**Issue by gauravG2021** [Azure-Samples/cognitive-services-speech-sdk#2222]
Hi ,

I am getting 503 intermittently during TTS.
Below three callbacks are called within a second (This is common pattern )

1. SynthesisStarted.Connect(){ }
2. Synthesizing.Connect() { }
3. SynthesisCanceled.Connect([channel](const SpeechSynthesisEventArgs& e)

{
SpeechSynthesisCancellationDetails::FromResult(e.Result)->ErrorDetails.c_str(),
                e.Result->ResultId.c_str() );
 }

Output logs get printed like below
"TTS request failed: Service unavailable (503). Please try the request again. result_id value : XXXXXX;

On similar line i get  beow errors as well
Internal error: HttpAPI failed - Failed with error: HTTPAPI_READ_DATA_FAILED [0x9]#012POST https://XXXXXv1#012X-ConnectionId: XXXXX 

"Internal service error (502). Error Details:  Bad Gateway Please check request"

May i know what can be wrong from my side.
I am using C++ SDK

**Comment by jpalvarezl** [comment]
Hi, thanks for using the SDK! We need a bit more information in order to be able to help you:
- What SDK version were you using?
- In what environment were you running the SDK?
- Please provide a more detailed description of what you want to accomplish.
- Please provide as much code as you can on how you setup the SDK (be mindful of not leaking secrets.) and how you are using it.
- A log file from a repro of the issue, [Speech SDK logging - Speech service - Azure AI services | Microsoft Learn](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-use-logging)

**Comment by gauravG2021** [comment]
> Hi, thanks for using the SDK! We need a bit more information in order to be able to help you:
> 
> * What SDK version were you using?
  we changed the sdk and now we are on "SpeechSDK-Linux-1.34.1"
> * In what environment were you running the SDK?
" ubuntu 18.04, we use private endpoint url"
> * Please provide a more detailed description of what you want to accomplish.
"Customers call us and we play dynamic information using TTS"
> * Please provide as much code as you can on how you setup the SDK (be mindful of not leaking secrets.) and how you are using it.
"We are using code from sample https://github.com/Azure-Samples/Cognitive-Speech-TTS/blob/master/MRCP/ms-synth/src/ms_synth_engine.cpp"
> * A log file from a repro of the issue, [Speech SDK logging - Speech service - Azure AI services | Microsoft Learn](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-use-logging)
I would love to do it , but the files came out of 14 Gb, We are getting lot of traffic and the issue is interminnent

**Comment by ralph-msft** [comment]
The errors you are describing are all "service" errors:
  - HTTP 503
  - HTTPAPI_READ_DATA_FAILED
  - Internal service error (502). Error Details: Bad Gateway Please check request"

In your case this appears to be an issue with your private endpoint.

**Comment by gauravG2021** [comment]
> The errors you are describing are all "service" errors:
> 
> * HTTP 503
> * HTTPAPI_READ_DATA_FAILED
> * Internal service error (502). Error Details: Bad Gateway Please check request"
> 
> In your case this appears to be an issue with your private endpoint.

Hi Ralph, Thanks for your prompt reply

 one more query, i see below logs in my server 
_Jan 25 12:36:32 [MS TTS] synthesis started. Request ID: : 74537653925c4eed81af908382d004d8
Jan 25 12:36:32  MS TTS synthesizing (audio data being received). Request ID: 74537653925c4eed81af908382d004d8
Jan 25 12:36:32 [MS TTS] synthesis canceled Service unavailable (503). Please try the request again. Request ID: 74537653925c4eed81af908382d004d8_

Now as per the [Azure sample code](https://github.com/Azure-Samples/Cognitive-Speech-TTS/blob/master/MRCP/ms-synth/src/ms_synth_engine.cpp) these logs are inside the call back functions

1. synthesizer->SynthesisStarted.Connect([](const SpeechSynthesisEventArgs& e)
2. synthesizer->Synthesizing.Connect([](const SpeechSynthesisEventArgs& e)
3. synthesizer->SynthesisCanceled.Connect([](const SpeechSynthesisEventArgs& e)

there is a mention of `e.Result->ResultId.c_str() ` in the code so the query is 

1. Who sets this result id TTS service or cpp sdk,
2.  Why it is printed as ResultId in the logs.
3. Will it help if i provide these ResultId to MS support team

**Comment by ralph-msft** [comment]
The `Request ID` you see in the logs is what you'll need to provide to be able to correlate the SDK logs with the service logs. In your case this would be `74537653925c4eed81af908382d004d8`. The `Result ID` is used to identify individual results within a connection and can help to narrow down issues one of particular e.g. TTS output.

**Comment by chschrae** [comment]
@gauravG2021 Are you still having this issue? Were you able to resolve it by investigating the private endpoint?

**Comment by gauravG2021** [comment]
No it has not been fixed yet.
 i have asked people managing private endpoint to help me out.

**Comment by gauravG2021** [comment]
Today i did not faced 502 or 503 

but below error has occured around 50 times
 _ErrorCode value : 9 ErrorDetails : [Internal error: HttpAPI failed - Failed with error: HTTPAPI_READ_DATA_FAILED [0x9]#012POST https://XXXX.azure.com/tts/cognitiveservices/v1#012X-ConnectionId: XXXXX] result_id value : XXXX_

**Comment by gauravG2021** [comment]
@ralph-msft  ErrorCode value : 9 ErrorDetails : [Internal error: HttpAPI failed - Failed with error: HTTPAPI_READ_DATA_FAILED [0x9]#012POST https://XXXX.azure.com/tts/cognitiveservices/v1#012X-ConnectionId: XXXXX] result_id value : XXXX.  is server side or client side problem

**Comment by yulin-li** [comment]
Hi, for the `HTTPAPI_READ_DATA_FAILED` error, could you share the SDK log?

And you can try to use the websocket, change your endpoint from https://XXXX.azure.com/tts/cognitiveservices/v1 to wss://XXXX.azure.com/tts/cognitiveservices/websocket/v1

**Comment by pankopon** [comment]
Closed since no customer update for the requested information, please open a new issue if more support is needed.
