### ISSUE TITLE
How to set properties previously set via UriQueryParameter ?

### ISSUE THREAD

**Issue by kokovoj** [Azure-Samples/cognitive-services-speech-sdk#2224]
We are using Java SDK and trying to upgrade from 1.31.0 -> 1.34.0. 

1. In 1.31.0, we are setting property `setfeature` to value `multichannel2` with below code to handle stereo streams
`
speechConfig.setServiceProperty("setfeature", "multichannel2", ServicePropertyChannel.UriQueryParameter);
`
which passes the value as uri query parameter in the endpoint
`
wss://eastus.stt.speech.microsoft.com/speech/recognition/dictation/cognitiveservices/v1?...setfeature=multichannel2...
`
this gives us 2 channels transcribed separately as expected:
- hi thanks for contacting the store how can i help you (role = INTERNAL)
- hi good morning i have couple of questions regarding my recent order (role = EXTERNAL)
2. After upgrading to 1.34.0, we are not getting transcription separated into two channels as before, instead transcription is just for one channel
- hi thanks for contacting the store how can i help you hi good morning i have couple of questions regarding my recent order (role = INTERNAL)

[The release notes for 1.34.0](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/releasenotes?tabs=speech-sdk ](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/releasenotes?tabs=speech-sdk#speech-sdk-1340-november-2023-release) say 
> Breaking changes: 
SpeechRecognizer has been updated to use a new endpoint by default (i.e. when not explicitly specifying a URL) which no longer supports query string parameters for most of the properties. Instead of setting query string parameters directly with ServicePropertyChannel.UriQueryParameter, please use the corresponding API functions.

Which corresponding API functions this is referring to and how to accomplish using multichannel2 with sdk 1.34.0 ?

**Comment by jpalvarezl** [comment]
Hi @kokovoj , thank you for using the SDK. I will get back to you with more details on this. I have forwarded your question to people more directly involved in this part of the project.

**Comment by glharper** [comment]
@M-Hietala What do you recommend here?

**Comment by pankopon** [comment]
Possibly the same question as 2402080040009007 on Speech Services support channel.

**Comment by kokovoj** [comment]
@pankopon, that sounds like an internal channel that I don't have access to. If/when there is a solution there, could you please let me know.

**Comment by pankopon** [comment]
Closing this item as processing continues on another support channel.
