### ISSUE TITLE
`KeywordRecognizer.RecognizeOnceAsync` blocks until a keyword is recognised

### ISSUE THREAD

**Issue by bpasero** [Azure-Samples/cognitive-services-speech-sdk#2229]
This is an issue for the C++ SDK (latest version):

I am about to add `KeywordRecognizer::FromConfig(audioConfig);` to our VS Code speech extension. I see a method `RecognizeOnceAsync` to start it and it works fine. But I struggle to call `StopRecognitionAsync` unless the previous call has returned.
 
Is this a known issue or am I doing something wrong. It looks like `RecognizeOnceAsync` really suspends the current Thread until the keyword is recognised, so it seems to me one cannot stop the recognition out of band?

This seems like a bug in the SDK to me because the method also returns a `Future`.

The workaround that I am using now is:

```c++
std::thread([&recognizer, &keywordRecognitionConfig]()
  { recognizer->RecognizeOnceAsync(keywordRecognitionConfig); })
.detach();
```

**Comment by ralph-msft** [comment]
Unfortunately, I cannot reproduce the issue you are seeing. If you capture the returned future (__without__ calling `.get()` it will not be a blocking call. For example the following code demonstrates the non-blocking nature of this by adding a 5 second timeout:

```c++
#include <iostream>
#include <chrono>

#include <speechapi_cxx_embedded_speech_config.h>
#include <speechapi_cxx_speech_recognition_eventargs.h>
#include <speechapi_cxx_keyword_recognizer.h>

using namespace std::chrono_literals;
using namespace Microsoft::CognitiveServices::Speech;
using namespace Microsoft::CognitiveServices::Speech::Audio;


static long long TimeSinceStartMs()
{
    static auto start = std::chrono::steady_clock::now();
    return std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now() - start).count();
}

int main()
{
    auto model = KeywordRecognitionModel::FromFile(PATH_TO_MODEL);
    auto recognizer = KeywordRecognizer::FromConfig(AudioConfig::FromDefaultMicrophoneInput());

    std::cout << "[" << TimeSinceStartMs() << "] About to call recognize once async" << std::endl;
    auto fut = recognizer->RecognizeOnceAsync(model);
    std::cout << "[" << TimeSinceStartMs() << "] Called recognize once async. Will now block on the future" << std::endl;
    
    std::future_status status = fut.wait_for(5s);
    switch (status)
    {
    default:
    case std::future_status::deferred:
        // should never happen
        std::cout << "[" << TimeSinceStartMs() << "] Something went horribly wrong" << std::endl;
        recognizer->StopRecognitionAsync().get();
        return 1;

    case std::future_status::timeout:
        std::cout << "[" << TimeSinceStartMs() << "] Timed out waiting for recognize once" << std::endl;
        recognizer->StopRecognitionAsync().get();
        return 2;

    case std::future_status::ready:
        // continue
        break;
    }

    auto result = fut.get();
    if (result->Reason == ResultReason::Canceled)
    {
        auto details = CancellationDetails::FromResult(result);
        std::cout << "[" << TimeSinceStartMs() << "] "
            << "CANCELED - Reason:" << (int)details->Reason
            << ", Code:" << (int)details->ErrorCode
            << ", Details: " << details->ErrorDetails;
    }
    else if (result->Reason == ResultReason::RecognizedKeyword)
    {
        std::cout << "[" << TimeSinceStartMs() << "] "
            << "SUCCESS - " << result->Text;
    }
    else
    {
        std::cout << "[" << TimeSinceStartMs() << "] "
            << "UNEXPECTED RESULT - " << (int)result->Reason
            << " - " << result->Text;
    }

    std::cout << std::endl;
    return 0;
}
```

With this code, you can see it that it writes to the console almost immediately (less than 1 ms) after the call to `RecognizeOnceAsync`, as well as successfully timeout, or return the keyword (which is computer):
```
E:\x64\Release>speech_sdk.exe
[0] About to call recognize once async
[0] Called recognize once async. Will now block on the future
[5014] Timed out waiting for recognize once

E:\x64\Release>speech_sdk.exe
[0] About to call recognize once async
[0] Called recognize once async. Will now block on the future
[1715] SUCCESS - Computer
```
I have tested this on version 1.34.1, and 1.33.0 of the Cognitive Services Speech SDK. If you continue to have issues, please update this issue with the following information:
  * The version of the Cognitive Service Speech SDK you are using
  * The minimum complete code you are running that reproduces this issue
  * The SDK log from a run that reproduces your issue. You can find instructions on how to capture the logs here: https://learn.microsoft.com/azure/ai-services/speech-service/how-to-use-logging

**Comment by bpasero** [comment]
@ralph-msft thanks for getting back to me. I have now updated the SDK to latest and it still reproduces. My project is using C++ SDK but in the context of node.js. Essentially I am building a node.js native module to be able to use some of the SDK features in VS Code.

As for the code we are using, the thread execution hangs here:

https://github.com/microsoft/node-speech/blob/59cfb382fbad45c9adbb7598e3c68402963d9f6f/src/main.cc#L444-L446

When I run the project (steps later below), I can see that the first message is printed but not the second. Even though I am not awaiting the future.

**Steps to reproduce:**
* install node.js 18.x if not yet done
* `git clone https://github.com/microsoft/node-speech.git`
* `git co ben/rude-llama`
* `npm i`
* `node index.js`

You should see this printed: `Starting keyword recognition` but not `Waiting for keyword recognition to end`

**Comment by ralph-msft** [comment]
Since you are not capturing the returned future, it is being destroyed immediately after the call to `RecognizeOnceAsync` returns. The destructor of the future will block until the future completes.

As shown in the code above, you can work around this by capturing the future to a local variable:

```c++
auto fut = recognizer->RecognizeOnceAsync(keywordRecognitionConfig);
```

And it will now work as expected:
```
e:\temp\node-speech>node index.js
Starting keyword recognition
Waiting for keyword recognition to end
```

**Comment by bpasero** [comment]
@ralph-msft thanks so much for helping me out, I clearly am not so experienced in writing C++ than I am writing TypeScript. You are absolutely right.

Fun related SO thread: https://stackoverflow.com/questions/23455104/why-is-the-destructor-of-a-future-returned-from-stdasync-blocking
