### ISSUE TITLE
Speech Services Delay and Uptime

### ISSUE THREAD

**Issue by joshthor3222** [Azure-Samples/cognitive-services-speech-sdk#223]
The SDK seems very inconstant at delivering the text conversion of the users speech. I have been working with this SDK every day for the last couple months and there are inconsistencies in when it connects. Sometimes I can spend 20 minutes going back and forth with it catching almost everything, other times i will spend the same amount of time and every other message doesnt recognize at all. 

The problem of course with this bug is how do i prove it? I am using a basic webapplication (like the $55 a month tier) as the server and the paid version of the cognitive services api, but it is just incredibly inconsistent so i cannot replicated it on command

**Comment by rhurey** [comment]
If you have the session ID's from when recognition isn't preforming well we can look into the service logs and any telemetry the client sent to try and spot what's going wrong.

**Comment by wolfma61** [comment]
@joshthor3222  - any more information?
 we need some way to pinpoint the incidents, for this we would need the sessionid and the region. With this information we can take a look at service logs to see what was going on at the service ....

**Comment by joshthor3222** [comment]
unfortunately no - as I mentioned it is very inconsistent and we weren't logging the session ids. As of a few months ago the development of this project was put on hold, however it sounds like we might start back up on it in the next few months. If so, Ill make sure we are logging the session ids to debug this issue if possible.

**Comment by wolfma61** [comment]
closing this for now, if you have more information, perhaps just open a new issue
thx
