### ISSUE TITLE
Calling `SpeechRecognizer.StopContinuousRecognitionAsync` takes `10s`

### ISSUE THREAD

**Issue by bpasero** [Azure-Samples/cognitive-services-speech-sdk#2231]
Info: I am using `EmbeddedSpeechConfig` with a local model!

Using the Speech SDK `1.32.1` in C++, I am creating a `SpeechRecognizer` with an embedded model and call `StartContinuousRecognitionAsync` to start it. Later when done, I call `StopContinuousRecognitionAsync`. It seems to take more than `10s` until I get an associated `SessionStopped` event. 

The reason I report this is that this makes me uncomfortable to share a single `SpeechRecognizer` for multiple uses because its not clear to me that I can call `StartContinuousRecognitionAsync` again after having called `StopContinuousRecognitionAsync`

**Comment by pankopon** [comment]
1. Please always use the current latest Speech SDK release (1.34.1 as of this writing).
2. You can call StartContinuousRecognitionAsync again after StopContinuousRecognitionAsync but you must wait for it to complete first. You can start and stop recognition using the same SpeechRecognizer instance multiple times.
3. Without any logs: If the input audio has been coming faster than the embedded recognizer can process, it means that at the time of `StopContinuousRecognitionAsync` there is unprocessed buffered audio. This will be processed to the end before the session is stopped. If you suspect some other reason and steps 1 and 2 make no difference, please attach a [Speech SDK log](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-use-logging).

**Comment by pankopon** [comment]
This is not related. From the log:
```
[66325]: 5006ms SPX_DBG_TRACE_VERBOSE:  rnnt_reco_engine_adapter.cpp:237 ProcessAudio: (0x0x123787ad0) End of audio ... size=0 (processed 39600/64759)
[66325]: 5006ms SPX_DBG_TRACE_VERBOSE:  rnnt_client.cpp:499 ProcessLeftovers: 1
[638413]: 5006ms SPX_DBG_TRACE_SCOPE_ENTER:  audio_stream_session.cpp:808 WaitForIdle
[638413]: 5006ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:809 [0x1238d7200]CSpxAudioStreamSession::WaitForIdle timeout: 16000 msec
```
At the time of the request to stop recognition, there is still 25159 samples ~ 1.57 seconds of unprocessed audio. With embedded speech, the WaitForIdle timeout is set 10x of that, rounded up.

After the remaining audio has been processed, a SessionStopped event is meant to be sent but there's an exception "The state of the promise has already been set" which means somewhere the value of the same `std::promise` is set twice:
```
[58403]: 5285ms SPX_DBG_TRACE_SCOPE_ENTER:  audio_stream_session.cpp:1724 DispatchEvent task started...
[58403]: 5285ms SPX_DBG_TRACE_VERBOSE:  resource_manager.cpp:133 Created 'CSpxSessionEventArgs' as '418547108'
[58403]: 5285ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:111 CSpxHandleTable::TrackHandle p=0x0x1176f9030
[58403]: 5285ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:121 CSpxHandleTable::TrackHandle class=ISpxSessionEventArgs, h=0x0x1176f9030, p=0x0x1176f9030, tot=1
[58403]: 5285ms SPX_TRACE_ERROR:  audio_stream_session.cpp:1686 Exception: The state of the promise has already been set.
```
Because SessionStopped does not complete, the session remains pending until the timeout:
```
[638413]: 21011ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:814 CSpxAudioStreamSession::WaitForIdle m_cv.wait_for, m_sessionState: 0, m_recoKind: 0, m_sessionStarted: 1, m_sessionStopped: 0
[638413]: 21011ms SPX_TRACE_WARNING: audio_stream_session.cpp:827 [0x1238d7200]CSpxAudioStreamSession::WaitForIdle: Timeout happened during waiting for Idle
```
Please provide some more information:
- Does the issue occur consistently in the same use case?
- Does it happen in other environments than OSX-arm64?
- When it happens, is your SessionStopped event handler not called until the timeout?
- Can you post the code of your recognizer event handlers (all of them)?

**Comment by hcldadi** [comment]
same problem in centOS7 with 1.34.1.
[msspeech.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/14031853/msspeech.log)
found some infos:
```log
SetShouldWaitForPendingData: 1
CSpxAudioStreamSession::WaitForIdle timeout: 10000 msec
CSpxAudioStreamSession::WaitForIdle: Timeout happened during waiting for Idle
```
Does it have certain config to modify WaitForIdle timeout ?

**Comment by bpasero** [comment]
@pankopon thanks for the analysis, it is not clear to me if this is something I am doing wrong from my code? I can explain what I am doing: I am building a native node.js module to be able to use the Speech SDK embedded in C++. The project is at:  https://github.com/microsoft/node-speech/tree/main

The code that deals with speech recognition starts from here: https://github.com/microsoft/node-speech/blob/70344bdfdeb3e9938dc3c81ec19367d3a5c8d4ef/src/main.cc#L95

> Does the issue occur consistently in the same use case?

Yes, I have a consistent repro.

> Does it happen in other environments than OSX-arm64?

Yes, I am quite certain I have seen this on macOS Intel too.

> When it happens, is your SessionStopped event handler not called until the timeout?

Good point! It is actually called immediately and not after the timeout.

> Can you post the code of your recognizer event handlers (all of them)?

Yes I can send you a repro, but note that my project is a native node.js module that makes some Speech SDK API available to VS Code. To get it running:

**Steps to reproduce:**
* install node.js 18.x if not yet done
* `git clone https://github.com/microsoft/node-speech.git`
* `git co ben/fashionable-aardvark`
* set a proper model path, name and key [here](https://github.com/microsoft/node-speech/blob/83b00c09da67fc1049c95fc48e384c78c6e99a34/index.ts#L126-L128)
* `npm i`
* `node index.js`

The transcription is stopped after `5s`, but the process only terminates a lot later.

**Comment by pankopon** [comment]
@hcldadi This issue is not related. You are using cloud services with a fixed timeout, this is about embedded speech that works differently. Please create a separate issue if the problem persists.

@bpasero When a SessionStopped (or any) event is fired, the SDK library calls your event handler and runs code there. As you said, "It is actually called immediately and not after the timeout." So it is possible that the exception is triggered by this code. Please surround your SessionStopped event handler body with try-catch and re-test.

**Comment by bpasero** [comment]
@pankopon the issue reproduces even when I catch exceptions (there is no exception).

Btw one interesting data point is that it even reproduces when I have refused access to the microphone from this dialog:

![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/900690/e2852e67-a1eb-4d71-aadb-052a539bd4e7)

So I somewhat doubt it is related to audio data still being in the buffer because in this case there cannot be any audio data recorded.

**Comment by bpasero** [comment]
I am sorry for the red herring, it is indeed a bug in my code. There seems to be an exception when I set the value of a future that already is resolved. This happens because I call `StopTranscriptionWorker` from the stopped event.

**Comment by gerrosc** [comment]
Hi, I'm current facing the same issue on this.  Were there a solution made for this?

Please help!
