### ISSUE TITLE
Allow faster speech-to-text responsiveness on cold startup

### ISSUE THREAD

**Issue by bpasero** [Azure-Samples/cognitive-services-speech-sdk#2232]
I am using `EmbeddedSpeechConfig` with a local model and notice that the time it takes until recording starts is noticeable, esp. slow on first startups.

Would it be possible to change `SpeechRecognizer` to allow to start reading from the microphone while the embedded model is initialising? 

I think recording from the microphone can start relatively soon, and then later be transcribed when the embedded model is loaded?

**Comment by pankopon** [comment]
This was just discussed with @hasyashah. The SDK cannot start reading microphone audio before SpeechRecognizer is initialized. And initialization of SpeechRecognizer in case of embedded speech means the embedded speech engine must be initialized and the model loaded.

As a "workaround" you can (and should) create the SpeechRecognizer well before you call RecognizeOnceAsync or StartContinuousRecognitionAsync. Create the recognizer as soon as you know the configuration (model etc.) needed for recognition.

**Comment by bpasero** [comment]
@pankopon your suggestion is what I had thought about as well, however we are using the embedded model and I can measure a `500MB` increase in memory use as soon as I create `SpeechRecognizer` with the model we have locally. So, eagerly creating this amount of memory without knowing if the user actually uses speech recognition was not something I was willing to do.
