### ISSUE TITLE
`PhraseListGrammar` is not entirely clear to me

### ISSUE THREAD

**Issue by bpasero** [Azure-Samples/cognitive-services-speech-sdk#2233]
I see how I can configure the speech recognizer with phrases, for example:

```
auto phraseList = PhraseListGrammar::FromRecognizer(recognizer);
phraseList->AddPhrase("VS Code");
phraseList->AddPhrase("Visual Studio Code");
phraseList->AddPhrase("GitHub");
```

But what is the impact of doing so and the scope? For example, I was wondering if I can give it some programming terms, such as variable names to help it recognize these better. For example set a phrase `editorViewState` and when I say it, this variable name would be recognised?

From my local testing that however does not seem to be the case, so some clarification would be helpful.

**Comment by ralph-msft** [comment]
You can find more information about phrase lists here:
https://learn.microsoft.com/azure/ai-services/speech-service/improve-accuracy-phrase-list

Unfortunately, there is currently a known issue with phrase lists not working properly which is being tracked by this GitHub issue:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2119

For the best recognition quality though, where feasible creating a custom language model is the way to go. You can find more details about this here:
https://learn.microsoft.com/azure/ai-services/speech-service/custom-speech-overview

**Comment by ralph-msft** [comment]
I am not currently aware of any such plans. Generally speaking any feature deprecation in Cognitive Services either in the SDK or service will be announced well in advance of the feature removal.

**Comment by bpasero** [comment]
@ralph-msft I should have mentioned that we are using Speech SDK with an embedded, local model, without using any Azure service. Does that make a difference for whether the API would work or not?
