### ISSUE TITLE
C#: ConversationTranscriber: SpeechServiceResponse_StablePartialResultThreshold 

### ISSUE THREAD

**Issue by Nico-VanHaaster** [Azure-Samples/cognitive-services-speech-sdk#2235]
Hello all,

I have been trying to find some documentation regarding the property `SpeechServiceResponse_StablePartialResultThreshold ` when using the `ConversationTranscriber`. It seems that when using the `ConversationTranscriber` this property makes no difference. Also when I check the logs between using the `SpeechRecognizer` and the `ConversationTranscriber` the logs indicate that the this property is set in the `SpeechRecognizer` but not the `ConversationTranscriber`.

Can I confirm that this is the expected result, and if so is there a property on the  `ConversationTranscriber` transcriber speechConfig that we can enable?

Thanks in advance.

**Comment by ralph-msft** [comment]
Thanks for using the Cognitive Services Speech SDK. In order to assist you further could you please include the following:
  - The SDK logs you mentioned
  - The sample code where you set the property for the SpeechRecognizer, as well as for the ConversationTranscriber

**Comment by Nico-VanHaaster** [comment]
Hello, sorry for the delay. Here is a sample of the C# code used for the SpeechRecognizer and the ConversationTranscriber. Note this is very basic code just to highlight the issues.

ConversationTranscriber:
```
var stream = new PushAudioInputStream(AudioStreamFormat.GetDefaultInputFormat());
var audioConfig = AudioConfig.FromStreamInput(stream);

var speechConfig = SpeechConfig.FromSubscription(_speechOptions.SubscriptionKey, _speechOptions.Region);
speechConfig.SetProperty(PropertyId.SpeechServiceResponse_StablePartialResultThreshold, "10");

speechConfig.SpeechRecognitionLanguage = _speechOptions.Language;
speechConfig.EnableDictation();

speechConfig.SetProperty(PropertyId.Speech_LogFilename, $"{_hostingOptions.LogsPath}/speech_sdk.log");
speechConfig.OutputFormat = OutputFormat.Detailed;

var speechRecognizer = new SpeechRecognizer(speechConfig, audioConfig);
await speechRecognizer.StartContinuousRecognitionAsync();
```

**ConversationTranscriber**:
```
var stream = new PushAudioInputStream(AudioStreamFormat.GetDefaultInputFormat());

var audioConfig = AudioConfig.FromStreamInput(stream);

var speechConfig = SpeechConfig.FromSubscription(_speechOptions.SubscriptionKey, _speechOptions.Region);
speechConfig.SetProperty(PropertyId.SpeechServiceResponse_StablePartialResultThreshold, "10");

speechConfig.SpeechRecognitionLanguage = _speechOptions.Language;
speechConfig.EnableDictation();

speechConfig.SetProperty(PropertyId.Speech_LogFilename, $"{_hostingOptions.LogsPath}/speech_sdk.log");
speechConfig.OutputFormat = OutputFormat.Detailed;
var conversationTranscriber = new ConversationTranscriber(speechConfig, audioConfig);
await conversationTranscriber.StartTranscribingAsync();
```

The logs are below for both types.

[conversation_transcriber.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/14089454/conversation_transcriber.log)
[speech_recognizer.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/14089456/speech_recognizer.log)

**Comment by M-Hietala** [comment]
Could you please provide SDK traces taken with the 1.34.1 version of SDK.
