### ISSUE TITLE
`SpeechRecognizer.SessionStarted` fires even when macOS permission dialog was not approved (yet)

### ISSUE THREAD

**Issue by bpasero** [Azure-Samples/cognitive-services-speech-sdk#2238]
Using the Speech SDK for C++ on macOS, I see the `SessionStarted` event fire, even before this dialog is acknowledged:

<img width="372" alt="image" src="https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/900690/da309e29-4620-474b-b3c0-8571895f42ce">

Even more interesting, if I say "Do not allow", I get the following transcription result:

"Play"
"Start"
"Play Music"

I think this leaves users of the SDK with no way of figuring out how the dialog was used by the user.

The code for speech recognition was taken from your sample and is here:

https://github.com/microsoft/node-speech/blob/70344bdfdeb3e9938dc3c81ec19367d3a5c8d4ef/src/main.cc#L95

**Comment by jhakulin** [comment]
Thanks for your report, do you have application-level check for microphone permission before the app starts the recognition?
It might be that if you create audio config from default microphone and start recognition, the OSX audio driver makes the pop-up appear in UI but the system does not really wait for the confirmation from that (could be bug in SDK design). 
As a workaround, in app level there should be way to add mic permission check using AVFoundation APIs and based on that start the recognition. Would that sound feasible as workaround?

**Comment by bpasero** [comment]
Well I am really only using the Speech SDK through a native node.js module: https://github.com/microsoft/node-speech. We do not have any other code to detect if permissions are granted for the application, though maybe that could be done via some other APIs.

Would the SDK be able to provide this kind of functionality?

**Comment by ralph-msft** [comment]
Requesting OS specific permissions for e.g. microphones is best deferred to the applications so they can make appropriate decisions based on their scenarios. Requesting these permissions is outside the scope for the Cognitive Services Speech SDK
