### ISSUE TITLE
STT works differently on-prem 

### ISSUE THREAD

**Issue by legom3s** [Azure-Samples/cognitive-services-speech-sdk#2241]
### **Local container vs normal service**
I was testing speech-to-text on-prem and noticed that the recognition doesn't work on the same way.
Im testing the recognition from a .wav file. 
Im using S0 Standard pricing tier.

### **Dockerfile:**
FROM mcr.microsoft.com/azure-cognitive-services/speechservices/speech-to-text:4.5.0-amd64-pt-pt

ENV Eula accept
ENV Billing https://*********/
ENV ApiKey *********

EXPOSE 5000

### **Config:**
config = SpeechConfig::FromHost(stt_local_ip.c_str()); OR config = SpeechConfig::FromSubscription(subscriptionKey, region);
config->SetSpeechRecognitionLanguage(language);
config->SetProperty(PropertyId::Speech_SegmentationSilenceTimeoutMs, recog_timeout);
config->SetProperty(PropertyId::SpeechServiceConnection_InitialSilenceTimeoutMs, silence_timeout);
config->SetProperty(PropertyId::SpeechServiceConnection_EndSilenceTimeoutMs, silence_timeout);

### **Result on local container:**
Recognizing: boa tarde 
Recognizing: boa tarde sou 
Recognizing: boa tarde sou capaz de 
Recognizing: boa tarde sou capaz de ler qualquer 
Recognizing: boa tarde sou capaz de ler qualquer texto 
........
Recognizing: boa tarde sou capaz de ler qualquer texto que você digitar aqui por exemplo aqui está uma citação da série game of thrones porque quando um homem constrói uma parede o próximo fiquei imediatamente curioso para saber o que há do outro lado
**Recognized:** Boa tarde, sou capaz de ler qualquer texto que você digitar aqui, por exemplo, aqui está uma citação da série Game of Thrones, porque quando um homem constrói uma Parede ou próximo, fica imediatamente curioso para saber o que há do outro lado.
Recognizing: e até mesmo esta 
..........
**Recognized:** E até mesmo esta situação. Eu Não vou parar a roda.
Recognizing: vou quebrar 
Recognizing: vou quebrar a roda 
**Recognized:** Vou quebrar a roda.

### **Result on normal service:**
Recognizing: boa tarde 
Recognizing: boa tarde sou capaz de 
Recognizing: boa tarde sou capaz de ler qualquer 
Recognizing: boa tarde sou capaz de ler qualquer texto que 
Recognizing: boa tarde sou capaz de ler qualquer texto que você 
Recognizing: boa tarde sou capaz de ler qualquer texto que você digitar aqui 
Recognizing: boa tarde sou capaz de ler qualquer texto que você digitar aqui por 
Recognizing: boa tarde sou capaz de ler qualquer texto que você digitar aqui por exemplo 
...............
Recognizing: boa tarde sou capaz de ler qualquer texto que você digitar aqui por exemplo aqui está uma citação da série game of thrones porque quando um homem constrói uma parede o próximo fiquei imediatamente curioso para saber o que há do outro lado
Recognizing: boa tarde sou capaz de ler qualquer texto que você digitar aqui por exemplo aqui está uma citação da série game of thrones porque quando um homem constrói uma parede o próximo fiquei imediatamente curioso para saber o que há do outro lado e até mesmo
Recognizing: boa tarde sou capaz de ler qualquer texto que você digitar aqui por exemplo aqui está uma citação da série game of thrones porque quando um homem constrói uma parede o próximo fiquei imediatamente curioso para saber o que há do outro lado e até mesmo esta
..........
Recognizing: boa tarde sou capaz de ler qualquer texto que você digitar aqui por exemplo aqui está uma citação da série game of thrones porque quando um homem constrói uma parede o próximo fiquei imediatamente curioso para saber o que há do outro lado e até mesmo esta citação eu não vou parar a roda
Recognizing: boa tarde sou capaz de ler qualquer texto que você digitar aqui por exemplo aqui está uma citação da série game of thrones porque quando um homem constrói uma parede o próximo fiquei imediatamente curioso para saber o que há do outro lado e até mesmo esta citação eu não vou parar a roda vou quebrar
.............
Recognizing: boa tarde sou capaz de ler qualquer texto que você digitar aqui por exemplo aqui está uma citação da série game of thrones porque quando um homem constrói uma parede o próximo fiquei imediatamente curioso para saber o que há do outro lado e até mesmo esta citação eu não vou parar a roda vou quebrar a roda
**Recognized:** Boa tarde, sou capaz de ler qualquer texto que você digitar aqui, por exemplo, aqui está uma citação da série Game of Thrones, porque quando um homem constrói uma Parede, o próximo fica imediatamente curioso para saber o que há do outro lado e até mesmo esta citação, Eu Não vou parar a roda, vou quebrar a roda.

### **Conclusion**
As you can see the normal service returns the whole file recognition by once and the local container phrase by phrase, the setup is 100% the same I only change the config ::FromHost(stt_local_ip.c_str()) to ::FromSubscription(subscriptionKey, region).
Am I missing something? Is it the pricing tier? Are the config-> done in other way?
Best regards and thank you for your time.
PS: I already tested in :latest and :es-es containers, with the same .wav file in that specific language and the same happens

**Comment by pankopon** [comment]
@legom3s Hi, if configuration remains the same except for the FromHost vs. FromSubscription part then both container and cloud service will receive the same parameters and input, and the difference in output is only generated on their end. Possible reasons include different internal config defaults, recognizer engine version and/or language (base) model version. The service and containers may get updates at different times and you may not always get 1:1 results.

So you've already tried with the latest container version, right? How about the Speech SDK version, are you using the latest? What is the region you use with your subscription?

**Comment by pankopon** [comment]
Regarding language model versions, our PM has stated the following:
> We do aim to provide the same models in the cloud and the containers. Due to different release cycles we do have some delay in the release process however. Container updates are provided on a monthly schedule and usually out around mid-month. Depending on when a new model has been deployed to the cloud the update will then come to containers with 1-2 months delay.

**Comment by pankopon** [comment]
Closing the issue since no further information received; ref. the earlier answers for possible reasons for different outputs. Please open a new issue if more support is needed.
