### ISSUE TITLE
Unable to connect to Avatar using Master branch js/browser/avatar

### ISSUE THREAD

**Issue by kdubious** [Azure-Samples/cognitive-services-speech-sdk#2242]
The error message I get on screen is:
Unable to start avatar: Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="name resolver error: no matching vi websocket error code: 1011

I am using the correct key for an S0 Speech Service. I was able to connect to the CommunicationService and obtain my credentials.

But when I click "Start Session", in about 30 seconds, I receive this error.

**Comment by yulin-li** [comment]
Hi @kdubious, could you try the least SDK to see if this happens or not? We have fixed a similar issue.

**Comment by pankopon** [comment]
Closed since no further customer update, presumed fixed in latest SDK releases.
