### ISSUE TITLE
Where can we find the list of Avatars and their Styles

### ISSUE THREAD

**Issue by kdubious** [Azure-Samples/cognitive-services-speech-sdk#2243]
From the docs:

Avatar Character - The character of the avatar. By default it's lisa, and you can update this value to use a different avatar.
Avatar Style - The style of the avatar. You can update this value to use a different avatar style. This parameter is optional for custom avatar.

However, after some searching, I cannot find a list of Avatars, nor the styles.

**Comment by yinhew** [comment]
@kdubious here it is:
https://learn.microsoft.com/en-us/azure/ai-services/speech-service/text-to-speech-avatar/avatar-gestures-with-ssml#supported-pre-built-avatar-characters-styles-and-gestures

**Comment by andriibulbuk** [comment]
Is there a GET endpoint to retrieve a list of avatars?
I can't find one.

**Comment by dargilco** [comment]
@yinhew can you answer @andriibulbuk 's question?

**Comment by yinhew** [comment]
Hi, @andriibulbuk 

No, we don’t have such endpoint.
You can only get the list from our document which I shared above.

Thanks,
Yinhe
