### ISSUE TITLE
Thread safety of Java speech SDK

### ISSUE THREAD

**Issue by valerauko** [Azure-Samples/cognitive-services-speech-sdk#2245]
Is the Java speech SDK thread safe? I couldn't find any relevant documentation.

Specifically the SpeechConfig and SpeechSynthetizer classes.

**Comment by valerauko** [comment]
No particular issues so far, it's more a planning issue.

I'm going to use the Java speech SDK from a multi-threaded web server environment, and I wasn't sure if it's safe to reuse SpeechSynthetizer instances across threads/requests or should I make a new one for each request.

**Comment by chschrae** [comment]
yes that should be safe as long as you are careful with the callbacks as well. If you are using any.

Feel free to reopen this issue if you have any more questions
