### ISSUE TITLE
SpeechRecognizer Disposal throws Exception

### ISSUE THREAD

**Issue by kellyelton** [Azure-Samples/cognitive-services-speech-sdk#2249]
the SpeechRecognizer is currently designed to throw an InvalidOperationException if you try and dispose it while RecognizeOnceAsync is running.

This is a huge antipattern. Nobody is expecting exceptions to get thrown from Dispose calls. 

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1065

**Comment by dargilco** [comment]
Closing the item as we now have a work item on the backlog and will use that to track this feature request (no ETA). Please open a new issue if support on other topics is needed.
