### ISSUE TITLE
Access to microphone from iOS app (HTML/Cordova)

### ISSUE THREAD

**Issue by Marcophono2** [Azure-Samples/cognitive-services-speech-sdk#225]
Hello!
I successfully coded a HTML/Cordova app for Android to record audio, stream it to the Azure server and get back the translated text. But for iOS it is not working because getUserMedia is not available here. So I grab now the stream from the microphone with a Cordova plugin. That is working so far but now I must connect the Audio object from the plugin with the stream from the Azure JS code to stream it also like in the Android app to the Azure server. But what exactlly is that stream?

```
function startCapture() {
	audioinput.start({
		streamToWebAudio: true
	});
	audioinput.connect(XXX);
// I need the correct object name for the stream where the XXX is
}
```
Every help is really very appreciated!

Best regards
Marc

**Comment by rhurey** [comment]
Looking at the Cordova documentation a bit it looks like that API call wants an object that implements [AudioNode](https://webaudio.github.io/web-audio-api/#audionode) to insert it into the audio chain.

The JavaScript Speech SDK doesn't expose any objects that implement AudioNode as an input.

The best bet loks to be to proxy calls from the AudioNode's EventTarget implementation to a PushAudioInputStream's Write() method.

**Comment by Marcophono2** [comment]
Hi Ryan!
Thanks a lot for your fast reply and taking the time to look into the Cordova docs. And also for your hint. But... OMG!! :)
I have absolute no idea just how to start to realize that implementation. May be that the certain Cordova plugin I found is a bit nearer to a more simple solution. It's this one:
[cordova-plugin-audioinput](https://github.com/edimuj/cordova-plugin-audioinput)
(or do you have checked especially this plugin code? Then you must have used some of my code from my first post to google it...?)
Undepending from the above: Do I have to convert the iOS micro input to 1 channel 16k wav format on the fly before streaming it to the Azure server?

Best regards
Marc

**Comment by rhurey** [comment]
Well, I can only tell you where I'd start. 
Not sure it would work, but seems like a decent place to begin poking around.
Oh, and yes, you'd have to convert the input to mono 16Khz wave before putting into the SDK.

Fortunately, the [JavaScript SDK](https://github.com/Microsoft/cognitive-services-speech-sdk-js) is open source and already has most of the code I think you need in it.  The [PCMRecorder](https://github.com/Microsoft/cognitive-services-speech-sdk-js/blob/master/src/common.browser/PCMRecorder.ts) has the code to receive an AudioProcessingEvent, resample to 16Khz and put it into a wav stream. 

My initial investigation would be to see if that was the same event type that you get from the plugin.

**Comment by janowsiany** [comment]
@Marcophono2 I made a wrapper for cordova around ios sdk, perhaps you may want to try [cordova-plugin-ms-speech-service](https://github.com/janowsiany/cordova-plugin-ms-speech-service) it. Let me know if you have problems.

**Comment by Marcophono2** [comment]
@janowsiany: WHAT?? How great!! I'll check it out later today! :)

**Comment by Marcophono2** [comment]
@janowsiany: 
You write 

"You need to provide Cognitive Services Speech SDK in ./bin/MicrosoftCognitiveServicesSpeech.framework"

I am using Phonegap Build what means that I upload a zip file containing the www folder and the config.xml to the Adobe server to let it convert. Seems this way does not work for me, is it? I am working on a Windows PC that's why I use Phonegap Build for the iOS apps. 
I tried to add the bin//MicrosoftCognitiveServicesSpeech.framework/ folder under the www folder before zipping and uploading the zip file but that was too simple planned I think. It did not work.
To be honest, I also have a Mac Mini. I never used it for coding Cordova but surely that cannot be so difficult. ;)

**Comment by janowsiany** [comment]
I could potentially put the framework into repository but it is 476,9 MB. If so you could then use it like:

_config.xml_:
`<plugin spce="https://github.com/janowsiany/cordova-plugin-ms-speech-service" source="git"/>`

wdyt?

**Comment by Marcophono2** [comment]
Would the app size also count > 476 MB then?

**Comment by chlandsi** [comment]
> Would the app size also count > 476 MB then?

No. The framework contains libraries for  multiple architectures (currently arm64, armv7, armv7s, and simulators for 32 and 64 bit), plus bitcode for the device architectures. Most of this is stripped away on submission to the App Store or on download to devices.

**Comment by Marcophono2** [comment]
If so, then YES! :) :) 👍

**Comment by janowsiany** [comment]
Ok, it turns out that [you can push up to 100 MB into GitHub repo](https://help.github.com/en/articles/conditions-for-large-files#100-mb-push-limit).
So i just made 0.0.1 release:
`<plugin name="cordova-plugin-ms-speech-service" spec="https://github.com/janowsiany/cordova-plugin-ms-speech-service/releases/download/v0.0.1/cordova-plugin-ms-speech-service-0.0.1.tgz" />`

or:
`cordova plugin add cordova-plugin-ms-speech-service@https://github.com/janowsiany/cordova-plugin-ms-speech-service/releases/download/v0.0.1/cordova-plugin-ms-speech-service-0.0.1.tgz`

Let me know if you any troubles, any feedback appreciated!

**Comment by Marcophono2** [comment]
Phonegan Build returns an error. Here is the log:

> Fetching plugin "cordova-plugin-x-socialsharing" via npm
> Installing "cordova-plugin-x-socialsharing" at "5.4.4" for ios
> Fetching plugin "es6-promise-plugin@^4.1.0" via npm
> Installing "es6-promise-plugin" at "4.2.2" for ios
> Fetching plugin "cordova-plugin-file@^6.0.1" via npm
> Installing "cordova-plugin-file" at "6.0.1" for ios
> 3242ab8b669a232fecda6afe5086d2ba07d8c22a
> Fetching plugin "https://github.com/edimuj/cordova-plugin-audioinput.git" via git clone
> Using shallow clone
> Repository "https://github.com/edimuj/cordova-plugin-audioinput.git" checked out to git ref "master" at "3242ab8".
> Installing "cordova-plugin-audioinput" at "1.0.1" for ios
> Fetching plugin "cordova-plugin-compat@^1.2.0" via npm
> Installing "cordova-plugin-compat" at "1.2.0" for ios
> 
> "plugman-151 install --platform ios --project /project --plugin https://github.com/janowsiany/cordova-plugin-ms-speech-service/releases/download/v0.0.1/cordova-plugin-ms-speech-service-0.0.1.tgz --nohooks=.": Fetching plugin "https://github.com/janowsiany/cordova-plugin-ms-speech-service/releases/download/v0.0.1/cordova-plugin-ms-speech-service-0.0.1.tgz" via git clone
> Cloning full repository
> Failed to fetch plugin https://github.com/janowsiany/cordova-plugin-ms-speech-service/releases/download/v0.0.1/cordova-plugin-ms-speech-service-0.0.1.tgz via git.
> Either there is a connection problems, or plugin spec is incorrect:
> 	Error: git: Command failed with exit code 128 Error output:
> Cloning into '/tmp/git/1558102349671'...
> remote: Not Found
> fatal: repository 'https://github.com/janowsiany/cordova-plugin-ms-speech-service/releases/download/v0.0.1/cordova-plugin-ms-speech-service-0.0.1.tgz/' not found

**Comment by janowsiany** [comment]
spec => **value**?
```xml
<plugin name="cordova-plugin-ms-speech-service" value="https://github.com/janowsiany/cordova-plugin-ms-speech-service/releases/download/v0.0.1/cordova-plugin-ms-speech-service-0.0.1.tgz" />
```

**Comment by Marcophono2** [comment]
Unfortunatelly the same/similar message:

> Fetching plugin "cordova-plugin-x-socialsharing" via npm
> Installing "cordova-plugin-x-socialsharing" at "5.4.4" for ios
> Fetching plugin "es6-promise-plugin@^4.1.0" via npm
> Installing "es6-promise-plugin" at "4.2.2" for ios
> Fetching plugin "cordova-plugin-file@^6.0.1" via npm
> Installing "cordova-plugin-file" at "6.0.1" for ios
> 3242ab8b669a232fecda6afe5086d2ba07d8c22a
> Fetching plugin "https://github.com/edimuj/cordova-plugin-audioinput.git" via git clone
> Using shallow clone
> Repository "https://github.com/edimuj/cordova-plugin-audioinput.git" checked out to git ref "master" at "3242ab8".
> Installing "cordova-plugin-audioinput" at "1.0.1" for ios
> Fetching plugin "cordova-plugin-compat@^1.2.0" via npm
> Installing "cordova-plugin-compat" at "1.2.0" for ios
> "plugman-151 install --platform ios --project /project --plugin cordova-plugin-ms-speech-service --nohooks=.": Fetching plugin "cordova-plugin-ms-speech-service" via npm
> Failed to fetch plugin cordova-plugin-ms-speech-service via registry.
> Probably this is either a connection problem, or plugin spec is incorrect.
> Check your connection and plugin name/version/URL.
> Error: Unpublished by janowsiany on 2019-05-17T13:25:31.201Z

The last line is funny. ;)

**Comment by janowsiany** [comment]
Indeed i tried to publish it to npm but there is also a problem with large binaries.

Try without **name**:
```xml
<plugin spec="https://github.com/janowsiany/cordova-plugin-ms-speech-service/releases/download/v0.0.1/cordova-plugin-ms-speech-service-0.0.1.tgz" source="git" >
  <param name="SPEECH_KEY" value="foo" />
  <param name="SERVICE_REGION" value="westus" />
</plugin>
```

Also if it may help i can send you sample project which i just created, i successfully added the plugin with:
```
cordova plugin add cordova-plugin-ms-speech-service@https://github.com/janowsiany/cordova-plugin-ms-speech-service/releases/download/v0.0.1/cordova-plugin-ms-speech-service-0.0.1.tgz --variable SPEECH_KEY=foo --variable SERVICE_REGION=westus
```

**Comment by Marcophono2** [comment]
> Fetching plugin "cordova-plugin-x-socialsharing" via npm
> Installing "cordova-plugin-x-socialsharing" at "5.4.4" for ios
> Fetching plugin "es6-promise-plugin@^4.1.0" via npm
> Installing "es6-promise-plugin" at "4.2.2" for ios
> Fetching plugin "cordova-plugin-file@^6.0.1" via npm
> Installing "cordova-plugin-file" at "6.0.1" for ios
> 3242ab8b669a232fecda6afe5086d2ba07d8c22a
> Fetching plugin "https://github.com/edimuj/cordova-plugin-audioinput.git" via git clone
> Using shallow clone
> Repository "https://github.com/edimuj/cordova-plugin-audioinput.git" checked out to git ref "master" at "3242ab8".
> Installing "cordova-plugin-audioinput" at "1.0.1" for ios
> Fetching plugin "cordova-plugin-compat@^1.2.0" via npm
> Installing "cordova-plugin-compat" at "1.2.0" for ios
> 
> "plugman-151 install --platform ios --project /project --plugin https://github.com/janowsiany/cordova-plugin-ms-speech-service/releases/download/v0.0.1/cordova-plugin-ms-speech-service-0.0.1.tgz --nohooks=. --var SPEECH_KEY=64e6df36b0ec438aaXXXXXXXXXX --var SERVICE_REGION=westeurope": Fetching plugin "https://github.com/janowsiany/cordova-plugin-ms-speech-service/releases/download/v0.0.1/cordova-plugin-ms-speech-service-0.0.1.tgz" via git clone
> Cloning full repository
> Failed to fetch plugin https://github.com/janowsiany/cordova-plugin-ms-speech-service/releases/download/v0.0.1/cordova-plugin-ms-speech-service-0.0.1.tgz via git.
> Either there is a connection problems, or plugin spec is incorrect:
> 	Error: git: Command failed with exit code 128 Error output:
> Cloning into '/tmp/git/1558110240758'...
> remote: Not Found
> fatal: repository 'https://github.com/janowsiany/cordova-plugin-ms-speech-service/releases/download/v0.0.1/cordova-plugin-ms-speech-service-0.0.1.tgz/' not found

I think I'll install Phonegap on my Mac. The coding then must be done per remote access to Phonegap Build because my Mac is too old to install the latest xCode so I think the Apple Review would not let pass the app when it was coded with the old xCode on my Mac.

**Comment by Marcophono2** [comment]
I think that will also not work what I imagined. Using Phonegap Build from my Mac would let occure the same problem: Bringing Phonegap Build using yout Plugin. The only difference would be that I do the pre-work on my local Mac. But that isn't the point. :) Anyway, as long as I do not buy a new Mac I need another Mac. So I asked a friend to compile the app including your framework. He is working at it right now. Of cause I'll keep you updated!

**Comment by Marcophono2** [comment]
Okay, my friend successfully built the iOS app. Your plugin was add via

> cordova plugin add cordova-plugin-ms-speech-service@https://github.com/janowsiany/cordova-plugin-ms-speech-service/releases/download/v0.0.1/cordova-plugin-ms-speech-service-0.0.1.tgz --variable SPEECH_KEY=64e6df36b0ec438aa0XXXXXXXX --variable SERVICE_REGION=westeurope

But the recording function did not work. So I would like to ask you how the structure of the iOS app differs from the Android one. Aside from the different permission request Plugin for the microphone access the only difference in the JS code on index.html probably would affect the JS code for the speech API. Simple asked: Shall the JS code stay unchanged in index.html? What my friend fried was to remove the 

> <script src="microsoft.cognitiveservices.speech.sdk.bundle.js"></script>

to exclude double code with your added framework. But that did not help. I am using the code from

> https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/js-browser/index.html

**Comment by janowsiany** [comment]
Not sure if the usage was right but it should be as follows:
```js
const onSuccess = ({ value }) => console.log(value);
const onError =  ({ message }) => console.log(message);
cordova.plugins.msSpeechService.recognizeOnce(onSuccess, onError);
```

There are also `startContinuousRecognition` and `stopContinuousRecognition` with the same signature.

**Comment by Marcophono2** [comment]
Okay, one difference seems to be 
   recognizeOnce <-> recognizeOnceAsync
Have you a simple working code for a iOS app? May be that my code is too adjusted and differs too much meanwhile from the standard code.

**Comment by janowsiany** [comment]
The snippets above are working pieces of code. If you have more questions we can discuss https://tlk.io/msspeechservice

**Comment by Marcophono2** [comment]
@janowsiany: Have you gotten my email? It's nothing urgent. Just to make sure that I took the correct mail address.

**Comment by wolfma61** [comment]
I'm closing this for now, this discussion has gone stale ...
if there are similar issues, it might be best to create a new issue with the required details.
thx
Wolfgang

**Comment by aroraadi65** [comment]
> Hello!
> I successfully coded a HTML/Cordova app for Android to record audio, stream it to the Azure server and get back the translated text. But for iOS it is not working because getUserMedia is not available here. So I grab now the stream from the microphone with a Cordova plugin. That is working so far but now I must connect the Audio object from the plugin with the stream from the Azure JS code to stream it also like in the Android app to the Azure server. But what exactlly is that stream?
> 
> ```
> function startCapture() {
> 	audioinput.start({
> 		streamToWebAudio: true
> 	});
> 	audioinput.connect(XXX);
> // I need the correct object name for the stream where the XXX is
> }
> ```
> 
> Every help is really very appreciated!
> 
> Best regards
> Marc

Hi Marc, can you please share the repo where you implemented the android example. It would be of great help as I'm also trying to add the same to my ionic application.

Regards
Aditya

**Comment by Marcophono2** [comment]
Hi Aditya!
I have no idea how to set up or share a Repro here. :) If you want I can send you the complete code. 

Best regards
Marc

**Comment by isigui** [comment]
> Hi Aditya!
> I have no idea how to set up or share a Repro here. :) If you want I can send you the complete code.
> 
> Best regards
> Marc

Hello Marcophono2, It would be great if you could share or send your android implementation ?
Thanks a lot

**Comment by Marcophono2** [comment]
Can you send me an email to marc@waesche.org ?

Best Marc
