### ISSUE TITLE
How to get talking avatar progress percentage value in script?

### ISSUE THREAD

**Issue by MurlocTW** [Azure-Samples/cognitive-services-speech-sdk#2253]
In Azure Speech Studio, there is a Live Chat avatar that you can try on your own.
When the avatar is loading, it displays a progress bar with a percentage.
How can I get this value in script?

**Comment by yinhew** [comment]
Hi, @MurlocTW 

The avatar loading progress bar on the Azure speech studio is just a mocked one.
There is no signal from backend to tell the loading progress.
The avatar loading time is usually 4~5s.
The progress bar simply moves based on this foreseeing.

Thanks,
Yinhe

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
