### ISSUE TITLE
CocoaPod Installation seems to arbitrarily cause the error "No such module 'MicrosoftCognitiveServicesSpeech'"

### ISSUE THREAD

**Issue by nikhilKapse7** [Azure-Samples/cognitive-services-speech-sdk#2254]
XCode version: 15.2
13-inch MacBook Pro 2020
macOS: Sonoma 14.3
Project: Swift on XCode 15.2
MicrosoftCognitiveServicesSpeech: 1.33.0

I've had this happen to me twice now, where upon closing and reopening an XCode project that uses the MicrosoftCognitiveServicesSpeech CocoaPod with success, I will begin to get the error "No such module 'MicrosoftCognitiveServicesSpeech'" wherever I try to import MicrosoftCognitiveServicesSpeech. 

The first time I received this error, I fixed it by commenting out the line `use_frameworks!`. Here is what the Podfile looks like:

```
platform :ios, '16.0'
#use_frameworks!

target 'SpeakEasy' do
  pod 'MicrosoftCognitiveServicesSpeech-iOS', '~> 1.33.0'
end
```

Expected behavior: error should not occur

I'm really not sure what the issue could be since it seems so arbitrary - I simple closed and reopened the project (which was working perfectly previously), and the issue appeared. Sometimes, the import error highlight on the import statement is accompanied by a `Command SwiftCompile failed with a nonzero exit code` error,  the logs for which are below:

`SwiftCompile normal x86_64 Compiling\ ScenarioContextView.swift,\ MicView.swift,\ ScenarioOptionView.swift,\ AudioTrackerView.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Chat/Scenarios/ScenarioContextView.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Chat/MicView.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Chat/Scenarios/ScenarioOptionView.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Chat/MessageView/AudioTrackerView.swift (in target 'SpeakEasy' from project 'SpeakEasy')
    cd /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy
    builtin-swiftTaskExecution -- /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Chat/Scenarios/ScenarioContextView.swift -primary-file /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Chat/MicView.swift -primary-file /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Chat/Scenarios/ScenarioOptionView.swift -primary-file /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Chat/MessageView/AudioTrackerView.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/SettingsView.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Chat/MessageView/MessagingUtils.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Chat/ChatView.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/HomeView.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Chat/ProgressAnimation.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Chat/CustomMenuStyle.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/SpeakEasyApp.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Chat/MessageView/MessageView.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Chat/MessageView/FlexibleView.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Archived/VoiceView.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/SpeechRecognizer.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Constants.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Chat/MessageView/TranslateButton.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/API/APIService.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Chat/MessageView/Pronunciation/WordPronunciationView.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Chat/MessageView/SpeechSynthesizerDelegate.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Chat/MessageView/ReactionsPane.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/API/APIStructs.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/ConversationsView.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Chat/Scenarios/ScenarioSelectionView.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/PronunciationAssessmentService.swift /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/SpeakEasy/Chat/AlternateMicView.swift /Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Intermediates.noindex/SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/DerivedSources/GeneratedAssetSymbols.swift -supplementary-output-file-map /Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Intermediates.noindex/SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/Objects-normal/x86_64/supplementaryOutputs-155 -emit-localized-strings -emit-localized-strings-path /Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Intermediates.noindex/SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/Objects-normal/x86_64 -target x86_64-apple-ios16.0-simulator -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.2.sdk -I /Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Products/Debug-iphonesimulator -F /Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Products/Debug-iphonesimulator/PackageFrameworks -F /Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Products/Debug-iphonesimulator/PackageFrameworks -F /Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Products/Debug-iphonesimulator -F /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy/MicrosoftCognitiveServicesSpeech.xcframework/ios-arm64_x86_64-simulator -no-color-diagnostics -enable-testing -g -module-cache-path /Users/nikhilkapse/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -profile-generate -profile-coverage-mapping -swift-version 5 -enforce-exclusivity\=checked -Onone -D DEBUG -serialize-debugging-options -const-gather-protocols-file /Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Intermediates.noindex/SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/Objects-normal/x86_64/SpeakEasy_const_extract_protocols.json -enable-bare-slash-regex -empty-abi-descriptor -validate-clang-modules-once -clang-build-session-file /Users/nikhilkapse/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xcc -working-directory -Xcc /Users/nikhilkapse/Documents/Projects/XCode-Projects/SpeakEasy -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -ivfsstatcache -Xcc /Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator17.2-21C52-4f2951bfe8f3cd53c99228b0131e163e.sdkstatcache -Xcc -I/Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Intermediates.noindex/SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Intermediates.noindex/SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/SpeakEasy-generated-files.hmap -Xcc -I/Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Intermediates.noindex/SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/SpeakEasy-own-target-headers.hmap -Xcc -I/Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Intermediates.noindex/SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/SpeakEasy-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Intermediates.noindex/SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Intermediates.noindex/SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/SpeakEasy-project-headers.hmap -Xcc -I/Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Products/Debug-iphonesimulator/include -Xcc -I/Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Intermediates.noindex/SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/DerivedSources-normal/x86_64 -Xcc -I/Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Intermediates.noindex/SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/DerivedSources/x86_64 -Xcc -I/Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Intermediates.noindex/SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/DerivedSources -Xcc -DDEBUG\=1 -module-name SpeakEasy -frontend-parseable-output -disable-clang-spi -target-sdk-version 17.2 -target-sdk-name iphonesimulator17.2 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.2.sdk/usr/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.2.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.2.sdk/usr/local/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.2.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/local/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/lib/swift/host/plugins -o /Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Intermediates.noindex/SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/Objects-normal/x86_64/ScenarioContextView.o -o /Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Intermediates.noindex/SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/Objects-normal/x86_64/MicView.o -o /Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Intermediates.noindex/SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/Objects-normal/x86_64/ScenarioOptionView.o -o /Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Build/Intermediates.noindex/SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/Objects-normal/x86_64/AudioTrackerView.o -index-unit-output-path /SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/Objects-normal/x86_64/ScenarioContextView.o -index-unit-output-path /SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/Objects-normal/x86_64/MicView.o -index-unit-output-path /SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/Objects-normal/x86_64/ScenarioOptionView.o -index-unit-output-path /SpeakEasy.build/Debug-iphonesimulator/SpeakEasy.build/Objects-normal/x86_64/AudioTrackerView.o -index-store-path /Users/nikhilkapse/Library/Developer/Xcode/DerivedData/SpeakEasy-apkccmxmxhbgaedcadgzqedwnjwh/Index.noindex/DataStore -index-system-modules`

**Comment by jhakulin** [comment]
@nikhilKapse7 When problem happens, does the restarting the XCode helps? 

I have probably seen the issue occasionally and have not identified issue specific to Speech SDK but thinking more probably issue with pod installation related tooling with XCode. I am afraid, there is hard to do any further actions than keeping eye on this and see when that happens, think is there any specific way to repro the issue and try to narrow down what makes the issue happen.

**Comment by nikhilKapse7** [comment]
I've since noticed that opening the .xcodeworkspace file rather than the .xcodeproj file seems to get rid of the error for some reason, but still not sure why that's the case.

**Comment by jhakulin** [comment]
@nikhilKapse7 That is good point, thanks for details, especially when the Xcode projects depends on pods, the .xcodeworkspace file gets generated during pod install and that shall be used. I'll close the issue as probably this is not directly Speech SDK related.
