### ISSUE TITLE
Python Speech-to-text version 3.2-preview Error with multiple locales gives error

### ISSUE THREAD

**Issue by piebebakke** [Azure-Samples/cognitive-services-speech-sdk#2256]
When running the example https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/chlandsi/v3.2-preview/samples/batch/python/python-client/main.py  with only line 159 uncommented:
"
 properties.language_identification = swagger_client.LanguageIdentificationProperties(["en-US", "ja-JP"])
"
and my credtials/params gives the following output/error when run:
"
02/05/2024 08:50:31 AM UTC Starting transcription client...
Traceback (most recent call last):
  File "/home/ec2-user/voicetry/AZR3.2-preview.py", line 209, in <module>
    transcribe()
  File "/home/ec2-user/voicetry/AZR3.2-preview.py", line 159, in transcribe
    properties.language_identification = swagger_client.LanguageIdentificationProperties(["en-US", "ja-JP"])
  File "/home/ec2-user/voice/lib64/python3.9/site-packages/swagger_client/models/language_identification_properties.py", line 60, in __init__
    self.candidate_locales = candidate_locales
  File "/home/ec2-user/voice/lib64/python3.9/site-packages/swagger_client/models/language_identification_properties.py", line 106, in candidate_locales
    raise ValueError("Invalid value for `candidate_locales`, must not be `None`")  # noqa: E501
ValueError: Invalid value for `candidate_locales`, must not be `None`
"
When run against V3.1 it runs flawlessly.

Operating sytstem: Amazon Linux 2023
Python version: 3.9

**Comment by chlandsi** [comment]
Thanks for notifying us about the error in the sample! There was an update to the language identification feature; it now takes `mode` that can be either `single` or `continuous`, so the updated call is `properties.language_identification = swagger_client.LanguageIdentificationProperties(mode="single", candidate_locales=["en-US", "ja-JP"])`.
The sample code has been [updated](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/aabcf40724f6c8bb2bbbf39b5894e138da23e098/samples/batch/python/python-client/main.py#L160) as well.

**Comment by piebebakke** [comment]
Thanks for your swift response and resolution.

I have tested it, both in the example code and my own application and it works as a charm.

BTW: I noticed the particular line (160) in the example code is left uncommented. Not sure if that is intended. 

Thanks again.
