### ISSUE TITLE
Network check fails behind a specialised DNS server

### ISSUE THREAD

**Issue by maczikasz** [Azure-Samples/cognitive-services-speech-sdk#226]
**Describe the bug**
Trying to run an app relying on cognitive services in a corporate kubernetes environment. There is a special dns server that can only resolve hostnames within the corporate network, all http requests should go through a proxy. The proxy hostname can be resolved by this DNS server, so I can wget out to the cognitive services endpoint, but when I try to use the cognitive services API it fails with a DNS resolution error.

**To Reproduce**
1. change DNS server in /etc/resolve.conf so it can resolve your proxy's IP
2. setup proxy in SpeechConfig
3. try to connect

**Expected behavior**
All connection requests go though the proxy

**Version of the Cognitive Services Speech SDK**
1.4.0

**Platform, Operating System, and Programming Language**
 - OS: ubuntu:16.04 within a docker in kubernetes
 - Programming language: Java

**Additional context**
`(627): 11164179ms SPX_DBG_TRACE_VERBOSE: LogPropertyAndValue: this=0x1c1d1198; name='AudioConfig_SampleRateForCapture'; value='16000'
(627): 11164179ms SPX_DBG_TRACE_VERBOSE: LogPropertyAndValue: this=0x1c1d1198; name='AudioConfig_BitsPerSampleForCapture'; value='16'
(627): 11164179ms SPX_DBG_TRACE_VERBOSE: LogPropertyAndValue: this=0x1c1d1198; name='AudioConfig_NumberOfChannelsForCapture'; value='1'
(627): 11164179ms SPX_DBG_TRACE_VERBOSE: UspInitialize: recoMode=1
(627): 11164180ms SPX_TRACE_INFO: AZ_LOG_INFO: connectionUrl=wss://westeurope.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?format=detailed&language=en-US
(627): 11164180ms SPX_DBG_TRACE_VERBOSE: speech.config {"context":{"audio":{"source":{"bitspersample":"16","channelcount":"1","model":"","samplerate":"16000","type":"Stream"}},"os":{"name":"XXX","platform":"Linux","version":"XXXX"},"system":{"build":"Linux-x64","lang":"Java","name":"SpeechSDK","version":"1.4.0"}}}
(627): 11164180ms SPX_DBG_TRACE_VERBOSE: speech.config='{"context":{"audio":{"source":{"bitspersample":"16","channelcount":"1","model":"","samplerate":"16000","type":"Stream"}},"os":{"name":"XXX","platform":"Linux","version":"XXX"},"system":{"build":"Linux-x64","lang":"Java","name":"SpeechSDK","version":"1.4.0"}}}'
(627): 11164180ms SPX_DBG_TRACE_SCOPE_EXIT: SetFormat
(627): 11164180ms SPX_TRACE_INFO: AZ_LOG_INFO: Start network check westeurope.stt.speech.microsoft.com
(627): 11164180ms SPX_TRACE_INFO: AZ_LOG_INFO: load_system_store not implemented on this platform
(627): 11164281ms SPX_TRACE_ERROR: AZ_LOG_ERROR: Network Check failed -3
(627): 11164281ms SPX_TRACE_ERROR: Error: File:/home/vsts/work/1/s/source/core/usp/transport.cpp Func:DnsComplete Line:536 
(627): 11164281ms SPX_TRACE_INFO: AZ_LOG_INFO: TS:101, TransportError: connection:0xdc002690, reason=6, code=-3 [0xfffffffd], string=
(627): 11164281ms SPX_DBG_TRACE_VERBOSE: Response: On Error: Code:5, Message: DNS connection failed (the remote host did not respond). Internal error: -3.`

**Comment by maczikasz** [comment]
I assume nobody is looking at this :)

**Comment by zhouwangzw** [comment]
Thank you for reporting the issue. Currently in Speech SDK the service host name needs to be resolved by the DNS server in your network setting. We may remove this limitation in future, i.e. just using proxy configuration without resolving service host name via DNS. I will bring up your case in our feature planning meeting. 
Sorry for the inconvenience!

Zhou
