### ISSUE TITLE
A new deployment is failing. New functions are empty after creation

### ISSUE THREAD

**Issue by joejony** [Azure-Samples/cognitive-services-speech-sdk#2262]
Deployed the Ingestion client today, in East US and also South Central US.
Deployment was successful, but the two functions StartTranscriptionFunction and FetchTranscriptionFunction are empty.
Solution is not working in any of the regions.

The Speech API was previously deployed in East US and it is working inside API Speech Studio.

On Activity Log for both functions we got this error:

-- Operation Name: Sync Web Apps Function Triggers
-- Error Code: BadRequest
-- Message: Encountered an error (InternalServerError) from host runtime.

![error-functions](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/19648959/a0e702a2-e393-4e72-b27d-3a399c0220e1)

**Comment by glharper** [comment]
@joejony Thank you for using Speech SDK and writing this issue up. This appears to be an issue with a runtime using the SDK, correct? Could you provide details or logs from the host runtime to help us determine whether the Speech SDK is causing that InternalServerError?

Which version of Speech SDK are you using, and which language?

**Comment by joejony** [comment]
@glharper . The issue is happening when I deploy the Ingestion Client, Batch Version, using this Azure Custom Deployment Template from this location: https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json 

The deployment finishes successfully. 

But for unknown reasons the 2 Functions are not deployed correctly. There are "empty". See below:

![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/19648959/3968c242-b80c-4b1f-ae5b-0826ef152b27)

 When I try to access the function, I got an error:

![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/19648959/134c07b4-7d4b-4e69-a992-531831fed647)

The same happens with the other function:

![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/19648959/58b3488c-b607-41eb-94cc-48cc3ce7e79f)

I did a deployment using the same JSON, 30 days ago and worked perfect. I still have the environment and it is working and has the functions there. I can share more information on the previous working environment if you need.

thanks.

**Comment by joejony** [comment]
![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/19648959/d12ab387-9827-47b8-849f-aa44529f0c45)

=x=x=x=x=x

{
    "authorization": {
        "action": "Microsoft.Web/sites/host/sync/action",
        "scope": "/subscriptions/XPTO/resourceGroups/rg-hilton5/providers/Microsoft.Web/sites/StartTranscriptionFunction-hilton5/host/default"
    },
    "caller": "jcoimbra@XPTO",
    "channels": "Operation",
    "claims": {
        "aud": "https://management.core.windows.net/",
        "iss": "https://sts.windows.net/16b3c013-d300-468d-ac64-7eda0820b6d3/",
        "iat": "1707318859",
        "nbf": "1707318859",
        "exp": "1707323380",
        "http://schemas.microsoft.com/claims/authnclassreference": "1",
        "aio": "AZQAa/8VAAAA/8yGwUrmvcqJIL6kPR3iS5BZSBcclXbZQubWlZp1vqSLYR2RRgdg8x3RChX507phd5KeQ6aa6OjqSMumOOdHFZgB95SdquATf1emEtdET09IpGLN+AWvDe8mrg9aBqlpaXSRTdkIU5tft74yceT/F/QNl262CjjGzr5sP+XFOE5EjMUWtZo47ybirJC9hge7",
        "altsecid": "5::10030000801C1D1D",
        "http://schemas.microsoft.com/claims/authnmethodsreferences": "fido,rsa,mfa",
        "appid": "c44b4083-3bb0-49c1-b47d-974e53cbdf3c",
        "appidacr": "0",
        "http://schemas.microsoft.com/2012/01/devicecontext/claims/identifier": "d43909ac-3251-49fe-a8c4-c8875741b4af",
        "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress": "jcoimbra@XPTO",
        "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname": "Coimbra",
        "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname": "Joao",
        "groups": "b1304022-08e6-447d-b094-15370597c6b6,d34c4ebe-4984-4903-a64d-8c20283d516b,e3096df7-b65c-4e32-ab1a-7a35dc684f0a",
        "http://schemas.microsoft.com/identity/claims/identityprovider": "https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/",
        "idtyp": "user",
        "ipaddr": "2600:1700:5d00:749f:4ce7:b3e:c1b9:5ee9",
        "name": "Joao Coimbra",
        "http://schemas.microsoft.com/identity/claims/objectidentifier": "7b10b846-56d8-4f60-9f64-9daf812355bb",
        "puid": "10032002576C3253",
        "rh": "0.AUYAE8CzFgDTjUasZH7aCCC200ZIf3kAutdPukPawfj2MBPxAEc.",
        "http://schemas.microsoft.com/identity/claims/scope": "user_impersonation",
        "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier": "ITdXLNIq1VYWFwzVRgO3EVDqpxzOzozOluAr_Z1HU9I",
        "http://schemas.microsoft.com/identity/claims/tenantid": "16b3c013-d300-468d-ac64-7eda0820b6d3",
        "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name": "jcoimbra@XPTO,
        "uti": "MOku8douiUmNjNlLaiJ0AA",
        "ver": "1.0",
        "xms_cae": "1",
        "xms_edov": "true",
        "xms_tcdt": "1645137228"
    },
    "correlationId": "d56d07e9-4ec1-4b90-bfef-26909792d23d",
    "description": "",
    "eventDataId": "10c37a5c-bef9-429f-826a-5389738cb6e9",
    "eventName": {
        "value": "EndRequest",
        "localizedValue": "End request"
    },
    "category": {
        "value": "Administrative",
        "localizedValue": "Administrative"
    },
    "eventTimestamp": "2024-02-07T15:50:54.7318135Z",
    "id": "/subscriptions/3714133c-d21b-4f8d-943b-78a89ded31d5/resourceGroups/rg-hilton5/providers/Microsoft.Web/sites/StartTranscriptionFunction-hilton5/host/default/events/10c37a5c-bef9-429f-826a-5389738cb6e9/ticks/638429178547318135",
    "level": "Error",
    "operationId": "c9f62830-1b82-4e48-9a92-adc1293c8dab",
    "operationName": {
        "value": "Microsoft.Web/sites/host/sync/action",
        "localizedValue": "Sync Web Apps Function Triggers"
    },
    "resourceGroupName": "rg-hilton5",
    "resourceProviderName": {
        "value": "Microsoft.Web",
        "localizedValue": "Azure Web Sites"
    },
    "resourceType": {
        "value": "Microsoft.Web/sites/host",
        "localizedValue": "Microsoft.Web/sites/host"
    },
    "resourceId": "/subscriptions/3714133c-d21b-4f8d-943b-78a89ded31d5/resourceGroups/rg-hilton5/providers/Microsoft.Web/sites/StartTranscriptionFunction-hilton5/host/default",
    "status": {
        "value": "Failed",
        "localizedValue": "Failed"
    },
    "subStatus": {
        "value": "BadRequest",
        "localizedValue": "Bad Request (HTTP Status Code: 400)"
    },
    "submissionTimestamp": "2024-02-07T15:54:31Z",
    "subscriptionId": "3714133c-d21b-4f8d-943b-78a89ded31d5",
    "tenantId": "16b3c013-d300-468d-ac64-7eda0820b6d3",
    "properties": {
        "statusCode": "BadRequest",
        "serviceRequestId": null,
        "statusMessage": "{\"Code\":\"BadRequest\",\"Message\":\"Encountered an error (InternalServerError) from host runtime.\",\"Target\":null,\"Details\":[{\"Message\":\"Encountered an error (InternalServerError) from host runtime.\"},{\"Code\":\"BadRequest\"},{\"ErrorEntity\":{\"Code\":\"BadRequest\",\"Message\":\"Encountered an error (InternalServerError) from host runtime.\"}}],\"Innererror\":null}",
        "eventCategory": "Administrative",
        "entity": "/subscriptions/3714133c-d21b-4f8d-943b-78a89ded31d5/resourceGroups/rg-hilton5/providers/Microsoft.Web/sites/StartTranscriptionFunction-hilton5/host/default",
        "message": "Microsoft.Web/sites/host/sync/action",
        "hierarchy": "16b3c013-d300-468d-ac64-7eda0820b6d3/896a9463-4bb5-462e-b7b5-2e525d3e1a03/08cc2a62-5116-449e-bed1-98c29bd48de7/3714133c-d21b-4f8d-943b-78a89ded31d5"
    },
    "relatedEvents": []
}

**Comment by glharper** [comment]
@HenryvanderVegte Could you take a look at this?

**Comment by dargilco** [comment]
I pinged @HenryvanderVegte  and @mahilleb-msft today

**Comment by HenryvanderVegte** [comment]
Hi @joejony ,

as discussed offline:
The issue was that no new application packages could be published. Fixed it in PR https://github.com/Azure-Samples/cognitive-services-speech-sdk/pull/2263 .

Thanks!
