### ISSUE TITLE
Calling SpeechSynthesizer.StopSpeakingAsync() takes a long time to stop audio output when synthesizing longer texts.

### ISSUE THREAD

**Issue by csivek-braintrain** [Azure-Samples/cognitive-services-speech-sdk#2264]
**Problem:** 
When synthesizing text to the speaker output, The `SpeechSynthesizer.StopSpeakingAsync() `method does not work correctly during long text synthesis. The method works correctly if the text being synthesized is only a few sentences long. When called on text that is multiple paragraphs (generally 2000+ characters), audio continues to be outputted for around 30 seconds after calling the stop function, but it does seem to stop correctly if called within ~10 seconds of calling `StartSpeakingTextAsync();`.

**Expected Behavior:**
`SpeechSynthesizer.StopSpeakingAsync()` should stop any audio output immediately and be consistent regardless of text length.

**Steps to reproduce:**
1. Call `StartSpeakingTextAsync(text)` with long text (I tested with 2000+ character text)
2. Wait at least 10 seconds
3. call `SpeechSynthesizer.StopSpeakingAsync()`
4. Speech continues to be outputted for several seconds, upwards to around 30 seconds after.

**Code to reproduce:**

```
internal class Program
{
  private const string SAMPLE_SHORT_TEXT = "the quick brown fox jumps over the lazy dog";

  private const string SAMPLE_LONG_TEXT = "<insert 2000+ character text here>";

  static void Main(string[] args)
  {
    string subscriptionKey = "";
    string subscriptionRegion = "";
    var config = SpeechConfig.FromSubscription(subscriptionKey, subscriptionRegion);
    var synthesizer = new SpeechSynthesizer(config);
    
    Task.Run(async () => {
      Console.WriteLine("Start speaking short text");
      await synthesizer.StartSpeakingTextAsync(SAMPLE_SHORT_TEXT);
      Thread.Sleep(3000);
      Console.WriteLine("Stop speaking short text");
      await synthesizer.StopSpeakingAsync();

      Thread.Sleep(3000);
      Console.WriteLine("Start speaking long text");
      await synthesizer.StartSpeakingTextAsync(SAMPLE_LONG_TEXT);
      Thread.Sleep(10000);
      Console.WriteLine("Stop speaking long text");
      await synthesizer.StopSpeakingAsync();
    });
    while (true) { }
  }
}
```

**Other Info:**
- Using version 1.35.0

 - OS: Windows 10
 - Hardware - x64
 - Programming language: C#

**Comment by yulin-li** [comment]
@csivek-braintrain it would be helpful if you can share the [SDK log](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-use-logging). Sometimes the stop issue is from the audio driver so we need the log to investigate.

**Comment by pankopon** [comment]
Closed since no logs provided. Please open a new issue if more support is needed.

**Comment by hth26** [comment]
I have the same problem!
