### ISSUE TITLE
"Hey Siri" stops working when using keyword recognition

### ISSUE THREAD

**Issue by bpasero** [Azure-Samples/cognitive-services-speech-sdk#2265]
**Describe the bug**

1. Set up Siri and make sure she responds to "Hey, Siri".
2. Launch VS Code with VS Code Speech installed.
3. Set accessibility.voice.keywordActivation to "chatInContext". (Probably anything other than "off" will do the trick.)
4. Say "Hey, Siri". Siri will not respond.

**To Reproduce**

1. open VS Code
2. install [GitHub Copilot Chat](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-chat) and [VS Code Speech](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-speech) extension 
3. accessibility.voice.keywordActivation to "chatInContext"

**Expected behavior**

"Hey Siri" should still work.

**Version of the Cognitive Services Speech SDK**

1.33.x

**Platform, Operating System, and Programming Language**

Darwin arm64 23.3.0

**Additional context**

Originally reported as https://github.com/microsoft/vscode/issues/204811

VS Code extension is using the Azure Speech SDK in C++ and the keyword recognition code is here: https://github.com/microsoft/node-speech/blob/22064207050a16d0b30b1305857bafbba07402c9/src/main.cc#L424

**Comment by glecaros** [comment]
hi @bpasero, the reason for this is that the SDK starts recording audio when keyword spotter is active, so this is expected to interfere with Siri in the same way that, for example, recording a voice memo would interfere with it. To mitigate this, the app can stop recognizing when it goes into the background.

**Comment by pankopon** [comment]
Closed as answered, with a workaround.
