### ISSUE TITLE
Low quality when talking in MS Teams while keyword recognition

### ISSUE THREAD

**Issue by bpasero** [Azure-Samples/cognitive-services-speech-sdk#2266]
**Describe the bug**

1. open VSCode, ensure that there's the micro icon appears on the system tray, and copilot voice chat in vscode is ok
2. join a Microsoft Teams meeting, the collegues says that they cannot hear you very clearly, even if you're not using vscode voice chat at that moment.
3. close VSCode, then collegues on Teams says it's good now.

**To Reproduce**

1. open VS Code
2. install [GitHub Copilot Chat](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-chat) and [VS Code Speech](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-speech) extension 
3. accessibility.voice.keywordActivation to "chatInContext"

**Expected behavior**

Quality of voice recording in Teams should not degrade.

**Version of the Cognitive Services Speech SDK**

1.33.x

**Platform, Operating System, and Programming Language**

Windows 11

**Additional context**

Originally reported as https://github.com/microsoft/vscode/issues/204722

VS Code extension is using the Azure Speech SDK in C++ and the keyword recognition code is here: https://github.com/microsoft/node-speech/blob/22064207050a16d0b30b1305857bafbba07402c9/src/main.cc#L424

**Comment by glecaros** [comment]
hi @bpasero, similar to #2265, this is related to how the OS handles audio and the mitigation would be to either stop recognizing/recording when losing focus.

**Comment by deepak1556** [comment]
Chromium based applications generally connect to `IAudioClient` under `AUDCLNT_SHAREMODE_SHARED` mode, refs https://source.chromium.org/chromium/chromium/src/+/main:media/audio/win/audio_low_latency_input_win.cc. Does speech sdk also connect under this mode ? Would it be any different using the exclusive mode ?

**Comment by pankopon** [comment]
Closed since based on input from @dargilco this is now followed up internally.
