### ISSUE TITLE
List all the endpoints that need to be opened for azure cognitive services to work

### ISSUE THREAD

**Issue by maczikasz** [Azure-Samples/cognitive-services-speech-sdk#227]
Need to work with Azure Cognitive services in a corporate environment, and I need to file a firewall request for each endpoint that needs to be opened from MS, so I would appreciate a list of these if the code is not open source...

So far I have found:
westeurope.stt.speech.microsoft.com
westeurope.api.speech.microsoft.com

but it seems to fail for not having access to :
http://mscrl.microsoft.com/pki/mscorp/crl/Microsoft%20IT%20TLS%20CA%205.crl

**Comment by zhouwangzw** [comment]
westeurope.stt.speech.microsoft.com is for speech-to-text using WestEurope region. If you want to use other regions, *.stt.speech.microsoft.com should be good. 

If you need translation, *.s2s.speech.microsoft.com are host names being used.

On platforms using OpenSSL (linux/android/windows uwp), SDK needs to access sites specified in the certificates to get certification revocation lists. http://mscrl.microsoft.com is one of such sites. 

Thanks,
Zhou

**Comment by mahilleb-msft** [comment]
Please also check out the REST API section [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-speech-to-text) for other endpoints.

crl3.digicert.com is currently also used for certificate revocation lists.

**Comment by maczikasz** [comment]
It seems that CRL have changed to  http://www.microsoft.com/pkiops/crl/Microsoft%20Azure%20TLS%20Issuing%20CA%2001.crl

from mscrl.microsoft.com 

This actually caused our app not to function with the latest updates, are there any other changes like this where we need to adapt firewall policies? 

I checked the release notes and saw no mention of this, how can we be aware of such changes?

**Comment by maczikasz** [comment]
https://docs.microsoft.com/en-us/azure/security/fundamentals/tls-certificate-changes#will-this-change-affect-me

**Comment by wolfma61** [comment]
look at the date of that article ... October 2020
you should have seen the result of these changes several month ago

**Comment by maczikasz** [comment]
well the problem only manifests if you upgrade the SDK, which i have not done. As well it could have been at least mentioned in the release notes
