### ISSUE TITLE
Runtime error: Failed to initialize platform (azure-c-shared). Error: 2176. For Microsoft.CognitiveServices.Speech in Azure Linux App Service with .NET 8

### ISSUE THREAD

**Issue by TheSwilliam** [Azure-Samples/cognitive-services-speech-sdk#2272]
Transcription recognizer cancels on initial start of the Recognizer in Azure Linux App Service with .NET 8. The code works in Linux App Service with .NET 6.

I am using version 1.34.0 of Microsoft.CognitiveServices.Speech

ErrorDetails=Runtime error: Failed to initialize platform (azure-c-shared). Error: 2176 SessionId: 06e91e57101349c185539ec809c06d31

It might just be an issue with Linux App service and running .NET 8.

**To Reproduce**

1. Deploy .NET 8 code with Microsoft.CognitiveServices.Speech to azure linux appservice with Framework version .NET 8 and try and start transcribing real time audio.

Here is a code snippet:

```
 public AzureTranscriptionService()
    {
        var audioStreamFormat = AudioStreamFormat.GetWaveFormatPCM(SampleRate, BitsPerSample, Channel);

        var settings = azureSettings.CurrentValue;
        var config =
            SpeechConfig.FromSubscription(settings.SpeechService.SubscriptionKey, settings.SpeechService.RegionName);
        config.SpeechRecognitionLanguage = LanguageCode;

        config.OutputFormat = OutputFormat.Detailed;

        _inputStream = AudioInputStream.CreatePushStream(audioStreamFormat);
        _audioInput = AudioConfig.FromStreamInput(_inputStream);

        _recognizer = new SpeechRecognizer(config, _audioInput);
        _recognizer.SessionStarted += TranscriberStarted;
        _recognizer.Canceled += TranscriberCancelled;
        _recognizer.SessionStopped += TranscriberStopped;

        _recognizer.Recognizing += TranscribingSpeech;
        _recognizer.Recognized += TranscribedSpeech;
    }

    public Task StartAsync()
    {
        return _recognizer.StartContinuousRecognitionAsync();
    }

  public void WriteToTranscriptionStream(byte[] audio)
    {
        _inputStream.Write(audio);
    }
```

**Comment by dargilco** [comment]
@TheSwilliam thank you for bringing this to our attention! Please enable Speech SDK logs, do a run and share the log with us. Instructions for enabling logs: https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-use-logging

Please also try out our console .NET samples: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/csharp/dotnetcore/console . Clone the repo on your Linux machine, pick a speech recognition sample (to start with), enter our speech key and azure region, and run the sample. You should first update the .csproj file such that net6.0 is used (instead of netcoreapp3.1) and see if that works. Then update to net8.0 and see if that still works. That will be good information to narrow down the issue. Thanks!

**Comment by dargilco** [comment]
@TheSwilliam Also note this GitHub issue with the same error: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2204 . Not clear to me if you have the same issue, as it worked for you when using net6.0.

**Comment by dargilco** [comment]
@TheSwilliam what Linux OS and version are you running? Please also run "openssl version" on your Linux box and let us know what version you have. Thanks!

**Comment by TheSwilliam** [comment]
Error received during the test. Log file attached.

ErrorDetails=Runtime error: Failed to initialize platform (azure-c-shared). Error: 2176 SessionId: 598dc07cda6444e485083856b3847d1a

OpenSSL 3.0.11 19 Sep 2023 (Library: OpenSSL 3.0.11 19 Sep 2023)

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian

[MicrosoftCognitiveServicesSpeechLogs.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/14388295/MicrosoftCognitiveServicesSpeechLogs.txt)

Please let me know if anything else is needed.

**Comment by dargilco** [comment]
@TheSwilliam Speech SDK needs Open SSL 1.x to run. We are in the process of updating it to use Open SSL 3.x, and that will be available in a future version of Speech SDK. For the time being, please follow the instructions here to compile and deploy Open SSL 1.x in your Linux environment: https://learn.microsoft.com/en-us/azure/ai-services/speech-service/quickstarts/setup-platform?tabs=linux%2Cubuntu%2Cdotnetcli%2Cdotnet%2Cjre%2Cmaven%2Cnodejs%2Cmac%2Cpypi&pivots=programming-language-csharp
