### ISSUE TITLE
Incorrect C# docs: PronunciationAssessmentGranularity.Syllable still in docs while its removed from the SDK

### ISSUE THREAD

**Issue by TomDoesb** [Azure-Samples/cognitive-services-speech-sdk#2277]
The `C#` documentation still mentions the Granularity.Syllable option: [C# docs](https://learn.microsoft.com/en-gb/azure/ai-services/speech-service/how-to-pronunciation-assessment?pivots=programming-language-csharp) This seems to be removed from the sdk and should be removed from the `C#` docs.

![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/12149839/79b9c67b-9061-4144-ab07-88b321aa0e99)

**Comment by jhakulin** [comment]
@yinhew Please help to improve this.

**Comment by wangkenpu** [comment]
![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/15028609/0d1aa789-d429-4c2c-bc2c-4222c80f96b8)
Doc has been updated.

**Comment by yulin-li** [comment]
@TomDoesb thanks for reporting this issue. We fixed the doc accordingly. Closing this now
