### ISSUE TITLE
SetSpeechSynthesisOutputFormat does not work for translation

### ISSUE THREAD

**Issue by panitaxx** [Azure-Samples/cognitive-services-speech-sdk#2279]
**Describe the bug**

When using the following configuration I  always get WAV files. 

```c++
  auto speechConfig =
      SpeechTranslationConfig::FromSubscription(speechKey, speechRegion);
  speechConfig->SetProperty(PropertyId::Speech_LogFilename, "/tmp/speech.log");
  speechConfig->SetSpeechRecognitionLanguage("es-ES");

  speechConfig->AddTargetLanguage("en");
  speechConfig->SetVoiceName("en-US-AriaNeural");
  speechConfig->SetSpeechSynthesisOutputFormat(SpeechSynthesisOutputFormat::Raw8Khz16BitMonoPcm);
``` 

I expect RAW PCM. I also tried with ulaw raw pcm and same output.  (it does translate correctly though)

I output the first bytes and it is  a wav file:

```
RECOGNIZED: Text=Esto es una prueba.
RECOGNIZED: Translation=en Text=This is a test.
R I F F . . . . W A V E f m t   . . . . . . . . . > . . . } . . . . . . d a t a . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
``` 

**To Reproduce**

create a speech config set any use SetSpeechSynthesisOutputFormat

**Expected behavior**

Get raw format.

**Version of the Cognitive Services Speech SDK**

Which version of the SDK are you using. 1.35.0

**Platform, Operating System, and Programming Language**

Linux x86-64 c++ Ubuntu 22.04

**Comment by jhakulin** [comment]
@yulin-li Please let us know if this is a bug or current design?

**Comment by yulin-li** [comment]
As far as I know, only `riff-16khz-16bit-mono-pcm` format is supported in speech translation audio output. This is a feature gap. I will track this internally. I am closing this issue for now.
