### ISSUE TITLE
Azure Neural Voice: Invalid deploymentId

### ISSUE THREAD

**Issue by ericabutts** [Azure-Samples/cognitive-services-speech-sdk#2282]
I trained, created and deployed a Custom Voice model with Azure's Speech Studio.

On the Deploy Model page, I am given a Resource key, a Service region and Endpoint ID. I used the Endpoint ID (I am sure that it is correct) in my code below.

However, I'm getting this error: **Error code: 1007. Error details: Invalid deploymentId XXXXX USP state: TurnStarted. Received audio size: 0 bytes.] CANCELED: Did you set the speech resource key and region values?**

**To Reproduce**

1. Attempt to use your neural voice with .NET SDK
2. Provide region, resource key, provide endpoint ID.

`using System;
using System.IO;
using System.Threading.Tasks;
using Microsoft.CognitiveServices.Speech;
using Microsoft.CognitiveServices.Speech.Audio;

class Program 
{
    // This example requires environment variables named "SPEECH_KEY" and "SPEECH_REGION"
    static string speechKey = "my-resource-key";
    static string speechRegion = "my-region";

    

    static void OutputSpeechSynthesisResult(SpeechSynthesisResult speechSynthesisResult, string text)
    {
        switch (speechSynthesisResult.Reason)
        {
            case ResultReason.SynthesizingAudioCompleted:
                Console.WriteLine($"Speech synthesized for text");
                break;
            case ResultReason.Canceled:
                var cancellation = SpeechSynthesisCancellationDetails.FromResult(speechSynthesisResult);
                Console.WriteLine($"CANCELED: Reason={cancellation.Reason}");

                if (cancellation.Reason == CancellationReason.Error)
                {
                    Console.WriteLine($"CANCELED: ErrorCode={cancellation.ErrorCode}");
                    Console.WriteLine($"CANCELED: ErrorDetails=[{cancellation.ErrorDetails}]");
                    Console.WriteLine($"CANCELED: Did you set the speech resource key and region values?");
                }
                break;
            default:
                break;
        }
    }

    async static Task Main(string[] args)
    {
        var speechConfig = SpeechConfig.FromSubscription(speechKey, speechRegion);  
           

        // The language of the voice that speaks.
        speechConfig.SpeechSynthesisVoiceName = "MyNeuralVoice"; 
        speechConfig.EndpointId = "my-endpoint-id"; 

        using (var speechSynthesizer = new SpeechSynthesizer(speechConfig))
        {
            // Get text from the console and synthesize to the default speaker.
            Console.WriteLine("Enter some text that you want to speak >");
            string text = Console.ReadLine();

            var speechSynthesisResult = await speechSynthesizer.SpeakTextAsync(text);
            OutputSpeechSynthesisResult(speechSynthesisResult, text);
        }

        Console.WriteLine("Press any key to exit...");
        Console.ReadKey();
    }
}

`

**Expected behavior**

**Error code: 1007. Error details: Invalid deploymentId XXXXX USP state: TurnStarted. Received audio size: 0 bytes.] CANCELED: Did you set the speech resource key and region values?**

**Version of the Cognitive Services Speech SDK**

Net7.0
Microsoft.CognitiveServices.Speech/1.35.0

**Platform, Operating System, and Programming Language**

 - OS: MacOS
 - Hardware - Intel
 - Programming language: C#

https://stackoverflow.com/questions/78084989/azure-neural-voice-invalid-deploymentid

**Comment by BrianMouncer** [comment]
Deployments are key and region specific.
are you sure your key and region here match the custom endpoint id you used below?

SpeechConfig.FromSubscription(**speechKey**, **speechRegion**);

**Comment by ericabutts** [comment]
<img width="711" alt="Screen Shot 2024-03-01 at 12 17 38 PM" src="https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/26892171/d3648200-3526-49fa-bb47-26c236fae3fc">

Yes I'm using the Resource key, the Service region and Endpoint ID provided by the endpoint. 

It is able to work with the other models:
`
speechConfig.SpeechSynthesisVoiceName = "en-US-JennyNeural";  // don't provide an EndpointID
`

However, It doesn't work on my own neural model:
`
speechConfig.SpeechSynthesisVoiceName = "ElderlyVoiceModel";
speechConfig.EndpointId = "my-endpointID-here"; 
// the error above is caused after providing some text to speak
`

**Comment by yulin-li** [comment]
@Kerry-LinZhang could you help to forward to custom voice team and triage?

**Comment by Kerry-LinZhang** [comment]
sure, we are investigating on it.

**Comment by Kerry-LinZhang** [comment]
Hi @ericabutts we noticed the page shows 'custom speech', and not custom voice, would you please check if you have gone to the right page for certain deployment?

**Comment by ericabutts** [comment]
Great, it worked now for me!!! Sorry, I was on the wrong page... Thank you so much!

**Comment by gamullen** [comment]
@ericabutts - can you please let me know exactly how you solved this? I'm hitting the exact same error.

You just moved to a Custom Voice project instead of Custom Speech?

**Comment by ericabutts** [comment]
> @ericabutts - can you please let me know exactly how you solved this? I'm hitting the exact same error.
> 
> You just moved to a Custom Voice project instead of Custom Speech?

@gamullen I was on the wrong page. When in Azure initially selecting a service, don't select 'Custom Speech'. **Select 'Custom Voice'.** It's a little further down the page. They sound very similar so that tripped me up.
