### ISSUE TITLE
WebSocket upgrade failed: Authentication error (401).

### ISSUE THREAD

**Issue by Soappiness** [Azure-Samples/cognitive-services-speech-sdk#2286]
Hello!

I'm trying to make a Speech to Text project with Speech SDK. After following many code examples I get this code:

```c#
public static async Task<string> RecognizeSpeechAsync(string serviceRegion, string subKey)
{
    var audioProcessingConstants = AudioProcessingConstants.AUDIO_INPUT_PROCESSING_NONE;
    var audioProcessingOptions = AudioProcessingOptions.Create(audioProcessingConstants);

    using var audioInput = AudioConfig.FromWavFileInput(@"C:\temp\emilie_wav.wav", audioProcessingOptions);

    var config = SpeechConfig.FromSubscription(subKey, serviceRegion);
    config.SpeechRecognitionLanguage = "fr-FR";
    config.OutputFormat = OutputFormat.Detailed;

    var recognizer = new SpeechRecognizer(config, audioInput);

    recognizer.SessionStarted += (s, e) =>
    {
        Console.WriteLine("Session started.");
    };

    recognizer.Canceled += (s, e) =>
    {
        Console.WriteLine($"CANCELED: Reason={e.Reason}");

        if (e.Reason == CancellationReason.Error)
        {
            // NOTE: In case of an error, do not use the same recognizer for recognition anymore.
            Console.Error.WriteLine($"CANCELED: ErrorCode={e.ErrorCode}");
            Console.Error.WriteLine($"CANCELED: ErrorDetails=\"{e.ErrorDetails}\"");
        }
    };

    var result = await recognizer.RecognizeOnceAsync().ConfigureAwait(false);

    Console.WriteLine(result);

    return result.ToString();
}
```

The 'subKey' and the 'serviceRegion' come from the Speech Studio infos as you can see there:

![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/46789044/6ef4f330-fd3c-419c-84a5-ae90ff465d87)

But I always get an Authentication Error:

> WebSocket upgrade failed: Authentication error (401). Please check subscription information and region name. SessionId: xxxxxx

Am I missing something ? 

Thank you in advance for any tips or help

**Comment by pankopon** [comment]
Hi, looks like you are possibly trying to use Azure Speech Services with an Azure OpenAI subscription/resource, while you really need to have a Speech resource: https://portal.azure.com/#create/Microsoft.CognitiveServicesSpeechServices
Please check the resource type, then use some simple pre-made quickstart/sample for testing like https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/dotnetcore/from-microphone

**Comment by Soappiness** [comment]
@pankopon that was it, I created a Azure Speech Services ressource and now it works!

It's a little confusing that in Speech Studio it only shows my Azure OpenAI ressources and the button "Show code examples on GutHub" leads to the Speech SDK. Maybe I must have missed the line in the README that explains the necessity of the Speech Services Ressource.

Thank you for your help!

**Comment by pankopon** [comment]
Closed as resolved, please open a new issue if more support is needed.
