### ISSUE TITLE
Playstation 4/5 compliant native library

### ISSUE THREAD

**Issue by dschwarz-tripp** [Azure-Samples/cognitive-services-speech-sdk#2289]
**Is your feature request related to a problem? Please describe.**
We would like to use this to enable cross platform speech recognition for our VR app (without having to leverage OS level STT for every OS)

**Describe the solution you'd like**
I have rolled out applications with CSC SDK before and I like it for a variety of reasons, but one thing I'm wary about is PSVR2 support (since it's a primary platform for us)

**Describe alternatives you've considered**
An alternative would be to run whisper or some other local model but that has compute cost.

**Additional context**
It would be nice if the CSC team could explore the lift in building the native libraries targeting the PS platforms, or maybe you guys already have and can share?

**Comment by pankopon** [comment]
Hi, according to information available in public, the PlayStation 4 system software is based on FreeBSD. Presumably 5 is similar.

Adding support for a new platform is a significant ask and it is not currently in plans. It would require a large demand and/or a large enough customer that this could be considered. If you think your company would meet the bar, please let us know and I can connect you with our PMs for further discussion.

To note, the original FreeBSD system does provide [Linux binary compatibility](https://docs.freebsd.org/en/books/handbook/linuxemu/). But we are not aware of anyone ever trying to (successfully) use the Speech SDK with it, and not sure if PlayStation 4/5 even includes the capability.

For cross platform real-time SR, would [Node.js](https://learn.microsoft.com/azure/ai-services/speech-service/quickstarts/setup-platform?pivots=programming-language-javascript) be an option?

**Comment by dschwarz-tripp** [comment]
Understood, I appreciate your response and consideration! I don't think we are nearly big enough (100kish users) to warrant that consideration, maybe in the near future. Unfortunately, we're Unity based, with a fairly complicated C# codebase (and more inhouse C# talent than anything else) so it would be nice to stick with C# SDKs. Will probably go the whisper route then. Thanks for checking!

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
