### ISSUE TITLE
Azure Avatar - Azure Communication Services Network Traversal (TURN) will be retired on 31 March 2024 

### ISSUE THREAD

**Issue by Stevenwa1te** [Azure-Samples/cognitive-services-speech-sdk#2298]
Please can you update as to how we would use the Avatar service once Azure Communication Services Network Traversal (TURN) will be retired on 31 March 2024 – transition to an external service to avoid disruption.

**Comment by mohammadkhanTEKenable** [comment]
> Please can you update as to how we would use the Avatar service once Azure Communication Services Network Traversal (TURN) will be retired on 31 March 2024 – transition to an external service to avoid disruption.

I have the same question..

**Comment by SteveW117** [comment]
This demo seems to have been updated to remove dependency on this service:

https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/browser/avatar

**Comment by pankopon** [comment]
Closed as resolved since updated samples are available, ref. commit https://github.com/Azure-Samples/cognitive-services-speech-sdk/commit/1ede838ff53407f36c6845c6b21cb8e5610e30e3 for change details.
