### ISSUE TITLE
[Unity] Cannot build on VR Daydream

### ISSUE THREAD

**Issue by dyoxyne** [Azure-Samples/cognitive-services-speech-sdk#230]
**Describe the bug**

With Unity 2018.3, I tried to use the Speech SDK with [Google Daydream SDK](https://github.com/googlevr/gvr-unity-sdk). I got `FileNotFoundException: Could not find file "\csharp-unity\Temp\StagingArea\assets\bin\Data\Managed\tempStrip\netstandard.dll"` when I tried to build.

**To Reproduce**
1. Add [Google Daydream SDK](https://github.com/googlevr/gvr-unity-sdk)
2. Add Speech SDK
3. Build

**Expected behavior**
I expect to be able to build and run Speech SDK on VR Daydream.

**Version of the Cognitive Services Speech SDK**
1.5.0

**Platform, Operating System, and Programming Language**
 - OS: Android (Daydream)

**Comment by BrianMouncer** [comment]
I've not seen this before, but I've also never tried to use our APIs with the Daydream VR SDK.
As a quick sanity check, I just rebuild our quick start sample targeting both Pie and Oreo without any problem, even if I checked "Virtual Reality Supported" in player properties, and selected "Daydream SDK".

Can you try this [speech quick start](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/csharp-unity/README.md), especially the "Import the Speech SDK" and "Build and run the sample for Android platform" sections? assuming that works for you, can you then add the Daydream SDK and see if you still have the same issues? 

If you still hit the same issue, reply back with more detail on the error you see and the players setting you are using (like minimum and target api level, XR and AR settings).

**Comment by dyoxyne** [comment]
This is what I tried:

1. Load quickstart/csharp-unity in Unity 2018.3
2. Import Speech SDK
=> Build to Android: **OK**
3. In Player Settings / XR Settings, check Virtual Reality Supported and add Daydream in Virtual Reality SDKs
=> Build to Android: **OK**
4. Import Google Daydream SDK
=> Build to Android: **Not OK**
`FileNotFoundException: Could not find file "\csharp-unity\Temp\StagingArea\assets\bin\Data\Managed\tempStrip\netstandard.dll"`
5. In `HelloWorld.cs`, comment everything inside `ButtonClick()`: no use of classes from `Microsoft.CognitiveServices.Speech`
=> Build to Android: **OK**

I didn't change the settings so they are the same defined by the quickstart project.
If you need more information & test from me, let me know.

**Comment by jhakulin** [comment]
Thanks for reporting the issue. We have not verified the Unity Android support with Google Daydream SDK, we will investigate.

**Comment by jhakulin** [comment]
@dyoxyne I tried to repro on Unity 2018.3.11f1, 
1. Imported latest Google VR SDK from here https://github.com/googlevr/gvr-unity-sdk/releases
2. Imported latest Speech SDK (1.6.0)
3. Enabled Unity script which uses Speech SDK
Android builds OK, runtime used: Mono

Let me know is there something I do differently or are you able to repro the issue still ?

**Comment by wolfma61** [comment]
no feedback - closing
