### ISSUE TITLE
 Error code: 4429. Error details: The request is throttled because you have exceeded the concurrent request limit allowed for your sub USP state: TurnStarted. Received audio size: 0 bytes.

### ISSUE THREAD

**Issue by Raciel-c** [Azure-Samples/cognitive-services-speech-sdk#2305]
I use F0 price, but I don't have 20 frequencies per minute, why do I keep reporting 4429 errors

 Error code: 4429. Error details: The request is throttled because you have exceeded the concurrent request limit allowed for your sub USP state: TurnStarted. Received audio size: 0 bytes.

**Comment by yulin-li** [comment]
@Kerry-LinZhang please help to triage.

@Raciel-c could you share a result id when you got throttled?

**Comment by Raciel-c** [comment]
I probably know the reason, maybe 0.5million characters per month used up, I applied for other areas, can run, thank you
