### ISSUE TITLE
CompressedStreamsSample demo crash

### ISSUE THREAD

**Issue by dragonbattlesun** [Azure-Samples/cognitive-services-speech-sdk#2310]
**IN ORDER TO ASSIST YOU, PLEASE PROVIDE THE FOLLOWING:**

- Speech SDK log taken from a run that exhibits the reported issue. 
See [instructions on how to take logs](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging).

- A stripped down, simplified version of your source code that exhibits the issue. Or, preferably, try to reproduce the problem with one of the public samples in this repository (or a minimally modified version of it), and share the code.

- If relevant, a WAV file of your input audio.

- Additional information as shown below

**Describe the bug**
The CompressedStreamsSample is currently non-functional.
**To Reproduce**

1: Pull the project from Git.
2: Open the CompressedStreamsSample project in iOS.
3: Compile the GStreamerWrapper.framework.
4: After running CompressedStreamsSample, the application crashes upon clicking the "Recognize from MP3 file" button.

**Expected behavior**

**Version of the Cognitive Services Speech SDK**

Which version of the SDK are you using.
The SDK version in the demo project.
**Platform, Operating System, and Programming Language**

 - OS: iOS
 - Hardware - ARM64
 - Programming language: Objective-C

**Additional context**

 - Error messages, stack trace
 2024-03-22 10:22:44.938996+0800 CompressedStreamsSample[26650:2301738] Exception caught in core: Exception with an error code: 0x29 (SPXERR_GSTREAMER_NOT_FOUND_ERROR)
[CALL STACK BEGIN]

3   MicrosoftCognitiveServicesSpeech    0x0000000101b50f24 GetModuleObject + 30772
4   MicrosoftCognitiveServicesSpeech    0x0000000101b98bdc GetModuleObject + 324844
5   MicrosoftCognitiveServicesSpeech    0x0000000101b98534 GetModuleObject + 323140
6   MicrosoftCognitiveServicesSpeech    0x0000000101b95608 GetModuleObject + 311064
7   MicrosoftCognitiveServicesSpeech    0x0000000101b9580c GetModuleObject + 311580
8   MicrosoftCognitiveServicesSpeech    0x00000001019f790c recognizer_create_speech_recognizer_from_config + 3964
9   MicrosoftCognitiveServicesSpeech    0x00000001019f6a38 recognizer_create_speech_recognizer_from_config + 168
10  MicrosoftCognitiveServicesSpeech    0x0000000101b10330 pal_string_to_wstring + 699704
11  MicrosoftCognitiveServicesSpeech    0x0000000101b0f098 pal_string_to_wstring + 694944

12  MicrosoftCognitiveServicesSpeech    0x0000000101b0dc74 pal_string_to_wstring + 689788
13  CompressedStreamsSample             0x0000000100924770 -[ViewController recognizeFromMP3File] + 460
14  CompressedStreamsSample             0x0000000100924534 __51-[ViewController recognizeFromMP3FileButtonTapped:]_block_invoke + 36
15  libdispatch.dylib                   0x0000000101554520 _dispatch_call_block_and_release + 32
16  libdispatch.dylib                   0x0000000101556038 _dispatch_client_callout + 20
17  libdispatch.dylib                   0x0000000101558b60 _dispatch_queue_override_invoke + 1052
18  libdispatch.dylib                   0x000000010156a43c _dispatch_root_queue_drain + 408
19  libdispatch.dylib                   0x000000010156ae34 _dispatch_worker_thread2 + 196
[CALL STACK END]
2024-03-22 10:22:44.940024+0800 CompressedStreamsSample[26650:2301738] speechRecoImpl is nil in speech recognizer destructor
2024-03-22 10:22:44.940300+0800 CompressedStreamsSample[26650:2301738] *** Terminating app due to uncaught exception 'SPXException', reason: 'Exception with an error code: 0x29 (SPXERR_GSTREAMER_NOT_FOUND_ERROR)
[CALL STACK BEGIN]

3   MicrosoftCognitiveServicesSpeech    0x0000000101b50f24 GetModuleObject + 30772
4   MicrosoftCognitiveServicesSpeech    0x0000000101b98bdc GetModuleObject + 324844
5   MicrosoftCognitiveServicesSpeech    0x0000000101b98534 GetModuleObject + 323140
6   MicrosoftCognitiveServicesSpeech    0x0000000101b95608 GetModuleObject + 311064
7   MicrosoftCognitiveServicesSpeech    0x0000000101b9580c GetModuleObject + 311580
8   MicrosoftCognitiveServicesSpeech    0x00000001019f790c recognizer_create_speech_recognizer_from_config + 3964
9   MicrosoftCognitiveServicesSpeech    0x00000001019f6a38 recognizer_create_speech_recognizer_from_config + 168
10  MicrosoftCognitiveServicesSpeech    0x0000000101b10330 pal_string_to_wstring + 699704
11  MicrosoftCognitiveServicesSpeech    0x0000000101b0f098 pal_string_to_wstring + 694944
12  MicrosoftCognitiveServicesSpeech    0x0000000101b0dc74 pal_string_to_wstring + 689788
13  CompressedStreamsSample             0x0000000100924770 -[ViewController recognizeFromMP3File] + 460
14  CompressedStreamsSample             0x0000000100924534 __51-[ViewController recognizeFromMP3FileButtonTapped:]_block_invoke + 36
15  libdispatch.dylib                   0x0000000101554520 _dispatch_call_block_and_release + 32
16  libdispatch.dylib                   0x0000000101556038 _dispatch_client_callout + 20
17  libdispatch.dylib                   0x0000000101558b60 _dispatch_queue_override_invoke + 1052
18  libdispatch.dylib                   0x000000010156a43c _dispatch_root_queue_drain + 408
19  libdispatch.dylib                   0x000000010156ae34 _dispatch_worker_thread2 + 196
[CALL STACK END]

'
*** First throw call stack:
(0x1a950ccb4 0x1a25ac3d0 0x1a9679c6c 0x101b0f978 0x101b0dc74 0x100924770 0x100924534 0x101554520 0x101556038 0x101558b60 0x10156a43c 0x10156ae34 0x20933dda0 0x20933db7c)
libc++abi: terminating due to uncaught exception of type NSException

**Comment by BrianMouncer** [comment]
That exception usually indicate that either GStreamer or the wrapper framework was not found by the SDK in the deployed application.

Have you followed the steps in the compressed audio sample readme?  Specifically, not only compile the gstreamer wrapper framework... but also include both the speech SDK framework, and the gstreamer wrapper framework with your application, and deploy them with your application. The framework wrapper also needs to be compiled with the "Generic iOS Device target", not for a specific platform...

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/objective-c/ios/compressed-streams/README.md

**Comment by pankopon** [comment]
Closed as answered and no further response from the customer in 3 weeks.
