### ISSUE TITLE
Please add support to use MicrosoftCognitiveServicesSpeech.xcframework using Swift Package Manager.

### ISSUE THREAD

**Issue by klolage** [Azure-Samples/cognitive-services-speech-sdk#2311]
**Is your feature request related to a problem? Please describe.**
I did not see if we can link _MicrosoftCognitiveServicesSpeech.xcframework_ using SPM in my app. I do not want to use cocoa pods or link a downloaded XCFramework (every new version would need downloading it again)

**Describe the solution you'd like**
Please provide support for Swift Package Manager for iOS and Mac developers so we can link the framework as swift package.

**Comment by juliencampy** [comment]
Agreed

**Comment by rhurey** [comment]
Hello, and thank you for reaching out with your feature request!

We understand that integrating Speech SDK through Swift Package Manager (SPM) would be beneficial for iOS and Mac developers, providing a more streamlined and convenient approach.

While we can't provide a specific timeline for adding SPM support, we greatly appreciate your suggestion and have taken note of it. Community feedback, upvotes, and support play a significant role in helping us prioritize our work and make improvements to the SDK. We encourage other developers to chime in and express their interest in this feature, as this will help us understand the demand and prioritize accordingly.

Once again, thank you for your valuable input, and please feel free to share any additional ideas or concerns you may have.

**Comment by pankopon** [comment]
Internal work item ref. 7044008. No ETA.

**Comment by pankopon** [comment]
Closing the issue since we actually have a backlog item about this that was created 2 years ago - and there isn't any faster resolution expected in the near future... If this does get planned for release at some point, we'll update status here.

**Comment by ruofeilyu** [comment]
Please support SPM, make it to be Priority number one
