### ISSUE TITLE
Recording immediately ends after starting

### ISSUE THREAD

**Issue by StefanNikolovXR** [Azure-Samples/cognitive-services-speech-sdk#2312]
Hey guys, I'm using the Cognitive Services SDK for Unity (2022.3.11f1). I used to be able to use speech-to-text, but this last week whenever I try to toggle it, the recording immediately ends. I haven't made any changes to the speech code, so I'm honestly not sure what's causing the issue. I've attached my relevant code below:

    private void Awake()
    {
#if PLATFORM_ANDROID
            // Request to use the microphone, cf.
            // https://docs.unity3d.com/Manual/android-RequestingPermissions.html
            //_message = "Waiting for mic permission";
            if (!Permission.HasUserAuthorizedPermission(Permission.Microphone))
            {
                Permission.RequestUserPermission(Permission.Microphone);
            }
#elif PLATFORM_IOS
            if (!Application.HasUserAuthorization(UserAuthorization.Microphone))
            {
                Application.RequestUserAuthorization(UserAuthorization.Microphone);
            }
#endif

        _mainThreadContext = SynchronizationContext.Current;

        SpeechConfig _config = SpeechConfig.FromSubscription(_subscriptionKey, _serviceRegion);
        _config.EnableDictation();
        _config.SetProperty(PropertyId.Speech_SegmentationSilenceTimeoutMs, _silencePauses.ToString());
        _config.SetProperty(PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs, silenceInitial.ToString());
        _config.SetProperty(PropertyId.SpeechServiceConnection_EndSilenceTimeoutMs, _silenceFinal.ToString());

        _recognizer = new SpeechRecognizer(_config);
    }

    private void OnEnable()
    {
        _dictationSO.OnStartRecording += StartRecording;
        _dictationSO.OnRecordingEnded += StopRecording;
    }

    private void OnDisable()
    {
        _dictationSO.OnStartRecording -= StartRecording;
        _dictationSO.OnRecordingEnded -= StopRecording;
        StopRecording();
    }

    private void OnDestroy()
    {
        _recognizer.Dispose();
    }

    private void StartRecording()
    {
        _recognizer.Recognizing += RecognizingHandler;
        _recognizer.Recognized += RecognizingHandler;

      //  _recognizer.Canceled += CancelRecognizeHandler;
        _recognizer.SessionStopped += SessionStoppedRecognizingHandler;
        _recognizer.SpeechEndDetected += SpeechEndedRecognizeHandler;

        _recognizer.StartContinuousRecognitionAsync().ConfigureAwait(false);
    }

    private void StopRecording()
    {
        _recognizer.Recognizing -= RecognizingHandler;
        _recognizer.Recognized -= RecognizingHandler;

       // _recognizer.Canceled -= CancelRecognizeHandler;
        _recognizer.SessionStopped -= SessionStoppedRecognizingHandler;
        _recognizer.SpeechEndDetected -= SpeechEndedRecognizeHandler;

        _recognizer.StopContinuousRecognitionAsync().ConfigureAwait(false);
    }

    private void CancelRecognizeHandler(object s, SpeechRecognitionCanceledEventArgs e)
    {
        _mainThreadContext.Post(state =>
        {
            _dictationSO.RecordingEnded();
        }, null);
    }

    private void RecognizingHandler(object sender, SpeechRecognitionEventArgs e)
    {
        _mainThreadContext.Post(state =>
        {
            _dictationSO.Recording(e.Result);
        }, null);
    }

    private void SessionStoppedRecognizingHandler(object sender, SessionEventArgs e)
    {
        _dictationSO.RecordingEnded();
    }

    private void SpeechEndedRecognizeHandler(object sender, RecognitionEventArgs e)
    {
        _dictationSO.RecordingEnded();
    }
    
    using Microsoft.CognitiveServices.Speech;
using System;
using UnityEngine;

[CreateAssetMenu(menuName = "ScriptableObject/DictationSO")]
public class DictationSO : ScriptableObject
{
    public Action OnStartRecording { get; set; }

    public Action<SpeechRecognitionResult> OnRecording { get; set; }

    public Action OnRecordingEnded { get; set; }

    public void StartRecording()
    {
        OnStartRecording?.Invoke();
    }

    public void Recording(SpeechRecognitionResult speechRecognitionResult)
    {
        OnRecording?.Invoke(speechRecognitionResult);
    }

    public void RecordingEnded()
    {
        Debug.Log("Recording ended");
        OnRecordingEnded?.Invoke();
    }
}

Any assistance would be greatly appreciate! I've been tearing my hair out trying to troubleshoot.

**Comment by rhurey** [comment]
Hey, thanks for using the Speech SDK, sorry there's a problem...

The Cancelled event is going to have the best source of information if the call to StartContinuousRecogniton doesn't throw an exception. In particular the [SpeechRecognitionCanceledEventArgs ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechrecognitioncanceledeventargs?view=azure-dotnet) class. There's a sample [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/561b86e6d0310e0c068015e51ca45690107527a7/samples/csharp/unity/speechrecognizer/Assets/SpeechSDKSample/Scripts/SpeechRecognition.cs#L236) that gets error information.

**Comment by StefanNikolovXR** [comment]
Hey, thanks for the response! I just wanted to update you guys, the issue seems to be fixed now. I haven't changed anything in terms of the code so I imagine it was a problem with the API itself? Regardless, it all seems good now so I will close the issue.
