### ISSUE TITLE
mstts:backgroundaudio stop after first message/language

### ISSUE THREAD

**Issue by doumhfr** [Azure-Samples/cognitive-services-speech-sdk#2313]
Hi,

I'm trying to use TTS with audio in background

but the music stop after first lang

It should continue until the end

<speak version="1.0" xml:lang="en-US" xmlns:mstts="http://www.w3.org/2001/mstts">
  <mstts:backgroundaudio src="https://www.url.com/test.wav" />
  <voice name="fr-FR-VivienneMultilingualNeural">
  <lang xml:lang="fr-FR">Message en francais.</lang>
  <lang xml:lang="en-US">Message in english.</lang>
 </voice
</speak>

the music stop at the end of message en francais, and the message in english is played without music

**Comment by yulin-li** [comment]
@Kerry-LinZhang could you help to triage?

**Comment by Kerry-LinZhang** [comment]
Hi @doumhfr this is not supported by TTS team, let me contact certain team for certain respond.

**Comment by Kerry-LinZhang** [comment]
Under investigation

**Comment by Kerry-LinZhang** [comment]
Hi @doumhfr Following up on the issue reported, we tried on voice AvaNeural, but cannot repro it, would you mind providing us the voice you used, and if possible, the ssml on it?
