### ISSUE TITLE
support 48khz raw opus

### ISSUE THREAD

**Issue by reg31** [Azure-Samples/cognitive-services-speech-sdk#2314]
Hi,

It would be nice to have audio-48khz-16bit-48kbps-mono-opus format.

Thank you

**Comment by yulin-li** [comment]
we can add a 48kHz opus format, but 48kbps is somehow low to keep the quality.

**Comment by pankopon** [comment]
@yulin-li Will you create a work item for this request? Please update status if this is accepted for implementation.

**Comment by yulin-li** [comment]
I created and work item and the internal id is 11690. The work item is in backlog now. I am closing the issue here to avoid duplicated tracking and will update the status once it's done.

**Comment by reg31** [comment]
How can I query this format? Is this available?
