### ISSUE TITLE
Getting Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED wss://eastus.stt.speech.microsoft.com/speech/universal/v2

### ISSUE THREAD

**Issue by zubairkhanmzk** [Azure-Samples/cognitive-services-speech-sdk#2320]
**IN ORDER TO ASSIST YOU, PLEASE PROVIDE THE FOLLOWING:**

- Speech SDK log taken from a run that exhibits the reported issue. 

- A stripped down, simplified version of your source code that exhibits the issue. Or, preferably, try to reproduce the problem with one of the public samples in this repository (or a minimally modified version of it), and share the code.
- https://github.com/mjg123/twilio-media-streams-x-azure-cognitive-services-speech/blob/finished-project/src/main/java/com/example/twilio/mediastreamsazuretranscription/TwimlRestController.java

- Additional information as shown below

**Describe the bug**
I am trying to run azure speech sdk to stream realtime audio from twilio and feed to azure through websockets. And this example works on my Macbook M2 pro. But when I am running on my Azure VM it does not transcribe. The transcription is empty for now.

**To Reproduce**
Just run java code.

**Expected behavior**
Get transcription.

**Version of the Cognitive Services Speech SDK**

Which version of the SDK are you using.
1.36.0

**Platform, Operating System, and Programming Language**

 - OS: Ubuntu 20.04 - please be specific
 - Hardware - x64
 - Programming language: Java

- Additional details
`$ openssl version -d
OPENSSLDIR: "/usr/lib/ssl"`

`$ nslookup eastus.stt.speech.microsoft.com
<emtpy no output>
`

**Comment by rhurey** [comment]
Thanks for getting in touch with the problem you're having...

The connection failed because the socket didn't connect in 10 seconds.
```
[662403]: 10035ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  socketio_berkeley.c:683 Failure: poll failure, retval 0, errno 0.
```

Typically this winds up being a network configuration problem between the host and the Speech Service. The lack of response from nslookup is unexpected.

To help narrow down the number of moving parts, can you try this curl command?
```
curl -v https://eastus.stt.speech.microsoft.com/api/v1.0/languages/recognition
```
That should print a list of ISO language codes and will validate the VM->Service connection is fine.

**Comment by zubairkhanmzk** [comment]
`$ curl -v https://eastus.stt.speech.microsoft.com/api/v1.0/languages/recognition
*   Trying 20.42.6.167:443...
* TCP_NODELAY set
* connect to 20.42.6.167 port 443 failed: Connection timed out
* Failed to connect to eastus.stt.speech.microsoft.com port 443: Connection timed out
* Closing connection 0
curl: (28) Failed to connect to eastus.stt.speech.microsoft.com port 443: Connection timed out`

**Comment by rhurey** [comment]
Thanks for the additional info.

Can the VM access other destinations not in the Azure data center? Amazon.com, google.com, etc?

This seems to be a problem with the networking setup in the VM.

**Comment by zubairkhanmzk** [comment]
`$ curl www.google.com
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for."`

Yes, it can access outside our vnet.

**Comment by zubairkhanmzk** [comment]
I fixed this issue. I was required to create private endpoint on azure as we were using vnets on VM and speech service.
