### ISSUE TITLE
AI model behind ConversationTranscriber

### ISSUE THREAD

**Issue by vpszi** [Azure-Samples/cognitive-services-speech-sdk#2325]
Can you tell me which AI model is used in the background when using the [ConversationTranscriber](https://learn.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.transcription.conversationtranscriber?view=azure-dotnet) class from the [Quickstart: Create real-time diarization](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/get-started-stt-diarization?pivots=programming-language-csharp&tabs=windows) sample?

Does it use the Whisper model from OpenAI?

**Comment by pankopon** [comment]
Hi, it's not Whisper. Unfortunately, further model details are not public.
