### ISSUE TITLE
Roadmap about this SDK and the Batch Transcription functionality

### ISSUE THREAD

**Issue by pistocop** [Azure-Samples/cognitive-services-speech-sdk#2327]
Hello,
I would like to inquire about the integration of the "[Batch Transcription](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/batch-transcription-create?pivots=rest-api)" feature, primarily for Python, as I couldn't find any information online regarding this matter.

Currently, this feature is intended for use directly via the REST API ([official documentation](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/)), and it's not integrated into the SDK. 
Is there any plan to integrate it into the SDK in the future? If so, has a release date been scheduled?

Thank you!

**Comment by pankopon** [comment]
Hi, there is no plan to support batch transcription directly in the Speech SDK.
(If necessary, you could achieve corresponding functionality by adding logic in the application that uses the SDK.)

Batch transcription using the REST API is literally meant for batch processing whereas the Speech SDK is for real-time use cases, they are very different scenarios.
