### ISSUE TITLE
How to output subtitle files when converting text to speech?

### ISSUE THREAD

**Issue by dnlzsy** [Azure-Samples/cognitive-services-speech-sdk#2328]
How to output subtitle files when converting text to speech?

**Comment by yulin-li** [comment]
we have `wordboundary` events, you can construct the subtitle file based on it. e.g., https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechSynthesisSamples.java#L704

**Comment by dnlzsy** [comment]
thanks.

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.

**Comment by dnlzsy** [comment]
> we have `wordboundary` events, you can construct the subtitle file based on it. e.g., https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechSynthesisSamples.java#L704

Thanks！
