### ISSUE TITLE
Output audio use loopback device

### ISSUE THREAD

**Issue by kj54321** [Azure-Samples/cognitive-services-speech-sdk#2329]
Hi team,
 
I am trying to leverage sdk text to speech feature, however the audio output is not working by defult sample on Ubuntu desktop when using loopback device.

My current audio configuration is using snd-aloop to loop all audio to a loopback device and then push audio stream to ffmpeg with an airplay speaker. It works well under system level and other applications(chrome, music app etc.) 

Audio config as below

```
aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC289 Analog [ALC289 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Loopback [Loopback], device 0: Loopback PCM [Loopback PCM]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 1: Loopback [Loopback], device 1: Loopback PCM [Loopback PCM]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
Steps to reproduce
1. Initialize lookback device
`modprobe snd-aloop pcm_substreams=1
`
2.  push audio stream to airplay speaker
 `ffmpeg -hide_banner -loglevel panic -f alsa -channels 2 -sample_rate 44100 -i hw:Loopback,1,0 -c:ffmpeg -hide_banner -loglevel panic -f ala libmp3lame -b:a 320k -f mp3 - | atvremote --manual --address x.x.x.x --port 7000 --protocol raop --id aa:aa:aa:aa set_volume=80 stream_file=-`
3.  Everything works fine except running synthesis text to speech [quickstart.py](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/python/text-to-speech/quickstart.py) is not playable to airplay speaker.

I also notice there is [speech_config](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/d804b10f5577605cb6b27e0b601155a2f67d719d/quickstart/python/text-to-speech/quickstart.py#L16) to customize the output, however I did not find any detailed documentation. So please advise further. 
Your kindly help will be much appreciated.

**Comment by pankopon** [comment]
Hi, what is the output of `aplay -L`? If it shows your loopback device, try the following code
```
device_config = speechsdk.audio.AudioOutputConfig(use_default_speaker=False, device_name="YourLoopbackDeviceName")
speech_synthesizer = speechsdk.SpeechSynthesizer(speech_config, device_config)
```
where `YourLoopbackDeviceName` is the device name from `aplay -L` output. This is similar to choosing a specific input device, ref. https://learn.microsoft.com/azure/ai-services/speech-service/how-to-select-audio-input-devices#audio-device-ids-on-linux

**Comment by pankopon** [comment]
Closed since configuration instructions have been provided.
