### ISSUE TITLE
StartContinuousRecognitionAsync Not Working on Windows 7 x86

### ISSUE THREAD

**Issue by RodrigoRVieira** [Azure-Samples/cognitive-services-speech-sdk#233]
**Describe the bug**
While using StartContinuousRecognitionAsync on Windows 7, the connection to the Cognitive server suddenly dies during start.

Was able to trace the error using SDK 1.4+:

_(893): 5203ms SPX_TRACE_ERROR: AZ_LOG_ERROR: WS open operation failed with result=8(WS_OPEN_ERROR_INVALID_BYTES_RECEIVED_ARGUMENTS), code=998[0x000003e6]
(893): 5204ms SPX_TRACE_ERROR: Error: File:D:\a\1\s\source\core\usp\transport.cpp Func:?OnWSOpened@@YAXPAXU_WS_OPEN_RESULT_DETAILED@@@Z Line:422 
(893): 5204ms SPX_TRACE_INFO: AZ_LOG_INFO: TS:1223, TransportError: connection:0x6304a8, reason=2, code=8 [0x00000008], string=998
(893): 5204ms SPX_DBG_TRACE_VERBOSE: Response: On Error: Code:5, Message: **Connection failed (no connection to the remote host). Internal error: 8. Error details: 998. Please check network connection, firewall setting, and the region name used to create speech factory**.._

**To Reproduce**
1. Start a new Console project targeting 4.6.2 Framework
2. Add a Nuget reference to Microsoft.CognitiveServices.Speech v1.3.1. (Newer releases throws a CreateFile2 entrypoint missing on Kernel32"

3.

```
SpeechConfig speechConfig = SpeechConfig.FromSubscription(
                ConfigurationManager.AppSettings["Microsoft.SubscriptionKey"],
                ConfigurationManager.AppSettings["Microsoft.ServiceRegion"]);

speechConfig.SpeechRecognitionLanguage = "pt-BR";

SpeechRecognizer speechRecognizer = new SpeechRecognizer(speechConfig);

speechRecognizer.Recognized += (sender, recognitionResult) =>
{
                Console.WriteLine($"{recognitionResult.Result.Text}");
};

await speechRecognizer.StartContinuousRecognitionAsync().ConfigureAwait(false);
```
4. Target platform: x86

**Expected behavior**
Sentences being recognized as it does while running on Windows 10

**Version of the Cognitive Services Speech SDK**
1.0.0~1.5.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 7 Enterprise x68 7601 SP1
 - Hardware - Core i7-7700HQ
 - Programming language: C#

**Exactly same code works flawlessly on Windows 10 build 1903**

**Comment by mahilleb-msft** [comment]
I'm sorry, @RodrigoRVieira -- Windows 7 is not a supported platform for the Speech SDK.
Please checkout https://docs.microsoft.com/azure/cognitive-services/speech-service/ for the platform support matrix.

Best, Mark

**Comment by RodrigoRVieira** [comment]
You have no plans on opening this component? Perhaps we (the community) can make it compatible.

**Comment by chrisbasoglu** [comment]
we do have plans to open-source this component.  in ~2-3 months.

**Comment by amkorousagi** [comment]
i have similar problem but my OS is Ubuntu 18.04.3 LTS. what is problem?


Say something...
Speech Recognition canceled: CancellationReason.Error
Error details: Connection failed (no connection to the remote host). Internal error: 1. Error details: -2. Please check network connection, firewall setting, and the region name used to create speech factory.

**Comment by gabser10** [comment]
Hi, is this sdk now compatible in windows 7?

**Comment by IllidanS4** [comment]
Any progress?

**Comment by chrisbasoglu** [comment]
Unfortunately, we have not been able to prioritize compatibility with Windows 7 yet.

**Comment by mrx23dot** [comment]
There should be an older version that supports win7
this is from 2011 https://stackoverflow.com/questions/5813746/microsoft-speech-api-installation

**Comment by mrx23dot** [comment]
This one works great, no dependency, only REST API:
https://github.com/mediatechlab/tts-wrapper
