### ISSUE TITLE
Where can I request for embedded speech translation models? 

### ISSUE THREAD

**Issue by yujinqiu** [Azure-Samples/cognitive-services-speech-sdk#2330]
From the [doc](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/swift/ios/embedded-speech/models/ST),  I visit   https://aka.ms/embedded-speech 

> For embedded speech, you need to download the speech recognition models for [speech to text](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/speech-to-text) and voices for [text to speech](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/text-to-speech).

on the page, I can only find Speech to text and text to speech model, where is speech translation model ?

**Comment by pankopon** [comment]
Hi, please see the important note in https://aka.ms/embedded-speech:

> Microsoft limits access to embedded speech. You can apply for access through the Azure AI Speech [embedded speech limited access review](https://aka.ms/csgate-embedded-speech). For more information, see [Limited access for embedded speech](https://learn.microsoft.com/en-us/legal/cognitive-services/speech-service/embedded-speech/limited-access-embedded-speech?context=/azure/ai-services/speech-service/context/context).

After your application for access to embedded speech is reviewed and approved, you will get information on how to download models.
