### ISSUE TITLE
Unity SpeechSDK VisionOS compatibility

### ISSUE THREAD

**Issue by blanxdev** [Azure-Samples/cognitive-services-speech-sdk#2331]
Is there a chance that the SpeechSDK will be compiled for Apple VisionOS?
Tried to enable the iOS library for VisionOS, but that did not work.

**Comment by pankopon** [comment]
Hi, this has been asked before in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1990

We have a work item on the backlog but there is no plan for it at the moment.
