### ISSUE TITLE
API ttv unable to create audio fro SSML with '&'

### ISSUE THREAD

**Issue by Sirorezka** [Azure-Samples/cognitive-services-speech-sdk#2332]
Hello,

Sorry for bothering, I think I've encountered a bug with the Azure speech kit. Basically one of multilingual voices can't pronounce "&" sign. I'm doing direct requests to Azure API using following Python script:

```
      tts_endpoint = "https://eastus.tts.speech.microsoft.com/cognitiveservices/v1".format(
          AZURE_REGION
      )

    header = {
        "X-Microsoft-OutputFormat": out_audio_format,
        "Content-Type": "application/ssml+xml",
        "Ocp-Apim-Subscription-Key": AZURE_KEY,
        "User-Agent": "spoken_app",
    }

    ssml_string = """
    <speak version="1.0" 
    xmlns="http://www.w3.org/2001/10/synthesis" 
    xml:lang="en-GB"
    xmlns:mstts="https://www.w3.org/2001/mstts">
        <voice name="en-US-AvaMultilingualNeural">
                Jack & Jones
        </voice>
    </speak>
    """

    async with httpx.AsyncClient(timeout=timeout) as client:
        res = await client.post(url=tts_endpoint, data=ssml_string, headers=header)
```

In return from the server I recieve:
`http code 400; with msg - b''`

However if I replace '&' with 'and' I get a valid audio back. Any thoughts on this? Thank you.

**Comment by trrwilson** [comment]
Hello!

Just as a hunch, could you try escaping the ampersand character by using `&amp;` instead? `&` is one of the few reserved characters in XML and, in the absence of any caller-based sanitization logic, that may be causing an early document processing error.

**Comment by Sirorezka** [comment]
Hello @trrwilson,

Thanks, replacing '&' with '&amp;' worked. Thank you!

**Comment by duanjun** [comment]
If the word boundary event is used, then the words and character entities inside are all split, and the sentence types are also incorrect.

**Comment by pankopon** [comment]
Closed as resolved. @duanjun Please create a new issue on a different topic.
