### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'play') at chat.js

### ISSUE THREAD

**Issue by tsharma15kpmg** [Azure-Samples/cognitive-services-speech-sdk#2334]
My avatar is not constantly speaking as in sometimes it works and sometimes it does not. When it does not work, I do have written replies on my chat area however the avatar does not speak.

Uncaught TypeError: Cannot read properties of null (reading 'play') at chat.js

**Comment by ralph-msft** [comment]
Closing out this issue since it is not actionable.
