### ISSUE TITLE
sample_speech.py crashes

### ISSUE THREAD

**Issue by Jake-Breaks-Stuff** [Azure-Samples/cognitive-services-speech-sdk#234]
OS: Windows 10
Running python 3.7.0

I have 3 different wav files in the same folder as _speech_sample.py_, and the other files from _cognitive-services-speech-sdk/samples/python/console/_. When I run for _speech_sample.py_ from _main.py_, any time **speech_recognizer** is used, the program crashes without any kind of error messages.

I have the wav file swapped in at the top of the code, _main.py_ recognizes that I've selected the method from _speech_sample.py_, and using print statements, I've narrowed down the issue of crashing to **speech_recognizer** being used.

For example, in **speech_recognize_once_from_file()**, I use my 5 second long wav file, and the moment the program reaches **result = speech_recognizer.recognize_once()**, it crashes.
Result: **You selected: <function speech_recognize_once_from_file at 0x0000024979A91378>** followed by immediate termination of program.

With a longer wav file loaded, I tried **speech_recognize_continuous_from_file()**, 
The moment the program reached **speech_recognizer.start_continuous_recognition()**, it crashed again. 
I verified this by placing **print("checkpoint1")** before speech_recognizer and **print("checkpoint2")** after speech_recognizer. Checkpoint1 was the only print statement to reach the terminal.  

I checked the error handling (more print statements) from main, and determined the program never reaches it.

Steps to reproduce:
1. Clone files from _cognitive-services-speech-sdk/samples/python/console/_.
2. Add in your keys and endpoints.
3. Place a wav file in the folder all the source code is located in.
4. Set **weatherfilename** to the name of your wav file.
5. Run main, and select any of the **speech_recognize..._from_file** options.
6. Main says you've selected: <**speech_recognize..._from_file** at [object reference to the wav file>
7. Program crashes without any error messages.
![Speech_output](https://user-images.githubusercontent.com/41161508/57321956-cf057900-70d8-11e9-852b-f89a508bdd0e.png)

**Comment by chlandsi** [comment]
Hi,

to help finding the problem, could you share one of the files you are experiencing problems with? Also, could you post the debug log, which you can enable by calling `config.set_property(speechsdk.PropertyId.Speech_LogFilename, "logfile.log")` after initializing the SpeechConfig instance? Also, which version of the SDK are you using (`speechsdk.__version__`)?

Thanks!

**Comment by Jake-Breaks-Stuff** [comment]
The SDK version number is **1.5.0** according to the output. I've included a zip folder with the longer wav file, and the log file.
[Requested files.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/3157034/Requested.files.zip)

**Comment by amitkumarshukla** [comment]
@Jake-Breaks-Stuff I was able to transcribe the file after converting it to 16bit, 16 KHZ mono, little endian format. Please use goldwav to convert the file and it will surely solve your issue.

**Comment by amitkumarshukla** [comment]
[Lemon_rant_converted.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/3506848/Lemon_rant_converted.zip)

**Comment by amitkumarshukla** [comment]
Try with the above file and it will be transcribed

**Comment by Jake-Breaks-Stuff** [comment]
About three months too late, but I appreciate the effort,
