### ISSUE TITLE
Could not initialize class com.microsoft.cognitiveservices.speech.SpeechConfig

### ISSUE THREAD

**Issue by yangman92** [Azure-Samples/cognitive-services-speech-sdk#2340]
[Install the Speech SDK](https://learn.microsoft.com/zh-cn/azure/ai-services/speech-service/quickstarts/setup-platform?tabs=linux%2Cubuntu%2Cdotnetcli%2Cdotnet%2Cjre%2Cmaven%2Cnodejs%2Cmac%2Cpypi&pivots=programming-language-java)
[Configure RHEL/CentOS 7](https://learn.microsoft.com/zh-cn/azure/ai-services/speech-service/how-to-configure-rhel-centos-7)
All the steps above the two links I've done and I was seeking the same issues on github all of them i've been try to but all of them didn't work on me.

I've been trying to solve this problem for almost 2 days.
On my local server it worked but It didn't work on centos 7 server.
Could you please tell me which step i was doing wrong. 
Tanks a lot.

I attacked files below.

system: CentOS 7.9.2009 x86_64(Py3.7.9)
error: 
- java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.cognitiveservices.speech.SpeechConfig
- java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V

**Comment by yangman92** [comment]
step: Configure RHEL/CentOS 7
![1](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/108913829/0fa6a4a4-3468-4eca-9690-8a49309608d6)
![2](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/108913829/6fe81b19-0526-491b-a653-fd2ccce5ead2)
![3](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/108913829/0d4e025b-5299-4ddc-a93e-bbf5ebaf424d)
![4](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/108913829/1b4f9d80-2b4a-44c9-aa70-574b95755c52)
![5](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/108913829/a881fa75-8b0c-486a-81f4-318dcab43b4f)
![6](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/108913829/32e7e65d-0242-44c5-a9cd-c474670b0c0f)
![7](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/108913829/fcc568e0-d74d-4c79-b5ea-fa3c5e357944)
![8](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/108913829/491dc9b5-7646-4b68-bc52-b1a0f2e33051)
![9](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/108913829/5a6b79ca-0c9d-4e7c-a034-d2db87f2bfe0)
![10](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/108913829/46fc420d-7b77-48b7-a547-4407a31235fa)

**Comment by yangman92** [comment]
step:Install the Speech SDK![11](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/108913829/77623b06-82a7-414e-af5d-cf0de016dffd)

**Comment by pankopon** [comment]
@yangman92 Your screenshots show **errors** while trying to build gcc 7.5.0 and runtimes, therefore newer C/C++ runtime libraries required by the Speech SDK were not installed. Looks like you may have already tried to run a build before the screenshots, so it's best to start anew with a clean build. I just verified that instructions in https://learn.microsoft.com/azure/ai-services/speech-service/how-to-configure-rhel-centos-7#cc-compiler-and-runtime-libraries still work on an up-to-date CentOS 7.9.2009 system. Please do not run any commands blindly - check and verify that they complete successfully, otherwise investigate why they failed.

For Java on CentOS 7, see https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1769 for an earlier similar question. (Regarding the Speech SDK version used in the example, note that the current latest is 1.37.0.)

Please note that CentOS 7 will reach **end of life** on **June 30, 2024**: https://www.redhat.com/en/topics/linux/centos-linux-eol
The Speech SDK support for it will be dropped shortly after.

**Comment by yangman92** [comment]
@pankopon Hi. This time I am sure that I correctly done the 2 steps.

```
# Build GCC 7.5.0 and runtimes and install them under /usr/local
curl https://ftp.gnu.org/gnu/gcc/gcc-7.5.0/gcc-7.5.0.tar.gz -O
tar -xf gcc-7.5.0.tar.gz
mkdir gcc-7.5.0-build && cd gcc-7.5.0-build
../gcc-7.5.0/configure --enable-languages=c,c++ --disable-bootstrap --disable-multilib --prefix=/usr/local
make -j$(nproc)
sudo make install-strip
```
These commands were executed successfully. The info was so long to print.
But it still did not work.
I don't know what I can do else.
All the same issues I tried to understand but I am still confusing.

![1713272011079](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/108913829/631364ea-bd3f-4b47-9d5d-f18ce763d9b0)

I can provide more information you want to see.

**Comment by pankopon** [comment]
@yangman92 Here's a command-line example from scratch, presuming you have all dependencies already in place.

Verify that the new compiler (and therefore also the updated C/C++ runtime libraries) is indeed installed:
```
# which gcc
/usr/local/bin/gcc
# gcc --version
gcc (GCC) 7.5.0
```
Clone and prepare the Speech SDK sample repository:
```
# git clone https://github.com/Azure-Samples/cognitive-services-speech-sdk
# cd cognitive-services-speech-sdk/samples/java/jre/console/
# sed -i 's/1\.34\.0/1.37.0/g' pom.xml
# git diff
diff --git a/samples/java/jre/console/pom.xml b/samples/java/jre/console/pom.xml
index 56059d2..de8de3a 100644
--- a/samples/java/jre/console/pom.xml
+++ b/samples/java/jre/console/pom.xml
@@ -56,7 +56,7 @@
     <dependency>
       <groupId>com.microsoft.cognitiveservices.speech</groupId>
       <artifactId>client-sdk</artifactId>
-      <version>1.34.0</version>
+      <version>1.37.0</version>
     </dependency>
     <dependency>
       <groupId>jakarta.json</groupId>
```
Try for example the case with wav file input.
Edit the source file `src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java` and find `continuousRecognitionWithFileAsync()` in that file and replace "*Your...*" strings with your subscription key, service region, and some wav file path.

In the following, `mvn` was downloaded from https://maven.apache.org/download.cgi (`apache-maven-3.9.6-bin.zip`).
(CentOS 7 has only a very old version of `mvn`, like many other programs.)
Extract the package under `/opt` and add `/opt/apache-maven-3.9.6/bin` to `PATH` like
```
# export PATH=/opt/apache-maven-3.9.6/bin:$PATH
# mvn --version
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /opt/apache-maven-3.9.6
Java version: 1.8.0_402, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.402.b06-1.el7_9.x86_64/jre
```
You can use Java 8 or newer, but make sure both java and javac have the same version and you don't have multiple versions conflicting with each other:
```
# yum list installed | grep jdk
copy-jdk-configs.noarch                 3.3-11.el7_9                   @updates
java-1.8.0-openjdk.x86_64               1:1.8.0.402.b06-1.el7_9        @updates
java-1.8.0-openjdk-devel.x86_64         1:1.8.0.402.b06-1.el7_9        @updates
java-1.8.0-openjdk-headless.x86_64      1:1.8.0.402.b06-1.el7_9        @updates

# java -version
openjdk version "1.8.0_402"
OpenJDK Runtime Environment (build 1.8.0_402-b06)
OpenJDK 64-Bit Server VM (build 25.402-b06, mixed mode)

# javac -version
javac 1.8.0_402
```
Now build, verify that the correct Speech SDK version is used, and run the sample:
```
# mvn clean package
...
[INFO] BUILD SUCCESS

# mvn dependency:tree
...
[INFO] SpeechSDKDemo:SpeechSDKDemo:jar:0.0.1-SNAPSHOT
[INFO] +- com.microsoft.cognitiveservices.speech:client-sdk:jar:1.37.0:compile

# export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH
# java -jar ./target/SpeechSDKDemo-0.0.1-SNAPSHOT-jar-with-dependencies.jar
 1. Speech recognition with microphone input.
 2. Speech recognition with microphone input and detailed recognition results
 3. Speech recognition in the specified language.
 4. Speech recognition using customized model.
 5. Speech continuous recognition using events with file.
...
Your choice (0: Stop): 5

    Session started event.

RECOGNIZING: Text=what's the weather
RECOGNIZING: Text=what's the weather like
RECOGNIZED: Text=What's the weather like?
CANCELED: Reason=EndOfStream

    Session stopped event.
```
If this really doesn't work for you then it seems your CentOS 7 installation/environment is somehow different from what is should be.

**Comment by yangman92** [comment]
It is not easy to deploy on a centos system.
You need to do 3 steps.
Some issues did not clearly show what the problem is or less steps.

[Install the Speech SDK](https://learn.microsoft.com/zh-cn/azure/ai-services/speech-service/quickstarts/setup-platform?tabs=linux%2Cubuntu%2Cdotnetcli%2Cdotnet%2Cjre%2Cmaven%2Cnodejs%2Cmac%2Cpypi&pivots=programming-language-java)
[Configure RHEL/CentOS 7](https://learn.microsoft.com/zh-cn/azure/ai-services/speech-service/how-to-configure-rhel-centos-7)
[Download and extract the Speech SDK](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/cpp/linux/from-microphone)

My friend helped me today to deploy. It worked now.

**Comment by jpalvarezl** [comment]
Thank you for the update. I will close the issue now since it seems like the discussion reached its conclusion. Feel free to open this issue again if there is some more questions related to this topic.

**Comment by songlinyu-hub** [comment]
> 在 centos 系统上部署并不容易。 你需要做 3 步。 有些问题没有清楚地显示问题是什么或步骤较少。
> 
> [安装语音 SDK](https://learn.microsoft.com/zh-cn/azure/ai-services/speech-service/quickstarts/setup-platform?tabs=linux%2Cubuntu%2Cdotnetcli%2Cdotnet%2Cjre%2Cmaven%2Cnodejs%2Cmac%2Cpypi&pivots=programming-language-java) [配置 RHEL/CentOS 7](https://learn.microsoft.com/zh-cn/azure/ai-services/speech-service/how-to-configure-rhel-centos-7) [下载并解压语音 SDK](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/cpp/linux/from-microphone)
> 
> 今天我的朋友帮我部署了。现在可以正常工作了。

是哪一个环节出了问题？我检查了以上步骤都执行了，仍然没有解决？

**Comment by songlinyu-hub** [comment]
> 在centos 系统上安装并不容易。 你需要做3步。 有些问题没有明确表明问题是什么或步骤较少。
> 
> [安装语音SDK](https://learn.microsoft.com/zh-cn/azure/ai-services/speech-service/quickstarts/setup-platform?tabs=linux%2Cubuntu%2Cdotnetcli%2Cdotnet%2Cjre%2Cmaven%2Cnodejs%2Cmac%2Cpypi&pivots=programming-language-java) [配置 RHEL/CentOS 7](https://learn.microsoft.com/zh-cn/azure/ai-services/speech-service/how-to-configure-rhel-centos-7) [下载并解压语音SDK](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/cpp/linux/from-microphone)
> 
> 今天我的朋友帮我安装了。我们现在收到了。

请问是哪个环节出了问题？我检查了以上步骤都执行了，仍然没有解决

**Comment by yangman92** [comment]
> > 在centos 系统上安装并不容易。 你需要做3步。 有些问题没有明确表明问题是什么或步骤较少。
> > [安装语音SDK](https://learn.microsoft.com/zh-cn/azure/ai-services/speech-service/quickstarts/setup-platform?tabs=linux%2Cubuntu%2Cdotnetcli%2Cdotnet%2Cjre%2Cmaven%2Cnodejs%2Cmac%2Cpypi&pivots=programming-language-java) [配置 RHEL/CentOS 7](https://learn.microsoft.com/zh-cn/azure/ai-services/speech-service/how-to-configure-rhel-centos-7) [下载并解压语音SDK](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/cpp/linux/from-microphone)
> > 今天我的朋友帮我安装了。我们现在收到了。
> 
> 请问是哪个环节出了问题？我检查了以上步骤都执行了，仍然没有解决

我用的是宝塔面板，如果使用面板上的启动是会有问题，加载不到sdk，我使用了另外一种方法，使用命令行启动程序。nohup java -jar -Xmx1024M -Xms256M /www/wwwroot/java/project.jar --server.port=8088 > /home/project.txt 2>&1 &
