### ISSUE TITLE
Does cognitive services speech sdk for python support async await functions?

### ISSUE THREAD

**Issue by hmthang96** [Azure-Samples/cognitive-services-speech-sdk#2343]
I tried to read all docs in the azure speech for python, but I could find anything ralate to asyn await. 
Does the SDK STT for python has any async await method like google STT or Openai STT?

**Comment by jpalvarezl** [comment]
Hi @hmthang96 thank you for the question.

The SDK does not expose the methods directly. But you can easily wrap the ones you need using the async framework of your choice. Here is an example using `asyncio` modifying one of our samples:

```python
import asyncio
import azure.cognitiveservices.speech as speechsdk

speech_key, service_region = "YourSubscriptionKey", "YourServiceRegion"
speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)

# Set the voice name, refer to https://aka.ms/speech/voices/neural for full list.
speech_config.speech_synthesis_voice_name = "en-US-AvaMultilingualNeural"

# Creates a speech synthesizer using the default speaker as audio output.
speech_synthesizer = speechsdk.SpeechSynthesizer(speech_config=speech_config)

async def synthesize_speech(text):
    # Synthesizes the received text to speech.
    # The synthesized speech is expected to be heard on the speaker with this line executed.
    result = speech_synthesizer.speak_text_async(text).get()

    # Checks result.
    if result.reason == speechsdk.ResultReason.SynthesizingAudioCompleted:
        print("Speech synthesized to speaker for text [{}]".format(text))
    elif result.reason == speechsdk.ResultReason.Canceled:
        cancellation_details = result.cancellation_details
        print("Speech synthesis canceled: {}".format(cancellation_details.reason))
        if cancellation_details.reason == speechsdk.CancellationReason.Error:
            if cancellation_details.error_details:
                print("Error details: {}".format(cancellation_details.error_details))
        print("Did you update the subscription info?")

async def request_user_input():
    print("Type some text that you want to speak...")
    text = input()
    return text

async def print_work_start():
    print("Start working...")

async def print_work_end():
    print("Work ending...")


async def main():
    text = await request_user_input()

    await asyncio.create_task(print_work_start())

    await asyncio.create_task(synthesize_speech(text))

    await asyncio.create_task(print_work_end())

asyncio.run(main())
```

**Comment by hmthang96** [comment]
Hi @jpalvarezl. thank you for your help
"I use the speechsdk.SpeechSynthesizer and I'm trying to wrap it like you did for this line: result = speech_recognizer.start_continuous_recognition_async().get(). However, it seems that the result always returns 'None'.


I'm running a task to recognize about 50 to 300 audios per minute. If I use a callback function, it works normally but it runs sequentially, which I don't prefer. So, I'm looking for direct asynchronous methods."

`async def pronunciation_assessment_continuous_from_file(speech_config: speechsdk.SpeechConfig,
                                                        candidate_object: candidate_information.CandidateInformation,
                                                        audio_bytes: bytes, reference_text: str):
    try:
        audio_config = speechsdk.audio.AudioConfig(stream=await convert_any_audio_files_to_stream(audio_bytes))
        print(f"reference_text: {reference_text}")
        enable_miscue = True
        enable_prosody_assessment = False
        pronunciation_config = speechsdk.PronunciationAssessmentConfig(
            grading_system=speechsdk.PronunciationAssessmentGradingSystem.HundredMark,
            granularity=speechsdk.PronunciationAssessmentGranularity.Phoneme,
            enable_miscue=enable_miscue)
        pronunciation_config.reference_text = reference_text
        pronunciation_config.phoneme_alphabet = 'IPA'
        pronunciation_config.nbest_phoneme_count = 3

        if enable_prosody_assessment:
            pronunciation_config.enable_prosody_assessment()

        language = 'en-US'
        speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, language=language,
                                                       audio_config=audio_config)
        # endregion
        pronunciation_config.apply_to(speech_recognizer)
        result = speech_recognizer.start_continuous_recognition_async().get()
        await asyncio.sleep(10)
        speech_recognizer.stop_continuous_recognition_async()
        print(result)`

Here is my code

**Comment by hmthang96** [comment]
after few hours, I find a way to fix this.  using asyncio.to_thread to wrap future_result class. It won't block the main threads anymore ;D
