### ISSUE TITLE
es-ES Not show phoneme

### ISSUE THREAD

**Issue by hiddow** [Azure-Samples/cognitive-services-speech-sdk#2345]
**Is your feature request related to a problem? Please describe.**
Currently, Azure Speech Assessment provides valuable insights into pronunciation accuracy, but it can be challenging for language learners focusing on Spanish (es-ES) to pinpoint the exact phonemes where they may be struggling.  Detailed phoneme-level feedback would significantly enhance the learning process.

**Describe the solution you'd like**
I would like Azure Speech Assessment to include a detailed breakdown of the output at the phoneme level for Spanish (es-ES) assessments. This would involve:

Individual Phoneme Scores: Assign accuracy ratings (e.g., Correct, Substitution, Deletion, Insertion) to each phoneme within the assessed text.
Visual Representation: Provide a clear visual representation of this breakdown, potentially highlighting problematic phonemes for quick identification.

**Describe alternatives you've considered**
Manual Phonetic Analysis: It's possible to manually transcribe the audio using the International Phonetic Alphabet (IPA) and compare against a reference, but this is extremely time-consuming and requires specialized knowledge.
Third-Party Tools: There are some limited phonetic analysis tools, but integrating this functionality within Azure's suite would be far more streamlined.

**Additional context**
Detailed phoneme-level feedback has the potential to greatly benefit:

Spanish Language Learners: Allows users to target specific areas of pronunciation difficulty, leading to more focused and effective practice.
Language Instructors: Provides actionable data for lesson planning and individualized pronunciation guidance.

<img width="1341" alt="image" src="https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/8944374/18922586-0d98-4864-9535-a8fce7aaf450">

**Comment by jpalvarezl** [comment]
Hello @hiddow thank you for using the SDK. As you may be aware currently `es-ES` is not part of the [supported languages for this feature](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-pronunciation-assessment?pivots=programming-language-javascript#supported-features-per-locale).

I will notify the feature team for this area to review the issue and they will evaluate, given their current roadmap and resources, whether this can be moved into active development.

**Comment by yulin-li** [comment]
@wangkenpu could you check?

**Comment by wangkenpu** [comment]
It's by design. 
For new feature requests, please fill [Microsoft Forms](https://forms.office.com/pages/responsepage.aspx?id=v4j5cvGGr0GRqy180BHbR7yq_YbJ2b9IuYylLZw63tZUN1FURE9GNUZZRTZEUlJCRjNCOVZURDVDVS4u). After you submit the form, our team will contact you in 2 weeks.

**Comment by pankopon** [comment]
Closed as by design.

**Comment by fabswt** [comment]
People really like getting pronunciation feedback on Gliglish.com for en-US (I'm using Azure's Pronunciation Assessment), but I cannot extend it to more languages without phoneme-level data.

It's a little absurd to offer phoneme-level scores without phoneme-level data.

I submitted a response to the form mentioned above.

**Comment by NashIlli** [comment]
+1
