### ISSUE TITLE
iOS about  SPXAudioStreamFormat

### ISSUE THREAD

**Issue by hold-my-hand** [Azure-Samples/cognitive-services-speech-sdk#235]
/**
  * Initialize the audio stream format object with the specified PCM waveformat characteristics.
  * @param samplesPerSecond sample rate, in samples per second (Hertz).
  * @param bitsPerSample bits per sample, typically 16.
  * @param channels number of channels in the waveform-audio data. Monaural data uses one channel and stereo data uses two channels.
  * @return an instance of audio stream format.
  */
- (nullable instancetype)initUsingPCMWithSampleRate:(NSUInteger)samplesPerSecond bitsPerSample:(NSUInteger)bitsPerSample channels:(NSUInteger)channels;

#pragma mark 音频质量通过此参数调整
-(AudioStreamBasicDescription)audioStreamBasicDescription{
    AudioStreamBasicDescription asbd;
    memset(&asbd, 0, sizeof(asbd));
    asbd.mSampleRate = 16000;            //采样率
    asbd.mFormatID = kAudioFormatLinearPCM;
    asbd.mFormatFlags = kLinearPCMFormatFlagIsSignedInteger | kAudioFormatFlagIsPacked;
    asbd.mChannelsPerFrame = 1;         //单声道
    asbd.mFramesPerPacket = 1;          //每一个packet一侦数据
    asbd.mBitsPerChannel = 16;          //每个采样点16bit量化
    asbd.mBytesPerFrame = (asbd.mBitsPerChannel / 8) * asbd.mChannelsPerFrame;
    asbd.mBytesPerPacket = asbd.mBytesPerFrame ;
    return asbd;
}

-(SPXPushAudioInputStream *)inputStream{
    if (!_inputStream) {
        NSUInteger mSampleRate =  self.record.audioStreamBasicDescription.mSampleRate;
        NSUInteger bitsPerSample = self.record.audioStreamBasicDescription.mBitsPerChannel;
        NSUInteger channels = self.record.audioStreamBasicDescription.mChannelsPerFrame;
        
        SPXAudioStreamFormat *format  =[[SPXAudioStreamFormat alloc] initUsingPCMWithSampleRate:mSampleRate bitsPerSample:bitsPerSample channels:channels];
        
        _inputStream = [[SPXPushAudioInputStream alloc] initWithAudioFormat:format];
    }
    return _inputStream;
}

I want to provide more clear audio data. Can these two parameters in SPXAudioStream Format initialization be changed?

**Comment by zhouwangzw** [comment]
Do you want to use different mSampleRate or bitsPerSample? You can do that by providing correct SPXAudioStreamFormat.  However, 16KHz 16bit audio should be sufficient for speech recognition. Background noise or SNR could affect recognition accuracy more than sample rate and frequency. 

Currently, SDK only supports single channel (mono) though.

Thanks,
Zhou

**Comment by hold-my-hand** [comment]
OK
