### ISSUE TITLE
ServiceTimeout: USP error: timeout waiting for the first audio chunk

### ISSUE THREAD

**Issue by sc-nm** [Azure-Samples/cognitive-services-speech-sdk#2354]
Hi,

**Describe the bug**
I encountered a strange issue with the java SDK when doing basic things with `synth.SpeakText()`, but only on a specific envionment . Lately, in most of the calls (about 9/10 times), it takes around ~2 minutes for the method to return, and I get the above USP error as response. After that, it takes another ~10 minutes for the AudioConfig and the SpeechSynthesizer to close (leaving a try-with-resources block). In the other 1/10 cases a successful response is received fast.

**To reproduce**
This is basically the code that is used, but I could not reproduce it on other environments:

```
public boolean check(String key, String region) {
  SpeechConfig speechCfg = SpeechConfig.fromSubscription(key, region);
  try(AudioConfig audioCfg = AudioConfig.fromStreamOutput(AudioOutputStream.createPullStream());
      SpeechSynthesizer synth = new SpeechSynthesizer(speechCfg, audioCfg)) {
    SpeechSynthesisResult res = synth.SpeakText("");
    ResultReason reason = res.getReason();
    if(ResultReason.SynthesizingAudioCompleted.equals(reason)) {
      return true;
    } else if(ResultReason.Canceled.equals(reason)) {
      SpeechSynthesisCancellationDetails details = SpeechSynthesisCancellationDetails.fromResult(res);
      LOG.error("Speech check failed: {}: {}", details.getErrorCode(), details.getErrorDetails());
    } else {
      LOG.warn("unhandled result reason: {}", reason);
    }
  }
  return false;
}
```

**Expected behavior**
No USP error

**Version of the Cognitive Services Speech SDK**
Speech SDK 1.37.0

**Platform, Operating System, and Programming Language**
 - OS: centos:centos8 docker image on an oracle linux server 8.8 host
 - Programming language: Java 11

**Additional context**
 - Error messages: ServiceTimeout: USP error: timeout waiting for the first audio chunk
 - I added two speech SDK debug log files: one of a timeout scenario and one of a success scenario (on the exact same environment and config):
   - [speech_timeout.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/15106683/speech_timeout.log)
   - [speech_success.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/15106682/speech_success.log)
 - I already checked with tcpdump if there is anything blocked on the network. At least, in an error case, I can see packages going from/to some microsoft IP, so it is probably not a network issue.
 - When I run the same code locally on my windows 10 machine using the same config and key and region, I don't get those error responses, so it is probably not a subscription issue.

I am not sure if this is even a bug, but a few debugging hints would be helpful. In case any information is missing, please let me know.

Best regards

**Comment by ralph-msft** [comment]
From the log files, this appears to be a networking issue. From the speech_timeout.log we can see:
```
[994321]: 200ms SPX_TRACE_INFO:  web_socket.cpp:800 DoWork: open transport.
[994321]: 200ms SPX_TRACE_INFO:  web_socket.cpp:479 Start to open websocket. WebSocket: 0x55ead800, wsio handle: 0x55e71920
[994321]: 200ms SPX_TRACE_SCOPE_ENTER:  uws_web_socket.cpp:149 Open
```
But 40 seconds later, the web socket connection has still not been established and so the code times out:
```
[310589]: 40200ms SPX_TRACE_ERROR:  usp_tts_engine_adapter.cpp:307 USP error: timeout waiting for the first audio chunk
```


By comparison, the the success log, the web socket connection is established within a 100ms:
```
[199986]: 206ms SPX_TRACE_INFO:  web_socket.cpp:800 DoWork: open transport.
[199986]: 206ms SPX_TRACE_INFO:  web_socket.cpp:479 Start to open websocket. WebSocket: 0x99d8dc00, wsio handle: 0x99c1e7b0
...
[199986]: 243ms SPX_TRACE_SCOPE_EXIT:  uws_web_socket.cpp:149 Open
...
[199986]: 341ms SPX_TRACE_SCOPE_ENTER:  uws_web_socket.cpp:247 OnWebSocketOpened
[199986]: 341ms SPX_TRACE_INFO:  web_socket.cpp:880 Opening websocket completed. TransportRequest: 0x99d8dc00, wsio handle: 0x99c1e7b0, time: 2024-04-25T08:26:54.5582023Z

**Comment by sc-nm** [comment]
Hi,

thanks for the reply and the clearification. It still seems odd to me since the connection sometimes works in the exact same environment. But I don't know the details of the settings of the firewall that is being used in the data center. I will check that.

If you don't mind, I still have two further questions related to this issue:
- As you probably have noticed, the above code does a connectivity and subscription validity check during the startup of our application, which cannot operate in case this check fails. Is there any other way to check this properly?
- Is it possible to reduce the ~10 minute delay when closing the AudioConfig and SpeechSynthesizer?

Best regards

**Comment by sc-nm** [comment]
The issue still persists. Any idea how I can debug the sporadic serice timeout? And why does `com.microsoft.cognitiveservices.speech.util.SafeHandle.releaseSynthesizerHandle` take so long sometimes?

**Comment by nm-scordes** [comment]
The issue still exists. The question is, why the SDK sometimes does not send application data. The trace was made on the machine where the SDK is running, so no firewall etc. in between. Can please someone have a look at it?

**Comment by pankopon** [comment]
@sc-nm @nm-scordes 
> centos8

Sorry, but this environment is seriously out of support by now. Do you see the same issues with the current latest Speech SDK release (1.38.0) on [supported Linux distributions](https://learn.microsoft.com/azure/ai-services/speech-service/quickstarts/setup-platform?tabs=linux&pivots=programming-language-java#platform-requirements)? (Note, RHEL/CentOS 7 will be dropped very soon so do not try them.)

**Comment by pankopon** [comment]
Closed since CentOS 8 is not a supported Linux environment.
