### ISSUE TITLE
Session management 

### ISSUE THREAD

**Issue by vdharashive** [Azure-Samples/cognitive-services-speech-sdk#2355]
Please help me to understand how is session management needs to be done for asr , can I create a connection and keep it open through the call duration , 

Or open a session when its needed during call and close it once task is done, so using this method there would be 10 time open and close request.  

How is billing done in case of connection kept open throughout the call duration even if there bank audio sent

Please suggest some best practices

**Comment by ralph-msft** [comment]
I am not clear on what it is you are trying to do. By ASR do you mean Automatic Speech Recognition? What types of recognition do you plan to do?

I would suggest that you take a look at the Speech SDK documentation as that may provide the information you need:
* Speech recognition documentation: https://learn.microsoft.com/azure/ai-services/speech-service/speech-to-text
* Pricing information: https://azure.microsoft.com/pricing/details/cognitive-services/speech-services/

**Comment by pankopon** [comment]
Closed since no further updates, presumed resolved with the documentation provided.
