### ISSUE TITLE
Real-time speaker diarization doesn't seem to work for me

### ISSUE THREAD

**Issue by TDulka** [Azure-Samples/cognitive-services-speech-sdk#2360]
<img width="1248" alt="image" src="https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/26122417/9eb64cb8-4cdf-4503-8a42-1307b48d6379">

When testing in the Speech Studio I am seeing exactly the behavior that I am trying to get, as in the picture. Real time speaking into the microphone gets continually transcribed and chunks of text get real-time diarized.

I tried to follow the [quickstart guide on real-time diarization](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/get-started-stt-diarization?tabs=windows&pivots=programming-language-javascript), but if I run it what happens is that I only get the "TRANSCRIBED" logs after the whole audio is processed and I don't get the intermediate results. If I add a listener on `.transcribing` this successfully logs text as it is processed, but without attributing it to a specific speakerId (speakerId is undefined). See image from my terminal. You can also see that I get all the "Transcribing" events first and the "Transcribed" events only at the end of the whole audio.
<img width="1072" alt="image" src="https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/26122417/07341100-a1a6-437a-872d-dd43bba8f08a">

What I desire to see instead is what was shown in [this announcement of real-time diarization](https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/announcing-the-public-preview-of-real-time-diarization-in-azure/ba-p/3876802) where the transcribing events are interleaved with transcribed events once an utterance is identified.

I have searched the documentation and samples here, but seem to be unable to find anything on this. I am not sure if this is a bug or if I am missing some crucial piece of information. I would greatly appreciate any help! (I am using JavaScript)

**Comment by TDulka** [comment]
Okay, I figured things out. I just needed to do processing in the browser and use ConversationTranscriber with fromDefaultMicrophoneInput(), also used the authorization flow described here: https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/README.md#token-exchange-process

Example:
```
const audioConfig = SpeechSDK.AudioConfig.fromDefaultMicrophoneInput();
const speechConfig = SpeechSDK.SpeechConfig.fromAuthorizationToken(authorizationToken, region);
const transcriber = new SpeechSDK.ConversationTranscriber(speechConfig, audioConfig);
transcriber.transcribing = (sender, transcriptionEventArgs) => console.log("transcribing", transcriptionEventArgs.result)
transcriber.transcribed = (sender, transcriptionEventArgs) => console.log("transcribed", transcriptionEventArgs.result)
transcriber.startTranscribingAsync();
```

**Comment by pankopon** [comment]
Closed as resolved based on the latest comments.
