### ISSUE TITLE
Odd Syllables

### ISSUE THREAD

**Issue by BeastBlood1885** [Azure-Samples/cognitive-services-speech-sdk#2365]
I've noticed that, since around mid-March or so, the voices Andrew and Brian sound a bit odd when pronouncing certain syllables. 

Regarding Andrew:
I'm hearing short, high-pitched noises when he speaks. For example, in this recording, the noises can be heard three times - when he says the words "tree", "shrub", and the first instance of the word "genus": https://vocaroo.com/11r2L3lf5irE

Four more can be heard in this example, with the words "branches," "ratios", "shoots" and once more with the word "tree": https://vocaroo.com/1bV1OtNn9nqd

They happen often enough that it rather distracts from whatever he's reading about, especially when reading an article about pines as he seems to particularly struggle with the word "tree". I hear the click every time he says that word.

I am using earbuds connected to a Sound Blaster Z card and hear the noises no matter what options I turn on or off in my sound settings, if that helps any.

Regarding Brian: 
To be honest, I'm not sure if my problem with him is caused by a bug or if it's an intended change, but in case it is the former, my issue is that his overall quality seems to have lowered since the update around mid-March or so. He sounds a lot less lively and his speaking rate seems inconsistent. More importantly, it seems like he now puts rather strong emphasis on certain consonants/syllables, which makes them stick out a bit oddly from the rest of his speech. 

It's more noticeable when his pitch is lowered, which is incidentally how I like to listen to him.

Here is a comparison between his old version and the updated one. The first one was recorded in the middle of October, and the second I recorded just now.

Before: https://vocaroo.com/1gsErjQ2e4eA
After: https://vocaroo.com/13pBRlZK88PX

The words "called" and "require" kind of "spike" from the rest of the words in the second sample, whereas they're perfectly subtle and in-line with the rest in the first one so as to not be distracting.

Here's another short sample to further explain what I mean: https://vocaroo.com/1i7IkSsxkkbo

He pronounces the gr- and cr- sounds of the words "great" and "crimson" too strongly, which again makes them stick out oddly from the rest of the speech, where the rest of what is said is said more softly and consistently.

Regarding his speaking rate, I've noticed that he tends to switch from talking a bit too slowly (as in the "after" sample I posted) to speaking downright too fast without me ever changing his speaking rate, which again makes me unsure of the changes to him being intentional or not.

**Comment by Kerry-LinZhang** [comment]
Hi @BeastBlood1885 Thanks for your feedback, shall we have the script of the audio example you mention in the feedback for further checking?

**Comment by BeastBlood1885** [comment]
> Hi @BeastBlood1885 Thanks for your feedback, shall we have the script of the audio example you mention in the feedback for further checking?

Sure! I'll provide the text for each sample. Also, terribly sorry for getting back to you so late; I hadn't seen any notifications somehow.

The first two are bits of text from Wikipedia's article about pine trees. 

First:
A pine is any conifer tree or shrub in the genus Pinus of the family Pinaceae. Pinus is the sole genus in the subfamily Pinoideae.

Second: 
The spiral growth of branches, needles, and cones scales are arranged in Fibonacci number ratios. The new spring shoots are sometimes called "candles"; they are covered in brown or whitish bud scales and point upward at first, then later turn green and spread outward. These "candles" offer foresters a means to evaluate soil fertility and vigour of the trees.

The third is some quest text from World of Warcraft:
Heroes of the Horde, I bring news. The Dragon Isles are awakening! The Isles went dormant in the wake of the Sundering. But now, at long last, they have called my kin and I home. While the Isles hold many wonders, it is also a perilous land. We will require the aid of our mortal allies to reclaim our legacy. I am about to present the Aspects' invitation to the Horde Council in Orgrimmar. Meet me there and we shall see what they have to say.

The last one is just part of some text I wrote for a roleplaying game:
And those eyes, like great, crimson torches, alight with terrible anger and recognition.

**Comment by BeastBlood1885** [comment]
I don't hear the squeaky noises anymore with the new update to Andrew.

And I didn't see anything about Brian in the release notes on the Azure site, but I could swear he sounds a bit more lively. He still sounds funny when saying the words "great", "crimson", "creature", "require" (basically anything with that hard c sound), but that's more nitpicking than pointing out bugs.

Thanks. :)
