### ISSUE TITLE
macOS: calling `SpeechSynthesizer.StopSpeakingAsync()` and then `StartSpeakingTextAsync()` does not work immediately

### ISSUE THREAD

**Issue by bpasero** [Azure-Samples/cognitive-services-speech-sdk#2367]
**Describe the bug**

A call to `SpeechSynthesizer.StopSpeakingAsync()` with a new `StartSpeakingTextAsync` does not synthesise for up to 30 seconds. The log file is here: [log.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/15231083/log.txt)

This issue maybe related to https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2350 and https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1836 and https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2264

**To Reproduce**

We are building a node.js binding for Speech SDK and the C++ sources mimic the samples. The synthesis is implemented here: https://github.com/microsoft/node-speech/blob/967976ce0f4887a2b5b27f486e5209a51588516f/src/main.cc#L477

The call to `StopSpeakingAsync` here: https://github.com/microsoft/node-speech/blob/967976ce0f4887a2b5b27f486e5209a51588516f/src/main.cc#L539

To reproduce from that module:
* using node.js `18.x` on the system
* `git clone https://github.com/microsoft/node-speech.git`
* open `index.ts` and append the snippet [1] at the end
* from a terminal cd into the workspace and run `npm i`
* run `node index.js`

[1]

```ts
const t = createSynthesizer({
  modelPath: '<path to TTS model>',
  modelName: 'Microsoft Server Speech Text to Speech Voice (en-US, AriaNeural)',
  modelKey: '<model key>',
}, (error, result) => {
  if (error) {
    console.error(error);
  } else {
    console.log(result);
  }
});
t.synthesize(`
Now more than ever, developers are expected to build voice-enabled applications that can reach a global audience. With the same voice persona across languages, organizations can keep their brand image more consistent. To support the growing need for a single voice to speak multiple languages, particularly in scenarios such as localization and translation, a multi-lingual neural TTS voice is brought out in public preview.
`);
setTimeout(() => {
  console.log('stopping');
  t.stop();
}, 2000);
setTimeout(() => {
  console.log('synthesizing');
  t.synthesize(`This text is not synthesized`);
}, 3000);
```

**Expected behavior**

Calling `SpeechSynthesizer.StopSpeakingAsync` immediately stops synthesis and `StartSpeakingTextAsync` works right after. 

**Version of the Cognitive Services Speech SDK**

`1.37.0`

**Platform, Operating System, and Programming Language**

 - OS: macOS 14.4.1
 - Hardware: ARM
 - Programming language: C++

//cc @ralph-msft

**Comment by pankopon** [comment]
Closed as duplicate with the same cause as in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2350.
