### ISSUE TITLE
May has a bug in save_to_wav_file

### ISSUE THREAD

**Issue by panxin801** [Azure-Samples/cognitive-services-speech-sdk#2370]
Hello, I'm using azure tts servuce with python. When I finish one inference with speechsdk, and then I want to save to file, I get the following error.
![image](https://github.com/Azure-Samples/Cognitive-Speech-TTS/assets/30232283/545b5bb2-c435-4bb5-ad10-d71683f410bb)

stream is the picture return from the following  code
```python
if result.reason == speechsdk.ResultReason.SynthesizingAudioCompleted:
        if len(result.audio_data) == 0:
            raise ValueError('[ERROR] empty audio data.')
        else:
            stream = speechsdk.AudioDataStream(result)
            return stream
```

I meet the error this morning the first time, but I can't figure out what's wrong with this error. Thank you fir your reply.

**Comment by pankopon** [comment]
@yulin-li Can you check?

**Comment by yulin-li** [comment]
could you check if you have permission to create the file? e.g., if the parent folder exists and not read-only? Could you try to remove non-ascii characters in the file path and try again?

**Comment by panxin801** [comment]
> could you check if you have permission to create the file? e.g., if the parent folder exists and not read-only? Could you try to remove non-ascii characters in the file path and try again?

Thank you friends, it's solved. filename in some cases has problem, thanks a lot
