### ISSUE TITLE
How "customvoice" module to get?

### ISSUE THREAD

**Issue by koichino** [Azure-Samples/cognitive-services-speech-sdk#2373]
[personal_voice_sample.py](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/custom-voice/python/personal_voice_sample.py)

The code above shows that "import customvoice". However the module cannot be recognized.

I could install "azure-cognitiveservices-speech" based on [link](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/custom-voice/python) .
But  ["azure-cognitiveservices-speech"](https://learn.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech?view=azure-python) doesn't include "customvoice" module. 

Please update so that we can run the script to try out.

**Comment by ForrestGumb** [comment]
Did  you copy [customvoice](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/custom-voice/python/customvoice) folder, and put it besides [personal_voice_sample.py](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/custom-voice/python/personal_voice_sample.py)?
