### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='none.tts.speech.microsoft.com', port=443): Max retries exceeded with url: /cognitiveservices/avatar/relay/token/v1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BA41E47910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

### ISSUE THREAD

**Issue by hamzahjazi** [Azure-Samples/cognitive-services-speech-sdk#2374]
I've tried to test the Sample and I've entered the required Keys and endpoint but I got an error message says

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='none.tts.speech.microsoft.com', port=443): Max retries exceeded with url: /cognitiveservices/avatar/relay/token/v1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BA41E47910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by pankopon** [comment]
Closed since no further information provided.
