### ISSUE TITLE
Does the python voice avatar support arabic?

### ISSUE THREAD

**Issue by hamzahjazi** [Azure-Samples/cognitive-services-speech-sdk#2376]
whenever I try to speak in Arabic it can't recognize the Arabic language and answer me in different languages like chineese or german and if not how can I add the Arabic language ?

**Comment by pankopon** [comment]
Please see the documentation on [Avatar voice and language](https://learn.microsoft.com/azure/ai-services/speech-service/text-to-speech-avatar/what-is-text-to-speech-avatar#avatar-voice-and-language).

**Comment by pankopon** [comment]
Closed as answered.
