### ISSUE TITLE
Failed to Import speech SDK Python

### ISSUE THREAD

**Issue by prakash-lekkala** [Azure-Samples/cognitive-services-speech-sdk#238]
Hi,

I'm experimenting with speech SDK in python. After following all the steps mentioned in quick page 
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-python

quickstart.py code is failing to load **speechsdk** library. Please file the error message below

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-ceac8af4667b> in <module>()
----> 1 import azure.cognitiveservices.speech as speechsdk

~\AppData\Roaming\Python\Python36\site-packages\azure\cognitiveservices\speech\__init__.py in <module>()
      6 """
      7 
----> 8 from .speech import *
      9 from . import audio
     10 from . import intent

~\AppData\Roaming\Python\Python36\site-packages\azure\cognitiveservices\speech\speech.py in <module>()
      6 
      7 
----> 8 from . import speech_py_impl as impl
      9 from .audio import AudioConfig
     10 

ImportError: cannot import name 'speech_py_impl'

---------------------------
Please suggest what could have possible gone wrong.

I check the following:
- azure-cognitiveservices-speech is updated to the latest version
- "quickstart.py" & "quickstart.ipynb" are failing to import speechsdk

**Comment by chlandsi** [comment]
Did you install the package with `pip install azure-cognitiveservices-speech --user`? This is currently not possible. Please try to install without the `--user` flag.

**Comment by prakash-lekkala** [comment]
Hi Christian, 
Yes, I did install the package with <pip install azure-cognitiveservices-speech --user>. Its failing to install without the <--user> flag

**Comment by chlandsi** [comment]
In that case, a workaround should be to copy the files that get installed to `~\AppData\Roaming\Python\Lib\site-packages\azure\cognitiveservices\speech` to the directory `~\AppData\Roaming\Python\Python36\site-packages\azure\cognitiveservices\speech\`. Alternatively, you could try to experiment with a virtual environment. Sorry for the inconvenience; the next release will contain a fix for this problem.

**Comment by prakash-lekkala** [comment]
Thank you!!! this worked
