### ISSUE TITLE
No Batch Transcription Example using JavaScript

### ISSUE THREAD

**Issue by JamesEarle** [Azure-Samples/cognitive-services-speech-sdk#239]
Right now there are only samples on using the Batch Transcription API using C# and Python. It would be great if there were samples using other languages, specifically JavaScript.

**Comment by BrianMouncer** [comment]
Batch is based on a REST API, you don't need a language specific SDK.
You should be able to convert the existing examples to any language.

Here is a pointer to the Python example.

https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/python/from-blob

Brian.
