### ISSUE TITLE
How to Adjust "Speaking Style" for Neural Voices

### ISSUE THREAD

**Issue by jillbourque** [Azure-Samples/cognitive-services-speech-sdk#2392]
Is there a way to adjust the "Speaking Styles" in SSML for the Neural Voices like Andrew, similar to how it can be done for voices like Jason?

<img width="385" alt="Screenshot 2024-05-27 at 9 03 44 PM" src="https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/10834956/0e89dfe3-55b1-4d6e-a13b-0f50fb3f6372">

**Comment by telzhou618** [comment]
```python
# Define the SSML with the voice style parameters
ssml_string = """
<speak version='1.0' xmlns='http://www.w3.org/2001/10/synthesis' xmlns:mstts='http://www.w3.org/2001/mstts' xml:lang='zh-CN'>
  <voice name='zh-CN-XiaoxiaoNeural'>
    <mstts:express-as style='poetry-reading'>
      登鹳雀楼
      王之涣〔唐代〕
      白日依山尽，黄河入海流。
      欲穷千里目，更上一层楼。
    </mstts:express-as>
  </voice>
</speak>
"""
````

**Comment by ForrestGumb** [comment]
Andrew voice doesn't support style. You can find a list of voice that support style here.
https://learn.microsoft.com/azure/ai-services/speech-service/language-support?tabs=tts#voice-styles-and-roles

**Comment by jillbourque** [comment]
Okay, thank you!
