### ISSUE TITLE
Does the python sdk support alpine images?

### ISSUE THREAD

**Issue by rivendell1984** [Azure-Samples/cognitive-services-speech-sdk#2395]
I can't use pip command to install the python sdk, so I'm wondering if the python sdk can support alpine linux?
Thanks

**Comment by pankopon** [comment]
Hi, Alpine is not directly supported and there is no plan for it, please see https://learn.microsoft.com/azure/ai-services/speech-service/quickstarts/setup-platform?tabs=linux&pivots=programming-language-python#platform-requirements for the current supported Linux environments.
You may still be able to use the Speech SDK on Alpine by creating e.g. a Debian chroot environment as in https://wiki.alpinelinux.org/wiki/Running_glibc_programs and then following Speech SDK setup instructions for Debian.

**Comment by andreped** [comment]
@pankopon The current supported Linux images (Ubuntu/Debian) contain too many vulnerabilities to be relevant for our production applications.

Previously, I have used Alpine with both Python and C# with great success. However, recently, we hit an obstacle as the Azure Speech SDK does not seem to be compatible with Alpine. This makes it very challenging to use the Speech SDK for production.

Any update on this? Or is there a different channel where I might continue this dialogue?
