### ISSUE TITLE
Can we edit the text then translate and speak it

### ISSUE THREAD

**Issue by Tommy95271** [Azure-Samples/cognitive-services-speech-sdk#2396]
**Is your feature request related to a problem? Please describe.**
When users speak and call recognizeOnceAsync() in JavaScript, the translation result will output from browser, but sometimes user might want to edit the text they spoked and play the audio again.

**Describe the solution you'd like**
Wondering if we can edit the source text in UI and call another function to play the translated audio without speaking again?

**Comment by pankopon** [comment]
Hi, translation generates the following results:
- recognized speech as text in the source language
- translated speech as text in the target language(s)
- (optional) synthesized translated speech audio

See the [single-shot translation example](https://learn.microsoft.com/azure/ai-services/speech-service/how-to-translate-speech?tabs=terminal&pivots=programming-language-javascript#single-shot-recognition), `e.result.text` contains the recognized speech as text in the source language, `e.result.translations` contains the translated speech as text.

Considering
> sometimes user might want to edit the text they spoked and play the audio again

Editing the result text will not affect the result audio already produced. Either you need to run translation with new spoken input from the user, or you can use the edited text as input for standalone [speech synthesis](https://learn.microsoft.com/azure/ai-services/speech-service/how-to-speech-synthesis?tabs=browserjs&pivots=programming-language-javascript).
