### ISSUE TITLE
Timeout Training Custom Voice Model

### ISSUE THREAD

**Issue by gamullen** [Azure-Samples/cognitive-services-speech-sdk#2399]
I've gotten this three times in a row.

![Screenshot 2024-05-30 152339](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/46575004/e4a526b4-42d0-4ebb-84ae-614bdc1bf469)
**IN ORDER TO ASSIST YOU, PLEASE PROVIDE THE FOLLOWING:**

- Speech SDK log taken from a run that exhibits the reported issue. 
See [instructions on how to take logs](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging).

- A stripped down, simplified version of your source code that exhibits the issue. Or, preferably, try to reproduce the problem with one of the public samples in this repository (or a minimally modified version of it), and share the code.

- If relevant, a WAV file of your input audio.

- Additional information as shown below

**Describe the bug**

A clear and concise description of what the bug is. If things are not working as you expect, 
**describe exactly what you are getting and why that is not what you expect**. 
For example, speech recognition "does not work" may mean you got a cancellation 
event with a particular error message, or you did not get any recognition events, 
or the recognition result you got contains text that does not match what was spoken.

**To Reproduce**

1. ...
2. ...

**Expected behavior**

**Version of the Cognitive Services Speech SDK**

Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**

 - OS: [e.g. Windows, Linux, Android, iOS, ...] - please be specific
 - Hardware - x64, x86, ARM, ...
 - Programming language: C#, C++, Java, JavaScript, Objective-C, Python
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific

**Additional context**

 - Error messages, stack trace, ...
 - Any additional information.

**Comment by Kerry-LinZhang** [comment]
Hi @gamullen Thanks for your feedback, shall we have the region, your Speech Resource, project name or ID for further investigation? 
And when does this issue happen? (could you please make clear the time zone)

**Comment by gamullen** [comment]
I am in US Central timezone. I just tried again and it failed, so around 7:45AM.

Speech Service: GarySpeechResource, East US.

Project: GaryCustomVoice.

**Comment by gamullen** [comment]
I tried in West US with only 21 samples, failed there too in exact same way.

**Comment by ms-feizhao** [comment]
Hi @gamullen, it seems the request failed due to pool network connection. Were you using a network outside EUS or using WIFI with low bandwidth?

**Comment by gamullen** [comment]
@ms-feizhao - I have fiber optic, 500MBps. No problem with network speed.

But all the samples are already up in Azure. Wouldn't the training compute have access to everything it needs without reaching back to my laptop?

Also, it happened in both East and West US with the same error.

**Comment by ms-feizhao** [comment]
Hi @gamullen, the training data are uploaded from your laptop, so the network situation also depends on where you locate. Could you try using a VPN or try a Region that nearby? (not EUS or WUS)

**Comment by gamullen** [comment]
@ms-feizhao - I have 20+ accepted voice samples in each region. Doesn't that mean that the audio is already up in Azure and already approved? When I click "Train model" what other networking communication happens to my personal workstation?

That doesn't make any sense to me.

**Comment by gamullen** [comment]
I tried again and it worked. No idea why, I had my MSFT-AzVPN enabled.

**Comment by ForrestGumb** [comment]
This issue is Custom neural voice lite training timeout. When you start training Custom neural voice lite, the web explorer will send recording data to service. The timeout happened during data uploading because of network issue.
Gamullen resolved this issue by enabling VPN.
