### ISSUE TITLE
How to do multiple files in a single request to Batch Transcription API?

### ISSUE THREAD

**Issue by JamesEarle** [Azure-Samples/cognitive-services-speech-sdk#240]
Both of the samples for the Batch Transcription API ([here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch) in Python and C#) only do a single file. The documentation says you should be able to do multiple files from a single SAS URL but does not show anywhere how to do this. I am able to successfully receive a transcription from a single file SAS URL but anything else consistently causes an error claiming the URI is invalid. Considering this is a batch API, shouldn't multi-file be the default use case? What do I need to pass to the API to do this?

**Comment by wolfma61** [comment]
the samples have not been updated to the latest version of the batch api, which got released last week
we'll try to fix this soon ....

**Comment by JamesEarle** [comment]
@wolfma61 That makes sense, thanks. Is there a way to do the multi-file batch transcription today? e.g. passing a SAS URL for the entire storage container with certain permissions (e.g. Blob read only)?

**Comment by wolfma61** [comment]
The SAL url can identify a single file or a blob container

no updates to the documentation yet, or the samples, I know ... coming ....

**Comment by JamesEarle** [comment]
Where do you get the SAS URL for the entire container? I've tried getting it from Azure Storage Explorer but always receive an error unless it's for a single file. Where else can I get this? In the Azure Portal I'm only seeing options to create SAS URLs for the entire storage account, where you can specify permissions based on blob vs file, etc., or for individual files in a blob. I'm not seeing any in between, such as a URL for a specific container in a blob.

**Comment by wolfma61** [comment]
@PanosPeriorellis  - can you please fill in the details?
thx

**Comment by PanosPeriorellis** [comment]
You can create a SAS URI for a container using Azure Storage Explorer. However The API that processes a container SAS URI is in preview. Send us an email in our email support alias <speechsupport> and I will send you the details.

**Comment by wolfma61** [comment]
closing this - I also expect this to be available soon-ish

**Comment by theonlygusti** [comment]
Is it supported yet?

Also @PanosPeriorellis what email address is that, so I can email too?
