### ISSUE TITLE
WebGL Support For Unity Builds

### ISSUE THREAD

**Issue by calebeno** [Azure-Samples/cognitive-services-speech-sdk#2403]
**Is your feature request related to a problem? Please describe.**
I am aware that [https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2024](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2024) exists. It has been nearly a year since the last update.  Is there any more clarity on when the Unity Speech SDK will support WebGL builds in Unity?

**Describe the solution you'd like**
To build Unity projects to WebGL with the Speech Studio SDK successfully.

**Describe alternatives you've considered**
I am in the process of evaluating the Speech Studio JS plugin to see if I can wrap it in a jslib.  This is a soul-crushing task as I spent the last month getting the Speech Studio SDK for Unity working in my project only to discover at the 11th hour that it did not support WebGL builds.

**Additional context**
I'm a dev, I get it.  Lots of things take priority.  But having this would solve a major headache for me (and others apparently).

**Comment by pankopon** [comment]
Hi, sorry for a late response but unfortunately there is no update in plans. Support for WebGL builds is not in the current Speech SDK roadmap, at least for this year.
