### ISSUE TITLE
Why the Keyword Recognition will be blocked for 10 seconds

### ISSUE THREAD

**Issue by rivendell1984** [Azure-Samples/cognitive-services-speech-sdk#2404]
Hello,
I'm testing the _speech_recognize_keyword_locally_from_microphone_ function in speech_sample.py on Raspberry Pi. And I found after it recognizes the keyword, it'll be blocked for 10 seconds. And I need to stop_recognition_async after it recognizes the keyword.
Could you tell me why it happed? is the stop_recognition_async right way to fix it?
Thanks

**Comment by pankopon** [comment]
Hi, this may be related to https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2379 - until resolved, you should continue to use your "workaround".
