### ISSUE TITLE
Avatar WebRTC setup on page load instead of session start click

### ISSUE THREAD

**Issue by ggiunta92** [Azure-Samples/cognitive-services-speech-sdk#2408]
Hi,
I'm trying to embed the avatar in an HTML web page. Using the basic.html example file, I'm able to load the avatar without problems using the "Start Session" button. But then, if I want to force the session start of the avatar at the page loaded event (instead of button click) the Avatar doesn't appear, although all loading phases and logs are ok.
![Avatar loading issue](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/115783667/9ca58a88-3e80-4a41-a870-090f9d26bdbd)
Could anyone suggest me how to investigate more thoroughly?
Thank you.

Gabriele

**Comment by yulin-li** [comment]
@yinhew  could you pleas take a look?

**Comment by yinhew** [comment]
Hi, @ggiunta92 

Please refer to https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide
This is an industry policy which most browsers are following.
You need some user interaction before auto-playing some media.

Before your change, the click on the button is the user interaction.
After your change, the user interaction is gone.

That's the reason.

Thanks,
Yinhe

**Comment by ggiunta92** [comment]
Hi, @yinhew 
perfect understood. Thanks for your support.

Gabriele
