### ISSUE TITLE
I want a off line translate sdk

### ISSUE THREAD

**Issue by hold-my-hand** [Azure-Samples/cognitive-services-speech-sdk#241]
I want a off line translate iOS sdk
and do you have a  converstion sdk for mobile app?

**Comment by hold-my-hand** [comment]
I want a off line translate iOS sdk

**Comment by wolfma61** [comment]
currently the SDK doesn't support offline functionality, we are looking into this, but it will take a while for this becoming part of 

conversation sdk for mobile app - can you be more specific? What is what you need or are missing from the SDK?

Wolfgang

**Comment by chriswendt1** [comment]
For offline text translation see: https://github.com/MicrosoftTranslator/Local-Feature-Android.
