### ISSUE TITLE
Matching word timecodes with transcript in NBest Display property

### ISSUE THREAD

**Issue by grale88** [Azure-Samples/cognitive-services-speech-sdk#242]
**Is your feature request related to a problem? Please describe.**
Currently I'm using speech to text feature in order to process some audio files and generate complete speech transcript. I am also relying on the feature to return timecodes on word basis which I'm combining with the transcript. I'm wondering if there is an configuration option or ability for you to provide this word array based on NBest -> Display transcript for particular SpeechRecognitionResult.

Below is the example of the result:
`"Duration": 89100000,
  "NBest": [
    {
      "Confidence": 0.94624471664429,
      "Display": "Well, how did you find it I know what you mean but I literally couldn't put it down and stayed up till 3:00 in the morning to finish it.",
      "ITN": "Well how did you find it I know what you mean but I literally couldn't put it down and stayed up till 300 in the morning to finish it",
      "Lexical": "well how did you find it i know what you mean but i literally couldn't put it down and stayed up till three in the morning to finish it",
      "MaskedITN": "Well how did you find it I know what you mean but I literally couldn't put it down and stayed up till 300 in the morning to finish it",
      "Words": [
        {
          "Duration": 4400000,
          "Offset": 375500000,
          "Word": "well"
        },
        {
          "Duration": 2600000,
          "Offset": 382000000,
          "Word": "how"
        },
        {
          "Duration": 1900000,
          "Offset": 384700000,
          "Word": "did"
        },
        {
          "Duration": 1500000,
          "Offset": 386700000,
          "Word": "you"
        },
        {
          "Duration": 2300000,
          "Offset": 388300000,
          "Word": "find"
        },
        {
          "Duration": 2800000,
          "Offset": 390700000,
          "Word": "it"
        },
        {
          "Duration": 3300000,
          "Offset": 397900000,
          "Word": "i"
        },
        {
          "Duration": 2700000,
          "Offset": 401300000,
          "Word": "know"
        },
        {
          "Duration": 1500000,
          "Offset": 404100000,
          "Word": "what"
        },
        {
          "Duration": 1300000,
          "Offset": 405700000,
          "Word": "you"
        },
        {
          "Duration": 3300000,
          "Offset": 407100000,
          "Word": "mean"
        },
        {
          "Duration": 2900000,
          "Offset": 410500000,
          "Word": "but"
        },
        {
          "Duration": 1100000,
          "Offset": 413500000,
          "Word": "i"
        },
        {
          "Duration": 11300000,
          "Offset": 414700000,
          "Word": "literally"
        },
        {
          "Duration": 5100000,
          "Offset": 426300000,
          "Word": "couldn't"
        },
        {
          "Duration": 2100000,
          "Offset": 431500000,
          "Word": "put"
        },
        {
          "Duration": 1300000,
          "Offset": 433700000,
          "Word": "it"
        },
        {
          "Duration": 4300000,
          "Offset": 435100000,
          "Word": "down"
        },
        {
          "Duration": 2100000,
          "Offset": 439500000,
          "Word": "and"
        },
        {
          "Duration": 3700000,
          "Offset": 441700000,
          "Word": "stayed"
        },
        {
          "Duration": 1300000,
          "Offset": 445500000,
          "Word": "up"
        },
        {
          "Duration": 1600000,
          "Offset": 446900000,
          "Word": "till"
        },
        {
          "Duration": 3500000,
          "Offset": 448600000,
          "Word": "three"
        },
        {
          "Duration": 1000000,
          "Offset": 452200000,
          "Word": "in"
        },
        {
          "Duration": 600000,
          "Offset": 453300000,
          "Word": "the"
        },
        {
          "Duration": 3400000,
          "Offset": 454000000,
          "Word": "morning"
        },
        {
          "Duration": 1100000,
          "Offset": 457500000,
          "Word": "to"
        },
        {
          "Duration": 2900000,
          "Offset": 458700000,
          "Word": "finish"
        },
        {
          "Duration": 2400000,
          "Offset": 461700000,
          "Word": "it"
        }
      ]
    }`

Currently returned words are matching "Lexical" field content which has all the lowercase letters and no punctuation and also handles time or decimal numbers in a different way. See the example with "3:00" in Best Display recognized as "three" in the word array. 

I suppose other example might be 2.54 that would maybe represented as "two point five four" in the words array. Hence it is difficult to detect whole group of words and determine the real duration.

**Describe the solution you'd like**
Return the word array per requested transcript field (Display, Lexical, ITN...)

**Additional context**
I am developing a Java application and I'm using latest version of Speech SDK 1.5.1

**Comment by BrianMouncer** [comment]
We only have the two formats OutputFormat::Detailed, and OutputFormat::Simple.
It looks like you are already using the detailed output format and retrieving the services JSON output.

If I understand your request, you would like "Duration" and "Offset" values for each path in the lattice that is dumped out in the detailed JSON response?

Please let me know if that is a correct interpretation, and I will add the request to our backlog of features.

**Comment by zhouwangzw** [comment]
By setting RequestWordLevelTimestamps() on SpeechConfig you will get word-level timestamps in result. In C# you can use Best() method to get those values. In Java, you have to read detailed output from property SpeechServiceResponse_JsonResult , something like 
`detailedResult = result.getProperties().getProperty(PropertyId.SpeechServiceResponse_JsonResult)`
and then parse `detailedResult` as JSON object by yourself. 

Thanks,
Zhou

**Comment by jhakulin** [comment]
Closing, let us know if you need more information

**Comment by DanielFalkSR** [comment]
Is there any update on the progress here? We have the same demand for getting timestamps for the Display text.
