### ISSUE TITLE
Can't distribute App with 'MicrosoftCognitiveServicesSpeech-macOS' pod on MacOS

### ISSUE THREAD

**Issue by shekunsky** [Azure-Samples/cognitive-services-speech-sdk#243]
I can't distribute App from Xcode with embedded framework 'MicrosoftCognitiveServicesSpeech-macOS'. Xcode crashes...
If i'll try to "Validate App" (not "Distribute") Xcode also crashes. 
I tried to do it on sample app ("helloworld") with Xcode 10.2.1
Please help.

**Comment by shekunsky** [comment]
Update:
Xcode 9.4.1 shows error:
Couldn't find platform family in Info.plist CFBundleSupportedPlatforms or Mach-O LC_VERSION_MIN for A

**Comment by shekunsky** [comment]
RESOLVED
In every MicrosoftCognitiveServicesSpeech.framework version's (A, Current) info.plist need to add:
<key>LSMinimumSystemVersion</key>
	<string>13.0</string>
<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>

**Comment by chlandsi** [comment]
@shekunsky Thank you for reporting and investigating this issue! We will add this tag to the framework metadata for the next release.
