### ISSUE TITLE
speech_recognizer.recognize_once_async().get() returns No Match Not recognized when System Mic is already in use

### ISSUE THREAD

**Issue by SumiranLohani** [Azure-Samples/cognitive-services-speech-sdk#2437]
Hello All,

I am using the cognitive-services-speech-sdk and facing an issue:

If the system mic is already in use like a Teams call, or a Screen recorder app, then the speech_recognizer.recognize_once_async fails to detect the sound.

Even countinuous recognition did not work in this case. Hence, seeking guidance on what is the recommended approach to tackle this issue. Thanks!

**Comment by pankopon** [comment]
Hi, this can depend on the OS and its version (which you didn't specify - Teams is multiplatform, and there are many apps called "Screen recorder") but if the system doesn't support shared microphone access by default then no other apps can access the audio input until the app that first started capturing audio stops.

If this behavior is not configurable in system settings, you could try searching for an API to "detect if a microphone is used by any application" and use that in your code to check the situation before starting recognition. Unfortunately there is probably not much else you can do about it.
