### ISSUE TITLE
No javascript example to transcribe for AudioConfig.fromStreamInput method.

### ISSUE THREAD

**Issue by mitanshu001** [Azure-Samples/cognitive-services-speech-sdk#244]
Can you please provide a example. I am new to the azure speech SDK.

**Comment by rhurey** [comment]
Sure. There's an example of using a push stream to read from a file in the node sample set.

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/node/index.js

We are lacking a pull stream sample though, I'll see about getting one added.

**Comment by mitanshu001** [comment]
Actually I am interested in using this method to continuously send audio streams from a MediaStream object which is created from a HTMLMediaelement. Is this possible ?

**Comment by rhurey** [comment]
Yes, it's possible. 

But its not direct and there's additional steps that would need to happen.

The SDK doesn't have a method that can construct an AudioConfig from a platform specific object like a MediaStream (The SDK interface has been kept mostly generic across all languages and platforms)

Once the MediaStream is captured, you'd need to process audio frames from it, PCM encode them, and send them into a stream type that AudioConfig did understand. (I'd recommend a PushStream). While not callable publicly, the SDK has most of the code in place to act as a sample of how to do this.

PCMRecorder::Record (https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/common.browser/PCMRecorder.ts) is a good place to start if you want to explore that path.

Being able to recognize speech directly from a MediaStream is a request that has come up before, and what the preferred construct to support a platform specific audio interface looks like is something that we're discussing.

**Comment by mitanshu001** [comment]
Thanks for the response @rhurey.
Can you please explain why will you prefer PushStream ? I was thinking of using  PullAudioInputStreamCallback as explained in this article [](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-audio-input-streams)

**Comment by rhurey** [comment]
Seems like less work.

The media stream that the existing microphone code works from raises events when it has audio, handing you an audio frame of some size. You need to encode the frame and then do something with it.

If you're using a PushStream, you can call Write() and pass the frame into the stream and that's it. The PushStream will handle buffering the frame along with others and send it off to the speech service once it has enough data to fill a transmission packet, handling splitting audio as necessary.

If you use a PullStream, you need to buffer the frame along with any other frames that occur until the PullStreamCallback asks for audio. Then you need to provide the PullStream with the audio frames. You may need to split the data you have into smaller or larger segments to fill the PullStream's read buffer.

**Comment by wolfma61** [comment]
closing

**Comment by kaioduarte** [comment]
I'll drop my solution here in case someone stumbles across this again.

```js
const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
const audioConfig = SpeechSDK.AudioConfig.fromStreamInput(stream);
const recognizer = new SpeechSDK.SpeechRecognizer(speechConfig, audioConfig);

// register to recognizer events

recognizer.startContinuousRecognitionAsync();
```
