### ISSUE TITLE
Please provide an example of using AutoDetectSourceLanguageConfig.FromOpenRange() in JS /browser

### ISSUE THREAD

**Issue by sabbadino** [Azure-Samples/cognitive-services-speech-sdk#2445]
Please provide an example of using AutoDetectSourceLanguageConfig.FromOpenRange() in JS /browser

I tried to modify similar ones not using FromOpenRange but i get error
in reco.recognizeOnceAsync callback , successfulResult.privErrorDetails = "Invalid 'language' query parameter or unknown custom deployment. websocket error code: 1007"

NOTE that i am using a **SpeechRecognizer** , not a **speechTranslator**

-------------
```

export function doRecognizeOnceAsync(
  audioFile: any,
  callback: any,
  debug: boolean,
  key: string,
  region: string,
  culture: string
) {
  const audioConfig = getAudioConfig(audioFile, debug);
  const speechConfig = getSpeechConfig(
    SpeechSDK.SpeechConfig,
    key,
    region,
    culture
  );
  if (!audioConfig || !speechConfig) return;

  reco = new SpeechSDK.SpeechRecognizer(speechConfig, audioConfig);
  const autoDetectSourceLanguageConfig = SpeechSDK.AutoDetectSourceLanguageConfig.fromOpenRange();
  autoDetectSourceLanguageConfig.mode = SpeechSDK.LanguageIdMode.AtStart;

  reco = SpeechSDK.SpeechRecognizer.FromConfig(
    speechConfig,
    autoDetectSourceLanguageConfig,
    audioConfig
  );

  // reco.recognized = undefined;

  reco.recognizeOnceAsync(
    function (successfulResult: any) {
      onRecognizedResult(successfulResult);
      callback(successfulResult);
    },
    function (err: string) {
      window.console.log(err);
    }
  );
}  
  ....
  
  function getSpeechConfig(
  sdkConfigType: typeof SpeechSDK.SpeechConfig,
  key: string,
  region: string,
  culture: string
): any {
  const v2EndpointInString = `wss://${region}.stt.speech.microsoft.com/speech/universal/v2`;
  const v2EndpointUrl = new URL(v2EndpointInString);
  const speechConfig = sdkConfigType.fromEndpoint(v2EndpointUrl, "");
  speechConfig.authorizationToken = key;

  speechConfig.outputFormat = SpeechSDK.OutputFormat.Simple;

  return speechConfig;
}
```

**Comment by pankopon** [comment]
Hi, `FromOpenRange` is not supported with `SpeechRecognizer` (and there are no plans for it), you need to specify the source language candidates. See
https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/e89846a774639bfb05e9550d4d759871790cf627/src/sdk/AutoDetectSourceLanguageConfig.ts#L29
(Speech SDK for JS does not support `FromOpenRange` with translation either, only synthesizer)

**Comment by sabbadino** [comment]
Hi about this statement "Speech SDK for JS does not support FromOpenRange with translation either, only synthesizer" : is there an ETA for the  support in the js SDK ?
Thanks
