### ISSUE TITLE
[IngestionClient] Use bicep templates instead of raw ARM json templates for deployment. 

### ISSUE THREAD

**Issue by superhindupur** [Azure-Samples/cognitive-services-speech-sdk#2451]
**Is your feature request related to a problem? Please describe.**
From the official Azure documentation:  "You can use Bicep instead of JSON to develop your Azure Resource Manager templates (ARM templates). The JSON syntax to create an ARM template can be verbose and require complicated expressions. Bicep syntax reduces that complexity and improves the development experience. Bicep is a transparent abstraction over ARM template JSON and doesn't lose any of the JSON template capabilities. During deployment, the Bicep CLI converts a Bicep file into ARM template JSON."

[This](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/overview?tabs=bicep#benefits-of-bicep) is a more detailed list of advantages Bicep can give you.

**Describe the solution you'd like**
Replace the raw JSON ARM templates in IngestionClient with the equivalent bicep templates, and support running `azd up` to deploy to Azure.

**Comment by pankopon** [comment]
@HenryvanderVegte There are several "[IngestionClient]" items open, are these actual customer issues or more general backlog work items? Is there a plan for them? Please update.

**Comment by HenryvanderVegte** [comment]
As discussed in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2521, moving item to internal backlog. Not an actual customer issue, but general backlog work item.
