### ISSUE TITLE
Ubuntu 22.04.4 -java.lang.UnsatisfiedLinkError: 'void com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(java.lang.String)'

### ISSUE THREAD

**Issue by songlinyu-hub** [Azure-Samples/cognitive-services-speech-sdk#2453]
java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V
        at com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Native Method)
        at com.microsoft.cognitiveservices.speech.SpeechConfig.<clinit>(Unknown Source)
I use the voice service demo locally and it runs normally. When I deploy it on Ubuntu, I get an error: java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V. I also downloaded SpeechSDK and configured the environment. , this problem has not been solved yet, does anyone have relevant experience to offer? grateful

**Comment by songlinyu-hub** [comment]
Deployment on centos7 is no problem, but error is still reported on Ubuntu

**Comment by pankopon** [comment]
Please re-test with the Speech SDK 1.40.0 release out now:
https://learn.microsoft.com/azure/ai-services/speech-service/releasenotes?tabs=speech-sdk
Ensure that you have installed all required dependencies:
https://learn.microsoft.com/azure/ai-services/speech-service/quickstarts/setup-platform?tabs=linux&pivots=programming-language-java#platform-requirements
If you still get an error, post the full console output.

**Comment by pankopon** [comment]
Closed since no updates and not repro.
