### ISSUE TITLE
[Ingestion Client] Move all keys/secrets to KeyVault

### ISSUE THREAD

**Issue by ross-p-smith** [Azure-Samples/cognitive-services-speech-sdk#2456]
**Is your feature request related to a problem? Please describe.**
The functions communicate with various Azure services, these connection strings are stored in App Settings. They are

- [ ] APPLICATIONINSIGHTS_CONNECTION_STRING
- [ ] AzureServiceBus
- [ ] AzureWebJobsStorage
- [ ] [AzureWebJobsDashboard (Isn't this a really old key?)](https://github.com/Azure-Samples/cognitive-services-speech-sdk/pull/2496)
- [ ] CompletedServiceBusConnectionString
- [ ] FetchTranscriptionServiceBusConnectionString
- [ ] StartTranscriptionServiceBusConnectionString

**Describe the solution you'd like**
These could be stored as secrets in KeyVault and use the @Microsoft.KeyVault() expression to retrieve them

**Describe alternatives you've considered**
This is in interim step before using RBAC instead to remove all of the keys

**Comment by pankopon** [comment]
@HenryvanderVegte There are several "[IngestionClient]" items open, are these actual customer issues or more general backlog work items? Is there a plan for them? Please update.
