### ISSUE TITLE
[Ingestion Client] Move away from Access Keys in preference of RBAC

### ISSUE THREAD

**Issue by ross-p-smith** [Azure-Samples/cognitive-services-speech-sdk#2457]
**Is your feature request related to a problem? Please describe.**
The Functions communicate with ServiceBus and Storage - both of these are using Access Keys

**Describe the solution you'd like**
This solution should utilise Role Based Access Control and remove the need for keys

**Describe alternatives you've considered**

**Additional context**
This will require the deployment to need an Owner/User Access Administrator to deploy Role Permissions

**Comment by ross-p-smith** [comment]
This would be implemented by using https://learn.microsoft.com/en-us/azure/azure-functions/functions-identity-based-connections-tutorial-2 running as an identity and removing the keys from AppSettings - this would make the application much more secure.

**Comment by pankopon** [comment]
@HenryvanderVegte There are several "[IngestionClient]" items open, are these actual customer issues or more general backlog work items? Is there a plan for them? Please update.

**Comment by HenryvanderVegte** [comment]
As discussed in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2521, moving item to internal backlog. Not an actual customer issue, but general backlog work item.
