### ISSUE TITLE
Error when trying apple upload

### ISSUE THREAD

**Issue by Vliosgep** [Azure-Samples/cognitive-services-speech-sdk#246]
Hello, 
I get below error when i try validate app and app store upload. I used embedded binary for Xcode 9 but trying upload from latest Xcode. 
![Screenshot 2019-05-28 at 2 41 08 PM](https://user-images.githubusercontent.com/49437974/58467927-305dbc80-815a-11e9-9b6d-4dcd7e51dfdb.png)
Let me know how can i get over this?
Thank you.

**Comment by shekunsky** [comment]
Hi!
I recently encountered the same problem.
RESOLVED:
In every MicrosoftCognitiveServicesSpeech.framework version's (A, Current) info.plist need to add:
<key>LSMinimumSystemVersion</key>
<string>10.13</string>
<key>CFBundleSupportedPlatforms</key>
<array>
<string>MacOSX</string>
</array>

**Comment by Vliosgep** [comment]
I have embedded framework and not used pods. As said when started Xcode was 9 so had to use the embed framework method. So in this case , I can't find its info plist file. I am using this for iPhone app.
What can I do? Can you help me with your screenshot?

**Comment by chlandsi** [comment]
The fix provided by @shekunsky is for macOS apps only; I assume you are trying to build an iOS app.

Can you click on "Show logs" in the dialog on your screenshot and post the messages here to help debugging? Thanks!

**Comment by Vliosgep** [comment]
Yes its for iPhone app.

**Comment by Vliosgep** [comment]
There are lots of logs exactly which logs you want ?

**Comment by chlandsi** [comment]
That is difficult to say remotely... Anything to do with code signing, and any error messages you can find might be helpful.

**Comment by chlandsi** [comment]
Closing, after switching to including the framework with CocoaPods resolved the issue.
