### ISSUE TITLE
Specific version of speech sdk binaries

### ISSUE THREAD

**Issue by krambojun** [Azure-Samples/cognitive-services-speech-sdk#2461]
https://aka.ms/csspeech/linuxbinary gives me the latest version of the binaries, is there a url that i could use to get the older or any version for that matter?

**Comment by pankopon** [comment]
You can see it in the `wget` output:
```
# wget -O SpeechSDK-Linux.tar.gz https://aka.ms/csspeech/linuxbinary
--2024-06-28 16:41:48--  https://aka.ms/csspeech/linuxbinary
Resolving aka.ms (aka.ms)... 23.201.69.142
Connecting to aka.ms (aka.ms)|23.201.69.142|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://csspeechstorage.blob.core.windows.net/drop/1.38.0/SpeechSDK-Linux-1.38.0.tar.gz [following]
```
So by taking the url shown above and replacing 1.38.0 with another version number, you can download an older release.
However, urls other than aka.ms may change at any time, there is no guarantee that the location is permanent (but you can always check it as above). Also, there is effectively no support for releases older than the latest.
