### ISSUE TITLE
INSTALL_FAILED_CONFLICTING_PROVIDER

### ISSUE THREAD

**Issue by anhduy5689h** [Azure-Samples/cognitive-services-speech-sdk#2463]
com.microsoft.cognitiveservices.speech:client-sdk:1.38.0

Error: INSTALL_FAILED_CONFLICTING_PROVIDER: Scanning Failed.: Can't install because provider name com.microsoft.cognitiveservices.speech.util.InternalContentProvider (in package com.example.dev) is already used by com.example.staging

**Comment by pankopon** [comment]
Presuming this is about Android, there is already a service incident report 516797247 and the fix will be in the next public Speech SDK release in August.

**Comment by pankopon** [comment]
To note, the older 1.36.0 release should not have this issue and can be used as a workaround until the fix is out.

**Comment by pankopon** [comment]
This has been fixed in the Speech SDK 1.40.0 release out now.
