### ISSUE TITLE
Release notes for speech sdk linux

### ISSUE THREAD

**Issue by krambojun** [Azure-Samples/cognitive-services-speech-sdk#2469]
Is there an api  which lists releases of https://aka.ms/csspeech/linuxbinary (ideally in json or xml format) ? i am trying to use the Renovate bot and need to define a [custom data source ](https://docs.renovatebot.com/configuration-options/#customdatasources) in order to look for specific versions.

**Comment by pankopon** [comment]
Hi, there is no such API so you would need to parse the version numbers from published release information. Some possible sources:
- Speech SDK release notes
  https://learn.microsoft.com/azure/ai-services/speech-service/releasenotes?tabs=speech-sdk
- Speech SDK nupkg versions
  https://www.nuget.org/packages/Microsoft.CognitiveServices.Speech#versions-body-tab
- Speech SDK for Java versions
  https://mvnrepository.com/artifact/com.microsoft.cognitiveservices.speech/client-sdk or
  https://repo1.maven.org/maven2/com/microsoft/cognitiveservices/speech/client-sdk/

Note that the SpeechSDK-Linux.tar.gz is guaranteed to be updated only on main (`x.y.0`) releases, minor/hotfix releases (`x.y.1`, `x.y.2`...) do not necessarily include all packages if e.g. Linux is not affected by changes.

**Comment by pankopon** [comment]
Closed as answered.
