### ISSUE TITLE
Final Recognization is not captured after stopContinuousRecognitionAsync is called

### ISSUE THREAD

**Issue by jason2211** [Azure-Samples/cognitive-services-speech-sdk#247]
**Describe the bug**
My app is using the continuous recognition feature to translate a spoken dictation.  When the speaker finishes they click on a finish button which calls the stopContinuousRecognitionAsync method.  Their last spoken words are never translated.  

I receive calls to the recognizing event with parts of their final utterances but the call to recognized never happens once the stop method is called.  I would expect the recognized event to fire one final time after the stop is called.  

As a work-around, I've added a delay between the button click and the stopContinuousRecognitionAsync call.  This is less than optimal since there is no way to mute the microphone to prevent capturing words said after the stop is clicked.  It is also a challenge to implement a pause feature if they speaker is interrupted (phone call, etc.) during their dictation.

**To Reproduce**
1. Call startContinuousRecognitionAsync
2. Speak words, then call stopContinuousRecognitionAsync without a long pause after last spoken word
3. Final utterance is never sent to the recognized event

**Expected behavior**
The recognized event should fire for the last utterance translation.

**Version of the Cognitive Services Speech SDK**
Javascript/Browser v1.5.0

**Platform, Operating System, and Programming Language**
 - Programming language: JavaScript
 - Browser: Chrome 74.0.3729.169

_Side note, great work on the SDK, it was easy to implement with the quickstarts, samples, and doc._

**Comment by rhurey** [comment]
Thanks for report. There's a difference in behavior between the JS implementation and our other languages around the meaning of "stop"

As you've noticed, the JS implementation treats "Stop" more abruptly and stops raising events in addition to stopping audio collection. It should take the approach of suspending audio collection and still process events returned from the Speech Service.

I'll put a bug in our backlog around this.

**Comment by jason2211** [comment]
@rhurey Thanks for responding.  Is there a way I can monitor the bug to see when it is fixed?

**Comment by rhurey** [comment]
It'll be mentioned in the SDK release notes for JavaScript. You can follow the releases @https://github.com/microsoft/cognitive-services-speech-sdk-js/releases

**Comment by jhakulin** [comment]
Closing the issue as fix is under planning for the upcoming releases. Thanks for reporting the issue
