### ISSUE TITLE
Java SDK always send SSML even using StartSpeakingText

### ISSUE THREAD

**Issue by jackfengji** [Azure-Samples/cognitive-services-speech-sdk#2471]
- Speech SDK log taken from a run that exhibits the reported issue. 
[azure.log](https://github.com/user-attachments/files/16088510/azure.log)

- Describe the bug
I want to speak the text without using SSML but it's not possible in java sdk

**To Reproduce**
1. Integrate java sdk 1.38.0
2. Use "StartSpeakingTextAsync" to speak the text
3. From log, it's still using SSML.

**Expected behavior**

It should send the text only without SSML

**Version of the Cognitive Services Speech SDK**

com.microsoft.cognitiveservices.speech:client-sdk:1.38.0

**Platform, Operating System, and Programming Language**

 - OS: Android
 - Hardware - ARM, ...
 - Programming language: Java

**Comment by yulin-li** [comment]
Plain text is not supported by the service, so SDK constructs the SSML based on voice name, text etc.
