### ISSUE TITLE
Domain/Host/IP allowlist for streaming speech to text 

### ISSUE THREAD

**Issue by ashwyn** [Azure-Samples/cognitive-services-speech-sdk#2472]
Hi, 

We use `istio` service entries for gating egress from our containers. And we are having trouble configuring the domains/hosts/IPs that need to be allowed when using the Python Speech SDK for streaming transcriptions. 

SDK log file has the following error: 

```SPX_TRACE_ERROR: AZ_LOG_ERROR:  socketio_berkeley.c:959 Socketio_Failure: Receiving data from endpoint: errno=104.```

When we disable egress checks, everything works fine. 

Could you share a list of domains that we need to add to the allowlist?

Thanks!

**Comment by pankopon** [comment]
Please see https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1105 for information and links.

**Comment by pankopon** [comment]
Closed as answered.
