### ISSUE TITLE
Issues with word with timecodes array

### ISSUE THREAD

**Issue by grale88** [Azure-Samples/cognitive-services-speech-sdk#249]
**Describe the bug**
I am creating Java application that processes audio files and generates transcript with timecodes. I have "requestWordLevelTimestamps" option enabled for recognition. Currently during processing of particular file, for one recognition result I get for the word "mother's" two words in the array as:

`{  
   "Duration":3600000,
   "Offset":219200000,
   "Word":"mother"
 },
 {  
   "Duration":1000000,
   "Offset":222900000,
   "Word":"'s"
},`

The part of the phrase containing these words - "We're looking at her mother's daughter by Alice Fitzgerald, a novel written from..."

In the same transcript for example I have "we're" and "we've" that are returned as a single word in the array

**To Reproduce**
1. Running speech file containing this kind of words (possessions)

**Expected behavior**
This kind of words meaning possession or similar with apostrophes should not be treated as separate words in resulting array.

**Version of the Cognitive Services Speech SDK**
Version 1.5.1

**Platform, Operating System, and Programming Language**
 - OS: Windows 10 and Ubuntu 18.04
 - Hardware - x64
 - Programming language: Java

**Additional context**
If necessary I can also provide you with the file I used for testing

**Comment by jhakulin** [comment]
Thanks for the feedback, we will check internally if this is by design or an issue we should fix.
