### ISSUE TITLE
Github examples still references to API version 3.1 rather than 3.2

### ISSUE THREAD

**Issue by piebebakke** [Azure-Samples/cognitive-services-speech-sdk#2494]
I noticed that on https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python the swagger client stills refers to API version 3.1, whilst the current one is 3.2

No sure if this is the right place to report it as it not a big issue.

Thanks

**Comment by chlandsi** [comment]
Hi, thanks for bringing this to our attention. The samples have been updated to use the new stable API version.

**Comment by chlandsi** [comment]
Samples are updated.
