### ISSUE TITLE
SPXERR_EXTENSION_LIBRARY_NOT_FOUND in UWP

### ISSUE THREAD

**Issue by PeteK68** [Azure-Samples/cognitive-services-speech-sdk#250]
I have code using `Microsoft.CognitiveServices.Speech` services in a UWP app. While trying to do keyword spotting, I get the following error:
`Exception with an error code: 0x24 (SPXERR_EXTENSION_LIBRARY_NOT_FOUND)`

On the following line of code:
```cs
await recognizer.StartKeywordRecognitionAsync(model).ConfigureAwait(false);
````

Using 1.5.1 version of the SDK.

**Comment by MahadevanSrinivasan** [comment]
Keyword spotting for UWP is not available in the current release. We are working on it and it will be added really soon.

**Comment by daltskin** [comment]
Are there updates on the time frame for this being supported?

**Comment by ZaherAirout** [comment]
@daltskin 
Can you include additional DLL named "Microsoft.CognitiveServices.Speech.extension.kws.dll"
I had the same error in another enviroment (python code not UWP) and I solved it by adding this DLL

**Comment by daltskin** [comment]
Thanks, but that doesn't work. 

---------------------------
Microsoft Visual Studio
---------------------------
A reference to 'C:\Users\**\.nuget\packages\microsoft.cognitiveservices.speech\1.6.0\runtimes\win-x64\native\Microsoft.CognitiveServices.Speech.extension.kws.dll' could not be added. Please make sure that the file is accessible, and that it is a valid assembly or COM component.
---------------------------
OK   
---------------------------

**Comment by tom1milman** [comment]
I contacted Microsoft about this, the devs told me that kws is not supported for UWP. I had to find a workaround, you can see it in this [repository](https://github.com/tom1milman/Azure-Cognitive-Services-Keyword-Spotting-for-UWP).
