### ISSUE TITLE
[IngestionClient] Modularization of the bicep template

### ISSUE THREAD

**Issue by komalg1** [Azure-Samples/cognitive-services-speech-sdk#2502]
**Is your feature request related to a problem? Please describe.**
Currently, our Bicep file is monolithic, making it difficult to manage, update, and reuse specific parts of the template. This increases the risk of errors and complicates collaboration, as we have to navigate through a large, single file to make changes or additions.

**Describe the solution you'd like**
Modularizing the existing Bicep template into smaller, reusable components. Each module will handle a specific part of the infrastructure (e.g., storage accounts, virtual networks, compute resources). This approach will improve maintainability, enable better code reuse, and simplify the process of updating individual parts of the infrastructure.

**Additional context**
Related to #2451 & will also help completing #2449 

**Pre-requisite task**
Move `Setup` & `scripts` folder to `infra` folder

**Comment by ross-p-smith** [comment]
@HenryvanderVegte - Maybe worth looking at : - https://azure.github.io/Azure-Verified-Modules/ to break these into Modules

**Comment by pankopon** [comment]
@HenryvanderVegte There are several "[IngestionClient]" items open, are these actual customer issues or more general backlog work items? Is there a plan for them? Please update.

**Comment by HenryvanderVegte** [comment]
As discussed in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2521, moving item to internal backlog. Not an actual customer issue, but general backlog work item.
