### ISSUE TITLE
Support for Swift in iOS

### ISSUE THREAD

**Issue by Deepak2690** [Azure-Samples/cognitive-services-speech-sdk#252]
Hello Team
Is there any chance to provide iOS sdk in swift in some time in future?

**Comment by chlandsi** [comment]
Hi, you can already use the SDK with Swift using a bridging header. We will provide a sample for this soon.

**Comment by Deepak2690** [comment]
Hi @chlandsi 
I already tried with bridging header but it showing that MicrosoftCognitiveServicesSpeech/SPXSpeechApi.h file is not found.
It is the same issue that was reported by one user in your open issue sections.
So please help us on it.

**Comment by chlandsi** [comment]
This should be a working bridging header (`MicrosoftCognitiveServicesSpeech-Bridging-Header.h`):
```
#ifndef MicrosoftCognitiveServicesSpeech_Bridging_Header_h
#define MicrosoftCognitiveServicesSpeech_Bridging_Header_h

#import <MicrosoftCognitiveServicesSpeech/SPXSpeechAPI.h>

#endif /* MicrosoftCognitiveServicesSpeech_Bridging_Header_h */
```

For the header to be found, the MicrosoftCognitiveServicesSpeech.framework needs to be in the framework search path. If you are using cocoapods, please put this section into your `Podfile`:

```
target 'SpeechSDKSwift' do
  platform :ios, '9.3'
  pod 'MicrosoftCognitiveServicesSpeech-iOS', '~> 1.5.1'
  use_frameworks!
end
```

A full sample should be ready by the end of the week or so.

**Comment by Deepak2690** [comment]
Hi @chlandsi 
I have tried with same bridging header as you are providing & still I am getting the same error. 
It would be great if you can provide the sample. I will wait for this week for sample & will try again next week by using your sample.
thanks.

**Comment by Deepak2690** [comment]
hi @chlandsi 
we are waiting for you to share the sample in swift code.
Please share it at the earliest.

**Comment by chlandsi** [comment]
Hi @Deepak2690 , I put a preliminary sample [here](https://github.com/chlandsi/cognitive-services-speech-sdk/tree/chlandsi-samples/swift-sample/quickstart/swift-ios/helloworld). Note that we will be changing error handling and reporting for the Objective-C and swift bindings of the SDK in the next release or the one after, which will make (small) changes to Swift code necessary on the dependency update.
