### ISSUE TITLE
[IngestionClient] move ingestion client build to be localised.

### ISSUE THREAD

**Issue by ross-p-smith** [Azure-Samples/cognitive-services-speech-sdk#2521]
**Is your feature request related to a problem? Please describe.**
The GitHub action files are in the root of the repo (which is where GitHub expects them to be). However, because this is a mono repo and the Ingestion Client only needs to be opened at the `/workspaces/cognitive-services-speech-sdk/samples/ingestion/ingestion-client/` level, it often means that build concerns are missed when developing the Ingestion Client

**Describe the solution you'd like**
Have the workflows defined in the ingestion client directory structure as a reusable workflow and call them from the root, but allow people to be able to copy just the Ingestion Client if they want.

Whilst we are there, I think we should only check the json matches the bicep if someone changes the bicep file, because at the moment, when a new bicep tool is released the build breaks.

**Comment by pankopon** [comment]
@HenryvanderVegte There are several "[IngestionClient]" items open, are these actual customer issues or more general backlog work items? Is there a plan for them? Please update.

**Comment by HenryvanderVegte** [comment]
Hey @pankopon ,

all of them are backlog items, not customer issues. Need to check with @mahilleb-msft what we'll address and what's the timeline.

Thanks!

**Comment by pankopon** [comment]
@HenryvanderVegte In that case, would it be better to have them on an internal backlog, like it's done with SDK work items, instead of listing them here?

**Comment by HenryvanderVegte** [comment]
hey @pankopon , sorry for the late response. 

I agree, makes more sense to track them in an internal backlog. Will close all items with a comment. 

Thanks!

**Comment by HenryvanderVegte** [comment]
As discussed in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2521, moving item to internal backlog. Not an actual customer issue, but general backlog work item.
