### ISSUE TITLE
[BUG] Pronunciation assessment for Korean is always scoring high all of a sudden even in your own Azure AI Speech Studio

### ISSUE THREAD

**Issue by riiight** [Azure-Samples/cognitive-services-speech-sdk#2537]
Pronunciation assessment for Korean was working fine. Sometime in the past few days/weeks, it stopped working properly. Now, even if you completely mispronounce a word in Korean, it will score very high (90%+). I noticed this in my app using the SDK, but you can reproduce it easily on your own Azure AI Speech Studio (https://speech.microsoft.com/portal/811cc118d47c430faea884b0299c43f1/pronunciationassessmenttool).

**Step to Reproduce**

1) Go to Azure AI Speech Studio (https://speech.microsoft.com/portal/811cc118d47c430faea884b0299c43f1/pronunciationassessmenttool)
2) Choose Korean for the Pronunciation Assessment language.
3) Instead of using Sample 1, switch to "Your Own" and enter this for the test phrase: "북한".
4) Say "ha ha" or anything else. You will get a 90+ score.

**Expected behavior**

It should give a very low score.

**Comment by pankopon** [comment]
@yinhew @yulin-li Can you please check?

**Comment by wangkenpu** [comment]
@riiight Thanks for your feedback. It's a known issue for ko-KR of the default mode.

 We already have a premium model, but it's only for big customers (usage > 1k hours/month or commitment tires users).

**Comment by riiight** [comment]
@wangkenpu Does that mean it will not be fixed? Also, can you tell me what other languages suffer from this problem? Also, don't you think that developers should be made aware of this before they spend time trying to develop apps?

**Comment by wangkenpu** [comment]
@riiight After deep investigations, we have fixed the issue. The change will be deployed in 1 week.

**Comment by riiight** [comment]
@wangkenpu Thank you!
