### ISSUE TITLE
std::runtime_error Exception with an error code: 0x1f (SPXERR_CHANGE_CONNECTION_STATUS_NOT_ALLOWED)

### ISSUE THREAD

**Issue by 237370905** [Azure-Samples/cognitive-services-speech-sdk#254]
**Describe the bug**
I am using MicrosoftCognitiveServicesSpeech-iOS-1.5.0 on the iOS platform， there is chance ERROR:
	
	#0 Thread
	std::runtime_error
	Exception with an error code: 0x1f (SPXERR_CHANGE_CONNECTION_STATUS_NOT_ALLOWED)

	[call stack begin]
	MicrosoftCognitiveServicesSpeech 0x00000001035baf64 participant_get_property_bag + 154208 4 MicrosoftCognitiveServicesSpeech 0x0000000103611b60 participant_get_property_bag + 509532 5 MicrosoftCognitiveServicesSpeech 0x0000000103611968 participant_get_property_bag + 509028 6 MicrosoftCognitiveServicesSpeech 0x0000000103611ee0 participant_get_property_bag + 510428 7 MicrosoftCognitiveServicesSpeech 0x00000001036146d8 participant_get_property_bag + 520660 8 libsystem_pthread.dylib 0x000000020b2f02c0 <redacted> + 128 9 libsystem_pthread.dylib 0x000000020b2f0220 _pthread_start + 44 10 libsystem_pthread.dylib 0x000000020b2f3cdc thread_start + 4
	[call stack end]

Creation process

	SPXSpeechConfiguration *configuration = [[SPXSpeechConfiguration alloc]initWithSubscription:MICROSOFT_SPEECH_KEY region:MICROSOFT_SERVICE_REGION];
    configuration.speechRecognitionLanguage = tempFromLanguage;
    if (!configuration) {
        self.errorCode = NETWORK_ERROR_CODE;
        [self errorEndTaskState];
        return;
    }
    SPXAudioStreamFormat *format = [[SPXAudioStreamFormat alloc]initUsingPCMWithSampleRate:16000 bitsPerSample:16 channels:1];
    if (!format) {
        self.errorCode = NETWORK_ERROR_CODE;
        [self errorEndTaskState];
        return;
    }
    self.stream = [[SPXPushAudioInputStream alloc]initWithAudioFormat:format];
    if (!self.stream) {
        self.errorCode = NETWORK_ERROR_CODE;
        [self errorEndTaskState];
        return;
    }
    SPXAudioConfiguration *audioConfiguratian = [[SPXAudioConfiguration alloc]initWithStreamInput:self.stream];
    if (!audioConfiguratian) {
        self.errorCode = NETWORK_ERROR_CODE;
        [self errorEndTaskState];
        return;
    }
    self.speechRecognizer = [[SPXSpeechRecognizer alloc] initWithSpeechConfiguration:configuration audioConfiguration:audioConfiguratian];
    if (!self.speechRecognizer) {
        self.errorCode = NETWORK_ERROR_CODE;
        [self errorEndTaskState];
        return;
    }
    WEAKSELF
    [self.speechRecognizer addRecognizedEventHandler:^(SPXSpeechRecognizer * recognizer, SPXSpeechRecognitionEventArgs * args) {
        //do something
    }];
    [self.speechRecognizer addRecognizingEventHandler:^(SPXSpeechRecognizer * recognizer, SPXSpeechRecognitionEventArgs * args) {
        
    }];
    self.connection = [[SPXConnection alloc]initFromRecognizer:self.speechRecognizer];
    if (!self.connection) {
        self.errorCode = NETWORK_ERROR_CODE;
        [self errorEndTaskState];
        return;
    }
    [self.connection addConnectedEventHandler:^(SPXConnection * connection, SPXConnectionEventArgs * args) {
        weakSelf.connectioned = YES;
        [weakSelf.speechRecognizer startContinuousRecognition];
        [weakSelf speechRecorderStartTaskState];
    }];
    [self.connection addDisconnectedEventHandler:^(SPXConnection * connection, SPXConnectionEventArgs * args) {
  		//do something
    }];
    [self.connection open:YES];

Called after each use recognition

1、[SPXPushAudioInputStream close];
2、[SPXSpeechRecognizer stopContinuousRecognition];
3、[SPXConnection close];

**Comment by wolfma61** [comment]
Hi -

can you add a listener to the cancel event and see if any other error is reported before this?

You also do not need a connection object, once you have a recognizer, you can start recognition and the connection will be managed under the cover for you.

Wolfgang

**Comment by chlandsi** [comment]
Hi, in addition to what @wolfma61 said, could you also [turn on logging](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging#ios), and post the log file from when the error occurs? Thanks!

**Comment by wolfma61** [comment]
@237370905 - is there any more information on this issue you can give us?

**Comment by 237370905** [comment]
> @237370905 - is there any more information on this issue you can give us?

not more iusse informations

no expcetion occurred, no used SPXConnection

**Comment by wolfma61** [comment]
@237370905  - can you create a client log file?
what is the sessionid of the ongoing recognition, in what region?

**Comment by Checkroth** [comment]
I've run in to the same issue, running the Python SDK in a server. I believe in my case it is from incorrect usage of the Connection object.

Firstly, I am using the Connection object because I have another error that I periodically get -- Azure closes my SDK connection, and the cancel event is called with `WS_UNDERLYING_IO_ERROR`. I haven't been able to work around this issue, so I set up a Connection object so that I can at least see when the connection is being canceled, so I can maybe retry recognition.

My idea here was to simply re-open the connection, and re-call `start_continuous_recognition`. However, the Connection object throws `SPXERR_CHANGE_CONNECTION_STATUS_NOT_ALLOWED` when I try to call `open` on it a second time.

**Comment by chlandsi** [comment]
@Checkroth: This is not supported. If an error of any kind has occurred, the recognizer becomes invalid and a new one has to be constructed. The connection object can only be used to establish the initial connection, not to manually reconnect in case of a problem.

**Comment by Checkroth** [comment]
@chlandsi thanks for the response.

I did find that out on my own. I'm still using the Connection object so I can set an event callback specifically on dropped connections.

Would be good for a little more documentation surrounding these limitations. SDK Documentation and source code don't mention that at all.

**Comment by LeePepe** [comment]
Hi, I also met this issue in iOS.
```
libc++abi: terminating due to uncaught exception of type std::runtime_error: Exception with an error code: 0x1f (SPXERR_CHANGE_CONNECTION_STATUS_NOT_ALLOWED)
[CALL STACK BEGIN]

3   MicrosoftCognitiveServicesSpeech    0x0000000112b8507c GetModuleObject + 170600
4   MicrosoftCognitiveServicesSpeech    0x0000000112ca9c78 GetModuleObject + 1369700
5   MicrosoftCognitiveServicesSpeech    0x0000000112ca9c04 GetModuleObject + 1369584
6   MicrosoftCognitiveServicesSpeech    0x0000000112cabaa4 GetModuleObject + 1377424
7   MicrosoftCognitiveServicesSpeech    0x0000000112ca9ddc GetModuleObject + 1370056
8   MicrosoftCognitiveServicesSpeech    0x0000000112cacc18 GetModuleObject + 1381892
9   libsystem_pthread.dylib             0x00000001f525e06c _pthread_start + 136
10  libsystem_pthread.dylib             0x00000001f52590d8 thread_start + 8
```
I'm trying to start and close connection repeatedly, which will more easier to trigger this issue.
