### ISSUE TITLE
Streaming Text Input for TTS with Output as a Streaming Audio Buffer

### ISSUE THREAD

**Issue by atulyaatul1999** [Azure-Samples/cognitive-services-speech-sdk#2548]
I need to process streaming text input for text-to-speech (TTS) and receive the response as a streaming audio buffer with minimal latency. Is there any documentation available on how to achieve this? I tried accessing the documentation, but the GitHub link appears to be broken:

[GitHub Link](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/python/tts-text-stream)

**Comment by yulin-li** [comment]
this is fixed now, for streaming output see #2541

**Comment by pankopon** [comment]
Closed as fixed.
