### ISSUE TITLE
en-US-NovaMultilingualNeural no longer available

### ISSUE THREAD

**Issue by fabswt** [Azure-Samples/cognitive-services-speech-sdk#2550]
The docs about Azure TTS ([here on the Azure site](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/language-support?tabs=tts) or [here on GitHub](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/ai-services/speech-service/includes/language-support/tts.md) mention the following voice:

- **`en-US-NovaMultilingualNeural`, supported on region `swedencentral`**. I've been using it for months.

However, as of today, it fails like so:

> AZURE_SPEECH_API_REGION: swedencentral
> Speech synthesis canceled: CancellationReason.Error
> Error details: Connection was closed by the remote host. Error code: 1007. Error details: Unsupported voice en-US-NovaMultilingualNeural. USP state: TurnStarted. Received audio size: 0 bytes.

It's unclear whether it's an temporary error or if that voice has been removed for good (which would make the docs outdated.)

I understand that the OpenAI voices are in preview. Even then, it's annoying if a voice is removed without warning. The issue caused loss of service in production.

So, to recap:

- Observed: voice `en-US-NovaMultilingualNeural` is gone from region Sweden Central.
- Expected: that voice should either still be available, or the docs updated to reflect it.

FYI, as an alternative, I was able to get `en-US-NovaTurboMultilingualNeural` (mind the 'Turbo') on region West Europe to work as a replacement. I'm not sure when it was introduced.

---

P.S.: the Python script used to test and demonstrate the above

```python
"""
python3 azure_tts_minimal.py
"""

import os
import azure.cognitiveservices.speech as speechsdk
import dotenv

dotenv.load_dotenv()

def create_tts(content, output_file):
    speech_config = speechsdk.SpeechConfig(
        subscription=os.getenv("AZURE_SPEECH_API_KEY"),
        region=os.getenv("AZURE_SPEECH_API_REGION")
    )
    print(f"AZURE_SPEECH_API_REGION: {os.getenv('AZURE_SPEECH_API_REGION')}")
    
    """
    As of 2024-08-21:
    - "en-US-NovaMultilingualNeural" on Sweden Central is no longer available
      and -- no announcement about it!
    - "en-US-NovaTurboMultilingualNeural" is available on West Europe and works
      fine.
    """
    # speech_config.speech_synthesis_voice_name = "en-US-NovaTurboMultilingualNeural"
    speech_config.speech_synthesis_voice_name = "en-US-NovaMultilingualNeural"

    audio_config = speechsdk.audio.AudioOutputConfig(filename=output_file)
    
    synthesizer = speechsdk.SpeechSynthesizer(speech_config=speech_config, audio_config=audio_config)
    
    result = synthesizer.speak_text_async(content).get()
    
    if result.reason == speechsdk.ResultReason.SynthesizingAudioCompleted:
        print(f"Speech synthesized and saved to {output_file}")
    elif result.reason == speechsdk.ResultReason.Canceled:
        cancellation_details = result.cancellation_details
        print(f"Speech synthesis canceled: {cancellation_details.reason}")
        if cancellation_details.reason == speechsdk.CancellationReason.Error:
            print(f"Error details: {cancellation_details.error_details}")
    else:
        print(f"Speech synthesis failed: {result.reason}")
        if cancellation_details.reason == speechsdk.CancellationReason.Error:
            print(f"Error details: {cancellation_details.error_details}")

create_tts("Hello, world!", "output.wav")
```

**Comment by yulin-li** [comment]
There was a service regression and it should recover now
