### ISSUE TITLE
Trying to use Python SDK azure-cognitiveservices-speech  with webm container on Mac OSX M1

### ISSUE THREAD

**Issue by neeagl** [Azure-Samples/cognitive-services-speech-sdk#2556]
Installed the latest version of gstreamer on Mac using https://gstreamer.freedesktop.org/download/#macos
but keep getting SPXERR_GSTREAMER_NOT_FOUND_ERROR

Please suggest a fix or a possible workaround.

**Comment by pankopon** [comment]
Hi, unfortunately compressed audio is only supported with GStreamer on Windows and Linux, see
https://learn.microsoft.com/azure/ai-services/speech-service/how-to-use-codec-compressed-audio-input-streams?pivots=programming-language-python
So you will have to convert any compressed audio to PCM before it can be used as Speech SDK input on macOS.
