### ISSUE TITLE
FATAL error caused by SDK 1.40.0 with jvm crash

### ISSUE THREAD

**Issue by lhbyte** [Azure-Samples/cognitive-services-speech-sdk#2572]
**Describe the bug**
JVM crashes after running TTS for a few days

**To Reproduce**
crash randomly

**Expected behavior**
Fatal Error does not appear.

**Version of the Cognitive Services Speech SDK**
SpeechSDK-Linux-1.40.0

**Platform, Operating System, and Programming Language**
- OS: CentOS Linux release 7.8.2003
- Hardware: x64, x86, ARM
- Programming language: java
- 0penSSL: 1.1.1u 

**error stack frame**
``` 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f9f93af6009, pid=32200, tid=140323025278720
#
# JRE version: Java(TM) SE Runtime Environment (8.0_40-b26) (build 1.8.0_40-b26)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.40-b25 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libMicrosoft.CognitiveServices.Speech.core.so+0x1e1009]
#
# Core dump written. Default location: /data/service/outbound/core or core.32200
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

**Comment by lhbyte** [comment]
![ae3e5f9282968af38dec216f1992f9e](https://github.com/user-attachments/assets/4dd0bff6-2c1b-4e1a-8bf1-d0f74ea397fe)

**Comment by pankopon** [comment]
> OS: CentOS Linux release 7.8.2003

CentOS 7 is unsupported since its EOL on June 30, 2024 and the Speech SDK 1.40.0 release:
https://www.redhat.com/topics/linux/centos-linux-eol
https://learn.microsoft.com/azure/ai-services/speech-service/releasenotes?tabs=speech-sdk#speech-sdk-140-2024-august-release

Current supported Linux environments:
https://learn.microsoft.com/azure/ai-services/speech-service/quickstarts/setup-platform?tabs=linux&pivots=programming-language-java#platform-requirements

**Comment by lhbyte** [comment]
We recently switched to Speech SDK 1.38.0, but still encountered Fatal errors.
Except for the SDK versoion, all other information is consistent with this feedback.
The error message is as follows:



#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fa83e3b5eb8, pid=2850, tid=140359522543360
#
# JRE version: Java(TM) SE Runtime Environment (8.0_40-b26) (build 1.8.0_40-b26)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.40-b25 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libcrypto.so.10+0x144eb8]  ASN1_item_verify+0x38
#
# Core dump written. Default location: /data/service/offlinetask/cti-outbound/core or core.2850
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

---------------  T H R E A D  ---------------

Current thread is native thread

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000004

Registers:
RAX=0x0000000000000000, RBX=0x00007fa7ff7b5750, RCX=0x00007fa84c096820, RDX=0x0000000000000000
RSP=0x00007fa7ff7b5420, RBP=0x00007fa84805d030, RSI=0x0000000000000000, RDI=0x00007fa83e6b61e0
R8 =0x00007fa84805d030, R9 =0x0000000000000000, R10=0x0000000000000014, R11=0x00007fa95cc01590
R12=0x00007fa84805d030, R13=0x00007fa848063ed0, R14=0x00007fa7ff7b5750, R15=0x00007fa8480d0940
RIP=0x00007fa83e3b5eb8, EFLAGS=0x0000000000010206, CSGSFS=0x0000000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

**Comment by lhbyte** [comment]
We recently switched to Speech SDK 1.38.0, but still encountered Fatal errors.
Except for the SDK versoion, all other information is consistent with this feedback.
The error message is as follows:



```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fa83e3b5eb8, pid=2850, tid=140359522543360
#
# JRE version: Java(TM) SE Runtime Environment (8.0_40-b26) (build 1.8.0_40-b26)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.40-b25 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libcrypto.so.10+0x144eb8]  ASN1_item_verify+0x38
#
# Core dump written. Default location: /data/service/offlinetask/cti-outbound/core or core.2850
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

---------------  T H R E A D  ---------------

Current thread is native thread

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000004

Registers:
RAX=0x0000000000000000, RBX=0x00007fa7ff7b5750, RCX=0x00007fa84c096820, RDX=0x0000000000000000
RSP=0x00007fa7ff7b5420, RBP=0x00007fa84805d030, RSI=0x0000000000000000, RDI=0x00007fa83e6b61e0
R8 =0x00007fa84805d030, R9 =0x0000000000000000, R10=0x0000000000000014, R11=0x00007fa95cc01590
R12=0x00007fa84805d030, R13=0x00007fa848063ed0, R14=0x00007fa7ff7b5750, R15=0x00007fa8480d0940
RIP=0x00007fa83e3b5eb8, EFLAGS=0x0000000000010206, CSGSFS=0x0000000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e
```

**Comment by lhbyte** [comment]
@pankopon Can you help me take a look at this issue
