### ISSUE TITLE
SpeechSynthesizer fires SynthesisCompleted too early

### ISSUE THREAD

**Issue by PeteK68** [Azure-Samples/cognitive-services-speech-sdk#258]
**Describe the bug**
Instance of `SpeechSynthesizer` fires the `SynthesisCompleted` event before the end of output of the audio.

**To Reproduce**
1. Create an instance of `SpeechSynthesizer` with default output.
    1. `var synthesizer = new SpeechSynthesizer(config, AudioConfig.FromDefaultSpeakerOutput())`
1. Subscribe to the `SynthesisCompleted` event.
    1. `synthesizer.SynthesisCompleted += Synthesizer_SynthesisCompleted;`
1. Synthesize some long text.
    1. `await synthesizer.SpeakTextAsync(longText).ConfigureAwait(false);`

**Expected behavior**
Expected to receive the `SynthesisCompleted` event raised at the end of the audio playback.

**Version of the Cognitive Services Speech SDK**
- v1.5.1
- .NET Framework 4.7.2

**Platform, Operating System, and Programming Language**
 - OS: Windows 10, Version 1809 build 17763.437
 - building an x64 WPF application using C#

**Comment by lisaweixu** [comment]
Looking at the issue. Will get back to you soon.

**Comment by yinhew** [comment]
Thanks for the feedback.
The current SynthesisCompleted event is fired when the SDK received all the audio data from service side. The playback is usually not finished at this time point. We don't have an event indicating the end of playback yet.
We'll resolve this in next release, by either adding an additional event indicating the end of audio playback, or changing the SynthesisCompleted event to be fired when playback is done.

**Comment by jhakulin** [comment]
Closing the issue as fix will be in the next release. Let us know if you see issues with that.

**Comment by juharris** [comment]
I don't see a fix in the JavaScript library (`"microsoft-cognitiveservices-speech-sdk": "1.16.0"`). Also the `onAudioEnd` event on `SpeakerAudioDestination` isn't firing for me.
Here's what I'm doing:
```TypeScript
import * as speechSdk from 'microsoft-cognitiveservices-speech-sdk'

...

this.ttsPlayer = new speechSdk.SpeakerAudioDestination()
this.ttsPlayer.onAudioEnd = (): void => {
    console.debug("onAudioEnd")
}
const audioConfig = speechSdk.AudioConfig.fromSpeakerOutput(this.ttsPlayer)
this.ttsPlayer.onAudioStart = (s): void => {
    console.debug("onAudioStart", s)
}
this.speechSynthesizer = new speechSdk.SpeechSynthesizer(this.azureSpeechConfig!, audioConfig)
this.speechSynthesizer.speakTextAsync(text, (r) => {
    console.debug("speakTextAsync result", r)
}, err => {
    console.error("Error with the Azure SpeechSynthesizer", err)
})
```

**Comment by livioenrico** [comment]
We are in the 2023 and this problem is not solved !

**Comment by MatanMd** [comment]
this problem is not solved !

**Comment by marcgille** [comment]
This problem is not solved.

**Comment by zhangolve** [comment]
This problem is not solved.

**Comment by falvarezco** [comment]
This problem is not solved.
