### ISSUE TITLE
[Multi-Device Conversation][DotNet] Cannot set display name/Nickname when join conversation.

### ISSUE THREAD

**Issue by maivanchuong95** [Azure-Samples/cognitive-services-speech-sdk#2588]
I tried to implement the code according to the example at the link: https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/csharp/dotnet/multi-device-conversation/helloworld/Program.cs. But when I set display name (nickname) " await conversationTranslator.JoinConversationAsync(conversation, displayName)". Then I catch the event "ParticipantsChanged" but in it I only get Id and DisplayName as "Host" or "Participant" but not the display name I set.
Is this problem due to my account subscription or is there a problem with my code?
Thanks.

**Comment by maivanchuong95** [comment]
When I catch the Transcribed or Transcribing event it's the same. Just get DisplayName="Host" or DisplayName="Participant 1"

**Comment by billylo1** [comment]
Any updates on this one.  The latest SDK still has this issue.
