### ISSUE TITLE
wpf sample not working

### ISSUE THREAD

**Issue by galastur** [Azure-Samples/cognitive-services-speech-sdk#259]
**Describe the bug**
I have fired up the WPF sample "Microsoft Speech SDK Speech Recognition Sample". I went into settings, input source: use microphone, recognition type: baseline model, region and language:
uksouth and English.. i have given my subscription key and hit start button. I will start talking and nothing will happen, when i press stop the same. the "Baseline Model Output" stills contains the same text "Start speech recognition using microphone in en-US language"

I will expect the baseline model output to display the speech to text conversation from my speaking.

Version of the Cognitive Services Speech SDK: 1.5.1.28

Windows 10 Pro x64
Programming language: C#

I have created a console app following this sample and it is working fine! thus I know it is not a problem with my microphone and/or azure (using the same key)
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-csharp-dotnet-windows

Thanks

**Comment by lisaweixu** [comment]
Hi galastur,

I am taking a look at this issue. I will get back to you by the end of today for sure.

-Wei

**Comment by lisaweixu** [comment]
The Cognitive Speech Services Speech SDK contains two dlls which are needed for any csharp applications. They are Microsoft.CognitiveServices.Speech.csharp.dll and Microsoft.CognitiveServices.Speech.core.  It looks that the second one is not being deployed to the output folder. The default output folder is "obj\amd64". 

To workaround the issue, go to "speechtotext-wpf" solution and right click it. And then go to Properties. And then go to the tab of Build. Under Output panel, there is a "Generate serialization assembly:" field. Select "Auto".  After that, rebuild the solution. The Microsoft.CognitiveServices.Speech.core should showsup under the output folder of "obj\amd64". 

I can get a correct recognition result show up on the screen from the microphone after that.

Sorry for your inconvenience. We will fix the project file in our next release.

**Comment by galastur** [comment]
Thanks, it is working now
