### ISSUE TITLE
Python client libraries

### ISSUE THREAD

**Issue by jtlz2** [Azure-Samples/cognitive-services-speech-sdk#26]
Is a Python SDK available/on the roadmap?

**Comment by wolfma61** [comment]
yes, we are going to do a Python SDK, but it is probably several month out ... 
in the near future we will have .netcore support on Linux, java on Windows and Linux
mid-term javascript
then python

Wolfgang

**Comment by wolfma61** [comment]
I forgot to add, some macOS, iOS work is also happening (objective-c/swift)

**Comment by nicolaspanel** [comment]
Hi @wolfma61,

Thanks for sharing this.

Do you have any ETA  ?  A [swig](http://www.swig.org) wrapper should be enough I think :)
Best regards
Nicolas

**Comment by nicolaspanel** [comment]
thanks @wolfma61  for the quick reply !

**Comment by nicolaspanel** [comment]
@wolfma61 thank you  (and the team) for the [python binding](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/python) !
I have a question though: is it possible to adjust `profanity` and `format` parameters described in https://docs.microsoft.com/en-us/azure/cognitive-services/Speech-Service/rest-apis#query-parameters

**Comment by chlandsi** [comment]
Hi @nicolaspanel,

1. The profanity level can't be adjusted at the moment, but the output format can be set using `speech_config.output_format = speechsdk.OutputFormat.Simple`. This only affects the json representation of the result (`result.json`), which contains the detailed information.
2. `recognize_once` is designed to recognize a single utterance, and it can't recognize for more than 15s. Hopefully, `start/stop_continuous_recognition` will serve your needs. Samples on how to use it are coming soon!
