### ISSUE TITLE
core dump occurred while testing C++ demo offline under linux

### ISSUE THREAD

**Issue by little-jack** [Azure-Samples/cognitive-services-speech-sdk#260]
**Describe the bug**
core dump occurred while testing C++ demo offline under linux

**To Reproduce**
1.Compile the demo code via g++ and run program。
2.Retry several times when an error occurs。

**Version of the Cognitive Services Speech SDK**
version 1.5.1-linux 

**Platform, Operating System, and Programming Language**
 - OS:ubuntu16.04
 - Hardware - x64
 - Programming language:  C++

**Additional context**
 
The contents of the core file：
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./test'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Unexpected size of section `.reg-xstate/11371' in core file.
#0  0x0000000000411ea2 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_get_use_count() const ()
[Current thread is 1 (Thread 0x7f30f224a700 (LWP 11371))]
(gdb) 

Terminal content：
MAIN MENU
1.) Speech recognition samples.
2.) Intent recognition samples.
3.) Translation samples.
4.) Speech synthesis samples.

Choice (0 to Exit): 1

SPEECH RECOGNITION SAMPLES:
1.) Speech recognition with microphone input.
2.) Speech recognition in the specified language and using detailed output format.
3.) Speech continuous recognition with file input.
4.) Speech recognition using customized model.
5.) Speech recognition using pull stream input.
6.) Speech recognition using push stream input.
7.) Speech recognition using microphone with a keyword trigger.

Choice (0 for MAIN MENU): 7
Say something starting with 'YourKeyword' followed by whatever you want...
RECOGNIZING KEYWORD: Text=hi well
RECOGNIZED KEYWORD: Text=hi well
SESSIONSTARTED: SessionId=5528a79a1eb643858939cbexxxd9eb0c
CANCELED: Reason=1
CANCELED: ErrorCode=5
CANCELED: ErrorDetails=Connection failed (no connection to the remote host). Internal error: 1. Error details: -3. Please check network connection, firewall setting, and the region name used to create speech factory.
CANCELED: Did you update the subscription info?
SESSIONSTOPPED: SessionId=5528a79a1eb643858939cbexxxd9eb0c

SPEECH RECOGNITION SAMPLES:
1.) Speech recognition with microphone input.
2.) Speech recognition in the specified language and using detailed output format.
3.) Speech continuous recognition with file input.
4.) Speech recognition using customized model.
5.) Speech recognition using pull stream input.
6.) Speech recognition using push stream input.
7.) Speech recognition using microphone with a keyword trigger.

Choice (0 for MAIN MENU): Segmentation fault (core dumped)

**Comment by lisaweixu** [comment]
I am taking a look at this issue. Will get back to you with more information.

**Comment by lisaweixu** [comment]
You have 

**CANCELED: ErrorDetails=Connection failed (no connection to the remote host). Internal error: 1. Error details: -3. Please check network connection, firewall setting, and the region name used to create speech factory.**

Have you check your subscription key and region in  "auto config = SpeechConfig::FromSubscription"? 

I can have the above case running fine under Ubuntu 18.04 with correct subscription key and region.

**Comment by little-jack** [comment]
The program runs normally when there is no problem on the network.
But when I disconnect from the network, the program will go wrong like above and a core dump will occur when it is run a few times.

**Comment by lisaweixu** [comment]
I have reproduced the issue on a Ubuntu 18.04 box. This might has something to do how the SDK terminates the audio recording thread. We will fix the issue in a feature release.

**Comment by little-jack** [comment]
@lisaweixu By the way,the recognized accuracy is lower when i use the intent recognizer.How can i reach a higher accuracy?

**Comment by lisaweixu** [comment]
The service for Intent Recognizer right now uses an older version decoder than what Speech Recognizer uses. Uniting them into using the same one is on the road map. 

If you want, you can first sending the audio via Speech Recognizer and then feed the recognized text to the LUIS API. https://github.com/Azure-Samples/cognitive-services-language-understanding

**Comment by little-jack** [comment]
@lisaweixu Thank you for your answer。

**Comment by BlueBlueBling** [comment]
@lisaweixu  Can you tell me when do you plan to fix this issue?
Thank you.

**Comment by wolfma61** [comment]
this is on the roadmap for the next 30 days
