### ISSUE TITLE
I wonder use speech service Java SDK and return detailed result, anyone can help me?

### ISSUE THREAD

**Issue by lizekui** [Azure-Samples/cognitive-services-speech-sdk#261]
When I use speech service SDK, I can only analyze wav file content info, rather than some valuable words' time offset and confidence. 

I know REST method can return info above [when config is 'detailed'], but my wav files are more than 15 sec , so I have to use SDK method.

I found in Java there is a method in Java SDK: com.microsoft.cognitiveservices.speech.SpeechConfig,  and the methods below:

`import com.microsoft.cognitiveservices.speech.OutputFormat;`
`config.setOutputFormat(OutputFormat arg);`

but I didn't find out some clue to instantiate the type OutputFormat to 'detailed'

I also found current OutputFormat is Simple....
`System.out.println(recognizer.getOutputFormat());`

Anyone can help me? Thanks firstly~

**Comment by chlandsi** [comment]
This should work:
```
import com.microsoft.cognitiveservices.speech.OutputFormat;
SpeechConfig s = SpeechConfig.fromSubscription(...);
s.setOutputFormat(OutputFormat.Detailed);
```

**Comment by lizekui** [comment]
Dear bro chlandsi, you are genius! @chlandsi 
It really works fine, I search some methods could solve my problem according to your perfect codes. Thanks again!
