### ISSUE TITLE
Unable to find the file generated using translation 

### ISSUE THREAD

**Issue by rohanpandey** [Azure-Samples/cognitive-services-speech-sdk#262]
I have been able to synthesize the audio file while using speech to speech from one language to the other in python. I am unable to locate the audio file that is generated as a result. Any help?
![image](https://user-images.githubusercontent.com/31413869/59228091-920b3580-8bf4-11e9-9bd7-d2f4abcfe74e.png)

**Comment by jhakulin** [comment]
Thanks for the question,

I do not think you are able to get audio file directly but you can get audio from TranslationSynthesisResult as specified below (example for C#):
https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.translation.translationsynthesisresult.getaudio?view=azure-dotnet#Microsoft_CognitiveServices_Speech_Translation_TranslationSynthesisResult_GetAudio

**Comment by chlandsi** [comment]
The synthesized audio is available as the `.result.audio` property of the event that is delivered to the callback function to the `synthesizing` callback of a `TranslationRecognizer`. Please have a look at [this example](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/6f86952cfd3bedf85cf265de9cc3bc4e006dc53b/samples/python/console/translation_sample.py#L110) on how to get the data.

**Comment by rohanpandey** [comment]
@chlandsi this is the exact sample and isn't specifying how I can play or get the audio file generated as a result of the translation.

**Comment by chlandsi** [comment]
Playing the synthesized audio from translation is not part of the SDK; how to do this depends on your system. The audio returned in the callback is PCM-encoded WAV audio with a RIFF header in a python `bytes` object; you can save it to a file and play it from there, or play it from memory with an appropriate audio library. This callback will save the audio to a `.wav` file:

```
    def synthesis_callback(evt):
        """
        callback for the synthesis event
        """
        print('SYNTHESIZING {}\n\treceived {} bytes of audio. Reason: {}'.format(
            evt, len(evt.result.audio), evt.result.reason))
        if evt.result.reason == speechsdk.ResultReason.SynthesizingAudio:
            try:
                with open('out.wav', 'wb') as wavfile:
                    wavfile.write(evt.result.audio)
            except Exception as e:
                print(f'could not write to file: {e}')
```

**Comment by rohanpandey** [comment]
@chlandsi I'm unable to generate the audio file for the same using this method.

**Comment by chlandsi** [comment]
@rohanpandey Can you share some more detailed information about the issue? Is there any output or error message? Is the file created, and if so, what are the contents?

**Comment by rohanpandey** [comment]
@chlandsi the audio file is getting generated. However, the output is not the file expected. I'm giving a 2-minute audio as input and getting a 6-second file as an output.

**Comment by chlandsi** [comment]
Thanks for the clarification. The `synthesis_callback` is called for each utterance in the input audio, so it is presumably called multiple times for a longer audio file, and if the output file name doesn't change, it is overwritten each time. If that is what actually happens in your case should be visible from the console output (e.g., do you see multiple instances of something like `SYNTHESIZING ... Reason: ResultReason.SynthesizingAudio`?). How to handle this is up to your application -- probably the easiest way to save all the audio files would be to have a global variable that counts the utterances and include the current count in the file name. 

Closing the issue, since this is not an SDK issue.
