### ISSUE TITLE
Speech to text produced transcription Offset is wrong

### ISSUE THREAD

**Issue by aahmad-btit** [Azure-Samples/cognitive-services-speech-sdk#2622]
Logs where you can see the issue of resetting Offset:
[recording.log](https://github.com/user-attachments/files/17311488/recording.log)
[final-compiled.log](https://github.com/user-attachments/files/17312318/final-compiled.log)

I used Javascript speech SDK to produce transcript from MediaRecorder.
Repos code that I have used and their events: 
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/javascript/browser/from-microphone

Audio file:
[audio.webm](https://github.com/user-attachments/assets/b6074c8a-28f5-4a49-9aa8-11585ce31345)

Here is the transcript
[transcript.json](https://github.com/user-attachments/files/17312006/transcript.json)

**Describe the bug**
I record audio and transcribe text using Azure speech to text SDK and store it for further use. I noticed that after sometime of recording the produced transcript Offset got reset and starts over again from beginning. Expected behavior is that Offset must be in increasing order progressively. A phrase offset can not be lesser than previous phrase offset.

You can see the issue in attached recording.log file, I have also attached another one that I have briefed in log file final-compiled.log
you will see the issue clearly that between two phrases new connection is instantiated and then later produced offset has been reset and starts over again.
final-compiled.log is the brief of recording.log

**Expected behavior**
Expected behavior is that Offset must be in increasing order progressively. A phrase offset can not be lesser than previous phrase offset.

**Version of the Cognitive Services Speech SDK**
Version: 1.40

**Platform, Operating System, and Programming Language**
 - OS: Windows
 - Hardware - x64
 - Programming language: JavaScript
 - Browser Chrome

**Comment by pankopon** [comment]
Closed since also reported as Azure incident, ref. 555331702.
