### ISSUE TITLE
SpeechRecognizer fires KeywordRecognized out of order with KeywordRecognizing

### ISSUE THREAD

**Issue by PeteK68** [Azure-Samples/cognitive-services-speech-sdk#264]
**Describe the bug**
the `SpeechRecognizer` fires the `Recognized` event, followed by `Recognizing`, followed by `Recognized` event again.

**To Reproduce**
1. Instantiate the keyword recognizer
    1. `keywordRecognizer = new SpeechRecognizer(config);`
1. Subscribe to the events, and log output to the console or debug window from each of these handlers.
    1. `keywordRecognizer.Recognized += KeywordRecognizer_Recognized;`
    1. `keywordRecognizer.Recognizing += KeywordRecognizer_Recognizing;`
1. Start keyword recognition with your keyword model
    1. `await keywordRecognizer.StartKeywordRecognitionAsync(model).ConfigureAwait(false);`
1. Activate the keyword by speaking something, followed by a query in the same breath
    1. Say "Ok, computer, what time is it?" and notice that `Recognized` gets called prior to `Recognizing`.

**Expected behavior**
I expect the `Recognized` event to be fired after the SDK has picked up the keyword, and the user has finished speaking.

**Version of the Cognitive Services Speech SDK**
- v1.5.1
- .NET Framework 4.7.2

**Platform, Operating System, and Programming Language**
- OS: Windows 10, Version 1809 build 17763.437
- building an x64 WPF application using C#

**Comment by BrianMouncer** [comment]
Thank you for reporting this issue.

From the times I have used the Keyword Recognizer, I would expect multiple "Recognized" and "Recognizing" events to come in, but if you look at the "Result.Reason" you will see several event of different types (Microsoft.CognitiveServices.Speech.ResultReason).

In the simplest case, I would expect to see a "Recognizing" followed by a "Recognized" event for the Keyword, then several "Recognizing" events for the different "hypothesized" recognitions, followed by a final "Recognized" event for the final recognition result.  So it is expected that you could see a "recognized" event before the user has finished speaking.

If you have multiple utterances in the audio, this pattern will repeat multiple times, and if you are using the "intent" or "translator" version of the keyword spotter, then you may also see a series of additional recognizing and recognized events for each of the intent or translations.  You will want to examine the "Result.Reason" of each event to see what the source of the event is.

If you are seeing something different, or I misunderstood your question, then please let me know.

Thanks,

Brian.
