### ISSUE TITLE
How to get the results of batch synthesis avatar generation if I pass a batch of texts as input

### ISSUE THREAD

**Issue by shivjiachnet** [Azure-Samples/cognitive-services-speech-sdk#2644]
As per the official documentation, we can send a batch of texts for avatar generation. But the output result schema mentions only one download url. How to get the download url for all the avatars in this case?

Docs link for referral - https://learn.microsoft.com/en-us/azure/ai-services/speech-service/text-to-speech-avatar/batch-synthesis-avatar#get-batch-synthesis

**Comment by yulin-li** [comment]
Hi, in this case you need to use your own blob as output destination (search `properties.destinationContainerUrl` in [the doc](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/text-to-speech-avatar/batch-synthesis-avatar-properties#batch-synthesis-job-properties))

The output video files are uploaded to the same folder, e.g., `0001.mp4`, `0002.mp4`, etc

**Comment by shivjiachnet** [comment]
That was immensely helpful, thanks!

**Comment by shivjiachnet** [comment]
Hi, we tried by passing our blob storage container url. The job gets created successfully, but the status remains in NotStarted for quite long and does not progress.

**Comment by yulin-li** [comment]
We are checking this issue
