### ISSUE TITLE
 Issue with developing a Chrome plugin using Microsoft Speech SDK for speech-to-text functionality. 

### ISSUE THREAD

**Issue by ramaboya** [Azure-Samples/cognitive-services-speech-sdk#2646]
We are facing an issue with developing a Chrome plugin using Microsoft Speech SDK for speech-to-text functionality. 

**Describe the bug**

Speech needs to be recognized even though we have provided all parameters and initialsed everything correctly.

The same code base works fine in JavaScript and Chrome Browser.

But when we target CHROME Browser PLUGIN  it fails to detect speech.

**To Reproduce**

Build sample chrome plugin with Microsoft Speech SDK example.

Stack Trace
content.js:4 (anonymous function)
// Load the Speech SDK from Microsoft's CDN
const script = document.createElement('script');
script.src = "https://aka.ms/csspeech/jsbrowserpackaged";
document.head.appendChild(script);
 
script.onload = function() {
	// Replace these with your own Azure Speech API key and region
	const subscriptionKey = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
	const serviceRegion = 'eastus';
 
	// Configure the speech recognizer
	const speechConfig = SpeechSDK.SpeechConfig.fromSubscription(subscriptionKey, serviceRegion);
	const audioConfig = SpeechSDK.AudioConfig.fromDefaultMicrophoneInput();
	const recognizer = new SpeechSDK.SpeechRecognizer(speechConfig, audioConfig);
 
	// Start the speech recognition
    recognizer.recognizeOnceAsync(result => {
    	const recognizedText = result.text;
    	alert(`Recognized: ${recognizedText}`);
    	
    	// Optionally, you can display the recognized text in the popup
        chrome.runtime.sendMessage({ action: "updatePopup", text: recognizedText });
	});
};
 
// Listen for messages from the content script to update the popup
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
	if (message.action === "updatePopup") {
        document.getElementById('recognizedText').textContent = `Recognized: ${message.text}`;
	}
});
 
Refused to load the script 'https://aka.ms/csspeech/jsbrowserpackaged' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
 

**Expected behavior**

Speech should be recognized in Chrome web browser

**Version of the Cognitive Services Speech SDK**

Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**

 - OS: [e.g. Windows, ] 
 - Hardware - x64, x86, ARM, ...
 - Programming language: JavaScript, 
 - Browser [e.g. Chrome]

**Comment by pankopon** [comment]
The issue with using the SDK inside a Chrome browser plugin has been addressed in Azure service incident ID 570133199. Please contact the assigned support engineer for any details.
