### ISSUE TITLE
Unable to fetch the text generated from the speech to text.

### ISSUE THREAD

**Issue by rohanpandey** [Azure-Samples/cognitive-services-speech-sdk#265]
I am getting the appropriate text from the audio file ( Using speech_recognize_continuous_from_file() function). But I'm unable to get the text generated and dump into a text file. Any help will be appreciated.
![image](https://user-images.githubusercontent.com/31413869/59336716-acd8c980-8d1c-11e9-9a11-6781ad7f1f0a.png)

**Comment by chlandsi** [comment]
This is achieved by concatenating the results in the callback function to the `recognized` signal. This is an example extending the `speech_recognize_continuous_from_file()` sample to get you started:
```
    transcriptions = []

    def recognized_cb(evt):
        nonlocal transcriptions
        transcriptions.append(evt.result.text)

    speech_recognizer.recognized.connect(recognized_cb)

    # Start continuous speech recognition
    speech_recognizer.start_continuous_recognition()
    while not done:
        time.sleep(.5)

    print(transcriptions)
```

**Comment by rohanpandey** [comment]
@chlandsi This seems to do the trick. Thank you so much for your help and quick support.
