### ISSUE TITLE
Unable to create new user signature using https://signature.centralus.cts.speech.microsoft.com/api/v1/Signature/GenerateVoiceSignatureFromByteArray

### ISSUE THREAD

**Issue by Dogmus** [Azure-Samples/cognitive-services-speech-sdk#266]
[tesfile.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/3281486/tesfile.zip)

Good day,  i have one issue with a  https://signature.centralus.cts.speech.microsoft.com/api/v1/Signature/GenerateVoiceSignatureFromByteArray service. While working on prototype app for the Roobo device i decided to implement possibility to enroll user directly from the device(record and audio and send it to the service) but for some reason every time i am getting bad request with description "Not enough words". I've tried to record different files with lengths up to 5 min and result is the same.  But when i send these exact files to the Speach-to-Text service I've receive a proper transcription, so looks like file specification is correct.  If someone can help or share some findings it would be really great!   Thanks in advance!

**Comment by jhakulin** [comment]
Thanks for feedback, we will take a look.

**Comment by sarahlume** [comment]
Is your audio captured from the Roobo device? The audio volume is too low for signature generation.
To control the signature service, we recommended to use the close talk audio. You can use PC microphone to capture the audio.

If it still doesn't work, Let us know.

**Comment by Dogmus** [comment]
@sarahlume  Yeah, seem like this was the case, i imported my Audio file to Audacity and amplify it volume, after this file was processed correctly.  Now i just need to figure out how to either increase volume in the roobo device or amplify file from Java code :)  Thank You very much for fast feedback!
