### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by JohnnyHooo** [Azure-Samples/cognitive-services-speech-sdk#268]
SPXSpeech - SPXTranslationRecognizer
Why does Chinese have so many Spaces and no punctuation

**Comment by BrianMouncer** [comment]
I recently noticed a change in the character width of the "?", and in some languages (German/French) an extra space is added at the end of a sentence, but have not seen the extra space issue for Chinese.

I'm having someone look into this in more detail and see what introduced this change recently.

@JohnnyHooo, It would be helpful if you gave me an example of your English and Chinese sentences, and what part is not correct. this will help the translation team to narrow down the cause.

Thanks,

Brian.
