### ISSUE TITLE
embedd speech tts model loads error 

### ISSUE THREAD

**Issue by positive666** [Azure-Samples/cognitive-services-speech-sdk#2682]
Choose a number (or none for exit) and press Enter: 11
Enter some text that you want to speak, or none for exit.
> hello
CANCELED: Reason=1
CANCELED: ErrorCode=Synthesis started.
12
CANCELED: ErrorDetails="Local TTS speak failed, with TTS error code = EMBEDDED_TTS_ERROR_VOICES_HAVE_SAME_NAME. Local TTS engine not initialized, check data location and storage permissions."
Enter some text that you want to speak, or none for exit.
> a

**Comment by pankopon** [comment]
Hi, sounds like your `EMBEDDED_SPEECH_SYNTHESIS_VOICE_PATH` / `EmbeddedSpeechSynthesisVoicePath` points to a directory tree that contains two or more TTS voices with the same name (possibly different versions of the same voice). Try and set the path to a single voice folder. If that works, check the previous path for voices that may share the same name, and move duplicates out as necessary.

For embedded speech specific questions, please prefer using the support email address (that you presumably received when you got access to the models).

**Comment by pankopon** [comment]
Closed as answered since no further questions received.
