### ISSUE TITLE
Numerical problem of speech recognizer in Chinese

### ISSUE THREAD

**Issue by BlueBlueBling** [Azure-Samples/cognitive-services-speech-sdk#269]
Language: zh-CN

I hope that the recognized text of speech recognizer is numerical string in Arabic numerals.
For example,
“打开编号11的灯”
“设置编号11的灯亮度为50”

But when I test, the result sometimes in spoken form,
for example,
“打开编号一一的灯”
“设置编号一一的灯亮度为五十”
sometimes in Arabic numerals,
for example,
“打开编号12345678的灯”

How can I make the result always in Arabic numerals?
Thank you.

**Comment by lisaweixu** [comment]
You can have the 一二三 四五六 back from the "Lexical" field in the Nbest result.

You need to turn on the detailed result from your speech config object as follows.
**_auto config = SpeechConfig::FromSubscription("YourSubscriptionKey", "YourRegion");
config->SetServiceProperty("format", "detailed", ServicePropertyChannel::UriQueryParameter);_**

The nbest result can found at the recognized result as follows:

**_auto json = e.Result->Properties.GetProperty(PropertyId::SpeechServiceResponse_JsonResult);
 where e is SpeechRecognitionEventArgs_**


After applying the above changes to your code, you can view the following

 name='RESULT-Json'; value='{"Duration":33700000,"NBest":[{"Confidence":0.9999812841415405,"Display":"打开编号 123456 的灯。","ITN":"打开 编号 一二三 四五六 的 灯","Lexical":"打开 编号 一二三 四五六 的 灯","MaskedITN":"打开编号 123456 的灯"},{"Confidence":0.9999489784240723,"Display":"打开 编号 一二三 四五六 的 登","ITN":"打开 编号 一二三 四五六 的 登","Lexical":"打开 编号 一二三 四五六 的 登","MaskedITN":"打开 编号 一二三 四五六 的 登"},{"Confidence":0.999945878982544,"Display":"打开 编号 一二三 四五六 地 灯","ITN":"打开 编号 一二三 四五六 地 灯","Lexical":"打开 编号 一二三 四五六 地 灯","MaskedITN":"打开 编号 一二三 四五六 地 灯"},{"Confidence":0.9999433755874634,"Display":"打开 编号 一二三 四五六 的 蹬","ITN":"打开 编号 一二三 四五六 的 蹬","Lexical":"打开 编号 一二三 四五六 的 蹬","MaskedITN":"打开 编号 一二三 四五六 的 蹬"},{"Confidence":0.9999444484710693,"Display":"打开 编号 一二三 四五六 的 瞪","ITN":"打开 编号 一二三 四五六 的 瞪","Lexical":"打开 编号 一二三 四五六 的 瞪","MaskedITN":"打开 编号 一二三 四五六 的 瞪"}],"Offset":700000,"RecognitionStatus":"Success"}'

The above example code is in C++. The syntax for other programming languages are similar.  The complete API reference are [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk).

**Comment by BlueBlueBling** [comment]
@lisaweixu  Thank you very much for your reply.
Can you explain the difference between "Display"/ITN"/"Lexical"/"MaskedITN"?
And I want to have "编号1""设置为50" back, not"编号一""设置为五十".
Is there any other way to alway have "编号1""设置为50" back?
Thank you.

**Comment by mahilleb-msft** [comment]
Here's some documentation on the returned JSON:

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-speech-to-text#response-parameters

**Comment by BlueBlueBling** [comment]
Thank you anyway.
I will replace all "一二三"  with "123" by coding.
Close this issue.
