### ISSUE TITLE
ALSA lib error

### ISSUE THREAD

**Issue by eryzerz** [Azure-Samples/cognitive-services-speech-sdk#2699]
I get an ALSA lib error and cannot get an audio response when running the program on a docker container (local & gcp). I tried a workaround to enable sound card access on container by adding asound.conf, like this:
```
pcm.null {
  type null
}
pcm.!default {
  type plug
  slave.pcm null
}
```
but it doesn't solve the issue, only removes the error but the client still couldn't get an audio response. 

Here's my Dockerfile:
```Dockerfile
# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app
# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore
# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out
# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
# Install audio library
RUN apt-get update && apt-get install -y libasound2 && rm -rf /var/lib/apt/lists/*
COPY --from=build-env /app/out .
COPY appsettings*.json ./
COPY firebase.json ./
EXPOSE 8080
ENTRYPOINT ["dotnet", "Project.dll"]
```

and the error log:
```bash
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
```

**Platform, Operating System, and Programming Language**

 - OS: Windows, MacOS
 - Hardware: x64, ARM
 - Programming language: C#
 - Browser: Chrome

**Comment by pankopon** [comment]
Hi, this is a general container setup question, not Speech SDK specific. Please check guides like
https://github.com/mviereck/x11docker/wiki/Container-sound:-ALSA-or-Pulseaudio
https://prateeksrivastav598.medium.com/playing-sound-in-docker-containers-a-step-by-step-guide-f7a06e246a35
https://stackoverflow.com/questions/52890474/how-to-get-docker-audio-and-input-with-windows-or-mac-host
though these typically presume that the **host** OS is Linux as well.
