### ISSUE TITLE
Post setting "AddDiarization" property to "true" in the batch transcription code, the call to PostTranscriptionAsync() fails with "This locale does not support diarization"

### ISSUE THREAD

**Issue by shmisra** [Azure-Samples/cognitive-services-speech-sdk#272]
I am using the batch transcription code from https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/csharp

The purpose is to use Speaker Separation (Diarization). 
Per https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription the "AddDiarization" property can be set. 

{
 "recordingsUrl": "<URL to the Azure blob to transcribe>",
 "models": [{"Id":"<optional acoustic model ID>"},{"Id":"<optional language model ID>"}],
 "locale": "<locale to us, for example en-US>",
 "name": "<user defined name of the transcription batch>",
 "description": "<optional description of the transcription>",
 "properties": {
   "AddWordLevelTimestamps" : "True",
   "AddDiarization" : "True"
 }
}

In the batch transcription code from https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/csharp, I did this: 

// File: transcription_definition.cs
        private TranscriptionDefinition(string name, string description, string locale, Uri recordingsUrl, IEnumerable<ModelIdentity> models)
        {
            this.Name = name;
            this.Description = description;
            this.RecordingsUrl = recordingsUrl;
            this.Locale = locale; // This is set to "en-US".
            this.Models = models;
            this.properties = new Dictionary<string, string>();
            this.properties.Add("AddWordLevelTimestamps", "True");
            this.properties.Add("AddDiarization", "True"); // <== I have set this property. 
        }

Post setting the "AddDiarization" property I get to see the exception below when we call PostTranscriptionAsync().

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at BatchClient.Program.Main(String[] args) in D:\csharp\program.cs:line 67

Inner Exception 1:
FailedHttpClientRequestException: This locale does not support diarization.

Though we have set the locale to "en-US", why does "This locale does not support diarization" appear?

**Comment by amitkumarshukla** [comment]
Thanks a lot for your question. We will get back to you.

**Comment by PanosPeriorellis** [comment]
There was an issue with the model deployment that we have since rectified.
