### ISSUE TITLE
How to correctly speech recognise from an audio file?

### ISSUE THREAD

**Issue by theonlygusti** [Azure-Samples/cognitive-services-speech-sdk#273]
I got the example that transcribes my voice direct from the microphone to work, but now I want to transcribe a file.

I tried

    using (var recognizer = new SpeechRecognizer(config, AudioConfig.FromWavFileInput(@"/Full/Path/To/File.wav")))
    {
        recognizer.Recognizing += (s, e) =>
        {
            Console.WriteLine($"RECOGNIZING: Text={e.Result.Text}");
        };

        recognizer.Recognized += (s, e) =>
        {
            if (e.Result.Reason == ResultReason.RecognizedSpeech)
            {
                Console.WriteLine(e.Result.Text);
            }
            else if (e.Result.Reason == ResultReason.NoMatch)
            {
                Console.WriteLine($"NOMATCH: Speech could not be recognized.");
            }
            else if (e.Result.Reason == ResultReason.Canceled)
            {
                var cancellation = CancellationDetails.FromResult(e.Result);
                Console.WriteLine($"CANCELED: Reason={cancellation.Reason}");

                if (cancellation.Reason == CancellationReason.Error)
                {
                    Console.WriteLine($"CANCELED: ErrorCode={cancellation.ErrorCode}");
                    Console.WriteLine($"CANCELED: ErrorDetails={cancellation.ErrorDetails}");
                    Console.WriteLine($"CANCELED: Did you update the subscription info?");
                }
            }
        };

        recognizer.Canceled += (s, e) =>
        {
            Console.WriteLine($"CANCELED: Reason={e.Reason}");

            if (e.Reason == CancellationReason.Error)
            {
                Console.WriteLine($"CANCELED: ErrorCode={e.ErrorCode}");
                Console.WriteLine($"CANCELED: ErrorDetails={e.ErrorDetails}");
                Console.WriteLine($"CANCELED: Did you update the subscription info?");
            }
        };

        recognizer.SessionStarted += (s, e) =>
        {
            Console.WriteLine("\nSession started event.");
        };

        recognizer.SessionStopped += (s, e) =>
        {
            Console.WriteLine("\nSession stopped event.");
            Console.WriteLine("\nStop recognition.");
        };

        await recognizer.StartContinuousRecognitionAsync();
    }

But I never get the file's transcript, the console prints only "Session started" and then exits.

How can I transcribe an audio file with `Microsoft.CognitiveServices.Speech`?

**Comment by mahilleb-msft** [comment]
Please take a look here -- https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/d79a4fa67017591fb0b6ab31e70ad9bf2a0d7d2f/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L171-L243

StartContinuousRecognitionAsync() merely starts to recognize, and then you're removing the recognizer.
You'll need to wait for your results, then eventually to StopContinousRecognitionAsync() and/or dispose.

Hope this helps, Mark

**Comment by jhakulin** [comment]
I will close the issue with the current resolution, let us know if you need more information.
