### ISSUE TITLE
How to correctly use python batch transcription transcriptions?

### ISSUE THREAD

**Issue by theonlygusti** [Azure-Samples/cognitive-services-speech-sdk#274]
I am using the python example for batch transcription.

I have set the variables in the code

```py
RECORDINGS_BLOB_URI = "https://myblob.blob.core.windows.net/my-container/"
SUBSCRIPTION_KEY = "my speech cognitive services key 1"
HOST_NAME = "uksouth.cris.ai"
```

I installed `swagger_client` for uksouth.

The only output I get when running the sample `main.py` is

```
Starting transcription client...
Deleting all existing completed transcriptions.
Creating transcriptions.
Checking status.
Transcriptions status: completed (this transcription): False, 0 running, 1 not started yet
Transcriptions status: completed (this transcription): False, 0 running, 2 not started yet
Transcriptions status: completed (this transcription): False, 1 running, 2 not started yet
Transcriptions status: completed (this transcription): False, 2 running, 2 not started yet
Transcriptions status: completed (this transcription): False, 3 running, 2 not started yet
Transcriptions status: completed (this transcription): False, 4 running, 2 not started yet
Transcriptions status: completed (this transcription): False, 5 running, 2 not started yet
Transcription failed.
Transcriptions status: completed (this transcription): True, 5 running, 2 not started yet
Press any key...
```

(I added an `elif transcription.status == "Failed":` clause of my own)

I also tried with a link pointing straight at one of my files

```py
RECORDINGS_BLOB_URI = "https://myblob.blob.core.windows.net/my-container/myaudio16bit16khz.wav"
```

but get basically the same output

```
Starting transcription client...
Deleting all existing completed transcriptions.
Creating transcriptions.
Checking status.
Transcriptions status: completed (this transcription): False, 0 running, 1 not started yet
Transcriptions status: completed (this transcription): False, 0 running, 2 not started yet
Transcriptions status: completed (this transcription): False, 1 running, 2 not started yet
Transcription failed.
Transcriptions status: completed (this transcription): True, 1 running, 2 not started yet
Press any key...
```

Why are the transcriptions failing?

**Comment by amitkumarshukla** [comment]
Thanks a lot for your question. We will get back to you asap.

**Comment by theonlygusti** [comment]
I figured out I was using the wrong URI.

I was meant to have used a generated SAS one.

**Comment by amitkumarshukla** [comment]
Great. Please let us know if you have any difficulty again. 

Thanks

**Comment by vishnureddy45** [comment]
Hi George/Amit,

I'm facing issues when trying to implement the Speech Services Batch Transcription API using Python. It would be really great if you can help us on this case.


Code:
[speech-to-text.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/5643130/speech-to-text.txt)

Error:

**---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-fa6651aa4dd2> in <module>
    200 
    201 if __name__ == "__main__":
--> 202     transcribe()

<ipython-input-2-fa6651aa4dd2> in transcribe()
    139     print(client)
    140     # create an instance of the transcription api class
--> 141     api = cris_client.DefaultApi(api_client=client)
    142 
    143     # Specify transcription properties by passing a dict to the properties parameter. See

AttributeError: module 'swagger_client' has no attribute 'DefaultApi'**
