### ISSUE TITLE
Text-To-Speech Example for Hololens Uwp

### ISSUE THREAD

**Issue by wassx** [Azure-Samples/cognitive-services-speech-sdk#275]
**Is your feature request related to a problem? Please describe.**
I was able to run TTS in the unity editor but it seems that it does not work on Hololens 1.

**Describe the solution you'd like**
Can you provide an example how to achieve TTS on the hololens please?

**Comment by jhakulin** [comment]
Thanks for your feedback,

Could you describe more the issue you see with Hololens ? Debugger logs for example.
Is it possible to provide sample code where the problem reproduces ?

**Comment by wassx** [comment]
Hi, sry for the sparse information. 
I built with unity 2019.1.4f1, xrtk, hololens 1 (x86)
Please find the log and the sample code below:
[UnityPlayer (2).log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/3313815/UnityPlayer.2.log)

[MainController.cs.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/3313822/MainController.cs.txt)

**Comment by yinhew** [comment]
Hi, Stefan

The text-to-speech API currently doesn't support directly play the output audio natively.
You can alternatively synthesize the speech to an audio file, and then playback the audio file with UWP API.
Here is the UWP sample code with such approach:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/uwp/texttospeech-uwp/texttospeech-uwp/MainPage.xaml.cs#L70

You can refer to it in your unity code.

Let me know if this still doesn't meet your requirement.

Thanks,
Yinhe

**Comment by wassx** [comment]
Ah ok thank you for the example. This will help! Thanks!

**Comment by yinhew** [comment]
The UWP sample above called some WinRT API, which should not be available in Unity project.
I wrote a Unity sample today, which calls the UnityEngine API to playback the audio:
[HelloWorld.cs.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/3321402/HelloWorld.cs.txt)
This should be more suitable for you to refer to.
The whole sample project will be put on this repo later.

**Comment by wassx** [comment]
Cool, thank you very much!

**Comment by wolfma61** [comment]
closing - new samples have also been published
