### ISSUE TITLE
the microsoft translate  app  is better than this speech translate sdk

### ISSUE THREAD

**Issue by hold-my-hand** [Azure-Samples/cognitive-services-speech-sdk#276]
I test with my iPhone iOS 12.0 
when I speak to microsoft translate  app , the answer is different with the speech translate sdk
and it is better, Are they different ?

I speak to my iOS and android app and got a wrong translate answer, both of them use the speech transalte sdk,but when I speak to the microsoft translate app, it is right

“今天星期几?”  is my test words
the speech translate sdk translate it "today week a new",it is wrong
microsoft translate  app translate it  "what day it is today?",it is right

**Comment by hold-my-hand** [comment]
I speak to my iOS and android app and got a wrong translate answer, both of them use  the speech transalte sdk,but when I speak to the microsoft translate app, it is right

**Comment by hold-my-hand** [comment]
“今天星期几?”  is my test words

**Comment by amitkumarshukla** [comment]
Thanks a lot for your question. We will get back to you asap.

**Comment by chriswendt1** [comment]
Hi @hold-my-hand , could you validate that the actual recognition of your utterance was correct? The translation system used by the SDK and by the app is the same. My suspicion would be that the recognition differed.

**Comment by hold-my-hand** [comment]
I record two videos
one is our app use speech translate sdk and other is microsoft translate app.
please review
[归档.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/3328207/default.zip)

**Comment by lisaweixu** [comment]
Hello @hold-my-hand ,

Thanks for using the Speech SDK.

I watched your two videos. I did not hear what you said to the Microsoft translation app.
The SDK and the Microsoft translation app are targeting the exact same service. 
Have you checked the audio recording on your app? Can you share the audio captured in your app and also the speech recognition results of the translation.

Have you done more tests in your app? I have been using the SDK for translating from Chinese to English on Windows. It has been working fine for me. I also have the Microsoft translation app installed on my iPhone.  I don't feel the translation results are too much different.

**Comment by hold-my-hand** [comment]
[归档.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/3332573/default.zip)
I record a test file
Both my app an Microsoft translation app recognition is correct. and my app translate is incorrect,Microsoft translation app the translation results is correct. can you test it ?

**Comment by StephenDai** [comment]
Hi guys,
  I got SAME problem on my app. “今天星期几” got "Today Week A few".
  I tried a lot of sentences and the results are good but this one is not correct.
  I am using region "eastasia".

**Comment by hold-my-hand** [comment]
@StephenDai  Our PM test with "今天周几","这件衣服多少钱",both got incorrect translate. But the 
Microsoft translation app is correct

**Comment by StephenDai** [comment]
@hold-my-hand You are right. I tried them and got incorrect results.

**Comment by hold-my-hand** [comment]
I tried to grab the package for translating SDK in my app, but it failed.

I use Charles Mac app to capture packet Microsoft translation app。 It use a websocket connect server
[Untitled.chls.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/3332693/Untitled.chls.zip)

**Comment by lisaweixu** [comment]
I will take a look at your package late today. 

Have you verify that your app on iPhone can capture audio correctly and consistently?

**Comment by hold-my-hand** [comment]
#pragma mark 音频质量通过此参数调整
-(AudioStreamBasicDescription)audioStreamBasicDescription{
    AudioStreamBasicDescription asbd;
    memset(&asbd, 0, sizeof(asbd));
    asbd.mSampleRate = 16000;            //采样率
    asbd.mFormatID = kAudioFormatLinearPCM;
    asbd.mFormatFlags = kLinearPCMFormatFlagIsSignedInteger | kAudioFormatFlagIsPacked;
    asbd.mChannelsPerFrame = 1;         //单声道
    asbd.mFramesPerPacket = 1;          //每一个packet一侦数据
    asbd.mBitsPerChannel = 16;          //每个采样点16bit量化
    asbd.mBytesPerFrame = (asbd.mBitsPerChannel / 8) * asbd.mChannelsPerFrame;
    asbd.mBytesPerPacket = asbd.mBytesPerFrame ;
    return asbd;
}

-(SPXPushAudioInputStream *)inputStream{
    if (!_inputStream) {
        NSUInteger mSampleRate =  self.record.audioStreamBasicDescription.mSampleRate;
        NSUInteger bitsPerSample = self.record.audioStreamBasicDescription.mBitsPerChannel;
        NSUInteger channels = self.record.audioStreamBasicDescription.mChannelsPerFrame;
        
        SPXAudioStreamFormat *format  =[[SPXAudioStreamFormat alloc] initUsingPCMWithSampleRate:mSampleRate bitsPerSample:bitsPerSample channels:channels];
        
        _inputStream = [[SPXPushAudioInputStream alloc] initWithAudioFormat:format];
    }
    return _inputStream;
}
-(void)write:(NSData *)data{
    if (_inputStream) {
        [_inputStream write:data];
    }
}

 I think it is correctly。

**Comment by hold-my-hand** [comment]
@lisaweixu can you help me find out the reason?

**Comment by hold-my-hand** [comment]
ok,today I find It is all correct
