### ISSUE TITLE
Need SDK to support Android4.4

### ISSUE THREAD

**Issue by StephenDai** [Azure-Samples/cognitive-services-speech-sdk#277]
Hello,
  I have a Android 4.4 product using Translate API which will no longer work on Oct 15. I need a SDK which can support Android 4.4 to migrate. (The product is not able to upgrade to later Android version).
  Or as an alertnative solution, I can use a websocket solution similar to Translate API. But I need to know the websocket endpoints speech service SDK is using. A guide or sample is required.
  Thanks!

**Comment by wolfma61** [comment]
Officially our minimal supported platform is API 23: Android 6.0 (Marshmallow)

We run test on Android 4.4.2 devices (API 19). We are trying to keep support for this API level, but it gets more difficult, although not the official supported lowest level API platform, it works...

Wolfgang

**Comment by StephenDai** [comment]
@wolfma61 do you mean latest SDK already passed test on Android API 19? All the cases?
If it's true, that's ok for me to have this unofficial support. :)

**Comment by wolfma61** [comment]
Speech SDK tests on Android are executed on a collection of devices. Android 4.4.2 devices are part of this mix and execute the same tests as later Android versions/devices. 
yes - all cases.

**Comment by StephenDai** [comment]
Thanks @wolfma61 !
I just tried latest SDK which can be built and run on Android4.4. (I was using v1.2 which can not build on 4.4 so I asked this question.)
Please close this issue. Thanks!

**Comment by wolfma61** [comment]
thank you ! glad it worked
Wolfgang
