### ISSUE TITLE
Chinese Recognition Results

### ISSUE THREAD

**Issue by shaohui93** [Azure-Samples/cognitive-services-speech-sdk#278]
Many < eos0 > < eos0 > symbols will be returned for Chinese recognition now, but not for English recognition.

**Comment by shaohui93** [comment]
SDK version is 1.5.1

**Comment by amitkumarshukla** [comment]
@shaohui93  Thanks a lot for reporting the issue. If you can tell me which platform you were running and possibly the sample app that you were using.

**Comment by shaohui93** [comment]
@amitkumarshukla I use the Android platform.  A demo using the Android SDK alone has caused the above problems.

**Comment by wolfma61** [comment]
there was a service issue that was fixed. Not sure if this is related.
Please try again, if you still have issues, please give us some more detail
(failed recognition, perhaps a sessionid etc)

thx
Wolfgang

**Comment by shaohui93** [comment]
That's all right.
