### ISSUE TITLE
Conversation Transcription does not work

### ISSUE THREAD

**Issue by Dogmus** [Azure-Samples/cognitive-services-speech-sdk#279]
Good day, currently i am working on a app to utilize Roobo device + conversation transcription possibilities. Everything was working fine till 26/06/2019, now when i start conversation transcription using SDK (on Android) i am either getting no results or $ref$, this happens in both my App and sample Androidapp (which should work perfectly fine) i am using CentralUS congnitive speech service(I can run user enrollment on this service without issues), i tried to delete and recreate this service several times but no luck(.

Can You please advice is there any issues with Service right now?

Thanks in advance!

**Comment by lisaweixu** [comment]
Hello Dogmus,

We did not see any issues on the service right now, as we and other users can access it without problem.

Here are documentations of how to use Conversation Transcription

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-conversation-transcription-service

And here is an example of how end users can call the Speech SDK APIs. Please note that SDK only supports pull/push data stream from the end users.
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/cpp/windows/console/samples/conversation_transcriber_samples.cpp

Could you share more details about how you are calling the APIs

**Comment by Dogmus** [comment]
Hi Wei!

Thank You for looking into this! I will try again on Monday( I will have two devices) and if still no luck I will share source code for the class that I use to call api.

Thanks once more and have a good weekend.

Best Regards
Evgeniy



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by lisaweixu** [comment]
Have a nice weekend, too.

**Comment by Dogmus** [comment]
Hi Wei,

I've tried to run Conversation transcription once more and it is still don't  work. I am using Java SDK for android from Sample APP, i think version is 1.5.1 (may release).   I was trying to find version 1.6 and try with it but didn't manage to do so, can You please send it to me?

[cid:897b4db5-ac7f-462a-9efb-7742518df6f5]

Thanks in advance!

Best Regards
Evgeniy
________________________________

**Comment by wolfma61** [comment]
all the download links on the documentation page are pointing to 1.6
maven packages for 1.6 are uploaded.
 please check again ...
where are you looking for the 1.6 packages and not able to find them?

**Comment by Dogmus** [comment]
Hi Wolfgang, i had a local maven issue, after i resolved it i was able to pull 1.6 from Maven repo and test it. With SDK version 1.6 everything works fine.  Thanks everyone for the help, closing this ticket :) 

Best Regards
Evgeniy

**Comment by wolfma61** [comment]
thank you for updating the issue - 

take care!
