### ISSUE TITLE
No handling of failed(batch)  transcription

### ISSUE THREAD

**Issue by mikenewman1** [Azure-Samples/cognitive-services-speech-sdk#281]
In the sample code
```https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/python/python-client/main.py```

There is a test
```            if transcription.status == "Failed" or transcription.status == "Succeeded":
```
but there is no message to the user if the recognition fails. This is extremely unhelpful if you are a new user of this service and you are trying to debug the setup.

**To Reproduce**
1. ...
2. ...

**Expected behavior**

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - please be specific
 - Hardware - x64, x86, ARM, ...
 - Programming language: C#, C++, Java, JavaScript, Objective-C, Python
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific

**Additional context**
 - Error messages, log information, stack trace, ...
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by mikenewman1** [comment]
Oops. The blank line was supposed to read
`            if transcription.status == "Failed" or transcription.status == "Succeeded":`
but it isn't showing up for me in the original post

**Comment by chlandsi** [comment]
Thanks for the report, @mikenewman1. We'll amend this shortly.

**Comment by chlandsi** [comment]
Adressed by #288.
