### ISSUE TITLE
bug report: websocket error with Speech SDK javascript v.1.6.0

### ISSUE THREAD

**Issue by inglesuniversal** [Azure-Samples/cognitive-services-speech-sdk#282]
I updated the SDK libraries... and when running same test code used on v.1.5.0 from May's release, I got the following error:

WebsocketMessageAdapter.ts: 294 WebSocket is already in CLOSING or CLOSED state.

Any clue how I can fix it?

This same code works flawlessly on version 1.5.0

Regards

**Comment by wolfma61** [comment]
should still work  ;)

any more details what is going on in your test code, can you create a simple scenario to reproduce this?

thx
Wolfgang

**Comment by inglesuniversal** [comment]
Good evening... I keep getting the same error ONLY with latest release 1.6.0 (js web sdk)

attaching screen capture URL (mac os 10.14.5| chrome latest version: Version 75.0.3770.100 (Official Build) (64-bit))

IMAGE:

https://screenshot.net/nlgmf14

**Comment by rhurey** [comment]
Can you help me understand what calls are being made when this happens?

Continuous recognition? Stopping? Translation?

Was this during / after a long recognition? (i.e. 10 minutes+)

**Comment by wolfma61** [comment]
@inglesuniversal - is there any feedback you can give Ryan?

**Comment by inglesuniversal** [comment]
ok I'm still getting this error when I press the STOP recording (either on once or continuous mode)

WebsocketMessageAdapter.ts:294 WebSocket is already in CLOSING or CLOSED state.

The HTML code used was pretty much the same I used on version 1.5.0

Do you need any other information that may be useful to spot this error I keep getting?

version 1.5.0 works flawlessly!

Regards

**Comment by rhurey** [comment]
There were some changes to simplify the set of continuations in the main recognize method, I suspect there's an error case that is misbehaving.

The questions I have to try and narrow down the repro case are:
- Continuous recognition? Stopping? Translation? 
- Was this during / after a long recognition? (i.e. 10 minutes+)
- Is the audio source a microphone or a file?

The next move may be to turn up the diagnostic logging on the client and see what's happening with the service conversation.

**Comment by inglesuniversal** [comment]
Thanks for following up on this issue...

* one time recognition and continuous recognition
* this record shows up immediately after one shot recognition auto stops or by clicking stop while using the continuous recognition mode
* I have not tested using audio file... my main target is for microphone usage

Hope this info helps.

**Comment by rhurey** [comment]
Let's try turning up the logging and see if something in the service interaction can help out.

If you're using the bundled js, can you change the line:
Exports_2.Events.instance.attachListener(new Exports_1.ConsoleLoggingListener());
to
Exports_2.Events.instance.attachListener(new Exports_1.ConsoleLoggingListener(0));

You'll need to redact your keys from any output you share as they'll be logged at the beginning.

**Comment by wolfma61** [comment]
no feedback - closing
