### ISSUE TITLE
Speech endpoint in UK South returns 401 unauthorized

### ISSUE THREAD

**Issue by pviotti** [Azure-Samples/cognitive-services-speech-sdk#283]
Despite being [marked as available in UK South](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/regions#standard-and-neural-voices), the Speech API returns authentication failure when executing the [quickstart code](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/text-to-speech/csharp-dotnetcore).

```
ErrorCode=AuthenticationFailure   
ErrorDetails="HTTPAPI result code = HTTPAPI_OK. HTTP status code = 401."
```
The status page says that the service is up and running, and with credentials from West Europe it works.

**To Reproduce**
Execute the quickstart C# code with key and region from a subscription in UK South.  
I actually tried it with the following F# script but it should be the same:

```fsharp

open System
open Microsoft.CognitiveServices.Speech

[<EntryPoint>]
let main argv =
    Console.Write "type something you want to speak: "
    let line = Console.ReadLine()
    let config = SpeechConfig.FromSubscription("mykey", "uksouth")
    config.SpeechSynthesisVoiceName <- "en-US-GuyNeural" 
    use synthetizer = new SpeechSynthesizer(config)
    let task = line |> synthetizer.SpeakTextAsync 
    task.Wait()
    match task.Result.Reason with
        | ResultReason.Canceled -> 
            let cancellation = SpeechSynthesisCancellationDetails.FromResult task.Result
            if CancellationReason.Error = cancellation.Reason then 
                printfn "ERROR: ErrorCode=%A" cancellation.ErrorCode
                printfn "ERROR: ErrorDetails=%A" cancellation.ErrorDetails
        | _ -> printfn "Everything OK"
    0
```

**Version of the Cognitive Services Speech SDK**
1.6.0 (as NuGet package)

**Platform, Operating System, and Programming Language**
 - OS: Linux 5.1.15, Arch
 - Hardware - x64
 - Programming language: F#, C#

**Comment by wolfma61** [comment]
I can not reproduce this problem. The C# quickstart code (and the 1.6 version of the SDK) work fine for me with in the uksouth region with a uksouth subscription key, with a westeurope subscription key it works against the westeurope region.

You can't mix regions/keys ...

Wolfgang

**Comment by pviotti** [comment]
Thanks for the reply. I believe I did not mix keys and regions. I'll try again between today and tomorrow and let you know if this is is still happening or close the issue.

**Comment by pviotti** [comment]
It works now, on Windows. There must be something wrong with the configuration of my Linux box. Closing for now. Thanks anyway!
