### ISSUE TITLE
Python batch transcription: add diarization

### ISSUE THREAD

**Issue by rajivramanjani** [Azure-Samples/cognitive-services-speech-sdk#286]
AddDiarization and AddSentiment dont seem to work in the Python Batch Transcription
I tried to execute the Python main.py code.  However I could not enable the properties AddDiarization, AddSentiment and PunctuationMode when I try to execute the transcription in batch mode.   The code sample also does not show how these properties are enabled for a Python batch code.  Please revert back soon. 

**Describe the solution you'd like**
The main.py code that gets generated from swagger should have code that allows for Diarization, Sentiment enabling etc. 

**Describe alternatives you've considered**

**Additional context**
The json that describes the properties of the batch transcription (as mentioned in this URL: https://docs.microsoft.com/en-gb/azure/cognitive-services/speech-service/batch-transcription ) seem to allow for AddDiarization, AddSentiment etc.  However these don't seem to be enabled for Python Batch Transcription

**Comment by mahilleb-msft** [comment]
The TranscriptionDefinition constructor of the generated Swagger client takes a `properties` parameters by which you can pass a dictionary, for example `properties={"AddDiarization": "True"}`.

**Comment by PanosPeriorellis** [comment]
Just to add that for Diarization you need to set to True both AddDiarization and AddWordLevelTimestamps

**Comment by rajivramanjani** [comment]
Thank you - this works.  I have another issue with Diarization - which I will post as fresh issue.
