### ISSUE TITLE
iOS  spxerr_mic_error

### ISSUE THREAD

**Issue by Lzlwind** [Azure-Samples/cognitive-services-speech-sdk#293]
when   [speechRecognizer startContinuousRecognition] 
faile   spxerr_mic_error

**Comment by chlandsi** [comment]
This means there is a problem getting audio from the microphone. Can you give some more information, i.e., is your code running on device or on simulator, which version of the SDK are you using, what audio hardware is being used? Thanks!

**Comment by wolfma61** [comment]
also - how is this related to issue  #291 ?

is this the same code sample?

**Comment by Lzlwind** [comment]
resolve

**Comment by thermogl** [comment]
how did you resolve this?

**Comment by Lzlwind** [comment]
Before use sdk  return on the microphone  [[AVAudioSession sharedInstance] setActive:YES error:&activeError         current effective treatment methods
