### ISSUE TITLE
IntentRecognitionResult does not expose the intent score

### ISSUE THREAD

**Issue by tomconte** [Azure-Samples/cognitive-services-speech-sdk#294]
**Is your feature request related to a problem? Please describe.**

I would like to check the score of the top level intent to determine if the result can be trusted. Currently an intent can be recognised whereas it has a very low score.

**Describe the solution you'd like**

A `getScore()` method would return the score.

**Describe alternatives you've considered**

**Additional context**

**Comment by chlandsi** [comment]
The intent score is contained in the json representation of the intent service result, which is returned as part of the `IntentRecognitionResult` object. How that json can be accessed depends on which language bindings are used.

**Comment by tomconte** [comment]
Would it make sense to expose the score in a simpler way in the API? Checking the intent score seems to be something that should be easy to do. In the Java API, it seems quite verbose to retrieve the JSON and parse it just to extract the score.

**Comment by wolfma61** [comment]
we'll add this as a feature requests -

thx
Wolfgang
