### ISSUE TITLE
IntentRecognitionResult does not expose the intent score

### ISSUE THREAD

**Issue by tomconte** [Azure-Samples/cognitive-services-speech-sdk#295]
**Is your feature request related to a problem? Please describe.**

I would like to check the score of the top level intent to determine if the result can be trusted. Currently an intent can be recognised whereas it has a very low score.

**Describe the solution you'd like**

A `getScore()` method would return the score.

**Describe alternatives you've considered**

Obtain the JSON via properties to access the score.

**Comment by chlandsi** [comment]
Closing as duplicate of #294.
