### ISSUE TITLE
Can Add words to your corpus?

### ISSUE THREAD

**Issue by hold-my-hand** [Azure-Samples/cognitive-services-speech-sdk#298]
We have a hardware called "ONE Mini", when I speak in Chinese, it recognizes "玩迷你",I want it to recognize the two words "ONE mini", how to add it to your corpus?

**Comment by wolfma61** [comment]
Custom Phrase lists (https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-phrase-lists) or Custom Speech (https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-custom-speech) might help here.

Custom Phrase lists are currently only available in en-us language, but will be available in other languages soon.

**Comment by wolfma61** [comment]
closing - for similar issues please create a new discussion
thx
