### ISSUE TITLE
Speech Recognition with Intents is Incomplete

### ISSUE THREAD

**Issue by bbunderson** [Azure-Samples/cognitive-services-speech-sdk#30]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
NA

### Any log messages given by the failure
>
NA

### Expected/desired behavior
>
When using the IntentRecognizer, it returns IntentRecognitionResult. The IntentRecognitionResult only has the intents and not the entities. I have found that I can add Microsoft.Bot.Builder.Ai.LUIS and related packages. I then have to cast this in a very confusing way.

var result = await recognizer.RecognizeAsync().ConfigureAwait(false);
var luisJson = result.Properties.Get<string>(ResultPropertyKind.LanguageUnderstandingJson);
var luisResult = JsonConvert.DeserializeObject<LuisResult>(luisJson);

Why would dependencies be needed for the BotBuilder framework? The BotBuilder framework is huge, and not directly related. The predecessor of this project (ProjectOxford) seemed to have had at least a Payload property for storing the JSON. In addition, it would be nice to have a LuisResult or an extension that would not be dependent on the whole BotBuilder framework to get a complete Intent object with entities, scoring, etc.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). Other.
Windows 10

### Versions
>
 Version 0.5.0

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bbunderson** [comment]
I figured out that you can get the Microsoft.Azure.CognitiveServices.Language.LUIS.Runtime package to get the LuisResult class.

**Comment by wolfma61** [comment]
thank you for posting the answer ... closing
please open a new issue if required
