### ISSUE TITLE
Diarization not able to differentiate between people

### ISSUE THREAD

**Issue by rajivramanjani** [Azure-Samples/cognitive-services-speech-sdk#301]
**Describe the bug**
I have two bugs here:
Bug 1: There is an audio conversation between two women.  The diarization is not able to distinguish which parts of the speech are spoken by which women.  SpearkerID is showing as 1 for places where the second speaker is talking.  In those cases it is mixing up the speech spoken by speaker 1 and 2 into a single sentence and categorizing it as SpeakerID: 1

Bug 2: We have another audio conversation between a man and a woman.  Here it is able to distinguish clearly between speakers.  However for the second speaker ......initially the SpeakerID has a value of null.  Somewhere down the line it changes to SpeakerID: 2 .  For speaker 1 - there is consistency where it always shows SpeakerID : 1.  The issue is with the second speaker where it alternates between null and 2. 

**To Reproduce**
1. Try to diarize a conversation between two women or two men with similar sounding voices.
2. SpeakerID value should never show null.  It should always show 1 or 2.  I don't know how to reproduce this.  But probably if the second speaker says very short phrases - like "ok" or "yes" probably you could reproduce this issue.

**Expected behavior**
When two people of the same gender are talking - it should clearly distinguish who is talking what and not jumble the talk together.  Also SpeakerID values must be 1 or 2 and never null. 

**Version of the Cognitive Services Speech SDK**
I am using the Batch transcription mode. 

**Platform, Operating System, and Programming Language**
Windows, Python, Edge browser

**Comment by majin-ms** [comment]
Hi, Rajiv, could you attach audios so that we can reproduce the first bug if available?
As for the null speaker labels, it is a known issue and we are fixing this.

**Comment by rajivramanjani** [comment]
Please provide me a mail id to which I can send the audio file to - as it cannot be shared in a public forum such as this.

**Comment by rajivramanjani** [comment]
The null speaker labels still appears - especially when the speaker talks just a few words such as "Yeah, yes" or "ok" etc.

**Comment by rajivramanjani** [comment]
Ma jin - you should have received the email with details.  Please confirm.

**Comment by majin-ms** [comment]
well received, investigation is ongoing.

**Comment by majin-ms** [comment]
For the first mixed speaker label audio, I've checked the diarizered results and found that spk1 is partly mixed with spk2, and spk2 is almost pure. We centernly has tests on same gender, most of them works well but few doesn't. This is partly due to diarizer algorithm. This issue may be improved in next version(update should soon in a few months).
For the second null speaker label, we've changed this code and it should take effect in a few days, you could try it next week.

**Comment by rajivramanjani** [comment]
Do you have a tentative date when the next version would be released - as we have an important internal business need that depends on it.

**Comment by majin-ms** [comment]
sorry, I cannot give you a date. But I think it might before Oct., it is a huge update.

**Comment by vasavenk** [comment]
Hey @majin-ms , in this scenario rajivramanjani is using Batch API. Any of the SDKs support speaker Diarization?

**Comment by majin-ms** [comment]
Hi @vasavenk , currently MSDiarizer only support batch API.

**Comment by rajivramanjani** [comment]
The null speaker label issue is still alive.  I am still getting null label in some instances.

**Comment by eldakms** [comment]
Which data center/endpoint are you using? Could you please share an audio input with me? I tried to reproduce using AGL.wav you shared earlier but I'm not successful. Nulls are not generated.

**Comment by eldakms** [comment]
email is eldak at microsoft dot com. thanks!

**Comment by rajivramanjani** [comment]
I am using the following endpoint: https://eastus.api.cognitive.microsoft.com/sts/v1.0/issuetoken .  I am using the same AGL wave file

**Comment by rajivramanjani** [comment]
@eldakms is there any update to this issue?

**Comment by eldakms** [comment]
I could not reproduce this. if you would share a full repro with me (client code + video), that would help

**Comment by eldakms** [comment]
btw, does you input file have 2 channels? Diarization only supports a single channel currently

**Comment by rajivramanjani** [comment]
I am using the same AGL wave file that you already have.  I have mailed you the code I am using.

**Comment by SantoshML** [comment]
Hi, I am also facing the same issue where I have three speakers in a mono channel  and I am using batch transcription

Speaker1: Female
Speaker2: Female
Speaker3: Male

while I am going through the transcript, I see Azure batch transcription is not able to separate between speaker 1 and speaker 2

Is azure batch transcription is able to separate three speakers from a mono audio file?

Please let me know if we have any parameter where we can say that the call has three speakers

**Comment by eldakms** [comment]
Currently diarization models are trained for 2 speakers only, we are working on extending this to more speakers.

**Comment by blakemartin** [comment]
Hi @eldakms - is there an estimated release date for > 2 speaker diarization?

**Comment by wolfma61** [comment]
There is no official date for diarization with more than 2 speakers

**Comment by Chris1234567899** [comment]
@wolfma61 
Sorry for coming back to this. I just wonder - it has been 2 years now - is there any progress on diarization with >2 speakers?

**Comment by eldakms** [comment]
@Chris1234567899 , this feature is currently in the private preview. Tentative date for the public preview is April 2022. If you want to try early bits/private preview, please ping me directly at eldak at microsoft dot com. Thanks!

**Comment by flankerad** [comment]
@eldakms hi, I have been following this thread since 4 months, any update on the feature, we do heavy transcription tasks and I was looking to move out of AWS Transcribe.

**Comment by eldakms** [comment]
@flankerad , all bits are ready, please ping me directly, i will share the new swagger link with you. thanks!

**Comment by flankerad** [comment]
@eldakms great to hear, dropped you a mail from` flanker dot ad at gmail dot com`

**Comment by Chris1234567899** [comment]
Cool, any date for putting this public?
