### ISSUE TITLE
Python Batch transcription requires to be executed twice

### ISSUE THREAD

**Issue by rajivramanjani** [Azure-Samples/cognitive-services-speech-sdk#302]
**Describe the bug**
Whenever I try to execute the python batch transcription for speech-to-text : for a second time (after a successful first execution) - I face this issue and am unable to execute it.  I have to try to do it a third time for it to work (and it works the third time).  

Here is the log I get when trying to do the second round execution:

Starting transcription client...
Deleting all existing completed transcriptions.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-ff49436c206e> in <module>()
    117 
    118 if __name__ == "__main__":
--> 119     transcribe()

<ipython-input-10-ff49436c206e> in transcribe()
     48     # if transcriptions are still running or not started, they will not be deleted
     49     for transcription in transcriptions:
---> 50         transcription_api.delete_transcription(transcription.id)
     51 
     52     logging.info("Creating transcriptions.")

C:\ProgramData\Anaconda3\lib\site-packages\swagger_client\api\custom_speech_transcriptions_api.py in delete_transcription(self, id, **kwargs)
    145             return self.delete_transcription_with_http_info(id, **kwargs)  # noqa: E501
    146         else:
--> 147             (data) = self.delete_transcription_with_http_info(id, **kwargs)  # noqa: E501
    148             return data
    149 

C:\ProgramData\Anaconda3\lib\site-packages\swagger_client\api\custom_speech_transcriptions_api.py in delete_transcription_with_http_info(self, id, **kwargs)
    214             _preload_content=params.get('_preload_content', True),
    215             _request_timeout=params.get('_request_timeout'),
--> 216             collection_formats=collection_formats)
    217 
    218     def get_supported_locales_for_transcriptions_b_ba(self, **kwargs):  # noqa: E501

C:\ProgramData\Anaconda3\lib\site-packages\swagger_client\api_client.py in call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, auth_settings, async_req, _return_http_data_only, collection_formats, _preload_content, _request_timeout)
    328                                    response_type, auth_settings,
    329                                    _return_http_data_only, collection_formats,
--> 330                                    _preload_content, _request_timeout)
    331         else:
    332             thread = self.pool.apply_async(self.__call_api, (resource_path,

C:\ProgramData\Anaconda3\lib\site-packages\swagger_client\api_client.py in __call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, auth_settings, _return_http_data_only, collection_formats, _preload_content, _request_timeout)
    167             # deserialize response data
    168             if response_type:
--> 169                 return_data = self.deserialize(response_data, response_type)
    170             else:
    171                 return_data = None

C:\ProgramData\Anaconda3\lib\site-packages\swagger_client\api_client.py in deserialize(self, response, response_type)
    239             data = response.data
    240 
--> 241         return self.__deserialize(data, response_type)
    242 
    243     def __deserialize(self, data, klass):

C:\ProgramData\Anaconda3\lib\site-packages\swagger_client\api_client.py in __deserialize(self, data, klass)
    278             return self.__deserialize_datatime(data)
    279         else:
--> 280             return self.__deserialize_model(data, klass)
    281 
    282     def call_api(self, resource_path, method,

C:\ProgramData\Anaconda3\lib\site-packages\swagger_client\api_client.py in __deserialize_model(self, data, klass)
    624                     kwargs[attr] = self.__deserialize(value, attr_type)
    625 
--> 626         instance = klass(**kwargs)
    627 
    628         if (isinstance(instance, dict) and

C:\ProgramData\Anaconda3\lib\site-packages\swagger_client\models\error_content.py in __init__(self, details, innererror, code, message, target)
     64         if innererror is not None:
     65             self.innererror = innererror
---> 66         self.code = code
     67         self.message = message
     68         if target is not None:

C:\ProgramData\Anaconda3\lib\site-packages\swagger_client\models\error_content.py in code(self, code)
    136         """
    137         if code is None:
--> 138             raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501
    139 
    140         self._code = code

ValueError: Invalid value for `code`, must not be `None`

**Expected behavior**
The batch transcription script is expected to execute successfully each time. 

This is happening despite commenting out this line of code in the error_content.py file:

#from swagger_client.models.inner_error import InnerError  # noqa: F401,E501

**Comment by chlandsi** [comment]
@rajivramanjani Thanks for reporting. We amended the sample so the error doesn't occur anymore.

**Comment by rajivramanjani** [comment]
@chlandsi this error is still recurring.  I downloaded the latest client from the swagger site - for EastUS region and noticed that the issue hasn't been fixed yet.

**Comment by chlandsi** [comment]
@rajivramanjani We don't control the creation of the swagger client, that is done by the swagger autogeneration. Actually, the error can be ignored, and the updated [sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/python/python-client/main.py) does so. Please try with the updated sample.
