### ISSUE TITLE
Recognized text is not correct and irrelevant

### ISSUE THREAD

**Issue by therowf** [Azure-Samples/cognitive-services-speech-sdk#305]
Hi,

I have a wav file and when I try to recognize speech using node.js sdk it shows a different result. Sometimes it recognizes precisely but other times shows very odd words and irrelevant text.

as an example, when the real text should be:

> section two you'll hear a tour guide giving a talk about a museum center called riverside industrial village first you have some time to look at questions eleven to thirteen now listen carefully and answer questions eleven to thirteen

it shows:

> Shop Hun.Hello hello as I'm not true dat. Boi have my shine shine goosefish can phone.Fish hello how long **** **** **** ****Call from London Luges Hongs Awesome ****

Here is my code

```

 recognizer.startContinuousRecognitionAsync(function () {}, function (err) {
                    console.trace("err - " + err);
                    cstat = 100;
                    removefile(url);
                    res.json({
                        status: "OK",
                        message: tempText
                    });
                });

                recognizer.canceled = function (s, e) {
                    var str = "(cancel) Reason: " + sdk.CancellationReason[e.reason];
                    if (e.reason === sdk.CancellationReason.Error) {
                        str += ": " + e.errorDetails;
                    }

                    cstat = 100;
                    removefile(url);
                    res.json({
                        status: "OK",
                        message: tempText
                    });
                }

                recognizer.recognized = function (s, e) {
                    // Indicates that recognizable speech was not detected, and that recognition is done.
                    if (e.result.reason === sdk.ResultReason.NoMatch) {
                        var noMatchDetail = sdk.NoMatchDetails.fromResult(e.result);
                        console.log("\r\n(recognized)  Reason: " + sdk.ResultReason[e.result.reason] + " NoMatchReason: " + sdk.NoMatchReason[noMatchDetail.reason]);
                        // tempText += e.result.text;
                    } else {
                        console.log("\r\n(recognized)  Reason: " + sdk.ResultReason[e.result.reason] + " Text: " + e.result.text);
                        tempText += e.result.text;
                    }
                };

                recognizer.recognizing = function (s, e) {
                    //var str = "(recognizing) Reason: " + e.result + "---"+e.privResult;
                    console.log(e);
                };
                recognizer.sessionStopped = function (s, e) {
                    recognizer.stopContinuousRecognitionAsync()
                    var str = "(sessionStopped) SessionId: " + e.sessionId;
                    cstat = 100;
                    removefile(url);
                    res.json({
                        status: "OK",
                        message: tempText
                    });
                    console.log(str);
                };


```

**Comment by wolfma61** [comment]
is it possible to share the wave file so we can reproduces and analyze the problem in house?

thx
Wolfgang

**Comment by therowf** [comment]
Thanks for your reply.
Here are 2 files.
https://www.dropbox.com/sh/cp71s91com4ggaw/AAAle_OXK5trY_Ed1BAbc7XRa?dl=0

**Comment by wolfma61** [comment]
@therowf 

we are looking into this ... the preferred bitrate is 256kbps, but unfortunately we still see some issues with one of your files. 
...looking into it...

**Comment by therowf** [comment]
@wolfma61 Thanks

**Comment by wolfma61** [comment]
@therowf - these are a couple of interesting issues you discovered ;)
some more investigation is needed - but so far:

there is a problem in the JS SDK with 44khz audio files, that makes your m*81.wav audio file fail using the javascript.sdk (it is really a special file). It works with the native SDK (C#, Python etc). We will fix this in the JS sdk in an upcoming version. Converting to 16khz the file transcribes fine (as expected)

Your m*76.wav file converted to 16khz creates wrong results when converted with Audacity. The desired transcription is generated, but not as the best result. This seems to be a model issue, which is being investigated by the service team.

Wolfgang

**Comment by wolfma61** [comment]
this should create good results now
