### ISSUE TITLE
How to use custom wake word model in Cognitive-Services-speech-SDK - node or Javascript

### ISSUE THREAD

**Issue by ranjithrengaraj** [Azure-Samples/cognitive-services-speech-sdk#309]
Hi Team,

Will cognitive service speech SDK -Node or JavaScript support custom wake word model .
I have created the model using Custom Speech Service Portal and download as zip file.But i am not able to detect the keyword.

**Comment by chrisbasoglu** [comment]
wake word on node or JS is not yet supported.  This is in our plans however.  The support matrix is listed here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/scenario-availability
