### ISSUE TITLE
Could not figure out the usage of continuous speech recognition

### ISSUE THREAD

**Issue by tavaresdong** [Azure-Samples/cognitive-services-speech-sdk#31]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Run continuous speech recognition with StartContinuousRecognitionAsync(),
I know that when there is a stream bind with the recognizer. The read() method
returns 0 means the stream is over.  But how could I know the recognition result received
is complete too? could there be multiple final results during the recognition process? can I
identify which one is the real last result?

>Also I'm not very clear about how OnSessionEvent behaviour, which action could trigger 
session start and stop event? Could anyone give a solid example? Thanks!

### Any log messages given by the failure
>N/A

### Expected/desired behavior
>N/A

### OS and Version?
> Windows 10

### Versions
> N/A

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wolfma61** [comment]
we will continue improving/adding to docs and samples
this github contains serveral  samples which show the usage of continuous recognition and events. 
In the process of continuous recognition you will receive several 'received' event, they all indicate that an utterance was recognized,...
