### ISSUE TITLE
Currencies accuracy recognition

### ISSUE THREAD

**Issue by jchomarat** [Azure-Samples/cognitive-services-speech-sdk#311]
Hello,

When I try to recognize an amount with currencies in French, the output is not correct:
When I say "Je veux emprunter 10 000 euros", the recognized sentence is 
"Je veux emprunter EUR 10000".

I have tried with other currencies and it is the same behavior.

**Expected behavior**
In french, the currency should be after the amount (10000 EUR)

**Version of the Cognitive Services Speech SDK**
The latest

**Platform, Operating System, and Programming Language**
 - OS: Windows
 - Hardware - x64,,
 - Programming language: JavaScript,
 - Browser: Edge Chrome

**Comment by jhakulin** [comment]
There will be fix on displaying large numbers on end of May 2020.
