### ISSUE TITLE
WebSocket Endpoint and Protocol for new Microsoft Speech STT Service

### ISSUE THREAD

**Issue by gMehlmann** [Azure-Samples/cognitive-services-speech-sdk#312]
Hi, 
I have been working with the WebSocket version of Bing STT. I want to migrate to the new speech service now. I have changed the endpoint for the authorization token, which works well, but I don't get the new service working with the new endpoint. I am using the following endpoint and headers:

GET /speech/recognition/conversation/cognitiveservices/v1?format=detailed&language=de-DE HTTP/1.1
Host: westeurope.stt.speech.microsoft.com
Upgrade: WebSocket
Connection: keep-alive, Upgrade
Sec-WebSocket-Key: {...}
Sec-WebSocket-Version: 13
Sec-WebSocket-Protocol: USP
Authorization: Bearer {...}
X-ConnectionId: {...} 

The header is exactly the same as used with the Bing service.

What am I doing wrong?

**Comment by wolfma61** [comment]
what the message you are getting back? what error code?

**Comment by gMehlmann** [comment]
Hi Wolfgang,

The server immediately closes the connection without any message. I am actually trying two endpoint url's:

Constructing the url with "https" this gives me a "400" error (bad request - not a websocket request):

"https://" + region + ".stt.speech.microsoft.com:443/speech/recognition/" +
                    scenario + "/cognitiveservices/v1?" + "format=" + format + "&" + "language=" + language;

HTTP/1.1 400 Bad Request
Connection: close
Date: Tue, 16 Jul 2019 10:01:05 GMT
Server: Kestrel
Transfer-Encoding: chunked
Strict-Transport-Security: max-age=31536000; includeSubDomains

Constructing the url with "wss" gives me a runtime exception (system.io socket closed by host)

"wss://" + region + ".stt.speech.microsoft.com:443/speech/recognition/" +
                    scenario + "/cognitiveservices/v1?" + "format=" + format + "&" + "language=" + language;

is the port 443 correct?

Best regards

  Gregor

**Comment by zhouwangzw** [comment]
The new speech service needs a different subscription key than Bing speech. And the key is bound to a particular region. What kind of key are you using, free key or S0?

**Comment by gMehlmann** [comment]
Hi,
I have a new subscription key for the new service. I am currently using the free tariff (F0). Should I try the S0 version?

**Comment by gMehlmann** [comment]
The subscription is for the western europe region and i am also using this in the url

**Comment by zhouwangzw** [comment]
Are you able to use the free key on REST API for new speech service? If not, your key is probably expired or invalid. If yes, please give us the X-ConnectionID you are using. We can check .

**Comment by gMehlmann** [comment]
i will check this and report to you as soon as I know.

**Comment by gMehlmann** [comment]
the last connection id that i used during the last failed websocket request was  494d271c14d043e88898e3f5be536514

**Comment by gMehlmann** [comment]
i can also use the authentication service with my subscription

**Comment by zhouwangzw** [comment]
When did you run the last test?

**Comment by gMehlmann** [comment]
a minute ago

**Comment by zhouwangzw** [comment]
unfortunately, I cannot see any request with this id in our service log. Are you able to use your key for the REST API?

**Comment by gMehlmann** [comment]
yes - the rest api works

**Comment by gMehlmann** [comment]
So, authentication and REST API both work with the subscription key (F0), but not the websocket service

**Comment by gMehlmann** [comment]
i was using the following REST service: 
https://westeurope.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?format=detailed&language=de-DE

**Comment by gMehlmann** [comment]
I've just used fiddler to check the requet and response: The last request I tested was
GET wss://westeurope.stt.speech.microsoft.com:443/speech/recognition/interactive/cognitiveservices/v1?format=detailed&language=de-DE HTTP/1.1
Host: westeurope.stt.speech.microsoft.com:443
Upgrade: WebSocket
Connection: keep-alive, Upgrade
Sec-WebSocket-Key: MTYwZDM3ZGQtN2E2NC00NDI0LWJlZTktNjI3ZmViZWI0MmM0
Sec-WebSocket-Version: 13
Sec-WebSocket-Protocol: USP
Ocp-Apim-Subscription-Key: {...}
X-ConnectionId: ca8bb19b4a7b489f85db18efceed7254

The server returned zero bytes

**Comment by zhouwangzw** [comment]
should be https in GET, instead of wss?

GET https://westeurope.stt.speech.microsoft.com:443/speech/recognition/interactive/cognitiveservices/v1?format=detailed&language=de-DE HTTP/1.1

**Comment by gMehlmann** [comment]
When using htps like this:

GET https://westeurope.stt.speech.microsoft.com/speech/recognition/interactive/cognitiveservices/v1?format=detailed&language=de-DE HTTP/1.1
Host: westeurope.stt.speech.microsoft.com
Upgrade: WebSocket
Connection: keep-alive, Upgrade
Sec-WebSocket-Key: YWYxMmRiZDEtOTNlZS00ZjA5LWI1N2YtZjhlYTNhZTY1ZmUz
Sec-WebSocket-Version: 13
Sec-WebSocket-Protocol: USP
Ocp-Apim-Subscription-Key: {...}
X-ConnectionId: d1d0f68ace56452da0aedf79e2e7bb4f

I get this back:

HTTP/1.1 400 Bad Request
Connection: close
Date: Wed, 17 Jul 2019 13:30:25 GMT
Server: Kestrel
Transfer-Encoding: chunked
Strict-Transport-Security: max-age=31536000; includeSubDomains

17
Not a WebSocket request
0

**Comment by zhouwangzw** [comment]
Could you please provide us the code that connects to the service endpoints, so that we can investigate?

**Comment by zhouwangzw** [comment]
We did check again, and it seems that "Sec-WebSocket-Key: YWYxMmRiZDEtOTNlZS00ZjA5LWI1N2YtZjhlYTNhZTY1ZmUz" is not correct. According to RFC, "The value of this header field MUST be a nonce consisting of a randomly selected 16-byte value that has        been base64-encoded (see Section 4 of [RFC4648]).  The nonce MUST be selected randomly for each connection." 
https://tools.ietf.org/html/rfc6455#section-4. 
And the key you used seems a guid with base64-encoded.
I tried with this: QUJDREVGR0hBQkNERUZHSA==, and it works.

**Comment by gMehlmann** [comment]
Hi, 
you are totally right!
I didn't notice that - this is certainly a bug in the software I use. I fixed this and now it seems to work well ... for now (;-)). 
Thank you very much for the great support!

**Comment by wolfma61** [comment]
thank you for the confirmation

we certainly would encourage you to use the speech sdk, and not do the protocol yourself, as we can support you with SDK related questions, but not problems with the underlying protocol,

**Comment by gabrielfreire** [comment]
> we certainly would encourage you to use the speech sdk, and not do the protocol yourself, as we can support you with SDK related questions, but not problems with the underlying protocol,

The SDK doesn't work with Xamarin
