### ISSUE TITLE
Error 'Microsoft.CognitiveServices.Speech.core.dll' at debug function in on macOS

### ISSUE THREAD

**Issue by teleginski** [Azure-Samples/cognitive-services-speech-sdk#313]
**Describe the bug**
An Azure Function project was created with the blob trigger template.
When the trigger works, the error occurs.

**Error**
`System.Private.CoreLib: Exception while executing function: ConversaoFalaEmTextoFunction. Microsoft.CognitiveServices.Speech.csharp: Unable to load shared library 'Microsoft.CognitiveServices.Speech.core.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libMicrosoft.CognitiveServices.Speech.core.dll, 1): image not found.`

**Version of the Cognitive Services Speech SDK**
Microsoft.CognitiveServices.Speech 1.6.0

**Operating System**
macOS - Mojave

**Comment by chlandsi** [comment]
Hi, sorry for the delay in responding. Can you share the code you are running? Does this happen when you are running the Azure function in Azure, or when deploying it locally? Thanks!

**Comment by chlandsi** [comment]
@krwq Linux ARM32 is currently not supported (see [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/) for supported platforms).

**Comment by CobraCalle** [comment]
> @krwq Linux ARM32 is currently not supported (see [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/) for supported platforms).

do you know if it is planned to support? I`ve build a voice application with dotnet core and use raspberry pi as platform. Using the key word detection from azure would be the best option in this scenario.

**Comment by jhakulin** [comment]
@jlchappell Here is the list of supported Linux distros. I believe you can use Ubuntu on RPi2
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk?tabs=linux%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio#get-the-speech-sdk

As this issue is closed, please create new issue for any further questions.
