### ISSUE TITLE
IntentRecognizer not including role of entities

### ISSUE THREAD

**Issue by jan-ai** [Azure-Samples/cognitive-services-speech-sdk#317]
**Describe the bug**
The LUIS Result (from e.Result.Properties.GetProperty (PropertyId.LanguageUnderstandingServiceResponse_JsonResult); while e is IntentRecognitionEventArgs) does include entities, but the role of the entities is missing,

**To Reproduce**
- setup a simple LUIS app in luis,ai
- add some intent, some utterances and a regular expression entity like (\d{7,8}). Also add a role to the Entity
- mark some utterances with the entity including role
- Setup an app using IntentRecognizer

**Expected behavior**
The role of the entity should be included in the json result. 

**Version of the Cognitive Services Speech SDK**
latest SDK version 1.6 was used

**Platform, Operating System, and Programming Language**
 - OS: Linux Ubuntu (would love to have CentOS!)
 - Hardware - x64
 - Programming language: C#
 - Browser n/a
- used Version of luis.ai is eu.luis.ai

**Comment by amitkumarshukla** [comment]
@jan-ai Sorry for the delay. Please test this our latest released SDK version 1.12.0 and you can see the role in the JSON payload. We have also extended our support for CentOS. I am closing this issue. Please feel free to file a new issue as soon as you notice something.
