### ISSUE TITLE
Python SpeechConfig.set_proxy not working

### ISSUE THREAD

**Issue by ebmtz** [Azure-Samples/cognitive-services-speech-sdk#318]
**Describe the bug**
`SpeechConfig` adapter has an incorrectly defined `set_proxy` method. The `port` argument should be `int`, not `str`
**To Reproduce**
When attempting:
```
import azure.cognitiveservices.speech as speechsdk
speech_config = speechsdk.SpeechConfig(subscription=SUBSCRIPTION, region=service_region)
speech_config.set_proxy('<hostname>', '<port>', '<username>', '<password>')
```

This throws error:
```
NotImplementedError: Wrong number or type of arguments for overloaded function 'SpeechConfig_set_proxy'.
  Possible C/C++ prototypes are:
    Microsoft::CognitiveServices::Speech::SpeechConfig::SetProxy(std::string const &,uint32_t,std::string const &,std::string const &)
    Microsoft::CognitiveServices::Speech::SpeechConfig::SetProxy(std::string const &,uint32_t,std::string const &)
    Microsoft::CognitiveServices::Speech::SpeechConfig::SetProxy(std::string const &,uint32_t)
```
**Expected behavior**
Set up network proxy values for `speech_config`

**Version of the Cognitive Services Speech SDK**
1.6.0.

**Platform, Operating System, and Programming Language**
 - OS: Windows 10 64-bit
 - Hardware - x64
 - Programming language: Python

**Additional context**
[This](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.speechconfig?view=azure-python#set-proxy-hostname--str--port--str--username--str--password--str-) states that`port` is to be a string, however, the method it is calling has [this](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechconfig.setproxy?view=azure-dotnet) implementation in which `port` is expected to be an `int`.

 I went into `.../site-packages/azure/cognitiveservices/speech.py` and changed line 192 to:
```def set_proxy(self, hostname: str, port: int, username: str, password: str):```

This fixed my issue, but I figured it might need to be patched

**Comment by chlandsi** [comment]
Hi @ebmtz, thanks for reporting. We will fix this for the next release. You shouldn't have to change the module code though, the Python type annotations (`str` in that case) aren't binding, and you can just pass an int instead.

**Comment by ebmtz** [comment]
I see. I forget that python doesn't really enforce datatypes. Thanks for the reminder!
