### ISSUE TITLE
"The recordings URI is invalid" error during Batch Transcriptions

### ISSUE THREAD

**Issue by raosudha89** [Azure-Samples/cognitive-services-speech-sdk#322]
Hello,

I am trying to use the batch transcription python code (https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python) to transcribe audio files stored in azure storage blob.
I was able to successfully transcribe an audio file stored in blob by generating the shared access signature manually using the azure storage explorer. 
However, when I create the shared access signature programmatically (see the code below) and then run the transcription code, I get the error "The recordings URL is invalid.."
Can you please verify if the code below is the right way to programmatically get the recordings_blob_uri required by the transcription code? Thank you for your time!

from azure.storage.blob import (
    BlockBlobService,
    BlobPermissions
)
SUBSCRIPTION_KEY = "<subscription key>"

LOCALE = "en-US"
ACCOUNT_NAME = "<account name>"
ACCOUNT_KEY = "<account key>"
URI_PREFIX = "https://<project_name>.blob.core.windows.net/<container_name>"

block_blob_service = BlockBlobService(account_name=ACCOUNT_NAME, account_key=ACCOUNT_KEY)

container_name = URI_PREFIX
blob_name = <blob_name>
sas_url = block_blob_service.generate_blob_shared_access_signature(
            container_name,
            blob_name,
            permission=BlobPermissions.READ,
            expiry=datetime.utcnow() + timedelta(hours=1),
            start=datetime.utcnow()
        )
recordings_blob_uri = container_name + '/' + blob_name + '?' + sas_url

**Comment by wooters** [comment]
@raosudha89 I don't know the answer to your question, and maybe you have already tried this, but I have noticed that in the Azure web interface for storage, when you generate a SAS token, the token begins with the `?` character. So is it possible that the the code above is adding an extra `?` character to the `recordings_blob_uri`?

**Comment by mahilleb-msft** [comment]
@raosudha89 - from above it seems you are passing a full URL as `container_name` parameter to `generate_blob_shared_access_signature()`. Can you try just passing the container name instead, i.e. `"<container_name>"`?

**Comment by mahilleb-msft** [comment]
(In order to validate, you should be able to just run `curl '<recodings_blob_uri>'` on your local machine with the URL generated in your code above.)

**Comment by raosudha89** [comment]
Passing just the container name instead of the full URL when calling the function generate_blob_shared_access_signature() resolves this issue. Thank you very much for your prompt response.
