### ISSUE TITLE
virtualassistant-uwp and multiple bot speech responses

### ISSUE THREAD

**Issue by daltskin** [Azure-Samples/cognitive-services-speech-sdk#325]
**Describe the bug**
When bot returns multiple messages with speech (SSML) the sample will play the first one received only and ignore others.

**To Reproduce**
Create a bot that outputs multiple SSML responses from a single request eg:

```
string msg1 = $"<speak version='1.0' xmlns='https://www.w3.org/2001/10/synthesis' xml:lang='en-US'><voice name='{fontName}'>Message 1</voice></speak>";
await stepContext.Context.SendActivityAsync(MessageFactory.Text("Message 1", msg1), cancellationToken: cancellationToken);
// do some stuff
string msg2 = $"<speak version='1.0' xmlns='https://www.w3.org/2001/10/synthesis' xml:lang='en-US'><voice name='{fontName}'>Message 2</voice></speak>";
await stepContext.Context.SendActivityAsync(MessageFactory.Text("Message 2", msg2), cancellationToken: cancellationToken);
```

**Expected behavior**
The audio of each message should be played after one another

**Version of the Cognitive Services Speech SDK**
v1.6.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 10 version 1903
 - Hardware - x64
 - C#
 - UWP

**Additional context**
Log file: [logfile.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/3451374/logfile.txt)

In addition, the [documentation](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-virtual-assistant-csharp-uwp#add-sample-code) shows using SynchronouslyPlayActivityAudio whilst this code uses AudioGraph.

**Comment by oscholz** [comment]
@daltskin, apologies for the prolonged radio silence on this. Could you please try this again with v 1.12.1 of the SDK? If this is still an issue, please reopen this and let us know.
