### ISSUE TITLE
Speech language detector using Microsoft Speech Services

### ISSUE THREAD

**Issue by shmisra** [Azure-Samples/cognitive-services-speech-sdk#326]
One of our customer is trying to - 
A. Create a Speech language detector using Microsoft Speech Services.
B. Especially the customer is looking for the Languages English(en-US) & Mandarin(zh-CN). 
C. The idea is: Whatever language you speak, the model (ideally the BOT) should catch the locale and convert it to that locale specific text. 

Is this possible using Microsoft Speech Services?
Is there any "Audio Speech language detector" in Cognitive Services?

**Comment by susanhuhu** [comment]
For now, we cannot. We are aware of this feature gap and it is a high priority work item on the team's plate.
