### ISSUE TITLE
Any solution to support opus stream

### ISSUE THREAD

**Issue by jcao78** [Azure-Samples/cognitive-services-speech-sdk#328]
Would you please confirm currently Azure speech to text does not yet support the opus stream?
If not, any workaround to it?

**Comment by wolfma61** [comment]
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams

Streaming compressed audio is only supported for C++, C#, and Java on Linux (Ubuntu 16.04, Ubuntu 18.04, Debian 9). Speech SDK version 1.4.0 or higher is required.

other platforms and codecs will follow

**Comment by jcao78** [comment]
Thanks. This is very helpful.  Is there any samples for it? I am trying to migrate the javascript-browser sample into linux version but found "microsoft.cognitiveservices.speech.sdk.bundle.js" need to be created for linux.  Where to find this file for linux?

**Comment by rhurey** [comment]
The bundled JavaScript file is platform agnostic.

But JavaScript isn't one of the languages where we support other codecs yet.
