### ISSUE TITLE
Websocket protocol for binary message

### ISSUE THREAD

**Issue by gabrielfreire** [Azure-Samples/cognitive-services-speech-sdk#329]
Hi Guys, i'm trying to reproduce the protocol for Binary message to use with my custom websocket code in Xamarin since the SDK doesn't work there.

below is the code i'm using to create the header

```csharp
public struct WSHeader
    {
        public string Path;
        public string XRequestId;
        public string XTimestamp;
        public string ContentType;
    }

public static int GetHeaderSize(WSHeader header)
        {
            var str = "";
            str += header.Path;
            str += header.XRequestId;
            str += header.XTimestamp;
            str += header.ContentType;
            return str.Length;
        }

 public static WSHeader makeAudioHeaders(string type, string reqId)
        {
            var header = new WSHeader()
            {
                Path = $"path:{type}\r\n",
                XRequestId = $"x-requestid:{reqId}\r\n",
                XTimestamp = $"x-timestamp:{DateTime.UtcNow.ToString("o", System.Globalization.CultureInfo.InvariantCulture)}\r\n"
            };
            return header;
        }
```

Then i write to the stream giving the 2 byte header length value
```csharp

public static void WriteHeaderToStream(Stream stream, string type, Func<WSHeader> makeHeader)
        {
            var header = makeHeader();
            Encoding encoding = type == "audio" ? Encoding.ASCII : Encoding.UTF8;
            using (var writer = new BinaryWriter(stream, encoding, true))
            {
                if (type == "audio")
                {
                    writer.Write($"{(short)GetHeaderSize(header)}\r\n"); // i also tried without '\r\n'
                    // writer.Write((short)GetHeaderSize(header)); // this doesn't work for some reason
                }

                writer.Write(encoding.GetBytes(header.Path));
                writer.Write(encoding.GetBytes(header.XRequestId));
                writer.Write(encoding.GetBytes(header.XTimestamp));
                writer.Write(encoding.GetBytes(header.ContentType));

                writer.Write(encoding.GetBytes("\r\n"));
            }
        }
```

The `turn.start` works and gives me the below **_(my console is printing the requestId all weird)_**
```json
X-RequestId:6666666666664666A666666666666668
Content-Type:application/json; charset=utf-8
Path:turn.start

{
  "context": {
    "serviceTag": "9c3e3a3565f64cc8b0d099952e9546ab"
  }
}

```

After that, i get this error for subsequent requests, i think i'm not writing the header to the stream properly, i'm new to C#, could anyone help me please ?
```shell
[0:] Status Code InvalidPayloadData
[0:] Status Code Description Incorrect message format. Binary message has invalid header size
```
**p.s. this is all spaghetti code for now until i get this working.**

**Comment by rhurey** [comment]
Unfortunately we have limited bandwidth to support WebSocket implementations and instead focus support on SDK consumers. 

But you're also in a spot with Xamarin...

I'd mention that there's an open-sourced version of the SDK (that's written in TypeScript) 
[cognitive-services-speech-sdk-js/src/common.speech/WebsocketMessageFormatter.ts ](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/common.speech/WebsocketMessageFormatter.ts) may be useful at understanding what the service expects.

A quick look through there (and some extra debug comments) shows the headers being written are:
path: audio
x-requestid: <32 byte ID>
x-timestamp: 2019-08-02T23:01:19.555Z
(length: 99 bytes)

**Comment by gabrielfreire** [comment]
Hi @rhurey , thanks for your reply, unfortunately i couldn't make the SDK work on Xamarin. I looked through the source code in the Typescript SDK, but i think my issue is on writing this Header specifically in C#, if you could help me with a BinaryWriter snippet for this header.
Thanks

**Comment by gabrielfreire** [comment]
Hi, i managed to get it working, 

But i would like to understand the documentation 

> The first 2 bytes of the binary WebSocket message specify, in big-endian order, the 16-bit integer size of the header section

In my very limited understanding, writing a Int16 value for the length of the header should suffice, but what i ended up doing was to skip the first byte, and write the length in the second, like so
```csharp
using (var writer = new BinaryWriter(stream, Encoding.ASCII, true))
{
     var headerLength = (short)GetHeaderSize(header);
     writer.Seek(1, SeekOrigin.Begin); // skip position 0
     writer.Write(new byte[] { (byte)headerLength }); // write at position 1
 // ... the rest of the header, etc
}
``` 
This way i managed to get the service working, but i don't understand why the documentation doesn't mention that we must skip the first byte, would this be what `big-endian` order means ? the way i understand, the following should be enough
```csharp
using (var writer = new BinaryWriter(stream, Encoding.ASCII, true))
{
     var headerLength = (short)GetHeaderSize(header);
     writer.Write(new byte[] { (byte)headerLength }); // Position 0
 // ... the rest of the header, etc
}
``` 

But maybe i don't know enough about writing binaries, anyway, if you could provide a simple explanation, thank you :)

**Comment by rhurey** [comment]
BinaryWriter.Write(Int16) is documented to write little endian.

https://docs.microsoft.com/en-us/dotnet/api/system.io.binarywriter.write

So it reversed the bytes on you. By writing only one byte you didn’t give it any choice.

A decent article on endianness: https://en.m.wikipedia.org/wiki/Endianness

**Comment by gabrielfreire** [comment]
Just in case somebody else get stuck on the endianess thing

This is how we invert the order from little endian to big endian
```csharp
public byte[] GetBigEndianLength()
        {

            var headerBytes = new buffer[...]; // the buffer

            var headerHeadBytes = BitConverter.GetBytes((UInt16)headerBytes.Length);
            var isBigEndian = !BitConverter.IsLittleEndian;
            var headerHead = !isBigEndian ? new byte[] { headerHeadBytes[1], headerHeadBytes[0] } : new byte[] { headerHeadBytes[0], headerHeadBytes[1] };
            return headerHead;
        }
```
Cheers

**Comment by jhakulin** [comment]
Closing this issue with the note that Xamarin support is being worked on currently and targeted to be available in the coming speech SDK release.
