### ISSUE TITLE
missing .so native library for Android deployment

### ISSUE THREAD

**Issue by erezbaum** [Azure-Samples/cognitive-services-speech-sdk#33]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Download/Clone the repo at https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/java-android
2. Build and Run the quick-start app according to the instructions provided
3. Run on Pixel API 26 emulator
>

### Any log messages given by the failure
The app crashes on start with the log:
08-22 22:08:33.601 20360-20360/com.microsoft.cognitiveservices.speech.samples.sdkdemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.microsoft.cognitiveservices.speech.samples.sdkdemo, PID: 20360
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList
... truncated..
couldn't find "libMicrosoft.CognitiveServices.Speech.java.bindings.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.microsoft.cognitiveservices.speech.SpeechFactory.<clinit>(SpeechFactory.java:52)
        at com.microsoft.cognitiveservices.speech.SpeechFactory.configureNativePlatformBindingWithDefaultCertificate(SpeechFactory.java:81)
08-22 22:08:33.603 20360-20360/com.microsoft.cognitiveservices.speech.samples.sdkdemo 
>

### Expected/desired behavior
>

### OS and Version?
Android SDK API 26
Android Studio 3.1.4
> 
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wolfma61** [comment]
we heard you - we will have to take a look ...

**Comment by erezbaum** [comment]
I have more information: It seems the problem is caused by lack of x86 .so libraries, the ARM libraries (both for arm64-v8a and armeabi-v7a) do exists in the distribution. The emulator I was running was based on x86 distribution since this is the recommended configuration for macOS machines and is 10x faster then emulating ARM.

**Comment by wolfma61** [comment]
thank you for the update. 
Currently we have Android only on ARM, we will support other hardware in the future. But I can't give a concrete date yet.

Wolfgang

**Comment by dingchao-95** [comment]
I'm having the same issues as well. Is there currently a workaround for this?

**Comment by wolfma61** [comment]
no work around - beside us providing an non-ARM version. This is NOT part of the next refresh ...
no confirmed ETA yet

**Comment by wolfma61** [comment]
closing - until we can post a clear shipping date ....
