### ISSUE TITLE
 How to get the voice recognition sent to the server's audio？

### ISSUE THREAD

**Issue by kknsy** [Azure-Samples/cognitive-services-speech-sdk#330]
C# Unity sample for Windows or Android， How to get the voice recognition sent to the server's audio？In the demo, I can get the result text data，So what method can I use to get audio data?

**Comment by kknsy** [comment]
The version before speech recognition is to record voice through unity and then send voice data, but now I don't know how he sends voice data to the server, and I want to know how to get this voice data.

**Comment by kknsy** [comment]
The SDK itself does not have the functionality to save audio data in a file，I know.But how do I get this audio data?I need to implement the function to back up this audio data to my own background, so that I can view these raw data in the background.

**Comment by chrisbasoglu** [comment]
The best way to be do this would be to save the audio in your app before sending the audio to the SDK.  If you are using our SDK to open the microphone, you will need to open the microphone yourself, get the audio data from the microphone, save the audio data, and then pass the audio to the SDK via stream.

**Comment by jackyhanyu** [comment]
how to pass the audio to sdk via stream?c# example support get audio data from  result.audioData,why unity sdk don't support?

**Comment by jhakulin** [comment]
Related to streams, please check the answer on the previous issue https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/342#issuecomment-519798612

**Comment by pankopon** [comment]
Closing this case due to no further comments. Please re-open if you still need more information.
