### ISSUE TITLE
Microsoft Translator APP uses cognitive-service-speech-sdk?

### ISSUE THREAD

**Issue by BlueAnthony** [Azure-Samples/cognitive-services-speech-sdk#332]
Microsoft Translator APP uses cognitive-service-speech-sdk?
Because the inference result from Microsoft Translator APP is worse than from cognitive-service-speech. But the audio reception of Microsoft Translator APP is more sensitive than cognitive-service. And, I test them on the same mobile phone.
Do they use the same model?
Thank you~

**Comment by lisaweixu** [comment]
The Microsoft Translator App does not use cognitive-service-speech-sdk.  The App is planing to use cognitive-service-sdk in the future.
