### ISSUE TITLE
BatchTranscription: Why are there multiple AudioFileResults and SegmentResults?

### ISSUE THREAD

**Issue by Kleinhummel** [Azure-Samples/cognitive-services-speech-sdk#333]
I don't really understand why the TranscriptionResult of the Batch-Transcription has multiple AudioFileResults...Is it able to transcribe multiple AudioFiles at the same time?
And why are there multiple SegmentResults in an AudioFileResult?
What is a segment, when do I have more than one segment and are segments used when I don't use the sentiment analysis feature of the batch-transcription?
And I also don't really understand what NBest stands for and why there are multiple NBest in one SegmentResult

**Comment by chrisbasoglu** [comment]
1. In case of multiple channels in the file (stereo for example)
2. Each segment can be thought of audio separated by long silence (like the silence found between sentences or paragraphs). 
3. For each segment, we can have multiple possible recognition choices.  NBest is the list of N best possible choices.  They are ordered by most likely correct to least likely correct.

**Comment by Kleinhummel** [comment]
> 1. In case of multiple channels in the file (stereo for example)
> 2. Each segment can be thought of audio separated by long silence (like the silence found between sentences or paragraphs).
> 3. For each segment, we can have multiple possible recognition choices.  NBest is the list of N best possible choices.  They are ordered by most likely correct to least likely correct.

Ah ok, thank you very much. That helped a lot!
