### ISSUE TITLE
How to use speech-to-text API with python in Chinese? 

### ISSUE THREAD

**Issue by 18617109893** [Azure-Samples/cognitive-services-speech-sdk#335]
How can i use speech-to-text API with python in Chinese? I have tried quick start demo with python, and English recognition is good, but what about Chinese? is there any documentation?Many Thanks!

**Comment by chlandsi** [comment]
You can set the speech recognition language on the [`SpeechConfig`](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.speechconfig?view=azure-python) object, e.g. `config = SpeechConfig(subscription=speech_key, region=service_region, speech_recognition_language='zh-CN')`.
The list of supported languages with the corresponding codes is [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support).

**Comment by 18617109893** [comment]
@chlandsi You're handsome! Thanks.
By the way, do you have more guide about "start_continuous_recognition()"?

**Comment by chlandsi** [comment]
Thank you, glad to help ;) Please have a look at our [extended Python samples](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/python/console). These cover continuous recognition and other related topics.

**Comment by 18617109893** [comment]
@chlandsi Thanks a lot! ~~
