### ISSUE TITLE
LUIS + Custom Speech Model integration.

### ISSUE THREAD

**Issue by rurounijones** [Azure-Samples/cognitive-services-speech-sdk#336]
**Is your feature request related to a problem? Please describe.**

This is a feature request to solve a problem. Currently my applications uses Language Understanding Model (LUIS) with Intents to be able to process requests. The corpus of words and general language causes LUIS much trouble and it is frequently unable to transcribe the Speech To Text correctly.

I looked into using Custom Speech models ( https://speech.microsoft.com )  and after some initial training the results look very promising in improving the accuracy of transcription.

However as best I can determine the Custom Speech model is only usable by `SpeechRecognizer` and not LUIS `IntentRecognizer`s using the C# Speech SDK (Not sure on other languages but I imagine the same issue).

This is a gap in functionality and *appears* to be an obvious synergistic feature. However I found a related ticket that indicates a request similar / identical to this has been open for over a year ( https://github.com/Microsoft/BotFramework-WebChat/issues/1216 ) and a feature request on uservoice hasn't been updated for 4 months : https://cognitive.uservoice.com/forums/551524-language-understanding-luis/suggestions/36350680-speech-support-of-custom-speech-models-from-cris

**Describe the solution you'd like**
Applications using LUIS to be able to benefit from custom Speech models to improve transcription accuracy. Using whatever method microsoft deems best. Possibly by being able to specify the custom speech endpoint as a separate part of the `SpeechConfig` option or by setting it in the backend LUIS portal.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by wolfma61** [comment]
there are several projects ongoing that integrate intent closer with the rest of the speech services, while keeping backwards compatibility. The first integration stage should go live by the end of October (and will be transparent to the user). In following stages intent will integrate with custom speech and other services. That should happen late this calendar year.

Sorry - I can't give you an exact date at this time.
