### ISSUE TITLE
I am getting bad request (400) when I accessed post method transcription

### ISSUE THREAD

**Issue by rnpramasamy** [Azure-Samples/cognitive-services-speech-sdk#337]
I cloned batch transcription repository, tired it and worked fine.

Copied code from repository, created durable azure function, pasted code in it , tested it and but I got bad request when I invoked post method of batch transcription.

Please help me.

**Comment by rarera** [comment]
Hi rnpramasamy,

are you refering to this sample (C# version) : https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch ?

With 400 some request data has to be different.
Are you using in both tries the same version of NewtonSoft json. I have no personal experience with Durable Azure Functions, but I remember that there were some limitations regarding supported versions of NewtonSoft.

Thanks,
Ramin

**Comment by rarera** [comment]
Hi rnpramasamy,

Please let me know if the nuget versions you use are the same for the Azure Function.
Besides that I realized there was a recent PR for this. Maybe you should pull the repo and see if that helps with your issue.

**Comment by pankopon** [comment]
Closing the issue as resolved, based on the linked PR.
