### ISSUE TITLE
500 error code happened when i tried to get all transcritions i created

### ISSUE THREAD

**Issue by LWleo** [Azure-Samples/cognitive-services-speech-sdk#338]
Hi,
I use demo code( cognitive-services-speech-sdk/samples/batch/csharp/) to transcribe some audio files on Azure blob storage. The code worked properly two months ago.  But now I try to get all transcriptions by request the service address(api/speechtotext/v2.0/Transcriptions). It makes me wait a long time and return 500 error code when I  debug at the code "using (var response = await this.client.GetAsync(path).ConfigureAwait(false))". 
 please help me to solve this problem. 

Thanks.

**Comment by mahilleb-msft** [comment]
Hi,

  for investigation, could you let us know your region and Subscription ID, i.e., the ID of your speech subscription resource in Azure, **not** the (secret) subscription key in Azure.

  Thanks, Mark

**Comment by LWleo** [comment]
Hi Mark,

I'm not sure if i have the permission to tell you these information, but I find a email address that is provided in https://westus.cris.ai/swagger/ui/index#/Custom%20Speech%20accuracy%20tests%3A. and I send a email to the team by MS email. Thank you anyway.

Thanks,
Li.

**Comment by mahilleb-msft** [comment]
Ok .. closing here.
