### ISSUE TITLE
access violation in AddIntent

### ISSUE THREAD

**Issue by hramoser** [Azure-Samples/cognitive-services-speech-sdk#34]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
```
auto factory = SpeechFactory::FromSubscription(L"xxxx", L"westeurope");
auto recognizer = factory->CreateIntentRecognizer(L"en-US");
auto model = Intent::LanguageUnderstandingModel::FromAppId(L"xxxx");
recognizer->AddIntent(L"id1", model); // <- access violation in speechapi_cxx_intent_trigger.h line 47
```   
But   
```
recognizer->AddIntent(L"dummy", model, L"dummy"); // this works fine
```

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 10 and Ubuntu 16.04 

### Versions
> Speech SDK 0.5 and 0.6

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wolfma61** [comment]
we'll investigate ...

**Comment by wolfma61** [comment]
there have been several bug fixes and this will be changed/updated in a soon to come release ...
