### ISSUE TITLE
start_continuous_recognition() -- not working

### ISSUE THREAD

**Issue by Khushu06** [Azure-Samples/cognitive-services-speech-sdk#340]
import azure.cognitiveservices.speech as speechsdk

# Creates an instance of a speech config with specified subscription key and service region.
# Replace with your own subscription key and service region (e.g., "westus").
speech_key, service_region = "Key", "Region"
speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)

# Creates a recognizer with the given settings
speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config)

print("Say something...")

# Starts speech recognition, and returns after a single utterance is recognized. The end of a
# single utterance is determined by listening for silence at the end or until a maximum of 15
# seconds of audio is processed.  The task returns the recognition text as result. 
# Note: Since recognize_once() returns only a single utterance, it is suitable only for single
# shot recognition like command or query. 
# For long-running multi-utterance recognition, use start_continuous_recognition() instead.
result = speech_recognizer.start_continuous_recognition()

#Checks result.
if result.reason == speechsdk.ResultReason.RecognizedSpeech:
    print("Recognized: {}".format(result.text))
elif result.reason == speechsdk.ResultReason.NoMatch:
    print("No speech could be recognized: {}".format(result.no_match_details))
elif result.reason == speechsdk.ResultReason.Canceled:
    cancellation_details = result.cancellation_details
    print("Speech Recognition canceled: {}".format(cancellation_details.reason))
    if cancellation_details.reason == speechsdk.CancellationReason.Error:
        print("Error details: {}".format(cancellation_details.error_details))

**The error is :**

Say...
Traceback (most recent call last):
  File "C:\Users\Khushboo.Girotra\Desktop\audio2textmicro.py", line 31, in <module>
    if result.reason == speechsdk.ResultReason.RecognizedSpeech:
AttributeError: 'NoneType' object has no attribute 'reason'

Kindly help

**Comment by rhurey** [comment]
First, please edit the post above and remove your key.

Continuous recognition is event based, see https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_sample.py (speech_recognize_continuous_from_file) for a sample of how to connect and get events for continuous recognition.

**Comment by Khushu06** [comment]
I have used the code from the above link only . When I am trying to use  start_continuous_recognition() in place of  recognize_once() for long-running multi-utterance recognition, it is showing an error

**Comment by Khushu06** [comment]
Okay , thanks let me try

**Comment by Khushu06** [comment]
#!/usr/bin/env python
# coding: utf-8

# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE.md file in the project root for full license information.

import time
import wave

try:
    import azure.cognitiveservices.speech as speechsdk
except ImportError:
    print("""
    Importing the Speech SDK for Python failed.
    Refer to
    https://docs.microsoft.com/azure/cognitive-services/speech-service/quickstart-python for
    installation instructions.
    """)
    import sys
    sys.exit(1)


# Set up the subscription info for the Speech Service:
# Replace with your own subscription key and service region (e.g., "westus").
speech_key, service_region = "key", "region"

# Specify the path to an audio file containing speech (mono WAV / PCM with a sampling rate of 16
# kHz).
english = 'C:/Users/KK/Desktop/Audio/english.wav'



def speech_recognize_continuous_from_file():
    """performs continuous speech recognition with input from an audio file"""
    # <SpeechContinuousRecognitionWithFile>
    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)
    audio_config = speechsdk.audio.AudioConfig(filename=english)

    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)

    done = False

    def stop_cb(evt):
        """callback that stops continuous recognition upon receiving an event `evt`"""
        print('CLOSING on {}'.format(evt))
        speech_recognizer.stop_continuous_recognition()
        nonlocal done
        done = True

    # Connect callbacks to the events fired by the speech recognizer
    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
    speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))
    # stop continuous recognition on either session stopped or canceled events
    speech_recognizer.session_stopped.connect(stop_cb)
    speech_recognizer.canceled.connect(stop_cb)

    # Start continuous speech recognition
    speech_recognizer.start_continuous_recognition()
    while not done:
        time.sleep(.5)
    # </SpeechContinuousRecognitionWithFile>

I tried running this code , but it is not showing anything in the prompt /no error reflecting

**Comment by chlandsi** [comment]
It's hard to tell because the formatting in the pasted code is lost (best to wrap in a block of triple backticks `` ``` ... ``` ``), but are you calling the `speech_recognize_continuous_from_file()` function? Try running the `main.py` file provided in the sample directory (after adding subscription info and the path to a wave file to `speech_sample.py`), it provides a way to run all the different samples.

**Comment by Khushu06** [comment]
Can you please direct me the path of main.py and speech_sample.py .
I am very new to this !

**Comment by chlandsi** [comment]
Both files, along with instructions on how to use the sample, can be found [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/python/console).

**Comment by Khushu06** [comment]
``` #!/usr/bin/env python
# coding: utf-8

# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE.md file in the project root for full license information.

import speech_sample
import intent_sample
import translation_sample

from collections import OrderedDict
import platform

eofkey = 'Ctrl-Z' if "Windows" == platform.system() else 'Ctrl-D'

samples = OrderedDict([
    (speech_sample, [
        speech_sample.speech_recognize_once_from_mic,
        speech_sample.speech_recognize_once_from_file,
        speech_sample.speech_recognize_once_from_file_with_customized_model,
        speech_sample.speech_recognize_once_from_file_with_custom_endpoint_parameters,
        speech_sample.speech_recognize_async_from_file,
        speech_sample.speech_recognize_continuous_from_file,
        speech_sample.speech_recognition_with_pull_stream,
        speech_sample.speech_recognition_with_push_stream,
        speech_sample.speech_recognize_keyword_from_microphone,
    ]), (intent_sample, [
        intent_sample.recognize_intent_once_from_mic,
        intent_sample.recognize_intent_once_async_from_mic,
        intent_sample.recognize_intent_once_from_file,
        intent_sample.recognize_intent_continuous,
    ]), (translation_sample, [
        translation_sample.translation_once_from_mic,
        translation_sample.translation_once_from_file,
        translation_sample.translation_continuous,
    ])
])


def select():
    print('select sample module, {} to abort'.format(eofkey))
    modules = list(samples.keys())
    for i, module in enumerate(modules):
        print(i, module.__name__)

    try:
        num = int(input())
        selected_module = modules[num]
    except EOFError:
        raise
    except Exception as e:
        print(e)
        return

    print('select sample function, {} to abort'.format(eofkey))
    for i, fun in enumerate(samples[selected_module]):
        print(i, fun.__name__)

    try:
        num = int(input())
        selected_function = samples[selected_module][num]
    except EOFError:
        raise
    except Exception as e:
        print(e)
        return

    print('You selected: {}'.format(selected_function))
    try:
        selected_function()
    except Exception as e:
        print('Error running sample: {}'.format(e))

    print()


while True:
    try:
        select()
    except EOFError:
        break```

I have tried running this code  (main.py) . It reflects below error:

Traceback (most recent call last):
  File "C:/Users/Khushboo.Girotra/Desktop/Audio/main.py", line 7, in <module>
    import speech_sample
ModuleNotFoundError: No module named 'speech_sample'

**Comment by chlandsi** [comment]
All the .py files from the sample must be present in the same folder. Try following [these instructions](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/README.md#get-the-samples) to make sure all the files are in the right places.

**Comment by Khushu06** [comment]
It is still reflecting the above error. I have downloaded the zip file and kept at desktop

**Comment by chlandsi** [comment]
Did you unzip the file? The resulting path should be something like `C:/Users/Khushboo.Girotra/Desktop/cognitive-services-speech-sdk-master/samples/python/console/main.py`; the other 3 python files need to be in the same folder `C:/Users/Khushboo.Girotra/Desktop/cognitive-services-speech-sdk-master/samples/python/console`.

**Comment by Khushu06** [comment]
Yes , I got it it is there. I run main.py 
It gave this result :
 RESTART: C:\Users\Khushboo.Girotra\Desktop\cognitive-services-speech-sdk-master\samples\python\console\main.py 
select sample module, Ctrl-Z to abort
0 speech_sample
1 intent_sample
2 translation_sample

**Comment by Khushu06** [comment]
```#!/usr/bin/env python
# coding: utf-8

# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE.md file in the project root for full license information.

import time
import wave

try:
    import azure.cognitiveservices.speech as speechsdk
except ImportError:
    print("""
    Importing the Speech SDK for Python failed.
    Refer to
    https://docs.microsoft.com/azure/cognitive-services/speech-service/quickstart-python for
    installation instructions.
    """)
    import sys
    sys.exit(1)


# Set up the subscription info for the Speech Service:
# Replace with your own subscription key and service region (e.g., "westus").
speech_key, service_region = "key", "region"

# Specify the path to an audio file containing speech (mono WAV / PCM with a sampling rate of 16
# kHz).
english = "C:/Users/Khushboo.Girotra/Desktop/Audio/english.wav"


def speech_recognize_continuous_from_file():
    """performs continuous speech recognition with input from an audio file"""
    # <SpeechContinuousRecognitionWithFile>
    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)
    audio_config = speechsdk.audio.AudioConfig(filename=english)

    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)

    done = False

    def stop_cb(evt):
        """callback that stops continuous recognition upon receiving an event `evt`"""
        print('CLOSING on {}'.format(evt))
        speech_recognizer.stop_continuous_recognition()
        nonlocal done
        done = True

    # Connect callbacks to the events fired by the speech recognizer
    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
    speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))
    # stop continuous recognition on either session stopped or canceled events
    speech_recognizer.session_stopped.connect(stop_cb)
    speech_recognizer.canceled.connect(stop_cb)

    # Start continuous speech recognition
    speech_recognizer.start_continuous_recognition()
    while not done:
        time.sleep(.5)
    # </SpeechContinuousRecognitionWithFile>```

I tried running the same query again , it is not reflecting anything in prompt. Now all the paths are correct.
Result:

 RESTART: C:\Users\Khushboo.Girotra\Desktop\cognitive-services-speech-sdk-master\samples\python\console\speech_sample.py 
>>>

**Comment by chlandsi** [comment]
When you run the `main.py`, you need to enter the digit corresponding to the sample you want to run. To run the sample for continuous speech recognition, this should be `0 <enter> 5 <enter>`.

**Comment by Khushu06** [comment]
```RESTART: C:\Users\Khushboo.Girotra\Desktop\cognitive-services-speech-sdk-master\cognitive-services-speech-sdk-master\samples\python\console\main.py 
select sample module, Ctrl-Z to abort
0 speech_sample
1 intent_sample
2 translation_sample
0
select sample function, Ctrl-Z to abort
0 speech_recognize_once_from_mic
1 speech_recognize_once_from_file
2 speech_recognize_once_from_file_with_customized_model
3 speech_recognize_once_from_file_with_custom_endpoint_parameters
4 speech_recognize_async_from_file
5 speech_recognize_continuous_from_file
6 speech_recognition_with_pull_stream
7 speech_recognition_with_push_stream
8 speech_recognize_keyword_from_microphone
5
You selected: <function speech_recognize_continuous_from_file at 0x0000022DCFA47678>
Error running sample: Exception with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED)
[CALL STACK BEGIN]

    > CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - recognizer_stop_keyword_recognition_async_wait_for

    - recognizer_create_speech_recognizer_from_config

    - 00007FFF3FB47505 (SymFromAddr() error: Attempt to access invalid address.)

    - PyInit__speech_py_impl

    - 00007FFF3FABD22C (SymFromAddr() error: Attempt to access invalid address.)

    - PyMethodDef_RawFastCallKeywords

    - PyMethodDef_RawFastCallKeywords

    - PyEval_EvalFrameDefault

    - PyMethodDef_RawFastCallKeywords



[CALL STACK END]



select sample module, Ctrl-Z to abort
0 speech_sample
1 intent_sample
2 translation_sample```

I got this when I enter 0 and 5

**Comment by chlandsi** [comment]
Very likely this means the path to the audio file given in `speech_sample.py` ([here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/098e2288e215f0fee5fe630acb0c39b41919a49d/samples/python/console/speech_sample.py#L29) is not correct. Make sure that is a valid absolute path.

**Comment by Khushu06** [comment]
Can you direct me , If my audio file is in _Hindi language_(What is the code for the same ). 

Where in code do I have to mention about that and Moreover it's a **4 minutes audio**

**Comment by chlandsi** [comment]
You can set the speech recognition language on the SpeechConfig object, e.g. `speech_config = SpeechConfig(subscription=speech_key, region=service_region, speech_recognition_language='hi-IN')`. In the sample code, this is in [line 196].(https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/098e2288e215f0fee5fe630acb0c39b41919a49d/samples/python/console/speech_sample.py#L196)
The list of supported languages with the corresponding codes is [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support).

**Comment by Khushu06** [comment]
```#!/usr/bin/env python
# coding: utf-8

# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE.md file in the project root for full license information.

import time
import wave

try:
    import azure.cognitiveservices.speech as speechsdk
except ImportError:
    print("""
    Importing the Speech SDK for Python failed.
    Refer to
    https://docs.microsoft.com/azure/cognitive-services/speech-service/quickstart-python for
    installation instructions.
    """)
    import sys
    sys.exit(1)


# Set up the subscription info for the Speech Service:
# Replace with your own subscription key and service region (e.g., "westus").
speech_key, service_region = "key", "region"

# Specify the path to an audio file containing speech (mono WAV / PCM with a sampling rate of 16
# kHz).
hindi = "C:/Users/Khushboo.Girotra/Desktop/audio1.wav"
def speech_recognize_continuous_from_file():
    """performs continuous speech recognition with input from an audio file"""
    # <SpeechContinuousRecognitionWithFile>
    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region,speech_recognition_language='hi-IN')
    audio_config = speechsdk.audio.AudioConfig(filename=hindi)

    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)

    done = False

    def stop_cb(evt):
        """callback that stops continuous recognition upon receiving an event `evt`"""
        print('CLOSING on {}'.format(evt))
        speech_recognizer.stop_continuous_recognition()
        nonlocal done
        done = True

    # Connect callbacks to the events fired by the speech recognizer
    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
    speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))
    # stop continuous recognition on either session stopped or canceled events
    speech_recognizer.session_stopped.connect(stop_cb)
    speech_recognizer.canceled.connect(stop_cb)

    # Start continuous speech recognition
    speech_recognizer.start_continuous_recognition()
    while not done:
        time.sleep(.5)
    # </SpeechContinuousRecognitionWithFile>```

```I made these changes for hindi audio , it is still not working .

 RESTART: C:\Users\Khushboo.Girotra\Desktop\cognitive-services-speech-sdk-master\samples\python\console\main.py 
select sample module, Ctrl-Z to abort
0 speech_sample
1 intent_sample
2 translation_sample
0
select sample function, Ctrl-Z to abort
0 speech_recognize_once_from_mic
1 speech_recognize_once_from_file
2 speech_recognize_once_from_file_with_customized_model
3 speech_recognize_once_from_file_with_custom_endpoint_parameters
4 speech_recognize_async_from_file
5 speech_recognize_continuous_from_file
6 speech_recognition_with_pull_stream
7 speech_recognition_with_push_stream
8 speech_recognize_keyword_from_microphone
5
You selected: <function speech_recognize_continuous_from_file at 0x0000019054446708>

=============================== RESTART: Shell ===============================
>>> ```

**Comment by chrisbasoglu** [comment]
Can you confirm that your file is mono WAV / PCM with a sampling rate of 16 kHz ?

**Comment by Khushu06** [comment]
It's a wav file but there is noise in the audio

**Comment by chrisbasoglu** [comment]
Is the wave file PCM and 16 KHz inside?  You can use a tool like Audacity to load the wav file and check its format inside.
![image](https://user-images.githubusercontent.com/16262519/62717945-af247080-b9b9-11e9-847a-26b015234813.png)

**Comment by Khushu06** [comment]
![audio](https://user-images.githubusercontent.com/53889816/62718125-e3804700-ba22-11e9-8ea4-55adacce3f4b.JPG)

**Comment by chrisbasoglu** [comment]
8KHz 32-bit float will not work.  So you need to convert your file to 16 KHz, and 16-bit.  You can use a "Export" feature in Audacity ("Save as Wav") and choose "Wav (Microsoft) signed 16-bit PCM" before clicking on Save.  

![image](https://user-images.githubusercontent.com/16262519/62718590-f95a2180-b9ba-11e9-8701-16a8bf4962b0.png)

**Comment by Khushu06** [comment]
![new](https://user-images.githubusercontent.com/53889816/62719013-a026d800-ba24-11e9-9cf7-19d517878763.JPG)

I have saved the file in the above mentioned format , but it is still showing the same 8kHz format

**Comment by chlandsi** [comment]
8 kHz sampling frequency should work, too.

**Comment by Khushu06** [comment]
```
RECOGNIZING: SpeechRecognitionEventArgs(session_id=e8ca7844f97a4f7b9ed1e150887022bb, result=SpeechRecognitionResult(result_id=06be63236b9c4e04b4a1eb9e434acc3e, text="चार फ़िल्म की योजना का सर्विस कैसी किया गया है अच्छा कैटरीना किया इसके अलावा आप कितना मज़ा आएगा", reason=ResultReason.RecognizingSpeech))
RECOGNIZING: SpeechRecognitionEventArgs(session_id=e8ca7844f97a4f7b9ed1e150887022bb, result=SpeechRecognitionResult(result_id=5bdb853f494746d395d3c501ae19c598, text="चार फ़िल्म की योजना का सर्विस कैसी किया गया है अच्छा कैटरीना किया इसके अलावा आप कितना मज़ा", reason=ResultReason.RecognizingSpeech))
RECOGNIZING: SpeechRecognitionEventArgs(session_id=e8ca7844f97a4f7b9ed1e150887022bb, result=SpeechRecognitionResult(result_id=f2ea48c8e84143199c0367936d0747ee, text="चार फ़िल्म की योजना का सर्विस कैसी किया गया है अच्छा कैटरीना किया इसके अलावा आप कितना मज़ा आएगा", reason=ResultReason.RecognizingSpeech))
RECOGNIZING: SpeechRecognitionEventArgs(session_id=e8ca7844f97a4f7b9ed1e150887022bb, result=SpeechRecognitionResult(result_id=86ee25455f7641c2b00c41635a55f4fa, text="चार फ़िल्म की योजना का सर्विस कैसी किया गया है अच्छा कैटरीना किया इसके अलावा आप कितना मदरसा के रास्ते से", reason=ResultReason.RecognizingSpeech))
RECOGNIZED: SpeechRecognitionEventArgs(session_id=e8ca7844f97a4f7b9ed1e150887022bb, result=SpeechRecognitionResult(result_id=7685b5ac00394e499b23a4cdef64faac, text="4 फ़िल्म की योजना का सर्विस कैसी किया गया है अच्छा कैटरीना किया इसके अलावा आप कितना मदरसा के रास्ते से", reason=ResultReason.RecognizedSpeech))
CANCELED SpeechRecognitionCanceledEventArgs(session_id=e8ca7844f97a4f7b9ed1e150887022bb, result=SpeechRecognitionResult(result_id=34a4dc0261f24119a66b3da8be9f58a4, text="", reason=ResultReason.Canceled))
CLOSING on SpeechRecognitionCanceledEventArgs(session_id=e8ca7844f97a4f7b9ed1e150887022bb, result=SpeechRecognitionResult(result_id=34a4dc0261f24119a66b3da8be9f58a4, text="", reason=ResultReason.Canceled))
SESSION STOPPED SessionEventArgs(session_id=e8ca7844f97a4f7b9ed1e150887022bb)
CLOSING on SessionEventArgs(session_id=e8ca7844f97a4f7b9ed1e150887022bb)```
The audio file got converted to 16Khz but it was still 32 bit float . Though the code has run now
Just wanted to know , how can I club the text , or can download any text file ?

**Comment by chlandsi** [comment]
Please refer to https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/169#issuecomment-467892120 on a hint on how to accumulate the text in a variable. You can use [standard Python methods](https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files) to save the text to a file.

Since the sample works now with your data and all SDK-related issues are resolved, I am closing this issue.

**Comment by Khushu06** [comment]
Just wanted to tell that, there is very less accuracy of the speech to text conversion of my audio file - as there is noise as well. Moreover it's telephonic conversation - there are 2 speakers in the conversation . How can I get the text on the basis of speaker 1 and speaker 2 ?
