### ISSUE TITLE
[unity]C# Unity sample for Windows or Android.SpeechRecognizer，How to send voice messages to the server

### ISSUE THREAD

**Issue by kknsy** [Azure-Samples/cognitive-services-speech-sdk#342]
I didn't find what the SpeechRecognizer sent to the server, but I got the text message of the voice transfer. I tried to record the voice with the Microphone but I got a delay than you. I can't directly get the voice information sent by the SpeechRecognizer as a backup to our own. Backstage for easy viewing.
@zhouwangzw

**Comment by zhouwangzw** [comment]
Not sure I completely understand your question. Do you want have a copy of audio that you sent for recognition via SpeechRecognizer? If so, Speech SDK does not have API to do that, but it has AudioPullInputStream or AudioPushInputStream, which allows you to stream audio to server. You can get audio directly from microphone, send it to service via AudioPull/PushInputStream API, and at the same time you have a copy of audio. With AudioPull/PushInputStream API, you can send data at any time, without waiting for the end of speech, so the delay is negligible. You can find samples  about using [PullStream](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L246) and [PushStream](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L318).

Thanks,
Zhou

**Comment by kknsy** [comment]
if (recognizer == null)
        {
            SpeechConfig config = SpeechConfig.FromSubscription(SpeechServiceAPIKey, SpeechServiceRegion);
            config.SpeechRecognitionLanguage = fromLanguage;
            recognizer = new SpeechRecognizer(config);

            if (recognizer != null)
            {
                // Subscribes to speech events.
                recognizer.Recognizing += RecognizingHandler;
                recognizer.Recognized += RecognizedHandler;
                recognizer.SpeechStartDetected += SpeechStartDetectedHandler;
                recognizer.SpeechEndDetected += SpeechEndDetectedHandler;
                recognizer.Canceled += CanceledHandler;
                recognizer.SessionStarted += SessionStartedHandler;
                recognizer.SessionStopped += SessionStoppedHandler;
            }
        }
        UnityEngine.Debug.LogFormat("CreateSpeechRecognizer exit");



   private void RecognizingHandler(object sender, SpeechRecognitionEventArgs e)
    {
        if (e.Result.Reason == ResultReason.RecognizingSpeech)
        {
            UnityEngine.Debug.LogFormat($"HYPOTHESIS: Text={e.Result.Text}");
            lock (threadLocker)
            {
                recognizedString = $"HYPOTHESIS: {Environment.NewLine}{e.Result.Text}";
                valueing = e.Result.Text;
            }
        }
    }


Created a recognizer ，I got the text.But I don't know what  I sent to the server

**Comment by kknsy** [comment]
I am now doing real-time voice-to-text, and also record the voice content I said on our own server, so that users can view their voice records later.
@zhouwangzw

**Comment by zhouwangzw** [comment]
please take a look at the samples I mentioned above. AudioPush/PullInputStream should resolve your problem.

Thanks

**Comment by kknsy** [comment]
Sorry, because other things have been delayed until now, I moved the speech_recognition_samples.cs and helper.cs to the unity project and called but did not succeed.
The first problem that arises is to save the audio file there，I temporarily hide him from how it works and doesn't work.
![image](https://user-images.githubusercontent.com/26211860/63149695-70d12600-c037-11e9-95d1-8c7ea1e3790b.png)
![image](https://user-images.githubusercontent.com/26211860/63149706-77f83400-c037-11e9-9c65-3eec2c69a55f.png)

![image](https://user-images.githubusercontent.com/26211860/63149763-9ceca700-c037-11e9-9965-a563c3fae401.png)

![image](https://user-images.githubusercontent.com/26211860/63149877-ef2dc800-c037-11e9-981c-c85353db05d5.png)

![image](https://user-images.githubusercontent.com/26211860/63149913-05d41f00-c038-11e9-8d55-1b55c6a15026.png)
@zhouwangzw

**Comment by zhouwangzw** [comment]
I am not an Unity expert. We do have samples for Unity [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/unity/speechrecognizer). Are you able to run the samples?

**Comment by kknsy** [comment]
Unity project can run, but unity has no audio transmission information，I am continuing to try to modify.C#，Why did you enter the boost error input?
![image](https://user-images.githubusercontent.com/26211860/63152073-88aba880-c03d-11e9-9fbf-840f3866dffe.png)
![image](https://user-images.githubusercontent.com/26211860/63152222-e63ff500-c03d-11e9-943d-8a239feb83ac.png)

**Comment by kknsy** [comment]
![image](https://user-images.githubusercontent.com/26211860/63152752-2b185b80-c03f-11e9-8a65-4b91350e16a6.png)
This is the reason for the Chinese input method.

**Comment by zhouwangzw** [comment]
It seems the input read by the sample is invalid. Check the sample code [here
 ](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/Program.cs#L50)
               x = Console.ReadKey();
                Console.WriteLine("");
                switch (x.Key)
What is the console key you got when running the sample? Were you using different keyboard layout or locale?

**Comment by kknsy** [comment]
That is the reason for the Chinese input method， thank you for your help
