### ISSUE TITLE
error when converting a wav audio file to text

### ISSUE THREAD

**Issue by eddyzhu1980** [Azure-Samples/cognitive-services-speech-sdk#344]
**Describe the bug**

**To Reproduce**
1. use .net console sample code.
2. I use Camtasia software to convert my video mp4 file to export audio file (wav file).
3. run it and select #3 to convert audio file to text. (wav file is 35 minutes long and 350MB)
3. .ApplicationException: Exception with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED)

**Expected behavior**

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.
1.6

**Platform, Operating System, and Programming Language**
 - OS: windows 10
 - Hardware - x64
 - Programming language: C#
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific

**Additional context**
 - Error messages, log information, stack trace, ...
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by chrisbasoglu** [comment]
can you verify the type of wav file produced by loading into a tool like Audacity?  Needs to be 16-bit PCM, 16KHz, Mono

![image](https://user-images.githubusercontent.com/16262519/62906888-9d2e2f00-bd25-11e9-8bb9-7234a241af63.png)

**Comment by pankopon** [comment]
Closing the issue since no further comments since August, please re-open if necessary.
