### ISSUE TITLE
japanese language modification

### ISSUE THREAD

**Issue by chinmayembedded** [Azure-Samples/cognitive-services-speech-sdk#346]
I have referred the code as below

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/python/quickstart.py

To support it for japanese language, following is my code

def speech_recognize_once_from_file():
    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)
    speech_config.speechRecognitionLanguage = 'ja-JP'
    speech_config.targetLanguage = 'ja-JP'
    audio_config = speechsdk.audio.AudioConfig(filename='file.wav')
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)
    result = speech_recognizer.recognize_once()

    # Check the result
    if result.reason == speechsdk.ResultReason.RecognizedSpeech:
        print("Recognized: {}".format(result.text))
    elif result.reason == speechsdk.ResultReason.NoMatch:
        print("No speech could be recognized: {}".format(result.no_match_details))
    elif result.reason == speechsdk.ResultReason.Canceled:
        cancellation_details = result.cancellation_details
        print("Speech Recognition canceled: {}".format(cancellation_details.reason))
        if cancellation_details.reason == speechsdk.CancellationReason.Error:
            print("Error details: {}".format(cancellation_details.error_details))

However the result text it returns is in english and not meaningful.

Please suggest the modification to be done for a japanese audio input and speech recognition output in japanese

**Comment by chlandsi** [comment]
The name of the property to select the recognition language is `speech_recognition_language` (with underscores). This is documented [here](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.speechconfig?view=azure-python).

The `target_languages` property is used for [translation](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.translation.speechtranslationconfig?view=azure-python).

**Comment by chinmayembedded** [comment]
@chlandsi Thanks!
