### ISSUE TITLE
startKeywordRecognitionAsync(model) not working Android (Java)

### ISSUE THREAD

**Issue by veeresh1456** [Azure-Samples/cognitive-services-speech-sdk#348]
**Describe the bug**
 startKeywordRecognitionAsync(model) not working Android (Java).  the execution stops on that line no error nothing.

**To Reproduce**
1. ... call startKeywordRecognitionAsync(model)  then the execution stops on that line no error nothing.

**Expected behavior**
 it should start listening for keyword.

**Version of the Cognitive Services Speech SDK**
Services Speech SDK1.6

**Platform, Operating System, and Programming Language**
 - OS: [Android,] - please be specific
 - Hardware - ARM, ...
 - Programming language:  Java,

**Additional context**
 -when i checked 

public Future<Void> startKeywordRecognitionAsync(final KeywordRecognitionModel var1) {
        Contracts.throwIfNull(var1, "model");
        return s_executorService.submit(new Callable<Void>() {
            public Void call() {
                Runnable var1x = new Runnable() {
                    public void run() {
                        SpeechRecognizer.this.recoImpl.StartKeywordRecognition(var1.getModelImpl());
                    }
                };
                SpeechRecognizer.this.doAsyncRecognitionAction(var1x);
                return null;
            }
        });
    }

the execution stops on SpeechRecognizer.this.doAsyncRecognitionAction(var1x); with no error no exception nothing..

**Comment by jhakulin** [comment]
1.8.0 release contains support for KeywordRecognizer methods on Android.
Please let us know if there is any problems
