### ISSUE TITLE
Translate Error

### ISSUE THREAD

**Issue by hold-my-hand** [Azure-Samples/cognitive-services-speech-sdk#349]
“我想要一个鸳鸯锅”，translate to ''I want a  pot", it is incorrect
 but other translate app translate it to "I want a mandarin duck pot"  it iscorrect

**Comment by amitkumarshukla** [comment]
Thanks a lot for the feedback. We have noted the issue and will work on it. Please look for our future release and it should be done. I am closing this for the time being.
