### ISSUE TITLE
Is Batch Transcription used in the Python console sample?

### ISSUE THREAD

**Issue by michhar** [Azure-Samples/cognitive-services-speech-sdk#351]
In the Python console app speech sample file, [speech_sample.py](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_sample.py), does the `speech_recognize_continuous_from_file()` function use Batch Transcription?  Trying to develop a Python sample that utilizes it.

**Comment by chlandsi** [comment]
The sample you mention uses the real-time transcription service. A sample for using the batch service with Python can be found [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python).

**Comment by amitkumarshukla** [comment]
@michhar I am closing this issue for the time being. If you still have issues please reopen this with more information.
Thanks
