### ISSUE TITLE
SpeechSynthesizer doesn't have method to cancel or stop manually

### ISSUE THREAD

**Issue by jingweihaha** [Azure-Samples/cognitive-services-speech-sdk#354]
There is no method to cancel or stop a SpeechSynthesizer, think about for a long conversation, the user already input something but she is still speaking. Referring to System.Speech.Synthesis, there are several methods to stop or cancel. Can we have the same thing here as well?

**Comment by yulin-li** [comment]
Currently we don't have a stop/cancel method in speechSyntheizer. I think maybe you can stop playing the syntheized audio manually to handle this case. Sorry for the inconvenience. Pls let me know if you have other concern.

**Comment by zxubian** [comment]
This is very inconvenient, because the synthesizer complains about being disposed while synthesizing.
An option to pass a CancellationToken would be greatly appreciated

**Comment by yulin-li** [comment]
@zxubian [StopSpeakingAsync()](https://docs.microsoft.com/en-us/cpp/cognitive-services/speech/speechsynthesizer#stopspeakingasync) method was added in release 1.14.
