### ISSUE TITLE
TranslationRecognizer can't download crl.

### ISSUE THREAD

**Issue by wall3001** [Azure-Samples/cognitive-services-speech-sdk#356]
1、install apk such as the android smaples

2、invoke recognizer.startContinuousRecognitionAsync();

3、speak something but have no result 

4、use wireshark grab bags,find that  tcp packet had lost. Sometimes the http for crl request even have not be called.

5、uninstall apk

6、repeat 1-5

We test this in China network. It offten happens. When test it in USA,it become normally.

We make sure that the network works well in China because we invoke http request "http://mscrl.microsoft.com/pki/mscorp/crl/Microsoft%20IT%20TLS%20CA%204.crl" to download this crl nomorlly.

**Comment by amitkumarshukla** [comment]
Please try with 1.11.0 version of Speech sdk and let us know if Is it still reproable ? If not could you please close the issue ?

**Comment by jhakulin** [comment]
Closed since no update, please reopen if necessary.
