### ISSUE TITLE
[Unity] Can't build for Android using IL2CPP Scripting Backend

### ISSUE THREAD

**Issue by rc1911** [Azure-Samples/cognitive-services-speech-sdk#358]
I'm unable to build for Android using Unity 2019.2.1 using the IL2CPP scripting backend. I get the following error:

`Failed running C:\Program Files\Unity\Hub\Editor\2019.2.1f1\Editor\Data\il2cpp\build/UnityLinker.exe`

The player builds fine if I use the Mono backend though.

**Comment by jhakulin** [comment]
Thanks for feedback, could you try solution workaround as suggested here
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/229#issuecomment-508820602

We are working on to improve this.

**Comment by rc1911** [comment]
> Thanks for feedback, could you try solution workaround as suggested here
> [#229 (comment)](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/229#issuecomment-508820602)
> 
> We are working on to improve this.

I've determined the issue seems to be specifically related to having Virtual Reality enabled (with the Oculus SDK). I will try the steps mentioned in #229 and see if that fixes the issue.

**Comment by jhakulin** [comment]
This will be fixed in the coming Sep release of Speech SDK
