### ISSUE TITLE
Detecting Pause

### ISSUE THREAD

**Issue by prateekvjain** [Azure-Samples/cognitive-services-speech-sdk#359]
Hi All,
We have got the Microsoft Speech to Text Integrated with the IOS app , but the challenge is user have to press the button to start audio recording and then stop it to generate the wave file and have it processed.

Would it be possible to detect the pause and have stop recording done, rather than having user press the stop button.

I am also looking at option where we use the Siri sdk to do this work and have the siri provide us the wave file and have it processed with microsoft STT rest api.

Please provide your thoughts.

**Comment by rhurey** [comment]
IOS isn't a platform I have much experience with, but looking at the sample code in https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/objective-c/ios/speech-samples/speech-samples/ViewController.m (recognizeFromMicrophone), what's preventing recognition directly from the microphone?

Perhaps some additional information on what language you're app is written in would help.

**Comment by prateekvjain** [comment]
We are using the SWIFT language and that does not have the SDK and hence record the audio and send over the rest api to Azure STT api, One of the option I am telling team to use is Objective C code shared above by you which has SDK and use bridging header.

**Comment by chlandsi** [comment]
The SDK is in fact available for Swift (via bridging header, as you mention). Please have a look at the [Swift quickstart](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/swift-ios) and also additional samples for Objective-C; this might help answer your original question.

**Comment by amitkumarshukla** [comment]
@prateekvjain I am closing this issue for the time being. If you still have the issue, please reopen it and we will get back to you.
