### ISSUE TITLE
How to delete voice signature?

### ISSUE THREAD

**Issue by leolorenzoluis** [Azure-Samples/cognitive-services-speech-sdk#360]
Looking at the specs from https://signature.centralus.cts.speech.microsoft.com/UI/index.html#/Signature/Signature_GenerateVoiceSigatureFromByteArray

It looks like it only creates signature. How do I delete a voice signature? And do Microsoft store the audio forever? Where is the data privacy for this one?

**Comment by jhakulin** [comment]
Thanks for the questions. @sarahlume could you comment on this ?
