### ISSUE TITLE
Batch for nodejs?

### ISSUE THREAD

**Issue by eformx** [Azure-Samples/cognitive-services-speech-sdk#361]
Can I use nodejs for batch transcription?  Is there any sample code?  Or is there any batch project for c#?

**Comment by zhouwangzw** [comment]
We do not have batch samples in node.js yet, but there is [C# samples](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/csharp) and [python ](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python). You can also use [Swagger](https://westus.cris.ai/swagger/ui/index).

Thanks,

**Comment by eformx** [comment]
Do you have an eta for a node.js batch solution or documentation?

**Comment by eformx** [comment]
Ran the C# batch program and I get JsonPropertyAttribute not found.  Can't run the sample project.

**Comment by chlandsi** [comment]
Please try the latest version of the [sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/csharp), and rebuild the project. The issue you mention should have been fixed by #357.
