### ISSUE TITLE
Speech Recognition on the oculus Quest with Unity

### ISSUE THREAD

**Issue by kknsy** [Azure-Samples/cognitive-services-speech-sdk#367]
Looking through the forums, I learned that the Oculus quest is a "bare bones" version of Android that doesn't have native Speech Recognition.But I want use Speech recognition with live hypotheses (i.e. interim results),Is there a solution?

**Comment by jhakulin** [comment]
Thanks for the feedback, we have not verified our SDK using Oculus Quest so cannot confirm if there is any issues on Speech SDK Unity plugin. We will put this into our backlog, please let us know your findings if you investigate this further.

**Comment by jhakulin** [comment]
Please see this comment https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/229#issuecomment-530156472

And let us know if that helps.

**Comment by kknsy** [comment]
Thank you，the SDK works on Oculus quest
