### ISSUE TITLE
Batch transcription suddenly stopped working

### ISSUE THREAD

**Issue by raosudha89** [Azure-Samples/cognitive-services-speech-sdk#368]
Hi,

For the past few months, I have been able to successfully use the batch transcription code (in python) i.e. cognitive-services-speech-sdk/samples/batch/python/python-client/main.py

However, suddenly last week it stopped working and started giving me this error below:

_File "~/cognitive-services-speech-sdk/samples/batch/python/python-client/main.py", line 121, in transcribe
    transcriptions: List[cris_client.Transcription] = transcription_api.get_transcriptions()
  File "~/.local/lib/python3.6/site-packages/swagger_client/api/custom_speech_transcriptions_api.py", line 413, in get_transcriptions
    (data) = self.get_transcriptions_with_http_info(**kwargs)  # noqa: E501
  File "~/.local/lib/python3.6/site-packages/swagger_client/api/custom_speech_transcriptions_api.py", line 479, in get_transcriptions_with_http_info
    collection_formats=collection_formats)
  File "~/.local/lib/python3.6/site-packages/swagger_client/api_client.py", line 330, in call_api
    _preload_content, _request_timeout)
  File "~/.local/lib/python3.6/site-packages/swagger_client/api_client.py", line 161, in __call_api
    _request_timeout=_request_timeout)
  File "~/.local/lib/python3.6/site-packages/swagger_client/api_client.py", line 351, in request
    headers=headers)
  File "~/.local/lib/python3.6/site-packages/swagger_client/rest.py", line 238, in GET
    query_params=query_params)
  File "~/.local/lib/python3.6/site-packages/swagger_client/rest.py", line 228, in request
    raise ApiException(http_resp=r)
swagger_client.rest.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Content-Length': '138', 'Content-Type': 'text/plain; charset=utf-8', 'Expires': '-1', 'Server': 'Microsoft-IIS/10.0', 'X-Powered-By': 'ASP.NET', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Set-Cookie': 'ARRAffinity=f3df9cf866b9a2d9e808ae21645f7fba0e58497b8931a9d16f3158c1e55c39cb;Path=/;HttpOnly;Domain=westus.cris.ai', 'Date': 'Thu, 29 Aug 2019 18:46:22 GMT'})
HTTP response body: {"code":"UnexpectedError","message":"Could not complete request, because an unhandled exception was thrown at 08/29/2019 18:46:22 +00:00"}_

Below is the relevant piece of code:

`_configuration = cris_client.Configuration()
configuration.api_key['Ocp-Apim-Subscription-Key'] = SUBSCRIPTION_KEY
client = cris_client.ApiClient(configuration)
transcription_api = cris_client.CustomSpeechTranscriptionsApi(api_client=client)
transcriptions: List[cris_client.Transcription] = transcription_api.get_transcriptions()_`

I am not sure what changed. I didn't change anything from my end. Can someone help me resolve this?

Thanks
Sudha

**Comment by bexxx** [comment]
Hi Sudha, 

this is a server side issue that was analyzed and we're going to deploy a fix in the next days.

The underlying issue is the number of transcriptions you have under your subscription. 

A viable workaround to unblock you is to use pagination and add url parameters ?skip=0&take=1000 and increase the value for skip in subsequent calls.

Hope it unblocks you,
Ralf

**Comment by raosudha89** [comment]
Hi Ralf,

Thank you for your response. Can you elaborate on your workaround suggestion? Where exactly in the code should I add the url parameters? 

Also, is there a way I can increase the number of transcriptions under my subscription to allow for more calls? I ask this because we are currently doing a large scale transcription where we plan to call the service on around 500K audio files. 

Thanks
Sudha

**Comment by chlandsi** [comment]
@raosudha89 For the Python client, you can pass these parameters to the `transcription_api.get_transcriptions()` method ([here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/e095701571e5c122fab6ec222da0cba16bcc3628/samples/batch/python/python-client/main.py#L48) in the sample), like so:

```
transcriptions = []
transcriptions.extend(transcription_api.get_transcriptions(skip=0, take=100)
transcriptions.extend(transcription_api.get_transcriptions(skip=100, take=100)
# etc.
```

**Comment by raosudha89** [comment]
I tried passing these parameters but when I do that, the script just keeps waiting with repeatedly printing the following message:
Transcriptions status: completed (this transcription): False, 0 running, 0 not started yet
Transcriptions status: completed (this transcription): False, 0 running, 0 not started yet
Transcriptions status: completed (this transcription): False, 0 running, 0 not started yet
....

I think the problem is I don't understand what the parameters 'skip' and 'take' are supposed to be doing here. Can you please elaborate or give me some references?

Thanks
Sudha

**Comment by raosudha89** [comment]
Thank you for your detailed explanation. The solution you suggested worked for me and I am able to use the batch transcription service now. Thanks again!

**Comment by choudhary-dinesh** [comment]
Hi @chlands, 
I am also facing same issues in batch transcription as mentioned above, And I tried the solution you suggested here but its not helping. In my case i am not even able to get the transcription identified by the transcription ID.  Earlier all this was working fine.
Can you help me here.
Thanks
Dinesh.

**Comment by chlandsi** [comment]
Hi @choudhary-dinesh, we'll need some more information to diagnose this. Please describe the error you are seeing in more detail - what is the exact error message? Can you also post a transcription id, the region of the speech service you are using, and the approximate time when you created that transcription? Thanks!

**Comment by choudhary-dinesh** [comment]
hi @chlandsi 
When I checked today,  i am not getting error(mentioned above) . I am able to use batch transcription service.
Also able to get transcription by ID.
Regards
Dinesh
