### ISSUE TITLE
Intent Recognition sample app is invalid

### ISSUE THREAD

**Issue by thegoldenmule** [Azure-Samples/cognitive-services-speech-sdk#369]
**Describe the bug**
When attempting to run SCENE 2 from the https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/unity/speechrecognizer guide, the json model provided is invalid. When you attempt to import the json file (`LUIS-App-Export-Unity-FunWithShapes.json`) you get the error:

`BadArgument: Character indicies 17,20 do not correspond to the start and end of a token.`

**To Reproduce**
1. In LUIS, click on *My apps* > *Import new app*.
2. Select LUIS-App-Export-Unity-FunWithShapes.json.

**Expected behavior**
The app should be created successfully.

**Version of the Cognitive Services Speech SDK**
N/A.

**Platform, Operating System, and Programming Language**
Chrome.

**Additional context**
The json file is valid JSON, but the website gives the error: `BadArgument: Character indicies 17,20 do not correspond to the start and end of a token.`.

**Comment by jhakulin** [comment]
Thanks for the feedback, we will investigate, @ActiveNick FYI

**Comment by LessThan12Parsecs** [comment]
Did this ever got resolved?

**Comment by thegoldenmule** [comment]
@LessThan12Parsecs I just tried it again-- same error.

**Comment by LessThan12Parsecs** [comment]
Yeah, that's a pity, I tried exporting a random app from LUIS to see if there was some field missing but wasn't able to find any changes to make it work.

**Comment by amitkumarshukla** [comment]
@thegoldenmule We are very sorry that it didn't work yet. We figured out that the json file is currently not compatible with the latest LUIS schema as they have done some modification. We have fixed the issue. 

Please use the attached json file. We will publish this in the official release once we do the next release. I am closing the issue for the time being. If you face any issue, please let us know .

[LUIS-App-Export-Unity-FunWithShapes.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4194943/LUIS-App-Export-Unity-FunWithShapes.zip)

**Comment by reptilebeats** [comment]
should update it now, almost gave up before finding this

**Comment by chrisbasoglu** [comment]
The official release is out tomorrow: 3/2/2020.

**Comment by reptilebeats** [comment]
haha figures
