### ISSUE TITLE
Why does translation-wpf sample get 3 results?

### ISSUE THREAD

**Issue by tatsuya-takahashi** [Azure-Samples/cognitive-services-speech-sdk#37]
When I use below sample, I got 3 translated results.
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/csharp/uwp/speechtotext-uwp

and voice says "hello slash hello slash hello...".
I expected only 1 results.

![image](https://user-images.githubusercontent.com/34804215/44625276-74f4c700-a940-11e8-83f9-9bdb2a60facf.png)

**Comment by wolfma61** [comment]
There are final results and partial results shown in the notification area. You can change the code to only show final results, if you desire so ...
