### ISSUE TITLE
Unity sample does not properly dispose

### ISSUE THREAD

**Issue by thegoldenmule** [Azure-Samples/cognitive-services-speech-sdk#370]
**Describe the bug**
After you run the unity intent recognition sample scene, stop the scene. When you try to start the scene again or close Unity, the application hangs indefinitely. It appears something is not cleaned up properly and a task is still running.

**To Reproduce**
1. Run the intent recognition sample.
2. Stop the intent recognition sample.
3. Run the intent recognition sample again, or try to close unity.

**Expected behavior**
The sample runs again or Unity is closed.

**Version of the Cognitive Services Speech SDK**
Commit 68e88f0856704eac879108bac1ab4a310cc787a4, SDK 1.6.0.

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware: x64
 - Programming language: C# (Unity)
- Unity version 2019.2.0.

**Comment by jhakulin** [comment]
Thanks for the feedback, does this happen only in Editor ?

With Unity Editor it is possible to get hang happening if script gets stopped before all async operations are finished. We will take a look, FYI @ActiveNick

**Comment by thegoldenmule** [comment]
This is editor only. On device (HoloLens 1 + 2), there isn't really a corollary of killing stopping play mode and restarting. Killing the application works, but that works in the editor as well.
