### ISSUE TITLE
Program startup throws an exception

### ISSUE THREAD

**Issue by JackZhangCN** [Azure-Samples/cognitive-services-speech-sdk#373]
I wrote a program that calls the SpeechRecognizer interface，and set it to autostart by systemd.
But in most cases the software will work fine, but sometimes an exception will be thrown when executing the `auto kwrecognizer = SpeechRecognizer::FromConfig(kwconfig); `code.

Output the SDK‘s log information to a file and find `SPX_THROW_ON_FAIL: ::recognizer_create_speech_recognizer_from_config( &hreco, HandleOrInvalid<SPXAUDIOCONFIGHANDLE,SpeechConfig>(speechconfig), HandleOrInvalid<SPXAUDIOCONFIGHANDLE, Audio::AudioConfig>(audioInput)) = 0x7ffd5fbed588`.

Reproduction rate： 1/10
I doubt if it is because the program started too early.

**To Reproduce**
1. Create a program and set it autostart when computer boot.
2. Check if the program exit.

**Expected behavior**
Program can work fine.

**Version of the Cognitive Services Speech SDK**
Speech SDK 1.6.0

**Platform, Operating System, and Programming Language**
 - OS: Linux（Ubuntu16.04）
 - Hardware - x64
 - Programming language:  C++

**Comment by wolfma61** [comment]
I assume it works 10 out of 10 times if you don't start it during autostart or computer boot?
If so, it probable is because the program started to early?

you could try to enable logging:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

**Comment by JackZhangCN** [comment]
@wolfma61 
I have enabled the logging function, but when the exception thrown, the log file didn't created. I'm sure that the exception was occured while creating a recognizer. I can't comfirm whether the program will work will if I don't start it during autostart or computer boot.

**Comment by JackZhangCN** [comment]
I have tested the program again. If I start the program during computer boot, and add 5s delay before the program call to SDK, the unusual phenomenon will occurred every time. But if I add 15s delay, the unusual phenomenon will disappear.  The length of the delay may vary depending on the environment.So if you want to reproduce this problem, I suggest you use Ubuntu 16.04 LTS, start the program by systemd and add delay before call to the SDK.

**Comment by JackZhangCN** [comment]
@amitkumarshukla 
I output the error information to a file, the details are as follows:

> SPX_THROW_ON_FAIL: ::recognizer_create_speech_recognizer_from_config( &hreco, HandleOrInvalid<SPXAUDIOCONFIGHANDLE,SpeechConfig>(speechconfig), HandleOrInvalid<SPXAUDIOCONFIGHANDLE, Audio::AudioConfig>(audioInput)) = 0x14f1470
> Exception with an error code: 0xe (SPXERR_MIC_NOT_AVAILABLE)
> [CALL STACK BEGIN]
> 
> /usr/lib/libMicrosoft.CognitiveServices.Speech.core.so(+0x115938) [0x7fb488dae938]
> /usr/lib/libMicrosoft.CognitiveServices.Speech.core.so(+0x1cf446) [0x7fb488e68446]
> /usr/lib/libMicrosoft.CognitiveServices.Speech.core.so(+0x132e6d) [0x7fb488dcbe6d]
> /usr/lib/libMicrosoft.CognitiveServices.Speech.core.so(+0x19a0fe) [0x7fb488e330fe]
> /usr/lib/libMicrosoft.CognitiveServices.Speech.core.so(+0x1ca454) [0x7fb488e63454]
> /usr/lib/libMicrosoft.CognitiveServices.Speech.core.so(+0x132e6d) [0x7fb488dcbe6d]
> /usr/lib/libMicrosoft.CognitiveServices.Speech.core.so(+0x19a0fe) [0x7fb488e330fe]
> /usr/lib/libMicrosoft.CognitiveServices.Speech.core.so(+0x18e2e3) [0x7fb488e272e3]
> /usr/lib/libMicrosoft.CognitiveServices.Speech.core.so(+0x12fda7) [0x7fb488dc8da7]
> /usr/lib/libMicrosoft.CognitiveServices.Speech.core.so(+0x130ce6) [0x7fb488dc9ce6]
> /usr/lib/libMicrosoft.CognitiveServices.Speech.core.so(+0x131476) [0x7fb488dca476]
> /usr/lib/libMicrosoft.CognitiveServices.Speech.core.so(+0xdbc69) [0x7fb488d74c69]
> /usr/lib/libMicrosoft.CognitiveServices.Speech.core.so(recognizer_create_speech_recognizer_from_config+0xc0) [0x7fb488d6f890]
> /home/root/speechRecoTask() [0x415d28]
> /home/root/speechRecoTask() [0x4088f7]
> /home/root/speechRecoTask() [0x40907d]
> /home/root/speechRecoTask() [0x4076ff]
> /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fb487e54830]
> /home/root/speechRecoTask() [0x407e49]
> [CALL STACK END]
Obviously, this is because of the mic's problem.
Now, I catch the exception and the problem has never happened again.

**Comment by lisaweixu** [comment]
@JackZhangCN Thank for your feedback. 

I am planning to investigate your problem in a couple of days since I have to focus on another task.   Sorry that I can start working on it right now.

Do you mind share your client code here or email it to me?

**Comment by JackZhangCN** [comment]
@lisaweixu I just used the example code on github and add log in SDK's header file.

**Comment by jhakulin** [comment]
Closing as functionality is expected if microphone is not ready yet in the boot
