### ISSUE TITLE
How to Speech to a Stream, that can be saved to a File

### ISSUE THREAD

**Issue by TonyHenrique** [Azure-Samples/cognitive-services-speech-sdk#377]
Is there a simple sample of how to make the Speech be downloaded/saved on a MP3 on a System.IO.File.Stream?

**Comment by TonyHenrique** [comment]
I found it:
```
var fileName = "outputaudio.wav";
using (var fileOutput = AudioConfig.FromWavFileOutput(fileName))
{
// Code here...
}
```
From https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_synthesis_samples.cs#L177

**Comment by yulin-li** [comment]
Yes, exactly you can use the `FromWavFileOutput` method to save synthesized audio to a file.
Alternatively, you can also use the [SaveToWaveFileAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.audiodatastream.savetowavefileasync?view=azure-dotnet#Microsoft_CognitiveServices_Speech_AudioDataStream_SaveToWaveFileAsync_System_String_) method of `AudioDataStream`.
