### ISSUE TITLE
C++ sample app crash on Linux/Ubuntu

### ISSUE THREAD

**Issue by formater** [Azure-Samples/cognitive-services-speech-sdk#38]
Hi,
 I compiled the SpeechSDK/quickstart/cpp-linux sample under Ubuntu, but when starting, I get the following error:

root@JOE-LAPTOP:/home/formater/SpeechSDK/quickstart/cpp-linux# ./helloworld
Say something...
(642): 51ms SPX_THROW_HR_IF: (0x015) = 0x15
(64): 55ms SPX_RETURN_ON_FAIL: hr = 0x580018b0
(64): 56ms SPX_REPORT_ON_FAIL: hr = Recognizer_RecognizeAsync_WaitFor(hasync, (4294967295U), phresult) = 0x580018b0
(64): 57ms SPX_RETURN_ON_FAIL: hr = 0x580018b0
(529): 58ms
SPX_TRACE_VERBOSE: [CALL STACK]

 [0x7fe465523b08]                                                     +0x63b08
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92d3a) [0x7fe4651c2d3a]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92d95) [0x7fe4651c2d95]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92d2e) [0x7fe4651c2d2e]
 [0x7fe466025922]                                                     +0x25922
 [0x7fe46601ebe9]                                                     +0x1ebe9
 [0x7fe46600f669]                                                     +0xf669
 [0x7fe46600f968]                                                     +0xf968
 [0x7fe464b31b97]   __libc_start_main                                 +0xe7
 [0x7fe46600f22a]                                                     +0xf22a

I thought, maybe there is problem with microphone access, so I changed to CreateSpeechRecognizerWithFileInput, but I got the same error during execution.

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
Ubuntu
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by fjferdiez** [comment]
I also experienced a similar error testing on a windows environment! In the .NetCore Sample, at debugging mode, there's an unknown exception

**Comment by formater** [comment]
Since then, I tested on Debian Linux, latest version, exactly same crash :(

**Comment by mahilleb-msft** [comment]
@formater - which Ubuntu version are you using?
Please note at this stage we're only supporting Ubuntu 16.04, https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk#linux.

**Comment by formater** [comment]
Ubuntu 18.04. So I will install ubuntu 16.04, and repeat my test.

**Comment by formater** [comment]
Thanks. Installed 16.04, no crash, it works as expected.
