### ISSUE TITLE
AudioConfig.fromDefaultMicrophoneInput not working ios12

### ISSUE THREAD

**Issue by yaki4** [Azure-Samples/cognitive-services-speech-sdk#384]
**Describe the bug**
The function AudioConfig.fromDefaultMicrophoneInput works perfectly on macos but not on ios. 
There is no error but i never got any feedback when i'm talking.
I try to use AudioConfig.fromMicrophoneInput with a deviceid but ios just doesn't give any deviceid. And even with 'default' or 'communication' as deviceid i got no feedback.

**To Reproduce**
Just do:
let audioConfig = AudioConfig.fromDefaultMicrophoneInput()
and launch your app in ios and you'll see no prompt asking for access.

**Expected behavior**
Prompt to access microphone of user.

**Version of the Cognitive Services Speech SDK**
1.6.0

**Platform, Operating System, and Programming Language**
 - OS: ios 12
 - Programming language:JavaScrip
 - Browser Safari

**Additional context**

**Comment by rhurey** [comment]
I've been unable to get a repro of this on my device, ann you provide some additional details here?

Specifically, in what context are you starting speech recognition? 

IIRC Safari requires recognition be started as part of a user action and not a callback or continuation.

**Comment by yaki4** [comment]
Sorry it's my fault. 
I assumed that it'll work the same way that other os deal with it.
Thank you very much for your response and all your work. 
It's a great library
