### ISSUE TITLE
Missing release notes for 1.7.0

### ISSUE THREAD

**Issue by daltskin** [Azure-Samples/cognitive-services-speech-sdk#385]
There are no release notes for 1.7.0 to understand the changes.

They are missing from here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/releasenotes

**Comment by BrianMouncer** [comment]
I'm getting the release notes through our docs build pipeline today, expect the release notes and all our azure docs to update later today or tomorrow.

**Comment by BrianMouncer** [comment]
@daltskin, I am working to fix some bad links I found at the last minute in the new TTS samples MD files.

Here is the snippet of the new release notes, while you wait for the docs update to go live.

# Release notes
## Speech SDK 1.7.0: 2019-September release

**New Features**
*   Added beta support for Xamarin on Universal Windows Platform (UWP), Android, and iOS
*   Added iOS support for Unity
*   Added Compressed input support for ALaw, Mulaw, FLAC on Android, iOS and Linux
*   Added SendMessageAsync in Connection class for sending a message to service
*   Added SetMessageProperty in Connection class for setting property of a message
*   Added "word boundery" information for TTS.

**Bug fixes**
*   Fixed IL2CPP build issue on Unity 2019 for Android
*   Fixed issue with malformed headers in wav file input being proccessed incorrectly
*   Fixed issue with UUIDs not being unique in some connection properties
*   Fixed a few warnings about nullability specifiers in the Swift bindings (might require small code changes)
*   Fixed a bug that caused websocket connections to be closed ungracefully under network load
*   iOS: dropped support for arm7s architecture
*   Fixed an issue on Android that sometimes results in duplicate impression IDs used by DialogServiceConnector
*   Improvements to the stability of connections across multi-turn interactions and the reporting of failures (via Canceled events) when they occur with DialogServiceConnector
*   DialogServiceConnector session starts will now properly provide events, including when calling ListenOnceAsync() during an active StartKeywordRecognitionAsync()
*   Addressed a crash associated with DialogServiceConnector activities being received 
*   TTS added bindings for Java, Python, Switft, and Objective-C
*   TTS added playback support for OSx, iOS, and Android.

**Samples**
*   Quickstart for Xamarin
*   Updated CPP Quickstart with Linux ARM64 information
*   Updated Unity quickstart with iOS information

**Comment by daltskin** [comment]
This is great - thanks you.

**Comment by jhakulin** [comment]
Release notes are out now publicly also, closing this one
