### ISSUE TITLE
Linux-ARM support (Raspberry Pi) for .net core

### ISSUE THREAD

**Issue by daltskin** [Azure-Samples/cognitive-services-speech-sdk#388]
Whilst SDK supports UWP on ARM atm, is .net core on Linux-ARM support on the roadmap?

**Comment by pankopon** [comment]
There is no definite schedule yet, but Linux-ARM32 is something we will be probably working on in the coming months. Linux-ARM64 (with .NET Core 3.0) has not been discussed yet.

**Comment by daltskin** [comment]
Thanks @pankopon.  How about .net core on Windows 10 IoT Core (ARM)?

**Comment by pankopon** [comment]
It is not on the roadmap at the moment, but I added a backlog item about this and we will consider it at some point.

**Comment by RohitMungi-MSFT** [comment]
#https://github.com/MicrosoftDocs/azure-docs/issues/52932

**Comment by efraimnewman** [comment]
> When targeting Linux ARM64, and using C# - the .NET Core 3.x (dotnet-sdk-3.x package) is required. If you're targeting ARM32 or ARM64, Python is not supported.

(from the docs [https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk?tabs=linux%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio#get-the-speech-sdk]( https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk?tabs=linux%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio#get-the-speech-sdk)
????

**Comment by efraimnewman** [comment]
also on the release notes page for 1.11 Linux: 

> Added support for .NET Core C# on Linux ARM32 and ARM64.
[https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/releasenotes](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/releasenotes)
