### ISSUE TITLE
.NET Core sample for speech synthesis (Text-To-Speech)

### ISSUE THREAD

**Issue by jjgriff93** [Azure-Samples/cognitive-services-speech-sdk#39]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
> A .NET Core sample of using the speech synthesis feature of the Speech API - it is currently a nightmare to try and use the documentation to figure this out, as it just includes an API reference with no explanation of the best way to then play the audio file returned by the service (no System.Media library in .NET Core so can't use the .NET Framework example from the Bing Speech documentation)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wolfma61** [comment]
Text-To-Speech is currently not supported directly by the Speech SDK. 
To use Text-To-Speech right now, you need to use the direct 'REST' calls.

Wolfgang

(we will add this functionality in the future, no ETA yet)
