### ISSUE TITLE
KWS platform support

### ISSUE THREAD

**Issue by daltskin** [Azure-Samples/cognitive-services-speech-sdk#392]
Is keyword spotting now supported on all the platforms with samples based here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/

From an earlier issue: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/250#issuecomment-523693427 and from testing this with the latest 1.7.0 packages - doesn't look like it's working..

Would be good if the documentation showed which platforms had this enabled.

**Comment by jhakulin** [comment]
Thanks for feedback, KWS is currently available officially only for Speech Devices SDK
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-devices-sdk#get-the-speech-devices-sdk

However we are working on currently to extend the support for official Nuget package (UWP, Xamarin) and Unity as well.

**Comment by daltskin** [comment]
Thanks @jhakulin for the guidance.  

It's just a bit confusing as some of the samples have it in place and it works already on some platforms eg: https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_recognition_samples.cs

**Comment by jhakulin** [comment]
Thanks for feedback, we are working on to release support officially later this year. I will close the ticket.
