### ISSUE TITLE
Example for long-running multi-utterance recognition

### ISSUE THREAD

**Issue by ivankeller** [Azure-Samples/cognitive-services-speech-sdk#394]
I am trying to adapt the quickstart example https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/python in order to transcribe a one minute recorded conversation. 

The [documentation](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.recognizer?view=azure-python#stop-continuous-recognition-async--) suggest to use `start_continuous_recognition_async()` which requires  "to connect to EventSignal to receive recognition results."

Would be really great to provide an example.

**Comment by rhurey** [comment]
There's one near the end of the Python sample file for wiring up the event handlers.

Starts here, the next 20 or so lines.
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/6805d96bf69d9e95c9137fe129bc5d81e35f6309/samples/python/console/speech_sample.py#L329

We're working on improving the sample / quickstart mix to try and cut down on some of the back and forth between the two.

**Comment by ivankeller** [comment]
Got it! Great! Thanks.
