### ISSUE TITLE
Did Unity Sdk suppport to get AudioData?

### ISSUE THREAD

**Issue by jackyhanyu** [Azure-Samples/cognitive-services-speech-sdk#395]
We are real projects, not simple demos. We need to save voice data and perform other analysis instead of simply speech recognition. 

The Unity engine is a real-time engine that saves voice data, sends it to speech service, and then recognizes it, does not meeting the real-time project requirements.

Can Unity sdk support returning voice data?

**Comment by jhakulin** [comment]
Thanks for the feedback, let me try to understand your need better.

1) If Unity developer is using microphone from Speech SDK, that cannot be returned back to the user currently.
2) if Unity developer uses Unity's microphone object and stream audio from it using either pull or push audio mode streams to get recognized result from the speech service, I believe it is possible also to save audio from Unity's microphone by app for some other processing.

So option 2 seems to be only way at the moment.

**Comment by kknsy** [comment]
If the voice recording oculus quest is called after voice recognition is turned on, it will crash，but unity editor no problem @jhakulin

**Comment by kknsy** [comment]
I think your sdk should open up the interface for uploading audio data. Now many people want to get this data, but now sdk returns the result directly, we can't get the audio data uploaded to the server.
I now use the method of recognizing and then manually turning on the microphone to record the audio, but now the above problem has appeared.
@jhakulin  Thank you

**Comment by jhakulin** [comment]
Thanks for the feedback, related to getting the audio data user sends to service, we do not have the support available at the moment, however we see there is increasing need for this feature and will add the feature in our backlog for the future releases.

Related to crash, let's continue discussion under this issue https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/400
