### ISSUE TITLE
Multi-utterance extension of speech_recognizer.recognize_once() API

### ISSUE THREAD

**Issue by larschristensen** [Azure-Samples/cognitive-services-speech-sdk#397]
I'm using the speech_recognizer.recognize_once() method for synchronous/blocking transcription of audio files. However, this method only does recognition of a single utterance, but the files I wish to transcribe can contain multiple utterances.

What is the recommended approach for synchronous/blocking multi-utterance transcription of audio files? Would it be possible to extend the speech_recognizer.recognize_once() API to also accept multi-utterance audio files?

**Comment by chlandsi** [comment]
Please have a look at the continuous recognition mode. There is a sample [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/6805d96bf69d9e95c9137fe129bc5d81e35f6309/samples/python/console/speech_sample.py#L196). This [comment](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/345#issuecomment-522446582) shows how to accumulate all results from continuous recognition.

**Comment by larschristensen** [comment]
> Please have a look at the continuous recognition mode. There is a sample [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/6805d96bf69d9e95c9137fe129bc5d81e35f6309/samples/python/console/speech_sample.py#L196). This [comment](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/345#issuecomment-522446582) shows how to accumulate all results from continuous recognition.

Thanks for the information, the sample code seems to work fine with multiple utterances. However in this continuous recognition mode, I can't seem to delete the audio file immediately after the recognition is complete. Is there something I have to do in order to close the audio file used for recognition?

**Comment by chlandsi** [comment]
You could try calling `del recognizer` after the recognition is finished (i.e., after you have received a session stopped event) to clean up the recognizer resources. Also have a look at the [Batch API](https://docs.microsoft.com/en-gb/azure/cognitive-services/speech-service/batch-transcription) ([sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python)), maybe it fits for your needs.

**Comment by larschristensen** [comment]
I have tried deleting both `speech_recognizer` and others after recognition is completed, but it doesn't make any difference. Could it be that the file access is somehow not correctly released in the SDK after use when using `speech_recognizer.start_continuous_recognition()`?

**Comment by chlandsi** [comment]
Hi @larschristensen, could you share the code that shows the problem you are having? Also, could you check the discussion in #352 to see whether it might be related? Thanks!

**Comment by larschristensen** [comment]
> Hi @larschristensen, could you share the code that shows the problem you are having? Also, could you check the discussion in #352 to see whether it might be related? Thanks!

@chlandsi Thanks for the input. The issue identified in #352 indeed seems to be the same as I'm having: If I do `del speech_recognizer._impl`, the clean-up correctly does its job and I can delete the audio file afterwards without problems. Maybe you should update the sample code and/or SDK to not have this problem?

**Comment by chlandsi** [comment]
@larschristensen Good to know that this is the underlying issue. You should then also be able to solve the problem by calling `recognizer.canceled.disconnect_all()` (etc. for the other signals) after recognition has finished, or moving the call to `stop_continuous_recognition` out of the callback. We do indeed have work items in the backlog to make this easier and clearer, but no ETA yet.

I'll proceed to close the issue, please reopen if you continue to have problems. Thanks!
