### ISSUE TITLE
how Microsoft mentioned that Both the Microsoft speech recognition SDK and the REST API support the following languages (locales),while it doesn't !!!

### ISSUE THREAD

**Issue by justinDevel** [Azure-Samples/cognitive-services-speech-sdk#398]
I've tried the samples provided in Microsoft speachsdk ,it's detecting  English Speech but no arabic recognition while they mentioned that arabic is supported!! , I tried This method from Microsoft in order to get the language and it returns en-US 
public String getSpeechRecognitionLanguage(), 
My Question does it support Arabic Speech Recognition or Not ,if it Yes how to  implement that Using SpeachSDK ,I mean some code to set the recognition language like reco.setlanguage ar-SA Etc?

Thanks For your time

**Comment by justinDevel** [comment]
no one Responded !!!!!

**Comment by zhouwangzw** [comment]
Sorry for the late response!
Currently, for speech-to-text (speech recognition), the speech service only supports "ar-EG", but not "ar-SA" yet. Please see [the link](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support#speech-to-text) for all supported languages. 

btw. ar-SA is supported though for Text-To-Speech, i.e. Speech Synthesis using standard voices. This might led to your confusion.

Sorry for the inconvenience.

Thanks,
Zhou

**Comment by justinDevel** [comment]
hi @zhouwangzw  no its ok ,I answered my question after research ,What I mean with this question not the supported languages I meant that ,azure said that they support Arabic for ar-EG ,But my Problem ,they didn't mention on Documentation how to set the Recognition Language !! ,but I finded it Out after Struggling the answer is down Below ,

After research the answer is Yes you can ,but Azure just don't put that on their Documentation !! , how to do it just do the following

`private static final String SpeechRecognitionLanguage = "ar-EG";`
then Set the language to speech Configuration

```
// create config
        final SpeechConfig speechConfig;

   speechConfig = SpeechConfig.fromSubscription(SpeechSubscriptionKey,             SpeechRegion);
    //Set the  speechrecgnitionlanguage     


speechConfig.setSpeechRecognitionLanguage(SpeechRecognitionLanguage);
```

**Comment by lisaweixu** [comment]
Hello, @justinDevel,

I am passing your feedback to our documentation writer. We are refactoring the speech SDK documentation website to better serve our customers.

Sorry for you inconvenience and thanks a lot for your feedback.

**Comment by justinDevel** [comment]
Hi @lisaweixu ,
that would be nice from you :) ,thanks 

Thanks For your time
