### ISSUE TITLE
Transcription failed :The recordings URI contains invalid data while using Batch transcription and diarization

### ISSUE THREAD

**Issue by rsanimesh** [Azure-Samples/cognitive-services-speech-sdk#399]
Hi,

I am trying to use batch transcription service from azure in python.
When adding properties

PROPERTIES = {
    "AddWordLevelTimestamps" : "True",   
    "AddDiarization" :  "True"
  }

in my TranscriptionDefinition

cris_client.TranscriptionDefinition(
        recordings_url=RECORDINGS_BLOB_URI,
        locale=LOCALE,
        name=NAME,
        description=DESCRIPTION,
        properties = PROPERTIES  
    )

i am getting error:
Transcription failed :The recordings URI contains invalid data

If removing properties, the TranscriptionDefinition works fine, and gives result, without any error but not able to get diarization.

The code i am using is from github:

=============================================================
from typing import List
import logging
import sys
import requests
import time
from datetime import datetime, timedelta
import swagger_client as cris_client
from azure.storage.blob import (
BlockBlobService,
BlobPermissions
)

logging.basicConfig(stream=sys.stdout, level=logging.DEBUG, format="%(message)s")

# Your subscription key and region for the speech service
SUBSCRIPTION_KEY = ""
SERVICE_REGION = ""

NAME = "Simple transcription"
DESCRIPTION = "Simple transcription description"

LOCALE = "en-IN"

ACCOUNT_NAME = ""
ACCOUNT_KEY = ""
URI_PREFIX = "https://<account_name>.blob.core.windows.net/<container_name>"

block_blob_service = BlockBlobService(account_name=ACCOUNT_NAME, account_key=ACCOUNT_KEY)

container_name = ""
blob_name = "Test10_Priyanka_ch1.wav"
sas_url = block_blob_service.generate_blob_shared_access_signature(
container_name,
blob_name,
permission=BlobPermissions.READ,
expiry=datetime.utcnow() + timedelta(hours=1),
start=datetime.utcnow()
)
RECORDINGS_BLOB_URI = URI_PREFIX + '/' + blob_name + '?' + sas_url

PROPERTIES = {
    "AddWordLevelTimestamps" : "True",   
    "AddDiarization" :  "True"
  }

# Set subscription information when doing transcription with custom models
ADAPTED_ACOUSTIC_ID = None  # guid of a custom acoustic model
ADAPTED_LANGUAGE_ID = None  # guid of a custom language model

def transcribe():
    logging.info("Starting transcription client...")

    # configure API key authorization: subscription_key
    configuration = cris_client.Configuration()
    configuration.api_key['Ocp-Apim-Subscription-Key'] = SUBSCRIPTION_KEY
    configuration.host = "https://{}.cris.ai".format(SERVICE_REGION)

    # create the client object and authenticate
    client = cris_client.ApiClient(configuration)

    # create an instance of the transcription api class
    transcription_api = cris_client.CustomSpeechTranscriptionsApi(api_client=client)

    # get all transcriptions for the subscription
    transcriptions: List[cris_client.Transcription] = transcription_api.get_transcriptions()

    logging.info("Deleting all existing completed transcriptions.")

    # delete all pre-existing completed transcriptions
    # if transcriptions are still running or not started, they will not be deleted
    for transcription in transcriptions:
        try:
            transcription_api.delete_transcription(transcription.id)
        except ValueError:
            # ignore swagger error on empty response message body: https://github.com/swagger-api/swagger-core/issues/2446
            pass

    # Use base models for transcription. Comment this block if you are using a custom model.
    # Note: you can specify additional transcription properties by passing a
    # dictionary in the properties parameter. See
    # https://docs.microsoft.com/azure/cognitive-services/speech-service/batch-transcription
    # for supported parameters.
    transcription_definition = cris_client.TranscriptionDefinition(
        recordings_url=RECORDINGS_BLOB_URI,
        locale=LOCALE,
        name=NAME,
        description=DESCRIPTION,
        properties = PROPERTIES
    )

    data, status, headers = transcription_api.create_transcription_with_http_info(transcription_definition)

    # extract transcription location from the headers
    transcription_location: str = headers["location"]

    # get the transcription Id from the location URI
    created_transcription: str = transcription_location.split('/')[-1]

    logging.info("Created new transcription with id {}".format(created_transcription))

    logging.info("Checking status.")

    completed = False
    while not completed:
        running, not_started = 0, 0

        # get all transcriptions for the user
        transcriptions: List[cris_client.Transcription] = transcription_api.get_transcriptions()

        # for each transcription in the list we check the status
        for transcription in transcriptions:
            if transcription.status in ("Failed", "Succeeded"):
                # we check to see if it was the transcription we created from this client
                if created_transcription != transcription.id:
                    continue

                completed = True

                if transcription.status == "Succeeded":
                    results_uri = transcription.results_urls["channel_0"]
                    results = requests.get(results_uri)
                    logging.info("Transcription succeeded. Results: ")
                    logging.info(results.content.decode("utf-8"))
                else:
                    print(transcription)
                    logging.info("Transcription failed :{}.".format(transcription.status_message))
                    break
            elif transcription.status == "Running":
                running += 1
            elif transcription.status == "NotStarted":
                not_started += 1

        logging.info("Transcriptions status: "
                "completed (this transcription): {}, {} running, {} not started yet".format(
                    completed, running, not_started))

        # wait for 5 seconds
        time.sleep(5)

    input("Press any key...")

if __name__ == "__main__":
    transcribe()

==============================================================

Kindly suggest any solution

**Comment by chlandsi** [comment]
Hi, could you post the transcription id (which is printed to the console in the example code) of the request that failed? Also, can please try just with AddWordLevelTimestamps: true, and post the transcription id? And finally, would it be possible to share the problematic audio, or make sure that it is in the correct format using for example [shntool](https://linux.die.net/man/1/shntool) or Audacity? Thank you!

**Comment by rsanimesh** [comment]
We have checked our audio file, sorry can't share that.

Audio details:
length: 71 sec, format: wav, samplling rate: 44100 Hz
Mono channel, 32-bit float.

The code worked well when used just AddWordLevelTimestamps" : "True" 
(transcription id: Created new transcription with id 1748ab34-48be-4dc6-b726-4c2f146b3aa1)

But getting error while using below properties
PROPERTIES = {
"AddWordLevelTimestamps" : "True",
"AddDiarization" : "True" 
}

Error details:

'Transcription id': '95ec4b61-1856-4e04-bec8-05270b26c7ea'

Details: 

{'created_date_time': datetime.datetime(2019, 10, 15, 5, 19, 35, tzinfo=tzlocal()),
 'description': 'Simple transcription description',
 'id': '95ec4b61-1856-4e04-bec8-05270b26c7ea',
 'last_action_date_time': datetime.datetime(2019, 10, 15, 5, 19, 56, tzinfo=tzlocal()),
 'locale': 'en-IN',
 'models': [{'base_model': None,
             'created_date_time': datetime.datetime(2019, 6, 19, 10, 2, 11, tzinfo=tzlocal()),
             'datasets': [],
             'description': 'DIARIZATION_V0.0',
             'id': 'fe190b26-2c67-48df-810a-183eebc486f0',
             'last_action_date_time': datetime.datetime(2019, 6, 19, 13, 23, 12, tzinfo=tzlocal()),
             'locale': 'en-US',
             'model_kind': 'Diarization',
             'name': 'DIARIZATION_V0.0',
             'properties': {'Purpose': 'BatchTranscription,Diarization'},
             'status': 'Succeeded'},
            {'base_model': None,
             'created_date_time': datetime.datetime(2019, 2, 27, 11, 15, 4, tzinfo=tzlocal()),
             'datasets': [],
             'description': 'Unified',
             'id': '4064457c-2aa4-4a45-a353-ef3102a7d777',
             'last_action_date_time': datetime.datetime(2019, 2, 27, 11, 27, 28, tzinfo=tzlocal()),
             'locale': 'en-IN',
             'model_kind': 'AcousticAndLanguage',
             'name': 'v4.0 Unified',
             'properties': {'Purpose': 'OnlineTranscription,BatchTranscription,AcousticAdaptation,LanguageAdaptation'},
             'status': 'Succeeded'}],
 'name': 'Simple transcription',
 'properties': {'AddDiarization': 'True',
                'AddWordLevelTimestamps': 'True',
                'ProfanityFilterMode': 'Masked',
                'PunctuationMode': 'DictatedAndAutomatic'},
 'recordings_url': '',
 'report_file_url': None,
 'results_urls': {},
 'status': 'Failed',
 'status_message': 'The recordings URI contains invalid data.'}

**Comment by rsanimesh** [comment]
Hi Zhou, 

We are getting the same error even after converting audio to WAV | PCM | 16-bit | 16 kHz, mono.

Thanks,
Rahul

**Comment by eldakms** [comment]
Hi Rahul,

We need the input audio to reproduce this. Is it possible to anonymize the audio and send it to me directly to eldak at microsoft.com?
Thanks!

**Comment by rsanimesh** [comment]
Hi Eldak,

As asked I have sent you a mail containing the audio file.
The subject of the mail is Regarding Transcription failed: The recordings URI contains invalid data while using Batch transcription and diarization #399

Thanks,
Rahul

**Comment by rsanimesh** [comment]
Hi Eldar,

Could you please help on how you were able to extract the diarization from audio. As we tried from different regions like eastus.

**Comment by eldakms** [comment]
Hi Rahul,

I was not able to reproduce the issue on your input file. I was just using a sample in C#. Could you please share your python client directly with me (on my email)? Thanks!

**Comment by PeterOrneholm** [comment]
I know this is an old (and closed) issue, but I experienced the same issue and found a solution. I blogged about it here:
https://peter.orneholm.com/post/617527184031105024/solving-the-recordings-uri-contains-invalid

In my case it was related to that the audio file contained a video stream (for the jpg miniature), but that can be removed using ffmpeg.

**Comment by bhagerty** [comment]
I also encountered this old, closed issue and found a solution. In my case, the problem was that Google Drive does not work for blob storage. When I moved my file to a publicly accessible URL in Amazon S3, everything worked.

**Comment by humak** [comment]
Hello, experiencing the same issue. I am using batch transcription with data from my azure blob, I tried both one file BLOB sas uri and multi file CONTAINER sas uri, both of them giving me the 'Transcription failed: The recordings URI contains invalid data.' error. And this is strange because I used exact same files several times before and got the transcription succesfully. Any ideas on why I am getting this error now? 
Thanks.

**Comment by zhouwangzw** [comment]
@humak  you can find detailed error messages from report.json file, which you can retrieve when using GET files. If the error message there is not clear enough, please post the transcription id, region and approximate time, and we will investigate further.
