### ISSUE TITLE
The application closes with any message while trying to use the option 3 ("Speech recognition with file input").

### ISSUE THREAD

**Issue by lhgomes** [Azure-Samples/cognitive-services-speech-sdk#4]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Run application, select the option 3

### Any log messages given by the failure
>No. The application closes with any message or trace

### Expected/desired behavior
>Receive the text

### OS and Version?
> Windows 10 Pro

### Versions
> 1803

### Mention any other details that might be useful
> The audio file is attached here.
[20180531-134348_994114391_15361167-k_ENTMAY18-all.wav.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/2060834/20180531-134348_994114391_15361167-k_ENTMAY18-all.wav.zip)

**Comment by wolfma61** [comment]
we'll investigate ...

**Comment by zhouwangzw** [comment]
I tried to run the sample, which works as expected. Have you replaced "YourAudioFile.wav" with a proper audio file which should be 16-bit 16000KHz single channel PCM wav file.
```

            // Replace with your own audio file name.
            using (var recognizer = factory.CreateSpeechRecognizerWithFileInput(@"YourAudioFile.wav"))
```

Thanks,

**Comment by mahilleb-msft** [comment]
@lhgomes - closing this issue for now. If this issue persists for you (also using the latest Speech SDK bits), please re-open or open a new issue.

Thanks, Mark
