### ISSUE TITLE
Android speech result returns canceled recognized text: <>

### ISSUE THREAD

**Issue by hei9gag** [Azure-Samples/cognitive-services-speech-sdk#40]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Update the subscription key and region. Then press the start button

### Any log messages given by the failure
> N/A

### Expected/desired behavior
> Expect voice recognition work

### OS and Version?
> Android 7.0 API 24

### Versions
> 0.6

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wolfma61** [comment]
we can't reproduce this, this is our most standard test case on android devices.

in the result, is there any addition information in the error details?

**Comment by hei9gag** [comment]
Sorry, the problem is fixed. Thanks for the help
