### ISSUE TITLE
Oculus quest Speech Recognition problem（unity）

### ISSUE THREAD

**Issue by kknsy** [Azure-Samples/cognitive-services-speech-sdk#400]
who can tell me，If the voice recording oculus quest is called after voice recognition is turned on, it will crash，but unity editor no problem
![image](https://user-images.githubusercontent.com/26211860/66804497-272c8b00-ef55-11e9-84dd-f8d8c9bec5ae.png)
![image](https://user-images.githubusercontent.com/26211860/66804509-33184d00-ef55-11e9-8784-7374deef48fe.png)

**Comment by jhakulin** [comment]
@kknsy could we have short telco about your issue, I want to understand your issue better ? 
Please contact me at jhakulin@microsoft.com

**Comment by kknsy** [comment]
@jhakulin I have already left a message for you.

**Comment by jhakulin** [comment]
@kknsy, For Oculus, have you used the same settings as here ? https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/229#issuecomment-530156472

**Comment by jhakulin** [comment]
We have put this issue in our future backlog, we do not currently have ETA for solution unfortunately.
