### ISSUE TITLE
Error: "Only one acoustic and one language model can be specified"

### ISSUE THREAD

**Issue by BorislavZlatanov** [Azure-Samples/cognitive-services-speech-sdk#401]
**Describe the bug**
I am using the provided Python script for [the Batch Transcription API](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/). I am getting the error "Only one acoustic and one language model can be specified" when I run the script with a provided custom acoustic model and a custom language model.

**To Reproduce**
What I have done:
1. Created a custom acoustic model, uploaded audio+human transcription and trained the acoustic model on it.
2. Created a separate custom language model, uploaded a list of phrases and trained the language model on it.
3. Added the ID of the custom acoustic model and the ID of the custom language model in the corresponding places of the Python script.
4. When I run the script, I get the error: "Only one acoustic and one language model can be specified"

**Expected behavior**
I suspect I am not doing something right. I have followed [the documentation](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-custom-speech) and as best as I can understand, I am supposed to create two separate models (have two separate model IDs) - one custom language and one acoustic. And I am supposed to train the first one with phrases and the second one with audio+transcripts. But this workflow is giving me the mentioned error.

**Version of the Cognitive Services Speech SDK**
I am not using the SDK, I'm using the [the Batch Transcription API](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/).

**Platform, Operating System, and Programming Language**
 - OS: CentOS 8, running as a guest VM on Windows 10 through VirtualBox
 - Hardware - 64-bit
 - Programming language: Python
 - Browser: None, I'm running the Python script through command line

**Additional context**
Stack trace:

```

Starting transcription client...
Deleting all existing completed transcriptions.
Traceback (most recent call last):
  File "main.py", line 142, in <module>
    transcribe()
  File "main.py", line 82, in transcribe
    data, status, headers = transcription_api.create_transcription_with_http_info(transcription_definition)
  File "/usr/local/lib/python3.6/site-packages/swagger_client/api/custom_speech_transcriptions_api.py", line 127, in create_transcription_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/site-packages/swagger_client/api_client.py", line 330, in call_api
    _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/site-packages/swagger_client/api_client.py", line 161, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/site-packages/swagger_client/api_client.py", line 373, in request
    body=body)
  File "/usr/local/lib/python3.6/site-packages/swagger_client/rest.py", line 275, in POST
    body=body)
  File "/usr/local/lib/python3.6/site-packages/swagger_client/rest.py", line 228, in request
    raise ApiException(http_resp=r)
swagger_client.rest.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Content-Length': '96', 'Content-Type': 'text/plain; charset=utf-8', 'Expires': '-1', 'Server': 'Microsoft-IIS/10.0', 'api-supported-versions': '2.0, 2.1, 3.0-beta1', 'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '49', 'X-RateLimit-Reset': '2019-10-15T08:23:09Z', 'X-Powered-By': 'ASP.NET', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Date': 'Tue, 15 Oct 2019 08:23:03 GMT'})
HTTP response body: {"code":"InvalidPayload","message":"Only one acoustic and one language model can be specified."}

```

**Comment by chlandsi** [comment]
Hi @BorislavZlatanov, can you post a snippet of the code you are using to set the model ids for your custom models? Thanks!

**Comment by BorislavZlatanov** [comment]
@chlandsi Sure. I am using the provided [main.py](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/python/python-client/main.py) script.

Here is the place where I set the custom model IDs (around line 30):

```

# Set subscription information when doing transcription with custom models
ADAPTED_ACOUSTIC_ID = "d04934ad-40aa-4072-b7bd-eb66f08155d7"  # guid of a custom acoustic model
ADAPTED_LANGUAGE_ID = "bf83a84f-df4e-4a69-9705-f8f85dc3cc34"  # guid of a custom language model

```

And here is the place where the transcription definition is specified and the transcription call is made (after line 60) - I have commented out the base model section and uncommented the custom model:

```

    # Use base models for transcription. Comment this block if you are using a custom model.
    # Note: you can specify additional transcription properties by passing a
    # dictionary in the properties parameter. See
    # https://docs.microsoft.com/azure/cognitive-services/speech-service/batch-transcription
    # for supported parameters.
    #propertiesList = {'PunctuationMode' : 'Automatic', 'ProfanityFilterMode' : 'None', 'AddWordLevelTimestamps' : 'true', 'AddDiarization' : 'true', 'AddSentiment' : 'true'}
    #transcription_definition = cris_client.TranscriptionDefinition(
    #   name=NAME, description=DESCRIPTION, locale=LOCALE, recordings_url=RECORDINGS_BLOB_URI, properties=propertiesList
    #)

    # Uncomment this block to use custom models for transcription.
    # Model information (ADAPTED_ACOUSTIC_ID and ADAPTED_LANGUAGE_ID) must be set above.
    if ADAPTED_ACOUSTIC_ID is None or ADAPTED_LANGUAGE_ID is None:
        logging.info("Custom model ids must be set to when using custom models")
    transcription_definition = cris_client.TranscriptionDefinition(
        name=NAME, description=DESCRIPTION, locale=LOCALE, recordings_url=RECORDINGS_BLOB_URI,
        models=[cris_client.ModelIdentity(ADAPTED_ACOUSTIC_ID), cris_client.ModelIdentity(ADAPTED_LANGUAGE_ID)]
    )

    data, status, headers = transcription_api.create_transcription_with_http_info(transcription_definition)


```

Thanks for your help!

**Comment by chlandsi** [comment]
From our service logs, it looks like both the model ids you specified refer to adapted language models. Could you please double-check them? Thanks!

**Comment by BorislavZlatanov** [comment]
@chlandsi Maybe I am doing something wrong... I don't know how to make a model acoustic or language except by feeding it certain training data. From what I understand, it becomes an acoustic model if I train it on audio+transcript data, whereas it becomes a language model if I train it on phrases. Is that right or is there another way this is done?

Here are screenshots of both models from inside the Custom Speech Portal.

The model I've specified as acoustic model in the Python script:

![model1](https://user-images.githubusercontent.com/3427319/66845431-ab443a00-ef78-11e9-9672-c9d476f0f74a.jpg)


The model I've specified as language model in the Python script:

![model2](https://user-images.githubusercontent.com/3427319/66845464-b6976580-ef78-11e9-8869-4b700be419ec.jpg)

**Comment by chlandsi** [comment]
Hi @BorislavZlatanov, it turns out that this is an issue with the portal you are using. To train an acoustic model, currently you have to go through the "old" portal https://westus.cris.ai, or use the API directly. We'll notify the respective teams to clear this up and improve the documentation. We're sorry for your inconvenience using the service.

**Comment by BorislavZlatanov** [comment]
@chlandsi OK, I understand. Could you point me to how I can use the API directly for creating models, uploading data and training?

**Comment by chlandsi** [comment]
Probably it's easier if you retrain also the language model from the old portal, and choose the V3.3 base model for both model trainings. As I said, we are working on improving this experience.

**Comment by chlandsi** [comment]
As to your question about using the API directly, its documentation is [here](https://westus.cris.ai/swagger/ui/index).

**Comment by BorislavZlatanov** [comment]
@chlandsi Thanks for your help. Any estimate on when this will be fixed in speech.microsoft.com?

**Comment by ArcherAZ** [comment]
Thanks for reporting this Borislav :)
On new portal, we are trying to merge language model and acoustic model into a Single Model notion, which will come out in a month or two (once we have the new models and API ready). By today if you intend to train both AM + LM with separated IDs, please use directly through Swagger API. 
Sorry for the inconvenience.

**Comment by BorislavZlatanov** [comment]
Hi @ArcherAZ , is there any update on the deployment of the Single Model you mentioned?

**Comment by BeigeBadger** [comment]
I ran into this limitation today, any progress on the single model @ArcherAZ ?

**Comment by choudhary-dinesh** [comment]
Hi @ArcherAZ , facing same problem, any update on single model?

**Comment by bexxx** [comment]
The changes to the models api will be part of v3 of the API which will be released very soon. We still plan to make this happen in the next weeks.

**Comment by BeigeBadger** [comment]
@bexxx v3 of the API doesn't look to be live yet? Only v2 is available at [https://westus.cris.ai/swagger/ui/index](https://westus.cris.ai/swagger/ui/index).

**Comment by bexxx** [comment]
We are currently starting to roll out the code changes for v3 to production and once it's done and tested we will publish the swagger for it. Please wait for a couple of days more.

**Comment by wistreng** [comment]
To be sure, is the v3 API support using models from the web portal? Thanks @bexxx

**Comment by bexxx** [comment]
Models created on v2 and in the portal will be accessible from the v3 API.
The portal internally uses the v3 version already.

**Comment by jhakulin** [comment]
Closed as answered
