### ISSUE TITLE
Stop transcription task

### ISSUE THREAD

**Issue by jarneyRR** [Azure-Samples/cognitive-services-speech-sdk#402]
I'm using the api to transcribe audio >1hr long. Occasionally i make a mistake or decide I want to change some of the transcription parameters when the task is halfway complete. Is there anyway I can stop the running task (either on the command line or through my azure account) so that I do not have to wait around an hour for the current task to complete?

**Comment by chlandsi** [comment]
I assume you are referring to the [batch API](https://docs.microsoft.com/en-gb/azure/cognitive-services/speech-service/batch-transcription)? There is no way to stop a running task, but there is no need to wait for a task to complete before starting a new one, you can submit multiple tasks in parallel.

**Comment by jarneyRR** [comment]
Ah that's great thank you. 
I am indeed using the batch api, and i was testing it with the example script. I assume it's only the part that tries to delete the old results that fails, so getting rid of that should do it. 
Thanks for your help.

**Comment by chlandsi** [comment]
Good to hear this helped. The code in the beginning indeed just cleans up finished transcription jobs, it is not necessary to do this every time. I'll remove it from the sample, thanks for pointing this out.

I'm closing the issue for now, please feel free to reopen/open a new one if there are further problems.
