### ISSUE TITLE
Speech SDK jar not found

### ISSUE THREAD

**Issue by deepakgarg444** [Azure-Samples/cognitive-services-speech-sdk#404]
Hi team,
I am trying to use `Speech SDK` for `Speech to text` conversion on `macOS`.
So, i was checking this sample for Speech SDK, and from here i tried adding this dependency:

```
<repositories>
   <repository>
     <id>maven-cognitiveservices-speech</id>
     <name>Microsoft Cognitive Services Speech Maven Repository</name>
     <url>https://csspeechstorage.blob.core.windows.net/maven/</url>
   </repository>
 </repositories>
 <!-- </repositories> -->
 <!-- <dependencies> -->
 <dependencies>
   <dependency>
     <groupId>com.microsoft.cognitiveservices.speech</groupId>
     <artifactId>client-sdk</artifactId>
     <version>1.7.0</version>
   </dependency>
 </dependencies>
```

But it is giving me this error:
`Missing artifact com.microsoft.cognitiveservices.speech:client-sdk:jar:1.7.0`

Reference:
(https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-java-jre)
Here, it asks to add the above mentioned dependencies for macOS. But after adding those in my pom, it shows this error.

Can someone please help with this? Not sure if i am missing something here!

**Comment by jhakulin** [comment]
Thanks for the feedback,

If you use directly the quickstart sample here: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/java-jre, does that work ?

Verified here on MacOS that 1.7.0 release can be consumed correctly using that sample.

**Comment by jhakulin** [comment]
@deepakgarg444 did you find out the issue ? I am closing the case, let me know more details if you still see the issue.

**Comment by deepakgarg444** [comment]
Hi @jhakulin ,
Really sorry for the late reply. I just tried building the quickstart sample provided in the link above and i am still getting the same error while building the project.
I am attaching screenshots of the error in the `pom.xml`, if that helps.
<img width="693" alt="Screen Shot 2019-10-25 at 1 34 12 AM" src="https://user-images.githubusercontent.com/48828774/67521177-f9b7ae00-f6c7-11e9-90f8-fe5f1b063f37.png">
<img width="917" alt="Screen Shot 2019-10-25 at 1 34 26 AM" src="https://user-images.githubusercontent.com/48828774/67521180-fa504480-f6c7-11e9-8891-f865542e6690.png">

**Comment by deepakgarg444** [comment]
I am using `macOS Mojave, Version: 10.14.4 (18E226)`

**Comment by BrianMouncer** [comment]
Out of curiosity, if you switch back to client-sdk version 1.6.0, do you get the same error?

**Comment by deepakgarg444** [comment]
Hi @BrianMouncer ,
I tried using `client-sdk 1.6.0`, it says `Missing artifact client-sdk1.6.0`. Am i missing something here?

**Comment by raafaelima** [comment]
Hy @BrianMouncer, 

I'm trying to using the library in my Android project, and facing the same issue. Neither the AAR or the repository on maven are accessible or exists. Do you have any news about it? 
By the way, I'm using the zip of 1.6.0 and try to update to the new 1.8

**Comment by deepakgarg444** [comment]
Hi @raafaelima ,

Is 1.6.0 version working fine for you?

**Comment by rishugreat** [comment]
I am also facing same issue with all the versions: 1.6.0, 1.7.0, 1.8.0, 1.9.0
I am on Mac OS Mojave: 10.14.5. 

`Missing artifact com.microsoft.cognitiveservices.speech:client-sdk:jar:1.6.0`

**Comment by deepakgarg444** [comment]
@jhakulin Any updates on this?

**Comment by jhakulin** [comment]
@deepakgarg444 We have not been able to reproduce this issue, all releases have been tested to work with MacOS and speech SDK Java packages. We will retest this scenario again with the 1.10.0 release coming soon.

**Comment by jhakulin** [comment]
Closed as not reproduced
