### ISSUE TITLE
Batch transcription API Cognitive Services not supported

### ISSUE THREAD

**Issue by andrewginns** [Azure-Samples/cognitive-services-speech-sdk#406]
**Describe the bug**
I cannot run my batch transcription scripts on a newly created Cognitive Services resource. Using the base model and storing files in a storage account.

A previously created Cognitive Services resource is able to perform batch transcription with no problems. Both are configured in the same region and the same pricing plan S0.

**Steps to reproduce the behavior:**
1. Create a new Cognitive Services Resource
2. Store mp3 files in a blob storage resource
3. Use Python to run a transcription job through cris.ai

**Expected behavior**
Audio files from blob storage are transcribed

**Version of the Cognitive Services Speech SDK**
Using the REST endpoint through swagger-client

**Platform, Operating System, and Programming Language**
 - OS: Ubuntu Linux
 - Hardware: x64
 - Programming language: Python

**Additional context**

If I run the same code through my Cognitive Service resource created on the 7th of October 2019 it works as expected. I can see in the azure portal that the features in S0 pricing plan seem to have changed.

`Starting transcription client...
Deleting all existing completed transcriptions.
Traceback (most recent call last):
  File "azure_batch_transcribe.py", line 185, in <module>
    transcribe(blob.name, channel)
  File "azure_batch_transcribe.py", line 122, in transcribe
    data, status, headers = transcription_api.create_transcription_with_http_info(transcription_definition)
  File "/home/ubuntu/.venv/lib/python3.6/site-packages/swagger_client/api/custom_speech_transcriptions_api.py", line 127, in create_transcription_with_http_info
    collection_formats=collection_formats)
  File "/home/ubuntu/.venv/lib/python3.6/site-packages/swagger_client/api_client.py", line 330, in call_api
    _preload_content, _request_timeout)
  File "/home/ubuntu/.venv/lib/python3.6/site-packages/swagger_client/api_client.py", line 161, in __call_api
    _request_timeout=_request_timeout)
  File "/home/ubuntu/.venv/lib/python3.6/site-packages/swagger_client/api_client.py", line 373, in request
    body=body)
  File "/home/ubuntu/.venv/lib/python3.6/site-packages/swagger_client/rest.py", line 275, in POST
    body=body)
  File "/home/ubuntu/.venv/lib/python3.6/site-packages/swagger_client/rest.py", line 228, in request
    raise ApiException(http_resp=r)
swagger_client.rest.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Content-Length': '128', 'Content-Type': 'text/plain; charset=utf-8', 'Expires': '-1', 'Server': 'Microsoft-IIS/10.0', 'api-supported-versions': '2.0, 2.1, 3.0-beta1', 'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '48', 'X-RateLimit-Reset': '2019-10-17T11:05:43Z', 'X-Powered-By': 'ASP.NET', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Set-Cookie': 'ARRAffinity=3647c19a7a3981b48c692477c36543b2a9d277c03e3b2a27224fbc9739009fde;Path=/;HttpOnly;Domain=centralus.cris.ai', 'Date': 'Thu, 17 Oct 2019 11:05:38 GMT'})
HTTP response body: {"code":"InvalidProductId","message":"The subscription SKU \"CognitiveServices.S0\" is not supported in this service instance."}`

**Comment by andrewginns** [comment]
Provisioning the 'Speech' S0 resource instead of the base 'Cognitive Services' S0 resource fixed this error.

**Comment by florianbepunkt** [comment]
Could you please elaborate a bit on your solution? What do you mean by provisioning the Speech S0 resource? Thanks

**Comment by chrisbasoglu** [comment]
He means, that from the Azure Portal, when creating a new resource, one should choose the "Speech" resource and not the one called "Cognitive Service".  This can be confusing at first, because Speech is a type of Cognitive service.  S0 refers to the paid version.  See screen shot below (chose the black and not the red).  

![image](https://user-images.githubusercontent.com/16262519/68081783-a1bc2e00-fdd0-11e9-92d2-ad981a8fd440.png)

**Comment by andrewginns** [comment]
Yep @florianbepunkt what @chrisbasoglu said. I believe they changed how Cognitive services speech was provisioned and moved it to a seperate service entirely. From there you can select the S0 tier.

**Comment by riedwaanb** [comment]
Does this new way of deploying speech support az cli commands? Previously I would deploy with: az cognitiveservices account create --name myservicenamexyz --sku S0 --kind SpeechServices --location $location --resource-group myresourcegroupnamexyz

**Comment by yasar83** [comment]
Schicken Sie mir gottverdammter keine E-Mails
Mehr
Ich habe Schnauze voll von eure ständigen E-Mails wenn ich weitere E-Mails von euch bekomme von Azure dann werde ich eine Anzeige erstatten

Mit freundliche Grüße

Am 21.12.2020 um 13:34 schrieb Riedwaan Bassadien <notifications@github.com>:

﻿

Does this new way of deploying speech support az cli commands? Previously I would deploy with: az cognitiveservices account create --name myservicenamexyz --sku S0 --kind SpeechServices --location $location --resource-group myresourcegroupnamexyz
