### ISSUE TITLE
Program crashes when network connection error occurs

### ISSUE THREAD

**Issue by JackZhangCN** [Azure-Samples/cognitive-services-speech-sdk#407]
**Describe the bug**
The log is as follows:
```
SpeechRecognitionWithMicrophone CANCELED(result): ErrorCode = 5
SpeechRecognitionWithMicrophone CANCELED(result): ErrorDetails = Connection failed (no connection to the remote host). Internal error: 1. Error details: 2485. Please check network connection, firewall setting, and the region name used to create speech factory. SessionId: df7360e0e69d4b4db7755294c587d727
```
I don't know what "Error details:2485" means.
I want to know if there is a problem with my network configuration.

**Expected behavior**
A Error returned without crash.

**Version of the Cognitive Services Speech SDK**
SpeechSDK-Linux-1.7.0

**Platform, Operating System, and Programming Language**
 - OS: Ubuntu16.0.4
 - Hardware - x64
 - Programming language:  C++

**Comment by pankopon** [comment]
Hi, please upload the full SDK log and we will have a look. See https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging for instructions for how to enable logging.

**Comment by JackZhangCN** [comment]
Log file ：[speechReco.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/3748928/speechReco.log)

**Comment by pankopon** [comment]
Thank you for the log. It seems that there is an error while trying to download a Certificate Revocation List, thus SSL handshake fails. Are you able to access file http://mscrl.microsoft.com/pki/mscorp/crl/Microsoft%20IT%20TLS%20CA%204.crl manually e.g. in browser, just to check that the address is not somehow blocked?

(915): 153579ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:1001 Error loading CRL from http://mscrl.microsoft.com/pki/mscorp/crl/Microsoft%20IT%20TLS%20CA%204.crl
(915): 153579ms SPX_TRACE_ERROR:  trace_message.cpp:189 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:load_cert_crl_http Line:1001 
(915): 153579ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:1612 Unable to retrieve CRL, CRL check will fail.
(915): 153579ms SPX_TRACE_ERROR:  trace_message.cpp:189 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:crls_http_cb Line:1612 
(915): 153579ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:681 SSL handshake failed: 5
(915): 153579ms SPX_TRACE_ERROR:  trace_message.cpp:189 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:681 
(915): 153579ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:2376 FORCE-Closing tlsio instance.
(915): 153579ms SPX_TRACE_ERROR:  trace_message.cpp:189 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_close Line:2376 
(915): 153580ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  transport.cpp:364 WS open operation failed with result=1(WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED), code=2485[0x000009b5]
(915): 153580ms SPX_TRACE_ERROR:  trace_message.cpp:189 Error: File:/home/vsts/work/1/s/source/core/usp/transport.cpp Func:OnWSOpened Line:364 
(915): 153580ms SPX_TRACE_INFO: AZ_LOG_INFO:  uspimpl.cpp:809 TS:129953, TransportError: connection:0xb40eb0a0, reason=2, code=1 [0x00000001], string=2485

**Comment by JackZhangCN** [comment]
I have tried to access the  URL by browser,but the file couldn't be downloaded. After changing a wifi connection, I reaccessed this URL successfully. And the program didn't crash.
But, I think if my program couldn't download the CRL file, the program should throw a exception instead of exiting.

**Comment by JackZhangCN** [comment]
I have tried to access the URL by browser,but the file couldn't be downloaded. After changing a wifi connection, I reaccessed this URL successfully. And the program didn't crash.
But, I think if my program couldn't download the CRL file, the program should throw a exception or return error code instead of exiting.

**Comment by pankopon** [comment]
Closed the issue as resolved. Please note that upon a failure at trying to open a connection, the SDK returns a result with ResultReason::Canceled (+ details), which the client application can handle gracefully.
