### ISSUE TITLE
Programmatically retrieve region

### ISSUE THREAD

**Issue by zSeriesGuy** [Azure-Samples/cognitive-services-speech-sdk#408]
I am very new to Azure and can't figure out how to do this.

In the python SDK, the SpeechConfig requires a service key and a service region.
I am wondering how to programmatically retrieve the service region associated with the service key. Can this be accomplished using the tenant ID and/or subscription ID associated with the Azure resource?
Is there any example code to do this?
Thank you.

**Comment by chrisbasoglu** [comment]
with the Azure Command Line interface (Azure CLI), once you login (az login) you can do: az cognitiveservices account show --verbose -g <nameThatYouGaveForTheResourceGroupName>-n <nameThatYouGaveForYourCognitiveServiceResource> --subscription <id of the azure subscription with which you created your keys> --output json

In the resulting json, liike for the "location" field.  You are not limited only to cli.  You there is a rest API as well.

https://docs.microsoft.com/en-us/rest/api/cognitiveservices/accountmanagement/accounts/getproperties
https://docs.microsoft.com/en-us/rest/api/azure/#acquire-an-access-token

**Comment by zSeriesGuy** [comment]
Thank you.
I got it working using
        creds = ServicePrincipalCredentials(client_id=application_id, secret=application_secret, tenant=tenant_id)

        resource_client = ResourceManagementClient(credentials=creds, subscription_id=subscription_id)

        for item in resource_client.resources.list(subscription_id=subscription_id):
