### ISSUE TITLE
Install on Raspberry Pi 3

### ISSUE THREAD

**Issue by zSeriesGuy** [Azure-Samples/cognitive-services-speech-sdk#409]
I'm trying to pip install azure-cognitiveservices-speech on a Raspberry PI 3 running Ubuntu 18.04.
Python 3.6.8. 
I have confirmed 64-bit version of python running.

Getting 

> ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech (from versions: none)
ERROR: No matching distribution found for azure-cognitiveservices-speech

Any solution?

**Comment by pankopon** [comment]
Hi, unfortunately the SDK does not have support for Python on Linux ARM (either 32 or 64-bit) yet. This is something we will consider for future releases, though there is no definite schedule yet. Please refer to the matrix at https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/ for the current status.

**Comment by zSeriesGuy** [comment]
Thank you.
