### ISSUE TITLE
All samples error out with WebSocket Upgrade failed with an authentication error (403)

### ISSUE THREAD

**Issue by riverar** [Azure-Samples/cognitive-services-speech-sdk#41]
Deploying a Custom Speech resource on Azure results in failures; is Cognitive Services completely unavailable?

**Comment by zhouwangzw** [comment]
Hello, 

Did the failures happen during training or during recognition? Any more detailed information on failures? The Speech service is available. 

Thanks,

**Comment by mahilleb-msft** [comment]
@riverar - I had no problem generating a "Speech (preview)" or "Custom Speech (preview)" Cognitive Services resource in Azure just now. Can you share repro steps / parameters (region, pricing tier)?
[Note that for starting on the samples, "Speech (preview)", or even the 30-day trial should be sufficient to get going].

**Comment by riverar** [comment]
I tested with `cognitive-services-speech-sdk\samples\csharp\dotnetcore\console` and hitting the api.cognitive.microsoft.com endpoint with curl.

```curl -v -X POST "https://api.cognitive.microsoft.com/sts/v1.0/issueToken" -H "Content-type: application/x-www-form-urlencoded" -H "Content-Length: 0" -H "Ocp-Apim-Subscription-Key: [key1]"```

```{ "statusCode": 401, "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." }* Connection #0 to host api.cognitive.microsoft.com left intact```

I filed an Azure support ticket last night, looks like they make some tweaks but the samples are still non-functional.

![image](https://user-images.githubusercontent.com/475132/44997716-3d4fd580-af65-11e8-9348-5cbbc97218bb.png)

**Comment by mahilleb-msft** [comment]
Hi @riverar,

  for a "Speech service (preview)" subscription key, you should hit endpoints that include a region. See here, for example: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-apis#authentication for the token endpoint. The region depends where you've created the region.
[Note: this was different in the old speech service, documented at https://docs.microsoft.com/en-us/azure/cognitive-services/Speech/Home].

Now that would explain why the `curl` command is failling, if you're using a "new" key, but it doesn't explain why the sample is not running, if you've updated all key and region in there.

Can you confirm the type of subscription and region that you're using?

Sorry for the confusion, Mark

**Comment by riverar** [comment]
@mahilleb-msft Thanks Mark. curl works, so that's a good sign. Samples still spitting out authentication errors.

```
Recognition status: Canceled
There was an error, reason: WebSocket Upgrade failed with an authentication error (403). Please check the subscription key or the authorization token, and the region name.
```

Is there tracing I can turn on somewhere? Doesn't seem to get captured via Fiddler.

**Comment by riverar** [comment]
@mahilleb-msft @zhouwangzw Any thoughts on this? Am very eager to start pumping audio through this service 24/7!

**Comment by mahilleb-msft** [comment]
Just to confirm the situation --
* You've created "Speech service (preview)" subscription in Azure, free tier (F0) in the region westus.
   (cf. https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started#create-a-speech-resource-in-azure)
* Using the subscription key, you can obtain an authentication token with curl going against `https://westus.api.cognitive.microsoft.com/sts/v1.0/issueToken`. (cf. https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-apis)
* Using the same subscription key (not the token) and region with the sample `samples/csharp/dotnetcore/console` on Windows 10, however, you get an authentication error (403 above). (Please note that there are multiple places in the sample code where subscription key and region need to be updated)

Is the summary accurate?

Thanks, Mark

**Comment by riverar** [comment]
@mahilleb-msft That summary is accurate. I'll review the code again and make sure I didn't miss a spot.

**Comment by mahilleb-msft** [comment]
Thanks. I would appreciate if you could double-check your code.
Then there's two more things:
* Following https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/troubleshooting#validate-an-authorization-token, could you check if  uploading audio using `curl` works?
* Could you modify one of the samples with event handlers to output the SessionId when the session started event is fired? For example, add code at https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L270:
  ```
  if (e.EventType == SessionEventType.SessionStartedEvent)
  {
      Console.WriteLine("SessionId: " + e.SessionId);
  }
  ```

If you let us know the session ID, we can correlate with any errors on the service side. (Make sure to pick the right sample from the menu, in this case it would be `5`).

Thanks, Mark

**Comment by riverar** [comment]
@mahilleb-msft 

* Code looks good
* The documentation has me issue a request like so:
```
curl -v -X POST "https://westus.stt.speech.microsoft.com/speech/recognition/interactive/cognitiveservices/v1?language=en-US" -H "Authorization: Bearer [token removed]" -H "Transfer-Encoding: chunked" -H "Content-type: audio/wav; codec=audio/pcm; samplerate=16000" --data-binary [path to binary removed]
```

That results in:
```
< HTTP/1.1 403 Forbidden
< Date: Thu, 06 Sep 2018 18:11:56 GMT
< Content-Type: application/json; charset=utf-8
< Server: Kestrel
< Transfer-Encoding: chunked
< Strict-Transport-Security: max-age=31536000; includeSubDomains
<
{"Message":"Language parameter not supported for this kind of subscription"}
```

If I remove the `?language=en-US` parameter, I get:
```
< HTTP/1.1 400 Bad Request
< Date: Thu, 06 Sep 2018 18:15:06 GMT
< Content-Type: application/json; charset=utf-8
< Server: Kestrel
< Transfer-Encoding: chunked
< Strict-Transport-Security: max-age=31536000; includeSubDomains
<
{"Message":"Invalid cid"}
```

* Per request, I edited sample 5 and spit out session ID of `752cb6575eb6499d99809a60827e35d6`

**Comment by mahilleb-msft** [comment]
@riverar - can you please double-check the type of subscription you are using? It should have been created as "Speech service (preview)". Could it be it's currently a Custom Speech one?

You can decode the auth token also to check the type:
```
echo $YOUR_TOKEN | cut -d . -f2 | base64 -d
```


In the resulting JSON, product ID should be `SpeechServices.S0` or `SpeechServices.F0` (for the free one).

We suspect in your case it's `CRIS.*` rather, which would correspond to custom speech.

Thanks, Mark

**Comment by riverar** [comment]
@mahilleb-msft Wow. I feel about this small right now --> .

I recover a small bit of dignity, I must ask:
* Why do the CRIS offerings still exist? I thought those were renamed and long gone.
* What's the difference between the Custom Speech and Speech Preview with Custom Speech offerings? Am I confused? This blog post makes no distinction (https://azure.microsoft.com/en-us/blog/speech-services-now-in-preview/).
* My goal is to build a custom speech model -- I used to do this with CRIS but Speech Preview seems to support this too, right?

**Comment by mahilleb-msft** [comment]
Hi Rafael,

  fully understand the source of confusion. This will be fixed in the future, with deprecating the old types of subscriptions.

  You can use the Speech Preview subscription today for working with CRIS.

  Best, Mark
