### ISSUE TITLE
PushAudioInputStream doesn't work when multithreading

### ISSUE THREAD

**Issue by wakandan** [Azure-Samples/cognitive-services-speech-sdk#410]
**Describe the bug**
PushAudioInputStream doesn't seem to work when the stream is being pushed into from a different thread 

**To Reproduce**
```
"""
Example on how to recv binary content
"""

import threading

import azure.cognitiveservices.speech as speechsdk
import time
from dotenv import load_dotenv

load_dotenv()
import os
import wave

frames = []

speech_key = os.getenv('AZURE_SPEECH_KEY')
service_region = os.getenv('AZURE_SPEECH_REGION')
speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)

stream = speechsdk.audio.PushAudioInputStream()


def send_voice_frame():
    # The number of bytes to push per buffer
    n_bytes = 3200
    wav_fh = wave.open('audios/test_record.wav')
    try:
        while (True):
            frames = wav_fh.readframes(n_bytes // 2)
            print('read {} bytes'.format(len(frames)))
            if not frames:
                break

            stream.write(frames)
            time.sleep(.1)
    finally:
        stream.close()


def speech_recognition_with_push_stream():
    """gives an example how to use a push audio stream to recognize speech from a custom audio
    source"""
    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)

    # setup the audio stream
    audio_config = speechsdk.audio.AudioConfig(stream=stream)

    # instantiate the speech recognizer with push stream input
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)

    # Connect callbacks to the events fired by the speech recognizer
    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
    speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))

    speech_recognizer.start_continuous_recognition()


if __name__ == '__main__':
    thread1 = threading.Thread(target=speech_recognition_with_push_stream)
    thread1.start()
    thread2 = threading.Thread(target=send_voice_frame)
    thread2.start()
    time.sleep(30)
```

**Expected behavior**
As data bytes are pushed into the stream, transcribing should happen in real time

**Version of the Cognitive Services Speech SDK**
1.7.0

**Platform, Operating System, and Programming Language**
 - OS: MacOS Mojave 10.14.5
 - Hardware - Macbook 15" 2017
 - Programming language: Python

**Additional context**
 Nothing happens. The stream is being pushed into. The transcribing session started. After that nothing is received.

**Comment by jhakulin** [comment]
Thanks for the feedback, we are investigating on few issues currently related to multithreading, we let you know once we have fixes for this.

**Comment by zen-chetan** [comment]
I noticed the same issue happening with the `PullAudioInputStream` in a Flask application as well; with logging, I can see that it's `read()` method is never called by the speech recognizer. Is this threading related too?

Are there any workarounds for using an `AudioInputStream` derived instance?

**Comment by pankopon** [comment]
@wakandan
Sorry for the lack of updates on this. The issue in the code you posted is that speech_recognition_with_push_stream() does not wait for results, instead it exits right after speech_recognizer.start_continuous_recognition() returns and thus the recognizer object is lost.

I've attached a sample code that uses threads in the same way as in your original, but it adds a mechanism to ensure that the thread with speech_recognizer does not exit prematurely. Please have a look.
[push_stream.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4384345/push_stream.zip)

@zen-chetan
If the above is not helpful in your case, could you please post the code in question? The base logic in speech_recognition_with_pull_stream() in samples/python/console/speech_sample.py should be usable with threads as well.

**Comment by jhakulin** [comment]
Closing the case, please let us know if you need more information
