### ISSUE TITLE
LUIS and speech SDK integration samples error out with "Upgrade failed with a bad request (400). Please check the language name and endpoint id (if used) are correctly associated with the provided subscription key"

### ISSUE THREAD

**Issue by MeghanaM** [Azure-Samples/cognitive-services-speech-sdk#411]
**Describe the bug**
LUIS and speech SDK integration for intent recognition sample following the link https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-recognize-intents-from-speech-csharp errors out " Please check the language name and endpoint id (if used) are correctly associated with the provided subscription key"

**To Reproduce**
Created LUIS resource on standard tier on my Azure account. Copied key and assigned to prediction resource. Also correctly copied the App ID and the region. App is published in the canadacentral region. Keys in canadacentral region. Ran the sample code to get intents from audio from mic and also audio from file. App works on browser and also using LUIS runtime.

Both failed " Upgrade failed with a bad request (400). Please check the language name and endpoint id (if used) are correctly associated with the provided subscription key." Went through all the documentation and checked everything. Looks fine. 

**Expected behavior**
Top scoring intent and scores for other intents

**Version of the Cognitive Services Speech SDK**
v 1.7.0

**Platform, Operating System, and Programming Language**
 Windows 10, Google chrome

**Additional context**
 -

**Comment by chrisbasoglu** [comment]
can you make sure you are not using a Starter Key?

>  LUIS automatically generates a starter key so you can test the app using text queries. This key doesn't enable the Speech Services integration and won't work with this guide. Create a LUIS resource in the Azure dashboard and assign it to the LUIS app. You can use the free subscription tier for this guide.

**Comment by pankopon** [comment]
Closing the issue because no update since November, please re-open if still valid.
