### ISSUE TITLE
Wake Word 

### ISSUE THREAD

**Issue by SOliasS** [Azure-Samples/cognitive-services-speech-sdk#412]
Hey i was wondering if you have any updates when the wake word functionality will be available with standard Speech SDK, or if it is already included?@jhakulin
Wondering in particular for the Xamarin SDK.

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/scenario-availability
"Wake Word (Keyword Spotter/KWS) functionality might work with any microphone type, official KWS support, however, is currently limited to the microphone arrays found in the Azure Kinect DK hardware or the Speech Devices SDK"

 ref #309

**Comment by jhakulin** [comment]
Thanks for feedback, wake word functionality is targeted more publicly available in the next release estimated early Nov 2019.
Which platform you are using ?

**Comment by SOliasS** [comment]
I'm using xamarin/ so iOS and android

**Comment by jhakulin** [comment]
Closing the case, support is being released in coming 1.9.0 release soon for Windows UWP, Android and iOS through Nuget and Unity packages

**Comment by SOliasS** [comment]
@jhakulin is this feature delayed?
As we are currently on 1.7  and you initially teased early November and i don't expect you guys to release two new version so soon ;).
So when is 1.9 scheduled for release?

**Comment by jhakulin** [comment]
Sorry I meant the support is coming in 1.8.0, which is going to be released next week.

**Comment by TamaraShlomovMoveo** [comment]
Hi, I can't find the documentation to "wake word"  for ios (swift), can you please send me a link?

**Comment by jhakulin** [comment]
@TamaraShlomovMoveo iOS for objective-C/Swift bindings do not support yet keyword recognition, we are working on it to get it supported on future releases. Xamarin iOS using C# bindings supports  keyword recognition currently.

**Comment by upsilondynamics** [comment]
Any word on this? I am having issues getting keyword recognition to work on iOS but seems to work with Android (Xamarin/Speech Recognizer)
