### ISSUE TITLE
TTS JS Sample for Custom Speech endpoints 

### ISSUE THREAD

**Issue by manish-95** [Azure-Samples/cognitive-services-speech-sdk#413]
The current sample available for testing the STT functionality does not allow me to specify a custom speech endpoint. It would be helpful if there was a sample that allowed the use of Custom Speech endpoints.

**Comment by BrianMouncer** [comment]
I don't have any samples for fromEndpoint() at the moment.

You might find the [test cases for this API](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/6c6134687dd362a5467fc21f3a70b57e3f1d5a86/tests/SpeechConfigTests.ts#L130) helpful.

Though I suspect this will not give any more detail that the [SDK documentation](https://docs.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/speechconfig?view=azure-node-latest#fromendpoint-url--string-).


If you provide some information on what parts you found difficult after reading the API documentation, I can add that info to a WI to create an "Sample" for this area.

Thanks.

Brian.

**Comment by manish-95** [comment]
The current web sample available [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/browser) does not allow me to give the endpoint to which the call must be made. It only gives me subscription and region as selectable fields.

**Comment by szhaomsft** [comment]
@manish-95  do u mean TTS or SR? 

the sample link u gave is about SR

**Comment by pankopon** [comment]
This has been pending for a long time. I've added a work item to our backlog and we will address it in a future release. Once the work is done, we will update this issue to let you know when the sample will be available.
