### ISSUE TITLE
Stop recognizing immediately

### ISSUE THREAD

**Issue by SOliasS** [Azure-Samples/cognitive-services-speech-sdk#414]
I have a Button included in my app(Xamarin) where the user can start/stop voice recognition. If i wait till the stopContinuousRecognitionAsync response until i display that the app stops listening the Button would feel quite unresponsive.
It could take up to 15 seconds until the Button would react.
But if i immediately switch the Button icon without waiting for stopContinuousRecognitionAsync to finish, the user might have already started a new Recognition which might get terminated if i try to reuse the IntentRecognizer.@jhakulin #253 

It should be possible to at least immediately stop the recording process, because of privacy issues.

**Comment by jhakulin** [comment]
@SOliasS Thanks for the report, I'll try to reproduce and investigate. Does this happen on similarly on different platforms?

**Comment by SOliasS** [comment]
@jhakulin I only have tested on Android so far.

**Comment by jose-alvessh** [comment]
Hi there! 
I have a similar when using Speech Services on Android.
I'm trying to use keyword recognition to wake the system and then translate some speech to text. However when I detect the keyword and the user does not say nothing even using after the _stopContinuousRecognitionAsync_ method, I have always to wait 10 seconds until the service is stopped. Is there any way to stop the continuous recognition, after other timeout lower than 10 seconds,  if no speech is detected? Is there any way to stop immediately the continuous recognition if for instance i'm transiting between activities? 

Also, as I understood there's no option to use the Cognitive Services just to detect Keywords to wake the system. Will be this option implemented anywhere soon?
Thanks in advance!

**Comment by jhakulin** [comment]
Standalone KeywordRecognizer feature is currently under planning and will be implemented in the future releases during this spring.

@jose-alvessh If you need to use only keyword detection functionality from the SpeechRecognizer class, you can try if using stopContinuousRecognitionAsync().cancel(true) helps to achieve what you need in your application.

**Comment by SOliasS** [comment]
@jhakulin  stopContinuousRecognitionAsync().cancel(true) what would be the equivalent to this in the C# sdk?

**Comment by SOliasS** [comment]
@jhakulin is there an option for the xamarin sdk?

**Comment by LedanDark** [comment]
We've had the same issue trying to stop immediately, both with startContinousRecognition and recognizeOnceAsync.
stopContinuousRecognitionAsync() -> 10-15 seconds to resovle
stopContinuousRecognitionAsync().cancel(true) -> Not sure if this actually works, as we find we can reach TooManyRequests exceptions.

**Comment by jhakulin** [comment]
Reopening this as not fully covered by all languages (C#), we are planning to have improvement on this in future releases.

**Comment by GerardK1** [comment]
Hi All , I am using [JavaScript Browser Template](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/browser) as baseline, each time  stop recognize once asynch is called the recording still continues with the microphone enabled if the user continues talking /voice is detected. If the user stops talking the sessions stops as expected. Is this the same issue as others on this thread, if so is there a way/command to force stop of recognizeonceasync() immediately ?

**Comment by pankopon** [comment]
We've added a backlog work item to improve this and will address it in a future release (no exact schedule yet). Once the work is done, we will update this issue to let you know what release the feature will be in.

**Comment by TamarZanzouri** [comment]
Is there an update on this?

**Comment by TamarZanzouri** [comment]
Is there an update on this?
I am trying to StopContinuousRecognitionAsync but I want to cancel it so that the buffer audio will be cleared. 
I am using the c# SDK

**Comment by athul-android** [comment]
any update ?
using Android SDK

**Comment by hemeda3** [comment]
any update for js sdk?
