### ISSUE TITLE
Spot Strings/Keywords dynamically

### ISSUE THREAD

**Issue by SOliasS** [Azure-Samples/cognitive-services-speech-sdk#415]
Is it Possible to add a List of Strings to the intentRecognizer in Xamarin for adjusted word recognition?

I have a some Lists in my Application which the User can fill with items and later should be able to select an item with its name.
Is it possible to add a List<string> to the Call and let Luis know i'm looking for theses specific Strings(Names)?
So luis is able to identify these maybe unusual letter combinations.

I found it's possible to add a GrammerList/PhraseListGrammer to the request, but the docu about theses feature is a bit lacking and i don't understand there purpose exactly or how i should use them.

An alternative i could think of is, if it´s possible to add Patterns via an Api to Luis, but i'm not sure if that is possible either. 
@jhakulin

**Comment by SOliasS** [comment]
@jhakulin Any advice regarding how i could solve this, or who could could help me on this topic?
Is it even possible at the moment?

**Comment by jhakulin** [comment]
@SOliasS Sorry for late response, have you checked the document about PhraseLists ?
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-phrase-lists

Could you add a phrase/word using PhraseListGrammar for each added phrase user has added and get those recognized then individually ?

**Comment by SOliasS** [comment]
@jhakulin Sounds exactly like what i need...
But unfortunately it says on the page that it's only available in English atm.
Is this information up to date and if so when will it be available for german?

**Comment by jhakulin** [comment]
@SOliasS There seems to be indeed a gap in language support, I'll check plans for supporting other languages, german and others. Thanks.

**Comment by jhakulin** [comment]
I checked the plans and adding support for other languages using Phraselist is actively under work and expecting the support will be released in near future releases.

**Comment by SOliasS** [comment]
@jhakulin Any indication when it will hit live?

**Comment by jhakulin** [comment]
@SOliasS This is progressing and some new languages are being rolled out, however I do not have yet ETA for german, I will let you know when that happens.

**Comment by SOliasS** [comment]
@jhakulin Do you have any update about this issue?

**Comment by SOliasS** [comment]
@jhakulin any indication when the german support will arrive?
