### ISSUE TITLE
iOS continuous speech recognition runs out of threads.

### ISSUE THREAD

**Issue by leuski-ict** [Azure-Samples/cognitive-services-speech-sdk#416]
**Describe the bug**
iOS version of SDK (v 1.6) runs out threads using continuous recognition and dies.

**To Reproduce**
run the iOS SDK example where the audio is treated from the microphone or audio file using continuous recognition API:
 - allocate speech recognizer
 - initialize listeners and audio stream
 - call startContinuousRecognition
 - stream audio
 - call stream.close()
 - call stopContinuousRecognition
 - wait for the result. 
 - cleanup (deallocate recognizer) 
 - Repeat.

After about 500 iterations this process stops with
nw_socket_handle_socket_event [C201.1:1] Socket SO_ERROR [60: Operation timed out]

Attempting to restart the loop results in  

" UserInfo={NSLocalizedDescription=Error: thread constructor failed: Resource temporarily unavailable
[CALL STACK BEGIN]

2   MicrosoftCognitiveServicesSpeech    0x0000000101390968 recognizer_create_speech_recognizer_from_config + 900
3   MicrosoftCognitiveServicesSpeech    0x00000001012fd810 MicrosoftCognitiveServicesSpeech + 202768
4   MicrosoftCognitiveServicesSpeech    0x00000001012fdc54 MicrosoftCognitiveServicesSpeech + 203860
5   MicrosoftCognitiveServicesSpeech    0x00000001012fe3c0 MicrosoftCognitiveServicesSpeech + 205760
6   ASR Lab                             0x0000000100ba69c4 $sSo19SPXSpeechRecognizerC19speechConfiguration05audioD0ABSo0aD0C_So08SPXAudioD0CtKcfcTO + 148
7   ASR Lab                             0x0000000100ba2908 $sSo19SPXSpeechRecognizerC19speechConfiguration05audioD0ABSo0aD0C_So08SPXAudioD0CtKcfC + 68
8   ASR Lab                             0x0000000100ba2158 $s7ASR_Lab09MicrosoftA0026_03EC13A54A8284B7E5D3AEA26H5EC8ADLLC9publisher3url9arguments7Combine12AnyPublisherVyAA0A0V8ResponseVs5Error_pG10Foundation3URLV_AD9ArgumentsVtFyys6ResultOyANsAO_pGccfU_yycfU_ + 2096
9   ASR Lab                             0x0000000100b2d2f4 $sIeg_IeyB_TR + 52
10  libdispatch.dylib                   0x000000010c9e5e48 _dispatch_call_block_and_release + 32
11  libdispatch.dylib                   0x000000010c9e72a8 _dispatch_client_callout + 20
12  libdispatch.dylib                   0x000000010c9f8ccc _dispatch_root_queue_drain + 900
13  libdispatch.dylib                   0x000000010c9f9418 _dispatch_worker_thread2 + 144
14  libsystem_pthread.dylib             0x000000018382aa60 _pthread_wqthread + 216
15  libsystem_pthread.dylib             0x0000000183830c78 start_wqthread + 8
[CALL STACK END]

}

Breaking into the debugger I can see 500 zombie threads just sitting there waiting on some variable. Each thread stack is like this:

#0	0x0000000183908cc4 in __psynch_cvwait ()
#1	0x000000018382c508 in _pthread_cond_wait ()
#2	0x000000018395cda0 in std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) ()
#3	0x000000010145ce48 in ___lldb_unnamed_symbol5416$$MicrosoftCognitiveServicesSpeech ()
#4	0x000000010145fe18 in ___lldb_unnamed_symbol5464$$MicrosoftCognitiveServicesSpeech ()
#5	0x0000000183828d5c in _pthread_start ()

**Expected behavior**

**Version of the Cognitive Services Speech SDK**
1.6

**Platform, Operating System, and Programming Language**
 - OS: iOS 13.1.3
 - Hardware - iPhone
 - Programming language: Objective-C/ Swift

**Additional context**
 - Error messages, log information, stack trace, ...
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by leuski-ict** [comment]
After looking carefully at the SDK framework, the SDK version is 1.7.

**Comment by jhakulin** [comment]
Thank you for the report, we will investigate.

**Comment by jhakulin** [comment]
@leuski-ict Do you know is this iOS specific issue or happen also with other platforms?

**Comment by leuski-ict** [comment]
I'm sorry, I missed a note about the reply. No, I do not know about other platforms.

**Comment by jhakulin** [comment]
Ok, we are still working on this, investigation has been a bit delayed due to other urgent issues.

**Comment by pankopon** [comment]
We've added a backlog work item to improve this and will address it in a future release. Once the work is done, we will update this issue to let you know what release the improvement will be in.
