### ISSUE TITLE
Option to enable/disable punctuation and/or numbers, currencies

### ISSUE THREAD

**Issue by Chreschtf** [Azure-Samples/cognitive-services-speech-sdk#417]
**Is your feature request related to a problem? Please describe.**
Creating a tool which allows users to dictate exactly what they want to have written, I came across the following issues using the standard speech model: 

Achieving the output "#" :
If the utterance is "pound", output is "pound", however if the utterance is "pound sign", the output is "# sign", somehow unexpected.

Since "pound sign" can also mean "£" given the context, I then tried some sentences which should guarantee "£" as output:
Utterance  = "This costs seven pounds" -> output = "This costs 7 pounds", however if
Utterance = "You have to pay seven pounds", output = "You have to pay £7.00"
Since both sentences are pretty close in context I presumed they would give the same representation of "seven pounds".

When uttering "one or two" the output is "One or 2", but "two or three" becomes "2 or 3", which may not always be what one was going for.

**Describe the solution you'd like**
Would it be possible to add certain options for the model config to 

- (not) convert spoken punctuation into their respective symbol (even define just a subset of them to ignore/consider), 
- (not) convert spoken numbers into their respective digit form,
- (not) convert prices such as "seven pounds" to "£7.00", or even just convert them to "£7"
- (not) output the implicit punctuation of the language e.g. "Hello, who are you?" when utterance was "hello who are you"

**Describe alternatives you've considered**
While I can extract the lexical form of a recognised utterance from the detailed response, being able to toggle said options individually would make it more dynamic and require less post-processing after having received the recognition result, since the lexical form also changes most of the output to lowercase(?) and one might be interested in enforcing only one type of output format. The different options would add more overall consistency for certain use cases different from the typical email dictation.

I also tried using the config option *EnableDictation* but it did not give me a different output when dictation the same phrases. Could you explain what is supposed to change when using said option? https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechconfig.enabledictation?view=azure-dotnet doesn't provide much to work with...
**Additional context**

**Comment by amitkumarshukla** [comment]
@Chreschtf Thanks a lot for your feedback. We have made a note of this in our internal backlog and will be working on it to improve our models. However we cannot commit how long this is going to take. But we will keep improving the accuracy and experience.

In the meantime if you want to experience the punctuation on/off, please use the continuous recognition and try EnableDictation to see different results. 

For the time being I am closing this issue. Please keep an eye on our new releases for more.

Thank you.

**Comment by imkhubaibraza** [comment]
Any update on this ?
