### ISSUE TITLE
Xamarin No Compatible code running

### ISSUE THREAD

**Issue by SOliasS** [Azure-Samples/cognitive-services-speech-sdk#418]
It 's very tedious to debug code when the Xamarin Speech SDK is running in the background. 
As soon as you start the IntentRecognizer for example you can only debug until the next breakpoint.@jhakulin
After you hit the breakpoint you constantly get the "No compatible code running" error.
You are able to continue debugging but this "error" will constantly be thrown every second or so and this even results in sometimes different code behavior.
![image](https://user-images.githubusercontent.com/14180046/67698149-12ff7980-f9aa-11e9-902a-0e944318c122.png)

At the moment i'm debugging by hitting single breakpoints and then restarting....

I think the Xamarin Sourcelink Project could help https://github.com/dotnet/sourcelink

**Comment by jhakulin** [comment]
@SOliasS Thanks for information and proposal for solution. I need to study the issue as I have not seen this before, does that happen with all plaforms?

**Comment by SOliasS** [comment]
@jhakulin until now I have only tested on Android.

**Comment by SOliasS** [comment]
@jhakulin 
Did you have time to look in this issue?
Also when hitting a breakpoint before Luis stopped completely the debugger breaks without even showing anything.
The only working workaround is to put a delay of 7 seconds before the breakpoint 
But's gets quite annoying to always have to wait...

**Comment by pankopon** [comment]
We've created a backlog work item to improve this and will address it in a future release. Once the work is done, we will update this issue to let you know what release the improvement will be in.
