### ISSUE TITLE
Troubleshooting DirectLine Speech issues

### ISSUE THREAD

**Issue by theconvchamp** [Azure-Samples/cognitive-services-speech-sdk#419]
I am using C# SDK for Direct Line Speech to try and create a back and forth seamless communication from the bot and my voice app, but the websocket stream keeps getting disconnected after first or second back-and-forth. I see this error in Connector_Cancelled event: 

`Connector_Canceled:Error ConnectionFailure : Connection was closed by the remote host. Error code: 1011. Error details: Internal server error. SessionId: 08e399e7615b499eb1b38ba2ffc6b283`

How do I troubleshoot this issue and how do I correlate the SessionId. I don't see this session id is different each time even between the different events like Connection_SessionStarted and Connection_SessionStopped.

**Comment by jhakulin** [comment]
@trrwilson Could you please comment on this issue ?

**Comment by oscholz** [comment]
Hi @theconvchamp!
Thank you for this bug report. I apologize for the prolonged radio silence. We will do better in the future!
Could you please try this again with the most recent release of the Speech SDK (1.12.1 or later)?
If the issue still repros with that, please reopen this issue and we will get right on it. We now have a process in place whereby we get to your issues much more quickly. Again, my apologies for dropping the ball here.
