### ISSUE TITLE
Is there a way to set NO_PROXY on the SpeechConfig

### ISSUE THREAD

**Issue by maczikasz** [Azure-Samples/cognitive-services-speech-sdk#420]
I need to set NO_PROXY for some of the endpoint azure uses, because of our infrastructural setup, is there a way to do that?

I am using a the JAVA SDK

**Comment by pankopon** [comment]
Hi, the SDK does not support NO_PROXY or a similar environment variable at the moment. The SpeechConfig.setProxy() method [https://docs.microsoft.com/en-us/java/api/com.microsoft.cognitiveservices.speech.speechconfig.setproxy?view=azure-java-stable] can be used for proxy configuration; the default setting is no proxy.

**Comment by maczikasz** [comment]
Do you plan to support it?

**Comment by chrisbasoglu** [comment]
@maczikasz can you say why SpeechConfig.setProxy() is not sufficient?

**Comment by maczikasz** [comment]
Because in my setup I need to use proxy for some on the endpoints that you use but not for all of them

**Comment by wolfma61** [comment]
@maczikasz  -
you create a recognizer from a config without a proxy defined, you create another recognizer from a config with a proxy defined ...
why wouldn't this work?

**Comment by maczikasz** [comment]
Because this is not the problem I am facing :) we have a setup with express route to MS azure, and all requests to cognitive services endpoint should NOT go through the proxy but rather the express route, but all other requests to quota check, login, etc should go through the proxy

**Comment by wolfma61** [comment]
@maczikasz  -
Sorry, I'm not exactly sure what you need or even what you are asking. 

By default, the SDK is not using any proxy configuration. It is just doing an HTTP Connect to the endpoint.
If you define a proxy through the SpeechConfig.setProxy, then (and only then) the SDK tries to connect through this proxy to the endpoint. 

If you would specify NO_PROXY, how would you expect the SDK to behave? By default it is already NOT using a proxy. 

can you please clarify?

**Comment by maczikasz** [comment]
Generally most libraries ask for 3 (optionally 5) parameters for proxy settings
proxy host : proxy port
(optionally uname/pwd)
and noproxy hosts

noproxy hosts is a list of hosts for which the proxy is NOT used to connect. In my case we had a direct connection with some tcp routing magic to  https://$region.stt.speech.microsoft.com/speech/recognition, but not to login.ms.com or any other MS site that the SDK would access. So I would set proxyhost and port to my proxy settings and noproxy hosts to  https://$region.stt.speech.microsoft.com/speech/recognition

**Comment by wolfma61** [comment]
The SDK is just accessing *.speech.microsoft.com resources for standard speech to test. It is just creating an HTTPS connection and then upgrading it to a websocket connection. Some text to speech services might use REST endpoints with some different URL scheme.

as we are just using *.speech.microsoft.com connections, why would you need the NO PROXY  option?  The SDK isn't accessing login.ms.com etc ....

**Comment by rhurey** [comment]
Is there an error using the SpeechSDK without setting a proxy in your environment?

**Comment by chrisbasoglu** [comment]
please reopen if still an issue with info.

**Comment by maczikasz** [comment]
I want to reopen this issue

Our setup have changed significantly and we are back to trying to use the speech sdk from on premise, but with a private endpoint peering setup.

Basically I have the problem that we have the private endpoint "wss://test.cognitiveservices.azure.com" which is available from our on-prem setup without proxy, but for every other kind of outgoing connections we need to use our corporate proxy.

If i set the proxy connections on the speech SDK the connection fails when trying to connect to 'wss://test.cognitiveservices.azure.com', but if i don't set the proxy the connection fails when trying to get the CLR from azure

Can you please advise

**Comment by rhurey** [comment]
The client SDK will need access to the Azure CRL / OCSP distribution points. 

The location of these is listed here: https://docs.microsoft.com/en-us/azure/security/fundamentals/tls-certificate-changes#next-steps

**Comment by maczikasz** [comment]
The SDK in fact has access to that IF i set the proxy. If i dont it wont. But if i set the proxy then all the calls to our private endpoint for the speech service will go through the proxy, and this is not correct, this is where having NO_PROXY would normally come in

**Comment by pankopon** [comment]
As the situation with NO_PROXY support is unchanged from what it was a year ago, I've created a backlog item about bypassing the configured proxy for select addresses - to be considered and prioritized. Since this seems to be the only such request so far, I'll quote @oscholz from another issue:

> Could you put this feature request in our Feedback portal, please?
https://feedback.azure.com/forums/932041-cognitive-services
Also feel free to open a support request in the Azure portal (log in to portal.azure.com, open your Speech or Cognitive Services resource, then click on New support request in the lower left). This way we can have a more direct/non-public conversation with you about this request, and potentially get a better understanding of your use case to help us prioritize this request.

We'll update here with actual release information when available. Please open a new issue if you need any other support on specific topics.

**Comment by maczikasz** [comment]
Ok thanks, i opened an azure issue, since this is actively blocking our progress
