### ISSUE TITLE
How can use AddDiarization property with audio stream?

### ISSUE THREAD

**Issue by pushkarchaurasia** [Azure-Samples/cognitive-services-speech-sdk#421]
Hi All,

I am able to use AddDiarization property with using Audio file URL. But I need to pass Audio stream instead of URL. Is there any way to do it?

**Comment by pushkarchaurasia** [comment]
Hi All,

I am able to use AddDiarization property with using Audio file URL. But I need to pass Audio stream instead of URL. Is there any way to do it?

**Comment by pushkarchaurasia** [comment]
Hi Wolfgang,

Thanks for the reply.

Yes, I am using Batch Transcription REST API and you are already mentioned that we can not use stream with this API.

I want to distinguish between two speakers(agent and client), but with the use of audio stream. So, is there any other way we can do this. 
I am trying to create live conversation report, so I need to pass audio stream.

**Comment by wolfma61** [comment]
using the audio stream this isn't possible currently in the SDK.
This is a feature that will be added in a future release, but no definite release date is available yet.

**Comment by pushkarchaurasia** [comment]
Thanks Wolfgang for the confirmation.

**Comment by amitkumarshukla** [comment]
@pushkarchaurasia I am closing this for the time being. If you have any other questions please open a new issue.
