### ISSUE TITLE
iOS swift app crash 

### ISSUE THREAD

**Issue by fiazhussain43** [Azure-Samples/cognitive-services-speech-sdk#422]
let result = try! synthesizer.speakText(inputText)
       if result.reason == SPXResultReason.canceled
MicrosoftCognitiveServicesSpeech-iOS (1.7.0)
CoreFoundation`CFErrorGetCode:
    0x228ba2448 <+0>:  tbz    x0, #0x3f, 0x228ba2458    ; <+16>
    0x228ba244c <+4>:  adrp   x8, 184177
    0x228ba2450 <+8>:  add    x1, x8, #0xd7d            ; =0xd7d 
    0x228ba2454 <+12>: b      0x227e33520               ; objc_msgSend
->  0x228ba2458 <+16>: ldr    x8, [x0]
    0x228ba245c <+20>: adrp   x9, 237914
    0x228ba2460 <+24>: add    x9, x9, #0xd0             ; =0xd0 
    0x228ba2464 <+28>: ldr    x9, [x9]
    0x228ba2468 <+32>: cmp    x8, #0x0                  ; =0x0 
    0x228ba246c <+36>: ccmp   x8, x9, #0x4, ne
    0x228ba2470 <+40>: b.eq   0x228ba24a4               ; <+92>
    0x228ba2474 <+44>: adrp   x9, 237912
    0x228ba2478 <+48>: add    x9, x9, #0xd0             ; =0xd0 
    0x228ba247c <+52>: ldr    x9, [x9, #0xd8]
    0x228ba2480 <+56>: cmp    x8, x9
    0x228ba2484 <+60>: b.eq   0x228ba24a4               ; <+92>
    0x228ba2488 <+64>: tbz    w8, #0x0, 0x228ba244c     ; <+4>
    0x228ba248c <+68>: adrp   x10, 198643
    0x228ba2490 <+72>: ldr    x10, [x10, #0xc28]
    0x228ba2494 <+76>: ldr    x10, [x10]
    0x228ba2498 <+80>: and    x8, x10, x8
    0x228ba249c <+84>: cmp    x8, x9
    0x228ba24a0 <+88>: b.ne   0x228ba244c               ; <+4>
    0x228ba24a4 <+92>: ldr    x0, [x0, #0x10]
    0x228ba24a8 <+96>: ret

**Comment by szhaomsft** [comment]
@yulin-li  can u take a look

**Comment by yulin-li** [comment]
@fiazhussain43 
Thanks for reporting this issue, could you tell me more enviornment information such as OS version, Xcode version, ios SDK version. Do you run this code on simulator or real device?

Could you follow this [quickstart](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/text-to-speech/swift-ios) to see if it works?

**Comment by fiazhussain43** [comment]
@yulin-li 

I use real device

thanks

**Comment by fiazhussain43** [comment]
Your code not working please provide updated code

**Comment by yulin-li** [comment]
@fiazhussain43 Thanks

Could you pls tell your device model, iOS version and Xcode version?

**Comment by fiazhussain43** [comment]
iOS 13 and Version 11.0 (11A420a) Xcode

**Comment by yulin-li** [comment]
Hi @fiazhussain43 

We tested the quickstart app on real device and it worked fine. We use Xcode 11, iOS 13.2 and Speech SDK 1.7.0. Could you check again in your side? For easy diagnosis, could you try to test it on a simulator?
