### ISSUE TITLE
Batch API Sample using v2.0 endpoints causes 2.1 WebHooks to be unusable

### ISSUE THREAD

**Issue by markti** [Azure-Samples/cognitive-services-speech-sdk#425]
**Describe the bug**
The sample for batch transcription needs to be updated for v2.1 of the API.

**To Reproduce**
1. Setup a webhook using v2.1 of API (https://eastus.cris.ai/api/speechtotext/v2.1/transcriptions/hooks)
2. Start a batch transcription using v2.0 (as shown in the demo in this repo), notice webhook never fires!

**Expected behavior**
My Webhook should fire or sample should be updated to include 2.1 BatchClient code

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 - OS: Windows
 - Hardware - x64
 - Programming language: C#

**Additional context**
 - Error messages, log information, stack trace, ...
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by wolfma61** [comment]
some API changes and improvements to the batch docs are in progress
sorry for the delay

Wolfgang

**Comment by markti** [comment]
When can we expect an update? I'm looking to demo a prototype solution for this ASAP.

**Comment by PanosPeriorellis** [comment]
hi everyone, Just a quick note to say that the webhook functionality will be exposed publicly through v3 API which is under development. 2.1 is not public and we will not likley make it so.  I would suggest you stick with 2.0.
