### ISSUE TITLE
How do I recognize 8kHz audio for speech recognition sdk? 

### ISSUE THREAD

**Issue by byuns9334** [Azure-Samples/cognitive-services-speech-sdk#426]
what is the exact option or parameter for handling input audio's sample rate?

**Comment by chinmayembedded** [comment]
You can use **sox** command which can help you see and modify the audio parameters.

**Comment by amitkumarshukla** [comment]
Currently we do not support 8Khz audio for speech recognition. Please use goldwave or any other tool of your choice to convert the audio to 16Khz, 16 bit and mono wave file for recognition. Do let us know if you have more questions

**Comment by amitkumarshukla** [comment]
I am closing this for the time being.

**Comment by amitkumarshukla** [comment]
@chinmayembedded I am really sorry for the information. You can recognize 8khz wave file using speech sdk. the format should be 8Khz, 16 bits and mono.

Please use FromWavFileInput https://docs.microsoft.com/en-us/cpp/cognitive-services/speech/audio-audioconfig.

In our documentation it says that we only support 16Khz but we will go ahead and update the documentation. Do let us know if you still face any issue. 

I am closing it for the time being.

**Comment by carlossapnucivicom** [comment]
Hi!,

Is the class [WavStream.java](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/WavStream.java) updated for 8kHz WAV support? seems like it fails if it detects a sample rate not equal to 16kHz. 

Thanks-

**Comment by amitkumarshukla** [comment]
@carlossapnucivicom Thanks a lot for pointing this out to us. We should change this. Right now Speech sdk support all the wav formats.
