### ISSUE TITLE
Increasing performance of Custom speech to text 

### ISSUE THREAD

**Issue by chinmayembedded** [Azure-Samples/cognitive-services-speech-sdk#427]
I have referred open source data set provided by ezDI.
https://www.ezdi.com/open-datasets/

My training data consists of language data of all the files with 100 minutes of audio transcription.
So far on my training data set i have achieved WER 30%.

Any practices to increase the accuracy further?

**Comment by amitkumarshukla** [comment]
Please have a look at this following 
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-custom-speech
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-phrase-lists

and do let us know if that answers your question

**Comment by amitkumarshukla** [comment]
@chinmayembedded I am closing it for the time being. If you still have more doubt, please get back to us.
