### ISSUE TITLE
Samples fail on Windows 10 RS5

### ISSUE THREAD

**Issue by riverar** [Azure-Samples/cognitive-services-speech-sdk#43]
Initially posted this in the Windows Dev MVP alias but surfacing it here for visibility.

## Configuration
Windows 10 RS5, Build 17751
.NET Core 2.1 console app with [simple sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp-dotnetcore)

## Behavior
On start, immediately throws an exception on factory.CreateSpeechRecognizer(). (Does this SDK work on RS5? Final RS5 bits are on the horizon so am a little shocked here.)

I do not get the same exception on RS4.

```
(85): 18ms SPX_THROW_HR_IF: (0x00e) = 0xe
(85): 166ms SPX_RETURN_ON_FAIL: hr = 0x47967820
SPX_THROW_ON_FAIL: ::SpeechFactory_CreateSpeechRecognizer_With_Defaults(m_hfactory, &hreco) = 0x47967820

System.ApplicationException: 'Exception with an error code: 0xe
[CALL STACK]

    > CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - Session_SetParameter_String

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - SpeechFactory_CreateSpeechRecognizer_With_Defaults

    - CSharp_MicrosoftfCognitiveServicesfSpeechfInternal_FactoryParameterCollectionBase_SWIGUpcast___

    - CSharp_MicrosoftfCognitiveServicesfSpeechfInternal_ICognitiveServicesSpeechFactory_CreateSpeechRecognizer__SWIG_0___

    - 00007FFCE42D6F8F (SymFromAddr() error: The specified module could not be found.)
```

**Comment by mahilleb-msft** [comment]
`0xe` is an internal error code for no microphone being available. Could it be you're running in a VM, for example?

[We'll improve on the error message and their documentation]

**Comment by riverar** [comment]
@mahilleb-msft Wow, didn't realize that. Microphone device was disabled. Now I just need to get past the authentication issue (#41), thanks.
