### ISSUE TITLE
<audio> tag not working within SSML

### ISSUE THREAD

**Issue by upsilondynamics** [Azure-Samples/cognitive-services-speech-sdk#433]
Microsoft.CognitiveServices.Speech
C# SDK  Not working

I simply want to embed Audio as mentioned
(https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup

When the following SSML is called into the **SpeechSynthesizer.SpeakSsmlAsync**, the system returns a Cancel error:

**Connection was closed by the remote host. Error code: 1007. Error details: Unsupported voice . USP state: 3. Received audio size: 0bytes.**

I am clearly providing a URL with a valid file and I believe I have well formed the audio tag as per the documentation:

```
<speak version='1.0' xml:lang='en-US'>
<audio src="https://www.upsilondynamics.com/Content/TwilioGreetings/notify.wav" />
<voice xml:lang='en-US' xml:gender='male' name='en-US-GuyNeural'> 
Hello World, this is a test!</voice>
</speak>
```

Embedding it within the VOICE tag is preferable, it also dos not work:
```
<speak version='1.0' xml:lang='en-US'>
<voice xml:lang='en-US' xml:gender='male' name='en-US-GuyNeural'> 
<audio src="https://www.upsilondynamics.com/Content/TwilioGreetings/notify.wav" />
Hello World, this is a test!
</voice>
</speak>
```

This is a duplicate posted here as it is documented here, but I cannot get it to work:
https://github.com/MicrosoftDocs/azure-docs/issues/42668

**Comment by yulin-li** [comment]
Thanks @upsilondynamics for reporting this issue.
 
We are sorry for the inconvenience. 

1. Each segment of the SSML needs a `<voice>` tag, and our doc for the SSML may be outdated. Your second ssml is correct.
1. When you use your second SSML, I think you encounter an error like `wordboundary is unsupported ....`. This is a known issue and we are working on it. As a workaround for now, you can disable wordboudary feature by setting a property to the speech config.
` speechConfig.SetProperty("SpeechServiceResponse_Synthesis_WordBoundaryEnabled", "false");`

**Comment by nitinthewiz** [comment]
@yulin-li I would love to understand what the word boundary feature does, if you could please take the time to explain? The documentation is not very clear on it.

**Comment by yulin-li** [comment]
@nitinthewiz 
With this feature, you can get word boundary info from the server during synthesizing audio. Word boundary info will tell you the audio offset of each word. You can use this offset to highlight the words under playing and other things.

**Comment by nitinthewiz** [comment]
@yulin-li that seems to be a very interesting and useful feature! 

I assume it works right now with single voice audio? I didn't see the output anywhere. Is it similar to Amazon Polly's Speechmarks in that I need to change the file-type from mp3 to JSON (ndJSON in their case), and then I'll get the boundaries?

Also, just out of curiosity, how do you create the boundaries? Do you use a forced aligner after the audio generation to create the textual data? Or is it generated as part of the audio generation itself?

**Comment by yulin-li** [comment]
@nitinthewiz 
Sure, word boundary feature works fine with single voice audio. You don't need to change file type, just binding a `wordboundary event` is enough. You can refer [this c# sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_synthesis_samples.cs#L560) to try this feature (other language samples also available in this repo).

**Comment by ylz201** [comment]
Not working yet if one audio tag and sdk version is 1.19.0

**Comment by johnmalatras** [comment]
I'm also not able to user `audio` or `mstts:backgroundaudio`. Any update on this?
