### ISSUE TITLE
README.md should say "Voice Assistant quickstarts" instead of "Voice-first virtual assistants quickstarts"

### ISSUE THREAD

**Issue by dargilco** [Azure-Samples/cognitive-services-speech-sdk#435]
**Describe the bug**
This is a doc bug. README.md should say "Voice Assistant quickstarts" instead of "Voice-first virtual assistants quickstarts". [Voice Assistants](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/#pivot=start&panel=voice-assistants) is the new term to describe APIs in the Microsoft.CognitiveServices.Speech.Dialog namespace.

**Comment by chrisbasoglu** [comment]
Hi Darren,  since you are an MSFT employee, can you check to see if you have edit privileges?  If not, we will do this for you.  If you do, could you make the change?

![image](https://user-images.githubusercontent.com/16262519/69462973-4924e480-0d2f-11ea-9cf6-a52b90d170dd.png)

**Comment by jhakulin** [comment]
@trrwilson Could you take a look on this?

**Comment by dargilco** [comment]
@jhakulin @trrwilson @chrisbasoglu No problem, I'll take care of it on Monday.

**Comment by dargilco** [comment]
@jhakulin @chrisbasoglu [PR here (I can't add folks as reviewers)](https://github.com/Azure-Samples/cognitive-services-speech-sdk/pull/447). Please sign off

**Comment by jhakulin** [comment]
Closing the issue
