### ISSUE TITLE
Xamarin WakeWord KeywordRecognitionModel.FromFile

### ISSUE THREAD

**Issue by SOliasS** [Azure-Samples/cognitive-services-speech-sdk#439]
I was wondering how 
`KeywordRecognitionModel.FromFile(keywordSave);`
should work. @jhakulin
I added the Keyword generated file to my Assets folder and tried to reference it, but it couldn't find it.
So atm i reading the file from the Assets folder and then writing it locally.
Then referencing the local file Works fine.
But i can't be intended to copy the included file.....
In the Device SDK there is also a FromStream Function this would be a nice alternative...

KeywordRecognitionModel keywordRecognitionModel = KeywordRecognitionModel.fromStream(assets.open(KeywordModel), Keyword, true);

**Comment by jhakulin** [comment]
@SOliasS Apologies for late answer, I assume you are using Android ? 
Currently we do not have provide other solution to this than copying the file from asset to local cache (as it is done in kws-xamarin sample). Is that you would not like to do ?

**Comment by FallnGod** [comment]
Hello,

Quick question about this.  What does the format of the local file look like? Are the keywords separated by an enter key? I can't seem to find the proper format anywhere.

**Comment by SOliasS** [comment]
@FallnGod you have to create the file via the speechstudio, it's only available for english but it also works for other languages, because Key Word pronunciation doesn't/shouldn't differ between languages. https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-devices-sdk-create-kws

@jhakulin yes, it would be better if i could directly add the stream/or point to the location in the assets, without saving basically two copys of the same file in the app.

**Comment by pankopon** [comment]
We've created a backlog work item to improve this and will address it in a future release. Once the work is done, we will update this issue to let you know what release the improvement will be in.

**Comment by jogugil** [comment]
Hello, I am compiling an old code that I had to make a speech recognizer with Microsoft.CognitiveServices.Speech; and xamarin.Fomrs.
But when I run it it doesn't work with the updated versions.
In fact the function
KeywordRecognitionModel.FromFile (kwsModelDir);

It gives me an assembly error when before it worked without problem and it recognized the keyword to activate the recognizer.
The error is: libMicrosoft.CognitiveServices.Speech.core.so assembly: <unknown assembly> type: <unknown type> member: (null)
Versions:
Visual Studio 2019
Xamarin.Forms
(4n all 4.8 gives me an error and not before)
Microsoft.CognitiveServices.Speed ​​1.14

**Comment by jogugil** [comment]
Hello, I am compiling an old code that I had to make a speech recognizer with Microsoft.CognitiveServices.Speech; and xamarin.Fomrs.
But when I run it it doesn't work with the updated versions.
In fact the function
KeywordRecognitionModel.FromFile (kwsModelDir);

It gives me an assembly error when before it worked without problem and it recognized the keyword to activate the recognizer.
The error is: libMicrosoft.CognitiveServices.Speech.core.so assembly: <unknown assembly> type: <unknown type> member: (null)
Versions:
Visual Studio 2019
Xamarin.Forms
(4n all 4.8 gives me an error and not before)
Microsoft.CognitiveServices.Speed ​​1.14
