### ISSUE TITLE
Is there is a way to specify the recognize mode for android sdk?

### ISSUE THREAD

**Issue by ZhouGYong** [Azure-Samples/cognitive-services-speech-sdk#44]
As subject.

There is an introduction on this link:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech/concepts#recognition-modes

There are three modes of recognition: interactive, conversation, and dictation. The recognition mode adjusts speech recognition based on how the users are likely to speak. Choose the appropriate recognition mode for your application.

These modes are applicable when you directly use the REST or WebSocket protocol. The client libraries use different parameters to specify recognition mode. For more information, see the client library of your choice.

But I cannot find a way to specify recognition mode, anyone can help? Thanks a lot! 
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). Other.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wolfma61** [comment]
if you use StartContinousRecognition we use automatically conversation mode.
if you just use Recognize we use interactive mode.

you can set it by yourself if you specify the URL including the parameters once for creation of the recognizer. do you need more fine-grained control?

thx
Wolfgang

**Comment by wolfma61** [comment]
closing this one without additional feedback.
for specific issues please open a new request ...
