### ISSUE TITLE
Page Not Found.

### ISSUE THREAD

**Issue by bfarhan8** [Azure-Samples/cognitive-services-speech-sdk#440]
This Link
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/java/README.md#get-the-samples
Under this Label
"Download the sample code to your development PC".
Is not working.

It's returning the 404 Error.

**Comment by rhurey** [comment]
Thanks for pointing this out.

In a recent re-shuffling of the quickstarts, updating the readme.md files was missed. I'll work on that in the next day or so.

**Comment by rhurey** [comment]
Fixed.
