### ISSUE TITLE
Speech Services Client on docker for Linux | Recognition error : ErrorDetails=Runtime error: Failed to initialize platform (azure-c-shared)

### ISSUE THREAD

**Issue by cedrox** [Azure-Samples/cognitive-services-speech-sdk#441]
**Describe the bug**
We are deploying containers via IOT hub and we use speech Cognitive Service. Our containers must interact with Linux host audio IOs via Alsa and Pulse Audio. I can play a sound via "aplay" and recover the microphone from the command "arecord" from the container but I have problems accessing the server pulse as part of my netcore program. 

**To Reproduce**
1. Implement a Hello World program with audio and record on dotnet core 3
2. Embed it into a Ubuntu 18.04 container
3. Run on a Ubuntu host 
4. Run the command : 
sudo docker run -it --device /dev/snd -v /dev/shm:/dev/shm -v /var/lib/dbus:/var/lib/dbus -v /etc/machine-id:/etc/machine-id -e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native -v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native -v ~/.config/pulse/cookie:/root/.config/pulse/cookie --group-adapd $(getent group audio | cut -d: -f3)  [myimage] /bin/bash

Code use to get TextFromSpeech 

 public bool TryGetTextFromSpeech(IAudioConfigWrapper audioInputWrapper, string recognitionLanguage, out string text)
        {
            text = string.Empty;

            var speechConfig = SpeechConfig.FromSubscription(_config.AzureSubscription, _config.AzureRegion);
            speechConfig.SpeechRecognitionLanguage = recognitionLanguage;

            using (var recognizer = new SpeechRecognizer(speechConfig, audioInputWrapper.AudioConfig))
            {
                var result = recognizer.RecognizeOnceAsync().Result;
                audioInputWrapper.Dispose();

                if (result.Reason == ResultReason.RecognizedSpeech)
                {
                    text = result.Text;
                    _logger.LogInformation($"Speech recognized as: '{text}'");
                    return true;
                }

                else if (result.Reason == ResultReason.NoMatch)
                {
                    var details = NoMatchDetails.FromResult(result);

                    switch (details.Reason)
                    {
                        case NoMatchReason.InitialSilenceTimeout:
                            {
                                text = string.Empty;
                                return true;
                            }
                        case NoMatchReason.InitialBabbleTimeout:
                        case NoMatchReason.KeywordNotRecognized:
                        case NoMatchReason.NotRecognized:
                        default:
                            _logger.LogError($"Speech could not be recognized");
                            break;
                    }
                }
                else if (result.Reason == ResultReason.Canceled)
                {
                    var cancellation = CancellationDetails.FromResult(result);
                    _logger.LogError($"Recognition cancelled : Reason={cancellation.Reason}");

                    if (cancellation.Reason == CancellationReason.Error)
                    {
                        _logger.LogError($"Recognition error : ErrorCode={cancellation.ErrorCode}");
                        _logger.LogError($"Recognition error : ErrorDetails={cancellation.ErrorDetails}");
                    }
                }
            }

            return false;
        }

**Expected behavior**
Sound grab from the host. Docker sample would be great.

**Version of the Cognitive Services Speech SDK**
"Microsoft.CognitiveServices.Speech" Version="1.7.0

**Platform, Operating System, and Programming Language**
 - OS: Ubuntu 18.04 
 - Hardware - x64
 - Programming language: netcore 3

**Additional context**
 - Error messages, log information, stack trace, ...
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

2019-11-19 17:15:03.6656|INFO|Program.IAudioGrabber|Started recording for 2000ms. 
2019-11-19 17:15:03.7123|ERROR|Program.SpeechServicesClient|Recognition cancelled : Reason=Error 
2019-11-19 17:15:03.7130|ERROR|Program.SpeechServicesClient|Recognition error : ErrorCode=ConnectionFailure 
2019-11-19 17:15:03.7130|ERROR|Program.SpeechServicesClient|Recognition error : ErrorDetails=Runtime error: Failed to initialize platform (azure-c-shared) SessionId: c2256306e02943b9abf71687c2115ecf 

Ressources : 

FROM https://askubuntu.com/questions/972510/how-to-set-alsa-default-device-to-pulseaudio-sound-server-on-docker?rq=1 

https://stackoverflow.com/questions/45700653/can-my-docker-container-app-access-the-hosts-microphone-and-speaker-mac-wind 

https://superuser.com/questions/1223118/emulating-microphone-input-to-chrome-inside-docker-container

Pulseaudio : https://gavv.github.io/articles/pulseaudio-under-the-hood/

Mutliple container : https://stackoverflow.com/questions/28985714/run-apps-using-audio-in-a-docker-container

**Comment by chrisbasoglu** [comment]
Suggests that the issue is not with the audio input but the network output.  Looks like you are having trouble connecting to the service in the cloud.  Can you shell into into your container, install netcat and do a netcat command to test connectivity? nc -v -z <region>.stt.speech.microsoft.com 443

Please relace <region> with your region.  The result should be: "Connection to <region>.stt.speech.microsoft.com 443 port [tcp/https] succeeded!"

@mradmila, @BrianMouncer

**Comment by cedrox** [comment]
Hello Chris and thanks for your comment !
here's the result of the netcat command : 
Warning: inverse host lookup failed for 51.105.185.107: Unknown host
fe-l-prod5-weu.cris.ai [51.105.185.107] 443 (?) open

Thanks

**Comment by cedrox** [comment]
Erro from speech to text api log 

(329): 26ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  shim_openssl.c:51 libssl could not be loaded 

(329): 26ms SPX_TRACE_ERROR:  trace_message.cpp:192 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/shim_openssl.c Func:load_libssl Line:51  

(329): 26ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:2064 Could not load libssl 

(329): 26ms SPX_TRACE_ERROR:  trace_message.cpp:192 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_init Line:2064  

(329): 27ms SPX_DBG_TRACE_VERBOSE:  exception.cpp:107 About to throw Runtime error: Failed to initialize platform (azure-c-shared)

**Comment by cedrox** [comment]
you need to install downgraded version of libssl for ubuntu 18.04...  
apt-get install libssl1.0-dev 
From : https://stackoverflow.com/questions/51993225/solace-dot-net-core-ssl-issue

**Comment by chrisbasoglu** [comment]
@mradmila can point you to a docker container with python verson of the sdk inside.

**Comment by cedrox** [comment]
Thanks @chrisbasoglu for your prompt help !

**Comment by mradmila** [comment]
As you pointed out, you are missing libssl. Anyway we have a Docker container with the latest Carbon client here: antsu/on-prem-client:latest. This is on Docker hub. Also please look at instructions at https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk.

**Comment by mradmila** [comment]
To be specific, pull the client using: **docker pull antsu/on-prem-client:latest**. Instructions on how to use are here: https://hub.docker.com/r/antsu/on-prem-client.

And for the install instructions, please focus on the prerequisites. On Ubuntu 18.04, run the following:

**sudo apt-get update
sudo apt-get install libssl1.0.0 libasound2**

**Comment by cedrox** [comment]
Sorry, what's the benefit of this version compare to the cognitive-services-speech container ?

**Comment by cedrox** [comment]
Also, Even if I have configured the containers as describe in the documentation :

Note that I have 2 containers and I use port forwarding from 5000 to 5003 for speech to text and 5000 to 5004 for the text to speech version
I still have 
System.ApplicationException: 'Runtime error: Failed parsing http url path' on the dotnet app.

In cognitive service log : 

(994): 29039ms SPX_TRACE_INFO: AZ_LOG_INFO:  uspimpl.cpp:468 connectionUrl=http://192.168.0.121:5003/?language=en-US
(994): 29039ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  transport.cpp:642 Invalid host. Please provide a valid host (ws|wss://hostname[:port][/resource][?query_string]).
(994): 29039ms SPX_TRACE_ERROR:  trace_message.cpp:189 Error: File:D:\a\1\s\source\core\usp\transport.cpp Func:?TransportRequestCreate@USP@Speech@CognitiveServices@Microsoft@@YA?AV?$unique_ptr@UTransportRequest@USP@Speech@CognitiveServices@Microsoft@@U?$default_delete@UTransportRequest@USP@Speech@CognitiveServices@Microsoft@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@6@PEAXPEAUTelemetry@1234@PEAUHTTP_HEADERS_HANDLE_DATA_TAG@@0PEBUProxyServerInfo@@_NPEBD5@Z Line:642 
(229): 29113ms SPX_DBG_TRACE_INFO:  audio_stream_session.cpp:380 Received audio chunk: time: 2019-11-28T17:02:15.4938730Z, size:3200.
(196): 29113ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:272 Microsoft::CognitiveServices::Speech::Impl::CSpxUspRecoEngineAdapter::ProcessAudio: (0x0000023BBBAA05A0) Ignoring audio size=3200 ... (audioState/uspState=0/0)
(196): 29113ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:520 Microsoft::CognitiveServices::Speech::Impl::CSpxAudioStreamSession::ProcessNextAudio: no audio buffer in the m_audioBuffer.
(2): 29143ms SPX_DBG_TRACE_INFO:  audio_stream_session.cpp:380 Received audio chunk: time: 2019-11-28T17:02:15.5240324Z, size:3200.
(994): 29155ms SPX_DBG_TRACE_VERBOSE:  exception.cpp:107 About to throw Runtime error: Failed to create transport request. 
[CALL STACK BEGIN]

    > CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - beginthreadex

    - BaseThreadInitThunk

    - RtlUserThreadStart



[CALL STACK END]


(994): 29156ms SPX_TRACE_ERROR:  usp_reco_engine_adapter.cpp:337 Error: 'Runtime error: Failed to create transport request.'
(994): 29156ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:1699 Response: On Error: Code:5, Message: Runtime error: Failed to create transport request..
(994): 29156ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:2200 Microsoft::CognitiveServices::Speech::Impl::CSpxUspRecoEngineAdapter::ChangeState; audioState/uspState: 1/0 => 1/-1 USP-ERRORERROR
(994): 29156ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:1708 Microsoft::CognitiveServices::Speech::Impl::CSpxUspRecoEngineAdapter::OnError: site->Error() ... error='Runtime error: Failed to create transport request.'
(994): 29156ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1840 Microsoft::CognitiveServices::Speech::Impl::CSpxAudioStreamSession::Error: Creating/firing ResultReason::Canceled result
(994): 29156ms SPX_DBG_TRACE_VERBOSE:  factory_helpers.h:56 Creating object via Microsoft::CognitiveServices::Speech::Impl::SpxFactoryEntryCreateObject: class 



(637): 33671ms SPX_DBG_TRACE_VERBOSE:  exception.cpp:107 About to throw Runtime error: Failed parsing http url path 
[CALL STACK BEGIN]

    > CreateModuleObject

    - CreateModuleObject

    - participant_set_voice_signature

    - CreateModuleObject

    - CreateModuleObject

    - synthesizer_create_speech_synthesizer_from_config

    - 00007FFD9836BB0E (SymFromAddr() error: The specified module could not be found.)

**Comment by cedrox** [comment]
Hello, 
Just want to precise that the web service are perfectly accessible via swagger and a chromium client on http://localhost:5003 - http://localhost:5004.

**Comment by cedrox** [comment]
Just check endpoint if you face this issue :
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-container-howto?tabs=stt%2Ccsharp#query-the-containers-prediction-endpoint

**Comment by jjxtra** [comment]
Seeing issue on Ubuntu 22.04 dedicated server as well, not using docker.

**Comment by TasseDeCafe** [comment]
Getting a similar error too.

**Comment by jjxtra** [comment]
Ended up using open source text to speech. 100x cheaper, no api flakiness and more throughput.

**Comment by DesiKeki** [comment]
> Ended up using open source text to speech. 100x cheaper, no api flakiness and more throughput.

Which text to speech did you use?
