### ISSUE TITLE
android 1.6.0 sdk so error

### ISSUE THREAD

**Issue by wall3001** [Azure-Samples/cognitive-services-speech-sdk#443]
--1st
Use samsung C5000, android 8.1 , microsoft sdk 1.6.0;

1	#00 pc 000000000006a784 /system/lib64/libc.so (tgkill+8) [arm64-v8a]
2	#01 pc 000000000001db50 /system/lib64/libc.so (abort+88) [arm64-v8a]
3	#02 pc 00000000004140cc /system/lib64/libart.so (art::Runtime::Abort(char const*)+528) [arm64-v8a]
4	#03 pc 00000000004147dc /system/lib64/libart.so (art::Runtime::Aborter(char const*)+24) [arm64-v8a]
5	#04 pc 00000000004ffe58 /system/lib64/libart.so (android::base::LogMessage::~LogMessage()+900) [arm64-v8a]
6	#05 pc 0000000000226f98 /system/lib64/libart.so (art::IndirectReferenceTable::AbortIfNoCheckJNI(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)+292) [arm64-v8a]
7	#06 pc 00000000002b6e90 /system/lib64/libart.so (art::JValue art::interpreter::ExecuteSwitchImpl<true, true>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+54248) [arm64-v8a]
8	#07 pc 00000000004402a0 /system/lib64/libart.so (art::Thread::DecodeJObject(_jobject*) const+80) [arm64-v8a]
9	#08 pc 00000000002f21d0 /system/lib64/libart.so (std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, art::JITCodeEntry*>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, art::JITCodeEntry*>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, art::JITCodeEntry*>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, art::JITCodeEntry*> > >::__rehash(unsigned long)+432) [arm64-v8a]
10	#09 pc 00000000000d8e10 /data/app/com.test.microsoft-ZTPURndiJnqXNvDOkVEYow==/lib/arm64/libMicrosoft.CognitiveServices.Speech.java.bindings.so (SwigDirector_SessionEventListener::swig_connect_director(_JNIEnv*, _jobject*, _jclass*, bool, bool)+188) [arm64-v8a]
11	#10 pc 000000000007b964 /data/app/com.test.microsoft-ZTPURndiJnqXNvDOkVEYow==/oat/arm64/base.odex (oatexec+125284) [arm64-v8a]

----- 2nd

null upcall object in CallbackWrapper< Microsoft::CognitiveServices::Speech::SessionEventArgs const & >::Execute

----3rd

#00 pc 000000000006922c /system/lib64/libc.so (pthread_mutex_lock+0) [arm64-v8a]
--
2 #01 pc 00000000005c9a10 /data/app/com.test.microsoft-1/lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so (std::__ndk1::recursive_mutex::lock()+8) [arm64-v8a]
3 #02 pc 00000000001396fc /data/app/com.test.microsoft-1/lib/arm64/libMicrosoft.CognitiveServices.Speech.java.bindings.so (Microsoft::CognitiveServices::Speech::EventSignal<Microsoft::CognitiveServices::Speech::ConnectionEventArgs const&>::DisconnectAll()+48) [arm64-v8a]
4 #03 pc 0000000000101234 /data/app/com.test.microsoft-1/lib/arm64/libMicrosoft.CognitiveServices.Speech.java.bindings.so (Java_com_microsoft_cognitiveservices_speech_internal_carbon_1javaJNI_ConnectionEventSignal_1DisconnectAll+24) [arm64-v8a]
5 #04 pc 00000000000b8790 /system/lib64/libart.so [arm64-v8a]
6 #05 pc 00000000000af468 /system/lib64/libart.so [arm64-v8a]
7 #06 pc 00000000000bbeb0 /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+252) [arm64-v8a]
8 #07 pc 0000000000269bf0 /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+312) [arm64-v8a]
9 #08 pc 0000000000262bcc /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+592) [arm64-v8a]
10 #09 pc 0000000000530dac /system/lib64/libart.so (MterpInvokeStatic+356) [arm64-v8a]
11 #10 pc 00000000000a1d14 /system/lib64/libart.so (ExecuteMterpImpl+14612) [arm64-v8a]
12 java:
13 com.microsoft.cognitiveservices.speech.internal.ConnectionEventSignal.DisconnectAll(ConnectionEventSignal.java)
14 com.microsoft.cognitiveservices.speech.Connection.dispose(Connection.java)
15 com.microsoft.cognitiveservices.speech.Connection.close(Connection.java)

**Comment by wall3001** [comment]
And I have other errors not paste which by use other cellphone.Most of the errors are SIGSEGV(SEGV_MAPERR) .I had found that the ssl certificate couldn't download succeed.It maybe cause some errors.

**Comment by amitkumarshukla** [comment]
@wall3001 which Android sample you are following ?

**Comment by amitkumarshukla** [comment]
@wall3001 are you still facing this issue. Please uninstall and install the app again and see if this issue goes away. If it is still there please provide more info about how to reproduce the issue.
Thanks

**Comment by jhakulin** [comment]
Closing the issue, please repro if you can reproduce the issue still with Speech SDK 1.9.0 version
