### ISSUE TITLE
is it possible to take get the input from mic continuously? (streaming input)

### ISSUE THREAD

**Issue by abdvlz** [Azure-Samples/cognitive-services-speech-sdk#445]

**Comment by jhakulin** [comment]
Thanks for feedback, currently Speech SDK does not provide API to grab mic data from Speech SDK for application, we are planning this feature for future releases.  If your application needs mic data, you can capture it in separately and the stream it using Speech SDK pull or push mode APIs.

**Comment by abdvlz** [comment]
I have made a code that receives the input from mic, if Microsoft is interested please contact me at abdul.zarea@gmail.com, thanks.

**Comment by kknsy** [comment]
@abdvlz  I have been troubled by this problem for a long time. Can you help me ，And it needs to be solved by the authorities as soon as possible，Thank you

**Comment by jhakulin** [comment]
We have item in our backlog and will make the support for audio logging in the future releases.
Thanks for your feedback on this!
