### ISSUE TITLE
Sample for sending MULAW encoding base64 encoded audio stream

### ISSUE THREAD

**Issue by sowsan** [Azure-Samples/cognitive-services-speech-sdk#446]
Hello Team,

I am trying to send base64 encoded audio stream (MULAW) to Azure Speech To Text Service and couldn't find any samples or references for doing the same in C# either using REST or SDK. Hope this should be doable in SDK as I saw the latest release note has support for MULAW encoded audio format. Trying to implement what mentioned here (nodejs) in C# , https://www.twilio.com/blog/live-transcribing-phone-calls-using-twilio-media-streams-and-google-speech-text

**Context**: I am trying stream twilio stream from phone. Seems Twilio supports and integrated with Google Speech To Text and Amazon lexa. Trying to implement a prototype for the same with Azure.

Twilio documentation : https://www.twilio.com/docs/voice/twiml/stream 
"mediaFormat": { 
     "encoding": "audio/x-mulaw", 
     "sampleRate": 8000, 
     "channels": 1 
   } 

You can find more details around their integration and details with AWS and Google here , https://www.twilio.com/blog/media-streams-public-beta 

Thanks for your help!

**Comment by amitkumarshukla** [comment]
@sowsan We have support for MULAW in wav container. Please look at the https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams for more information. Do let us know if this answers your question.

**Comment by sowsan** [comment]
Thank you so much, @amitkumarshukla. Haven't seen that :)

It says we need the gstreamer to work with the encoding. I am going to integrate the SDK code with asp.net core api app. Currently its in my local machine running on windows 10. The documentation talks about installation using sudo, so want to double check does it work with windows? https://gstreamer.freedesktop.org/download/ ,  also is it possible to install it in a docker container ?

Another question, does Speech To Text SDK support GRPC or WebSocket connections from client to azure Speech To Text Service? If so, do I need to enable anything specific as configuration settings?

**Comment by amitkumarshukla** [comment]
@sowsan The sample is shown with pull audio stream but it will work with push audio stream exactly the same way as it works for all the other scenario. please look at this sample https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/cpp/linux/compressed-audio-input 

Currently the compressed stream support is available only on Ubuntu, Android and iOS. We have not yet supported it on windows.

You can install gstreamer and recognize compressed stream on ubuntu docker container.

Speech to text sdk supports Websocket  connections (currently no GRPC). You need to follow the prerequisite from https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/setup-platform?pivots=programming-language-csharp&tabs=dotnet%2Clinux%2Cjre.

Do let me know if this answers your questions

**Comment by sowsan** [comment]
Thanks again for the clarifications and answers, @amitkumarshukla . That helps.

I just want to clarify few more items, what is the diff between pullaudiostream vs pushaudiostream? I theink I am missing some basic concepts around that. 

Thanks, I will set it up in docker. I have followed the prerequisites but didn't find any specific setting for WebSocket and I believe it's not needed and it works behind the scene, right?

Thanks again!

**Comment by amitkumarshukla** [comment]
@sowsan Please look at the https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.audio.pullaudioinputstream?view=azure-dotnet and https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.audio.pushaudioinputstream?view=azure-dotnet

Please follow the following sample to see its usage.

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/Program.cs for understand the different between the pullstream and push stream.

Please focus on the following 
                    case ConsoleKey.D5:
                        SpeechRecognitionSamples.RecognitionWithPullAudioStreamAsync().Wait();
                        break;
                    case ConsoleKey.D6:
                        SpeechRecognitionSamples.RecognitionWithPushAudioStreamAsync().Wait();

Do let me know if this answers your question.

**Comment by pankopon** [comment]
Closing the issue because no update since November, please re-open if still valid.

**Comment by init-asr** [comment]
> @sowsan We have support for MULAW in wav container. Please look at the https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams for more information. Do let us know if this answers your question.

Hi, is this not supported for python yet? If no, is there any work around?
