### ISSUE TITLE
Speaker recognition on Azure home page does not work

### ISSUE THREAD

**Issue by seanfcarroll** [Azure-Samples/cognitive-services-speech-sdk#45]
I'm trying out [this demo](https://azure.microsoft.com/en-us/services/cognitive-services/speaker-recognition/) and it is not working. The spinner is just stuck. When I inspect the page there are js errors. 

<img width="1241" alt="screen shot 2018-09-09 at 18 48 12" src="https://user-images.githubusercontent.com/11340230/45266795-17449c80-b461-11e8-98ce-d5d6b21c9f79.png">

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). Other.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wolfma61** [comment]
Looks like the issue you report is specific to speaker recognition. This repo is specific to the Speech SDK.
You should report this directly, perhaps here? https://docs.microsoft.com/en-us/azure/cognitive-services/speaker-recognition/home
although there might be more direct support links I don't know about.

Wolfgang

**Comment by wolfma61** [comment]
Closing this one, for Speech SDK issues please reopen a new issue.
