### ISSUE TITLE
Python 3.8.0

### ISSUE THREAD

**Issue by zSeriesGuy** [Azure-Samples/cognitive-services-speech-sdk#451]
Trying to pip install azure-cognitiveservices-speech on Windows 10 64-bit with Python 3.8.0 64-bit.
Getting:
  Could not find a version that satisfies the requirement azure-cognitiveservices-speech (from versions: )
No matching distribution found for azure-cognitiveservices-speech

**Comment by jhakulin** [comment]
Thanks for feedback, we are aware of the issue and working on to get support for Python 3.8.0
Please install earlier version of Python 3.7 and let me know if you see still issues.

**Comment by Curious425** [comment]
This is a known issue.
Python  3.8 went public just as we released 1.8 of our SDK.

We looked I to adding support for Python 3.8 in the current release, but at the moment are waiting on Azure hosted agent to support the latest python on all our supported platform, so I do not have an exact ETA for when this will be added, but I hope to see it in the next few releases...

**Comment by zSeriesGuy** [comment]
Thank you. I'll monitor the releases and watch for support.
