### ISSUE TITLE
startKeywordListeningAsync is not working in Android

### ISSUE THREAD

**Issue by KayMKM** [Azure-Samples/cognitive-services-speech-sdk#457]
**Describe the bug**
I am using wake word feature in Android as following:
```
            final KeywordRecognitionModel keywordRecognitionModel = KeywordRecognitionModel.fromStream(assets.open(keywordModel), keyword, true);
            final Future<Void> task = botConnector.startKeywordRecognitionAsync(keywordRecognitionModel);
            setOnTaskCompletedListener(task, result -> {
                LogInfo("KeywordRecognitaionStarted");
            });
```
The result is null when the task completed.

**To Reproduce**
1. ...
2. ...

**Expected behavior**
the keyword recognizer works will. if not, return a meaningful result.

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.
v1.8.0

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - please be specific
 - Hardware - x64, x86, ARM, ...
 - Programming language: C#, C++, Java, JavaScript, Objective-C, Python
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific
Android, Java

**Additional context**
 - Error messages, log information, stack trace, ...
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by jhakulin** [comment]
Thanks for feedback, KWS will be support in Android .aar package in the next 1.9.0 release.
With 1.8.0 release, KWS is supported in Android by Xamarin (C#) through nuget.
You can use KWS also with Android Studio (Java) if you take Android native and managed binaries from 1.8.0 nuget and place those into your Android Studio project. Let us know if you want to do this before 1.9,0 release happens, we can provide detailed information how to do it.

**Comment by KayMKM** [comment]
@jhakulin Thanks for your reply! I think I need to try KWS with 1.8.0 now. It is very helpful if you can provide detailed information!

**Comment by jhakulin** [comment]
@KayMKM please try following:
1. Download Microsoft.CognitiveServices.Speech 1.8.0 Nuget from https://www.nuget.org/packages/Microsoft.CognitiveServices.Speech/  
2. Copy libMicrosoft.CognitiveServices.Speech.extension.kws.so native library from the nuget   \build\monoandroid\libs\<target> directory to your Android Studio \app\src\main\<target> directory (where target could be e.g. arm64-v8a), NOTE: only arm binaries were supported in 1.8.0 release.
3. Build your Android Studio app again

**Comment by KayMKM** [comment]
@jhakulin I had done the following steps, but skill not work. Should I do any changes in code?
1. copy the so file into my app folder:
![image](https://user-images.githubusercontent.com/19773357/70436226-bec8d880-1ac3-11ea-9c62-18ffd1de9df7.png)
2. add 'arm64-v8a' in abiFilters

**Comment by jhakulin** [comment]
@KayMKM In code, you need to integrate KeywordRecognition related methods of the recognizer:
KeywordRecognitionModel.fromFile(GetAssetPath(kwsModelFile));
startKeywordRecognitionAsync(kwsModel);
stopKeywordRecognitionAsync()

Have you done this ?

We will provide Android Studio sample on 1.9.0 release, you can take a look corresponding C# sample for KWS:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/csharp/xamarin/kws-xamarin/kws-xamarin

**Comment by KayMKM** [comment]
@jhakulin Thank you. I will try this sample code. BTW, when will 1.9.0 release?

**Comment by chrisbasoglu** [comment]
Around Jan 10.
