### ISSUE TITLE
Connection failure occurs when using this sdk in China

### ISSUE THREAD

**Issue by haohighview** [Azure-Samples/cognitive-services-speech-sdk#458]
region: Azure.CN chinaeast2

**Version of the Cognitive Services Speech SDK**
1.8.0

**Platform, Operating System, and Programming Language**
 - OS: Xamarin.Android

**Additional context**
ErrorDetails=Connection failed (no connection to the remote host). Internal error: 1. Error details: 7. Please check network connection, firewall setting, and the region name used to create speech factory.

**Comment by jhakulin** [comment]
Thanks for your feedback, currently for Microsoft Cognitive Services Speech SDK, we do not have presence at chinaeast2 region, please see supported regions under the link below:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/regions

How did you create a key for cognitive services speech ? Please use the region name from the link provided in the key creation phase

**Comment by jhakulin** [comment]
Closing as there is proposed resolution, please re-open if you need more information
