### ISSUE TITLE
Fatal error in C# SDK for specific content

### ISSUE THREAD

**Issue by crachmanin** [Azure-Samples/cognitive-services-speech-sdk#459]
**Describe the bug**

When running with the attached clip, the C# SDK encounters a fatal error:
Process finished with exit code -1073740791 (0xC0000409)

**To Reproduce**

Run sample #3 (ContinuousRecognitionWithFileAsync) with the attached repro content.
[repro_content.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/3947464/repro_content.zip)

**Expected behavior**
The transcription should successfully complete.

**Version of the Cognitive Services Speech SDK**
1.8

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - x64
 - Programming language: C#

**Additional context**

Error messages: samples.exe' has exited with code -1073740791 (0xc0000409)

URI used for transcription: "wss://westus.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?initialSilenceTimeoutMs=900000&endSilenceTimeoutMs=900000&language=hi-in"

**Comment by jhakulin** [comment]
Thanks for feedback and details how to repro, we will investigate.

**Comment by jhakulin** [comment]
This issue will be fixed on the next Speech SDK release (1.9.0) around mid Jan 2020.

**Comment by jhakulin** [comment]
Speech SDK release 1.9.0 will be released next week, closing this issue.
