### ISSUE TITLE
Keyword recognition data usage

### ISSUE THREAD

**Issue by BarryOCathain** [Azure-Samples/cognitive-services-speech-sdk#460]
Hi there, this is just a query around the workings of `IntentRecognizer.StartKeywordRecognitionAsync()` in the .net SDK.

I'm trying to understand what level of data is transmitted through the azure services.

I'm writing a custom voice activated home automation client, and deploying a console app on the raspberry pi to act as a listener / responder.

I have a LUIS subscription, and am using the `AddAllIntents()` method.

I assume that the purpose of this approach is to cache the intents locally, and use that to drive intent recognition, is that understanding correct?

Also, I intend to run constant audio recording, while listening for the keyword, so again I assume that loading from the keyword file means that keyword recognition is a local operation, and that transmission of data only really begins at the point of keyword recognition?

I'm not looking for a detailed description of the inner workings of the SDK here, just a general guide on what level of data I'm sending through the services, and what keyword / intent recognition happens locally.

Many thanks.

**Comment by robch** [comment]
Hi Barry. Thanks for your inquiry ... 

Calling `AddAllIntents()` method communicates to us that you'll be using all the intents from the LUIS model. This enables two things under the covers:
1. The speech service will use a pre-built language model to ensure SR accuracy is as good as it can be. This pre-built model will be built from the data you've given to the LUIS service (which you've primarily done to enable the actual act of doing intent recognition and entity extraction). 
2. The speech service will call LUIS (service to service) on your behalf, with the appropriate LUIS model information to allow LUIS to do the actual intent recognition and entity extraction (based on the text the speech service sent to it). 

Yes, calling `StartKeywordAsync` method passing in the keyword model allows the SDK components to **locally** capture audio data and attempt to determine when a user speaks the keyword. If the SDK components running locally detect that it's highly likely that a user spoke the keyword (based on the model loaded), the SDK will then (and only then) start transmitting audio data from the local device to the speech service in the cloud (so it can recognize the text the user speaks). 

Does that answer your question? 

Thanks. -- rob

**Comment by jhakulin** [comment]
Closing this, let us know if you need more information
