### ISSUE TITLE
Xamarin Intent Recognition broken

### ISSUE THREAD

**Issue by SOliasS** [Azure-Samples/cognitive-services-speech-sdk#461]
@jhakulin I was wondering why my speechrecognition wasn't working anymore....

It seems you guys changes something and it broke the xamarin sdk... 

i still get the Text back but no intents or entities....
I tried everything to fix it... created multiple new Ressources in azure and lui created a new lui app,
even tried the new LUIS v3 and still only getting back the Text...
When i try it with the Browser it works fine... so it must be something in the communication with the sdk that broke-.-

**Comment by SOliasS** [comment]
{ResultId:485dfadd111c4a549d661d3607849c66 Reason:RecognizedSpeech IntentId:<> Recognized text:<Lese mir meine Aufgaben vor.> Recognized Json:{"DisplayText":"Lese mir meine Aufgaben vor.","Duration":17200000,"Id":"044fa12fd36842b79f2f98339409f603","NBest":[{"Confidence":0.8916875,"Display":"Lese mir meine Aufgaben vor.","ITN":"lese mir meine aufgaben vor","Lexical":"lese mir meine aufgaben vor","MaskedITN":"Lese mir meine Aufgaben vor"},{"Confidence":0.73007244,"Display":"Lese mir meine Aufgabe vor.","ITN":"lese mir meine aufgabe vor","Lexical":"lese mir meine aufgabe vor","MaskedITN":"Lese mir meine Aufgabe vor"},{"Confidence":0.78380924,"Display":"Lesen sie mir meine Aufgaben vor.","ITN":"lesen sie mir meine aufgaben vor","Lexical":"lesen sie mir meine aufgaben vor","MaskedITN":"Lesen sie mir meine Aufgaben vor"},{"Confidence":0.6790511,"Display":"Lese mir meine Aufgaben Four.","ITN":"lese mir meine aufgaben four","Lexical":"lese mir meine aufgaben four","MaskedITN":"Lese mir meine Aufgaben Four"},{"Confidence":0.6911208,"Display":"Lese dir meine Aufgaben vor.","ITN":"lese dir meine aufgaben vor","Lexical":"lese dir meine aufgaben vor","MaskedITN":"Lese dir meine Aufgaben vor"}],"Offset":6300000,"RecognitionStatus":"Success"}. LanguageUnderstandingJson:}

**Comment by rhurey** [comment]
Well, sorry things aren't working.

Just to make sure I'm looking in the right area, is my understanding of what's happening correct?

You've got a Xamrin app using an intent recognizer that's only recognizing speech.

Can you help me understand what trying it with a browser means? Is it using the Javascript Speech SDK, the LUIS app site, or something else?

**Comment by rhurey** [comment]
Few more questions:
I assume this same code worked previously?
What region is the LUIS app hosted in?

**Comment by rhurey** [comment]
Our service team is looking at a problem in two data centers in Europe, likely related.

**Comment by SOliasS** [comment]
We are using the xamarin sdk, Location ist euwest, in Luis there are snippets for accessing the API that you can simply put in the Browser  trying the api. I also tried accessing it with via Text and the web API in the App with the Same Access  Data which ist working also working fine.

**Comment by SOliasS** [comment]
I tried at 7-15 GMT+1. but i think the error exists since since a few days, but i'm not  sure because i was working on another part of the application...
It's just really strange... since i get the text back and no error...
and calling the api with text is also working fine....

**Comment by rhurey** [comment]
The problem is in the Speech Service failed to call into LUIS in the West Europe region.

When the intent recognizer is used it triggers a service to service call after speech is recognized, but the speech and LUIS messages are returned to the client in separate messages. Normally the client will hold the speech message until the LUIS message arrives, but the Speech Service is ending the recognition without sending the LUIS response so the client forwards what it has.

Why the LUIS response isn’t being sent is under investigation.

**Comment by SOliasS** [comment]
Any Idea how long it gonna take?

**Comment by SOliasS** [comment]
Ok it is working again...
