### ISSUE TITLE
Speech Service integration

### ISSUE THREAD

**Issue by BarryOCathain** [Azure-Samples/cognitive-services-speech-sdk#462]
Hi I couldn't find any samples so I thought I'd ask the question.

Does the Speaker recognition service integrate with an of the speech service SDKs?

Specifically I'm looking to see if I can do speaker recognition alongside speech recognition using the speech sdk?

Many thanks.

**Comment by chrisbasoglu** [comment]
Not directly.  You can however send the audio to both services at the same time, and then wait for the 2 results.  If you are using the microphone, the Speech SDK allows you to switch to use push/pull streams, so you can fork the audio to both services in your app.

**Comment by BarryOCathain** [comment]
So I understand correctly I can have both, services reference the same pull / push audio stream, and use it?

**Comment by chrisbasoglu** [comment]
You can grab data yourself from your Microphone into buffers, then you can push the each buffer to the SpeakerID service, at the same-time you can use the push/pull feature of the Speech SDK to get the same audio buffers to the SR service.
