### ISSUE TITLE
Speech Services Client on docker for Linux | Connection failure | AZ_LOG_ERROR:  uws_client.c:2068 xio_setoption failed.

### ISSUE THREAD

**Issue by cedrox** [Azure-Samples/cognitive-services-speech-sdk#463]
Hello, 
I have a new connection failure with speech to text cognitive service local container.
The netcat don't work : nc -v -z westeurope.stt.speech.microsoft.com 443

I already have some trouble before : https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/441 but I manadge to get it work thank to your advice. Seems that the config is the same...

**Platform, Operating System, and Programming Language**
 - OS: Ubuntu 18.04
 - Hardware - x64, 
 - Programming language: C#, 

**Additional context**
Here's the logs :

(420): 77179ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:90 TrackHandle type=Microsoft::CognitiveServices::Speech::Impl::CSpxAsyncOp<void> handle=0x0x7fbc74007450, ptr=0x0x7fbc74007450, total=2
(343): 77179ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:190 SetFormat: this=0x0x7fbc0c0047c0
(343): 77179ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:201 SetFormat
  wFormatTag:      PCM
  nChannels:       1
  nSamplesPerSec:  16000
  nAvgBytesPerSec: 32000
  nBlockAlign:     2
  wBitsPerSample:  16
  cbSize:          0
(343): 77179ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:2235 ChangeState; audioState/uspState: 0/0 => 1/0 USP-START
(343): 77179ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:223 SetFormat: (0x0x7fbc0c0047c0)->PrepareFirstAudioReadyState()
(343): 77179ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:2325 ResetBeforeFirstAudio: this=0x0x7fbc0c0047c0 ... USP-RESET
(343): 77179ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:297 UspInitialize: this=0x0x7fbc0c0047c0
(343): 77179ms SPX_DBG_TRACE_VERBOSE:  factory_helpers.h:56 Creating object via SpxFactoryEntryCreateObject: Microsoft::CognitiveServices::Speech::Impl::CSpxUspCallbackWrapper as Microsoft::CognitiveServices::Speech::Impl::ISpxUspCallbacks
(343): 77179ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1264 GetScenarioCount: countSpeech=1; countIntent=0; countTranslation=0; countDialog=0, countTranscriber=0
(343): 77179ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0x7fbc2000c570; name='SPEECH-Endpoint'; value='ws://localhost:5003/speech/recognition/interactive/cognitiveservices/v1'
(343): 77179ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:400 SetUspEndpoint: Using Custom endpoint: ws://localhost:5003/speech/recognition/interactive/cognitiveservices/v1
(343): 77180ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0xf335d8; name='SPEECH-UserDefinedQueryParameters'; value=''
(343): 77180ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:559 SetUspEndpointDefaultSpeechService: Endpoint type: Speech.
(343): 77180ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0xf335d8; name='SPEECH-Region'; value=''
(343): 77180ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0x7fbc2000c570; name='SPEECH-RecoLanguage'; value='en-US'
(343): 77180ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0xf335d8; name='SpeechServiceResponse_RequestWordLevelTimestamps'; value=''
(343): 77180ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0xf335d8; name='SpeechServiceResponse_OutputFormatOption'; value=''
(343): 77180ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0xf335d8; name='SpeechServiceResponse_RequestDetailedResultTrueFalse'; value=''
(343): 77180ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0x7fbc2000c570; name='SPEECH-RecoLanguage'; value='en-US'
(343): 77180ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0x7fbc2005b6d8; name='SPEECH-RecoMode'; value='INTERACTIVE'
(343): 77180ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:467 SetUspRecoMode: recoMode=0
(343): 77180ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0xf335d8; name='SPEECH-USPPollingInterval'; value=''
(343): 77180ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:450 SetUspEndpoint: Setting Websocket Polling interval to 10
(343): 77180ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0xf335d8; name='SPEECH-SubscriptionKey'; value=''
(343): 77180ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0xf335d8; name='SPEECH-AuthToken'; value=''
(343): 77180ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0xf335d8; name='SPEECH-RpsToken'; value=''
(343): 77180ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0xf335d8; name='DIALOG-ApplicationId'; value=''
(343): 77181ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0xf335d8; name='OPENSSL_SINGLE_TRUSTED_CERT'; value=''
(343): 77181ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0xf335d8; name='SPEECHSDK-SPEECH-CONFIG-OS'; value=''
(343): 77181ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0x7fbc2000c570; name='SPEECHSDK-SPEECH-CONFIG-SYSTEM-LANGUAGE'; value='C#'
(343): 77181ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0x7fbc2005b6d8; name='AudioConfig_AudioSource'; value='Microphones'
(343): 77181ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0x7fbc2005b6d8; name='SPEECH-MicrophoneNiceName'; value='SEEED ReSpeaker 4 Mic Array (UAC1.0) at usb-0000:00:14.0-1, full speed'
(343): 77181ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0x7fbc2005b6d8; name='AudioConfig_SampleRateForCapture'; value='16000'
(343): 77181ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0x7fbc2005b6d8; name='AudioConfig_BitsPerSampleForCapture'; value='16'
(343): 77181ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0x7fbc2005b6d8; name='AudioConfig_NumberOfChannelsForCapture'; value='1'
(343): 77181ms SPX_TRACE_INFO: AZ_LOG_INFO:  uspimpl.cpp:467 Connect: entering...
(343): 77181ms SPX_TRACE_INFO: AZ_LOG_INFO:  uspimpl.cpp:549 connectionUrl=ws://localhost:5003/speech/recognition/interactive/cognitiveservices/v1?language=en-US
(990): 77181ms SPX_DBG_TRACE_INFO:  audio_stream_session.cpp:391 Received audio chunk: time: 2019-12-12T18:46:08.6803678Z, size:464.
(990): 77181ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:474 [0x7fbc2005b650]CSpxAudioStreamSession::SlowDownThreadIfNecessary: Stashing ... sleeping for 6 ms
(343): 77181ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  uws_client.c:2068 xio_setoption failed.
(343): 77181ms SPX_TRACE_ERROR:  trace_message.cpp:192 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/src/uws_client.c Func:uws_client_set_option Line:2068 
(343): 77181ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  uws_client.c:2068 xio_setoption failed.
(343): 77181ms SPX_TRACE_ERROR:  trace_message.cpp:192 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/src/uws_client.c Func:uws_client_set_option Line:2068 
(343): 77181ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  uws_client.c:2068 xio_setoption failed.
(343): 77181ms SPX_TRACE_ERROR:  trace_message.cpp:192 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/src/uws_client.c Func:uws_client_set_option Line:2068 
(505): 77181ms SPX_DBG_TRACE_INFO:  audio_stream_session.cpp:391 Received audio chunk: time: 2019-12-12T18:46:08.6806327Z, size:464.
(224): 77181ms SPX_DBG_TRACE_WARNING: audio_stream_session.cpp:542 [0x7fbc4406a410]CSpxAudioStreamSession::ProcessNextAudio: Unexpected SessionState: recoKind 2; sessionState 5
(343): 77181ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 LogPropertyAndValue: this=0x0x7fbc2005b6d8; name='SPEECH-ConnectionUrl'; value='ws://localhost:5003/speech/recognition/interactive/cognitiveservices/v1?language=en-US'
(343): 77181ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:977 speech.config {"context":{"audio":{"source":{"bitspersample":"16","channelcount":"1","model":"SEEED ReSpeaker 4 Mic Array (UAC1.0) at usb-0000:00:14.0-1, full speed","samplerate":"16000","type":"Microphones"}},"os":{"name":"Linux 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64","platform":"Linux","version":"5.0.0-37-generic"},"system":{"build":"Linux-x64","lang":"C#","name":"SpeechSDK","version":"1.8.0"}}}
(505): 77181ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:474 [0x7fbc4406a410]CSpxAudioStreamSession::SlowDownThreadIfNecessary: Stashing ... sleeping for 6 ms
(343): 77181ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:1041 speech.config='{"context":{"audio":{"source":{"bitspersample":"16","channelcount":"1","model":"SEEED ReSpeaker 4 Mic Array (UAC1.0) at usb-0000:00:14.0-1, full speed","samplerate":"16000","type":"Microphones"}},"os":{"name":"Linux 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64","platform":"Linux","version":"5.0.0-37-generic"},"system":{"build":"Linux-x64","lang":"C#","name":"SpeechSDK","version":"1.8.0"}}}'
(343): 77181ms SPX_TRACE_INFO: AZ_LOG_INFO:  uspimpl.cpp:740 Create requestId  for messageType 0
(343): 77181ms SPX_DBG_TRACE_SCOPE_EXIT:  usp_reco_engine_adapter.cpp:189 SetFormat
(343): 77181ms SPX_DBG_TRACE_SCOPE_EXIT:  audio_stream_session.cpp:2361 InformAdapterSetFormatStarting
(343): 77181ms SPX_DBG_TRACE_SCOPE_EXIT:  audio_stream_session.cpp:2290 HotSwapAdaptersWhilePaused

**Comment by cedrox** [comment]
The error is : 
**(343): 77181ms SPX_TRACE_ERROR: AZ_LOG_ERROR: uws_client.c:2068 xio_setoption failed.
(343): 77181ms SPX_TRACE_ERROR: trace_message.cpp:192 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/src/uws_client.c Func:uws_client_set_option Line:2068
(343): 77181ms SPX_TRACE_ERROR: AZ_LOG_ERROR: uws_client.c:2068 xio_setoption failed.
(343): 77181ms SPX_TRACE_ERROR: trace_message.cpp:192 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/src/uws_client.c Func:uws_client_set_option Line:2068
(343): 77181ms SPX_TRACE_ERROR: AZ_LOG_ERROR: uws_client.c:2068 xio_setoption failed.
(343): 77181ms SPX_TRACE_ERROR: trace_message.cpp:192 Error:**

**Comment by cedrox** [comment]
I have other kind of error :
(23): 82975ms SPX_TRACE_INFO: AZ_LOG_INFO:  transport.cpp:769 Start to open websocket. TransportRequest: 0x2c0052c0, wsio handle: 0x2c001270
(23): 82975ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  socketio_berkeley.c:710 Failure: connect failure 111.
(23): 82975ms SPX_TRACE_ERROR:  trace_message.cpp:192 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/socketio_berkeley.c Func:socketio_open Line:710 
(23): 82975ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  transport.cpp:364 WS open operation failed with result=1(WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED), code=111[0x0000006f]
(23): 82975ms SPX_TRACE_ERROR:  trace_message.cpp:192 Error: File:/home/vsts/work/1/s/source/core/usp/transport.cpp Func:OnWSOpened Line:364 
(23): 82975ms SPX_TRACE_INFO: AZ_LOG_INFO:  uspimpl.cpp:890 TS:1, TransportError: connection:0x2c004000, reason=2, code=1 [0x00000001], string=111
(23): 82975ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:1732 Response: On Error: Code:5, Message: Connection failed (no connection to the remote host). Internal error: 1. Error details: 111. Please check network connection, firewall setting, and the region name used to create speech factory..
(23): 82975ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:2235 ChangeState; audioState/uspState: 1/0 => 1/-1 USP-ERRORERROR
(23): 82975ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:1741 OnError: site->Error() ... error='Connection failed (no connection to the remote host). Internal error: 1. Error details: 111. Please check network connection, firewall setting, and the region name used to create speech factory.'
(23): 82975ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1856 Error: Creating/firing ResultReason::Canceled result
(23): 82975ms SPX_DBG_TRACE_VERBOSE:  factory_helpers.h:56 Creating object via SpxFactoryEntryCreateObject: Microsoft::CognitiveServices::Speech::Impl::CSpxRecognitionResult as Microsoft::CognitiveServices::Speech::Impl::ISpxRecognitionResult
(23): 82975ms SPX_DBG_TRACE_FUNCTION:  recognition_result.cpp:22 CSpxRecognitionResult

**Comment by cedrox** [comment]
It was working one week ago. Have you release something recently ?

**Comment by rhurey** [comment]
The latest SDK release was on 11/2. 

The last error you hit was an internal state where close was called on a null connection. I suspect that's fallout from some other connection error and an unfortunate overwriting of the real error.

As for the connect error, the only places where there's 3 calls to xio_setoption in a row are all configuring TLS, which should either be ignored or not done since you're connecting with ws://. I'm investigating what's going on.

Thanks for the log, btw. Super helpful.

**Comment by rhurey** [comment]
And the xio_setoption errors are spurious and don't block connections from happening. Setup a container and confirmed.

I see you're connecting to port 5003, I assume you changed the default port from 5000, but want to make sure that's the case.

**Comment by cedrox** [comment]
Hello and thanks a lot for studding this case !
Yes I use the port forwarding from host 5003 to container 5000 as I use more than One container. It work perfectly when I try to access my container from my local dev machine. Don't work when our custom app is deployed on the same docker host than the cognitive services containers.
Anything else : we are using Azure Iot Hub and Iot Edge for deployement.
Thanks

**Comment by cedrox** [comment]
Hello, I have now error on my Windows dev machine like : 

(708): 35150ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  socketio_win32.c:313 Failure: connect failure 10060.
(708): 35150ms SPX_TRACE_ERROR:  trace_message.cpp:192 Error: File:D:\a\1\s\external\azure-c-shared-utility\adapters\socketio_win32.c Func:socketio_open Line:313 
(708): 35150ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  transport.cpp:364 WS open operation failed with result=1(WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED), code=10060[0x0000274c]
(708): 35150ms SPX_TRACE_ERROR:  trace_message.cpp:192 Error: File:D:\a\1\s\source\core\usp\transport.cpp Func:?OnWSOpened@@YAXPEAXU_WS_OPEN_RESULT_DETAILED@@@Z Line:364 
(708): 35150ms SPX_TRACE_INFO: AZ_LOG_INFO:  uspimpl.cpp:890 TS:21001, TransportError: connection:0xda2c4e50, reason=2, code=1 [0x00000001], string=10060
(708): 35151ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:1732 Response: On Error: Code:5, Message: Connection failed (no connection to the remote host). Internal error: 1. Error details: 10060. Please check network connection, firewall setting, and the region name used to create speech factory..
(708): 35151ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:2235 Microsoft::CognitiveServices::Speech::Impl::CSpxUspRecoEngineAdapter::ChangeState; audioState/uspState: 1/0 => 1/-1 USP-ERRORERROR
(708): 35151ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:1741 Microsoft::CognitiveServices::Speech::Impl::CSpxUspRecoEngineAdapter::OnError: site->Error() ... error='Connection failed (no connection to the remote host). Internal error: 1. Error details: 10060. Please check network connection, firewall setting, and the region name used to create speech factory.'
(708): 35151ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1856 Microsoft::CognitiveServices::Speech::Impl::CSpxAudioStreamSession::Error: Creating/firing ResultReason::Canceled result
(708): 35151ms SPX_DBG_TRACE_VERBOSE:  factory_helpers.h:56 Creating object via Microsoft::CognitiveServices::Speech::Impl::SpxFactoryEntryCreateObject: class Microsoft::CognitiveServices::Speech::Impl::CSpxRecognitionResult as class Microsoft::CognitiveServices::Speech::Impl::ISpxRecognitionResult
(708): 35151ms SPX_DBG_TRACE_FUNCTION:  recognition_result.cpp:22 Microsoft::CognitiveServices::Speech::Impl::CSpxRecognitionResult::CSpxRecognitionResult
(708): 35151ms SPX_DBG_TRACE_VERBOSE:  create_object_helpers.h:51 Microsoft::CognitiveServices::Speech::Impl::SpxCreateObjectWithSite: Attempted SetSite(CSpxRecognitionResult), objectWithSite==nullptr
(708): 35151ms SPX_DBG_TRACE_FUNCTION:  recognition_result.cpp:80 Microsoft::CognitiveServices::Speech::Impl::CSpxRecognitionResult::InitFinalResult
(708): 35151ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119 Microsoft::CognitiveServices::Speech::Impl::ISpxPropertyBagImpl::LogPropertyAndValue: this=0x0000021BDA35C420; name='RESULT-ErrorDetails'; value='Connection failed (no connection to the remote host). Internal error: 1. Error details: 10060. Please check network connection, firewall setting, and the region name used to create speech factory.'
(708): 35151ms SPX_DBG_TRACE_VERBOSE:  recognition_result.cpp:104 Microsoft::CognitiveServices::Speech::Impl::CSpxRecognitionResult::InitFinalResult: resultId=e5ad569192b94c479ba9bca56c6a80f6 reason=1, cancellationReason=1, text=''
(708): 35151ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1003 [0000021BD9AC0280]CSpxAudioStreamSession::WaitForRecognition_Complete: ...
(708): 35151ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1091 [0000021BD9AC0280]CSpxAudioStreamSession::FireResultEvent
(708): 35151ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:119

**Comment by cedrox** [comment]
Hello, here's some new logs :

(412): 204473ms SPX_DBG_TRACE_SCOPE_ENTER:  audio_stream_session.cpp:114 Term
(412): 204473ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:115 [0xf4dc00]CSpxAudioStreamSession::Term:...
(412): 204473ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:2538 [0xf4dc00]CSpxAudioStreamSession::ChangeState:  recoKind/sessionState: 2/1 != 2/5
(412): 204473ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:2538 [0xf4dc00]CSpxAudioStreamSession::ChangeState:  recoKind/sessionState: 2/2 != 2/5
(412): 204473ms SPX_DBG_TRACE_ERROR:  audio_stream_session.cpp:141 [0xf4dc00]CSpxAudioStreamSession::Term: **NOT CALLED** StopPump[0x7f250c018bb8] - state: 5
(654): 204473ms SPX_DBG_TRACE_FUNCTION:  recognition_result.cpp:27 ~CSpxRecognitionResult
(412): 204473ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:167 [0xf4dc00]CSpxAudioStreamSession::CancelPendingSingleShot
(412): 204473ms SPX_DBG_TRACE_VERBOSE:  create_object_helpers.h:79 SpxTerm: ptr=0x0x7f250c018bb8
(412): 204473ms SPX_DBG_TRACE_VERBOSE:  create_object_helpers.h:79 SpxTerm: ptr=0x0x7f24fc006740
(53): 204473ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  audio_sys.c:1110 error from snd_pcm_readi: Input/output error
(412): 204473ms SPX_DBG_TRACE_SCOPE_ENTER:  microphone_pump_base.cpp:32 ~CSpxMicrophonePumpBase
(53): 204473ms SPX_TRACE_ERROR:  trace_message.cpp:192 Error: File:/home/vsts/work/1/s/source/core/audio/linux/audio_sys.c Func:CaptureAudio Line:1110
(53): 204473ms SPX_DBG_TRACE_SCOPE_ENTER:  microphone_pump_base.cpp:174 MicrophonePumpBase::UpdateState() ...
(412): 204473ms SPX_DBG_TRACE_SCOPE_EXIT:  microphone_pump_base.cpp:32 ~CSpxMicrophonePumpBase
(53): 204473ms SPX_DBG_TRACE_VERBOSE:  microphone_pump_base.cpp:178 UpdateState: UpdateState with state as 4.
(692): 204473ms SPX_DBG_TRACE_INFO:  audio_stream_session.cpp:391 Received audio chunk: time: 2019-12-17T15:49:17.9332581Z, size:464.
(53): 204474ms SPX_DBG_TRACE_SCOPE_EXIT:  microphone_pump_base.cpp:174 MicrophonePumpBase::UpdateState ... Done!
(412): 204473ms SPX_DBG_TRACE_VERBOSE:  create_object_helpers.h:79 SpxTerm: ptr=0x0x7f24dc000e18
(692): 204474ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  lock_pthreads.c:50 pthread_mutex_lock failed.
(692): 204474ms SPX_TRACE_ERROR:  trace_message.cpp:192 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/lock_pthreads.c Func:Lock Line:50
(692): 204474ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  lock_pthreads.c:77 pthread_mutex_unlock failed.
(692): 204474ms SPX_TRACE_ERROR:  trace_message.cpp:192 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/lock_pthreads.c Func:Unlock Line:77
(412): 204474ms SPX_DBG_TRACE_VERBOSE:  create_object_helpers.h:79 SpxTerm: ptr=0x0x7f24dc066768
(412): 204474ms SPX_DBG_TRACE_SCOPE_ENTER:  usp_reco_engine_adapter.cpp:69 Terminating CSpxUspRecoEngineAdapter...
(412): 204474ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:70 Term: this=0x0x7f24dc066720
(412): 204474ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:2235 ChangeState; audioState/uspState: 2/-1 => 2/9998 USP-TERMINATING
(412): 204474ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:74 Term: Terminating USP Connection (0x0x7f24dc067820)
(412): 204474ms SPX_DBG_TRACE_VERBOSE:  create_object_helpers.h:79 SpxTerm: ptr=0x0x7f24dc066b28
(412): 204474ms SPX_TRACE_INFO: AZ_LOG_INFO:  transport.cpp:117 ~TransportRequest: destroying uwsclient.
(412): 204474ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:2235 ChangeState; audioState/uspState: 2/9998 => 2/9999 USP-ZOMBIE
(412): 204474ms SPX_DBG_TRACE_SCOPE_EXIT:  usp_reco_engine_adapter.cpp:69 Terminating CSpxUspRecoEngineAdapter... Done!
(412): 204474ms SPX_DBG_TRACE_VERBOSE:  create_object_helpers.h:79 SpxTerm: ptr=0x0x7f250c04d738
(412): 204474ms SPX_DBG_TRACE_SCOPE_ENTER:  usp_reco_engine_adapter.cpp:47 ~CSpxUspRecoEngineAdapter
(412): 204474ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:48 ~CSpxUspRecoEngineAdapter: this=0x0x7f24dc066720
(412): 204474ms SPX_DBG_TRACE_SCOPE_EXIT:  usp_reco_engine_adapter.cpp:47 ~CSpxUspRecoEngineAdapter

**Comment by cedrox** [comment]
Hello I try to use 
_speechConfigTextToSpeech = SpeechConfig.**FromHost**(new Uri(_config.HostTextToSpeech));
_speechConfigSpeechToText = SpeechConfig.**FromHost**(new Uri(_config.HostSpeechToText));
and 
_speechConfigTextToSpeech = SpeechConfig.**FromEndpoint**(new Uri(_config.HostTextToSpeech));
 _speechConfigSpeechToText = SpeechConfig.**FromEndpoint**(new Uri(_config.HostSpeechToText));

with different flavour of  url endpoint :
ws://192.168.0.121:5008
http://192.168.0.121:5004

http://192.168.0.30:5004/speech/synthesize/cognitiveservices/v1
ws://192.168.0.30:5008/speech/recognition/interactive/cognitiveservices/v1

But still having trouble to connect from my custom app container. Do I need to pass some parameter to my container app ? do I need to open a port ?

Thanks

**Comment by rhurey** [comment]
Let's step back for a minute....

Can you help me understand what the deployment / goal you have here? Not just of the speech containers, but what the audio source is, and how it's connected.

Can you send a full log for one recognition attempt?

**Comment by cedrox** [comment]
Ok, look like we mix api key with non speech cognitive service. 
Please be careful about : 
**1. Voice** 
_Error_ : 
HTTPAPI result code = HTTPAPI_OK. HTTP status code = 400. Reason:  Synthesis failed. StatusCode: InvalidArgument, Details: Voice does not match..
_Reponse_ : 
You have to use en-US-JessaRUS
en-US-JessaNeural is not available right now in container version of text to speech


**2. cognitive service type **
_Error :_
{"code":"InvalidProductId","message":"The subscription SKU \"CognitiveServices.S0\" is not supported in this service instance."}
_Reponse_ :
Need to create a speech ressource (not a cognitive service one)


**3. Model version**
_Error_
Failed to fetch manifest: Status: 400 Bad Request Body: {"code":"InvalidModel","message":"The specified model is not supported for endpoint manifests."}
_Response_: 
Support model > 20190220 (v4.5 Unified)

**Comment by rhurey** [comment]
Well, sorry our key story is complicated. :-(
