### ISSUE TITLE
SDK ERROR : SPXERR_INVALID_ARG

### ISSUE THREAD

**Issue by cedrox** [Azure-Samples/cognitive-services-speech-sdk#466]
**Describe the bug**
When we try to output form speech-to-text, we have an random error. What does it mean ?

**To Reproduce**
random error. 

**Expected behavior**
output the audio

**Version of the Cognitive Services Speech SDK**
1.8

**Platform, Operating System, and Programming Language**
ubuntu 18.04 with docker 

**Additional context**
terminate called after throwing an instance of 'Microsoft::CognitiveServices::Speech::Impl::ExceptionWithCallStack'
  what():  Exception with an error code: 0x5 (SPXERR_INVALID_ARG)

**Comment by rhurey** [comment]
Any chance I could get the full log, or the call stack with that error from it?

It means something inside the SDK got an invalid argument passed, but not sure what.

**Comment by yulin-li** [comment]
You can refer [this](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging) to enable logging of the the sdk and share the log with us, so we can help to diagnose.

**Comment by cedrox** [comment]
Thanks for your answer !
I would do so but for now I couldn't reproduce. I will re open this case if needed.
Thanks

**Comment by cedrox** [comment]
Hello, 
Here's log file (SPXERR_INVALID_ARG is **bold**)


(49): 542448ms SPX_DBG_TRACE_SCOPE_ENTER:  recognizer.cpp:244 FireResultEvent
(278): 542448ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:2538 [0x7f7f50001cb0]CSpxAudioStreamSession::ChangeState:  recoKind/sessionState: 2/2 != 2/5
(49): 542448ms SPX_DBG_TRACE_VERBOSE:  recognizer.cpp:260 FireResultEvent: No FinalResult event signal connected!! nobody listening...
(278): 542448ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:2538 [0x7f7f50001cb0]CSpxAudioStreamSession::ChangeState:  recoKind/sessionState: 2/2 != 2/5
(49): 542448ms SPX_DBG_TRACE_SCOPE_EXIT:  recognizer.cpp:244 FireResultEvent
(278): 542448ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:982 [0x7f7f50001cb0]CSpxAudioStreamSession::StopRecognizing: Now (still) WaitForAdapterCompletedSetFormatStop ...
(278): 542448ms SPX_DBG_TRACE_SCOPE_EXIT:  audio_stream_session.cpp:898 StopRecognizing
(278): 542448ms SPX_DBG_TRACE_SCOPE_EXIT:  usp_reco_engine_adapter.cpp:2168 FireFinalResultNow: GetSite()->FireAdapterResult_FinalResult()  complete!
(278): 542448ms SPX_TRACE_INFO: AZ_LOG_INFO:  uspimpl.cpp:1173 Response Message: content type: application/json; charset=utf-8.
(278): 542448ms SPX_TRACE_INFO: AZ_LOG_INFO:  uspimpl.cpp:1179 TS:11016 Response Message: path: turn.end, size: 2.
(278): 542448ms SPX_DBG_TRACE_VERBOSE:  uspimpl.cpp:1242 Got turn end, clear m_streamIdLangMap.
(278): 542448ms SPX_TRACE_INFO: AZ_LOG_INFO:  metrics.cpp:426 SendSerializedTelemetry: Send telemetry (requestId:acd42a2cebfb48cc953bb96b499e07b2): {"Metrics":[{"End":"2020-01-06T13:35:21.651Z","Id":"1cb10332ff084e3a8c10979482647792","Name":"Connection","Start":"2020-01-06T13:35:21.642Z"},{"DeviceId":["57e0b2df-6b6f-4b8f-9402-4b55f5f7b3ae"],"Name":"device"}],"ReceivedMessages":[]}
(278): 542448ms SPX_TRACE_INFO: AZ_LOG_INFO:  metrics.cpp:426 SendSerializedTelemetry: Send telemetry (requestId:acd42a2cebfb48cc953bb96b499e07b2): {"Metrics":[{"PhraseLatencyMs":[8513]},{"FirstHypothesisLatencyMs":[1526]}],"ReceivedMessages":[{"turn.start":["2020-01-06T13:35:21.662Z"]},{"turn.end":["2020-01-06T13:35:32.656Z"]},{"speech.startDetected":["2020-01-06T13:35:21.954Z"]},{"speech.endDetected":["2020-01-06T13:35:32.655Z"]},{"speech.hypothesis":["2020-01-06T13:35:22.593Z","2020-01-06T13:35:22.989Z","2020-01-06T13:35:26.408Z"]},{"speech.phrase":["2020-01-06T13:35:32.655Z"]}]}
(278): 542449ms SPX_DBG_TRACE_SCOPE_ENTER:  usp_reco_engine_adapter.cpp:1615 CSpxUspRecoEngineAdapter::OnTurnEnd ... started... 
(278): 542449ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:1616 Response: Turn.End message.
(278): 542449ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:2235 ChangeState; audioState/uspState: 9/2999 => 9/0 
(278): 542449ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:1668 OnTurnEnd: site->AdapterStoppedTurn()
(278): 542449ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1337 [0x7f7f50001cb0]CSpxAudioStreamSession::AdapterStoppedTurn: m_currentTurnGlobalOffset=39700000, previousTurnGlobalOffset=0 bufferedBytes=241888
(278): 542449ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1383 [0x7f7f50001cb0]CSpxAudioStreamSession::AdapterStoppedTurn: Still WaitForAdapterCompletedSetFormatStop, calling ->SetFormat(nullptr) ...
(278): 542449ms SPX_DBG_TRACE_SCOPE_ENTER:  audio_stream_session.cpp:2409 InformAdapterSetFormatStopping
(278): 542449ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:2428 [0x7f7f50001cb0]CSpxAudioStreamSession::InformAdapterSetFormatStoppingSetFormat(nullptr)
(278): 542449ms SPX_DBG_TRACE_SCOPE_ENTER:  usp_reco_engine_adapter.cpp:189 SetFormat
(278): 542449ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:190 SetFormat: this=0x0x7f7fa0000920
(278): 542449ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:192 SetFormat - pformat == nullptr
(278): 542449ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:2235 ChangeState; audioState/uspState: 9/0 => 0/0 USP-DONE
(278): 542449ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:228 SetFormat: (0x0x7f7fa0000920) site->AdapterCompletedSetFormatStop()
(278): 542449ms SPX_DBG_TRACE_SCOPE_ENTER:  audio_stream_session.cpp:2450 *** CSpxAudioStreamSession::AdapterCompletedSetFormatStop kicked-off THREAD started ***
(278): 542449ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:2451 [0x7f7f50001cb0]CSpxAudioStreamSession::AdapterCompletedSetFormatStop: kicked-off THREAD started ***
(278): 542449ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:2528 [0x7f7f50001cb0]CSpxAudioStreamSession::ChangeState: recoKind/sessionState: 2/5 => 1/2
(278): 542449ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:2455 [0x7f7f50001cb0]CSpxAudioStreamSession::AdapterCompletedSetFormatStop: KwsSingleShot Waiting for done ... Done!! Switching back to Keyword/Processing
(454): 542449ms SPX_DBG_TRACE_SCOPE_EXIT:  audio_stream_session.cpp:620 WaitForIdle
(278): 542449ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:2456 [0x7f7f50001cb0]CSpxAudioStreamSession::AdapterCompletedSetFormatStop: Now Keyword/ProcessingAudio ...
(278): 542449ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1035 [0x7f7f50001cb0]CSpxAudioStreamSession::FireSessionStoppedEvent: Firing SessionStopped event: SessionId: 1cb10332ff084e3a8c10979482647792
(278): 542449ms SPX_DBG_TRACE_SCOPE_ENTER:  audio_stream_session.cpp:1072 EnsureFireResultEvent
(278): 542449ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1073 [0x7f7f50001cb0]CSpxAudioStreamSession::EnsureFireResultEvent
(278): 542449ms SPX_DBG_TRACE_SCOPE_EXIT:  audio_stream_session.cpp:1072 EnsureFireResultEvent
(293): 542449ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:130 StopTracking handle=0x0x7f7f50018950
(278): 542449ms SPX_DBG_TRACE_SCOPE_EXIT:  audio_stream_session.cpp:2450 *** CSpxAudioStreamSession::AdapterCompletedSetFormatStop kicked-off THREAD stopped ***
(293): 542449ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:140 StopTracking type=Microsoft::CognitiveServices::Speech::Impl::CSpxAsyncOp<void> handle=0x0x7f7f50018950, ptr=0x0x7f7f50018950, total=0
(278): 542449ms SPX_DBG_TRACE_SCOPE_EXIT:  usp_reco_engine_adapter.cpp:189 SetFormat
(293): 542449ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:130 StopTracking handle=0x0x7f7f50019d30
(49): 542449ms SPX_DBG_TRACE_VERBOSE:  factory_helpers.h:56 Creating object via SpxFactoryEntryCreateObject: Microsoft::CognitiveServices::Speech::Impl::CSpxSessionEventArgs as Microsoft::CognitiveServices::Speech::Impl::ISpxSessionEventArgs
(278): 542449ms SPX_DBG_TRACE_SCOPE_EXIT:  audio_stream_session.cpp:2409 InformAdapterSetFormatStopping
(293): 542449ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:140 StopTracking type=Microsoft::CognitiveServices::Speech::Impl::ISpxRecognizer handle=0x0x7f7f50019d30, ptr=0x0x7f7f50019d30, total=9
(278): 542449ms SPX_DBG_TRACE_SCOPE_EXIT:  usp_reco_engine_adapter.cpp:1615 CSpxUspRecoEngineAdapter::OnTurnEnd ... DONE!
(49): 542449ms SPX_DBG_TRACE_VERBOSE:  create_object_helpers.h:51 SpxCreateObjectWithSite: Attempted SetSite(CSpxSessionEventArgs), objectWithSite==nullptr
(49): 542449ms SPX_DBG_TRACE_SCOPE_ENTER:  recognizer.cpp:29 ~CSpxRecognizer
(49): 542449ms SPX_DBG_TRACE_SCOPE_ENTER:  recognizer.cpp:330 TermDefaultSession
(49): 542449ms SPX_DBG_TRACE_FUNCTION:  audio_stream_session.cpp:570 RemoveRecognizer
(49): 542449ms SPX_DBG_TRACE_VERBOSE:  create_object_helpers.h:79 SpxTerm: ptr=0x0x7f7f50001cf0
(49): 542449ms SPX_DBG_TRACE_SCOPE_ENTER:  audio_stream_session.cpp:114 Term
(49): 542449ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:115 [0x7f7f50001cb0]CSpxAudioStreamSession::Term:... 
(49): 542449ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:2538 [0x7f7f50001cb0]CSpxAudioStreamSession::ChangeState:  recoKind/sessionState: 1/1 != 1/2
(49): 542449ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:2528 [0x7f7f50001cb0]CSpxAudioStreamSession::ChangeState: recoKind/sessionState: 1/2 => 1/4
(49): 542449ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:127 [0x7f7f50001cb0]CSpxAudioStreamSession::Term: Now StoppingPump ...
(49): 542449ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:130 [0x7f7f50001cb0]CSpxAudioStreamSession::Term: StopPump[0x7f7f50024008]
(49): 542449ms SPX_DBG_TRACE_SCOPE_ENTER:  microphone_pump_base.cpp:138 MicrophonePumpBase::StopPump ...
(49): 542449ms SPX_THROW_HR_IF:  microphone_pump_base.cpp:141 (0x005) = 0x5
**(49): 542450ms SPX_DBG_TRACE_VERBOSE:  exception.cpp:100 About to throw Exception with an error code: 0x5 (SPXERR_INVALID_ARG)** 
[CALL STACK BEGIN]

/app/libMicrosoft.CognitiveServices.Speech.core.so(+0x1443bd) [0x7f8000b293bd]
/app/libMicrosoft.CognitiveServices.Speech.core.so(+0x237f15) [0x7f8000c1cf15]
/app/libMicrosoft.CognitiveServices.Speech.core.so(+0x1e844e) [0x7f8000bcd44e]
/app/libMicrosoft.CognitiveServices.Speech.core.so(+0x1651e5) [0x7f8000b4a1e5]
/app/libMicrosoft.CognitiveServices.Speech.core.so(+0x17e691) [0x7f8000b63691]
/app/libMicrosoft.CognitiveServices.Speech.core.so(+0x17f00e) [0x7f8000b6400e]
/app/libMicrosoft.CognitiveServices.Speech.core.so(+0x17f3a9) [0x7f8000b643a9]
/app/libMicrosoft.CognitiveServices.Speech.core.so(+0x1e12fb) [0x7f8000bc62fb]
/app/libMicrosoft.CognitiveServices.Speech.core.so(+0x1e18d7) [0x7f8000bc68d7]
/app/libMicrosoft.CognitiveServices.Speech.core.so(+0x1d8555) [0x7f8000bbd555]
/app/libMicrosoft.CognitiveServices.Speech.core.so(std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)+0x29) [0x7f8000b66389]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf827) [0x7f857c7e1827]
/app/libMicrosoft.CognitiveServices.Speech.core.so(+0x1db40f) [0x7f8000bc040f]
/app/libMicrosoft.CognitiveServices.Speech.core.so(+0x20ecc3) [0x7f8000bf3cc3]
/app/libMicrosoft.CognitiveServices.Speech.core.so(std::thread::_Impl<std::_Bind_simple<void (*(std::shared_ptr<Microsoft::CognitiveServices::Speech::Impl::CSpxThreadService::Thread>))(std::shared_ptr<Microsoft::CognitiveServices::Speech::Impl::CSpxThreadService::Thread>)> >::_M_run()+0x3f) [0x7f8000bf8a4f]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbd9e0) [0x7f857c3029e0]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f857c7d96db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f857b9bf88f]
[CALL STACK END]


(49): 542450ms SPX_DBG_TRACE_SCOPE_EXIT:  microphone_pump_base.cpp:138 MicrophonePumpBase::StopPump ... Done
(49): 542450ms SPX_DBG_TRACE_SCOPE_EXIT:  audio_stream_session.cpp:114 Term
(49): 542450ms SPX_DBG_TRACE_SCOPE_EXIT:  recognizer.cpp:330 TermDefaultSession

**Comment by cedrox** [comment]
Sorry 2 important points : 
- This error occur when using Speech to Text and not TTS. Also we are using Custom Text to Speech. 
- We are using 2 instances of an object witch could pump different audio stream at the same time. Error occurs mainly here but not always.

Thanks in advance for your help

**Comment by cedrox** [comment]
> You can refer [this](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging) to enable logging of the the sdk and share the log with us, so we can help to diagnose.

Can you route logging output to application Inisght ?

**Comment by yulin-li** [comment]
> > You can refer [this](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging) to enable logging of the the sdk and share the log with us, so we can help to diagnose.
> 
> Can you route logging output to application Inisght ?

Thanks for posting the log, we will investigate. I don't think we can route the logging insight.

**Comment by pankopon** [comment]
Closing the issue because no update since early January, please re-open if the issue is still valid and reproducible with the latest SDK release (1.9.0 as of this writing).

**Comment by Akash1000x** [comment]
when you face this problem you  match your Cognetive service location and your .env file in your code

**Comment by PhPeKe** [comment]
I had this error and it was due to me putting quotes inside my env file, so the SDK key/region contained quotes which is an illegal character and causes this error!
