### ISSUE TITLE
Entity recognition broken when no intent recognized

### ISSUE THREAD

**Issue by SOliasS** [Azure-Samples/cognitive-services-speech-sdk#468]
@jhakulin @rhurey From Thursday on the entity recgonition stopped working for LUIS EUW Xamarin SDK.

KeyRecognizedEvent?.Invoke(key, e?.Result.Properties.GetProperty(PropertyId.LanguageUnderstandingServiceResponse_JsonResult));

When trying to get the intents from a result the function returns null instead of the json result, when manually inspecting the element it looks fine ... -.-

![image](https://user-images.githubusercontent.com/14180046/71277952-86908800-2356-11ea-8f7d-aa3bcce49879.png)

And when an intent is recognized it returns  the function works like always and returns the proper json....

```
{
  "query": "erstelle eine neue aufgabe 2",
  "topScoringIntent": {
    "intent": "Todo_AddTodo",
    "score": 0.685601056
  },
  "entities": [
    {
      "entity": "aufgabe",
      "type": "builtin.keyPhrase",
      "startIndex": 19,
      "endIndex": 25
    },
    {
      "entity": "eine",
      "type": "builtin.number",
      "startIndex": 9,
      "endIndex": 12,
      "resolution": {
        "value": "1"
      }
    },
    {
      "entity": "2",
      "type": "builtin.number",
      "startIndex": 27,
      "endIndex": 27,
      "resolution": {
        "value": "2"
      }
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/14180046/71278090-e7b85b80-2356-11ea-9450-cf7cd3d730f4.png)

This is not the behavior expected nor what was happening until now....
P.s. we wanted to launch the first version of our application early next year... And now this is the second breaking error within a week... i'm getting a little nervous-.-

**Comment by SOliasS** [comment]
When calling the Web Api directly, it also works fine...

```
{
  "query": "Test 2",
  "topScoringIntent": {
    "intent": "None",
    "score": 0.9864209
  },
  "intents": [
    {
      "intent": "None",
      "score": 0.9864209
    },
    {
      "intent": "Utilities_Skip",
      "score": 0.0158703849
    },
    {
      "intent": "Todo_UpdateStartDate",
      "score": 0.0142106963
    },
    {
      "intent": "Utilities_Reject",
      "score": 0.008009068
    },
    {
      "intent": "Todo_FinishComment",
      "score": 0.00602537
    },
    {
      "intent": "Todo_SaveTodo",
      "score": 0.00405051559
    },
    {
      "intent": "Utilities_ShowNext",
      "score": 0.00395736843
    },
    {
      "intent": "Utilities_Stop",
      "score": 0.00382424821
    },
    {
      "intent": "Todo_UpdateTitle",
      "score": 0.00370009174
    },
    {
      "intent": "Utilities_FinishTask",
      "score": 0.003631373
    },
    {
      "intent": "Utilities_Confirm",
      "score": 0.00334284035
    },
    {
      "intent": "Todo_UpdateNote",
      "score": 0.003330475
    },
    {
      "intent": "Todo_ShowTodos",
      "score": 0.003188316
    },
    {
      "intent": "Utilities_StartOver",
      "score": 0.00290041557
    },
    {
      "intent": "Utilities_ShowPrevious",
      "score": 0.002387351
    },
    {
      "intent": "Utilities_Repeat",
      "score": 0.00198053615
    },
    {
      "intent": "Todo_ReasignTodo",
      "score": 0.00194834289
    },
    {
      "intent": "Utilities_Help",
      "score": 0.00179816142
    },
    {
      "intent": "Todo_UpdateEndDate",
      "score": 0.00162262458
    },
    {
      "intent": "Todo_UpdateComment",
      "score": 0.00141581893
    },
    {
      "intent": "Utilities_GoBack",
      "score": 0.00135915831
    },
    {
      "intent": "Utilities_Cancel",
      "score": 0.00134516647
    },
    {
      "intent": "Todo_AddTodo",
      "score": 0.00124487665
    },
    {
      "intent": "Utilities_ReadAloud",
      "score": 0.00100413931
    },
    {
      "intent": "Todo_EditTodo",
      "score": 0.00062723615
    },
    {
      "intent": "Todo_ListTodos",
      "score": 0.000496222463
    },
    {
      "intent": "Todo_UpdateKind",
      "score": 0.000445523357
    }
  ],
  "entities": [
    {
      "entity": "test",
      "type": "builtin.keyPhrase",
      "startIndex": 0,
      "endIndex": 3
    },
    {
      "entity": "2",
      "type": "builtin.number",
      "startIndex": 5,
      "endIndex": 5,
      "resolution": {
        "value": "2"
      }
    }
  ]
}
```

**Comment by rhurey** [comment]
The last week has been rough. We've not done a good job at making some changes.

Let me shed some light on what's been happening behind the scenes. 

When using the IntentRecognizer to recognize speech the Speech Service will make service to service calls to LUIS and get intent results. This is done to save latency, reduce client bandwidth, and improve the quality of the recognition result.

This service to service feature has existed only in the legacy Bing Speech Service, and with it's retirement work has been done to enable the functionality in the Cognitive Speech Service.

The problems of the last week have been with rolling out the change to which service will answer IntentRecognizer requests. The rollout targeted the West Europe region first. This change was planned to have been invisible to the client.

We've had a couple of problems, one was in the auth pipeline to LUIS where the service to service calls were being rejected that we only saw in production and today's where the behavior of the new service for an intent type of "None" had changed.

After the first we'd increased the testing and monitoring, but clearly not enough to spot the behavior change. Sorry. We'll be looking at what other cases are missing to avoid another repeat.

In both cases we aborted the rollout and shifted traffic in West Europe back to the existing system. I've checked and None is again returning intent information.

**Comment by SOliasS** [comment]
Hey @rhurey thanks for your detailed response...
I can confirm that everything is working again.
But it would be nice if you could warn us before you make significant changes, or ask for some betatesters... 
This time it just hit us out of nowhere...

**Comment by SOliasS** [comment]
Today same issue again....
@rhurey Come on guys why???

**Comment by chris-lindstrom** [comment]
Our apologies - I think I didn't understand the scope of the issue earlier. But - we did discover and check in a fix for this on Friday. It should roll out tomorrow. Will update this thread at that time.

**Comment by chris-lindstrom** [comment]
Fix rolled out - I have tested it in production. Please let us know if you continue to experience issues.

**Comment by SOliasS** [comment]
@chris-lindstrom is working again.
Still it is strange that you would change the service while knowing there were a bug and then wait push out the fix...
