### ISSUE TITLE
LUIS SDK azure vs container implementation

### ISSUE THREAD

**Issue by cedrox** [Azure-Samples/cognitive-services-speech-sdk#470]
**Is your feature request related to a problem? Please describe.**
When using the container version, you need to access web service. There is no SDK Abstraction as sdk version differ in webservice endpoints...
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/424

The problem here is that prediction results are not the same...

**Exemple in code :** 
     Task<PredictionResponse> pred;
             
                if (_config.UseLocalServices)
                {
                    pred = GetPredictionFromEndpointAsync(_config.LuisAPIKey, _config.LuisContainerUrl, _config.LuisAppId, _config.LuisSlotName, question.ToLowerInvariant());
                }
                else
                {
                    IList<DynamicList> dynamicLists = _luisFeedDynamicListService.LuisEntries.Select(e => new DynamicList(e.Key, RequestListExtensions.FromLuisEntries(e.Value))).ToList();
                    var predictionRequest = new PredictionRequest(question.ToLowerInvariant(), null, null, dynamicLists);
                   
                    pred = _luisClient.Prediction.GetSlotPredictionAsync(
                       Guid.Parse(_config.LuisAppId),
                       slotName: _config.LuisSlotName,
                       predictionRequest,
                       verbose: true,
                       showAllIntents: true,
                       log: true);
                }

**Describe the solution you'd like**
The proper solution would be to change only the enpoint like this:
**Version Azure**
        _luisClient = new LUISRuntimeClient(new ApiKeyServiceClientCredentials(_config.LuisAPIKey))
            {
                Endpoint = _config.LuisHostRegion
            };

**Version container**
            _luisClient = new LUISRuntimeClient(new MockCredentials())
            {
                Endpoint = "http://localhost:5010"
            };

**Comment by lisaweixu** [comment]
Hello cedrox,

It looks that you are using the LUIS Runtime SDK.  This is for Cognitive Speech SDK.  I will try to find a channel that you can post your LUIS Runtime SDK questions.

Inside the Speech SDK, there is a IntentRecognizer that talks to the LUIS service as well. Check it out [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/intent-recognition?pivots=programming-language-csharp).

**Comment by lisaweixu** [comment]
You may want to go to https://github.com/Azure-Samples/cognitive-services-language-understanding/issues.

**Comment by cedrox** [comment]
Thanks @lisaweixu for your advice. 
Adding issue here : https://github.com/Azure-Samples/cognitive-services-language-understanding/issues/28
