### ISSUE TITLE
The recognizer is using a free subscription that ran out of quota. Response 

### ISSUE THREAD

**Issue by hold-my-hand** [Azure-Samples/cognitive-services-speech-sdk#471]
We update the subscription, but the sdk still response this error until we uninstall the app, and reinstall the app. we use subscriptionKey in our app.
if we use token ,how long does a token valid？

**Comment by wolfma61** [comment]
token lifetime is 10 minutes

**Comment by lisaweixu** [comment]
It sounds that your free subscription is working after re-installation of your application. Do you mind checking what changed in your app?

**Comment by hold-my-hand** [comment]
@lisaweixu no，it cannot use until we update the subscription

**Comment by hold-my-hand** [comment]
@wolfma61 thanks a lot
