### ISSUE TITLE
Speech Recognition causes crashes on Oculus Quest when using Unity 2019.2.15f1

### ISSUE THREAD

**Issue by talespin-erik** [Azure-Samples/cognitive-services-speech-sdk#474]
**Description:**
Using the SpeechRecognizer in a Unity app built for Oculus Quest in version 2019.2.15f1 or later sometimes causes a hard app crash during recognition. This happens both when using ContinuousRecognitionAsync, and when using RecognizeOnceAsync. The crash doesn't happen with every recognition attempt, but happens often enough to be a problem.

The crash also started happening only after an update to Unity 2019.2, and the exact same code seemed to function fine on Unity 2019.1 or lower. Furthermore, we also attempted to replace our code with the Unity sample provided for the SpeechSDK and the crash also occurred a number of times.

The crash log for this error (see attached) is very limited, but points to an obscure java.lang.Error: FATAL EXCEPTION [UnityMain] that seems to be very low level. It does not explicitly mention the SpeechSDK or Speech Recognition, but only happens when someone speaks and the recogniser is active. When removing Speech Recognition entirely, the app worked without any errors. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a Unity project in 2019.2.15f1 or higher.
2. Add SpeechSDK and necessary code to interpret recognition.
3. Build for Android and run on Oculus Quest.
4. Start recognition and repeatedly pass in voice input.

**Expected Behaviour**
Input is processed accordingly and the correct events are fired for every voice input passed in.

**Actual Behaviour**
Input is sometimes processed correctly, but will occasionally hard crash and close the app.

**Version of the Cognitive Services Speech SDK**
1.8.0 and 1.7.0

**Platform, Operating System, and Programming Language**
 - OS: Android
 - Hardware - Oculus Quest
 - Programming language: C# (Unity)

**Additional context**
- The error happened in Unity versions 2019.2.15.f1, 2019.2.16f1, 2019.2.17f1. Presumably other versions of 2019.2 cause the same problem. 
 - Crash Log: [CrashLog.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4026427/CrashLog.log)

**Comment by jhakulin** [comment]
Thanks for the feedback, we will investigate the issue. 
@talespin-erik Could you try to get Speech SDK logs by following API below ?
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

**Comment by talespin-erik** [comment]
> Thanks for the feedback, we will investigate the issue.
> @talespin-erik Could you try to get Speech SDK logs by following API below ?
> https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

@jhakulin the saving of Log Files in that way, while it works on PC when working with Oculus Rift, seems to cause crashes on the Oculus Quest. We believe this is likely due to file permission issues. Unfortunately it is not possible for me to get you any more detailed logs than the one I have provided.

**Comment by talespin-erik** [comment]
@jhakulin This issue seems to no longer be a problem following the update to SpeechSDK 1.9.0 a few days ago. We are still not sure about the root cause of the problem, but we are no longer experiencing the crashes, so for now the issue seems to have resolved itself and can be closed.

**Comment by jhakulin** [comment]
Thanks for information!
