### ISSUE TITLE
Unable to import Speech SDK

### ISSUE THREAD

**Issue by wiazur** [Azure-Samples/cognitive-services-speech-sdk#475]
**Describe the bug**
Python.
When I try `pip install --upgrade azure-cognitiveservices-speech`, I get errors:
```
ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech (from versions: none)
ERROR: No matching distribution found for azure-cognitiveservices-speech
```
I read somewhere that it's due to not using Python 64-bit, but I am using that. I am using Python 3.8.0. Windows 10.

Referencing this quickstart: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/speech-to-text-from-file?tabs=linux&pivots=programming-language-python

**To Reproduce**
Try `pip install --upgrade azure-cognitiveservices-speech` from the command line from your project folder.

**Version of the Cognitive Services Speech SDK**
Whichever version is with the latest installation.

**Comment by pankopon** [comment]
Hi, unfortunately there is no package for Python 3.8 yet. It will be added in the SDK 1.10.0 release at the latest. Until then, please use an older version (from 3.5 up to 3.7) of Python. We have submitted a correction for Python version requirement on the quickstart page and it should show up in a couple of days.

**Comment by wiazur** [comment]
What a relief, thanks!
