### ISSUE TITLE
AttributeError: module 'swagger_client' has no attribute 'CustomSpeechTranscriptionsApi'

### ISSUE THREAD

**Issue by roverflow** [Azure-Samples/cognitive-services-speech-sdk#477]
Hi community, 

I am following the tutorial "How to use the Speech Services Batch Transcription API from Python" (see: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python).

After following all the steps (downloading the "cognitive-services-speech-sdk', moving the 'python-client-generated' -from swagger- file in that folder) and changing my Subscription key, service region and blob uri I receive the following error: 

> AttributeError: module 'swagger_client' has no attribute 'CustomSpeechTranscriptionsApi'

The error occurs in the transcribe function: 
>     transcription_api = cris_client.CustomSpeechTranscriptionsApi(api_client=client)

Anyone ideas how I can solve this (or what I am doing wrong?).

Many thanks in advance!

**Comment by chlandsi** [comment]
Hi, please try installing the module into your python environment using `pip install`, as described in the instructions, and then remove the swagger_client directory from your working directory. If that doesn't help, please put the command `print(dir(cris_client))` before the failing command, and post the output here.

**Comment by roverflow** [comment]
> Hi, please try installing the module into your python environment using `pip install`, as described in the instructions, and then remove the swagger_client directory from your working directory. If that doesn't help, please put the command `print(dir(cris_client))` before the failing command, and post the output here.

Thanks for your help! 
1). I exactly followed the instruction (the installing via pip the Python Client). 
2). When I run this in the command line, it gives no error: 
> C:\Users\xxx>python -c "import swagger_client"

3). When running the main script again, I received the same error as this topics name. 
4). I removed 'swagger_client'. Resulting in: ModuleNotFoundError: No module named 'swagger_client'
5). I restored the 'swagger_client' again, and added your print suggestion: 

```

runfile('C:/Users/xxx/Desktop/Azure_Blob_Text/cognitive-services-speech-sdk-master/samples/batch/python/python-client/main.py', wdir='C:/Users/xxx/Desktop/Azure_Blob_Text/cognitive-services-speech-sdk-master/samples/batch/python/python-client')
Starting transcription client...

['ApiClient', 'ApiResponse', 'Category', 'Configuration', 'Order', 'Pet', 'PetApi', 'StoreApi', 'Tag', 'User', 'UserApi', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'api', 'api_client', 'configuration', 'models', 'rest']

Traceback (most recent call last):

  File "C:\Users\xxx\Desktop\Azure_Blob_Text\cognitive-services-speech-sdk-master\samples\batch\python\python-client\main.py", line 144, in <module>
    transcribe()

  File "C:\Users\xxx\Desktop\Azure_Blob_Text\cognitive-services-speech-sdk-master\samples\batch\python\python-client\main.py", line 47, in transcribe
    transcription_api = cris_client.CustomSpeechTranscriptionsApi(api_client=client)

AttributeError: module 'swagger_client' has no attribute 'CustomSpeechTranscriptionsApi'
```

**Comment by chlandsi** [comment]
Hi,
this looks very much like the default API that the swagger autogenerator uses. Apparently the import of `https://<your-region>.cris.ai/docs/v2.0/swagger` in the online tool didn't work properly. Please completely remove the current python module from your system (`pip uninstall`) and try the complete process again. Please make sure that the swagger website shows the heading "Speech Services API v2.0" before you download the Python client.

**Comment by roverflow** [comment]
> Hi,
> this looks very much like the default API that the swagger autogenerator uses. Apparently the import of `https://<your-region>.cris.ai/docs/v2.0/swagger` in the online tool didn't work properly. Please completely remove the current python module from your system (`pip uninstall`) and try the complete process again. Please make sure that the swagger website shows the heading "Speech Services API v2.0" before you download the Python client.

Thanks again Christian. I followed every step regarding Swagger, as mentioned [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python).  

However, I don't see the heading "Speech Services API v2.0". Attached some print screens how I filled everything in... do you spot any mistake? 

Many thanks! 


![1 original](https://user-images.githubusercontent.com/48087408/72152257-befe1180-33aa-11ea-9299-ee053cd8526c.PNG)
![2 insert url](https://user-images.githubusercontent.com/48087408/72152259-c1f90200-33aa-11ea-80f3-617d7a7398f4.PNG)
![3 result](https://user-images.githubusercontent.com/48087408/72152262-c45b5c00-33aa-11ea-80ab-ba1954ad9234.PNG)

**Comment by roverflow** [comment]
> Hi,
> this looks very much like the default API that the swagger autogenerator uses. Apparently the import of `https://<your-region>.cris.ai/docs/v2.0/swagger` in the online tool didn't work properly. Please completely remove the current python module from your system (`pip uninstall`) and try the complete process again. Please make sure that the swagger website shows the heading "Speech Services API v2.0" before you download the Python client.

You are right, thanks! What solved the problem, was pasting "westeurope" instead of "west-europe" and "<west-europe>" in Swagger.

**Comment by chlandsi** [comment]
Glad that it is fixed!

**Comment by georgearun** [comment]
I'm not able to get eastus region python client from the swagger. I have used the following in import url swagger for version 2
https://eastus.cris.ai/docs/v2.0/swagger.

Can someone help me out in this

**Comment by nikitamalviya** [comment]
Go through the [README](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python) on the site.

To execute the sample you need to generate the Python library for the REST API which is generated through [Swagger](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/python/swagger.io).

Follow these steps for the installation:

- Go to https://editor.swagger.io/.
- Click **File**, then click **Import URL**.
- Enter the Swagger URL for the Speech Services API: `https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/cognitiveservices/data-plane/Speech/SpeechToText/stable/v3.1/speechtotext.json`.
- Click **Generate Client** and select **Python**.
- Save the client library.
- Extract the downloaded python-client-generated.zip somewhere in your file system.
- Install the extracted python-client module in your Python environment using pip:` pip install path/to/package/python-client`.
- The installed package has the name swagger_client. You can check that the installation worked using the command `python -c "import swagger_client"`

Follow these steps. It will work.
