### ISSUE TITLE
Transcribing a live rtmp video stream

### ISSUE THREAD

**Issue by jinyeng** [Azure-Samples/cognitive-services-speech-sdk#478]
What is best way to Transcribing a live rtmp video stream? Is there any example code available ?

**Comment by pankopon** [comment]
Hi, SDK does not support video as a whole, but you can achieve the same by separating audio from the video stream and then using only the audio part as SDK input, with a suitable AudioConfig method like FromStreamInput(). Sample code has examples of the use of FromStreamInput() depending on the programming language you use.
