### ISSUE TITLE
Using Net.CredentialCache.DefaultCredentials with SetProxy()

### ISSUE THREAD

**Issue by ash-sls** [Azure-Samples/cognitive-services-speech-sdk#480]
In order to set proxy settings what we usually use is something similar to the following - 

`var wp = System.Net.WebRequest.DefaultWebProxy;
wp.Credentials = System.Net.CredentialCache.DefaultCredentials;`

Is there anyway to use this or similar with `SpeechConfig.SetProxy` method?

Currently receiving the following error -

 CANCELED: ErrorDetails=Connection failed (no connection to the remote host). Internal error: 1. Error details: 11001. Please check network connection, firewall setting, and the region name used to create speech factory. SessionId: f59b665c6e724ca386fc2e9c3e870c45

This is received when using the SetProxy method as so -

`_config.SetProxy("http://192.168.170.142", 8080);`

Could I use the `SetProxy()` overload method with default credentials?

Any help much appreciated!

**Comment by pankopon** [comment]
Hi, you can use SetProxy also with proxyUserName and proxyPassword parameters - see the API reference (C#):
https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechconfig.setproxy?view=azure-dotnet

Also please note that proxyHostName should not have a protocol prefix (http://).

Unfortunately there is currently no support for using a DefaultCredentials object (System.Net.ICredentials) as a parameter directly.
