### ISSUE TITLE
RuntimeError: Exception with an error code: 0xe (SPXERR_MIC_NOT_AVAILABLE)

### ISSUE THREAD

**Issue by kapilg1997** [Azure-Samples/cognitive-services-speech-sdk#482]
I am testing Azure Cognitive Services Speech API for voice recognition. I have the code given from

MIcrosoft Guide: Link given Below

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/speech-to-text-from-microphone?tabs=dotnet%2Cx-android%2Clinux%2Cjava-runtime&pivots=programming-language-python#sample-code

The code is: 

import azure.cognitiveservices.speech as speechsdk

speech_key, service_region = "YourSubscriptionKey", "YourServiceRegion"
speech_config = speechsdk.SpeechConfig(subscription="XXXX", region="XXXX")

speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config)

print("Say something...")

result = speech_recognizer.recognize_once()

if result.reason == speechsdk.ResultReason.RecognizedSpeech:
    print("Recognized: {}".format(result.text))
elif result.reason == speechsdk.ResultReason.NoMatch:
    print("No speech could be recognized: {}".format(result.no_match_details))
elif result.reason == speechsdk.ResultReason.Canceled:
    cancellation_details = result.cancellation_details
    print("Speech Recognition canceled: {}".format(cancellation_details.reason))
    if cancellation_details.reason == speechsdk.CancellationReason.Error:
        print("Error details: {}".format(cancellation_details.error_details))

I am getting following error:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

D:\Anaconda3\python.exe "c:\Users\CFS Soft 4\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\lib\python\new_ptvsd\wheels\ptvsd\launcher" d:\k\STT\azure_recogn.py
Traceback (most recent call last):
  File "d:\STT\azure_recogn.py", line 9, in <module>
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config)
  File "D:\Anaconda3\lib\site-packages\azure\cognitiveservices\speech\speech.py", line 761, in __init__
    self._impl = self._get_impl(impl.SpeechRecognizer, speech_config, audio_config)
  File "D:\Anaconda3\lib\site-packages\azure\cognitiveservices\speech\speech.py", line 549, in _get_impl
    _impl = reco_type._from_config(speech_config._impl, None)
RuntimeError: Exception with an error code: 0xe (SPXERR_MIC_NOT_AVAILABLE)
[CALL STACK BEGIN]

    > CreateModuleObject

    - source_lang_config_release

    - CreateModuleObject

    - CreateModuleObject

    - source_lang_config_release

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - CreateModuleObject

    - recognizer_stop_keyword_recognition_async_wait_for

    - recognizer_create_speech_recognizer_from_config

    - 000007FED55B21B5 (SymFromAddr() error: Attempt to access invalid address.)

    - PyInit__speech_py_impl

    - 000007FED5560F57 (SymFromAddr() error: Attempt to access invalid address.)

 - OS: Windows 7
 - Programming language: Python 3.7.5
 - Azure Cognitive Services Speech API Version == 1.8.0

**Comment by Curious425** [comment]
(SPXERR_MIC_NOT_AVAILABLE) exceptions usually means you don't have a microphone on the system, or your app does not have access/permission to the microphone.

Have you checked you mic in something like sound recorder?

**Comment by jhakulin** [comment]
I see you are using OS: Windows 7, this is not officially supported environment for Speech SDK. Could you update your Windows OS version to the newer version ?

**Comment by jhakulin** [comment]
Closing this due to use of unsupported Windows version, let me know if you have an issue with Windows 10 or later.

**Comment by manueltorrs** [comment]
I have the same issue on Widows 10, I have this code:

    import azure.cognitiveservices.speech as speechsdk
    import time

    weatherfilename = "video.wav" 
    use_default_microphone=True
    device_name="1"

    speech_key, service_region = "MyKey", "MyServer"
    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)
    source_language_config = speechsdk.languageconfig.SourceLanguageConfig("es-ES")
    audio_config = speechsdk.audio.AudioConfig(device_name=device_name)

    def speech_recognize_continuous_from_file():

        speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config,
                                                   source_language_config=source_language_config,
                                                   audio_config=audio_config)

        done = False

        def stop_cb(evt):
            """callback that stops continuous recognition upon receiving an event `evt`"""
            print('CLOSING on {}'.format(evt))
            speech_recognizer.stop_continuous_recognition()
            nonlocal done
            done = True

        speech_recognizer.recognizing.connect(lambda evt: print("{}".format(evt.result.text)))
        speech_recognizer.session_stopped.connect(stop_cb)
        speech_recognizer.canceled.connect(stop_cb)

        # Start continuous speech recognition
        speech_recognizer.start_continuous_recognition()
        while not done:
            time.sleep(.5)
        # </SpeechContinuousRecognitionWithFile>

    speech_recognize_continuous_from_file()

And it works pretty good when I use a file .wav or the default microfone (weatherfilename = "video.wav"
use_default_microphone=True) but when I want to use any specific device it shows me this error:

> Traceback (most recent call last):
>   File "RecoVozAzure.py", line 50, in <module>
>     speech_recognize_continuous_from_file()
>   File "RecoVozAzure.py", line 23, in speech_recognize_continuous_from_file
>     audio_config=audio_config)
>   File "C:\Users\Manuel\AppData\Roaming\Python\Python37\site-packages\azure\cognitiveservices\speech\speech.py", line 802, in __init__
>     self._impl = self._get_impl(impl.SpeechRecognizer, speech_config, audio_config, language, source_language_config, auto_detect_source_language_config)
>   File "C:\Users\Manuel\AppData\Roaming\Python\Python37\site-packages\azure\cognitiveservices\speech\speech.py", line 874, in _get_impl
>     return reco_type._from_config(speech_config._impl, source_language_config._impl, audio_config._impl)
> RuntimeError: Exception with an error code: 0xe (SPXERR_MIC_NOT_AVAILABLE)
> [CALL STACK BEGIN]
> 
>     > pronunciation_assessment_config_to_json
> 
>     - pronunciation_assessment_config_to_json
> 
>     - pronunciation_assessment_config_to_json
> 
>     - pronunciation_assessment_config_to_json
> 
>     - pronunciation_assessment_config_to_json
> 
>     - pronunciation_assessment_config_to_json
> 
>     - pronunciation_assessment_config_to_json
> 
>     - pronunciation_assessment_config_to_json
> 
>     - pronunciation_assessment_config_to_json
> 
>     - pronunciation_assessment_config_to_json
> 
>     - pronunciation_assessment_config_to_json
> 
>     - pronunciation_assessment_config_to_json
> 
>     - pronunciation_assessment_config_to_json
> 
>     - pronunciation_assessment_config_to_json
> 
>     - pronunciation_assessment_config_to_json
> 
>     - pronunciation_assessment_config_to_json
> 
> 
> 
> [CALL STACK END]

It happens even if I try to use the default one but calling it with the device_name function.. As I said, my microphone and the algorithm work very well and I have problems only when I call the device_name function... Thanks

**Comment by jhakulin** [comment]
@manueltorrs Could you please create new GitHub issue as this one is closed? Also for the new issue add information for listing of your audio device names based on the program listed here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-select-audio-input-devices#audio-device-ids-on-windows-for-desktop-applications
