### ISSUE TITLE
Checksum failure for microsoft-cognitiveservices-speech-sdk@1.8.0

### ISSUE THREAD

**Issue by fsilvestre** [Azure-Samples/cognitive-services-speech-sdk#483]
**Describe the bug**
Need to update package.json to use version 1.8.1d

**To Reproduce**
1. go to **quickstart/javascript/node** directory
2. run `npm install`

**Expected behavior**
Install dependencies from package.json.

**Version of the Cognitive Services Speech SDK**
1.8.0

**Comment by chrisbasoglu** [comment]
1.9.0 to be released within the next 1-3 days.
