### ISSUE TITLE
Discrepancy Between Portal and Swagger Documentation

### ISSUE THREAD

**Issue by nstubing** [Azure-Samples/cognitive-services-speech-sdk#484]
**The Swagger Documentation is out of date**
The swagger documentation was useful when the *OLD (V2)* portal was around but now it is out of date with the features available on the V3 portal.

**Why is this an issue**
On the new portal, all models created are marked as a "modelKind": "Language" even if you are training the model with an Acoustic dataset and it allows you to train a new model with datasets of all dataImportKinds. (This makes more sense than how it was done in v2.)  This feature is not available for posting new models with the V2 api.

When trying to post a model with an acoustic and language dataset using the V2 api, I am getting Invalid Payload responses with the message "A new language model requires a language dataset and an optional pronunciation dataset." because this was the expected behavior with the *OLD* portal.

I am obviously able to perform the post I need by using https://westus.cris.ai/api/speechtotext/v3.0-beta1/models but I do not want to put a beta link in my production software in fear of it breaking.  

**When is the swagger documentation going to be updated to include the features of the V3 portal?**

**Comment by wolfma61** [comment]
The V2 API is the official supported API.
The V3 API is (even in its pre-beta form) is still work in progress and is changing as we are preparing the beta. When we make it an 'official beta API' we will make documentation available.

I will check anyhow on your issue ...

**Comment by bexxx** [comment]
The new portal is not supporting acoustic adaptations at the moment.
It always trains only with your language data.
Under the hood it passes the modelKind "language" in the model creation POST request.

The v2 API supports both modelKinds "acoustic" and "language". In case of language, you need to pass one language dataset and optionally a pronunciation dataset. If you train an acoustic model, pass the modelKind "acoustic" and one acoustic dataset.

This is one of the remaining differences between old and new portal. Once this work is complete, the new v3 beta API will be ready for public testing and we will release the swagger with it.

**Comment by nstubing** [comment]
@bexxx Thank you for the response. So what you are saying is, if I train a model in the V3 portal with a Language dataset and an Acoustic dataset, it will only actually train the model on the language model? (See image.) If that is the case, and I have to go back to training separate models (language and acoustic) to host on an endpoint, then I am also going to be getting screwed by the new Endpoint pricing model of $0.0538 per model per hour.  
![MicrosoftTraining](https://user-images.githubusercontent.com/39907303/72454966-c50f3c00-3776-11ea-82c9-b7c93eb65bae.PNG)

**V2 api and previous price model of $40 per endpoint per month**
That wont be a problem, since I was able to train a model on each dataset, and host a single endpoint with those models for $40 per month.

**V2 api and new price model of $0.0538 per model per hour for an endpoint**
I train the models just like before, a Language model and Speech model; but now I am having to pay more than $80 dollars per month per endpoint. (.0538 * 2 models * 24 hours * 31 days=$80.05)  **Why are my costs going to double out of no where?**

**V3 api and new price model of $0.0538 per model per hour for an endpoint**
I will be able to train a a single model with both an acoustic and language dataset and use that single model to host my endpoint bringing my price back to the original price of $40 per month.

**Comment by bexxx** [comment]
A manual workaround for the interim is to train the acoustic model with the V2 API and deploy the endpoint also with the V2 API. That POST takes both the language and acoustic models as input parameters.

**Comment by nstubing** [comment]
@bexxx So if I post the endpoint with the V2 api with 2 models, I will still be charged based on the old pricing model of $40 per month?

**Comment by bexxx** [comment]
$40 per month and $0.0538 per hour are the same (*24 * 31).
We only changed from charging per day to charging per hour which changed the docs.

**Comment by nstubing** [comment]
I am sorry, I really don't mean to be going in circles here, just looking to clarify. The pricing page says  it is $0.0538 per **model** per hour, and I will be using the V2 api to deploy the endpoint with **2** models (language/acoustic)  wouldn't that mean I am being charged  .0538 * 2 models * 24 hours * 31 days=$80.05?  

Is the pricing page supposed to say $0.0538 per endpoint per hour?  I am just confused here, and I thank you for helping me out with this.

**Comment by bexxx** [comment]
We charge per endpoint per hour. It does not matter whether it is a language model, an acoustic model or a combined endpoint with acoustic and language model. I will try to clarify this in the docs.

**Comment by nstubing** [comment]
Thank you so much, with that being said, the discrepancy between the portal and the swagger is negligible.  Thank you for your help.

**Comment by nstubing** [comment]
> The V2 API is the official supported API.
> The V3 API is (even in its pre-beta form) is still work in progress and is changing as we are preparing the beta. When we make it an 'official beta API' we will make documentation available.
> 
> I will check anyhow on your issue ...
Is there any estimate as to when V3 will be usable?  It makes way more sense to be able to train a model with many datasets in V3 rather than with V2 having one dataset per model. 

Right now if I want to update a model/endpoint with the V2 api, I have to create a whole new dataset with 90% of the same information. That is cumbersome and unintuitive when I am dealing with a "Base" language model of 500,000 lines and utilizing speech datasets.  It forces me to be consistently sending redundant information and very large files.  Am I missing something on the V2 api or is this just how I am going to have to do things until V3 is available?

@bexxx as well.
