### ISSUE TITLE
Azure speech java SDK - Connection was closed by the remote host. Error code: 1011.

### ISSUE THREAD

**Issue by ranjithrengaraj** [Azure-Samples/cognitive-services-speech-sdk#489]
**Describe the bug**
Running speech service container in local machine and container is up running but not able to test with Java sdk getting bellow error.
CANCELED: Reason=Error
CANCELED: ErrorCode=ConnectionFailure
CANCELED: ErrorDetails=Connection was closed by the remote host. Error code: 1011. Error details: Internal server error. SessionId: 5ea51a3dc00647278b35f7d9b86b32ce
CANCELED: Did you update the subscription info

**To Reproduce**
1. Created the cognitive service in azure portal
2. Run the docker by using - docker pull containerpreview.azurecr.io/microsoft/cognitive-services-speech-to-text:latest
 
docker run --rm -it -p 5000:5000 --memory 4g --cpus 4 \
containerpreview.azurecr.io/microsoft/cognitive-services-speech-to-text \
Eula=accept \
Billing={ENDPOINT_URI} \
ApiKey={API_KEY}

Replaced my subscription key and endpoint and run the docker container 

3. Docker container is up and running (validated using http://localhost:5000/status)
4. When i trying to call this service from Java sdk , am getting like Connection was closed by the remote host. Error code: 1011

**Expected behavior**
It should convert the my audio into text

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using. -  
<dependency>
      <groupId>com.microsoft.cognitiveservices.speech</groupId>
      <artifactId>client-sdk</artifactId>
      <version>1.9.0</version>
    </dependency>

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - MacOS catalina 10.15.12
 - Hardware - 2.3 GHz Dual-Core Intel Core i5 , 8 GB 2133 MHz LPDDR3
 - Programming language: Java
 - Browser [e.g. Firefox, Safari] (

**Additional context**
 - Error messages, log information, stack trace, ...
 -CANCELED: Reason=Error
CANCELED: ErrorCode=ConnectionFailure
CANCELED: ErrorDetails=Connection was closed by the remote host. Error code: 1011. Error details: Internal server error. SessionId: 5ea51a3dc00647278b35f7d9b86b32ce
CANCELED: Did you update the subscription info?
 
- Any other additional information
As per document (https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-container-howto?tabs=stt%2Ccsharp) i have updated the code to connect my service **SpeechConfig config = SpeechConfig.fromHost(new URI("ws://localhost:5000"));**

**Comment by jhakulin** [comment]
Thanks for feedback, could you provide logs as instructed here ?
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

**Comment by ranjithrengaraj** [comment]
Hi,

I think i found the problem. It may be my container not able to connect the public service for metering .

**Comment by tatemunja** [comment]
Could there be another issue cause this besides not being able to connect to the metering because I get this error (x amount of audio files i want to process) then it goes to process them successfully after.
