### ISSUE TITLE
iOS and Android doc comment improvements

### ISSUE THREAD

**Issue by rozele** [Azure-Samples/cognitive-services-speech-sdk#491]
I've been referring to the API reference documentation for [iOS](https://docs.microsoft.com/en-us/objectivec/cognitive-services/speech/) and [Android](https://docs.microsoft.com/en-us/java/api/com.microsoft.cognitiveservices.speech?view=azure-java-stable). I'm having trouble figuring out the semantics of some of the methods from the doc comments alone:

1. **`recognizeOnce` vs. `recognizeOnceAsync`:** When I last tested, both `recognizeOnce` and `recognizeOnceAsync` block the current thread until the speech recognition result is ready on iOS. Is there some explanation of the threading model for these two options on iOS and in what cases one would use one over the other? I'm interested to know if the blocking behavior is intentional and what thread / dispatch queue we can expect the speech result callback on.

2. **`startSpeakingText` vs. `speakText`:** I suspect the `startSpeakingText` API returns once there has been a successful response from the Speech service, and the `speakText` API returns once the audio has finished playing, but this is not explicitly documented in the doc comments. It gets even more confusing when deciding between `StartSpeakingTextAsync`, `StartSpeakingText` and `SpeakTextAsync` on the Java Speech SDK.

3. **Cancellation of `speakText`:** It's not well documented, but I'm curious if there is any way to cancel the `speakText` operation while it's in progress. It's doable if you write your own audio playback mechanism, but it would be great if it was also possible with the speech SDK. For example, if I call `SpeakTextAsync` on Android, then call `cancel(true)` on the resulting `Future<SpeechSynthesisResult>`, will it cancel the audio? Should this be documented behavior? Are there similar options on other flavors of the SDK (.NET, Obj-C)?

4. **Cancellation of `recognizeOnce`:** It's not documented, but seems to work. If I have an active session triggered by `recognizeOnce` or `recognizeOnceAsync`, and then call `stopContinuousRecognition`, it will terminate the `recognizeOnce` session. Perhaps some notes should be added to `stopContinuousRecognition` that it will cancel active sessions for methods other than `startContinuousRecognition`.

**Comment by jhakulin** [comment]
Thanks for the feedback,

1. RecognizeOnceAsync shouldn't be blocking the calling thread, if that is blocking then it is a bug, do you see the issue only with iOS ?

2. Thanks for informing about documentation gaps, we will improve our documentation regarding this.

3. @yulin-li Could you comment on this ? We are considering improvements to v2.0.0 API design on how to cancel pending speak.
	
4. This will be addressed in v2.0.0 API

**Comment by yulin-li** [comment]
Thanks for the comments.

`speakText` returns the result after all audio chunks are received from the service, also, if the audio is rendered to a speaker, `speakText` will wait for palying finished. `startSpeakingText` returns when the synthesis request is sent to service, at which time, the service just start synthesizing and no audio is received.

We will update the doc.

**Comment by jhakulin** [comment]
Closing the case, created workitem to verify RecognizeOnceAsync operation on iOS
