### ISSUE TITLE
How to use StartContinuousRecognitionAsync?

### ISSUE THREAD

**Issue by erotavlas** [Azure-Samples/cognitive-services-speech-sdk#492]
Hi, do you have an example how to use StartContinuousRecognitionAsync() ?
Specifically start the recording with a button, then stop and get the final result text.
(kind of like the online demo on this page. https://azure.microsoft.com/en-us/services/cognitive-services/speech-to-text/

The documentation for it doesn't offer any guidance for that particular method.

Thanks

**Comment by jhakulin** [comment]
Thanks for asking, we have a console sample e.g. for C# here:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/csharp/dotnet-windows/console
Which use sample code for continuous recognition:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_recognition_samples.cs

**Comment by erotavlas** [comment]
@jhakulin ok thank you I see the sample for // Speech recognition with audio stream

Do you know how to separate the start and stop to separate buttons - i.e. start the recognition and subscribe to the recognizing event using one button, but then send the stop notification using another button (in WPF)?

**Comment by nstubing** [comment]
Just have one button call (SpeechRecognizer).StopContinuousRecognitionAsync(); and have the other button call (SpeechRecognizer).StartContinuousRecognition(); 
Your recognizer would have to be a global variable or at least be available for both methods.
