### ISSUE TITLE
Endpoint fails after being posting with V2 API

### ISSUE THREAD

**Issue by nstubing** [Azure-Samples/cognitive-services-speech-sdk#493]
**Describe the bug**
I am attempting to post an endpoint with the V2 API and it fails every time (Fails through portal as well).  I do not know why and would love some insight as to why.  

**To Reproduce**
1. Create an acoustic dataset and a language dataset on V2 API or V2 portal.
2. Create an Acoustic model on V2 API or V2 portal with the new acoustic dataset- must use base model 20190523 (v4.14b Unified) otherwise it will not succeed.  *(Why is this my only option when there are better/newer base models available????)*
3. Create a Language model on V2 API or V2 portal with the new language dataset- must use base model 20190523 (v4.14b Unified) because the base model has to be the same if you are posting these models in an endpoint.
4. Create an Endpoint on V2 API or V2 portal with the new Language Model and Speech Model.
5. Wait for the endpoint status of "Failure".

**Expected behavior**
"Succeeded"

**Version of the Cognitive Services Speech SDK**
API

**Platform, Operating System, and Programming Language**
 - OS: Windows 
 - Hardware - x64
 - Programming language: C#

**Additional context**
Here is the Endpoint which should have worked. 
Successful datasets->successful models->Successful Posting of Endpoint->Failure
{
    "endpointKind": "SpeechRecognition",
    "models": [
      {
        "modelKind": "Acoustic",
        "baseModel": {
          "modelKind": "AcousticAndLanguage",
          "lastActionDateTime": "2019-11-01T23:17:21Z",
          "status": "Succeeded",
          "id": "78cb890b-4246-46df-b8ea-c3d8b7a5ee19",
          "createdDateTime": "2019-09-13T08:40:36Z",
          "locale": "en-US",
          "name": "20190523 (v4.14b Unified)",
          "description": "Unified",
          "properties": {
            "Purpose": "OnlineTranscription,BatchTranscription,AcousticAdaptation,LanguageAdaptation,LanguageOnlineInterpolation",
            "ModelClass": "unified-v4",
            "VadKind": "Tuned",
            "Deprecated": "None"
          }
        },
        "datasets": [
          {
            "dataImportKind": "Acoustic",
            "lastActionDateTime": "2020-01-22T23:14:35Z",
            "status": "Succeeded",
            "id": "65ccfda1-7135-424f-8fcd-3a8a33961e9f",
            "createdDateTime": "2020-01-22T23:11:50Z",
            "locale": "en-US",
            "name": "TestingofpostZip",
            "properties": {
              "Duration": "00:02:50",
              "SuitableForAdaptation": "True",
              "AcceptedLines": "31",
              "RejectedLines": "0",
              "AcousticDataAudioFilesUrl": "https://spsvcprodusw.blob.core.windows.net/bestor-338cca94-e7c5-4fc1-8a7b-7b8c19fd291a/AcousticData/663ec49e-876b-49b1-b2bb-e896d7c8cfcf?sv=2017-04-17&sr=b&sig=qvZS6AQL2ONDBuMKZSk%2FanbrMZMdDAI1QdMBcIQkL5o%3D&st=2020-01-23T20:49:09Z&se=2020-01-26T20:54:09Z&sp=rl",
              "ReportUri": "https://spsvcprodusw.blob.core.windows.net/bestor-338cca94-e7c5-4fc1-8a7b-7b8c19fd291a/AcousticData/f9d7f19d-70c9-45e3-a2c7-d936e4e156a7?sv=2017-04-17&sr=b&sig=y4%2Bu6Qx6hD1DhF5YCRTWf6LqWpV0I2eNOrZmFb8qsXQ%3D&st=2020-01-23T20:49:09Z&se=2020-01-26T20:54:09Z&sp=rl"
            }
          }
        ],
        "lastActionDateTime": "2020-01-23T00:14:03Z",
        "status": "Succeeded",
        "id": "3fd1d301-cad2-4c27-86e2-5351cf9050f8",
        "createdDateTime": "2020-01-22T23:17:13Z",
        "locale": "en-US",
        "name": "datasetFromMedtalk",
        "description": "description"
      },
      {
        "modelKind": "Language",
        "baseModel": {
          "modelKind": "AcousticAndLanguage",
          "lastActionDateTime": "2019-11-01T23:17:21Z",
          "status": "Succeeded",
          "id": "78cb890b-4246-46df-b8ea-c3d8b7a5ee19",
          "createdDateTime": "2019-09-13T08:40:36Z",
          "locale": "en-US",
          "name": "20190523 (v4.14b Unified)",
          "description": "Unified",
          "properties": {
            "Purpose": "OnlineTranscription,BatchTranscription,AcousticAdaptation,LanguageAdaptation,LanguageOnlineInterpolation",
            "ModelClass": "unified-v4",
            "VadKind": "Tuned",
            "Deprecated": "None"
          }
        },
        "datasets": [
          {
            "dataImportKind": "Language",
            "lastActionDateTime": "2020-01-22T23:14:25Z",
            "status": "Succeeded",
            "id": "b12a3d37-ed02-4ba0-ba5c-f9596d898871",
            "createdDateTime": "2020-01-22T23:11:50Z",
            "locale": "en-US",
            "name": "TestingofPost1",
            "properties": {
              "AcceptedLines": "37",
              "RejectedLines": "0",
              "LanguageDataUrl": "https://spsvcprodusw.blob.core.windows.net/bestor-338cca94-e7c5-4fc1-8a7b-7b8c19fd291a/LanguageData/eca90eee-a530-4163-9713-a2a9393bf9f5?sv=2017-04-17&sr=b&sig=9HqCBh2pHAg7mil4nH%2FlW2QQURw0NMRM7NZdEOs3V8o%3D&st=2020-01-23T20:49:09Z&se=2020-01-26T20:54:09Z&sp=rl",
              "ReportUri": "https://spsvcprodusw.blob.core.windows.net/bestor-338cca94-e7c5-4fc1-8a7b-7b8c19fd291a/LanguageData/f7ab144c-19c7-47b0-82a5-bef3d03d6324?sv=2017-04-17&sr=b&sig=rLUWnASHUAgwtYPL9JLfFi9dAXB%2BksturBBZU8t9UXc%3D&st=2020-01-23T20:49:09Z&se=2020-01-26T20:54:09Z&sp=rl"
            }
          }
        ],
        "lastActionDateTime": "2020-01-22T23:43:01Z",
        "status": "Succeeded",
        "id": "3d8e7ce8-0c2f-44a8-8c78-3cdc06e7b62f",
        "createdDateTime": "2020-01-22T23:16:10Z",
        "locale": "en-US",
        "name": "datasetFromMedtalk",
        "description": "description"
      }
    ],
    "concurrentRecognitions": 20,
    "contentLoggingEnabled": true,
    "endpointUrls": {
      "HttpRestInteractive": "https://westus.stt.speech.microsoft.com/speech/recognition/interactive/cognitiveservices/v1?cid=f2a39a09-0073-4e46-9601-83c6072a23a9",
      "HttpRestDictation": "https://westus.stt.speech.microsoft.com/speech/recognition/dictation/cognitiveservices/v1?cid=f2a39a09-0073-4e46-9601-83c6072a23a9",
      "ClientWebSocket": "https://westus.stt.speech.microsoft.com/ws/cris/speech/recognize?cid=f2a39a09-0073-4e46-9601-83c6072a23a9",
      "ClientWebSocketContinuous": "https://westus.stt.speech.microsoft.com/ws/cris/speech/recognize/continuous?cid=f2a39a09-0073-4e46-9601-83c6072a23a9",
      "ServiceWebSocket": "wss://westus.stt.speech.microsoft.com/ws/cris/speech/recognize?cid=f2a39a09-0073-4e46-9601-83c6072a23a9",
      "ServiceWebSocketContinuous": "wss://westus.stt.speech.microsoft.com/ws/cris/speech/recognize/continuous?cid=f2a39a09-0073-4e46-9601-83c6072a23a9",
      "UniversalWebSocketInteractive": "wss://westus.stt.speech.microsoft.com/speech/recognition/interactive/cognitiveservices/v1?cid=f2a39a09-0073-4e46-9601-83c6072a23a9",
      "UniversalWebSocketConversation": "wss://westus.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?cid=f2a39a09-0073-4e46-9601-83c6072a23a9",
      "UniversalWebSocketDictation": "wss://westus.stt.speech.microsoft.com/speech/recognition/dictation/cognitiveservices/v1?cid=f2a39a09-0073-4e46-9601-83c6072a23a9"
    },
    "lastActionDateTime": "2020-01-23T20:33:36Z",
    "status": "Failed",
    "id": "f2a39a09-0073-4e46-9601-83c6072a23a9",
    "createdDateTime": "2020-01-23T20:03:27Z",
    "locale": "en-US",
    "name": "TesterWithContentLoggingAndUserModels"
  }

**Comment by bexxx** [comment]
This was an issue with incorrect metadata on the selected base model which was provided by the service.
I've updated it and tested the endpoint creation with a model trained on that base model and it is now completing successfully.

Please try again.

**Comment by nstubing** [comment]
It works now, thank you.   Any timeline on when the new API will be in public beta?

**Comment by bexxx** [comment]
We work hard to get it out soon into the hands of developers. :)
