### ISSUE TITLE
Problems with continuous recognition

### ISSUE THREAD

**Issue by Ghckodak** [Azure-Samples/cognitive-services-speech-sdk#495]
I am trying to run a test of continuous recognition by using the provided sample code. When I run it there is no error but I can't get any result. How can I fix it?

![2020-01-23 (1)](https://user-images.githubusercontent.com/58378180/73044604-42eadb80-3e38-11ea-84a4-5ad083b4bd4a.png)

**Comment by jhakulin** [comment]
Thanks for question, please check the sample here:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_sample.py

You need to wait for result after starting continuous recognition.

**Comment by jhakulin** [comment]
Closing this, let me know if more information is needed.
