### ISSUE TITLE
Unable to retrieve AudioRecord objectAudio Record 

### ISSUE THREAD

**Issue by jose-alvessh** [Azure-Samples/cognitive-services-speech-sdk#497]
**Describe the bug**
I'm developing an Android sample app for testing different keywords for wake up of my voice recognition system. I have based my app on the Android sample App provided in this sdk, using the same MicrophoneStream class as the Audio Input of my app (configured in the AudioConfig of my SpeechRecognizer). 
As I need to test several keywords, thus I have to stop and initialise the speech recogniser several times in order to test with the different keywordModels. Am I right?
However, several times I'm getting a native Android Library error: **"E/AudioRecord: Unable to retrieve AudioRecord object"** that makes both the SpeechRecognizer class and my App to crash. 
This error happens in this [class](https://android.googlesource.com/platform/frameworks/base/+/master/core/jni/android_media_AudioRecord.cpp) and as I understood it happens because the native AudioRecorder does not exist anymore. This error happens randomly, this is, sometimes it happens at the first stop and restart and other times it happens after several tries.

**To Reproduce**
Stop and restart several times the SpeechRecognizer or stop and restart the AudioRecord inside the MicrophoneStream class. 
- To start the speech recognistion I'm using the _startKeywordRecognitionAsync(kwsModel)_ method and to stop it I'm using the _stopKeywordRecognitionAsync()_ method. 
- I've also tried to force the cancellation of the speech service using the _MicrophoneStream.close()_ method but this error also happens. 

**Expected behavior**
The SpeechRecognizer should be re-initialised without any problem since the stop of the SpeechRecognizer should immediately stop the read on the AudioRecorder side. 

**Version of the Cognitive Services Speech SDK**
I'm using the version 1.9.0

**Platform, Operating System, and Programming Language**
 - OS: Android
 - Hardware - ARM

**Additional context**
 - I have tried already to surround the method  **read(byte[] bytes)** of the **MicrophoneStream** class with a try and catch, but unless it happens less times this error still happens.
- I have also tried to save the cognitive services logs, but when the app crashes nothing is saved unless the normal logs (the error logs are not saved because the app natively crashes)

**Comment by jhakulin** [comment]
Thanks for feedback, yes you should be able to stop and then start the existing speech recognizer with the different keywordModel, we will take a look and see what is the problem.

**Comment by jhakulin** [comment]
@jose-alvessh I tried to reproduce the issue in Java using MicrophoneStream implementation from: https://github.com/microsoft/botframework-solutions/blob/master/samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/MicrophoneStream.java 

I had an app which has Start and Stop button:

When Start button is pressed 1) KWS model is created from file and recognizer is created using MicrophoneStream audio config 2) startKeywordRecognitionAsync(KWSmodel) is called and keyword recognition starts

When Stop button is pressed 1) stopKeywordRecognitionAsync is called 2) MicrophoneStream.close() 3) Remove recognizer callback event listeners 4) Recognizer.close

I have not been able to reproduce the issue you have after several (20 trials). 
Do you think the following should reproduce the issue ?

**Comment by jose-alvessh** [comment]
Hi @jhakulin! 
I have significant differences between what you have done  when pressing the stop button, that i what I have done: 
stopKeywordRecognitionAsync is called
Then Inside the event listener:
- MicrophoneStream.close()
- SpeechRecognitzer.close()

I was not removing the listeners since I thought that they were removed automatically when the close() method is called. 

Should I close both MicrophoneStream and Speech Recognizer inside the stop async event listener? There's always the need to remove the event listeners when I close the SpeechRecognizer, even if when I want to start it again, I will have to add them?

**Comment by jhakulin** [comment]
@jose-alvessh I would believe there is an issue if you close microphone stream before speech recognizer. Could you try to close mic after speech recognizer ?

**Comment by jhakulin** [comment]
Closing this, we have created work item to handle case more gracefully when Microphone stream gets closed before SpeechRecognizer is stopped.
