### ISSUE TITLE
How to use Azure speech recognition for other language than English?

### ISSUE THREAD

**Issue by rahmatiaria** [Azure-Samples/cognitive-services-speech-sdk#498]
**Describe the bug**
I'm writing a code to transcribe an audio file using Azure speech recognition. The audio is in Norwegian. I'm not sure how to set the input language the API.
Following is my code, but I get an error.

**To Reproduce**
```Python
import azure.cognitiveservices.speech as speechsdk
from os import path

# Creates an instance of a speech config with specified subscription key and service region.
# Replace with your own subscription key and service region (e.g., "westus").

audio_filename = 'path to the audio file'

# use the audio file as the audio source
audio_input = speechsdk.AudioConfig(filename=audio_filename)

# configure the speech recognition
speech_key, service_region = "my_key", "my_region"
speech_config = speechsdk.SpeechConfig(subscription=speech_key, 
                                       region=service_region)
speech_config.speech_recognition_language='no'

# Creates a recognizer with the given settings
speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, 
                                               audio_config=audio_input)


result = speech_recognizer.start_continuous_recognition()
```

**Expected behavior**

**Platform, Operating System, and Programming Language**
 - OS: iOS
 - Hardware - x64
 - Programming language: Python

**Error**
 Speech Recognition canceled: CancellationReason.Error
Error details: WebSocket Upgrade failed with a bad request (400). Please check the language name and endpoint id (if used) are correctly associated with the provided subscription key.

**Comment by rhurey** [comment]
The recognition language needs to be in the 4 letter format for one of the supported languages here:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support

Norwegian would be nb-NO
