### ISSUE TITLE
OutputFormat.Detailed does not affect intermediate recognition

### ISSUE THREAD

**Issue by LedanDark** [Azure-Samples/cognitive-services-speech-sdk#499]
Overview of the Issue 
      Intermediate results from continuous recognition don't have a confidence score, even when OutputFormat has been set to detailed. 
      Is there documentation on what is included in intermediate results, and/or what is included in simple vs detailed output?

Expected output - 
      Changing OutputFormat from simple to detailed will give have the intermediate results report their confidence level.
    Version - what version is affected (e.g. 0.1.2)
         1.8.0, java SDK
    Motivation for or Use Case - explain what are you trying to do and why the current behavior is a bug for you
    Operating System - Linux
    Reproduce the Error - 
      var config = SpeechConfig.fromSubscription("YorKey","AValidRegion")
      config.outputFormat = OutputFormat.Detailed
      //Audioconfig is from an audiostream
      var recognizer = SpeechRecognizer(speechConfig, audioConfig)
      recognizer.recognizing.addEventListener{s,e -> 
         e.result.properties.getProperty(PropertyId.SpeechServiceResponse_JsonResult)
         //Gives a json that has duration, text, and offset
      }
      recognizer.recognized.addEventListener{s,e -> 
         e.result.properties.getProperty(PropertyId.SpeechServiceResponse_JsonResult)
         //Gives a json that has duration, text, offset, and a list of nbest results with confidence scores.
      }

**Comment by lisaweixu** [comment]
The OutputFormat.Detailed only controls the recognized results. The intermediate results only contains Text, Offset and Duration regardless the OutputFormat is set to. 

I would not put too much trust into the intermediate results since they are changing. So the confidence score sounds not very useful.
