### ISSUE TITLE
Unable to recognize Silences

### ISSUE THREAD

**Issue by roverflow** [Azure-Samples/cognitive-services-speech-sdk#501]
Hi community, 

I am following [this ](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/from-blob?pivots=programming-language-python)tutorial. 

It is converting my speech properly! However, what I am missing (and what is key for my analysis), is to recognize silences (with for example dots). 

For example: 
"Hey what is your name?   My name is euhm ........... X"     (dots representing silences) 

Does anyone knows how I can get that into the translation? It should be available, since it is working with the "5: speech_recognize_continuous_from_file - performs continuous speech recognition with input from an audio file". 

Many thanks in advance!

**Comment by lisaweixu** [comment]
Could you feed your audio file from translation_sample.translation_continuous in the main.py by replacing weatherflename with your own audio file?

Please note the silence can't be too long, otherwise the recognizer may think it reaches the end of an utterance and stop decoding the rest of the sentence.

**Comment by nstubing** [comment]
You could take the (offset of previous recognition+duration of previous recognition) - offset of next recognition and get the exact time between each recognition and do whatever you want with that info. 

 Or if it is all in one recognition, you could do the same process with word level timestamps. But like @lisaweixu said, if there is a long enough pause it will process it as separate utterances.

**Comment by wolfma61** [comment]
You have to distinguish between longer silence and short silences (.5 sec or so) while you are speaking. 

Long silence will break the input audio stream into turns, this will give you multiple final results in your recognition (there are other conditions (technical and semantic) that can create final results). Recognition result-duration and result-offset can help here to recognize silence between these results.

To detect short silence periods (which will not result in a new turn) you can request word-level-timestamps in your recognition (SpeechConfig.RequestWordLevelTimestamps). Then you should look at the json part of the final result you receive in the callback (e.Result.Properties.GetProperty(PropertyId.SpeechServiceResponse_JsonResult). There you will find a word list, and a startoffset and duration for each word. With some calculation you can find silence periods between words. Just to note, there is some natural silence in between words (you don't slur words together in your speech), this will not get detected this way. It must be some more noticeable silence between words. 

To pre-empt your next questions: 
- the silence interval that triggers new turns/results can't be changed (currently).
- silence is currently not an event type that is returned, there is discussion to have this feature, but when/if this will become available is not decided

**Comment by pankopon** [comment]
Closing the question as answered, please re-open if more information is needed.
