### ISSUE TITLE
Java SDK : Units of Duration

### ISSUE THREAD

**Issue by LedanDark** [Azure-Samples/cognitive-services-speech-sdk#504]
https://docs.microsoft.com/en-us/java/api/com.microsoft.cognitiveservices.speech.recognitionresult.getduration?view=azure-java-stable

Unclear what units the duration is in. Is it in 100ns units, i.e. 2 would be 200ns, or is it in nanoseconds but only has the resolution of 100 nanoseconds?

**Comment by lisaweixu** [comment]
Duration is in nano seconds with a resolution of 100 nano seconds. E.g. duration 25 means 2500 nano seconds(25*100= 2500 nano seconds).
