### ISSUE TITLE
Keyword recognition stops working after some time

### ISSUE THREAD

**Issue by CobraCalle** [Azure-Samples/cognitive-services-speech-sdk#506]
**Describe the bug**
I've build my own voice controll for my home automation system, that is based on raspberry pi. The solution is based on dotnet core (Blazor to be specific) and because of the fact that the azure speech API does not work with dotnet under Linux on arm, I stream the microphone data over the network to a server application Wich feeds the data into a azure speechrecognizer to recognize the wake word. That works fine, but after some time it just stops recognizing... The data it still feeder to the recognizer (I've tried push and pull streams), but the recognizer does not react.

Do I have to restart the recognizer in some cases? Perhaps over midnight or something like that?

**To Reproduce**
1. Use SpeechRecognizer from dotnet core app to detect a keyword 
2. Let it run for some hours

**Expected behavior**
Even after hours of silence or audio without the keyword it should react to the keyword when spoken

**Version of the Cognitive Services Speech SDK**
Latest nuget on Windows 10. Dotnet core web app (Blazor)

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - x64
 - Programming language: C#

**Additional context**
 - Error messages, log information, stack trace, ...
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by jhakulin** [comment]
Thanks for feedback, do you see CanceledReason::Error event on the app side when the KWS stops ?
As a workaround you can stop the current recognizer and create new one as replacement.
We have workitem on backlog for similar issue.

**Comment by CobraCalle** [comment]
Thank you for directing me to the Canceled-Event... If attached that, and that is the result:

Error (Connection was closed by the remote host. Error code: 1000. Error details: Exceeded maximum websocket connection idle duration(> 300000ms) SessionId: f510ec34cbf14ceaa7a9f33eef00484b)

What does that mean? Is the problem that there was no new data for the recognizer for more than 300000ms? What connection is meant here? I thought that the keyword recognizer works offline...?!

**Comment by jhakulin** [comment]
@CobraCalle Keyword recognition methods are currently designed as part of recognizer objects (e.g. SpeechRecognizer) so that after keyword is detected, speech sdk will automatically start speech recognition followed by the keyword. If you are offline, keyword recognition will work but the speech recognition after that will not work and will cause connection failure, which you probably see now.

We have in near future plans to provide separate KeywordRecognizer object which is not tied to any recognizer objects.

**Comment by CobraCalle** [comment]
> @CobraCalle Keyword recognition methods are currently designed as part of recognizer objects (e.g. SpeechRecognizer) so that after keyword is detected, speech sdk will automatically start speech recognition followed by the keyword. If you are offline, keyword recognition will work but the speech recognition after that will not work and will cause connection failure, which you probably see now.
> 
> We have in near future plans to provide separate KeywordRecognizer object which is not tied to any recognizer objects.

Thank you for the update. Can I stop the recognition manually to prevent the system from streaming audio to the cloud (andbget rid of the exception)?

**Comment by jhakulin** [comment]
@CobraCalle We are investigating this and inform you if there is a workaround. Unfortunately there seems to be bug in the state machine inside speech SDK when the canceled event occurs with KeywordRecognizer.

**Comment by jhakulin** [comment]
This will be fixed in 1.11.0 release coming end of this month (ETA), closing the issue

**Comment by CobraCalle** [comment]
Thanks alot. I`ve already installed the new version. But now the detection works only one time... do I have to restart the recognition after a keyword was detected in the new version?

**Comment by jhakulin** [comment]
Fix is not yet in 1.10.0 (latest), but in 1.11.0 release which is coming end of this month (ETA). Unfortunately I do nto have workaround to provide for 1.10.0

**Comment by CobraCalle** [comment]
Sorry my fault... Haven't seen the 11 😁

**Comment by CobraCalle** [comment]
Just an other small update: Under Windows (x64) I get the Error described in the second post. But under Linux-arm64 the recognition only works one time. The Sessions stopped event is not called and after some time the canceled event is rised. but event stopping and restarting the recognizer does not help... it ony recognizes the keyword onyl one time.

PS: I installed linux 64 bit on raspberry and using the speech api now from dotnet core under linux on rapsberry pi :-)

**Comment by jhakulin** [comment]
@CobraCalle Do you mean keyword recognition works only once in Linux-arm64 if you try to recognize keyword with speech (e.g. "Computer, what's the weather like?") few times in a row ?

Would it be possible for you to provide speech sdk log under Linux arm64 using the instructions here ?
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

**Comment by jhakulin** [comment]
@CobraCalle Let us know what is the version of Linux OS you have installed?

**Comment by CobraCalle** [comment]
The version is: Ubuntu 18.04.4 LTS (GNU/Linux 4.19.105-v8-28 aarch64)

as a temporary fix I`ll try to dispose a recreate the SpeechRecognizer instance every time it has recognized a keyword... perhaps that will work until we get this fixed.

**Comment by CobraCalle** [comment]
> @CobraCalle Do you mean keyword recognition works only once in Linux-arm64 if you try to recognize keyword with speech (e.g. "Computer, what's the weather like?") few times in a row ?
> 
> Would it be possible for you to provide speech sdk log under Linux arm64 using the instructions here ?
> https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

Yes exactly. The first time works fine, but then it stops responding. Here what i´ve found out so far:

The recognizer reacts different ased on the cpu architecture... 

...on x64 (windows and linux):
1. It recognizes the keyword
2. Session started event is fired
3. Session stopped event is fired
4. Some times Canceled event is fired with the following exception message: Canceled: Error (Connection was closed by the remote host. Error code: 1000. Error details: Exceeded maximum websocket connection idle duration(> 300000ms)
5. Addition keywords are detected without any problems (only when the canceled event is fired there is a little time span where the keyword is not recognized)

...on arm (only linux tested so far)
1. It recognizes the keywork
2. Session started event is fired
3. Session stopped event is NOT fired
4. It stopes reconizing keywords (of course session stopped is not fired)
5. Canceld event is fired (other message than on x64, but I can not reproduce it at the moment and don´t remember the exact message)
6. Event calling "StopKeywordRecognitionAsync" and than "StartKeywordRecognitionAsync" doe not help. It doe not recognize any keywords anymore

**Comment by CobraCalle** [comment]
> @CobraCalle Do you mean keyword recognition works only once in Linux-arm64 if you try to recognize keyword with speech (e.g. "Computer, what's the weather like?") few times in a row ?
> 
> Would it be possible for you to provide speech sdk log under Linux arm64 using the instructions here ?
> https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

I've built a version the writes the log... as soons as I have the possibility to test it, I'll provide the log to you

**Comment by CobraCalle** [comment]
OK... the problem is not as ciritical as I thought... the keyword detector does react more than one time. The problem was on my side... on ubuntu on arm64 I cannot stop and restart the recording from the microphone... don't know wats the problem here, but it not the speech recognizer.
