### ISSUE TITLE
Tenant Model integration with Custom Speech model

### ISSUE THREAD

**Issue by manish-95** [Azure-Samples/cognitive-services-speech-sdk#507]
**Is your feature request related to a problem? Please describe.**
I have a custom speech model, which I have trained to better recognise specific terms. I would like to also use the Tenant Model, currently in preview, and be able to create an endpoint that can use both the custom speech model as well as the Tenant model, to create a speech endpoint that has an overall higher accuracy of speech detection.

**Describe the solution you'd like**
A solution in the custom speech portal that allows me to deploy an endpoint using more than one trained model OR alternatively allows me to use the data generated as part of the Tenant Model to trained one combined model, trained on both my custom data as well as organizational data.

**Comment by pankopon** [comment]
To @wolfma61 - will you follow up on this? Please re-assign if necessary.

**Comment by wolfma61** [comment]
@manish-95 

This feature has been discussed.
We 'like' it, but unfortunately it is not currently scheduled due to schedule contrains. It will not get addressed in the next several month.

Wolfgang

**Comment by jhakulin** [comment]
Closing as item is acknowledged for future planning
