### ISSUE TITLE
I can't find a header file "SPXSpeechSynthesizer.h"

### ISSUE THREAD

**Issue by hold-my-hand** [Azure-Samples/cognitive-services-speech-sdk#509]
**Describe the bug**
I can't find a header file "SPXSpeechSynthesizer.h" in MicrosoftCognitiveServicesSpeech.framework

**To Reproduce**
My iOS MicrosoftCognitiveServicesSpeech.framework version is 1.9.0 ,Do you forget to put it in the headers dir?
I find these files in 1.8.0 
SPXSpeechSynthesisCancellationDetails.h
SPXSpeechSynthesisEventArgs.h
SPXSpeechSynthesisResult.h
SPXSpeechSynthesizer.h
And some api in SPXSpeechConfiguration.h is different between 1.8.0 with 1.9.0 
How to use Speech synthesis in 1.9.0?

**Comment by jhakulin** [comment]
@yulin-li Could you please check this as related to SpeechSynthesizer ?

**Comment by yulin-li** [comment]
Hi @hold-my-hand 

We double checked the 1.9.0 release, and found the SPXSpeechSynthesis*.h files are included int he freamwork. You can donwload the framework dirctly from [here](https://aka.ms/csspeech/iosbinary) to check.

I also manully checked the [quickstart](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/swift/ios/text-to-speech) using 1.9.0 SDK, which works fine.

Cloud you pls try again?

**Comment by pankopon** [comment]
Closing the issue since it was verified that the current latest release 1.9.0 works correctly. Please re-open if there's need for further information.

**Comment by hold-my-hand** [comment]
<img width="345" alt="截屏2020-02-24上午10 50 05" src="https://user-images.githubusercontent.com/11240397/75126113-73ea5480-56f3-11ea-8705-e2b722844e76.png">
I check my local files again I don't find it.I will download the framework  to check again
