### ISSUE TITLE
Nodejs Speech Synthesizer

### ISSUE THREAD

**Issue by reflash** [Azure-Samples/cognitive-services-speech-sdk#510]
Hello,

I'm trying to migrate from BingTTS to new speech services. Unfortunately I'm not able to find any samples of Text-to-Speech in documentation and related types are not available in the package. Is it possible to use this feature ?

**Comment by yulin-li** [comment]
The Speech SDK dosen't support NodeJs TTS now. We plan to add this support, but I am not sure the ETA.

**Comment by yulin-li** [comment]
Closing this issue for now.
