### ISSUE TITLE
Unable to receive response from "SynthesisWordBoundaryEventAsync" (key Q)

### ISSUE THREAD

**Issue by rvrjp7** [Azure-Samples/cognitive-services-speech-sdk#513]
**Not receiving any response from the server even after setting a proper subscription key and region, following error was displayed:**
```
CANCELED: Reason=Error
CANCELED: ErrorCode=ConnectionFailure
CANCELED: ErrorDetails=[Connection was closed by the remote host. Error code: 1011. Error details: Internal server error. USP state: 3. Received audio size: 0bytes.]
CANCELED: Did you update the subscription info?
```

**To Reproduce**
1. run"dotnet run" in the sample project.

**Expected behavior**
Should print response received from the server.

**Version of the Cognitive Services Speech SDK**
1.9.0

**Platform, Operating System, and Programming Language**
 - OS:  Windows, Linux
 - Hardware - x64
 - Programming language: C#
 - Browser: (It's a console app)

**Additional context**
 - Verified in Windows and ubuntu
 - Tried turning off firewall, updating dotnetcore but didn't work

**Comment by yulin-li** [comment]
Hi @rvrjp7, I tested this sample, it works. Could you pls tell us which region do you use? If you change the codes, pls also let us know.

**Comment by rvrjp7** [comment]
Hi Yulin, Thanks for your reply.
I'm still facing same issue. I'm using the free trial of speech services with region "westus".

**Comment by rvrjp7** [comment]
Hi @yulin-li  , Thanks for your reply.
I'm still facing the same issue. I'm using the free trial of speech services with region "westus". 

Note: I want to buy a speech service package to dynamically highlight words on a web page, while reading the text (using **word-level timestamps**). Please let me know if this is a proper approach to get timestamps or there is another way of getting time stamps. I've also tried to get timestamps using **"RequestWordLevelTimestamp"** method by running the helloword program from **"cognitive-services-speech-sdk-master\quickstart\csharp\dotnetcore\text-to-speech\helloworld"** folder.

Tried to find a fix from a related issue: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/489 but didn't get any solution.

**Comment by rvrjp7** [comment]
Hi @yulin-li  , Thanks for your reply.
I'm still facing the same issue. I'm using the free trial of speech services with region "westus". 

Note: I want to buy a speech service package to dynamically highlight words on a web page, while reading the text (using **word-level timestamps**). Please let me know if this is a proper approach to get timestamps or there is another way of getting timestamps. I've also tried to get timestamps using **"RequestWordLevelTimestamp"** method by running the helloword program from **"cognitive-services-speech-sdk-master\quickstart\csharp\dotnetcore\text-to-speech\helloworld"** folder.

I've also tried to find a fix from a related issue: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/489 but didn't get any solution.

**Comment by yulin-li** [comment]
Hi @rvrjp7 

It's very weird, as this is a simple sample. Could you follow [this](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging) to enable the logging and paste the log here?

The `WordBoundary` is the right way to get the time stamps of TTS, while `RequestWordLevelTimestam` is for SR, which you should not use.

**Comment by rvrjp7** [comment]
Hi @yulin-li ,
I've attached logfile.txt ( refer line 126 where the error occurred for the first time) and terminal image.
( I've used VSCode here, but the same error occurs in visual studio 2017 as well)

[logfile.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4275361/logfile.txt)

![CMD_output](https://user-images.githubusercontent.com/35190682/75676641-ad046500-5caf-11ea-9705-f970c9661da9.png)

**Comment by yulin-li** [comment]
Looks it's a key issue. I use a paid key then it works. When I use a free key, I got the same error with you. It's very odd... We will take further look. Sorry for the inconvenience.

**Comment by pankopon** [comment]
@yulin-li Is this still a valid bug, is there a fix?

**Comment by oscholz** [comment]
@rvrjp7 I've opened a bug in our backlog. Once we resolve the bug, we will comment here to let you know what we found. Thank you for reporting this!

**Comment by yulin-li** [comment]
I tested this issue today, and confirmed this issue has been fixed.
