### ISSUE TITLE
Documentation improvement for macOS

### ISSUE THREAD

**Issue by karel1980** [Azure-Samples/cognitive-services-speech-sdk#516]
**Is your feature request related to a problem? Please describe.**
The python quickstart sample that accesses the microphone did not work out of the box for me on macOS.
I needed to grant access to the microphone to the 'Terminal' application via the 'privacy' tab.

![image](https://user-images.githubusercontent.com/153021/75115810-6933af00-5662-11ea-9692-080028e4f349.png)

**Describe the solution you'd like**
It would be nice if the documentation mentioned this (or if it already does to mention it in a place that's more likely to be seen by the average user).

I haven't found a way to make the java sample work (running from Intellij). I think it could be a similar reason, but intellij is not in the list of applications that can be granted access to the microphone.

**Comment by oscholz** [comment]
I made the change under Build and Run app in [this document](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/speech-to-text-from-microphone?pivots=programming-language-python). Should be live by 4/28.
