### ISSUE TITLE
"Transcription failed. Status: Authentication failed for recordings URI." error during Batch Transcriptions.

### ISSUE THREAD

**Issue by zhangwexxx** [Azure-Samples/cognitive-services-speech-sdk#518]
I am trying to use the batch transcription C# code (https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/csharp) to transcribe audio files stored in azure storage blob.

I set the azure storage blob container to "Public".
Before I stored three audio files in azure storage blob "https://311calltranscription.blob.core.windows.net/audio-files". I got "Transcription failed. Status: Authentication failed for recordings URI." error. I deleted two files and just keep one file to try. I still get the same "Transcription failed. Status: Authentication failed for recordings URI." error.
I tried the two URLS:
private const string RecordingsBlobUri = "https://311calltranscription.blob.core.windows.net/audio-files";
or 
private const string RecordingsBlobUri = "https://311calltranscription.blob.core.windows.net/audio-files/Call1.mp3";

I can get the audio through a browser by using https://311calltranscription.blob.core.windows.net/audio-files/Call1.mp3

Could you please to help me to resolve this problem,

**Comment by zhouwangzw** [comment]
I tried a batch request using your blob URL "https://311calltranscription.blob.core.windows.net/audio-files/Call1.mp3" . and got the same error as you mentioned. Also tried to access it via browser, failed too. But when I tried with my own public accessible blob uri, and it succeeded. I suspect that the blob URL has not been made public accessible. Could you please double check whether you have  granted "anonymous read access to blob" to the container "audio-files"?

Thanks,
Zhou

**Comment by zhangwexxx** [comment]
Hello Zhou,

I checked and confirmed that I have granted "anonymous read access to blob" to the container "audio-files". Please see the following picture. I reset it to Container "anonymous read access to blob" again. Please see the picture.

I asked my colleague to try the blob URL "https://311calltranscription.blob.core.windows.net/audio-files/Call1.mp3<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2F311calltranscription.blob.core.windows.net%2Faudio-files%2FCall1.mp3&data=02%7C01%7Cwei.zhang%40ottawa.ca%7C65a5de793fc443270d4008d7b975f891%7Cdfcc033ddf874c6ea1b88eaa73f1b72e%7C0%7C0%7C637181789186519246&sdata=%2F8PMt0x8kSS7z%2FYLuNQNzpKiaSjnMgl7BGkBc78gamQ%3D&reserved=0>" through a browser. He do not have account on Azure Storage, and he can open the audio file.

I think there is something wrong with the “Speech to Text” service.

Thanks,

Wei

[cid:image002.jpg@01D5EBB8.8A578900]
[cid:image004.jpg@01D5EBB8.8A578900]

**Comment by zhouwangzw** [comment]
I am unable to see the pictures you mentioned. 
Instead of using "public anonymous access to the blob", another option is to create a SAS URL to the blob and pass it as recordingUrl. Could you please try whether this works?

**Comment by zhangwexxx** [comment]
Hello,

For the SAS URL, I got
Connection string:
BlobEndpoint=https://311calltranscription.blob.core.windows.net/;TableEndpoint=https://311calltranscription.table.core.windows.net/;SharedAccessSignature=sv=2019-02-02&ss=b&srt=sco&sp=rwdlac&se=2021-02-20T03:06:37Z&st=2020-02-19T19:06:37Z&spr=https&sig=o7ojMvlgBHAgs8hCfgR5GtDUKrDF1fua1lUKP9bgPKI%3D

SAS token
?sv=2019-02-02&ss=b&srt=sco&sp=rwdlac&se=2021-02-20T03:06:37Z&st=2020-02-19T19:06:37Z&spr=https&sig=o7ojMvlgBHAgs8hCfgR5GtDUKrDF1fua1lUKP9bgPKI%3D

Blob service SAS URL
https://311calltranscription.blob.core.windows.net/?sv=2019-02-02&ss=b&srt=sco&sp=rwdlac&se=2021-02-20T03:06:37Z&st=2020-02-19T19:06:37Z&spr=https&sig=o7ojMvlgBHAgs8hCfgR5GtDUKrDF1fua1lUKP9bgPKI%3D

How do I use the token in the Csharp sample code?

Thanks,

Wei

**Comment by zhouwangzw** [comment]
Please use a [Service SAS](https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas), but not a account SAS. You can go to portal.azure.com, select the blob file you want to transcribe, and then click on "..."->Generate SAS, and grant Read permission. After "Generate SAS token and URL, just copy the Blob SAS URL and use it as RecordingUri. 

It is also possible to generate the SAS using C# as described [here](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-service-sas-create-dotnet)

Thanks,
Zhou

**Comment by zhangwexxx** [comment]
Hello,

Followed your instruction, I got:
Blob SAS token
sp=rcwd&st=2020-02-25T16:20:14Z&se=2021-02-26T00:20:14Z&spr=https&sv=2019-02-02&sr=b&sig=8BLbsc1v9kzmrm5fO2nuKG7n4CkJExq8jsAxTcQKcA0%3D

Blob SAS URL
https://311calltranscription.blob.core.windows.net/audio-files/Call1.mp3?sp=rcwd&st=2020-02-25T16:20:14Z&se=2021-02-26T00:20:14Z&spr=https&sv=2019-02-02&sr=b&sig=8BLbsc1v9kzmrm5fO2nuKG7n4CkJExq8jsAxTcQKcA0%3D

I used https://311calltranscription.blob.core.windows.net/audio-files/Call1.mp3?sp=rcwd&st=2020-02-25T16:20:14Z&se=2021-02-26T00:20:14Z&spr=https&sv=2019-02-02&sr=b&sig=8BLbsc1v9kzmrm5fO2nuKG7n4CkJExq8jsAxTcQKcA0%3D for private const string RecordingsBlobUri 

I still got :

Starting transcriptions client...
Deleting all existing completed transcriptions.
Created transcription with id c5f88d32-9785-4659-b696-0efd8ec09924.
Checking status.
Transcriptions status: 0 completed, 0 running, 1 not started yet
Transcriptions status: 0 completed, 0 running, 1 not started yet
Transcriptions status: 0 completed, 1 running, 0 not started yet
Transcription failed. Status: Authentication failed for recordings URI.
Transcriptions status: 1 completed, 0 running, 0 not started yet
Press any key...

**Comment by zhouwangzw** [comment]
Yesterday I tried with the audio blob URI you provided, and got it transcribed correctly (I am using westus.cris.ai, summary below. removed other information for privacy reason). But when I today tried to investigate further why your request failed, I found that the audio URI is not valid anymore. Both batch request and curl failed to download the audio. Is the blob not available anymore?
I also tried with my own audio with SAS URL, which works correctly. And it seems that we have not received similar reports from other users. 
Sorry for inconvience. Please let us know how we can best help you. If you do not want to share the audio publicly, you can create an Azure Support Ticket, so that we can share information there privately.

"statusMessage": "None.",
  "lastActionDateTime": "2020-02-27T14:42:33Z",
  "status": "Succeeded",
  "id": "8cad1bf7-ab18-4690-XXXX-XXXXXXXXXXXX",
  "createdDateTime": "2020-02-27T14:41:24Z",
"recordingsUrl": "https://311calltranscription.blob.core.windows.net/audio-files/Call1.mp3?sp=rcwd&st=2020-02-25T16:20:14Z&se=2021-02-26T00:20:14Z&spr=https&sv=2019-02-02&sr=b&sig=8BLbsc1v9kzmrm5fO2nuKG7n4CkJExq8jsAxTcQKcA0%3D",

Thanks,
Zhou

**Comment by zhangwexxx** [comment]
Hello,

Sorry, my colleague had removed that file and added some new audio files into the storage blob. I added it back, so you can check “https://311calltranscription.blob.core.windows.net/audio-files/Call1.mp3”

I got some new errors, I think my code did not change.  I do not know what happened. Could you please help me to find out the reasons?

Thanks,

Wei

System.AggregateException: 'One or more errors occurred.'

NotImplementedException: The method or operation is not implemented.

This exception was originally thrown at this call stack:
    BatchClient.BatchClient.GetAsync<TResponse>(string) in batchclient.cs<navigate-to-context:0>
                System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
                System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter.GetResult()
    BatchClient.Program.TranscribeAsync() in program.cs<navigate-to-context:4>

**Comment by zhangwexxx** [comment]
Hello,

I figured out the new problem. My colleague has change the access key.
But the old problem is still at there.

Thanks,

Wei

From: Zhang, Wei
Sent: February 28, 2020 9:25 AM
To: Azure-Samples/cognitive-services-speech-sdk <reply@reply.github.com>; Azure-Samples/cognitive-services-speech-sdk <cognitive-services-speech-sdk@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [Azure-Samples/cognitive-services-speech-sdk] "Transcription failed. Status: Authentication failed for recordings URI." error during Batch Transcriptions. (#518)

Hello,

Sorry, my colleague had removed that file and added some new audio files into the storage blob. I added it back, so you can check “https://311calltranscription.blob.core.windows.net/audio-files/Call1.mp3”

I got some new errors, I think my code did not change.  I do not know what happened. Could you please help me to find out the reasons?

Thanks,

Wei

System.AggregateException: 'One or more errors occurred.'

NotImplementedException: The method or operation is not implemented.

This exception was originally thrown at this call stack:
    BatchClient.BatchClient.GetAsync<TResponse>(string) in batchclient.cs<navigate-to-context:0>
                System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
                System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter.GetResult()
    BatchClient.Program.TranscribeAsync() in program.cs<navigate-to-context:4>

**Comment by zhouwangzw** [comment]
I can transcribe the new audio URI correctly, and got text results (the audio length is 69.2 seconds). So the audio URI looks ok.

The exception you showed is thrown when the response is not successful or has wrong content type (as the code [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/csharp/batchclient.cs#L196) shows). If you can debug to see what the response is returned, you may know what is wrong.

Thanks,
Zhou

**Comment by zhangwexxx** [comment]
Hello Zhou,


With the "recordingsUrl": "https://311calltranscription.blob.core.windows.net/audio-files/Call1.mp3?sp=rcwd&st=2020-02-25T16:20:14Z&se=2021-02-26T00:20:14Z&spr=https&sv=2019-02-02&sr=b&sig=8BLbsc1v9kzmrm5fO2nuKG7n4CkJExq8jsAxTcQKcA0%3D<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2F311calltranscription.blob.core.windows.net%2Faudio-files%2FCall1.mp3%3Fsp%3Drcwd%26st%3D2020-02-25T16%3A20%3A14Z%26se%3D2021-02-26T00%3A20%3A14Z%26spr%3Dhttps%26sv%3D2019-02-02%26sr%3Db%26sig%3D8BLbsc1v9kzmrm5fO2nuKG7n4CkJExq8jsAxTcQKcA0%253D&data=02%7C01%7Cwei.zhang%40ottawa.ca%7Ca3df5be7235d47087d3a08d7bc250a80%7Cdfcc033ddf874c6ea1b88eaa73f1b72e%7C0%7C0%7C637184739588763375&sdata=QY73yFzFKTcCh1MS%2BuzCAXtR%2Bs%2FYe1AXF54V2sf7G00%3D&reserved=0>", the sample program is successfully get the transcription of the audio file. But that is just for one audio file.

I would like to get the transcription from multiple audio files  in the folder https://311calltranscription.blob.core.windows.net/audio-files. How to do it?

Thanks,

Wei

**Comment by zhouwangzw** [comment]
Glad to hear that it works for you too. 

The current batch API supports only 1 audio URI in each transcription request. If you want to transcribe all files in a blob container, you need to write code to list available audio files in that folder and pass each blob URI to build a separate transcription request.

We are working on new API which will supports Azure storage container. It will allows you to pass the container URI and all audios inside the container will be transcribed within a single request. The new API will probably become available in March. Please stay tuned.

Thanks,
Zhou

**Comment by zhangwexxx** [comment]
Hello Zhou,

Thank you very much for your help.

Wei

**Comment by zhouwangzw** [comment]
Thank you! 
I am closing the issue. If you have further questions, please re-open it or open a new one. 

Zhou

**Comment by CloudBreadPaPa** [comment]
This is very confusing. It's a "batch" job, and it's hard to understand that it only handles one file, not the entire files in container. Something more needs documentation in Microsoft docs site.
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/from-blob?pivots=programming-language-python

**Comment by zhouwangzw** [comment]
The new V3 API does not support container or multiple audio URLs. Please use the V3 API. https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription.

Thanks,

**Comment by ronawaz** [comment]
I am having very similar problem, I am testing on local host.

**Comment by newworld0** [comment]
Hi there, the API works nicely when using Container URI, the only issue I am having, which I am stuck at is getting to process files in only one subdir. The scenario here is , in the container there are 3 folders, Audio-Input , Processed, and Transcript-Out directories. even after I moved the files into the processed dire the API still process them, I tried to rename the extension like .old , also did not work, I tried to get the file list from the blob using segment sync, but that gives me only the file names and the API needs array of URI's. any suggestion or method you can provide to force the API to use a subdir and not the entire container or  how to build Uri's for the list of files. thanks an advance!
