### ISSUE TITLE
text translate error

### ISSUE THREAD

**Issue by wall3001** [Azure-Samples/cognitive-services-speech-sdk#520]
use texttranslate  rest api
use text translate chinese -- ko
你好  -->정말 
and then ko--chinese
정말 -->真的 
I use other translate app.It make correct.
你好--->안녕하세요

**Comment by swmachan** [comment]
Thanks @wall3001. This is a bug and we are working on fixing it. Will keep you updated once the fix is live.

**Comment by pankopon** [comment]
@swmachan Has the fix been released by now, can we close this issue?

**Comment by swmachan** [comment]
@pankopon - the fix is released and this issue can be closed

**Comment by oscholz** [comment]
Closing this.
