### ISSUE TITLE
continuous Recognition Source Language Auto Detection Don’t return NOMATCH 

### ISSUE THREAD

**Issue by sjtuxiaoming** [Azure-Samples/cognitive-services-speech-sdk#523]
**Describe the bug**
I have been testing the continuousRecognitionWithFileAndSourceLanguageAutoDetection. 
code  from here: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console
The Language Auto Detection needs to config at most two kinds of language.

**To Reproduce**
1. eg: My input is a Japanese news wav which is broadcast by Japanese while my config is 
`        AutoDetectSourceLanguageConfig autoDetectSourceLanguageConfig = AutoDetectSourceLanguageConfig.fromLanguages(Arrays.asList("en-US", "zh-CN"));`
2.  input is a Japanese news wav which is broadcast by Japanese

**Expected behavior**
So my expect is that the return looks like “RECOGNIZING: Langauge=NOMATCH”, but the fact is result always choose one of the config language with the max likelihood.

**Version of the Cognitive Services Speech SDK**
 <dependency>
      <groupId>com.microsoft.cognitiveservices.speech</groupId>
      <artifactId>client-sdk</artifactId>
      <version>1.9.0</version>

**Platform, Operating System, and Programming Language**
 - OS: MacOS Mojava 10.14.6 
 - Programming language:  Java

**Additional context**
Is it a bug or the design method without consideration about this issue ?
Thanks very much! Looooking forward reply. 3ks.

**Comment by pankopon** [comment]
Hi, the current behavior is as designed, the service always makes its best guess between the two configured languages. We are checking if there are any plans to change this, will get back to you soon.

**Comment by sjtuxiaoming** [comment]
> Hi, the current behavior is as designed, the service always makes its best guess between the two configured languages. We are checking if there are any plans to change this, will get back to you soon.

Thanks for your quick reply and looking forward to new change. While on the version , do we have any ways to get the detail probability  of either configured language ?

**Comment by pankopon** [comment]
Hi, unfortunately there is no such detail available at the moment. The feature was originally designed to be used in a situation with input in max two known languages. However, your feedback has been noted, and there is discussion about adding more options in the future.

**Comment by jhakulin** [comment]
Closing the issue as we have entered the item into our future release planning
