### ISSUE TITLE
Missing documentation regarding language support of sentiment analysis

### ISSUE THREAD

**Issue by tillahoffmann** [Azure-Samples/cognitive-services-speech-sdk#524]
The [documentation](https://docs.microsoft.com/en-gb/azure/cognitive-services/speech-service/batch-transcription#the-batch-transcription-api) for `AddSentiment` in batch mode does not list which languages support the sentiment feature. Is there an authoritative list?

**Comment by wolfma61** [comment]
please see here:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription#sentiment-analysis
