### ISSUE TITLE
SPXERR_START_RECOGNIZING_INVALID_STATE_TRANSITION exception

### ISSUE THREAD

**Issue by Greta-A** [Azure-Samples/cognitive-services-speech-sdk#525]
**Describe the bug**
Running the Hololens 2 Tutorial: _Integrating and using speech recognition and transcription_ in the editor or in the device itself, fails with an exception: ApplicationException: Exception with an error code: 0x13 (SPXERR_START_RECOGNIZING_INVALID_STATE_TRANSITION). This happens right after adding the Lunarcom Wake Word Recognizer and filling in the wake and dismiss words. When this happens, the blue terminal in the scene disappears and the exception is thrown.

**To Reproduce**
Follow all the steps in the Hololens tutorial, to step 25

**Expected behavior**
Scene runs in Unity editor without issues and can build to Hololens 2 and see the terminal instructions. 

**Version of the Cognitive Services Speech SDK**
1.9.0

**Platform, Operating System, and Programming Language**
Windows 10 version 1903
Unity 2019.2.5fl

**Additional context**
Full Log trace:

ApplicationException: Exception with an error code: 0x13 (SPXERR_START_RECOGNIZING_INVALID_STATE_TRANSITION)
Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail (System.IntPtr hr) (at <e457ba9a5c92456198197a11a4e7e701>:0)
Microsoft.CognitiveServices.Speech.Recognizer.StartContinuousRecognition () (at <e457ba9a5c92456198197a11a4e7e701>:0)
Microsoft.CognitiveServices.Speech.Recognizer.DoAsyncRecognitionAction (System.Action recoImplAction) (at <e457ba9a5c92456198197a11a4e7e701>:0)
Microsoft.CognitiveServices.Speech.SpeechRecognizer.<StartContinuousRecognitionAsync>b__44_0 () (at <e457ba9a5c92456198197a11a4e7e701>:0)
System.Threading.Tasks.Task.InnerInvoke () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Threading.Tasks.Task.Execute () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
LunarcomWakeWordRecognizer+<BeginRecognizing>d__11.MoveNext () (at Assets/Lunarcom/Lunarcom Scripts/LunarcomWakeWordRecognizer.cs:82)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:114)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

**Comment by hakulinenjarno** [comment]
Thanks for the feedback, we will look further.
This problem might happen if e.g. microphone/stream stops before recognition is stopped. I can reproduce this when using Unity microphone and streams to Speech SDK.

**Comment by Lenovezhou** [comment]
I have the same problem. This error occurs when hololens2 is running, and then the logic cannot run, and the voice cannot be recognized. Please resolve as soon as possible.

**Comment by jhakulin** [comment]
thanks for feedback, I'll try to prioritize higher this. Any possibility to get log using https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging, see UWP section ?

**Comment by jhakulin** [comment]
@Lenovezhou @Greta-A  Do you see the issue when using following sample ? https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/unity/keywordrecognizer

**Comment by Lenovezhou** [comment]
Hi jhakulin.I have used the sample of this link to test it on hololens2。No error is reported, but an errolog like this will be displayed
![HoloLens2ErrorLog](https://user-images.githubusercontent.com/19359233/76067968-4347cc00-5fcb-11ea-877f-7da934c61f0e.png)

**Comment by Lenovezhou** [comment]
Sorry, I used this samplehttps://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/unity/speechrecognizer

**Comment by Greta-A** [comment]
The link to 'download the code to your PC' inside the link https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/unity/keywordrecognizer does not work; 404 error

**Comment by jhakulin** [comment]
Thanks for pointing the issue with link, that link in the README.md may not be valid as the sample code for keywordrecognizer is under this GitHub project, here:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/unity/keywordrecognizer/Assets/Scripts

**Comment by Lenovezhou** [comment]
@jhakulin   @Greta-A , I recently used the tutorial of this connection, and successfully recognized my language and translated it on hololens1 and hololens2. Thank you!

https://docs.microsoft.com/en-US/windows/mixed-reality/mrlearning-speechsdk-ch1

**Comment by jhakulin** [comment]
Thanks for the information, closing the case.

**Comment by amitguptampct12** [comment]
Got issue in iOS:-
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Exception with an error code: 0x13 (SPXERR_START_RECOGNIZING_INVALID_STATE_TRANSITION)
