### ISSUE TITLE
npm install of node failing on integrity checks (again)

### ISSUE THREAD

**Issue by brianlmerritt** [Azure-Samples/cognitive-services-speech-sdk#527]
**Describe the bug**
Integrety checksums are failing again for the javascript node install.  This is with several node versions.

**To Reproduce**
1. ...Clone this repo then cd to `quickstart/javascript/node` 
2. ...run `npm install`

**Expected behavior**
npm install should work - e.g. it should install.

**Version of the Cognitive Services Speech SDK**
1.9.0, 1.9.1, 1.8.1 are all failing.

**Platform, Operating System, and Programming Language**
 - OS:LINUX Ubuntu 18.04
 - Hardware - x64
 - Programming language: JavaScript
 - Browser na

**Additional context**
npm install returns

 tarball data for microsoft-cognitiveservices-speech-sdk@1.9.0 (sha512-B1z9cOQSfQxHgjnbkx4NBj5YOHz0ymUBnXYec+thgwRsfJntKfWGJEdarvEjiHr0+UkC+ejuCaFshnHgtwgphQ==) seems to be corrupted. Trying one more time.
npm ERR! code EINTEGRITY
npm ERR! sha512-B1z9cOQSfQxHgjnbkx4NBj5YOHz0ymUBnXYec+thgwRsfJntKfWGJEdarvEjiHr0+UkC+ejuCaFshnHgtwgphQ== integrity checksum failed when using sha512: wanted sha512-B1z9cOQSfQxHgjnbkx4NBj5YOHz0ymUBnXYec+thgwRsfJntKfWGJEdarvEjiHr0+UkC+ejuCaFshnHgtwgphQ== but got sha512-Iq833JWy9D5uaAmQWr1aifOdxRF8BOskL89EnL/4VAB0QCSOcVk1g9cnRDZ/b/PXo6XnjcbIH69AL/owNa4ETw==. (794682 bytes)

**Comment by rhurey** [comment]
Opened a PR to update the version used in the quickstarts to 1.10.0

**Comment by brianlmerritt** [comment]
Thanks - all good!
