### ISSUE TITLE
How is the Speech SDK Selecting Which Endpoint To Use?

### ISSUE THREAD

**Issue by ththiem** [Azure-Samples/cognitive-services-speech-sdk#530]
We use the streaming SDK over websocket to do speech-to-text and I'm wondering how the system determines which endpoint ot use.

We create the speech config using the .FromEndpoint( Uri, subscription key) method, where we provide the url to the endpoint, such as:

wss://westus.stt.speech.microsoft.com/speech/recognition/dictation/cognitiveservices/v1

And then our subscription key. We've always done it this way and it has always worked, however we have 2 different endpoint Ids setup in our subscription, and each of them shows a unique URL when viewed in the https://westus.cris.ai portal, such as:

wss://westus.stt.speech.microsoft.com/speech/recognition/dictation/cognitiveservices/v1 **?cid=endpointIdGuid**

If we don't include that ?cid= parameter in the URL, which endpoint is it using?

Same question regarding creating a speech config using .FromSubscription( subscriptionKey, region). What endpoint does it select?

**Comment by chrisbasoglu** [comment]
We highly recommend you do not use FromEndpoint() unless you are targeting a non-standard URI -- which you are not. FromEndpoint, you will run into issues later should you wish to set or use certain features. Instead, use FromSubscription(Key, Region) and for Region, use "westus".  Off of the config, there is a property called EndpointId  and set that with your endpointIdGuid.  By using 

If you don't set EndpointId  (or set cid quereyParam) you will get an endpoing for unadapted speech.
