### ISSUE TITLE
No way to upgrade or modify language & acoustic model for endpoints?

### ISSUE THREAD

**Issue by ththiem** [Azure-Samples/cognitive-services-speech-sdk#531]
**Describe the bug**
According to the portal, our older endpoints are configured to use the **20180601 (v3.0 Beta Unified)** language and acoustic model while our newer endpoints have the **20190520 (v4.14 Unified)** model. They're not custom models, they're supposed to be whatever the default base model is. There's no functionality to change the model in use by an endpoint, nor upgrade these to a newer version. Is deleting and recreating endpoints once in a while the only way to ensure we're on the latest version? We cannot be doing this in production environments.

**To Reproduce**
1. Login to cris.ai portal
2. Go to Endpoints, click details
3. View language model version

**Expected behavior**
That endpoints are always on the latest version of the default base model.

**Version of the Cognitive Services Speech SDK**
Latest

**Comment by bexxx** [comment]
Please use our new portal at https://speech.microsoft.com/.
Here you can use the button "change model" to update an existing endpoint with a new model.

**Comment by ththiem** [comment]
Unless you're looking at some internal preview version of that portal, there is nothing at all in there. There are no endpoints, no Ids, no information, nothing at all. Just a radio button to select an overall speech resource, and speech studio that contains nothing. None of what you're describing exists at all under any menu.

![image](https://user-images.githubusercontent.com/15839533/76363001-5fa37b80-62df-11ea-9c09-cebcf1a097f8.png)

**Comment by bexxx** [comment]
Please select the subscription of the endpoint in the first screen (speech resources + go to studio).
Then you need to create a new project (everything in the UI is project based). Click it to select the project scope and then go to deployments. The UI will prompt to migrate existing endpoints into the project, please select "connect".

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/10616556/76413614-09454400-6396-11ea-9aaf-4c60ee38dd24.png">

Now you should be able to see your existing endpoint in the new portal UI.

"Connecting" the endpoint does not have any side effect on the functionality of the endpoint, it's just a scoping in the UI. You can also remove or change the connect later on.
