### ISSUE TITLE
How to access Azure Blob Storage secured by firewalls from Cognitive Service?

### ISSUE THREAD

**Issue by tuanle07** [Azure-Samples/cognitive-services-speech-sdk#532]
I have an Azure Blob storage account which is only accessible from selected networks using firewalls and virtual networks settings. I keep receiving `Authentication failed` error when running Cognitive service batch process. How can I solve this problem?

**Comment by wolfma61** [comment]
we are planning on supporting Service Tags in the near future (https://docs.microsoft.com/en-us/azure/virtual-network/service-tags-overview). This allows you to identify the address range that the speech service will use. This should be available on all speech service regions in the next couple of month.

there is more work planned on more security features, but this is a little bit further out.

Wolfgang

**Comment by tuanle07** [comment]
> we are planning on supporting Service Tags in the near future (https://docs.microsoft.com/en-us/azure/virtual-network/service-tags-overview). This allows you to identify the address range that the speech service will use. This should be available on all speech service regions in the next couple of month.
> 
> there is more work planned on additional networking features, but this is a little bit further out.
> 
> Wolfgang

Hi Wolfgang,

Do you have a specific timeline for this feature? Thanks.

**Comment by wolfma61** [comment]
I'll post an update here, as soon as I have the details...

**Comment by pankopon** [comment]
@wolfma61 Any news/roadmap/update on the Service Tags support?

**Comment by fmegen** [comment]
We have rolled out ServiceTags for a limited set of regions initially and are currently in the process of expanding the set of regions which known ip addresses for our services. In fact, there are 6 more regions to be supported in the next few days.

Can you please state for which regions you are looking to use ServiceTags? thanks!

**Comment by oscholz** [comment]
@tuanle07 here are the regions we've rolled ServiceTags out to:
Australia East
Central India
North Europe
Southeast Asia
East US
East US2
South Central US
West US
West Central US
West Europe
West US 2
These should have them in the next couple of days (if not already). Other regions will follow over the next weeks.
Please let us know if you have further questions. I will close this issue for the time being. Feel free to reopen if you have trouble...

**Comment by tuanle07** [comment]
@oscholz : do you have any document explaining how to use this feature? Thanks.
