### ISSUE TITLE
Is there a way to authenticate access to Cognitive service via managed identity?

### ISSUE THREAD

**Issue by tuanle07** [Azure-Samples/cognitive-services-speech-sdk#535]
Currently, we need to send the `SubscriptionKey` in the request header when making a batch transcription request. I prefer using IAM role identity to allow access to the service instead. Just wondering if there is a way to do it as I can’t seem to find any documentations about this. Thanks.

**Comment by PanosPeriorellis** [comment]
Not at the moment but we do plan to support this feature in the future.

**Comment by juchom** [comment]
I just hit the same problem.

Is there an issue we can track to know when this feature will be available or should this one be reopen?

Thanks

**Comment by tuanle07** [comment]
@PanosPeriorellis : should we reopen this issue so that we can have something to track the progress as suggested by @juchom ? Thanks.
