### ISSUE TITLE
Why are AudioFileResults, CombinedResults, SegmentResults, and NBest defined as a list?

### ISSUE THREAD

**Issue by tuanle07** [Azure-Samples/cognitive-services-speech-sdk#536]
I couldn’t seem to find any documentations explaining what `AudioFileResults`, `CombinedResults`, `SegmentResults`, and `NBest` are. I always see 1 item existing in these lists so far so I have no idea why they are defined as lists either. Thanks.

**Comment by PanosPeriorellis** [comment]
Combined results contains a combination of the segments. it is a convenient way to extract the entire audio transcript from the JSON. Segments are the final results list. Nbest are the top responses from the transcription decoder. AudioFileResults encapsulates the details of entire audio file. We will make sure the documentation provides a section with explanation of the returned JSON. Thank you for feedback.

**Comment by tuanle07** [comment]
@Pano

> Combined results contains a combination of the segments. it is a convenient way to extract the entire audio transcript from the JSON. Segments are the final results list. Nbest are the top responses from the transcription decoder. AudioFileResults encapsulates the details of entire audio file. We will make sure the documentation provides a section with explanation of the returned JSON. Thank you for feedback.

What is a segment btw?

**Comment by PanosPeriorellis** [comment]
As audio is streamed to the service, the service will determine segments based on features like pauses (silences) and for those segments it will generate ITN and display results and return them to the client.

**Comment by tuanle07** [comment]
@PanosPeriorellis : I see. Thanks for your explanations. They should go to the documentation as well I think. Very limited documentation available atm. Thanks.
