### ISSUE TITLE
Broken link in documentation for quick start

### ISSUE THREAD

**Issue by managedcoder** [Azure-Samples/cognitive-services-speech-sdk#541]
**Describe the bug**
The "accompanying article" link in the quick start is broken.  I think the correct link is [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-voice-assistant-csharp-uwp)

**To Reproduce**
Go to link above and look for  "accompanying article" link

**Expected behavior**

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - please be specific
 - Hardware - x64, x86, ARM, ...
 - Programming language: C#, C++, Java, JavaScript, Objective-C, Python
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific

**Additional context**
 - Error messages, log information, stack trace, ...
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by jhakulin** [comment]
Closing as fix under work
