### ISSUE TITLE
Conversation Transcription API: duration and offset completely wrong

### ISSUE THREAD

**Issue by ariksidney** [Azure-Samples/cognitive-services-speech-sdk#542]
**Describe the bug**
We upload a .wav file to the Conversation Transcription API via the Java SDK (1.10.0). The extracted text in the result looks really good, however the offsetInTicks is completely inaccurate by up to 10 seconds on our 50 seconds file.

**To Reproduce**
1. We can provide you our .wav file and code if you wish to have it.

**Expected behavior**
Since the speech to text is working really well, we expect to get quite accurate timestamps for the offset.

**Version of the Cognitive Services Speech SDK**
1.10.0

**Platform, Operating System, and Programming Language**
 - OS: OS X 10.15.3
 - Programming language: Java

**Additional context**
- The file is not recorded with the Roobo Smart Audio Dev Kit but with an iPhone 11.

**Comment by jhakulin** [comment]
@ariksidney Thanks for feedback, would be great if you can provide wave file and sample code you are using ?

**Comment by glharper** [comment]
@ariksidney Any chance you could send the wav file over for testing? Thanks.

**Comment by ariksidney** [comment]
@glharper Sorry for my late response. It looked like the bitrate from my audio file was different then it needs to be for the api. However if you still want the file, is it possible to send it to you somehow not public?
