### ISSUE TITLE
Return Speaker ID in the DetailedSpeechRecognitionResult 

### ISSUE THREAD

**Issue by josephsctan** [Azure-Samples/cognitive-services-speech-sdk#543]
**Is your feature request related to a problem? Please describe.**
On Android, it is not possible to capture audio from MIC to send to Speaker ID (ProjectOxford.SpeakerRecognition)  while streaming Audio to  SpeechRecognizer. 

**Describe the solution you'd like**
Return Speaker ID in the DetailedSpeechRecognitionResult 

**Describe alternatives you've considered**
- tried to record audio in Android while streaming it to SpeechRecognizer (not possible - one of them will get silence)
- tried to use Azure Conversation Transcription  feature  - it requires 8 channel PCM WAV audio - not possible from an Android device 

 
**Additional context**
Trying to transcribe and analyse a conversation in real time on Android / IOS using Azure Cognitive Services, with speaker ID functionality.

**Comment by jhakulin** [comment]
Thanks for feedback, one possibility for Android device is to record audio from microphone using Android APIs and the push or pull the stream of audio to Speech SDK. Here is example how it is done in Unity (works on Android device also) using Android microphone and pushmode audio stream to Speech SDK.
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/unity/from-unitymicrophone/Assets/Scripts/HelloWorld.cs

Let me know if this would help you further.

**Comment by josephsctan** [comment]
Hi There,

Thanks - will give this a go.

**Comment by jhakulin** [comment]
Closing this, please reopen if you need more information/issues exists

**Comment by josephsctan** [comment]
Hi @jhakulin, 

I managed to get recording and speech recognition working simultaneously using a push audio stream. So, it  **IS**  possible to get speaker id by sending snippets of audio to the Speaker Recognition API, from inside the Speech Recognition "Recognized" event handler.

However, this is obviously inefficient, since the same data is sent twice, once to speech recognition, and again to speaker ID recognition. Also, there is a delay between when the text is recognized, and the speaker is identified.

It would be far more efficient if there was a way to chain (or integrate) the speech recognition to the speaker recognition, so that we only have to send WAV data over the line once, and get SpeakerId in DetailedSpeechRecognitionResult. Something similar is possible with the Azure Bot Framework, where we can get LUIS intents and also Azure QNA responses in the same call. 

Thanks
Joseph

**Comment by jhakulin** [comment]
@josephsctan We are adding speaker recognition functionality to Speech SDK release in May timeframe, which you can use simultaneously with SpeechRecognizer. Also for future releases we will make it easier to integrate those two functionalities together.
