### ISSUE TITLE
Diarization does not work for nl-NL locale

### ISSUE THREAD

**Issue by machteldbogels** [Azure-Samples/cognitive-services-speech-sdk#544]
I am working with the batch api in python to transcribe from a blob file in Dutch (the nl-NL locale). The transcription itself works well, but for the diarization I only get **"SpeakerId": null** after setting both diarization & addworldleveltimestamps to true. 

```
properties = {
        # 'PunctuationMode': 'DictatedAndAutomatic',
        # 'ProfanityFilterMode': 'Masked',
        'AddWordLevelTimestamps': 'True',
         'AddDiarization': 'True'
        # 'AddSentiment': False,
        # 'TranscriptionResultsContainerUrl': "<results container>"
    }
```
It does not throw the error that diarization is not supported for this locale. The audio file is a very clear conversation between a man & woman so that ~should not be the issue. Is there anything else I should try?

**Comment by zhouwangzw** [comment]
Diarization is language agnostic, but currently it only supports mono audio. Stereo audio is not supported yet.

Thanks,
Zhou

**Comment by machteldbogels** [comment]
I thought I was using a mono file but it turns out I wasn't! Works now, thank you 👍

**Comment by BrianMouncer** [comment]
Thanks for the update.
