### ISSUE TITLE
Intent not recognize

### ISSUE THREAD

**Issue by ratneshkumarcs** [Azure-Samples/cognitive-services-speech-sdk#545]
**Describe the bug**
Intent not recognize

**To Reproduce**
1. download C# sample and replace key as per https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-recognize-intents-from-speech-csharp
2. Application only show Spoken word in TEXT 

**Expected behavior**
it should send JSON result if matched intent found.   
"
### **"Say something...
RECOGNIZED: Text=Turn off the light.
    Intent not recognized.
Please press Enter to continue."***

I already created LUIS app on LUIS.AI and link with Azure and after LUIS app created i can see same app on Azure and took Key and end point from "Key & endpoint" menu and same used in application.

**Comment by glharper** [comment]
@ratneshkumarcs Did you also get a LUIS application ID from the Application Settings menu item in the "Manage" Tab for your LUIS app on preview.luis.ai? If so, could you try pasting it into the C# sample code, replacing "YourLanguageUnderstandingAppId"?

(For LUIS applications, you need two keys (the LUIS subscription key and the LUIS application ID) and the LUIS region for your resource. I didn't see the LUIS application ID mentioned in the issue description.)
