### ISSUE TITLE
Prebuild Entity DateTimeV2 Bug

### ISSUE THREAD

**Issue by SOliasS** [Azure-Samples/cognitive-services-speech-sdk#546]
DateTimeV2 converts back wrong values if no complete date is given
For example :"XXXX-04-15" is still returned as "2019-04-15"
and also if month is missing it just randomly picks one....

Another example:
"Dienstag 11:00 uhr" (Tuesday 11 o Clock)got recognized but translated to 
2020-02-11 instead of  2020.03.13
the timex output is completely screwed here XXXX-WXX-2.
The Time is also completely missing

"Mittwoch 12:00 uhr" (Wednesday 11 oclock"
2020-02-12 instead of 2020-03-18

And sometimes when saying "18.4"
i sometime get "XXXX-04-18" and sometimes "04-18""
The Response seems completely random at times-.-

**Comment by SOliasS** [comment]
@jhakulin is there anybody in particular who could help with this isssue?

**Comment by amitkumarshukla** [comment]
@SOliasS If you can please send us the repro steps ?
Thanks

**Comment by SOliasS** [comment]
@amitkumarshukla What steps do you need?
Do you want other/ more example which times support is missing?

**Comment by SOliasS** [comment]
@amitkumarshukla any Update?

**Comment by rhurey** [comment]
It's not completely clear to me where the result is getting mangled.

From the question I'm assuming you've got an intent with an entity of type DateTimeV2 in it and are trying to recognize it.

When the date comes back wrong, is it wrong in the intent JSON returned, or in the recognized speech that's on the result.getText()?

Can you send an example of the text from the result and the JSON for what's in the LanguageUnderstandingServiceResponse_JsonResult for the entity?

I'm trying to disambiguate if the problem is in the speech->text pipeline or in the text->LUIS result pipeline.

**Comment by SOliasS** [comment]
There were two diffrent problems i think...
I think the First one is working now "15.4" => 15.04.2020
{
  "query": "15.4.",
  "topScoringIntent": {
    "intent": "None",
    "score": 0.231632113
  },
  "entities": [
    {
      "entity": "15.4.",
      "type": "builtin.datetimeV2.date",
      "startIndex": 0,
      "endIndex": 4,
      "resolution": {
        "values": [
          {
            "timex": "XXXX-04-15",
            "type": "date",
            "value": "2020-04-15"
          },
          {
            "timex": "XXXX-04-15",
            "type": "date",
            "value": "2021-04-15"
          }
        ]
      }
    },
    {
      "entity": "15",
      "type": "builtin.number",
      "startIndex": 0,
      "endIndex": 1,
      "resolution": {
        "value": "15"
      }
    },
    {
      "entity": "4",
      "type": "builtin.number",
      "startIndex": 3,
      "endIndex": 3,
      "resolution": {
        "value": "4"
      }
    }
  ]
}
The Second one is still broken "Dienstag 11 Uhr" results in strange results"2020-02-11" instead of "26.05.2020" here the problem seems that the Time is recognized as a date and it tries to find a tuesday which matches instead of recognizing that it is a day and a time combined....
{
  "query": "dienstag 11:00 uhr",
  "topScoringIntent": {
    "intent": "None",
    "score": 0.296005666
  },
  "entities": [
    {
      "entity": "dienstag 11",
      "type": "builtin.datetimeV2.date",
      "startIndex": 0,
      "endIndex": 10,
      "resolution": {
        "values": [
          {
            "timex": "XXXX-WXX-2",
            "type": "date",
            "value": "2020-02-11"
          },
          {
            "timex": "XXXX-WXX-2",
            "type": "date",
            "value": "2020-08-11"
          }
        ]
      }
    },
    {
      "entity": "11",
      "type": "builtin.number",
      "startIndex": 9,
      "endIndex": 10,
      "resolution": {
        "value": "11"
      }
    },
    {
      "entity": "00",
      "type": "builtin.number",
      "startIndex": 12,
      "endIndex": 13,
      "resolution": {
        "value": "0"
      }
    }
  ]
}

**Comment by SOliasS** [comment]
When using numbers instead of Dates it is working as expected 
```
{
  "query": "15.4. 11:30 uhr",
  "topScoringIntent": {
    "intent": "None",
    "score": 0.6714722
  },
  "entities": [
    {
      "entity": "15.4. 11:30 uhr",
      "type": "builtin.datetimeV2.datetime",
      "startIndex": 0,
      "endIndex": 14,
      "resolution": {
        "values": [
          {
            "timex": "XXXX-04-15T11:30",
            "type": "datetime",
            "value": "2020-04-15 11:30:00"
          },
          {
            "timex": "XXXX-04-15T11:30",
            "type": "datetime",
            "value": "2021-04-15 11:30:00"
          },
          {
            "timex": "XXXX-04-15T23:30",
            "type": "datetime",
            "value": "2020-04-15 23:30:00"
          },
          {
            "timex": "XXXX-04-15T23:30",
            "type": "datetime",
            "value": "2021-04-15 23:30:00"
          }
        ]
      }
    },
    {
      "entity": "15",
      "type": "builtin.number",
      "startIndex": 0,
      "endIndex": 1,
      "resolution": {
        "value": "15"
      }
    },
    {
      "entity": "4",
      "type": "builtin.number",
      "startIndex": 3,
      "endIndex": 3,
      "resolution": {
        "value": "4"
      }
    },
    {
      "entity": "11",
      "type": "builtin.number",
      "startIndex": 6,
      "endIndex": 7,
      "resolution": {
        "value": "11"
      }
    },
    {
      "entity": "30",
      "type": "builtin.number",
      "startIndex": 9,
      "endIndex": 10,
      "resolution": {
        "value": "30"
      }
    },
    {
      "entity": "4.",
      "type": "builtin.ordinal",
      "startIndex": 3,
      "endIndex": 4,
      "resolution": {
        "value": "4"
      }
    }
  ]
}
```

**Comment by rhurey** [comment]
Thanks, the JSON was extremely helpful.

We're making progress tracking this down.

**Comment by rhurey** [comment]
The root cause looks to be an issue in the text recognizer LUIS is using. I've opened https://github.com/microsoft/Recognizers-Text/issues/2123 to track it and will work to get it triaged.

Thanks for the help here.
