### ISSUE TITLE
Using KeywordRecognitionAsync only works 2 times

### ISSUE THREAD

**Issue by ksaye** [Azure-Samples/cognitive-services-speech-sdk#548]
Perhaps I misunderstand.  In the following code sample, it works 2 times but after that the event Recognized is never fired.  Is there a misconfiguration?  I am using 1.10.0 of the frameworks on .Net Core 3.1.

```
using System;
using System.Threading.Tasks;
using Microsoft.CognitiveServices.Speech;
using Microsoft.CognitiveServices.Speech.Audio;

namespace ConsoleApp1
{
    class Program
    {
        static SpeechRecognizer speechRecognizer;
        static KeywordRecognitionModel keywordRecognition;

        static async Task Main(string[] args)
        {
            keywordRecognition = KeywordRecognitionModel.FromFile(@"c:\Users\KevinSaye\Desktop\Hello_Jarvis.table");

            SpeechConfig speechConfig = SpeechConfig.FromSubscription("0e84bXXXXXXXXXXXXX0c2ce", "South Central US");

            AudioConfig audio = AudioConfig.FromDefaultMicrophoneInput();
            
            speechRecognizer = new SpeechRecognizer(speechConfig, audio);

            speechRecognizer.Recognized += SpeechRecognizer_Recognized;

            await speechRecognizer.StartKeywordRecognitionAsync(keywordRecognition);
            while (true)
            {
                Console.Write(".");
                System.Threading.Thread.Sleep(1000 * 5);
            }
        }

        static void SpeechRecognizer_Recognized(object sender, SpeechRecognitionEventArgs e)
        {
            Console.WriteLine("heard " + e.Result.Text);
        }
    }
}

```

**Comment by jhakulin** [comment]
Thanks for feedback,

Your sample code should work more than 2 times and it worked when I tried with .NET core 3.1 C# console sample app

When you say keyword, e.g. "Computer, what's the weather like" 3 times in a row the output may look like following

heard Computer
.heard Computer what's the weather like?
.heard Computer
heard Computer what's the weather like?
.heard Computer
heard Computer what's the weather like?

What happens when you try the same?

**Comment by jhakulin** [comment]
Closing the issue as not reproduced with 1.10.0 release and KWS working as expected

**Comment by jhakulin** [comment]
@ksaye Please check that your speech subscription key works ok, e.g. by running basic speech recognition test ?

**Comment by ksaye** [comment]
@jhakulin , thanks for the suggestion.  It appears that because I used the region "South Central US" instead of "SouthCentralUS" that it stopped working after 2 tries.  Great suggestion!
