### ISSUE TITLE
How to disable profanity check on speech-sdk-javascript (web)

### ISSUE THREAD

**Issue by inglesuniversal** [Azure-Samples/cognitive-services-speech-sdk#549]
I can't seem to find in your manuals, how to disable and re-enable profanity check "*****" from the sdk targeted for the web.

There are some ESL reasons why at some time we may need to have it turn on or off.

Thanks

NOTE: Amazing SDK and it keeps getting better.

**Comment by chrisbasoglu** [comment]
Here is how to do it at request time: https://docs.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/speechconfig?view=azure-node-latest#setprofanity-profanityoption-
