### ISSUE TITLE
Whom do I contact if I spot a word that is translated incorrectly?

### ISSUE THREAD

**Issue by inglesuniversal** [Azure-Samples/cognitive-services-speech-sdk#550]
Just like Google has a website where developers can improve the translation results.

Does MS-Azure have a service or contact person to address related issues?

Thanks

ESL Certified Instructor since 1996 
Regional TOEFL® Test Supervisor for our schools
Co-Founder INGLES UNIVERSAL English Learning Centers
inglesuniversal.com

**Comment by swmachan** [comment]
@inglesuniversal 
Microsoft offers a way of improving translations by creating your own custom models that can be trained to translate domain specific terminologies. Here's the portal - http://customtranslator.ai, where you can upload your documents and train the models. 

You can find more details by reading through this documentation - https://docs.microsoft.com/en-us/azure/cognitive-services/translator/custom-translator/overview
