### ISSUE TITLE
demo test file make voice to text error

### ISSUE THREAD

**Issue by jiajia1012** [Azure-Samples/cognitive-services-speech-sdk#551]
Describe the bug
I am using azure sample test error occurs when the text to audio file, reference url:https://docs.microsoft.com/en/azure/cognitive-services/speech-service/quickstarts/speech-to-text-from-file? Tabs =linux&pivots=programming-language-cpp, the same parameter is normal for Java testing, the error message is as follows：
CANCELED: Reason=1
CANCELED: ErrorCode= 5
CANCELED: ErrorDetails=Connection failed (no connection to the remote host). Internal error: 1. Error details: 2460. Please check network connection, firewall setting, and the region name used to create speech factory. SessionId: d9e45623199f411b96edaecca499a01f
CANCELED: Did you update the subscription info?
Please press a key to continue.

Expected behavior
Can be recognized normally

Version of the Cognitive Services Speech SDK
SpeechSDK-Linux-1.7.0

Platform, Operating System, and Programming Language
 - OS: Centos7
 - Hardware - x86
 - Programming language: C++

[error.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4337638/error.log)

**Comment by pankopon** [comment]
Hi, unfortunately CentOS 7 x86 is not supported by SpeechSDK 1.7.0. Officially we support RHEL/CentOS 8 x64 from SpeechSDK 1.10.0 onwards (see https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/releasenotes and https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk?tabs=linux). However, there is a way to have it working on RHEL/CentOS 7 x64 as well, we will publish instructions for this when SpeechSDK 1.11.0 is released. RHEL/CentOS target architectures other than x64 have not been tested and are not officially supported at the moment.
