### ISSUE TITLE
How to specify gender and timbre

### ISSUE THREAD

**Issue by LinJinghuidev** [Azure-Samples/cognitive-services-speech-sdk#552]
What API should I call on Android platform to specify the gender and timbre of speech synthesis

**Comment by yulin-li** [comment]
You can set the voice name by [setSpeechSynthesisVoiceName](https://docs.microsoft.com/java/api/com.microsoft.cognitiveservices.speech.speechconfig.setspeechsynthesisvoicename?view=azure-java-stable#com_microsoft_cognitiveservices_speech_SpeechConfig_setSpeechSynthesisVoiceName_String_).
The voice list is [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support#text-to-speech).

**Comment by LinJinghuidev** [comment]
I didn't find any Android calls to this API

**Comment by LinJinghuidev** [comment]
I've found it
