### ISSUE TITLE
quick start make voice to text "Connection failed" error

### ISSUE THREAD

**Issue by jiajia1012** [Azure-Samples/cognitive-services-speech-sdk#553]
Describe the bug
Yesterday's case :
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/551

According to your Suggestions, the system version has been upgraded to centos8, and the current version of GCC is 8.3.1, but the problem remains, the description and log are the same as the previous version
[error0317.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4342922/error0317.log)

I am using azure sample test error occurs when the text to audio file, reference url:https://docs.microsoft.com/en/azure/cognitive-services/speech-service/quickstarts/speech-to-text-from-file? Tabs =linux&pivots=programming-language-cpp, the same parameter is normal for Java testing, the error message is as follows：
CANCELED: Reason=1
CANCELED: ErrorCode= 5
CANCELED: ErrorDetails=Connection failed (no connection to the remote host). Internal error: 1. Error details: 2460. Please check network connection, firewall setting, and the region name used to create speech factory. SessionId: b5945a6426c346acb42b917f08e28790
CANCELED: Did you update the subscription info?
Please press a key to continue.

Expected behavior
Can be recognized normally

Version of the Cognitive Services Speech SDK
SpeechSDK-Linux-1.7.0

Platform, Operating System, and Programming Language

OS: Centos8
Hardware - x86
Programming language: C++
gcc version: 8.3.1

**Comment by jhakulin** [comment]
@jiajia1012 Did you also update Speech SDK to 1.10.0 ?

**Comment by jiajia1012** [comment]
Yes, I strictly followed the Quickstart steps and compiled helloworld under centos8, but I reported an error of Connection failed when executing./helloworld. I don't know which step went wrong,SubscriptionKey and ServiceRegion should be fine, because I tested them in the same environment using Java and everything worked fine

**Comment by jiajia1012** [comment]
@jhakulin 
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/cpp/linux/from-microphone
“wget -O SpeechSDK-Linux.tar.gz https://aka.ms/csspeech/linuxbinary”，I have confirmed version 1.10

**Comment by jhakulin** [comment]
@jiajia1012, based on the log your problem is related to OpenSSL cerificate is not found.

Please check the following instruction how to configure OpenSSL for CentOS
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-openssl-linux

Let me know if this help

**Comment by jhakulin** [comment]
@jiajia1012 One possible reason could be also that you seems to use x86 hardware. We are currently suppoorting only x64 CentOS
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk?tabs=linux

**Comment by jiajia1012** [comment]
> @jiajia1012 One possible reason could be also that you seems to use x86 hardware. We are currently supporting only x64 CentOS
> https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk?tabs=linux
Thank you very much for your reply

You reminded me to check the system version. I am x86, but when configuring LD_LIBRARY_PATH, I configured x64. Now I have changed the environment variable to x86, and running helloword has caused another error
"./helloworld: error while loading shared libraries: libMicrosoft.CognitiveServices.Speech.core.so: wrong ELF class: ELFCLASS32"

**Comment by jiajia1012** [comment]
I want to confirm again whether the SDK does not support x86 centos8, if so, I have to rebuild the new system

**Comment by jiajia1012** [comment]
> @jiajia1012 One possible reason could be also that you seems to use x86 hardware. We are currently supporting only x64 CentOS
> https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk?tabs=linux

Thanks for your reply. I have confirmed that the system is x64 and centos8 should be available

[root@centos8 home]# getconf LONG_BIT
64

**Comment by jiajia1012** [comment]
> @jiajia1012, based on the log your problem is related to OpenSSL cerificate is not found.
> 
> Please check the following instruction how to configure OpenSSL for CentOS
> https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-openssl-linux
> 
> Let me know if this help

Is it required to configure openssl before 1.9 as documented? Then I confirmed the openssl certificate under the next centos8, and the result is as follows, does this mean that my openssl configuration is ok
![20200318093730](https://user-images.githubusercontent.com/25816282/76916772-74de6280-68fc-11ea-872e-c1a82093876f.png)

**Comment by jhakulin** [comment]
@jiajia1012, you need to use 1.10.0 release, CentOS 8 x64 system and configure OpenSSL as instructed here
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-openssl-linux
Have you verified all these are done and please let me know what is the outcome ?

**Comment by pankopon** [comment]
The following is verified to work on CentOS 8 x64. Adjust paths according to your system.

`sudo yum update -y`
`sudo yum install -y alsa-lib gcc-c++ make openssl`
`export SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt`
`export LD_LIBRARY_PATH=/path/to/SpeechSDK-Linux-1.10.0/lib/x64:$LD_LIBRARY_PATH`
`cd /path/to/cognitive-services-speech-sdk/quickstart/cpp/linux/from-microphone`
`make`
`./helloworld`

Output:

`Say something...`
`We recognized: Testing`

**Comment by jiajia1012** [comment]
I have checked these configurations repeatedly, there is no problem, but I am sure there is an error message on centos8, now I have switched to Debian9, everything is ok

**Comment by jhakulin** [comment]
Closing the issue, let us know if you need more help.

**Comment by jiajia1012** [comment]
Shut it down thanks, I just don't know what went wrong .
