### ISSUE TITLE
Batch Transcription is no longer working

### ISSUE THREAD

**Issue by tuanle07** [Azure-Samples/cognitive-services-speech-sdk#555]
**Describe the bug**
Using the sample code on the Microsoft website to submit a transcription request, but it does not work anymore. It used to work a couple of days ago. No code change was made in my side.

**Expected behavior**
It should work as how it used to.

**Platform, Operating System, and Programming Language**
 - OS: Windows 10 - please be specific
 - Hardware - x64
 - Programming language: C#

**Additional context**
 `Exception while executing function: System.Private.CoreLib: The given key 'channel_0' was not present in the dictionary.`

**Comment by PanosPeriorellis** [comment]
We identified and deployed a fix for this bug. It should work now
