### ISSUE TITLE
Doc/folder name bug: Change Virtual Assistant to Voice Assistant

### ISSUE THREAD

**Issue by dargilco** [Azure-Samples/cognitive-services-speech-sdk#558]
In folder name, doc title etc. I also fixed a broken link to docs.microsoft as a result of these name confusions. Please check links as well.

For example:

Change cognitive-services-speech-sdk/quickstart/csharp/uwp/virtual-assistant/

to

cognitive-services-speech-sdk/quickstart/csharp/uwp/voice-assistant/

**Comment by oscholz** [comment]
Assigning this to @trrwilson per chat with @dargilco.

**Comment by jhakulin** [comment]
closing the issue as I believe changes are already done.
