### ISSUE TITLE
Doc issue: Rename section "Voice First Virtual Assistant" and add link to new Voice Assistant GitHub repo 

### ISSUE THREAD

**Issue by dargilco** [Azure-Samples/cognitive-services-speech-sdk#559]
1. "[Voice first virtual assistants](https://github.com/Azure-Samples/cognitive-services-speech-sdk#voice-first-virtual-assistants-quickstarts)" should be renamed to "Voice Assistant" (per docs.microsoft terminology). I think I filed an issue about that before, but I'm not sure.

2. The above section should link to the [Voice Assistant](https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant) GitHub repo, where you can find complete clients, development & test tools, Custom Command skills and Azure deployment scripts.

**Comment by dargilco** [comment]
Feel free to assign this to me

**Comment by jhakulin** [comment]
Thanks Darren for improving our docs!
