### ISSUE TITLE
How to use StartContinuousRecognitionAsync and PushAudioInputStream with C++

### ISSUE THREAD

**Issue by jiajia1012** [Azure-Samples/cognitive-services-speech-sdk#564]
The example seems to use PullAudioInputStream with Java,this is very useful:
[https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/79c1d6eaba1940eb583b5bcc91dd5a49ba81e402/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java](url)

do you have an example how to use StartContinuousRecognitionAsync() and PushAudioInputStream with C++?

**Comment by rhurey** [comment]
Thanks for asking, https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/04a3f93a2c23a2432818b8d9512978133a12d4ac/samples/cpp/windows/console/samples/speech_recognition_samples.cpp#L333 shows C++ using a PushAudioStream.

**Comment by jiajia1012** [comment]
@r-andert thx
