### ISSUE TITLE
How to implement Azure TTS for dynamic text using JS speech-sdk

### ISSUE THREAD

**Issue by inglesuniversal** [Azure-Samples/cognitive-services-speech-sdk#571]
The following variable holds my last recognized speech (mySpeech)

phraseDiv.innerHTML = result.text + "\r\n";
var mySpeech = result.text;

Now... I want to implement a TTS response based on the value obtained above (mySpeech)

if(mySpeech == "Good morning.") {
createTTS("Hello there Sir", "us-EN");
}

So my question... how to implement the above using: synthesizing (provided in the sample html file) hosted right here.

I tried different ways but it ONLY works in the browser... Unlike you sample translator with checkbox to enable audio playback in the target language... it works great on browser and iPhone... so I would like to obtain the same result for my custom code.

Hope you can help.

Best regards

**Comment by szhaomsft** [comment]
@yulin-li

**Comment by yulin-li** [comment]
Thanks @inglesuniversal for reaching out. Our JS SDK doesn't support browser now. Which sample html file are you referring to? Could you provide more details of your codes?

**Comment by pankopon** [comment]
@inglesuniversal Is this still a valid issue, if yes can you please provide more info as asked?

**Comment by oscholz** [comment]
@inglesuniversal I am closing this issue for now. We have support for TTS from JavaScript now. You can read more about that here:
https://docs.microsoft.com/azure/cognitive-services/speech-service/quickstarts/text-to-speech?&pivots=programming-language-javascript
We also support a number of other programming languages that you can see in this and other articles. 
If you still have questions after that, please reopen this ticket and let us know. 
Thank you for using the Speech SDK!
