### ISSUE TITLE
Text to Speech Connection failure

### ISSUE THREAD

**Issue by francescaromana** [Azure-Samples/cognitive-services-speech-sdk#574]
Hi,

I am trying to use the Text to Speech service in Java, but it always raise the above error. With the same key and region both the speech to text and the translation work.
All the services have been tried using the code in the QuickStart and in the following link
[](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/java)

At the beginning I created an account and subscribed for the free trial for cognitive speech API, so the region was _westus_, then I tried to create the service through the azure portal (as suggested in the forum), but still Text to Speech service is the only one that doesn't work (in this case the region was _westeurope_).

This is the dependency added in the Maven project.
<dependency>
         <groupId>com.microsoft.cognitiveservices.speech</groupId>
	 <artifactId>client-sdk</artifactId>
	<version>1.10.0</version>
</dependency>

I am trying to run the code in Eclipse on MacOS Mojave.

Following there is the raised error.
```
2020-04-03 12:43:01.821 java[647:58084] CFNetwork SSLHandshake failed (-9836)
2020-04-03 12:43:01.954 java[647:58084] CFNetwork SSLHandshake failed (-9836)
CANCELED: Reason=Error
CANCELED: ErrorCode=ConnectionFailure
CANCELED: ErrorDetails=Connection failed (no connection to the remote host). Internal error: 11. Error details: 0. Please check network connection, firewall setting, and the region name used to create speech factory. USP state: 2. Received audio size: 0bytes.
CANCELED: Did you update the subscription info?
```

**Comment by szhaomsft** [comment]
what is your java sdk version?

**Comment by yulin-li** [comment]
Hi @francescaromana , thanks for reaching out. Are you using Java 8 on macOS Mojave (10.14.x)? If yes, it's a known issue for our SDK, you can try either Java 11 or macOS Catalina. The reason that only TTS failed is that the TTS service only supports TLS v1.2.

If failed again, could you follow [this](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging) to enable logging and paste the log here?

**Comment by francescaromana** [comment]
Yes I was using Java 8 on macOS Mojave. Now with Java 11 it works fine, thanks
