### ISSUE TITLE
Mulaw support in python sdk

### ISSUE THREAD

**Issue by init-asr** [Azure-Samples/cognitive-services-speech-sdk#575]
Hi,
In reference to @amitkumarshukla's  answer in #446:
> @sowsan We have support for MULAW in wav container. Please look at the https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams for more information. Do let us know if this answers your question.

the link suggests that the mulaw support is not there for python yet. Is there any work around? Or a probable timeline when we can expect this?

**Comment by amitkumarshukla** [comment]
Currently it is not there in Python. Right now there is no work around also. But we can surely add this asap. I will get back to you with the plan. By the way what is your scenario. From where are you getting Mulaw data and what is the container format you guys are using.

**Comment by xuchen** [comment]
having exactly the same issue. @amitkumarshukla what did you mean by "there is no work around also"? Can we directly call a REST endpoint to configure the audio format?

**Comment by pankopon** [comment]
We've created a backlog item for this and will address it in a future release, there's no guaranteed timeline yet. Once the work is done, we will update this issue to let you know which release will have the feature.

You can use REST and batch transcription for supported formats:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-speech-to-text
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription
