### ISSUE TITLE
`Recognizer.StopContinuousRecognitionAsync()` in Unity produces heavy hiccup

### ISSUE THREAD

**Issue by nbrindic** [Azure-Samples/cognitive-services-speech-sdk#578]
**Describe the bug**
We are currently using SpeechSDK v1.7 in Unity 2018.4.19 LTS, and so far we do not have issues with basic operations, like start/stop continuous recognition. If we update SpeechSDK to any version greater than 1.7 (we have tried with v1.9 and v1.11), there is a huge hiccup when calling `Recognizer.StopContinuousRecognitionAsync().ConfigureAwait(false);`. 
In Unity on Windows, - it halts the editor for more than 5 seconds, and then goes back to normal behaviour.
On Oculus Quest - it immediately terminates the app and goes back to home screen

**To Reproduce**
1. Initiate continuous recognition with: 
```
var recognizer = new SpeechRecognizer(_config, audioConfig);
await recognizer.StartContinuousRecognitionAsync().ConfigureAwait(false);
```
2. When you want to stop recognition, do it with:
```
await recognizer.StopContinuousRecognitionAsync().ConfigureAwait(false);
```

**Expected behavior**
Lightweight and smooth recognition stopping

**Version of the Cognitive Services Speech SDK**
v1.7 - works fine
v1.9 and v1.11 - tested and reproduced the bug with both versions

**Platform, Operating System, and Programming Language**
 - Hardware
    - Dev machine: Windows 10 Pro on x64 i7 processor, 16GB RAM, NVIDIA 1050
    - Target device: Android on Oculus Quest
 - Programming language: C# in Unity 2018.4.19 LTS

**Additional context**
- Error is reproduced 100% of time.
- I have assembled the sample project so if you need it, I can provide you with that

**Comment by jhakulin** [comment]
@nbrindic  Thanks for the report. 

When you say 1.7 release works fine, does it mean 
- On Unity Editor on Windows, stop happens immediately without 5 seconds wait ? 
- On Oculus Quest on app is not terminated ?

Could you please provide the sample project ?

**Comment by nbrindic** [comment]
@jhakulin Hey, man, so - regarding 1.7 release:
- On Unity Editor on Windows, it works without any issues. It doesn't stop immediately, but, as we are stopping it in the background with async/await, it is smoothly executed in the background, without any hiccups

**Comment by jhakulin** [comment]
@nbrindic Hey there, thanks for the sample! I looked the sample and there seems to stop the stream before stopping the recognition ? Could you try to stop recognition before stopping the stream from external micrphone?

**Comment by nbrindic** [comment]
@jhakulin Hey man, thank you so much for help! Your suggestion totally worked! For all the people out there who potentially face the same issue, here is the working sequence of steps needed to be undertaken in order to have smooth behaviour:

**Comment by jhakulin** [comment]
@nbrindic Thanks for information! We will improve SDK on this limitation in the future releases.

**Comment by Demi871023** [comment]
@nbrindic Sorry, can you share sample project again? This is download link is missing.
