### ISSUE TITLE
Android. SpeechSynthesizer cancelation

### ISSUE THREAD

**Issue by ayratis** [Azure-Samples/cognitive-services-speech-sdk#579]
How do I cancel audio playing of speechSynthesizer.SpeakText("some text")? Seems like speechSynthesizer.close() should work but it doesn't.

**Comment by amitkumarshukla** [comment]
@yulin-li Please help with the answer

**Comment by yulin-li** [comment]
For now, the SDK doesn't support stop or cancel the audio playing. The `speechSynthesizer.close()` is used for disposing the object. 

We plan to add an api to cancel the playing. As a workaround for now, you can use MediaPlayer or other Android api to control the playback yourself.

**Comment by manideeppabba1991** [comment]
@yulin-li is there any update on this issue? I am facing same issue. If not can your provide an example how to control the playback using Android.Media media player ?

**Comment by yulin-li** [comment]
@manideeppabba1991 we will support stop() method in release 1.14, which will be released before the end of this month.
