### ISSUE TITLE
Microsoft.CognitiveServices.Speech.extension.codec.dll: Can't find dependent libraries

### ISSUE THREAD

**Issue by wukun2015** [Azure-Samples/cognitive-services-speech-sdk#580]
Hello,

When i upgrade sdk from 1.10.0 to 1.11.0 for Java-jre on Windows10, sample code continuousRecognitionWithFileAsync() with .wav file (16k, 16bit, mono as required) running now throw a new run time err msg: 

Could not load an optional Speech SDK library because of the following error: C:\Users\abcd\AppData\Local\Temp\speech-sdk-native-5412956719501271709\Microsoft.CognitiveServices.Speech.extension.codec.dll: Can't find dependent libraries

The wav can be still transcribed as usual, but not sure whether this new err msg will hurt somewhat. 

Anything i miss in config ? 

Thank you. 

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using: 1.11.0

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - Windows 10
 - Hardware - x64
 - Programming language: Java

**Comment by amitkumarshukla** [comment]
Thanks a lot for raising the issue. Looks like this is a real issue with the SDK. For the time being you can get rid of this error by installing https://gstreamer.freedesktop.org/data/pkg/windows/1.14.4/gstreamer-1.0-x86_64-1.14.4.msi and putting the (InstallDrive)\gstreamer\1.0\x86_64\bin folder into your system path.

**Comment by amitkumarshukla** [comment]
This is just one of the extra logging in our SDK. So for the time being if you are not comfortable installing https://gstreamer.freedesktop.org/data/pkg/windows/1.14.4/gstreamer-1.0-x86_64-1.14.4.msi, you dont need to do that and you can just ignore the print. In our next release we will clean some of these prints.

Thanks a lot for raising the issue.
