### ISSUE TITLE
Getting Errors when transcribing audio to text

### ISSUE THREAD

**Issue by raveenb** [Azure-Samples/cognitive-services-speech-sdk#581]
I wanted to try out the Azure batch speech to text api. So i setup the account for it and proceeded to use the swagger page to try out

I had uploaded a file to the blob storage earlier, the uri for it is public you can check it out
the response . its around 25 min of audio, from a podcast, and is in mp3 format, which is supported by the batch api per documentation

audio sas url here - https://makemysummary.blob.core.windows.net/audio-makemysummary/radiolab_podcast20dispatch1numbers.mp3?sp=r&st=2020-04-13T12:11:56Z&se=2020-04-13T20:11:56Z&spr=https&sv=2019-02-02&sr=b&sig=62ZkjjYqkMSqmOQm%2BkC4K1sN26aiAL7IjM2KtJ9eQEo%3D

Issues
1. For a long time i kept getting 401's even when i was able to run the speech recognition via the continuous speech. mysteriously that vanished without doing anything
2. When it did work, the response indicates that i failed, with this message 'The recordings URI contains invalid data.' you can listen to the audio its just a plain podcast mp3 file
3. the resulting sas endpoint says its a video file, which is strange, there is no video feed just audio

how can complete my tests here so that i can attempt to incorporate azure speech to text into my app. I am looking at batch processing using python

error

[
  {
    "recordingsUrl": "https://makemysummary.blob.core.windows.net/audio-makemysummary/radiolab_podcast20dispatch1numbers.mp3?sp=r&st=2020-04-13T12:11:56Z&se=2020-04-13T20:11:56Z&spr=https&sv=2019-02-02&sr=b&sig=62ZkjjYqkMSqmOQm%2BkC4K1sN26aiAL7IjM2KtJ9eQEo%3D",
    "reportFileUrl": "https://spsvcprodusw.blob.core.windows.net/bestor-338cca94-e7c5-4fc1-8a7b-7b8c19fd291a/TranscriptionData/1ceafd3a-7130-4c35-be72-a2ec26ebd27b.txt?sv=2019-02-02&sr=b&sig=WM7GndiHPJpx5qv7n6xppEjTtwdHgpbKTrqbNUYZGT0%3D&st=2020-04-13T12:30:35Z&se=2020-04-14T00:35:35Z&sp=rl",
    "resultsUrls": {},
    "models": [
      {
        "modelKind": "AcousticAndLanguage",
        "datasets": [],
        "lastActionDateTime": "2019-12-12T14:20:31Z",
        "status": "Succeeded",
        "id": "7a64fbdb-d028-49b6-83d8-3b57c812432d",
        "createdDateTime": "2019-12-12T13:43:14Z",
        "locale": "en-US",
        "name": "20191202",
        "description": "en-US base model",
        "properties": {
          "Purpose": "OnlineTranscription,BatchTranscription,LanguageAdaptation",
          "Deprecated": "None",
          "ModelClass": "unified-v4-pch",
          "VadKind": "Tuned",
          "UseOnlineInterpolation": "False",
          "IsDynamicGrammarSupported": "True",
          "UsesHalide": "True"
        }
      },
      {
        "modelKind": "AcousticAndLanguage",
        "datasets": [],
        "lastActionDateTime": "2019-12-12T14:20:31Z",
        "status": "Succeeded",
        "id": "7a64fbdb-d028-49b6-83d8-3b57c812432d",
        "createdDateTime": "2019-12-12T13:43:14Z",
        "locale": "en-US",
        "name": "20191202",
        "description": "en-US base model",
        "properties": {
          "Purpose": "OnlineTranscription,BatchTranscription,LanguageAdaptation",
          "Deprecated": "None",
          "ModelClass": "unified-v4-pch",
          "VadKind": "Tuned",
          "UseOnlineInterpolation": "False",
          "IsDynamicGrammarSupported": "True",
          "UsesHalide": "True"
        }
      }
    ],
    "statusMessage": "The recordings URI contains invalid data.",
    "lastActionDateTime": "2020-04-13T12:27:48Z",
    "status": "Failed",
    "id": "40530de5-4bf0-4bb4-88b4-3d02f7e41b97",
    "createdDateTime": "2020-04-13T12:27:26Z",
    "locale": "en-US",
    "name": "Transcription using locale en-US",
    "description": "An optional description of the transcription.",
    "properties": {
      "AddWordLevelTimestamps": "True",
      "AddDiarization": "True",
      "AddSentiment": "True",
      "ProfanityFilterMode": "Masked",
      "PunctuationMode": "DictatedAndAutomatic",
      "CustomPronunciation": "False"
    }
  },
  {
    "recordingsUrl": "https://makemysummary.blob.core.windows.net/audio-makemysummary/radiolab_podcast20dispatch1numbers.mp3?sp=r&st=2020-04-13T12:11:56Z&se=2020-04-13T20:11:56Z&spr=https&sv=2019-02-02&sr=b&sig=62ZkjjYqkMSqmOQm%2BkC4K1sN26aiAL7IjM2KtJ9eQEo%3D",
    "reportFileUrl": "https://spsvcprodusw.blob.core.windows.net/bestor-338cca94-e7c5-4fc1-8a7b-7b8c19fd291a/TranscriptionData/184e2570-634c-44bf-94e4-f4f648338231.txt?sv=2019-02-02&sr=b&sig=APvn39YIHbpgdPD3QbVnSvwqPtd8xvdOIltNrEuYTOc%3D&st=2020-04-13T12:30:35Z&se=2020-04-14T00:35:35Z&sp=rl",
    "resultsUrls": {},
    "models": [
      {
        "modelKind": "AcousticAndLanguage",
        "datasets": [],
        "lastActionDateTime": "2019-12-12T14:20:31Z",
        "status": "Succeeded",
        "id": "7a64fbdb-d028-49b6-83d8-3b57c812432d",
        "createdDateTime": "2019-12-12T13:43:14Z",
        "locale": "en-US",
        "name": "20191202",
        "description": "en-US base model",
        "properties": {
          "Purpose": "OnlineTranscription,BatchTranscription,LanguageAdaptation",
          "Deprecated": "None",
          "ModelClass": "unified-v4-pch",
          "VadKind": "Tuned",
          "UseOnlineInterpolation": "False",
          "IsDynamicGrammarSupported": "True",
          "UsesHalide": "True"
        }
      },
      {
        "modelKind": "AcousticAndLanguage",
        "datasets": [],
        "lastActionDateTime": "2019-12-12T14:20:31Z",
        "status": "Succeeded",
        "id": "7a64fbdb-d028-49b6-83d8-3b57c812432d",
        "createdDateTime": "2019-12-12T13:43:14Z",
        "locale": "en-US",
        "name": "20191202",
        "description": "en-US base model",
        "properties": {
          "Purpose": "OnlineTranscription,BatchTranscription,LanguageAdaptation",
          "Deprecated": "None",
          "ModelClass": "unified-v4-pch",
          "VadKind": "Tuned",
          "UseOnlineInterpolation": "False",
          "IsDynamicGrammarSupported": "True",
          "UsesHalide": "True"
        }
      }
    ],
    "statusMessage": "The recordings URI contains invalid data.",
    "lastActionDateTime": "2020-04-13T12:28:11Z",
    "status": "Failed",
    "id": "34ed657d-fb03-48ea-8856-2131f969446d",
    "createdDateTime": "2020-04-13T12:27:52Z",
    "locale": "en-US",
    "name": "Transcription using locale en-US",
    "description": "An optional description of the transcription.",
    "properties": {
      "AddWordLevelTimestamps": "True",
      "AddDiarization": "True",
      "AddSentiment": "True",
      "ProfanityFilterMode": "Masked",
      "PunctuationMode": "DictatedAndAutomatic",
      "CustomPronunciation": "False"
    }
  },
  {
    "recordingsUrl": "https://makemysummary.blob.core.windows.net/audio-makemysummary/radiolab_podcast20dispatch1numbers.mp3?sp=r&st=2020-04-13T12:11:56Z&se=2020-04-13T20:11:56Z&spr=https&sv=2019-02-02&sr=b&sig=62ZkjjYqkMSqmOQm%2BkC4K1sN26aiAL7IjM2KtJ9eQEo%3D",
    "reportFileUrl": "https://spsvcprodusw.blob.core.windows.net/bestor-338cca94-e7c5-4fc1-8a7b-7b8c19fd291a/TranscriptionData/c95dc555-e809-42c0-abdd-f1db54ae7131.txt?sv=2019-02-02&sr=b&sig=v%2FLnETx%2FlyQPvl6C9sbcqUXo2jaLTngOR4OfeVwQEck%3D&st=2020-04-13T12:30:35Z&se=2020-04-14T00:35:35Z&sp=rl",
    "resultsUrls": {},
    "models": [
      {
        "modelKind": "AcousticAndLanguage",
        "datasets": [],
        "lastActionDateTime": "2019-12-12T14:20:31Z",
        "status": "Succeeded",
        "id": "7a64fbdb-d028-49b6-83d8-3b57c812432d",
        "createdDateTime": "2019-12-12T13:43:14Z",
        "locale": "en-US",
        "name": "20191202",
        "description": "en-US base model",
        "properties": {
          "Purpose": "OnlineTranscription,BatchTranscription,LanguageAdaptation",
          "Deprecated": "None",
          "ModelClass": "unified-v4-pch",
          "VadKind": "Tuned",
          "UseOnlineInterpolation": "False",
          "IsDynamicGrammarSupported": "True",
          "UsesHalide": "True"
        }
      },
      {
        "modelKind": "AcousticAndLanguage",
        "datasets": [],
        "lastActionDateTime": "2019-12-12T14:20:31Z",
        "status": "Succeeded",
        "id": "7a64fbdb-d028-49b6-83d8-3b57c812432d",
        "createdDateTime": "2019-12-12T13:43:14Z",
        "locale": "en-US",
        "name": "20191202",
        "description": "en-US base model",
        "properties": {
          "Purpose": "OnlineTranscription,BatchTranscription,LanguageAdaptation",
          "Deprecated": "None",
          "ModelClass": "unified-v4-pch",
          "VadKind": "Tuned",
          "UseOnlineInterpolation": "False",
          "IsDynamicGrammarSupported": "True",
          "UsesHalide": "True"
        }
      }
    ],
    "statusMessage": "The recordings URI contains invalid data.",
    "lastActionDateTime": "2020-04-13T12:28:39Z",
    "status": "Failed",
    "id": "4ac3cdb8-8f10-4a7f-a438-4d7bc457b739",
    "createdDateTime": "2020-04-13T12:28:21Z",
    "locale": "en-US",
    "name": "Transcription using locale en-US",
    "description": "An optional description of the transcription.",
    "properties": {
      "AddWordLevelTimestamps": "True",
      "AddDiarization": "True",
      "AddSentiment": "True",
      "ProfanityFilterMode": "Masked",
      "PunctuationMode": "DictatedAndAutomatic",
      "CustomPronunciation": "False"
    }
  },
  {
    "recordingsUrl": "https://makemysummary.blob.core.windows.net/audio-makemysummary/radiolab_podcast20dispatch1numbers.mp3?sp=r&st=2020-04-13T12:11:56Z&se=2020-04-13T20:11:56Z&spr=https&sv=2019-02-02&sr=b&sig=62ZkjjYqkMSqmOQm%2BkC4K1sN26aiAL7IjM2KtJ9eQEo%3D",
    "reportFileUrl": "https://spsvcprodusw.blob.core.windows.net/bestor-338cca94-e7c5-4fc1-8a7b-7b8c19fd291a/TranscriptionData/a579a17a-17ca-4517-97f7-de7c4809d371.txt?sv=2019-02-02&sr=b&sig=4N0GMqWemop1UqqIKT36vMhAmiBbv%2BeGDr6HYyi4VOI%3D&st=2020-04-13T12:30:35Z&se=2020-04-14T00:35:35Z&sp=rl",
    "resultsUrls": {},
    "models": [
      {
        "modelKind": "AcousticAndLanguage",
        "datasets": [],
        "lastActionDateTime": "2019-12-12T14:20:31Z",
        "status": "Succeeded",
        "id": "7a64fbdb-d028-49b6-83d8-3b57c812432d",
        "createdDateTime": "2019-12-12T13:43:14Z",
        "locale": "en-US",
        "name": "20191202",
        "description": "en-US base model",
        "properties": {
          "Purpose": "OnlineTranscription,BatchTranscription,LanguageAdaptation",
          "Deprecated": "None",
          "ModelClass": "unified-v4-pch",
          "VadKind": "Tuned",
          "UseOnlineInterpolation": "False",
          "IsDynamicGrammarSupported": "True",
          "UsesHalide": "True"
        }
      },
      {
        "modelKind": "AcousticAndLanguage",
        "datasets": [],
        "lastActionDateTime": "2019-12-12T14:20:31Z",
        "status": "Succeeded",
        "id": "7a64fbdb-d028-49b6-83d8-3b57c812432d",
        "createdDateTime": "2019-12-12T13:43:14Z",
        "locale": "en-US",
        "name": "20191202",
        "description": "en-US base model",
        "properties": {
          "Purpose": "OnlineTranscription,BatchTranscription,LanguageAdaptation",
          "Deprecated": "None",
          "ModelClass": "unified-v4-pch",
          "VadKind": "Tuned",
          "UseOnlineInterpolation": "False",
          "IsDynamicGrammarSupported": "True",
          "UsesHalide": "True"
        }
      }
    ],
    "statusMessage": "The recordings URI contains invalid data.",
    "lastActionDateTime": "2020-04-13T12:32:27Z",
    "status": "Failed",
    "id": "07aa1f29-36f4-45ea-a504-c527f0ad9846",
    "createdDateTime": "2020-04-13T12:32:09Z",
    "locale": "en-US",
    "name": "Radiolab Test",
    "description": "An optional description of the transcription.",
    "properties": {
      "ProfanityFilterMode": "Masked",
      "PunctuationMode": "DictatedAndAutomatic",
      "CustomPronunciation": "False"
    }
  }
]

**Describe the bug**

**To Reproduce**
1. ...
2. ...

**Expected behavior**

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - please be specific
 - Hardware - x64, x86, ARM, ...
 - Programming language: C#, C++, Java, JavaScript, Objective-C, Python
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific

**Additional context**
 - Error messages, log information, stack trace, ...
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by rarera** [comment]
Hi Raveenb, sorry for the inconveniences. 

I had a look at our logs and it looks like the file had two streams, a PNG (Image) and an AudioStream.

You can see that if you run ffprobe on the file.
With ffmpeg, and a few other free tools you can split the audio and remove the PNG stream.
If you then just submit the audio the transcription should work fine. 

We have on our roadmap to also handle files with multiple streams, but I cannot give you yet a timeline when that feature can be delivered.

I hope that this should unblock you.
Thank you,
Ramin

**Comment by raveenb** [comment]
@rarera this suggestion worked, i extracted the audio streams and combined into mono too which made the uploads smaller too.

but i think it should be made clear in the docs that azure expects only audio and not any other streams in the input

this is what i did

```

import sys
from typing import Optional

import ffmpeg
import rollbar
from loguru import logger

class AudioExtractor:
    audio_suffix: str = "_audio.mp3"

    def extract_audio(self, filename: str) -> Optional[str]:
        if filename is None:
            return None
        try:
            stream = ffmpeg.input(filename)
            out_filename = f"{filename}{self.audio_suffix}"
            ffmpeg.run(ffmpeg.output(stream.audio, out_filename))
            return out_filename
        except Exception as e:
            logger.error(f"exception in extracting audio: {str(e)}")
            rollbar.report_exc_info(sys.exc_info(), extra_data={"filename": filename})
            return None

    def extract_mono_audio(self, filename: str) -> Optional[str]:
        if filename is None:
            return None
        try:
            stream = ffmpeg.input(filename)
            out_filename = f"{filename}{self.audio_suffix}"
            ffmpeg.run(ffmpeg.output(stream.audio, out_filename, ac=1, ar="16k"))
            return out_filename
        except Exception as e:
            logger.error(f"exception in extracting audio: {str(e)}")
            rollbar.report_exc_info(sys.exc_info(), extra_data={"filename": filename})
            return None
```
