### ISSUE TITLE
Confidence score of speech recognition result

### ISSUE THREAD

**Issue by wukun2015** [Azure-Samples/cognitive-services-speech-sdk#585]
Hello,

Is there a way to know if the intermediate or final recognition result confidence score ?  Or even multiple recognized/recognizing result candidates each with scores respectively ? There seems no such info in com.microsoft.cognitiveservices.speech.RecognitionResult class.

i'm asking this because in some scenario, developer user of sdk would like to leverage such scores to decide whether to render or drop reco result per confident score. Such scenario cases are like big background noise, mis-match spoken languge, etc. 

Thank you.

**Comment by pankopon** [comment]
Hi, you can get the result candidates and their confidence scores for the final result (but not intermediate):
- request detailed output
- read the result property SpeechServiceResponse_JsonResult

For a C++ example on usage, see speech_recognition_samples.cpp, SpeechRecognitionWithLanguageAndUsingDetailedOutputFormat():
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/cpp/windows/console/samples/speech_recognition_samples.cpp#L64 (exact position as of this writing)

**Comment by wukun2015** [comment]
Thanks for info. 

I tried your sample and did receive NBest candidates with confidence score from recognizeOnceAsync() call of SpeechRecognizer class, but not from any other methods like startContinuousRecognitionAsync(). 

Any other config i missed ?

**Comment by wukun2015** [comment]
thank you for info.

**Comment by pankopon** [comment]
Closed as answered, please reopen if necessary.

**Comment by wukun2015** [comment]
Sorry for late reply. 

Yes, it helps, thanks for info.  @pankopon
