### ISSUE TITLE
Speech-to-text , whether to support separation of different speakers

### ISSUE THREAD

**Issue by jiajia1012** [Azure-Samples/cognitive-services-speech-sdk#586]
Speech-to-text , whether to support separation of different speakers

**Comment by pankopon** [comment]
Hi, there are the following options:

- https://docs.microsoft.com/bs-latn-ba/azure/cognitive-services/speech-service/batch-transcription (search for "Speaker separation (Diarization)" on the page)
- https://docs.microsoft.com/bs-latn-ba/azure/cognitive-services/speech-service/conversation-transcription

Please check if these meet your needs.

**Comment by pankopon** [comment]
Closed as answered, please reopen if more info needed.
