### ISSUE TITLE
Unable to make SpeechRecognizer work with RAW PCM Audio

### ISSUE THREAD

**Issue by viju2008** [Azure-Samples/cognitive-services-speech-sdk#589]
String path = Environment.getExternalStorageDirectory() + "/input/whatstheweatherlike.pcm";
            PullAudioInputStream pullAudio = AudioInputStream.createPullStream(new BinaryAudioStreamReader(path));

SpeechRecognizer reco = new SpeechRecognizer(config, ac);
            assert(reco != null);

            Future<SpeechRecognitionResult> task = reco.recognizeOnceAsync();
            assert(task != null);

            SpeechRecognitionResult result = task.get();
            assert(result != null);

However there is not OUTPUT from the API END and the JVM Crashes.

I also tried AudioConfig.fromWavFileInput(test.raw);  

Request to please guide, whether I am doing anything wrong.

How to send raw PCM MONO 16 HZ sample rate and 16-bit PCM audio to the REST/WEBSOCKET ENDPOINT

**Comment by chrisbasoglu** [comment]
Are you able to run the build and run sample here? https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java#L225

**Comment by viju2008** [comment]
Yes i tried these combination. The WavStream method is looking for the headers of the wav file.... since PCM data is raw and dosent have headers it seems its not working

**Comment by pankopon** [comment]
Please see https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/588 for a suggested working example.
