### ISSUE TITLE
Keyword recognition session not starting

### ISSUE THREAD

**Issue by mihalybalas** [Azure-Samples/cognitive-services-speech-sdk#591]
When I start a keyword recognition session, basically nothing happens. Even the session started event is not fired. Other recognitions work fine (e.g. continuous recognition).

Run [this sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_recognition_samples.cs) (the keyword recognition part).

Expected behavior
The keyword recognition session started event is fired, and the recognition starts and works. However, apparently nothing happens: no event is fired, no exception is thrown, and nothing gets recognized.

Version
I tried with 1.11.0 from NuGet at first, but tried basically all older versions as well, with no change in behavior.

Platform, Operating System, and Programming Language
- OS: Windows 10 x64 1909
- Programming language: C#. I have tried the .NET (Standard) and .NET Core versions, but the result was the same. I have also tried the Android sample on my phone (OnePlus 7 Pro GM1913), but the results were still the same: keyword recognition does not start, other recognition methods work.

Additional context
- I have tried debugging the .NET code but the problem appears to be in the unmanaged internal DLL.
- I have tried the keyword recognition with different table files, but the result did not change. I have also tried giving a random other file instead to the model, and I got an exception about the unsupported format, which is expected.
- I have tried setting an invalid subscription key to the SpeechConfig, but got no exception. With other recognition methods, I get an exception in this case, so the code does not appear to reach the point where it makes any API requests or validates the subscription key with another method.

**Comment by jhakulin** [comment]
Thanks for the feedback, I checked the sample with kws.table model file which you can found from https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/csharp/xamarin/kws-xamarin/kws-xamarin/kws-xamarin.UWP/Assets
The keyword is "Computer"
Sample worked ok with 1.11.0 latest release.
Could you try with that model and let us know do you see still issues ?

**Comment by jhakulin** [comment]
@mihalybalas I am closing this, please let us know if the previous answer did not help.
