### ISSUE TITLE
Disable Partial results and increase Chunk size of audio being sent over network

### ISSUE THREAD

**Issue by viju2008** [Azure-Samples/cognitive-services-speech-sdk#592]
Dear Sir

How can we disable partial results to the Wesocket endpoint when sending File such as .wav and .opus  . I do not want partial results as I cannot work on the partial results in my domain as every word is important. The whole audio should be processed in one shot and as a whole. I have a high speed network between the SDK and Speech recognition endpoint. And telling the Speech endpoint that whole speech has to be processed  I beleive will reduce the processing time and also improve throughput as it can save the compute time spent of making partial results and sending over network.

Also i saw that the audio is being sent in chunks/segments over the network to the WebSocket endpoint at Azure end and not in one single go. Also i think the processing is also happening in the chunks and getting clubbed. Is it possible to specify the chunk size and increase it.

Regards,

**Comment by oscholz** [comment]
@viju2008 Thank you for getting in touch! I am checking with the feature team on this, and we'll get back to you soon.

**Comment by viju2008** [comment]
Any Updates.

Regards,

Vijay

**Comment by amitkumarshukla** [comment]
@viju2008 Are you looking for disabling hypothesis ?

**Comment by amitkumarshukla** [comment]
@viju2008 From here https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.propertyid?view=azure-dotnet
try setting this SpeechServiceResponse_StablePartialResultThreshold
like             
config.SetProperty(PropertyId.SpeechServiceResponse_StablePartialResultThreshold, "100");

Play with different numbers and see what fits your requirement.

**Comment by viju2008** [comment]
I tried setting is as told   config.setProperty(PropertyId.SpeechServiceResponse_StablePartialResultThreshold, "200");


But it is stilling recognizing partially. Below is the output

RECOGNIZING: Text=I need
RECOGNIZING: Text=I need to
RECOGNIZING: Text=I need to transfer
RECOGNIZING: Text=I need to transfer seventh
RECOGNIZED: Text=I need to transfer 7000 rupees to sham.

**Comment by amitkumarshukla** [comment]
You have option not to subscribe to recognizing event and in that case the sdk wont callback the app for every intermediate. Do let me know if that solves your problem

**Comment by viju2008** [comment]
Will disabling the event listening for partial results actually stop the speech endpoint or containers from producing partial results  and sending them across the network Or will the sdk simply not display it. I wish that the partial results should not travel over the network also

**Comment by amitkumarshukla** [comment]
@viju2008 Even though you disable the event but the intermediate result will travel over the network. Please keep in mind the data which comes from service is a json payload which is text data. The amount of data received is much more lower than the amount of data sent to the service. So I can guarantee you that your data usage will never be a bottleneck for the incoming traffic.

**Comment by viju2008** [comment]
But the purpose of disabling partial results is not served. Its not only about the network overheads also the container need not waste time in making partial results and can in one shot take the hold file and process the same. 

The Main reason for the post was so that the response time is made better from container by disabling partial results over the network as well as the compute time involved for the container in partial results. As the partial results are not of any use in my case. Hence if the chunk size could be increased and the whole audio is taken and processed in one go the response time of the container will be better in my case

**Comment by amitkumarshukla** [comment]
@viju2008 That is a great input to us. Please put a feature request at https://cognitive.uservoice.com/forums/912208-speech-service

Our team will look at this and will work on it based on our priority.
Thanks a lot.
Closing it for the time being.

**Comment by viju2008** [comment]
Hello @amitkumarshukla 

I have put a feature request. Please provide update on progress

**Comment by jzhw0130** [comment]
waiting too
