### ISSUE TITLE
Deploying dotnet core sample on windows docker returns Microsoft.CognitiveServices.Speech.core.dll not found error

### ISSUE THREAD

**Issue by anjsha** [Azure-Samples/cognitive-services-speech-sdk#593]
**Describe the bug**
Build the app on windows docker and run container locally. The app throws Microsoft.CognitiveServices.Speech.core.dll not found error.

**To Reproduce**
1. Download docker for windows
2. Build docker image for sample app
`docker build -t samples .`
3. Run docker container
`docker run -it --rm samples
`

**Expected behavior**
Container image should work same as the sample app running from VS

**Version of the Cognitive Services Speech SDK**
1.9.0
1.11.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 10 Pro Version 1909
 - Hardware - x64 & ARM
 - Programming language: C#
- dotnet core 2.2

**Additional context**

StackTrace

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Unable to load DLL 'Microsoft.CognitiveServices.Speech.core.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)) ---> System.DllNotFoundException: Unable to load DLL 'Microsoft.CognitiveServices.Speech.core.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.CognitiveServices.Speech.Internal.SpeechConfig.speech_config_from_subscription(IntPtr& config, String subscriptionKey, String region)
   at Microsoft.CognitiveServices.Speech.SpeechConfig.FromSubscription(String subscriptionKey, String region)
   at MicrosoftSpeechSDKSamples.SpeechRecognitionSamples.RecognitionWithMicrophoneAsync()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
```

DockerFile

> FROM mcr.microsoft.com/dotnet/core/sdk:2.2
> WORKDIR /app
> COPY ["samples/samples.csproj", "samples/"]
> RUN dotnet restore "samples/samples.csproj"
> COPY . .
> WORKDIR "/app/samples"
> RUN dotnet build "samples.csproj" -c Release -o /app
> RUN dotnet publish "samples.csproj" -c Release -o /app
> WORKDIR /app
> ENTRYPOINT ["dotnet", "samples.dll"]
> 
>

**Comment by oscholz** [comment]
@anjsha thank you for getting in touch! I'm checking with the feature team on this, and we'll get back to you soon.

**Comment by amitkumarshukla** [comment]
@anjsha could you please share your dockerfile.

**Comment by anjsha** [comment]
> @anjsha could you please share your dockerfile.

@amitkumarshukla 
It's already shared. Please check additional context section above.

**Comment by amitkumarshukla** [comment]
@anjsha Oh I am sorry, I missed it :)

**Comment by amitkumarshukla** [comment]
@anjsha Thanks a lot for filing this bug. We are able to repro the issue locally and we will keep you updated with the fix.

**Comment by anjsha** [comment]
@amitkumarshukla 

I was able to workaround this issue as described here.
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/107#issuecomment-439335547

Looks like the issue is with VC++ runtime. These dlls are required for working with Microsoft Speech APIs but are not copied into the container by default. So, I updated my docker file to copy the VC++ runtime dlls into the container & it worked.

**Comment by amitkumarshukla** [comment]
@anjsha That's great. If you could paste your dockerfile here it will be great for others reference in future. Thanks a lot

**Comment by anjsha** [comment]
> @anjsha That's great. If you could paste your dockerfile here it will be great for others reference in future. Thanks a lot

Here you go! This is the updated docker file.
```
FROM mcr.microsoft.com/dotnet/core/sdk:2.2
WORKDIR /app
COPY ["samples/samples.csproj", "samples/"]
COPY vcruntimedlls /app
RUN dotnet restore "samples/samples.csproj"
COPY . .
WORKDIR "/app/samples"
RUN dotnet build "samples.csproj" -c Release -o /app
RUN dotnet publish "samples.csproj" -c Release -o /app
WORKDIR /app
ENTRYPOINT ["dotnet", "samples.dll"]
```

**Comment by amitkumarshukla** [comment]
Thank you.
