### ISSUE TITLE
Is there fluency format of recognized result ?

### ISSUE THREAD

**Issue by wukun2015** [Azure-Samples/cognitive-services-speech-sdk#598]
Hello,

Will the SDK support to format recognized spoken result with fluency into formal text ?  

This fluency format will help formal meeting transcription scenario, which does not expect spoken text forms. 

E.g. : 
- Utterance: "i want to ah, to book a flight to Denver, i mean, to Boston, the day, the day after, after Monday. "
- RECOGNIZED: "I want to are to book a flight to Denver. I mean to Boston the day, the day after after Monday."  
- Expected: " I want to book a flight to Boston the day after Monday."

Thank you.

**Comment by oscholz** [comment]
@wukun2015 this is currently not supported. 
Feel free to submit the feature idea in [UserVoice](https://cognitive.uservoice.com/forums/912208-speech-service).
