### ISSUE TITLE
Custom Headers in Speech WebSocket Request using Microsoft Speech SDK

### ISSUE THREAD

**Issue by viju2008** [Azure-Samples/cognitive-services-speech-sdk#599]
I am using Speech to Text Endpoint for development and plan to move to Containers for Speech to Text On-premise. I went to the SDK and container documentation but didnt find a method to add custom headers using Microsoft Speech SDK. I need to add additional authentication headers to validate at my end. Currently from the Speech SDK seems to expect the Container IP address directly as the Endpoint and doesn't support traffic flow through intermediate servers.

Is there any way to set Custom headers  using the Speech to text SDK provided will sending the request by using the recognizer object.  

Also i noticed that the Container doesn't validate any authorization header. The Container should also have a mechanism to input a Authentication String a shared secret which is sent by the client and validated at Container end.

**Comment by oscholz** [comment]
I reached out the the feature team. Somebody will get back to you early next week.

**Comment by robch** [comment]
Currently the sdk doesn't support the ability to add custom headers to the http websocket upgrade connection, nor add custom headers to individual web socket messages. However, the sdk does support pass thru proxy relays such as you're building. You could send a custom web socket message prior to starting recognition. See Connection.SendMessageAsync... Your proxy relay could intercept such messages and disallow relay prior to the custom message containing  your private authentication message.

**Comment by oscholz** [comment]
@viju2008 I'll close the question as it's answered. If you want to make a feature request, please feel free to do so [here](https://cognitive.uservoice.com/forums/912208-speech-service).

**Comment by viju2008** [comment]
Connection.SendMessageAsync... is there any Java Sample for this .

Can you elaborate in more detail on how to achieve this and what will be structure of the message when it is sent. Any examples in the github repository.

Is there an pass through sample already available with which i can build the intermediate server.

Also  I need to check at each socket sent message the header to prevent a highjacked TCP session case from happening by creating spoofed packets with MITM attacks.

**Comment by viju2008** [comment]
@oscholz 

Hello any update on my above post
