### ISSUE TITLE
Adapting own AudioInputStream for Linux SDK.

### ISSUE THREAD

**Issue by boldragon** [Azure-Samples/cognitive-services-speech-sdk#6]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [v] feature request
- [v] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> tyring to implement own audioinputstream and connect to speechapi factory

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). Other.
ubuntu 16.04
### Versions
>

### Mention any other details that might be useful
hi, 

Could you let me know how to connect own AudioInputStream more in detail for linux SDK? (sample code would be the best.)

I'm trying to adapt my own AudioInputStream on linux, c++ environment,
I have tried to implement MyAudioInputStream class which is defined as speechapi_cxx_audioinputstream.h and 
use InitSpeechApi_AudioInputStreamAdapterFromAudioInputStream() in speechapi_cxx_factory.h to apply the MyAudioInputStream class.
but on this point, I needed to derive the SpeechApi_AudioInputStreamAdapter struct which seems to be defined in the sdk as a default one. due to that I couldn't find any point of this already-implemented adapter to connect MyAudioInputStream to the SDK, got stuck eventually.

please let me know if I am digging wrong way, or how to fix this problem.

thank you in advance.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wolfma61** [comment]
The current version supports only file or microphone as an audiostream. 
We will soon release an update that will support to pass an audioinputstream to the factory, that should make it a lot easier ...

Wolfgang

**Comment by zhouwangzw** [comment]
Please check the new SDK version 0.4.0 which support AudioInputStream. You can find more information in How-To guides [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-audio-input-streams). And we have C# samples [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/Windows/csharp_samples/speech_recognition_samples.cs#L194). The C++ usuage is very similar, and we will provide C++ samples soon.

Please let us know if you have any questions or feedback to improve API.

Thanks,

**Comment by boldragon** [comment]
Checked. Thank you for your support.
