### ISSUE TITLE
Connection failure occurs when using this sdk in China

### ISSUE THREAD

**Issue by ufklemo** [Azure-Samples/cognitive-services-speech-sdk#60]
This app worked well before, Azure dashboard shows the last call from this app to speech service is successful in China on September 21. But this app has been unable to work since September 25 in China.

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Run cognitive-services-speech-sdk/quickstart/csharp-dotnet-windows application in China.
### Any log messages given by the failure
>Say something...
CANCELED: Reason=Error
CANCELED: ErrorDetails=Connection failed (no connection to the remote host). Internal error: 8. Error details: 998. Please check network connection, firewall setting, and the region name used to create speech factory.
CANCELED: Did you update the subscription info?
### Expected/desired behavior
>No Connection failed occurs.
### OS and Version?
> Windows 7
### Versions
>v1.0.0
### Mention any other details that might be useful
>none

**Comment by zhouwangzw** [comment]
Which service region were you using? Could you please try eastasia or southeastasia? 
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/regions

**Comment by ufklemo** [comment]
> 
> 
> Which service region were you using? Could you please try eastasia or southeastasia?
> https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/regions

I have tried eastasia region and westus region,both of them return the same error code.
![detail](https://user-images.githubusercontent.com/22672123/46183535-e343f500-c303-11e8-95ae-84ae6d7bb765.jpg)
I have tried run this app on another PC in China, but still got the same error.

**Comment by ufklemo** [comment]
> 
> 
> Could you please try use REST API as described [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/troubleshooting) to check whether you can use the Speech Service? If you can use the REST API but not running samples, the reason could be that some network settings (probably not on your local machine, but on your route connecting to Internet) like proxy or firewall prevent the websocket connection which is required for using Speech SDK.

Thank you very much for your reply and advice. I tried to use [REST API](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/troubleshooting) to validate subscription key by cURL as your advice, it looks like it's working fine.
![detail1](https://user-images.githubusercontent.com/22672123/46240127-8dd81880-c3d5-11e8-9418-09e07c233935.jpg)
![1538189561 1](https://user-images.githubusercontent.com/22672123/46240169-e0193980-c3d5-11e8-9a33-bc9c9ea580ba.jpg)
To avoid local network impact on this app, I tried to run it on Azure's VM server in China, but still got the same error.
![detail3](https://user-images.githubusercontent.com/22672123/46241749-c3d6c600-c3f0-11e8-8bfa-661371dc2875.jpg)

**Comment by zhouwangzw** [comment]
I might have not described clearly about REST API. Please use the REST API to verify whether you can use the Speech Service, which consists of 2 steps. The first step is to get an authorization token, which you have run successfully. The next step is to use the token you received for speech recognition, which is described in the next section of the same page, as [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/troubleshooting#validate-an-authorization-token
). Only this step is establishing the connection to the Speech Service (the step 1 is connecting to the token service). Have you also run Step 2, and what is the result?

Thanks,

**Comment by ufklemo** [comment]
> 
> 
> I might have not described clearly about REST API. Please use the REST API to verify whether you can use the Speech Service, which consists of 2 steps. The first step is to get an authorization token, which you have run successfully. The next step is to use the token you received for speech recognition, which is described in the next section of the same page, as [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/troubleshooting#validate-an-authorization-token). Only this step is establishing the connection to the Speech Service (the step 1 is connecting to the token service). Have you also run Step 2, and what is the result?
> 
> Thanks,

I'm sorry for my carelessness. I tried to use the token for speech recognition follow [the second step](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/troubleshooting#validate-an-authorization-token) by cURL，it looks like it's working fine.
![curl1](https://user-images.githubusercontent.com/22672123/46596497-5d982480-cb0f-11e8-85d7-ada243dac47f.jpg)
![curl2](https://user-images.githubusercontent.com/22672123/46596498-5e30bb00-cb0f-11e8-8a11-b99d327e9110.jpg)
![curl3](https://user-images.githubusercontent.com/22672123/46596499-5e30bb00-cb0f-11e8-8b8b-f1deb461a3c2.jpg)

**Comment by wolfma61** [comment]
looks like the issue was resolved.
closing this issue
