### ISSUE TITLE
How can I config what I used is Neural voices or Standard voices of "Text-to-speech"

### ISSUE THREAD

**Issue by guodan** [Azure-Samples/cognitive-services-speech-sdk#601]
In "Text-to-speech",there are three types voice, standard, custom and neural voices. And the price isn't equel. I want to use the standard voice,but I didn't found the config item of the voice type.

**Comment by rhurey** [comment]
There's a list of standard voices here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support#standard-voices

There's a sample here for how to specify the voice name: https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/eca390c47cc4da0e15528b3599e0faeba0673d40/samples/csharp/sharedcontent/console/speech_synthesis_samples.cs#L111

**Comment by oscholz** [comment]
This question appears to be answered. @guodan please reopen if you have further questions.

**Comment by guodan** [comment]
Thanks, it's good. But I find my region is japaneast where isn't support neural voice. 😄
