### ISSUE TITLE
How to control punctuation length ? 

### ISSUE THREAD

**Issue by wukun2015** [Azure-Samples/cognitive-services-speech-sdk#602]
Hello, 

Some time the recognized has long text without punctuation, which results in poor user experience especially for people with dyslexia. 

Is there any para config in speech sdk to receive different length level punctuation , e.g. short, middle or long ? 

E.g. 
- Utterance: "I have a good friend to visit next Sunday flying from Beijing to Seattle with gift to her decorated into a very beautiful flower box for Christmas surprise."
- Current reco: "I have a good friend to visit next Sunday, flying from Beijing to Seattle with gift to her decorated into a very beautiful flower box for Christmas surprise."
- Expected reco with short punctuation cofig: "I have a good friend to visit next Sunday, flying from Beijing to Seattle, with gift to her, decorated into a very beautiful flower box, for Christmas surprise.

Thank you.

**Comment by oscholz** [comment]
I reached out to the team to see if this is possible. It's not covered in [our documentation](https://docs.microsoft.com/en-us/azure/cognitive-services/Speech-Service/) so I believe the answer is No. 
If so, you can always make a feature request [here](url
![image](https://user-images.githubusercontent.com/8519705/80270446-0adc7a00-866d-11ea-9a8f-415d46d519cd.png) and we'll put this on our backlog.
Somebody will get back to you with an exact answer though. :)

**Comment by oscholz** [comment]
@wukun2015 I confirmed with the team that this isn't possible today. If you want to make a feature request, please do that at [UserVoice](https://cognitive.uservoice.com/forums/912208-speech-service), and we will put this on the backlog and slot it in based on demand.
