### ISSUE TITLE
Improving speech recognitio  for Names of persons

### ISSUE THREAD

**Issue by viju2008** [Azure-Samples/cognitive-services-speech-sdk#605]
What are the best practices to handle names of people in speech recognition as they are an open domain.

What are the capbilities or appraches to best handle names of people and places recognition.

Above was for open domain . What can be done for closed domain name recognition
Also i want to ask whether word hints can be sent to the recognizer dynamcially.

Means if i know that the words of some 100 people related to X will only be spoken out can i send that list dynamically via the SDK to the speech endpoint so that the names are recognized properly making it a closed domain name of people recognition

Regards,

**Comment by amitkumarshukla** [comment]
@viju2008 Please look at https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.phraselistgrammar?view=azure-dotnet and look for sample ContinuousRecognitionWithFileAndPhraseListsAsync inside https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_recognition_samples.cs

Do let us know if that solves your problem

**Comment by viju2008** [comment]
i added the PhraseList lines to my code in Java but it did not make a difference

        SpeechRecognizer recognizer = new SpeechRecognizer(config,audioInput);
        {
         
        	
        	 PhraseListGrammar phraseList = PhraseListGrammar.fromRecognizer(recognizer);
              phraseList.addPhrase("ram");
              phraseList.addPhrase("shyam");
              phraseList.addPhrase("jayant");

**Comment by amitkumarshukla** [comment]
I just used the following code and I was able to recognize all the word in the first shot

```java
    public static void continuousRecognitionWithPhraseListAsync() throws InterruptedException, ExecutionException, IOException
    {
        // Creates an instance of a speech config with specified
        // subscription key and service region. Replace with your own subscription key
        // and service region (e.g., "westus").
        SpeechConfig config = SpeechConfig.fromSubscription("yourkey", "yourregion");

        // Creates a speech recognizer using file as audio input.
        SpeechRecognizer recognizer = new SpeechRecognizer(config);
        {
            // Create the recognizer.
            PhraseListGrammar phraseList = PhraseListGrammar.fromRecognizer(recognizer);

            // Add a phrase to assist in recognition.
            phraseList.addPhrase("ram");
            phraseList.addPhrase("shyam");
            phraseList.addPhrase("jayant");
            

            // Subscribes to events.
            recognizer.recognizing.addEventListener((s, e) -> {
                System.out.println("RECOGNIZING: Text=" + e.getResult().getText());
            });

            recognizer.recognized.addEventListener((s, e) -> {
                if (e.getResult().getReason() == ResultReason.RecognizedSpeech) {
                    System.out.println("RECOGNIZED: Text=" + e.getResult().getText());
                }
                else if (e.getResult().getReason() == ResultReason.NoMatch) {
                    System.out.println("NOMATCH: Speech could not be recognized.");
                }
            });

            recognizer.canceled.addEventListener((s, e) -> {
                System.out.println("CANCELED: Reason=" + e.getReason());

                if (e.getReason() == CancellationReason.Error) {
                    System.out.println("CANCELED: ErrorCode=" + e.getErrorCode());
                    System.out.println("CANCELED: ErrorDetails=" + e.getErrorDetails());
                    System.out.println("CANCELED: Did you update the subscription info?");
                }
            });

            recognizer.sessionStarted.addEventListener((s, e) -> {
                System.out.println("\n    Session started event.");
            });

            recognizer.sessionStopped.addEventListener((s, e) -> {
                System.out.println("\n    Session stopped event.");
            });

            // Starts continuous recognition. Uses stopContinuousRecognitionAsync() to stop recognition.
            System.out.println("Say something...");
            recognizer.startContinuousRecognitionAsync().get();

            System.out.println("Press any key to stop");
            new Scanner(System.in).nextLine();

            recognizer.stopContinuousRecognitionAsync().get();
        }

        config.close();
        recognizer.close();
    }
```
Try this
By the way what is the speech region you are using.

**Comment by rhurey** [comment]
The important thing is that PhraseListGammars are for exact matches of the entire phrase. They don't assist at recognition of individual words in a larger phrase.

https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-phrase-lists

**Comment by viju2008** [comment]
@rhurey 

Will chaning this is to

PhraseListGrammar phraseList = PhraseListGrammar.fromRecognizer(recognizer);
          phraseList.addPhrase("rupees to ram");
          phraseList.addPhrase("rupees to shyam");
          phraseList.addPhrase("rupees to jayant");

Have a different affect.

**Comment by rhurey** [comment]
If that’s the entire phrase.

If the spoken was “1 lakh rupees to ram” having a phrase list of “rupees to ram” won’t help.

That scenario is in the area where custom speech is a better path to train a custom model.

**Comment by viju2008** [comment]
> If that’s the entire phrase.
> 
> If the spoken was “1 lakh rupees to ram” having a phrase list of “rupees to ram” won’t help.
> 
> That scenario is in the area where custom speech is a better path to train a custom model.

But how can i add all the names of Indian people.. there will be more than million names

**Comment by viju2008** [comment]
Any update

**Comment by amitkumarshukla** [comment]
@viju2008 Phrase list support is only for real-time biasing of very constrained size, typically no more than a few hundred items on a list. 

Your question about 10 million Indian names, I will say it should just work fine and you wont need to do anything unless or until there is a name which is highly uncommon. I am closing this issue for the time being as there is no other work around. Do open a new issue once you have issues.
Thank you.
