### ISSUE TITLE
Speech TTS audioDataStream C++ SDK support for higher bit and sampling rate

### ISSUE THREAD

**Issue by ronggong** [Azure-Samples/cognitive-services-speech-sdk#606]
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/eca390c47cc4da0e15528b3599e0faeba0673d40/samples/cpp/windows/console/samples/speech_synthesis_samples.cpp#L525

Does the TTS audioDataStream support for a better bitrate. The current buffer type is uint8_t. I guess it's mulaw bit rate and 8k sampling rate? Is there a better stream bit and sampling rate to choose?

Any class in the SDK to do resampling and bit conversion to PCM?

**Comment by amitkumarshukla** [comment]
@yulin-li could you please help here.

**Comment by yulin-li** [comment]
Hi @ronggong, you can find our supported format [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/rest-text-to-speech#audio-outputs). We support 8k/16k/24k sample rate and 8bit/16bit sample depth.

**Comment by ronggong** [comment]
Hi @yulin-li thanks! 

So this is the method to tell the config about the format right?
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/eca390c47cc4da0e15528b3599e0faeba0673d40/samples/cpp/windows/console/samples/speech_synthesis_samples.cpp#L217

How should I read 16bit sample from 2 elements? What is the formula to recover a single 16bit element from two 8bit elements?

**Comment by yulin-li** [comment]
`config->SetSpeechSynthesisOutputFormat(SpeechSynthesisOutputFormat::Audio16Khz32KBitRateMonoMp3);` is the correct way to set the format.

If you use 16bit raw pcm format, you can try this to convert to float[]
```c#
var sampleCount = result.AudioData.Length / 2;
var audioData = new float[sampleCount];
for (var i = 0; i < sampleCount; ++i)
{
    audioData[i] = (short)(result.AudioData[i * 2 + 1] << 8 | result.AudioData[i * 2]) / 32768.0F;
}
```

**Comment by ronggong** [comment]
@yulin-li Thanks. Could explain the syntax (result.AudioData[i * 2 + 1] << 8 | result.AudioData[i * 2]) I want to understand it. :)
