### ISSUE TITLE
[Android] Unable to find libMicrosoft.CognitiveServices.Speech.core

### ISSUE THREAD

**Issue by Ofboir** [Azure-Samples/cognitive-services-speech-sdk#607]
**Describe the bug**
I tried to implement a project using Speech SDK in Unity.
To do so, I started a new project from scratch, in which I created my own behaviours, greatly inspired by this sample :
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/unity/from-unitymicrophone
Everything works fine in the Unity editor. Both speech recognition and speech synthesis work perfectly.

When deploying to Android, the build works, the app starts but I get this message in Logcat :
Unable to find libMicrosoft.CognitiveServices.Speech.core
The speech recognition and synthesis don't work in the app.

**To Reproduce**
1. Add Speech SDK to Unity project
2. Create a MonoBehaviour using Speech SDK classes
3. Switch to Android platform
4. Build and Run

**Expected behavior**
Everything should work like in the Unity Editor.

**Version of the Cognitive Services Speech SDK**
1.11.0 downloaded from [here](https://aka.ms/csspeech/unitypackage)

**Platform, Operating System, and Programming Language**
 - OS: Android 7.0
 - Hardware - Samsung SM-G920F (arm64-v8a)
 - Programming language: C# in Unity
 - Unity version: 2019.3.9f1, using Android SDK/NDK/JDK installed with Unity

**Additional context**
Player settings in Unity:
- Minimum API Level: Android 7.0 (API Level 24)
- Target API Level: Automatic
- Scripting backend: IL2CPP
- API Compatibility Level: .NET 4.x
- Target architectures: only ARM64 is checked

**Comment by jhakulin** [comment]
@Ofboir Thanks for the feedback, I tested with following configuration and it works well:
- Unity 2019.3.11f1
- Not using Android SDK/NDK installed by Unity (checkbox unchecked) and gave paths to SDK and NDK separately
- Huawei P20 Pro, ARM64 target architecture only selected.

If you unzip the .apk file, do you see required libraries under \lib\arm64-v8a\ ?

**Comment by jhakulin** [comment]
@ofboir I tried also Android SDK/NDK/JDK installed with Unity, the package builds ok, but .apk installation does not work and fails with "There was a problem while parsing the package".

I would recommend to give a try to separate android-ndk-r19c and Android SDK not installed by Unity.

**Comment by Ofboir** [comment]
@jhakulin Thank you very much for your answer !
So the Android SDK & NDK installed with Unity seem to be the problem, why is that ? Are they too old ?

I have to figure out how to use other versions though, because Unity doesn't want NDK r19c :
![Image](https://img.tedomum.net/data/ndk-1674a7.png)

**Comment by jhakulin** [comment]
@Ofboir You can use workaround for that Unity issue as described here
https://issuetracker.unity3d.com/issues/unity-hub-android-ndk-integrated-ndk-version-is-not-compatible-with-available-unity-hub-or-android-developer-ndk-versions?_ga=2.103700805.475220060.1587760990-1460361734.1583456775

**Comment by jhakulin** [comment]
@Ofboir Did you check does .apk contain required libraries under \lib\arm64-v8a\?

**Comment by Ofboir** [comment]
> 
> 
> @Ofboir Did you check does .apk contain required libraries under \lib\arm64-v8a?

Yes, and it does

**Comment by Ofboir** [comment]
> 
> 
> @Ofboir You can use workaround for that Unity issue as described here
> https://issuetracker.unity3d.com/issues/unity-hub-android-ndk-integrated-ndk-version-is-not-compatible-with-available-unity-hub-or-android-developer-ndk-versions?_ga=2.103700805.475220060.1587760990-1460361734.1583456775

Actually, I already managed to download the required NDK version with sdkmanager.
The build works, but I still get the same error:

> Unable to find libMicrosoft.CognitiveServices.Speech.core

**Comment by jhakulin** [comment]
@Ofboir Yeah, not clear now why that happens. Has Speech SDK worked in earlier releases (1.10 or earlier) with your HW and Android 7.0 or is this your first try ?

**Comment by Ofboir** [comment]
@jhakulin This is my first try :)

**Comment by Ofboir** [comment]
OK, I finally get it to work !

Here is what I did : I tried my app on another phone (Motorola G5 with ARMv7 and Android 8.1). I still got the error message but the speech recognition/synthesis worked.

Back on the first phone, I figured that the app couldn't connect to the Internet. The error wasn't the reason why the app couldn't work, although the message made me think it was :)
I added internet permission to the Android manifest XML, and it worked ! I didn't have to do this on the other phone for some reason.

I still get the same error, but it doesn't seem to be critical:

> Unable to find libMicrosoft.CognitiveServices.Speech.core

Many thanks @jhakulin for your help !
Here are my takeaways:

1. We need to add internet permission to Android Manifest in order to maximize device (and/or Android version) compatibility.
Here is how to do it in Unity: Player settings -> Publishing settings -> check "Custom Main Manifest" and then modify the XML file (path appears under the checkbox)
2. This error message, although not critical, might be interesting to investigate.

**Comment by jhakulin** [comment]
@Ofboir Thanks for update and progress, where do you see this error message ? In the app UI ?

**Comment by jhakulin** [comment]
@Ofboir I see you earlier wrote the error message comes to logcat, I do not know why that is, but that seems to happen at the beginning when Unity starts to load libraries, eventually library is found.

**Comment by lingllting** [comment]
I also encountered issue on Google Pixel but no issue on HUAWEI device, I am sure if it's related to this issue:https://issuetracker.unity3d.com/issues/android-mono-il2cpp-unable-to-find-libc-error-thrown-when-executing-certain-sslstream-constructor. since both Samsung SM and Google Pixel are reported as problematic devices.
