### ISSUE TITLE
Feature to Add custom headers in the Web Socket while sending to Speech to Text Endpoing

### ISSUE THREAD

**Issue by viju2008** [Azure-Samples/cognitive-services-speech-sdk#608]
I am using Speech to Text Endpoint for development and plan to move to Containers for Speech to Text On-premise. I went to the SDK and container documentation but didnt find a method to add custom headers using Microsoft Speech SDK. I need to add additional authentication headers to validate at my end. Currently from the Speech SDK seems to expect the Container IP address directly as the Endpoint and doesn't support traffic flow through intermediate servers.

Is there any way to set Custom headers using the Speech to text SDK provided will sending the request by using the recognizer object.

Also i noticed that the Container doesn't validate any authorization header. The Container should also have a mechanism to input a Authentication String a shared secret which is sent by the client and validated at Container end.

Reply from @Rob Chambers

Currently the sdk doesn't support the ability to add custom headers to the http websocket upgrade connection, nor add custom headers to individual web socket messages. However, the sdk does support pass thru proxy relays such as you're building. You could send a custom web socket message prior to starting recognition. See Connection.SendMessageAsync... Your proxy relay could intercept such messages and disallow relay prior to the custom message containing your private authentication message.

@Reply from viju2008

But i need the feature of custom headers as its expected for many more things. Is this feature of custom heaserr planned in near future

Also after the initial message also I need to check at each socket sent message the header to prevent a highjacked TCP session case from happening by creating spoofed packets with MITM attacks. Hence I need the custom header for all the communication.

**Hence I am making a feature request for Adding Custom Headers for the whole communication.**

**Comment by robch** [comment]
I've logged an internal work item to track this request. I can't commit to a timeline at this point, but I'm hopeful that we can add this capability in the near future. Internally logged as task #2749417.

**Comment by wasid003** [comment]
do you know about loft.speech.google.com

**Comment by viju2008** [comment]
> do you know about loft.speech.google.com

No i am not aware

**Comment by pankopon** [comment]
Closing the issue as we have a backlog work item and will address it in a future release. Once the work is done, we will update this issue to let you know what release the feature will be in.
