### ISSUE TITLE
Custom Speech Model support in browser sample

### ISSUE THREAD

**Issue by prwani** [Azure-Samples/cognitive-services-speech-sdk#609]
**Is your feature request related to a problem? Please describe.**
The browser sample (https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/index.html) currently works well for public Speech endpoint. It will be great if this can also support Custom speech model.

**Describe the solution you'd like**
An additional text box on this page where the user can provide endpointID or modelID of the model developed using Custom Speech at Speech Studio (https://speech.microsoft.com/)

**Describe alternatives you've considered**

**Additional context**

**Comment by robch** [comment]
Thanks for the feedback. I've logged the feature request in our internal tracking system as task #2749428. Checking with team to see if there other easy mechanisms for you to work around.

**Comment by pankopon** [comment]
Closing the issue since a backlog work item has been created. We will address this in a future release. Once the work is done, we will update this issue to let you know what release the feature will be in.
