### ISSUE TITLE
Is there a way to control Segmentation length of recognized result ? 

### ISSUE THREAD

**Issue by wukun2015** [Azure-Samples/cognitive-services-speech-sdk#610]
Hello,

Is there a way like speech config parameter to control recognized result text length ? i didn't find such config in sdk doc. 

The reason and scenario of this asking is that, some time the output recognized text is too long to render friendly, e.g. mobile app with recognized text limit of 2 lines each max 20-char (or less). 

E.g. 

- Utterance: I will go to bookstore this afternoon to check if any new arrivals. After that Jack will pick up me there to gym for practice. We need to prepare a match in two weeks. Dinner will be taken in gym to save commute overhead. I will arrive home around 8:30 in the evening. 

- Current result from speech sdk: 
RECOGNIZED: Text=I will go to a bookstore this afternoon to check if any new arrivals after that Jack will pick up me there to gym for practice.
RECOGNIZED: Text=We need to prepare a match in two weeks.
RECOGNIZED: Text=Dinner will be taken in gym to save commute overhead. I will arrive home around 8:30 in the evening.

- Expect result: There shall be a control of segmentation length level (or even better, value) like short, middle or long. E.g. for middle segmentation length, below is expectation:
RECOGNIZED: Text=I will go to a bookstore this afternoon to check if any new arrivals.
RECOGNIZED: Text = After that Jack will pick up me there to gym for practice.
RECOGNIZED: Text=We need to prepare a match in two weeks.
RECOGNIZED: Text=Dinner will be taken in gym to save commute overhead. 
RECOGNIZED: Text=I will arrive home around 8:30 in the evening.

Thank you.

**Comment by amitkumarshukla** [comment]
Currently we dont  have this feature. I will recommend you to split the string based on your need. Do let me know if that works.

**Comment by amitkumarshukla** [comment]
If you think it is an important feature for you, please create a feature request here https://cognitive.uservoice.com/forums/912208-speech-service. 

Thanks a lot

**Comment by viju2008** [comment]
Me too need this feature
