### ISSUE TITLE
speech, TTS, Libgstreamer-1.0-0.dll is missing, windows 8.1

### ISSUE THREAD

**Issue by ronggong** [Azure-Samples/cognitive-services-speech-sdk#611]
Hi,

The script calls TTS API:

```cpp
   auto config = SpeechConfig::FromSubscription("", "");

    config->SetSpeechSynthesisOutputFormat(SpeechSynthesisOutputFormat::Raw16Khz16BitMonoPcm);

    auto synthesizer = SpeechSynthesizer::FromConfig(config, nullptr);

    // Creates a speech synthesizer using the default speaker as audio output. The default spoken language is "en-us".

    // Receives a text from console input and synthesize it to speaker.

    std::string text = "Receives a text from console input and synthesize it to speaker.";

    auto result = synthesizer->SpeakTextAsync(text).get();
```

It reports libgstreamer-1.0-0.dll missing. However, if I close the error dialogue and the synthesis works successfully. Why do we need libgstreamer-1.0-0.dll in this case? Can I disable it in my application?

**Comment by amitkumarshukla** [comment]
@ronggong Looks like you are using C++ APIs. I was trying to repro your scenario and I was not able to repro it. Could you provide more details about your environment. 

Also please add 
```cpp
config->SetProperty(PropertyId::Speech_LogFilename, "LogfilePathAndName.txt");
 ```

And provide us the text file. I want to see what is going on.

**Comment by ronggong** [comment]
[log.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4561048/log.txt)

Here you have the log file.

The error message is "The program can't start because libgstreamer-1.0-0.dll is missing from you computer. Try reinstalling the program to fix this issue"

I didn't install gstreamer on my laptop. My OS is windows 8.1. Maybe install gstreamer can solve the issue, but I can't force users who use the app also install it.

**Comment by amitkumarshukla** [comment]
@yulin-li If you could please look at this. From the logs I do not see that we are trying to load the *codec.dll. Is there any dependency of synthesis on gstreamer ?

**Comment by jhakulin** [comment]
@ronggong Windows 8.1 is not supported configuration, could you update to Windows 10 or later?

The Speech SDK supports Windows 10 and Windows Server 2016, or later versions. Earlier versions are not officially supported. It is possible to use parts of the Speech SDK with earlier versions of Windows, although it's not advised.

**Comment by ronggong** [comment]
@jhakulin Thanks, let me update my OS and try again.

**Comment by ronggong** [comment]
Problem solved after updating to Windows 10
