### ISSUE TITLE
Disable interim recognition

### ISSUE THREAD

**Issue by genabotpub** [Azure-Samples/cognitive-services-speech-sdk#612]
Hello,

Our application performs an ASR using the the SDK `startContinuousRecognitionAsync ()` approach.

We successfully receive the transcribed final text by subscribing to the `recognized` event.

Many of our users use mobile devices and we would like to minimize the data traffic. Is there a methodology to disable the interim submission of the binary recordings and submit only the final complete recording upon the user's silence?

Will such approach increase the recognition latency?

Thank you

**Comment by amitkumarshukla** [comment]
I didnt understand your problem definition completely but based on your description I assume that you do not want to stream the silence to the service.

From the time you call startContinuousRecognitionAsync(), speech sdk starts pushing the pcm data captured from microphone to the service. It will even stream the silence also. If you do not want to stream the silence consider using keyword recognizer. In that case only when the keyword is spoken only after that the data is submitted to the service. Do let us know if that solves your problem.

**Comment by genabotpub** [comment]
Thank you for you response. 

Please let me know if the following description makes more sense.

Based on the review of the websocket traffic between the browser client SDK instance and STT endpoint, it seems that not only the silence but also partial audio chunks are sent to the server. The processing of those chunks seem to result in interim results until the final recognition result is constructed and sent back. Please see the attached screenshot.
![image](https://user-images.githubusercontent.com/32314985/80649227-9ffdbb00-8a3f-11ea-9c5f-c14514b555bb.png).

Since I am interested only in the final result, is there a method to configure the client SDK instance to minimize the traffic.

I hope it makes sense.

**Comment by amitkumarshukla** [comment]
@genabotpub Now I understand that. There is a binary traffic and there is a text traffic. The binary traffic is the audio data going from client to the service. This is a needed data for service to do speech to text. 

On the other hand the text data is from service to the client. This is the result of the recognition. Right now there is no way we can disable this. Please feel free to submit a feature request https://cognitive.uservoice.com/forums/912208-speech-service

Our team will look at this and will decide one its priority.

Thanks a lot. Closing it for the time being.

**Comment by viju2008** [comment]
I too have posted for asking this feature... this feature could be an optional feature and also chunk size need to be increased

**Comment by amitkumarshukla** [comment]
@viju2008 I am really sorry as I missed the part where you are asking about chunk size. You can set the chunk size using "SPEECH-BytesPerFrame" property.

I assume you are using JAVA so you can use 
```java
// If you want to write 1 second chunk for 16khz, 16 bit mono wave file
config.setProperty("SPEECH-BytesPerFrame", "32000");
``

**Comment by viju2008** [comment]
Does this ensure that the whole chunk together.. suppose i have a 10 second audio... i want to send to the container/speech endpoint the whole audio file of 10 seconds.. in case of container the intermediate server and the container will be on same network ... hence whole chunk can be sent without network issues

**Comment by amitkumarshukla** [comment]
For 1 second it is 32000, for 2 seconds it is 64000. It depends upon your scenario, how much data is sent to the service in one chunk. If you are doing the recognition from a file it will be the amount that you specify will be send in one chunks (like 32000 or 64000). If you are doing it from Microphone, it will always be 3200 bytes of data in one chunk. Because for the case of microphone we do not want to introduce latency to the person who is speaking. 

Do let me know if it answers your question

**Comment by viju2008** [comment]
AudioConfig audioInput = AudioConfig.fromWavFileInput("F:\\test.wav");
        
        config.setProperty("SPEECH-BytesPerFrame", "96000");
     
    // audioInput = AudioConfig.fromWavFileInput("F:\\test.wav");
        System.out.println("Audio Input Intialized");
        SpeechRecognizer recognizer = new SpeechRecognizer(config,audioInput);
        {
            // Subscribes to events.
            recognizer.recognizing.addEventListener((s, e) -> {
                System.out.println("RECOGNIZING: Text=" + e.getResult().getText());
            });


It is not connecting to the container now . If i comment the line      config.setProperty("SPEECH-BytesPerFrame", "96000"); the speech recognizer works.

**Comment by rhurey** [comment]
The maximum websocket message size supported is 64K.

The SPEECH-BytesPerFrame value was meant to be used to fine tune transmission sizes to align with various possible network frame sizes. It's not meant to try and get the audio to the service in an atomic block as the underlying transport layer is going to fragment the message anyways. We wanted the ability to align as closely as possible with that underlying fragmentation to reduce latency in getting responses back to the client.

**Comment by viju2008** [comment]
So is the conclusion that partial resultd cant be disabled ??

**Comment by amitkumarshukla** [comment]
Yes. For the time being this is the default behaviour.

**Comment by jzhw0130** [comment]
Need the feature, make `partial results` optional ..
