### ISSUE TITLE
Speech C++, GUI thread block

### ISSUE THREAD

**Issue by ronggong** [Azure-Samples/cognitive-services-speech-sdk#613]
Hi, 

I am using JUCE (https://juce.com/) for GUI. The execution of the below code freezes the GUI. Wall time elapsed mainly from line `auto result = synthesizer->SpeakTextAsync(text).get();` to `auto audioDataStream = AudioDataStream::FromResult(result);`.

If SpeakTextAsync runs asynchronously, it should not freeze the GUI, no? Or is there a callback function for SpeakTextAsync to use?

```cpp
auto config = SpeechConfig::FromSubscription("", "");

    config->SetSpeechSynthesisOutputFormat(SpeechSynthesisOutputFormat::Raw16Khz16BitMonoPcm);
    auto synthesizer = SpeechSynthesizer::FromConfig(config, nullptr);
    
auto result = synthesizer->SpeakTextAsync(text).get();

    // Checks result.
    if (result->Reason == ResultReason::SynthesizingAudioCompleted)
    {
        auto audioDataStream = AudioDataStream::FromResult(result);
        uint8_t buffer[16000];
        uint32_t totalSize = 0;
        uint32_t filledSize = 0;
} else if ....
```

**Comment by amitkumarshukla** [comment]
SpeakTextAsync returns a future of type std::future<std::shared_ptr<SpeechSynthesisResult>>. If you do a get on the future it will be stuck till it finishes. So if you are not planning to stuck it here, do not do a get on the future.

**Comment by ronggong** [comment]
I don't know how to do continuation tasks with std::future. The method future::wait_for still blocks. So finally I use the synchronous SpeakText method with Parallel Patterns Library.
