### ISSUE TITLE
Bug TLS connection from android sdk 

### ISSUE THREAD

**Issue by viju2008** [Azure-Samples/cognitive-services-speech-sdk#614]
This has reference to issue 604

I am using my own own built endpoint to forward the requests to speech endpoint

I am connecting from Android SDK and i am getting TLS verify fail using mocrosoft SDK

I am conncting from Destop SDK and i am not getting TLS ISSUE. It succeeds.

Log file is given in issue 604

If the certificate was the issue the desktop sdk should also have rejected thr connection.

Also need to know how i can increase the log level for the logging in android sdk

**Comment by rhurey** [comment]
Can you send us the URL or the certificate's public information in .cer format to inspect?

And what Android version you're using.

**Comment by viju2008** [comment]
Android 7.1.1 
Model AZUS_Z01BDB

**Comment by viju2008** [comment]
Any updates

**Comment by oscholz** [comment]
@viju2008 sorry for the radio silence.
Could you please email your URL to oliversc_at_microsoft.com (replace _at_ with @). 
We'll see what we can do.
