### ISSUE TITLE
It takes too long to start recognition

### ISSUE THREAD

**Issue by tonyalves** [Azure-Samples/cognitive-services-speech-sdk#616]
I'm using "recognizeOnceAsync().get()" with a stream of wav file, but it takes about 3s-5s to start the recognizing. Is there any way to reduce this time?
Ex.:
[2020-05-02 17:08:28] [INFO   ] STARTING 
[2020-05-02 17:08:29] [INFO   ] IntentRecognitionResult result = recognizer.recognizeOnceAsync().get() 
[2020-05-02 17:08:32] [INFO   ] RECOGNIZING: Text=yes 
[2020-05-02 17:08:33] [INFO   ] RECOGNIZED: Text=yes. 
[2020-05-02 17:08:33] [INFO   ]     Intent Id: Utilities.Confirm

**Comment by viju2008** [comment]
Even i am facing same issue. How to reduce the time.

**Comment by rhurey** [comment]
We'd need a log file from the SDK to be able to diagnose this successfully. Instructions on how to grab one are here:

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

**Comment by tonyalves** [comment]
> We'd need a log file from the SDK to be able to diagnose this successfully. Instructions on how to grab one are here:
> 
> https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

HI!
Here's the log:
https://pastebin.com/9RXV9S3T

**Comment by rhurey** [comment]
Ok, the longest time from the client side appears to be downloading and verifying the Certificate Revocation List as there wasn't a cached copy.

Couple of questions about that:
1) Is this just the first connection every so often that's slow, or all of them?

2) Can you verify that there's a "TMP" or "TMPDIR" environment variable configured?

**Comment by tonyalves** [comment]
> Ok, the longest time from the client side appears to be downloading and verifying the Certificate Revocation List as there wasn't a cached copy.
> 
> Couple of questions about that:
> 
> 1. Is this just the first connection every so often that's slow, or all of them?
> 2. Can you verify that there's a "TMP" or "TMPDIR" environment variable configured?

1- All connections took this time, about 5s-6s.
2 - You mean OS enviroment or inside my application with JVM?

**Comment by BrianMouncer** [comment]
for #2 take a look at this info on configuring OpenSSL on linux.  You may not be using RedHat, but the temp folder path applies elsewhere too.

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-openssl-linux

 Note

It is also worth noting that some distributions of Linux do not have a TMP or TMPDIR environment variable defined. This will cause the Speech SDK to download the Certificate Revocation List (CRL) every time, rather than caching the CRL to disk for reuse until they expire. To improve initial connection performance you can create an environment variable named TMPDIR and set it to the path of your chosen temporary directory..

**Comment by viju2008** [comment]
Where to configure the TMPDIR... In android sdk...where to create it... In android... In external or internal storage of app... What else will go into tmpdir ...from security perspective

**Comment by tonyalves** [comment]
> for #2 take a look at this info on configuring OpenSSL on linux. You may not be using RedHat, but the temp folder path applies elsewhere too.
> 
> https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-openssl-linux
> 
> Note
> 
> It is also worth noting that some distributions of Linux do not have a TMP or TMPDIR environment variable defined. This will cause the Speech SDK to download the Certificate Revocation List (CRL) every time, rather than caching the CRL to disk for reuse until they expire. To improve initial connection performance you can create an environment variable named TMPDIR and set it to the path of your chosen temporary directory..

I checked this, about SSL is OK according to the documentation.
I noticed that it downloads the certificate for /tmp, these two files: 653b494a.crl.0  a67e6792.crl.0.
They remain in the folder after the program exits.

Here the log after running the programa 3 times:
https://pastebin.com/ShBZacZx

**Comment by viju2008** [comment]
@tonyalves 

After implenting tmpdir how much reduction in time happened. How many seconds reduced to start

**Comment by tonyalves** [comment]
> @tonyalves
> 
> After implenting tmpdir how much reduction in time happened. How many seconds reduced to start

In my case, I noticed that the certificates files were already been downloaded at /tmp. I dind't implement nothing cause the tmpdir was already used. It continues with the delay 5s-6s.

**Comment by viju2008** [comment]
@rhurey  

In the context of the reply from @tonyalves  ... please provide us solution to overcome this problem. 

In windows how to create TMPDIR... i could not make out from the document how to do it. In android SDK also how to do it so that atleast i can try out the solution

**Comment by pankopon** [comment]
@rhurey Based on your analysis, is there any area that could be improved in the SDK or otherwise? Please update.

**Comment by oscholz** [comment]
@tonyalves @viju2008 
The only indication we have at this point that anything is wrong is that it takes 1500ms to get a response from LUIS for intent recognition. That should take 300 to 500ms. The first thing we should look at here is where the Speech and LUIS resources are deployed relative to one another, and relative to where you are.
As a rule: You want to deploy the Speech and LUIS resources in the same region to decrease the amount of time required for the services to communicate with one another. And you want to deploy both services as close to your location as is available. 
For the Speech service, you can find the available regions here:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/regions
For both LUIS and Speech you can find this information here:
https://azure.microsoft.com/en-us/global-infrastructure/services/?products=cognitive-services
I am going to close this issue for now. If you are in the same regions, and relatively close to your location, and you still have trouble, please reactivate this issue and let us know the details of your configuration.
