### ISSUE TITLE
Can I get pronunciation score using the sdk version?

### ISSUE THREAD

**Issue by ziadhassan7** [Azure-Samples/cognitive-services-speech-sdk#618]
If I want to get the pronScore - fluency - accuracy should I use the Rest-API or can I get it using the sdk version?

**I'm using it in android and I was able to get the confidence score using this:**
```
SpeechConfig config = SpeechConfig.fromSubscription(speechSubscriptionKey, serviceRegion);

config.setServiceProperty("wordLevelConfidence","true", ServicePropertyChannel.UriQueryParameter);
config.setServiceProperty("format", "detailed", ServicePropertyChannel.UriQueryParameter); 
```
_But how can I get the other information like word pronunciation and ext._

**Comment by amitkumarshukla** [comment]
@ziadhassan7 Thanks a lot for your query. We will get back to you asap.

**Comment by amitkumarshukla** [comment]
@ziadhassan7 The feature is under development. If you can explain your use case and business we can plan to prioritize it higher.

**Comment by ziadhassan7** [comment]
I'm working on something to train and develop the speaking skill to non-English natives; so, it would be great if I could show the user how much accurate they pronounced each word.

**I've been also trying to do that on the REST-API using Postman to check if I could do it there, and to figure out what parameter should I pass to the url; So, maybe I could do that on the sdk version as well, but it didn't work with me neither!!** 

I should pass `pronunciationScoreParams` as the parameter and a JSON Base64 encoded text as the value of the parameter right? Or should I convert the json first to UTF8?

I tried both and nothing worked for me and I used those websites: [to Base64](https://codebeautify.org/json-to-base64-converter) - [to UTF8](https://www.browserling.com/tools/utf8-encode)

And I used the example JSON from documentations without spaces:
```
{
  "ReferenceText": "Good morning.",
  "GradingSystem": "HundredMark",
  "Granularity": "FullText",
  "Dimension": "Comprehensive"
}
```

**Comment by yinhew** [comment]
@ziadhassan7 do you mind sharing your code to call the REST API, so that I can check where the issue locates?
Also, can you give an estimation how much daily traffic (usage) you will have on your product? This can help us judge the priority of the SDK support.

**Comment by ziadhassan7** [comment]
@yinhew I haven't written the code yet, i'm using a software called Postman to test the API first.

**I converted this JSON** `{"ReferenceText":"Good morning."}`
**to this UTF-8 code:** 
`\x7b\x22\x52\x65\x66\x65\x72\x65\x6e\x63\x65\x54\x65\x78\x74\x22\x3a\x22\x47\x6f\x6f\x64\x20\x6d\x6f\x72\x6e\x69\x6e\x67\x2e\x22\x7d`
**and then from UTF-8 to Base64:**
```
XHg3Ylx4MjJceDUyXHg2NVx4NjZceDY1XHg3Mlx4NjVceDZlXHg2M1x4NjVceDU0XHg2NVx4Nzhc
eDc0XHgyMlx4M2FceDIyXHg0N1x4NmZceDZmXHg2NFx4MjBceDZkXHg2Zlx4NzJceDZlXHg2OVx4
NmVceDY3XHgyZVx4MjJceDdk
```
 So now, the url looks like that:
https://westus.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?language=en-US&Ocp-Apim-Subscription-Key=[API-KEY]&Content-Type=audio/wav; codecs=audio/pcm; samplerate=16000&pronunciationScoreParams=XHg3Ylx4MjJceDUyXHg2NVx4NjZceDY1XHg3Mlx4NjVceDZlXHg2M1x4NjVceDU0XHg2NVx4Nzhc
eDc0XHgyMlx4M2FceDIyXHg0N1x4NmZceDZmXHg2NFx4MjBceDZkXHg2Zlx4NzJceDZlXHg2OVx4
NmVceDY3XHgyZVx4MjJceDdk

And that's the result;
```
{
    "RecognitionStatus": "Success",
    "DisplayText": "Figure 2 shows an example of processing of speech using human ear models. He acted swiftly when his time came, taking all Miller. Last year the NBA playoffs. The boys humiliated themselves against Detroit control activities. It's important for the first time in 10 years research and development spending in the federal budget program. She's proprietary Macintosh graphic displays.",
    "Offset": 200000,
    "Duration": 214200000
}
```

**Comment by yinhew** [comment]
@ziadhassan7 can you replace the "conversation" in the URL into "interactive" and try again?
We currently still don't support the pronunciation assessment feature on "conversation" route, and only "interactive" route is support. Sorry for the misleading in the doc.
The "conversation" support should come out in the coming 1~2 weeks.

**Comment by ziadhassan7** [comment]
**Ok, this is great! now it says this:**
Unexpected json in 'pronunciationScoreParams' parameter. Unexpected character encountered while parsing value: \. Path '', line 0, position 0. Please make sure the JSON string is encoded with UTF8 and then base64.

Those are the websites that I used:
[UTF-8 Encoder](https://www.browserling.com/tools/utf8-encode)
[UTF-8 to Base64](https://onlineutf8tools.com/convert-utf8-to-base64)
**Maybe there is a setting in the website that i used wrong, any suggestion?**

**And also, Is there is any turnaround for using pronunciation in SDK ?**

**Comment by yinhew** [comment]
@ziadhassan7 I looked at your base64 string. I found its generated from string "\x7b\x22\x52\x65\x66\x65\x72\x65\x6e\x63\x65\x54\x65\x78\x74\x22\x3a\x22\x47\x6f\x6f\x64\x20\x6d\x6f\x72\x6e\x69\x6e\x67\x2e\x22\x7d". This is not the right way to do the base64 encoding.

For your JSON, the right base64 should be eyJSZWZlcmVuY2VUZXh0IjoiR29vZCBtb3JuaW5nLiJ9

**Comment by ziadhassan7** [comment]
**Thanks, mr @yinhew ! That worked.** 
It's weird that is says "Please make sure the JSON string is encoded with UTF8 and then base64." but it worked by encoding the JSON to Base64 directly. Maybe, the converter did the job by itself . 

Again, Thanks a lot and I hope the SDK version support `pronunciationScoreParams` soon. :D

**Comment by fabswt** [comment]
**Any update on when `dimension=Comprehensive` will be available from the Python SDK?** It's just more convenient to use the SDK than use the REST API. Also, the discrepancies between the two make room for confusion.

For anyone else stumbling upon this:

- The `dimension` parameter for Pronunciation Assessment is [usable and documented here in the REST API].(https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-speech-to-text-short#pronunciation-assessment-parameters)
- The same parameter is missing (not supported) from the Python [examples](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-pronunciation-assessment?pivots=programming-language-javascript) and [docs](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.pronunciationassessmentconfig?view=azure-python), because it's not yet part of the SDK.

Time spent clarifying such things up would be best spent coding and building something :)
