### ISSUE TITLE
Speech Recognition canceled 0x13

### ISSUE THREAD

**Issue by prabhukumardasari12** [Azure-Samples/cognitive-services-speech-sdk#620]
I got this error on android. The same apk is working fine in Oculus. \

2020-05-05 12:15:21.187 7569-7611/com.cognizant.lih.vr E/Unity: ApplicationException: Exception with an error code: 0x13 (SPXERR_START_RECOGNIZING_INVALID_STATE_TRANSITION)
      at Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail (System.IntPtr hr) [0x0005d] in <e8726d28585047138b8a3d5bf747813a>:0 
      at Microsoft.CognitiveServices.Speech.Recognizer.StartContinuousRecognition () [0x0005c] in <e8726d28585047138b8a3d5bf747813a>:0 
      at Microsoft.CognitiveServices.Speech.Recognizer.DoAsyncRecognitionAction (System.Action recoImplAction) [0x0005d] in <e8726d28585047138b8a3d5bf747813a>:0 
      at Microsoft.CognitiveServices.Speech.SpeechRecognizer.<StartContinuousRecognitionAsync>b__44_0 () [0x00001] in <e8726d28585047138b8a3d5bf747813a>:0 
      at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <0d749d7f5412452cb2b96c9f998d1075>:0 
      at System.Threading.Tasks.Task.Execute () [0x00010] in <0d749d7f5412452cb2b96c9f998d1075>:0 
    --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDis

Any suggestions?
Thanks Regards,
Prabhu

**Comment by jhakulin** [comment]
@prabhukumardasari12 Thanks for feedback, could you share more information, do you use streams (pull or push) and Unity microphone ? Does the issue happen occasionally or always ? If you use streams and Unity microphone, do you happen to close the mic before stopping the recognition?

**Comment by prabhukumardasari12** [comment]
Hi I am using streams and microphone input. Without using streams it is working fine. But I need to capture the mcrophone volume and pitch. So I am taking the input from microphone and using streams. The same code works fine in Oculus devices.
The speech gets cancelled while recognizing before I stop the mic.
Is there any way to capture the microphone data with speech sdk.

Regards,
Prabhu Kumar Dasari

________________________________

**Comment by jhakulin** [comment]
@prabhukumardasari12 Capturing mic data from SDK is not possible yet, but will be in future releases.
Could you share more details when do you close the Unity microphone stream vs do StopContinuousRecognitionAsync? Could you share the code sample for that?

**Comment by prabhukumardasari12** [comment]
using Microsoft.CognitiveServices.Speech;
using Microsoft.CognitiveServices.Speech.Audio;
using System;
using System.IO;
using System.Collections.Generic;
using UnityEngine;
using System.Linq;
using UnityEngine.UI;
using System.Threading.Tasks;

public class SpeechTranscriber : AnalyzerModule<SpeechTranscriberResult>
{
    public struct Utterance
    {
        public TimeSpan StartingTime;
        public TimeSpan Duration;
        public string SpokenText;
    }

    public string APIKey;
    public string APIRegion;
    public OVRMicInput MicrophoneInput;
    [Tooltip("The amplitude under which the sound will be considered silent.")]
    [Range(0.0f, 0.1f)]
    public float SilenceThreshold = 0.002f;
    [Tooltip("The duration of silence, in seconds, for the end of speech to be detected.")]
    [Range(0.1f, 10f)]
    public float SilenceTimeout = 3.0f;
    public bool StartOnAwake;
    public Text DebugSilenceThresholdValueText;

    public List<Utterance> Utterances { get; private set; }
    public SpeechRecognizer Recognizer { get; private set; }

    public bool HasTranscriptionAvailable =>    readStream.Length > 0
                                            ||  savedStreams.Count > 0
                                            ||  newSpeechStarted;

    public bool IsBusyTranscribing => readStream.Length > 0
                                    || savedStreams.Count > 0;

    AudioConfig audioConfig;
    SpeechConfig speechConfig;
    MemoryStream writeStream;
    MemoryStream readStream;
    Queue<MemoryStream> savedStreams;
    bool isSilent;
    bool newSpeechStarted;
    long silenceStarted;
    TaskCompletionSource<int> stopRecognition;

    string maxAudioString;
    public OVRMicInput oVRMicInput;
    private void Awake()
    {
        Utterances = new List<Utterance>();
        writeStream = new MemoryStream();
        readStream = new MemoryStream();
        savedStreams = new Queue<MemoryStream>();

        SetupSpeechSDK();// This only works because I manually edited the script execution order
        // to always go AFTER OVRMicInput
        if (StartOnAwake)
            StartRecording();

    }
    private void Start()
    {
        //Invoke("SpeechInint", 1);
    }

    void SpeechInint()
    {



    }


    bool recognitionStarted=false;
    private object threadLocker = new object();
    private string message;
    protected override async void Update()
    {
        base.Update();

        if (!IsRunning) return;

        if (DebugSilenceThresholdValueText)
        {
            DebugSilenceThresholdValueText.text = maxAudioString;
        }


        if (savedStreams.Count > 0 && readStream.Length == 0)
        {
            Debug.Log("reached");
            MemoryStream nextStream = savedStreams.Dequeue();

            nextStream.Seek(0, SeekOrigin.Begin);
            readStream.Seek(0, SeekOrigin.Begin);
            nextStream.CopyTo(readStream);
            readStream.Seek(0, SeekOrigin.Begin);

             if (started == true)
             {
                  stopRecognition = new TaskCompletionSource<int>();

             await Recognizer.StartContinuousRecognitionAsync().ConfigureAwait(false);

             Task.WaitAny(new[] { stopRecognition.Task });

             await Recognizer.StopContinuousRecognitionAsync().ConfigureAwait(false);
             }
           // readStream.SetLength(0);

            //await Recognizer.StopContinuousRecognitionAsync().ConfigureAwait(false);


        }
    }







    void OnMicrophoneInputReceived(float[] data, int channels)
    {
        if (!IsRunning) return;

        if (newSpeechStarted)
        {
            byte[] wav = WavUtility.GetRawAudioBytes(data);
            writeStream.Write(wav, 0, wav.Length);
        }

        float maxAudio = 0;
        for (int i = 0; i < data.Length; i++)
        {
            maxAudio = Mathf.Max(maxAudio, Mathf.Abs(data[i]));
        }

        // Debug for baseline screen
        maxAudioString = maxAudio.ToString("F4");

        // Is the current data set silent?
        if (maxAudio <= SilenceThreshold)
        {
            // Silence just started this frame
            if (!isSilent)
            {
                isSilent = true;
                silenceStarted = DateTime.Now.Ticks;
            }
            else
            {
                // We've been silent for a time
                TimeSpan duration = TimeSpan.FromTicks(DateTime.Now.Ticks - silenceStarted);
                if (duration.TotalSeconds > SilenceTimeout && newSpeechStarted)
                {
                    writeStream.Seek(0, SeekOrigin.Begin);

                    // Copy and save the current recorded clip
                    var stream = new MemoryStream();
                    writeStream.CopyTo(stream);
                    savedStreams.Enqueue(stream);

                    // Reset the detection stream
                    writeStream.SetLength(0);

                    newSpeechStarted = false;
                }
            }
        }
        else
        {

            if (isSilent && !SessionMonitor.itsOver) newSpeechStarted = true;

            isSilent = false;
        }
    }

    protected override void Analyze()
    {
        //Debug.Log("Analyze");

        analyzedResult = new SpeechTranscriberResult
        {
            CompleteTranscription = new List<string>()

            //WordsFound = new Dictionary<string, int>()
        };

        float totalSpeakTime = 0;
        float previousEndTime = -1;

        foreach (var utterance in Utterances)
        {
            if (previousEndTime > 0)
            {
                analyzedResult.TotalSilenceTime += (float)utterance.StartingTime.TotalSeconds - previousEndTime;
            }

            previousEndTime = (float)(utterance.StartingTime.TotalSeconds + utterance.Duration.TotalSeconds);

            if (utterance.SpokenText.Length == 0)
            {
                analyzedResult.TotalSilenceTime += (float)utterance.Duration.TotalSeconds;
            }
            else
            {
                totalSpeakTime += (float)utterance.Duration.TotalMinutes;
                analyzedResult.TotalCount += utterance.SpokenText.Sum(c => char.IsWhiteSpace(c) ? 1 : 0) + 1;
                analyzedResult.CompleteTranscription.Add(utterance.SpokenText);
            }
        }

        analyzedResult.TotalSpeakTime = totalSpeakTime * 60f;
        analyzedResult.WordsPerMinute = analyzedResult.TotalCount / totalSpeakTime;
    }

    private void OnDestroy()
    {

      //  StopRecording();
    }

    bool started = false;
   public void SetupSpeechSDK()
    {
        Debug.Log("Reached Setup");
        var format = AudioStreamFormat.GetWaveFormatPCM(44100, 16, 2);
        var binaryReader = new BinaryReader(readStream);


        audioConfig = AudioConfig.FromStreamInput(new BinaryAudioStreamReader(readStream), format);
        speechConfig = SpeechConfig.FromSubscription(APIKey, APIRegion);


       //  Recognizer = new SpeechRecognizer(speechConfig);
         Recognizer = new SpeechRecognizer(speechConfig, audioConfig);
        //Recognizer.Recognizing += RecognizingHandler;
         Recognizer.Canceled += Recognizer_Canceled;
         Recognizer.Recognized += Recognizer_Recognized;
         Recognizer.SessionStopped += Recognizer_SessionStopped;

       //StartRecording();
    }

    private void Recognizer_SessionStopped(object sender, SessionEventArgs e)
    {
        stopRecognition.TrySetResult(0);
    }


    public void GetData(TimeSpan _duration,string _spokentext,TimeSpan _time)
    {
        Utterance utterance = new Utterance()
        {
            Duration =_duration,
            SpokenText = _spokentext,
            StartingTime = _time
        };

        Utterances.Add(utterance);
        Debug.Log("current words count "+Utterances.Count);
        readStream.SetLength(0);
    }
    private void Recognizer_Recognized(object sender, SpeechRecognitionEventArgs e)
    {
        Debug.Log(e.Result.Reason);
         if (e.Result.Reason == ResultReason.RecognizedSpeech)
         {
             lock (threadLocker)
             {
                 message = e.Result.Text;
                 Debug.Log(e.Result.Text);
                 if (message != null)
                 {

                 }
             }
         }


         if (e.Result.Reason == ResultReason.RecognizedSpeech)
         {
              Debug.Log(e.Result.Text);

              Utterance utterance = new Utterance()
              {
                  Duration = e.Result.Duration,
                  SpokenText = e.Result.Text,
                  StartingTime = new TimeSpan(e.Result.OffsetInTicks)
              };

              Utterances.Add(utterance);
              readStream.SetLength(0);
              // recognitionStarted = false;
          }

    }

    private void Recognizer_Canceled(object sender, SpeechRecognitionCanceledEventArgs e)
    {
        if (e.ErrorCode != CancellationErrorCode.NoError)
        {
            Debug.LogError($"Error Code: {e.ErrorCode}");
            Debug.LogError($"Error Details: {e.ErrorDetails}");
            Debug.LogError($"Error Offset: {e.Offset}");
            Debug.LogError($"Error Reason: {e.Reason}");
            Debug.LogError($"Error Result: {e.Result}");
        }

        stopRecognition.TrySetResult(0);
    }

    public async void StartRecord()
    {
         await Recognizer.StartContinuousRecognitionAsync().ConfigureAwait(false);
    }

    public void StartRecording()
    {
       // StartRecord();
        Debug.Log(IsRunning);
        if (IsRunning) return;

      MicrophoneInput.OnMicrophoneDataInput.AddListener(OnMicrophoneInputReceived);
        started = true;
        IsRunning = true;
    }

    public void StopRecording()
    {
        Debug.Log(IsRunning);
        if (!IsRunning) return;
        //started = false;
        // Stop receiving any data
        MicrophoneInput.OnMicrophoneDataInput.RemoveListener(OnMicrophoneInputReceived);

        stopRecognition.TrySetResult(0);

        Recognizer.StopContinuousRecognitionAsync().ConfigureAwait(false);

        Recognizer.Dispose();

        IsRunning = false;
    }

    public void StopChecking()
    {
        newSpeechStarted = false;
    }
}


________________________________

**Comment by jhakulin** [comment]
Thanks for the code, when do you call StopRecording method ? Could you try to close external microphone stream after StopContinuousRecognitionAsync ?

**Comment by prabhukumardasari12** [comment]
When I click a button, I am calling stoprecording. But before itself it gets cancelled.

________________________________

**Comment by pankopon** [comment]
Closing this as duplicate, please see https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/679 for continuing investigation of Android mic/input issues.
