### ISSUE TITLE
Internet Explorer 11 Integration.

### ISSUE THREAD

**Issue by gabser10** [Azure-Samples/cognitive-services-speech-sdk#621]
Hi, i need to use Microsoft Cognitive Services in Internet Explorer 11. The js sdk is not loaded from this browser. Someone knows a solution? Thank You

**Comment by rhurey** [comment]
The JavaScript SDK doesn't support Internet Explorer 11. 

This is primarily due to IE 11 not support GetUserMedia which is how the SDK gets audio from the user's microphone.
