### ISSUE TITLE
Feature Request : Properties to define : Max Audio Recognition Time from Microphone OR Stop Recognition on silence 

### ISSUE THREAD

**Issue by viju2008** [Azure-Samples/cognitive-services-speech-sdk#625]
Hello,

I am doing speech recognition and am using Android SDK. I plan to move to containers in future. Stopping on silence is default as per documentation. How do i define the following the max audio time recognition time as below:

If the user is speaking and has spoken more than 15 seconds. The sdk should automatically stop the recognizer on Android end. If the user has spoken less than 15 seconds and was silent in between then it should be based on silence detection. The speech sdk should stop the microphone on android either on silence detection (when spoken < 15 seconds) or on completion of user saying 15 second audio.

In the container back-end how can i specify that the maximum audio length should be for 15 seconds . I could not find any such provision in the container documentation

Regards,

**Comment by pankopon** [comment]
Hi, there are no available controls for this. One option is that, instead of using the SDK microphone capture implementation, use your own microphone capture and create a push or pull audio input stream to feed the audio to the SDK library. This way you could then manage how much audio is allowed before closing the audio stream.

**Comment by viju2008** [comment]
What is the point in reworking the whole issue... the sdk is not open source that i can modify it... making own mircrophone means the whole websocket format and the chunk size , error handling all needs to be done again.

This is the reason for raising a feature request

**Comment by chrisbasoglu** [comment]
>>means the whole websocket format and the chunk size , 
>>error handling all needs to be done again.
No.  That is not the case.  The SDK has push stream/pull stream modes.  There are examples of these.  You can capture an audio buffer from the Microphone yourself and then use that buffer in  stream as defined by the SDK.  The SDK will take care of the websocket, chunksizing, error handling, etc...
