### ISSUE TITLE
Bug when using config.setProperty(ID, string) in Android (Java)

### ISSUE THREAD

**Issue by jose-alvessh** [Azure-Samples/cognitive-services-speech-sdk#626]
**Describe the bug**

So I was using this piece of code to set up the Initial Time Out and the EndSilenceTimeOut on the SpeechConfig to create a SpeechRecognizer instance with the 1.9.0 sdk and now I have tried to update to the 1.11.0 and 1.10.0 versions.
`config = SpeechConfig.fromSubscription(speechSubscriptionKey, serviceRegion);
  config.setSpeechRecognitionLanguage(recognitionLanguage);
  config.setProperty(SpeechServiceConnection_EndSilenceTimeoutMs, TIMEOUT);
  config.setProperty(SpeechServiceConnection_InitialSilenceTimeoutMs, INIT_TIMEOUT);
  speechRecognizer = new SpeechRecognizer(config,AudioConfig.fromDefaultMicrophoneInput());`

However, I get this following crash:
`java.lang.UnsatisfiedLinkError: No implementation found for int com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.PropertyId_Conversation_Speech_Activity_Template_get() (tried Java_com_microsoft_cognitiveservices_speech_internal_carbon_1javaJNI_PropertyId_1Conversation_1Speech_1Activity_1Template_1get and Java_com_microsoft_cognitiveservices_speech_internal_carbon_1javaJNI_PropertyId_1Conversation_1Speech_1Activity_1Template_1get__)
    at com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.PropertyId_Conversation_Speech_Activity_Template_get(Native Method)
    at com.microsoft.cognitiveservices.speech.internal.PropertyId.<clinit>(PropertyId.java:67)
    at com.microsoft.cognitiveservices.speech.PropertyId.<clinit>(PropertyId.java:19)
    at`

As I'm not setting up the property `PropertyId_Conversation_Speech_Activity_Template` this behaviour is really strange. I tried to use bot sdk 1.10.0 and 1.11.0 releases. I was using the sdk version 1.9.0 for a while and this error did not happen before.
 I have read the documentation of the new releases and this PropertyIDs  and the setProperty(PropertyID, String) methods still existing so I don't know why this is happening.

**To Reproduce**
1. Just run the piece of code that I wrote above ( I tried it several times with the same error). 
I have just sat up just one of the PropertyIds each time but the error still persisted.

**Version of the Cognitive Services Speech SDK**
1.11.0 and 1.10.0 (It did not happen on the older versions 1.9.0)

**Platform, Operating System, and Programming Language**
- OS Android

Can you help me solving this problem?
Thanks in advance,
Best regards.

**Comment by jhakulin** [comment]
@jose-alvessh Thanks for report, we will investigate.

**Comment by jhakulin** [comment]
@jose-alvessh I tried with Android 8.1 device and 1.11.0 Speech SDK release and everything works correctly. Do you see this problem consistently ? What is the version of Android OS and are you using device (ARM based) or emulator (x86) ?

**Comment by jose-alvessh** [comment]
Hi @jhakulin. I'm using a ARM based device (ARMv8) and the version of the Android is 8.1. 
It happens every time I start a new instance of the SpeechRecognizer. My app crashes and closes. I tried to comment both setProperty and the App did not have any crash. Using only of of the setProperty calls it does not work as well. 
If I downgrade the sdk to the 1.9.0 everything works fine.
Thanks for your help.

**Comment by jose-alvessh** [comment]
Hi @jhakulin  I have solved my problem. I don't know why but few months ago the .so files inside of the aar were not being imported to my App. So, I have manually introduced them into the jniLib files. I forgot to update them while updating the sdk thus this error was happening. 

My bad, sorry for bothering,
Thanks for your time,
