### ISSUE TITLE
Speech SDK for .NET Core does not run on macOS

### ISSUE THREAD

**Issue by robinmanuelthiel** [Azure-Samples/cognitive-services-speech-sdk#63]
As .NET Core is cross-platform, it is expected, that the SDK supports all these platforms as well.

### This issue is for a:
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Run the .[NET Core Tutorial](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp-dotnetcore) on macOS

### Any log messages given by the failure
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (The type initializer for 'Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE' threw an exception.) ---> System.TypeInitializationException: The type initializer for 'Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'Microsoft.CognitiveServices.Speech.csharp.bindings.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libMicrosoft.CognitiveServices.Speech.csharp.bindings.dll, 1): image not found
   at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_carbon_csharp(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE.SWIGExceptionHelper..ctor()
   at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE.SpeechConfig_FromSubscription(String jarg1, String jarg2)
   at Microsoft.CognitiveServices.Speech.Internal.SpeechConfig.FromSubscription(String subscription, String region)
   at Microsoft.CognitiveServices.Speech.SpeechConfig.FromSubscription(String subscriptionKey, String region)
   at doetnettest.Program.RecognizeSpeechAsync() in /Users/robinmanuelthiel/Desktop/doetnettest/Program.cs:line 13
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at doetnettest.Program.Main() in /Users/robinmanuelthiel/Desktop/doetnettest/Program.cs:line 50
```

### OS and Version?
> macOS Mojave

### Versions
> 1.0.0

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wolfma61** [comment]
this is a known issue (and we don't have it under the 'supported platforms')
we have this as a request already in our database. It is currently not scheduled for the next release(s). So I can't give you an ETA.

Wolfgang

ps - I close this (we have this on the wish list). For specific issues, please open a new issue

**Comment by robinmanuelthiel** [comment]
Wait what? You are offering a **.NET Core** (cross-platform by its nature) SDK that **only runs one Windows** without bothering about it or mentioning it in any docs??

**Comment by wolfma61** [comment]
the table at the documentation entry page lists Windows (64bit, 32bit) and linux x64 (a recent addition)
we will support macOS in the future, even we can't develop, build, test, document everything at once

sorry for the inconvenience and to dissapoint. we are trying to fill / extend the matrix ...

**Comment by robinmanuelthiel** [comment]
Ah okay, found it: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/

I'd like to suggest adding macOS as a new Row here to make clear, it is not supported at the moment.
First of all (as mentioned), when a developer reads ".NET Core", the probably assumes it runs on all .NET Core Platforms. Second (and more important), macOS runs on Linux, so if I read Linux, I would assume that this included macOS if it is not listed separately.

Thanks!

**Comment by lmoe** [comment]
MacOS does not run on Linux. It's *based* on Unix and it's Kernel XNU (X is not Unix) implies diverese ties, even though it's still an Unix variant.

However, I would also expect an unchecked Mac OS listing in the documentation and hope there is some movement in the near future. :)

**Comment by wolfma61** [comment]
we'll discuss it with the documentation folks ... unfortunately, at this time, the not supported platforms might outweigh the supported ones ;) ;) ;)

anyhow - let's see what proposal the documentation folks will have...

**Comment by asurjit79** [comment]
Although, it is closed but quite disappointing to see wrong documentation and poor sample code. 
On one end, we are building best in class Cognitive speech libraries and at the same time, we are unable to find out, the client machine is Mac and this sample code can not run. I am getting weird stack trace errors due to this. Wasted my 6 hrs since morning before I hit this thread...Come on guys, 8 months gone and still there is no change to this issue.

**Comment by mahilleb-msft** [comment]
@asurjit79 - maybe you already did? is it #270 ?

**Comment by asurjit79** [comment]
yes @mahilleb-msft. I reported it already under #270. 
I am using the latest SDK from the GitHub which is 1.5.1. Let me know if you need any more details for the same.

**Comment by teleginski** [comment]
macOS Mojave
Version 10.14.04

I created an Azure Function project.

`System.Private.CoreLib: Exception while executing function: ConversaoFalaEmTextoFunction. Microsoft.CognitiveServices.Speech.csharp: Unable to load shared library 'Microsoft.CognitiveServices.Speech.core.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libMicrosoft.CognitiveServices.Speech.core.dll, 1): image not found.`

With console project, works correctly..
