### ISSUE TITLE
Is Text-to-Speech Javascript method "fromDefaultSpeakerOutput()" in "AudioConfig" Class not implemented yet?

### ISSUE THREAD

**Issue by mason1002** [Azure-Samples/cognitive-services-speech-sdk#631]
Hi, 

I use Javascript SDK to implement TTS and I want to synthesize text directly to speaker output, but there's no voice at all. I have checked my device settings and they seems good. 

From the official DOC (https://docs.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/audioconfig?view=azure-node-latest#fromdefaultspeakeroutput--) I read that:
---
fromDefaultSpeakerOutput()
Creates an AudioConfig object representing the default speaker. Note: this is just a place holder, not implemented now.
---

Is the method not implemented yet? if so, when would it be implemented, thanks!

**Comment by rhurey** [comment]
Our next release will have browser support. The current release has TTS supported for NodeJS.

The code is in master if you would like a preview.
