### ISSUE TITLE
How to reduce SpeechRecognizer overhead for successive reco case  ? 

### ISSUE THREAD

**Issue by wukun2015** [Azure-Samples/cognitive-services-speech-sdk#633]
[speechRecognizerOverhead.py.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4613489/speechRecognizerOverhead.py.txt)
Hello,

In real time scenario, i have multiple .wav files (successively generated from audio pick up device like microphone) to be recognized. The number of files is not un-predictable because of un-predictable audio length. Therefore, i hope the overhead of reco switch among these wav files is as small as possible to fit real-time scenario like "seamless" reco experience. 

However, connecting local speech container, i found this overhead in speech sdk(1.11.0) of python (3.8.2) is about 1000ms in Window10 and 500ms in Mac, which is a little bit expensive to such real-time case. 

Per analysis, this overhead seems coming from de/construction of  SpeechRecognizer python object used to recognize different wav files by different audio_config value, i.e. file name. 

Is there any way to reduce this overhead ? E.g. any way to re-config the same existing SpeechRecognizer object's audio config para in run-time without re-de/construct the whole object ? 

Thank you. 

p.s. Attached is my sample code measuring this overhead. 
[speechRecognizerOverhead.py.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4613493/speechRecognizerOverhead.py.txt)

**Comment by viju2008** [comment]
I am also facing the same issue for a 6 second audio the overhead is 8 seconds which is very high

**Comment by mradmila** [comment]
First, I assume you are experiencing the same issue with cloud speech endpoint, and not only with on-prem containers, as the cost should be in creating speech SDK objects? If that's true, the only way I know how to optimize this and amortize the cost is to switch from file based API to stream based API with some silence/delimiter between them. I understand that's not the ideal solution, but I don't know of any better one in the current SDK.

Our speech SDK team is aware of the issue and is planning to add a way to "reuse" the AudioConfig. I don't have the delivery date for this work item, though.

**Comment by wukun2015** [comment]
> First, I assume you are experiencing the same issue with cloud speech endpoint, and not only with on-prem containers, as the cost should be in creating speech SDK objects? 

Yes, same issue with online endpoint.

**Comment by wolfma61** [comment]
if you want to reuse the connection and stream another audio file, you need to inform the server side that the audio is finished. Currently there is no way to say "I'm finished with streaming, I want the final result" without closing the connection/destroying the recognizer.

as a work around:
You stream several seconds of silence the to the service (~5 secs?) after one file is finishe. You are guaranteed that a final result (containing all audio from the audio file) is being generated, and you can start streaming a new file on the connection (same recognizer). This avoids reconnection, but requires a few more seconds of audio being send to the service.

**Comment by pankopon** [comment]
Closing the issue as workarounds have been provided. Reusable AudioConfig, among other changes, is in consideration for a future release, but we cannot give a definite timeline at the moment.
