### ISSUE TITLE
Phraselist Germany

### ISSUE THREAD

**Issue by SOliasS** [Azure-Samples/cognitive-services-speech-sdk#634]
Hey like in this ticket #415 i was wondering if there is any indication when Phraselists will be supported for the german language...
It's quite an important feature which is still missing.
@jhakulin @glharper

**Comment by pankopon** [comment]
Hi, unfortunately there is still no ETA. Currently it is expected that the team working on this can provide more a firm timeline after summer.

**Comment by SOliasS** [comment]
@pankopon This is really disappointing....
So it's basically impossible to look for names or titles in german atm...
So i have these possibilities:
1. Recognize when the user want something out of a list and switch to the english api and hope that it might be recognized...
2. Number everything and show tell the user which options he has and then listen for the number
3. Get every possible speech to text translation and then try to find the keyword and then try to find a match in the list...
4.Go .... and look for another api solution with better support for german language

**Comment by SOliasS** [comment]
@pankopon wouldn't it be possible to just add the english version of phraselist to the german api?
So we would have easy access to this option which wouldn't be optimal but better than nothing...
