### ISSUE TITLE
Issue while invoking the version2.1 batch transcription API from C# code

### ISSUE THREAD

**Issue by harmandeepsinghkalsi** [Azure-Samples/cognitive-services-speech-sdk#636]
Hi

In my code for batch transcription , when I use version2.0 batch transcription API  , the processing happens smoothly but as soon as I switch to version 2.1 , it start throwing error , that recordingUrl is not valid . This is happening when i do a post call in C# code. If I do the same thing from postman, all goes well. So I am not able to figure out what am I doing wrong here?

**Comment by jhakulin** [comment]
@wolfma61 @PanosPeriorellis Could you comment on this ?

**Comment by bexxx** [comment]
v2.1 is not a public version and is not documented. It unfortunately has breaking changes (in your case, the property must be called RecordingsUrls and is a string[] of urls). This was one of the reasons why it was never published.

I would recommend to continue using v2.0 until it gets replaced with the next version (v3.0)

**Comment by vasudev-hv** [comment]
@bexxx - Any idea when will 2.1 or 3.0 be available to public?

**Comment by harmandeepsinghkalsi** [comment]
@bexxx - Also, is there any way we can use the functionality of batch transcription in  version 2.0?

**Comment by wolfma61** [comment]
3.0 should be available in the next week or so (really really soon).
You will have to wait for the 3.0 to be released to have access to the new API

**Comment by pankopon** [comment]
@wolfma61 Is 3.0 now released, or still coming? https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription only shows v2.0 API calls.

**Comment by bexxx** [comment]
The v3.0 version has been released. You can find the swagger documentation here: https://eastus2.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/operations/CopyModelToSubscription

We're going to update the how to sections very soon to reflect the new API.

**Comment by pankopon** [comment]
@bexxx Thanks for the info. Please post an update when all sections have been revised and we can close this issue.

**Comment by oscholz** [comment]
@harmandeepsinghkalsi I am going to close this issue now. If you continue to have an issue with v3 of the batch transcription API, please reactivate the issue.

**Comment by harmandeepsinghkalsi** [comment]
Sure @oscholz , will reactivate if I get some issues. Thank you everyone for the help and guidance!
