### ISSUE TITLE
Is it possible to use container with SDK?

### ISSUE THREAD

**Issue by tonyalves** [Azure-Samples/cognitive-services-speech-sdk#637]
I checked that C# SDK has `fromHost` to access the SpeechService running on container. Is there something equaly to use in Java? If no, is there something planned to add this function on Java SDK?

**Comment by jhakulin** [comment]
@tonyalves Thanks for question, Java has the same APIs, check here: https://docs.microsoft.com/en-us/java/api/com.microsoft.cognitiveservices.speech.speechconfig?view=azure-java-stable

**Comment by tonyalves** [comment]
> @tonyalves Thanks for question, Java has the same APIs, check here: https://docs.microsoft.com/en-us/java/api/com.microsoft.cognitiveservices.speech.speechconfig?view=azure-java-stable

Thanks. For some reason it was not showing in auto complete.
