### ISSUE TITLE
MacOS Unity Support for Speech SDK

### ISSUE THREAD

**Issue by adbalano** [Azure-Samples/cognitive-services-speech-sdk#638]
**Is your feature request related to a problem? Please describe.**
MacOS Unity support for Speech. Our app is integrating the Speech SDK and would like feature parity across all platforms which include PC, Android and Mac.

**Describe the solution you'd like**
Speech SDK supports Unity based applications on MacOS

**Describe alternatives you've considered**
N/A

**Additional context**
We are an internal product. Please contact for additional details.

**Comment by jhakulin** [comment]
@adbalano Thanks for the report, we will discuss about this feature request and let you know the plan.

**Comment by adbalano** [comment]
@jhakulin Great! Please let me or @in2dair know if have any questions. Thank you!

**Comment by pankopon** [comment]
We've now added a work item for this feature to our backlog and will address it in a future SDK release (no definite timeline yet). Once the work is done, we will update this issue to let you know when the support will be available.
