### ISSUE TITLE
Error SPXERR_MIC_NOT_AVAILABLE when deployed to Windows 2016 VM 

### ISSUE THREAD

**Issue by lukezak** [Azure-Samples/cognitive-services-speech-sdk#64]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Deploy sample code in .net core web application to Azure Windows Server 2016 VM
> Access through web browser and initiate speech to text

### Any log messages given by the failure
> AggregateException: One or more errors occurred. (Exception with an error code: 0xe (SPXERR_MIC_NOT_AVAILABLE)

### Expected/desired behavior
> 

### OS and Version?
> Windows Server 2016 VM

### Versions
>

### Mention any other details that might be useful
Same codes work on development machine (Windows 10, VS 2017 IDE) but when deployed I encounter the above mentioned error.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by zhouwangzw** [comment]
The error shows microphone is not available. If you do not have access to mic on Windows Server 2016 VM, you can use file or stream as audio input source.

**Comment by lukezak** [comment]
Thanks Zhou. I'm assuming it doesn't work in the way of a web application in which it is available on the server and a client can connect through a web browser with a microphone connected to their device and initiate speech to text? It is local only? Any plans to do this?

**Comment by wolfma61** [comment]
closing ...
