### ISSUE TITLE
How to auto detect langauge using speechsdk

### ISSUE THREAD

**Issue by yatinn-j** [Azure-Samples/cognitive-services-speech-sdk#641]

**Comment by rhurey** [comment]
Our Language Detection feature hasn't made it into the JavaScript / TypeScript based library yet. It's in our backlog to do so, but I don't have a firm date I can share for when it'll be done.

**Comment by yatinn-j** [comment]
> Our Language Detection feature hasn't made it into the JavaScript / TypeScript based library yet. It's in our backlog to do so, but I don't have a firm date I can share for when it'll be done.

Is there any support with C# or Python? The main motive is auto detection of spoken language by speaker.

**Comment by rhurey** [comment]
The C# HowTo is here:
https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-automatic-language-detection?pivots=programming-language-csharp

From there you can also select to see the samples in Python.

**Comment by yatinn-j** [comment]
> The C# HowTo is here:
> https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-automatic-language-detection?pivots=programming-language-csharp
> 
> From there you can also select to see the samples in Python.
Alright! Thanks.

**Comment by yatinn-j** [comment]
> The C# HowTo is here:
> https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-automatic-language-detection?pivots=programming-language-csharp
> 
> From there you can also select to see the samples in Python.

**AutoDetectSourceLanguageConfig** not working as expected. I have added two source languages i.e. **hi-IN and en-US** but it is always recognizing **en-US**. But when I set **hi-IN** only, it works fine. Kindly help what I need to do more?

**Comment by yashugupta786** [comment]
I am also getting the same problem .When passing multiple languages parameter it is not working correct for spanish and indian languages

**Comment by paulchua-pc3** [comment]
I am having the same problem with auto detection using en-US and ja-JP. I found out that you need to pause for a while about 10 secs, before speaking in another language for it to detect properly. Is there anyway I could perform language auto detection per every line of speech without any pause?

**Comment by jhakulin** [comment]
@paulchua-pc3 Thanks for the question, reopening the case.

**Comment by shiwenmichael** [comment]
The latest Speech SDK @ 1.17.0 (announced today) has support for this. We will be talking about the new features in the SDK at our upcoming //Build conference. Also updated developer documentation will be available mid next week

**Comment by shiwenmichael** [comment]
This is the example of how to do continuous language detection and speech recognition with multiple languages in Carbon 1.17.0:

[sample code](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/054b4783de9d52f28109c435bf90e073513fec97/samples/csharp/sharedcontent/console/speech_recognition_with_language_id_samples.cs#L78)

**Comment by paulchua-pc3** [comment]
> This is the example of how to do continuous language detection and speech recognition with multiple languages in Carbon 1.17.0:
> 
> [sample code](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/054b4783de9d52f28109c435bf90e073513fec97/samples/csharp/sharedcontent/console/speech_recognition_with_language_id_samples.cs#L78)

Thanks for the assistance, I was able to get it working using the V2 endpoint.
