### ISSUE TITLE
File names are too long, causing file path length errors and failures to install.

### ISSUE THREAD

**Issue by Kobyspeech** [Azure-Samples/cognitive-services-speech-sdk#644]
**Description:** File paths cap out at 260 characters making certain things impossible to download with long file names (for Instance: C:\Users\<Username>\Desktop\1.11\cognitive-services-speech-sdk-master\quickstart\cpp\windows\translate-speech-to-text\packages\Microsoft.CognitiveServices.Speech.1.11.0

In this instance the NuGet packages fail to install because the path becomes too long.
 
**Impact:** Unable to install things like NuGet packages and files after a certain point.
NOTE: Abbreviating or shortening some of the longer file names would be beneficial for the length: i.e  Microsoft.CognitiveServices.Speech.1.11.0 and cognitive-services-speech-sdk-master
 
I have encountered this issue multiple times and the only workaround I've found is to move the files out of the desktop folder to the C:/ drive manually. This can be a bad user experience.
 
**SDK Version:** 1.11
 
**Repro Steps:**
1. Download SDK 1.11 (https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart)
2. Extract the zip on the desktop in a folder. 
3. Open and enter the subscription and region for Translate speech to text 
 
**Actual result:** The build will fail to install NuGet packages due to the length of the file path.

**Expected behavior:** File pathing being short enough to complete these downloads from an easy location, like the desktop.

**Platform, Operating System, and Programming Language**
 - OS: Windows
 - Hardware: x64 ing 
 - Language: C++ Visual studio 2019
 - Browser Chrome

**Comment by pankopon** [comment]
Hi, there is a way to enable longer paths on Windows 10:
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#enable-long-paths-in-windows-10-version-1607-and-later

Could you use this setting? (Nowadays the Python installer for Windows, for example, provides an option at the end of setup to disable the path length limit as well.)

**Comment by pankopon** [comment]
Closed as answered, please reopen if you need further support.
