### ISSUE TITLE
Any plans to suport debian buster (10)

### ISSUE THREAD

**Issue by maczikasz** [Azure-Samples/cognitive-services-speech-sdk#645]
**Is your feature request related to a problem? Please describe.**
We use the debian buster image for our java apps, but cannot because of azure sdk

**Describe the solution you'd like**
Dupport for debian buster

**Describe alternatives you've considered**
Debian 9, but its not as up to date

**Comment by pankopon** [comment]
Hi, the official support is not planned yet. But based on some quick testing with  debian:stable from https://hub.docker.com/_/debian and our console sample app from https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/java/jre/console, there should be no immediate problems with using the Speech SDK on Debian 10 either. Have you encountered any issues?

For Java, the same prerequisites apply as on Debian 9 except you can use newer versions of libssl and openjdk. So at least the following packages are required on Debian 10:
- libasound2
- libssl1.1
- openjdk-11-jdk (or -jre if you need only the runtime)

If you want to use compressed audio for input, install also the following GStreamer packages:
- libgstreamer1.0-0
- gstreamer1.0-plugins-base
- gstreamer1.0-plugins-good
- gstreamer1.0-plugins-bad
- gstreamer1.0-plugins-ugly

**Comment by maczikasz** [comment]
Thanks, i got a native exception from the jni carbon wrapper. But maybe i am just missing some libs, i assumed that it was because of buster, but i might be wrong. Nevertheless if it works it is still good to know that there is no official support planned, so we can make an informed decision about putting it live even if it works

**Comment by pankopon** [comment]
As of now there is no schedule for official support, but most likely it will be considered at some point in the future. Currently Speech SDK releases are not tested on Debian 10, but if you can provide details of specific issues you are seeing, we can have a look at them as well.

**Comment by pankopon** [comment]
Closed as answered, please reopen if you need further support.

**Comment by maczikasz** [comment]
I tried and it worked, now its more of a question of going to production on an unsupported platform

**Comment by pankopon** [comment]
This is a late comment, but I've added a backlog work item for Debian 10 support (mainly verification and documentation) and we'll check if it can be prioritized for implementation in the coming months. This issue will be updated when the work is done and release information is available.
