### ISSUE TITLE
Offline wake-word (keyword) recognition not working

### ISSUE THREAD

**Issue by genghis-kane** [Azure-Samples/cognitive-services-speech-sdk#647]
I have been trying to figure out if wake-word (keyword) recognition is meant to be supported offline, found a comment thread [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/506) that seems to indicate yes - can you advise if this is the case?

I've tried it out locally with a C# Console app and gotten partway there - this is what I have done so far, based off the [VoiceAssistantClient](https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/tree/master/clients/csharp-wpf). It works exactly as expected online but not offline:

- Trained and downloaded a wake word model using Speech Studio
- Set up `WakeWordConfiguration` using the local path to that downloaded model
- Registered `Connector_Recognizing`, `Connector_Recognized`, `Connector_Canceled`, etc events to log simple info messages to the console when they are hit.
- Set up my `DialogServiceConnector` as follows: `_connector.StartKeywordRecognitionAsync(_activeWakeWordConfig.WakeWordModel);`

When I am offline, I only ever get to the `Connector_Recognizing` event when I speak the wake-word. It logs its message to the console, but then after that, immediately fails with the following error, which is logged in the `Connector_Canceled` event:
`Error (ConnectionFailure) : Connection failed (no connection to the remote host). Internal error: 1. Error details: 11001. Please check network connection, firewall setting, and the region name used to create speech factory.`

So technically, I am able to detect that the keyword has been spoken, set a variable inside the `Connector_Recognizing` event, and handle it within `Connector_Canceled`, but this doesn't seem like the most robust approach. 

Any guidance here would be very much appreciated, happy to supply exact source code if it would help. I'm running on Windows 10 and version 1.12.0 of the Microsoft.CognitiveServices.Speech SDK.

**Comment by jhakulin** [comment]
@genghis-kane Thanks for feedback, in 1.12.0 release you can also use standalone KeywordRecognizer object, see sample here: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/uwp/keyword-recognizer

That is not tied to any online recognizers and could be better solution for you.

**Comment by genghis-kane** [comment]
@jhakulin thank you very much! This is exactly what I am looking for, I tried the sample out and it works perfectly. I appreciate your time :)
