### ISSUE TITLE
punctuation and capitalisation in nbest (words) results

### ISSUE THREAD

**Issue by adamteale** [Azure-Samples/cognitive-services-speech-sdk#649]
Hi there!

Any recommendations on how to receive the NBest results (list of words) with correct capitalisation and punctuation ?

I essentially want the "display" str value but as a list of capitalised and punctuated words with time offset&duration values.

This is the config I am using (python):
    speech_config.enable_dictation()
    speech_config.set_service_property(
        "wordLevelConfidence", "true", speechsdk.ServicePropertyChannel.UriQueryParameter)
    speech_config.set_service_property(
        "format", "detailed", speechsdk.ServicePropertyChannel.UriQueryParameter)

Cheers!

Adam

**Comment by pankopon** [comment]
Hi, you can get word level offset and duration values with

```
speech_config.request_word_level_timestamps()
```

With "a list of capitalised and punctuated words", do you mean that in an example like below, the result should have `"Word": "What's"` for the first word and `"Word": "like?"` for the last? I'm not sure if it's directly possible, but let me double-check.

```
    "NBest": [
        {
            "Confidence": 0.97701865,
            "Display": "What's the weather like?",
            "ITN": "what's the weather like",
            "Lexical": "what's the weather like",
            "MaskedITN": "what's the weather like",
            "Words": [
                {
                    "Confidence": 0.9752328,
                    "Duration": 3900000,
                    "Offset": 500000,
                    "Word": "what's"
                },
                {
                    "Confidence": 0.9912971,
                    "Duration": 1300000,
                    "Offset": 4500000,
                    "Word": "the"
                },
                {
                    "Confidence": 0.9947196,
                    "Duration": 2900000,
                    "Offset": 5900000,
                    "Word": "weather"
                },
                {
                    "Confidence": 0.9936005,
                    "Duration": 4800000,
                    "Offset": 8900000,
                    "Word": "like"
                }
            ]
        },
```

**Comment by pankopon** [comment]
Sorry for the delay - so the NBest Words list contains tokens based on lexical analysis of input (cf. the Lexical result attribute which contains the whole phrase) and the format is not configurable. Timestamps are assigned to these lexical tokens.

If you need it for visualization of results, for instance, you could e.g. split the Display result string into a list of words with https://docs.python.org/3/library/stdtypes.html#str.split and then do mapping between them and lexical tokens that have time information, though this of course requires some extra code.

**Comment by pankopon** [comment]
Closing the issue as answered, please re-open if more information is needed.

**Comment by zhouwangzw** [comment]
The "Words" contain actually the words in lexical format which does not have any punctuation and capitalization. The "Display" field  contains text with punctuation and capitalization but no at the world level. We are working on feature to provide word level information for display format, which will be probably be available in the next months. But we do not have detailed ETA yet. Stay tuned.

**Comment by ominfowave** [comment]
> Sorry for the delay - so the NBest Words list contains tokens based on lexical analysis of input (cf. the Lexical result attribute which contains the whole phrase) and the format is not configurable. Timestamps are assigned to these lexical tokens.
> 
> If you need it for visualization of results, for instance, you could e.g. split the Display result string into a list of words with https://docs.python.org/3/library/stdtypes.html#str.split and then do mapping between them and lexical tokens that have time information, though this of course requires some extra code.

Hi @pankopon , I'm having the same query. but the mapping solution which you have mentioned might not match some words, because in Display text, numbers are provided in the numeric format while in Words list those numbers are in words(Lexical). 

For example, if the Display text is "Amount is $18 billion", then the words will be like this {"Amount", "is", "eighteen", "billion", "dollar"}

Is there any other solution to get punctuation in the word list?
