### ISSUE TITLE
Crashed when doing continuous speech recognition from a file

### ISSUE THREAD

**Issue by Sleepingbug** [Azure-Samples/cognitive-services-speech-sdk#65]
It's OK to do speech-to-text from microphone.
But it's crashed when to do speech recognition from a file.

I copied the codes and download a wav file from 
https://docs.microsoft.com/en-US/azure/cognitive-services/speech-service/how-to-recognize-speech-java.
and my subscriptionKey and serviceRegion are correct.

the errors are as blow:

java.lang.RuntimeException: Exception with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED)
    [CALL STACK]
    
      # 0: 0x7bf49b72f8  _ZN9Microsoft17CognitiveServices6Speech4Impl17CSpxWavFileReader4OpenEPKw
      # 1: 0x7bf49b9924  _ZN9Microsoft17CognitiveServices6Speech4Impl15CSpxWavFilePump10EnsureFileEPKw
      # 2: 0x7bf49ba02c  _ZThn64_N9Microsoft17CognitiveServices6Speech4Impl15CSpxWavFilePump4OpenEPKw
      # 3: 0x7bf499e8c4  _ZN9Microsoft17CognitiveServices6Speech4Impl22CSpxAudioStreamSession12InitFromFileEPKw
      # 4: 0x7bf4975b7c  _ZN9Microsoft17CognitiveServices6Speech4Impl20CSpxSpeechApiFactory31InitSessionFromAudioInputConfigENSt6__ndk110shared_ptrINS2_11ISpxSessionEEENS5_INS2_15ISpxAudioConfigEEE
      # 5: 0x7bf4974450  _ZN9Microsoft17CognitiveServices6Speech4Impl20CSpxSpeechApiFactory34CreateRecognizerFromConfigInternalEPKcS5_S5_NS1_12OutputFormatENSt6__ndk110shared_ptrINS2_15ISpxAudioConfigEEE
      # 6: 0x7bf4974b80  _ZThn48_N9Microsoft17CognitiveServices6Speech4Impl20CSpxSpeechApiFactory32CreateSpeechRecognizerFromConfigEPKcNS1_12OutputFormatENSt6__ndk110shared_ptrINS2_15ISpxAudioConfigEEE
      # 7: 0x7bf4955fd0  recognizer_create_speech_recognizer_from_config
      # 8: 0x7bf4d5be4c  _ZN9Microsoft17CognitiveServices6Speech16SpeechRecognizer10FromConfigENSt6__ndk110shared_ptrINS1_12SpeechConfigEEENS4_INS1_5Audio11AudioConfigEEE
      # 9: 0x7bf4d4082c  Java_com_microsoft_cognitiveservices_speech_internal_carbon_1javaJNI_SpeechRecognizer_1FromConfig_1_1SWIG_10
      #10: 0x7c1211c794  ???
      #11: 0x7c1211346c  ???
      #12: 0x7c1211feb4  _ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc
      #13: 0x7c122cdbf4  _ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE
      #14: 0x7c122c7cb0  _ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE
      #15: 0x7c12596ae0  MterpInvokeStaticRange
      #16: 0x7c12106018  ExecuteMterpImpl
      #17: 0x7c12106018  ExecuteMterpImpl
      #18: 0x7c12106018  ExecuteMterpImpl
      #19: 0x7c12106018  ExecuteMterpImpl
      #20: 0x7c12106018  ExecuteMterpImpl
      #21: 0x7c12106018  ExecuteMterpImpl
      #22: 0x7c12106018  ExecuteMterpImpl
      #23: 0x7c12106018  ExecuteMterpImpl
      #24: 0x7c12106018  ExecuteMterpImpl
      #25: 0x7c12106018  ExecuteMterpImpl
      #26: 0x7c12106018  ExecuteMterpImpl
      #27: 0x7c12106018  ExecuteMterpImpl
    
    
        at com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.SpeechRecognizer_FromConfig__SWIG_0(Native Method)
        at com.microsoft.cognitiveservices.speech.internal.SpeechRecognizer.FromConfig(SpeechRecognizer.java:41)
        at com.microsoft.cognitiveservices.speech.SpeechRecognizer.<init>(SpeechRecognizer.java:88)
        at com.microsoft.cognitiveservices.speech.samples.sdkdemo.MainActivity.testFile(MainActivity.java:437)
        at com.microsoft.cognitiveservices.speech.samples.sdkdemo.MainActivity$1.onClick(MainActivity.java:230)
        at android.view.View.performClick(View.java:5646)
        at android.view.View$PerformClick.run(View.java:22473)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

Phone info:
HUAWEI Honor 8, Android 7.0

**Comment by fmegen** [comment]
hi,

the error indicates that the file was not at the location passed to the audio config object.

can you please verify that the file actually exists on disk at the location you specified.

note: adding the file to the "Assets" folder of your Android project does not store it on disk.
rather, it is stored as an asset within the generated apk of your application. In this case, you need to use the Stream api, passing it the stream you get from opening the resource in your application.

kind regards,
 friedel

**Comment by Sleepingbug** [comment]
I have solved this problem. just open storage permissions.
Thanks
