### ISSUE TITLE
When the KWS is enabled the STT stops working

### ISSUE THREAD

**Issue by raafaelima** [Azure-Samples/cognitive-services-speech-sdk#653]
Hi Everyone,

#### What happens?

When I say the keyword, The app wake, show the animation, as expected. However do not show any signs of recognising my voice from the wake moment, even when I click on the microfone icon.

Also, when I try to use the ```botConnector.startKeywordRecognitionAsync(model)``` instead, on the recognized section, they return to me the Keyword name plus my actual command. Instead of getting **Do This**, im getting **Computer, Do This.**

#### What language is this in?
Language: 
> Java/Android

SDK: 
> com.microsoft.cognitiveservices.speech:client-sdk:1.12.0

#### Can you share any logs, error output, etc.?

Here is the code Sample:

```
KeywordRecognizer keywordRecognizer = new KeywordRecognizer(AudioConfig.fromDefaultMicrophoneInput());
final KeywordRecognitionModel model = KeywordRecognitionModel.fromStream(inputStream, keyword, false);
final Future<KeywordRecognitionResult> task = keywordRecognizer.recognizeOnceAsync(model);

keywordRecognizer.recognized.addEventListener((o, speechRecognitionResultEventArgs) -> {
      final KeywordRecognitionResult result = speechRecognitionResultEventArgs.getResult();
      if (result.getReason() == ResultReason.RecognizedKeyword) {
        EventBus.getDefault().post(new BotListening());
        botConnector.listenOnceAsync(); 
     } else {
        LogException("Error: got the wrong sort of recognition.");
    }
});

botConnector.recognized.addEventListener((o, speechRecognitionResultEventArgs) -> {
   final String recognizedSpeech = speechRecognitionResultEventArgs.getResult().getText();
   LogInfo("Final result received: " + recognizedSpeech); //NEVER GET HERE
});
```

**Comment by glecaros** [comment]
Hi @raafaelima,

The behavior of sending the keyword to the service is expected. If you don't want it there, one thing that you could do the following:
- Build the `KeywordRecognizer` from microphone input (as you are doing)
- Build the `DialogServiceConnector` from an `AudioConfig` that uses a `PushAudioInputStream` as input.
- One you get a keyword recognition result, get an `AudioDataStream` from it (`AudioDataStream.fromResult`)
- Pump the data from the result data stream into the push stream.
- Call `listenOnceAsync`

If you do this, skipping the keyword is as simple as discarding the first few reads from the audio data stream (based on the reported keyword duration).

We did put together a quick sample of how to do it (using a SpeechRecognizer and without the skipping) and you look at it in this branch ([link](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/glecaros/keyword_stream/quickstart/java/android/keyword-recognizer-stream/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/quickstart/MainActivity.java#L102)).

Please let us know if that works for you.

**Comment by raafaelima** [comment]
Hi @glecaros,

Fist of all thanks a lot fo answering my question and provide a sample, however I maybe be asking the wrong question there and forgive me for that. 

I Try the implementation that I shown above, with the _KeywordRecognizer_, to see if the problem goes away, but is not the case, as we need to do the steps that you mention in order to work.

I am using that [VAClient](https://microsoft.github.io/botframework-solutions/clients-and-channels/clients/virtual-assistant-client/) of Microsoft as base implementation, on there I have a method to recognise the keyword, and some callbacks, as showed on the code bellow. The problems remains the same Instead of getting **Do This**, im getting **Computer, Do This.**

The question is, should I do the same approach in this case?
If so, I didn't understand well the skip, could you explain again how the skip works or provide a sample with it?


```
....

final KeywordRecognitionModel value = KeywordRecognitionModel.fromStream(inputStream, keyword, false);
final Future<Void> task = intentRecognizer.startKeywordRecognitionAsync(value);

....

intentRecognizer.recognized.addEventListener((o, speechRecognitionResultEventArgs) -> {
   final IntentRecognitionResult result = speechRecognitionResultEventArgs.getResult();
   final ResultReason reason = result.getReason();
   final String recognizedSpeech = result.getText();
   if (!reason.equals(ResultReason.RecognizedKeyword)) {
       LogDebug("Final result received: " + recognizedSpeech + ", intent: " + intentId); 
    }
});
```

**Comment by glecaros** [comment]
Hey @raafaelima,

Here is a quick sample of what I meant by skipping the first few bytes:

```java
final long duration = result.getDuration().longValue();
final long precedingAudioOffsetInTicks = 5000000; // Around 500ms
/* We are muliplying for 16/10000 because sample rate is 16[kHz] and we want ticks (100ns) */
long durationInBytes = (long)(((duration + precedingAudioOffsetInTicks) * 16) / 10000);
byte[] buffer = new byte[8000];
long remainingToSkip = durationInBytes;
while (remainingToSkip > 0)
{
  long read = 0;
  if (remainingToSkip >= 8000)
  {
    read = stream.readData(buffer);
  }
  else
  {
    byte[] smallBuffer = new byte[remainingToSkip];
    read = stream.readData(smallBuffer);
  }
  remainingToSkip -= read;
} 
```

Another thing that you may want to consider is to just remove the keyword manually (both from the client and the bot)

Let me know if this helps.

**Comment by raafaelima** [comment]
Hi @glecaros, this snippet help I lot to understand the concept.
I ended up doing some hybrid approach with the code you send and the manually removing.
Thank you for your help with this.

**Comment by glecaros** [comment]
Cool, glad you could solve your problem.
