### ISSUE TITLE
AudioInputStream stream converter support in cognitive services stream api

### ISSUE THREAD

**Issue by kmoore-riphaina** [Azure-Samples/cognitive-services-speech-sdk#654]
AudioInputStream requires implementing a pullaudioinputstreamcallback, the code sample code comments isn't clear on if the expected input is the container or the contents of a file. the subsequent header method also makes it more uncertain. futhermore there really should be a stream handler as users of the api may have the data from various sources and it really shouldn't matter what the source is since streams all operate the same way. so in short please impliment a audiostreaminput createfromstream(stream input) method

**Comment by rhurey** [comment]
Sorry this is confusing.

The answer is it depends on the audio format.
If the audio is raw PCM, the contents should be only the audio frames, and not the WAV header from a file.
If the audio is a compressed stream, the entire contents of the file are sent.

We've heard the feedback that a language correct (C#, Java, etc) version of streams when available is something that would make the experience easier and have items in our backlog to address this.

**Comment by kmoore-riphaina** [comment]
it takes 30 lines in google's voice recognition service to process an audio stream, the way the cognitive services api is implemented it takes multiple classes helper classes including writing a buffer reader callback, the documentation is clearly written on googles documentation page, the documentation in cognitive services is severely lacking, there is nothing ms documentation that even mention's the possibility of processing a stream. i'll be switching to another service provider until those issues can be addressed.

**Comment by rhurey** [comment]
The streams have multiple options for input.
One is to write a callback if you have an audio source that is pull based.
If you have a set of audio available, you can use a push stream to send all the audio into the SDK at once, or do so as it becomes available.

You can find samples of compressed audio with a pull stream here: https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/6d14d5ead40c77290606fa5014e790ae0d8405ba/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L245

The PushStream sample for compressed audio is here:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/6d14d5ead40c77290606fa5014e790ae0d8405ba/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L322

**Comment by kmoore-riphaina** [comment]
code samples shouldn't be the source of truth for how an api works

**Comment by rhurey** [comment]
I agree samples aren't the best method to explain concepts in, I'd shared them to get the information we did have available to you.

Improving the documentation is an ongoing effort, and something we're working on making better. Your feedback does help set priorities, so thank you for it.

**Comment by Charming-Cactus** [comment]
Hi, thank you for your code. I created a speech to text app (something like your "ContinuousRecognitionWithFileAsync") and it works fine with wave files. In the view of storage space I want to use mp3's instead of wav. While I was searching for a solution I found your code. Can you please explain what the class "BinaryAudioStreamReader" does? How can I use it? Do I need to import anything to use it too? Thank you for your support
