### ISSUE TITLE
Intermittent failed problem

### ISSUE THREAD

**Issue by Jinnanms** [Azure-Samples/cognitive-services-speech-sdk#656]
To access East Asia endpoint from china mainland mobile phone.  The phenomenon is not recognizable. I analyzed the log, the websocket connection was successful, and the SDK also received voice data. Based on the upload speed of the mobile terminal at this time, I found that it didn't seem to be sent. I don't know why it was not sent.
[logfile (15).txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4648194/logfile.15.txt)

**Comment by rhurey** [comment]
Looking at the log, the SDK attempted to send ~1440 100ms frames of audio. At the point recognition was canceled ~1110 of the frames were still in the device's send buffer.

The first audio made it into the push stream ~6 seconds into the log and was sent to the Speech Service ~110ms later.

Enough audio got off the device the service responded in ~70ms that it had received the first audio frame. Then there's no further service response, which may be expected depending on what was in the ~3 seconds of audio that got off the device.

It's not clear why bottled up transmission, at the level it was queued it usually points to something choking the network.

**Comment by Jinnanms** [comment]
thanks for quick response. this is my customer's issue. can we say the main cause of this problem is on network choking?

**Comment by rhurey** [comment]
Its the best diagnosis I have based on the available information.

**Comment by jhakulin** [comment]
Closing the issue with the given analysis, let us know if there is more information needed
