### ISSUE TITLE
Facing issues in Java SDK  for some languages (Japanese, Chinese) in docker

### ISSUE THREAD

**Issue by AravindaM** [Azure-Samples/cognitive-services-speech-sdk#657]
HI,

I am trying to use java SDK v1.11.0. Facing issues related to languages like Japanese, Chinese. This works fine locally on OSX 10.15.4

SSML request

```
<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="ja-JP">
    <voice name="Microsoft Server Speech Text to Speech Voice (ja-JP, Ayumi, Apollo)">
    <prosody rate="1.00">外務省の危険情報を中心に、世界各国・地域の治安情報、災害情報、感染症情報をお伝えしています</prosody>
    </voice>
</speak>
```

What i get is 46bytes file without any valid audio.

Here is the log.
[tts.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4650020/tts.log)

Deployment env.
-  docker image - centos:8
-  alsa-lib-1.1.9-4.el8.x86_64                                                                                                   
-  openssl-1:1.1.1c-2.el8_1.1.x86_64                                             
-  adoptopenjdk-11-hotspot-jre-11.0.7+10-1.x86_64 

Is this related to deployment env / java version or i am i missing something here.

**Comment by rhurey** [comment]
Thanks for the log, it was helpful.

This looks like an encoding problem with the string as it gets into the SDK. I tried 1.11.0 and the log with the text to be spoken came back:

> (510): 52ms SPX_DBG_TRACE_VERBOSE:  usp_tts_engine_adapter.cpp:260 ssml <speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="ja-JP"><voice name="Microsoft Server Speech Text to Speech Voice (ja-JP, Ayumi, Apollo)"><prosody rate="1.00">外務省の危険情報を中心に、世界各国・地域の治安情報、災害情報、感染症情報をお伝えしています</prosody></voice></speak>

Where with the log you have it's:

> (858): 3659ms SPX_DBG_TRACE_VERBOSE:  usp_tts_engine_adapter.cpp:260 ssml <speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="ja-JP"><voice name="Microsoft Server Speech Text to Speech Voice (ja-JP, Ayumi, Apollo)"><prosody rate="1.00">?????????????????????????????????????????????</prosody></voice></speak>

I used the string as a constant in the app and compiled with "-encoding utf8"

**Comment by AravindaM** [comment]
Thanks @rhurey. Default file encoding in centos8 is set to `ANSI_X3.4-1968` . 

Just adding following env variable in Dockerfile fixed the issue.
`ENV JAVA_TOOL_OPTIONS -Dfile.encoding=UTF8`

Feel free to close this.

**Comment by rhurey** [comment]
Great, glad its working.
