### ISSUE TITLE
Azure transcription merge different channel files

### ISSUE THREAD

**Issue by harmandeepsinghkalsi** [Azure-Samples/cognitive-services-speech-sdk#658]
Hi All

I have a question is there a way we can merge the channel0.json and channel1.json files to create a single transcription file?

Please let me know if possible , how we can achieve this ? I was checking the both the files but I did not get any clue as to how we can establish the relation between them and merge.

Thanks in advance!

**Comment by zhouwangzw** [comment]
If you want to merge transcription text from 2 separate channels, you can use the SegmentResults which list each transcribed utterance along with offset and duration. Based on offset/duration you can merge texts from both channel0.json and channel1.json.

**Comment by harmandeepsinghkalsi** [comment]
Thank you @zhouwangzw  for the reply. One clarfication , do I have to use both of them or one can serve the purpose?

**Comment by zhouwangzw** [comment]
For stereo audio, channel0.json and channel1 are the transcription text for 2 channels. Whether you need use one or both files is depending on your use case.

**Comment by harmandeepsinghkalsi** [comment]
Yes I understand stereo audio. Actually I was confirming about Offset and Duration, whether I have to use both of them or any one would serve the purpose for merging the audios?

**Comment by zhouwangzw** [comment]
The offset and duration refer to the position of each individual channel, but both channels in a stereo audio should start with the same "zero" position, so they are synchronized in most cases. For merging transcription texts, you probably need to look into both results in order not to miss any text. If both channel speak at the same time, the offset/duration from different channels might be overlapped.

**Comment by harmandeepsinghkalsi** [comment]
Thank you very much @zhouwangzw  for the clarifications!
