### ISSUE TITLE
Speech to text cuts off after short silence

### ISSUE THREAD

**Issue by michelpelletier07** [Azure-Samples/cognitive-services-speech-sdk#659]
I am using Microsoft Azure Speech to Text transcription in batch mode and it works quite well. The only problem I have is that the transcription is cut short when there is a silence of 2 or more seconds in the audio stream. I then get the resulting transcription up to that point, but I am missing what follows. Is there a way to parameterize transcription so that silences up to a given duration do not cause it to stop?

**Comment by zhouwangzw** [comment]
if you are using [Batch Transcription](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription), the complete file should be transcribed, and the silence in file should not stop the transcription. 
Could you please provide us the transcription id (together with region and approximate time), and if possible, also the audio causing the problem?

Thanks,

**Comment by michelpelletier07** [comment]
Oh.  I just found it.  I am receiving each part separately in the result.  All is good.  Many thanks for your help.

**Comment by michelpelletier07** [comment]
Many thanks for your help.
