### ISSUE TITLE
Application quits to desktop on Raspberry Pi

### ISSUE THREAD

**Issue by rozensoftware** [Azure-Samples/cognitive-services-speech-sdk#660]
Hi,

I got stuck with testing a speech to text sample on my Raspberry Pi 3B (Raspbian).
I was trying to run the [sample](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/speech-to-text-from-file?tabs=linux%2Cbrowser%2Cwindowsinstall&pivots=programming-language-csharp) in Raspberry (.NET Core 3.1, arm32).

Unfortunately program is not stable and quits to Bash very often with:
corrupted size vs. prev_size.

I didn't find too much about it but the error is located somewhere in Microsoft.CognitiveServices.Speech.csharp.dll.

I ran c++ version of that example with the same result. gdb shown segmentation fault in file malloc.c.

Hope this helps to find a solution for this bug. (Speech SDK Release 1.12.0)

**Comment by pankopon** [comment]
Hi, unfortunately Raspbian is not supported at the moment. Please see https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk?tabs=linux for the list of officially supported environments (for example, Ubuntu on RPi).
