### ISSUE TITLE
transcription.Properties Exceeds the maximum length for a value of 256 characters.

### ISSUE THREAD

**Issue by wistreng** [Azure-Samples/cognitive-services-speech-sdk#661]
Previous batch transcription script is not working:
I am using swagger_client from API v2
I use azure blob (service sas key) for the transcription result

properties = {
        'AddSentiment': True,
        'TranscriptionResultsContainerUrl': RESULT_BLOB_URI
    }

![image](https://user-images.githubusercontent.com/20368309/82617505-62e2ae00-9c24-11ea-958d-f8d4f034e53e.png)

**Comment by bexxx** [comment]
I can confirm this is an issue on v2.

We will provide a fix for this in the next deployment to PROD which is expected to be complete within 10 days.

**Comment by BeigeBadger** [comment]
:eyes:

**Comment by bexxx** [comment]
The release will start rolling out beginning of next week. We just started the deployment into pre production systems. Sorry for the slight delay.

**Comment by oscholz** [comment]
Closing this as the fix should be rolled out now. @wistreng please let us know if this is still an issue.
