### ISSUE TITLE
SIGSEGV(SEGV_MAPERR)

### ISSUE THREAD

**Issue by wall3001** [Azure-Samples/cognitive-services-speech-sdk#663]
It is an intermittent issue.
1.device 
 android 8.1
 sdk 1.11.0
2. use PushAudioInputStream  to write audio data.
May be cause it.
Java_com_microsoft_cognitiveservices_speech_internal_carbon_1javaJNI_PushAudioInputStream_1Write+108)
3.I had check the SpeechRecognizer and inpustream state before wirte.

**Comment by jhakulin** [comment]
@wall3001 Could you please test and report on the latest 1.12.0 release also ?

**Comment by wall3001** [comment]
OK.I’ll test it.

**Comment by jhakulin** [comment]
Closing the issue as not repro, let us know if you still see problems.
