### ISSUE TITLE
I had a error - Connection failed

### ISSUE THREAD

**Issue by bokyungJ** [Azure-Samples/cognitive-services-speech-sdk#664]
I want to use voice recognition technology in Unity.
So I got a 30-day free trial account. 
I tried your <Quickstart: Recognize speech from a microphone> in Speech Service.
I find and replace the string"YourSubcriptionKey" with my key
and I find and replace the string "YourServiceRegion" with my region "koreacentral"
But I got a Error.
The error log is "CANCELED:Reason=Error ErrorDetails=Connection failed (no connection to the remote host). Internal error: 1. Error details: -1. Please check network connection, firewall setting, and the region name used to create speech factory."
My Unity version is 2019.3.13f1

**Comment by lisaweixu** [comment]
Is your subscription key created in "koreacentral" region? Is your key working under other platforms, such as Windows or Linux?

**Comment by bokyungJ** [comment]
The key created in Korea.
I didn't try this under other platform.
My platform is Window and I want to use this SDK under Unity.

**Comment by jhakulin** [comment]
@bokyungJ 

Are you using UWP app built from Unity ?

In the section Publishing Settings, please check that checkmarks are set for the these capabilities in the Capabilities control (these should be there in the sample by default).
InternetClient
InternetClientServer
Microphone

**Comment by bokyungJ** [comment]
@jhakulin 
Oh sorry. I'll build it android.
The Publishing Settings in android platform, there is no Capabilities control.
What should I do?

**Comment by jhakulin** [comment]
@bokyungJ Android should also work fine as long as your key works. Could you make a test with your Windows PC by running following sample with your keys, does that work OK ?
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/dotnet/from-microphone

If you still have an issue, could you provide a log using instructions below?
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

**Comment by jhakulin** [comment]
Closing the issue as there has been no response for more information.
