### ISSUE TITLE
Word/phrase level timestamp consistency between recognizing and recognized result

### ISSUE THREAD

**Issue by wukun2015** [Azure-Samples/cognitive-services-speech-sdk#665]
Hello,

Is word and/or phrase level "Offset" and "Duration" values in Recogniz-ing result consistent/same as those in Recogniz-ed result ? 

E.g. Phrase "What is" time-stamp starts from 79600000 and ends on 83900000 (= offset 79600000 + duration 4300000) in Recogniz-ing result. Is its timestamp the same in Recogniz-ed result ? 

- RECOGNIZ-ING: Text={"Duration":4300000,"Id":"33661131e4b54d5cb5954ac005c712ee","Offset":79600000,"Text":"What is"}
- RECOGNIZ-ING: Text={"Duration":6600000,"Id":"b24420e71a8b4b8a8276414c0a78edd8","Offset":79600000,"Text":"What is the weather"}
- RECOGNIZ-ING: Text={"Duration":17400000,"Id":"199cc81c096e4e108451b494f0b99313","Offset":79600000,"Text":"What is the weather of Seattle"}
- RECOGNIZ-ING: Text={"Duration":17600000,"Id":"199cc81c096e4e108451b494f0b99313","Offset":79600000,"Text":"What is the weather of Seattle today ?"}
- 
- RECOGNIZ-ED: Text={"DisplayText":"What is the weather of Seattle today ?","Duration":17600000,"Id":"7e02086a833542d79d435ac9abf4b7dc","Offset":79600000,"RecognitionStatus":"Success"}

Such consistency will empower more scenarios like word/phrase level meeting-minute proofread, in additional to traditional sentence-level proofread. 

Thank you.

**Comment by rhurey** [comment]
The timing / offset values may not be consistent between Recognizing and Recognized results.

In most cases, Recognizing results are meant to be a way to help show progress to the user and aren't meant for long term decision making.

Can you expand more on what scenarios a more consistent Recognizing event would help with? I'm wondering if the word level timings that are available in the detailed Recognized results would be equally useful.

**Comment by rhurey** [comment]
I should elaborate...

Depending on your programming language…. (C# below)

Calling https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechconfig.requestwordleveltimestamps?view=azure-dotnet#Microsoft_CognitiveServices_Speech_SpeechConfig_RequestWordLevelTimestamps
Setting the output format to detailed
https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechconfig.outputformat?view=azure-dotnet#Microsoft_CognitiveServices_Speech_SpeechConfig_OutputFormat

And then reading the result JSON:
 `var json = result.Properties.GetProperty(PropertyId.SpeechServiceResponse_JsonResult)`

Will get detailed JSON like:

```
{
    "Id": "791d3f8a724846f69e9d9256947d2479",
    "RecognitionStatus": "Success",
    "Offset": 500000,
    "Duration": 13000000,
    "DisplayText": "What's the weather like?",
    "NBest": [
        {
            "Confidence": 0.97660327,
            "Lexical": "what's the weather like",
            "ITN": "what's the weather like",
            "MaskedITN": "what's the weather like",
            "Display": "What's the weather like?",
            "Words": [
                {
                    "Word": "what's",
                    "Offset": 500000,
                    "Duration": 3900000
                },
                {
                    "Word": "the",
                    "Offset": 4500000,
                    "Duration": 1300000
                },
                {
                    "Word": "weather",
                    "Offset": 5900000,
                    "Duration": 2900000
                },
                {
                    "Word": "like",
                    "Offset": 8900000,
                    "Duration": 4600000
                }
            ]
        },

```

**Comment by wukun2015** [comment]
It is working well for customer scenario. 

Thank you, Ryan
