### ISSUE TITLE
StartContinuousRecognitionAsync is not awaited

### ISSUE THREAD

**Issue by SOliasS** [Azure-Samples/cognitive-services-speech-sdk#666]
@jhakulin 
Other then RecognizeOnceAsync for example StartContinuousRecognitionAsync is not awaited and instead continuous like an async void.
Which is inconsistent behavior and not as nice to use.
This should we awaited like the other functions for more consistent use.
Also it would be nice if it would be possible to cash the complete dictation and get the result at the end when the dication get stopped and StartContinuousRecognitionAsync finishes.

**Comment by jhakulin** [comment]
@SOliasS Thanks for the feedback, so you would like an API method which starts continuous recognition and provides the result when awaited and recognition is stopped via other API method call? We will discuss this in the next upgrade (v2) of the API planning.

**Comment by SOliasS** [comment]
@jhakulin ye that's it.
Because at the moment i have to check the results and cache them and then combine them to get the full result.
And also it would be nice if the Recognition Methods all behave the same unlike StartContinuousRecognitionAsync  and RecognizeOnceAsync  which behave differently.

**Comment by pankopon** [comment]
We've added a work item for this to our backlog and will try to address it in a future release. Once the work is done, this issue will be updated to let you know when the release will be available.
