### ISSUE TITLE
How to remove punctuation ?

### ISSUE THREAD

**Issue by wukun2015** [Azure-Samples/cognitive-services-speech-sdk#667]
Hello,

How can i receive recognized result without punctuation ? 

E.g. Instead of "What is the weather today **?**", i'm expecting "What is the weather today" without question mark. 

Thank you.

**Comment by lisaweixu** [comment]
The "Lexical" field in the detailed recognized text does not contain punctuation.
For speech to text, you can turn on detailed format by `speechConfig->SetProperty(PropertyId::SpeechServiceResponse_OutputFormatOption, "detailed")` before creating the recognizer.

The Lexical field can be retrieved as follows:
```
auto result = recognizer->RecognizeOnceAsync().get();
string jsonResult = result->Properties.GetProperty(PropertyId::SpeechServiceResponse_JsonResult);
```
Here is an example of the jsonResult:

![image](https://user-images.githubusercontent.com/36937677/82932143-d1817d80-9f3c-11ea-872d-f18b59daea27.png)

**Comment by pankopon** [comment]
Closing the issue as the question was answered.

**Comment by prabhatsubedi** [comment]
I am having same issue in javascript sdk and I am using **startContinuousRecognitionAsync** function. I have added `speechConfig.setProperty("SpeechServiceResponse_OutputFormatOption", "detailed")` before creating the recognizer object but it's not returning `Lexical` field in :
```
recognizer.recognized = function (s, e) {
 console.log('recognized text', e.result.properties.getProperty("SpeechServiceResponse_JsonResult"));
};
```
Am I missing something ? Thank You.

**Comment by rhurey** [comment]
To set the output format use:
speechConfig.outputFormat = sdk.OutputFormat.Detailed;

The property you found about it is an internal one that isn't used by all recognizer types, the config option should work for all types.

**Comment by prabhatsubedi** [comment]
@rhurey Thanks it helped. But we need to enable` speechConfig.enableDictation();` so, this `Lexical` field is not useful. Is there any way to stop auto punctuation please ? Thank You.

**Comment by rhurey** [comment]
Just to make sure I get the right information...

Do you want automatic punctuation turned off, and explicit punctuation to still be on and rendered?

i.e. if the user spoke the words: "Call my wife period" you'd get "Call my wife." 
but if the user spoke "Call my wife" you'd get "Call my wife"
?

**Comment by prabhatsubedi** [comment]
@rhurey yes. That's exactly we want. Thanks

**Comment by prabhatsubedi** [comment]
@rhurey Is there any way to fix my issue please ?

**Comment by rhurey** [comment]
Add this:

speechConfig.setServiceProperty('punctuation', 'explicit', SpeechSDK.ServicePropertyChannel.UriQueryParameter);

To where you initialize your config object.

**Comment by 4voiceAG** [comment]
@rhurey Thanks, this does the trick. But your solution is incredibly hard to find.
For SpeechConfig.SetProperty() there's a PropertyId enumeration, at least, where you can browse the possible values in the online documentation.
But I failed to find any documentation on the different property names and values for SpeechConfig.SetServiceProperty.
Do you have any idea where to look?

TIA
