### ISSUE TITLE
Is it possible to get the duration of the audio blob stored in the container using C#

### ISSUE THREAD

**Issue by harmandeepsinghkalsi** [Azure-Samples/cognitive-services-speech-sdk#668]
Hi All,

I have a requirement wherein I need to know whether it is at all possible to get the duration of the audio blob stored in azure container using C# . Based on that I will further actions on the audio blob. 
Please suggest .

**Comment by harmandeepsinghkalsi** [comment]
The scenario I have is , once the audio blob (mostly .mp3 file) is uploaded to the container I need to check its duration(in min/secs) before further processing . I saw we have property in blob called as Length( size in bytes) but that will not suffice requirement. So my ask is there any mechanism I can get the duration of the audio blob (.mp3 file) using CloudStorageApis or any other way.

**Comment by pankopon** [comment]
Looks like the question was answered in https://stackoverflow.com/questions/62067362/get-the-duration-of-audio-blob-stored-in-azure-container-using-c-sharp therefore I'm closing this issue.

If you can find the duration of the audio file before or after uploading it, you can also store that information as blob metadata and later fetch the metadata as necessary, see https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-metadata.

**Comment by harmandeepsinghkalsi** [comment]
Yeah I was able to get the audio blob length while processing it too. Thank you !
