### ISSUE TITLE
Dictation mode not working when trying to transcribe a slash symbol ("/")

### ISSUE THREAD

**Issue by mgp19** [Azure-Samples/cognitive-services-speech-sdk#670]
I am using the speech SDK to transcribe voice to text. I am using the dictation mode enabling it in my code (EnableDictation() method) to transcribe a slash symbol ("/") but it doesn't work.
(https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-choose-recognition-mode?pivots=programming-language-csharp#dictation)

Example text I am using:
saying "hello slash hello slash hello" returns exactly the same.
Also in this case "150 slash 60" returns the same.

My goal is to achieve this to working in spanish language.
Example in spanish is "150 barra 60".

Is this supported?

**Version of the Cognitive Services Speech SDK**
1.12.0 (latest)

**Platform, Operating System, and Programming Language**
C#

**Comment by lisaweixu** [comment]
Have you tried to turn on the detailed output and check whether one of the nbest can achieve your goal? Please take a look at RecognitionWithLanguageAndDetailedOutputAsync at [here].(https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_recognition_samples.cs)

**Comment by mgp19** [comment]
Hello. Thank you for the quick answer.
 
I have seen the example you have shared.

I did not mention that I am using the continuous recognition mode. This involves receiving the transcription result by an **intermediate** result event (speechrecognizer.recognizing) and, after a short pause in the dictation (silence), by a **final** result event (speechrecognizer.recognized).

These are my observations:
- The received **intermediate** result does not contain nbest information (detailed) and does not transcribe a "/" symbol.
- The final result contains nbest and works well in spanish. It returns the desired "/" symbol.  I have not achieved it in english using "slash" or "forward slash".

I use the **intermediate** result event to give more real-time transcription response but I can not get this "/" symbol transcribed that way. Only after a pause (silence) is done on the dictation, the **final** result event is triggered giving the expected "/" symbol transcribed. 

Here is an example output:
![speechtotext_example_result](https://user-images.githubusercontent.com/32220562/83439686-f0ec3f00-a443-11ea-9760-6cf77b322a8c.PNG)

"barra diagonal" transcribes to "/" as expected.
This is only achieved when a dictation pause is done and the **final** result event is triggered.

I wonder if this symbol transcription part can be done as continuous as the rest of the transcription.

**Comment by amitkumarshukla** [comment]
@mgp19 As I understood your question, you are fine with the final result but somehow intermediate results do not match your expectation?

Just to let you know, intermediate results are mainly for user experience and you should not use it for any other purpose. You should only use the final result for all kind of your application. 

Do let me know if this works for you.

**Comment by mgp19** [comment]
Exactly. I use the intermiediate result only to show a real-time transcription result to the user (as he is being recorded) but I process this result when the recording is finished so I will take your advice of using the final result for this.

As the transcription precision is good I can do any workaround and manage to show a real-time symbol transcription as the user is recorded if needed.

We can close this, thanks.

**Comment by amitkumarshukla** [comment]
Thanks alot
