### ISSUE TITLE
cognitive-services-speech Browsers Compatibility 

### ISSUE THREAD

**Issue by soso-maitha** [Azure-Samples/cognitive-services-speech-sdk#671]
Hello,

I've been searching on the internet but couldn't find which browsers Microsoft Cognitive Speech is compatible with.

Most importantly these browsers:
- Edge
- Samsung internet (for Android)
- Safari (for iOS mobile) 
- Chrome (i'm sure this is compatible but just to confirm)

Because 2 years ago, it didn't work with IE and some mobile browsers.

**Comment by rhurey** [comment]
We regularly tested with FireFox (Windows), Chrome (Mac, Windows, Android), Edge (Windows), and Safari (Mac & iOS).

IE isn't in the test or support matrix as IE doesn't implement getUserMedia and that's how the SDK accesses the microphone.

Firefox and Chrome on iOS are usable for TTS playback but not speech recognition as they also don't have microphone support.

I'm going to close, this, please reopen if you need more information.
