### ISSUE TITLE
Word in NBest is not the same as DisplayText

### ISSUE THREAD

**Issue by wukun2015** [Azure-Samples/cognitive-services-speech-sdk#678]
Hello,

I'm using speechconfig.requestWordLevelTimestamps() to retrieve word-level timestamps in reco result. It is noticed that for numbers like 1025, 16.5%, 2020, 0.05, etc., the display text is different from that of Word in NBest. 

E.g. utterance "1025" in English will be recognized as "1025" in display text, while the NBest Words list are "one", "thousand", "and", "twenty", five". 
<img width="245" alt="1025" src="https://user-images.githubusercontent.com/13058007/84120684-bea49800-aa68-11ea-8204-4950bf92bda0.png">
Is there any way to change lexicon format in NBest Words list to Display Text format ? The purpose is to enrich post-recognition user experience. 

Thank you.

**Comment by pankopon** [comment]
Hi, the NBest Words list contains tokens based on lexical analysis of input (cf. the Lexical result attribute which contains the whole phrase) and the format is not configurable. Timestamps are assigned to these lexical tokens. If you are trying to provide visualization of recognized numerical digits with timestamps, you could try mapping between them and lexical tokens in code.
