### ISSUE TITLE
Class Not Found Errror AudioStreamContainerFormat

### ISSUE THREAD

**Issue by tonyalves** [Azure-Samples/cognitive-services-speech-sdk#681]
I just updated for version 1.12.0, I was in 1.9.0. When I start my programa I got this error:
`Exception in thread "main" java.lang.NoClassDefFoundError: com/microsoft/cognitiveservices/speech/internal/AudioStreamContainerFormat
`
But, looking at the files downloaded by Maven, the class file is there.
I could not find in the samples the code to use recognition from a file, or anothers methods, like before. Just the recog from mic.

**Comment by jhakulin** [comment]
@tonyalves Thanks for feedback, did you import the class as below?
import com.microsoft.cognitiveservices.speech.audio.AudioStreamContainerFormat;

https://docs.microsoft.com/en-us/java/api/com.microsoft.cognitiveservices.speech.audio.audiostreamcontainerformat?view=azure-java-stable

**Comment by tonyalves** [comment]
> import com.microsoft.cognitiveservices.speech.audio.AudioStreamContainerFormat;

Hi!
Yes, just like that.
The part of the code:
```
PullAudioInputStreamCallback callback = new WavStream(new FileInputStream(path));
		AudioInputStream inStream = AudioInputStream.createPullStream(callback,
				AudioStreamFormat.getCompressedFormat(AudioStreamContainerFormat.ALAW));

		AudioConfig audioInput = AudioConfig.fromStreamInput(inStream);`
```

**Comment by jhakulin** [comment]
@tonyalves We will update our documentation, there was an update in 1.12.0 which causes the issue as internal namespace is not in use anymore for public components.
import com.microsoft.cognitiveservices.speech.internal.AudioStreamContainerFormat;
In 1.12.0 that should be changed to
import com.microsoft.cognitiveservices.speech.audio.AudioStreamContainerFormat;
Apologies for confusion.

**Comment by tonyalves** [comment]
The

> @tonyalves We will update our documentation, there was an update in 1.12.0 which causes the issue as internal namespace is not in use anymore for public components.
> import com.microsoft.cognitiveservices.speech.internal.AudioStreamContainerFormat;
> In 1.12.0 that should be changed to
> import com.microsoft.cognitiveservices.speech.audio.AudioStreamContainerFormat;
> Apologies for confusion.

I understood. Thanks!
