### ISSUE TITLE
Integration between Batch Transcription and LUIS

### ISSUE THREAD

**Issue by harmandeepsinghkalsi** [Azure-Samples/cognitive-services-speech-sdk#682]
Hi

I have a requirement to do integration between the batch transcription and LUIS wherein I will pass the transcriptions as such to LUIS and get the intent of the audio.

As far as I know we can pass the data for intent analysis to LUIS as a query which accepts only 500 characters. 

So here comes the question is it possible to pass the full transcription from speech to text batch transcription API to LUIS for intent analysis or we have to feed the data in chunks to LUIS ? 

If we feed the data in chunks how we will get the overall intent of the audio?

Please suggest on the best possible way to achieve this.

**Comment by pankopon** [comment]
Is the whole transcription expected to represent one or more intents?

If it can represent multiple intents, then each recognized sentence in transcription SegmentResults can result in max 1 recognized intent from LUIS, right?

If the whole transcription is meant to describe just one intent, how long would the utterance for that reasonably be? For example, the following quote is 500 characters:

> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Curabitur pretium tincidunt lacus. Nulla gravida orci

**Comment by harmandeepsinghkalsi** [comment]
Is the whole transcription expected to represent one or more intents?
**Ideally yes.**

If it can represent multiple intents, then each recognized sentence in transcription SegmentResults can result in max 1 recognized intent from LUIS, right? 
**This is not the case. Since it is one conversation , it should ideally represent one single intent but I am afraid , if I sent the data to LUIS in chunks of 500 characters each seeing the limit,  it may result in getting different intents from LUIS, which is not expected here in my case.** 

If the whole transcription is meant to describe just one intent, how long would the utterance for that reasonably be?
**Yes , it should be one intent for the whole transcription . The length of the utterance will depend on the audio length. But since, we can only send 500 characters in the query to LUIS, I was thinking to split transcription and feed to LUIS which may or may not result in different intents from LUIS. In case i get different intents for the chunks , will it be possible for me to get the overall transcription intent. If yes , how can I achieve this?**

**Comment by pankopon** [comment]
I don't understand the scenario still. If it's just one intent for the whole transcription, can you please give examples of utterances that should result in an intent with your LUIS model? Based on
https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-concept-utterance
I consider utterances to be like "What kind of county fairs are happening in the Seattle area this summer?" which is one sentence of less than 100 characters.

If you mean that, despite of expecting only one such utterance to appear during a whole conversation, there might be actually several utterances that are recognized as different intents, and you would then like to get "the overall transcription intent" - how would you define the overall intent?

**Comment by pankopon** [comment]
Actually there's a specific note about this
https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-limits

> If you have text longer than this character limit [500], you need to segment the utterance prior to input to LUIS and merge the responses accordingly. There are obvious breaks you can work with, such as punctuation marks and long pauses in speech.

**Comment by harmandeepsinghkalsi** [comment]
I totally agree to the point that  utterances should be small , not more than 500 characters and that is what I am trying to do here , merge the segments from transcriptions into small groups on 500 characters and pass to LUIS for intent analysis.

 **you would then like to get "the overall transcription intent" - how would you define the overall intent?** - Yup that's what even I am thinking how is this achievable. I am asking the same.

Let me go through the links you shared.

**Comment by oscholz** [comment]
@harmandeepsinghkalsi I am going to close this issue for the moment. If you have further questions, please reopen the issue and describe your end to end scenario. 
With a better understanding of the end to end scenario, we might be able to recommend a better strategy for achieving your goals.
LUIS is meant to analyze the intent of individual conversation segments, which are usually shorter than 500 characters. It is not meant to analyze entire emails (as an example of longer text). 
Thank you for using the Speech SDK!
