### ISSUE TITLE
Grammar Support

### ISSUE THREAD

**Issue by tonyalves** [Azure-Samples/cognitive-services-speech-sdk#685]
Is there grammar support on azure? If so, there's some examples to follow and documentation?

**Comment by oscholz** [comment]
Thank you for your question @tonyalves!
It depends on what scenario you are trying to accomplish/build for. 
The Speech SDK supports [phrase lists](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-phrase-lists?pivots=programming-language-csharp), and you can also build a [custom speech model](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-custom-speech) without writing any code (Speech Studio makes this super easy). 
I'll close this issue for now. If this doesn't completely answer your question, please reopen the issue and provide us more details about your scenario. 
Thank you for using the Speech SDK!

**Comment by tonyalves** [comment]
> Thank you for your question @tonyalves!
> It depends on what scenario you are trying to accomplish/build for.
> The Speech SDK supports [phrase lists](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-phrase-lists?pivots=programming-language-csharp), and you can also build a [custom speech model](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-custom-speech) without writing any code (Speech Studio makes this super easy).
> I'll close this issue for now. If this doesn't completely answer your question, please reopen the issue and provide us more details about your scenario.
> Thank you for using the Speech SDK!

"Currently, Phrase Lists supports only English for speech-to-text."
Any chance to be available in another languages?
