### ISSUE TITLE
JVM crashing abruptly possibly due to low level binding issue

### ISSUE THREAD

**Issue by AravindaM** [Azure-Samples/cognitive-services-speech-sdk#689]
Hi, We are using text to speech function in the sdk and the jvm crashes randomly. This is happening under low load as well.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fae38433dc3, pid=7, tid=26214
#
# JRE version: OpenJDK Runtime Environment (11.0.7+10) (build 11.0.7+10)
# Java VM: OpenJDK 64-Bit Server VM (11.0.7+10, mixed mode, tiered, compressed oops, serial gc, linux-amd64)
# Problematic frame:
# C  [libMicrosoft.CognitiveServices.Speech.java.bindings.so+0x159dc3]  std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()+0x43
#
# Core dump will be written. Default location: /opt/api-service/core.7
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
#
```
As per the crash log this seems to be due to and issue in the library and it is not clear the exact cause of this.

SDK version : 1.11.0
container - centos:8

alsa-lib   1.1.9-4.el8
openssl  1:1.1.1c-2.el8_1.1
adoptopenjdk-11-hotspot-jre 11.0.7+10-1

Here is the full jvm crash log. 
[crash.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4796428/crash.log)

Appreciate if somebody can look into this.

**Comment by oscholz** [comment]
@AravindaM Thank you for submitting this bug, and I am sorry you are hitting this. I've added this to our backlog, and we will look at this as part of our current sprint. When we find a solution for this bug, we will update this issue with the details. In the meantime, we will close this issue, since we are now tracking this in our backlog. 
You may also want to try the latest version of the SDK (1.12.1) to see if the bug repros there as well. 
Thank you for using the Speech SDK!

**Comment by oscholz** [comment]
@AravindaM we closed the bug on our side, since the code in 12.1 is all new for this area. If you still experience this in 12.1 or later, please let us know.

**Comment by AravindaM** [comment]
hi @oscholz Thanks for the update. We have been running the service in both `centos:8` and `ubuntu:18.4` since this issue occured and in ubuntu it was pretty stable. Plan is to update to latest sdk version soon and i can verify this after sometime.

**Comment by oscholz** [comment]
Thank you @AravindaM. I hope it doesn't repro at that point. :)
