### ISSUE TITLE
Issue while integrating with Chatbot directline -instance.speechIsAvailable is not a function

### ISSUE THREAD

**Issue by Jibin12345** [Azure-Samples/cognitive-services-speech-sdk#69]
Hi,
     I have been using BING Speech API for TTS and STT functionalities within chat bot directline channel. And it has been working fine where we pass the speechOptions with speech recognizers and synthesizers.

However I am unable to find a corresponding code for new Azure Speech Service. I have created speech instance in azure west us region and have keys ready. However getting an error of "instance.speechIsAvailable is not a function" on page load itself
**Details:**
Chat bot- Microsoft Bot Framework V3
Chat bot channel- Directline
Speech Service Tier- Free
Speech Service Regions tried - westus and eastus,

Please refer screenshots and kindly guide on how to proceed. 
![js fail](https://user-images.githubusercontent.com/44056324/46851377-f03d0a00-ce14-11e8-9f2f-2ee025734684.PNG)
![js_code](https://user-images.githubusercontent.com/44056324/46851387-f92ddb80-ce14-11e8-89d5-52476eaaabdf.jpg)
Main requirement is to add speech capabilities into chat bot directline leveraging Azure Speech Service.

**Comment by wolfma61** [comment]
we are also not that familar with chatbot, you should approach this team directly

thx
Wolfgang

**Comment by wolfma61** [comment]
no feedback - closing
