### ISSUE TITLE
Is Pronunciation assessment feature available in Batch transcription as well?

### ISSUE THREAD

**Issue by tuanle07** [Azure-Samples/cognitive-services-speech-sdk#690]
I can only find documentations about the `pronunciation assessment` feature for single file transcription from Microsoft website. How can I do it for `batch` transcription? Thanks.

**Comment by pankopon** [comment]
@bexxx Is pronunciation assessment supported in batch transcription?

**Comment by bexxx** [comment]
It is not supported as part of batch transcriptions.

**Comment by oscholz** [comment]
I am going to close this issue @tuanle07 . If you want to make a feature request for this, please do so at our [UserVoice page](https://cognitive.uservoice.com/forums/912208-speech-service).

**Comment by melissamaai** [comment]
PG team will track this feature support in our backlog now.

**Comment by saurabhj2511** [comment]
Is Pronunciation Assessment supported as part of Speech Services - Batch Transcription?

**Comment by saurabhj2511** [comment]
Is Pronunciation Assessment supported as part of Speech Services - Batch Transcription?

**Comment by zhouwangzw** [comment]
Pronunciation assessment is currently not supported in batch transcriptions.
