### ISSUE TITLE
Only WavStream found. No Mp3 or PCM Stream class supported.

### ISSUE THREAD

**Issue by raymondmeng36** [Azure-Samples/cognitive-services-speech-sdk#693]
**Describe the bug**
Can not transfer inputstream(mp3 or pcm) to PullAudioInputStreamCallback. 

**To Reproduce**
Class: SpeechRecognitionSamples
Method: recognitionWithAudioStreamAsync

**Expected behavior**
I saw you guys provided a wavStream to create wav stream, but how can i create mp3 or pcm stream. I try to use wavstream with mp3 or pcm stream input but failed.

**Comment by pankopon** [comment]
Please see https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/588 for answers (use AudioStreamContainerFormat.MP3 for mp3).

**Comment by pankopon** [comment]
Closed as resolved since no further comments. Please open a new issue with details if you need more support.

**Comment by raymondmeng36** [comment]
I used the following code and got error: Unexpected exception: Exception with an error code: 0x29 (SPXERR_GSTREAMER_NOT_FOUND_ERROR)

AudioStreamFormat audioFormat = AudioStreamFormat.getCompressedFormat(AudioStreamContainerFormat.MP3);
            PullAudioInputStream pullStream = AudioInputStream.createPullStream(new BinaryAudioStreamReader(audioFileName), audioFormat);
            AudioConfig audioInput = AudioConfig.fromStreamInput(pullStream);
