### ISSUE TITLE
nodeJS speech to text errors initial silence timeout.

### ISSUE THREAD

**Issue by hungltph03955** [Azure-Samples/cognitive-services-speech-sdk#695]
I have problem about nodeJS speech to text errors initial silence timeout.

1. node index.js speech
2. (recognized)  Reason: NoMatch NoMatchReason: InitialSilenceTimeout

- MacOS
- Node v10.18.1

![image_2020_06_19T09_26_30_860Z](https://user-images.githubusercontent.com/20923439/85496528-a86d0f00-b606-11ea-8ed1-a51552a4e5a1.png)

**Comment by pankopon** [comment]
@glharper @rhurey Please check.

**Comment by glharper** [comment]
@hungltph03955 Thanks for the feedback. Could you attach test13.wav so that we can reproduce this issue?

**Comment by hungltph03955** [comment]
@glharper thank you for reply. This is the file I used in nodeJS speech to text.
[test13.wav.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4828802/test13.wav.zip)

**Comment by glharper** [comment]
@hungltph03955 Your file is a 44.1 kHz stereo wav file. Currently only 16 kHz mono wav files are supported for the nodeJS SDK. From the [quickstart (link)](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/speech-to-text-from-file?tabs=linux%2Cnodejs%2Cwindowsinstall&pivots=programming-language-javascript), note the line:
**var filename = "YourAudioFile.wav"; // 16000 Hz, Mono**

Thanks.

**Comment by glharper** [comment]
@hungltph03955 Please use this code to create the PushStream for a 44.1 kHz stereo file: 
 
**var format = sdk.AudioStreamFormat.getWaveFormatPCM(44100, 16, 2); //44.1 kHz, 16-bit, 2-channel
var pushStream = sdk.AudioInputStream.createPushStream(format);**

**Comment by hungltph03955** [comment]
@glharper 
thank you!! 
I have converted the text with test13.wav file. But when I test vs this file test9.wav, I got the InitialSilenceTimeout error. Because there are 5 seconds not saying.
Is there any way to fix it? Thank you so much

[test9.wav.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4834870/test9.wav.zip)

![Screen Shot 2020-06-26 at 10 01 33](https://user-images.githubusercontent.com/20923439/85816024-44785100-b794-11ea-8724-55722bed4808.png)

**Comment by glharper** [comment]
@hungltph03955 Set the InitalSilenceTimeout property using the code below:
  **speechConfig.setProperty(sdk.PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs, "10000"); // 10000ms**

Thanks.

**Comment by hungltph03955** [comment]
Hi @glharper 
I have convered the text but it seems n is missing text. Is there a way to fix it or am I missing that parameter?

![image_2020_06_26T04_09_04_572Z](https://user-images.githubusercontent.com/20923439/85929618-a1811d80-b8e0-11ea-91da-c7106e3da431.png)

Thanks.

**Comment by glharper** [comment]
@hungltph03955 You will have to use startContinuousRecognitionAsync instead of recognizeOnceAsync. Look through [Speech Recognition Tests](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/tests/SpeechRecognizerTests.ts)  for examples of the correct workflow for your use case. 

I'm closing this issue now as the original question has been answered.
