### ISSUE TITLE
 speechRecognizer.close() block thread on Android?

### ISSUE THREAD

**Issue by jzhw0130** [Azure-Samples/cognitive-services-speech-sdk#696]
**Describe the bug**
warning:
Long monitor contention with owner main (18771) at long com.microsoft.cognitiveservices.speech.util.SafeHandle.releaseRecognizerHandle(long)(SafeHandle.java:-2) waiters=0 in void com.microsoft.cognitiveservices.speech.Recognizer.doAsyncRecognitionAction(java.lang.Runnable) for 16.538s

Since I call the API in UI thread, it blocks the app for 16.538s.
Attention: The duration here is not constant, it changes depends on when I call close().

**To Reproduce**
1. Create a speechRecognizer
2. Call speechRecognizer.startContinuousRecognitionAsync();
3. After several seconds, call 
     speechRecognizer.stopContinuousRecognitionAsync();
     speechRecognizer.close();

Repeat the cycle twice, the issue occurs.

**Expected behavior**
speechRecognizer.close() does not block the thread.

**Version of the Cognitive Services Speech SDK**
v1.12.0

**Platform, Operating System, and Programming Language**
 - OS: Android 10
 - Hardware - ARM
 - Programming language: Java

**Comment by pankopon** [comment]
Thanks for reporting the issue. The call is necessarily synchronous but the time it's taking here seems quite high. We've created a backlog work item to improve this and intend to address it in a future release. When the work is done, this item will be updated with information about the release that contains the improvement.

**Comment by jzhw0130** [comment]
@pankopon 

Has the issue beed fixed?
