### ISSUE TITLE
how can i make real time speech to text with nodejs.

### ISSUE THREAD

**Issue by ArsalanNgi** [Azure-Samples/cognitive-services-speech-sdk#703]
I am recording user audio on the browser and send it on the backend. but not getting the right result.

If I record **hello how are you?** and send on the backend the result return **hello**.

I did not find any example with nodejs in a real-time speech to text with the stream.

Can any from Microsoft share code example, demo, or docs?

Thanks in advance.

**Comment by ArsalanNgi** [comment]
my backend code.

` ss(client).on('stream', function (stream, data) {
      // get the name of the stream
      const { region, samplesPerSecond, bitsPerSample, channels } = {
        "region": "--",
        "samplesPerSecond": 44100,
        "bitsPerSample": 16,
        "channels": 1
      };

      var s = sdk.SpeechConfig.fromSubscription('---', region);

      let p;
      const format = sdk.AudioStreamFormat.getWaveFormatPCM(samplesPerSecond, bitsPerSample, channels);


      p = sdk.AudioInputStream.createPushStream(format)
      stream.on('data', function (data) {
        p.write(data)
      })
      stream.on('end', function () {
        p.close()
        const audioConfig = sdk.AudioConfig.fromStreamInput(p);

        const r = new sdk.SpeechRecognizer(s, audioConfig);
        r.canceled = (o, e) => {
          try {
            var str = "(cancel) Reason: " + sdk.CancellationReason[e.reason];
            if (e.reason === sdk.CancellationReason.Error) {
              str += ": " + e.errorDetails;
            }
            console.log(str);

          } catch (error) {
            console.log("canceled error", error)

          }
        };
        r.recognized = (o, e) => {
          try {
            console.log(e.result.text)
            // var str = "(cancel) Reason: " + sdk.CancellationReason[e.reason];
            // if (e.reason === sdk.CancellationReason.Error) {
            //   str += ": " + e.errorDetails;
            // }

          } catch (error) {
            console.log("canceled error", error)

          }
        };

        r.recognizeOnceAsync(
          (p2) => {
            const res = p2;
            try {
              console.log(res.text)
              // resolve(res.text)
            } catch (error) {
              console.log(error)
              // reject(error)

              // done.fail(error);
            }
          },
          (error) => {
            // reject(error)
            console.log(error)

            // done.fail(error);
          });
      })
    })`

my front end code.

`recordAudio = RecordRTC(stream, {
                    type: 'audio',
                    mimeType: 'audio/webm',
                    sampleRate: 44100,
                    desiredSampRate: 16000,

                    recorderType: StereoAudioRecorder,
                    numberOfAudioChannels: 1,


                    //1)
                    // get intervals based blobs
                    // value in milliseconds
                    // as you might not want to make detect calls every seconds
                    timeSlice: 1000,

                    //2)
                    // as soon as the stream is available
                    ondataavailable: function (blob) {
                        console.log('here');
                        // 3
                        // making use of socket.io-stream for bi-directional
                        // streaming, create a stream
                        var stream = ss.createStream();
                        // stream directly to server
                        // it will be temp. stored locally
               
                        ss(socket).emit('stream', stream);
                        // pipe the audio blob to the read stream
                        ss.createBlobReadStream(blob).pipe(stream);
                    }
                });

                recordAudio.startRecording();
                stopRecording.disabled = false;
            }, function (error) {
                console.error(JSON.stringify(error));
            });`

**Comment by BrianMouncer** [comment]
have you seen the JS examples in our SDK Samples repo?
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/index.html

giving you code a quick scan, I do not see anything glaringly wrong.
I would look into these two areas:

1) You used recognizeOnceAsync, so if there is a long enough pause between "hello" and "how are you" the reco would endpoint and return only "hello". You may want to switch to startContinuousRecognitionAsync(). the above sample has some examples of that.

2) If there is any mismatch in sample rate, bit rate, or channels from what you are recording, and the format you told the SDK the audio format is, you may not get an immediate error, but can get VERY unpredictable reco results. So double check the format you passed to sdk.AudioInputStream.createPushStream(format) is actually what you are recording with in your front end stream.

If neither of those help you figure it out, give me some more details, and I can have someone on the team that is better in Node/JS take a look at your question.

**Comment by ArsalanNgi** [comment]
Thanks for your response.
I have updated my front end and backend.
`

function SpeechToText () {
  const { region, samplesPerSecond, bitsPerSample, channels } = {
    "region": "--",
    "samplesPerSecond": 44100,
    "bitsPerSample": 16000,
    "channels": 1
  };

  var s = sdk.SpeechConfig.fromSubscription('--', region);

  let p;
  const format = sdk.AudioStreamFormat.getWaveFormatPCM(samplesPerSecond, bitsPerSample, channels);


  this.pushStream = sdk.AudioInputStream.createPushStream(format)

  this.recognizeAsync = function () {
    let audioConfig = sdk.AudioConfig.fromStreamInput(this.pushStream);
    this.recognizer = new sdk.SpeechRecognizer(s, audioConfig);
    this.recognizer.startContinuousRecognitionAsync();
cognizer.canceled = (o, e) => {
      try {
        console.log("canceled", e, o)

      } catch (error) {
        console.log("canceled error", error)

      }
    };
    this.recognizer.recognizing = (rec, { result }) => {
      console.log('recognizing', result.text)
    };
    this.recognizer.recognized = (rec, { result }) => {
      console.log('recognized: ', result.text)

    };
  }
}

var speectToText = new SpeechToText();
speectToText.recognizeAsync()


// Converts text to speech using the input from readline.
function _speechToText(text, config, selectedLang) {
  return new Promise(async (resolve, reject) => 
    speectToText.pushStream.write(text)
  })

};`

and my front end code 

`
navigator.mediaDevices.getUserMedia({ audio: true }).then(
              stream => {
                let vm = this;
                vm.stream_data = stream;
                function convertFloat32ToInt16(buffer) {
                  let l = buffer.length;
                  let buf = new Int16Array(l / 3);

                  while (l--) {
                    if (l % 3 === 0) {
                      buf[l / 3] = buffer[l] * 0xffff;
                    }
                  }
                  return buf.buffer;
                }
                AudioContext = window.AudioContext || window.webkitAudioContext;
                context = new AudioContext({
                  // if Non-interactive, use 'playback' or 'balanced' // https://developer.mozilla.org/en-US/docs/Web/API/AudioContextLatencyCategory
                  latencyHint: "interactive"
                });
                processor = context.createScriptProcessor(bufferSize, 1, 1);
                processor.connect(context.destination);
                context.resume();
                globalStream = stream;
                input = context.createMediaStreamSource(stream);
                input.connect(processor);

                processor.onaudioprocess = function(e) {
                  microphoneProcess(e);
                };

                var downsampleBuffer = function(
                  buffer,
                  sampleRate,
                  outSampleRate
                ) {
                  if (outSampleRate == sampleRate) {
                    return buffer;
                  }
                  if (outSampleRate > sampleRate) {
                    throw "downsampling rate show be smaller than original sample rate";
                  }
                  var sampleRateRatio = sampleRate / outSampleRate;
                  var newLength = Math.round(buffer.length / sampleRateRatio);
                  var result = new Int16Array(newLength);
                  var offsetResult = 0;
                  var offsetBuffer = 0;
                  while (offsetResult < result.length) {
                    var nextOffsetBuffer = Math.round(
                      (offsetResult + 1) * sampleRateRatio
                    );
                    var accum = 0,
                      count = 0;
                    for (
                      var i = offsetBuffer;
                      i < nextOffsetBuffer && i < buffer.length;
                      i++
                    ) {
                      accum += buffer[i];
                      count++;
                    }

                    result[offsetResult] = Math.min(1, accum / count) * 0x7fff;
                    offsetResult++;
                    offsetBuffer = nextOffsetBuffer;
                  }
                  return result.buffer;
                };

                function microphoneProcess(e) {
                  var left = e.inputBuffer.getChannelData(0);
                  // var left16 = convertFloat32ToInt16(left); // old 32 to 16 function
                  var left16 = downsampleBuffer(left, 44100, 16000);
                  ss(socket).emit("microsoft-stt", left16);
                }

              },
              function(error) {
                console.error("error0--------", JSON.stringify(error));
                this.microphone = false;
                this.recorder.stopRecording();
              }
            );

`

If I convert blob in base64 and send on backend it works fine but when converting in binary send on the backend it does not work.

**Comment by pankopon** [comment]
@glharper Can you please check this?

**Comment by glharper** [comment]
First, a minor point. For using async methods, ordering is important. You should define your canceled, recognized, and recognizing callbacks before calling StartContinuousRecogntionAsync. 

So for converting in binary, how do you know the data you're passing into the push stream is the same as for base64, given that the push stream parameters ( "samplesPerSecond": 44100,"bitsPerSample": 16000,"channels": 1) are the same for both conversions?

**Comment by pankopon** [comment]
@ArsalanNgi Is this still a valid issue for you? Please update.

**Comment by trrwilson** [comment]
Standard text: to keep our active issues list fresh, we'll consider an issue resolved after 14 days of inactivity [here, already elapsed]. If this was premature, please open another issue (and feel free to reference this one) and we'll investigate. Thank you!

**Comment by NereaCabiedasMoreno** [comment]
hello, I would like to know how I can add the speech to text functionality to a bot that I have created in Node.js
