### ISSUE TITLE
Possibility to train custom model via REST API calls ?

### ISSUE THREAD

**Issue by manojmsrit** [Azure-Samples/cognitive-services-speech-sdk#706]
Hello all, I am aware of training a new custom model in MS-AZURE through the portal but I would like to do the custom model training process ( upload the training datasets, train, test, deploy ) through REST API. 

If not so, Please suggest me how can I do the custom model training programmatically (using Python). Thank you for your consideration.

Regards,
Manoj

**Comment by BrianMouncer** [comment]
I was just talked to our PM about programmatic access to our training portals yesterday.  He suggested we can use the SWAGER interfaces to do most things done manually in the Web Portal. 

I was talking to him about the LUIS intent models, which can be found here, https://westus.dev.cognitive.microsoft.com/docs/services/luis-programmatic-apis-v3-0-preview/operations/5890b47c39e2bb052c5b9c2f

but I think we have the same for the "custom speech models" and I will try to find them and get back to you here.
For general Swagger info you can look here, https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/swagger-documentation#:~:text=The%20Speech%20service%20offers%20a%20Swagger%20specification%20to,portal%20can%20be%20completed%20programmatically%20using%20these%20APIs.

When the team gets back next week, I will see if they have any better links to Swagger and Rest documentation for custom speech models, but above is the info I have right now.

**Comment by BrianMouncer** [comment]
Our PM got back to me, and the REST/Swagger docs for the custom model building is here.

https://westeurope.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/operations/CreateModel

Please take a look at these, and I will add a Work Item to our backlog to create SDK API surfaces for these REST APIs, similar to what I would requested for retrieving the list of supported TTS voice for the region and datacenter your application is connected to.

**Comment by manojmsrit** [comment]
Thank you for the information. I will try this and get back to you if I face any issues. 

Regards,
Manoj

**Comment by megharangaswamy** [comment]
Hi @BrianMouncer , 

I also used this option and now trying to use the services using a curl call in a script. I see the call is successful and see the changes ( eg: when I try to create a new custom model). But to do further actions inside the script, I want to get the response which includes the ID of the model it created (I mean in model creation case, I need the model ID). In swagger UI, I see the response headers include Location info and at the end of the path, I can access it. But for some reason, I do not get the response headers including Location info. 

for Instance, 
```
response  = requests.post(My_API_curl_call_here)
print(response.headers) 
```
# this contains only the below fields
`{'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Content-Length': '104', 'Content-Type': 'text/plain; charset=utf-8', 'Expires': '-1', 'Server': 'Microsoft-IIS/10.0', 'api-supported-versions': '2.0-apim, 2.0, 2.1, 3.0-beta1, 3.0-rc, 3.0', 'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '49', 'X-RateLimit-Reset': '2020-07-13T11:51:09Z', 'X-Powered-By': 'ASP.NET', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Date': 'Mon, 13 Jul 2020 11:51:04 GMT'}`

Please suggest to me, how I can get a workaround for this.

Thank you,
Megha

**Comment by megharangaswamy** [comment]
> Hi @BrianMouncer ,
> 
> I also used this option and now trying to use the services using a curl call in a script. I see the call is successful and see the changes ( eg: when I try to create a new custom model). But to do further actions inside the script, I want to get the response which includes the ID of the model it created (I mean in model creation case, I need the model ID). In swagger UI, I see the response headers include Location info and at the end of the path, I can access it. But for some reason, I do not get the response headers including Location info.
> 
> for Instance,
> 
> ```
> response  = requests.post(My_API_curl_call_here)
> print(response.headers) 
> ```
> 
> # this contains only the below fields
> `{'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Content-Length': '104', 'Content-Type': 'text/plain; charset=utf-8', 'Expires': '-1', 'Server': 'Microsoft-IIS/10.0', 'api-supported-versions': '2.0-apim, 2.0, 2.1, 3.0-beta1, 3.0-rc, 3.0', 'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '49', 'X-RateLimit-Reset': '2020-07-13T11:51:09Z', 'X-Powered-By': 'ASP.NET', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Date': 'Mon, 13 Jul 2020 11:51:04 GMT'}`
> 
> Please suggest to me, how I can get a workaround for this.
> 
> Thank you,
> Megha

I just figured it out. Whenever the POST call is not successful, the header will not contain Location info.

**Comment by glecaros** [comment]
Closing as there hasn't been any activity for a while. Please reopen if you need to follow up.
