### ISSUE TITLE
Xamarin iOS Linking Error

### ISSUE THREAD

**Issue by SOliasS** [Azure-Samples/cognitive-services-speech-sdk#707]
@jhakulin I tried to finaly build my app for iOS, but unfortunatly i ran into an Problem.
When try to build for iOS i get a linking error as soon as i try to include code from the Cognitive Speech librarie.
I am able to build if i enable full linking, but this completly destroys the rest of the project.
Is there any way to workaround this issue?
![image](https://user-images.githubusercontent.com/14180046/86521482-7901a200-be51-11ea-9e37-3a89c704ab54.png)

**Comment by jhakulin** [comment]
@SOliasS Did you find solution for this as this was closed by you?

**Comment by SOliasS** [comment]
I thought i had it fixed by adding a --registrar:static and enable link framework, but unfortunatly i was only able to make it compile again...
When trying to use it it doesn't work.
I was not able to go deeper and infestigate further yet...
![image](https://user-images.githubusercontent.com/14180046/86600044-c724bb80-bf9f-11ea-80a6-fab3c54ac006.png)

**Comment by jhakulin** [comment]
@SOliasS Some clarifications, are you using device or simulator? Is there a build issue or functionality issue? What is the functionality you are testing and what is the error you see ? Did the https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/xamarin sample work for you ?

**Comment by SOliasS** [comment]
@jhakulin @pankopon  i'm not exactly sure what i did but the problem disapeared...
i can even set the linking to none and remove the additional arguments..
i added a vew permissions to info plist and change some stuff around in the project and restartet...
so no clue what the problem originated from but now it works as expected.

**Comment by jhakulin** [comment]
@SOliasS Yes, there should not be need for additional build arguments, perhaps the build environment required clean-up,
