### ISSUE TITLE
 Microsoft cognitive speech sdk failing on appcenter install.

### ISSUE THREAD

**Issue by Smolinskie** [Azure-Samples/cognitive-services-speech-sdk#712]
I get the following issue when trying to use the microsoft cognitive speech through app center

         __ZN9Microsoft17CognitiveServices6Speech4Impl13BaseGstreamer15ThrowAfterCleanEbjPKc in 174.o

         __ZN9Microsoft17CognitiveServices6Speech4Impl13BaseGstreamer11UnrefObjectEPPv in 174.o

         __ZN9Microsoft17CognitiveServices6Speech4Impl13BaseGstreamer4StopEv in 174.o

         __ZN9Microsoft17CognitiveServices6Speech4Impl13BaseGstreamer9GetStatusEv in 174.o

         __ZN9Microsoft17CognitiveServices6Speech4Impl11OpusDecoder15PadAddedHandlerEP11_GstElementP7_GstPadPS3_ in 176.o

     "_gst_pad_get_current_caps", referenced from:

         __ZN9Microsoft17CognitiveServices6Speech4Impl11OpusDecoder15PadAddedHandlerEP11_GstElementP7_GstPadPS3_ in 176.o

     "_gst_pad_is_linked", referenced from:

         __ZN9Microsoft17CognitiveServices6Speech4Impl11OpusDecoder15PadAddedHandlerEP11_GstElementP7_GstPadPS3_ in 176.o

     "_gst_pad_link", referenced from:

         __ZN9Microsoft17CognitiveServices6Speech4Impl11OpusDecoder15PadAddedHandlerEP11_GstElementP7_GstPadPS3_ in 176.o

     "_gst_pipeline_new", referenced from:

         __ZN9Microsoft17CognitiveServices6Speech4Impl13BaseGstreamerC2ENSt3__18functionIFiPhjEEE in 174.o

     "_gst_sample_get_buffer", referenced from:

         __ZN9Microsoft17CognitiveServices6Speech4Impl13BaseGstreamer10NewSamplesEP11_GstElementPS3_ in 174.o

     "_gst_structure_get_name", referenced from:

         __ZN9Microsoft17CognitiveServices6Speech4Impl11OpusDecoder15PadAddedHandlerEP11_GstElementP7_GstPadPS3_ in 176.o

   ld: symbol(s) not found for architecture arm64

I am not seeing this issue at all locally but as soon as I deploy the code onto azure the build continuously keeps failing. I have tried changing several of the xcode build settings in order to try and get around this error but have not been able to successfully deploy this. Any suggestions would be much appreciated.

I am using xcode:11.5

**Comment by trrwilson** [comment]
Hello, and thank you for getting in touch.

The first thing that comes to mind: the offending lines in the above objects (related to GStreamer and OPUS) are functionality that come from a 3rd-party library (separate from the Speech SDK) that needs to be present in the execution environment for certain audio format support. This page provides some information, but it's tailored to Ubuntu/RHEL config and not an Azure deployment: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams

If you're using advanced audio format support, could you please verify that gstreamer is deployed/configured along with your application and its dependencies?

And if you're not using advanced audio format support, this is a surprise as the gstreamer dependency is optional and as-needed. In that case, have you tried deploying one of the sample applications to rule out any code differences?

Thank you!

**Comment by Smolinskie** [comment]
> Hello, and thank you for getting in touch.
> 
> The first thing that comes to mind: the offending lines in the above objects (related to GStreamer and OPUS) are functionality that come from a 3rd-party library (separate from the Speech SDK) that needs to be present in the execution environment for certain audio format support. This page provides some information, but it's tailored to Ubuntu/RHEL config and not an Azure deployment: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams
> 
> If you're using advanced audio format support, could you please verify that gstreamer is deployed/configured along with your application and its dependencies?
> 
> And if you're not using advanced audio format support, this is a surprise as the gstreamer dependency is optional and as-needed. In that case, have you tried deploying one of the sample applications to rule out any code differences?
> 
> Thank you!



> Hello, and thank you for getting in touch.
> 
> The first thing that comes to mind: the offending lines in the above objects (related to GStreamer and OPUS) are functionality that come from a 3rd-party library (separate from the Speech SDK) that needs to be present in the execution environment for certain audio format support. This page provides some information, but it's tailored to Ubuntu/RHEL config and not an Azure deployment: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams
> 
> If you're using advanced audio format support, could you please verify that gstreamer is deployed/configured along with your application and its dependencies?
> 
> And if you're not using advanced audio format support, this is a surprise as the gstreamer dependency is optional and as-needed. In that case, have you tried deploying one of the sample applications to rule out any code differences?
> 
> Thank you!

I'm using Ionic  Media, MediaObject  from '@ionic-native/media/ngx'; to handle some audio.I tried to comment out that audio code and re run the azure devops pipeline and still getting the same issue. Most of the code I have is from the sample with a few modifications nothing else related to advanced audio besides what is in the sample and ionic media,mediaObject which still seem to cause the issue. we are also using mac-os latest in azure dev ops pipeline

**Comment by Smolinskie** [comment]
Is there a way we can ignore the gstream wrapper?

**Comment by jhakulin** [comment]
@Smolinskie GStreamerWrapper.framework is s weakly linked inside Speech SDK framework, which means that the app should be able to run on device/OS that doesn't have that particular framework available. https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/WeakLinking.html
However there has been similar issues also to describe problems with the Apple store deployment, could be that requirements in app deployment has been changed by Apple related to weak_framework. We are looking for that.

**Comment by Smolinskie** [comment]
I was able to get around that issue to an extent by manually adding the gstream framework.However I am now seeing this issue on the azure pipeline when trying to deploy❌  ld: bitcode bundle could not be generated because '/Users/runner/work/1/s/ios/App/Pods/MicrosoftCognitiveServicesSpeech-iOS/GStreamerWrapper.framework/GStreamerWrapper' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/runner/work/1/s/ios/App/Pods/MicrosoftCognitiveServicesSpeech-iOS/GStreamerWrapper.framework/GStreamerWrapper' for architecture arm64

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by aceecoder** [comment]
got past the error by adding bitcode flags. But he archive step is failing as below. Even tried with the code sample 
CompressedStreamsSample.

/usr/bin/xcodebuild -exportArchive -archivePath /Users/runner/work/1/s/CompressedStreamsSample.xcarchive -exportPath /Users/runner/work/1/s/output/iphoneos/Release -exportOptionsPlist _XcodeTaskExportOptions.plist | /usr/local/lib/ruby/gems/2.6.0/bin/xcpretty --no-color
2020-07-09 01:15:58.105 xcodebuild[2284:24082] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/CompressedStreamsSample_2020-07-09_01-15-58.104.xcdistributionlogs'.


error: exportArchive: IPA processing failed
Error Domain=IDEFoundationErrorDomain Code=1 "IPA processing failed" UserInfo={NSLocalizedDescription=IPA processing failed}

**Comment by aceecoder** [comment]
@trrwilson Any suggestions on this error? error: exportArchive: IPA processing failed
Error Domain=IDEFoundationErrorDomain Code=1 "IPA processing failed" UserInfo={NSLocalizedDescription=IPA processing failed}

**Comment by jhakulin** [comment]
@aceecoder Could you try with latest 1.13.0 release and let us know do you see the issue anymore?

**Comment by jhakulin** [comment]
Closing as no customer updates, please let us know if you have more issues.
