### ISSUE TITLE
Does the Azure Cognitive Services Speech SDK allow for Pronunciation assessment?

### ISSUE THREAD

**Issue by setwerks** [Azure-Samples/cognitive-services-speech-sdk#714]
I only see it in the REST API...which works but hoping to have more options. Am I missing it somewhere in the SDK? Any help would be appreciated.

**Comment by trrwilson** [comment]
Thanks for contacting us. You're unfortunately not missing anything--the SDK and the service results it uses don't yet have the pronunciation information that the REST API's endpoint provides. It's a great feature request for us to prioritize. I've added it to the team's work backlog with a backtrace to this issue and we'll update here once there's progress or new information.

**Comment by pankopon** [comment]
Closing the issue since a backlog work item has been created. Once the work is done, we will update this to let you know what release the feature will be in.

**Comment by yulin-li** [comment]
@swashtek The pronunciation assessment feature was released with SDK 1.14.0. Check our [how-to](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-pronunciation-assessment) for quick starting!
