### ISSUE TITLE
SDK functionality support of v3 API

### ISSUE THREAD

**Issue by SOliasS** [Azure-Samples/cognitive-services-speech-sdk#716]
@jhakulin I was wondering if the sdk supports the new Features of the V3 API like "external entities" and "dynamic lists".
And if these features are supported in the german version.
In addition to that i was wondering what the diffrences between dynamic lists and Phrase lists are.

Source:
https://docs.microsoft.com/en-us/azure/cognitive-services/luis/schema-change-prediction-runtime

**Comment by SOliasS** [comment]
@jhakulin I was just completly blown away... Pharse list are working now with german selected.
Why did you guys didn't say anything/ said you could only give an eta in summer?

**Comment by jhakulin** [comment]
@SOliasS Thanks for feedback, for phraselist support, I am checking the deployments for different languages comes with the official communication.

**Comment by pankopon** [comment]
To update on the original topic, I've added a work item to the SDK backlog for study and planning of support for the mentioned features. This will be considered for future releases and we'll update this issue when the timeline is known.
