### ISSUE TITLE
Any possible way to use sdk without JNI library?

### ISSUE THREAD

**Issue by iamronic** [Azure-Samples/cognitive-services-speech-sdk#723]
To use JAVA sdk,  prerequisite is to install following 
apt-get install -y build-essential libssl1.0.0 libasound2

Our service backend team is worrying any potential conflict between JVM and JNI and reject to include it to docker file. In this situation,  do you have any guide or best practice to use sdk without install lib? Or it is impossible, still do you have guide to use websocket directly not going through sdk?

Thanks in advance.

**Comment by rhurey** [comment]
The Speech SDK has a native layer at its core allowing it to be projected into multiple different programming languages.

While in future versions it may become possible to reduce the native dependency footprint today its not.
From those libraries the speech SDK consumes today:
- build-essential: The runtime libraries for native components provided by the compiler / langauge.
- libssl: The encryption library that enables secure communication to the Speech Service.
- libasound2: Platform specific microphone support.

We do not publish the details of the WebSocket protocol.

As an alternative, we have a JavaScript variant of the Speech SDK that uses no native components.

**Comment by rhurey** [comment]
I'm going to close this assuming my response answered the question. If not lease comment and we can re-open tnis.
