### ISSUE TITLE
IntentRecognizer not working with au.luis.ai (australiaeast)

### ISSUE THREAD

**Issue by mentorfloat** [Azure-Samples/cognitive-services-speech-sdk#725]
**Describe the bug**
`IntentRecognizer` will not work with a LUIS app created in `australiaeast` (https://au.luis.ai). This is true even with a non-Starter_Key resource. Trying to run the C# console sample will return:

`CANCELED: ErrorCode=ConnectionFailure` and `CANCELED: Did you update the subscription info?`

I created a dummy LUIS app and resource in `westus` (https://www.luis.ai) and replaced the keys accordingly to test the hypothesis and the C# console sample worked fine.

**To Reproduce**
1. Create, train and publish a LUIS app in `australiaeast` (https://au.luis.ai)
2. Create and assign a `australiaeast` resource to the LUIS app
3. Use the above keys and region in the C# console sample in this repos
4. Build and run console app will return the error

**Expected behavior**
Initiates `RecognizeOnceAsync()` because `australiaeast` should be a supported region according to docs

**Version of the Cognitive Services Speech SDK**
Microsoft.CognitiveServices.Speech.csharp 1.12.1.28 

**Platform, Operating System, and Programming Language**
 - OS: Windows 10 Build 18363
 - Hardware - x64
 - Programming language: C#

**Comment by rhurey** [comment]
We've done some service side investigating and determined that there were some transient auth issues a few days ago, but as of now everything is working correctly.

Can you ensure that you're using a Prediction Resource key and not an Authoring Key and try again?
It would also be helpful if you had a session ID and an approximate time of connection for us to look through the service telemetry.

**Comment by mentorfloat** [comment]
It would've been before or on the same day as when I opened the issue, unfortunately no time stamp logged. Definitely was a Prediction key, not Authoring, but I tried both at that time when the first did not work.

I migrated to `westus` anyway so I don't have the original Luis resource to test now. Glad to hear it's working now.
