### ISSUE TITLE
Recogniser returns an error

### ISSUE THREAD

**Issue by nikunj-phutela** [Azure-Samples/cognitive-services-speech-sdk#726]
I tried deploying a custom commands demo from [https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-custom-commands-application](url), and I get an error which says recognizer returns an error while testing the application after training

**Comment by encorona-ms** [comment]
Thanks for the report, we are familiar with this error, is happening in the testing modal of the portal when there is no audio input for the turn.

We have are working on a fix and will update his issue once is live.

**Comment by encorona-ms** [comment]
The fix is live now.
