### ISSUE TITLE
Audio file gets capped to 10 minutes

### ISSUE THREAD

**Issue by koenverburg** [Azure-Samples/cognitive-services-speech-sdk#734]
Hi,

I'm running the Standard pricing model and my audio files get capped to 10 minutes, is this by design or am I missing a feature?

Quick googling and I came across the [long audio API](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/long-audio-api).
Do I need to switch to the long audio API to get longer than 10 minutes of audio recordings?

Kind regards,

Koen

**Comment by rhurey** [comment]
Sorry you're running into this problem.

From mentioning the long audio API I'm assuming you're trying to do text to speech and not speech recognition.

Yes, for text to speech there is a 10 minute limit on realtime audio file generation, and the long audio api should be used for longer speech synthesis.

**Comment by rhurey** [comment]
@yulin-li pointed me to this also: https://github.com/Azure-Samples/Cognitive-Speech-TTS/wiki/How-to-synthesize-long-sentences-to-a-single-audio-file

So you can make multiple requests and send them all to the same file.

**Comment by koenverburg** [comment]
Yes, that is correct. I'm using doing text to speech. The code can be viewed [here ](https://github.com/koenverburg/medium-to-speech/blob/development/src/Speech.ts)if necessary.

You mentioned that I can do multiple requests. Do I need to chuck my text and do the request per chuck?
Could you point me to the documentation where that is explained? Because I couldn't find in the link from @yulin-li I'm afraid.

**Comment by yulin-li** [comment]
yes, you need to split your text and do the request per chunk. It will be somethins like:

```ts
synthesizer.speakTextAsync(
      text1,
      null,
      (e) => this.handleError(e, synthesizer),
    );

...

synthesizer.speakTextAsync(
      textn,
      (r) => this.handleResponse(r, synthesizer),
      (e) => this.handleError(e, synthesizer),
    );

```

**Comment by rhurey** [comment]
I think we've answered this so I'm going to close it, @koenverburg if I'm wrong comment and I'll open it back up.

**Comment by koenverburg** [comment]
@rhurey I was a bit busy, so I haven't had the chance to update my project. But you have indeed answered my question. So closing the issue is fine. Thank you and @yulin-li
