### ISSUE TITLE
Expand the use of PropertyId for setting properties on DialogServiceConfig

### ISSUE THREAD

**Issue by wilhen01** [Azure-Samples/cognitive-services-speech-sdk#741]
At present, there is an inconsistency in the SDK around the use of the [PropertyId enum](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.propertyid?view=azure-dotnet). Certain properties that we set when creating the `DialogServiceConfig` object, e.g. `Conversation_From_Id`, `Speech_LogFilename`, are present in the enum. 

Others (e.g. `SPEECH-TransmitLengthBeforeThrottleMs`, `flightId`, `botId`) are not present, and hence magic strings have to be used, which is error prone. 

Could all available properties be added to this enum? Or another similar mechanism (SDK constants, etc.)?

**Comment by rhurey** [comment]
There's a balancing act in this. So I'll start by saying the SDK likely has the balance off kilter in some places.

The design principle the SDK aspires to follow when it comes to how to expose properties is one of progressive disclosure. In this philosophy we aim to not have an Intellisense experience where a developer types '.' and gets 100 options to choose from. The SDK then promotes the most used fields to be strongly typed on the config objects themselves. The goal is to expect that properties at this level are used by ~90% of developers in key scenarios.

Then there are properties that are discoverable by an enumeration. These properties are expected to be used by 5-8% of developers in varied scenarios.

The last set of configuration properties are ones the expectation is 2% or less of developers will consume them. Here the disclosure path is less clear or uniform. Some properties are mentioned in various How-To's. Some come out as a result of Issues, Support Tickets, or other means and aren't published publicly.

With that as a baseline for what properties are disclosed how, the throttle parameters are ones that we really hope much less than 2% of developers will need to use, the botId should be changed via the from*() methods on the BotFrameworkConfig, and the flightID isn't useful unless you are involved in flighting, which is a small number of users.

**Comment by wilhen01** [comment]
That's all fair - I certainly wouldn't expect some of the stuff we're dealing with here to be first class citizens of the config objects with their own convenience methods.

Is there a middle way where we can gain the benefit of type safety even for experimental features, maybe by using a separate enum or constants file? `ExperimentalPropertyId` or similar? It seems a shame to rely on magic strings in a strongly typed language.

**Comment by rhurey** [comment]
That's fair feedback. We're going to undertake a review of all the string based properties to determine which ones need more exposure and discoverability.

I'm going to close this for now, and will get back once the review is over.
