### ISSUE TITLE
How can I use different Neural Voice styles when synthesizing my audio files?

### ISSUE THREAD

**Issue by nansravn** [Azure-Samples/cognitive-services-speech-sdk#742]
[In this doc](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support#neural-voices) I've seen that the `PT-BR-FranciscaNeural` language support multiple voice styles.
* Is there any way to get this list of supported styles with the SDK?
* I didn't find any documentation with the full list of supported voice styles for FranciscaNeural.

**How can I synthesize Francisca's voice using a `calm` or `cheerful` style, for example?**

Here's my actual code:
```python
speech_key, service_region = "***REDACTED***", "southcentralus"

speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)
speech_config.speech_synthesis_voice_name = "pt-BR-FranciscaNeural"

file_config = speechsdk.audio.AudioOutputConfig(filename="output.wav")

speech_synthesizer = speechsdk.SpeechSynthesizer(speech_config=speech_config, audio_config=file_config)

## Calling the Speech Sythesizer 
text = "Muito obrigado!" #Portuguese text
result = speech_synthesizer.speak_text_async(text).get()
```

I've based on this script to synthesize my wav files: [speech_synthesis_sample.py](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_synthesis_sample.py)

**Comment by BrianMouncer** [comment]
It is a pain point I share, that I can't query the list of supported voiced, or translation languages via the client SDK.
I have a work item in our backlog to add this functionality to the SDK API surface.

For now, you can get the list via the web, and in your program via a rest API.

General info: http://docs.microsofttranslator.com/languages.html

TTS Specific: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-text-to-speech#get-a-list-of-voices

And a REST example in Python: https://docs.microsoft.com/bs-latn-ba/azure/cognitive-services/speech-service/quickstart-python-get-text-to-speech-voices


As to the "Speaking Style" you probably want to look at the documentation on SSML support.
This gives you the most flexibility in adjusting prosody, pitch, or selecting a style using <mstts:express-as style="cheerful">

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup

Let me know if you need more detail that this, and I will ask someone on our TTS team to give a more detailed response.


Brian.

**Comment by nansravn** [comment]
Thanks Brian for the quick answer.
Some comments about the links you've shared:

This link is not working for me:
`General info: http://docs.microsofttranslator.com/languages.html`

I've used the [third link](https://docs.microsoft.com/bs-latn-ba/azure/cognitive-services/speech-service/quickstart-python-get-text-to-speech-voices) to retrieve the full list of languages, and here I found all the styles for pt-BR-FranciscaNeural:
```
{'Name': 'Microsoft Server Speech Text to Speech Voice (pt-BR, FranciscaNeural)',
  'DisplayName': 'Francisca',
  'LocalName': 'Francisca',
  'ShortName': 'pt-BR-FranciscaNeural',
  'Gender': 'Female',
  'Locale': 'pt-BR',
  'StyleList': ['cheerful', 'calm'],
  'SampleRateHertz': '24000',
  'VoiceType': 'Neural'}
```

Regarding the [SSML link](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup?tabs=python#adjust-speaking-styles), initially it wasn't clear for me how to use the [SpeechSynthesizer.read_ssml_async()](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.speechsynthesizer?view=azure-python#speak-ssml-async-ssml--str-----azure-cognitiveservices-speech-resultfuture) method. But I've managed to make it work!

```python
speech_key, service_region = "***REDACTED***", "southcentralus"

speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)
file_config = speechsdk.audio.AudioOutputConfig(filename="output.wav")

speech_synthesizer = speechsdk.SpeechSynthesizer(speech_config=speech_config, audio_config=file_config)

#SSML with Portuguese text
text = """
    <speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="https://www.w3.org/2001/mstts" xml:lang="pt-BR">
        <voice name="pt-BR-FranciscaNeural">
            <mstts:express-as style="calm">
                Muito obrigado!
            </mstts:express-as>
        </voice>
    </speak>""" 

## Calling the Speech Sythesizer 
result = speech_synthesizer.speak_ssml_async(ssml=text).get()
```

Feel free to close this issue thread. As a final feedback, **I didn't find any documentation about sending SSML strings using the `SpeechSynthesizer.read_ssml_async()` method on this GitHub repo**. It would be great to have a more clear documentation about creating audios with voice styles, using the Python SDK (and/or other SDKs).**

**Comment by rhurey** [comment]
Thanks for the feedback on the documentation. I'm going to close this now since we took care of the original request.
