### ISSUE TITLE
VoiceProfiles not listed or verifying when creating as VoiceProfileType.TextInDependentVerification

### ISSUE THREAD

**Issue by QuackersCoder** [Azure-Samples/cognitive-services-speech-sdk#746]
When i Create a new voice profile of type VoiceProfileType.TextInDependentVerification using the SDK's CreateProfileAsync method..

It is not listed when i query the API with POSTMAN at either
https://westus.api.cognitive.microsoft.com//spid/v1.0/identificationProfiles
or
https://westus.api.cognitive.microsoft.com//spid/v1.0/verificationProfiles

However, the SDK successfully returns a voiceprofile with ID, 
I can use the SDK to then Enroll using 30s or so of speech, and it confirms it as enrolled.

When i try to verify, it says the profile can't be found

**Expected behavior**
I expect/assume the profile will be listed with other  verificationProfiles
Expect the profile to be found and run verification as appropriate when calling 

Environment
Using the windows version of SDK
OS: windows 10 Version 10.0.18363 Build 18363
Programming language: C# in a project targeting netstandard2.0
Tried enrolling using microphone and wav files and get the same errors.
App: Winforms

Version: Microsoft.CognitiveServices.Speech SDK 1.13.0

**Comment by rhurey** [comment]
The SDK is creating profiles in the v2 verion of the REST API, so the URLs to access them are:
/speaker/identification/v2.0/text-independent/profiles
/speaker/verification/v2.0/text-independent/profiles
/speaker/verification/v2.0/text-dependent/profiles

Same host name.

**Comment by QuackersCoder** [comment]
Thanks @rhurey is there a swagger definition anywhere for the speaker recognition V2 API? most links point to V1 or direct you towards the text-tospeech

**Comment by rhurey** [comment]
I didn't find a swagger file that I could share.

https://docs.microsoft.com/en-us/rest/api/speakerrecognition/ has examples using the 2.0 API.
