### ISSUE TITLE
ModuleNotFoundError: No module named '_speech_py_impl'

### ISSUE THREAD

**Issue by namujumd** [Azure-Samples/cognitive-services-speech-sdk#747]
**Describe the bug**
I am using the speech sdk in a Flask application for STT and TTS. The Flask Application builds fine on my Windows machine.

However, when I push it to Azure App Service(for Linux) it gives me the ModuleNotFoundError: No module named '_speech_py_impl'

I am currently trying to do the same using Docker Containers as suggested by Oliver in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/437 but am still facing the same issue. Error stack, requirements.txt and Dockerfile given below.

Btw if I run the application without the functionality of speech sdk, I can build and deploy the app to App Service and it runs fine for me.

**To Reproduce**
1. I am uploading a minimal version of my project at https://github.com/namujumd/testbug
2. Try building and running the docker container locally/push it to ACR->App Service. Both of them fail.

**Suspects**
1. I am new to Docker. Am I installing the system packages in the DockerFile properly?

**Version of the Cognitive Services Speech SDK**
azure-cognitiveservices-speech==1.12.1 (python)

**Platform, Operating System, and Programming Language**
Runs fine on Windows 10 locally. Cannot deploy to App Service for Linux (default Python app)/App Service for Containers way successfully. 

**Additional context**
Error Stack:
C:\Projects\Hack2020\dockertest\testbug>docker run testbug
Starting SSH ...
Starting OpenBSD Secure Shell server: sshd.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/azure/cognitiveservices/speech/speech_py_impl.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/local/lib/python3.6/site-packages/azure/cognitiveservices/speech/_speech_py_impl.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/runserver.py", line 6, in <module>
    from flaskwebapp import app
  File "/code/flaskwebapp/__init__.py", line 6, in <module>
    import azure.cognitiveservices.speech as speechsdk
  File "/usr/local/lib/python3.6/site-packages/azure/cognitiveservices/speech/__init__.py", line 8, in <module>
    from .speech import *
  File "/usr/local/lib/python3.6/site-packages/azure/cognitiveservices/speech/speech.py", line 8, in <module>
    from . import speech_py_impl as impl
  File "/usr/local/lib/python3.6/site-packages/azure/cognitiveservices/speech/speech_py_impl.py", line 17, in <module>
    _speech_py_impl = swig_import_helper()
  File "/usr/local/lib/python3.6/site-packages/azure/cognitiveservices/speech/speech_py_impl.py", line 16, in swig_import_helper
    return importlib.import_module('_speech_py_impl')
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_speech_py_impl'

---------------------------------------------------------------------------------------------------------------------------

requirements.txt
-----------------------
astroid==2.4.2
azure-cognitiveservices-speech==1.12.1
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
colorama==0.4.3
Flask==1.1.2
idna==2.10
isort==4.3.21
itsdangerous==1.1.0
Jinja2==2.11.2
lazy-object-proxy==1.4.3
MarkupSafe==1.1.1
mccabe==0.6.1
pylint==2.5.3
requests==2.24.0
six==1.15.0
toml==0.10.1
typed-ast==1.4.1
urllib3==1.25.9
Werkzeug==1.0.1
wrapt==1.12.1

-------------------------------------------------------------------------------------------------

DockerFile
FROM python:3.6.1

RUN mkdir /code
WORKDIR /code
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl1.0.0 \
    libasound2 
ADD requirements.txt /code/
RUN pip install -r requirements.txt
ADD . /code/

# ssh
ENV SSH_PASSWD "root:Docker!"
RUN apt-get update \
        && apt-get install -y --no-install-recommends dialog \
        && apt-get update \
	&& apt-get install -y --no-install-recommends openssh-server \
	&& echo "$SSH_PASSWD" | chpasswd 

COPY sshd_config /etc/ssh/
COPY init.sh /usr/local/bin/
	
RUN chmod u+x /usr/local/bin/init.sh
EXPOSE 5000 2222
ENTRYPOINT ["init.sh"]

**Comment by rhurey** [comment]
Thanks @pankopon for the answer:

> ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/local/lib/python3.6/site-packages/azure/cognitiveservices/speech/_speech_py_impl.so)


libstdc++ on the system is too old, ref. https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7

**Comment by namujumd** [comment]
Thanks @rhurey  @pankopon !

I used an ubuntu:18.04 base image in my DockerFile, installed python, system packages and the other requirements and is working fine now. 

Dockerfile looks like below now

FROM ubuntu:18.04

RUN mkdir /code
WORKDIR /code
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl1.0.0 \
    libasound2 \
    python3.7
RUN apt-get install -y python3-pip
ADD requirements.txt /code/
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
ADD . /code/

# ssh
ENV SSH_PASSWD "root:Docker!"
RUN apt-get update \
        && apt-get install -y --no-install-recommends dialog \
        && apt-get update \
	&& apt-get install -y --no-install-recommends openssh-server \
	&& echo "$SSH_PASSWD" | chpasswd 

COPY sshd_config /etc/ssh/
COPY init.sh /usr/local/bin/
	
RUN chmod u+x /usr/local/bin/init.sh
EXPOSE 5000 2222
ENTRYPOINT ["init.sh"]
