### ISSUE TITLE
[iOS] App Store publishing error #702 -still not solved.

### ISSUE THREAD

**Issue by bedro96** [Azure-Samples/cognitive-services-speech-sdk#748]
The issue has been reported on #702 but still identical error message been observed under 1.13.0.
Cx asked for a guildance as next step.

**Comment by amitkumarshukla** [comment]
@jhakulin could you please take a look at this.

**Comment by bedro96** [comment]
Hi,
 
here's the steps that our Cx took for verification and hope this will help for understanding the issue more clearly.

1. To isolate the issue, Cx tried to upload a code from our sample code, which is quickstart-swift-ios-from-microphone project from https://github.com/Azure-Samples/cognitive-services-speech-sdk instead of their own code.

2. Updated SDK from 1.12.1 to MicrosoftCognitiveServicesSpeech-iOS 1.13.0.
<img width="557" alt="attachment1" src="https://user-images.githubusercontent.com/33794164/88995989-02a87080-d327-11ea-8f59-864047cf5fd5.png">

3. Cx still facing following error messages during App Store upload. 

- Undefined symbol: _OBJC_CLASS_$_SPXSpeechRecognizer
![attachment2](https://user-images.githubusercontent.com/33794164/88996686-daba0c80-d328-11ea-807c-a57e00a1dd85.png)

Cheers,

**Comment by jhakulin** [comment]
@bedro96 armv7 is not supported in the latest speech SDK, could you use arm64 ?

**Comment by jhakulin** [comment]
@bedro96 Did using arm64 help to your issue?

**Comment by jhakulin** [comment]
@bedro96 One more follow-up before closing the ticket, please let us know if using arm64 fixed the problem ?

**Comment by bedro96** [comment]
Sorry for late response. Checking with Cx and will update the feedback soon. Thank you.

**Comment by jhakulin** [comment]
@bedro96 any updates?

**Comment by bedro96** [comment]
No update from customer. Thank you.

**Comment by bedro96** [comment]
Cx is caught up with other task at this moment and promised to come back next week. Thank you for your patience.

**Comment by pankopon** [comment]
@bedro96 Can you please provide a status update this week? Otherwise we'll close the item as resolved.

**Comment by pankopon** [comment]
Closing the issue since no update from the customer, presumed resolved. If further support is needed, please open a new issue with details.
