### ISSUE TITLE
KeywordRecognizer doesn't work with PushAudioInputStream

### ISSUE THREAD

**Issue by noxord** [Azure-Samples/cognitive-services-speech-sdk#749]
**Describe the bug**
KeywordRecognizer doesn't seem to workwith  PushAudioInputStream as input audio source. 
I used wav file as an input and tried that very same file with SpeechRecognizer with the same configuration - it worked fine., text was recognized. However it doesn't work for KeywordRecognizer. 

**To Reproduce**
1. Create PushAudioInputStream using AudioStreamFormat. (I tried 16 kHz and 8kHz 16 bits 1 channel)
2. Use created PushAudioInputStream as stream input for AudioConfig.
3. Use created AudioConfig for KeywordRecognizer.
4. Fill PushAudioInputStream with audio data.

**Expected behavior**
KeywordRecognizer should recognize a keyword in input stream. 

**Version of the Cognitive Services Speech SDK**
1.13.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - x64
 - Programming language: Java

**Comment by glharper** [comment]
@noxord Hi, thanks for opening this issue. Could you pass along the wav file, the table file, and the actual code you used?

**Comment by noxord** [comment]
Hi! Wav and table attached. The code, taken mostly from different sdk samples:
```
var keywordModel = KeywordRecognitionModel.fromFile("PATH_TO Hi_Jimmy.table");
InputStream inputStream = new FileInputStream("PATH_TO jimmy_start.wav");
PushAudioInputStream pushStream = AudioInputStream.createPushStream(AudioStreamFormat.getWaveFormatPCM(16000, (short)16, (short)1));
AudioConfig audioInput = AudioConfig.fromStreamInput(pushStream);
KeywordRecognizer keywordrecognizer = new KeywordRecognizer(audioInput);
keywordrecognizer.recognized.addEventListener((o, e) -> {
	if (e.getResult().getReason() == ResultReason.RecognizedKeyword) {
		{
			System.out.println("Recognized keyword " + e.getResult().getText());
                        //further intent recognition logic ...
		}
	}
});
keywordrecognizer.recognizeOnceAsync(keywordModel);
System.out.println("Recognizing keyword...");
{
    byte[] readBuffer = new byte[320];
    try {
    	while (inputStream.read(readBuffer) != -1) {
    		pushStream.write(readBuffer);
    	}
    } catch (IOException e) {
    	e.printStackTrace();
    }
}
pushStream.close();
audioInput.close();
keywordrecognizer.close();
keywordModel.close();
[wav_and_table.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4996018/wav_and_table.zip)

```

**Comment by jhakulin** [comment]
@noxord The problem could be related to your kws model, as I tried with kws.table model from our sample https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/java/android/keyword-recognizer-stream/app/src/main/assets, and your code works with the wav file which use "Computer" keyword ok. Please check the model has been done correctly. I'll also check the model you provided further with the keyword engine team.

**Comment by noxord** [comment]
@jhakulin Thanks for looking into it. I'm pretty sure that model and pronunciation in wav file are fine. That's because at the time I was recording the sample I was running same code with microphone input and it was recognized by keyword model just fine.
Besides I just run the test - playing wav file from the speaker and running the code above with microphone input. It was recognized, that means the wav file and the model are fine.

**Comment by jhakulin** [comment]
@noxord hmm, thanks for information, we will check the model and wav file also to see if our solution should be optimized. Your audio input sounds ok to me, audio level looks to be good etc., however I now recorded own wave file using Audacity and said "Hi Jimmy, start recording" and that works ok with your code and model. We will check why with your wave file, keyword does not get detected. You can try to record another wave file and say Hi Jimmy bit slower and/or bit louder to see if that has impact.

**Comment by noxord** [comment]
@jhakulin That's interesting. I too was using audacity for the record. I tried handful of times, thinking that maybe some format not supported (btw I didn't find info on what sample rates are supported by KeywordRecognizer), tried to increase volume levels, strip header from wav file and so on. I'll try to make new samples. Thank you!

**Comment by jhakulin** [comment]
@noxord Format in your file, 16kHz, mono PCM is supported, Our docs mention that as default format  
https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.audio.pushaudioinputstream.-ctor?view=azure-dotnet#Microsoft_CognitiveServices_Speech_Audio_PushAudioInputStream__ctor
But I agree we could describe the support clearer for all supported formats and features.

For your testing, you can try to say "Hi Jimmy" bit slower and see if that impacts to result.
Thanks

**Comment by noxord** [comment]
@jhakulin I've been able to record a sample what is working alright with the code above. I had to be very loud and clear, I guess it's volume level in wav file after all, though increasing volume with audacity for the previous sample did not yield results. Thank you for the help, I'm closing the issue.

**Comment by jhakulin** [comment]
@noxord  We analyzed the clip more and we have identified an issue there if keyword is early in the wav file, it will not be detected. We plan to fix on the next Speech SDK release. Thanks for reporting the issue!
