### ISSUE TITLE
[iOS] SPXPushAudioInputStream doesn't work

### ISSUE THREAD

**Issue by Sleepingbug** [Azure-Samples/cognitive-services-speech-sdk#75]
I write a class named MSAudioStream inherited from SPXPushAudioInputStream 
and call the method   -(void)write:(NSData*)data in a thread,
like this: [self write:data]; 
the data is read from microphone  and I'm sure data is OK because I save these data in a WAV file( 16K,16bits) and the wav file is OK.

here is part of my code:

MSAudioStream* stream = [ MSAudioStream new];
SPXAudioConfiguration* audioCfg = [[ SPXAudioConfiguration alloc] initWithStreamInput: stream ];
SPXSpeechConfiguration* speechCfg = [[ SPXSpeechConfiguration alloc] initWithSub.....

**Comment by zhouwangzw** [comment]
For SPXPushAudioInputStream, you do not need to create your own class. Instead, you just need to read data from source and directly write data to stream. Please refer to #74 for some code samples. We are working on more samples for audio input streams. 

Thanks,

**Comment by Sleepingbug** [comment]
Thanks you very much! It works well

**Comment by p710041025** [comment]
SPXAudioConfiguration* weatherAudioSource = [[SPXAudioConfiguration alloc] initWithWavFileInput:weatherFile];
I received the weatherAudioSource is always nil in this HelloWorld Demo

**Comment by chlandsi** [comment]
@p710041025 : Please check that the path to the audio file is valid (`NSLog(@"weatherFile path: %@", weatherFile);`, and that the file is present. If the problems remain, please open a new issue.
