### ISSUE TITLE
Python sample for Conversation Transcription

### ISSUE THREAD

**Issue by olegrod** [Azure-Samples/cognitive-services-speech-sdk#750]
Hello,

Would it be possible to share some examples of Python code to implement Conversation Transcription
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/conversation-transcription

Thanks in advance,
Oleg

**Comment by glharper** [comment]
Hi Oleg,
Conversation Transcription is currently not supported in the Python version of the SDK. Support is planned for a future release, and we will include samples once that support is added.
