### ISSUE TITLE
Cannot set speech synthesis output format to opus via python sdk

### ISSUE THREAD

**Issue by sakethpo** [Azure-Samples/cognitive-services-speech-sdk#753]
**Describe the bug**
I cannot set speech synthesis output format to opus when using python sdk.

**To Reproduce**
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_synthesis_sample.py#L150

^ This line in the sample file and the corresponding http link in there (to rest-text-to-speech#audio-outputs) say that I should be able to set the output format to opus (ogg-24khz-16bit-mono-opus). 

However, it was not to be found when I tried browsing the python sdk (https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.speechsynthesisoutputformat?view=azure-python). 

Strangely, I did find an enum in javacript sdk though (https://docs.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/speechsynthesisoutputformat?view=azure-node-latest).

**Expected behavior**
I was hoping there'd be a way in python sdk to set the speech synthesis output format to opus, just like javascript.

**Version of the Cognitive Services Speech SDK**
1.13.0

**Platform, Operating System, and Programming Language**
 - OS: Ubuntu 18.04
 - Hardware - x86_64
 - Programming language: Python

**Comment by yulin-li** [comment]
Hi @sakethpo 

Thanks for reaching out. Unfortunately, the python SDK doesn't support setting opus format for now. We will support it in version 1.14, which is supposed to be released late this month. I was trying to find a workaround but I failed. You can use the sample python codes to call rest api for now.

**Comment by sakethpo** [comment]
@yulin-li thanks! will use rest api for now. waiting for 1.14 sdk

**Comment by yulin-li** [comment]
@sakethpo Thanks! Just FYI, the code for this feature is finished now, so it will be certainly release with version 1.14 😄
