### ISSUE TITLE
Unable to run intent recognizer sample in australiaeast region

### ISSUE THREAD

**Issue by jamescarpinter** [Azure-Samples/cognitive-services-speech-sdk#755]
**Describe the bug**
The .NET Core console intent recognizer sample ($/samples/csharp/dotnetcore/console/samples) fails when using a LUIS model provisioned in the Australia region (with an australiaeast prediction key). The error message returned is:

CANCELED: Reason=Error
CANCELED: ErrorCode=ConnectionFailure
CANCELED: ErrorDetails=Connection failed (no connection to the remote host). Internal error: 1. Error details: 11001. Please check network connection, firewall setting, and the region name used to create speech factory. SessionId: 1e4c42181eae45a0a5e12d749a659943
CANCELED: Did you update the subscription info?

The same sample works fine when:
* Using a LUIS model created in the US region (with a westus2 prediction key).
* Manually specifying the host name (i.e. instead of using `SpeechConfig.FromSubscription`, using `SpeechConfig.FromHost(new Uri("wss://australiaeast.sr.speech.microsoft.com"), "<my key here>");`).

**To Reproduce**
1. Create a new model at https://au.luis.ai and attach a prediction key from the australiaeast region.
2. Update the `ContinuousRecognitionWithFileAsync` method in the intent_recognition_samples.cs file with the new LUIS model ID, prediction key, and region.
3. Run the sample and select option "D" when prompted.

N.B. the sample runs successfully when using a model created at https://luis.ai and run with a prediction key in the westus2 region.

**Expected behavior**
Speech is correctly recognized as text and matched to a LUIS intent.

**Version of the Cognitive Services Speech SDK**
1.13.0 (as referenced by sample code)

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - Windows 10 (also repros on macOS & Android+Unity)
 - Hardware - x64
 - Programming language: C#
 - Browser [e.g. Chrome, Safari] (if applicable) - N/A

**Additional context**
 - If Fiddler is running, and the sample updated to specify it as the proxy, it appears that the SDK tries to connect to "eastaustralia.sr.speech.microsoft.com". This causes a DNS resolution failure. I have confirmed that there is no reference to eastaustralia in my code and that the region is being correctly passed as australiaeast.

**Comment by lisaweixu** [comment]
This will be fixed in the next release of the SDK. Thanks for reporting this. Good catch. You have found a workaround, fromhost.
