### ISSUE TITLE
Response ErrorCode 5 on Android SDK

### ISSUE THREAD

**Issue by jzhw0130** [Azure-Samples/cognitive-services-speech-sdk#759]
**Describe the bug**
Sometimes `recognizing` and `recognized` is not triggered after call `startContinuousRecognitionAsync`. 
BTW, `sessionStarted` is triggered correctly.

In this case, I checked the azure audio log, it says:
```
  (200): 5097336ms SPX_TRACE_ERROR:  usp_reco_engine_adapter.cpp:1839 Response: On Error: Code:5, Message: 
  Connection failed (no connection to the remote host). Internal error: 1. Error details: 792. Please check network connection, 
  firewall setting, and the region name used to create speech factory..
```
or 
```
  (32): 450168ms SPX_TRACE_ERROR:  usp_reco_engine_adapter.cpp:1839 Response: On Error: Code:5, Message: 
  Connection failed (no connection to the remote host). Internal error: 1. Error details: 7. Please check network connection, 
  firewall setting, and the region name used to create speech factory..
```
BTW, I enable the audio log by setting : ` config.setProperty(PropertyId.Speech_LogFilename, logFile);  `

Please check the attached azure logs, thx
I tested 3 times, 1st works, 2nd does not work, 3rd works again.

**To Reproduce**
1. `speechRecognizer = new SpeechRecognizer()`
2. `speechRecognizer.startContinuousRecognitionAsync()`
3. speak some words
4. `speechRecognizer.stopContinuousRecognitionAsync()`
5. repeat step 1 - 4

**Expected behavior**
Every time speech service works

**Version of the Cognitive Services Speech SDK**
1.13.0

**Platform, Operating System, and Programming Language**
 - OS: Android 9
 - Hardware - ARM
 - Programming language: Java

**Additional context**
[FIRST - 2020-08-08 16_22_53 -azure-speech-audio.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/5044958/FIRST.-.2020-08-08.16_22_53.-azure-speech-audio.txt)
[SECOND - 2020-08-08 16_23_02 -azure-speech-audio.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/5044956/SECOND.-.2020-08-08.16_23_02.-azure-speech-audio.txt)
[THIRD - 2020-08-08 16_24_22 -azure-speech-audio.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/5044957/THIRD.-.2020-08-08.16_24_22.-azure-speech-audio.txt)

**Comment by jzhw0130** [comment]
Moreover, seems the key word is : 
```
  (200): 5097335ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  web_socket.cpp:784 WS open operation failed with 
  result=1(WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED), code=792[0x00000318]

```

**Comment by glecaros** [comment]
Hi, can you share the a snippet of code with a bit more details on what you are doing?

**Comment by jzhw0130** [comment]
@glecaros 

sure, refer to the following code:

```
    private void startRecognition() {
        closeSpeechRecognizerIfNeed();
        createSpeechRecognizer();
        speechRecognizer.startContinuousRecognitionAsync();
    }

    private void stopRecognition() {
        if (speechRecognizer != null) {
            try {
                speechRecognizer.sessionStarted.removeEventListener(sessionStartedHandler);
                speechRecognizer.recognizing.removeEventListener(recognizingHandler);
                speechRecognizer.recognized.removeEventListener(recognizedHandler);
                new Timer().schedule(new TimerTask() {
                    @Override
                    public void run() {
                        try {
                            if (speechRecognizer != null) {
                                speechRecognizer.stopContinuousRecognitionAsync().get();
                            }
                        } catch (Exception e) {
                    }
                }, 0);
            } catch (Exception e) {}
        }
    }

    private void closeSpeechRecognizerIfNeed() {
        try {
            if (speechRecognizer != null) {
                speechRecognizer.stopContinuousRecognitionAsync();
            }
        } catch (Exception e) {}
    }


    private void createSpeechRecognizer() {
        SpeechConfig config = SpeechConfig.fromSubscription(speechSubscriptionKey, serviceRegion);
        config.setProperty(PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs, "5000");
        speechRecognizer = new SpeechRecognizer(config, preferredLanguage);
        speechRecognizer.sessionStarted.addEventListener(sessionStartedHandler);
        speechRecognizer.sessionStopped.addEventListener(sessionStoppedHandler);
        speechRecognizer.canceled.addEventListener(canceledHandler);
        speechRecognizer.recognizing.addEventListener(recognizingHandler);
        speechRecognizer.recognized.addEventListener(recognizedHandler);
        speechRecognizer.speechStartDetected.addEventListener(speechStartDetectedHandler);
        speechRecognizer.speechEndDetected.addEventListener(speechEndDetectedHandler);
    }

```

**Comment by glecaros** [comment]
Hi, it seems your closeSpeechRecognizerIfNeed is not really closing the recognizer. You should .get() on the operation and also call .close() on the recognizer (since you won't reuse it)

**Comment by jzhw0130** [comment]
@glecaros 

That's not the case. 
Even though I did  as you said before, the issue still occured.
The reason I didn't call `.close()` is the api is buggy. 
Refer to : 
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/696

**Comment by pankopon** [comment]
Closing this as we now have a work item for this issue on the backlog to be prioritized and planned. We'll update with information about the release schedule when known.
