### ISSUE TITLE
SDK for Xamarin Android and Xamarin IOS

### ISSUE THREAD

**Issue by shiningazure** [Azure-Samples/cognitive-services-speech-sdk#76]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> NaN

### Any log messages given by the failure
> NaN

### Expected/desired behavior
> NaN

### OS and Version?
> IOS 12

### Versions
> Any Version

### Mention any other details that might be useful
Is there any SDK for xamarin ios and xamarin android? Because it seems not possible to use the C# Version for them at the moment (The only available C# is windows)

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/
> ---------------------------------------------------------------

**Comment by wolfma61** [comment]
it is going to happen ;) 
unfortunately no ETA - there is going to be support for more platforms and languages..., more Linux, Android support (x86 etc), and additional support for MacOS and iOS
