### ISSUE TITLE
SPXERR_GSTREAMER_NOT_FOUND_ERROR when using mp3 file with Microsoft.CognitiveServices.Speech

### ISSUE THREAD

**Issue by kedzior-io** [Azure-Samples/cognitive-services-speech-sdk#764]
I have this piece of code throwing the error in the title:

```
using (var audioInput = AudioConfig.FromStreamInput(new PullAudioInputStream(new BinaryAudioStreamReader(new BinaryReader(File.OpenRead(audioFile))), AudioStreamFormat.GetCompressedFormat(AudioStreamContainerFormat.MP3))))
using (var recognizer = new SpeechRecognizer(config, sourceLanguageConfig, audioInput))
```
audioFile is the path to mp3 file with audio to transcribe.

I have installed the latest GStreamer gstreamer-1.0-msvc-x86_64-1.17.2.msi for Windows and added it to the User's PATH and set GSTREAMER_ROOT_X86. That did not work.

In the docs here https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams?tabs=debian&pivots=programming-language-csharp

> Handling compressed audio is implemented using GStreamer. For licensing reasons GStreamer binaries are not compiled and linked with the Speech SDK. Developers need to install several dependencies and plugins, see Installing on Windows. Gstreamer binaries need to be in the system path, so that the speech SDK can load gstreamer binaries during runtime. If speech SDK is able to find libgstreamer-1.0-0.dll during runtime it means the gstreamer binaries are in the system path.

It says it will look for libgstreamer-1.0-0.dll which is no longer included in the latest version (1.17.2) so I went back to gstreamer-1.0-x86-1.14.1 which does have the required dll, but still getting the same error.

From Visual Studio 2019 console I can invoke exe files included in that folder so I know the PATH is set correctly.

What am I missing?

**Comment by amitkumarshukla** [comment]
You need to set GSTREAMER_ROOT_X86_64 not GSTREAMER_ROOT_X86.

Could you try opening a new command prompt and run the following and see if you are getting a correct version. Which will help you to find if your installation path is there in the system path.
gst-inspect-1.0.exe --version

Also when you are building the solution from visual studio make sure instead of anyCpu choose x64 configuration. Do let us know if that solves your problem.

**Comment by kedzior-io** [comment]
Thanks!

Did fresh install of **gstreamer-1.0-msvc-x86_64-1.17.2.msi** 

![image](https://user-images.githubusercontent.com/40808369/90123332-ecef6e00-dd5e-11ea-8d12-e56b2807e1cf.png)

Still the same. 

Checking **gstreamer-1.0-x86-1.14.1**

**Comment by kedzior-io** [comment]
**That did it:**

[gstreamer-1.0-x86_64-1.14.5.msi
](https://gstreamer.freedesktop.org/pkg/windows/1.14.5/gstreamer-1.0-x86_64-1.14.5.msi)

![image](https://user-images.githubusercontent.com/40808369/90124351-89fed680-dd60-11ea-8c9f-d8151b8395e5.png)

So seems like an issue with the latest version of GStreamer. You guys should maybe mention it in the docs here: [https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams?tabs=debian&pivots=programming-language-csharp](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams?tabs=debian&pivots=programming-language-csharp
)
Thanks for help!

**Comment by kedzior-io** [comment]
Another quick question:
How do I make ti work in Azure Function? 😃

**Comment by amitkumarshukla** [comment]
Currently we have known issue running speech SDK inside azure functions. For a workaround please follow the thread https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/437#issuecomment-622592123

**Comment by vortex1024** [comment]
I have the same issue, I did evetything outlined here, but to no avail. Used gstreamer 1.14 x64, set build to x64, the binaries are in path:
WARNING: no real random source present!
gst-inspect-1.0 version 1.14.5
GStreamer 1.14.5
Unknown package origin
the root variable is also defined, both as user and system variable.
Anything else? Has the required gstreamer version changed? I use speech sdk 1.16.
thanks.

**Comment by kedzior-io** [comment]
@vortex1024 

Try `Microsoft.CognitiveServices.Speech` version `1.13.0`

Here is my working sample:  

Packages:

```
<PackageReference Include="CommandLineParser.Core" Version="1.0.1" />
<PackageReference Include="Microsoft.CognitiveServices.Speech" Version="1.13.0" />
```

Program:

```
using System;
using System.IO;
using CommandLineParser.Core;
using Microsoft.CognitiveServices.Speech;
using Microsoft.CognitiveServices.Speech.Audio;
using System.Threading.Tasks;
using MicrosoftSpeechSDKSamples;

namespace GetTextFromMp3
{
    internal class Program
    {
        private static async System.Threading.Tasks.Task Main(string[] args)
        {
            var parser = new FluentCommandLineParser<ApplicationArguments>();

            parser.Setup(arg => arg.File)
                .As('f', "file");

            var result = parser.Parse(args);

            if (result.HasErrors)
            {
                Console.WriteLine(result.ErrorText);
                return;
            }

            if (!File.Exists(parser.Object.File))
            {
                Console.WriteLine("Option 'f:file' error. File doesn't exist.");
                return;
            }

            var audioFile = parser.Object.File

            var textFile = Path.ChangeExtension(audioFile, "txt");
            var sourceLanguageConfig = SourceLanguageConfig.FromLanguage("es-ES");
            var config = SpeechConfig.FromSubscription("YourAzureSubscriptionKey", "EastUS");

            var stopRecognition = new TaskCompletionSource<int>();

            using (var audioInput = AudioConfig.FromStreamInput(new PullAudioInputStream(new BinaryAudioStreamReader(new BinaryReader(File.OpenRead(audioFile))), AudioStreamFormat.GetCompressedFormat(AudioStreamContainerFormat.MP3))))
            using (var recognizer = new SpeechRecognizer(config, sourceLanguageConfig, audioInput))
            {
                recognizer.Recognized += (s, e) =>
                {
                    if (e.Result.Reason == ResultReason.RecognizedSpeech)
                    {
                        Console.WriteLine($"RECOGNIZED: Text={e.Result.Text}");
                        File.AppendAllText(textFile, e.Result.Text + Environment.NewLine);
                    }
                    else if (e.Result.Reason == ResultReason.NoMatch)
                    {
                        Console.WriteLine($"NOMATCH: Speech could not be recognized.");
                    }
                };

                recognizer.Canceled += (s, e) =>
                {
                    Console.WriteLine($"CANCELED: Reason={e.Reason}");

                    if (e.Reason == CancellationReason.Error)
                    {
                        Console.WriteLine($"CANCELED: ErrorCode={e.ErrorCode}");
                        Console.WriteLine($"CANCELED: ErrorDetails={e.ErrorDetails}");
                        Console.WriteLine($"CANCELED: Did you update the subscription info?");
                    }

                    stopRecognition.TrySetResult(0);
                };

                recognizer.SessionStopped += (s, e) =>
                {
                    Console.WriteLine("\n    Session stopped event.");
                    stopRecognition.TrySetResult(0);
                };

                Console.WriteLine("Recognizing text");
                await recognizer.StartContinuousRecognitionAsync();

                Task.WaitAny(new[] { stopRecognition.Task });

                await recognizer.StopContinuousRecognitionAsync();
            }
        }
    }
}
```

BinaryAudioStreamReader class is taken from here:

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/helper.cs

Run: 

`GetTextFromMp3 -f C:\\example.mp3`

**Comment by vortex1024** [comment]
@kedzior-io, thanks, this way it works perfectly!
@amitkumarshukla, this really should be documented somewhere. Playing with gstreamer and speech sdk versions is not ffun. :)

**Comment by DanielcomerNHS** [comment]
the way i fixed this... 

use version 1.14.5 of Gstreamer https://gstreamer.freedesktop.org/pkg/windows/1.14.5/gstreamer-1.0-x86_64-1.14.5.msi - complete setup

use version 1.13 of Microsoft.CognitiveServices.Speech (Nuget package)

Go to environment variables on your pc and add to the User variable called path the following C:\gstreamer\1.0\x86_64\bin

then add a system variable called "GSTREAMER_ROOT_X86_64" (without the quotes) and the value to "C:\gstreamer\1.0\x86_64"

you may need to reboot if still having issues. but this is now working for me.

**Comment by jhakulin** [comment]
Thanks for comments, I reopen the issue as we need to improve the documentation here

**Comment by QC-Technology** [comment]
hi guys, while we are looknig at improving documentation, i'm trying to use this for a .net core C# console project which i want to host as a continious webjob at some point in the near future.
the .WAV conversion is working perfectly, however the mp3 is not for the same above reason.

can i ask to have clear simple steps for .net core implementation of GStreamer which i can package publish and use as a stand alone ... i.e. in a webapp continious webjob ?

cheers

**Comment by kedzior-io** [comment]
@QC-Technology 
The example above works perfectly passing mp3 files and using Gstreamer: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/764#issuecomment-813906143

**Comment by luismaiaDEVSCOPE** [comment]
Update: You should use https://gstreamer.freedesktop.org/data/pkg/windows/1.18.3/mingw/gstreamer-1.0-mingw-x86_64-1.18.3.msi as is at the moment.

**Comment by jpalo** [comment]
What about now? What version to use with Microsoft.CognitiveServices.Speech 1.34.1?

**Comment by onionhammer** [comment]
What about now?

**Comment by 7oaker** [comment]
@amritp-deepinfinityai  same issue. Still no solution
