### ISSUE TITLE
KeywordRecognitionResult has incorrect Offset and Duration values.

### ISSUE THREAD

**Issue by noxord** [Azure-Samples/cognitive-services-speech-sdk#766]
**Describe the bug**
KeywordRecognitionResult has incorrect Offset and Duration values.

**To Reproduce**
1. Execute the code with provided wav file and keyword model. Check returned values for Offset and Duration of KeywordRecognitionResult.
2. Inspect wav file in Audacity and check real offset and duration of keyword.

**Expected behavior**
KeywordRecognitionResult should return correct offset and duration values.

**Version of the Cognitive Services Speech SDK**
1.13.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - x64
 - Programming language: Java

**Additional context**
Results are off about x2, so one may thought that wav setting of PushAudioInputStream are incorrect, but they are correct and match wav file. Using exactly same PushAudioInputStream with same file and audio settings for SpeechRecognizer returns correct results.
KeywordRecognitionResult: Offset: 2265, Duration: 1495
SpeechRecognitionResult : Offset: 1340, Duration: 690
Actual rough timings: Offset: 1407, Duration: 500

The code:
```
var keywordModel = KeywordRecognitionModel.fromFile("PATH_TO Hi_Jimmy.table");
InputStream inputStream = new FileInputStream("PATH_TO jimmy_start.wav");
PushAudioInputStream pushStream = AudioInputStream.createPushStream(AudioStreamFormat.getWaveFormatPCM(16000, (short)16, (short)1));
AudioConfig audioInput = AudioConfig.fromStreamInput(pushStream);
KeywordRecognizer keywordrecognizer = new KeywordRecognizer(audioInput);
keywordrecognizer.recognized.addEventListener((o, e) -> {
	if (e.getResult().getReason() == ResultReason.RecognizedKeyword) {
		{
			System.out.println("Recognized keyword " + e.getResult().getText());
                        System.out.println("Offset: " + e.getResult().getOffset().longValue() /10000 + ", Duration: " + e.getResult().getDuration().longValue() /10000);
		}
	}
});
keywordrecognizer.recognizeOnceAsync(keywordModel);
System.out.println("Recognizing keyword...");
{
    byte[] readBuffer = new byte[320];
    try {
    	while (inputStream.read(readBuffer) != -1) {
    		pushStream.write(readBuffer);
    	}
    } catch (IOException e) {
    	e.printStackTrace();
    }
}
new Scanner(System.in).nextLine();
pushStream.close();
audioInput.close();
keywordrecognizer.close();
keywordModel.close();
```
[wav_and_table.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/5069434/wav_and_table.zip)

**Comment by amitkumarshukla** [comment]
@glecaros Could you please look into it.

**Comment by pankopon** [comment]
To update: Based on our initial investigation the current behavior is due to limitations of the keyword recognition engine that cannot accurately estimate the start time of the keyword, instead it returns the end time minus a constant 1.5 seconds. We have added a work item about it to the backlog so I'm closing this issue now, we'll provide an update once we know which Speech SDK release will contain a fix.

**Comment by ShrivastavaAkash** [comment]
Hi, I'm also getting the same duration (1.495 seconds) almost every time a keyword is recognized. I'm using Cognitive Services Speech SDK 1.15.0. 
Do we know yet which release would fix this?
