### ISSUE TITLE
Improve Saving APIs

### ISSUE THREAD

**Issue by Ziugy** [Azure-Samples/cognitive-services-speech-sdk#769]
**Is your feature request related to a problem? Please describe.**
Yes, my feature request is related to an issue I ran into while trying to cache audio coming back to disk.

I followed other recommendations in closed issues for saving an audio file, like so:
```csharp
SpeechConfig speechConfig = SpeechConfig.FromSubscription(key, region);
speechConfig.SetSpeechSynthesisOutputFormat(SpeechSynthesisOutputFormat.Raw24Khz16BitMonoPcm);
SpeechSynthesisResult synthesisResult = await synthesizer.SpeakTextAsync(speechToSynthesize);
using (AudioDataStream stream = AudioDataStream.FromResult(synthesisResult))
{
    await stream.SaveToWaveFileAsync(filePath);
}
```

Now, the code above does save an audio file. The issue is that the audio file isn't a wave file, but a raw audio file because of the output format I've selected, `SpeechSynthesisOutputFormat.Raw24Khz16BitMonoPcm`.

**Describe the solution you'd like**
There's a couple solution that I think might be reasonable with various pros and cons, so here they are:
- `SaveToWaveFileAsync` throws and exception is header info isn't provided and other methods are created like `SaveToRawFileAsync` and `SaveToMP3Async`. While this increases the number of methods, the end result is expected.
- My personal preference is supplying the `SaveToWaveFileAsync` the `SpeechSynthesisOutputFormat`. This could be added into `SpeechSynthesisResult` or a new method is created if there's concerns of APIs breakage. If this is done `SaveToFileAsync` would be a better name.

**Describe alternatives you've considered**
My working solution is that I've ended up writing the wave file myself.

After writing this up I did have a thought that perhaps `AudioDataStream.FromResult` does the processing of header files for us, so perhaps I'm able to swap to alternate output formats and use `SaveToWaveFileAsync`. Regardless, I still think saving was unclear as to what's happening and should be improve or further documented.

**Additional context**
I've integrated the Cognitive Speech SDK into Unity and I'm using the raw format as that's the easiest to convert to Unity's [audio data format](https://docs.unity3d.com/ScriptReference/AudioClip.GetData.html) and avoids needing to read the audio file headers to process the audio data. I'll be testing  `AudioDataStream.FromResult` to see how that data comes back with headers in the result.

**Comment by yulin-li** [comment]
@Ziugy Thank you very much for this proposal. The current `SaveToWaveFileAsync()` acutually saves the audio file using the `SpeechSynthesisOutputFormat` in speech config, instead of a `wav` format. We plan to update `SaveToWaveFileAsync()` with a format parameter, just like your proposal.

For you scenario, I suggest you using a Riff format, you can cut the header (46 Bytes) to get the raw audio, and it will save a wav format audio file.

**Comment by amitkumarshukla** [comment]
Please follow the workaround and keep checking our future release notes.
