### ISSUE TITLE
gradle always downloads aar file (no android!)

### ISSUE THREAD

**Issue by tarantelklient** [Azure-Samples/cognitive-services-speech-sdk#77]
Hey there,

I want to include the Microsoft Speech SDK into my gradle project. It should run on linux.

### This issue is for a: (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
* Create a gradle project
* Set repo and dep like this (converted from maven to gradle)
```
repositories {
    maven {
        url "https://csspeechstorage.blob.core.windows.net/maven"
    }
}
dependencies {
    implementation "com.microsoft.cognitiveservices.speech:client-sdk:1.0.1"
}
```
* Try to use sample code
* --> Package `com.microsoft.cognitiveservices.speech` is not available

### Any log messages given by the failure
Could not find `com.microsoft.cognitiveservices.speech`

### Expected/desired behavior
Download .jar file instead of the .aar file

### OS and Version?
Ubuntu 18.04

### Versions
> 1.0.1

### Mention any other details that might be useful
It seems like gradle always downloads the aar file. 

Thank you very much! :)
Best regards

**Comment by fmegen** [comment]
Thanks for reporting this issue!
I will take a look-

**Comment by fmegen** [comment]
I have verified that the jar file is indeed in our maven repository

Please note that we currently only support Ubuntu 16.4, not yet 18.4. Could you please retest on 16.4?

kind regards
 friedel

**Comment by tarantelklient** [comment]
Hey fmegen,

i set up an Ubuntu 16.04 and tried it again with the same result. This time I checked the files downloaded by gradle:
https://csspeechstorage.blob.core.windows.net/maven/com/microsoft/cognitiveservices/speech/client-sdk/1.0.1/client-sdk-1.0.1.pom
In this pom is only a aar file.

Thank you for answere :)
Best regards

**Comment by tarantelklient** [comment]
hey @fmegen 

thank you really much for your effort! 
After long period of failures I found a workaround for gradle. It is possible to declare an extension for the dependency:

```
dependencies {
    implementation group: 'com.microsoft.cognitiveservices.speech', name: 'client-sdk', version: "1.0.1", ext: "jar"
}
```

Best regards

**Comment by wolfma61** [comment]
thank you for posting the work-around ... closing for now

**Comment by wildunne** [comment]
👍 this issue still exists, the workaround works but it took me quite a lot of searches for the issue to find this.

For me this was happening on gradle 5 with Intellij 2018.3

**Comment by fmegen** [comment]
Hi @wildunne,
thanks a lot for reporting this.
we will update our documentation for the java quickstart to reflect this issue

**Comment by AndreasVolkmann** [comment]
Also hit this one. Please add this to the readme for discoverability.

**Comment by wimvanhouts** [comment]
> hey @fmegen
> 
> thank you really much for your effort!
> After long period of failures I found a workaround for gradle. It is possible to declare an extension for the dependency:
> 
> ```
> dependencies {
>     implementation group: 'com.microsoft.cognitiveservices.speech', name: 'client-sdk', version: "1.0.1", ext: "jar"
> }
> ```
> 
> Best regards

Please update the docu with this solution since it will save a lot of people a lot of time...

**Comment by harrydhillon43** [comment]
This is still an issue
