### ISSUE TITLE
not able to login with speech studio in windows 

### ISSUE THREAD

**Issue by chintansoni22** [Azure-Samples/cognitive-services-speech-sdk#770]
**Describe the bug**
I have created free account and azure and speech studio is not opening in my windows

**To Reproduce**
not able to login
![speech](https://user-images.githubusercontent.com/50165497/90341286-f3f6d480-e01b-11ea-84d8-cbe1b325895b.png)

**Comment by amitkumarshukla** [comment]
@chintansoni22 Sorry for the inconvenience caused. Could you please try today as see if it works for you. If not, could you please send us your location and we will see what is going wrong on your site.

**Comment by amitkumarshukla** [comment]
I am closing this, please feel free to reopen if you still see the issue.
