### ISSUE TITLE
Android/Java : Unable to pause or stop Text To Speech sound playing

### ISSUE THREAD

**Issue by manideeppabba1991** [Azure-Samples/cognitive-services-speech-sdk#771]
In Android app, Whenever there is a long text that is being spoken by SpeechSynthesizer using "SpeakTextAsync" method, There is no way to pause or stop the audio.

"SpeechSynthesizer.close()" or any other close() methods do not work. If you try to call close() method while SpeechSynthesizer is speaking, it will crash the app and error out saying "All resources are not disposable as some of them are still in use"

**To Reproduce**
1. Using the (Text to speech) Quickstart app for android from Git hub, try to give the "SpeakTextAsync" method a very big paragraph to read
2. Now try to pause or stop the audio while the SpeechSynthesizer is reading out.

**Expected behavior**
There should be a way to pause or stop the audio in Android/Java

**Version of the Cognitive Services Speech SDK**
implementation 'com.microsoft.cognitiveservices.speech:client-sdk:1.12.1'

**Platform, Operating System, and Programming Language**
 - OS: Android
 - Programming language: Java/Kotlin

**Comment by yulin-li** [comment]
Hi @manideeppabba1991 , thanks for reaching out.

We will support stopping the synthesis in version 1.14, which will be released around the end of this month.

**Comment by manideeppabba1991** [comment]
@yulin-li Thanks for the update. I will be waiting for the release.

**Comment by yulin-li** [comment]
@manideeppabba1991 we are closing this issue now. Feel free to re-open it if you have any questions.

**Comment by manideeppabba1991** [comment]
@yulin-li I still do not see version 1.14 available on [Release Notes](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/releasenotes)

**Comment by manideeppabba1991** [comment]
@yulin-li I still do not see version 1.14 available on https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/releasenotes

**Comment by yulin-li** [comment]
@manideeppabba1991 sorry, the release was delayed.
