### ISSUE TITLE
Exception with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED) in azure function (windows)

### ISSUE THREAD

**Issue by ductranit** [Azure-Samples/cognitive-services-speech-sdk#773]
My project can work well when I run on windows local in visual studio. But when I deploy into azure function (windows), I got this exception:
```
Exception with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED)
```
I wonder whether the machine host doesn't have microphone (I use text to speech api but only generate audio file) or it can't load the certificate file (relate to [this issue](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/442) on linux) causing it? 
Here is my .csprj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.9" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.5.0" />
    <PackageReference Include="Microsoft.CognitiveServices.Speech" Version="1.13.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```
**Version of the Cognitive Services Speech SDK**
1.13.0

**Platform, Operating System, and Programming Language**
 - OS: windows 
 - Hardware - x86,
 - Programming language: C#

**Comment by amitkumarshukla** [comment]
@ductranit Could you please provide your sample to repro the issue.

**Comment by amitkumarshukla** [comment]
This is a known issue, but you can follow this to work around your problem https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/437#issuecomment-622592123.
