### ISSUE TITLE
Firefox on Android Keeps Asking For Permission When Calling GetUserMedia

### ISSUE THREAD

**Issue by roperjonathan** [Azure-Samples/cognitive-services-speech-sdk#774]
I'm having an issue where when using Firefox on Android, every time I want to open the microphone I have to give permission. 

Is this expected behaviour within Firefox on Android? If so, then is there a way I can get around it? For example, could I "mute" the microphone rather than turning it off?

**Comment by glharper** [comment]
From [https://support.mozilla.org/en-US/kb/how-firefox-android-use-permissions-it-requests](https://support.mozilla.org/en-US/kb/how-firefox-android-use-permissions-it-requests): Firefox will always display a message asking for permission each time a site asks to add a photo or record audio. It never records audio, takes pictures or records video unless you opt-in each time it asks.

**Comment by pankopon** [comment]
Closed the item as resolved.
