### ISSUE TITLE
ApiException: (401) Reason: Unauthorized

### ISSUE THREAD

**Issue by blee300** [Azure-Samples/cognitive-services-speech-sdk#775]
Hi community,

I am following the tutorial "How to use the Speech Services Batch Transcription API from Python" (see: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python).

After following all the steps (downloading the "cognitive-services-speech-sdk', moving the 'python-client-generated' -from swagger- file in that folder) and changing my Subscription key, service region and blob uri I receive the following error:

ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Content-Length': '133', 'Content-Type': 'text/plain; charset=utf-8', 'Expires': '-1', 'Server': 'Microsoft-IIS/10.0', 'X-Powered-By': 'ASP.NET', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Date': 'Wed, 19 Aug 2020 06:42:48 GMT'})
HTTP response body: {"code":"Unauthorized","details":null,"message":"Authentication is required to access the resource.","target":null,"innerError":null}

Anyone ideas how I can solve this (or what I am doing wrong?).

Many thanks in advance!

**Comment by chlandsi** [comment]
Hi @blee300, are you using a free (F0 tier) subscription key? The batch functionality is only available with a paid (S0 tier) subscription key.

**Comment by blee300** [comment]
Oh, yes I was using the free (F0 tier) subscription key. I did switch to S0 tier and still it's not transcribing. I am not sure what I am doing wrong... could you please help?

I get result of this:

> Transcriptions status: completed (this transcription): False, 0 running, 1 not started yet
> Transcriptions status: completed (this transcription): False, 0 running, 1 not started yet
> Transcriptions status: completed (this transcription): False, 1 running, 0 not started yet
> Transcriptions status: completed (this transcription): False, 1 running, 0 not started yet
> Transcriptions status: completed (this transcription): False, 1 running, 0 not started yet
> Transcriptions status: completed (this transcription): False, 1 running, 0 not started yet
> Transcription failed :The recordings URI is invalid..
> Transcriptions status: completed (this transcription): True, 0 running, 0 not started yet
> Press any key...

**Comment by chlandsi** [comment]
Hi @blee300, can you share the link that you were using? Please also post the transcription id, region and time of request (all should be contained in the output of the sample code).

**Comment by pankopon** [comment]
@blee300 Is this still a valid issue for you? Please update with the requested information.

**Comment by trrwilson** [comment]
Standard text: to keep our active issues list fresh, we'll consider an issue resolved after 14 days of inactivity [here, already elapsed]. If this was premature, please open another issue (feel free to reference this one) and we'll investigate. Thank you!
