### ISSUE TITLE
Text to Speech Audio volume getting decreased after config the Speech to text

### ISSUE THREAD

**Issue by Selvaraj314** [Azure-Samples/cognitive-services-speech-sdk#776]
**Describe the bug**
Text to Speech Audio volume getting decreased after config the Speech to text

**To Reproduce**
1. Text to speech config.
SPXSpeechConfiguration
SPXSpeechSynthesizer
SPXSpeechSynthesisResult
2. Speech to Text(From microphone) config.
SPXSpeechConfiguration
SPXSpeechRecognizer
SPXSpeechRecognitionResult
First, I called **Text to Speech** config for speech some text -> After I have configured the **Speech to Text(from the microphone)**.
After the above step, if I called Text to speech means, the audio volume is getting decreased.

**Comment by yulin-li** [comment]
@Selvaraj314 Thanks for reaching out. We will investigate this issue. As a workaround, you can control the playback by your self now.

**Comment by jhakulin** [comment]
@Selvaraj314 Which platform you are using, Windows, Linux, Android, iOS, Mac ?

**Comment by Selvaraj314** [comment]
iOS(Swift) @jhakulin

**Comment by pankopon** [comment]
@yulin-li Is there a work item about this on the backlog? Please update.

**Comment by yulin-li** [comment]
@pankopon this work item is in my backlog

**Comment by pankopon** [comment]
Closing this item as there's now a task on the team's backlog. We will update the issue when a Speech SDK release with a fix is available.

**Comment by kasimok** [comment]
I can also reproduce, @jhakulin @pankopon we suspect it is caused by the AEC(Echo Cancellation) of the iOS system. 
May I have the final result of your backlog, is it resolved?
