### ISSUE TITLE
IOS From Microphone example

### ISSUE THREAD

**Issue by JohnStraumann66** [Azure-Samples/cognitive-services-speech-sdk#778]
Hello:

Thanks for the great example: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/swift/macos

What is the best practice for determine when someone is done speaking? Should I listen for a pause, or use a trigger word like stop? So for example:
Unlock front door <2 secondpause> so we know input is done
or
Unlock front door STOP

and so we know the speaker is done by the word STOP?

Can you post some example code on how to stop the listening?

Thanks!

**Comment by amitkumarshukla** [comment]
@JohnStraumann66 looks like your scenario is very small sentences. If that is the scenario please use recognizeonce. recognizeonce automatically determines when you have stopped speaking and will produce the result. Here is the example for it 
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/219a394d37289edae79e6850e27dc660ed657eba/quickstart/swift/macos/from-microphone/helloworld/helloworld/AppDelegate.swift#L66

Do let me know if this answers your question.

**Comment by JohnStraumann66** [comment]
Hello:

Thanks for the reply. That's the example I am using, but when I stop speaking, the label I use for the result gets cleared, it sets the label text to the words spoken, but then when I stop speaking I think it is still listening, and since I didn't say anything sets the label to blank.

**Comment by amitkumarshukla** [comment]
@jhakulin could you please look into it.

**Comment by pankopon** [comment]
@JohnStraumann66 Could you just check whether result.text is empty (which can genuinely happen) and if it is, not update the label if you don't want to clear it? For example
```
let isResultOk = (result.text ?? "").isEmpty ? false : true
```
and then call updateLabel only if isResultOk is true. Or put the condition inside the updateLabel func.

**Comment by JohnStraumann66** [comment]
Hello:

Thanks for the response. I pasted below what I tried, still see the same behavior, as soon as I stop speaking the label text is cleared.

func recognizeFromMic() {
        var speechConfig: SPXSpeechConfiguration?
        do {
            try speechConfig = SPXSpeechConfiguration(subscription: sub, region: region)
        } catch {
            print("error \(error) happened")
            speechConfig = nil
        }
        speechConfig?.speechRecognitionLanguage = "en-US"
        
        let audioConfig = SPXAudioConfiguration()
        
        let reco = try! SPXSpeechRecognizer(speechConfiguration: speechConfig!, audioConfiguration: audioConfig)
        
        reco.addRecognizingEventHandler() {reco, evt in
            print("intermediate recognition result: \(evt.result.text ?? "(no result)")")
            self.updateLabel(text: evt.result.text, color: .gray)
        }
        
        updateLabel(text: "Listening ...", color: .gray)
        print("Listening...")
        
        let result = try! reco.recognizeOnce()
        let isResultOk = (result.text ?? "").isEmpty ? false : true
        if (isResultOk)
        {
          print("recognition result: \(result.text ?? "(no result)")")
          updateLabel(text: result.text, color: .black)
        }
    }
    
    func updateLabel(text: String?, color: UIColor) {
        DispatchQueue.main.async {
            self.lblDetectedText.text = text
            self.lblDetectedText.textColor = color
        }
    }

**Comment by jhakulin** [comment]
@JohnStraumann66 

When using either of following samples
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/swift/ios/from-microphone
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/swift/macos/from-microphone

If the text box, which collects the recognition results (first intermediate results and at the end the final result), is cleared after you stop speaking that means your final result was empty. 

I tried on my side with iOS and Mac and these samples worked fine (the final result after I stopped speaking was displayed in the UI). Now to see better what happens in your scenario, could you please collect the logs by using following instructions ?
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

**Comment by JohnStraumann66** [comment]
I'll try the logs, in the meantime I attached my Project to see if you can spot anything. I am testing Apple speech recognition against Azure...
https://1drv.ms/u/s!Au3qGElrrIbJkawQnAuVWYwkQVJFXA?e=bK9zfV


[ViewController.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/5145183/ViewController.txt)

**Comment by jhakulin** [comment]
@JohnStraumann66 I tested your app and that works also as expected (results are captured correctly, I tested in westus endpoint), could be that problem is related to your service region/endpoint.  Instead of full speech SDK logs, could you register to SessionStarted event and provide the session id from that event ? Also let us know in which region you are testing ?

**Comment by jhakulin** [comment]
@JohnStraumann66 Let me know if you have the issue and provide session ID? Issue will be closed soon if no updates.

**Comment by jhakulin** [comment]
@JohnStraumann66 
To check what happens on service side, we would need sessionId value from 
https://docs.microsoft.com/en-us/objectivec/cognitive-services/speech/spxsessioneventargs
You can get this event by subsribing using addSessionStartedEventHandler, see https://docs.microsoft.com/en-us/objectivec/cognitive-services/speech/spxrecognizer

**Comment by pankopon** [comment]
@JohnStraumann66 If this is still a valid issue for you, can you please provide the session id info as requested?

**Comment by pankopon** [comment]
Closed since no update, please open a new issue if you need more support.
