### ISSUE TITLE
Sometimes speechRecognizer kill the app

### ISSUE THREAD

**Issue by emelyanovkirill** [Azure-Samples/cognitive-services-speech-sdk#783]
This error is occurred.
Thread 90
#0	0x0000000104e3f4e4 in ___lldb_unnamed_symbol2713$$MicrosoftCognitiveServicesSpeech ()

**Comment by jhakulin** [comment]
@emelyanovkirill Thanks for the report, we would need some more information. Could you provide steps how to reproduce this error?

**Comment by jhakulin** [comment]
@emelyanovkirill Let me know more information, issue will be closed soon if no update,
