### ISSUE TITLE
Integrate microsoft-cognitiveservices-speech-sdk”: “^1.13.1” with React  JS application

### ISSUE THREAD

**Issue by prascomesin** [Azure-Samples/cognitive-services-speech-sdk#787]
**Describe the bug**
Receiving loader errors when trying to import microsoft sdk into React project

**To Reproduce**
1. Performed npm install microsoft-cognitiveservices-speech-sdk
2. In the react src , created a file with sdk = require("microsoft-cognitiveservices-speech-sdk")

**Expected behavior**
Need to be able to use sdk for setting up the speech recognizer

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.  1.13.0

**Platform, Operating System, and Programming Language**
 - OS:  Mac
 - Hardware - x64,
 - Programming language: React Javascript
 - Browser Chrome
**Additional context**
On react build and run getting the error "You may need an appropriate loader to handle this file typ" for different files like ws.* within the sdk 

Can you advise on the steps to integrate this SDK with a React application. This application is hosted on a Node server.

 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by prascomesin** [comment]
Error 
./node_modules/microsoft-cognitiveservices-speech-sdk/node_modules/ws/lib/websocket.js
Module parse failed: Unexpected token (345:6)
You may need an appropriate loader to handle this file type.
|       compress: true,
|       fin: true,
|       ...options
|     };
| 
 @ ./node_modules/microsoft-cognitiveservices-speech-sdk/node_modules/ws/index.js 3:18-44
 @ ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/es2015/src/common.browser/WebsocketMessageAdapter.js
 @ ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/es2015/src/common.browser/Exports.js
 @ ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/es2015/microsoft.cognitiveservices.speech.sdk.js
 @ ./src/index.js undefined
./node_modules/microsoft-cognitiveservices-speech-sdk/node_modules/ws/lib/permessage-deflate.js
Module parse failed: Unexpected token (347:8)
You may need an appropriate loader to handle this file type.
| 
|       this._inflate = zlib.createInflateRaw({
|         ...this._options.zlibInflateOptions,
|         windowBits
|       });
 @ ./node_modules/microsoft-cognitiveservices-speech-sdk/node_modules/ws/lib/sender.js 5:26-57
 @ ./node_modules/microsoft-cognitiveservices-speech-sdk/node_modules/ws/index.js
 @ ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/es2015/src/common.browser/WebsocketMessageAdapter.js
 @ ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/es2015/src/common.browser/Exports.js
 @ ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/es2015/microsoft.cognitiveservices.speech.sdk.js
 @ ./src/index.js undefined
./node_modules/microsoft-cognitiveservices-speech-sdk/node_modules/ws/lib/websocket-server.js
Module parse failed: Unexpected token (55:6)
You may need an appropriate loader to handle this file type.
|       path: null,
|       port: null,
|       ...options
|     };
| 
 @ ./node_modules/microsoft-cognitiveservices-speech-sdk/node_modules/ws/index.js 6:19-52
 @ ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/es2015/src/common.browser/WebsocketMessageAdapter.js
 @ ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/es2015/src/common.browser/Exports.js
 @ ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/es2015/microsoft.cognitiveservices.speech.sdk.js
 @ ./src/index.js undefined
./node_modules/microsoft-cognitiveservices-speech-sdk/node_modules/ws/lib/stream.js
Module parse failed: Unexpected token (66:4)
You may need an appropriate loader to handle this file type.
| 
|   const duplex = new Duplex({
|     ...options,
|     autoDestroy: false,
|     emitClose: false,
 @ ./node_modules/microsoft-cognitiveservices-speech-sdk/node_modules/ws/index.js 5:34-57
 @ ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/es2015/src/common.browser/WebsocketMessageAdapter.js
 @ ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/es2015/src/common.browser/Exports.js
 @ ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/es2015/microsoft.cognitiveservices.speech.sdk.js
 @ ./src/index.js undefined

**Comment by trrwilson** [comment]
Thanks for filing this and apologies on the slower turnaround on replying to this issue -- I've been trying to track down a team member with experience integrating with React but want to at least provide an acknowledgement in the interim.

As you've seen, part of the trouble is that we don't have a sample or any specific instructions for React as part of our documentation (on the main docs at http://aka.ms/speech/sdk or for the JS SDK specifically at https://github.com/Microsoft/cognitive-services-speech-sdk-js). I've filed a work item for us to produce a formal sample there as a reference.

That's longer term: in the nearer term, we'll keep tracking down any reference currently available.

**Comment by trrwilson** [comment]
I got in touch with someone with far more React knowledge than I have and there are a few follow-up points/questions for us to get to the bottom of this:

- What build tools are being used (webpack, babel, is CRA being used, etc.) and what version?
- What version of React is this being built against?
- Can you build other es2015, es2016 apps/modules?

It sounds like this sort of error ("can't parse this .js file") typically stems from a version/capability mismatch with the tooling.

**Comment by pankopon** [comment]
@prascomesin Is this still a valid issue for you? Please update with the requested information, othewise we'll have to close it.

**Comment by pankopon** [comment]
Closing the item since no update from the customer in a couple of months. Please create a new issue if you still need support on any specific topics.
