### ISSUE TITLE
Speech to text not working in iPhone safari browser 

### ISSUE THREAD

**Issue by MalateshPatil** [Azure-Samples/cognitive-services-speech-sdk#788]
**Describe the bug**
We have an angular app and integrated azure cognitive speech to text service into it. Most of the samples on speech to text available on the internet, have a button and on that button click speech to text, continuous recognition will start.  But in our application we have started the speech to text service on one of the tokbox events. Speech to text working fine with Windows and Android Chrome browsers. But not working in iPhone  and Mac safari browser.

Also noticed that if I start speech to text in angular ngOnInit or ngAfterViewInit lifecycle hooks, It is not working in all the devices.

**Expected behavior**
Speech to text need to work on iPhone safari browser when we start the service in one of tokbox events.

**Version of the Cognitive Services Speech SDK**
1.8.1

**Platform, Operating System, and Programming Language**
 - OS:  iOS, Mac
 - Programming language: JavaScript
 - Browser- Safari

**Comment by brandom-msft** [comment]
Hi @MalateshPatil - the releases since 1.8 have had fixes applied related to iOS issues reported in the past. Are you able to update to the current available version (1.13) and retry this?

**Comment by pankopon** [comment]
Closed as fixed in current SDK releases.
