### ISSUE TITLE
C++ Text-to-Speech quickstart page needs to update the libssl version. The package mentioned there does not exist

### ISSUE THREAD

**Issue by dargilco** [Azure-Samples/cognitive-services-speech-sdk#789]
In this page
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/cpp/linux/text-to-speech

It says:
"On Ubuntu, install these packages to build and run this sample:
sudo apt-get update
sudo apt-get install build-essential libssl1.0.0 libasound2 wget"

Installing libssl1.0.0 fails on Ubuntu because it does not exist. I changed it to libssl1.1 and that worked. I'm able to run this sample on Ubuntu 20.04 LTS on a RPi4.

Darren

**Comment by pankopon** [comment]
That's because these instructions are specific to Ubuntu 16.04 and 18.04 that are listed in prerequisites on that same page. Newer versions with Ubuntu 20.04 and Debian 10 information exist in the Speech SDK repository and will be published when the SDK 1.14.0 release is out.
