### ISSUE TITLE
What's the endpoint ? (wss)

### ISSUE THREAD

**Issue by Sleepingbug** [Azure-Samples/cognitive-services-speech-sdk#79]
see: 
https://docs.microsoft.com/en-US/azure/cognitive-services/speech-service/how-to-migrate-from-bing-speech

**Speech Service WebSockets API is compatible with Bing Speech (different endpoint). Migrate to the Speech SDK if possible to simplify your code.**

I know Bing Speech WebSocket protocol.
Now I want to know:
what's the endpoint of new Speech API ?
Please tell me. It's very important to me

**Comment by Sleepingbug** [comment]
in Bing Speech Websocket protocol, client connects to server with a token.
in Speech API [new API] , client connects to server with subscription key and region string.
I think the HEADER is different between old protocol and new protocol.

**Comment by Sleepingbug** [comment]
now I can get the endpoint from Azure.
but I can't check if the endpoint is useful.
because I don't know the HTTP headers in the Speech protocol. 
what should I fill in the HTTP headers?

**Comment by zhouwangzw** [comment]
The endpoint of new Speech Service is described [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-apis#speech-to-text). Please replace `https` with `wss`.

The new Speech service also supports Authorization token, which can be specified using the request header Authorization, same way as the old speech. Please refer [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-apis#speech-to-text) for details.

Thanks,

**Comment by Sleepingbug** [comment]
Thank you very much. 
I have test it and it works

**Comment by SongKeTong** [comment]
@zhouwangzw , About this question, there are only Service of "speech to text" and "text to speech".
But where is the service of speech translation api?

**Comment by zhouwangzw** [comment]
Speech-To-Text/Speech Translation API is a part of SDK, Please find details here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-translate-speech-csharp

Thanks!

**Comment by SongKeTong** [comment]
@zhouwangzw ,My code is coding by golang, so I want to use websocket to connect server.
I want to use speech translation api to translate one audio data to another language audio data. But i did't find endpoint or url in the documentation.

**Comment by Sleepingbug** [comment]
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-apis#speech-to-text

**Comment by SongKeTong** [comment]
what I need is "speech to speech" translator service ,audio data to audio data

**Comment by Sleepingbug** [comment]
No such service. 
I suggest you to do:

**Comment by Sleepingbug** [comment]
No such service. 
you can do:
1, speech to text and translate it,
2, text to speech

**Comment by wolfma61** [comment]
whats wrong with using the SDK the way it is documented?

**Comment by SongKeTong** [comment]
My code is coding by golang, so I want to use websocket to connect server, not SDK.
I want to use speech translation api to translate one audio data to another language audio data. 
But i did't find endpoint or url in the documentation.
I need  endpoint and protocol to connect.

**Comment by SongKeTong** [comment]
Please solve my doubts. Or I understand mistakes. @zhouwangzw @wolfma61 .

**Comment by zhouwangzw** [comment]
You can try the following websocket endpoint for translation: 
`wss://westus.s2s.speech.microsoft.com/speech/translation/cognitiveservices/v1?format=simple&from=en-us&to=de-DE&features=texttospeech&voice=Microsoft%20Server%20Speech%20Text%20to%20Speech%20Voice%20(de-DE%2c%20Hedda)`
Please replace "westus" with your service region, set "from=" to your source language, and "to=" to your target language, and "voice=" with the voice name in your target language. Supported voice names can be found [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support#text-to-speech
). If you want to specify multiple target languages, just repeat the query parameter "to" for each language, like: "from=en-us&to=de-DE&to=zh-CN". Only one voice language is supported, and it must match the first "to" language. 

The protocol for Speech-to-Text/Speech translation works similar to the protocol for speech-to-text. You send the same audio message to service, and will receive translation.hypothesis and translation.phrase for translated text, and translation.synthesis and translation.synthesis.end messages for voice output. However, there is no public documentation about translation protocol yet. Currently, using SDK is the only supported way for translation service. 

Thanks,

**Comment by SongKeTong** [comment]
Thank you for your reply @zhouwangzw .
I use "wss://westus.s2s.speech.microsoft.com/speech/translation/cognitiveservices/v1?from=zh-CN&to=en-US" to translate, and i received "translation.phrase " and "translation.hypothesis" for the text output. But I did't receive "translation.synthesis" for voice output.What could this be?How should I change it?

**Comment by SongKeTong** [comment]
Thank you for your reply @zhouwangzw @wolfma61 
I get audio data now!
But as your meaning, it is not officially supported.Can I use it in my project ?
Will there be support plan later?

**Comment by Sleepingbug** [comment]
Very good!

**Comment by wolfma61** [comment]
it's not a secret, not the official way to talk to the service, so no real support, and no guarantees that the protocol won't change.
On the other hand we will need to support 'existing' clients using the SDK ...

**Comment by SongKeTong** [comment]
When I use websocket endpoint for translation,I have another problem：

I sent two sentences.it return two text sentences result ,but with one audio result. The last sentence can not be translated to voice.

**Comment by zhouwangzw** [comment]
Did you receive translation.synthesis.end message?

**Comment by SongKeTong** [comment]
Yse ,I reveived it. 
but Just one sentence missing.

**Comment by zhouwangzw** [comment]
To clarify: you received 2 translation.phrase messages (each of them contains a translated text), but only 1 translation.synthesis message(which is only corresponding to the first translated text), and then 1 translation.synthesis.end message? What is the status in translation.synthesis.End message?

Could you please try your audio using our SDK. (e.g C++,C#, Java, JavaScript one) and check whether you get expected audio output?

**Comment by SongKeTong** [comment]
the status in translation.synthesis.End message is {"SynthesisStatus":"Success"}

And I used c++ SDK demo from github, I used AudioInputFromFileCallback to contol audio stream input.
And get audio data in Synthesizing.Connect([](const TranslationSynthesisEventArgs& e){} method .
I receive two audio data, but the second data is "RIFF" + all 0 data

**Comment by zhouwangzw** [comment]
For each translation.phrase message, you should expect one translation.syntheis message, and one translation.synthesis.end (which means the synthesis for this phrase is done). Then you will receive the next translation.phrase, translation.synthesis, translation.synthesis.end, until you receive turn.end which indicates the end of recognition/translation.

In SDK, both synthesis and synthesis.end are delivered as Synthesizing event, but the Reason value is different, one is SynthesizingAudio, and the other is SynthesizingAudioCompleted. The audio size of the second one must be 0.

**Comment by SongKeTong** [comment]
Yes,the audio size of the second one is 0.
But what I said is that the second sentence translation result audio data is wav header + "0x00000..."data.
I receive the audio length, but the data is wav header + "0x00000..."data

**Comment by zhouwangzw** [comment]
I tried a couple of audio files with multiple sentences, and can receive correct audio messages via SDK. If you have a translation text result and a non-zero audio message, it should contain audio data. Would it be possible to share your audio for investigation?

**Comment by SongKeTong** [comment]
Due to Configuration reasons，I have to use websocket to connect the service,not by SDK.
And just the same question ,I send two sentence to translate, but return with two text result but one audio data.

Follow is the result print:

Path:turn.start{}
Path:speech.startDetected  {"Offset":600000}
Path:translation.hypothesis  {"Text":"你好.",...}
Path:translation.hypothesis  {"Text":"你好."...}
Path:translation.phrase  {"RecognitionStatus":"Success"...}
Path:translation.synthesis RIFF��  WAVEfmt      �>   }      datad....
 Path:translation.synthesis.end  {"SynthesisStatus":"Success"}]
Path:translation.hypothesis  {"Text":"今天天气怎么样?"...}

I notice the text result of the second sentence has no "translation.phrase", is this mean the second sentence need more data? How to let it output the translate result?

**Comment by SongKeTong** [comment]
Is the 0 byte audio message need message header? Sample as 
Path + Content-Type + X-RequestId + X-Timestamp + 0  byte audio data

**Comment by SongKeTong** [comment]
why all audio data result has the RIFF header?

**Comment by zhouwangzw** [comment]
So that you can play each audio block independently.

**Comment by zhouwangzw** [comment]
And the 0 byte audio message need the same message header.

**Comment by SongKeTong** [comment]
How to separate audio data?
Following the ”Path:translation.synthesis” is audio result, start with the RIFF header,and it seems like There's something at the end .Looks like some event data?
What's the result audio data protocol like?

**Comment by zhouwangzw** [comment]
The translation.synthesis contains a wav header and pcm audio data. After that, there is a translation.synthesis.end message which indicates end of the synthesis audio for this final result. For the next result, you will receive another Translation.synthesis message, following by a translation.synthesis.end message.

**Comment by SongKeTong** [comment]
If After the The translation.synthesis is all audio data, I write it to file ,but it looks like something wrong at the end. You can look the following data, every sentence has a wrong tail

![wa1l6gj7vbpaxude d 5 la](https://user-images.githubusercontent.com/19605341/48876638-10abab80-ee3a-11e8-8ce6-7f2968bdf5ce.png)

[trans.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/2606314/trans.zip)

**Comment by SongKeTong** [comment]
Or if I need get the audio length from the RIFF header,and get the data of corresponding length

**Comment by fmegen** [comment]
please be aware that the synthesis wav file contains several additional RIFF chunks (some comming after the PCM data) and you need to make sure only to take the PCM data itself, not any of the other chunks.

**Comment by SongKeTong** [comment]
Length of RIFF header is 46??? not 44??
![k hs7t3m 121ac t3 j j](https://user-images.githubusercontent.com/19605341/48926302-a6f9d300-ef07-11e8-8c6c-b64eaa3a583e.png)

**Comment by fmegen** [comment]
the length of the chunks can vary and additional data being added at the ende.

for more information, you may check https://en.wikipedia.org/wiki/WAV
