### ISSUE TITLE
How to get the text from the audio wav bytes ?

### ISSUE THREAD

**Issue by shreeraj04** [Azure-Samples/cognitive-services-speech-sdk#791]
I wanted to know if we can get the STT result from the audio bytes or base64 embedded instead of a file. I wanted this for the real time STT.
Client will be sending the bytes or base64 embedded string using which I want to send request to Azure Speech Services to get the text out of it.

Please guide if there is a way for this. I checked the Python samples, but everywhere it is getting read from the wav file.

PS: Not an issue, but a general question

**Comment by jhakulin** [comment]
@shreeraj04 Thanks for question. You can use following method to convert base64 string to bytes and then feed it to Speech SDK using push stream or create customized pullstream reader for your project.
https://docs.microsoft.com/en-us/dotnet/api/system.convert.frombase64string?view=netcore-3.1

Let us know if this helps

**Comment by pankopon** [comment]
Closed the item since no further update and the question was answered.
