### ISSUE TITLE
azure speech recognition crash the console-app on linux IOT with KeywordRecognizer

### ISSUE THREAD

**Issue by tree1370** [Azure-Samples/cognitive-services-speech-sdk#793]
hi 

i use KeywordRecognizer for recognize word . 

i have a console app that uses azure for speech recognition offline from microphone (by KeywordRecognitionModel table) on linux IOT(raspberry pi).

when i run it, at first time it works correctly and can recognize my word, but after 3 or more recognition , it crashes the app, even try-catch cant handle it.

Note : the following code works good on windows PC, without any crash or error, but on linux raspberry pi it crashes the app.

`using Microsoft.CognitiveServices.Speech;
 using Microsoft.CognitiveServices.Speech.Audio;
 using System;
 using System.Diagnostics;
 using System.Runtime;
 using System.Runtime.InteropServices;
 using System.Threading;
 using System.Threading.Tasks;
    
 namespace VoiceAssistant
 {
     class Program
     {
    
         static async Task Main()
         {
         bool working = false;
             while (true)
             {
                 try
                 {
                     if (!working)
                     {
                         Console.WriteLine("**true working**");
    
                         working = true;
                         await PropertyStart();
                     }
    
                 }
                 catch (Exception ex)
                 {
                     Console.WriteLine("**false working**");
    
                     working = false;
                     Console.WriteLine(ex.Message);
    
                     Console.ReadLine();
        
                 }
             }
    
         }
    
         private static async Task PropertyStart()
         {
             int count = 0;
    
             Console.WriteLine("Start 2");
             try
             {
                 //var config = SpeechTranslationConfig.FromSubscription("key", "westus");
    
                 Console.WriteLine("Step 1");
    
    
                 //RecordingPanel recordingPanel = new RecordingPanel();
    
                 var keywordModel = KeywordRecognitionModel.FromFile("my_home.table");
    
                 Console.WriteLine("Step 2");
    
    
   
                 var audioConfig = AudioConfig.FromDefaultMicrophoneInput();
    
                 var keywordRecognizer = new KeywordRecognizer(audioConfig);
                 //keywordRecognizer.Properties.SetProperty("SPEECH-ObjectCountWarnThreshold", "10000");
    
                 Console.WriteLine("Step 3");
    
    
    
    
                 while (true)
                 {
    
    
                     try
                     {
    
                         Console.WriteLine("Start Result");
    
                           
    
                         KeywordRecognitionResult result = await keywordRecognizer.RecognizeOnceAsync(keywordModel);
    
        
                         Console.WriteLine("A Start Result");
    
                         // Checks result.
                         if (result.Reason == ResultReason.RecognizedKeyword)
                         {
                             count++;
        
                             Console.WriteLine("Stop");
    
                             //await keywordRecognizer.StopRecognitionAsync();
    
                             //await keywordRecognizer.StopRecognitionAsync();
                             Console.WriteLine("a Stop" + result.Duration.TotalSeconds.ToString());
    
    
                             Console.WriteLine(count.ToString() + $"We recognized: {result.Text}");
                             //recordingPanel.StartBtn_Click();
                             //keywordRecognizer.Dispose();
    
    
                         }
                         else if (result.Reason == ResultReason.NoMatch)
                         {
                             Console.WriteLine($"NOMATCH: Speech could not be recognized.");
                         }
                         else if (result.Reason == ResultReason.Canceled)
                         {
                             var cancellation = CancellationDetails.FromResult(result);
                             Console.WriteLine($"CANCELED: Reason={cancellation.Reason}");
    
                             if (cancellation.Reason == CancellationReason.Error)
                             {
                                 Console.WriteLine($"CANCELED: ErrorCode={cancellation.ErrorCode}");
                                 Console.WriteLine($"CANCELED: ErrorDetails={cancellation.ErrorDetails}");
                                 Console.WriteLine($"CANCELED: Did you update the subscription info?");
                             }
                         }
                         //await RecognizeSpeechAsync();
                         Console.WriteLine("**");
                     }
                     catch (Exception ex)
                     {
                         Console.WriteLine("Error in :::: " + ex.Message);
                     }
                      
                 }
    
             }
             catch (Exception ex)
             {
    
                 Console.WriteLine("Error " + ex.Message);
    
             }
             Console.ReadLine();
         }
    
    
    
 }`

i'm use using but doesn't work  correctly.

![image](https://user-images.githubusercontent.com/12994961/90308959-6327d800-def9-11ea-96fc-04851ae3bed7.png)

**Comment by trrwilson** [comment]
Thank you for filing this issue! That certainly doesn't look expected and I'd like us to take a deeper look into it. We could use your help with some additional information to diagnose the problem:

* What version of the Speech SDK is in use? 1.12.0, 1.12.1, and 1.13.0 have the KeywordRecognizer available but only 1.13.0 has a bug fix related to audio advancement that *could* result in a crash depending on underlying audio management
* Similarly: how was the keyword generated for use with the KeywordRecognizer? If you know roughly when it was created out of the Speech Studio, that'd help us in evaluating if there's an incompatibility with the specific model.
* Are there any additional details reported with the crash or is the fatal exit with the segmentation fault all the information provided?
* If you can follow the [instructions for enabling file-based logging](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging) and share that with us, it'll give us a lot of information about what's failing--potentially even including a call stack for the crash.

Thanks again!

**Comment by pankopon** [comment]
@tree1370 Which Linux distribution are you using? The Speech SDK does not support Raspberry Pi OS (Raspbian) at the moment, with known issues exactly like those seen in your screenshot.

(The list of supported Linux distributions can be found at https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk?tabs=linux%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio.)

**Comment by pankopon** [comment]
Closed since no further update and the problem seems to be due to unsupported Raspberry Pi OS.
