### ISSUE TITLE
Cpp AudioConfig::FromStreamInput(shared_ptr<PullAudioInputStream>) does not copy the shared ptr

### ISSUE THREAD

**Issue by nathanaelk** [Azure-Samples/cognitive-services-speech-sdk#794]
**Describe the bug**
AudioConfig::FromStreamInput does not make a copy of the PullAudioInputStream shared ptr so the ref count is never increased and the caller has to make sure the pointer is always valid. This is a rather unusual way to use shared_ptr because by passing a shared_ptr the expectation is that it will be copied (increase in ref count) so the caller does not have to worry about it.
If the raw pointer is going to be used, a better API design will be to take the raw pointer as an input so it is clear that the caller has to make sure the pointer is always valid.
The raw pointer is later used in Read to 

static std::shared_ptr<AudioConfig> FromStreamInput(std::shared_ptr<AudioInputStream> stream)
    {
        SPX_IFTRUE_THROW_HR(stream == nullptr, SPXERR_INVALID_ARG);

        SPXAUDIOCONFIGHANDLE haudioConfig = SPXHANDLE_INVALID;
        SPX_THROW_ON_FAIL(audio_config_create_audio_input_from_stream(&haudioConfig, **GetStreamHandle(stream)**));

        auto config = new AudioConfig(haudioConfig);
        return std::shared_ptr<AudioConfig>(config);
    }

The raw pointer is later used to create a shared_pointer but at that point the destructor may already been called:
static std::shared_ptr<PullAudioInputStream> Create(std::shared_ptr<AudioStreamFormat> format, std::shared_ptr<PullAudioInputStreamCallback> callback)
    {
        format = UseDefaultFormatIfNull(format);

        SPXAUDIOSTREAMHANDLE haudioStream = SPXHANDLE_INVALID;
        SPX_THROW_ON_FAIL(audio_stream_create_pull_audio_input_stream(&haudioStream, GetFormatHandle(format)));

        auto stream = new PullAudioInputStream(haudioStream);
        SPX_THROW_ON_FAIL(pull_audio_input_stream_set_callbacks(haudioStream, stream, ReadCallbackWrapper, CloseCallbackWrapper));
        SPX_THROW_ON_FAIL(pull_audio_input_stream_set_getproperty_callback(haudioStream, stream, GetPropertyCallbackWrapper));

        stream->m_callback = callback;

        return **std::shared_ptr<PullAudioInputStream>(stream);**
    }

**To Reproduce**
1. Created an PullAudioInputStream object with AudioInputStream::CreatePullStream
2. Call AudioConfig::FromStreamInput with the shared_ptr returned in 1
3. Make sure the shared_ptr in 1 goes out of scope and try to get the PullAudioStream to call read

**Expected behavior**
Invalid pointer

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 - OS: Windows
 - Hardware - x64, x86, ARM, ...
 - Programming language: C++

**Comment by trrwilson** [comment]
Nathan, thanks for the great report. This provides all the detail we need to investigate and I've filed an issue for us to look into it. I know I've seen something like this myself in the C# projection (letting the stream go out of scope ends up with a nigh-impossible-to-diagnose ExecutionEngineException at some unpredictable point, whenever the GC decides to take action) and so I agree that improvement here would be great.

I've linked this issue from our internal work item and we'll update when we have more information on next steps. To keep things clean, we'll close the item in the interim, but subscribing should let you see the update on the (closed) item as soon as it arrives.
