### ISSUE TITLE
How to use ContinuousRecognition

### ISSUE THREAD

**Issue by SOliasS** [Azure-Samples/cognitive-services-speech-sdk#796]
Hey, i have some issues with ContinuousRecognition.
I start the recognition with intentRecognizer.StartContinuousRecognitionAsync.
Then i use the intentRecognizer.Recognized to track the recognized intents and write them to a collection.
But sometimes there are intents missing...

@jhakulin Do i have to use another event or am i doing something else wrong?

**Comment by BrianMouncer** [comment]
@SOliasS 

I would subscribe for both Recognized and Recognizing events, but Recognized should be enough assuming the speech is good enough to fire the Intent rules. I would also listen for the Canceled event so you know if the service timed out or got disconnected from some reason.

Did you look at the sample for intent recognition with continuous recognition?

https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/intent_recognition_samples.cs

**Comment by jhakulin** [comment]
@SOliasS That is correct way, could you provide session id from the recognized event when the intent is missing ?
We need to look on speech service side if we see why intent is not returned.

**Comment by SOliasS** [comment]
Hey, 
sry haven't had any time to investigate it further...
Maybe i'll get around on friday

**Comment by pankopon** [comment]
@SOliasS Is this still a valid issue for you? Please update with the requested information, otherwise we'll have to close.

**Comment by pankopon** [comment]
Closing the item since no update from the customer in a couple of months. Please create a new issue if you still need support on any specific topics.
