### ISSUE TITLE
Implement new DateTime fix

### ISSUE THREAD

**Issue by SOliasS** [Azure-Samples/cognitive-services-speech-sdk#797]
Hey,
the Recognizers-Text team implemented a fix for worng interpeted Datetimes in May,
but the Bug is still present in LUIS.
Could you please implement it?

https://github.com/microsoft/Recognizers-Text/issues/2123

**Comment by rhurey** [comment]
I'm following up with the internal teams about what the deployment timeline is...

**Comment by BrianMouncer** [comment]
@SOliasS 

The service engineering team got back to us, and the current plan is to deploy this fix in about 3 weeks.

**Comment by pankopon** [comment]
Closing the item as the deployment of a service fix has been scheduled.
