### ISSUE TITLE
Implementation of c# PullAudioInputStreamCallback Abstract Class missing ref keyword

### ISSUE THREAD

**Issue by mrscience21** [Azure-Samples/cognitive-services-speech-sdk#799]
From reviewing the[ Azure Cognitive Services Documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.audio.pullaudioinputstreamcallback?view=azure-dotnet) for this class and looking as code samples from other languages, it seems to me the abstract class intends for implementations to pass binary data by saving it into dataBuffer and size - here passes as parameters. Even the metadata generated code definitions seem to indicate this:
`public abstract class PullAudioInputStreamCallback : IDisposable
{
        // ...

        //
        // Summary:
        //     Reads binary data from the stream. Note: The dataBuffer returned by Read() should
        //     not contain any audio header.
        //
        // Parameters:
        //   dataBuffer:
        //     The buffer to fill
        //
        //   size:
        //     The size of the buffer.
        //
        // Returns:
        //     The number of bytes filled, or 0 in case the stream hits its end and there is
        //     no more data available. If there is no data immediately available, Read() blocks
        //     until the next data becomes available.
        public abstract int Read(byte[] dataBuffer, uint size);

        // ...
}`

However, in order to do this, the abstract class should include a ref keyword in-front of both. Otherwise, the variables are not passed by reference and they cannot be modified by the function they're passed to.

**Version of the Cognitive Services Speech SDK**
Version 1.13.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Programming language: C#

**Comment by rhurey** [comment]
Arrays are inherently reference types in C#.

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/passing-arrays-as-arguments.

The intent is that Read() will be called with a already allocated byte[] that Read() will write data into, not that Read() will allocate new memory to write into. The uint size is the length of that array.  In this case the size parameter isn't strictly need as you can call .Length on the array and is more an artifact of maintaining a cross language library.

Read() should then return the number of bytes written into the buffer.

**Comment by pankopon** [comment]
Closed as answered.
