### ISSUE TITLE
Conversation options?

### ISSUE THREAD

**Issue by rsquizz** [Azure-Samples/cognitive-services-speech-sdk#80]
In Bing Speech, conversation recognition mode (as opposed to interactive or dictation) was limited to 10 languages. I understand that in the new Speech Service, there is no longer any need to specify the recognition mode, but are all of the [listed languages](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support) for text-to-speech supported for conversation now?

**Comment by wolfma61** [comment]
the pages list the supported languages - correct
