### ISSUE TITLE
Major delays on speech recognition updates as captions get long enough.

### ISSUE THREAD

**Issue by benlifson** [Azure-Samples/cognitive-services-speech-sdk#800]
**Describe the bug**
In AltSpace, you can enable Speech Recognition and Captions in order to see captions based on what you, or another player in the scene, is saying. We have found that when Altspace speech captions get long enough, there are progressively longer delays between updates to the text. In some cases, this can be nearly 5 or more seconds. This causes snowballing delays, as the captions struggle to catch up.

**Theory of Cause**
After some debugging, it is theorized that the probable source of the delays was in the [SpeechThread.cs script.](https://github.com/AltspaceVR/UnityClient/blob/dev/Assets/Altspace/Scripts/Captions/SpeechThread.cs) That script has a [TranslationRecognizer ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.translation.translationrecognizer?view=azure-dotnet)variable called translator. It in turn has two EventHandlers called Recognizing and Recognized. Their invocation are critical to updating the captions. For some reason, they are being invoked less frequently when there is a lot of text in the sentences its keeping track of. Unfortunately, TranslationRecognizer is a sealed class, so further investigation could not be made.

**To Reproduce**

1. Enter Altspace, and enable Speech Recognition and Captions
2. Have a second user enter Altspace, and enable Speech Recognition and Captions. 
3. Ensure both users are unmuted. Have one user go to the location of the other.
4. Have user (or users) talk quickly in long, run-on sentences. Since captions only cleanup captions from a bubble based on how many sentences are completed, this will result in very large amounts of text per bubble.
5. Eventually, the updates to the text will become progressively less frequent. Eventually, the captions will stop updating all together for several seconds. The bubble may even close, only to re-open. 

**Expected behavior**
It is expected that player captions, both sender and receiver, will update several times per second as the speaker continues to speak. This should happen regularly, regardless of the length of the sentence. 

**Version of the Cognitive Services Speech SDK**
Version 1.12.0

**Platform, Operating System, and Programming Language**
 - OS: Windows (Both the sender and receiver where using the AltSpace 2D mode for Windows)
 - Unity Build Settings, Platform: "PC, Mac & Linux Standalone"
 - Unity Build Settings, Target Platform: Windows
 - Unity Build Settings, Architecture: x86_64
 - Programming language: C#

**Additional context**
 - I have created the Speech SDK Traces file. The Session ID is b43818f5-ccbc-483b-8f1d-7a85802bd2e0. This is also written in the trace files filename. It has been sent privately, for security reasons. This Trace Log was generated on a private build of Altspace, specifically designed for extra logging. The shipped version of AltSpace **does not** include this logging process, as it was created for the purposes of investigating this bug only.

**Comment by BrianMouncer** [comment]
@benlifson 

I do not seem to have access to 

https://github.com/AltspaceVR/UnityClient/blob/dev/Assets/Altspace/Scripts/Captions/SpeechThread.cs

Or even see the UnityClient project repo to be able to request access.

How many languages are you translating into at a time, and what languages are you using?
I've seen final recognition results take some time if translating into may languages at one time.
Can you give a standalone repo of app for this, or at grant me access to the code you linked above, so I can see if I spot anything wrong with the the code?

Also, are you subscribing to the "recognizing" event, or only the final "recognized" event.
the recognizing events will fire far more often, where the recognized event can have some delay depending on how long the user talks, and when they pause long enough to cause the service to endpoint and send recognized result.

In general is is good the use the recognizing event to should progress, but the quality of the text will not be as good, then when a recognized event comes in, to go back and update the caption built from the "recognizing" event with the more accurate text from the recognized event. 

I hope that helps,

Brian.

**Comment by benlifson** [comment]
@BrianMouncer 
Sorry for the delay. I will add you to the teams chat we are having regarding this bug.

**Comment by jhakulin** [comment]
@benlifson Based on the log you provided, there is translations to en, de, es, fr, it, ja, ko, pt languages at the same time? Could you check if using one translation e.g. from en to de, would impact to delays you are seeing?

**Comment by benlifson** [comment]
Thank you. Unfortunately, my apartment has lost internet. I am responding on my laptop, but my git work is on my desktop, and laptop has trouble with ALtSPace. I will not be able to run any tests until my internet returns.

**Comment by pankopon** [comment]
@benlifson Is this still a valid issue, can you please test the suggested setup (i.e. translation only from en to de, for example) for comparison?

**Comment by pankopon** [comment]
@BrianMouncer Please follow up on this with @in2dair and update as necessary.

**Comment by jhakulin** [comment]
@benlifson We have been able to reproduce the issue and created internal ticket to find resolution. Closing this item.
