### ISSUE TITLE
ErrorCode: ConnectionFailure. ErrorDetails:Connection failed (no connection to the remote host). 

### ISSUE THREAD

**Issue by pabloandrei** [Azure-Samples/cognitive-services-speech-sdk#801]
Hello.

I created an application that consumes the Microsoft.CognitiveServices service on Azure.
Locally I use Linux Ubuntu-20 with VSCODE for the application with dotneCore 3.1, **and locally everything works perfectly**.

I created a container, **when I access the microk8s resource of the POD, I have the following error message:**
_ErrorCode: ConnectionFailure.
ErrorDetails:Connection failed (no connection to the remote host). Internal error: 1. Error details: 2460. Please check network connection, firewall setting, and the region name used to create speech factory._

**Information:** 
Error occurs when accessing the resource: Microsoft.CognitiveServices.Speech.SpeechConfig.FromSubscription(myKey, .myRegion)
Location: Southern Brazil
Endpoint: https://brazilsouth.api.cognitive.microsoft.com/sts/v1.0/issuetoken

**My docker file:**
```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["Services/SpeechEventBus/SpeechEventBus.API/SpeechEventBus.API.csproj", "Services/SpeechEventBus/SpeechEventBus.API/"]
COPY ["BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.csproj", "BuildingBlocks/EventBus/EventBusRabbitMQ/"]
COPY ["BuildingBlocks/EventBus/EventBus/EventBus.csproj", "BuildingBlocks/EventBus/EventBus/"]
RUN dotnet restore "Services/SpeechEventBus/SpeechEventBus.API/SpeechEventBus.API.csproj"
COPY . .
WORKDIR "/src/Services/SpeechEventBus/SpeechEventBus.API"
RUN dotnet build "SpeechEventBus.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SpeechEventBus.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SpeechEventBus.API.dll"]


RUN apt-get update && apt-get install -y apt-transport-https
RUN apt-get install -y ubuntu-standard
RUN apt-get install -y apt-utils
RUN apt-get install -y build-essential libssl1.0.0 libasound2 wget
RUN apt-get install -y libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly
```
I did troubleshooting following the steps described at https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/troubleshooting#validate-an-authorization-token, **and connected successfully.**

TELNET and CURL connect to the resource as well.

Would anyone have any tips?

**Comment by BrianMouncer** [comment]
My first guess would be a network issues on the host or container.  Docker desktop was easy to setup, but when the first setup docker on an ubuntu host, I had the follow a few extra steps to get the default dns servers to work correctly.  e.g. I had a working network, but no name resolution inside the containers, and a few other issues. If you think that might has the same network issues I did, try the "dns resolver" issue steps here, https://docs.docker.com/engine/install/linux-postinstall/
That is what got me unblocked the first time I started using docker containers.

We also have a prebuilt Ubuntu 18,04 based container, that has the SPX speech command line tool preinstalled.  It might be worth trying to use that container from your docker host, just to verify the host is either works or has some issue that is unique to the speech sdks use of the network.

docker pull msftspeech/spx:latest will pull a container from dockerhub with SPX tool compiled against the latest public release of the speech SDK.

To learn how to use the Speech CLI, take a look at this getting started page https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/spx-basics?tabs=dockerinstall

If SPX works from the same docker host, using the same key keys and regions, then you'll at least know the host is good and can can use speech with that network setup?

**Comment by pabloandrei** [comment]
> My first guess would be a network issues on the host or container. Docker desktop was easy to setup, but when the first setup docker on an ubuntu host, I had the follow a few extra steps to get the default dns servers to work correctly. e.g. I had a working network, but no name resolution inside the containers, and a few other issues. If you think that might has the same network issues I did, try the "dns resolver" issue steps here, https://docs.docker.com/engine/install/linux-postinstall/
> That is what got me unblocked the first time I started using docker containers.
> 
> We also have a prebuilt Ubuntu 18,04 based container, that has the SPX speech command line tool preinstalled. It might be worth trying to use that container from your docker host, just to verify the host is either works or has some issue that is unique to the speech sdks use of the network.
> 
> docker pull msftspeech/spx:latest will pull a container from dockerhub with SPX tool compiled against the latest public release of the speech SDK.
> 
> To learn how to use the Speech CLI, take a look at this getting started page https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/spx-basics?tabs=dockerinstall
> 
> If SPX works from the same docker host, using the same key keys and regions, then you'll at least know the host is good and can can use speech with that network setup?

Hello.
I read your post, e change the DNS resolution. After I tried connetion to services (Azure), the same error ocorrered.

**Below follow result of the command curl to endpoint of azure  service:**
![image](https://user-images.githubusercontent.com/16004192/93603511-79aecc80-f99a-11ea-8f1e-a2997af7c29d.png)

**Test of AVX2 Supported:**
root@speechapi-deployment-54dfc5d9b8-f6nhz:/app# grep -q avx2 /proc/cpuinfo && echo AVX2 supported || echo No AVX2 support detected
AVX2 supported

**Ping to google (DNS resolution):**
root@speechapi-deployment-54dfc5d9b8-f6nhz:/app# ping www.google.com
PING www.google.com.br (172.217.172.195) 56(84) bytes of data.
64 bytes from gru14s14-in-f3.1e100.net (172.217.172.195): icmp_seq=1 ttl=114 time=16.3 ms
64 bytes from gru14s14-in-f3.1e100.net (172.217.172.195): icmp_seq=2 ttl=114 time=15.5 ms
64 bytes from gru14s14-in-f3.1e100.net (172.217.172.195): icmp_seq=3 ttl=114 time=14.6 ms

--- www.google.com.br ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 14.610/15.502/16.354/0.719 ms
root@speechapi-deployment-54dfc5d9b8-f6nhz:/app# 

Ill try uses this page https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/spx-basics?tabs=dockerinstall

**Comment by pabloandrei** [comment]
@BrianMouncer msftspeech didn't work!

Do you have any ideas or suggestions?
![image](https://user-images.githubusercontent.com/16004192/93622531-b1763e00-f9b3-11ea-9715-826770338bab.png)

**Comment by BrianMouncer** [comment]
I deleted your post because you missed redacting your speech key in the console output from SPX recognize command.
Please take measures to expire and regenerate your speech key, just to be safe...

For getting SPX to work for you, I notice you had some paths wrong,  e.g. the path to the mp3 file was a path on the host file system. it should have been rooted in the container with "/data/".  Also the container does not have GStreamer installed by default, so MP3 will not work out of the box.  please try with a wave file instead.

Here is a command line example that I just used from a windows host and docker desktop, but the only difference should be you would use /temp/data rather than c:\temp\data.  I also omitted the file output, so I will see the recognized text right way rather that needing to open the csv file.

docker run -it -v c:\temp\data:/data --rm msftspeech/spx recognize --files /data/whatstheweatherlike.wav

**Comment by pabloandrei** [comment]
Hello @BrianMouncer .

In the commented item on the command line: "docker run -it -vc: \ temp \ data: / data --rm msftspeech / spx recognize --files /data/whatstheweatherlike.wav", this folder belongs to the physical machine "c : \ temp \ data "and is it docker / pod" /data/whatstheweatherlike.wav "?

I execute, no error and no results are returned.

**Comment by pankopon** [comment]
@pabloandrei Were you able to resolve the issue by now? To clarify, in the command
```
docker run -it -v c:\temp\data:/data --rm msftspeech/spx recognize --files /data/whatstheweatherlike.wav
```
the part `c:\temp\data` indeed refers to a folder on you physical machine (choose whichever folder you want to use) and `/data` (a "mount point") is how it will be seen inside the docker container. So a file `c:\temp\data\whatstheweatherlike.wav` is then visible to apps inside the container as `/data/whatstheweatherlike.wav`.

**Comment by pabloandrei** [comment]
@pankopon hello!
In the past, with help this group, Im resolved this problem. 
Very tks for your attention.
