### ISSUE TITLE
Auto Language Detection/ Speaker out /wav file synthesis not working when using speech Translation in python

### ISSUE THREAD

**Issue by yashugupta786** [Azure-Samples/cognitive-services-speech-sdk#803]
Hi Team 
When using the speech Translation in python .
1. Auto Language Detection option is not there when performing SST. However this exist in normal Speech to Text module .
How to do Auto Language Detection with in speech Translation using python SDK

2. When using the Speech Translation Python SDK .After the Translation there is no option for Synthesis speaker out (TTS ) in python speech sdk  for Translation 

3. When using the Speech Translation using python SDK. When outputting the synthesis in wav file. The File is empty most of the times .Synthesis not happening either through speaker/wav file 

#------------------------------------------------------
def translation_continuous():
    """performs continuous speech translation from input from an audio file"""
    # <TranslationContinuous>
    # set up translation parameters: source language and target languages
    translation_config = speechsdk.translation.SpeechTranslationConfig(
        subscription=speech_key, region=service_region,
        speech_recognition_language='en-US',
        target_languages=('de', 'fr'), voice_name="de-DE-Hedda")
    audio_config = speechsdk.audio.AudioConfig(filename=weatherfilename)

    # Creates a translation recognizer using and audio file as input.
    recognizer = speechsdk.translation.TranslationRecognizer(
        translation_config=translation_config, audio_config=audio_config)

    def result_callback(event_type, evt):
        """callback to display a translation result"""
        print("{}: {}\n\tTranslations: {}\n\tResult Json: {}".format(
            event_type, evt, evt.result.translations.items(), evt.result.json))

    done = False

    def stop_cb(evt):
        """callback that signals to stop continuous recognition upon receiving an event `evt`"""
        print('CLOSING on {}'.format(evt))
        nonlocal done
        done = True

    # connect callback functions to the events fired by the recognizer
    recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
    # event for intermediate results
    recognizer.recognizing.connect(lambda evt: result_callback('RECOGNIZING', evt))
    # event for final result
    recognizer.recognized.connect(lambda evt: result_callback('RECOGNIZED', evt))
    # cancellation event
    recognizer.canceled.connect(lambda evt: print('CANCELED: {} ({})'.format(evt, evt.reason)))

    # stop continuous recognition on either session stopped or canceled events
    recognizer.session_stopped.connect(stop_cb)
    recognizer.canceled.connect(stop_cb)

    def synthesis_callback(evt):
        """
        callback for the synthesis event
        """
        print('SYNTHESIZING {}\n\treceived {} bytes of audio. Reason: {}'.format(
            evt, len(evt.result.audio), evt.result.reason))

    # connect callback to the synthesis event
    recognizer.synthesizing.connect(synthesis_callback)

    # start translation
    recognizer.start_continuous_recognition()

    while not done:
        time.sleep(.5)

recognizer.stop_continuous_recognition()

#-----------------

**Comment by brandom-msft** [comment]
Hi @yashugupta786, I'm looking into the issues you called out, thanks for posting them. I need to enlist the python experts on our team for assistance getting you some answers to these, I'll update you then!

**Comment by TANMAY007100** [comment]
I am facing the same issue. I receive the audio output from `evt.result.audio` in synthesis_callback but the audio is sounding very funny when I am trying to write it to a wav file using writeframes. The audio is bytes which I checked and confirmed. I am setting channel as 1 format to pyaudio.paInt16 and sample rate to 44100. Below is gist of what I am trying in the synthesis_callback event.

```
def synthesis_callback(evt):
            """
            callback for the synthesis event
            """
            print('SYNTHESIZING {}\n\treceived {} bytes of audio. Reason: {}'.format(
                evt, len(evt.result.audio), evt.result.reason))
            print ("len(evt.result.audio)", len(evt.result.audio))
            if len(evt.result.audio) > 0:
                translated_file = wave.open('recorded_audio_'+str(time.time())+'.wav', 'wb')
                translated_file.setnchannels(1)
                translated_file.setsampwidth(self.audio.get_sample_size(pyaudio.paInt16))
                translated_file.setframerate(44100)
                translated_file.writeframes(evt.result.audio)
                translated_file.close()
```

**Comment by pankopon** [comment]
Sorry for the delay in response. In the future, please create separate items for individual topics to help processing.

Answers:
1. This is not supported at the moment, no ETA.
2. The same. You can play the result audio by using e.g. simpleaudio as below:
```
import simpleaudio as sa
...
        if len(evt.result.audio) > 44:
            audio_data = evt.result.audio[44:] # skip wav header
            num_channels = 1
            bytes_per_sample = 2
            sample_rate = 16000
            play_obj = sa.play_buffer(audio_data, num_channels, bytes_per_sample, sample_rate)
            play_obj.wait_done()
```
  - For reference on how it's done in our samples for other languages at the moment:
    - C# - https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/translation_samples.cs#L77
    - Java - https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/TranslationSamples.java#L83

3. and @TANMAY007100 - do it like this:
```
        if len(evt.result.audio) > 0:
            wavbytes = memoryview(evt.result.audio)
            filename = 'translated_' + str(time.time()) + '.wav'
            with open(filename, 'wb') as out:
                out.write(wavbytes)
```
  - I've attached a working example that you can try out, edit to add your own subscription key and service region as usual.
[example.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/5576780/example.zip)

**Comment by pankopon** [comment]
Closed as answered, please create a new issue if you need more support on specific topics.
