### ISSUE TITLE
IPhone IOS not sending audio when use video chat with Speech to Text Conversation Translator

### ISSUE THREAD

**Issue by nuenook** [Azure-Samples/cognitive-services-speech-sdk#804]
**Describe the bug**
My website is Video Chat, so I want to use Speech to text translation on my website
but when I turn on Speech to text, Safari cannot send audio, in the other hand when try to restart audio it can send audio but no translation text, it seems safari only reserve one Microphone?

**To Reproduce**
1. goto my example web https://nuenook.github.io/ then click allowed Mic/Video
2. test Speaking, I can hear myself
3. Start Speech to text by input token/region then click start Speaking
4. The text is shown but I cannot hear myself anymore 

 Example webRTC from https://webrtc.github.io/samples/
 Room Translator from https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/javascript/browser/multi-device-conversation
**Expected behavior**
If not bug, do you have a solution or guide for solving?
**Version of the Cognitive Services Speech SDK**
"microsoft-cognitiveservices-speech-sdk": "^1.13.0"

**Platform, Operating System, and Programming Language**
 - OS: IOS 14
 - Hardware - Iphone 8
 - Programming language: JavaScript
 - Browser Safari

**Additional context**
It happens only Safari on iPhone, Safari on Mac is working

Thank you

**Comment by brandom-msft** [comment]
Hi @nuenook - thanks for raising this issue. Since it pertains to the JS SDK, I'm going to open it as an issue in that repo and will reply there. https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/243

I'll be closing this issue but please reactivate and let me know if I've misunderstood anything here.
