### ISSUE TITLE
What is best practices to performance to use Microsoft.CognitiveServices.Speech with file?

### ISSUE THREAD

**Issue by pabloandrei** [Azure-Samples/cognitive-services-speech-sdk#806]
I have a doubt.
I am using Microsoft.CognitiveServices.Speech on Azure, the requests use WAV file type that has 1 hour audio media.

Before sending to Azure, I set the file format to "ffmpeg -acodec pcm_s16le -ac 1 -ar 16000"

My perception that the delay in voice recognition is 1 to 1, that is, if the audio file has 1 hour, the processing takes 1 hour as well.

Is there any way to get more performance?

Location: brazilsouth
Type of service: S0 Standard

Code:
`using (var audioInput = AudioConfig.FromStreamInput(new PullAudioInputStream(new BinaryAudioStreamReader(
                                    new BinaryReader(File.OpenRead(filePath))),
                                    AudioStreamFormat.GetCompressedFormat(AudioStreamContainerFormat.MP3))))`

**Comment by brandom-msft** [comment]
Hi @pabloandrei - there isn't a specified or guaranteed speed declared for long-form audio, but generally I've found the completion time to be shorter than the file duration. (I want to stress this is generalization based on my own anecdotal usage, your turnaround time will vary but I would expect it to be some amount shorter than your audio file)

Closing this issue but feel free to comment-back here with further questions/comments.
