### ISSUE TITLE
Text to speech stop or pause option

### ISSUE THREAD

**Issue by Selvaraj314** [Azure-Samples/cognitive-services-speech-sdk#807]
**Describe the bug**

After start speech, is that any option is there to stop/pause/cancel the audio session?

I am using following code for speak the text.

`var speechSynthesizerResult: SPXSpeechSynthesisResult?
        do {
            try speechSynthesizerResult = speechSynthesizerVal.startSpeakingText(inputTextVal)
        } catch  {
            print("SPEECH SYNTHESIZER RESULT: \(error)")
            speechSynthesizerResult = nil
        }`

**Expected behavior**
Need to stop/pause/cancel the audio session while playing.

**Platform, Operating System, and Programming Language**
 - iOS
 - SWIFT

**Comment by brandom-msft** [comment]
Hi @Selvaraj314 - as you've found, there is functionality provided for starting playback of a text string. Beyond that, additional media controls (like pause/stop) would need to be implemented per your app/program's needs.

I'm resolving this issue as "closed" but please don't hesitate to reach out with any other questions or feedback!
