### ISSUE TITLE
The Speech-To-Text service does not support Korean. I wonder when I plan to apply.

### ISSUE THREAD

**Issue by kaki104** [Azure-Samples/cognitive-services-speech-sdk#81]
**Is your feature request related to a problem? Please describe.**
Bing Speech Service supports Korean in the Speech-To-Text service. I would like to use the new Speech SDK but I was using Bing Speech service because it does not support Korean language. I am worried that it will be canceled after one year.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Speech SDK can be made to support Korean. Also, the quality of the Korean voice supported by the Text-To-Speech service is not very good. So, I am using AWS Polly. Of course, it is possible because there are few users, but I think that it is better to provide better service in this case to win another AWS or Google.

**Additional context**
As a Korean MVP, I hope that Microsoft will expand the Korean language service in Korea and use it for many developers.

**Comment by wolfma61** [comment]
the SDK is not responsible for deciding when/if a new language gets added. 
We also can deny/confirm and language support.
You should other support options described here. 
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/support

Not sure what other options are available for you as an MVP

For feature requests etc I believe this is the best choice: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/support#uservoice-forum
