### ISSUE TITLE
System.DllNotFoundException in Microsoft.CognitiveServices.Speech.Internal.Speech Config.speech config_from e

### ISSUE THREAD

**Issue by gabser10** [Azure-Samples/cognitive-services-speech-sdk#810]
Running a WPF application in a clean Windows 10 1909 version generate an exception of missing dll.

**Comment by brandom-msft** [comment]
Hi @gabser10 - 

Can you share more about your WPF project setup? 
Also, how are you including the SDK in your project?
And which version of the SDK are you using?

**Comment by gabser10** [comment]
Hi @brandom-msft, thank you for your response. I've solved the error by installing Microsoft Visual C++ Redistributable for Visual Studio 2019 in the system implementing the application and now works.
I use NuGet Package Manager to include the SDK in version 1.12,
