### ISSUE TITLE
Azure text-to-speech is not accessable in Windows 2012 r2

### ISSUE THREAD

**Issue by sprgchma** [Azure-Samples/cognitive-services-speech-sdk#811]
**Describe the bug**

1. https://azure.microsoft.com/en-us/updates/azuretls12/ - here MS says that they are going to switch to tls12, it is okey. Win2012r2 support this version of TLS.

2. Here the list of cipher that win10 supports: https://docs.microsoft.com/en-us/windows/win32/secauthn/tls-cipher-suites-in-windows-10--version-1507

    It contains following ciphers suites

   ```
   TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
   TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 
   ```
3. Here the list of cipher that win2012r8 (aka win8.1) supports: https://docs.microsoft.com/en-us/windows/win32/secauthn/tls-cipher-suites-in-windows-8-1

    It does not contain the cipher suites from above

4. And this is Azure endpoint of text-to-speech API: https://southeastasia.tts.speech.microsoft.com/cognitiveservices/v1

   With help of this utils https://github.com/rbsec/sslscan i have scanned the site above to see what cipher suites it supports
   
   ```
   > sslscan.exe --tls1.2 southeastasia.tts.speech.microsoft.com
   ...
   Connected to 20.43.132.2
   Testing SSL server southeastasia.tts.speech.microsoft.com on port 443 using SNI name southeastasia.tts.speech.microsoft.com
   ...
   Supported Server Cipher(s):
   Preferred TLSv1.2 128 bits ECDHE-RSA-AES128-GCM-SHA256 Curve 25519 DHE 253 <<< win10 only
   Accepted TLSv1.2 256 bits ECDHE-RSA-AES256-GCM-SHA384 Curve 25519 DHE 253 <<< win10 only
   Accepted TLSv1.2 256 bits ECDHE-RSA-CHACHA20-POLY1305 Curve 25519 DHE 253 <<< non-win at all
   ...
   ```

It appears that text-to-speech TLS supports only three suites:
- one is not supported by any windows version,
- and other two are supported only by windows 10

So win2012 server is not supported by azure text-to-speech, 

**To Reproduce**

Try to get tts voices list like described  in the documentation, here the powershell script

``` powershell
# getlang.ps1

$RestHeader = @{
  'Content-type'='application/x-www-form-urlencoded';
  'Content-Length'= '0';
  'Ocp-Apim-Subscription-Key' = 'TTS-SUBSCRIPTION-KEY';
}
$bearer = Invoke-RestMethod -Method POST -Uri `
 "https://southeastasia.api.cognitive.microsoft.com/sts/v1.0/issueToken" `
 -Headers $RestHeader

Write-Host $bearer

$RestHeader = @{
  'Authorization' = 'Bearer '+$bearer;
}
$langs = Invoke-RestMethod -Method Get -Uri `
  "https://southeastasia.tts.speech.microsoft.com/cognitiveservices/voices/list" `
  -Headers $RestHeader

$langs
```

- on win10 the script works,
- on 2012/2008 it successfully fetches the token and then get an exception 'The request was aborted: Could not create SSL/TLS secure channel.' on the second `Invoke-RestMethod`.

**Expected behavior**

It should work on win2012r2

**Version of the Cognitive Services Speech SDK**

no sdk, plain http requests. 

**Platform, Operating System, and Programming Language**

 - OS: Windows 2012r2
 - Hardware - x64
 - Programming language: C#

**Comment by brandom-msft** [comment]
Hi @sprgchma - I'm raising this with the team to find the best person suited to get support, I'll update you when I have more. Thanks!

**Comment by jhakulin** [comment]
@wolfma61 Would you comment on this, using rest API should work on Windows Server 2012 R2 which is based on Windows 8.1?

**Comment by sprgchma** [comment]
As for 2020-10-04 the scanning gives five cipher suites:

```
Preferred TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384   Curve 25519 DHE 253
Accepted  TLSv1.2  256 bits  ECDHE-RSA-CHACHA20-POLY1305   Curve 25519 DHE 253
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-GCM-SHA256   Curve 25519 DHE 253
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA384       Curve 25519 DHE 253
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-SHA256       Curve 25519 DHE 253
```

Last two ones are supported by win2012r2 (and by win2008r2). So for now problem is resolved by Azure team.
