### ISSUE TITLE
Cognitive does not exsist error.

### ISSUE THREAD

**Issue by 3Park** [Azure-Samples/cognitive-services-speech-sdk#812]
Hello. I am using Unity to make an app for iOS, Android and StandAlone PC.
I made an Unity project and imported Microsoft.CognitiveServices.Speech.1.13.0.unitypackage to use STT and TTS.

There is no problem for building Android and StandAlone PC by setting on Unity but,
for building iOS, it makes some errors even though I set the build setting to ARM64.

The most represent error is that Cognitive does not exsist in the namespace Microsoft.

In this site : https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/setup-platform?tabs=unity%2Cmacos%2Cjre%2Cbrowser&pivots=programming-language-csharp

It says the unitypackage supports iOS ARM32 and 64 but it makes some error. 
How can I solve this problem??

**Comment by jhakulin** [comment]
@3Park Thanks for question, did you check the instructions here: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/unity/from-microphone#build-and-run-the-sample-for-ios-platform ? Specifically Under Project > Assets > SpeechSDK > Plugins > iOS, check that Microsoft.CognitiveServices.Speech.csharp.dll target is enabled for Editor and iOS platforms.

**Comment by 3Park** [comment]
oh, I will check it. thanks

**Comment by jhakulin** [comment]
@3Park Let us know if you still see the issue, if not the issue closes soon

**Comment by jhakulin** [comment]
Closing the issue, let us know if more info is needed.
