### ISSUE TITLE
Issue with local image: mcr.microsoft.com/azure-cognitive-services/speechservices/speech-to-text:latest 

### ISSUE THREAD

**Issue by pabloandrei** [Azure-Samples/cognitive-services-speech-sdk#814]
I recently signed up at https://customervoice.microsoft.com/, to be able to run container or docker from the mcr.microsoft.com/azure-cognitive-services/speechservices/speech-to-text:latest image locally.
After a long wait, I received an email with the release to use the image.

After downloading the image, I tried to run the docker as instructed at: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-container-howto 

I have the following error, would anyone know what the workaround solution is?

`Unhandled Exception: System.Exception: Model configuration /usr/local/models/properties.json not found.
   at Microsoft.CloudAI.Containers.Common.EnvironmentVariants.IsCustomContainer()
   at Microsoft.CloudAI.Containers.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.CloudAI.Containers.Program.Main(String[] args)
./run-host: line 75:    54 Aborted                 (core dumped) "$@"
./run-host: line 82: kill: (54) - No such process
Process start failed for: dotnet Microsoft.CloudAI.Containers.SpeechToText.dll Eula=accept Billing=https://brazilsouth.api.cognitive.microsoft.com/sts/v1.0/issuetoken ApiKey=*********
/onprem_start
grep: /usr/local/models/properties.json: No such file or directory
/dpp /onprem_start
/onprem_start
/mts /onprem_start
/onprem_start
/diarizer /onprem_start
/onprem_start
/textclassifier/app /onprem_start
/onprem_start
`

**Version of the Cognitive Services Speech SDK**
mcr.microsoft.com/azure-cognitive-services/speechservices/speech-to-text:latest

**Platform, Operating System, and Programming Language**
 - OS: Linux Ubuntu 20
 - Hardware - x64,
 - Programming language: C#
 

**Additional context**
![image](https://user-images.githubusercontent.com/16004192/94269427-061a3b80-ff15-11ea-938d-347f49adb0b0.png)

**Comment by yshahin** [comment]
The command shows you are using cutom-speect-to-text not speech-to-text. This container requires a custom model id to be supplied. Please update the command and it should work.
If you are looking to create a custom speech to text model you can check the portal https://speech.microsoft.com/

**Comment by jhakulin** [comment]
Closing the issue, let us know if there is more information needed.

**Comment by pabloandrei** [comment]
> The command shows you are using cutom-speect-to-text not speech-to-text. This container requires a custom model id to be supplied. Please update the command and it should work.
> If you are looking to create a custom speech to text model you can check the portal https://speech.microsoft.com/

In fact, I forgot about the model. Thank you!
