### ISSUE TITLE
addConversationParticipantsChangedEventHandler not getting called in iOS  after joining conversation with conversation id or on starting the conversation

### ISSUE THREAD

**Issue by srinivasdr** [Azure-Samples/cognitive-services-speech-sdk#815]
**Describe the bug**
ConversationTranslator addConversationParticipantsChangedEventHandler not getting called in iOS Swift code base after joining conversation with conversation code

**To Reproduce**
1. Create a conversation in https://translator.microsoft.com/ in desktop browser
2. Join the same conversation from iOS swift using conversation code create through above step
3. Join the same conversation in other desktop browser window

Same issue is observed when we start the conversation from iOS:
1.  Start conversation from iPad
2. Join the same conversation  https://translator.microsoft.com/  with code obtained from above created conversation

**Expected behavior**
addConversationParticipantsChangedEventHandler in iOS should be called as new participant was joined to conversation

**Version of the Cognitive Services Speech SDK**
latest

**Platform, Operating System, and Programming Language**
 - OS: iOs 14
 - Hardware - x64
 - Programming language: Swift
 

**Additional context**
 - Error messages, log information, stack trace, ...
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by jhakulin** [comment]
@srinivasdr Thanks for the report, we will check this and let you know.

**Comment by srinivasdr** [comment]
Same issue is observed even when we try to start conversation too from iPad  swift code

**Comment by jhakulin** [comment]
@srinivasdr We have a fix which will be released on the next 1.14.0 release. 
As a workaround please make sure that your app is registered to canceled event using addCanceledEventHandler, did you have that in your app ?

**Comment by srinivasdr** [comment]
Thank you @jhakulin 
But The work around here you suggested won’t give all participants info  in a room I believe.
is there any work around where we can get info of all participants inside ios SDK who joins and leaves room like how we can query like e.participnats inside addconversationparticipantschanged event handler

**Comment by ralph-msft** [comment]
@srinivasdr please make sure that you are calling addCanceledEventHandler first, then calling addConversationParticipantsChangedEventHandler afterwards. You need to call those two methods ___before___ you call joinConversationAsync.

The first conversation participants changed event raised will always contain all the participants in the conversation. The events after that will reflect the deltas (e.g. participant left, participant changed their nickname, new participant joined).

**Comment by srinivasdr** [comment]
Thank you @ralph-msft. Will check that and let you know

**Comment by jhakulin** [comment]
Fix will be included in 1.14.0, closing the issue.
