### ISSUE TITLE
Unreal engine Cognitive services integration

### ISSUE THREAD

**Issue by smartcharith** [Azure-Samples/cognitive-services-speech-sdk#817]
How can I integrate C++ Sdk into UE4?
Please help!

**Comment by jhakulin** [comment]
@smartcharith Currently speech SDK does not have Unreal engine support in released packages. Without knowing much details about Unreal engine requirements, I would assume it is possible to create native C++ plugins there which would utilize speech SDK native libraries. Which platform you are using, Android, iOS, Windows or something else?

**Comment by smartcharith** [comment]
platform Windows

**Comment by jhakulin** [comment]
We have made a backlog item for this issue, however there is no ETA for the support for Unreal at the moment. Closing the case.

**Comment by lucoiso** [comment]
@smartcharith 

I created a plugin that I've been working on that integrates the Azure Speech SDK into the unreal engine: https://github.com/lucoiso/UEAzSpeech
