### ISSUE TITLE
Unit tests for Objective-C quickstart example are not running in Xcode

### ISSUE THREAD

**Issue by rozele** [Azure-Samples/cognitive-services-speech-sdk#82]
**Describe the bug**
After checking out the Objective-C quickstart sample and downloading/adding the Speech SDK dependency, I cannot run the UI tests from Xcode. The app runs on the simulator, but the UI tests do not. I believe there is something missing in the .xcodeproj.

**To Reproduce**
1. Clone the repo
2. Add the Speech SDK dependency
3. Set your speech key and region
4. Confirm the app runs correctly on the simulator.
5. Try to run tests from Xcode

**Expected behavior**
Tests run and pass.

**Version of the Cognitive Services Speech SDK**
Version downloaded from https://aka.ms/cssspeech/iosbinary on 10/17/2018

**Platform, Operationg System, and Programming Language**
 - OS: iOS
 - Hardware: Simulator
- IDE: Xcode 10
- Language: Objective-C

**Additional context**
 - Error messages, log information, stack trace, ...
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by chlandsi** [comment]
This should be fixed by #83 .
