### ISSUE TITLE
Error Encountered When Trying To Import azure.cognitiveservices.speech

### ISSUE THREAD

**Issue by terencebeh** [Azure-Samples/cognitive-services-speech-sdk#821]
I am going through this exercise on Microsoft site (https://docs.microsoft.com/en-gb/learn/modules/transcribe-speech-input-text/5-exercise-convert-speech-from-audio-file?pivots=python)

Using: 
1. Visual Studio Code
2. Python version - Python 3.7.4 (also have Python 3.8.5 installed)
3. MacOS

Error Encountered: 
Run Python in the terminal

/usr/local/bin/python3 /Users/comp/Python/SpeechToTextPython/speechtotext.py

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
(base) $ /usr/local/bin/python3 /Users/userid/Python/SpeechToTextPython/speechtotext.py
Traceback (most recent call last):
  File "/Users/userid/Python/SpeechToTextPython/speechtotext.py", line 1, in <module>
    import azure.cognitiveservices.speech as speechsdk
ModuleNotFoundError: No module named 'azure'

**To Reproduce**
As above.

**Expected behavior**
As stated in the exercise.

**Version of the Cognitive Services Speech SDK**
Requirement already up-to-date: azure-cognitiveservices-speech in /Users/userid/opt/anaconda3/lib/python3.7/site-packages (1.13.0)

**Platform, Operating System, and Programming Language**
 - OS: MacOS
 - Programming language: Python
 - Browser: Chrome

Really appreciate help here.

**Comment by chlandsi** [comment]
Hi @terencebeh, it looks like the Python interpreter you are using (/usr/local/bin/python3, which may be from Homebrew) is not the one where the speech sdk is installed (judging from this path /Users/userid/opt/anaconda3/lib/python3.7/site-packages).  Please try to either explicitly use the anaconda interpreter for the sample, or install the Speech SDK package with the pip in `/usr/local/bin/pip3`.

**Comment by pankopon** [comment]
@terencebeh Was your issue resolved by the suggestions? Please update.

**Comment by pankopon** [comment]
Closed as answered. Please create a new issue if you need further support on any specific topics.
