### ISSUE TITLE
combine 2 channels' output into 1 single conversation in proper time order

### ISSUE THREAD

**Issue by celinef** [Azure-Samples/cognitive-services-speech-sdk#823]
Awesome samples! Thank you. I'm using cognitive-services-speech-sdk/samples/batch/transcription-enabled-storage/  AS IS.

The json output has this bit shown below, and I will only need to use the display property (bolded). 
 
"combinedRecognizedPhrases": [
    {
      "channel": 0,
      **"display": "Thank you for calling XYZ. How may I help you? Till five o'click. Thank you bye bye."**
    },
    {
      "channel": 1,
      **"display": "Hi, what time are you open today? OK alright, i'll come in soon"**
    }
  ]

Is it possible to arrange the 2 channels in time order so that I get back the full conversation in proper time order? In this example, I'd like to see:

 **"display": "Thank you for calling XYZ. How may I help you? Hi, what time are you open today? Till five o'clock. Ok alright, I'll come in soon. Thank you bye bye."**

There may be a CombinedResult property that replaces SegmentResults, but I couldn't find either SegmentResults nor CombinedResult in the code base.

Thank you!

**Comment by zhouwangzw** [comment]
Yes, you can based on timing info (offset and duration) in recognizedPhrases to combine results of each channel to single output with proper time order.
CombinedResult and SegmentResults are fields in the result files for V2 API. And for the new V3 API, please use combinedRecognizedPhrases and recognizedPhrases.
Thanks,

**Comment by celinef** [comment]
Thank you Zhou Wang!
