### ISSUE TITLE
E/AudioRecord: start() status -38

### ISSUE THREAD

**Issue by ramesh123456** [Azure-Samples/cognitive-services-speech-sdk#824]
**E/AudioRecord: start() status -38**
i get this error how can i solve this error

**Comment by jhakulin** [comment]
@ramesh123456 Could be that your app tries to open microphone while it is already reserved by some other process/object. 
Could you please share information how your app uses Speech SDK?

**Comment by jhakulin** [comment]
Closing as missing information from customer
