### ISSUE TITLE
Getting error: 'swagger_client' has no attribute 'DefaultApi'

### ISSUE THREAD

**Issue by stefaner1** [Azure-Samples/cognitive-services-speech-sdk#826]
**Describe the bug**
When running Runing cognitive-services-speech-sdk batch python module:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/python/python-client/main.py
I get:
`module 'swagger_client' has no attribute 'DefaultApi'
`

**To Reproduce**
1. using instruction on website: https://docs.microsoft.com/pl-pl/azure/cognitive-services/speech-service/quickstarts/from-blob?pivots=programming-language-python

**Platform, Operating System, and Programming Language**
 - OS:  Linux Ubuntu 20
 - Hardware - x64
 - Programming language: Python 3.7

**Comment by chlandsi** [comment]
Please use [this sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/python), and make sure you are using the corresponding version of the swagger client. To be sure, run `pip uninstall swagger_client` before installing the new version.
