### ISSUE TITLE
Time out  error while using azure cognitive api services

### ISSUE THREAD

**Issue by rathdebi** [Azure-Samples/cognitive-services-speech-sdk#827]
Hi Team,

Trust you are doing well.  

This is Debi Prasad from Xebia. We are the gold partner for Microsoft . 

 I am using azure cognitive services api for ocr-text extraction . While doing so many documents are not being picked up due to time out exception.  It seems that api is not working as expected with post and get request there by having a significant delay in write operation . Adding on, we have to deliver the project with very strict timelines. Please help us in resolving this issue , to find a way at the earliest. 

For better clarity, please refer to below error , 

File "/home/debi/xebia projects/scanner/venv/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out',))

Regards,
Debi Prasad Rath

**Comment by chlandsi** [comment]
This repository handles samples and issues for the Cognitive Services *Speech* SDK. Please engage with customer support or use one of the methods listed [here](https://docs.microsoft.com/en-us/azure/cognitive-services/form-recognizer/) to get support for your issue.
