### ISSUE TITLE
Can't install this package in raspOS

### ISSUE THREAD

**Issue by Ad1tyaV** [Azure-Samples/cognitive-services-speech-sdk#828]
When I try to install **azure-cognitiveservices-speech** on Rasp OS, I get error:
_No matching distribution found for azure-cognitiveservices-speech_
```
root@raspberrypi:~# pip install azure-cognitiveservices-speech
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech (from versions: none)
ERROR: No matching distribution found for azure-cognitiveservices-speech
```

Is there support for rasp OS for this package ?

**Comment by chlandsi** [comment]
As a first step, please make sure you are using Python 3 (>= 3.5). Python 2 is not supported by this package.

**Comment by Ad1tyaV** [comment]
```
pi@raspberrypi:~/Downloads $ python3 --version
Python 3.7.3
pi@raspberrypi:~/Downloads $ pip3 install azure-cognitiveservices-speech
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech (from versions: none)
ERROR: No matching distribution found for azure-cognitiveservices-speech

```

**Comment by chlandsi** [comment]
Right, Rasp OS is actually not supported; sorry for the misleading first guess. The supported distributions are listed [here](https://docs.microsoft.com/en-gb/azure/cognitive-services/speech-service/speech-sdk?tabs=linux%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio#get-the-speech-sdk).

**Comment by stepkillah** [comment]
Any suggestions where `raspOS` will be supported?

**Comment by pankopon** [comment]
There are no plans for it at the moment. Please use one of the supported distributions for now. In addition to those currently listed in [system requirements](https://docs.microsoft.com/azure/cognitive-services/speech-service/speech-sdk?tabs=linux%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio#get-the-speech-sdk), Debian 10 and Ubuntu 20.04 LTS will be officially supported in the Speech SDK 1.14 release.
