### ISSUE TITLE
speechConfig.setProperty does not accept enum as first argument. Throws type error in TypeScript. Is there any other way to set InitialSilenceTimeout?

### ISSUE THREAD

**Issue by saikiahemant** [Azure-Samples/cognitive-services-speech-sdk#829]
**Describe the bug**
I am trying to set InitialSilenceTimeout and EndSilenceTimeout, in a nodeJS project. I am using typescript to code this.

```speechConfig.setProperty(sdk.PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs, "10000");```

I get the following error. 
```
Argument of type 'import(".../node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/sdk/PropertyId").PropertyId' is not assignable to parameter of type 'string'
```

**To Reproduce**
1. Create a typescript project 
2. Initialize recognizer using the following code.
```
import * as sdk from "microsoft-cognitiveservices-speech-sdk";

pushStream = sdk.AudioInputStream.createPushStream(AudioStreamFormat.getWaveFormatPCM(8000, 16, 1));
const speechConfig = sdk.SpeechConfig.fromSubscription(subscriptionKey, "centralindia");
const audioConfig = sdk.AudioConfig.fromStreamInput(pushStream);
let sdkRecognizer = new sdk.SpeechRecognizer(speechConfig, audioConfig);
// the next line throws an error
speechConfig.setProperty(sdk.PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs, "10000");
```
3. Or else use my test repo. The file is 
[https://github.com/saikiahemant/azure-streaming-server/blob/master/src/utils/azureutil.ts](https://github.com/saikiahemant/azure-streaming-server/blob/master/src/utils/azureutil.ts)

**Expected behavior**
Like NodeJS where the example works, since type constraints aren't there. I would somehow be able to set Initial and End silence timeout properties. 

**Version of the Cognitive Services Speech SDK**
 "microsoft-cognitiveservices-speech-sdk": "^1.13.1"

**Platform, Operating System, and Programming Language**
 - OS: macOS Catalina
 - Hardware - x86_64
 - Programming language: Typescript

**Additional context**
 -I can see that ```SpeechConfig.fromSubscrition(``` returns a ```SpeechConfig``` where the definition of the function is ``` setProperty(name: string, value: string): void; ```. And hence the problem. Since enum is not string.  
-SpeechConfigImpl object extends SpeechConfig class and has the setProperty function that would take an enum. But I haven't figured out how to use that.

**Comment by saikiahemant** [comment]
The current implementation if the ```fromSubscription``` method returns a SpeechConfig object.
[https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/sdk/SpeechConfig.ts#L41](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/sdk/SpeechConfig.ts#L41)

I am re-implementing the method, and keeping the return type as SpeechConfigImpl, which let' me send enum in setProperty function.
```const fromSubscriptionMine = (region: string, subscriptionKey: string):```**sdk.SpeechConfigImpl**

Is this the right way to do it?  I am still not getting desired results of timeouts yet.
```speechConfig.setProperty(sdk.PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs, "6000");```
The setting is the above. And I am still recognizing an audio with 10sec initial silence. Am I wrong somewhere?

**Comment by glharper** [comment]
@saikiahemant Please use
`
  speechConfig.setProperty(sdk.PropertyId[sdk.PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs], "10000");`

Several usage examples are available [here](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/tests/SpeechConfigTests.ts)

**Comment by saikiahemant** [comment]
Awesome. That is definitely the right way to do it. Thank you. 

I am still not getting the desired timeouts though. I am still recognising audios with 10s initial silence, when the setting is clearly for 2 s.

**Comment by glharper** [comment]
My guess would be the service does not allow lower than 5s. SDK passes the 2s value on, but the end service silently says and processes with a default 10s timeout. I'd try higher values like 4, 5, and 8 seconds.

[Here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/502#issuecomment-585987283) is an good explanation of the recognition parameters, if this is something you'd care to investigate and learn more about.

**Comment by saikiahemant** [comment]
Thanks
