### ISSUE TITLE
speaker recognition - verification - quickstart for javascript node and browser not working

### ISSUE THREAD

**Issue by muhmuhcow** [Azure-Samples/cognitive-services-speech-sdk#831]
**Describe the bug**
After following instructions for the quickstart and running the script the following error is received after around 5 seconds
CREATE PROFILE ERROR:
'Unhandled callback error: SyntaxError: Unexpected token R in JSON at position 0'

**To Reproduce**
Follow instructions for voice verification quickstart for javascript node and/or browser

**Expected behavior**
Profile is able to be created.

**Version of the Cognitive Services Speech SDK**
Speech SDK Release 1.13.0

**Platform, Operating System, and Programming Language**
 - OS: Mac Catalina Version 10.15.7
 - Hardware - 2.3 GHz 8-Core Intel Core i9
 - Programming language: JavaScript
 - Browser: Chrome

**Additional context**
 'Unhandled callback error: SyntaxError: Unexpected token R in JSON at position 0'
CREATE PROFILE ERROR

**Comment by muhmuhcow** [comment]
forgot to set location as westus and used westus2 instead

**Comment by yoshigev** [comment]
If anyone else is getting this issue, note that currently only `westus` region is supported (see https://azure.microsoft.com/en-us/global-infrastructure/services/?products=cognitive-services).

Also, the `SyntaxError: Unexpected token R in JSON at position 0` error is actually hiding the error `Request took longer than expected` (which is not handled correctly by the SDK).
