### ISSUE TITLE
Keyword Recognition with DialogServiceConnector

### ISSUE THREAD

**Issue by marcominerva** [Azure-Samples/cognitive-services-speech-sdk#832]
I'm trying Custom Commands with Keyword Recognition feature. I have a code like the following (the computer.table file is taken from https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/blob/master/keyword-models/computer.table.):

```
var config = CustomCommandsConfig.FromSubscription(Constants.CustomCommandsAppId, Constants.SubscriptionKey, 
             Constants.Region);
config.Language = Constants.Language;

var connector = new DialogServiceConnector(config, AudioConfig.FromDefaultMicrophoneInput());
// Connector Events registration...

await connector.ConnectAsync();

var wakeWordModel = KeywordRecognitionModel.FromFile(@"D:\Computer.table"));
_ = connector.StartKeywordRecognitionAsync(wakeWordModel);
```

I have noticed that, after the Recognized event of **DialogServiceConnector** with _RecognizedKeyword_ reason, the next Recognized event with _RecognizedSpeech_ reason contains also the keyword itself in the speech-to-text result: For example, if I say "computer" (the keyword) and then "turn off the tv", the Recognized event with _RecognizedSpeech_ reason returns the text "computer turn off the tv", so the intent recognition fails (because I have trained Custom Commands without the keyword).

Is this the expected behavior? Should I train Custom Commands taking care of the keyword?

**Comment by dargilco** [comment]
@marcominerva There is a setting in Custom Command authoring portal to specify the keyword the client used for activation. I believe once you enter the keyword there, Custom Command will strip away that keyword if it appears at the beginning of the sentence, so you do not need to train with the keyword.

**Comment by marcominerva** [comment]
Oh... You're right, I totally missed the Custom Keyword Settings page on Custom Commands. Thank you for pointed me to it!

**Comment by dargilco** [comment]
@marcominerva if this feature is missing from the [Custom Commands documentation](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/custom-commands), can you please enter a feedback at the bottom of a relevant document page? I will follow up with the Custom Command team to make sure it's documented. Thanks!

**Comment by marcominerva** [comment]
Done: https://github.com/MicrosoftDocs/azure-docs/issues/64238. Thank you for your support!
