### ISSUE TITLE
Custom Commands Web Endpoint called twice

### ISSUE THREAD

**Issue by marcominerva** [Azure-Samples/cognitive-services-speech-sdk#837]
I'm trying to use a Web Endpoint with my Custom Commands. The guide available at https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-custom-commands-setup-web-endpoints says that I can retrieve HTTP Response by using a particular syntax:

![image](https://user-images.githubusercontent.com/3522534/96279842-82b1ae80-0fd7-11eb-9317-14dd22979822.png)

However, I have noticed that, if I specify such a field in the "On success" tab of the "Call web endpoint" configuration dialog:

![image (1)](https://user-images.githubusercontent.com/3522534/96279874-8cd3ad00-0fd7-11eb-97cb-88d982148437.png)

The field `Message` is correctly retrieved from the response of my endpoint and included in the speech response, but the web endpoint is called twice. If I remove the reference to the HTTP Response (leaving only "OK"), is it called only one time. 

I have also tried creating a new Custom Commands project, but the behavior is the same.

Could someone help me with this issue?

**Comment by dargilco** [comment]
Hi @marcominerva, thank you for reporting this! I'll let the Custom Command service team know about it right away. They or I will reply here. Darren.

**Comment by dargilco** [comment]
@marcominerva, the Custom Command service team will take a look at this bug this week.

**Comment by marcominerva** [comment]
Thank you for your support!

**Comment by dargilco** [comment]
@marcominerva The Custom Command service team identified the regression that caused this bug, and a fix is in code review right now. The fix is expected to be deployed in a few days.
