### ISSUE TITLE
Set the recognition timeout to 5 seconds.

### ISSUE THREAD

**Issue by assitive** [Azure-Samples/cognitive-services-speech-sdk#838]
I am developing an application using C# SDK. Currently the maximum length of any utterance is around 15 seconds. I need to change it to 5 seconds for my application. Basically, I want to limit the utterances to 5 seconds maximum, how can this be achieved?

**Comment by rhurey** [comment]
Sorry, but the maximum phrase length isn't currently controllable from the SDK.

**Comment by assitive** [comment]
Or force it to end recognition in code and return the recognized text before the stop call?

**Comment by rhurey** [comment]
Calling StopContinuousRecongitionAsync() will stop audio capture and return results for the audio that's been captured.

**Comment by assitive** [comment]
My program calls RecognizeOnce, does StopContinuousRecongitionAsync stop recognize once?

**Comment by rhurey** [comment]
StopContinuousRecongitionAsync will stop either recognition mode.

**Comment by assitive** [comment]
The name of the function doesn't suggest it would stop recognize once. No way I would know this without actually trying it. Can you rename the function, and update the intellisense and documentation to make it more clear?

**Comment by rhurey** [comment]
When the API was originally designed, we'd not thought a single recognition needed a stop function. That was clearly an oversight.

We'll get the documentation updated. Re-naming the function would be a breaking change and is in plan for the next time we do a major release.

**Comment by pankopon** [comment]
Closed since answered, there is now a work item on our backlog to update documentation on this.
