### ISSUE TITLE
Troubleshooting and Error Codes

### ISSUE THREAD

**Issue by jewwy** [Azure-Samples/cognitive-services-speech-sdk#84]
Hello, 

Trying to troubleshoot an issue with speech recognition from a wav file. The audio should be ok as we currently use Google Speech API with no issues. Under cognitive services everything seems to work ok with the Microsoft sample wav files however when giving it a custom wav file the follow error(s) display. 

Session started event.
(51): 38ms SPX_REPORT_ON_FAIL: (0x003) = 0x3
(51): 45ms SPX_RETURN_ON_FAIL: hr = 0x3
(51): 49ms SPX_REPORT_ON_FAIL: hr = recognizer_recognize_once_async_wait_for(hasync, 0xffffffffui32, phresult) = 0x3
(51): 64ms SPX_RETURN_ON_FAIL: hr = 0x3

I'm not sure how to make since of this? Also do we have any information on supported wav settings?

**Comment by rhurey** [comment]
The supported format is single-channel (mono) WAV / PCM with a sampling rate of 16 kHz.

**Comment by jewwy** [comment]
Thanks! Thinking this was the case but I could not find any references. Future plans for expanded support? Also was this documented somewhere?

**Comment by wolfma61** [comment]
what's you format in your file? I would really like to understand what broke...
having your sessionId and time you tried this, might help to investigate on the service.

some other formats work (PCM), so we are a 'little bit' flexible

we will support also addition formats in the future.
If you are mostly interested in transcribing from files, I would recommend the batch APIs. There are also additional format supported for batch API
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription

**Comment by jewwy** [comment]
Thanks for the links guys! I knew I was missing the documentation somewhere :). Great help!

This case was Mono 16-Bit 11025Hz WAV audio produced from a video surveillance application.  Unfortunately the application goes from 11025Hz to 44100Hz so I knew I was off from the sample but couldn't identity how far off initially. Although it would be nice to see expanded support, this is more of a limitation within the application so it's not a major concern. I'll see if we can open a feature request with them for 16kHz support.

**Comment by jewwy** [comment]
Some more feedback here. The batch API seems to be based on Azure storage blobs.. It would be nice to see sample code / documentation reflecting a local storage option as this would be something worth trying on my end.

On the other hand using 16 kHz seems to slightly work under the original method. Still an issue with generic errors and limited information however maybe 1 of 10 recognition's do work and they have great accuracy! Hard to tell why the other 9 fail given the current state of error handling unfortunately.
