### ISSUE TITLE
Maximum number for transcripted text alternatives (NBest result)

### ISSUE THREAD

**Issue by mailong25** [Azure-Samples/cognitive-services-speech-sdk#840]
I'm using the recognize_once() function with detailed output format. I was able to get 5 different versions of recognized speech, denoted as NBest, where N = 5.
However, I want to retrieve more than 5 partial results. How can I set the number N using python SDK ?

Thanks

**Comment by pankopon** [comment]
Hi, NBest is the list of N best possible choices (so they are not exactly "partial"). They are ordered by most likely correct to least likely correct, and the number of them can vary based on the service internal thresholds. Unfortunately, this is not configurable on the SDK side.
