### ISSUE TITLE
Unable to contact server. StatusCode: 1006 && failed: HTTP Authentication failed; no valid credentials available

### ISSUE THREAD

**Issue by lkbansal1993** [Azure-Samples/cognitive-services-speech-sdk#844]
when we are used intend with luis but alway generate error with those code.
![Screenshot from 2020-10-26 19-58-46](https://user-images.githubusercontent.com/6930147/97185844-94106d00-17c6-11eb-8d6f-d618d1f758e3.png)

I used java-script code ()
can you help me for this issue?

please share usable solution for this issue.

**Comment by lisaweixu** [comment]
I will forward this question to our javascript dev to take a look.

**Comment by lkbansal1993** [comment]
> I will forward this question to our javascript dev to take a look.

thanks for given quickly response :+1:  
actually this issue is every sample of Luis intend used

**Comment by glharper** [comment]
@lkbansal1993 Could you ping me on teams and forward me the subscription key you're using for this? I'm glharper on teams.

**Comment by lkbansal1993** [comment]
> glharper

can you send email id which is on teams then we will discuss.

**Comment by glharper** [comment]
my id on teams is glharper, email is glharper@microsoft.com
