### ISSUE TITLE
Speech recognition requires constant and repetitive permission after a few minutes on being idle

### ISSUE THREAD

**Issue by inglesuniversal** [Azure-Samples/cognitive-services-speech-sdk#845]
I have noticed this issue on iPhone so far.

Is there a way that even though I use a remote LAMP server to generate a safe token, there is no need to authorize it so often?

I am using the javascript browser SDK (latest version) and an iPhone running iOS 14.

Hope I can get some ideas how to improve the UX.

STAY SAFE

**Comment by glharper** [comment]
@inglesuniversal I believe there is, first generate a token using the steps outlined [here](https://docs.microsoft.com/en-us/azure/cognitive-services/authentication?tabs=powershell#authenticate-with-an-authentication-token), then, on your server, make that token accessible under a name like "token.php" and in the client browser code, use [this sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/98d518a81e9cea55eb0cdb9b7178255da4d6060f/quickstart/javascript/browser/from-microphone/index.html#L44).

**Comment by pankopon** [comment]
@inglesuniversal Were you able to resolve the issue with the suggested steps? Please update.

**Comment by pankopon** [comment]
Closed as answered. Please create a new issue if you need further support on any specific topics.
