### ISSUE TITLE
Identify the evolution (percentage) of a transcription

### ISSUE THREAD

**Issue by homerokzam** [Azure-Samples/cognitive-services-speech-sdk#847]
How can I identify the percentage of a transcription using SpeechRecognizer with an input wav file?

Thanks

**Comment by homerokzam** [comment]
I have the following code:

      using (StreamWriter outputFromLanguageFile = new StreamWriter(fileTo))
      using (var audioInput = AudioConfig.FromWavFileInput(fileInput))
      using (var recognizer = new SpeechRecognizer(config, audioInput))
      {
        recognizer.Recognized += async (s, e) =>
        {
          if (e.Result.Reason == ResultReason.RecognizedSpeech)
          {
                ///
                /// How do I know the amount that has already been transcribed?
                ///
          }
        };

        await recognizer.StartContinuousRecognitionAsync().ConfigureAwait(false);
      }

**Comment by lisaweixu** [comment]
You can call e.Result.Duration and e.Result.OffsetInTicks to get the timing information. Duration means the total audio length in one hundred nanoseconds(HNS). OffsetInTicks for the phrase means the beginning of a phrase as detected by the Speech Recognition engine. Offset normally contains silence. OffsetInTicks is also in HNS.

**Comment by homerokzam** [comment]
Sorry but I don't understand how I can use these attributes.

I need to inform the user that the audio being transcribed has already processed 10%, 25%, 90%, 100%. With these attributes can I get that information?
