### ISSUE TITLE
Find a phrase in the audio file

### ISSUE THREAD

**Issue by homerokzam** [Azure-Samples/cognitive-services-speech-sdk#848]
After a transcription, how do I find the exact time of a certain text in the audio file?

Thanks

**Comment by lisaweixu** [comment]
You can find the word level time information after you turn on word level timestamps. The following is how to do it in C++.

```
       auto config = SpeechConfig::FromSubscription("YourSubScriptionKey", "YourRegion");
       auto audioInput = AudioConfig::FromWavFileInput("Whatstheweatherlike.wav");
       config->RequestWordLevelTimestamps();
       auto recognizer = SpeechRecognizer::FromConfig(config, audioInput);
       auto result = recognizer->RecognizeOnceAsync().get();
       auto detailedResult = result->Properties.GetProperty(PropertyId::SpeechServiceResponse_JsonResult);
```

The work level time information is in the  detailedResult->NBest->Words. Here is an example of a detailedResult:

`{"DisplayText":"What's the weather like?","Duration":13200000,"Id":"4f9204eaa8064cb1a79884ee96260d54","NBest":[{"Confidence":0.90865743,"Display":"What's the weather like?","ITN":"what's the weather like","Lexical":"what's the weather like","MaskedITN":"what's the weather like","Words":[{"Duration":3900000,"Offset":500000,"Word":"what's"},{"Duration":1300000,"Offset":4500000,"Word":"the"},{"Duration":2900000,"Offset":5900000,"Word":"weather"},{"Duration":4800000,"Offset":8900000,"Word":"like"}]},{"Confidence":0.92920566,"Display":"what is the weather like","ITN":"what is the weather like","Lexical":"what is the weather like","MaskedITN":"what is the weather like","Words":[{"Duration":3000000,"Offset":500000,"Word":"what"},{"Duration":600000,"Offset":3600000,"Word":"is"},{"Duration":1500000,"Offset":4300000,"Word":"the"},{"Duration":2900000,"Offset":5900000,"Word":"weather"},{"Duration":4800000,"Offset":8900000,"Word":"like"}]},{"Confidence":0.83604157,"Display":"what's the weather lie","ITN":"what's the weather lie","Lexical":"what's the weather lie","MaskedITN":"what's the weather lie","Words":[{"Duration":3900000,"Offset":500000,"Word":"what's"},{"Duration":1300000,"Offset":4500000,"Word":"the"},{"Duration":2900000,"Offset":5900000,"Word":"weather"},{"Duration":1400000,"Offset":8900000,"Word":"lie"}]},{"Confidence":0.90033555,"Display":"what's the weather","ITN":"what's the weather","Lexical":"what's the weather","MaskedITN":"what's the weather","Words":[{"Duration":3900000,"Offset":500000,"Word":"what's"},{"Duration":1300000,"Offset":4500000,"Word":"the"},{"Duration":3500000,"Offset":5900000,"Word":"weather"}]},{"Confidence":0.90259683,"Display":"what's the weather in","ITN":"what's the weather in","Lexical":"what's the weather in","MaskedITN":"what's the weather in","Words":[{"Duration":3900000,"Offset":500000,"Word":"what's"},{"Duration":1300000,"Offset":4500000,"Word":"the"},{"Duration":2500000,"Offset":5900000,"Word":"weather"},{"Duration":500000,"Offset":8500000,"Word":"in"}]}],"Offset":500000,"RecognitionStatus":"Success"}`

[Here](https://docs.microsoft.com/en-us/cpp/cognitive-services/speech/speechconfig) is the reference doc for RequestWordLevelTimestamps. [Here](https://docs.microsoft.com/en-us/cpp/cognitive-services/speech/recognitionresult) is the reference Duration and Offset.

I am using C++ in my example. Cognitive Service Speech SDK offers C#/Java/Python/Swift/objective-C/JavaScript support as well.
