### ISSUE TITLE
What are "Remote updates" in the Web endpoints section of Custom Commands?

### ISSUE THREAD

**Issue by marcominerva** [Azure-Samples/cognitive-services-speech-sdk#851]
Hi all!

I have noticed that a new toggle `Remote updates` has appeared in the Web endpoints section of Custom Commands, but I haven't found any reference to it in the documentation available at https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-custom-commands-setup-web-endpoints.

![image](https://user-images.githubusercontent.com/3522534/97808866-a9274900-1c69-11eb-8a56-258c2dc480d9.png)

Could you share some information about this feature?

Regards.

**Comment by encorona-ms** [comment]
Hi Marco, doc will be available soon, I'll update this thread with the link.

**Comment by pankopon** [comment]
@encorona-ms Is documentation still in the works? Please update.

**Comment by BrianMouncer** [comment]
@encorona-ms did we update the docs on this yet?

thanks.

**Comment by pankopon** [comment]
Closed since no further updates and a work item was identified, @encorona-ms please provide the doc link if/when completed.
