### ISSUE TITLE
Remote skills not available on Custom Commands

### ISSUE THREAD

**Issue by marcominerva** [Azure-Samples/cognitive-services-speech-sdk#852]
Hi!

According to https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-custom-commands-integrate-remote-skills, in the `Settings` section of Custom Commands I should find a `Remote skills` options. However, I dont' have such option (and `Key vault` and `JSON definition` neither) in my projects. 

I have also tried creating a new project, but with no success. I'm working with Speech resources in West Europe. 

Are these new features already deployed to all the regions?

Kindest regards.

**Comment by singhsaumya** [comment]
Hi @marcominerva 
Thanks for reporting the issue. This was a miss on our side, where the documentation went ahead of the feature launch :) 
Really sorry about that.

We just launched and verified the 'Remote Skills' feature. You don't need to create a new project to consume it, just use your existing application. Let us know if face any issues!

Regarding the other options which you see in the screenshot, please ignore them for now. We haven't officially launched those features, and the screenshot pertains to our development environment. I will update the image soon.

**Comment by marcominerva** [comment]
Hi!

Thank you very much for the update!

**Comment by glecaros** [comment]
Closing this as the concern seems to have been addressed. @marcominerva please reopen if you need more help.
