### ISSUE TITLE
Is it possible to add a function to pause the voice each time a period occurs in the text.

### ISSUE THREAD

**Issue by backnext321** [Azure-Samples/cognitive-services-speech-sdk#853]
For Speech Synthesis. I want to add a function to pause the voice each time a period occurs in the text. Resume can then be done manually. I try it this way:

edit: look at the code below

This works in a desktop Chrome browser. In Webview and chrome on Android text stops after 1 or 2 extra characters after the period.

**Comment by glharper** [comment]
@backnext321 Some actual classes for these objects would be helpful...what class is the "player" object you're using? Does it come from SpeechSDK?

**Comment by backnext321** [comment]
This is based on the sample SpeechSdkMaster (Microsoft Cognitive Services Speech SDK) (.../js/browser).
I want to make a little system to read text just by clicking on the text first and then resume with resumebutton "verder".
Reading should stop each time a period occurs in the text.
This works now with this code but it doesn't feel stable. I had to insert a "setTimeout(function..." on 2 places which is not the correct way I think.

`  
    <script src="microsoft.cognitiveservices.speech.sdk.bundle.js"></script>
    
    <script>
        var authorizationEndpoint = "token.php";
        function RequestAuthorizationToken() {
            if (authorizationEndpoint) {
                var a = new XMLHttpRequest();
                a.open("GET", authorizationEndpoint);
                a.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
                a.send("");
                a.onload = function () {
                    var token = JSON.parse(atob(this.responseText.split(".")[1]));
                    authorizationToken = this.responseText;
                }
            }
        }
    </script>
    
    <script>
        // On document load resolve the Speech SDK dependency
        function Initialize(onComplete) {
            if (!!window.SpeechSDK) {
                document.getElementById('content').style.display = 'block';
                document.getElementById('warning').style.display = 'none';
                onComplete(window.SpeechSDK);
            }
        }
    </script>
    
    <script>
        // status fields and start button in UI
        var highlightDiv;
        var startSynthesisAsyncButton, pauseButton, resumeButton, testknop;
        // subscription key and region for speech services.
        var subscriptionKey;
        var authorizationToken;
        var isSsml;
        var SpeechSDK;
        var synthesizer;
        var player;
        var wordBoundaryList = [];
        var leesTekst = "Dit is een testzin. Dit is de tweede zin. En hier heb je er nog eentje.";
        var puntGevonden = false;
        document.getElementById('testknop').style.backgroundColor = "#00ff00";
        document.getElementById("startSynthesisAsyncButtonID").innerHTML = leesTekst;
        document.addEventListener("DOMContentLoaded", function () {
            startSynthesisAsyncButton = document.getElementById("startSynthesisAsyncButtonID");
            testknop = document.getElementById("testknop");
            pauseButton = document.getElementById("pauseButton");
            resumeButton = document.getElementById("resumeButton");
            subscriptionKey = document.getElementById("subscriptionKey");
            isSsml = document.getElementById("isSSML");
            highlightDiv = document.getElementById("highlightDiv");

            setInterval(function () {
                if (player !== undefined) {
                    const currentTime = player.currentTime;
                    var wordBoundary;
                    for (const e of wordBoundaryList) {
                        if (currentTime * 1000 > e.audioOffset / 10000) {
                            wordBoundary = e;
                        } else {
                            break;
                        }
                    }
                    if (wordBoundary !== undefined) {
                        var zinBegin = leesTekst.substr(0, wordBoundary.textOffset);
                        var zinBegin2 = leesTekst.substr(0, wordBoundary.textOffset + (wordBoundary.text).length + 2);
                        var zinEinde = leesTekst.substr(wordBoundary.textOffset + wordBoundary.wordLength);
                        if ((zinBegin2.endsWith(". ")) && puntGevonden == false) {
                            setTimeout(function () { document.getElementById('pauseButton').click(); }, 900);//***
                            puntGevonden = true;
                            document.getElementById('testknop').style.backgroundColor = "#ff00ff";
                        } else {
                            highlightDiv.innerHTML = "<span class='highlightDiv'>" + zinBegin + "</span>" +
                                "<span class='highlight'>" + wordBoundary.text + "</span>" +
                                "<span class='highlightDiv'>" + zinEinde + "</span>";
                        }
                    } else {
                        highlightDiv.innerHTML = "<span class='highlightDiv'>" + leesTekst + "</span>";
                    }
                }
            }, 50);

            pauseButton.addEventListener("click", function () {
                player.pause();
                pauseButton.disabled = true;
                resumeButton.disabled = false;
            });
            ['click', 'touchstart'].forEach(function (event) {
                pauseButton.addEventListener(event, clickTouchendpauseButton, false);
            });
            function clickTouchendpauseButton(event) {
                event.preventDefault();
                player.pause();
                pauseButton.disabled = true;
                resumeButton.disabled = false;
            }
            ['click', 'touchstart'].forEach(function (event) {
                resumeButton.addEventListener(event, clickTouchendresumeButton, false);
            });
            function clickTouchendresumeButton(event) {
                event.preventDefault();
                setTimeout(function () { puntGevonden = false; }, 900);//***
                document.getElementById('testknop').style.backgroundColor = "#00ff00";
                player.resume();
                pauseButton.disabled = false;
                resumeButton.disabled = true;
            }

            startSynthesisAsyncButton.addEventListener("click", function () {
                document.getElementById('startSynthesisAsyncButtonID').style.display = 'none';
                document.getElementById('startSynthesisAsyncButtonID').style.backgroundColor = "#c8fcc2";
                document.getElementById('highlightDiv').style.display = 'block';
                startSynthesisAsyncButton.disabled = true;
                wordBoundaryList = [];

                // if we got an authorization token, use the token. Otherwise use the provided subscription key
                var speechConfig;
                if (authorizationToken) {
                    speechConfig = SpeechSDK.SpeechConfig.fromAuthorizationToken(authorizationToken, 'westeurope');
                } else {
                    if (subscriptionKey.value === "" || subscriptionKey.value === "subscription") {
                        alert("Please enter your Microsoft Cognitive Services Speech subscription key!");
                        return;
                    }
                    speechConfig = SpeechSDK.SpeechConfig.fromSubscription(subscriptionKey.value, 'westeurope');
                }
                speechConfig.speechSynthesisVoiceName = "Microsoft Server Speech Text to Speech Voice (nl-NL, ColetteNeural)";
                player = new SpeechSDK.SpeakerAudioDestination();
                player.onAudioEnd = function (_) {
                    startSynthesisAsyncButton.disabled = false;
                    pauseButton.disabled = true;
                    resumeButton.disabled = true;
                    wordBoundaryList = [];
                    document.getElementById('highlightDiv').style.display = 'none';
                    document.getElementById('startSynthesisAsyncButtonID').style.display = 'block';
                };
                var audioConfig = SpeechSDK.AudioConfig.fromSpeakerOutput(player);
                synthesizer = new SpeechSDK.SpeechSynthesizer(speechConfig, audioConfig);
              
                synthesizer.synthesizing = function (s, e) {
                    //window.console.log(e);
                    //eventsDiv.innerHTML += "(synthesizing) Reason: " + SpeechSDK.ResultReason[e.result.reason] +
                    //        "Audio chunk length: " + e.result.audioData.byteLength + "\r\n";
                };
                synthesizer.synthesisStarted = function (s, e) {
                    //window.console.log(e);
                    //eventsDiv.innerHTML += "(synthesis started)" + "\r\n";
                    pauseButton.disabled = false;
                };
                synthesizer.synthesisCompleted = function (s, e) {
                    //console.log(e);
                    //eventsDiv.innerHTML += "(synthesized)  Reason: " + SpeechSDK.ResultReason[e.result.reason] +
                    //        " Audio length: " + e.result.audioData.byteLength + "\r\n";
                };
                synthesizer.SynthesisCanceled = function (s, e) {
                    const cancellationDetails = SpeechSDK.CancellationDetails.fromResult(e.result);
                    let str = "(cancel) Reason: " + SpeechSDK.CancellationReason[cancellationDetails.reason];
                    if (cancellationDetails.reason === SpeechSDK.CancellationReason.Error) {
                        str += ": " + e.result.errorDetails;
                    }
                    //window.console.log(e);
                    //eventsDiv.innerHTML += str + "\r\n";
                    startSynthesisAsyncButton.disabled = false;
                    pauseButton.disabled = true;
                    resumeButton.disabled = true;
                };
                synthesizer.wordBoundary = function (s, e) {
                    //window.console.log(e);
                    //eventsDiv.innerHTML += "(WordBoundary), Text: " + e.text + ", Audio offset: " + e.audioOffset / 10000 + "ms." + "\r\n";
                    wordBoundaryList.push(e);
                };

                const complete_cb = function (result) {
                    if (result.reason === SpeechSDK.ResultReason.SynthesizingAudioCompleted) {
                        //resultsDiv.innerHTML += "synthesis finished";*****************************************************************
                    } else if (result.reason === SpeechSDK.ResultReason.Canceled) {
                        //resultsDiv.innerHTML += "synthesis failed. Error detail: " + result.errorDetails;
                    }
                    //window.console.log(result);
                    synthesizer.close();
                    synthesizer = undefined;
                };
                const err_cb = function (err) {
                    startSynthesisAsyncButton.disabled = false;
                    phraseDiv.innerHTML += err;
                    //window.console.log(err);
                    synthesizer.close();
                    synthesizer = undefined;
                };
                synthesizer.speakTextAsync(leesTekst, complete_cb, err_cb);
            });
            Initialize(function (speechSdk) {
                SpeechSDK = speechSdk;
                startSynthesisAsyncButton.disabled = false;
                pauseButton.disabled = true;
                resumeButton.disabled = true;
                if (typeof RequestAuthorizationToken === "function") {
                    RequestAuthorizationToken();
                }
            });
        });
    </script>`

**Comment by glharper** [comment]
@backnext321 player.resume() is actually an async function with callbacks, so I'd suggest changing those lines to:
`
                player.resume( function () {
                 pauseButton.disabled = false;
                 resumeButton.disabled = true;
               },
               function (err) {
                  //window.console.log(err);
              });
`
Other than that, code looks fine. I believe this is a timing issue with the respective JS engines on various platforms, as your statement "This works in a desktop Chrome browser. In Webview and chrome on Android text stops after 1 or 2 extra characters after the period." indicates. Does that make sense?

**Comment by backnext321** [comment]
Thanks. This is doing the same but with better code for player.resume(). Am I right to say that player.pause() is sync and doesn't need these callbacks?
I still need those setTimeouts 
There is no problem anymore with different platforms after using those setTimeouts. 
Don't get me wrong, this works fine with this code. But I think there must be a better way...
One problem is - I think - the setInterval function repeating every 50 ms. This way it 'finds' the same period several times. 
Also I don't feel happy about searching in the strings (wordBoundary.textOffset...) and hoping that the 'sound' (spoken words) are synchronized. So when in the strings a period occurs, stopping at that point should hopefully correspond with the end of the spoken sentence.

**Comment by glharper** [comment]
Player.pause is indeed synchronous and does not need callbacks.
