### ISSUE TITLE
Could not find a version that satisfies the requirement azure-cognitiveservices-speech (from versions: none) - Raspberry Pi4

### ISSUE THREAD

**Issue by MarcoAndrade26** [Azure-Samples/cognitive-services-speech-sdk#856]
**Describe the bug**
I am trying to install Azure Cognitive Services Speech on Raspberry Pi4, but I am getting "Could not find a version that satisfies the requirement azure-cognitiveservices-speech (from versions: none)

**To Reproduce**
1. pip3 install azure-cognitiveservices-speech
2. Error occurs
3. Tried with: pip install azure-cognitiveservices-speech
4. Error occurs

**Version of the Cognitive Services Speech SDK**
Latest version

**Platform, Operating System, and Programming Language**
 - OS: Ubuntu 20.04
 - Hardware - ARM (64 bits)
 - Programming language: Python

**Comment by hmmbob** [comment]
Possibly similar issue as #854

**Comment by chlandsi** [comment]
Unfortunately, Python is not yet supported on ARM. You can find the supported distributions/platforms [here](https://docs.microsoft.com/en-gb/azure/cognitive-services/speech-service/speech-sdk?tabs=linux%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio#get-the-speech-sdk).
I'm sorry for the inconvenience.

**Comment by glecaros** [comment]
@MarcoAndrade26 I've added an item to our backlog to add ARM64 support to our python bindings. Please let us know if there is anything else you need help with.

**Comment by chrisbasoglu** [comment]
We have added this work item to our future 1.16 release.

**Comment by MarcoAndrade26** [comment]
@chrisbasoglu Is there any timeline for 1.16 release? Thanks!

**Comment by pankopon** [comment]
There is no exact date, but at the moment Speech SDK 1.15 is scheduled for the beginning of 2021 and 1.16 should follow a couple of months or so after that.
