### ISSUE TITLE
getting error 

### ISSUE THREAD

**Issue by mohit1993** [Azure-Samples/cognitive-services-speech-sdk#857]
Code snipet(Type Script):

import * as speechSdk from 'microsoft-cognitiveservices-speech-sdk';

const audioConfig = speechSdk.AudioConfig.fromAudioFileOutput(filename);
const speechConfig = speechSdk.SpeechConfig.fromSubscription(subscriptionKey, serviceRegion); 

i received error while trying to fetch audio config.
Error:
"TypeError", errorType: "error"} additionalData: "TypeError" errorLocation: "TypeError: fs__WEBPACK_IMPORTED_MODULE_0__.openSync is not a function↵    at new AudioFileWriter (https://dev.whiteboard.microsoft.com/blueboard/scripts/fakeboard.js:88001:66)↵    at Function.fromAudioFileOutpu

Please find full code here:

/* eslint-disable no-console */
/* eslint-disable @typescript-eslint/explicit-module-boundary-types */
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

import * as speechSdk from 'microsoft-cognitiveservices-speech-sdk';
// import readline from 'readline';

// pull in the required packages.

// replace with your own subscription key,
// service region (e.g., "westus"), and
// the name of the file you save the synthesized audio.
const subscriptionKey = 'my key';
const serviceRegion = 'eastasia'; // e.g., "westus"
const filename = 'YourAudioFile.wav';

// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
export function getVoice() {
	console.log('getVoice started');
	const audioConfig = speechSdk.AudioConfig.fromAudioFileOutput(filename);
	console.log('audio config fetched');
	const speechConfig = speechSdk.SpeechConfig.fromSubscription(subscriptionKey, serviceRegion);
	console.log('sppech config fetched');
	// create the speech synthesizer.
	const synthesizer = new speechSdk.SpeechSynthesizer(speechConfig, audioConfig);

	// const rl = readline.createInterface({
	// 	input: process.stdin,
	// 	output: process.stdout
	// });
	// rl.question('Type some text that you want to speak...\n> ', (text) => {
	// 	rl.close();
	// 	// eslint-disable-next-line no-param-reassign
	const text = 'hello how are you doing';
	// start the synthesizer and wait for a result.
	synthesizer.speakTextAsync(
		text,
		(result) => {
			if (result.reason === speechSdk.ResultReason.SynthesizingAudioCompleted) {
				// eslint-disable-next-line no-console
				console.log('synthesis finished.');
			} else {
				// eslint-disable-next-line no-console
				console.error(
					`Speech synthesis canceled, ${result.errorDetails}\nDid you update the subscription info?`
				);
			}
			synthesizer.close();
			// synthesizer = undefined;
		},
		(err) => {
			// eslint-disable-next-line no-console
			console.trace(`err - ${err}`);
			synthesizer.close();
			// synthesizer = undefined;
		}
	);
	// eslint-disable-next-line no-console
	console.log(`Now synthesizing to: ${filename}`);
	// });
}

**Comment by glharper** [comment]
@mohit1993 
Looks like a weird dependency issue. In an empty folder, from the command line, type `npm install microsoft-cognitiveservices-speech-sdk`.
Then copy the following code into a new js file in that folder and run "node <filename>.js".
The code:
```const speechSdk = require('microsoft-cognitiveservices-speech-sdk');

// import readline from 'readline';

// pull in the required packages.

// replace with your own subscription key,
// service region (e.g., "westus"), and
// the name of the file you save the synthesized audio.
const subscriptionKey = 'my key';
const serviceRegion = 'eastasia'; // e.g., "westus"
const filename = 'YourAudioFile.wav';

// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
function getVoice() {
console.log('getVoice started');
const audioConfig = speechSdk.AudioConfig.fromAudioFileOutput(filename);
console.log('audio config fetched');
const speechConfig = speechSdk.SpeechConfig.fromSubscription(subscriptionKey, serviceRegion);
console.log('sppech config fetched');
// create the speech synthesizer.
const synthesizer = new speechSdk.SpeechSynthesizer(speechConfig, audioConfig);

// const rl = readline.createInterface({
// 	input: process.stdin,
// 	output: process.stdout
// });
// rl.question('Type some text that you want to speak...\n> ', (text) => {
// 	rl.close();
// 	// eslint-disable-next-line no-param-reassign
const text = 'hello how are you doing';
// start the synthesizer and wait for a result.
synthesizer.speakTextAsync(
	text,
	(result) => {
		if (result.reason === speechSdk.ResultReason.SynthesizingAudioCompleted) {
			// eslint-disable-next-line no-console
			console.log('synthesis finished.');
		} else {
			// eslint-disable-next-line no-console
			console.error(
				`Speech synthesis canceled, ${result.errorDetails}\nDid you update the subscription info?`
			);
		}
		synthesizer.close();
		// synthesizer = undefined;
	},
	(err) => {
		// eslint-disable-next-line no-console
		console.trace(`err - ${err}`);
		synthesizer.close();
		// synthesizer = undefined;
	}
);
// eslint-disable-next-line no-console
console.log(`Now synthesizing to: ${filename}`);
// });
}

getVoice();
```

**Comment by pankopon** [comment]
@mohit1993 Were you able to resolve the issue, using the provided info? Please update.

**Comment by mohit1993** [comment]
@pankopon Thanks for your help, issue has been resolved it looks like issue was there due to local file path

**Comment by pankopon** [comment]
Closed as resolved.
