### ISSUE TITLE
Unable to load library in Debian

### ISSUE THREAD

**Issue by ivankom** [Azure-Samples/cognitive-services-speech-sdk#86]
**Describe the bug**
We're trying to use this library with .NET Core 2.1 on Linux. 

1. The issue is that with current DllImport naming scheme library should be named libMicrosoft.CognitiveServices.Speech.csharp.bindings.dll and should be put into /usr/lib/x86_64-linux-gnu. I believe DllImport should be simply Microsoft.CognitiveServices.Speech.csharp.bindings, then both Windows and Linux will load it properly.
Otherwise, one gets:

The type initializer for 'Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'Microsoft.CognitiveServices.Speech.csharp.bindings.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libMicrosoft.CognitiveServices.Speech.csharp.bindings.dll: cannot open shared object file: No such file or directory

2. Looks like there's an issue with OpenSSL versioning in native libraries:
  required from libcrypto.so.1.0.0:
    0x066a2b22 0x00 12 OPENSSL_1.0.2
    0x066a2b20 0x00 05 OPENSSL_1.0.0
  required from libssl.so.1.0.0:
    0x066a2b21 0x00 21 OPENSSL_1.0.1
    0x066a2b20 0x00 02 OPENSSL_1.0.0

From libcrypto.so.1.0.0 it requires OPENSSL_1.0.2 which obviously is not there.

Also is it possible to get this native library for linux-x64 built against libssl1.0.2 ? 
Because currently we can't install libssl1.0.2 and libssl1.0.0 simultaneously because there will be a mess with usage from .NET Core.

**Version of the Cognitive Services Speech SDK**
1.0.1

**Platform, Operationg System, and Programming Language**
 - OS:  SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
 - Hardware - x64

**Comment by ivankom** [comment]
Any updates perhaps? 
Will this be updated and if yes, when?

**Comment by wolfma61** [comment]
there is an update coming shortly, that took a lot of our attention -
this will NOT fix this issue (at least to our knowledge)

we will investigate this issue once the update is out ... 

sorry for the trouble and delay

**Comment by nicolaspanel** [comment]
still here in `1.2.0` (I'm using `debian stretch`)
upgrading to [libssl1.0.2](https://packages.debian.org/stretch/libssl1.0.2) should fix the issue

**Comment by wolfma61** [comment]
correct

**Comment by thewwwizard** [comment]
Debian GNU/Linux 9.8 (stretch) 
Python SDK v1.3.1

Using libssl1.0.2
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory

Using libssl1.0.0 (deb http://security.debian.org/debian-security jessie/updates main)
ImportError: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version `OPENSSL_1.0.2' not found (required by /usr/local/lib/python3.5/dist-packages/azure/cognitiveservices/speech/_speech_py_impl.so)

The only version I got it working with - libssl1.0.0_1.0.2l-1~bpo8+1_amd64.deb
It can be found here - http://ftp.debian.org/debian/pool/main/o/openssl/?C=M;O=A

Am I doing something wrong and is there a way it can work with the latest libssl versions (1.0.2 / 1.1)
Or is there updates coming shortly in relation to this issue?

**Comment by mahilleb-msft** [comment]
@thewwwizard, @ivankom, @nicolaspanel - if you're on Debian 9, or a Debian 9 based image, please try out Speech SDK version 1.5.0, which adds support for Debian 9.
Make sure to install the binary dependencies, in particular OpenSSL and libasound2:

```
sudo apt-get update
sudo apt-get install libssl1.0.2 libasound2
```

Best, Mark

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-cpp-linux

**Comment by thewwwizard** [comment]
@mahilleb-msft , thank you for the update!
I've installed and tested the latest version 1.5.1 on Debian 9 and libssl1.0.2. Recognition works perfect and no more libssl errors. 
But one strange thing, there is 10 sec delay after a text is recognized and before python script stops.
The script is the same one I use with the old SDK version 1.3.1. Not sure its SDK issue so I'll investigate it further and leave a comment when find smth.
