### ISSUE TITLE
iOS Speech SDK: 'SPXDialogServiceConnector'  class is missing

### ISSUE THREAD

**Issue by hemantgore** [Azure-Samples/cognitive-services-speech-sdk#860]
Thank you  MS Team for the great SDK!!
 
**Missing Wrapper Class:**
Connection to Bot service using 'SPXDialogServiceConnector' class is unavailable in iOS Speech SDK. 
Note: It is available for Windows SDK and Android SDK.

**Alternative:** Developers need to write their own Objective-C++ wrapper to utilize the core C++ SDK class. 

If it will be available natively from iOS Speech SDK, everyone won't have to write!!!
   
And this is a need of time where SDK has more potential when we connect Speech to Bot service.

Regards,
Hemant

**Comment by amitkumarshukla** [comment]
@glecaros Could you please take a look at this one

**Comment by jhakulin** [comment]
@hemantgore Thanks for question,
We will include SPXDialogServiceConnector for Objective-C for iOS in future releases, probably during spring 2021.
Currently you can do Xamarin/Unity app using DialogServiceConnector for iOS (using C#).
Let us know your feedback.

**Comment by hemantgore** [comment]
@jhakulin, We already have a native iOS app in swift serving client and also need to meet the requirement in next couple of months, so C# won't be the option.

The immediate solution is to continue writing our own Objective-C++ wrapper for missing classes.

Current progress:
- DialogServiceConnector initialization - Done
- Custom 'keyword' recognition to start the Bot service - Done
- GetActivity from bot service in text format - Done
- Get and play Audio from activity - in progress 

If we can get any references **implementation** (NOT how to use) of 'SPXRecognizer'/ 'SPXSpeechSynthesizer' of existing iOS Speech SDK, that will help speed up the deliverable. 

Thanks in advance.

**Comment by oscholz** [comment]
@hemantgore 
Hi Hemant! Could you put this feature request in our Feedback portal, please?
https://feedback.azure.com/forums/932041-cognitive-services

Also feel free to open a support request in the Azure portal (log in to portal.azure.com, open your Speech or Cognitive Services resource, then click on New support request in the lower left). This way we can have a more direct/non-public conversation with you about this request, and potentially get a better understanding of your use case to help us prioritize this request.

Thank you!

**Comment by pankopon** [comment]
Closing this issue as there is now a work item on our backlog, to be prioritized for future releases. We will provide an update here when information about the release schedule is available. Please see above about additional support requests as necessary.
