### ISSUE TITLE
SpeechActivityTemplate method is missing in DialogServiceConnector class for Android

### ISSUE THREAD

**Issue by ranjanraviraj** [Azure-Samples/cognitive-services-speech-sdk#861]
**Describe the bug**
SpeechActivityTemplate method is missing in DialogServiceConnector class for Android which can be used to pass channel data using Speech SDK to the bot.

**Expected behavior**
SpeechActivityTemplate should be there as it is present in .Net platform.

**Version of the Cognitive Services Speech SDK**
1.14.0

**Platform, Operating System, and Programming Language**
 - OS: Android
 - Java
 - Android app

**Comment by amitkumarshukla** [comment]
@glecaros Could you please take a look at this one

**Comment by pankopon** [comment]
Closing this issue as there is now a work item on our backlog to be prioritized and planned. We'll update this with release schedule information when available.
