### ISSUE TITLE
Pronunciation assessment: recoginzeOnceAsync can't detect an utterance's end.

### ISSUE THREAD

**Issue by Terenfear** [Azure-Samples/cognitive-services-speech-sdk#862]
**Describe the bug**
`SpeechRecognizer.recognizeOnceAsync()`, while used with an applied `pronunciationAssessmentConfig`, can't detect that an utterance has already ended. Because of that the recognizer just goes on and listens for sounds for about 30 seconds.

**To Reproduce**
1. Run any pronunciation assessment sample which uses `recognizeOnceAsync()`.
2. Say a short sentence or a word.

**Expected behavior**
Recognition ends shortly after you stop speaking and you can view an assessment result.

**Actual behavior**
Recognition just goes on and on until it hits some kind of a timeout around 30 seconds. Only then you can view a result.

**Version of the Cognitive Services Speech SDK**
1.14.0

**Platform, Operating System, and Programming Language**
 - OS: Android, Windows (tested several samples)
 - Programming language: Java, C++
I've tested on two Android quickstart samples (added the assessment logic myself as described [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-pronunciation-assessment?pivots=programming-language-java)), and two Windows samples (JRE and C++).

**Additional context**
I tried to use the assessment logic on a result from a continuous recognition session and it worked quite fast, so I believe that the pronunciation assessment logic itself is not the cause.

**Comment by amitkumarshukla** [comment]
@Terenfear Thanks a lot for raising the issue. I verified at my end also and your observation is right. Please give us sometime and we will get back to you.

**Comment by yinhew** [comment]
Hi, @Terenfear 

Thanks for your feedback!
This is a known behavior which is specific for pronunciation assessment on RecognizeOnce.
This is on purpose of taking care of language learners (most are kids), who sometimes give a long pause in the utterance.
We therefore set the silence timeout to unlimited for pronunciation assessment on RecognizeOnce.
But definitely this has impact on the microphone scenario. We will consider balancing this silence timeout.
Our recommendation is to use stream as the audio input, and send zero-size chunk to explicitly end the stream.

Let me know if you have futher questions.

Thanks,
Yinhe

**Comment by Terenfear** [comment]
@yinhew Thanks for the details. I wonder, maybe it is viable to have this behavior configurable by a boolean parameter, kind of like EnableMiscue?

**Comment by yinhew** [comment]
@Terenfear this is good suggestion. We will consider it. Thanks a lot!

**Comment by pankopon** [comment]
Closed since clarified, there is now a work item on our backlog about this (not planned yet).
