### ISSUE TITLE
Mask specific information 

### ISSUE THREAD

**Issue by Ray12345678910** [Azure-Samples/cognitive-services-speech-sdk#864]
Hi all, 

We are using the Azure Cognitive Services (Speech to Text) in a large company (if we go live, we estimate to transcribe >500 files a day). However, we are facing some issues with the first batch. And I am actually looking for best practices. The issue:

**Dealing with Numbers**
After transcribing audio into text, we have a Python script were we are trying to deal with privacy. Therefore, we are masking all the numbers (e.g. 0,1,2,3,4,5,6... and one, two, three etc.). 

Unfortunately, this is not fulfilling, since we want to remove on the one hand all the personal info. However, on the other hand keeping product information (e.g. serial number, product number etc.). 

Therefore my question: are there any best practices for this problem (since I cannot imagine that we are the first one dealing with this :-)). 

Many thanks in advance!

**Example:**
Original: Hi, my phone number is 12345 and I am calling for product X, with serial number 9876. 
Our case: Hi, my phone number is !!!!! and I am calling for product X, with serial number !!!!.

We would like to have the serial number.. and it can also happen that it is not appearing directly after each other. E.g.: 
> Hi, welcome how can i help you?
> Hi, i would like to return product X
> Ok. Do you have a serial number for me? 
> Is that the same as a product number? 
> Yes
> Ok. It is 9876

**Comment by amitkumarshukla** [comment]
@Ray12345678910 Thanks a lot for raising the issue. We currently do not have this feature implemented in our service. But please raise your request at https://cognitive.uservoice.com/forums/912208-speech-service and we will prioritize it further. I am closing this issue for the time being. Please stay tuned for our further releases and features.

**Comment by Ray12345678910** [comment]
Thank you Amit. I raised the request. 

Does Microsoft has any ETA, when they are prioritizing an idea? 

Many thanks again!

**Comment by amitkumarshukla** [comment]
Hi Ray, 
We cannot make any forecast about the ETA at this point of time. But it will be useful to explore the text analytics from https://azure.microsoft.com/en-us/services/cognitive-services/text-analytics/ 

This will help you to do the broad entity extraction to achieve your requirement in a better and correct way.
Thanks
