### ISSUE TITLE
Is it possible to identify the number of characters that has been consumed by the Azure Cognitive Services Speech Synthesis (TTS) at a point of time. A kind of metric to track that from the Azure Portal. 

### ISSUE THREAD

**Issue by backnext321** [Azure-Samples/cognitive-services-speech-sdk#865]
Hi, I am testing this service. I want to know the number of characters that has been consumed on my website with TTS. This way I can calculate the costs.

**Comment by amitkumarshukla** [comment]
@backnext321 Thanks a lot for raising the query. We will get back to you very soon.

**Comment by pankopon** [comment]
@yulin-li or @yinhew, do you happen to know?

**Comment by pankopon** [comment]
@backnext321 Update:
The billing report for text-to-speech is based on billable characters and it is available on the Azure portal dashboard. Please see the following pages for more details + instructions for cost analysis.
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/text-to-speech#pricing-note
https://docs.microsoft.com/en-us/azure/cost-management-billing/costs/quick-acm-cost-analysis
However, if you are looking for the number of billed characters per each request, this kind of detail is not available.

**Comment by pankopon** [comment]
Closed as answered.
