### ISSUE TITLE
Is using codec compressed audio like ogg or mp3 better than wav regarding network latency?

### ISSUE THREAD

**Issue by Michael-Jing** [Azure-Samples/cognitive-services-speech-sdk#866]
As in the title.

**Comment by amitkumarshukla** [comment]
@Michael-Jing Not at this moment. In Speech SDK we currently decompress any compressed stream like MP3 or Ogg/Opus to PCM sample (which is raw) and send it over the network. So network usage is going to be same. The only benefit you get at this point of time is to transcribe a compressed stream.

I hope that helps. I am closing this request here. Feel free to give any input or feedback you have in future.
