### ISSUE TITLE
Text to Speech: Not able to find any option to pause or stop audio

### ISSUE THREAD

**Issue by namrathanithya** [Azure-Samples/cognitive-services-speech-sdk#867]
I have implemented text to speech, but requirement is: When the user interrupts the ongoing voice response and attempt another question over the mic, previous response doesn't not stop. I didn't see any stop() in the sdk.

**Comment by amitkumarshukla** [comment]
@namrathanithya Could you please share a sample code that you are using. We will be able to help you better with that.

**Comment by amitkumarshukla** [comment]
We do have stop in the recognizer. Please look at the use of recognizer stop here https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/995d20d9d49b8a054c8141030ad647b5bf5fefd6/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L241

Do let us know if this helps

**Comment by namrathanithya** [comment]
@amitkumarshukla I am looking for a method which stops the audio if user clicks on a button and I didn't find any stop method in the text to speech sdk. 
I referred to this code:[ https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/java/android/text-to-speech/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/quickstart/MainActivity.java](url)

`
package com.microsoft.cognitiveservices.speech.samples.quickstart;

import android.support.v4.app.ActivityCompat;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.EditText;
import android.widget.TextView;

import com.microsoft.cognitiveservices.speech.ResultReason;
import com.microsoft.cognitiveservices.speech.SpeechConfig;
import com.microsoft.cognitiveservices.speech.SpeechSynthesisCancellationDetails;
import com.microsoft.cognitiveservices.speech.SpeechSynthesisResult;
import com.microsoft.cognitiveservices.speech.SpeechSynthesizer;

import static android.Manifest.permission.*;

public class MainActivity extends AppCompatActivity {

    // Replace below with your own subscription key
    private static String speechSubscriptionKey = "YourSubscriptionKey";
    // Replace below with your own service region (e.g., "westus").
    private static String serviceRegion = "YourServiceRegion";

    private SpeechConfig speechConfig;
    private SpeechSynthesizer synthesizer;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // Note: we need to request the permissions
        int requestCode = 5; // unique code for the permission request
        ActivityCompat.requestPermissions(MainActivity.this, new String[]{INTERNET}, requestCode);

        // Initialize speech synthesizer and its dependencies
        speechConfig = SpeechConfig.fromSubscription(speechSubscriptionKey, serviceRegion);
        assert(speechConfig != null);

        synthesizer = new SpeechSynthesizer(speechConfig);
        assert(synthesizer != null);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();

        // Release speech synthesizer and its dependencies
        synthesizer.close();
        speechConfig.close();
    }

    public void onSpeechButtonClicked(View v) {
        TextView outputMessage = this.findViewById(R.id.outputMessage);
        EditText speakText = this.findViewById(R.id.speakText);

        try {
            // Note: this will block the UI thread, so eventually, you want to register for the event 
            SpeechSynthesisResult result = synthesizer.SpeakText(speakText.getText().toString());
            assert(result != null);

            if (result.getReason() == ResultReason.SynthesizingAudioCompleted) {
                outputMessage.setText("Speech synthesis succeeded.");
            }
            else if (result.getReason() == ResultReason.Canceled) {
                String cancellationDetails =
                        SpeechSynthesisCancellationDetails.fromResult(result).toString();
                outputMessage.setText("Error synthesizing. Error detail: " +
                        System.lineSeparator() + cancellationDetails +
                        System.lineSeparator() + "Did you update the subscription info?");
            }

            result.close();
        } catch (Exception ex) {
            Log.e("SpeechSDKDemo", "unexpected " + ex.getMessage());
            assert(false);
        }
    }
}
`

**Comment by amitkumarshukla** [comment]
I am sorry as I understood that you are looking for Speech to Text. Actually you are mentioning Text to Speech. We have added the stop in our latest 1.14.0 release. Please look at the following and let me know if that helps

https://docs.microsoft.com/en-us/java/api/com.microsoft.cognitiveservices.speech.speechsynthesizer.stopspeakingasync?view=azure-java-stable

**Comment by namrathanithya** [comment]
@amitkumarshukla I am looking for stop in text to speech.

[https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/java/android/text-to-speech/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/quickstart/MainActivity.java](url)

**Comment by amitkumarshukla** [comment]
@namrathanithya Please look at my previous reply and let me know if that helped.

**Comment by yulin-li** [comment]
@namrathanithya Pls use [`StopSpeakingAsync` method](https://docs.microsoft.com/en-us/java/api/com.microsoft.cognitiveservices.speech.speechsynthesizer.stopspeakingasync?view=azure-java-stable) The method is not in the quickstart yet.

**Comment by backnext321** [comment]
I understand that the StopSpeakingAsync method exists in C++/C#/Java/Python/Objective-C/Swift. Is it possible in Javascript?

**Comment by amitkumarshukla** [comment]
@glharper Could you please answer the question for Javascript

**Comment by glharper** [comment]
@backnext321 StopSpeakingAsync is not currently implemented in JavaScript, no.

**Comment by namrathanithya** [comment]
I used StopSpeakingAsync method but I am getting  "Cannot resolve method 'StopSpeakingAsync' in 'SpeechSynthesizer'. Also, after using StartSpeakingTextAsync method app is crashing.

**Comment by yulin-li** [comment]
@namrathanithya could you share some repro codes?

**Comment by backnext321** [comment]
> @backnext321 StopSpeakingAsync is not currently implemented in JavaScript, no.

ok. Would be nice to have it in Javascript too...

**Comment by namrathanithya** [comment]
I've created a capacitor plugin from the below sdk.
[https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/995d20d9d49b8a054c8141030ad647b5bf5fefd6/quickstart/java/android/text-to-speech](url)

This is how I used stopspeakingAsync. Let me know if you want more details?
`
public class SpeechToText extends Plugin {

    // Replace below with your own subscription key
    private String SpeechSubscriptionKey;
    // Replace below with your own service region (e.g., "westus").
    private String SpeechRegion;
    static final int REQUEST_ALL = 12345;
    //this.cordova.getActivity().getApplicationContext();

    SpeechConfig speechConfig;
    SpeechSynthesizer synthesizer;
    SpeechSynthesisResult result;

    //Intent intent = new Intent(Intent.);
    //
    // Configuration for intent recognition
    //
    // Replace below with your own Language Understanding subscription key
    // The intent recognition service calls the required key 'endpoint key'.
    private static final String LanguageUnderstandingSubscriptionKey = "en-US";
    // Replace below with the deployment region of your Language Understanding application
    private static final String LanguageUnderstandingServiceRegion = "eastus";
    // Replace below with the application ID of your Language Understanding application
    private static final String LanguageUnderstandingAppId = "com.speech.to.text";
    // Replace below with your own Keyword model file, kws.table model file is configured for "Computer" keyword
    private static final String KwsModelFile = "kws.table";

    private TextView recognizedTextView;


    private MicrophoneStream microphoneStream;
    private MicrophoneStream createMicrophoneStream() {
        if (microphoneStream != null) {
            microphoneStream.close();
            microphoneStream = null;
        }

        microphoneStream = new MicrophoneStream();
        return microphoneStream;
    }

    @PluginMethod
    public void echo(PluginCall call) {
        String value = call.getString("value");
        //test something
        JSObject ret = new JSObject();
        ret.put("value", value);
        call.success(ret);
    }
    @PluginMethod
    public void recognizeText(PluginCall call){
        // Initialize speech synthesizer and its dependencies
        //SpeechConfig speechConfig;
        //SpeechSynthesizer synthesizer;
        String speakText = call.getString("value");
        speechConfig = SpeechConfig.fromSubscription(SpeechSubscriptionKey, SpeechRegion);
        assert(speechConfig != null);

        synthesizer = new SpeechSynthesizer(speechConfig);
        assert(synthesizer != null);

        // Note: this will block the UI thread, so eventually, you want to register for the event
        result = (SpeechSynthesisResult) synthesizer.StartSpeakingTextAsync(speakText.toString());
        assert(result != null);

        if (result.getReason() == ResultReason.SynthesizingAudioCompleted) {
            System.out.println("Speech synthesis succeeded.");
        }
        else if (result.getReason() == ResultReason.Canceled) {
            String cancellationDetails =
                    SpeechSynthesisCancellationDetails.fromResult(result).toString();
            System.out.println("Error synthesizing. Error detail: " +
                    System.lineSeparator() + cancellationDetails +
                    System.lineSeparator() + "Did you update the subscription info?");
        }

        result.close();
    }
    @PluginMethod 
    public void stopRec(PluginCall call){
        if(synthesizer != null){
            //synthesizer.playSilentUtterance();
            synthesizer.StopSpeakingAsync();
            result.close();
            synthesizer.close();
            speechConfig.close();
        }

    }
`

**Comment by pankopon** [comment]
@yulin-li Please follow up on this and update as necessary.

**Comment by yulin-li** [comment]
@namrathanithya sorry for the delay response due to holiday. Did the "cannot resolve method 'StopSpeakingAsync'" error occur during making? Could you just try our [quickstart](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/java/android/text-to-speech) by adding `synthesizer.StopSpeakingAsync();` like this

```java
//
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE.md file in the project root for full license information.
//
package com.microsoft.cognitiveservices.speech.samples.quickstart;

import android.support.v4.app.ActivityCompat;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.EditText;
import android.widget.TextView;

import com.microsoft.cognitiveservices.speech.ResultReason;
import com.microsoft.cognitiveservices.speech.SpeechConfig;
import com.microsoft.cognitiveservices.speech.SpeechSynthesisCancellationDetails;
import com.microsoft.cognitiveservices.speech.SpeechSynthesisResult;
import com.microsoft.cognitiveservices.speech.SpeechSynthesizer;

import static android.Manifest.permission.*;

public class MainActivity extends AppCompatActivity {

    // Replace below with your own subscription key
    private static String speechSubscriptionKey = "a8a1a9413a1b46a39484ace7244f3e83";
    // Replace below with your own service region (e.g., "westus").
    private static String serviceRegion = "eastus";

    private SpeechConfig speechConfig;
    private SpeechSynthesizer synthesizer;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // Note: we need to request the permissions
        int requestCode = 5; // unique code for the permission request
        ActivityCompat.requestPermissions(MainActivity.this, new String[]{INTERNET}, requestCode);

        // Initialize speech synthesizer and its dependencies
        speechConfig = SpeechConfig.fromSubscription(speechSubscriptionKey, serviceRegion);
        assert(speechConfig != null);

        synthesizer = new SpeechSynthesizer(speechConfig);
        assert(synthesizer != null);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();

        // Release speech synthesizer and its dependencies
        synthesizer.close();
        speechConfig.close();
    }

    public void onSpeechButtonClicked(View v) {
        TextView outputMessage = this.findViewById(R.id.outputMessage);
        EditText speakText = this.findViewById(R.id.speakText);

        try {
            // Note: this will block the UI thread, so eventually, you want to register for the event 
            SpeechSynthesisResult result = synthesizer.SpeakText(speakText.getText().toString());
            assert(result != null);

            if (result.getReason() == ResultReason.SynthesizingAudioCompleted) {
                outputMessage.setText("Speech synthesis succeeded.");
            }
            else if (result.getReason() == ResultReason.Canceled) {
                String cancellationDetails =
                        SpeechSynthesisCancellationDetails.fromResult(result).toString();
                outputMessage.setText("Error synthesizing. Error detail: " +
                        System.lineSeparator() + cancellationDetails +
                        System.lineSeparator() + "Did you update the subscription info?");
            }

            result.close();

            synthesizer.StopSpeakingAsync();
        } catch (Exception ex) {
            Log.e("SpeechSDKDemo", "unexpected " + ex.getMessage());
            assert(false);
        }
    }
}
```

**Comment by BrianMouncer** [comment]
@namrathanithya  Please let us know if Yulin's answer resolved your issue?

Thanks,

**Comment by pankopon** [comment]
Closed as resolved since no further updates. Please open a new issue if you need more support.
