### ISSUE TITLE
Is there a timeline for new voices?

### ISSUE THREAD

**Issue by backnext321** [Azure-Samples/cognitive-services-speech-sdk#868]
The Dutch voice ColetteNeural is a typical voice for the Netherlands. In Flanders / Belgium we have the same language but very different pronunciation. A 'nl-BE' voice would be very welcome.

**Comment by pankopon** [comment]
@yulin-li & @yinhew Could you comment on the timeline for new voices, if any?

**Comment by yulin-li** [comment]
+@QinyingLiao

**Comment by pankopon** [comment]
We received an update from the person who is working on locale/voice expansion for TTS: "The nl-BE neural voice is in evaluation stage." The current release ETA is in mid-December. So please expect to see support in the near future.

**Comment by pankopon** [comment]
Closed as answered.

**Comment by backnext321** [comment]
Nice. Thanks

**Comment by backnext321** [comment]
Today 2 more Dutch nl-NL voices are released (thanks for that) but no still nl-BE...

**Comment by carsten88** [comment]
![Image](https://github.com/user-attachments/assets/aaafde1a-0c22-4941-9be2-42958d440c5d)
This one is NL-BE. Too sexy for reading newsarticles.
I use it in Speech Note.

**Comment by specialspeak** [comment]
Thanx, but I don't find this voice. Do you have a link?

**Comment by carsten88** [comment]
Its in the settings, tab text to speech, then find the voice in the list and download it.

**Comment by specialspeak** [comment]
Thanx for quick response. Which settings do you mean? I search in Voice Gallery in Azure AI Foundry where I think all voices for TTS are gathered. Nl-Nl now has 3 voices with Personality and Adapted scenario Nl-Be (Dutch Belgium) has only 2 simple voices.

**Comment by carsten88** [comment]
Oops sorry. My bad. I got confused with Speech Note.

**Comment by specialspeak** [comment]
No problem. But for people who can help: In Voice Gallery in Azure AI Foundry the TTS voices "Nl-Nl" now has 3 voices with Personality and Adapted scenario. The  "Nl-Be" (Dutch Belgium) has only 2 simple voices. Is there a possibility for more voices?
