### ISSUE TITLE
Change default language

### ISSUE THREAD

**Issue by Axxeption** [Azure-Samples/cognitive-services-speech-sdk#87]
Hi, 

I used the following link ( https://docs.microsoft.com/nl-nl/azure/cognitive-services/speech-service/speech-to-text-sample#Continuousspeechrecognitionfromafile ) to do continuous speech recognition from a WAV-file. This works fine for my english files, but I need to put speech to text for dutch (nl-NL) which should be supported. I am just nog able to put in my code how to do that. 

I found a solution here: https://docs.microsoft.com/en-us/windows/uwp/design/input/specify-the-speech-recognizer-language but this only seems to work for microphone + my VS says I don't have the Windows assembly?

Please help me out, Thanks!

**Comment by wolfma61** [comment]
take a look at this sample:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_recognition_samples.cs


code like this:
            // <recognitionWithLanguageAndDetailedOutputFormat>
            // Creates an instance of a speech config with specified subscription key and service region.
            // Replace with your own subscription key and service region (e.g., "westus").
            var config = SpeechConfig.FromSubscription("YourSubscriptionKey", "YourServiceRegion");

            // Replace the language with your language in BCP-47 format, e.g., en-US.
            var language = "de-DE";
            config.SpeechRecognitionLanguage = language;
            config.OutputFormat = OutputFormat.Detailed;


the samples in this repository are for the Microsoft Cognitive Services Speech SDK
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/

thx
Wolfgang

**Comment by wolfma61** [comment]
also, for example the C# reference documentation:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechconfig.speechrecognitionlanguage?view=azure-dotnet

**Comment by Axxeption** [comment]
Wauw, Thanks @wolfma61! I managed to get this working now!
