### ISSUE TITLE
Speech To Text Callback IP Address

### ISSUE THREAD

**Issue by hre88** [Azure-Samples/cognitive-services-speech-sdk#871]
Hello,
Im using speech to text batch processing behind a firewall. What are the ip addresses of speech to text that needs to be whitelisted in order for the speech to text webhook callback request to get through?
Region: uksouth

**Comment by pankopon** [comment]
@zhouwangzw @wolfma61 Can you please comment?

**Comment by zhouwangzw** [comment]
@bexxx  Could you please help on this Webhook callback related question?

**Comment by bexxx** [comment]
We're working on using IPs from a predefined IP pool to start supporting service tags which will make your scenario easy to configure. Now the IPs are not fixed, and the firewall config cannot be done.

**Comment by hre88** [comment]
Thanks @bexx! Any idea when it will be ready? Are there service tags already available for other regions beside uksouth?

**Comment by hre88** [comment]
Does anyone else know when the service tags will be ready?

**Comment by pankopon** [comment]
@bexx Can you please comment on the schedule?

**Comment by bexxx** [comment]
We do not have a fixed ETA for this feature.

**Comment by pankopon** [comment]
Closing the item since the requested feature is not supported at the moment, it is on the service team's backlog (but no ETA).
