### ISSUE TITLE
SPXERR_GSTREAMER_NOT_FOUND_ERROR in iOS

### ISSUE THREAD

**Issue by ZDerain** [Azure-Samples/cognitive-services-speech-sdk#872]
**Describe the bug**
Following the steps in your documentation(cognitive-services-speech-sdk-master/samples/objective-c/ios/compressed-streams/README.m), I created the GStreamerWrapper.framework, and put it into the project;
I have replaced the speechKey and serviceRegion, and it compiles fine, but it gives me an error when I run it;

**To Reproduce**
CompressedStreamsSample[4000:776977] Exception caught in core: Exception with an error code: 0x29 (SPXERR_GSTREAMER_NOT_FOUND_ERROR)

**Expected behavior**
Following the steps in your documentation

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 - OS:  iOS
 - Hardware - x64
 - Programming language: Objective-C
 - Browser: Safari

**Additional context**
I have tried many times, and every time I get the same error, and I would like your advice.

CompressedStreamsSample[4000:776977] Exception caught in core: Exception with an error code: 0x29 (SPXERR_GSTREAMER_NOT_FOUND_ERROR)
[CALL STACK BEGIN]

3   MicrosoftCognitiveServicesSpeech    0x0000000104669ec8 pronunciation_assessment_config_apply_to_recognizer + 41068
4   MicrosoftCognitiveServicesSpeech    0x00000001046a99ec pronunciation_assessment_config_apply_to_recognizer + 301968
5   MicrosoftCognitiveServicesSpeech    0x00000001046a8cf8 pronunciation_assessment_config_apply_to_recognizer + 298652
6   MicrosoftCognitiveServicesSpeech    0x00000001046a4e88 pronunciation_assessment_config_apply_to_recognizer + 282668
7   MicrosoftCognitiveServicesSpeech    0x00000001046a5120 pronunciation_assessment_config_apply_to_recognizer + 283332
8   MicrosoftCognitiveServicesSpeech    0x00000001045fd0d8 recognizer_create_speech_recognizer_from_config + 2508
9   MicrosoftCognitiveServicesSpeech    0x00000001045fc7a8 recognizer_create_speech_recognizer_from_config + 156
10  MicrosoftCognitiveServicesSpeech    0x000000010455709c MicrosoftCognitiveServicesSpeech + 553116
11  MicrosoftCognitiveServicesSpeech    0x0000000104555c14 MicrosoftCognitiveServicesSpeech + 547860
12  MicrosoftCognitiveServicesSpeech    0x0000000104554280 MicrosoftCognitiveServicesSpeech + 541312
13  CompressedStreamsSample             0x000000010400c978 -[ViewController recognizeFromMP3File] + 548
14  CompressedStreamsSample             0x000000010400c6dc __51-[ViewController recognizeFromMP3FileButtonTapped:]_block_invoke + 40
15  libdispatch.dylib                   0x00000001042f3824 _dispatch_call_block_and_release + 24
16  libdispatch.dylib                   0x00000001042f4dc8 _dispatch_client_callout + 16
17  libdispatch.dylib                   0x00000001042f7c90 _dispatch_queue_override_invoke + 888
18  libdispatch.dylib                   0x00000001043061dc _dispatch_root_queue_drain + 376
19  libdispatch.dylib                   0x0000000104306bc8 _dispatch_worker_thread2 + 156
[CALL STACK END]

**Comment by jhakulin** [comment]
@ZDerain Thanks for feedback, which SDK release version you are using ? We disabled support for Gstreamer on iOS on 1.13.0 release as there was customer reports indicating they had problems with Apple store verification and that Gstreamer part lacked some verification on our side. However we have verified now with our internal iOS apps using Speech SDK that Gstreamer extension as a weak framework should cause no problems with Apple store and we will enable this back on 1.15.0 (ETA Jan 2021). If you want to use earlier versions of Speech SDK which has this support and try that out, please use Speech SDK version earlier than 1.13.0.

**Comment by ZDerain** [comment]
@jhakulin Now I'm using sdk version 1.12.1. that work fine; Thanks.
