### ISSUE TITLE
PushAudioInputStream demo on Android

### ISSUE THREAD

**Issue by Michael-Jing** [Azure-Samples/cognitive-services-speech-sdk#873]
When I use PushAudioInputStream in a python script running on MacOS 11.0.1, everything works fine. But after I changed the sdkdemo on Android to use PushAudioInputStream instead of PullAudioInputStreamCallback, the demo barely works, the recognition accuracy is very low. So could the team provide a demo using PushAudioInputStream on Android?

**Comment by jhakulin** [comment]
@Michael-Jing Thanks for feedback, which Android PushAudioInputStream demo you are referring to that produced low recognition accuracy?

**Comment by Michael-Jing** [comment]
I'm doing some tweak based on the sdkdemo located at samples/java/android/sdkdemo. The demo uses PullAudioInputStreamCallback as input and works well. However, after I changed the input to PushAudioInputStream, the accuracy became low.

**Comment by jhakulin** [comment]
@Michael-Jing Attached initial sample which use pushstream with continuous recognition on Android and reads data from microphone using Android AudioRecorder. Alternatively you can create stream which reads data from wave files from your app asset. We will improve our official samples in the next Speech SDK release.
[PushStreamSampleAndroid.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/5594602/PushStreamSampleAndroid.zip)
Let me know if this helps you further.

**Comment by Michael-Jing** [comment]
Yes, it helps, thank you very much!
