### ISSUE TITLE
Wrong usage of InputStream in the sample code

### ISSUE THREAD

**Issue by f-paulus** [Azure-Samples/cognitive-services-speech-sdk#874]
**Describe the bug**
There is a bug in the examples of how to use the continuous recognition, for example here:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java#L359
The linked implementation is based on the assumption that the `InputStream#read(byte[])` is always filling the entire array. But this may not be true. It also can only fewer bytes. This is the reason why the returned value gives the number of read bytes. With the example implementation, one may loose bytes.
This happened to me when experimenting with the Speech SDK and copy-pasting from the samples.

**To Reproduce**
Read file from the resources of a JAR may reproduce the described problem. But reproducing it is not really needed since the docs are clear.

**Expected behavior**
Correctly read the referenced audio without loosing bytes.

**Version of the Cognitive Services Speech SDK**
1.14.0

**Platform, Operating System, and Programming Language**
 - OS: Manjaro
 - Hardware - x86
 - Programming language: Java

**Comment by jhakulin** [comment]
@f-paulus Thanks for the feedback, I think you are correct and this sample has limitations you mentioned. Did you improve/fix the code which was based on the sample for your app ? If so, would you like to contribute on improving the sample for our samples GitHub repository?

**Comment by f-paulus** [comment]
@jhakulin Thanks for the fast reply. I won't create a PR for now, but I can add my code here:
```
byte[] readBuffer = new byte[4096];
int readBytes;
while ((readBytes = inputStream.read(readBuffer)) != -1) {
    byte[] sizedArray = new byte[readBytes];
    System.arraycopy(readBuffer, 0, sizedArray, 0, readBytes);
    pushStream.write(readBuffer);
}
```
I hope this already helps!

**Comment by jhakulin** [comment]
@f-paulus Thanks, I have created item for our backlog for the next release. Thanks for the feedback!
