### ISSUE TITLE
Custom Keyword Feature Offline Usage

### ISSUE THREAD

**Issue by webfolderio** [Azure-Samples/cognitive-services-speech-sdk#875]
Hi,

KWS feature does not require back-end services. Is it enough to have "Speech subscription" to use this feature. Is there any additional license/service fee?

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/custom-keyword-basics?pivots=programming-language-csharp#prerequisites

**Prerequisites**:
```
The steps in this article require a **Speech subscription**, and the Speech SDK.
```

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/custom-keyword-basics?pivots=programming-language-csharp#use-a-keyword-model-with-the-sdk

**Note**:
```
The example shown here uses local keyword recognition,
since it does not require a SpeechConfig object for authentication context,
and **does not contact the back-end**. However,
you can run both keyword recognition and verification utilizing a continuous back-end connection.
```

**Comment by jhakulin** [comment]
@webfolderio You need a subscription to create keyword model (.table file). Once you have the keyword model, using Speech SDK's KeywordRecognizer alone does not require subscription/connection to the online service.
