### ISSUE TITLE
How to use with Django?

### ISSUE THREAD

**Issue by trevorphillips** [Azure-Samples/cognitive-services-speech-sdk#876]
Some overview...

I use django-storages, specifically the amazon storage part of that module, to save audio files for my CarTrip objects. How would I pass in that audio file into cognitive services for it to work?

Here is an example of what it kind of looks like.
trip: <Trip: [1.5] Transcription Pending> (Actual trip object)
trip.audio: <FieldFile: audio-trips/161/20201123122006.wav> (The audio field of the trip which is a FileField)
trip.audio.file: <S3Boto3StorageFile: audio-trips/161/20201123122006.wav> (This is where django storage save it in an S3 bucket on aws... etc...)

I can't pass the file object as a filename so I'm assuming I'd have to pass it in as a stream but I have no clue how as I've tried a million different things..

I hope this is clear what I'm trying to do. Thanks.

**Comment by jhakulin** [comment]
@trevorphillips Thanks for the question, I assume you are planning to process your audio files offline? And you prefer to directly use django-storages to get the audio files from? I am thinking if you create Azure function which integrated Speech SDK functionalities you want and triggers to HTTP request which your app does (containing the audio binary inside a body) and that would produce transcriptions as a response?

**Comment by chlandsi** [comment]
This sounds like a good use case for the [batch transcription API](https://docs.microsoft.com/en-gb/azure/cognitive-services/speech-service/batch-transcription). It allows to send the URLs to the audio files in a REST request, and collect the transcription results later.

**Comment by jhakulin** [comment]
closing as answered, let us know if more information is needed
