### ISSUE TITLE
Error 400 -> cognitive-services-speech-sdk/quickstart/javascript/node/from-blob/

### ISSUE THREAD

**Issue by Bmelob423** [Azure-Samples/cognitive-services-speech-sdk#877]
Hy.
I'm using the from-blob.js code in cognitive-services-speech-sdk/quickstart/javascript/node/from-blob/ and it returns me a error 400.
What's is a error 400 in this case? Can help me please??

**Comment by rubendsm** [comment]
I have the same question!

**Comment by chlandsi** [comment]
There is an error in the sample. Please remove the backtick (`` ` ``) in [this line](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/995d20d9d49b8a054c8141030ad647b5bf5fefd6/quickstart/javascript/node/from-blob/from-blob.js#L15) of the sample. The sample will be updated shortly.

**Comment by jhakulin** [comment]
closing as issue identified and we are updating the sample
