### ISSUE TITLE
Pronunciation assessment: recoginzeOnceAsync returning incorrect recognition result text 

### ISSUE THREAD

**Issue by mbuotidem** [Azure-Samples/cognitive-services-speech-sdk#879]
**Describe the bug**
The speech recognition result text is always the reference text when SpeechRecognizer.recognizeOnceAsync() is used with an applied pronunciationAssessmentConfig. It doesn't matter what the user says, the returned recognition result text is always the reference text. 

**To Reproduce**
1. Run a pronunciation assessment sample which uses recognizeOnceAsync(), passing in a reference text of your choice. I based mine off the example at https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-pronunciation-assessment?pivots=programming-language-csharp.
2. Using the code in step 1, record a snippet saying anything.  Regardless of what you say, the result text will be whatever you set as the reference text. 

**Expected behavior**
The recognition result text should be what was actually recorded by the microphone. 

**Version of the Cognitive Services Speech SDK**
1,14,0

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - x64
 - Programming language: C# and Python (tried with both) using the logic https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-pronunciation-assessment?pivots=programming-language-csharp, reproduced below
 - Browser : Not applicable, running from console

**Additional context**
The pronunciation assessment part works, assigning low scores when the spoken text differs from the reference text and high scores when it matches it. The only issue is the incorrect recognition result text displayed. 

Also, when SpeechRecognizer.recognizeOnceAsync() is used without an applied pronunciationAssessmentConfig, the recognition result text is accurate. 

Code snippet based on the from-microphone hello-world sample and the pronunciation assessment documentation linked above: 

```public static async Task RecognizePronunciation()
        {
            var audioConfig = AudioConfig.FromDefaultMicrophoneInput();
            var speechConfig = SpeechConfig.FromSubscription("YourSubscriptionKey", "YourServiceRegion");
	    var referenceText = "Pronunciation assessment evaluates speech pronunciation and gives speakers feedback on the accuracy and fluency of spoken audio."
            var pronunciationAssessmentConfig = new PronunciationAssessmentConfig(referenceText, GradingSystem.HundredMark, Granularity.Phoneme);
            Console.WriteLine("Please say something...");
            using (var recognizer = new SpeechRecognizer(
                speechConfig,
                audioConfig))
            {
                // apply the pronunciation assessment configuration to the speech recognizer
                pronunciationAssessmentConfig.ApplyTo(recognizer);
                var speechRecognitionResult = await recognizer.RecognizeOnceAsync();

                if (speechRecognitionResult.Reason == ResultReason.RecognizedSpeech)
                {
                    Console.WriteLine($"We recognized: {speechRecognitionResult.Text}");
                }
                else if (speechRecognitionResult.Reason == ResultReason.NoMatch)
                {
                    Console.WriteLine($"NOMATCH: Speech could not be recognized.");
                }
                else if (speechRecognitionResult.Reason == ResultReason.Canceled)
                {
                    var cancellation = CancellationDetails.FromResult(speechRecognitionResult);
                    Console.WriteLine($"CANCELED: Reason={cancellation.Reason}");

                    if (cancellation.Reason == CancellationReason.Error)
                    {
                        Console.WriteLine($"CANCELED: ErrorCode={cancellation.ErrorCode}");
                        Console.WriteLine($"CANCELED: ErrorDetails={cancellation.ErrorDetails}");
                        Console.WriteLine($"CANCELED: Did you update the subscription info?");
                    }
                }


                var pronunciationAssessmentResult =
                    PronunciationAssessmentResult.FromResult(speechRecognitionResult);
                var pronunciationScore = pronunciationAssessmentResult.PronunciationScore;
                var accuracyScore = pronunciationAssessmentResult.AccuracyScore;
                var fluencyScore = pronunciationAssessmentResult.FluencyScore;
                var completenessScore = pronunciationAssessmentResult.CompletenessScore;
                Console.WriteLine($"Accuracy Score: {accuracyScore}");
                Console.WriteLine($"Fluency Score: {fluencyScore}");
                Console.WriteLine($"Completeness Score: {completenessScore}");
                Console.WriteLine($"Pronunciation Score: {pronunciationScore}");
            }

        }

```

**Comment by pankopon** [comment]
@yulin-li Can you please check.

**Comment by yulin-li** [comment]
@mbuotidem Thanks for using the pronunciation assessment and reaching out. We have a parameter `EnableMiscue`, with which enabled, the pronounced words will be compared to the reference text, and will be marked with omission/insertion based on the comparison. Accepted values are False and True. Default: False. If this parameter is set to false, the recognized text is always the reference text. See [doc here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-pronunciation-assessment).

**Comment by mbuotidem** [comment]
@yulin-li Thank you for the clarification, using the EnableMiscue parameter works :). Any chance the doc can be updated to call out that "If this parameter is set to false, the recognized text is always the reference text."? It does not currently state that.

**Comment by yulin-li** [comment]
@mbuotidem thanks for the suggestion, we will update the doc to make it clearer
