### ISSUE TITLE
very bad user experience in recording to text

### ISSUE THREAD

**Issue by Sleepingbug** [Azure-Samples/cognitive-services-speech-sdk#88]
Hello, I am an Azure user and I'm using Microsoft Cognitive Services.
The recognition accuracy and response speed of the new service are higher than the old one, which is very good.
But the efficiency of recording to text is still very low, 1 hour of recording files takes 34 minutes, a very bad experience.
In China, Iflytek is processed in 15 minutes or less.
Your strength lies in supporting more languages, but the efficiency of recording to text is really low.
I suggest that you change your approach,
The speech server waits until the recording file is uploaded, and then performs the cognitive service as a whole.
For recording to text, users are more concerned with the results, not the process.
Shorter wait, better experience

**Comment by wolfma61** [comment]
this service is tailored for real time speech. To tune the effectiveness of the service and responds time for all uses, the upload time of precorded files might be limited due to load of the service. This isn't effecting realtime streaming, just the streaming of files,

For pre-recorded files we strongly recommend the batch service, that is not effected by this

thx
Wolfgang

**Comment by Sleepingbug** [comment]
Thank you for your reply

**Comment by Sleepingbug** [comment]
Hello Wolfgang,
Can you tell me more about the batch transcription service?
I read the documentation for the batch service:
Https://docs.microsoft.com/en-US/azure/cognitive-services/speech-service/batch-transcription
The documentation does not seem to be as detailed as the REST API of the speech.
I tried to test with Java,
but failed。
I've seen the example of C#, I think the batch service end point should be:
Https://eastasia.cris.ai:443/api/speechtotext/v2.0/Transcriptions
But the actual operation is wrong, it seems that this uri does not exist.

**Comment by ramrezai** [comment]
Hi Sleepingbug, can you please provide more details?
What request did you try? And what status code did you get?

Here an example using the RestSharp nuget package:

	var client = new RestClient("https://eastasia.cris.ai/api/speechtotext/v2.0/transcriptions");
	var request = new RestRequest(Method.POST);
	request.AddHeader("ocp-apim-subscription-key", subscriptionKeyForEastAsia);
	request.AddHeader("content-type", "application/json");
	request.AddParameter("application/json", "{\r\n \"recordingsUrl\": \"" + url + "\",\r\n  \"locale\": \"en-us\",\r\n  \"name\": \"" +  name + "\"\r\n}", ParameterType.RequestBody);
	var response = client.Execute(request);

Hope this helps,
Ramin

**Comment by Sleepingbug** [comment]
Thank you very much！ your reply is very helpful to me.  now it seems that there is no error to upload information.
Now I am trying to get the text result , it has not been successful yet. I'm trying...

**Comment by Sleepingbug** [comment]
I am confused, the bath service doesn't return any results after uploading.
I don't know how to get results .
when I add one parameter "Ocp-Apim-Subscription-Key" (and set my key) to GET , 
I get a HTML result with "<title>Sign in to your account</title>".
when I add two or more parameters ( "local","name","description") to GET, I get a "not found" error.

**Comment by Sleepingbug** [comment]
@ramrezai Ramin，can you give me an example to GET  recording-to-text result ?
Thanks a lot.

**Comment by ramrezai** [comment]
Hi Sleepingbug, 
I guess something with your subscription key is wrong. Please make sure that you are using a Cognitive Speech Services Subscription Key for the eastasia region. Be aware also to not use the subscriptionId.

Here is an example of a GET request to get all your transcriptions:
var client = new RestClient("https://eastasia.cris.ai/api/speechtotext/v2.0/transcriptions");
var request = new RestRequest(Method.GET);
request.AddHeader("ocp-apim-subscription-key", subscriptionKeyForEastAsia);
request.AddHeader("content-type", "application/json");
IRestResponse response = client.Execute(request);

Hope this helps,
Ramin

**Comment by Sleepingbug** [comment]
No, subscription key is right.

**Comment by Sleepingbug** [comment]
Thank you all !!!
I'm so excited!!!
I can get the result now !
