### ISSUE TITLE
Improved intent recognizer responses

### ISSUE THREAD

**Issue by jamescarpinter** [Azure-Samples/cognitive-services-speech-sdk#880]
**Is your feature request related to a problem? Please describe.**
We've been using the Intent Recognizer capability that's part of the Speech SDK to perform both speech-to-text and LUIS-based intent recognition in a single call. However, we've been missing some of the capabilities that are available when using these services separately. Specifically, the ability to get prediction scores for all intents does not seem to be available via Intent Recognizer (but is available from LUIS directly). Other capabilities, like sentiment and options around profanity are also less available.

**Describe the solution you'd like**
Provide an option to retrieve the full LUIS response from the Intent Recognizer response. This would include content like scores for all intents (not just the top scoring one; against the V2 LUIS endpoint, this requires verbose=true, and against the V3 LUIS endpoint, this requires show-all-intents=true). Providing access to other parts of the LUIS response, like text sentiment (when enabled for the model), would also be useful.

**Describe alternatives you've considered**
While some of the benefits of Intent Recognizer, like speech priming, are highly useful, the missing features highlighted above are leading us to consider switching away from this approach and using Speech API + LUIS API separately to get the full power of each. We've also considered just adding just a subset of intents to the Intent Recognizer; however, the lack of an ability to remove intents after starting limits this capability in practice.

**Additional context**
N/A

**Comment by jhakulin** [comment]
@jamescarpinter Thanks for request, we are working on this and targeting to support all intents from the JSON with the Speech SDK API (v2 based LUIS) solution on the 1.15.0 release. The release has ETA around mid January 2021.

**Comment by pankopon** [comment]
Closed since there's a work item with ETA on our backlog. Please open a new issue if you need further support.
