### ISSUE TITLE
Azure Function Blob Trigger Not Recognized as StreamInput 

### ISSUE THREAD

**Issue by thedonmon** [Azure-Samples/cognitive-services-speech-sdk#882]
**Describe the bug**
When running an Azure Function v3 with a Blob Trigger to pull the file specified, the stream is not recognized as a .wav file to run through the Speech recognizer. The function setup is as follows:
```
		public static async Task RunNLP(
			[ActivityTrigger] string context,
			[Blob("audiophiles/{context}", FileAccess.Read, Connection = "BlobConnection")] Stream myBlob,
			ILogger log)
		{

```
I tried doing the following 
```
	using (var pushStream = AudioInputStream.CreatePushStream())
	{
		using (var audioInput = AudioConfig.FromStreamInput(pushStream))
		{
		    // Creates a speech recognizer using audio stream input.
		     using (var recognizer = new SpeechRecognizer(config, audioInput))
		     {
.... //await StartSpeechRecognitionAsync(..)
     using (BinaryReader reader = new BinaryReader(myBlob))
     {
	byte[] buffer = new byte[1000];
	while (true)
	{
	     var readSamples = reader.Read(buffer);
	     if (readSamples == 0)
	     {
		break;
	     }

		pushStream.Write(buffer, readSamples);
	}
     }

```
The stream gets written to the PushStream successfully but the recognizer keeps stating that the Speech was not recognized. When I load the file from the local machine instead it works. 

Is there anything I am missing here when reading a .wav file from blob?

**To Reproduce**
1. Create a blob trigger function
2. Upload a valid .wav file to the blob
3. Read in the stream and try to use it as stream input
4. Listen for the recognizer events and see that the result returns NotRecognized

**Expected behavior**
The stream from a valid .wav file should be read into the Recognizer successfully and output the correct result text. 

**Version of the Cognitive Services Speech SDK**
1.14.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - x86
 - Programming language: C#

**Additional context**
No errors just not processing the speech properly from the blobstream. 
I have tried using the specific WavStream codec as the PushStream as such:
```
			byte channels = 1;
			byte bitsPerSample = 16;
			int samplesPerSecond = 16000; // or 8000
			var audioFormat = AudioStreamFormat.GetWaveFormatPCM((uint)samplesPerSecond, bitsPerSample, channels);
			StringBuilder sb = new StringBuilder();
			using (var pushStream = AudioInputStream.CreatePushStream(audioFormat))

```
No luck as well.

**Comment by jhakulin** [comment]
@thedonmon
Please check that local.settings from your Azure function project are also deployed in the settings inside Azure portal, e.g. check that your "BlobConnection" value is set correcty in portal also.

Also you could read directly from blob to pushstream: 
```csharp
// Start continuous recognition. Uses StopContinuousRecognitionAsync() to stop recognition.
await recognizer.StartContinuousRecognitionAsync().ConfigureAwait(false);

// open and read the stream and push the buffers into the recognizer
byte[] buffer = new byte[1000];
while (true)
{                            
    var readSamples = myBlob.Read(buffer, 0, buffer.Length);
    if (readSamples == 0)
    {
        break;
    }
    pushStream.Write(buffer, readSamples);
}
pushStream.Close();

// Waits for completion.
// Use Task.WaitAny to keep the task rooted.
Task.WaitAny(new[] { stopRecognition.Task });

// Stop recognition.
await recognizer.StopContinuousRecognitionAsync().ConfigureAwait(false);
```

**Comment by thedonmon** [comment]
> @thedonmon
> Please check that local.settings from your Azure function project are also deployed in the settings inside Azure portal, e.g. check that your "BlobConnection" value is set correcty in portal also.
> 
> Also you could read directly from blob to pushstream:
> 
> ```cs
> // Start continuous recognition. Uses StopContinuousRecognitionAsync() to stop recognition.
> await recognizer.StartContinuousRecognitionAsync().ConfigureAwait(false);
> 
> // open and read the stream and push the buffers into the recognizer
> byte[] buffer = new byte[1000];
> while (true)
> {                            
>     var readSamples = myBlob.Read(buffer, 0, buffer.Length);
>     if (readSamples == 0)
>     {
>         break;
>     }
>     pushStream.Write(buffer, readSamples);
> }
> pushStream.Close();
> 
> // Waits for completion.
> // Use Task.WaitAny to keep the task rooted.
> Task.WaitAny(new[] { stopRecognition.Task });
> 
> // Stop recognition.
> await recognizer.StopContinuousRecognitionAsync().ConfigureAwait(false);
> ```

Will try this forsure! The connections are correct and can confirm the stream is valid but didnt think of reading directly from it. Thanks for the suggestion will report back if it works.

**Comment by thedonmon** [comment]
> @thedonmon
> Please check that local.settings from your Azure function project are also deployed in the settings inside Azure portal, e.g. check that your "BlobConnection" value is set correcty in portal also.
> 
> Also you could read directly from blob to pushstream:
> 
> ```cs
> // Start continuous recognition. Uses StopContinuousRecognitionAsync() to stop recognition.
> await recognizer.StartContinuousRecognitionAsync().ConfigureAwait(false);
> 
> // open and read the stream and push the buffers into the recognizer
> byte[] buffer = new byte[1000];
> while (true)
> {                            
>     var readSamples = myBlob.Read(buffer, 0, buffer.Length);
>     if (readSamples == 0)
>     {
>         break;
>     }
>     pushStream.Write(buffer, readSamples);
> }
> pushStream.Close();
> 
> // Waits for completion.
> // Use Task.WaitAny to keep the task rooted.
> Task.WaitAny(new[] { stopRecognition.Task });
> 
> // Stop recognition.
> await recognizer.StopContinuousRecognitionAsync().ConfigureAwait(false);
> ```

No luck using this method... Even tried passing in the audioFormat to the PushStream still comes back as NoMatch

**Comment by jhakulin** [comment]
@thedonmon How did you verify input data is ok ?

**Comment by thedonmon** [comment]
> @thedonmon How did you verify input data is ok ?

It's the same file I have locally so unless uploading it to the blob changes the data when it gets streamed in it should be ok. Especially since when I reference the same file locally it transcribes properly. I verified the wav headers were present in the stream as well. Is there another method you suggest?

**Comment by jhakulin** [comment]
@thedonmon Also I want to double check, you have checked in Azure Portal, blob connection which you have inside local.settings file in your Azure function project exists in Azure Portal ? I think I had the same issue you are reporting before and the reason was that my settings in Azure Portal were not correct

**Comment by jhakulin** [comment]
@thedonmon One other comment I have is that have you logged you get any intermediate results using Microsoft.Extensions.Logging ? Could you add logs like following and provide us sessionId, so that we can check what happened on service side.

```csharp
recognizer.Recognizing += (s, e) =>
{
    log.LogInformation($"RECOGNIZING: Text={e.Result.Text}");
};

recognizer.Recognized += (s, e) =>
{
    if (e.Result.Reason == ResultReason.RecognizedSpeech)
    {
        log.LogInformation($"RECOGNIZED: Text={e.Result.Text}");
        result += e.Result.Text;
    }
    else if (e.Result.Reason == ResultReason.NoMatch)
    {
        log.LogInformation($"NOMATCH: Speech could not be recognized.");
    }
};

recognizer.Canceled += (s, e) =>
{
    log.LogInformation($"CANCELED: Reason={e.Reason}");

    if (e.Reason == CancellationReason.Error)
    {
        log.LogInformation($"CANCELED: ErrorCode={e.ErrorCode}");
        log.LogInformation($"CANCELED: ErrorDetails={e.ErrorDetails}");
        log.LogInformation($"CANCELED: Did you update the subscription info?");
    }

    stopRecognition.TrySetResult(0);
};

recognizer.SessionStarted += (s, e) =>
{
    log.LogInformation($"\nSession started event, sessionID={e.SessionId}");
};

recognizer.SessionStopped += (s, e) =>
{
    log.LogInformation($"\nSession stopped event, sessionID={e.SessionId}");
    log.LogInformation($"\nStop recognition.");
    stopRecognition.TrySetResult(0);
};
```

**Comment by thedonmon** [comment]
@jhakulin yea I've checked the settings a few times they are correct I've confirmed it's the correct file streaming in. I can try and see if I can switch to secondary key or something and see. 

I'll definitely add session id and update soon. Thanks so much for the help would be really great to get this working

**Comment by thedonmon** [comment]
@jhakulin Here are a few session Ids:
00f008cd087747419848e7a00b554440
9c74a6b5642f4b1390fae81d1c2b4270
7d8d88cd33364eb9b18578d1a6043e27

Let me know if you need more info.

**Comment by jhakulin** [comment]
@thedonmon I checked the function of AzureFunction with 1.14.0 worked OK on my side. 
I have attached the script I used for your testing
[BlobTriggerCSharp1.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/5657389/BlobTriggerCSharp1.zip)

Steps what I did are basically following:

1. Created storage resource and under that container (MyBlobContainer), where to upload the wave files) on Azure portal
2. Created Azure Function on VSCode for C# as a Blob trigger which use the storage account you created and connects to MyBlobContainer
3. Integrated the attached C# script to the VSCode project
4. Tested the project works locally by uploading a file to Azure blob container and see that gets transcribed on VSCode output
5. Deployed the VSCode project as new function to Azure using the Azure VSCode extension
6. Added MyStorage_STORAGE connection key (from local.settings.json file from VSCode project) value pair to Azure function (BlobTriggerCSharp1) settings inside Azure portal (NOTE: this setting was not there by default and needs to be added)
7. Tested that Azure function works in Azure portal by uploading files to the container by using using BlobTriggerCSharp1 | Monitor and where I can see the result when looking the monitor output .

Please check you did all these.

**Comment by jhakulin** [comment]
@thedonmon If the previous steps do not help, could you share your wave file also ?

**Comment by pankopon** [comment]
Closed as resolved since no further updates. Please open a new issue if you need more support.
