### ISSUE TITLE
Quickstart from-file does not use file, but microphone only

### ISSUE THREAD

**Issue by marki555** [Azure-Samples/cognitive-services-speech-sdk#884]
**Describe the bug**
Quickstart for JavaScript/browser should contain example which uses wav file as a source for Speech to Text recognition, but the provided index.html only contains code for recognition from microphone.
File `quickstart/javascript/browser/from-file/index.html` is almost the same as `quickstart/javascript/browser/from-microphone/index.html`

**Expected behavior**
Provide correct quickstart example also for "from-file".

**Version of the Cognitive Services Speech SDK**
Downloaded master branch as ZIP today.

**Comment by BrianMouncer** [comment]
@glharper 

User feedback seems valid to me.

        speechConfig.speechRecognitionLanguage = "en-US";
        var audioConfig  = SpeechSDK.AudioConfig.fromDefaultMicrophoneInput();
        recognizer = new SpeechSDK.SpeechRecognizer(speechConfig, audioConfig);

Did we change this for testing, and accidentally push to out?
Either way, can you please update?

Thanks,

**Comment by glharper** [comment]
@marki555 Thank you for bringing this to our attention! I've checked in more applicable sample, if you'd care to verify: [from file JS Speech Recognition sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/javascript/browser/from-file/index.html)
