### ISSUE TITLE
Support for Ubuntu 18

### ISSUE THREAD

**Issue by vins31** [Azure-Samples/cognitive-services-speech-sdk#89]
**Is your feature request related to a problem? Please describe.**
As reported in this issue  #38, the current C++ and Java SDK are not compatible with Ubuntu 18 (we reproduced the issue).
We are very surprised there is not support for Ubuntu 18, released 6 months ago. It is not an exotic OS! Unfortunately, using Ubuntu 16 is not an option for us.

**Describe the solution you'd like**
We would like a build of the SDK with Ubuntu18 support or access to the source code.

**Describe alternatives you've considered**
As an alternative, we will have to consider using Google Speech-to-text

**Comment by wolfma61** [comment]
yes, agree - we will add support for Ubuntu in one of our coming updates. It will not make it into the update, but hopefully in the December one 

sorry for the inconvenience ...

Wolfgang

**Comment by mahilleb-msft** [comment]
Version 1.2.0 was tested against Ubuntu 18.04, can you give it a go?

On top of your development tools, make sure to install packages that the SDK depends on:

```
sudo apt-get update
sudo apt-get install libssl1.0.0 libcurl3 libasound2 wget
```

Best, Mark

**Comment by mahilleb-msft** [comment]
Closing this one, please let us know if you run into any problems.

Thanks, Mark

**Comment by vins31** [comment]
We performed tests this morning with this new version and it works perfectly.
Thank you for your reactivity.
