### ISSUE TITLE
Installation of the module succeeds on one Ubuntu system but not on Raspbian

### ISSUE THREAD

**Issue by JoergZ2** [Azure-Samples/cognitive-services-speech-sdk#890]
I've installed cognitive-services-speech-sdk on a Ubuntu 20.04 system with python 3.8 (64 bit). All works fine. Withe a simple python script I got german speech from my given text. Now I tried to install on a Raspbian System also with python 3.8 (64 bit).
Errors:
```
ERROR: Could not find a version that satisfies the requirement azure.cognitiveservices.speech (from versions: none)
ERROR: No matching distribution found for azure.cognitiveservices.speech

pi@raspi:~$ python --version
Python 3.8.5

pi@raspi:~$ pip3 --version
pip 20.2.2 from /usr/lib/python3.8/site-packages/pip (python 3.8)

pi@raspi:~$ python -c "import struct; print(struct.calcsize('P') * 8)"
64
```
Extensive log file in the appendix. 
[pip_error.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/5652759/pip_error.log)

**Comment by pankopon** [comment]
Hi, unfortunately the Speech SDK does not support the Raspbian OS or Python on Linux ARM at the moment. There is no ETA for Raspbian support, but Python on ARM may appear at some point next year. Please use one of the supported development environments for now, see
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk?tabs=linux%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio#get-the-speech-sdk
