### ISSUE TITLE
No audio data received

### ISSUE THREAD

**Issue by venkatr21** [Azure-Samples/cognitive-services-speech-sdk#895]
I'm using expo react native, to record a 3-second audio and I wanted it to be transcribed with Azure speech to text REST API.
I get the response as "No audio data received"
Here is my code,
```
const stream = await FileSystem.readAsStringAsync(this.recording.getURI());
    const headers = {
      method: "POST",
      headers: {
        "Content-type": "audio/wav; codecs=audio/pcm; samplerate=16000",
        "Ocp-Apim-Subscription-Key": subscription_key_voice
        },
      body: stream
    }
    fetch(endpoint_voice,headers)
    .then(res => res.text())
    .then(val => console.log(val))
```
Please help me solve this issue, thanks!

**Comment by eldakms** [comment]
Could you please add "&RequestId=<someguid>" to the URL and give me the value of <someguid>, so that I can find this particular request on the service side and check the logs? Thanks!

**Comment by venkatr21** [comment]
> Could you please add "&RequestId=" to the URL and give me the value of , so that I can find this particular request on the service side and check the logs? Thanks!

`Object {
  "config": Object {
    "adapter": [Function xhrAdapter],
    "audio": "",
    "data": undefined,
    "headers": Object {
      "Accept": "application/json, text/plain, */*",
      "Ocp-Apim-Subscription-Key": "KEY",
      "Transfer-Encoding": "chunked",
    },
    "maxBodyLength": -1,
    "maxContentLength": -1,
    "method": "post",
    "timeout": 0,
    "transformRequest": Array [
      [Function transformRequest],
    ],
    "transformResponse": Array [
      [Function transformResponse],
    ],
    "url": "https://eastus.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?language=en-US&requestId",
    "validateStatus": [Function validateStatus],
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
  },
  "data": "No audio data received",
  "headers": Object {
    "cache-control": "public, max-age=0",
    "content-type": "text/plain; charset=utf-8",
    "date": "Mon, 14 Dec 2020 10:22:38 GMT",
    "server": "Kestrel",
    "strict-transport-security": "max-age=31536000; includeSubDomains",
    "transfer-encoding": "chunked",
  },
  "request": XMLHttpRequest {
    "DONE": 4,
    "HEADERS_RECEIVED": 2,
    "LOADING": 3,
    "OPENED": 1,
    "UNSENT": 0,
    "_aborted": false,
    "_cachedResponse": undefined,
    "_hasError": false,
    "_headers": Object {
      "accept": "application/json, text/plain, */*",
      "ocp-apim-subscription-key": "KEY",
      "transfer-encoding": "chunked",
    },
    "_incrementalEvents": false,
    "_lowerCaseResponseHeaders": Object {
      "cache-control": "public, max-age=0",
      "content-type": "text/plain; charset=utf-8",
      "date": "Mon, 14 Dec 2020 10:22:38 GMT",
      "server": "Kestrel",
      "strict-transport-security": "max-age=31536000; includeSubDomains",
      "transfer-encoding": "chunked",
    },
    "_method": "POST",
    "_perfKey": "network_XMLHttpRequest_https://eastus.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?language=en-US&requestId",     
    "_requestId": null,
    "_response": "No audio data received",
    "_responseType": "",
    "_sent": true,
    "_subscriptions": Array [],
    "_timedOut": false,
    "_trackingName": "unknown",
    "_url": "https://eastus.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?language=en-US&requestId",
    "readyState": 4,
    "responseHeaders": Object {
      "Cache-Control": "public, max-age=0",
      "Content-Type": "text/plain; charset=utf-8",
      "Date": "Mon, 14 Dec 2020 10:22:38 GMT",
      "Server": "Kestrel",
      "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
      "Transfer-Encoding": "chunked",
    },
    "responseURL": "https://eastus.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?language=en-US&requestId",
    "status": 400,
    "timeout": 0,
    "upload": XMLHttpRequestEventTarget {},
    "withCredentials": true,
  },
  "status": 400,
  "statusText": undefined,
}`

This was the response, the ID for the response is NULL!

**Comment by venkatr21** [comment]
> Could you please add "&RequestId=" to the URL and give me the value of , so that I can find this particular request on the service side and check the logs? Thanks!

`https://eastus.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?language=en-US&RequestId=1234512345`
This was the value of RequestId i sent! Thanks

**Comment by eldakms** [comment]
On the service side we do not see the audio. are you sure you are actually sending the bytes (can you use fiddler/or browser to check)? can you also maybe share an audio file with me if it is not private and specific one? i cannot reproduce this on our side if i simply use curl. thanks!

**Comment by venkatr21** [comment]
> On the service side we do not see the audio. are you sure you are actually sending the bytes (can you use fiddler/or browser to check)? can you also maybe share an audio file with me if it is not private and specific one? i cannot reproduce this on our side if i simply use curl. thanks!

Is there any threshold on the minimum size of the audio file? Mine is just a 3-second audio file! I've actually converted the audio to a base64 encoded format before adding it to the request body, is the method by which I'm adding, correct?

**Comment by venkatr21** [comment]
I figured it out, for the problem "No Audio data Received", the audio file should be added as binary data in a field called "data" in the request. Your request will somewhat look like:
`
config = {
method: 'post',
URL : 'url here',
headers : { list of all headers here},
data : 'audio data as binary coded string'
}
axios(config)
.then()
.catch()
`
This is how the request looks like in Node.js axios request method.
