### ISSUE TITLE
The source language can be modified in the process of translation？

### ISSUE THREAD

**Issue by shaydeng** [Azure-Samples/cognitive-services-speech-sdk#898]
I hope that the source language can be modified in the process of translation without restarting the translation function.

**Comment by trrwilson** [comment]
Hello!

Although `TranslationRecognizer` supports adding target languages mid-recognition, source language can't be modified once the recognition operation has started. This feature, along with multiple-source-language recognition, is something under active investigation. In the meantime, you should be able to switch source languages by simply re-creating the recognizer; the below snippet demonstrates changing both targets and source during a single user-perceived interaction.

```cs
  TranslationRecognizer GetRecognizer(string sourceLanguage, params string[] targetLanguages)
  {
      var config = SpeechTranslationConfig.FromSubscription(Subscriptions.WestUS2.Key, Subscriptions.WestUS2.Region);
      config.SpeechRecognitionLanguage = sourceLanguage;
      targetLanguages.ToList().ForEach(target => config.AddTargetLanguage(target));
      var recognizer = new TranslationRecognizer(config);
      recognizer.Recognized += (_, e) =>
      {
          Print($"Recognized: {e.Result.Text}");
          e.Result.Translations.ToList().ForEach(translation => Print($"  {translation.Key} : {translation.Value}"));
      };
      return recognizer;
  }

  using (var translator = GetRecognizer("en-US", "fr"))
  {
      await translator.StartContinuousRecognitionAsync();
      Print($"Recognizing English to French, 10 seconds");
      await Task.Delay(TimeSpan.FromSeconds(10));
      translator.AddTargetLanguage("es");
      Print($"Recognizing English to French & Spanish, 10 seconds");
      await Task.Delay(TimeSpan.FromSeconds(10));
      await translator.StopContinuousRecognitionAsync();
  }

using (var translator = GetRecognizer("es-ES", "en-US", "fr"))
{
    await translator.StartContinuousRecognitionAsync();
    Print($"Recognizing Spanish to English & French, 10 seconds");
    await Task.Delay(TimeSpan.FromSeconds(10));
    translator.AddTargetLanguage("de");
    Print($"Recognizng Spanish to English, French, & German, 10 seconds");
    await Task.Delay(TimeSpan.FromSeconds(10));
    await translator.StopContinuousRecognitionAsync();
}
```
The output from this is what you'd expect for a seamless interaction:
```
[09:53.065] Recognizing English to French, 10 seconds
[09:55.922] Recognized: Hello.
[09:55.959]   fr : Bonjour.
[10:03.365] Recognizing English to French & Spanish, 10 seconds
[10:06.919] Recognized: Hi there.
[10:06.955]   es : Hola.
[10:06.986]   fr : Salut.
[10:15.281] Recognizing Spanish to English & French, 10 seconds
[10:18.785] Recognized: ¿Cómo estás?
[10:18.815]   en : How are you?
[10:18.846]   fr : Comment vas-tu?
[10:25.360] Recognizng Spanish to English, French, & German, 10 seconds
[10:29.794] Recognized: Más o menos bien, no.
[10:29.824]   de : Ziemlich gut, nein.
[10:29.855]   en : Pretty good, no.
[10:29.886]   fr : Plutôt bien, non.
```

Is this approach of regenerating the recognizer problematic for your use case? We'd love to learn more about your scenario and needs.

**Comment by shaydeng** [comment]
@trrwilson 
Hi trrwilson,

I write the voice data into the audio file continuously, and then read the voice data continuously from the audio file for translation.
If I switch the source language by recreating the recognizer, the offset of the translation result will be recalculated, but I need the offset to index the location of the audio file.
Here is an example of my implementation process.
`
<dependency>
      <groupId>com.microsoft.cognitiveservices.speech</groupId>
      <artifactId>client-sdk</artifactId>
      <version>1.14.0</version>
    </dependency>
`

`	
public static void translationWithAudioStreamAsync() throws InterruptedException, ExecutionException, IOException, UnsupportedAudioFileException {
		
		SpeechTranslationConfig config = SpeechTranslationConfig.fromSubscription("", "eastasia");

		String fromLanguage = "en-US";
		config.setSpeechRecognitionLanguage(fromLanguage);
		config.addTargetLanguage("zh-Hans");
		config.addTargetLanguage("en");
		config.requestWordLevelTimestamps();

		boolean read = true;
		File file = new File("C:\\logs\\record-1608108056247.wav");
		RandomAccessFile raf = new RandomAccessFile(file, "r");
		PushAudioInputStream pushStream = AudioInputStream.createPushStream();
		AudioConfig audioInput = AudioConfig.fromStreamInput(pushStream);

		TranslationRecognizer recognizer = new TranslationRecognizer(config, audioInput);
		{
			recognizer.recognizing.addEventListener((s, e) -> {
			});

			recognizer.recognized.addEventListener((s, e) -> {
				if (e.getResult().getReason() == ResultReason.TranslatedSpeech) {
					String json = e.getResult().getProperties().getProperty(PropertyId.SpeechServiceResponse_JsonResult);
					System.out.println("json=" + json);
				}
				if (e.getResult().getReason() == ResultReason.RecognizedSpeech) {
					System.out.println("RECOGNIZED: Text=" + e.getResult().getText());
					System.out.println("    Speech not translated.");
				}
				else if (e.getResult().getReason() == ResultReason.NoMatch) {
					System.out.println("NOMATCH: Speech could not be recognized.");
				}
			});

			recognizer.canceled.addEventListener((s, e) -> {
				System.out.println("CANCELED: Reason=" + e.getReason());

				if (e.getReason() == CancellationReason.Error) {
					System.out.println("CANCELED: ErrorCode=" + e.getErrorCode());
					System.out.println("CANCELED: ErrorDetails=" + e.getErrorDetails());
					System.out.println("CANCELED: Did you update the subscription info?");
				}
			});

			recognizer.sessionStarted.addEventListener((s, e) -> {
				System.out.println("\nSession started event.");
			});

			recognizer.sessionStopped.addEventListener((s, e) -> {
				System.out.println("\nSession stopped event.");
				System.out.println("\nStop translation.");
			});

			System.out.println("Start translation...");
			recognizer.startContinuousRecognitionAsync().get();

			byte[] readBuffer = new byte[4096];

			// Continuous read audio data
			while (read) {
				if (raf.getFilePointer() < raf.length()) {
					raf.read(readBuffer);
					pushStream.write(readBuffer);
				}
				else {
					Thread.sleep(1000);
				}

			}

			pushStream.close();

			System.out.println("Press any key to stop");
			new Scanner(System.in).nextLine();

			// Stops translation.
			recognizer.stopContinuousRecognitionAsync().get();
		}
		config.close();
		audioInput.close();
		recognizer.close();
	}
`

**Comment by pankopon** [comment]
As the requested functionality is currently not available and based on comments the suggested workaround is not sufficient, I've added a work item to our backlog for consideration in future Speech SDK releases.

Closing this issue, we will update when the work is done and the release schedule is known. Please create a new item if you need support on other topics.
