### ISSUE TITLE
build error by android.mk

### ISSUE THREAD

**Issue by zhaize1115** [Azure-Samples/cognitive-services-speech-sdk#90]
1. I add the client-sdk-1.0.1.aar into my project which is a system-app in android source code,
and make by Android.mk, then it will build error:
**ERROR: IntentRecognizer.java:136-137: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.concurrent.Callable**
2. It will be OK building by gradle in AndroidStudio. But it is system-app, we have to build by Android.mk.
3.There is my [Android.mk.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/2533491/Android.mk.txt).
@jdhuntington @chad @paulbatum @berberich

**Comment by fmegen** [comment]
Did you set  the option to compile with JAVA_1_8 as this is needed by the library.

**Comment by zhaize1115** [comment]
> Did you set the option to compile with JAVA_1_8 as this is needed by the library.

I have set the option LOCAL_JAVA_LANGUAGE_VERSION := 1.8 in Android.mk, but it will still build error.

**Comment by zhaize1115** [comment]
> > Did you set the option to compile with JAVA_1_8 as this is needed by the library.
> 
> I have set the option LOCAL_JAVA_LANGUAGE_VERSION := 1.8 in Android.mk, but it will still build error. @fmegen

**Comment by zhaize1115** [comment]
> Did you set the option to compile with JAVA_1_8 as this is needed by the library.

@fmegen I have solved this problem. Set the option LOCAL_JACK_ENABLED := disabled to close Jack compiler, because jack does not support lambda.Thank you all the same.
