### ISSUE TITLE
Reusing SpeechRecognizer object multiple time

### ISSUE THREAD

**Issue by imankur** [Azure-Samples/cognitive-services-speech-sdk#900]
In my use case, I want to recognize speech multiple times after some time interval.

```
const speechRecognizer = new SpeechSDK.SpeechRecognizer(speechConfig, audioConfig);
speechRecognizer.recognizeOnceAsync(
    function (result) {
        window.console.log(result);
    }
);
```
Can I reuse this `speechRecognizer` object or I need to create a new instance every time I want to perform speech to text task?

SDK - cognitive-services-speech-sdk javascript

**Comment by glharper** [comment]
@imankur In the current version (1.14.1), reusing the speechRecognizer object doesn't work, you will have to create a new one. The next version (1.15) has a fix and reusing the object works.
