### ISSUE TITLE
How to get crashdump from speech SDK

### ISSUE THREAD

**Issue by maczikasz** [Azure-Samples/cognitive-services-speech-sdk#901]
Hi,

our production service runs inside Azure App Services and sometimes semi randomly produces crashes from inside the Azure speech SDK. We would like to analyze these crashes to be able to find our why this could happen, so far we were not able to consistently reproduce it. Is there any way to force the azure SDK to create a crash dump somewhere? 

We are running a linux docker image, contai ning a JAVA app, running in a linux app service environment inside azure. I would appreciate some help (there is also an azure support ticket open, if you need the number I can provide it)

Szava

**Comment by jhakulin** [comment]
@maczikasz Currently Speech SDK APIs do not have capability to enable crash dumps. Have you tried to enable core dumps for the docker image? Some finding from SO https://stackoverflow.com/questions/28335614/how-to-generate-core-file-in-docker-container

**Comment by pankopon** [comment]
Closed as resolved since no further updates, please create a new issue if you need more support.
