### ISSUE TITLE
Are webhooks no longer calling back in southcentralus?

### ISSUE THREAD

**Issue by kleindev** [Azure-Samples/cognitive-services-speech-sdk#906]
I originally thought I was getting the stuck "NotStarted" issue again, but it looks like they are completing, but not calling the webhook back.

The last call back I got was 

12/30/2020, 4:27:37.027 AM
--

Any insight on why a webhook would stop calling back?

**Comment by bexxx** [comment]
Could you please let me know the identity of your webhook, or the name of your subscription? This would be me to get your service logs and look at the issue.

**Comment by bexxx** [comment]
What you can do yourself is to check the state of your webhook by doing a GET on it. 

The service sets it to failed if there were too many failures while calling into your callback. If it's in state "Failed" you can simply update the url to the same value to try enabling it again (with a PATCH).

**Comment by kleindev** [comment]
Thank you - here is the info:

We have two, but the key one:
https://southcentralus.api.cognitive.microsoft.com/speechtotext/v3.0/webhooks/80f96f25-3087-469d-990a-b18e268ea895


Details-> 
  "displayName": "Transcription web hook",
      "self": "https://southcentralus.api.cognitive.microsoft.com/speechtotext/v3.0/webhooks/80f96f25-3087-469d-990a-b18e268ea895",
      "links": {
        "ping": "https://southcentralus.api.cognitive.microsoft.com/speechtotext/v3.0/webhooks/80f96f25-3087-469d-990a-b18e268ea895/ping",
        "test": "https://southcentralus.api.cognitive.microsoft.com/speechtotext/v3.0/webhooks/80f96f25-3087-469d-990a-b18e268ea895/test"

  "displayName": "Transcription Grader web hook",
      "self": "https://southcentralus.api.cognitive.microsoft.com/speechtotext/v3.0/webhooks/47481178-9122-4794-b94a-c3f58cd44716",
      "links": {
        "ping": "https://southcentralus.api.cognitive.microsoft.com/speechtotext/v3.0/webhooks/47481178-9122-4794-b94a-c3f58cd44716/ping",
        "test": "https://southcentralus.api.cognitive.microsoft.com/speechtotext/v3.0/webhooks/47481178-9122-4794-b94a-c3f58cd44716/test"

**Comment by kleindev** [comment]
Here is a result of a Get - status appears to be "Succeeded" 

{
  "displayName": "Transcription web hook",
  "self": "https://southcentralus.api.cognitive.microsoft.com/speechtotext/v3.0/webhooks/80f96f25-3087-469d-990a-b18e268ea895",
  "links": {
    "ping": "https://southcentralus.api.cognitive.microsoft.com/speechtotext/v3.0/webhooks/80f96f25-3087-469d-990a-b18e268ea895/ping",
    "test": "https://southcentralus.api.cognitive.microsoft.com/speechtotext/v3.0/webhooks/80f96f25-3087-469d-990a-b18e268ea895/test"
  },
  "properties": {
    "apiVersion": "v3.0"
  },
  "webUrl": "https://func-snasr-prod-001.azurewebsites.net/api/callback",
  "events": {
    "transcriptionCreation": true,
    "transcriptionProcessing": true,
    "transcriptionCompletion": true
  },
  "createdDateTime": "2020-11-05T21:08:32Z",
  "lastActionDateTime": "2020-11-05T21:08:33Z",
  "status": "Succeeded"
}

**Comment by bexxx** [comment]
The queue was processing unusually slow. We restarted it and you should see the notifications appear until it catches up.

**Comment by kleindev** [comment]
Awesome!  I have logging on my end to catch this sooner now.

If this should appear again, is raising an issue here the best way to address?

**Comment by rarera** [comment]
The system has fully catched up processing should be fast again.
Yes, filing an issue in GitHub is a good way to ask for support.

**Comment by bexxx** [comment]
We also tweaked the thresholds for our internal monitoring to catch this kind of issue faster (threshold was too relaxed)

**Comment by kleindev** [comment]
Thank you both

**Comment by kleindev** [comment]
@bexxx or @rarera any chance the queues are running behind today (southcentralus)?  We're starting to see items waiting for over 1 hour - just curious.  Not sure the best way to ask about this

**Comment by chlandsi** [comment]
Hi @kleindev, yes we are looking at an issue with higher latencies than usual. We are sorry for the inconvenience.
You can report issues here or submit a support request in the Azure Portal.

**Comment by kleindev** [comment]
@chlandsi - sorry to bother, but it seems as though there still may be latencies?

**Comment by chlandsi** [comment]
Hi @kleindev, yes, unfortunately we are still seeing this issue. We hope we'll have a more permanent situation in the next few days. If you have the possibility to switch your traffic to a different region, this will very likely improve the situation; US South Central is more affected than other regions.

**Comment by kleindev** [comment]
Which region is least impacted?  I would need to move/retrain all data - not necessarily a quick task, but possible

**Comment by chlandsi** [comment]
Hi @kleindev, all other (US and non-US) regions should be better. We do, however, expect to improve the situation also in USSC next week.

**Comment by kleindev** [comment]
Ok our audio traffic tapers off after Friday 6 pm central - so fingers crossed we can hobble through the rest of today and tomorrow.  I appreciate the transparency and help

**Comment by kleindev** [comment]
seems like it is in a better state today (so far) - just curious if the fix/improvement you had in mind was able to be put in place already?

**Comment by chlandsi** [comment]
Hi @kleindev, sorry for the delayed response - yes, we deployed a first batch of fixes on 03/22 around 9:0 UTC, and that has improved delays according to our metrics. A second batch of improvements is currently being rolled out, which will reach US South Central end of this or beginning of next week. Please reach out if you continue to see problems!

**Comment by kleindev** [comment]
Looks like I have about 800+ jobs stuck last 24 hours...  

I need to find a way to work around this issue

**Comment by eldakms** [comment]
i see a lot of webhook events in the queue, it is being cleaned up slowly.

**Comment by kleindev** [comment]
I don't see any new requests..  we are pulling people in to manually type

**Comment by chlandsi** [comment]
It is only the webhooks which are showing delays, transcriptions are being processed. Please try polling the API as a fallback.

**Comment by kleindev** [comment]
Meaning the webhook on my azure subscription is not responding ?

**Comment by chlandsi** [comment]
We would need the webhook id to check on that particular webhook, but I don't think this was the problem. We have made a change so that queued up webhook invocations are processed quickly now. Still, it would be good if your application would fall back on polling the API if there is no response on the webhook within the expected timeframe.

**Comment by eldakms** [comment]
it will take approx an hour for the queue to clean up

**Comment by kleindev** [comment]
Ok I'll check over the next hour, I don't see them currently.   We'll work on adding something to poll the API as well

**Comment by kleindev** [comment]
Do there happen to be any queue or web hook issues in south central ?

**Comment by hakansoncu** [comment]
Web hooks function as expected in south central. The last request to your web hook (80f96f25-3087-469d-990a-b18e268ea895) was on 04-07-2021 at 05:21 UTC. Do you trigger any job after that time?

**Comment by kleindev** [comment]
Perfect - that helps me troubleshoot the issue - thank you

**Comment by kleindev** [comment]
We are seeing a few items that don't appear to have been called back since ~9 am central.  We are working on changes to poll the service instead, but that is not yet in production -  Curious if there is any queue backlog

**Comment by kleindev** [comment]
Good morning - just wanted to do a quick health check - last call back I see is 4/20/2021, 10:25:16.173 PM (cst) - do thinks look clear on the southcentral side?

**Comment by rarera** [comment]
Hi kleindev, on our side everything looks fine, queues are emptied ...
it looks like we get ServiceUnavailable when we try to send the webhook requests.

**Comment by kleindev** [comment]
@rarera did it say where service unavailable is coming from?  Here is what I show 

![image](https://user-images.githubusercontent.com/9289866/115593807-985fa380-a29a-11eb-960a-7a2241dba932.png)

**Comment by kleindev** [comment]
I'm confused where the service unavailable comes from - Azure functions here have no trace of 503

**Comment by kleindev** [comment]
I've pinged and tested from and they were both accepted.  Is there something else I need to do to reset this?  Again I don't see any trace of service unavailable

**Comment by kleindev** [comment]
I've deleted the webhooks, re-added, the web hooks now have a status of success.  I submitted a few and it was working - but now I believe it has stopped again (last call back over 1 hour ago).

**Comment by rarera** [comment]
Hi kleindev, our queues are empty in southcentral us, so from that perspective it looks good.
I am now checking if I find again that we received Service Unavailable

**Comment by rarera** [comment]
Hi again, I went again through our logs and dashboards. Our service looks healthy, all errors I find are about timeout (no answer from the remote server). In some cases I see also service availability problems on the remote server. If restart on your side helped, that might be an indicator that you need to look into the health of your side as well. You might want to look into your Azure function, and check the usage, see if it is pegged.

Most of the problems I see with remote sites is when the remote server does not answer, and we get a timeout.
