### ISSUE TITLE
Conversion of a byte[] to AudioInputStream

### ISSUE THREAD

**Issue by Muskan-14** [Azure-Samples/cognitive-services-speech-sdk#91]
I am building an ASP.Net Core WebAPI project in which I want to implement Speech to text conversion for which I am using Microsoft Cognitive Services.
Following the samples, I want to use AudioConfig.FromStreamInput which accepts an AudioInputStream type of object but my input is either a byte[] or a Stream. There is no method in AudioInputStream which can be overriden to take my input and provide an AudioInputStream  object in return.

Please tell me how this can be solved.
Thank you.

**Comment by zhouwangzw** [comment]
You can create a PushAudioInputStream, which can be passed to AudioConfig.FromStreamInput. Then you can write your data into the push stream by using its Write() method, and close the stream after you send all data. 

We will add samples for using PushAudioInputStream very soon.

Thanks

**Comment by Muskan-14** [comment]
Apologies in the delay and thank you for the reply, @zhouwangzw 
I will try the method you have suggested. Meanwhile, I have found a way too. 
I noticed in one of the sample codes that if we pass a Binary reader type of object to ReadInputAsAudioConfig(), it inherently calls FromStreamInput() and returns an AudioConfig type of object itself which can directly be passed to the Speech Recongnizer with my configuration settings.

I have therefore converted my input stream to an object of Binary reader type and used the above mentioned way to pass it to my recognizer and it works as expected.
Please suggest if this workaround is alright and which is better to use as well. 

Thank you.

**Comment by Muskan-14** [comment]
Apologies for the delay and thank you for the reply, @zhouwangzw 
I have tried your method and it works as expected. Thank you.
Meanwhile, I have found a way too. 
Since, my first input is of type Stream, I noticed in one of the sample codes that FromStreamInput also takes in a BinaryAudioStreamReader type of object.
I have therefore converted my input stream to an object of Binary reader type and used the above mentioned way to pass it to my recognizer and it works as expected.
Please suggest if this workaround is alright and which is better to use as well. 

Thank you.

**Comment by Muskan-14** [comment]
Apologies for the delay and thank you for the reply, @zhouwangzw 
I have tried your method and it works as expected. Thank you.
Meanwhile, I have found a way too. 
Since, my first input is of type Stream, I noticed that FromStreamInput also takes in a BinaryAudioStreamReader type of object.
I have therefore converted my input stream to an object of Binary reader and then to BinaryAudioStreamReader type and used the above mentioned way to pass it to my recognizer and it works as expected.
Please suggest if this workaround is alright and which is better to use as well. 

Thank you.

**Comment by prasanthranga** [comment]
Hi Zhou Wang,

I am trying to implement speech to text conversion with java, with following code byte[] as audio input.
PushAudioInputStream pushStream = AudioInputStream.createPushStream();
			pushStream.write(file.getBytes());
			pushStream.close();
AudioConfig audioConfig = AudioConfig.fromStreamInput(pushStream);

but am getting occured java.lang.IllegalArgumentException: or service time out.

**Comment by wolfma61** [comment]
@prasanthranga - please don't open an old, unrelated issue, please open a new issue. 


@jhakulin - can you please take a look?

**Comment by jhakulin** [comment]
@prasanthranga Please check does the following sample help you get further? https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/00e5785418521941bb507c9e17ce5646cb6004bd/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java#L298
Also please open a new issue if that will not help.

**Comment by prasanthranga** [comment]
Still my issue not resolved.

Could you please share any relevant git hub link.

Am trying to implement azure speech to text with stream input.

With thyemeleaf front end and spring boot backend.



⁣Get BlueMail for Android ​

**Comment by dargilco** [comment]
@prasanthranga, @jhakulin had a GitHub link in his above reply to you with a Java sample. 

Remove the line pushStream.close() in your code and try again.

If you still need help, open a new GitHub issue in this repo.

**Comment by prasanthranga** [comment]
I have removed pushStream.close() and I have tried, getting service time out error.

I have posted as issue with my code in git hub it's name is speech to text conversion #924.

I hope you will help us.

Thanks,
Prasanth. R

⁣Get BlueMail for Android ​
