### ISSUE TITLE
Swagger Code Gen, generates "java.io.File" instead of the custom Speech Service API "File" object

### ISSUE THREAD

**Issue by hemeda3** [Azure-Samples/cognitive-services-speech-sdk#913]
**Describe the bug**
[Java]
- Swagger for the Speech Services API  used ""$ref": "#/definitions/File" which result of "File" object got generated referencing package
java.io.File, instead of SpeechServiceApi custom  "File" object.  this  will affect  getTranscriptionFilesAsync()+getTranscriptionFiles**()  almost every method used  PaginatedFiles  as response  will be effected.
* it's a swagger api code-gen bug.
* 
**To Reproduce**
1. Go to https://editor.swagger.io.
2. Click File, then click Import URL.
3. Enter the Swagger URL for the Speech Services API: https://westus.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/export?DocumentFormat=Swagger&ApiName=Speech%20to%20Text%20API%20v3.0.
4.  Click Generate Client and select Java.
5. go to generated files models/PaginatedFiles.java
6. `import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
  ===> import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PaginatedFiles
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-01-01T09:06:00.195Z")
public class PaginatedFiles {
  @SerializedName("values")
  ===>  private List<File> values = null;`
.

**Expected behavior**
I expect the name to be different than File like TransactionFile , since it's not a generic File.

**Version of the Cognitive Services Speech SDK**
https://westus.api.cognitive.microsoft.com/speechtotext/v3.0/transcriptions
Batch API.

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - MacOS
 - Hardware - x64, x86, ARM, ... x64
 - Programming language: C#, C++, Java, JavaScript, Objective-C, Python: Java 
 
**Additional context**
After I changed Swagger API `#/definitions/File`  to ` #/definitions/ TransactionFile`  then I was able to get the transcription files 
before that once I receive resposne  of ` public void onSuccess(PaginatedFiles result,` 
result have real java.io.File (so there is no "Kind" property.

 "$ref": "#/definitions/File" to   "$ref": "#/definitions/TransactionFile"
and `"File": {
      "title": "File",
      "type": "object",
      "properties": {
        "kind": {
          "description": "The kind of this file.",
          "enum": [
              "DatasetReport",
              "Audio",
              "LanguageData",
              "PronunciationData",
              "AcousticDataArchive",
              "AcousticDataTranscriptionV2",
              "Transcription",
              "TranscriptionReport",
              "EvaluationDetails"
          ],`
to 
`"TransactionFile": {
      "title": "File",
      "type": "object",
      "properties": {
        "kind": {
          "description": "The kind of this file.",
          "enum": [
              "DatasetReport",
              "Audio",
              "LanguageData",
              "PronunciationData",
              "AcousticDataArchive",
              "AcousticDataTranscriptionV2",
              "Transcription",
              "TranscriptionReport",
              "EvaluationDetails"
          ],`

`defaultApi.getTranscriptionFilesAsync(transid, 1000, 0, 100, new ApiCallback<PaginatedFiles>() {
				 @Override
				 public void onFailure(ApiException e, int statusCode, Map<String, List<String>> responseHeaders) {

				 	e.printStackTrace();
					 System.out.println("failure");
				 }

				 @Override
				 public void onSuccess(PaginatedFiles result, int statusCode, Map<String, List<String>> responseHeaders) {
					 System.out.println("success");
					 System.out.println("result"+result.getValues().get(0)==null);
					 result.getValues().stream().forEach(file -> {
						 try {
							 System.out.println("File"+file);
							 file.getKind();
						 } catch (Exception e) {
							 e.printStackTrace();
						 }
					 });

				 }`

*I think this is  bug in Swagger(OpenAPI) codegen  look here: 
https://github.com/OpenAPITools/openapi-generator/issues/6017

**Comment by pankopon** [comment]
@bexxx Can you please check, or know who could best comment?

**Comment by pankopon** [comment]
Closing this item since the bug has been already reported to openapi-generator (https://github.com/OpenAPITools/openapi-generator/issues/6017) and a workaround exists (change `#/definitions/File` to `#/definitions/ TransactionFile`). Please open a new issue if you need further support on Speech SDK topics.
