### ISSUE TITLE
[Sample transcriptionresult_v3.schema.json] produces java.lang.NumberFormatException: when  "durationInTicks" audio transcription response is maximum than java.lang.Integer.Max_VALUE

### ISSUE THREAD

**Issue by hemeda3** [Azure-Samples/cognitive-services-speech-sdk#914]
**Describe the bug**
In this  sample swagger file line :
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/e302ccc42d6cb0e3bb4cd93fecabebd3d7c8c2ee/samples/batch/transcriptionresult_v3.schema.json#L35

durationInTicks has  "type": "integer",  if we have 1 hour of audio file (3600000000000 nano seconds)->in ticks (1 tick is 100 nanoseconds) -> equal 36000000000 ticks as value which is  bigger that java.lang.Integer.MAX_VALUE
which leads to java.lang.NumberFormatException when convert generated TranscriptionResult Json 
to transcriptionresult_v3.schema's generated swagger Java object

**To Reproduce**
1. Go to https://editor.swagger.io.
2. Click File, then click Import URL.
3. Enter the Swagger URL for the Speech Services API: https://westus.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/export?DocumentFormat=Swagger&ApiName=Speech%20to%20Text%20API%20v3.0.
4. Copy this Transcription Result Schema json : 
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/transcriptionresult_v3.schema.json
content into previous file 
5.  Click Generate Client and select Java/ or use any swagger code gen ( I used Spring Maven Code Gen plugin)
6. then check your generated object  you will find it has durationInTicks as Integer type

**Expected behavior**
durationInTicks should parse any generated number .

**Version of the Cognitive Services Speech SDK**
BATCH Schema V3
 https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/66d7131368ce53b333e13416428996b023be88cc/samples/batch/transcriptionresult_v3.schema.json#L35

**Comment by wolfma61** [comment]
@bexxx - can you please take a look

**Comment by yasar83** [comment]
Nooo email

Mit freundliche Grüße

Am 05.01.2021 um 08:57 schrieb Wolfgang Manousek <notifications@github.com>:

﻿

@bexxx<https://github.com/bexxx> - can you please take a look

**Comment by bexxx** [comment]
It looks like the json schema is missing the format "int64" for those properties.
Try editing the schema and add
"format": "int64",
for all "durationInTicks" and "offsetInTicks" properties and regenerate the code.

I will create a PR to fix the schema too.

**Comment by pankopon** [comment]
Closed as resolved since no further updates, please open a new issue if more support is needed.
