### ISSUE TITLE
SpeechSynthesis.StopSpeakAsync has bug

### ISSUE THREAD

**Issue by incomingflyingbrick** [Azure-Samples/cognitive-services-speech-sdk#915]
**Describe the bug**
When you call this method in middle of a speech, future object won't return when you can call .get() on the future object.

**To Reproduce**
1. start speaking using SpeakSsmlAsync method on android
2. In Middle of speech , call .StopSpeakAsync() to get a future object.
3. call .get() on the future object. 
4. .get() never return.

Android 10

**Comment by yulin-li** [comment]
@incomingflyingbrick Thanks for reporting, we are investigating this issue.

**Comment by yulin-li** [comment]
Hi @incomingflyingbrick The bug is fixed and will be released with 1.15.0
