### ISSUE TITLE
Model Training Stuck "Processing" for 10+ hours - how to cancel?

### ISSUE THREAD

**Issue by kleindev** [Azure-Samples/cognitive-services-speech-sdk#918]
I have a speech model that has been training since 1/4 @ 10:21 pm central.  I am unable to delete nor have been able successfully train another model 

The key difference is that I switched to use baseline model of 20201019 where previously I was using 20200715

**Comment by kleindev** [comment]
southcentralus - https://speech.microsoft.com/portal/2377508570e74b00ac9d1a34d47cc046/customspeech

**Comment by kleindev** [comment]
Looks like it is specific to the 20201019 base model - at least on these recent ones:

![image](https://user-images.githubusercontent.com/9289866/103671839-13e25280-4f41-11eb-830b-952234b44b04.png)

**Comment by pkranen** [comment]
The base model 20201019 for en-us supports acoustic adaptation while the 20200715 model only does language adaptation. If the data sets that you used to train the model contain acoustic data then those will be used for acoustic adaptation in the 20201019 model. Acoustic adaptation takes significantly more time than language adaptation, the actual training duration depends on the length of the acoustic data and the quality of the transcription. The maximum duration for the acoustic adaptation is seven days, after that it will time out. If you use up to 2GB of acoustic data (which is the limit for a single acoustic import) the adaptation should not time out. If you use multiple data sets for adaptation and the cumulative size largely exceeds the 2GB, the adaptation may time out. In that case please limit the amount of acoustic data to 2GB (or roughly 20 hours of audio) and use from the remaining data only the transcriptions (i.e. import only the text portion).

**Comment by kleindev** [comment]
Thanks for the details.  It is still running at this moment - and it is very likely that I have more than 2GB of audio - I was unaware of the differences .  Is 20201019 the first of its kind?  

Does this mean that the 20200715 / language adaptation model does not take into account human labeled audio?  

Original issue I was fighting was trying to determine which training data "broke" the pronunciation of a medical term - and right now it is still inconclusive - but oddly "breaks" the same way with different training material

**Comment by pkranen** [comment]
This is correct, the audio data is not used in the case of the 20200715 model, only the text (human labels).

Some related infos from our FAQ:
Q: How long will it take to train a custom model with audio data?
A: Training a model with audio data is a lengthy process. Depending on the amount of data, it can take several days to create a custom model. If it cannot be finished within one week, the service might abort the training operation and report the model as failed. For faster results, use one of the regions where dedicated hardware is available for training. You can copy the fully trained model to another region using the REST API. Training with just text is much faster and typically finishes within minutes.
Some base models cannot be customized with audio data. For them the service will just use the text of the transcription for training and ignore the audio data. Training will then be finished much faster and results will be the same as training with just text.

**Comment by kleindev** [comment]
How do we know which models accept audio and which do not?  And if it is 20 hours max - what product does this recommendation apply to - we've made decisions and significant investments based on what looks like confusing/conflicting/non-transparent guidance now.

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-custom-speech-human-labeled-transcriptions

![image](https://user-images.githubusercontent.com/9289866/104057440-c885a980-51b7-11eb-962e-db4ed2ca5b54.png)

**Comment by rurounijones** [comment]
I was also tripped up by this issue and only found this issue after contacting, and spending quite a long time with, Microsoft support trying to figure out what was going on.

Could we get an update and especially an answer to @kleindev 's question above regarding the training "hours".

**Comment by pankopon** [comment]
@pkranen Can you please provide more info on base models and suggested hours as requested, or know who could clarify? Is it documented which models use acoustic data and which ones don't?

**Comment by pkranen** [comment]
The model that support acoustic adaptation can be seen per locale at https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support#speech-to-text.

**Comment by andreasjl** [comment]
Sorry for the confusion from the documentation. Also based on your feedback, we have now tried to improve the documentation and make it clearer what data is actually used by the service. The effort spent on creating the transcriptions is certainly not lost. Even the transcripts alone will be valuable to improve recognition results. If they resemble the expected real input, this will help to improve the recognition overall. You have probably already noticed that if you compare the recognition results of your custom model to the base model.

**Comment by pankopon** [comment]
Closing this item since clarifications have been provided. Please open a new issue if more support is needed.
