### ISSUE TITLE
Using the speech SDK from a Swift Package (iOS)

### ISSUE THREAD

**Issue by j-h-a** [Azure-Samples/cognitive-services-speech-sdk#919]
I guess this isn't available via SPM yet, so I've imported the speech SDK using cocoapods, but this links it with my App Target in my project file. The code that needs to call it is in my own Swift Package, but I don't know how to make the imports visible to these modules, since there isn't a swift module for the speech SDK.

Is this even possible or will I have to write wrappers in the Project (App-Target) that I can inject into my Swift modules?

**Comment by j-h-a** [comment]
Here is what I have tried (and ultimately failed):

I downloaded the binary version of the cocoapod which is linked from the docs page:
https://aka.ms/csspeech/iosbinary

And I created a new Swift package:
```
mkdir SPXSpeech
cd SPXSpeech
swift package init --type library
```
Then I copied the downloaded `MicrosoftCognitiveServicesSpeech.framework` into this package directory, and removed all the default package directories (`Sources`, `Tests`) and edited the `Package.swift` to just be a package wrapper for the framework:
```
// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "SPXSpeech",
    products: [
        .library(
            name: "SPXSpeech",
            targets: ["SPXSpeech"]),
    ],
    dependencies: [
    ],
    targets: [
        .binaryTarget(
            name: "SPXSpeech",
            path: "MicrosoftCognitiveServicesSpeech.framework"),
    ]
)
```

This failed because SPM needs it to be a `.xcframework` not a plain old `.framework`. So I tried to convert it using:
```
xcodebuild -create-xcframework -framework ./MicrosoftCognitiveServicesSpeech.framework -output ./MicrosoftCognitiveServicesSpeech.xcframework
```
and this failed with the following error
```
error: binaries with multiple platforms are not supported '/path/to/SPXSpeech/MicrosoftCognitiveServicesSpeech.framework/MicrosoftCognitiveServicesSpeech'
```

At this point I gave up because it looks like while it should be possible to create a swift package that exposes a binary framework, it seems the the sources must be compiled into separate binaries. I'm not sure if I am able to do this from the framework binary. There's the `lipo` command to extract different libraries from a fat binary - but I don't know how to do this or what binaries/versions should be extracted (I'm guessing it's a simulator version and a device version?).

However, it looks like it should be relatively easy for the maintainers to compile things slightly differently to produce a `.xcframework` and provide a SPM binary distribution of the Speech SDK - is this planned at all? the docs I followed are here: https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages and the `Package.swift` file would be similar to above but it would use the `name`/`url`/`checksum` version of `.binaryTarget`.

I'll have to stick with cocoapods for now and a wrapper injected from the app target, but it'd be fantastic to get this available via SPM as now that `AppCenter/Distribute` supports SPM, this SDK is the last thing using Cocoapods in my project.

**Comment by jhakulin** [comment]
@j-h-a Thanks for the report, we are adding module framework support for iOS on the next release (ETA March 2021). Would it be sufficient for you if you are able to import Speech SDK as module?

**Comment by j-h-a** [comment]
If it's available as an `.xcframework` (no more fat binary) then I think the example `Package.swift` from above should be enough to make it fully available via SPM - but even if it's not available via SPM it should still be possible for people to use the `.xcframework` binary by including it with their own local copy of the `Package.swift` example above.

**Comment by pankopon** [comment]
I've added a work item about this to our backlog for consideration, so closing the issue. We'll update here when the work is done and the actual release schedule is known.

**Comment by j-h-a** [comment]
Is there any way to track/monitor this? I don't really understand the way GH Issues are being used here, i.e. closing a ticket once a separate work item is raised somewhere else (presumably private?). It'd be nice to know when it's ready/available, is there a separate public tracker I can watch?

**Comment by jhakulin** [comment]
@j-h-a Did you try the solution which is described in the link below ? I think the problem with "-create-xcframework" command is that does not support multi-architecture binaries, like now we have x86_64 and arm64 bundled inside the framework.
https://help.apple.com/xcode/mac/11.4/#/dev544efab96

**Comment by j-h-a** [comment]
Yes - my comment on 6th Jan describes trying this.

If the current release (which I'm thinking might include SPM support, based on the comment from @pankopon on 17th Feb) is delayed, would it be possible to provide a hotfix release from the previous version that includes SPM support? As far as I know the process is mostly described above, the only thing missing is the compile settings to produce an `.xcframework` with separate binaries instead of the fat binary.

Thanks, J

**Comment by jhakulin** [comment]
@j-h-a It is possible to create xcframework using following steps. Let us know if this helps you further?

1. Step download https://aka.ms/csspeech/iosbinary
$ ls
MicrosoftCognitiveServicesSpeech.framework

2. Extract arm64 from the framework to separate binary because xcframework conversion does not support multiple binaries
jhakulin$ lipo -extract arm64 MicrosoftCognitiveServicesSpeech.framework/MicrosoftCognitiveServicesSpeech -o MicrosoftCognitiveServicesSpeech
jhakulin$ ls
MicrosoftCognitiveServicesSpeech		MicrosoftCognitiveServicesSpeech.framework

3. Replace multi-arch (x86_64, arm64) binary in the framework with arm64 extracted binary
jhakulin$ cd MicrosoftCognitiveServicesSpeech.framework/
jhakulin$ ls
Headers					MicrosoftCognitiveServicesSpeech	_CodeSignature
Info.plist				Modules
jhakulin$ rm MicrosoftCognitiveServicesSpeech 
jhakulin$ ls
Headers		Info.plist	Modules		_CodeSignature
jhakulin$ cd ..
jhakulin$ ls
MicrosoftCognitiveServicesSpeech		MicrosoftCognitiveServicesSpeech.framework
jhakulin$ mv MicrosoftCognitiveServicesSpeech MicrosoftCognitiveServicesSpeech.framework/

4. Create xcframework from the update framework file
jhakulin$ xcodebuild -create-xcframework -framework MicrosoftCognitiveServicesSpeech.framework/ -output MicrosoftCognitiveServicesSpeech.xcframework
xcframework successfully written out to: /Users/jhakulin/tmp/test/MicrosoftCognitiveServicesSpeech.xcframework

**Comment by jhakulin** [comment]
@j-h-a Are you able to progress further with the instructions above?

**Comment by tomasgreen** [comment]
> @j-h-a Are you able to progress further with the instructions above?

Hi!
just like to say that your xcframework tutorial works for building and running the app on local device. It got stuck uploading it to App Store for the following reason:

**ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.**

I'm sure I've missed something and I'm sticking to the pod for now. But, it might be a good idea to add a "manual installation" section in the readme until the SPM-release is completed (judging by the historical releases I guess the next one is scheduled for Juli?).

**Comment by jhakulin** [comment]
@j-h-a Thanks for feedback, it is good idea to add instructions for manual xcframework creation to the readme documentation. Next release should be out in about 2 weeks.

**Comment by j-h-a** [comment]
I haven't been able to try this yet because we have other priorities right now - it's great to see that the solution works though, and that this is useful for others :)

**Comment by tomasgreen** [comment]
@j-h-a I figured it out, apparently you can't use bitcode when uploading to App Store.

I created a small howto (for my own benefit) based on some info I googled at https://github.com/tomasgreen/MSSpeechServiceXCFramework, feel free to take a look, I even added a ready to use zipped version of the xcframework.
 
P.S 
@jhakulin it would be amazing Microsoft could host the .xcframework somewhere, or even better, create a separate SPM repo. And you might want to take a look at the whole bitcode thing? 😉

**Comment by jhakulin** [comment]
@tomasgreen What is the problem you have with the bitcode enabled binary and app store?

**Comment by tomasgreen** [comment]
@jhakulin I got these errors when uploading the when uploading to App Store. 

> ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.
> 
> ITMS-90562: Invalid Bundle - There's an issue with the app's bitcode compilation. Rebuild the app using the current public (GM) version of Xcode and upload it again.
> 
> ITMS-90562: Invalid Bundle - The app submission can not be successfully recompiled from bitcode due to missing symbols during linking. You can try to reproduce and diagnose such issues locally by following the instructions from: https://developer.apple.com/library/archive/technotes/tn2432/_index.html

I just created a local export with bitcode included and had a look at the export log. It may be that the bcsymbolmap for the framework is missing but I'm not sure yet.

**Comment by tomasgreen** [comment]
@jhakulin I'm pretty sure the symbols are the cause of the problem, but in order to fix it I need to run `xcodebuild -create-xcframework` with the `-debug-symbols` flag. However, that requires the dSYM file, any chance you can supply it?

**Comment by jhakulin** [comment]
@tomasgreen Could you please send me email to jhakulin@microsoft.com and provide a link where I could drop the dsym file for investigation. Thank you.

**Comment by jhakulin** [comment]
Reopening the issue and setting this issue accepted as we are updating ios packages to xcframeworks in near future.

**Comment by jhakulin** [comment]
@j-h-a Speech SDK 1.19.0 is packaged into xcframework, let us know if there are any problems.

**Comment by FanChen2016** [comment]
> @j-h-a Speech SDK 1.19.0 is packaged into xcframework, let us know if there are any problems.

build on Any iOS Device(arm 64),  
Showing All Messages
xxx/one-app/NativePluginProjects/iOS/NativeAudioPlugin/AudioPlugin/AudioPlugin/AudioRecorder.h:7:9: 'MicrosoftCognitiveServicesSpeech/SPXSpeechApi.h' file not found
build on simulator is OK 
@jhakulin 

How to fix it?

**Comment by gyuri-fluttech** [comment]
@jhakulin , I also have the same problem as @FanChen2016. Is there a way to fix this ? Based on the following comment https://github.com/flutter/flutter/issues/94719#issuecomment-988171832 it sounds that it would be fairly easy to add support in the SDK.

**Comment by jhakulin** [comment]
@gyuri-fluttech Thanks for the information and apologies for the issue. In the meantime we are investigating a proper fix, could you let me know if importing the Speech SDK in your swift app code where you use Speech SDK APIs would help ?

```
import MicrosoftCognitiveServicesSpeech
```

If this does not help, could you try to add use_modular_headers! in your Podfile and see if that helps.

```
target 'YourApp' do
    use_modular_headers!
end
```

**Comment by gyuri-fluttech** [comment]
@jhakulin , yep, I have it but still fails. 

```
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
```

**Comment by jhakulin** [comment]
@gyuri-fluttech Thanks, do you also import the speech SDK as follows in your Swift code ?
```
import MicrosoftCognitiveServicesSpeech
```

**Comment by gyuri-fluttech** [comment]
@jhakulin , sorry for my late reply. I just tried adding the import and still fails.

**Comment by jhakulin** [comment]
@gyuri-fluttech Thanks, could you provide the exact error message you get from Xcode ? The problem might be also that currently Speech SDK does not support armv7 (32-bit arm) which you need to exclude on the build of generic iOS device.

**Comment by gyuri-fluttech** [comment]
@jhakulin , sure. Here it is: 

```
Xcode's output:
↳
warning: [CP] Unable to find matching .xcframework slice in 'ios-arm64_x86_64-maccatalyst ios-arm64 ios-arm64_x86_64-simulator' for the current build architectures (arm64 armv7).
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/azure_cognitive_services-umbrella.h"
^
/Users/gyuri/work/upper/test_flutter/ios/Pods/Target Support Files/azure_cognitive_services/azure_cognitive_services-umbrella.h:13:9: note: in file included from /Users/gyuri/work/upper/test_flutter/ios/Pods/Target
Support Files/azure_cognitive_services/azure_cognitive_services-umbrella.h:13:
#import "AzureCognitiveServicesPlugin.h"
^
/Users/gyuri/work/upper/test_flutter/azure_cognitive_services/ios/Classes/AzureCognitiveServicesPlugin.h:2:9: error: 'MicrosoftCognitiveServicesSpeech/SPXSpeechAPI.h' file not found
#import <MicrosoftCognitiveServicesSpeech/SPXSpeechAPI.h>
^
<unknown>:0: error: could not build Objective-C module 'azure_cognitive_services'
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/azure_cognitive_services-umbrella.h"
^
/Users/gyuri/work/upper/test_flutter/ios/Pods/Target Support Files/azure_cognitive_services/azure_cognitive_services-umbrella.h:13:9: note: in file included from /Users/gyuri/work/upper/test_flutter/ios/Pods/Target
Support Files/azure_cognitive_services/azure_cognitive_services-umbrella.h:13:
#import "AzureCognitiveServicesPlugin.h"
^
/Users/gyuri/work/upper/test_flutter/azure_cognitive_services/ios/Classes/AzureCognitiveServicesPlugin.h:2:9: error: 'MicrosoftCognitiveServicesSpeech/SPXSpeechAPI.h' file not found
#import <MicrosoftCognitiveServicesSpeech/SPXSpeechAPI.h>
^
<unknown>:0: error: could not build Objective-C module 'azure_cognitive_services'
Command CompileSwiftSources failed with a nonzero exit code
Command CompileSwiftSources failed with a nonzero exit code
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
Command CompileSwiftSources failed with a nonzero exit code
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
Command CompileSwiftSources failed with a nonzero exit code
note: Using new build system
note: Planning
note: Build preparation complete
note: Building targets in parallel
```

You can also find an example project here: 

project path: `to_flutter_bug/example/ios/`
module path: `to_flutter_bug/ios/`

[to_flutter_bug.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/7675658/to_flutter_bug.zip)

**Comment by jhakulin** [comment]
@gyuri-fluttech Thanks, that is very helpful, I believe the issue is caused due to reason Xcode tries to find armv7 architecture, however that is not currently supported architecture for Speech SDK for iOS. Could you try to exclude the armv7 in Xcode settings, see comment on https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/969#issuecomment-785557900 ?

**Comment by jhakulin** [comment]
@gyuri-fluttech We need to update the SpeechSDK Cocoapod to exclude the armv7, that should resolve this issue. 

As a workaround, you can exclude the armv7 from Any iOS Device by doing following
1. `pod install`, which will install MicrosoftCognitiveServicesSpeech-iOS (1.19.0)
2. Exclude armv7 architecture by adding line below into `MicrosoftCognitiveServicesSpeech-iOS.debug/release.xcconfig` files under your app project `Pods/Target Support Files/MicrosoftCognitiveServicesSpeech-iOS` directory and `Pods-<YourApp>.debug/release.xcconfig` files under `Pods/Target Support Files/Pods-<YourApp>` directory. When I tested this workaround with https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/swift/ios/from-microphone quickstart, I needed to update 4 xcconfig files in total. 
```
EXCLUDED_ARCHS[sdk=iphoneos*] = armv7
``` 
We will target to push new Cocoapod during this week.

**Comment by gyuri-fluttech** [comment]
@jhakulin , that is quite cool ! Thank you a lot for your quick help. Looking forward for the new Pod. Will it be the same version ? 

Finally, the changes from your last message worked. As you said, I added `EXCLUDED_ARCHS[sdk=iphoneos*] = armv7` to the specified `xconfig` files. 🤝

**Comment by jhakulin** [comment]
@gyuri-fluttech Thanks for information! Hopefully no version change needed for the new Pod, the xcframework package stays the same, just requires change in the .podspec file (to exclude armv7) when updating the pod repo.

**Comment by gyuri-fluttech** [comment]
> @gyuri-fluttech Thanks for information! Hopefully no version change needed for the new Pod, the xcframework package stays the same, just requires change in the .podspec file (to exclude armv7) when updating the pod repo.

Thanks. Could you give me a sign here when it is done so I can retest without those changes ?

**Comment by gyuri-fluttech** [comment]
Happy New Year !  🥳
Any news about this ?

**Comment by ruofeilyu** [comment]
any next step?

**Comment by umairsuraj01** [comment]
Any updates on SPM for this?
