### ISSUE TITLE
Speech recognise from microphone not working with Unity on Oculus Quest with Photon Voice

### ISSUE THREAD

**Issue by ZisoM** [Azure-Samples/cognitive-services-speech-sdk#921]
I am working on a project where we use Photon (Unity networking package), i am guessing Photon Voice uses AudioRecord from java.

When i try to access the microphone with speech services i get an error on logcat "AudioRecord start() status -38", i get that while i have Photon Voice enabled. If i disable Photon Voice then speech recognition works just fine.

It seems like speech recognition can't access the microphone because Photon Voice has control over it.

Has anyone else come across this problem? i know it might be a bit niche.

Any suggestions are welcome!

**Comment by jhakulin** [comment]
@ZisoM There is limitation on Android how shared mic input can be used, please see https://developer.android.com/guide/topics/media/sharing-audio-input.

**Comment by ZisoM** [comment]
@jhakulin That link talks about different applications, i might be misunderstanding it, but im using one application where i have 2 processes trying to access the microphone. The weird thing is that in the Unity Editor (on windows) it works just fine.

**Comment by jhakulin** [comment]
@ZisoM The error code -38 happens if microphone is already in use. Microphone needs to be released before other process can successfully initialize it. Would it be feasible on your app to stop and release (audioRecord.stop(), audioRecord.release();) the mic from the owning process? I believe that is all which can be done.

**Comment by ZisoM** [comment]
I see, I've tested what you just suggested and it works but that doesn't really help me because it is not in my interest to stop photon voice at any time. Anyway, I will close this now, thank you for your help.
