### ISSUE TITLE
DllNotFoundException in ASP.NET Core 3.1 Docker container

### ISSUE THREAD

**Issue by ubid** [Azure-Samples/cognitive-services-speech-sdk#923]
Hello
I try to use TextToSpeech service, but i get exception when I publish to docker.

Exception:
'System.DllNotFoundException: 'Unable to load shared library 'libMicrosoft.CognitiveServices.Speech.core.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibMicrosoft.CognitiveServices.Speech.core.so: cannot open shared object file: No such file or directory''

I want to use this service like an API ->  192.168.1.23:8000/GetAudio

Docker file:
`FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["SweetHome.Api/SweetHome.Api.csproj", "SweetHome.Api/"]
RUN dotnet restore "SweetHome.Api/SweetHome.Api.csproj"
COPY . .
WORKDIR "/src/SweetHome.Api"
RUN dotnet build "SweetHome.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SweetHome.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SweetHome.Api.dll"]`

**Comment by jhakulin** [comment]
@ubid Please check corresponding issue https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/481 and let us know if that helps

**Comment by ubid** [comment]
hi!
Thanks for your help! Now its works!
