### ISSUE TITLE
speech to text convertion 

### ISSUE THREAD

**Issue by prasanthranga** [Azure-Samples/cognitive-services-speech-sdk#924]
Hi Team,

I am trying to implement Speech to Text with Azure.

Here input audio is from thymeleaf front end, speingboot is backend.

following is my code snippet:

JS script :
 <script>
            var SpeechRecognition = (function() {

                return {
                    curImgPos: 1,
                    imagesNum: 3,

                    incrementPos: function() {
                        if (this.curImgPos >= this.imagesNum) {
                            this.curImgPos = 1;
                        } else {
                            this.curImgPos++;
                        }
                    },

                    decrementPos: function() {
                        if (this.curImgPos <= 1) {
                            this.curImgPos = this.imagesNum;
                        } else {
                            this.curImgPos--;
                        }
                    },

                    executeCommand: function (recognizedText) {
                        if (recognizedText.toLowerCase() == 'next') {
                            this.incrementPos();
                            $('#image').attr('src', '/images/' + this.curImgPos + '.jpg');
                        } else if (recognizedText.toLowerCase() == 'previous') {
                            this.decrementPos();
                            $('#image').attr('src', '/images/' + this.curImgPos + '.jpg');
                        } else {
                            alert('Can not recognize a command: ' + recognizedText);
                        }
                    },

                    initAudio: function() {
                        var self = this;
                        var audioChunks;
                        $('#record-btn').on('mousedown', function() {
                            navigator.mediaDevices.getUserMedia({
                                audio:true
                            }).then(stream => {
                                audioChunks = [];
                                self.rec = new MediaRecorder(stream);

                                self.rec.ondataavailable = e => {

                                    audioChunks.push(e.data);
                                    if (self.rec.state == "inactive"){
                                        var blob = new Blob(audioChunks, { type:'audio/x-mpeg-3' });

                                        var fd = new FormData();
                                        fd.append('blob', blob);

                                        $.ajax({
                                            url: '/recognize',
                                            type: 'POST',
                                            data: fd,
                                            cache: false,
                                            processData: false,
                                            contentType: false,
                                            success: function (data) {
                                                if (data.success) {
                                                    self.executeCommand(data.recognizedText)
                                                } else {
                                                    console.log("Could not recognize speech");
                                                }
                                            },
                                            error: function (e) {
                                                console.log("Could not recognize speech: " + e);
                                            }
                                        });
                                    }
                                }
                                self.rec.start();
                        }).catch(e => console.log(e));
                        });

                        $('#record-btn').on('mouseup', function() {
                            self.rec.stop();
                        });
                    },

                    init: function () {
                        this.initAudio();
                    }
                };
            })();

            $(window).on('load', function() {
                SpeechRecognition.init();
            });
        </script>

Backend Code : 

Controller :  
 @ResponseBody
    @RequestMapping(value="/recognize", method=POST)
    public AjaxRecognizedSpeechResponse recognize(@RequestPart("blob") MultipartFile blob) throws InterruptedException, ExecutionException, IOException {
        String recognizedText = null;
        	SpeechRecognitionService.recognize(blob);
                   return new AjaxRecognizedSpeechResponse(true, recognizedText);
    }

Service :  
	public static Optional<String> recognize(MultipartFile file)
			throws IOException, InterruptedException, ExecutionException {
		try {

		

			PushAudioInputStream pushStream = AudioInputStream.createPushStream();
			try {
				pushStream.write(file.getBytes());
			}catch (Exception e) {
				System.out.println(e);
			}
			
			SafeHandle impl = pushStream.getImpl();
			System.out.println(impl);
			AudioConfig audioConfig = AudioConfig.fromStreamInput(pushStream);

			SpeechConfig speechConfig = SpeechConfig.fromSubscription("xxxx","centralindia");

			SpeechRecognizer recognizer = new SpeechRecognizer(speechConfig, audioConfig);

			System.out.println("Speak into your microphone.");
			Future<SpeechRecognitionResult> task = recognizer.recognizeOnceAsync();
			SpeechRecognitionResult result = task.get();
			System.out.println("RECOGNIZED: Text=" + result.getText());

			switch (result.getReason()) {
			case RecognizedSpeech:
				System.out.println("We recognized: " + result.getText());
				break;
			case NoMatch:
				System.out.println("NOMATCH: Speech could not be recognized.");
				break;
			case Canceled: {
				CancellationDetails cancellation = CancellationDetails.fromResult(result);
				System.out.println("CANCELED: Reason=" + cancellation.getReason());

				if (cancellation.getReason() == CancellationReason.Error) {
					System.out.println("CANCELED: ErrorCode=" + cancellation.getErrorCode());
					System.out.println("CANCELED: ErrorDetails=" + cancellation.getErrorDetails());
					System.out.println("CANCELED: Did you update the subscription info?");
				}
			}
				break;
			}
}

Error : 

RECOGNIZED: Text=
CANCELED: Reason=Error
CANCELED: ErrorCode=ServiceTimeout
CANCELED: ErrorDetails=Timeout: no recognition result received SessionId: b951bb4ff42348cb8d5fbcda872bc7b8

Could you please help me. Audio as speech input from front end and it should convert to text in backend Springboot.

**Comment by ralph-msft** [comment]
Hello. You are getting the "no recognition result received" cancellation event because you are not correctly _streaming_ the audio from the browser through to the speech service. In your javascript code, your ondataavailable handler is sending up parts of the continuous audio stream (this can contain ms of audio) separately in different POST requests.

The simplest way to accomplish what you are trying to do would be to use the Cognitive Speech Javascript SDK directly in your JS code. You can find instructions on how to do this here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-speech-to-text?pivots=programming-language-javascript
