### ISSUE TITLE
auto detect langauge using speechsdk identify wrong languages

### ISSUE THREAD

**Issue by yashugupta786** [Azure-Samples/cognitive-services-speech-sdk#925]
I have added 2 languages in the auto language detect and try to read from wav file . It is not able to identify the language and performing wrong automatic speech to text 

auto_detect_source_language_config = speechsdk.languageconfig.AutoDetectSourceLanguageConfig(languages=["en-US","en-IN"])
    # auto_detect_source_language_config = auto_detect_source_language_config
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config,auto_detect_source_language_config=auto_detect_source_language_config)

**Comment by glharper** [comment]
@yashugupta786 Thank you for writing this issue up. Could you share the wav file you used to reproduce this?

**Comment by pankopon** [comment]
@yashugupta786 Is this still a valid issue for you? If yes, please attach or link to the wav file in question so that we can further investigate.

**Comment by yashugupta786** [comment]
Hi Pankopon So we raised the issue with microsoft internally and they are able to reproduce it and they are working on it .Thanks a lot for the support you can close this issue

**Comment by gsgou** [comment]
@yashugupta786 , @pankopon this is  happening more often also between english and german and various languages. Is there any way to send reports with recorded audio to improve the service. I have a mobile App and would like to allow the user send reports.

**Comment by yashugupta786** [comment]
> @yashugupta786 , @pankopon this is  happening more often also between english and german and various languages. Is there any way to send reports with recorded audio to improve the service. I have a mobile App and would like to allow the user send reports.

@gsgou  we have raise this thing with microsoft cloud architects .this is found as a bug .from last 7-8 mnths this functionality not working properly ..

**Comment by gsgou** [comment]
@yashugupta786 do you mind if you reopen the issue so we can close it when you have some Feedback from the cloud architects. In case it helps to provide audio that has erroneous detection can you ask for the possibility to provide a  report API. Its a cool feature and if help is needed maybe more developers can provide feedback for this one.
