### ISSUE TITLE
wss connect  error usp_reco_engine_adapter.cpp:Error: 'std::bad_cast'

### ISSUE THREAD

**Issue by wall3001** [Azure-Samples/cognitive-services-speech-sdk#932]
I used the java sdk 1.14.
TranslationRecognizer failed to initialize.
The main logs were as follows:

53ms SPX_DBG_TRACE_SCOPE_ENTER:  usp_reco_engine_adapter.cpp:Init
(343): 53ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:Init: this=0x0x7f5af0002030
(343): 53ms SPX_DBG_TRACE_SCOPE_EXIT:  usp_reco_engine_adapter.cpp:Init
(343): 53ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a9001e040; name='SPEECH-Region'; value='southeastasia'
(343): 53ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a9001d2e0; name='INTENT-region'; value='southeastasia'
(343): 53ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:HotSwapAdaptersWhilePaused: ProcessingAudio - size=0
(343): 53ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:ProcessAudio: (0x0x7f5af0001450) IGNORING... size=0 ... (audioState/uspState=1/9999) USP-ZOMBIE
(343): 53ms SPX_DBG_TRACE_SCOPE_ENTER:  usp_reco_engine_adapter.cpp:SetFormat
(343): 53ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:SetFormat: this=0x0x7f5af0001450
(343): 53ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:SetFormat - pformat == nullptr
(343): 53ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:SetFormat: (0x0x7f5af0001450) IGNORING... (audioState/uspState=1/9999) USP-ZOMBIE
(343): 53ms SPX_DBG_TRACE_SCOPE_EXIT:  usp_reco_engine_adapter.cpp:SetFormat
(343): 53ms SPX_DBG_TRACE_SCOPE_ENTER:  audio_stream_session.cpp:InformAdapterSetFormatStarting
(343): 53ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:SetAdapterMode: singleShot=0
(343): 53ms SPX_DBG_TRACE_SCOPE_ENTER:  usp_reco_engine_adapter.cpp:SetFormat
(343): 53ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:SetFormat: this=0x0x7f5af0002030
(343): 53ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:SetFormat
  wFormatTag:      PCM
  nChannels:       1
  nSamplesPerSec:  48000
  nAvgBytesPerSec: 96000
  nBlockAlign:     2
  wBitsPerSample:  16
  cbSize:          0
(343): 53ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:ChangeState; audioState/uspState: 0/0 => 1/0 USP-START
(343): 53ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:SetFormat: (0x0x7f5af0002030)->PrepareFirstAudioReadyState()
(343): 53ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:ResetBeforeFirstAudio: this=0x0x7f5af0002030 ... USP-RESET
(343): 53ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:PrepareCompressionCodec: Prepare compression codec.
(343): 53ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a90009948; name='SPEECH-Compression-Codec-Module'; value=''
(343): 53ms SPX_RETURN_ON_FAIL:  usp_reco_engine_adapter.cpp:(0x004) = 0x4
(343): 53ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:PrepareFirstAudioReadyState: (0x0x7f5af0002030)->PrepareCompressionCodec() failed:        4. Sending the audio uncompressed
(343): 53ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:UspInitialize: this=0x0x7f5af0002030
(343): 53ms SPX_DBG_TRACE_VERBOSE:  create_module_object.cpp:SDKKWS_CreateModuleObject Creating object via SDKKWS_CreateModuleObject: CSpxUspCallbackWrapper as N9Microsoft17CognitiveServices6Speech4Impl16ISpxUspCallbacksE
(343): 53ms SPX_DBG_TRACE_VERBOSE:  factory_helpers.h:Creating object via SpxFactoryEntryCreateObject: N9Microsoft17CognitiveServices6Speech4Impl22CSpxUspCallbackWrapperE as N9Microsoft17CognitiveServices6Speech4Impl16ISpxUspCallbacksE
(343): 53ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:GetScenarioCount: countSpeech=0; countIntent=0; countTranslation=1; countDialog=0, countTranscriber=0
(343): 53ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a90009948; name='SPEECH-Endpoint'; value=''
(343): 53ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a90009948; name='SPEECH-Host'; value=''
(343): 53ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a90009948; name='SPEECH-UserDefinedQueryParameters'; value=''
(343): 53ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:SetUspEndpointTranslation: Endpoint type: Translation.
(343): 53ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a9001e040; name='SPEECH-Region'; value='southeastasia'
(343): 53ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a90009948; name='SpeechServiceResponse_RequestWordLevelTimestamps'; value=''
(343): 53ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a90009948; name='SpeechServiceResponse_OutputFormatOption'; value=''
(343): 53ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a90009948; name='SpeechServiceResponse_RequestDetailedResultTrueFalse'; value=''
(343): 53ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a9001e040; name='SPEECH-RecoLanguage'; value='zh-CN'
(343): 53ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a9001e040; name='TRANSLATION-ToLanguages'; value='en-US'
(343): 53ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a9001e040; name='TRANSLATION-Voice'; value='Microsoft Server Speech Text to Speech Voice (en-US, ZiraRUS)'
(343): 53ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a9001d2e0; name='SPEECH-RecoMode'; value='CONVERSATION'
(343): 53ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:SetUspRecoMode: recoMode=1
(343): 53ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a90009948; name='SPEECH-USPPollingInterval'; value=''
(343): 54ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:SetUspEndpoint: Setting Websocket Polling interval to 10
(343): 54ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a9001e040; name='SPEECH-SubscriptionKey'; value='******************************47'
(343): 54ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a90009948; name='SPEECH-AuthToken'; value=''
(343): 54ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a90009948; name='SPEECH-RpsToken'; value=''
(343): 54ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a90009948; name='DIALOG-ApplicationId'; value=''
(343): 54ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a90009948; name='ConversationTranslator_Token'; value=''
(343): 54ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a90009948; name='OPENSSL_SINGLE_TRUSTED_CERT'; value=''
(343): 54ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a90009948; name='SPEECHSDK-SPEECH-CONFIG-OS'; value=''
(343): 54ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a9001e040; name='SPEECHSDK-SPEECH-CONFIG-SYSTEM-LANGUAGE'; value='Java'
(343): 54ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a9001d2e0; name='AudioConfig_AudioSource'; value='Stream'
(343): 54ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a9001d2e0; name='SPEECH-MicrophoneNiceName'; value=''
(343): 54ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a9001d2e0; name='AudioConfig_SampleRateForCapture'; value='48000'
(343): 54ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a9001d2e0; name='AudioConfig_BitsPerSampleForCapture'; value='16'
(343): 54ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5a9001d2e0; name='AudioConfig_NumberOfChannelsForCapture'; value='1'
(343): 54ms SPX_TRACE_INFO: AZ_LOG_INFO:  uspimpl.cpp:Connect: entering...
(343): 54ms SPX_TRACE_INFO: AZ_LOG_INFO:  uspimpl.cpp:Adding subscription key headers
(343): 54ms SPX_TRACE_INFO: AZ_LOG_INFO:  uspimpl.cpp:connectionUrl=wss://southeastasia.s2s.speech.microsoft.com/speech/translation/cognitiveservices/v1?from=zh-CN&to=en-US&features=texttospeech&voice=Microsoft%20Server%20Speech%20Text%20to%20Speech%20Voice%20(en-US%2c%20ZiraRUS)
(343): 54ms SPX_TRACE_ERROR:  usp_reco_engine_adapter.cpp:Error: 'std::bad_cast'
(343): 54ms SPX_TRACE_ERROR:  usp_reco_engine_adapter.cpp:Response: On Error: Code:5, Message: std::bad_cast.
(343): 54ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:ChangeState; audioState/uspState: 1/0 => 1/-1 USP-ERRORERROR
(343): 54ms SPX_TRACE_ERROR:  usp_reco_engine_adapter.cpp:OnError: site->Error() ... error='std::bad_cast'
(343): 54ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:Error: Creating/firing ResultReason::Canceled result
(343): 54ms SPX_DBG_TRACE_VERBOSE:  create_module_object.cpp:SDKKWS_CreateModuleObject Creating object via SDKKWS_CreateModuleObject: CSpxRecognitionResult as N9Microsoft17CognitiveServices6Speech4Impl21ISpxRecognitionResultE
(343): 54ms SPX_DBG_TRACE_VERBOSE:  factory_helpers.h:Creating object via SpxFactoryEntryCreateObject: N9Microsoft17CognitiveServices6Speech4Impl21CSpxRecognitionResultE as N9Microsoft17CognitiveServices6Speech4Impl21ISpxRecognitionResultE
(343): 54ms SPX_DBG_TRACE_FUNCTION:  recognition_result.cpp:CSpxRecognitionResult
(343): 54ms SPX_DBG_TRACE_VERBOSE:  create_object_helpers.h:SpxCreateObjectWithSite: Attempted SetSite(CSpxRecognitionResult), objectWithSite==nullptr
(343): 54ms SPX_DBG_TRACE_FUNCTION:  recognition_result.cpp:InitFinalResult
(343): 54ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5af0004050; name='RESULT-ErrorDetails'; value='std::bad_cast'
(343): 54ms SPX_TRACE_VERBOSE:  recognition_result.cpp:InitFinalResult: resultId=cb43ab6d1eaf4236a53713843b20de9c reason=1, cancellationReason=1, text=''
(343): 54ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:[0x7f5a9001d250]CSpxAudioStreamSession::WaitForRecognition_Complete: ...
(343): 54ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:[0x7f5a9001d250]CSpxAudioStreamSession::FireResultEvent
(343): 54ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5af0004050; name='RESULT-ErrorDetails'; value='std::bad_cast'
(343): 54ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.h:LogPropertyAndValue: this=0x0x7f5af0004050; name='RESULT-ErrorDetails'; value='std::bad_cast SessionId: 10de21a774c143aab6c9cce2dc5f335a'
(343): 54ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:[0x7f5a9001d250]CSpxAudioStreamSession::FireResultEvent: Firing RecoResultEvent(Canceled): SessionId: 10de21a774c143aab6c9cce2dc5f335a
(343): 54ms SPX_DBG_TRACE_SCOPE_EXIT:  usp_reco_engine_adapter.cpp:SetFormat
(343): 54ms SPX_DBG_TRACE_SCOPE_EXIT:  audio_stream_session.cpp:InformAdapterSetFormatStarting
(343): 54ms SPX_DBG_TRACE_SCOPE_EXIT:  audio_stream_session.cpp:HotSwapAdaptersWhilePaused
(343): 54ms SPX_DBG_TRACE_WARNING: audio_stream_session.cpp:[0x7f5a9001d250]CSpxAudioStreamSession::StartRecognizing: Simulating GetSite()->AdapterCompletedSetFormatStop() ...
(343): 54ms SPX_DBG_TRACE_SCOPE_ENTER:  audio_stream_session.cpp:*** CSpxAudioStreamSession::AdapterCompletedSetFormatStop kicked-off THREAD started ***
(343): 54ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:[0x7f5a9001d250]CSpxAudioStreamSession::AdapterCompletedSetFormatStop: kicked-off THREAD started ***
(343): 54ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:[0x7f5a9001d250]CSpxAudioStreamSession::ChangeState:  recoKind/sessionState: 2/5 != 4/3
(343): 54ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:[0x7f5a9001d250]CSpxAudioStreamSession::ChangeState: recoKind/sessionState: 4/3 => 4/2
(343): 54ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:[0x7f5a9001d250]CSpxAudioStreamSession::AdapterCompletedSetFormatStop: Previous Adapter is done processing audio ... resuming Processing with the new adapter...
(343): 54ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:[0x7f5a9001d250]CSpxAudioStreamSession::AdapterCompletedSetFormatStop: Now ProcessingAudio ...
(343): 54ms SPX_DBG_TRACE_SCOPE_EXIT:  audio_stream_session.cpp:*** CSpxAudioStreamSession::AdapterCompletedSetFormatStop kicked-off THREAD stopped ***
(343): 54ms SPX_DBG_TRACE_SCOPE_EXIT:  audio_stream_session.cpp:StartRecognizing
(343): 54ms SPX_DBG_TRACE_SCOPE_EXIT:  usp_reco_engine_adapter.cpp:SetFormat
(343): 54ms SPX_DBG_TRACE_SCOPE_ENTER:  usp_reco_engine_adapter.cpp:~CSpxUspRecoEngineAdapter
(343): 54ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:~CSpxUspRecoEngineAdapter: this=0x0x7f5af0001450

**Comment by jhakulin** [comment]
@wall3001 Thanks for the report, we will investigate, does this happen occasionally or always for you?

**Comment by wall3001** [comment]
It is inevitable

**Comment by wall3001** [comment]
I use the Agora On-Premise Recording SDK and it runs first，the TranslationRecognizer  raises the exception "std::bad_cast".It is inevitable.
https://docs.agora.io/en/Recording/API%20Reference/recording_java/index.html

**Comment by trrwilson** [comment]
Hello!

Thank you for the log -- it helps narrow down where you're encountering the error. This is quite unusual as there's not a lot of code that executes between the last line before the std::bad_cast (printing your endpoint URL) and the next line that should appear, the sending of your config message. From a working case:

```
(437490): 262ms SPX_TRACE_INFO: AZ_LOG_INFO:  uspimpl.cpp:connectionUrl=wss://westus2.s2s.speech.microsoft.com/speech/translation/cognitiveservices/v1?from=zh-CN&to=en-US&features=texttospeech&voice=Microsoft%20Server%20Speech%20Text%20to%20Speech%20Voice%20(en-US,%20ZiraRUS)
(437490): 262ms SPX_DBG_TRACE_SCOPE_ENTER:  web_socket.cpp:Microsoft::CognitiveServices::Speech::USP::WebSocket::WebSocket
```

The best candidates for potential sources of this are environment-specific and related to internal device info queries and/or SSL configuration.

To diagnose further, could you please share:
* What kind of device/environment is this running on? E.g. a Windows PC with the Java JRE, an Android phone with a Java app, macOS, etc.?
* Which version of the SDK (e.g. 1.14) are you running?
* As much as you can, the source code snippet you're running that hits this will be very helpful, too--e.g. below is the C# code from the "working" case above.

```csharp
            var config = SpeechTranslationConfig.FromSubscription(Subscriptions.WestUS2.Key, Subscriptions.WestUS2.Region);
            config.SpeechRecognitionLanguage = "zh-CN";
            config.AddTargetLanguage("en-US");
            config.VoiceName = "Microsoft Server Speech Text to Speech Voice (en-US, ZiraRUS)";

            config.SetLogPath("translator.log");

            using (var translator = new TranslationRecognizer(config))
            {
                translator.Canceled += (_, e) => Print($"Canceled: {e.ErrorDetails}");
                Print($"请现在就说");
                var result = await translator.RecognizeOnceAsync();
                Print($"Result: {result.Text}");
                foreach (var translation in result.Translations)
                {
                    Print($"  -> [{translation.Key}]: {translation.Value}");
                }
            }
```

Thanks!! I'm very curious to find what's causing this std::bad_cast error.

**Comment by wall3001** [comment]
1. linux Ubuntu 16.04.6  
2. 1.14,I try other versions as well
3.  The code is correct. It works well when I don't run the Agora Recording SDK.I guess that there is a conflict between them.

**Comment by trrwilson** [comment]
Thanks for the clarification on the role that Agora has here--this makes a lot more sense now!

I'm not familiar with the usage of that SDK as an audio postprocessing shim. Could you please share the code snippet of how you're providing the audio to Speech SDK after it comes from Agora? I'm guessing it must involve something like `onAudioFrameReceived`, but I've never used it before.

Given the involvement, the most likely explanation is that there's a format mismatch or other related issue with the input audio (or, if this is happening implicit, audio device selection). We should emit a better error than this if that's the case, but making the code work should just be a matter of adjusting the I/O to line up appropriately.

**Comment by wall3001** [comment]
The format is matched beacuse I send the audio data  to  the other service which in another process  to translate it,it works well.I find that it can not work in the same process with Agora Recording SDK.I guesss that maybe some error  in .so lib.

the code snippet is as follows
PushAudioInputStream inputStream  =AudioInputStream.createPushStream(AudioStreamFormat.getWaveFormatPCM(Long.parseLong(sampling);

public void audioFrameReceived(long uid, Common.AudioFrame frame) {
          inputStream.write(downSampling48KTo16K(frame.pcm.pcmBuf));
	}

**Comment by glecaros** [comment]
Hi @wall3001 , were you able to resolved this?

**Comment by amitkumarshukla** [comment]
@wall3001 Please try with 1.16.0 of speech sdk. I am closing this issue for the time being. Please open it again if you face the problem.
