### ISSUE TITLE
Azure Speech-to-text: "RuntimeError: Exception with an error code: 0xe (SPXERR_MIC_NOT_AVAILABLE)"

### ISSUE THREAD

**Issue by manueltorrs** [Azure-Samples/cognitive-services-speech-sdk#934]
I have this issue on Widows 10, I have this code:

    import azure.cognitiveservices.speech as speechsdk
    import time

    weatherfilename = "video.wav" 
    use_default_microphone=True
    device_name="1"

    speech_key, service_region = "MyKey", "MyServer"
    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)
    source_language_config = speechsdk.languageconfig.SourceLanguageConfig("es-ES")
    audio_config = speechsdk.audio.AudioConfig(device_name=device_name)

    def speech_recognize_continuous_from_file():

        speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config,
                                                   source_language_config=source_language_config,
                                                   audio_config=audio_config)

        done = False

        def stop_cb(evt):
            """callback that stops continuous recognition upon receiving an event `evt`"""
                print('CLOSING on {}'.format(evt))
                speech_recognizer.stop_continuous_recognition()
                nonlocal done
                done = True

        speech_recognizer.recognizing.connect(lambda evt: print("{}".format(evt.result.text)))
        speech_recognizer.session_stopped.connect(stop_cb)
        speech_recognizer.canceled.connect(stop_cb)

        # Start continuous speech recognition
        speech_recognizer.start_continuous_recognition()
        while not done:
            time.sleep(.5)

    speech_recognize_continuous_from_file()

And it works pretty good when I use a file .wav or the default microfone (weatherfilename = "video.wav"
use_default_microphone=True) but when I want to use any specific device it shows me this error:

> Traceback (most recent call last):
> File "RecoVozAzure.py", line 50, in
> speech_recognize_continuous_from_file()
> File "RecoVozAzure.py", line 23, in speech_recognize_continuous_from_file
> audio_config=audio_config)
> File "C:\Users\Manuel\AppData\Roaming\Python\Python37\site-packages\azure\cognitiveservices\speech\speech.py", line 802, in init
> self._impl = self._get_impl(impl.SpeechRecognizer, speech_config, audio_config, language, source_language_config, auto_detect_source_language_config)
> File "C:\Users\Manuel\AppData\Roaming\Python\Python37\site-packages\azure\cognitiveservices\speech\speech.py", line 874, in _get_impl
> return reco_type._from_config(speech_config._impl, source_language_config._impl, audio_config._impl)
> RuntimeError: Exception with an error code: 0xe (SPXERR_MIC_NOT_AVAILABLE)
> [CALL STACK BEGIN]
> 
> > pronunciation_assessment_config_to_json
> 
> - pronunciation_assessment_config_to_json
> 
> - pronunciation_assessment_config_to_json
> 
> - pronunciation_assessment_config_to_json
> 
> - pronunciation_assessment_config_to_json
> 
> - pronunciation_assessment_config_to_json
> 
> - pronunciation_assessment_config_to_json
> 
> - pronunciation_assessment_config_to_json
> 
> - pronunciation_assessment_config_to_json
> 
> - pronunciation_assessment_config_to_json
> 
> - pronunciation_assessment_config_to_json
> 
> - pronunciation_assessment_config_to_json
> 
> - pronunciation_assessment_config_to_json
> 
> - pronunciation_assessment_config_to_json
> 
> - pronunciation_assessment_config_to_json
> 
> - pronunciation_assessment_config_to_json
> [CALL STACK END]

It happens even if I try to use the default one but calling it with the device_name function.. As I said, my microphone and the algorithm work very well and I have problems only when I call the device_name function...

The documentation of this is on this page:

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-select-audio-input-devices#feedback

And right now I don't know what I can do.

I have:
* Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)]
* Windows 10 Pro Ver. 2004 OSVer 19041.746
* azure-cognitiveservices-speech Ver. 1.14.0

Thanks for helping!

#482 

PD: @jhakulin This is the new topic, thanks

**Comment by jhakulin** [comment]
@manueltorrs Thanks! Could you inform the device names you get when listing the endpoints using the code from below link? https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-select-audio-input-devices#audio-device-ids-on-windows-for-desktop-applications

**Comment by manueltorrs** [comment]
Thank you so much, that was the problem, I was using a different program in python using the library Speech_Recognition to identify the source but it shows different names than the program in your suggestion.. I was identifying the sources with numbers of an index like

* "1"
* "2" or
* "3"

instead of

* "{0.0.1.00000000}.{90255f10-2e4d-4122-85ba-7cbd09359b60}" and
* "{0.0.1.00000000}.{cab9c07c-337f-41e4-a02b-9f90336d6761}"

those are the real names for windows..

This problem is solved, but I've found a new one, and I'll look for it and if I don't found the answer I'll ask again, thank you so much!

**Comment by trrwilson** [comment]
Glad that the ID selection worked appropriately! Closing this ticket to keep things tidy -- please open a new one for the other issue, as needed.

Thank you!
