### ISSUE TITLE
Phonetic translation

### ISSUE THREAD

**Issue by shaohui93** [Azure-Samples/cognitive-services-speech-sdk#94]
I use Android SDK for voice recognition, and when I translate voice, I return multiple bytes []. How can I synthesize multiple bytes [] into a single audio seamlessly?
Now in recognizer. synthesizing. addEventListener this callback will return multiple byte [], if I add all byte [] to an array and convert it into audio playback, it will only play the first returned byte [] audio, not all playback.

**Comment by zhouwangzw** [comment]
When receiving a synthesizing event, please check the Reason member. If it is SynthesizingAudio, the byte array in the event contains synthesized audio which contains a WAV header and data. If it is SynthesiszingAudioCompleted, it indicates the audio for the current translated text is complete. The audio size must be zero in this case.
In your case, each non-zero byte array contains its own wav header. If you want to concatenate them into a single one for playback, you need to remove wav header in the byte array. Alternatively, you can play each byte array as an independent wav file.
