### ISSUE TITLE
How to write a function that triggers the speech recognition javascript api by pressing a key?

### ISSUE THREAD

**Issue by inglesuniversal** [Azure-Samples/cognitive-services-speech-sdk#941]
Aside of clicking on the START button, how can I implement a feature to start the same process when pressing a single key on the keyboard?

Thanks

`document.body.onkeyup = function(e){
    if(e.keyCode == 32){
        console.log('Spacebar pressed.');
        recognizeVoice();
    }
}`

**Comment by glharper** [comment]
@inglesuniversal Attached is an example to get you started, along with the library files. Spacebar should start recognition, and Backspace stop recognition.
[keypress_example.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/5946248/keypress_example.zip)
