### ISSUE TITLE
speech-to-text support more languages 

### ISSUE THREAD

**Issue by jzhw0130** [Azure-Samples/cognitive-services-speech-sdk#945]
Hi, want to known any plan to support `vi-VN` and `bn-BD` in speech-to-text model.

**Comment by dargilco** [comment]
@jzhw0130 Thanks for posting this question! I was informed that vi-vn will be supported by the end of this Month. Please check out the "[Language and voice support for the Speech service](https://docs.microsoft.com/azure/cognitive-services/speech-service/language-support#:~:text=Neural%20voices%20%20%20%20Language%20%20,%20ar-SA-HamedNeural%20New%20%2025%20more%20rows)" page. It will be updated a few days after the new locale goes public and was verified.

With regards to bn-bd, it will be supported before the end of July 2021.

Darren

**Comment by dargilco** [comment]
@jzhw0130 Vietnamese (vi-VN) was enabled on cognitive speech service this week, in the following 5 Azure regions:
West Central US, West US, North Central US, East US 2, Australia East. Support will extend to other regions next week.
Darren

**Comment by jzhw0130** [comment]
@dargilco 

Hi, do we support `bn-BD` now?  
According to [Language and voice support for the Speech service](https://docs.microsoft.com/en-gb/azure/cognitive-services/speech-service/language-support#:~:text=Neural%20voices%20%20%20%20Language%20%20,%20ar-SA-HamedNeural%20New%20%2025%20more%20rows), seems not yet?
