### ISSUE TITLE
Text Independent - Identify Single Speaker REST API POST request returns 'Audio too noisy' error

### ISSUE THREAD

**Issue by muhmuhcow** [Azure-Samples/cognitive-services-speech-sdk#948]
**Describe the bug**
Text Independent - Identify Single Speaker REST API POST request returns 'Audio too noisy' error

Audio file: myVoiceIsMyPassportVerifyMe01.wav found in cognitive services quickstart

code snippet

`
const { createReadStream } = require('fs');
const stream = createReadStream('./myVoiceIsMyPassportVerifyMe01.wav');
var data = {
    "audioData": stream
  };
const options = {
    headers: 
    {
      'Ocp-Apim-Subscription-Key': 'SUB_KEY',
      'Content-type': 'audio/wav',
      'codecs': 'audio/pcm',
      'samplerate': '16000'
    }
}
axios.post(idSpeakerUrl, data, options)
      .then((response) => {
        console.log(response.data);
      })
      .catch(error => {
        console.log(error.response.data.error)
     })
`

error:
{ code: 'InvalidRequest', message: 'Audio is too noisy.' }

**Comment by muhmuhcow** [comment]
with the same audio file it works when using the SDK but not when using the REST API

**Comment by pankopon** [comment]
@chlandsi Can you please check? Is https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/387#issuecomment-536908564 still valid for a working example?

**Comment by jhakulin** [comment]
@muhmuhcow Thanks for feedback, could you please try the reproduce your problem again? We only keep debug logs for 1 week. Once you hit the problem again, could you please provide the request url you are using (with the profileids and time stamp)?

**Comment by glecaros** [comment]
Hi, I'm closing this issue has there hasn't been any activity in quite some time. @muhmuhcow please feel free to reopen it if you need further help.
