### ISSUE TITLE
iOS synthesized speech abnormal

### ISSUE THREAD

**Issue by xiaoMing0109** [Azure-Samples/cognitive-services-speech-sdk#949]
**About iOS access to the latest version of the SDK:**

1. Lost words occur;

2. Execute the `completedHandler` callback, but no sound is played;

3. Under the premise that it takes 14s for a piece of speech to be played completely:

     - 1s `stop` is not completed, execute `canceledEventHandler`

     - 1s `stop` has played the sound, execute `canceledEventHandler`

     - 10s `stop` has played the sound, execute `completedHandler`

```
SPXSpeechConfiguration *speechConfig = [[SPXSpeechConfiguration alloc] initWithSubscription:sub region:region];
        speechConfig.speechSynthesisVoiceName = @"zh-CN-XiaoxiaoNeural";// 如果为 ssml 合成(含发音人配置), 该配置会自动失效
        
        SPXAudioConfiguration *audioConfig = [[SPXAudioConfiguration alloc] initWithDefaultSpeakerOutput];
        _speechSynthesizer = [[SPXSpeechSynthesizer alloc] initWithSpeechConfiguration:speechConfig audioConfiguration:audioConfig];
```

```
- (void)speechSynthesisText:(NSString *)text {
    [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];// 静音模式下可外放
    dispatch_async(dispatch_get_global_queue(0, 0), ^{// 合成放到子线程, 避免阻塞
         [self.speechSynthesizer startSpeakingSsml:text];
    });
}
```

```
- (void)stopSpeechSynthesis {
    [self.speechSynthesizer stopSpeaking];
}
```

**Comment by yulin-li** [comment]
Thanks for reaching out.

For 1), is it random or always? Could you try to save the audio file to see if the word is missing?

For 2), is it random or always? Could you try to [enable the logging](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging) and share the log to us?

For 3), it's expected. If the synthesis is not finished (got all audio data from service), the result reason would be canceled, then the `canceledEventHandler` would be called. If the synthesized is finished, but the playback is ongoing, then the synthesis is completed, calling `stopSpeaking()` will stop the playback.

**Comment by pankopon** [comment]
@xiaoMing0109 Can you please update with additional info as requested above?

**Comment by yulin-li** [comment]
@xiaoMing0109 we are going to close this issue, feel free to reopen it if needed.
