### ISSUE TITLE
[Java,Android] Silence timeout between keyword and speech recognition

### ISSUE THREAD

**Issue by crazyracer98** [Azure-Samples/cognitive-services-speech-sdk#950]
Hi everybody,

for a project we've integrated your SDK into an Android app based on Java.
Now, due to the target device and the WiFi being somewhat slow, the silence timeout is already reached when the UI feedback (using SpeechRecognizer.recognizing) kicks in.
Is there some way to increase the timeout between the keyword and the speech recognition?
We've already tried setting the following properties on the AudioConfig object without success:
```java
// 1s = 1.000.000.000ns - 1s = 1000ms
float SECONDS = 1.0f;
audioConfig.setProperty(PropertyId.Conversation_Initial_Silence_Timeout, String.valueOf(SECONDS * 1000000000));
audioConfig.setProperty(PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs, String.valueOf(SECONDS * 1000));
audioConfig.setProperty(PropertyId.SpeechServiceConnection_EndSilenceTimeoutMs, String.valueOf(SECONDS * 1000));
```

Many thanks in advance.

**Comment by amitkumarshukla** [comment]
@crazyracer98  Thanks a lot for your query. We didnt understand the problem you are describing. Could please please provide the steps that you are doing. Possibly a sample code ? We will be able to help you better with that.

**Comment by crazyracer98** [comment]
We're using this code below:
```java
SpeechConfig speechConfig = SpeechConfig.fromSubscription(azure_subscription_key, azure_subscription_region);
AudioConfig audioConfig = AudioConfig.fromDefaultMicrophoneInput();
SpeechRecognizer speechRecognizer = new SpeechRecognizer(speechConfig, audioConfig);
PhraseListGrammar phraseListGrammar = PhraseListGrammar.fromRecognizer(speechRecognizer);
InputStream inputStream = activity.getAssets().open(getKeywordFile());
KeywordRecognitionModel keywordRecognitionModel = KeywordRecognitionModel.fromStream(inputStream, "hey computer", false);
inputStream.close();

speechRecognizer.recognizing.addEventListener((o, speechRecognitionEventArgs) -> {
    showUiAppIsListening(true);
}
speechRecognizer.recognized.addEventListener((o, speechRecognitionEventArgs) -> {
    parsePhrase(speechRecognitionEventArgs.getResult().getText());
    showUiAppIsListening(false);
}
phraseListGrammar.addPhrase("hey computer send message to peter");
phraseListGrammar.addPhrase("hey computer recover state of instrument");
// ...many other phrases
speechRecognizer.startKeywordRecognitionAsync(keywordRecognitionModel);
```

Now, most of the time our users wait for the UI to show that the App is listening. The problem is that when `showUiAppIsListening(true)` is called and the state is shown to the user, they have very little time to respond and continue their phrase they want to say.
We would like to increase the time / timeout / time of silence between the keyword being recognized and the speech to text afterwards.

**Comment by pankopon** [comment]
@crazyracer98 Unfortunately, the timeout after a keyword is not publicly configurable at the moment. SpeechServiceConnection_InitialSilenceTimeoutMs and _EndSilenceTimeoutMs have a different purpose, they are described in more detail in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/502, whereas Conversation_Initial_Silence_Timeout is not used at all for the time being.

What is the longest delay there can be between the keyword and speech in your use case i.e. how long may the user have to wait for the UI to show?

Does your app work on a good network if a user says, for example, [keyword][pause for 3 sec][command] ?

**Comment by crazyracer98** [comment]
Thanks for clarifying the properties!
I will have to test / time the exact timeout on monday, but I basically show the state in the UI immediately.
If I remember correctly there is at maximum about 0.5 sec between the UI showing the recognizing and recognized state.

**Comment by pankopon** [comment]
@crazyracer98 Do you mean that if there is more than 0.5 sec between the keyword and speech then the recognition result contains only the keyword? That seems strangely short, the timeout should be longer by default. It could be easier to measure by using a wav file input, with a specific length of silence between the keyword and speech. In any case, can you please also enable logging while testing, and attach the log file: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

**Comment by crazyracer98** [comment]
Hej hej, sadly I couldn't get my device to save the log files with the provided code snippets from your article.
Also I cannot generate any wav files with specific timings currently.
However, using the Windows 10 Alarm and Clock app the maximum time of silence between keyword and phrase seems to be around 1s to 1.5s, maybe even 1.5s to 2s (using `showUiAppIsListening(true)` and `showUiAppIsListening(false)` as a reference).
Waiting longer than 2 seconds always triggers `showUiAppIsListening(false)`.

**Comment by crazyracer98** [comment]
Hej @pankopon,
I finally got the log files of the device, but it contains information that I can't post as public.
Can I mail it directly to you? Or upload it somewhere safe?

**Comment by amitkumarshukla** [comment]
@crazyracer98 are you still facing this issue ?

**Comment by amitkumarshukla** [comment]
@crazyracer98 I am closing this issue for the time being. Please open a new issue incase you face it.
