### ISSUE TITLE
Why is punctuation and capitalization different when running against cloud and local containers for Swedish?

### ISSUE THREAD

**Issue by DanielFalkSR** [Azure-Samples/cognitive-services-speech-sdk#951]
When we use the cloud service we receive punctuation and capitalization correctly but when using the Swedish docker container locally (latest version 2.9.0) we do not receive any punctuation and the capitalization behaves differently, particularly capitalizing the last letter of a word and merging it with the next.

This is an example where the container version behaves weirdly:
```
{
  "text": "eric bergströMP fyra sjuhärad",
  "lexicalForm": "eric bergström p fyra sjuhärad",
  "normalizedForm": "eric bergströMP fyra sjuhärad",
  "maskedNormalizedForm": "eric bergströMP fyra sjuhärad",
  ...
}
```

And this is how it looks when running against the cloud:
```
{
  "text":"Erik bergström, p 4 sjuhärad."
  "lexicalForm":"bergström p fyra sjuhärad",
  "normalizedForm":"erik bergström p 4 sjuhärad",
  "maskedNormalizedForm":"",
  ...
}
```

Why is punctuation and capitalization different when running against cloud and local containers for Swedish?

**Comment by amitkumarshukla** [comment]
@DanielFalkSR Thanks a lot for your query. We will get back to you asap.

**Comment by anthonsu** [comment]
@amitkumarshukla Thanks for your query! 
The current local speech container has limited display (capitalization, punctuation and etc.) support on some locales like Swedish. The team is working on delivering more accurate displays as what Cloud speech provides today. 
Please stay tuned. And again really appreciate your feedback!

**Comment by fannedalk** [comment]
Thank you! Since we for security reasons need to run on premise, and the transcripts are quite hard to read as is for the users, we are really interested in the time frame. When do you estimate you will release this on Swedish locale?

**Comment by DanielFalkSR** [comment]
Thank you! Since we for security reasons need to run on premise, and the transcripts are quite hard to read as is for the users, we are really interested in the time frame. When do you estimate you will release this on Swedish locale?

**Comment by pankopon** [comment]
@anthonsu Can you please provide any estimate of the release time frame?

**Comment by anthonsu** [comment]
There is no clear estimate of the release yet. 
I will try post it here when any new updates coming.
Thanks!

**Comment by pankopon** [comment]
Closing the item since improvements have been identified and work is in progress, release information will be provided when known.
