### ISSUE TITLE
synthesiscomplete example

### ISSUE THREAD

**Issue by crwk78** [Azure-Samples/cognitive-services-speech-sdk#956]
Hi, using VB.NET, I have a private sub with a series of SpeakTextAsync calls based on various conditions using simple 'if / then / end if' structures. The idea is to replicate a simple conversation between two different voices and exactly what is said is based on what is determined within other subs.

My problem is that the speech overlaps and one voice starts talking before the other is finished etc. Can I use synthesiscompleted to rectify this and if so, how would I use it within a single sub containing a few dozen strings to be spoken, one after another and only once the previous one has completed?

**Comment by amitkumarshukla** [comment]
@yulin-li Could you please answer this question.

**Comment by v-demjoh** [comment]
SpeakTextAsync is **synchronous** when rendering audio to a speaker device attached to the computer. So if you're calling SpeakTextAsync and hearing overlaps, it's because you are synthesizing to a different target such as a stream, not to the computer speaker. True? When rendering to a stream, SpeakTextAsync fires SynthesisCompleted after the speech audio data is fully available on the local computer. When rendering to a speaker device on the computer, SynthesisCompleted indicates audio rendering has completed, and the Await keyword will pause at SpeakTextAsync until SynthesisCompleted has fired. Are you rendering audio to a target other than the computer's speaker?

**Comment by yulin-li** [comment]
Hi @crwk78, thanks for reaching out and sorry for the delay for Chinese New Year. If you want to sequence multi TTS playbacks, you can either
- use only one synthesizer to call `speakTextAsync` many times, then the synthesized audio will playback one by one, if you use multi synthesizer, there will be overlaps.
- await `speakTextAsync` then start another synthesis. `speakTextAsync.get()` will return after playback is finished if you use SDK playback.

**Comment by crwk78** [comment]
Thanks to you both for your comments. They both make a lot of sense.

It is happening because I'm using two synthesizers, one for each voice.

I started using a single synthesizer but I found that my program wasn't picking up any voice changes if I changed the voice after 
declaring the speechsynthesizer.

In other words, in terms of changing the default accent to a specified one, 1 works but 2 doesnt..

1)
  microsoftspeechperson1.SpeechSynthesisVoiceName = "en-GB-LibbyNeural"
  Dim microsoftsynthesiserperson1 As New SpeechSynthesizer(microsoftspeechperson1)

2)
  Dim microsoftsynthesiserperson1 As New SpeechSynthesizer(microsoftspeechperson1)
  microsoftspeechperson1.SpeechSynthesisVoiceName = "en-GB-LibbyNeural"

I'd like to be able to change the voice before each line of synthesized text to be spoken, as I'm trying to replicate a conversation. Can I do this without redeclaring the speechsynthesizer each time too?

I currently have the following (2x synthesizers, change of voices work but synthesis overlaps):
      
  microsoftspeechperson1.SpeechSynthesisVoiceName = "en-GB-LibbyNeural"
  Dim microsoftsynthesiserperson1 As New SpeechSynthesizer(microsoftspeechperson1)
  
  microsoftspeechperson2.SpeechSynthesisVoiceName = "en-GB-RyanNeural"
  Dim microsoftsynthesiserperson2 As New SpeechSynthesizer(microsoftspeechperson2)

  microsoftsynthesiserperson1.SpeakTextAsync(sentence1)
  microsoftsynthesiserperson2.SpeakTextAsync(sentence2)
  microsoftsynthesiserperson1.SpeakTextAsync(sentence3)
  microsoftsynthesiserperson2.SpeakTextAsync(sentence4)


I started with (1x synthesizer, no overlap but no change in voice either):

  Dim microsoftsynthesiserperson As New SpeechSynthesizer(microsoftspeechperson)
     
  microsoftspeechperson.SpeechSynthesisVoiceName = "en-GB-LibbyNeural"
  microsoftsynthesiserperson.SpeakTextAsync(sentence1)

  microsoftspeechperson.SpeechSynthesisVoiceName = "en-GB-RyanNeural"
  microsoftsynthesiserperson.SpeakTextAsync(sentence2)

  microsoftspeechperson.SpeechSynthesisVoiceName = "en-GB-LibbyNeural" 
  microsoftsynthesiserperson.SpeakTextAsync(sentence3)

  microsoftspeechperson.SpeechSynthesisVoiceName = "en-GB-RyanNeural"
  microsoftsynthesiserperson.SpeakTextAsync(sentence4)

Any further help as to how to achieve my end result would be much appreciated..

**Comment by yulin-li** [comment]
Hi @crwk78 you can use [SSML](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup?tabs=csharp) to config the voice name.

**Comment by crwk78** [comment]
Thanks for the info, and I’m very much going to show my lack of expertise here:

My project is in vb.net, the synthesis part is a very small part of the project. For SSML I need to use XML files, is this correct? Can you talk me through how I call speech synthesis from a VB project via an xml file containing the SSML data?

**Comment by yulin-li** [comment]
Hi @crwk78, you can use a simple string template, as you just need the voice name and text.

**Comment by yulin-li** [comment]
we are going to close this issue, feel free to re-open it if needed
