### ISSUE TITLE
Unable to load DLL 'Microsoft.CognitiveServices.Speech.core.dll'

### ISSUE THREAD

**Issue by hjam40** [Azure-Samples/cognitive-services-speech-sdk#957]
Hi,

I have a problem when I try to publish my project and copy it to another machine. In my developer workstation the application works fine but when I copy the publish folder to another Windows 10 and run the Console app I get the following error:

Unable to load DLL 'Microsoft.CognitiveServices.Speech.core.dll' or one of its dependencies: No se puede encontrar el módulo especificado. (0x8007007E):    at Microsoft.CognitiveServices.Speech.Internal.SpeechConfig.speech_config_from_subscription(IntPtr& config, String subscriptionKey, String region)
   at Microsoft.CognitiveServices.Speech.SpeechConfig.FromSubscription(String subscriptionKey, String region)

Both my developer workstation and the destination machine are Win10 x64 and I copy the full publish folder (with the runtimes subfolder).

**Developer Workstation info:**

dotnet --info
SDK de .NET (que refleje cualquier global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Destination workstation info:**
dotnet --info

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

Thanks.

**Comment by jhakulin** [comment]
@hjam40 Could you ensure that you have the latest "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019" installed in the other machine as well as Speech SDK depends on VS2019 runtimes ? Download and install it from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads. 

And let us know if that helps

**Comment by hjam40** [comment]
Thank you jhakulin! That was the problem. I don't know that I need this package in the other machine.
