### ISSUE TITLE
Node JS Sample for Batch Transcription

### ISSUE THREAD

**Issue by namrata01Apr** [Azure-Samples/cognitive-services-speech-sdk#958]
**Is your feature request related to a problem? Please describe.**
There is a customer that needs the node js sampled for the batch transcription. it currently exists only for Python and Csharp

**Describe the solution you'd like**
I have build the code , but need to commit to this repository as it doesnt exist yet

**Comment by amitkumarshukla** [comment]
Thanks a lot for creating the sample. I hope https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/javascript/node should be the right place for you to create a PR.

**Comment by namrata01Apr** [comment]
Hi
Currently I see the other batch transcription samples at the below path -
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/batch/

Let me know what you think?

**Comment by chlandsi** [comment]
Hi @namrata01Apr, that sounds like the right place. Looking forward to the PR.

**Comment by pankopon** [comment]
Closing the issue as there's now a PR https://github.com/Azure-Samples/cognitive-services-speech-sdk/pull/963 about the sample, @chlandsi please review.

**Comment by namrata01Apr** [comment]
@chlandsi <https://github.com/chlandsi> - let me know your view on the code
sample uploaded .
