### ISSUE TITLE
add stop/reset to synthesized audio in TTS JS sample

### ISSUE THREAD

**Issue by TwinMist** [Azure-Samples/cognitive-services-speech-sdk#959]
Is it possible to add a stop or reset button to the TTS JS sample so dont have the wait till the end to edit the text
thanks

**Comment by amitkumarshukla** [comment]
@glharper Please check the request.

**Comment by glharper** [comment]
@TwinMist Thanks for writing up this issue, and using Speech SDK. Currently I'm not finding an API on SpeechSynthesizer to bind to a stop button the way that the start button binds to SpeechSynthesizer.speakTextAsync(). We do have a plan to add StopSpeakingAsync() to SpeechSynthesizer within the next few releases. Should I ping you when that new method is added?

**Comment by TwinMist** [comment]
Many thanks for your reply. That would be great

**Comment by pankopon** [comment]
Closing the issue as there's a work item on the backlog, we'll update this when the feature becomes available.

**Comment by hanhsia** [comment]
any update? there are two years passed.
