### ISSUE TITLE
how to get audio data?

### ISSUE THREAD

**Issue by SongKeTong** [Azure-Samples/cognitive-services-speech-sdk#96]
In the demo, I can get the result text data, but how can I get the result Audio data?

**Comment by wolfma61** [comment]
what demo are you talking about, some more information is definitely helpful?

voice output is only generate for the translation recognizer
see for example translation_samples.cs

**Comment by SongKeTong** [comment]
Thanks, I used c++ translation demo. I can only get text result. how can I get the result Audio data?

**Comment by SongKeTong** [comment]
I used c++ translation demo. I can only get text result. how can I get the result Audio data? @wolfma61

**Comment by SongKeTong** [comment]
Okey!
Tanky you !
