### ISSUE TITLE
Option in js sample to select output

### ISSUE THREAD

**Issue by TwinMist** [Azure-Samples/cognitive-services-speech-sdk#960]
Be great if within the js sample there could be a option to select the type of output format when saving the audio

**Comment by pankopon** [comment]
Hi, so this must be about https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/synthesis.html - I have added a work item about it to our backlog for consideration, and we will update this item when the change is available.

**Comment by pankopon** [comment]
Closing as added to the backlog.
