### ISSUE TITLE
Authentication error (401)

### ISSUE THREAD

**Issue by Mallo-Lucas** [Azure-Samples/cognitive-services-speech-sdk#966]
Hi everyone, recently I downloaded the unity sample to test the project and when I press the button for continuous recognition I get this error:

CANCELED: ErrorDetails=WebSocket upgrade failed: Authentication error (401). Please check subscription information and region name. SessionId: 8c9bb8ab475a483083382edb6d7f8073
UnityEngine.Debug:LogFormat(String, Object[])

i follow the steps of the creation of the keys to use the sdk and still didnt work.

im using Microsoft.CognitiveServices.Speech.1.15.0 
My operating system is on windows x64 on c#

Ill add some pictures of the project and the errors
<img width="815" alt="errorSDK2" src="https://user-images.githubusercontent.com/61807778/108412230-5e294580-7208-11eb-836c-c92427dd9c73.png">
<img width="1140" alt="errorSDK3" src="https://user-images.githubusercontent.com/61807778/108412383-90d33e00-7208-11eb-8c08-683caba2f833.png">

Thanks All!

**Comment by pankopon** [comment]
@jhakulin Please check.
@Mallo-Lucas I removed one of your screenshots because you probably don't want to share your subscription key in public...

**Comment by jhakulin** [comment]
@Mallo-Lucas Have you checked your subscription key and region are valid?  Unity sample should work for that purpose as well, however if this is your first try of Speech SDK, you may want to try with simpler .NET version first, e.g.
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/dotnet/from-microphone

Let us know if you have any problems with that.

**Comment by Mallo-Lucas** [comment]
thanks for reply, how i know if there are correct? i mean i just create the resource of the picture and choose southbrasil becouse is near where i live
![imagen](https://user-images.githubusercontent.com/61807778/108439434-056da300-7230-11eb-9df8-3ee360be1fbc.png)

**Comment by jhakulin** [comment]
@Mallo-Lucas I would like you to try with some other sample, like the one I have pointed out below to figure out is there a problem with the Unity sample or with your keys. Let us know if the sample below works with the key and region you have.
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/dotnet/from-microphone

**Comment by Mallo-Lucas** [comment]
Hi, in the end I realized that the error was that I chose the wrong azure service, I had to choose cognitive services and not the speech service, thanks also for the help.
