### ISSUE TITLE
STT accuracy is very bad when using a stream compared to a .wav file

### ISSUE THREAD

**Issue by aditmer** [Azure-Samples/cognitive-services-speech-sdk#967]
**Describe the bug**
I'm getting a much lower STT accuracy when using `AudioConfig.FromInputStream()` ​than I do with `AudioConfig.FromWavFileInput()`

I pass the same file to both methods and get drastically different results. 

**To Reproduce**
1.  Create an AudioConfig from a wav file by passing in the file path
2. Create an AudioConfig from an input stream by passing in a PullAudioInputStream(new BinaryAudioStreamReader(new BinaryReader(audio))))
3. Pass each AudioConfig to the recognizer
4. Compare the results

**Expected behavior**
Exact same text results given the same input file regardless if it comes from a file or a stream.

**Version of the Cognitive Services Speech SDK**
1.15.0

**Platform, Operating System, and Programming Language**
 - OS: MacOS Big Sur 11.2 
 - Hardware - ARM M1
 - Programming language: C#
 - Browser: Edge Version 90.0.782.0 (Official build) Dev (64-bit)

**Additional context**

**Comment by jhakulin** [comment]
@aditmer Sharing the discussion which we had on emails which was that the wave file you were using was stereo but configuration was assuming mono (default). Did you managed to get it working by configuring pull audio stream to stereo ?

using (var audioInput = AudioConfig.FromStreamInput(new PullAudioInputStream(new BinaryAudioStreamReader(
                                    new BinaryReader(audio))), AudioStreamFormat.GetWaveFormatPCM(16000, 16,2)))  

Alternatively you could use mono wave file.
Closing the issue.
