### ISSUE TITLE
Nodej use microsoft-cognitiveservices-speech-sdk auth 401

### ISSUE THREAD

**Issue by zhaoxingyun** [Azure-Samples/cognitive-services-speech-sdk#968]
code like this:

```javascript
const fs = require('fs');
const sdk = require("microsoft-cognitiveservices-speech-sdk");
const speechConfig = sdk.SpeechConfig.fromSubscription("my key", "eastasia");

console.log('speech config', speechConfig)

function fromFile() {
    let pushStream = sdk.AudioInputStream.createPushStream();

    fs.createReadStream("./audio/e9dee8f7-马瑞文-2021-02-22-18-05-24.wav").on('data', function (arrayBuffer) {
        pushStream.write(arrayBuffer.slice());
    }).on('end', function () {
        pushStream.close();

        let audioConfig = sdk.AudioConfig.fromStreamInput(pushStream);
        let recognizer = new sdk.SpeechRecognizer(speechConfig, audioConfig);
        recognizer.recognizeOnceAsync(result => {
            console.log(result);
            console.log(`RECOGNIZED: Text=${result.text}`);
            recognizer.close();
        });
    });

}

fromFile();
```

`recognizer.recognizeOnceAsync` result ：
```javascript
{
  privResultId: '42525738ECF0488BA8C1D58EF10BCA4C',
  privReason: 1,
  privText: undefined,
  privDuration: undefined,
  privOffset: undefined,
  privLanguage: undefined,
  privLanguageDetectionConfidence: undefined,
  privErrorDetails: 'Unable to contact server. StatusCode: 1006, undefined Reason:  getaddrinfo ENOTFOUND undefined.stt.speech.microsoft.com',
  privJson: undefined,
  privProperties: PropertyCollection {
    privKeys: [ 'CancellationErrorCode' ],
    privValues: [ 'ConnectionFailure' ]
  },
  privSpeakerId: undefined
}
```

my service like this:

![image](https://user-images.githubusercontent.com/1892152/108806957-162a6a00-75de-11eb-952d-f548ed67cff3.png)
![image](https://user-images.githubusercontent.com/1892152/108806977-280c0d00-75de-11eb-8d01-95bb6549c16a.png)
![image](https://user-images.githubusercontent.com/1892152/108807011-3c500a00-75de-11eb-8dba-1fbd2704de4c.png)

I can't find the cause of the error, please help.

**Comment by glharper** [comment]
@zhaoxingyun "getaddrinfo ENOTFOUND undefined.stt.speech.microsoft.com" is your problem. Running your code works with no issue for me when I set the region to eastasia, but I get the exact same error as you when I use "undefined" for the region instead. Are you sure the region isn't getting overwritten somewhere in your code?

**Comment by glharper** [comment]
@zhaoxingyun Were you able to get this working?

**Comment by zhaoxingyun** [comment]
The reason is the account problem, it can be used normally after creating a new account.
