### ISSUE TITLE
iOS Archive Failed.

### ISSUE THREAD

**Issue by xiaoMing0109** [Azure-Samples/cognitive-services-speech-sdk#969]
```
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_SPXSpeechSynthesisCancellationDetails", referenced from:
      objc-class-ref in XZMicrosoftAzureManager.o
  "_OBJC_CLASS_$_SPXSpeechSynthesizer", referenced from:
      objc-class-ref in XZMicrosoftAzureManager.o
  "_OBJC_CLASS_$_SPXSpeechConfiguration", referenced from:
      objc-class-ref in XZMicrosoftAzureManager.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
![image](https://user-images.githubusercontent.com/19483154/108998482-f0838a80-76db-11eb-8fab-483117ffbb82.png)

Xcode Version 12.0.1 (12A7300)

**Comment by jhakulin** [comment]
@xiangyan99 Thanks for the feedback, supported architectures for iOS Speech SDK CocoaPod framework are x86_64 and arm64. Have you targeted you app also for armv7?

**Comment by xiangyan99** [comment]
@jhakulin I guess you want to @xiaoMing0109 ?

**Comment by jhakulin** [comment]
@xiangyan99 Thanks and apologies, yes, @xiaoMing0109 please see the question above.

**Comment by xiaoMing0109** [comment]
**I have solved the problem.**

#### Deployment Info
`iOS 9.3`

#### Podfile:
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ARCHS'] = "arm64 x86_64"
        end
    end
end
```

#### Build Settings
![image](https://user-images.githubusercontent.com/19483154/109100586-3124e780-7760-11eb-9a74-e5eb4a2673ef.png)

**Comment by jhakulin** [comment]
@xiaoMing0109 Awesome, thanks for details also.
