### ISSUE TITLE
Push Audio Stream not working and failed to transcribe (Speech to text)on Recorded WAV file .

### ISSUE THREAD

**Issue by yashugupta786** [Azure-Samples/cognitive-services-speech-sdk#971]
I am trying to do Speech to text  using the Azure Cognitive Services  and it is failing on the recorded  wav file  when i used PushAudioInputStream().I have also added the file and it uses language as en-IN . It works on the samples provided in the git 

```
import azure.cognitiveservices.speech as speechsdk
import wave
import time
weatherfilename="demo.wav"
def speech_recognition_with_push_stream():
    """gives an example how to use a push audio stream to recognize speech from a custom audio
    source"""
    speech_config = speechsdk.SpeechConfig(subscription=key, region=region)
    # setup the audio stream
    stream = speechsdk.audio.PushAudioInputStream()
    audio_config = speechsdk.audio.AudioConfig(stream=stream)
    # instantiate the speech recognizer with push stream input
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config,language="en-IN")
    # Connect callbacks to the events fired by the speech recognizer
    speech_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.recognizing.connect(lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(lambda evt: print('RECOGNIZED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
    speech_recognizer.canceled.connect(lambda evt: print('CANCELED {}'.format(evt)))

    # The number of bytes to push per buffer
    n_bytes = 3200
    wav_fh = wave.open(weatherfilename)

    # start continuous speech recognition
    speech_recognizer.start_continuous_recognition()

    # start pushing data until all data has been read from the file
    try:
        while(True):
            frames = wav_fh.readframes(n_bytes // 2)
            print('read {} bytes'.format(len(frames)))
            if not frames:
                break
            stream.write(frames)
            time.sleep(.3)
    finally:
        # stop recognition and clean up
        wav_fh.close()
        stream.close()
        # time.sleep(0.5)
        speech_recognizer.stop_continuous_recognition()
        time.sleep(0.5)

speech_recognition_with_push_stream()

```
using from here https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_sample.py

It is failing to Transcribe(speech to text) when taking the audio from custom source(WAV here ).
I have also attached the sample for the reference 
[demo.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6061537/demo.zip)

I am really stuck please help @trrwilson

**Comment by dargilco** [comment]
Hi @yashugupta786 , thank you for posting this issue. The WAV file you attached is 44.1khz, 16bit/sample, stereo. The default format Speech SDK expects is 16khz, 16bit/sample mono. This is the recommended format. Can you please convert your WAV file to this format and try again? Close this issue if that works.
There is a way to use a non-default format, but that requires you to [specify the stream_format when creating the PushAudioInputStream](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.audio.pushaudioinputstream?view=azure-python). However, streaming 44.1khz audio to the cloud is wastful as we only need a 16khz stream.
Darren

**Comment by yashugupta786** [comment]
Hi @dargilco  Thanks for the solution .Sure i will reduce it from 44.1 khz to 16khz . However is there any utility or something in python to check the information and  config of the wav file . As i am using windows and on properties i can only see the bitrate .Thanks for help

**Comment by dargilco** [comment]
@yashugupta786 I personally have not developed code in python and don't know of a Python WAV parser. I’m sure it’s not difficult to write one yourself. 
I'm going to close this issue. Feel free to open a new issue if you need help with anything else related to Speech SDK.
