### ISSUE TITLE
OpenSSL Question

### ISSUE THREAD

**Issue by jkhall** [Azure-Samples/cognitive-services-speech-sdk#973]
Hi. I've been working on a Xamarin Android app that uses Cognitive Services Speech and I see that it uses OpenSSL 1.1.1b. It's been brought to my attention that this version of OpenSSL has certain security vulnerabilities, so I was wondering if there were plans to move away from this version of OpenSSL. I realize this might not be the ideal place for a question like this because it doesn't necessarily pertain to the repo itself, but I am yet to find a better forum for asking this. Thanks!

**Comment by dargilco** [comment]
Hi @jkhall, thanks for reporting this! Indeed we are using version 1.1.1b, and the list of vulnerabilities [is publicly listed here]( https://www.openssl.org/news/vulnerabilities.html) from the OpenSSL org.  I will follow up with the team on this and will get back to you when I have new information. I created a ticket for this in our internal system, and therefore will go ahead and close this issue so we can keep the open issues list fresh. Please subscribe to the issue to get the latest.

**Comment by jkhall** [comment]
Thanks @dargilco !

**Comment by jkhall** [comment]
Hi, I just wanted to reach out and ask if there were any updates on this issue.  Thanks!

**Comment by dargilco** [comment]
Hi @jkhall we discussed this internally and I will investigate updating to recent version of OpenSSL as part of the next release of Speech SDK (version 1.17). We try to make a new release of Speech SDK every 1-2 months. I will update this thread when I can confirm the work is done.

**Comment by jkhall** [comment]
Okay. Thank you.

**Comment by 3AM-Innovations** [comment]
Have you considered making the Speech SDK open source?
