### ISSUE TITLE
StartContinuousRecognitionAsync problem with Android device

### ISSUE THREAD

**Issue by DebugD0tLog** [Azure-Samples/cognitive-services-speech-sdk#974]
Hello,

So I've been using the speech sdk successfully with Unity (mainly Oculus and PC applications) for quite a while now and I recently had to use it on mobile phone too (for this test the targeted platform was Android). And so I've tried the application (that is working fine on other platforms) on mobile and I get the following error : **SPXERR_START_RECOGNIZING_INVALID_STATE_TRANSITION**

What am I missing here ? Is there any specific set up that is required for mobile ?

**Useful information :**

- Devices used : Galaxy s8
- Unity version : 2019.3.4f1
- I'm actually failing to find the sdk version unfortunately.

- [Here are the logs](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6075542/logs.txt) that I got using the config.SetProperty(PropertyId.Speech_LogFilename, "MyfilePath").

Thank you for your time,

Cheers

**Comment by dargilco** [comment]
Thank you @DebugD0tLog for bringing this to our attention, with the attached log. It's important to us to know the Speech SDK version, as the same error was reported by another user in the latest version (1.15). It may also happen with 1.14, but I am not sure. Can you verify? Does this happen occasionally or all the time? As a workaround can you please try an earlier version?
I will be looking at the log and following up with the team. I'll get back to you if I need more information.
Thanks,
Darren

**Comment by DebugD0tLog** [comment]
Hello @dargilco thank you for your reply, unfortunately I have no way to find the current sdk version I'm using as there is no indication in Unity and I did not write it down at the time.
But I can tell you that I have been using the same sdk and have not updated it since early summer 2020 so it should not be near the lastest versions (1.14/1.15).
While you look at it, I will try with 1.14 as you mentioned and keep you inform.
Cheers

**Comment by dargilco** [comment]
@DebugD0tLog thank you for the additional information. If you can provide a new log showing the error with the latest version (1.15) that will help us narrow down the problem. Also describe exactly the steps you took to hit this error, so we can try to repeat it in our team.

**Comment by DebugD0tLog** [comment]
Ok so I just tried with the 1.15 sdk and it seems I got the exact same error : [here are the logs](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6077299/logs_sdk1.15.txt)

To give further information here is a sample of the code that is leading to the error on mobile :

- **InitSetting** is called to set the recognizer up with the right config
- **SpeechContiniousRecognition** is called twice, one to start the recognition and the other to end the recognition
```
private void InitSetting()
    {
        config = SpeechConfig.FromSubscription(CONFIG_SUBSCRIPTIONKEY, CONFIG_REGION);
        sourceLanguage = SourceLanguageConfig.FromLanguage(langueCode);
        audioConfig = AudioConfig.FromDefaultMicrophoneInput();
        recognizer = new SpeechRecognizer(config, sourceLanguage, audioConfig);
        connection = Connection.FromRecognizer(recognizer);

        recognizer.SessionStarted += SessionStartedHandler;
        recognizer.SessionStopped += SessionStoppedHandler;
        recognizer.Recognizing += RecognizingHandler;

        connection.Connected += Connected;
        connection.Disconnected += Disconnected;
    }

//This is called by a simple button : true to start - false to end
public async void SpeechContiniousRecognition(bool status, Action<string> callback = null)
    {
        if (callback != null)
        {
            onEndRecognition = callback;
        }

        if (!status && recognitionStarted)
        {
            await recognizer.StopContinuousRecognitionAsync().ConfigureAwait(false);

            lock (threadLocker)
            {
                recognitionStarted = false;

                string stringToReturn = String.Join(" ", results);

                onEndRecognition?.Invoke(stringToReturn);
            }
        }
        else
        {           

            await recognizer.StartContinuousRecognitionAsync().ConfigureAwait(false);
            lock (threadLocker)
            {
                recognitionStarted = true;
            }
        }

    }
    //This is the handler to get the result from continuous recognition
    private void RecognizingHandler(object sender, SpeechRecognitionEventArgs e)
    {
        lock (threadLocker)
        {  
                    string[] test = e.Result.Text.Split(' ');
                    foreach (string s in test)
                    {
                        if (!results.Contains(s))
                        {
                            results.Add(s);
                        }
                    }
            }
        }
    }

```

**Comment by dargilco** [comment]
To make sure I understand: In your code SpeechContiniousRecognition(true, .) is called first to start the recognition, then SpeechContiniousRecognition(false, .) is called next to stop the recognition. Roughly what was the duration between the two calls? Was it about 6 seconds? Can you confirm that this happens all the time? (or do you need to try the above several times before getting the exception)

**Comment by DebugD0tLog** [comment]
That is exactly right. The duration between the two calls is around 5 seconds.
I have tested multiple times already and it has always thrown me this error on mobile. One point though, is that I have no idea if this error is thrown at the firt call or the second I could investigate more if needed (see if I get any input at all for example)

**Comment by dargilco** [comment]
Got it! that's all I need now. I'm looking into it and will post an update here. As a workaround, please try earlier versions (1.13 and below). You were probably using 1.13 or 1.12.1, although I'm not sure now what was the earliest version we started supporting Unity.

**Comment by dargilco** [comment]
@DebugD0tLog I see in the log that the Azure region is set to "mydummycountry" (the CONFIG_REGION in your code above). Is that the value you set, instead of a real Azure region? If so, why?

**Comment by dargilco** [comment]
@DebugD0tLog I checked and if you call recognizer.StartContinuousRecognitionAsync() twice (without calling recognizer.StopContinuousRecognitionAsync() in between), you will get an exception with SPXERR_START_RECOGNIZING_INVALID_STATE_TRANSITION. Please harden your code to make sure recognizer.StartContinuousRecognitionAsync() can only be called if recognitionStarted == false. Can you confirm that indeed it was called twice?

**Comment by DebugD0tLog** [comment]
Hey @dargilco,

So first of all I juste change the config region in the log for privacy reason but it's set up correctly in the code :)
Second of all I just tried the following code on Galaxy s8 : 

```
    public async void SpeechContiniousRecognition(bool status, Action<string> callback = null)
    {

        if (callback != null)
        {
            onEndRecognition = callback;
        }

        if (!status && recognitionStarted)
        {
            await recognizer.StopContinuousRecognitionAsync().ConfigureAwait(false);

            lock (threadLocker)
            {
                recognitionStarted = false;

                string stringToReturn = String.Join(" ", results);

                onEndRecognition?.Invoke(stringToReturn);
            }
        }//This line is what you recommended me to add 
        else if(recognitionStarted == false && status)
        {
            await recognizer.StartContinuousRecognitionAsync().ConfigureAwait(false);
            lock (threadLocker)
            {
                recognitionStarted = true;
            }
        }

    }
```
But even with this I keep getting the error : [as you see in the logs I just got](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6082225/logs2.txt)

Thing is I have handlers that are checking whenever I start or stop a continuous recognition : 

```
    private void SessionStartedHandler(object sender, SessionEventArgs e)
    {
        lock (threadLocker)
        {
            Log.Info("Session Started !");
        }
    }
    private void SessionStoppedHandler(object sender, SessionEventArgs e)
    {
        lock (threadLocker)
        {
            Log.Info("Session has stopped !");
        }
    }
```
and those logs.info are triggered only once so it does not seem like the start is called twice.

Cheers

**Comment by dargilco** [comment]
Thanks for the new logs! I'm 100% sure StartContinuousRecognitionAsync is being called twice on Speech SDK:

In the new log:
(408): 28495ms SPX_DBG_TRACE_FUNCTION:  audio_stream_session.cpp:806 StartRecognitionAsync
...
(408): 34520ms SPX_DBG_TRACE_FUNCTION:  audio_stream_session.cpp:806 StartRecognitionAsync

The first call 28.495 seconds in, the second call 34.520 seconds in (so about 6 seconds apart). Both calls by the same thread (thread ID 408).

Can you put a Log.Info() above the call to  "await recognizer.StartContinuousRecognitionAsync().ConfigureAwait(false)"?

**Comment by DebugD0tLog** [comment]
Ok then I will try this out tomorrow or this week end and let you know :)

Cheers

**Comment by DebugD0tLog** [comment]
Hello @dargilco,

So I've tried everything you've said and it is now working on my s8 perfectly !

Thank you for everything and keep up the great work as you were really efficient.

Cheers

**Comment by dargilco** [comment]
@DebugD0tLog glad to hear that!
