### ISSUE TITLE
keyword-recognizer-stream includes keyword in STT transcription

### ISSUE THREAD

**Issue by jeffMeador** [Azure-Samples/cognitive-services-speech-sdk#977]
Is there a way to exclude the keyword from the STT transcription when using it as shown in the keyword-recognizer-stream quickstart for android? Right now the keyword will get transcribed along with the utterance and the desired behavior would be to not include the keyword in the transcription.

**Comment by dargilco** [comment]
Hi @jeffMeador, unfortunately at the moment there is no way to specify automatic removal of the keyword from the transcription. This has been requested before and I believe it's one of the work items in our backlog. I will follow up on this with the team.

**Comment by dargilco** [comment]
@jeffMeador I filed a ticket on this in our internal system and will follow up on this. To keep the list of open issues here fresh, I will go ahead and close this issue. Thank you again for your question and don’t hesitate to open a new issue if something else comes up.
Darren
