### ISSUE TITLE
iOS 10.3.3 not support

### ISSUE THREAD

**Issue by hold-my-hand** [Azure-Samples/cognitive-services-speech-sdk#98]
**Describe the bug**

**To Reproduce**
1. ...
2. ...

**Expected behavior**

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operationg System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - please be specific
 - Hardware - x64, x86, ARM, ...
 - Browser  [e.g. chrome, safari] (if applicable)- please be specific

**Additional context**
 - Error messages, log information, stack trace, ...
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by zhouwangzw** [comment]
Currently the Speech SDK for iOS only supports iOS11.4. We are working on supporting iOS 10, but no ETA yet.

Sorry for inconvenience.

**Comment by hold-my-hand** [comment]
When will it be finished?

**Comment by chlandsi** [comment]
Please have a look at the input streams available in the API, [SPXPullAudioInputStream](https://docs.microsoft.com/en-gb/objectivec/cognitive-services/speech/spxpullaudioinputstream) and [SPXPushAudioInputStream](https://docs.microsoft.com/en-gb/objectivec/cognitive-services/speech/spxpushaudioinputstream).

There is no planned release date for iOS 10.0 compatibility yet.

**Comment by hold-my-hand** [comment]
I tried, but a simple sentence can not be recognized.
, and could help me to see my demo. 
https://github.com/hold-my-hand/TranslateDemo

**Comment by chlandsi** [comment]
Can you be more specific about the issue? Do you see the expected results when doing recognition from a file, or from the default microphone implementation?

**Comment by hold-my-hand** [comment]
是的，那二种情况我都试过了没有问题，但是我希望以流的方式去识别并且翻译，我必须使用audiounit这个库，不知道它的audiobuffer如何转换成为你们所需要的pcmdata，不知道你看不看得懂中文.

**Comment by hold-my-hand** [comment]
translate：Yes, I've tried both cases，they have no problem，but I hope to identify and translate them in a streaming way. I have to use the AudioUnit library. I don't know how its audiobuffer can be converted into the pcm data you need. I don't know if you can read Chinese or not

**Comment by chlandsi** [comment]
Different varieties of Chinese are supported, see [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support). There aren't any samples for audio input streams with Objective-C yet, but maybe the [C++ sample on that topic](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/3131ab75577116fe9359242d6d86321808601e19/samples/cpp/windows/console/samples/speech_recognition_samples.cpp) is helpful.
