### ISSUE TITLE
Speech to text not working on bytes receive from Unmixed audio buffer Teams Source

### ISSUE THREAD

**Issue by yashugupta786** [Azure-Samples/cognitive-services-speech-sdk#980]
I am trying to the Speech to text using Azure Speech service  in c# using custom push audio stream . 
The audio Source is the Bytes received from the unmixed Audio Stream 
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/src/RecordingBot.Services/Media/SerializableAudioMediaBuffer.cs

I am passing the bytes received from SerializableUnmixedAudioBuffers[i] variable  to the Custom Audio Stream and it is failing to do the speech to text

**Comment by dargilco** [comment]
What do you mean by failing? you are not getting any "Recognizing" and "Recognized" events? Or are you getting a "Canceled" event? Please be more specific.

I'm assuming you are not getting "Recognizing" and "Recognized" events.

What is the format of the audio? (sample rate, number of channels, bits/sample). By default, Speech SDK expects 16khz, mono, 16 bit/sample signed integer). Please make sure the audio is in this format. You can try and use other formats by specifying the [AudioStreamFormat](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.audio.pushaudioinputstream.-ctor?view=azure-dotnet#Microsoft_CognitiveServices_Speech_Audio_PushAudioInputStream__ctor_Microsoft_CognitiveServices_Speech_Audio_AudioStreamFormat_), but it will be a waste to send audio to the speech service with higher sample rate or number of channels.

If you are using the default format, and still not getting recognition result, make sure the audio is valid. Dump whatever audio you feed Speech SDK to file and listen to it to make sure it's valid.

If the audio is valid and you are still not getting recognition results, [please take a log](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging) and share it here.

Darren.

**Comment by muradhaider5786** [comment]
Hi @yashugupta786 which sample are you using for speech to text?

**Comment by pankopon** [comment]
Closed since no update in a month, please open a new issue if more support is needed.
