### ISSUE TITLE
nodejs from-blob example

### ISSUE THREAD

**Issue by v-demjoh** [Azure-Samples/cognitive-services-speech-sdk#981]
I tried building this:

https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/javascript/node/from-blob

1. The first sentence of the **README.md** says an accompanying article "describes how to build the sample from scratch".  But the target article appears to be the REST API, and I don't see it using the sample. It does get into a C# sample.
2. I followed the instructions in README.md, but it didn't appear to work. **npm install** seems to run, but I don't see a **node_modules** directory created by that command.
3. The final step says node **index.js** should run the sample, but I don't see **index.js**. 
4. I removed **package-lock.json** from many NodeJS samples a while ago. Brian added the file. Sometimes these files should not be included, so Node will instead create the file fresh on the local computer. But I can't get this whole sample to build so I can't test if this **package-lock.json** file is appropriate.

**Comment by glharper** [comment]
@v-demjoh Should that article link be removed? I could have sworn there was a "from blob" JS quickstart in Azure Docs, but I can't seem to find it now.

**Comment by v-demjoh** [comment]
It existed, but doesn't now. I've removed the mention in this PR:

https://github.com/Azure-Samples/cognitive-services-speech-sdk/pull/1007
