### ISSUE TITLE
package-lock.json in NodeJS conversation-transcription

### ISSUE THREAD

**Issue by v-demjoh** [Azure-Samples/cognitive-services-speech-sdk#982]
I tried building this:

https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/javascript/node/conversation-transcription

1. The first sentence of the README.md says an accompanying article "describes how to build the sample from scratch". But the target article appears to be the REST API, and I don't see it using the sample. It does get into a C# sample.
2. I followed the instructions in README.md, but it didn't appear to work. **npm install** fails with this:

![image](https://user-images.githubusercontent.com/64612748/110697131-c41e4280-81a0-11eb-81e9-c369aa484c60.png)

I removed **package-lock**.json from many NodeJS samples a while ago. Brian added the file back. I believe this failure is caused by the presence of **package-lock.json** in this sample. Maybe an exclusion rule should be added to the repo to prevent inclusion of **package-lock.json**.

**Comment by BrianMouncer** [comment]
I did not intentionally add the lock file back.
This was either my mistake, because I blindly used npm install to update our sdk package version, or a glitch in the two way merge between the internal staging repo, and the public repo on GitHub.

**Comment by v-demjoh** [comment]
@BrianMouncer or @glharper  I _think_ it's true that we _never_ want these lock files in our samples. Of so, can we add the filename to an exclude file? Can this repo have [a .git/info/exclude entry](https://docs.microsoft.com/en-us/azure/devops/repos/git/ignore-files?view=azure-devops&tabs=visual-studio#ignore-files-only-on-your-system) for this filename?

**Comment by v-demjoh** [comment]
I removed the lock files and added the filename to .gitignore for both node trees.
https://github.com/Azure-Samples/cognitive-services-speech-sdk/pull/1007
