### ISSUE TITLE
unable to install speech-sdk (python)

### ISSUE THREAD

**Issue by meganbloemsma** [Azure-Samples/cognitive-services-speech-sdk#983]
**Describe the bug**
speech sdk cannot be installed:
_ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech (from versions: none)
ERROR: No matching distribution found for azure-cognitiveservices-speech_

**To Reproduce**
1. pip install azure-cognitiveservices-speech
2. import azure.cognitiveservices.speech as speechsdk

**Expected behavior**
Import the Speech SDK (azure.cognitiveservices.speech) 

**Version of the Cognitive Services Speech SDK**
Latest version (1.15.0), but also tested with version 1.14.0

**Platform, Operating System, and Programming Language**
 - OS: 
Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎10/‎08/‎2020
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0
 - Hardware - x64bit
 - Programming language: Python (3.9.2) 64bit
 - Pip version: 20.2.3 and 21.0.1
 - Browser: N/A

**Additional context**
Tested both locally and in virtual environment, with different version of Python. Error remains the same:

pip install azure-cognitiveservices-speech
_ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech (from versions: none)
ERROR: No matching distribution found for azure-cognitiveservices-speech_

Double-checked with:
pip show azure-cognitiveservices-speech
_WARNING: Package(s) not found: azure-cognitiveservices-speech_

Not sure if relevant, but went through following without success:
- https://social.msdn.microsoft.com/Forums/en-US/12de3a4b-9ae9-469c-b09b-e2b2250c6a31/unable-to-install-azurecognitiveservicesspeech?forum=AzureCognitiveService
- https://stackoverflow.com/questions/54425580/cant-pip-microsoft-azure-cognitiveservices-speech
- https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/157
- https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/475

**Comment by yusufusta** [comment]
**Workaround**

- Download the most suitable wheel from [PyPi](https://pypi.org/project/azure-cognitiveservices-speech/#files).
- Unzip wheel file.
- Create a folder named azure
- Copy the files in Azure > cognitiveservices > speech into the folder you created.
- Use package like this: `from azure import speech as speechsdk`

This trick worked for me.

**Comment by jhakulin** [comment]
@meganbloemsma Support for Python 3.9 will be added in 1.16.0 Speech SDK release, which will be released soon.

**Comment by brandom-msft** [comment]
@meganbloemsma As Jarno mentions above, you can expect the 1.16 release in the next week or so. Once it's released, please don't hesitate to reach out again with related or additional questions!

**Comment by brandom-msft** [comment]
@meganbloemsma 
1.16 is now available - please give it a try and let us know if you have any issues/feedback.

**Comment by meganbloemsma** [comment]
It works now, thank you!
