### ISSUE TITLE
Restore conversation/chat history using Speech SDK

### ISSUE THREAD

**Issue by hemantgore** [Azure-Samples/cognitive-services-speech-sdk#984]
I've integrated Speech SDK in iOS to enable voice capability with Bot. Prior to this had Directline, text-only support.

**`Directline` had APIs to fetch conversation history by passing conversation ID. Curious to know, if the same can be available in Speech SDK?** 
 
If this is already available in any language SDK or a pointer to the documentation around it will be highly appreciated 

**Benefits:**  
Restoring the conversation provides more context to the user where s/he left, instead of restarting a new conversation every time.

**Comment by dargilco** [comment]
Hi @hemantgore, thank you for posting this issue.

Unfortunately, Direct Line Speech does not store conversation history. Your Bot will need to build and manage its own storage and store each conversation history based on the Conversation ID it gets from Direct Line Speech. Then retrieve the appropriate conversation history as needed on a new client connection. 

Darren
