### ISSUE TITLE
Output files not generating after uploading bulk files

### ISSUE THREAD

**Issue by maheshcheetirala** [Azure-Samples/cognitive-services-speech-sdk#993]
I tested this solution with 3-4 audio calls and was able to get the results in SQL DB. Now I have uploaded 45 calls and i see functions are running but no outputs in outputs blob. Is there any limitation of batch size to be done . Please suggest me how to do this also is it possible to get outputs based on call name rather than generating hash id's.

**Comment by zhouwangzw** [comment]
Could you please provide more details about "this solution"? There are multiple samples for different scenarios in this sample repository. Are you using batch transcriptions? If yes, there should not be any limitation in batch size. Could you please provide the transcription ids for transcription requests that have been submitted by functions but no result have been received, also together with the region and approximate time, so that we can help to check?
The output name has the transcription as prefix. It is not possible to get output based on call name, since call name might not be unique and you could transcribe the same file multiple times. In the result files (.json) the "Source" field is the original audio source file you provide, you can use that to corelate the result file with the audio.
Thanks,

**Comment by maheshcheetirala** [comment]
Thanks for your reply , call processing took some time. I was just wondering if we can get sentiment analysis on a call level into SQL database than n best from all calls. Please let me know how can i achieve this.

**Comment by zhouwangzw** [comment]
@HenryvanderVegte @PanosPeriorellis Could you please help on that? Thanks

**Comment by maheshcheetirala** [comment]
My nbest results output first 1000 rows gave all sentiments as zero, could you please let me know the reason for this.
all three sentiments are zero in columns.

**Comment by maheshcheetirala** [comment]
solution not making progress after 4 calls, it would be great if someone can connect with me and help me understanding  the issue. I have uploaded 45 files and only 4 calls got processed rest are not updating. Even DB count is not increasing.

Thanks
Mahesh

**Comment by maheshcheetirala** [comment]
it would be great if someone can take a session and help us understanding the issue.

**Comment by HenryvanderVegte** [comment]
Hi @maheshcheetirala,

if you didn't enable Sentiment Analysis when you deployed the ARM template (meaning if you didn't enable a TextAnalyticsKey and set SentimentAnalysis to 'None'), it is expected that you see zeros in the database. If you enable SentimentAnalysis, you will either see it on the level of NBest if you enabled UtteranceLevel sentiment, or on the Level of the channel if you enabled AudioLevel sentiment.

> Please suggest me how to do this also is it possible to get outputs based on call name rather than generating hash id's.

I'm not sure what you mean, can you elaborate? On blob storage the transcription has the name of your input audio file - and in the database we also provide the name of the audio input file. 

> solution not making progress after 4 calls, it would be great if someone can connect with me and help me understanding the issue. I have uploaded 45 files and only 4 calls got processed rest are not updating. Even DB count is not increasing.

I suspect that the other calls are still processing. Do you see anything in the error-report container or are there any errors in the function logs (under 'Monitor')?

Thanks,
Henry

**Comment by maheshcheetirala** [comment]
Hello Henry,

Thank you for your reply. I am trying to get sentiment based on a call or
any date so I can use it in reports.

Please suggest me how we do this , after getting the results in database I
find difficult filtering the results based on specific call . I am looking
to do the sentiment analysis on a call level  here the output comes as a
batch and facing difficult filtration on a call level.

Thanks
Mahesh

**Comment by HenryvanderVegte** [comment]
Hi Mahesh,

when you deploy the ARM template, please provide a Microsoft Text Analytics Key, the region of the Key and 'AudioLevel' for sentiment analysis as shown here:
![Capture](https://user-images.githubusercontent.com/12466089/111463895-664da580-8720-11eb-9d71-01218ec61101.PNG)

If you don't see any sentiment scores afterwards, please check the 'error-report' container on your storage account, there might be something wrong with your key then.

In the database, each Channel Result is linked to a TranscriptionID of the transcriptions table. You can get the name of the transcription from there.

Or you can just have a look at the .json file that is written to your storage account.

Thanks,
Henry

**Comment by maheshcheetirala** [comment]
I tried at audio level and got all sentiments zero as discussed earlier.
After changing to utterance level  I was able to get the sentiment. Now I
want a granular level of sentiment based on any filter like call or  date
so that we can use it in reports abd show to management.

Thanks.
Mahesh

**Comment by HenryvanderVegte** [comment]
Hi Mahesh,

the sentiment scores in the NBest are expected to be zeros if enable sentiment analysis at audio level, you will see the sentiment score on an audio level instead (inside of the CombinedRecognizedPhrases table).

We don't have any filtering on call/date built-in, you'll need to write a query for that on your own.

Thanks and best regards,
Henry

**Comment by maheshcheetirala** [comment]
Thank you for the clarification.

**Comment by maheshcheetirala** [comment]
Hello,

The issue is still there, initially I uploaded 23 files and it generated 23
outputs.
Now added additional 22 files but the outputs folder and  count in database
is not increasing.

[image: image.png]
[image: image.png]

these are my output and input blobs, output blob not increasing  from last
time. I restarted the functions apps as well but counts are not increasing.

Thanks
Mahesh

**Comment by HenryvanderVegte** [comment]
Hi @maheshcheetirala,

the count in database is probably not increasing because the files were not completely processed yet. You can always check the json output container (json-result-output) first to see if they were transcribed already. I expect that you won't see them in there, which means that your transcription job inside of the speech service did not complete yet.
Please try again and wait a while for the results.

Thanks and best regards,
Henry
