### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for com.microsoft.cognitiveservices.speech.dialog.DialogServiceConnector.stopListening

### ISSUE THREAD

**Issue by matecode** [Azure-Samples/cognitive-services-speech-sdk#994]
I'm using the library `com.microsoft.cognitiveservices.speech:client-sdk:1.15.0`
and the connection works fine. Now I'm trying to call
[DialogServiceConnector.stopListeningAsync](https://docs.microsoft.com/en-us/java/api/com.microsoft.cognitiveservices.speech.dialog.dialogserviceconnector.stoplisteningasync?view=azure-java-stable#com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector_stopListeningAsync__) but I get the following error during runtime:

**`java.lang.UnsatisfiedLinkError: No implementation found for long com.microsoft.cognitiveservices.speech.dialog.DialogServiceConnector.stopListening(com.microsoft.cognitiveservices.speech.util.SafeHandle) (tried Java_com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector_stopListening and Java_com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector_stopListening__Lcom_microsoft_cognitiveservices_speech_util_SafeHandle_2)`**

The async method wraps the method `stopListening` which seems not implemented in the SO counterpart.

**Comment by matecode** [comment]
seems like there is a `1.16.0` version today, but the problem still exists

**Comment by dargilco** [comment]
@matecode Can you please [turn on logs](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging), do a short run that captures the above and share the log here? Can you share a snippet of code that shows the order of Speech SDK APIs call you make, used to create this log.
Thanks,
Darren

**Comment by matecode** [comment]
Im calling [DialogServiceConnector.listenOnceAsync](https://docs.microsoft.com/de-de/java/api/com.microsoft.cognitiveservices.speech.dialog.dialogserviceconnector.listenonceasync?view=azure-java-stable#com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector_listenOnceAsync__) to start the recognition. After that and during the "user voice input" i'm calling [DialogServiceConnector.stopListeningAsync](https://docs.microsoft.com/de-de/java/api/com.microsoft.cognitiveservices.speech.dialog.dialogserviceconnector.stoplisteningasync?view=azure-java-stable#com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector_stopListeningAsync__) which throws the exception mentioned above.

 Here is the log you requested:

[speechSdk.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6188994/speechSdk.log)

**Comment by dargilco** [comment]
Thanks @matecode, I opened a ticket on this in our internal system. I will investigate and report back here when I have an update. This is Java on Android, correct?
I am going to close this GitHub issue to keep the open issues fresh.

**Comment by matecode** [comment]
Hi @dargilco 

Just for the record: I actually don't think it's a good practice to close the issue without having an answer because there is no way for the issue creator to keep track of their own open questions/issues.

Now the subject: any news from internal systems?

Thanks

**Comment by dargilco** [comment]
Hi @matecode, a fix for this issue will be in next release of Speech SDK (version 1.17), likely to be out by the end of next week (mid May). Thank you again for reporting this! 
Darren
