### ISSUE TITLE
KeywordRecognizer frequently returns inaccurate results when keyword is spoken shortly after some other speech audio in stream

### ISSUE THREAD

**Issue by ShrivastavaAkash** [Azure-Samples/cognitive-services-speech-sdk#995]
**Describe the bug**
The `KeywordRecognizer` does not always detect keywords when the keyword is followed by some other speech input.

**To Reproduce**
1. Start the input stream with some random audio (not containing Keyword), followed by a short pause (~half a second of silence) and then keyword and then again some audio.
2. KeywordRecognizer goes through stream and produces canceled event.

**Expected behavior**
The keyword should be recognized and `recognized` event should be raised.

**Version of the Cognitive Services Speech SDK**
1.15.0

**Platform, Operating System, and Programming Language**
 - OS:Windows
 - Hardware - x64
 - Programming language: C#

**Additional context**
- The recognition works better if the input stream has the keyword at the very beginning (silence can be there before the keyword).
- The recognition also works fine if the input stream has the audio preceding keyword is too far apart (~1-2 seconds of gap of silence between audio and following keyword).
- I could not find any guidelines for how much pause (silence) is required before and after Keyword in audio stream. My use case is I have a long audio stream where the keyword may be present more then once. I'm reading audio from `PushAudioInputStream` and calling `await keywordRecognizer.RecognizeOnceAsync(model)` and as soon as a Keyword is detected I schedule another  `await keywordRecognizer.RecognizeOnceAsync(model)` for remaining audio on stream.

**Comment by ShrivastavaAkash** [comment]
Can someone please give any feedback here? I'm curious to know why this discussion hasn't started. Does this need more details?

**Comment by pankopon** [comment]
Hi, sorry for no response sooner. This looks like a known performance issue with KeywordRecognizer - I've created an internal work item about it and we'll try to address this in future Speech SDK releases, no ETA at the moment.

**Comment by pankopon** [comment]
Closing this as there is now a work item on the Speech SDK backlog. We'll update this when fixes/improvements have been implemented and the release schedule is known.
