### ISSUE TITLE
KeywordRecognizer | Best way to listen for multiple keywords simultaneously from single incoming audio stream

### ISSUE THREAD

**Issue by ShrivastavaAkash** [Azure-Samples/cognitive-services-speech-sdk#996]
What is the recommended way to listen for more than 1 keyword?

So far, I've tried to train 2 models (1 keyword each) and running a 1 instance/keyword of `KeywordRecognizer`. 

```C#

// setup instances
var audioConfig = AudioConfig.FromDefaultMicrophoneInput();
using var keywordRecognizer1 = new KeywordRecognizer(audioConfig);
using var keywordRecognizer2 = new KeywordRecognizer(audioConfig);

// schedule recognition tasks
var tasks = new List<Task<KeywordRecognitionResult>>();
tasks.Add(keywordRecognizer1.RecognizeOnceAsync(model1));
tasks.Add(keywordRecognizer2.RecognizeOnceAsync(model2));
var task = await Task.WhenAny(tasks);

// get result
var result = await task;
```

I wonder if there's a better way to do it. Also, this does not work as well when using `AudioConfig.FromStreamInput()`. Same input stream for both instances parallelly throws errors.

**Comment by dargilco** [comment]
@ShrivastavaAkash We are working on adding better support for multi-keyword recognition. For live microphone input, it looks like you are doing the right thing. For stream input, I would create two separate AudioConfig objects, both pointing to the save WAV file, instead of using the same AudioConfig object to create your two KeywordRecognizers.

**Comment by skstudying** [comment]
> What is the recommended way to listen for more than 1 keyword?
> 
> So far, I've tried to train 2 models (1 keyword each) and running a 1 instance/keyword of `KeywordRecognizer`.
> 
> ```cs
> // setup instances
> var audioConfig = AudioConfig.FromDefaultMicrophoneInput();
> using var keywordRecognizer1 = new KeywordRecognizer(audioConfig);
> using var keywordRecognizer2 = new KeywordRecognizer(audioConfig);
> 
> // schedule recognition tasks
> var tasks = new List<Task<KeywordRecognitionResult>>();
> tasks.Add(keywordRecognizer1.RecognizeOnceAsync(model1));
> tasks.Add(keywordRecognizer2.RecognizeOnceAsync(model2));
> var task = await Task.WhenAny(tasks);
> 
> // get result
> var result = await task;
> ```
> 
> I wonder if there's a better way to do it. Also, this does not work as well when using `AudioConfig.FromStreamInput()`. Same input stream for both instances parallelly throws errors.

I meet the same problem as you did.
Does azure sdk support multi-keyword recognition now? 
And would you like to share how you solved that problem?
