### ISSUE TITLE
JAVA Speech SDK: How to get the connection between sendActivityAsync and the CanceledEvent if something goes wrong?

### ISSUE THREAD

**Issue by matecode** [Azure-Samples/cognitive-services-speech-sdk#998]
If i send a text with sendActitvityAsync i get an Activity ID back. But there is no guarantee that this activity is really send. I can get an CanceledEvent , but there is no link to the activity i just sent.

How to handle this to give the user feedback or in my case: I don't want the message to be on the chat with the user.

**Comment by trrwilson** [comment]
Thanks for contacting us!

We added a new feature in 1.15.0 ([release notes here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/releasenotes#speech-sdk-1150-2021-january-release)) that may help with this:

>***C++/C#/Java/JavaScript***: Make your voice assistant or bot react better to underlying system errors. `DialogServiceConnector` (C++, C#, Java, JavaScript) now has a new `TurnStatusReceived` event handler. These optional events correspond to every `ITurnContext` resolution on the Bot and will report turn execution failures when they happen, e.g. as a result of an unhandled exception, timeout, or network drop between Direct Line Speech and the bot. `TurnStatusReceived` makes it easier to respond to failure conditions. For example, if a bot takes too long on a backend database query (e.g. looking up a product), `TurnStatusReceived` allows the client to know to reprompt with "sorry, I didn't quite get that, could you please try again" or something similar.

In this case, after a call to `sendActivityAsync`, you should receive a matching `turnStatusReceived` that will report the success or failure of the turn initiated by sending the activity payload up. With that, you could either post the message to the chat only after receiving a "success" or *remove* it from the chat (or otherwise mark it) if a "failure" is later received.

Would this event in 1.15 and beyond meet your needs? It'd be great to get your feedback on it.

Thanks!

**Comment by matecode** [comment]
Hi @trrwilson ! Thanks for your answer, this really helps to understand what im implementing :)
But i'm still having some problems to understand how to find the path from TurnStatus to the send activity.
With [DialogServiceConnector.turnStatusReceived](https://docs.microsoft.com/de-de/java/api/com.microsoft.cognitiveservices.speech.dialog.dialogserviceconnector.turnstatusreceived?view=azure-java-stable#com_microsoft_cognitiveservices_speech_dialog_DialogServiceConnector_turnStatusReceived) i get the [TurnStatusReceivedEventArgs](https://docs.microsoft.com/de-de/java/api/com.microsoft.cognitiveservices.speech.dialog.turnstatusreceivedeventargs?view=azure-java-stable) which include conversationId ands interactionId, nnothing i can directly refer to the activity which initiated the conversation.
Furthermore there is no event fired when there are connection problems with, in my case, the mobile device. It just happens nothing.

So i still have two questions:
1. If there is a TurnstatusEvent, how to "connect" to activitys which are send via sendActivityAsnc?
2. How to handle activitys send and there is no turnStatusEvent?

**Comment by matecode** [comment]
@trrwilson any news on this? would be great to get answers to my questions. Thanks a lot!

**Comment by trrwilson** [comment]
@matecode, thanks for pinging me again and apologies for missing the earlier response!

Correlation will generally need to happen with activities *from* the bot *to* the client, as what's tracked is the resolution of the `ITurnContext` on the bot side. What you use to correlate will depend a bit on your dialog system's responses, but here's a common mapping for bots:

| In the activity payload (JSON) | In TurnStatusReceivedEventArgs | notes |
|---|---|---|
| `$.conversation.id` | `ConversationId` |
| `$.recipient.id` | `ConversationId` | may have an extra `|0000` or similar identifier in the JSON response |
| `$.replyToId` | InteractionId | this will also match the `SessionId` from `SessionStarted` / `SessionStopped` |

To make it a bit more concrete, here's some code from a C# test case that's comparing the most recent events received by a `DialogServiceConnector` to the activity payload of a response returned by a speaking echo bot:

```csharp
var lastActivity = JObject.Parse(helper.LastActivity);
var activityReplyToId = lastActivity.Value<string>("replyToId");
var activityConversationId = lastActivity["conversation"].Value<string>("id");
var activityRecipientId = lastActivity["recipient"].Value<string>("id");
Assert.IsTrue(activityReplyToId == helper.LastSessionStartedEvent.SessionId);
Assert.IsTrue(activityReplyToId == helper.LastSessionStartedEvent.SessionId);
Assert.IsTrue(activityReplyToId == helper.LastTurnStatusEvent.InteractionId);
Assert.IsTrue(activityConversationId == helper.LastTurnStatusEvent.ConversationId);
Assert.IsTrue(activityRecipientId == $"{helper.LastTurnStatusEvent.ConversationId}|0000");
```

On connection problems: what form of connection issue isn't providing any data for you to use? There should be a few different ways to be notified:

- `canceled` on `DialogServiceConnector` should raise an event if a connection failure happens during a session
- `CancellationErrorDetails.fromResult(...)`, used on `SpeechRecognitionResult` from `listenOnceAsync()` when the result reports `ResultReason.Canceled`, should also have extended error information
- `.disconnected` on a `Connection` (created via `Connection.fromDialogServiceConnector(...)`) should also report when disconnection occurs, though this won't have extended error information

**Comment by glecaros** [comment]
I'm closing this item as there hasn't been activity in a while. @matecode please feel free to reopen if you need further help.
